### ISSUE TITLE
No way to pass --schedule-opts to pgbackrest schedule

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#1002]
**Describe the bug**
https://github.com/CrunchyData/postgres-operator/blob/7fb5f61381314e0f7886709a6ffb27c027571050/pgo-scheduler/scheduler/pgbackrest.go#L147 this line makes impossible to pass any `--schedule-opts`
Whatever anyone adds - only `--repo-type=s3` is added to the `task.spec.parameters: backrest-opts: '--stanza=db --type=full'`

**To Reproduce**
1. create s3 pgbackrest schedule with any additional options e.g. `repo1-retention-full=2`

**Expected behavior**
additional options should be added 

**Please tell us about your environment:**

* Container Image Tag: 2.4.1
* PostgreSQL Version: 10.10
* Platform (Docker, Kubernetes, OpenShift): OCP
* Platform Version: 4.0.1

**Comment by jkatz** [comment]
This is fixed in in `v4.2.0`
