### ISSUE TITLE
Creating either Primary Cluster Member or Replica Cluster Member fails

### ISSUE THREAD

**Issue by Feelas** [CrunchyData/postgres-operator#1005]
**Describe the bug**
After installing the operator from Operator Hub (OpenShift 4.1.15) and creating either a Primary Cluster Member or a Replica Cluster Member (using the example), the deployment never succeeds. After inspecting, ReplicaSets hang on `Error creating: pods "test-cluster-577765969f-" is forbidden: unable to validate against
any security context constraint: [fsGroup: Invalid value: []int64{26}: 26 is not an allowed group]` error. This is due to lack of proper SCC (as in https://github.com/CrunchyData/postgres-operator/issues/517). Maybe the SCC should be created automatically. After using proposed https://github.com/CrunchyData/postgres-operator/blob/develop/examples/pgo-scc.yaml the deployment continues.

**To Reproduce**
1. Install Postgres-Operator using Operator Hub
2. Create one of the mentioned resources
3. After observing that pods did not create, inspect deployment and replicasets to see the bug happening

**Expected behavior**
The deployment should successfully get created

**Please tell us about your environment:**

* Operating System: Red Hat Enterprise Linux CoreOS 410.8.20190904.0
* Where is this running (Local, Cloud Provider): Local
* Container Image Tag: pgo-apiserver:rhel7-4.0.0-rc10 
* PostgreSQL Version: n/a
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.1

**Comment by cahoonpwork** [comment]
We are planning to add the SCC automatically.

**Comment by Feelas** [comment]
> We are planning to add the SCC automatically.

Thank you, and is there any ETA on that functionality being implemented?

**Comment by lkhomenk** [comment]
not using fsGroup in storageClass helped us here.

**Comment by jkatz** [comment]
The automatic adding of the SCC was added in v4.1.0, which was released in October.
