### ISSUE TITLE
pgo restore is broken for S3 backup type

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#1008]
**Describe the bug**
```pgo restore test-rest --pgbackrest-storage-type=s3 --backup-type=pgbackrest```
fails restore pod fails with 
```
ERROR [042]: : unexpected EOF reading line from remote process on 'test-rest-backrest-shared-repo'
ERROR [025]: : remote process on 'test-rest-backrest-shared-repo' terminated unexpectedly [025]: option repo1-s3-key is required
WARN: unable to shutdown protocol [025]: remote process on 'test-rest-backrest-shared-repo' terminated unexpectedly [025]: option repo1-s3-key is required
2019-09-18 18:43:41.478 P00   INFO: restore command end: aborted with exception [042]
```

**To Reproduce**
1. `pgo restore test-rest --pgbackrest-storage-type=s3 --backup-type=pgbackrest`
2. unset PGABACKREST_REPO1_HOST variable from restore pod
3. repeat 1
4. suceed

**Expected behavior**
should work 

**Please tell us about your environment:**

* Container Image Tag: 2.4.1
* PostgreSQL Version: 10.9
* Platform (Docker, Kubernetes, OpenShift): OCP
* Platform Version: 4.0.1

**Additional context**
This has a workaround. but the whole logic is kinda broken. restore from s3 doesn't need shared-backrest-repo pod at all.

**Comment by jkatz** [comment]
@lkhomenk At your convenience, I'm curious to know if this works for you in `v4.2.0` -- we definitely tested around it, but want to make sure it's good for you. Thanks!
