### ISSUE TITLE
why does the pgo client require a cert?

### ISSUE THREAD

**Issue by raffaelespazzoli** [CrunchyData/postgres-operator#101]
I can understand the CA bundle to validate the server CA, but why the client cert?
in the doc the server cert is reused also as the client cert. Is that the recommended way to go?
It doesn't make a lot of sense to me.

**Comment by jmccormick2001** [comment]
the current release uses a self signed set of credentials, meant to be for demo purposes only, I assumed that most people would want to generate their own credentials, would include both a client and server in that case.  I should probably change the example to explicitly create a client cert apart from the server to denote that.
