### ISSUE TITLE
Improve documentation around upgrading postgres clusters using the pgo client

### ISSUE THREAD

**Issue by chrisjtwomey-ibm** [CrunchyData/postgres-operator#1017]
Currently there isn't documentation around the experience with upgrading clusters using the pgo client and there are gaps in instructions particularly in the major upgrade experience. 

We'd like the following additions to the documentation in the Postgres Operator docs around upgrading via the pgo client:

 - Example experience of minor upgrade using the pgo client
   - what happens to primary & replicas and PVs in kube context
   - details of compatibility of crunchy-containers and operator version

 - Example experience of major upgrade
   - pointer to the crunchy-containers doc on major upgrade as this is a required step but not mentioned in the operator docs
   - details of compatibility of crunchy-containers and PostgreSQL versions

**Comment by jkatz** [comment]
We've done a bit of work on the upgrade docs, and notably, now have a process to automatically upgrade from version {4.1,4.2} => 4.3 per #1364
