### ISSUE TITLE
unable to connect to api server using 4.0.0

### ISSUE THREAD

**Issue by leoweiyu** [CrunchyData/postgres-operator#1028]
** Which example are you working with? **
i was trying to set up Postgres-operator on OpenShift 3.11, i have the operator running fine, but when i trying 
pgo version --apiserver-url https://my_api_url
Error: Authentication Failed: 401

and in the container log, we see

time="2019-09-30T12:36:29+13:00" level=debug msg="versionservice.VersionHandler called"
--
  | time="2019-09-30T12:36:29+13:00" level=debug msg="Authentication Attempt Version username=[pgoadmin]"
  | time="2019-09-30T12:36:29+13:00" level=error msg="Authentication Failed Version username=[pgoadmin]"

we have created file ~/.pgouser before running
make installrbac

**What is the current behavior?**
Error: Authentication Failed: 401

**What is the expected behavior?**
be able to connect to the api server and run pgo command

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**
Openshift3.11

* Operating System:
* Where is this running ( Local , Cloud Provider)
local
* Storage being used (NFS, Hostpath, Gluster, etc):
storageclass

* Container Image Tag:
pgo-apiserver:centos7-4.0.0
postgres-operator:centos7-4.0.0
pgo-scheduler:centos7-4.0.0

* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
OpenShift
* Platform Version:
3.11

**Comment by andrewlecuyer** [comment]
@leoweiyu are you installing using the Ansible or the bash installer?

If installing using Ansible, the `pgouser` file will be generated automatically in a directory such as the following: `${HOME?}/.pgo/<PGO_NAMESPACE>/pgouser`.  You can then point to that `pgouser` file by setting the `PGOUSER` environment variable, e.g.:

```
export PGOUSER="${HOME?}/.pgo/<PGO_NAMESPACE>/pgouser"
```

If installing using bash (or if generating the `.pgouser` file manually), please make sure that the credentials defined in your `.pgouser` file match those defined in the `$PGOROOT/conf/postgresql-operator/pgouser` file.  And if you do have the `PGOUSER` environment variable defined, please ensure it is pointing to the proper location for that file (if `PGOUSER` is not defined in your environment, the PGO will look for it in your home directory by default).

**Comment by leoweiyu** [comment]
thanks heap @andrewlecuyer , that seem resolved my problem, but funny thing is that after redeployment, the pod complains confmap being generated, i have to remove the password bit out of the config map, and it works.
