### ISSUE TITLE
Allow to setup PG_LOCALE or default to UTF8 encoding

### ISSUE THREAD

**Issue by Emmenemoi** [CrunchyData/postgres-operator#103]
Default locale of your containers is POSIX.
This creates default SQL_ASCII encoding on PG databases.

Either change the default locale of the PG containers to (for ex.) en_US.UTF8 to get UTF8 default encoding or allow users to setup PG_LOCALE to force initdb to set default UTF8 encoding from provided locale (if I'm right).

This is defenitely not a good idea to have SQL_ASCII database encoding in production.

**Comment by Emmenemoi** [comment]
Or add an option to kind: Pgcluster

**Comment by jmccormick2001** [comment]
fixed, I updated the config files for database creation under conf/postgres-operator/1/cluster to specify a PG_LOCALE value of en_US.UTF8 for both primary and replica instances.  This will land in the upcoming 2.5 release.
