### ISSUE TITLE
PITR not working with pgo restore command

### ISSUE THREAD

**Issue by NiraimathiGunalan** [CrunchyData/postgres-operator#1033]
**Steps followed**

Took backup with no tables added
```               List of relations
 Schema |        Name        | Type  |  Owner   
--------+--------------------+-------+----------
 public | pg_stat_statements | view  | postgres
 public | primarytable       | table | postgres 
```

Added a table **afterBackUpOne** and took a backup again and the below shows the two backups taken 

```backrest : postgres

Storage Type: local
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (11-1): 000000010000000000000001/000000030000000000000004

        full backup: 20190930-153050F
            timestamp start/stop: 2019-09-30 15:30:50 / 2019-09-30 15:31:16
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 30.3MB, backup size: 30.3MB
            repository size: 3.6MB, repository backup size: 3.6MB

        full backup: 20190930-154524F
            timestamp start/stop: 2019-09-30 15:45:24 / 2019-09-30 15:45:53
            wal start/stop: 000000030000000000000004 / 000000030000000000000004
            database size: 30.3MB, backup size: 30.3MB
            repository size: 3.6MB, repository backup size: 3.6MB
```
Now tried to restore at the time the first backup taken using the command ```pgo restore <clustername> --pitr-target="2019-09-30 15:32:14.921404+00" --backup-opts="--type=time" -n <namespace>```

Getting the data with latest backup not with the time mentioned.
Got the solution only if I use **--set** flag with the backup name (20190930-153050F)

**Comment by andrewlecuyer** [comment]
@NiraimathiGunalan the default behavior for pgBackRest is to use the latest backup when performing a restore, e.g. per the pgBackRest docs (https://pgbackrest.org/user-guide-centos7.html#pitr):

`The default behavior for restore is to use the last backup but an earlier backup can be specified with the --set option.`

Therefore it appears as though the behavior you are seeing is expected, i.e. since your performing a PITR to restore to a time prior to the latest backup, you will need to use `--set` to specify the proper backup to use for the restore.

**Comment by NiraimathiGunalan** [comment]
@andrewlecuyer I was referring this doc https://info.crunchydata.com/blog/pgbackrest-point-in-time-recovery-using-crunchy-postgresql-operator and they recovered the data without mentioning the `--set flag`

The restore to that particular backup can be done using this command `pgo restore <clustername>  --backup-opts=" --set=20190930-153050F"-n <namespace>`  so at what situation I should use PITR flag

**Comment by jkatz** [comment]
@NiraimathiGunalan I would recommend retrying this with [v4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0) and see if you have any issues. If the documentation is still unclear (or incorrect), we can modify it to ensure it is accurate.

Thanks!
