### ISSUE TITLE
Chart bug (2.4)

### ISSUE THREAD

**Issue by Emmenemoi** [CrunchyData/postgres-operator#104]
Missing collect.json + rmdata-job.json in configmap => pod can't start.

**Comment by jmccormick2001** [comment]
if you can retest, I just updated the chart to work with the latest release changes, it seems to work for me in my early testing, its within the master branch currently.  regards.

**Comment by Emmenemoi** [comment]
Master is working.

**Comment by jmccormick2001** [comment]
thanks for testing, I'll close this out.
