### ISSUE TITLE
Deployments should implement liveness checks

### ISSUE THREAD

**Issue by moshloop** [CrunchyData/postgres-operator#1059]
Currently, only the readiness check is implemented which is only checked on pod startup, The liveness check is used once the pod has passed its readiness check.

https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres/liveness.sh and https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres/readiness.sql should also be swapped around. 

i.e. liveness.sh should check if it is possible to execute a SQL command

**Comment by jkatz** [comment]
This is available in [v4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0), e.g.:

https://github.com/CrunchyData/postgres-operator/blob/v4.2.0/conf/postgres-operator/cluster-deployment.json#L37-L54
