### ISSUE TITLE
pgo create doesn't work with the --namespace option

### ISSUE THREAD

**Issue by raffaelespazzoli** [CrunchyData/postgres-operator#106]
When I issue the following command:
`pgo create cluster postgres-ha1 --password admin`
a postgres sql cluster is create correctly.
When I issue the following command:
`pgo --namespace product create cluster postgres-ha --password admin`
nothing happens. Notice that the `product` namespace already exists.
here is the log I see in the postgres-operator pod:
```
time="2018-01-24T13:07:17Z" level=debug msg="clusterservice.CreateClusterHandler called"
time="2018-01-24T13:07:17Z" level=debug msg="create cluster called for postgres-ha"
time="2018-01-24T13:07:17Z" level=debug msg="pgcluster postgres-ha not found so we will create it"
time="2018-01-24T13:07:17Z" level=debug msg="no policies are specified"
```

**Comment by jmccormick2001** [comment]
the operator works only in a single namespace currently.  The operator should report and catch this sort of error better than it currently does for sure.  Also, I suspect this is not as clear in the documentation as it needs to be.  I'll make sure to correct this in an upcoming release.

**Comment by jmccormick2001** [comment]
this is now cleaned up in master branch, --namespace is removed from the pgo command entirely, it was a remnant of the old pgo command before the apiserver was created...the apiserver determines which namespace is being used at this point.  When I implement global namespace functionality this command flag may reappear.
