### ISSUE TITLE
Improve resilience of auto-failover

### ISSUE THREAD

**Issue by moshloop** [CrunchyData/postgres-operator#1060]
Correct me if I am wrong, but the current implementation only uses a Ready -> NotReady watch to trigger a failover. 

However, without a liveness check this will only fire when postgres crashes and even then K8s watches are not guaranteed to be delivered. 

1) Failover should be based on a configurable timeout (to prevent flapping and unnecessary promotions that potentially lose data) 

2) Sanity checks should be performed before failover - are the potential replicas healthy, etc..

3) Failover should be triggered via a configurable watchdog loop to cater for corner cases where not-ready events are not delivered.

**Comment by jkatz** [comment]
Hi @moshloop.

Thank you again for the feedback! We are making changes to how high-availability is managed in our next release that will make it much more resilient by leveraging some existing proven open source technologies.

Thanks!

**Comment by moshloop** [comment]
Can you create the issues that track the new work or reopen this issue?

**Comment by lkhomenk** [comment]
I can add here - if one stops node with Primary postgres, operator won't do anything. no failover at all

**Comment by jkatz** [comment]
Which version are you using?

As mentioned, the HA system will be changing significantly in 4.2 and will be leveraging several proven open source technologies. The architecture will be taking the Operator out of the business of managing HA directly: the Operator will be responsible for setting the cluster definitions, but the cluster itself will manage the HA (think "distributed consensus"). The clusters will use pod anti-affinity rules to help ensure that PostgreSQL instances in a cluster are not scheduled together (while keeping in mind things like locality of storage, etc.)

We aim to have an alpha of this available soon, and by "soon" I mean within the next couple of weeks.

Thanks!

**Comment by lkhomenk** [comment]
@jkatz do you have any plans to improve failover for version prior 4.2? 
current failover logic triggers only when DB  falls into recovery or DB crashes.
* If anyone deletes pod with the master DB 
* if node with the master goes down
* if postgres-operator pod\node goes down 
Nothing happens - no failover

**Comment by lkhomenk** [comment]
https://github.com/CrunchyData/postgres-operator/blob/4.0.1/operator/cluster/autofailover.go#L102-L122 this part checks state of database container - no database container -> no autofailover

**Comment by jkatz** [comment]
Hi @lkhomenk,

We are not planning to backpatch the HA improvements that are in 4.2.

The HA work for 4.2 (the core of which is now committed in the `master` branch) is a fundamental shift in architecture for how it is handled. The Operator is no longer a single-point-of-failure (SPOF) for managing the PostgreSQL clusters. Instead, the PostgreSQL clusters themselves are able to manage their own availability. This is handled by "distributed consensus" and leverages the backing of Kubernetes in order to make appropriate failover decisions. 

As this represents a fundamental shift in architecture and is a "breaking" feature (though really, it improves autofailover) it would not be appropriate to backpatch as it could end up causing breakages with other expected behavior.

**Comment by lkhomenk** [comment]
Hi @jkatz 
Do you have any release date for 4.2? at least approximate. it looks really promising and has less magic under the hood.

**Comment by jkatz** [comment]
@lkhomenk Thanks, we're hoping so 😄 

We are looking to release before the end-of-the-year. We are close to making the first beta available.

**Comment by jkatz** [comment]
The major overhaul to the HA system is now complete. You can read about it in the [v4.2.0 release notes](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0).

The documentation is still being pushed out, but you can read about the [structure of the HA system in the nightly build documentation](https://crunchydata.github.io/postgres-operator/latest/architecture/high-availability/)
