### ISSUE TITLE
Add release 4.1 to OperatorHub.io

### ISSUE THREAD

**Issue by ron1** [CrunchyData/postgres-operator#1068]
Add release 4.1 to OperatorHub.io Kubernetes and OpenShift operators.

**Comment by jkatz** [comment]
Hi @ron1,

Thanks for the reminder! We will begin the process of adding.

**Comment by ron1** [comment]
@flamingdumpster Do you have a status update regarding this issue?

**Comment by jkatz** [comment]
@ron1 This is being actively worked on and we should have a PR shortly, perhaps as early as today. Thanks!

**Comment by jkatz** [comment]
Hi @ron1 - there is currently an open PR on the OperatorHub project: https://github.com/operator-framework/community-operators/pull/845

**Comment by jkatz** [comment]
Hi @ron1,

This was added earlier in the month. Closing out the issue.
