### ISSUE TITLE
Parametrize pg_basebackup method

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#1075]
**What is the motivation or use case for the change?**

When replica gets created sometimes there's a need to omit WAL files or stream.
Available options for method are ```none/fetch/stream``` 
Right now `fetch` is hardcoded and we can get into situation when huge DB replica was initiated but pgbackrest backup finished right after the start and cleaned up WAL files. and after copiyng terabytes of data one gets a message:
```pg_basebackup: could not get write-ahead log end position from server: ERROR:  requested WAL segment 000000070000146F000000B5 has already been removed```
**Describe the solution you'd like**
Parametrization via pgo.yaml

**Comment by jkatz** [comment]
@lkhomenk Agreed, this is not ideal, let alone practical, for large databases.

Just to note: in the next release (4.2) of the Operator, we are going to support pgBackRest only and remove support for pg_basebackup. We will likely maintain the `pg_basebackup` container for the time being.

However, I am presently on adding support for PG12, which contains changes for the recovery code. As this part of the recovery code, I will see about either parameterizing the WAL method for changing it to `stream`.

Thanks!

**Comment by jkatz** [comment]
@lkhomenk -- if it's ok with you, I want to move this ticket over to the [container suite](https://github.com/CrunchyData/crunchy-containers) project. I think it'd be worthwhile to add it to the pg_basebackup container.

**Comment by lkhomenk** [comment]
Ok. But I'm not sure if it's needed in crunchy-postgres-ha, which uses patroni

**Comment by jkatz** [comment]
@lkhomenk Correct, it's not needed by `crunchy-postgres-ha`, which uses Patroni **+ pgBackRest** for handling the boostrapping/healing. :smile:

It should still be helpful if one is using `crunchy-postgres` on its own and wants to bootstrap a replica, as that is still the method to do so (i.e. [here](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres/start.sh#L208-L241)). It would work independently of the Operator, but could be helpful.

**Comment by jkatz** [comment]
Closed in favor of https://github.com/CrunchyData/crunchy-containers/issues/1179 and the [v4.2.0 release](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0) that changes how replicas are both bootstrapped and healed..
