### ISSUE TITLE
pgBackrest Stanza Create and Backup do not work with Minio based S3

### ISSUE THREAD

**Issue by donicrosby** [CrunchyData/postgres-operator#1078]
**Which example are you working with?**
pgo backup
**What is the current behavior?**
At cluster creation S3 stanza creation fails to create if the S3 provider is Minio based
**What is the expected behavior?**
When creating the Stanza or running a backup for the cluster it should finish successfully allowing for backups to be used on Minio based S3 storage
**Other information** (e.g. detailed explanation, related issues,  etc)
The cluster was installed via Ansible and has the aws-s3-ca.crt replaced with the Let's Encrypt X3 CA as the CA
The stanza fails with this error:
`ASSERT: [025]: key 'vary' already exists\n        STACK TRACE:\n        common/io/http/header:httpHeaderAdd:100:(test build required for parameters)\n            ... function(s) omitted ...\n        common/io/http/client:httpClientRequest:(debug log level required for parameters)\n        storage/s3/storage:storageS3Request:(debug log level required for parameters)\n        storage/s3/storage:storageS3ListInternal:(debug log level required for parameters)\n        storage/s3/storage:storageS3List:(debug log level required for parameters)\n        storage/storage:storageList:(debug log level required for parameters)\n        command/stanza/create:cmdStanzaCreate:(debug log level required for parameters)\n        main:main:(debug log level required for parameters)\n`

The Minio bucket has it's policy set to none so that the cluster must authenticate in order to access the bucket and prevent the internet from accessing it.
**Please tell us about your environment:**

* Operating System:
Debian
* Where is this running ( Local , Cloud Provider)
Local
* Storage being used (NFS, Hostpath, Gluster, etc):
NFS for Minio and Postgres Cluster storage
* Container Image Tag:
crunchydata/crunchy-postgres:centos7-11.5-2.4.2
* PostgreSQL Version:
11.5
* Platform (Docker, Kubernetes, OpenShift):
Kubernetes
* Platform Version:
1.15.5

**Comment by lkhomenk** [comment]
I'd suggest filing this issue at https://github.com/pgbackrest/pgbackrest

**Comment by dwsteele** [comment]
We haven't seen MinIO generate multiple `vary` headers so these are probably being generated by a proxy.  In any case, it's a bug on our side that we have fixed at https://github.com/pgbackrest/pgbackrest/commit/10c8eeaf6c0413da265047aeb02a047209ef9d69.

If you would like your name to appear in the release notes rather than `donicrosby` just let us know.

**Comment by jkatz** [comment]
[v4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0) uses pgBackRest 2.20 and as such this issues is now resolved.
