### ISSUE TITLE
Creating clusters with custom PVC size

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1080]
Hello, 
We see more and more the need to create clusters with custom PVC sizes [data + backup] (as well as CPU and memory).
With the current implementation of the pgo, we can only use the predefined size exposed within the storage configuration.

Such a question has already been asked in the past.

Do you have any plan to make the size more dynamic (eg. passing the actual size to allocate as a parameter of the "create cluster command"?
If yes, do you have a timeline?

Thanks a lot,
José

**Comment by jkatz** [comment]
Hi @ajoyej,

The short answer is "yes" we need to do a better job managing storage sizes, container resource allocation, etc. This is on the roadmap for this year, and I would say it's a matter of "when" not if. To be transparent, I don't think it will be the next release, but we do want to allow for the flexibility to be able to better customize resource and disk allocation.

**Comment by jkatz** [comment]
Hi @jose-joye,

The first in a series of patches for this is now proposed. This should certainly be available in 4.3

Thanks!

**Comment by jose-joye** [comment]
Do you plan to also allow to custom size of backup pvc? Right now, the size is the same for every cluster created.

Thanks for the great work!
José

**Comment by jkatz** [comment]
Hi @jose-joye,

I was going to say "way ahead of you", but your message beat my commit: https://github.com/jkatz/postgres-operator/commit/7f00b27 :wink:

I'm also adding it for tablespaces (4.3 feature) and clone.

**Comment by dadez** [comment]
It would be nice to completely separate the pvc for the cluster from the pvc for the backup.
In our case, we should be able to use different annotations for both pvc's.

**Comment by jkatz** [comment]
Hi @dadez,

I don't follow what you mean. The pgBackRest PVC and the PostgreSQL cluster PVCs are completely separate.

Thanks,

Jonathan

**Comment by dadez** [comment]
@jkatz sorry, I didn't explain it well.
I was meaning the source file (postgres-operator/ansible/roles/pgo-operator/files/pgo-configs/pvc-storageclass.json).
We managed a workaround by adding annotations conditioned on pvc name, you can forget my question.
```
{{if ne .Name (printf "%s%s" .ClusterName "-pgbr-repo")}}
"mylabel": "myvalue",
{{end}}
```
