### ISSUE TITLE
Using SSD Persistent Disks | GCP

### ISSUE THREAD

**Issue by tiwarisuraj9** [CrunchyData/postgres-operator#1093]
**What is the motivation or use case for the change?**

Use SSD storage as PV for primary and replicas for faster I/O

**Please tell us about your environment:**

* Where is this running ( Local, Cloud Provider)
 `Google Cloud Platform`
* Storage being used (NFS, Hostpath, Gluster, etc):
`SSD PV`
* Platform (Docker, Kubernetes, OpenShift):
 `GKE`

**Additional context**

I tried using `storage8_type='faster'` & `storage8_class='pd-ssd'` as suggested in [ssd-pd](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/ssd-pd)  but it didn't work.

**Comment by cbandy** [comment]
@tiwarisuraj9 the `storage{n}_class` variable needs to be set to the name of a [StorageClass](https://kubernetes.io/docs/concepts/storage/storage-classes/) you have created in your Kubernetes cluster. `kubectl get storageclass` will show you the names of classes that are available.
