### ISSUE TITLE
Federation support

### ISSUE THREAD

**Issue by sapkra** [CrunchyData/postgres-operator#1099]
The postgres-operator should work with KubeFed to support HA across multiple data centers.

There are two related issues which both were closed but I couldn't find this feature in the current version.
https://github.com/CrunchyData/postgres-operator/issues/890
https://github.com/CrunchyData/postgres-operator/issues/282

**Comment by jkatz** [comment]
Hi @sapkra,

We are currently working on improving the HA abilities of PostgreSQL clusters managed by the Operator, which you can follow along in the master branch. We are moving to a distributed consensus based approach, which will be released as part of the v4.2.0 release. We want to ensure that we can appropriately support HA PostgreSQL clusters within a single region before opening up the complexities that come with a multi-region deployment.

This will lead us towards federation of PostgreSQL clusters via Kubernetes, though the exact implementation of this remains to be seen. The KubeFed API is still being developed and we want to continue to research what it can do before committing to this implementation path.

I hope this helps. Thanks!

Jonathan

**Comment by sapkra** [comment]
Ok, thank you for your fast response. I'm happy to hear that there is some progress and I must definitely agree that your strategy makes totally sense.

**Comment by jkatz** [comment]
Hi @sapkra,

Per this discussion, we have introduced a type of federation support in the [4.3.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.0) release. You can now [deploy PostgreSQL clusters with the Operator in multiple Kubernetes environments](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/).

As mentioned, we will continue to monitor progress of how Kubernetes multi-cluster support develops, but I believe this is a nice introduction to the ability to support federated workloads, and we will continue to evolve support.

Hope this helps.
