### ISSUE TITLE
How to restore a backup from Cluster A to Cluster B (pgbackrest)

### ISSUE THREAD

**Issue by ajoyej** [CrunchyData/postgres-operator#1101]
We are using pgo 4.1 and are wondering how to restore a pgbackrest backup made for Cluster A to another Cluster (eg: cluster B).
The backup was issued with 'pgo backup' command
We have read the user-guide (https://pgbackrest.org/user-guide.htm). However, we still do not understand how to handle this use case and specially with pgo.

Do you have any hints we can use?

thanks a lot,
José

**Comment by lkhomenk** [comment]
1) pass valid pgbackrest config from cluster A to cluster B
2) init `pgo restore`
We were creating Cluster B just as empty cluster and restoring data there. 
Regarding configuration - we had pgbackest-S3 backups
@ajoyej have you tried using `pgo restore` on cluster B with cluster A config?

**Comment by ajoyej** [comment]
Thanks for your answer!

On my side, I'm currently using local storage.

I have tried to use the `pgo restore`. However, all options are related to pgbasebackup and not to pgbackrest. --> I tried to run a restore for Cluster B by specifying the _backup-pvc_ of Cluster A. However, it has no effect.

I'm not too sure about what you mean by " passing cluster A config"

How did you pass "valid pgbackrest config from cluster A to cluster B"?

Thanks,
José

**Comment by lkhomenk** [comment]
create cluster B with `--pgbackrest` + specify all pgbackrest variables in `pgo.yaml` but use values from cluster A

**Comment by ajoyej** [comment]
I'm a bit lost with your explanation...
I'm using PGO 4.1 and it was installed with ansible.

When you say: specify all pgbackrest variables in `pgo.yaml`, I do not really follow you. 
Do you mean that I have to modify the file within the operator container?
The parameters related to pgo.yaml that can be provided together with the `pgo create cluster` are rather limited.

Thanks,
josé

**Comment by wmudge** [comment]
I tried the following (backup using an existing cluster's archive on S3) but received an error:

```
pgo restore test02 -n test-db --pgbackrest-storage-type=s3 --backup-opts='--repo-path=/backrestrepo/test01-backrest-shared-repo'
Warning:  If currently running, the primary database in this cluster will be stopped and recreated as part of this workflow!
WARNING: Are you sure? (yes/no): yes
Error: Flag --repo-path is not supported for use with PGO
```
How can I get `restore` to point to the other cluster's data?

**Comment by jkatz** [comment]
v4.2.0 added the support for `pgo clone` which solves this issue: this will restore Cluster A as a new cluster Cluster B. You can read more about clone in the release notes and documentation:

- https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0
- https://crunchydata.github.io/postgres-operator/latest/pgo-cli/reference/pgo_clone/

If you wanted to clone a cluster and restore to a particular point in time, in this first release, you must execute the clone and then the restore, e.g.

```shell
pgo clone clustera clusterb
# wait for clone to complete.
pgo restore clusterb --pitr-taget=... # etc.
```
