### ISSUE TITLE
Docker Image Pull Secret

### ISSUE THREAD

**Issue by cp4s-cases** [CrunchyData/postgres-operator#1106]
Operator and postgres images may be hosted on a docker registry requiring credentials.

It should be possible to specify an image pull secret in the ansible inventory which is used during operator install but also when creating pgclusters so that operator and postgres pods are able to pull images from protected repo.

**Comment by jkatz** [comment]
@cp4s-cases Thanks for the report! This is already on our roadmap for the next release.

**Comment by jkatz** [comment]
[v4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0) is released and contains support for `imagePullSecrets`
