### ISSUE TITLE
Failed to create secret pgouser-pgoadmin  caused by the double quotation marks "" for password  are missing in template pgouser-admin.yaml

### ISSUE THREAD

**Issue by zhangxpp** [CrunchyData/postgres-operator#1113]
**Describe the bug**
Failed to create secret pgouser-pgoadmin due to double quotation marks "" for password  are missing in template /odev/src/github.com/crunchydata/postgres-operator/deploy/pgouser-admin.yaml.

**To Reproduce**
1. follow up the guide to disable tls and install pg operator and
https://access.crunchydata.com/documentation/postgres-operator/4.1.1/installation/operator-install/
2. In step Operator Security, 
set passward as a number , for example, 12345678

pgoadmin:12345678

3. execute "$PGOROOT/deploy/install-bootstrap-creds.sh"

**Expected behavior**
Secret pgouser-pgoadmin can be succesfully created. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18004694/69949201-0aabd880-152c-11ea-94bc-3869b4b19ffe.png)

Error from server (BadRequest): error when creating "my-pgouser.yaml": Secret in version "v1" cannot be handled as a Secret: v1.Secret.StringData: ReadString: expects " or n, but found 1, error found in #10 byte of ...|assword":12345678,"r|..., bigger context ...|min","namespace":"pgo"},"stringData":{"password":12345678,"roles":"pgoadmin","username":"pgoadmin"},|...

**Please tell us about your environment:**

* Operating System: centos7
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

if put "", then the problem is fiexed. 
![image](https://user-images.githubusercontent.com/18004694/69949434-72622380-152c-11ea-9d62-0e575946b317.png)

**Comment by jkatz** [comment]
Hi @zhangxpp 

There's a syntax error in your original example:

```json
"stringData":{"password":12345678,"roles":"pgoadmin","username":"pgoadmin"},
```

specifically:

"password":12345678 `,"` roles"

Notice that the the quotation mark is outside of the comma. This is why adding two `"` around the password variable work.

To fix this, ensure it reads:

```json
"stringData":{"password":12345678", roles":"pgoadmin","username":"pgoadmin"},
```

i.e. using `",`

**Comment by zhangxpp** [comment]
> Hi @zhangxpp
> 
> There's a syntax error in your original example:
> 
> ```json
> "stringData":{"password":12345678,"roles":"pgoadmin","username":"pgoadmin"},
> ```
> 
> specifically:
> 
> "password":12345678 `,"` roles"
> 
> Notice that the the quotation mark is outside of the comma. This is why adding two `"` around the password variable work.
> 
> To fix this, ensure it reads:
> 
> ```json
> "stringData":{"password":12345678", roles":"pgoadmin","username":"pgoadmin"},
> ```
> 
> i.e. using `",`

I modified the template  as below  and it works.

apiVersion: v1
stringData:
  password: **"**$PGOADMIN_PASSWORD**"**
