### ISSUE TITLE
Improve S3 configuration experience with PGO.

### ISSUE THREAD

**Issue by chrisjtwomey-ibm** [CrunchyData/postgres-operator#1115]
This a git issue to track what was discussed in a cadence call with Crunchy team. Here are the main points:

1. Currently S3 configuration is only configurable via Operator deploy and not a per-cluster basis. This should be done at the cluster-level as multiple cluster should be able to use different S3 buckets if needed.

2. S3 configuration would be ideal if it were configurable via the `pgcluster` CRD.

3. S3 certs and credentials should be consumed by pgbackrest as kube secrets as opposed to updating yaml files in the pgo-backrest configuration.

4. (nice-to-have): debrand certain S3 configurations (ie. `aws-s3-key`, `aws-s3-key-secret`) as there are S3 providers that are not AWS.

**Comment by chrisjtwomey-ibm** [comment]
Related issue: https://github.com/CrunchyData/postgres-operator/issues/917

**Comment by jkatz** [comment]
Hi @chrisjtwomey-ibm, we are actively working on the per-cluster configuration for the 4.2 release as well as ensuring the credentials are in secrets. Thanks!

**Comment by jkatz** [comment]
The per-cluster configuration and ensuring credentials are in secrets were completed in the [v4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0) release.
