### ISSUE TITLE
Pgbackrest job - Error connectiong kube-api "connect: connection refused"

### ISSUE THREAD

**Issue by anshudutta** [CrunchyData/postgres-operator#1124]
**Describe the bug**
I have enabled pgbackrest and when backup job fails with  the error `connect: connection refused` when trying to send POST request to kube-api.

```
time="2019-12-06T03:27:53Z" level=info msg="pgo-backrest starts"
time="2019-12-06T03:27:53Z" level=info msg="debug flag set to false"
time="2019-12-06T03:27:53Z" level=info msg="backrest backup command requested"
time="2019-12-06T03:27:53Z" level=info msg="command to execute is [pgbackrest backup --type=full]"
time="2019-12-06T03:27:53Z" level=info msg="command is pgbackrest backup --type=full "
time="2019-12-06T03:27:53Z" level=error msg="error sending request: Post https://10.22.0.1:443/api/v1/namespaces/postgres-operator/pods/alchemy-database-backrest-shared-repo-5f7b689cbc-t9qq9/exec?command=bash&container=database&stderr=true&stdin=true&stdout=true: dial tcp 10.22.0.1:443: connect: connection refused"
time="2019-12-06T03:27:53Z" level=info msg="output=[]"
time="2019-12-06T03:27:53Z" level=info msg="stderr=[]"
time="2019-12-06T03:27:53Z" level=error msg="error sending request: Post https://10.22.0.1:443/api/v1/namespaces/postgres-operator/pods/alchemy-database-backrest-shared-repo-5f7b689cbc-t9qq9/exec?command=bash&container=database&stderr=true&stdin=true&stdout=true: dial tcp 10.22.0.1:443: connect: connection refused"

```
Note: we have istio as a side-car

**Expected behavior**
Backups should work

* Operating System: centos7
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag: centos7-11.4-2.3.3, centos7-3.5.3
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.12.10-gke.17
**Additional context**
Note: We have istio as service mesh and all pods have istio side-car

**Comment by jkatz** [comment]
Hi @anshudutta,

A few things:

1. The endpoint being hit `https://10.22.0.1:443/api/v1/namespaces/postgres-operator/pods/alchemy-database-backrest-shared-repo-5f7b689cbc-t9qq9/exec?` with the error `dial tcp 10.22.0.1:443: connect: connection refused"` this error seems to indicate there is some issue within your Kubernetes environment. This is independent of the PostgreSQL Operator's implementation of pgBackRest.

2. 3.5.3 is an older version. The latest release in the `REL_3_5` series is 3.5.5, which is effectively the final release of that series. I would recommend looking into upgrading to the 4.1.x series, which has better pgBackRest support, as will the unreleased 4.2.x series which standardizes the physical PostgreSQL backups around pgBackRest.

Thanks!

**Comment by anshudutta** [comment]
For some reason the jobs created for pgbackrest have `restartPolicy:Never`. This doesn't work as the job almost always fails the first time with the above error. I don't know why but this is not due to kubernetes setup as the cluster is working fine. Anyways, setting the `restartPolicy:OnFailure` seems to have solved the problem. For now...

**Comment by haf** [comment]
It's a faulty assumption that network is always up and that all connections always succeed. This should be reopened and be properly fixed.

**Comment by jkatz** [comment]
Please see comment in https://github.com/CrunchyData/postgres-operator/issues/1200#issuecomment-864090327

Note that the GH issues you keep referencing are several years old and a bunch has changed in PGO since they were opened.
