### ISSUE TITLE
Assign pre-existing volumes to pgo cluster

### ISSUE THREAD

**Issue by anshudutta** [CrunchyData/postgres-operator#1132]
** Which example are you working with? **
I have set up a cluster using pgo

**What is the current behavior?**
Setting the `storageType: dynamic` creates new pvc and volumes.

**What is the expected behavior?**
What if I wanted to provision a volume and make the cluster use that "pre-existing" volume. Is there a setting for that?

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

Operating System: centos7
Where is this running ( Local, Cloud Provider)
Storage being used (NFS, Hostpath, Gluster, etc):
Container Image Tag: centos7-11.4-2.3.3, centos7-3.5.5
PostgreSQL Version:
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.12.10-gke.17

**Comment by jkatz** [comment]
If you have a PVC that already exists, just set the name of your cluster to be the name of that PVC.

For example, if your PVC is called `existing-claim`, you can execute:

```shell
pgo create cluster existing-claim
```
