### ISSUE TITLE
all logs to stdout and stderr

### ISSUE THREAD

**Issue by dadez** [CrunchyData/postgres-operator#1141]
**What is the motivation or use case for the change? **
While debugging or monitoring no one think about search for logs in a file into a pod
the database logs are stored on the pod filesystem
```
$ ls -l /pgdata/<clustername>/pg_log
total 278728
-rw------- 1 postgres postgres 31686651 Dec  7 00:00 postgresql-Fri.log
-rw------- 1 postgres postgres 22811053 Dec 10 00:00 postgresql-Mon.log
-rw------- 1 postgres postgres 31696864 Dec  8 00:00 postgresql-Sat.log
-rw------- 1 postgres postgres 31703672 Dec  9 00:00 postgresql-Sun.log
-rw------- 1 postgres postgres 31683368 Dec  6 00:00 postgresql-Thu.log
-rw------- 1 postgres postgres 39911138 Dec 10 22:38 postgresql-Tue.log
-rw------- 1 postgres postgres 94752163 Dec 11 10:15 postgresql-Wed.log
```

**Describe the solution you'd like**
All logs should be sent to STDOUT and STDERR. 
I should be able to see all logs by running
`$ kubectl -n <namespace> logs <pod name>`

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: crunchydata/centos7-11.5-2.4.2
* PostgreSQL Version: 11.5
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.10.11

**Comment by jkatz** [comment]
Hi @dadez,

Thanks, this is something we are presently evaluating. We want to ensure we have a solution to allow people to persist their PostgreSQL logs after the Kubernetes default (10MB) of logs being stored and are looking into solutions around that.

If you want to log to stderr, you can manually change this in your `postgresql.conf` file.

In your `postgresql.conf` file, set

`log_destination = 'stderr'`

and reload the configuration.

**Comment by dadez** [comment]
Hi jkatz,
Thank you for the quick answer. 
Is there a way to reload the configuration in a pod without restart it?

**Comment by jkatz** [comment]
@dadez A few ways:

1. You can use the `pgo reload` command: [pgo reload](https://access.crunchydata.com/documentation/postgres-operator/latest/operatorcli/cli/pgo_reload/)
1. You can `kubectl exec` into the Pod and run `pg_ctl -D /pgdata/$DATA_DIR_NAME`

**Comment by GeorgFleig** [comment]
If anyone else is interested in logging to stderr:

`log_destination = 'stderr'` is already set in the default configuration. But logs get collected in log files if `logging_collector = on` is set. So set this to `off` instead. This could be done via `patronictl edit-config` or in the config maps containing a (custom) postgres config.


Furthermore, the described way of reloading postgres is not sufficient for this type of config change:

```
2020-05-15 13:01:00.468 UTC [19931] LOG:  received SIGHUP, reloading configuration files
2020-05-15 13:01:00.469 UTC [19931] LOG:  parameter "logging_collector" cannot be changed without restarting the server
```

I used `patronictl restart $CLUSTER_NAME` to apply the config change. Now logs are visible with the `kubectl logs` command.
