### ISSUE TITLE
Customized options are not appended if --custom-config is specified 

### ISSUE THREAD

**Issue by yuanlinios** [CrunchyData/postgres-operator#1179]
**Describe the bug**
Setup a streaming replication pg cluster with customized postgresql.conf does not work. The content of `/tmp/pgrepl-recovery.conf` is not appended to `postgresql.conf`

**To Reproduce**
```
oc create -n pg-proj configmap pg-custom-config \
    --from-file=configs/server.crt \
    --from-file=configs/server.key \
    --from-file=configs/pg_hba.conf \
    --from-file=configs/postgresql.conf

pgo create cluster devcluster --replica-count=1 --custom-config pg-custom-config -n pg-proj
```
login pod, check postgresql.conf and replication status

**Expected behavior**
The content of  `/tmp/pgrepl-recovery.conf` should append to `postgresql.conf` to make streaming replication work

**Please tell us about your environment:**

* Container Image Tag: crunchydata/crunchy-postgres:centos7-12.1-4.1.1
* PostgreSQL Version: 12.1
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 3.11

**Additional context**
Create the cluster without --custom-config works OK
```
pgo create cluster devcluster --replica-count=1 -n pg-proj
```

**Comment by jkatz** [comment]
Hi @yuanlinios,

I would like to better understand your use case as to why you want to customize the streaming replication settings.

In the context of the upcoming [`v4.2.0` release](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0-beta.1), we've improved the high-availability/disaster recovery system and encapsulated a lot of the complexity around setting up streaming replication manually and provide some additional features, such as being able to set up synchronous replicas.

Additionally, if you're using PostgreSQL 12, the `recovery.conf` file has been removed and its settings have been moved to the main `postgresql.conf file. Having the `recovery.conf` file present in the data directory of a PostgreSQL 12 cluster will trigger a `FATAL` error and cause it to not start.

**Comment by yuanlinios** [comment]
Hello @jkatz 

Thanks for your quick reply! 

Actually I do not want to customize the "streaming replication", I only want to to enable TLS/SSL encryption. That's the reason I created the "pg-custom-config" configmap.

The problem I noticed is: when I provide the `--custom-config` option, the streaming replication config lines, which are supposed to be appended in `postgresql.conf` in postgres 12 (right?), are not appended anymore

**Comment by jkatz** [comment]
Hi @yuanlinios,

So the short answer is my suggestion to re-evaluate when `v4.2.0` is released, which will be in the coming days. In v4.2.0, we leverage the open source Patroni framework for managing high-availability. Patroni will automatically manage the `postgresql.conf` and `recovery.conf` files, and similarly you are able to customize the inputs to Patroni to provide the TLS settings.

This also handles the PG12 transition better for how the management of recovery settings has changed.

**Comment by yuanlinios** [comment]
Hello @jkatz 

Thanks for the reply. I will try again with the `v4.2.0` release

**Comment by yuanlinios** [comment]
This issue no longer exists in `v4.2.x`.

In `v4.2.x`, some postgresql options (e.g. `max_connections`, `wal_keep_segments`, etc) are managed by patroni,  a configmap including customized `postgres-ha.yaml` is needed if you want to overwrite these default values
