### ISSUE TITLE
Allow extending postgresql.conf instead of full replacement when using --custom-config

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1193]
We have a use-case where we want to add/replace 1 or 2 values within the `postgresql.conf` file at the time a specific cluster is created using `pgo create cluster` .

At the moment, if we want this feature we have to provide the complete customized postgresql.conf within a configMap and refer it using the --custom-config parameter (when calling `pgo create cluster`.

Will it be possible to extend the feature so that we can select if we want a full replacement of `postgresql.conf` file (current situation) or simply an append using what is provided within the configMap provided using --custom-config parameter?

As an implementation idea, it could be possible to use the `include_dir` or `include_if_exists` feature within the postgresql.conf file

Regards,
José

**Comment by jkatz** [comment]
Hi @ajoyej,

This is a great suggestion. We have been thinking of ways to make it easier to add customizations into the `postgresql.conf` file and will incorporate this feedback!

**Comment by lkhomenk** [comment]
Full postgresql.conf replacement strategy was used in pre-4.2 versions. we were also expecting our full postgresql.conf to be used. in 4.2 we switched to creating our own config map from `postgres-ha.yaml` template. it kinda works if this configmap is created before cluster. but I assume it wasn't supposed to be used this way

**Comment by zarko-a** [comment]
Hope that you won't mind if I piggy-back on this issue. I had a different use case that is relevant to the custom config discussion. 

We are using TimescaleDB which requires us to modify the configuration to add the extension to `shared_preload_libraries`. Currently I'm handling this by editing postgres-ha-initdb.yaml and adding it to a custom docker image.  We need to create a custom image to add timescaledb in any case...

However, timescaledb offers a tune utility that will evaluate CPU and Memory resources and tweak some additional settings of PostgreSQL. It's just a small binary that modifies the config file which you can specify during the run.
https://github.com/timescale/timescaledb-tune
I tried adding, the following to `bootstrap-postgres-ha.sh`. But couldn't get expected results. The file didn't get modified. Not sure how/when is the `postgresql.base.conf` initially generated.
```
touch ${PATRONI_POSTGRESQL_DATA_DIR}/postgresql.base.conf
/usr/bin/timescaledb-tune -yes -conf-path ${PATRONI_POSTGRESQL_DATA_DIR}/postgresql.base.conf
```

What would be the best way to modify the image to run this utility each time before the Postgres starts? 

Maybe asking too much here, but it would be awesome if there was a way to easily specify a command to run before running PGS. Either in the image or on a cluster level. Like a "pre-run hook"...

**Comment by cubed-it** [comment]
I do not fully understand the new procedure. I see my customized /pgconf/postgresql.conf but the include in /pgdata/proddb-qpup/postgresql.conf is done at the very beginning. so some of the customized settings like e.g. work_mem are lost?

**Comment by zarko-a** [comment]
@cubed-it  I think we are waiting for a more robust solution from Crunchy team for now. 

At the moment I found a couple of ways to edit settings manually.
The first one I mentioned in my post above is done during the DB init, the second one can be used after the cluster is spun up. It's using `patronictl edit-config` and then `patronictl restart <cluster name > `.

**Comment by afreidah** [comment]
FYI to those having this issue...I found another approach that might work for you.  I was having the same issue where the fact the include was at the top of the file meant anything later referenced in the default postgresql.conf would override my changes.  Instead of creating a configmap with a postgresql.conf file, create one with a postgres-ha.yaml file.  From what I can tell this file gets read on init and the default postgresql.conf file in /pgdata gets rendered using values you supply here.  Example of my configmap that successfully put all these values in the running config:

`---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alex-test-pgcluster-configfile-configmap
data:
  postgres-ha.yaml: |-
    ---
    bootstrap:
      dcs:
        postgresql:
          parameters:
            max_connections: {{ .Values.config.max_connections }}
            pg_stat_statements.max: {{ .Values.config.pg_stat_statements_max }}
            pg_stat_statements.track: {{ .Values.config.pg_stat_statements_track }}
            shared_buffers: {{ .Values.config.shared_buffers }}
            maintenance_work_mem: {{ .Values.config.maintenance_work_mem }}
            work_mem: {{ .Values.config.work_mem }}
      initdb:
      - encoding: UTF8
`
obviously you can hard code values in there I'm just using templating.  But this does in fact work when you spin up a new cluster to get the values you want customized.

**Comment by jkatz** [comment]
Hi,

Version [4.3.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.0) has brought about a bunch of changes in terms of how you can [customize your PostgreSQL configuration](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/). I hope you find it much easier to do now. You can read about it here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/)

Thanks!

**Comment by Venryx** [comment]
Nevermind, it looks like the Custom Configuration page was just moved for v5: https://access.crunchydata.com/documentation/postgres-operator/5.0.1/tutorial/customize-cluster

I was able to achieve what I was looking for (enabling access to all databases for all users with an encrypted password, as [seen here](https://dba.stackexchange.com/a/84002/222697)) including the below in `postgres.yaml`:
```
[...]
spec:
  [...]
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - host all all 0.0.0.0/0 md5
```
