### ISSUE TITLE
Running initialization SQL queries on a cluster

### ISSUE THREAD

**Issue by paulbarbu** [CrunchyData/postgres-operator#1199]
Hello,

First of all: thanks for this piece of software. It makes life easier when porting a legacy app to Kubernetes to setup PostgreSQL.

Altough, there is something the documentation doesn't clearly states:
If I want to run a SQL query/file on a given PostgreSQL cluster, what are my possibilities?
(apart from connecting with psql to the pod running the CrunchyData postgresql operator and manually running the file)
The legacy app I'm porting to kubernetes requires the DB to be already initialized and populated when it first connects to it.

I saw there is a `pgo create policy` command and then `pgo apply <policyname>` counterpart.
What do these policies do and are they fit for my use case, considering the policy is stored?
Are these policies documented somewhere and I just missed the docs?
If not, then what are they and what are some use-cases for them?

**Comment by jkatz** [comment]
Hi @paulbarbu,

The `policy` name is a bit of a misnomer -- it's not a policy per se, but actually a way to execute a SQL file of your choosing.

So let's say you want to have a brand new cluster execute a SQL script that does something like:

```sql
CREATE TABLE vegetables (vegetable_name text);
INSERT INTO vegetables VALUES ('carrot'), ('tomato'), ('celery'), ('kale');
```

saved to `veggies.sql`

You could do the following:

```shell
pgo create policy veggie_bootstrap --in-file=veggies.sql
pgo create cluster healthfoods --policies=veggie_bootstrap
```

(with appropriate namespace if need be with `-n`)

The PostgreSQL Operator will create the PostgreSQL cluster and, once it is ready, will then execute the policy that was defined, which is a set of SQL statements that you define. The file will be executed as the `postgres` user, so you may wish to set the session authorization or the database you wish to connect to from within the file.

For more on getting started:

[Policy Management](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#policy-management)

Hope this helps!

**Comment by paulbarbu** [comment]
Thank you for the answer.

> For more on getting started:

Unfortunately there is not much detail in that document.
Could you please clarify for me the following details:

* Is there any way to see a list of the current policies and their content?
* How can one see the errors (if any) generated after a `pgo apply` command. If there are errors in a sql script apparently the command simply reports: "Applied policy on <cluster name>" (I introduced some errors manually since some of the SQL queries I have written are not executed properly and I'm trying to debug). `kubectl logs` doesn't yield anything useful. Which leads me to the next question:
* How are the `pgo apply` SQL queries really executed? Using `psql` on the pod running the operator (hence the master PostgreSQL instance)? I'm asking this since, apart from classic SQL queries, I'd like to run `psql` specific commands like `\c` in my policy file.

**Comment by paulbarbu** [comment]
>     * How are the `pgo apply` SQL queries really executed? Using `psql` on the pod running the operator (hence the master PostgreSQL instance)? I'm asking this since, apart from classic SQL queries, I'd like to run `psql` specific commands like `\c` in my policy file.

This I have puzzled out myself: including command like `\c your_db_name` in the policy SQL file works. So I assume it is ran through the `psql` command indeed.

**Comment by jkatz** [comment]
Hi @paulbarbu,

You've raised some very good points :smile:

> Is there any way to see a list of the current policies and their content?

```
pgo show policy --all
```

which covers both of your questions. You may need to add a `-n` flag for the namespace you are working in.

>How can one see the errors (if any) generated after a pgo apply command. If there are errors in a sql script apparently the command simply reports: "Applied policy on " (I introduced some errors manually since some of the SQL queries I have written are not executed properly and I'm trying to debug). kubectl logs doesn't yield anything useful.

By default, the PostgreSQL pods logs to the filesystem and is stored in the `pg_log` directory, which you can find in `/pgdata/<clustername>/pg_log`. That will show the errors.

We're looking into changing the default to having PostgreSQL log to `stderr`, which both PostgreSQL can handle and is more of the Kubernetes way of doing it. You can actual set PostgreSQL to log to `stderr` today by using a custom `postgresql.conf` file, e.g.:

https://github.com/CrunchyData/postgres-operator/issues/1141

**Comment by paulbarbu** [comment]
Hello @jkatz,

Thank you for the reply, it's all clear now.

I'm closing this.

**Comment by sskurapati** [comment]
Thanks to @paulbarbu  for bringing this question.
Thanks to @jkatz  from addressing this.

We are creating cluster with helm charts.
How to create/apply these policies using manifest files/helm files?

**Comment by dberardo-com** [comment]
correct, is there a way to upload a queries file to bootstrap the cluster, or perhaps some in-yaml hard coded queries as string ?
