### ISSUE TITLE
Jobs fail due to no delay and no retries when using an Istio sidecar

### ISSUE THREAD

**Issue by saltenhub** [CrunchyData/postgres-operator#1200]
**Describe the bug**
When using Istio with sidecar injection enabled and mTLS enabled on the namespace the cluster is deployed to, all jobs (creation and removal) fail due to the Istio sidecar (envoy proxy) not being ready to take requests when the jobs tries to query the API server ending in "connection refused" errors, leaving the jobs in a perpetual error state. 

**To Reproduce**
1. Install Istio in your cluster and enable sidecar injection for the operator namespace and the namespace the cluster should be deployed into.
2. Create cluster and find that the create-stanza transitions to an error state and is never removed (due to `restartPolicy: "Never"` and `backoffLimit: 0`
3. Remove cluster and find that the rmdata job transitions to an error state and is never removed with the cluster (and pvcs etc.) also not being removed

**Expected behavior**
I know that this behavior is not specific to this operator but since Istio is popular and a common usage scenario I would suggest that jobs should best have a configurable initial delay before trying to make requests and some configurable retry amounts for the API server calls, or maybe changing `restartPolicy` or `backoffLimit` or making them configurable. I am not an expert on the matter, but definitely willing to look into the implementation and maybe submit a PR to realize the delays.

**Please tell us about your environment:**

* Operating System: Linux (Centos 7)
* Where is this running ( Local, Cloud Provider): Baremetal self-hosted cloud
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: centos-4.2.0
* PostgreSQL Version: 12.1
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16.3
* Istio Version: 1.4.3

[Edit 2019-01-12]
Related issue on Istio side with various workarounds and fixes:
https://github.com/istio/istio/issues/11130

Related issue in this repo:
https://github.com/CrunchyData/postgres-operator/issues/1124

**Comment by cbandy** [comment]
Related: https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md

**Comment by haf** [comment]
It's a faulty assumption that network is always up and that all connection always succeed. This should be reopened and be properly fixed.

**Comment by haf** [comment]
Can I somehow tell this operator to put a retry policy on the job's container? This would be a quick fix; just have it restart

**Comment by jkatz** [comment]
PGO Job retries use the Kubernetes defaults, which is 6.

If you need to modify any of the Job instructions, you can do so from the the pgo-config ConfigMap.

Unfortunately the URL that @cbandy referenced no longer exists, but it had provided an explanation on the state of affairs around the original discussion a year ago.
