### ISSUE TITLE
postgres-operator ignores cluster CR deletion

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#1203]
**Describe the bug**
If PgCluster CR of the cluster is deleted - operator does nothing. all object remain

**To Reproduce**
1. Provision any pg_cluster with `pgo` or by creating CR from yaml
2. Wait for cluster creation to complete
3. Delete pg_cluster CR
4. Wait for cluster deletion

**Expected behavior**
Before 4.2 operator was deleting cluster objects after CR was deleted

**Please tell us about your environment:**

* Operating System: centos7
* Where is this running ( Local, Cloud Provider): AWS
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag: centos7-10.11-4.2.0
* PostgreSQL Version: 10-11
* Platform (Docker, Kubernetes, OpenShift): Openshift 
* Platform Version: 3.11

**Comment by stoetti** [comment]
Are there any updates on the timeline for this feature?

**Comment by jkatz** [comment]
This will be available in 4.6.0
