### ISSUE TITLE
Pod antiAffinity for pgbouncer

### ISSUE THREAD

**Issue by GeorgFleig** [CrunchyData/postgres-operator#1207]
**What is the motivation or use case for the change?**

Thanks for adding support for antiAffinity with 4.2.0 (and all the other great changes that came with that release)!

The pgbouncer pod itself is not considered for the antiAffinity of other pods because it is missing the label `"pg-pod-anti-affinity": "preferred"` when it was enabled during the creation of the cluster.

**Describe the solution you'd like**

Without this label it can happen that the pgbouncer ends up on the same node as the pg master. In case this node goes down, not only the master is gone but also the bouncer needs to get redeployed. I'd like the pgbouncer to be part of the antiAffinity setting. Especially when scaling up the pgbouncer deployment to make it HA, the two pods should not end up on the same node.

**Please tell us about your environment:**

* PostgreSQL Version: 11.6
* Platform (Docker, Kubernetes, OpenShift): v1.15
* Platform Version: 4.2.0

**Comment by jkatz** [comment]
Hi @GeorgFleig,

This is certainly a valid use case and something we can include in a future release.

I would note (as you noted) that the way the PostgreSQL Operator currently deploys pgBouncer does create it as a single-point-of-failure as we only support a single pgBouncer instance (Pod) in its Deployment. So even if with the updated pod anti-affinity rule on it, if the pgBouncer Pod is on a different node than the primary, and the primary goes down, and your connections are being routed via pgBouncer... :wink:

(This was one of the reasons why we pushed this case to a later release, as we wanted to get the base case with pod anti-affinity with the PostgreSQL instances into working order.)

**Comment by GeorgFleig** [comment]
Turned out the label is already present when PGO was deployed via bash and not via ansible. See https://github.com/CrunchyData/postgres-operator/issues/1218#issuecomment-575042520

Compare:
- https://github.com/CrunchyData/postgres-operator/blob/master/conf/postgres-operator/pgbouncer-template.json#L22
- https://github.com/CrunchyData/postgres-operator/blob/master/ansible/roles/pgo-operator/files/pgo-configs/pgbouncer-template.json#L21

**Comment by jkatz** [comment]
This should be fixed in v4.2.1
