### ISSUE TITLE
pgouser credentials are stored in configmap. 

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#121]
Is it possible to store the credentials in a secret object instead of configMap ?

**Comment by jmccormick2001** [comment]
it appears this is already the case, I think the create-secrets.sh script was confusing things, with that gone I think this is good to close.

**Comment by pmereddy1** [comment]
Even in 2.5 operator, apiserver-conf configMap contains pgouser credentials. 
This configMap is created by $COROOT/deploy/deploy.sh script.
Is it possible to move this into a secret object ?

**Comment by jmccormick2001** [comment]
should be fixed in 2.6,  but worth a test.
