### ISSUE TITLE
pgo output on windows has unreadable characters

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#122]
pgo show cluster testcluster

cluster : testcluster (centos7-9.6.6-1.7.1)
â”œâ”€â”€ pod : testcluster-cb4985cd-sxtfm (Running on w1.tectonic.local) (1/1)
	â”œâ”€â”€ pvc : testcluster-pvc
â”œâ”€â”€ pod : testcluster-replica-lube-64d8cf47f9-xs595 (Running on w1.tectonic.local) (1/1)
	â”œâ”€â”€ pvc : testcluster-replica-lube-pvc
â”œâ”€â”€ deployment : testcluster
â”œâ”€â”€ deployment : testcluster-replica-lube
â”œâ”€â”€ service : testcluster (10.3.243.44)

**Comment by jmccormick2001** [comment]
merged in a fix for this, special chars are now replaced with simple tabs, merged into pre26 branch
