### ISSUE TITLE
Release v4.2.1: PGO client library missing & images not yet available

### ISSUE THREAD

**Issue by saltenhub** [CrunchyData/postgres-operator#1223]
**Describe the bug**
First of all, I want to thank you for the great work in general and the quick fixes coming with v4.2.1.
Unfortunately, it seems as if the images are not ready yet and the PGO client library is missing in the [release](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.1). Hence the ansible install/update tasks fail with a 404 downloading the client library and I can only guess that this will be the same using the bash variant:
```
TASK [pgo-operator : Download PGO Linux Client] ****************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/usr/local/bin/pgo", "elapsed": 0, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "secontext": "system_u:object_r:bin_t:s0", "size": 36941034, "state": "file", "status_code": 404, "uid": 0, "url": "https://github.com/CrunchyData/postgres-operator/releases/download/v4.2.1/pgo"}
```
 Additionally, the v.4.2.1 releases are not available on [dockerhub](https://hub.docker.com/r/crunchydata/crunchy-postgres/tags) (yet), so container creation fails with:
```
Normal   Pulling    5m39s                 kubelet, example.com  Pulling image "crunchydata/postgres-operator:centos7-4.2.1"
``` 
If this is the case because of some sort of pre-release: I am sorry to have bothered you & please feel free to close this issue.

**To Reproduce**
1. Try to install/update 4.2.1 release via ansible
2. See that downloading client library fails
3. See that operator container creation fails

**Expected behavior**
Ansible install/update should work upon official release; Images should be available opon official release.

**Comment by jkatz** [comment]
Hi @saltenhub,

Thanks for your enthusiasm about the 4.2.1 release! Though the tag is applied, notice it is in the "pre-release" state as we are going through final builds, scans, and smoke tests.

I will be sure to update you when the "pre-release" state is moved.

Thanks!

**Comment by saltenhub** [comment]
Hey @jkatz! Oh, thanks for the information (I did expect something along these lines, but was confused by the release announcement text). Sorry for bothering you with this and thanks again for your work!

**Comment by jkatz** [comment]
@saltenhub Yeah, it's complicated :smile: We push the announcement to several channels though technically this is the base of it. Totally understand that it's confusing.

I mostly wanted to ensure that those who were pushing the message had all the appropriate stuff available. Also we like to leave it at pre-release in case we have to do some last minute thing until everything is all pushed (which so happened today).

Anyway, once it is up I'll let you know :smile: Thanks!

**Comment by jkatz** [comment]
Hi @saltenhub,

Everything is up. Enjoy!

**Comment by saltenhub** [comment]
Hey @jkatz!
Thanks for the work & the info - already updated :)
