### ISSUE TITLE
pgBackrest stanza create fails with URI path style s3 backend

### ISSUE THREAD

**Issue by GeorgFleig** [CrunchyData/postgres-operator#1228]
**Describe the bug**
I am experiencing the same issue as described in https://github.com/CrunchyData/postgres-operator/issues/1155 with PGO version 4.2.0.

Created a fresh pg cluster with S3 (Minio) as pgBackrest backend. Primary pg pod and pgbackrest pods are created, the stanza creation fails.

```
# kubectl logs pgs3only-stanza-create-qwn5k
time="2020-01-17T10:36:53Z" level=info msg="pgo-backrest starts"
time="2020-01-17T10:36:53Z" level=info msg="debug flag set to false"
time="2020-01-17T10:36:53Z" level=info msg="backrest stanza-create command requested"
time="2020-01-17T10:36:53Z" level=info msg="s3 flag enabled for backrest command"
time="2020-01-17T10:36:53Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=192.168.151.191 --db-path=/pgdata/pgs3only --repo-type=s3]"
time="2020-01-17T10:36:53Z" level=info msg="command is pgbackrest stanza-create  --db-host=192.168.151.191 --db-path=/pgdata/pgs3only --repo-type=s3 "
time="2020-01-17T10:36:54Z" level=error msg="command terminated with exit code 50"
time="2020-01-17T10:36:54Z" level=info msg="output=[]"
time="2020-01-17T10:36:54Z" level=info msg="stderr=[ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-archive.lock': Resource temporarily unavailable\n       HINT: is another pgBackRest process running?\n]"
time="2020-01-17T10:36:54Z" level=error msg="command terminated with exit code 50"
```

Executing the same command inside the pgbackrest-repo pod produces the same error. The lock file is present and used by a running pgbackrest process:

```
[pgbackrest@pgs3only-backrest-shared-repo-865d79d7f4-dtpg6 /]$ pgbackrest stanza-create  --db-host=192.168.151.191 --db-path=/pgdata/pgs3only --repo-type=s3
ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-archive.lock': Resource temporarily unavailable
       HINT: is another pgBackRest process running?

[pgbackrest@pgs3only-backrest-shared-repo-865d79d7f4-dtpg6 /]$ cat /tmp/pgbackrest/db-archive.lock
69

[pgbackrest@pgs3only-backrest-shared-repo-865d79d7f4-dtpg6 /]$ ps aux | more
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
pgbackr+     1  0.0  0.0  11712  2764 ?        Ss   10:36   0:00 /bin/bash /usr/local/bin/pgo-backrest-repo.sh
pgbackr+    17  0.0  0.0 112940  7600 ?        S    10:36   0:00 /usr/sbin/sshd -D -f /sshd/sshd_config
pgbackr+    47  0.0  0.0 115016  7852 ?        Ss   10:40   0:00 sshd: pgbackrest@notty
pgbackr+    48  0.0  0.0  13008  2984 ?        Ss   10:40   0:00 /bin/bash /usr/local/bin/archive-push-s3.sh --c --command=archive-push --log-level-file=off --log-level-stderr=error --pg1-path=/pgdata/pgs3only --process=0 --repo1-path=/backrestrepo/pgs3only-backrest-shared-repo --repo1-s3-bucket=pg-test --repo1-s3-ca-file=/sshd/aws-s3-ca.crt --repo1-s3-endpoint=XXX --repo1-s3-region=XXX --repo1-type=s3 --stanza=db --type=backup remote
pgbackr+    69  0.0  0.0 124028  8556 ?        S    10:40   0:00 pgbackrest --c --command=archive-push --log-level-file=off --log-level-stderr=error --pg1-path=/pgdata/pgs3only --process=0 --repo1-path=/backrestrepo/pgs3only-backrest-shared-repo --repo1-s3-bucket=pg-test --repo1-s3-ca-file=/sshd/aws-s3-ca.crt --repo1-s3-endpoint=XXX --repo1-s3-region=XXX --repo1-type=s3 --stanza=db --type=backup remote
pgbackr+    70  0.1  0.0  11980  3076 pts/0    Ss   10:42   0:00 /bin/bash
pgbackr+    91  0.0  0.0  51776  3516 pts/0    R+   10:43   0:00 ps aux
pgbackr+    92  0.0  0.0    356    16 pts/0    R+   10:43   0:00 more
```

Edit: More details further down: https://github.com/CrunchyData/postgres-operator/issues/1228#issuecomment-591550279

**To Reproduce**

```
pgo create cluster -n postgres --replica-count 2 --pgbackrest-s3-bucket pg --pgbackrest-s3-endpoint XXX --pgbackrest-s3-key XXX --pgbackrest-s3-key-secret XXX --pgbackrest-storage-type "s3" --pgbackrest-s3-region XXX pgs3only
```

Created 5 clusters, failed every time.

**Expected behavior**
Stanza creation works without issues.

**Please tell us about your environment:**

* Deployment method: ansible
* Operating System: Ubuntu 18.04
* Where is this running: Private cloud
* Storage being used: Ceph
* Container Image Tag: 4.2.0
* PostgreSQL Version: 11.6
* Platform (Docker, Kubernetes, OpenShift): k8s 1.15

**Additional context**
- Minio S3 backend
- S3 config is not placed in PGO yaml but provided during cluster creation
- Happens with  `--pgbackrest-storage-type "s3"` and  `--pgbackrest-storage-type "s3,local"`

Let me know if you need any additional debug information.

**Comment by eminden** [comment]
my case is different, but related to this thread, I have tried using wasabi s3 service, having the following error messages.

```
time="2020-02-07T22:54:16Z" level=info msg="pgo-backrest starts"
time="2020-02-07T22:54:16Z" level=info msg="debug flag set to false"
time="2020-02-07T22:54:16Z" level=info msg="backrest stanza-create command requested"
time="2020-02-07T22:54:16Z" level=info msg="s3 flag enabled for backrest command"
time="2020-02-07T22:54:16Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=100.64.0.168 --db-path=/pgdata/db --repo-type=s3]"
time="2020-02-07T22:54:16Z" level=info msg="command is pgbackrest stanza-create  --db-host=100.64.0.168 --db-path=/pgdata/db --repo-type=s3 "
time="2020-02-07T22:55:17Z" level=error msg="command terminated with exit code 95"
time="2020-02-07T22:55:17Z" level=info msg="output=[]"
time="2020-02-07T22:55:17Z" level=info msg="stderr=[ERROR: [095]: unable to verify certificate presented by 'test-db-backup.s3.eu-central-1.wasabisys.com:443': [19] self signed certificate in certificate chain\n]"
time="2020-02-07T22:55:17Z" level=error msg="command terminated with exit code 95"
```

**Comment by iboware** [comment]
I can backup to Google Cloud Storage with S3 interoperability, simply by aws-cli. I thought you're using the same API so I can backup to GCS with pgbackrest. First error I got was the one above, which is about certificate. I tried to disable certificate validation but the flags were blacklisted. Then I simply removed the contents of certificate file and tried it again. This time It said API was not implemented. It's probably because of lacking path style URI support. It seems to me that current S3 backup implementation forcing us to use only Amazon S3 storage, but there are many other backends compatible with S3 API. Can you please help?

**Comment by GeorgFleig** [comment]
I managed to do some progress with my issue. Looking at the postgres log file inside the pod, located at `/pgdata/<cluster_name>/pg_log/postgresql-Wed.log` helped me to further understand the problem.

```
ERROR: [049]: unable to load info file '/backrestrepo/pgs3-backrest-shared-repo/archive/db/archive.info' or '/backrestrepo/pgs3-backrest-shared-repo/archive/db/archive.info.copy':
       HostConnectError: raised from remote-0 protocol on 'pgs3-backrest-shared-repo': unable to get address for 'prod-k8s-pg1.minio.XXX.net': [-2] Name or service not known
```

Turns out pgbackrest is by default using host-based paths (as @iboware also pointed out) while minio uses directories.  Example:
- pgbackrest default: `bucket.endpoint`
- minio default: `endpoint/bucket`

Both tools can be configured to use the other option:
- https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-uri-style
- https://docs.min.io/docs/minio-server-configuration-guide.html (section Domain)

While pgbackrest can be configured to use URI path style, it is not (yet) possible with the postgres operator, see: https://github.com/CrunchyData/postgres-operator/issues/1239

Besides the path style issue it turned out that even though I am using a valid certificate for the minio endpoint, the postgres operator only uses a single CA to verify the certificate. This CA is by default the one AWS uses to sign their S3 endpoint certs. So make sure to provide the proper CA in `aws-s3-ca.crt` before deploying the pgo or directly in the `<cluster_name>-backrest-repo-config` secret when creating the cluster via a CRD.

@eminden make sure to put the CA of your self-signed cert into the file/secret.

**Comment by jkatz** [comment]
This was added as part of #1365 and is available as of v4.3.0-beta.1

**Comment by GeorgFleig** [comment]
Happy to hear v4.3.0 is on its way. Thanks for all the work on the new release!

If I understand the contents of https://github.com/CrunchyData/postgres-operator/pull/1365 correctly, this particular issue is not fixed as it requires to be able to set the path style during cluster creation, not just for a manually triggered backup. Please correct me if I'm mistaken here.

**Comment by jkatz** [comment]
Ah correct. Reopening.

**Comment by yaroslavkasatikov** [comment]
Hello team,

Sorry, I'm a bit confused.
Is path-style s3 repo flag  while cluster created already released? 
If yes, could you please shared details (or link to doc) how to use this feature?

Thanks,
Yaroslav

**Comment by ron1** [comment]
@jkatz Is this fixed in 4.3.1?

**Comment by jkatz** [comment]
@ron1 This is not in 4.3.1, but is an open ticket for our next release.

**Comment by ron1** [comment]
@jkatz Do you expect this to be resolved in a 4.3.x patch release or is it only scheduled for 4.4?

**Comment by asoltesz** [comment]
@jkatz I second the question of @ron1.

**Comment by jkatz** [comment]
It is in consideration for 4.4 as it involves an API change.

**Comment by jkatz** [comment]
I am pleased to report that this will be in 4.4.0.
