### ISSUE TITLE
Impossible to overwrite some properties of postgresql.conf

### ISSUE THREAD

**Issue by aurelienmarie** [CrunchyData/postgres-operator#1230]
**Describe the bug**
We wanted to try the custom-config example given in oder to have a custom postgresql.conf. The example use 3 PostgreSQL parameters but they are ignored during the creation of a new cluster. 

**To Reproduce**
1. `export PGO_NAMESPACE=pgouser1`
2. `./example/create.sh` it will create the pgo-custom-pg-config
3. `pgo create cluster mycluster -n pgouser1 --custom-config=pgo-custom-pg-config`
4. `pgo show cluster -n pgouser1 mycluster` and ensure the following label is  written: " custom-config=pgo-custom-pg-config"
5. ` kubectl exec -it -n pgouser1 mycluster-595b548499-n964m -- bash`
6. Once in the pod, you can execute psql in order to verify postgresql configuration: ` psql -c "show work_mem;"`

**Expected behavior**
According to the example, the `psql -c "show work_mem;"` should return a **5MB** value but it gives a **4MB**.

As we can see, the `/pgdata/mycluster/postgresql.conf` contains an include to the custom postgresql.conf. However, as it is placed at the beginning of the file, our custom parameter get overwritten by the standard parameter.

If placed at the end of the file, and the conf is reloaded, we have the right configuration. See below.

**Screenshots**
Cluster description
```
pgo show cluster -n pgouser1 mycluster      

cluster : mycluster (crunchy-postgres-ha:centos7-12.1-4.2.0)
        pod : mycluster-595b548499-n964m (Running) on minikube (1/1) (primary)
        pvc : mycluster
        resources : CPU Limit= Memory Limit=, CPU Request= Memory Request=
        storage : Primary=1G Replica=1G
        deployment : mycluster
        deployment : mycluster-backrest-shared-repo
        service : mycluster - ClusterIP (10.96.29.52)
        labels : pg-pod-anti-affinity= pgo-backrest=true pgo-version=4.2.0 current-primary=mycluster pgouser=pgoadmin autofail=true crunchy-pgbadger=false crunchy_collect=false name=mycluster workflowid=4f176766-a283-444c-be58-0d5c3eeabd5d deployment-name=mycluster pg-cluster=mycluster archive-timeout=60 crunchy-pgha-scope=mycluster custom-config=pgo-custom-pg-config
```
Include change and reloading the configuration
```
PS C:\Users\amarie> kubectl exec -it mycluster-595b548499-n964m -n pgouser1 -- bash
bash-4.2$  psql -c "show work_mem;"
 work_mem
----------
 4MB
(1 row)

bash-4.2$ vi /pgdata/mycluster/postgresql.conf
bash-4.2$ cat /pgdata/mycluster/postgresql.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
#include '/pgconf/postgresql.conf'

archive_command = 'source /tmp/pgbackrest_env.sh && pgbackrest archive-push "%p"'
archive_mode = 'True'
cluster_name = 'mycluster'
hot_standby = 'on'
listen_addresses = '0.0.0.0'
log_directory = 'pglogs'
log_min_duration_statement = '0'
log_statement = 'none'
logging_collector = 'True'
max_connections = '100'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '6'
max_worker_processes = '8'
port = '5432'
shared_buffers = '128MB'
shared_preload_libraries = 'pgaudit.so'
temp_buffers = '8MB'
track_commit_timestamp = 'off'
unix_socket_directories = '/tmp,/crunchyadm'
wal_keep_segments = '8'
wal_level = 'replica'
wal_log_hints = 'on'
work_mem = '4MB'
hba_file = '/pgdata/mycluster/pg_hba.conf'
ident_file = '/pgdata/mycluster/pg_ident.conf'

include '/pgconf/postgresql.conf'
bash-4.2$ psql -U postgres -c "SELECT pg_reload_conf();"
 pg_reload_conf
----------------
 t
(1 row)
bash-4.2$  psql -c "show work_mem;"
 work_mem
----------
 5MB
(1 row)
```

**Please tell us about your environment:**

* Where is this running ( Local, Cloud Provider): Minikube
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: 4.2.0
* PostgreSQL Version: 12.1
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.17.0

**Comment by jkatz** [comment]
@aurelienmarie This is related to #1193

**Comment by aurelienmarie** [comment]
Oh thanks @jkatz ! i haven't spotted that one. I'll close as it's kind of duplicated then !
