### ISSUE TITLE
Replicas not in sync after point-in-time restore

### ISSUE THREAD

**Issue by GeorgFleig** [CrunchyData/postgres-operator#1231]
**Describe the bug**
I followed the instructions of the blog post describing the point-in-time recovery with a cluster with 2 replicas: https://info.crunchydata.com/blog/pgbackrest-point-in-time-recovery-using-crunchy-postgresql-operator

After the first restore the data is recovered correctly and present on both replicas. Replication is working as expected:

```
postgres=# select * from pg_stat_replication;
 pid | usesysid |   usename   |     application_name      |  client_addr   | client_hostname | client_port |         backend_start         | backend_xmin |   state   | sent_lsn  | write_lsn | flush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+-------------+---------------------------+----------------+-----------------+-------------+-------------------------------+--------------+-----------+-----------+-----------+-----------+------------+-----------+-----------+------------+---------------+------------
 904 |    16411 | primaryuser | pg3-xtdw-55845b79df-8sz8p | 192.168.240.45 |                 |       50184 | 2020-01-17 16:44:38.188032+00 |              | streaming | 0/7013F30 | 0/7013F30 | 0/7013F30 | 0/7013F30  |           |           |            |             0 | async
 920 |    16411 | primaryuser | pg3-lpij-7955748c5-9p94k  | 192.168.238.42 |                 |       52318 | 2020-01-17 16:44:46.231713+00 |              | streaming | 0/7013F30 | 0/7013F30 | 0/7013F30 | 0/7013F30  |           |           |            |             0 | async
(2 rows)
```

Then I continued the tutorial and did the restore again after a second full backup by defining the correct backup set using `--set=`. (I skipped the iteration where the backup set is not defined and the restore won't produce the desired result.)

After the restore is completed, the new primary contains the correct data. The two replicas however, restored the data to the latest point and are not syncing anymore with the primary.

```
postgres=# select * from pg_stat_replication;
 pid | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | backend_xmin | state | sent_lsn | write_lsn | flush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+---------+------------------+-------------+-----------------+-------------+---------------+--------------+-------+----------+-----------+-----------+------------+-----------+-----------+------------+---------------+------------
(0 rows)
```

The replicas seem to be ahead of the primary:

```
# primary
postgres=#    SELECT txid_current_snapshot();
 txid_current_snapshot
-----------------------
 585:585:
(1 row)
```

```
# replica
postgres=#    SELECT txid_current_snapshot();
 txid_current_snapshot
-----------------------
 590:590:
(1 row)
```

After adding some data to the primary, the lag becomes visible
```
+----------+---------------------------+-----------------+--------+---------+----+-----------+
| Cluster  |           Member          |       Host      |  Role  |  State  | TL | Lag in MB |
+----------+---------------------------+-----------------+--------+---------+----+-----------+
| pg3-dxck | pg3-dxck-55854c8c7b-dc2kp |  192.168.238.30 | Leader | running |  2 |           |
| pg3-dxck | pg3-lpij-69d5545554-gfxrr | 192.168.151.161 |        | running |  2 |       110 |
| pg3-dxck | pg3-xtdw-5d5f65c7f6-666gp |  192.168.44.59  |        | running |  2 |       110 |
+----------+---------------------------+-----------------+--------+---------+----+-----------+
```
The postgres pod logs don't indicate any problems.

Are there any manual steps required to get the cluster in sync again?

**Expected behavior**
Cluster should be in sync after point-in-time recovery.

**Please tell us about your environment:**

* Deployment method: ansible
* Operating System: Ubuntu 18.04
* Where is this running: Private cloud
* Storage being used: Ceph
* Container Image Tag: 4.2.0
* PostgreSQL Version: 11.6
* Platform (Docker, Kubernetes, OpenShift): k8s 1.15

Let me know if you need any additional debug information.

**Comment by kaoet** [comment]
I have the same issue in my cluster. The master is recovered to the correct time, but the replicas are out of sync.

**Comment by jkatz** [comment]
Newer versions of the Operator, particularly starting with 4.4.0 and improved upon in 4.5.0, handled PITR and other scenarios much better. I recommended reviewing the documentation around the various methods and strategies you can invoke:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/)
