### ISSUE TITLE
pgo clone multi-namespace

### ISSUE THREAD

**Issue by lgarcia11** [CrunchyData/postgres-operator#1232]
Is it possible to pgo clone from one namespace to another? Is there any examples?
I'm using operator version 4.2.0,

**Comment by jkatz** [comment]
@lgarcia11 Not yet, but that is a feature we intend to add in the future!

The goal of `pgo clone` if 4.2 was to see if a) anyone would use it and b) if they use it, what would they want to do with it...which you are helping to validate with your question 😉

**Comment by lgarcia11** [comment]
Great, yes I think it will be very useful, the use case that I was thinking was to have a CI/CD pipeline do testing with data from a prod cluster but in a different namespace to keep production namespace isolated.

**Comment by jkatz** [comment]
@lgarcia11 Seems pretty reasonable 😉 

What would a CLI flag look like that makes sense?

- `--into-namespace`
- `--new-cluster-namespace`
- ` --new-namespace`
- `--clone-namespace`
- other?

**Comment by lgarcia11** [comment]
@jkatz I personally like the third option, 

> pgo clone oldcluster newcluster --namespace oldns --new-namespace newns

**Comment by jkatz** [comment]
Superseded by #2062
