### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by Toasterson** [CrunchyData/postgres-operator#1233]
In the Documentation under https://access.crunchydata.com/documentation/postgres-operator/4.2.0/pgo-client/common-tasks/

The create backup commands are out of date.
`pgo create backup $CLUSTER` should be `pgo backup $CLUSTER -n $NAMESPACE`

In general `-n $NAMESPACE` needs to provided for every command now acording to the cli.

**Comment by jkatz** [comment]
Hi @Toasterson,

This is covered [here](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#general-notes):

> For convenience, we will use the pgouser1 namespace in the examples below. For even more convenience, we recommend setting pgouser1 to be the value of the `PGO_NAMESPACE` variable. In the shell that you will be executing the pgo commands in, run the following command:
> 
> ```shell
> export PGO_NAMESPACE=shell
```
> If you do not wish to set this environmental variable, or are in an environment where you are unable to use envirionmental variables, you will have to use the --namespace (or -n) flag for most commands, e.g.
> 
> ```pgo version -n pgouser1```

Though as I type that, I realize there are a few typos in that statement.

I would be willing to

1. Fix said typos
1. Move and/or include that section in the previous page of the documentation (the overview)

but I believe for brevity it's much easier to **not** include `-n` on every single command to allow them to be copy and pasteable per using the above guidance.

**Comment by Toasterson** [comment]
Ah I see what the intention is. Could you add setting up PGO_NAMESPACE environment variable to the Quickstart guide like the rest of the environment? When I follow the Quickstart guide I won't leave the Quickstart page thus not see this until I do some advanced tasks.

I agree that adding -n to every command is too much.

**Comment by jkatz** [comment]
@Toasterson First round of changes made.

A good point on the quickstart. I'll sneak it in there, given it appears we reference `-n pgouser1` plenty in it.

**Comment by jkatz** [comment]
@Toasterson See #1235 and please let me know what you think. Thanks!

**Comment by Toasterson** [comment]
Wonderfull that fixes the -n thing. Have you had a look at the the `pgo create backup` command aswell? That command does not exist. I started a backup with `pgo backup`

**Comment by jkatz** [comment]
@Toasterson Yes, the name of the command is currently `pgo backup`, not `pgo create backup`.

**Comment by Toasterson** [comment]
Will that change? Because in the Documentation it is `pgo create backup`

**Comment by jkatz** [comment]
@Toasterson Somehow I missed that in my first read of the ticket. Anyway it's now fixed.

Thanks for your suggestions!
