### ISSUE TITLE
Custom config will replace stream replication feature

### ISSUE THREAD

**Issue by yummydsky** [CrunchyData/postgres-operator#1238]
**Describe the bug**
I use pgo v4.1.1 to create cluster via following steps
`pgo create cluster pgo-cluster --replica-count=5 --metrics -n pgouser1`
`pgo create pgpool pgo-cluster -n pgouser1`

Then I connect to pgpool to CREATE a database, I can see database has been replicated to replica pod successfully.
But when I create the cluster with custom config
`pgo create cluster pgo-cluster --replica-count=5 --metrics --custom-config pgo-custom-pg-config -n pgouser1`
`pgo create pgpool pgo-cluster -n pgouser1`
This time I also create database in pgpool pod, but I can not see anything in replica pod.

I found out that the /opt/cpm/bin/start.sh will configure archiving before replacing custom config, that may be the root cause.

/opt/cpm/bin/start.sh
```
    451 configure_archiving
    452 
    453 source /opt/cpm/bin/custom-configs.sh
```

**To Reproduce**
go to example/custom-config
`./create.sh`
`pgo create cluster pgo-cluster --replica-count=5 --metrics --custom-config pgo-custom-pg-config -n pgouser1`
`pgo create pgpool pgo-cluster -n pgouser1`

**Expected behavior**
Stream replication behavior should be applied after copy custom config

**Please tell us about your environment:**

* Operating System: CentOS 7.6
* Where is this running ( Local, Cloud Provider) Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos7-4.1.1
* PostgreSQL Version: v4.1.1
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 3.17

**Additional context**

**Comment by jkatz** [comment]
Hi @yummydsky,

Please see #1193 

Also note this won't be adjusted in the 4.1 line, but in 4.2 or later. We changed the mechanics of how we are supporting replication as of [v4.2](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0) and are going to continue supporting that methodology.

Additionally, we have dropped pgpool from support. If you require connection pooling, please use `--pgbouncer`.

Thanks!
