### ISSUE TITLE
pgbackrest s3 path-style support

### ISSUE THREAD

**Issue by strantalis** [CrunchyData/postgres-operator#1239]
**Describe the solution you'd like**
We currently utilize ceph object storage gateway which has an s3 compatible api. The issue I seem to be running into when utilizing the pgbackrest s3 option is we do path-style for buckets.

Ex. https://s3.example.com/<bucket> 

It seems there is an option in pgbackrest which can be set to enable that type of interaction but is currently not exposed through the operator.

https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-uri-style 

**Please tell us about your environment:**

* Where is this running ( Local, Cloud Provider) Private Cloud
* Storage being used (NFS, Hostpath, Gluster, etc): 
* Container Image Tag: centos7-12.1-4.2.0
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Openshift/Kubernetes
* Platform Version: 4.2/1.14

**Comment by jkatz** [comment]
@strantalis Have you tried passing in the options via the ` --backup-opts` flag for `pgo backup` or the `--schedule-opts` flag for `pgo create schedule`? These allow you to pass in variable options for pgBackRest, e.g.

`pgo backup --backup-opts="--repo1-s3-uri-style=path" ... `

**Comment by strantalis** [comment]
Looks like that functionality was added in [v2.21](https://github.com/pgbackrest/pgbackrest/releases/tag/release%2F2.21)  of pgbackrest and the postgres-operator is currently on v2.20 it seems.

**Comment by jkatz** [comment]
@strantalis Got it. So you will have to wait until we update to 2.22, which could occur in the next minor update (~mid Feb 😉) based on testing.

Thanks!

**Comment by strantalis** [comment]
@jkatz If a flag is supported in pgbackrest should they all work with --backup-opts as long as its within the version used by the operator?

Example 

```
pgo backup test-db -n test-namespace --pgbackrest-storage-type=s3 --backup-opts="--repo1-s3-verify-tls=n" 
Error: unknown flag: --repo1-s3-verify-ssl
```

https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-verify-tls

**Comment by jkatz** [comment]
@strantalis Yes, most flags that are supported by pgBackRest should work. However, there are certain flags that are disallowed, which you can view here:

https://github.com/CrunchyData/postgres-operator/blob/master/apiserver/backupoptions/pgbackrestoptions.go#L23-L30

The predecessor to `--repo-s3-verify-tls`, `--repo-s3-verify-ssl` happens to be on that list. However, I see no reason why it needs to be on that least, and likely this is relatively easy to modify.

**Comment by iboware** [comment]
I am having the same problem with Google Cloud Storage. GCS is S3 Interoperable, so I can use aws-cli to manage it, simply upload or download files. Lack of path style support is blocking me from using GCS as S3 backup storage. Is there a way to configure it currently?

**Comment by GeorgFleig** [comment]
@jkatz thanks for pointing out that the flag could be passed to the `pgo backup` command. However, there seems to be no way to pass it during cluster creation so wal archiving via pgbackrest will work. Or am I missing something?

**Comment by dejwsz** [comment]
Is it possible to pass "--repo-s3-uri-style=path" option during cluster creation? I think this is a very important feature to add. Many s3 compatible API use path-based URL instead of a host type. I need it too so I am voting to add support for it.

**Comment by jkatz** [comment]
@dejwsz It requires pgBackRest 2.21 support or above, which will come out in the next release. We just merged in support for pgBackRest 2.24, and from there can add in the flag.

**Comment by dejwsz** [comment]
Super!

**Comment by jkatz** [comment]
This was added by #1365 and is available starting with 4.3.0-beta.1

**Comment by asoltesz** [comment]
@dejwsz: Did you manage to set this? 

I couldn't use the flag on 4.3.0-beta.2 neither with pgo backup (backup-opts: unkown flag: --repo(1)-s3-uri-style) nor at cluster creation time (also, unknown flag).

@jkatz: How can we set this parameter at cluster creation or backup time? Could you give us an example command perhaps?

**Comment by asoltesz** [comment]
The reason it didn't work for me because my Ansible inventory file still referenced 4.2.2 versions. I had to update it to the 4.3.0-beta.2 inventory.

However, with the "4.3.0" versions, I get ImagePullBackoff errors + there are no such tags on Docker HUB.

@jkatz From where can one get the 4.3.0 beta images?
