### ISSUE TITLE
Some new features not documented

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/postgres-operator#124]
> You can turn off Basic Authentication entirely if you set the BasicAuth setting in the pgo.yaml configuration file to false.

This is the only mention made of BasicAuth in operator-docs.asciidoc. It should be included as an optional pgo.yaml file in the table along with a description.

> a confirmation for deletion commands allowing the user a final check before removing clusters or backups, users can override this with a --no-prompt command flag in the pgo client

This was mentioned in the release updates, but it's not documented.

> Debug:  true

This value is in pgo.yaml, but is not documented as one of the pgo.yaml values in the table.

**Comment by jmccormick2001** [comment]
thanks, merged into pre26 branch.
