### ISSUE TITLE
Postgres-ha replicas creation

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#1240]
**Describe the bug**
New approach for replica creation highly depends on 2 batch jobs succeed - stanza-create\ backup.
If anything goes wrong with those two - there's no usable way to retry/restart these jobs to get replicas created.

Possible scenarios:
1. Stanza creation fails with - ```unable to upgrade connection: container not found (\"database\")``` - seems like stanza-creation had started before database container became ready. not sure how to reproduce. it just happens from time to time
2. S3 pgbackrest - stanza creation fails - e.g. wasn't cleaned up and there's no `--force` anymore

**Expected behavior**
Retry or forced retry mechanics

**Please tell us about your environment:**

* Operating System: centos
* Where is this running ( Local, Cloud Provider): AWS
* Storage being used (NFS, Hostpath, Gluster, etc): EBS
* Container Image Tag: 10.11-4.2.1
* PostgreSQL Version: 10
* Platform (Docker, Kubernetes, OpenShift): OpenShift 3.11
* Platform Version: 3.11

**Additional context**
Operator 4.2.1 version

**Comment by lkhomenk** [comment]
ATM only manually created batch jobs would help

**Comment by jkatz** [comment]
@lkhomenk You mean the two jobs that run when a cluster is initially created, correct?

**Comment by lkhomenk** [comment]
yes. those 2 jobs

**Comment by jkatz** [comment]
@lkhomenk I believe we can optimize this and add some retry logic at some point, but the best bet right now is to delete and re-create the cluster.

We'll work on making it easier in the future.

**Comment by jose-joye** [comment]
@jkatz 
Any news on this?
We are also seeing this behavior (about 15% of cluster creation are failing due to this issue).

As you said a retry mechanism will do the job since the database container always come up but seems to have a hard time during its birth....

A simple retry within pgo-backrest.go for `COMMAND = crv1.PgtaskBackrestStanzaCreate` will fix the issue.

José

**Comment by jkatz** [comment]
@jose-joye When you've run into this, by chance did the PostgreSQL primary Pod crash? And if yes, do you have those logs?

The stanza create only gets kicked off once the PostgreSQL primary is up. It's possible that it crashed in between that and the stanza creation kick off.

The "fix" I have in mind is fairly easy (i.e. just retrying the failed stanza create) but I want to better understand what is causing it to fail.

Thanks!

**Comment by jkatz** [comment]
I've went ahead and changed the `retryPolicy` to `OnFailure` as this seems to treat symptomatically what's going on. The failures I've seen are over a range but are almost entirely transient errors, which makes sense in the :cloud: This should help at least with risk mitigation.

**Comment by jose-joye** [comment]
@jkatz :  Nice fix !

I just reproduced the error on our prod environment

We had no pod crash. Just a bit of delay.
To me, your fix should make everything smooth regarding this topic.
However, I could provide you some log in case you want to get more information.

José

**Comment by jkatz** [comment]
Thanks @jose-joye -- good to know.

Yeah, it seems to be transient, networking-ish errors. The interesting bit is we are establishing connections directly to the Pod IPs, so curious why we're hitting the issue.
