### ISSUE TITLE
Scaling a cluster doesn't deploy new pods; spams errors in log

### ISSUE THREAD

**Issue by daanemanz** [CrunchyData/postgres-operator#1256]
**Describe the bug**
Scaling a cluster does not actually scale the number of pods in the deployment, while still listing the replicas in `pgo show cluster`. I also wasn't able to remove replicas from the cluster with `pgo scaledown`.

In the meantime, while checking the logs of the earlier deployed pod, I'm seeing these logs:
```
2020-01-29 18:34:39,795 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 273, in _load_cluster
    self._wait_caches()
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 267, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2020-01-29 18:34:39,796 WARNING: Exception happened during processing of request from 127.0.0.1:56266
2020-01-29 18:34:39,796 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 273, in _load_cluster
    self._wait_caches()
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 267, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 145, in do_GET_config
    cluster = self.server.patroni.dcs.cluster or self.server.patroni.dcs.get_cluster()
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 634, in get_cluster
    cluster = self._load_cluster()
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 340, in _load_cluster
    raise KubernetesError('Kubernetes API is not responding properly')
patroni.dcs.kubernetes.KubernetesError: 'Kubernetes API is not responding properly'

2020-01-29 18:34:39,812 ERROR: ObjectCache.run ApiException()
2020-01-29 18:34:39,831 ERROR: ObjectCache.run ApiException()
2020-01-29 18:34:39,851 ERROR: ObjectCache.run ApiException()
2020-01-29 18:34:39,871 ERROR: ObjectCache.run ApiException()
2020-01-29 18:34:39,891 ERROR: ObjectCache.run ApiException()
[...]
2020-01-29 18:34:44,295 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 273, in _load_cluster
    self._wait_caches()
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 267, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2020-01-29 18:34:44,295 ERROR: Error communicating with DCS
2020-01-29 18:34:44,296 INFO: DCS is not accessible
2020-01-29 18:34:44,298 WARNING: Loop time exceeded, rescheduling immediately.
2020-01-29 18:34:44,312 ERROR: ObjectCache.run ApiException()
2020-01-29 18:34:44,335 ERROR: ObjectCache.run ApiException()
```

**To Reproduce**
1. Install `postgres-operator`
2. Create a cluster
3. Scale the cluster up and/or down

**Expected behavior**
Deployment scales to multiple pods when scaling up, removes replicas when scaling down. The log does not get spammed with error messages.

**Screenshots**
N/A

**Please tell us about your environment:**
* Operating System: *Ubuntu 18.04*
* Where is this running: *Local, minikube*
* Storage being used: *Hostpath*
* Container Image Tag: *crunchydata/crunchy-postgres-ha:centos7-12.1-4.2.0*
* PostgreSQL Version: 
* Platform (Docker, Kubernetes, OpenShift): *Kubernetes, Minikube*
* Platform Version: *1.15.3*

**Additional context**
We're seeing similar issues with a PG cluster deployed on a cloud provider.

**Comment by jkatz** [comment]
Hi @daanemanz,

The error indicates that your primary Kubernetes API is unreachable:

`patroni.dcs.kubernetes.KubernetesError: 'Kubernetes API is not responding properly'`

This is used as the backing for the [distributed consensus store to manage high-availability](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/).

Please check your networking and your deployment environment for issues.

Thanks!

**Comment by jkatz** [comment]
Here was a similar issue and resolution specific to a Minikube environment: https://github.com/CrunchyData/postgres-operator/issues/1234#issuecomment-576715060

**Comment by daanemanz** [comment]
@jkatz Thanks for pointing me in that direction. Upon further inspection the Kubernetes API should be accessible to the pod. Could this be an RBAC issue - does the running pod need access to resources in the Kubernetes API that it currently doesn't have?

**Comment by jkatz** [comment]
@daanemanz Each Pod does have a ServiceAccount associated with it, and the permissions should all be set up from the installer.

Which leads to my next question, how did you install the Operator?

**Comment by daanemanz** [comment]
@jkatz I installed the operator using Ansible, which worked great with only a few modifications. I can see that the pod received the `pgo-pg` service account which was installed using the operator.

**Comment by jkatz** [comment]
OK, so that will set up all the RBAC needed.

So drilling down further:

`2020-01-29 18:34:44,296 INFO: DCS is not accessible`

Ensure the Kubernetes DCS is up and accessible from the Pod :smile:

**Comment by daanemanz** [comment]
Excuse my ignorance but... how do I check that?

**Comment by andrewlecuyer** [comment]
Do you see any `configMaps` created in the namespace the PG cluster is being created in?  For instance, for a cluster named `mycluster1` created in namespace `pgouser1`, you would see `configMaps` such as those in the following output (which essentially comprise the DCS):

```bash
$ kubectl get cm -n pgouser1
NAME                             DATA      AGE
mycluster1-config                0         4h
mycluster1-leader                0         4h
...
```

If not (and based on the errors you posted), then I am assuming the primary pod is unable to contact the Kubernetes API as needed to initialize the cluster (e.g. to create the `configMaps` above).  To test this you can attempt to access the Kuberentes API via `curl` from within the primary PG pod that is currently unable to initialize, e.g. as follows (be sure to replace the pod name and namespace as needed for your environment):

```bash
kubectl exec -it mycluster1-69df55d8d4-4x496 -n pgo -- \
  curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
  "https://kubernetes.default.svc/api/"
```

If the request is successful, you should see a response such as the following:

```json
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "master:8443"
    }
  ]
}
```

Otherwise if not, it would appears as though there is a networking issue within your Kubernetes cluster that is preventing the PG pod from successfully accessing the Kubernetes API (which is needed to bootstrap and initialize the cluster).

**Comment by daanemanz** [comment]
@andrewlecuyer thanks for the help! Here's what I'm getting:
```
$ kubectl exec -ti testapp-pgcluster-7c449f4595-4dddb -n testing -- curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt "https://kubernetes.default.svc/api/"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

However that pod does have the right SA associated with it:
```
$ kubectl get pod testapp-pgcluster-7c449f4595-4dddb -o yaml | yq r - spec.serviceAccountName
pgo-pg
```

**Comment by jkatz** [comment]
Reviewing this again and looking at the Patroni code, this sounds like a problem with the Kubernetes cluster where Patroni is unable to reach some of the Kubernetes backed services. As mention upthread, it could be RBAC related, but based on the feedback coming in I can't tell which RBAC rules are needed, and likely it seems like it's RBAC from the administrative level,as the Operator includes the ServiceAccounts + RBAC need to run.
