### ISSUE TITLE
Change DefaultContainerResources for a running cluster

### ISSUE THREAD

**Issue by dvianello** [CrunchyData/postgres-operator#1268]
** Which example are you working with? **
N/A

**What is the current behavior?**
Seem unable to change DefaultContainerResources (or any parameter in the definition of a cluster) after creation.

**What is the expected behavior?**
Runtime changes, i.e.: 
 - I want to vertically scale a pod (say, from 1 vCPU 1 GB RAM to 4 vCPUs 4 GBs RAM)
 - enable S3 backups after creation

**Other information** (e.g. detailed explanation, related issues,  etc)
N/A

**Please tell us about your environment:**

* Operating System: 
* Where is this running ( Local , Cloud Provider): Cloud provider
* Storage being used (NFS, Hostpath, Gluster, etc): VMware 
* Container Image Tag: `centos7-12.1-4.2.1`
* PostgreSQL Version: `4.2.1`
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16.3

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName
N/A.

--- 
My PostgreSQL knowledge is quite small, so maybe I'm missing the obvious reason why vertical scaling - or changing any runtime property as mentioned above - isn't possible. 

Apologies in advance for the very probably noob question I've just asked!

**Comment by jkatz** [comment]
@dvianello Thanks for your ticket. This is already something we are looking into adding into the next release! Your use-case certainly helps us to understand what would be a good workflow to add it.

**Comment by dvianello** [comment]
Hi @jkatz, 

thanks for the quick reply! And great news you're already thinking about this - what's your usual release cycle?

**Comment by jkatz** [comment]
@dvianello Our aim is to get MINOR releases (MAJOR.MINOR.PATCH) out once a quarter, where MINOR releases have new features, typically end-of-quarter.

`PATCH` releases (bug fixes, software version updates) come out as needed, but we try to time it with the PostgreSQL update releases.

**Comment by jkatz** [comment]
#1378 should resolve this.
