### ISSUE TITLE
Validation Mechanisms when working Directly with CRDs

### ISSUE THREAD

**Issue by moshloop** [CrunchyData/postgres-operator#1269]
The pgo apiserver currently handles all validation inline, validation should be handled via the core kubernetes apiserver using a ValidatingAdmissionWebhook to more closely follows operator & CRD best practises.

Related to #847

**Comment by jkatz** [comment]
Hi @moshloop,

RE utilizing the [ValidatingAdmissionWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook)

Presently we are supporting Openshift 3.11 which is based on Kubernetes 1.11 so as such using the ValidatingAdmissionWebhook is not in our plans at this time. I do agree that we need to provide some better ways to validate when interacting directly with the CRDs and that is already in our plans.

While Operators have matured, we're still in the nascent stages of defining what the "best practices" are and we are doing our best to adopt what it appears people are standardizing around.

I'm retitling the ticket to reflect the overall nature of your request.

Thanks!

**Comment by jkatz** [comment]
PGO 5.0 uses CRD v1, which provides a validation layer. This is now addressed.
