### ISSUE TITLE
Move the standalone apiserver to a kubernetes api extension

### ISSUE THREAD

**Issue by moshloop** [CrunchyData/postgres-operator#1270]
This would eliminate the need for separate TLS and RBAC to be implemented and kubernetes standard RBAC can be used instead.

**Comment by jkatz** [comment]
Hi @moshloop,

We are not going to do this. We researched building an Aggregated API and determined that the efforts we would have to set up would not make sense, especially given we want to focus more on solving the desired workflow raised #847 

Thanks,

Jonathan

**Comment by jkatz** [comment]
I am going to upgrade this to "forseeable future" -- but our main focus will be on the CR-only workflow described in #847
