### ISSUE TITLE
Move scaling logic to scale sub-resource

### ISSUE THREAD

**Issue by moshloop** [CrunchyData/postgres-operator#1272]
This would allow the native `kubectl scale` command to be used

**Comment by jkatz** [comment]
In PGO 5.0, scaling a cluster is handled through modification of the `postgrescluster` custom resource (e.g. [https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/create-cluster/](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/create-cluster/)). As there are different topologies of Postgres clusters that can be created, we do not have plans to use `kubectl scale` at the moment.
