### ISSUE TITLE
Merge Pgtasks directly into status sub-resources

### ISSUE THREAD

**Issue by moshloop** [CrunchyData/postgres-operator#1273]
This provides a much more logical way of check the status of an operation.

Operations that require multiple tasks e.g. Cluster provisioning can use a state machine on a status or phase field. 

e.g. when phase is empty,  update phase to CreatingInitalBackup and start the operation, when x is done update phase to CreatedInitialBackup, and start the next operation etc...

This type of model is used very successfully by the ClusterAPI project which has many operations that need to occur on individual objects, and other objects that need to wait for task completion before continuing.

**Comment by jkatz** [comment]
Hi @moshloop,

We have plans to phase at pgtasks but it will take some time.

Thanks!

**Comment by jkatz** [comment]
pgtasks is obsoleted in 5.0.
