### ISSUE TITLE
Deletion of backup not working

### ISSUE THREAD

**Issue by aurelienmarie** [CrunchyData/postgres-operator#1274]
**Describe the bug**
The ability to delete a backup using `pgo delete backup` is not working. Creating a backup result in a pgtasks and as a result the pgbackup crd is not used. 

I've found documentation stating [the pgbackup will be deprecated](https://crunchydata.github.io/postgres-operator/3.5.2/design/) but it looks like the `pgo delete backup` as not been updated/deprecated accordingly.

**To Reproduce**
1. `pgo backup ex1 -n pgouser1` gives following output `created Pgtask backrest-backup-ex1`
2. `kubectl get pgbackups.crunchydata.com -n pgouser1` gives no result
3.  `pgo show backup ex1 -n pgouser1` gives  an output and state of the backup
4.  `pgo delete backup ex1 -n pgouser1` result in error

**Expected behavior**
Be able to delete backup using pgo

**Additional context**
```
$ pgo show backup ex1 -n pgouser1

backrest : ex1

Storage Type: local
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1): 000000010000000000000001/000000010000000000000004

        full backup: 20200207-103929F
            timestamp start/stop: 2020-02-07 10:39:29 / 2020-02-07 10:40:27
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 31MB, backup size: 31MB
            repository size: 3.7MB, repository backup size: 3.7MB

        incr backup: 20200207-103929F_20200207-104317I
            timestamp start/stop: 2020-02-07 10:43:17 / 2020-02-07 10:43:36
            wal start/stop: 000000010000000000000004 / 000000010000000000000004
            database size: 31.1MB, backup size: 195KB
            repository size: 3.7MB, repository backup size: 17.5KB
            backup reference list: 20200207-103929F

$ pgo delete backup ex1 -n pgouser1
WARNING: Are you sure? (yes/no): yes
Error: pgbackups.crunchydata.com "ex1" not found

$ kubectl get pgbackups.crunchydata.com -n pgouser1
No resources found in pgouser1 namespace.
```

**Comment by jkatz** [comment]
Hi @aurelienmarie,

Starting from the [4.2.0 release notes](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0):

> Standardization of physical backups and restores on pgBackRest, with native support for pg_basebackup removed.

Physical backups are completely standardized around pgBackRest, which does *not* use the pgbackups.crunchydata.com CRD. A careful read of the docs shows that references to this CRD have been removed :wink: (I say this as a joke, given it's clearly confusing that I did not put in a deprecation notice).

In actuality, we could have removed the pgbackups.crunchydata.com CRD from the last release, and in fact I had started a patch to do so. However, based on the timing, we decided to leave it in, in case people were migrating away from using it and to not introduce too much change into the code.

So this comes back to the original question, how do you delete a backup from pgBackRest?

The way pgBackRest works with backup expiration is by setting a retention number on the backups. You can see this example here:

- [Setting Backup Retention](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#disaster-recovery-backups-restores#setting-backup-retention)
- [Disaster Recovery in the PostgreSQL Operator](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/)

So then, what is the point of `pgo delete backup`? It is used to delete the logical backups that are created via the `pgdump` option :smile:

We could probably make the `pgo delete backup` command a bit clearer and I will make a note of that., but I will mark this as closed as backup deletion does work, just differently than it did pre-4.2 :smile:

**Comment by aurelienmarie** [comment]
Hi @jkatz,

Thanks for your quick reply ! 

So from your comment, i understand that doing a `pgdump` backup would give me the opportunity to use the `pgo delete backup` command.

However, I dont have more results by doing accordingly.

```
$ pgo backup -n pgouser1 ex1 --backup-type pgdump
created Pgtask backup-ex1-pgdump

$ k logs -n pgouser1 backup-ex1-pgdump-xlkt-bp8gc
Thu Feb 27 14:56:21 UTC 2020 INFO: Waiting for PostgreSQL to be ready..
ex1:5432 - accepting connections
Thu Feb 27 14:56:21 UTC 2020 INFO: Checking if PostgreSQL is accepting queries..
              now
-------------------------------
 2020-02-27 14:56:21.691604+00
(1 row)

Thu Feb 27 14:56:21 UTC 2020 INFO: Dumping to -f /pgdata/ex1-backups/2020-02-27-14-56-21/dump
Thu Feb 27 14:56:21 UTC 2020 INFO: Taking logical backup of the postgres database..
Thu Feb 27 14:56:22 UTC 2020 INFO: Logical backup completed.  Exiting..

$ pgo delete backup -n pgouser1 ex1
WARNING: Are you sure? (yes/no): yes
Error: pgbackups.crunchydata.com "ex1" not found
```

As the `delete backup` is searching for a deprecated CRD, i am not really sure how it should work ?
