### ISSUE TITLE
pgo clone rsync failed: Operation not permitted

### ISSUE THREAD

**Issue by lgarcia11** [CrunchyData/postgres-operator#1285]
`pgo clone oldcluster newcluster --pgbackrest-storage-source="local"` fails with log message "rsync failed: Operation not permitted"
Is there any restriction for backrest and backup storage's. I'm using an Azure file volume mounted with options.

mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=1000
- gid=1000
- mfsymlinks
- nobrl
- cache=none

**Comment by jkatz** [comment]
@lgarcia11 Have you tried it without the `--pgbackrest-storage-source` parameter?

**Comment by lgarcia11** [comment]
@jkatz It is the same without the parameter.

**Comment by jkatz** [comment]
@lgarcia11 So there should not be special permissions required -- is it a case where the directories are owned by different users? I have not played around with Azure's volumes so I am not sure how they handle file ownership.

The rsync does require for the files to be owned by the same UID across PVCs and uses rsync via SSH. Is there a chance that SSH is being blocked?
