### ISSUE TITLE
benchmark - FATAL:  pg_hba.conf rejects connection for host "", user "primaryuser", database "postgres", SSL off

### ISSUE THREAD

**Issue by jsdevalx** [CrunchyData/postgres-operator#1287]
OKD(Openshift)/RHEL7 3.11
pgo client version 4.2.1
pgo-apiserver version 4.2.1

Default configuration. Changes only in storage area.

pgo benchmark mycluster -n pgouser1
Created benchmark task for mycluster
workflow id is 0b02d5c7-f1f2-45db-a952-2406706dbaf6

pgo show workflow 0b02d5c7-f1f2-45db-a952-2406706dbaf6 -n pgouser1
parameter           value
---------           -----
job completed       2020-02-14T08:23:05Z
pg-cluster          mycluster
task submitted      2020-02-14T08:23:01Z
workflowid          0b02d5c7-f1f2-45db-a952-2406706dbaf6

kubectl get pods -n pgouser1
NAME                                             READY     STATUS      RESTARTS   AGE
backrest-backup-mycluster-l9pmp                  0/1       Completed   0          23h
benchmark-mycluster-kuod-lhrvz                   0/1       Error       0          35s
mycluster-775457c849-9wbc2                       1/1       Running     0          1d
mycluster-backrest-shared-repo-5cb5df78d-j7q99   1/1       Running     0          1d
mycluster-dlre-86884b478f-2nlnz                  1/1       Running     0          1d
mycluster-stanza-create-cww87                    0/1       Completed   0          1d
mycluster-zygg-66f658b99f-mk2nj                  1/1       Running     0          1d

kubectl logs benchmark-mycluster-kuod-lhrvz -n pgouser1
connection to database "postgres" failed:
FATAL:  pg_hba.conf rejects connection for host "", user "primaryuser", database "postgres", SSL off

**Comment by jsdevalx** [comment]
"Fix" -> but it isn't elegant solution. There should be some change in code I suppose but I can't find it quickly.

Before on primary pod:
bash-4.2$ vi /pgdata/mycluster/pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
local all postgres peer
local all crunchyadm peer
host replication primaryuser 0.0.0.0/0 md5
host all primaryuser 0.0.0.0/0 reject
host all all 0.0.0.0/0 md5

After on primary pod:
bash-4.2$ vi /pgdata/mycluster/pg_hba.conf
 Do not edit this file manually!
# It will be overwritten by Patroni!
local all postgres peer
local all crunchyadm peer
host replication primaryuser 0.0.0.0/0 md5
host all primaryuser 0.0.0.0/0 md5
host all all 0.0.0.0/0 md5

./usr/pgsql-12/bin/pg_ctl reload -D /pgdata/mycluster/


And it works... Any suggestion where/how to fix it in code?

grep -r "host all primaryuser" *
examples/custom-config/postgres-ha.yaml:    - host all primaryuser 0.0.0.0/0 reject

**Comment by dejwsz** [comment]
I had the same problem today with operator version 4.2.2

**Comment by jkatz** [comment]
Hi,

For the customizations, you can add custom pg_hba.conf settings to the `postgres-ha.yaml` file so it can be added to the cluster and the DCS. We made a couple of changes in v4.3 to make it easier to create a custom `postgres-ha.yml` file that were introduced in (ab2fab06), but those are not available just yet :wink:

Additionally, `pgo benchmark` is being removed in v4.3 (265cdcd) though you can still use the `crunchy-benchmark` container to run benchmarks.

Thanks!
