### ISSUE TITLE
ArchivePVC in 4.2

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#1289]
** Which example are you working with? **
4.2 introduced pgbackrest as a default option. meaning
https://github.com/CrunchyData/postgres-operator/blob/fe9a8260234c13456eeb21e57020f24dcf08625e/operator/cluster/clusterlogic.go#L88 - will always disable ArchivePVC. 
This also makes https://github.com/CrunchyData/postgres-operator/blob/fe9a8260234c13456eeb21e57020f24dcf08625e/util/util.go#L164 useless.
But huge load on DB generates a lot of WAL -> IO load on main /pgdata volume.
There was an ArchiveStorage profile before 4.0.
Even if `wal_keep_segments = 0` in 4.2 postmaster overuses main data volume `/pgdata/clustename/pg_wal` with IOps
**What is the current behavior?**
No way to add volume for PGWAL. although https://github.com/CrunchyData/crunchy-containers/blob/906062e95ff7c09c81d8dc95a32bec921ba9ee7f/conf/postgres-ha/postgres-ha-waldir.yaml exists, there's no way to customize volume for xlog/pgwal
**What is the expected behavior?**
profile for `archiveStorage`
**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**
* Container Image Tag: centos7-10.11-4.2.1
* PostgreSQL Version: 10
* Platform (Docker, Kubernetes, OpenShift): 3.11
* Platform Version: 4.2.1

**Comment by jkatz** [comment]
@lkhomenk You must be psychic because this is already on the roadmap for 4.3 😄

**Comment by jkatz** [comment]
Closed by #1452
