### ISSUE TITLE
Minimum required version of ansible is wrong in the documentation

### ISSUE THREAD

**Issue by taypo** [CrunchyData/postgres-operator#1292]
**Describe the bug**
Minimum ansible version is specified as 2.5 in the documentation. I am on ansible 2.7.12. But when I try to install the operator, playbook fails with the following message:

```
fatal: [10.215.117.116]: FAILED! => {"changed": false, "msg": "Invalid options for assert: quiet"}
```

Checking the ansible documentation, I see the `quiet` option for `assert` is added at 2.8

**To Reproduce**
1. Just following the quickstart with ansible 2.7.12

**Comment by jkatz** [comment]
Hi @taypo,

Thanks for reporting! I've gone and made updates to remove the 2.8 specific feature and ensure compatibility (to the best of my abilities, with an assist from @cbandy) with 2.7.0+

Thanks!
