### ISSUE TITLE
missing pgo client 

### ISSUE THREAD

**Issue by obeyler** [CrunchyData/postgres-operator#1296]
**Describe the bug**
when install by ansible the version 4.3.0
https://github.com/CrunchyData/postgres-operator/releases/download/v4.3.0/pgo
not already present

**Comment by ajoyej** [comment]
are you sure you want the version 4.3.0. 
The latest version seems to be 4.2.2

José

**Comment by obeyler** [comment]
I've just clone the github repo and use the default value in inventory with this version

**Comment by jkatz** [comment]
@obeyler For `v4.2.2` please use the REL_4_2 branch:

https://github.com/CrunchyData/postgres-operator/tree/REL_4_2

Versioning is discussed here:

https://github.com/CrunchyData/postgres-operator/blob/master/CONTRIBUTING.md#releases--versioning

v4.3.0 is unreleased. The `master` branch is the unreleased code, whereas the `REL_` branches contain code that is released. We do try to commit things to `master` that are stable, so it "should work" (to borrow the old development phrase) but we do not make any of the containers or packages available yet.

Thanks!
