### ISSUE TITLE
pgo upgrade - question

### ISSUE THREAD

**Issue by jsdevalx** [CrunchyData/postgres-operator#1297]
Hi,

Could You explain me what is the proper way of upgrading cluster/database to higher version?

I understand that update from OPERATOR RELEASE 4.2.1(eg. POSTGRES 12.1) to OPERATOR RELEASE 4.2.2(eg. POSTGRES 12.2) is not a problem and after new operator install with the latest/default 4.2.2 tag database cluster just starts up with higher 12.2 version. Because it is major version. There is information about it in below document.
https://crunchydata.github.io/postgres-operator/4.2.2/upgrade/upgrade4xto42_ansible/
Once the Operator is installed and functional, create a new 4.2.2 cluster with the same name and using the same major PostgreSQL version as was used previously. This will allow the new clusters to utilize the existing PVCs.

But what if I want upgrade from 11.6(4.2.1 Operator) to 12.2(4.2.2 Operator)? Sould I use pgo upgrade with --ccp-image-tag for 12.2 version? So first step would be a start on new operator(4.2.2) cluster in newer 11.7 version and after that run pgo upgrade with --ccp-image-tag for 12.2 version? Am I right? Or maybe such a big change sholud be processed manually/traditionally using backup/restore on traditional/non-container system?

**Comment by jkatz** [comment]
A bunch of changes have been made to the upgrade procedure for [4.3.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.0). You can read about them here:

https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/

The short answer is, the process has been automated significantly :smile:
