### ISSUE TITLE
The ansible playbook for installing postgres-operator is not idempotent

### ISSUE THREAD

**Issue by lingxiankong** [CrunchyData/postgres-operator#1298]
**Describe the bug**
The ansible playbook for installing postgres-operator is not idempotent.

**To Reproduce**

I'm following https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/.

On the first run, I met with the docker image issue (can't find image crunchydata/pgo-scheduler:centos7-4.2.2), then I changed the config in inventory file:
```
pgo_image_tag='centos7-4.2.1'
```

Ran the command `ansible-playbook -i inventory --tags=install main.yml`, another error was raised:
```
TASK [pgo-operator : Create PGO Admin Credentials] *****************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/root/.pgo/pgo/output/pgouser-admin.yaml"], "delta": "0:00:00.205903", "end": "2020-02-23 23:43:59.619674", "msg": "non-zero return code", "rc": 1, "st
art": "2020-02-23 23:43:59.413771", "stderr": "Error from server (AlreadyExists): error when creating \"/root/.pgo/pgo/output/pgouser-admin.yaml\": secrets \"pgouser-admin\" already exists", "stderr_lines": ["Error from server (AlreadyE
xists): error when creating \"/root/.pgo/pgo/output/pgouser-admin.yaml\": secrets \"pgouser-admin\" already exists"], "stdout": "", "stdout_lines": []}
```

**Expected behavior**
The ansible task should be idempotent, and skip if the resource was already created.

**Screenshots**
None

**Please tell us about your environment:**

* Operating System: Ubuntu Bionic
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): OpenStack Cinder CSI
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.17.2

**Additional context**
None

**Comment by jamessewell** [comment]
Looks like you can use `--tags update` to get round this, but yeah - not very Ansibley

**Comment by jkatz** [comment]
Hi @lingxiankong and @jamessewell,

We're redesigning the installer for 4.3 to both eliminate the need for Ansible. In the process, we are updating the installer to help ensure it can be run idempotently.

For 4.2.2, please see #1293.

Thanks!

**Comment by ajoyej** [comment]
Hello
You mentioned that you want to get rid of ansible 
What will be the replacement?

Thanks
José
