### ISSUE TITLE
Provide a way to clean up postgres cluster and its associated kube components

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#131]
pgo delete cluster did not completely delete the cluster and put it in "Terminating State". It could not be deleted even with kubectl --force option.

This ticket is to create a mechanism to delete cluster and its associated kube components like secrets, configMap, pvcs, etc to be completely removed from the kubecluster.

**Comment by jmccormick2001** [comment]
I created a bash script in bin/manual-cleanup.sh that should be a good start...you pass it a command line argument of the cluster name:

./bin/manual-cleanup.sh mycluster
