### ISSUE TITLE
Permission denied when creating cluster

### ISSUE THREAD

**Issue by litaobowl** [CrunchyData/postgres-operator#1312]
I'm trying to create a pg cluster on GKE,
and got this error in the database pod after running 
**pgo create cluster mycluster**

kubectl logs mycluster-78cdfd6cb6-qzbks -n pgo
Mon Mar  2 19:51:20 UTC 2020 INFO: Setting PGROOT to /usr/pgsql-11.
Mon Mar  2 19:51:20 UTC 2020 INFO: The PGUSER secret exists.
Mon Mar  2 19:51:20 UTC 2020 INFO: The PGROOT secret exists.
Mon Mar  2 19:51:20 UTC 2020 INFO: The PGPRIMARY secret exists.
mkdir: cannot create directory '/pgdata/mycluster': Permission denied
chmod: cannot access '/pgdata/mycluster': No such file or directory

please help

**Comment by jkatz** [comment]
Unfortunately this does not provide much information. How did you install the Operator? Which version are you using?

The bug reporting template provides a good starting point for the information that you can provide to help:

--------

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
-----

Thanks!

**Comment by litaobowl** [comment]
Operating System:
**Ubuntu**
Where is this running ( Local, Cloud Provider)
**Google Cloud**
Storage being used (NFS, Hostpath, Gluster, etc):
**standard**
Container Image Tag:
**whatever 4.0.1 is using**
PostgreSQL Version:
**whatever 4.0.1 is using**
Platform (Docker, Kubernetes, OpenShift):
**Kubernetes**
Platform Version:
**1.14**

**Comment by jkatz** [comment]
@litaobowl Thanks. 4.0.1 can use different version of the `crunchy-postgres` container, so unfortunately this does not provide enough information. You can find the list of compatibility here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/)

Please be sure you're using the 2.4.1 `crunchy-postgres` container. It might work with 2.4.2, but that transition occurred right before I started working on the Operator.

That all said, we don't support 4.0.1 anymore. Please try updating to a newer version. You can find instructions on upgrading here:

- [https://access.crunchydata.com/documentation/postgres-operator/4.2.2/upgrade/upgrade4xto42_ansible/](https://access.crunchydata.com/documentation/postgres-operator/4.2.2/upgrade/upgrade4xto42_ansible/)
- [https://access.crunchydata.com/documentation/postgres-operator/4.2.2/upgrade/upgrade4xto42_bash/](https://access.crunchydata.com/documentation/postgres-operator/4.2.2/upgrade/upgrade4xto42_bash/)

Thanks!
