### ISSUE TITLE
Change resource limits in running cluster

### ISSUE THREAD

**Issue by dk-do** [CrunchyData/postgres-operator#1318]
**Which example are you working with?**
pgo client version 4.2.2
pgo-apiserver version 4.2.2

**What is the current behavior?**
I changed the resource limitations in pgo.yaml and deployed the operator again.
New created clusters get the new resource limitations.

**What is the expected behavior?**
Existing clusters, which are linked to the same resource limitation in pgo.yaml should get the new defined limitation. Maybe with "pgo reload..."

* Operating System: Ubuntu 18.04.4 LTS
* Where is this running: Local
* Storage being used: ROOK/CEPH on SSDs
* Container Image Tag: centos7-12.2-4.2.2
* PostgreSQL Version: psql (12.2)
* Platform: Kubernetes
* Platform Version: 15.5

**Comment by dejwsz** [comment]
Yes, this is an interesting issue. Is there any procedure for this now? Or can I just bump the postgres deployments limits up manually? Is this acceptable?

**Comment by dk-do** [comment]
I tested a little bit with different settings.
I think the only option is to apply the new limits to the operator and then clone the existing cluster to a new one.

**Comment by dejwsz** [comment]
I understand for existing DB it is enough to edit primary or replica deployment resource limits and then PODS are redeployed with new resource requests and limits (tested successfully). Of course, after this, all related PODs like backrest-shared-rep must be recreated.
The case is you may want to bump up only one selected DB cluster. "pgo update cluster" cannot do that as I understand? Maybe it would be useful if "pgo cluster update" can change resource limits and disk size and apply it.

**Comment by jkatz** [comment]
This is related to #1268 and it is something we are looking into doing for the next release!
