### ISSUE TITLE
expenv: command not found

### ISSUE THREAD

**Issue by prestonvanloon** [CrunchyData/postgres-operator#1325]
**Describe the bug**

```
/tmp/postgres-operator/deploy/install-bootstrap-creds.sh: line 32: expenv: command not found
/tmp/postgres-operator/deploy/install-bootstrap-creds.sh: line 32: create: command not found
/tmp/postgres-operator/deploy/install-bootstrap-creds.sh: line 39: create: command not found
/tmp/postgres-operator/deploy/install-bootstrap-creds.sh: line 39: expenv: command not found
```

**To Reproduce**
1. Go to https://operatorhub.io/operator/postgresql
2. Follow instructions
3. Fails at `$PGOROOT/deploy/install-bootstrap-creds.sh`

**Expected behavior**
No failure

**Please tell us about your environment:**

* Operating System: Linux Macbook13 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Where is this running ( Local, Cloud Provider): EKS
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by jkatz** [comment]
Please ensure you have the `expenv` binary installed, which you can find here for v4.2.1:

https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.1

Alternatively, you can try one of the other installation methods. I encourage you to try the quickstart, which uses Ansible:

[https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/)
