### ISSUE TITLE
namespace list config in ansible installer

### ISSUE THREAD

**Issue by dejwsz** [CrunchyData/postgres-operator#1328]
Version 4.2.2
Maybe it is a small bug or not?

If you use Ansible installer with a config having: 
namespace="testns1, testns2"      -> wrong
namespace="testns1,testns2"      -> good

If you have a space char after a comma in a list of namespaces then you will get such error in operator like below. If space char is removed then everything works well so space char is treated as a namespace first character probably.

time="2020-03-09 12:05:18 +0000" level=error msg="invalid namespace name format a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?') namespace name  testns2" func="main.main()" file="postgres-operator.go:79" version=4.2.2

**Comment by jkatz** [comment]
I doubt this will happen in the while unless someone is intentionally trying to break their inventory file, but  I've pushed a fix for this, and backpatched down to `REL_4_2`.

Thanks for reporting.
