### ISSUE TITLE
Query outside of K8s cluster

### ISSUE THREAD

**Issue by litaobowl** [CrunchyData/postgres-operator#1329]
How can I query the db from outside of the k8s cluster?
How do I change the init shared_buffer size or change it on the fly?
How to restart the cluster using pgo?
Also, for k8s which uses --kubeconfig option to reference the config file,
how to let ansible run k8s commands with that option too?
`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl config use-context kubernetes-admin@kubernetes", "delta": "0:00:00.083991", "end": "2020-03-09 13:16:31.017684", "msg": "non-zero return code", "rc": 1, "start": "2020-03-09 13:16:30.933693", "stderr": "error: no context exists with the name: \"kubernetes-admin@kubernetes\".", "stderr_lines": ["error: no context exists with the name: \"kubernetes-admin@kubernetes\"."], "stdout": "", "stdout_lines": []}`
this failed because it's not using `--kubeconfig /etc/kubernetes/admin.conf`

Thank you!

**Comment by jkatz** [comment]
> How can I query the db from outside of the k8s cluster?
This is up to your network administrator. You can set the PostgreSQL Operator to use a different service type by tweaking the `ServiceType` variable in the "pgo.yaml" file  (the default is `ClusterIP`) (which can also be edited in the `pgo-config` ConfigMap and related the Operator.

You would subsequently need to set up an Ingress. There is an example for how to do this, but external networking is outside the scope of what the Operator manages.

> How do I change the init shared_buffer size or change it on the fly?

There are a variety of ways to do this. You can modify `shared_buffers` as part of the `postgres-ha.yml` file (which ensures it's in the DCS). There are some upcoming changes that make this easier, and #1287 has a discussion on this.

Note this is not an "on-the-fly" change, as PostgreSQL. must be restart for the shared buffer setting to take effect.

> How to restart the cluster using pgo?

You have astutely pointed out there is not an easy way to do that today -- you can reload, but not restart. My recommendation right now would be:

```shell
kubectl -n $NAMESPACE exec pod-of-the-rimary patronictl restart
```

(you have may have to get the list of member names via `patronictl list`)

> Also, for k8s which uses --kubeconfig option to reference the config file, how to let ansible run k8s commands with that option too?

You first need to run

`kubectl config current-context`

to get the context that you are currently executing in, and then substitute the `kubernetes_context` variable with that value. This is documented in several places, including the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/) (which uses kubernetes-admin@kubernetes as an example).

**Comment by litaobowl** [comment]
@jkatz thank you for the reply!

>This is documented in several places

That I know, I meant by default kubectl looks at $HOME/.kube for config file, but sometimes we need to use --kubeconfig to reference a config file in a different place, but ansible is always using kubectl. I tried to add an alias in bashrc, but ansible is not taking it
