### ISSUE TITLE
S3 certificate parameter

### ISSUE THREAD

**Issue by aurelienmarie** [CrunchyData/postgres-operator#1337]
I am using Minio and it has the ability to enable TLS. However, i need to pass the certificate so the operator is allowed to communicate with Minio. 

I've found a way to provide it during [operator deployment](https://github.com/CrunchyData/postgres-operator/blob/master/deploy/deploy.sh#L35), but there is no documentation around that subject.

Could there be an update about it please ?

**Comment by jkatz** [comment]
Hi @aurelienmarie,

We are already planning to do this for the next release. Thanks for reporting!

**Comment by jkatz** [comment]
This is handled by #1387
