### ISSUE TITLE
Helm install

### ISSUE THREAD

**Issue by aurelienmarie** [CrunchyData/postgres-operator#1338]
Using Helm is quite a standard nowadays and other Postgres operators can be installed using it. Could there be a chart for installation instead of a bash install and Ansible ? 

Here are some advantages :

- Fewer documentation to keep up to date
- Easier install (one command line `helm install` instead of `make setupnamespaces; make installrbac; makedeployoperator`)
- No need to use an expenv util (I noticed removal of this was done for [4.2.2 release ](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.2))
- Easier way to expose operator parameters to end user (example [here](https://github.com/CrunchyData/postgres-operator/issues/1337))

**Comment by jkatz** [comment]
Hi @aurelienmarie,

For this upcoming release, we are going to add an "installer" container that will replace the Ansible/Bash install and make it significantly easier to do so. You can view the draft PR at #1335

Helm is very popular, but we have found that users like to write their own Helm charts to orchestrate for their environment. We believe that the installer container will make it easier to write a Helm chart, and we may also provide an example for how to do so as well.

However, we don't have the intention to have an official Helm chart in the immediate future, but may incorporate one soon. We would also welcome the contribution of a Helm chart as well around the new installer container :wink:

**Comment by ccravens** [comment]
We are a fan of the Ansible install and use it as part of our automation, does this mean that the Ansible install will be deprecated? Would be nice to have that stay if possible

**Comment by jkatz** [comment]
Hi @ccravens,

Here is a fun fact: the Ansible installer will be running inside the installer container :wink: All of the install logic will be capture in the container.

If you want to run another script around it, by all means do so, but we believe that once you start running the installer container, you will not want to go back (though you may have suggestions for improvements :wink:)

**Comment by ccravens** [comment]
@jkatz def see the advantage! No tools required to install other than docker / podman. There's nothing stopping our automation from launching a container, but it's just so clean having the ansible running alongside our ansible that we like... just my 2 cents :)

**Comment by aurelienmarie** [comment]
@jkatz could you clarify the roadmap please ? From my understanding, there will now be 3 differents ways to install the operator. At least two of them (Ansible, Bash) will need to support either OpenShift/Kubernetes while Helm chart is agnostic from that. IMHO this will bring complexity to your code maintainability.

I really think the Helm stuff would also bring clarity to the repository as all .json would be some real templates. 

Also, I am currently doing a study around the different DB operator and I can see most of them have Helm as one of the main way of deployment:

- https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator
- https://github.com/kubedb/installer/tree/v0.13.0-rc.0/chart/kubedb
- https://github.com/vitessio/vitess/tree/master/helm/vitess

**Comment by jkatz** [comment]
@aurelienmarie We are standardizing around one installer, and that is the container installer mention in #1335 

The source for the container installer will be the Ansible scripts that we have created.

We used to maintain a Helm installer and we may do that again. First we want to ensure that we have made the install process as easy as possible, and we believe this container-based approach will do so. Please be patient as we put this together :wink: Thanks!

**Comment by aurelienmarie** [comment]
Thanks !

**Comment by tengzhuofei** [comment]
I want to Helm3 to install chart-4.2.2

**Comment by cameronbraid** [comment]
Have you considered https://kustomize.io/ ?

**Comment by c4po** [comment]
I like the idea to use native Kubernetes tools like Helm or Kustomize to manage the installation and upgrade. 
run ansible in docker container is better than run ansible directly. But it may get complicate to make things backwards compatible for future upgrade.

**Comment by tirelibirefe** [comment]
A working Helm chart would be a great option.

**Comment by jkatz** [comment]
The deployer container is now available, you can read about getting started here:

[https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator)

More information is available in the [installation](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/postgres-operator/) section.

I'd be curious to hear that now with the deployer container, is a Helm chart is needed?

**Comment by cameronbraid** [comment]
Granting the **cluster-admin** role to the deployer is concerning. 

You should create a custom role for the deployed with access limited to the pgo namespace and bind only the required permissions.

**Comment by andrewlecuyer** [comment]
@cameronbraid thanks for the feedback.

We do plan to further decompose the privileges assigned to the deployer ServiceAccount, specifically into a role containing only those priveleges required to install the Operator.  Therefore, the intention is to move away from the current `cluster-admin` requirement in an upcoming release, and instead utilize a role containing only the required privileges.

**Comment by aurelienmarie** [comment]
Thanks guys for your great work ! You made it in fact more easier !

However, the [postgres-operator.yml](https://github.com/CrunchyData/postgres-operator/blob/master/installers/kubectl/postgres-operator.yml) is quite long and the parameters might not be easily identifiable at first sight. Most of them are passed as environnement variable and so in multiple lines.

Some parameters might be easier to add for the installation. For example, if I want to add a cert file for S3 storage, i'd need to add it before, and then reference the secret in your deployment ? With the Helm charts, file are more easily embedded during the deployment phase. I really think that a _values.yaml_ having the needed parameters would benefit the users: 

- more readibility between key/value parameters (like the pgo.yaml)
- possibility to add eventually more documentation (i.e. comments) on the values.yaml to make the installion even smoother and avoid the users to go back to documentation page

**Comment by jkatz** [comment]
We have committed a Helm chart. This will be officially supported s of the v4.4.0 release.
