### ISSUE TITLE
creating a cluster based on a postgres database not in kubernettes.

### ISSUE THREAD

**Issue by philmcc** [CrunchyData/postgres-operator#1340]
move HI,

I am looking at using your postgres operator which looks amazing.

One thing I am not sure of is the best way to move data into the cluster created. Obviously, I could do it with a pg_dump but I would like to avoid the down time.

Logical replication would be another option but it can take a long time as our database is large and has a lot of throughput.

I was wondering if it is possible to create a backup of our current database with pgbackrest and continue streaming wal files to that location (an s3 bucket). 
Would it then be possible to create a cluster based on that backup and have it replay the additional wal? 

That seems like it would be the fastest and most reliable way to switch over with minimal downtime.

Thanks in advance
Philip

** Which example are you working with? **

**What is the current behavior?**

**What is the expected behavior?**

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by jkatz** [comment]
If you want to minimize downtime, you will likely want the upcoming 4.3 release and create a [standby cluster](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.0-beta.1) which allows you to do exactly that.

**Comment by jkatz** [comment]
The "standby cluster" functionality is now available, you can read more about it here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/)

I believe it covers exactly what you are looking to do. Good luck!
