### ISSUE TITLE
scheduled backup job-name pattern length changed in pgo 4.2

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1347]
The job-name pattern for the scheduled backup job-name has changed in 4.2. 
Actually it is longer than the version in 4.1

pgo 4.1.0: `<cluster-name>--pgbackrest-diff`
pgo 4.2.2: `<cluster-name>-backrest-full-backup-schedule`

It is much longer in 4.2.2. This reduce the maximal length of the cluster-name. 

In case we migrate existing cluster from 4.1.0 to 4.2.2 (with a cluster-name having more than **32** characters), we cannot schedule backup anymore.

```
postgres-operator-5488c85999-8w2lj operator time="2020-03-16 12:24:00 +0000" level=error msg="error creating Job pg-adrian-spring-music-database-fad225f8-backrest-full-backup-scheduleJob.batch \"pg-adrian-spring-music-database-fad225f8-backrest-full-backup-schedule\" is invalid: spec.template.labels: Invalid value: \"pg-adrian-spring-music-database-fad225f8-backrest-full-backup-schedule\": must be no more than 63 characters" func="kubeapi.CreateJob()" file="kubeapi/job.go:82" version=4.2.2
```
The modification has been performed in pgbackrest.go (line 82).

On our side, we have "live" cluster-name having more than the  32 limit. This means we cannot migrate them :-(

Any idea to overcome this limitation?

**Comment by jkatz** [comment]
I don't think it has changed?

[https://github.com/jkatz/postgres-operator/blame/master/pgo-scheduler/scheduler/pgbackrest.go#L82](https://github.com/jkatz/postgres-operator/blame/master/pgo-scheduler/scheduler/pgbackrest.go#L82)

It's been that way for awhile it seems, but if I were to dive into it further, I could see there being a change as the scheduled code is now more consolidated with the ad hoc code.

The "simple" solution would be to give your cluster a shorter name in the interim :smile:

On our end, we'll look into shortening the job names.

**Comment by jose-joye** [comment]
Hello Jonathan,
This is not an issue for the new cluster. However, for the existing one, I'm not aware of any way to rename them....

**Comment by jkatz** [comment]
Hi @jose-joye,

Unfortunately it is a bit of an arduous task :\ I took a brief look at what it would take in 4.1.1:

- Renaming the `ClusterName` attribute in the pgcluster and pgreplica CRD
- Matching the `Name` attribute in both of those CRDs to match the `ClusterName`

That would at least ensure that anything created off of those templates have the new name. But you would have to:

- Update the `pg-cluster` label on each Deployment to have the new name
- On the primary Deployment, 
- On replica Deployments, update the `replica-name` label to match the pattern
- Update the service labels
- Update the label on the pgBackRest repo

...and I'm sure I'm missing something :|

In 4.2.2, you could use `clone` and then re-set up the cluster :smile:

**Comment by jose-joye** [comment]
Hello @jkatz 
I will try to go another path....
Our clusters are created by the pgo-osb (customized for our needs). I will try to implement the following so as not to do to much internal tweaking:

- Create 2 k8s cronjobs per clusters (1 for full backup and 1 for diff backup)
- The cronjobs will start a job that will launch the pgo-client pod asking to run either a full or diff backup.

That's the idea. I will see if it work :-)

By the way, do you already know if "shortering the job name" task will be implemented in 4.3?

**Comment by jose-joye** [comment]
We have implemented the temporary workaround for live clusters based on k8s cronjobs. 
This seems ok. So just in case someone also need it, here it is:

First generate the "template" for the cronjob:
```
# create dir where template file will be stored
mkdir -p ${HOME?}/pg-bck-template
chmod 700 ${HOME?}/pg-bck-template
  
  
# Create the template file for the cronjob
cat <<'EOF' > ~/pg-bck-template/cron-bck-template.yaml
# This is a template for executing a cronjob for a full backup
# It is supposed to be used the following way:
# $ export CRON_CLUSTER_NAME="the-pgo-cluster-name"
# $ export CRON_NAMESPACE="cfae-bit-cbcd2"
# $ export CRON_BACKUP_TYPE="full"   # valid values are "full" or "diff"
# $ export CRON_SCHEDULE="11 22 * * 0"
# $ envsubst < cron-bck-template.yaml | kubectl apply -f -
#
#
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${CRON_BACKUP_TYPE}-${CRON_CLUSTER_NAME}
  namespace: pgo
spec:
  schedule: "${CRON_SCHEDULE}"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  startingDeadlineSeconds: 60
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        vendor: crunchydata
        workaround-name-too-long: "true"
      name: pgo-bck-${CRON_BACKUP_TYPE}-${CRON_CLUSTER_NAME}
    spec:
      backoffLimit: 5
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: pg-cluster-${CRON_BACKUP_TYPE}-backup
        spec:
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          containers:
          - env:
            - name: PGO_APISERVER_URL
              value: https://postgres-operator:8443
            - name: PGOUSERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pgouser-admin
            - name: PGOUSERPASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pgouser-admin
            - name: PGO_CA_CERT
              value: pgo-tls/client.crt
            - name: PGO_CLIENT_CERT
              value: pgo-tls/client.crt
            - name: PGO_CLIENT_KEY
              value: pgo-tls/client.pem
            name: pgo
            image: crunchydata/pgo-client:centos7-4.2.2
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: pgo-tls
              name: pgo-tls-volume
            args:
            - pgo
            - -n
            - ${CRON_NAMESPACE}
            - backup
            - ${CRON_CLUSTER_NAME}
            - --backup-opts
            - --type=${CRON_BACKUP_TYPE}
          volumes:
          - name: pgo-tls-volume
            secret:
              defaultMode: 420
              items:
              - key: tls.crt
                path: client.crt
              - key: tls.key
                path: client.pem
              secretName: pgo.tls
EOF

```

And now you can use it to create either a full and/or a diff backup with k8s cronjobs (they will be run in same ns as pgo):

```
export CRON_CLUSTER_NAME="pg-adrian-spring-music-database-fad225f8"
export CRON_NAMESPACE="cfae-cbcd2"
 
# full backup once a week on sunday
export CRON_BACKUP_TYPE="full"
export CRON_SCHEDULE="11 22 * * 0"
envsubst < ~/pg-bck-template/cron-bck-template.yaml | kubectl apply -f -
 
# diff backup every day except sunday
export CRON_BACKUP_TYPE="diff"
export CRON_SCHEDULE="11 22 * * 1-6"
envsubst <~/pg-bck-template/cron-bck-template.yaml | kubectl apply -f -
```

**Comment by jkatz** [comment]
@jose-joye Does this do the trick?

**Comment by jose-joye** [comment]
@jkatz : Perfect!
