### ISSUE TITLE
How do I change the default shared_buffer size

### ISSUE THREAD

**Issue by litaobowl** [CrunchyData/postgres-operator#1348]
Hi Jonathan,
1. I followed your advice to add `shared_buffer` to 
/examples/custom-config/postgres-ha.yaml, but it's not taking effect.
I think I'm looking at the wrong file.
2. How can I delete my operator entirely and start from scrach?
    Now I have to do 
`kubectl delete secrets,services,clusterrolebindings,rolebindings,clusterroles,serviceaccounts,roles,configmaps,deployments --all -n pgo` 
3. Also, is there a way to use a different version of postgres

Thank you

**Comment by jkatz** [comment]
1. There are a variety of ways to modify the `shared_buffer` parameter, including `ALTER SYSTEM SET shared_buffers TO 'blah';`. If you create a custom configuration, you need to set that and then deploy the PostgreSQL cluster. We are making this easier in 4.3

2. There are a few ways of doing this, [which are outlined in the documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/install-with-ansible/uninstalling-operator/)

3.  Yes, you can [adjust the image](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#create-a-postgresql-cluster-with-postgis) as well as select a different tag with the [`--ccp-image-tag` flag](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/). Note that the image does need to be compatible with the Operator.
