### ISSUE TITLE
archive_timeout default

### ISSUE THREAD

**Issue by adifri** [CrunchyData/postgres-operator#1354]
**I'm submitting a ...**

 
 - [x] bug report
 - [ ] feature request
 - [x] support request

**What is the current behavior?**

in clusterutilities.go line 298
```
		if _, exists := cluster.Spec.UserLabels[config.LABEL_ARCHIVE_TIMEOUT]; !exists {
			archiveTimeout = cluster.Spec.UserLabels[config.LABEL_ARCHIVE_TIMEOUT]
		} else {
			archiveTimeout = DefaultArchiveTimeout
		}
```

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**
```
		if _, exists := cluster.Spec.UserLabels[config.LABEL_ARCHIVE_TIMEOUT]; exists {
			archiveTimeout = cluster.Spec.UserLabels[config.LABEL_ARCHIVE_TIMEOUT]
		} else {
			archiveTimeout = DefaultArchiveTimeout
		}
```

**What is the motivation or use case for changing the behavior?**

archiveTimeout should be equal to DefaultArchiveTimeout only if there is no label LABEL_ARCHIVE_TIMEOUT in cluster

**Please tell us about your environment:**

 - Operator Version: 4.2.2

Am I wrong or is this a typo ?

Thanks
Adrian

**Comment by jkatz** [comment]
@adifri It is a typo. It likely went unnoticed as that parameter is not often tweaked, and the PostgreSQL default is 60.

On `master` the need for setting the default is entirely removed, but this is still a bug on 4.2, ergo I've patched it.

Thanks for reporting!
