### ISSUE TITLE
centos7-11.7-4.2.2 : ERROR:  could not resize shared memory segment "/PostgreSQL 

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1358]
Hello,

We have a cluster where a query is run on a view and we get the following error:

```
ERROR:  could not resize shared memory segment "/PostgreSQL.412969521" to 8409088 bytes: No space left on device
CONTEXT:  parallel worker
SQL state: 53100
```
looking at different posts:
https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device
https://meta.discourse.org/t/pg-throws-could-not-resize-shared-memory-segment-error/84744

It is explained that we should extend the shared memory size available when starting the docker image of postgresql  (`--shm-size`).

Looking at the Temp File usage, we clearly see that at the request time, the temp file was full.

Here is the size of shm:
```
 $ df
Filesystem       1K-blocks      Used  Available Use% Mounted on
shm                  65536         8      65528   1% /dev/shm
```  
So my questions are:
- Did you already run into this limit?
- Any hints about the way, we can increase the size to something bigger for large dB?

Thanks for any input!

José

**Comment by jose-joye** [comment]
I guess I can try to improve the situation by doing the following:

- Assign more memory to pod (eg 32 MB)
- change postgresql memory settings by adding entry in `"cluster"-config` CM as follow:
```
# Memory Settings
shared_buffers = '8192 MB'
work_mem = '256 MB'
maintenance_work_mem = '520 MB'
huge_pages = try   # NB! requires also activation of huge pages via kernel params, see here for more:
                   # https://www.postgresql.org/docs/current/static/kernel-resources.html#LINUX-HUGE-PAGES
effective_cache_size = '22 GB'
effective_io_concurrency = 300   # concurrent IO only really activated if OS supports posix_fadvise function
 ```

**Comment by jkatz** [comment]
@jose-joye I have a patch coming in minutes...

**Comment by jkatz** [comment]
@jose-joye See patches that expand access to POSIX shared memory. I opened them up to have some more eyes on it. We are going to discuss a bit more before committing (or not).

**Comment by jkatz** [comment]
@jose-joye Yes, that's correct.

People who are more versed than me in kernel memory management are debating the merits of said change, but I wanted to throw it out there as an option.

If increasing the container resource memory allocation and increasing setting the shared buffers to be 25% of that works, then that would also make me happy and potentially remove the need for this patch.

Fortunately, this is a [well documented](https://www.postgresql.org/docs/current/kernel-resources.html) topic in PostgreSQL and it's just ensuring we've covered all of our bases inside the container. Given we know people running some really large databases, I'm surprised this has not come up before. By chance, where your `shared_buffers` originally set to be the same size as those of your memory resources and/or what % of your memory resources were they?

**Comment by jose-joye** [comment]
@jkatz 
I have patch my installation and installed it on a test platform. This seems to work :-)
I will push this on our PROD platform on sunday and can give a final feedback on monday.

Related to the setting we had for this cluster, it is as follow:

```
inventory
resource3_name='single_standard_8'
resource3_requests_memory='1Gi'
resource3_requests_cpu=0.5
resource3_limits_memory='8Gi'
resource3_limits_cpu=2

In <cluster>-config CM:
shared_buffers:                  "2048 MB"
maintenance_work_mem:    "320 MB"
huge_pages:                       "off"
effective_cache_size:           "6 GB"
```

It is too low for our large cluster. We will need to change it. However, it allows us to find this issue :-)

José

**Comment by jkatz** [comment]
Yeah, tuning a PostgreSQL cluster is as much art as it is science.

Glad to hear the early results are positive. I have merged the patches in, and we will keep an eye on thsi one in general. Thanks for reporting!
