### ISSUE TITLE
Topology Awareness

### ISSUE THREAD

**Issue by ccravens** [CrunchyData/postgres-operator#1363]
I've been reading the following regarding HA and Node-Affinity here: https://access.crunchydata.com/documentation/postgres-operator/4.2.2/architecture/high-availability/

However, I'm not sure if I've found anything related to Topology awareness for failover zones (ie AWS Availability Zones). What I'm looking to do is ensure that we have a master and the replicas deployed on any node within each Availability Zone. This is different than node affinity / node anti-affinity in that we want to ensure that the deployment is distributed amongst the network topology. Any guidance on this would be much appreciated, thanks!

**Comment by jkatz** [comment]
What you're describing sounds exactly like node affinity / anti-affinity, so I'm not quite sure what you're asking about.

The Operator supports *pod anti-affinity* for ensuring each deployed Pod is not near each other. It also supports *node affiinity* (via the `--node-label` flag) so you can tell each Pod to be deployed amongst a particular node or nodes, including the replicas.

Perhaps I'm not following?
