### ISSUE TITLE
The ansible install sequence tries to download the wrong pgo client

### ISSUE THREAD

**Issue by paulbarbu** [CrunchyData/postgres-operator#1372]
**Describe the bug**
The inventory file in the 4.3.0-beta1 tag contains pgo_client_version='v4.3.0', but when downloading it, the URL cannot be found.

The correct URL is: https://github.com/CrunchyData/postgres-operator/releases/download/v4.3.0-beta.1/pgo

So the version needs to be changed to include "-beta.1"?
**To Reproduce**
ansible-playbook -i inventory --tags=install main.yml -K

**Expected behavior**
pgo client should download without errors.

**Comment by jkatz** [comment]
The containers are not available at this time. We typically don't push "beta" containers publicly for a plethora of reasons at this point, though that can always change in the future.

If you need an older version, you can update the ansible playbook to point to the older version.

The client version in `v4.3.0` matches the client version of the beta, so that does not need to be changed either.

**Comment by paulbarbu** [comment]
Now that was fast...

I don't understand. Why don't you publish beta containers?
How are we supposed to install this v4.3.0-beta.1 version then?

maybe the client version matches the version of the beta, but it cannot be downloaded when ansible is run.

**Comment by jkatz** [comment]
@paulbarbu Based on the various distributions we support we have a complicated build process. I will talk to some people and see if we want to publish the beta containers publicly.

You likely do not want to run the beta containers anyway except for testing purposes. While we try to commit features as stable-y as possible, they do have bugs (hence the beta and why we do thorough beta testing :smile:)

Please don't flood with tickets about this. I saw your original note, this is something we'll think about.

Thanks!

**Comment by paulbarbu** [comment]
At the time I created the other issue (#1373) you didn't close this one.

How are we supposed to test this beta version of the software if the containers are not available?
At the moment only you guys can do the testing, the community cannot.

**Comment by jkatz** [comment]
Hi @paulbarbu,

I understand your concerns and you're absolutely right. As I mentioned above, we're going to work on making it easier to test earlier.

One of the main reasons of the beta announcement was to give guidance on the features and, in particular, the timing of the release especially given the current global circumstances.

I'm glad you're excited for the upcoming 4.3 release and we are working diligently to make it available :smile:

Thanks,

Jonathan
