### ISSUE TITLE
No crunchydata/pgo-apiserver:centos7-4.3.0 image

### ISSUE THREAD

**Issue by paulbarbu** [CrunchyData/postgres-operator#1373]
**Describe the bug**
I think there's no crunchydata/pgo-apiserver:centos7-4.3.0 image since my PGO operator container is in the ImagePullBackoff state.

**To Reproduce**
ansible-playbook -i inventory --tags=install main.yml -K

**Expected behavior**
The PGO operator should start.

**Additional context**
In order to reach this step I actually had to change `pgo_client_version='v4.3.0-beta.1'` in the `inventory` file. Reported in #1372

**Comment by jkatz** [comment]
hi @paulbarbu,

I'm pleased to report that you can now get the image beta images here: https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator

Thanks for your patience and support!
