### ISSUE TITLE
could not find pgouser file

### ISSUE THREAD

**Issue by prestonvanloon** [CrunchyData/postgres-operator#1375]
**Describe the bug**
Using anisble install since the bash instructions do not work.  See https://github.com/CrunchyData/postgres-operator/issues/1325

I get this issue when running the ansible commands.
```
TASK [pgo-operator : Download PGO Linux Client] ******************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

OK so I install pgo myself.

Then I run 
```
pgo version --apiserver-url=localhost:8443
could not find pgouser file
```

I have no idea what to do from here. 

**To Reproduce**
See above

**Expected behavior**

Install instructions that work.

* Operating System:
* Where is this running ( Local, Cloud Provider): EKS
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: 
* PostgreSQL Version: 4.2.1
* Platform (Docker, Kubernetes, OpenShift): k8s
* Platform Version: 1.14

**Additional context**

**Comment by prestonvanloon** [comment]
After digging through documentation, it appears I need an environment variable for pgouser. Having set this. I have a new problem now #1376

**Comment by jkatz** [comment]
You can use the `--ask-become-pass` flag with the installer.
