### ISSUE TITLE
Do not allow exposing nodePort for every services if --service-type=NodePort is used

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1379]
Hello,
We have the need of exposing some services with NodePorts instead of the standard ClusterIP (for usage from outside of k8s).
Pgo provides the feature to export the services as NodePort :-)
`pgo create cluster my-cluster --service-type=NodePort`

However, it does not really make sense to expose all services as NodePort (eg: patroni, sshd, postgres.exporter).
In fact, it can be seen as a security issue if we do so.... I may miss a point here....

As an improvement, it could be possible to create 2 k8s services:
- 1 for the internal services (patroni, sshd, ...). These will always be ClusterIP 
- 1 for the services than can be safely exposed as nodePort (postgres, pgbadger, ...)

Thanks again for the great work :-)
José

**Comment by jkatz** [comment]
Hi @jose-joye,

Thanks, taking note of this. I think the likely approach would be to take a more granular approach to this.
