### ISSUE TITLE
"4.3.0 Beta 1" docker hub images missing

### ISSUE THREAD

**Issue by dejwsz** [CrunchyData/postgres-operator#1381]
I wanted to test latest 4.3.0 Beta 1 release but it turned out there are no images with 'v4.3.0-beta.1' tag.

**Comment by jkatz** [comment]
Hi,

I'm glad you're excited to test! Please see #1373 

We're presently not making beta builds available and, in general, DockerHub is the last registry we push too. We're working on some changes to make this easier in the future.

**Comment by jkatz** [comment]
Hi @dejwsz,

I'm pleased to report that you can now get the 4.3.0 beta images here:

https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator

Thanks again for your patience and support!
