### ISSUE TITLE
where is the pgo-installer image ?

### ISSUE THREAD

**Issue by obeyler** [CrunchyData/postgres-operator#1384]
** Which example are you working with? **
https://github.com/CrunchyData/postgres-operator/blob/master/docs/content/Installation/postgres-operator-installer/_index.md

I don't find the docker image for  pgo-installer on docker is it on another repository ?

**Comment by jkatz** [comment]
Please see #1381 about the status of the beta containers. We normally push to DockerHub last.

The documentation for the presently available installation methods is available here:

- [Quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/)
- [Installation](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/)

We aim to make the installation container in the near future. Thanks for your excitement about it!

**Comment by jkatz** [comment]
Hi @obeyler,

You can now get the 4.3.0 beta images here: https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator. The instructions follow the Ansible method, but the image is available following the image name pattern.

I will note that in Beta 3, we are renaming the image to `pgo-deployer` as it will be doing more than just intalling.

Thanks for your patience!

**Comment by obeyler** [comment]
sorry @jkatz could you reopen this issue as pgo-deployer is still not present on dockerhub
/reopen

**Comment by jkatz** [comment]
The containers are currently publicly available here (see instructions): [https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator)
