### ISSUE TITLE
pgbackrest warning: invalid page checksums found in file 

### ISSUE THREAD

**Issue by cubed-it** [CrunchyData/postgres-operator#1394]
Not sure if it is a bug or expected behavior. So maybe you can give me a shot if this is something that is important or if I can ignore it? Is my backup integrity okay? 

In version 4.2.1 a pgbackrest backup show the following warning:
```
time="2020-04-03T23:11:21Z" level=info msg="stderr=[WARN: invalid page checksums found in file 10.244.1.30:/pgdata/proddb-qpup/base/16411/pg_internal.init.83188 at pages 2313682945-2313682947\n]"
```

**Comment by jkatz** [comment]
From the [pgBackRest documentation](https://pgbackrest.org/#features/page-checksum):

> PostgreSQL has supported page-level checksums since 9.3. If page checksums are enabled pgBackRest will validate the checksums for every file that is copied during a backup. All page checksums are validated during a full backup and checksums in files that have changed are validated during differential and incremental backups.
>
> Validation failures do not stop the backup process, but warnings with details of exactly which pages have failed validation are output to the console and file log.
>
>This feature allows page-level corruption to be detected early, before backups that contain valid copies of the data have expired.

In other words, pgBackRest detected that one of the pages (the fundamental on-disk storage unit for PostgreSQL) is corrupted. While pgBackRest will continue to operate, you do need to investigate what is occurring with your PostgreSQL cluster and identify and fix the corruption.

**Comment by cubed-it** [comment]
All right. Thanks for the hint from the documentary. Sorry for the non PGO related trouble ;)

**Comment by jkatz** [comment]
Happy to help where I'm able to :smile:

**Comment by cubed-it** [comment]
Apparently, I'm lucky. The file pg_internal.init should obviously not exit at all, it should be deleted after the first postgres start/restore.
There was even a fix for pgbackrest, I guess I still have an older version :/ https://github.com/pgbackrest/pgbackrest/pull/941

**Comment by jkatz** [comment]
Yes, 4.2.x is on 2.20

4.3.x will go to 2.24
