### ISSUE TITLE
Issues with running Ansible playbook on microk8s 

### ISSUE THREAD

**Issue by rpdeadly** [CrunchyData/postgres-operator#1397]
Hello.
   I'm trying to setup a local instance of postgresql database on kubernetes ( microk8s implementation ) by following the instructions on https://access.crunchydata.com/documentation/postgres-operator/4.2.2/quickstart/#ansible
I see that many of the Ansible tasks ( pgo-preflight ) were skipped and at the end when i run the command to list deployment i see that nothing has been created.

kubectl -n pgo get deployments 
No resources found in pgo namespace

* Operating System: Ubuntu 18.04
* Where is this running : Local
* Storage being used (): Not sure
* Container Image Tag: 
* PostgreSQL Version: 
* Platform (Docker, Kubernetes, OpenShift): Microk8s
* Platform Version: v1.17.4

**Comment by jkatz** [comment]
It's okay for pre-flight checks to be skipped. Do you have an actual error message, such as at the end of the playbook? Or any additional logs?

Note that we don't test on Microk8s and it's not considered one of our supported platforms.

**Comment by rpdeadly** [comment]
This is what i see towards the end of the script

```
TASK [pgo-preflight : Check if the kubectl command is installed] ************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "which kubectl", "delta": "0:00:00.002139", "end": "2020-04-09 15:01:31.445366", "msg": "non-zero return code", "rc": 1, "start": "2020-04-09 15:01:31.443227", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [pgo-preflight : Ensure kubectl is installed] **************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "kubectl_result.rc == 0", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/"
}

localhost                  : ok=6    changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=1
```

**Comment by jose-joye** [comment]
On our side we also deploy it on microk8s for development purpose.
We can successfully install it using the following cmd:

$ ansible-playbook -i ansible/inventory --tags=install \
  -e "crunchy_debug=true kubernetes_context=microk8s" \
  -e "pgo_admin_password=admin create_pgo_rbac=false create_backrest_rbac=false" \
  -e "metrics=true auto_failover=true auto_failover_replace_replica=true db_replicas=1" \
  -e "namespace='postgres-testing'" \
  --ask-become-pass ansible/main.yml

José

**Comment by jkatz** [comment]
The issue is right here:

```TASK [pgo-preflight : Ensure kubectl is installed] **************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "kubectl_result.rc == 0", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/"
}```

On the machine that you are running `ansible` from, you do not have `kubectl` installed. You need to install `kubectl` (with the directions referencing that you can download it from [https://kubernetes.io/docs/tasks/tools/install-kubectl/](https://kubernetes.io/docs/tasks/tools/install-kubectl/).

We're hoping this process will be easier for 4.3 as we recently added a process for installing the Operator using `kubectl` directly via 7849878, though it still needs a bit more polish.

**Comment by rpdeadly** [comment]
Sorry for taking a long time but I got caught up in something. That is strange because I have an alias ( alias kubectl="microk8s kubectl" ) create for this reason. I will try @jose-joye command. Thanks for looking into this.
