### ISSUE TITLE
why don't you use statefullset to implement ?

### ISSUE THREAD

**Issue by orainxiong** [CrunchyData/postgres-operator#14]

**Comment by jmccormick2001** [comment]
thanks, I'm building the operator to support different deployment strategies and I could support a stateful set model pretty easily, I have examples of this in the containers project as well.  What advantages does a statefulset deployment provide over the current default deployment strategy for you?

**Comment by jmccormick2001** [comment]
I'm currently implementing postgres 'cluster' as Kube Deployments, the postgres master and each postgres replica are contained within a Kube Deployment.  I chose this for reasons of flexibility mainly, for example, I can assign a particular Postgres replica to a specific node if I wanted to.  I can also assign each postgres component a different storage class.  Hope than answers the Issue.  regards.
