### ISSUE TITLE
pgo backup command fails second time

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#140]
pgo backup command ran successfully the first time and it fails the second time. This is because the backup job is still running even after the backup completed successfully. 

Could you delete the backup job automatically to allow for subsequent backups to run ?

**Comment by jmccormick2001** [comment]
merged into pre26 branch...with this change, the *--no-prompt* flag is added to the *pgo backup* command, and also the apiserver will remove any existing backup job that might exist prior to submitting a new backup job.
