### ISSUE TITLE
Docker images for beta versions?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [CrunchyData/postgres-operator#1402]
Hello, I'm trying to test the 4.3-beta.2, but apparently there are no pre built docker images for them (correct me if I'm wrong!), which makes almost impossible quickly test new version... Are there plans to add beta images to the development pipeline?

Thanks

**Comment by jkatz** [comment]
Please see #1381 and #1373 

We're excited you want to test, and we do have plans to make the latest beta available, which we will reveal in the coming days.

**Comment by jkatz** [comment]
Hi @DanielFerreiraJorge,

I'm pleased to let you know that the beta images are now available here: https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator

Thanks again for your patience!
