### ISSUE TITLE
PGbackrest performance improvements

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#1407]
**What is the motivation or use case for the feature? **
To make pgbackrest perform much better one has to switch config file from ENV variables.
https://www.pgcon.org/2019/schedule/attachments/533_High-Performance-pgBackRest.pdf 
as long as process-max option differs a lot from the need in backup/restore/archive-push tasks

**Describe the solution you'd like**
Separate pgbackrest.conf file as part of custom config + ENV variable `PGBACKREST_REPO_HOST_CONFIG` ( `--repo-host-config` [link](https://pgbackrest.org/configuration.html#section-repository/option-repo-host-config) )

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Backup with 1 process-max are way to slow, and archive-push with process-max >1 might be unsafe. Restore needs all available process-max=CPU_core

**Comment by jkatz** [comment]
Hi @lkhomenk,

As always you seem to read my mind. Please see #1401 for a similar scenario.

We are looking to moving to using the config file but the earliest it will be is the release after 4.3

Thanks!

**Comment by jkatz** [comment]
Operator 4.5 introduced the ability to [customize pgBackRest from a ConfigMap](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0), which should allow for you to tailor pgBackRest settings to your cluster. Hopefully this resolves your issue. Thanks!
