### ISSUE TITLE
enhance pgo show backup to show backup date

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#141]
"pgo show backup" command does not show list of backups available and any of their details. 

pgbackup : abc
	PVC Name:	abc-backup-pvc
	PVC Access Mode:	ReadWriteMany
	PVC Size:		200M
	CCPImageTag:	centos7-10.2-1.8.0
	Backup Status:	completed
	Backup Host:	abc
	Backup User:	primaryuser
	Backup Port:	5432

**Comment by jmccormick2001** [comment]
updated the *pgo show backup* output to include the pgbackup CRD creation timestamp, this will show when the CRD was created to give an indication of when the backup occurred.
