### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by jangel97** [CrunchyData/postgres-operator#1412]
** Hello there, me and my team are considering to use Crunchy Operator in OpenShiftv3.11, but we would like to know if it can create new clusters out of existing databases, would that be possible? Thanks in advance!**

**Comment by jkatz** [comment]
Yes. Please see the [pgo clone](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_clone/) feature.

**Comment by jangel97** [comment]
Hello jkatz, thanks for your quick response, the problem is that the databases I want to use as primary are not in any existing cluster of Crunchy, and as I see it pg clone feature copies the primary database of an existing cluster to a new cluster.

Is there any feature to do so?

**Comment by jkatz** [comment]
This is more of a function of how you use PostgreSQL vs. as a function of the Operator. For example, you can borrow from the [upgrade PostgreSQL using pg_dumpall](https://info.crunchydata.com/blog/performing-a-major-postgresql-upgrade-with-pg_dumpall) technique and copy your data over from your existing cluster.

I would recommend executing it on the Pod that is serving as your destination: the `pg_dumpall` and `psql` binaries are included in the containers launched by the PostgreSQL Operator.

**Comment by jangel97** [comment]
Thank you very much!

**Comment by jangel97** [comment]
Hello there, I followed the procedure you provided me with, and when I apply the following command in the cunchy pod:

`$ pg_dumpall -h postgresql.postgresql.svc.cluster.local -U postgres | psql --single-transaction --no-psqlrc -h hippo -U postgres`

The command gets stuck a few minuts, once it finishes, it is not returning any message. Besides, no tables have been migrated to the pod. 

Do you know if there is something else I have to do? Something not specified in this link: https://info.crunchydata.com/blog/performing-a-major-postgresql-upgrade-with-pg_dumpall

Thanks for all your support!
