### ISSUE TITLE
how to enable metrics to existing cluster

### ISSUE THREAD

**Issue by gricuk** [CrunchyData/postgres-operator#1413]
I'm using PGO v4.2.2 . I want to enable metrics for my existing cluster. But **update cluster** option doesn't support this feature.  I see the folliwing closed issue:
https://github.com/CrunchyData/postgres-operator/pull/1319

It is possible to enable metrics without clone my cluster?

it would be great to have possibility to update cluster. What can you recommend and what about feature request?

**Comment by jkatz** [comment]
Thanks! This is something we do already have on the roadmap.

In the interim, you could always borrow from the Deployment definition of a cluster that is created with the metrics sidecar, and updated your existing Deployment to match that.

**Comment by gricuk** [comment]
> Thanks! This is something we do already have on the roadmap.
> 
> In the interim, you could always borrow from the Deployment definition of a cluster that is created with the metrics sidecar, and updated your existing Deployment to match that.

Hi! When I've manually set **crunchy_collect: "true"** in deployment and  I get the following error:
spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"archive-timeout":"60", "backrest-storage-type":"s3", "crunchy-pgha-scope":"cluster-test", "crunchy_collect":"true", "deployment-name":"cluster-test"", "name":"cluster-test"", "pg-cluster":"cluster-test"t", "pg-cluster-id":"4aee6fe5-b8e2-4bcc-8043-ab84258886dc", "pg-pod-anti-affinity":"", "pgo-version":"4.2.2", "pgouser":"admin", "vendor":"crunchydata", "workflowid":"1626aac9-2cba-404c-9d02-6e67adc179d2"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable.
I can't modify deployment.

**Comment by CermakM** [comment]
This would be nice to have 👍

**Comment by jkatz** [comment]
Using Operator 4.4.0, here is a way you can get to it. I will pause and say that even if we added a `--enable-metrics` flag to `pgo update cluster`, where would still be downtime.

Anyway, let's say you have created a simple cluster:

`pgo create cluster hippo`

If you want to add metrics

```
# take a backup for safety
pgo backup hippo
# let backup complete
pgo update cluster hippo --shutdown
# let the cluster shutdown, to ensure that all in process transactions are written
pgo delete cluster hippo --keep-backups
# let delete complete
pgo create cluster hippo --restore-from=hippo --metrics
```

and now you have metrics in your existing cluster.

**Comment by avanichy25** [comment]
hi @jkatz , I am using pgo `4.3.2` and i want to enable the monitoring. I deployed the `4.5.0` monitoring stack but it was not working.
How should i enable the monitoring for pgo `4.3.2` ?
