### ISSUE TITLE
Host and port of postgres cluster

### ISSUE THREAD

**Issue by yharish991** [CrunchyData/postgres-operator#1420]
Is it possible to include the host address and the port of the cluster created in the `status` of the CR that is used to create the cluster? Right now i can get the host and post by querying the service of the cluster or by knowing cluster name and namespace for ex: mycluster.demo

**Comment by jkatz** [comment]
The port is available as one of the CRD attributes:

https://github.com/CrunchyData/postgres-operator/blob/master/apis/crunchydata.com/v1/cluster.go#L49

I can understand why one may want that as part of the status, but I would note that the PostgreSQL port is a fundamental spec item.

For hostnames, It's an interesting idea. The challenge would be determining _what_ hostname to use, given different environments will have their own DNS policies, and if we start storing the hostname in the status, we will have to ensure we appropriately handle any updates to DNS naming schemes. We could store the Kubernetes standard FQDN, which seems safe but may not work for everyone. We could store a collection of hostnames, but I'm less enthused by that as it makes it reliant on changes to the networking environment that we cannot detect. However, I will admit that this involves more research.

For now, there are only a handful of services that are deployed with the Operator, and each are derived from the [ClusterName](https://github.com/CrunchyData/postgres-operator/blob/master/apis/crunchydata.com/v1/cluster.go#L45) spec parameter (or top-level "Name")

- Primary (`spec.ClusterName`)
- Replica (`spec.ClusterName` + "-replica")
- pgBouncer (`spec.ClusterName` + "-pgbouncer")

so there is a "convention" pattern that can be followed.

**Comment by yharish991** [comment]
Thanks for the reply. I think we can get the Kubernetes standard FQDN by concatenating `spec.primaryhost` and `spec.namespace`
