### ISSUE TITLE
Crunchy Data Storage Doubt 

### ISSUE THREAD

**Issue by jangel97** [CrunchyData/postgres-operator#1421]
Hello there,

I am new to Crunchy Data Operator and I am testing it with OpenShift 3.11, so I would like to know if the following is possible:

**I want to create a crunchy cluster in which the main database is to use glusterfs storage class (which is my default storage class), and the replica is to use nfs instead**

Would that be possible? 

Thanks in advance!

**Comment by jkatz** [comment]
Yes.

You can specify `--replica-storage-config` from the [`pgo create cluster`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) command, or --storage=config from the [`pgo scale`] command.

If you are running your setup with high-availability, I would not recommend having different storage classes.

I do encourage you to read through the documentation. While not every use case is covered, the flags and capabilities of the Operator are fully documented.
