### ISSUE TITLE
exp_type='pg' Label support from crunchy-collect - available?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1423]
Hello,
We are trying to integrate one of the grafana board exposed by pgmonitor to get cpu and memory information (https://github.com/CrunchyData/pgmonitor/blob/master/grafana/OS_Details.json).
It uses the 'exp_type' label exposed from pgmonitor (since v. 3.0). I'm not able to find it if I look at the metrics endpoint exposed by the cluster svc (`postgres-exporter`).

Looking at the issues and pull requests, I have found the pull request #1048 (Add the exp_type='pg' Label to all crunchy-collect Targets). Is this related to what I'm looking for?
If yes, is it is integrated into pgo 4.2.2?

Thanks,
José

**Comment by jkatz** [comment]
[Operator 4.5](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0) received a major update to [monitoring](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/), which has changed how some of the labels et al. work. It should be greatly improved, and I encourage you to have a look at it.

Thanks!
