### ISSUE TITLE
Docker image for 4.3.0-beta.2

### ISSUE THREAD

**Issue by yaroslavkasatikov** [CrunchyData/postgres-operator#1426]
Hello team,

I'm going through installation instruction for 4.3.0-beta.2  ( I need an abilitty to cross k8s cluster installation), but it doesn't work:
```
  Normal   Pulling    22s (x2 over 39s)  kubelet, ip-10-0-142-123.eu-west-1.compute.internal  Pulling image "crunchydata/postgres-operator:centos7-4.3.0"
```

Also I didn't find any 4.3.* images on dockerhub. 
Could you please push this image or we need to wait when 4.3.0 is released?

**Comment by jkatz** [comment]
We're excited to see you want to test! Please see #1381, #1373

DockerHub is the last repository we push to and we typically do not push beta images to there. However, we will be making beta images available in a brand new way very soon. I will circle back when this happens.

**Comment by jkatz** [comment]
Hi @yaroslavkasatikov,

We have made the beta images available here: https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator

Thanks again for your patience!
