### ISSUE TITLE
Where to set pgbackrest-storage-type using Ansible installer

### ISSUE THREAD

**Issue by Phil-Taylor-IW** [CrunchyData/postgres-operator#1430]
In the [docs](https://access.crunchydata.com/documentation/postgres-operator/4.2.2/architecture/disaster-recovery/#using-s3) you say to specify **--pgbackrest-storage-type** as a parameter to `pgo cluster create` but I'm using the Ansible installer and I can see where the auth and dest creds go but is there also a setting to choose between **local, s3 or both**?

There's no mention of it in the `roles/pgo-operator/defaults/main.yml` either.

I'm currently in local and the backups work fine but want to add S3 i.e. both.

Sorry but it's not clear to me, or at least I can't see it in the Ansible instructions.

Do you also need to add it to the Storage Setttings in the inventory file?

```
backrest_storage='nfsstorage'
backup_storage='nfsstorage'
```

Many thanks in advance. Fantastic work!

Phil

**Comment by jkatz** [comment]
Hi @Phil-Taylor-IW,

There is a difference between `--pgbackrest-storage-type` and `--pgbackrest-storage-config`. The `storage type` refers to the type of location where the pgBackRest backups and archives should be stored:

- `local`: leveraging the pgBackRest repository and Kubernetes-based storage that is available (Determined by the storage configuration)
- `s3`: using AWS S3 or equivalent system.

This becomes clearer in the unreleased v4.3, as there are not only improvements to using S3-like stores, but one can specify `--pgbackrest-storage-config` with `pgo create cluster`.

Hope this helps. Thanks for the kind words!

**Comment by Phil-Taylor-IW** [comment]
Thanks @jkatz but my question was the converse I believe i.e. how to set the storage type using Ansible in 4.2, the current version.

**Comment by jkatz** [comment]
Same as now, with the `--pgbackrest-storage-type` flag at cluster creation time. There is no "global" configuration for it.

**Comment by Phil-Taylor-IW** [comment]
Doh! I was getting confused between creating clusters and installing the Operator. Thanks 😊
