### ISSUE TITLE
How to change pgbackrest-storage-type to existing cluster

### ISSUE THREAD

**Issue by kglebova** [CrunchyData/postgres-operator#1435]
I'm using PGO v4.2.2 . I want to change pgbackrest-storage-type   for my existing cluster.

How I can to add pgbackrest-storage-type  's3'  (pgbackrest-storage-type=local,s3) without recreate existing cluster? 
How I can to change pgbackrest-storage-type with 'local' on 's3'  without recreate existing cluster?

**Comment by jkatz** [comment]
The short answer is that you have to manually change the settings on the pgcluster (though primarily to maintain that info), the various Deployments, `postgresql.conf` files etc., as well as create the initial stanza and backups on S3.

Adding this to the `update` functionality could be future work.

**Comment by mack314** [comment]
@jkatz 
do you have step by step documentation on the above process to migrate storage type from local to s3 for pgbackrest for  existing cluster.
