### ISSUE TITLE
How to cipher backups

### ISSUE THREAD

**Issue by kglebova** [CrunchyData/postgres-operator#1436]
I'm using PGO v4.2.2 .  I want to cipher backups. 
If I run backup (pgbackrest) with backup-opts --repo1-cipher-type=aes-256-cbc 
I get
Error: unknown flag: --repo1-cipher-type

How I can   to cipher backups for backup-type pgbackrest?
How I can to cipher backups for backup-type  pgdump?

**Comment by jkatz** [comment]
You can use pgBackRest's encryption feature starting in 4.3 thanks to commit c9759b8

There is no support in PostgreSQL for encrypting backups. You will need to do this on your own with the StorageClass you are using, or leverage `pgcrypto` to perform column-level encryption.
