### ISSUE TITLE
Rollback is not implemented if upgrade fails?

### ISSUE THREAD

**Issue by jacobzhang0110** [CrunchyData/postgres-operator#1438]
I'm reading code how upgrade is performed and seems there is no rollback mechanism?

E.g. I have a cluster with 1 primary and 3 replicas, no matter if I use UpgradeWithAutofailDisabled or UpgradeWithAutofailEnabled, if one replica upgrade fails, the whole cluster will not rollback to its original version. 

Just raising this ticket to confirm above understanding, thanks!

**Comment by jkatz** [comment]
Yes, that's correct, there is no rollback mechanism. You would have to try the upgrade again, or modify the objects directly to use different images.

PostgreSQL minor version updates are considered very safe. However, unless there is an underlying catalog version change in a minor update or some other change that requires modifications (both are rare), you could go back down to a lower version if needed.

**Comment by jacobzhang0110** [comment]
Thank you for prompt answer, please kindly close this. Have a nice day.
