### ISSUE TITLE
pgo version command returns ERRO[0000] PGOUSER env var not set

### ISSUE THREAD

**Issue by georambo** [CrunchyData/postgres-operator#144]
postgres-operator version 2.5

I have deployed the postgres-operator successfully via helm chart and deploy scripts.  The operator is running healthy, and awaiting commands.

I have also built the pgo client from the 2.5 branch with `make all`.

Everytime I run `pgo version` , I get the error below.

postgres-operator git:(2.5) pgo version
ERRO[0000] PGOUSER env var not set

I have also exported all the values specified in the documentation.  I dont see anything else in the setup instructions regarding setting PGOUSER env. 

https://github.com/CrunchyData/postgres-operator/blob/master/docs/operator-docs.asciidoc

Any help would be appreciated.  This seems like a great solution, and would like to test it out.

```
export GOPATH=$HOME/odev
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
export COROOT=$GOPATH/src/github.com/crunchydata/postgres-operator
export CO_BASEOS=centos7
export CO_VERSION=2.5
export CO_IMAGE_PREFIX=crunchydata
export CO_IMAGE_TAG=$CO_BASEOS-$CO_VERSION
export CO_NAMESPACE=demo
export CO_CMD=kubectl
export CO_APISERVER_URL=https://postgres-operator:8443
export PGO_CA_CERT=$COROOT/conf/apiserver/server.crt
export PGO_CLIENT_CERT=$COROOT/conf/apiserver/server.crt
export PGO_CLIENT_KEY=$COROOT/conf/apiserver/server.key
```

**Comment by jmccormick2001** [comment]
Hi,  create a .pgouser file in your home directory that looks like this:

username:password

echo "username:password" > $HOME/.pgouser

**Comment by georambo** [comment]
thanks jmccormick2001.  that worked!

What user information is this?  the basic auth?   Also, is there a series of places it looks for this file, or it must be at $HOME/.pgouser?  Or can it be in an ENV variable.

Thanks again.

**Comment by georambo** [comment]
omg, i read through that too, but sadly it didnt stick in my brain :(

Thanks a million for the reference, and I get 100% how it works, and have the pgo client working.  looking good so far.
