### ISSUE TITLE
problems applying policies

### ISSUE THREAD

**Issue by twalk4821** [CrunchyData/postgres-operator#146]
Hi again -

I am encountering difficulty applying policies to a deployment, whether at the time of creation or after the fact. Initially, I tried modifying the setup.sql to include my own commands, but soon discovered that file is not loaded anywhere by default (unless I am wrong about that). What I tried instead was creating an additional sql file, and following these steps:
1. pgo create policy dump --in-file='./myfile.sql'
2. pgo create cluster my-cluster policies=dump
Seemingly everything is okay but when I check the tables, all I can see is one table from halfway down the sql file, and that's it! I can't understand why only that one random table consistently makes it in. 
A snippet from my sql policy:
```
\c timeseries;
create sequence github_commit_contributions_data_over_time_id_seq
;

create table if not exists adjacency_matrices
(
        time timestamptz(35,6) not null,
        matrix json(max) not null
)
;

...
// this table randomly makes it in!
create table if not exists symbol
(
id int
)
;
```

I don't want to post issues that are about my own ineptitudes rather than problems with the tech, but I'm scratching my head here.
Thanks -
Tyler

**Comment by twalk4821** [comment]
Actually, you know what I think it's a problem with the sql itself. Sorry.

**Comment by twalk4821** [comment]
But if you could let me know if my policy creation process is correct, that would be much appreciated.

**Comment by jmccormick2001** [comment]
Hi,  what should work is to first create the cluster/database, make sure it
is running and healthy...

then, create your policy, then run "pgo apply yourpolicy
--selector=name=yourcluster" to
apply that policy.  You can verify that the policy was applied correctly by
looking
at the apiserver container log where a 'psql' command with your policy is
executed.  If there
is a problem with the policy being applied it will show up in that log.

hope that helps.
