### ISSUE TITLE
problems with policies

### ISSUE THREAD

**Issue by twalk4821** [CrunchyData/postgres-operator#147]
Hi -

Yeah, actually I am going to reopen this issue. Or well, this one is a repeat of one I closed a few hours ago. In trying to apply a policy, it seems like there is no effect. When I run the sql manually, all the tables and everything inserts fine. My process is:

1. pgo create policy mypolicy --in-file=myfile.sql
2. pgo apply mypolicy --selector=app=myapp
Status messages suggest this went fine, but when I check db as postgres user, nothing seems to be there.

Thanks,
Tyler

**Comment by twalk4821** [comment]
I see this in the postgres logs:

```
Waiting for postgreSQL to start...
timeseries2-84d95c7999-gfrvr:5432 - accepting connections
The database is ready for setup.sql.
SET
CREATE EXTENSION
CREATE EXTENSION
ALTER ROLE
CREATE ROLE
CREATE ROLE
CREATE TABLE
GRANT
CREATE DATABASE
GRANT
You are now connected to database "timescale" as user "postgres".
CREATE EXTENSION
CREATE EXTENSION
You are now connected to database "timescale" as user "testuser".
CREATE SCHEMA
CREATE TABLE
INSERT 0 1
INSERT 0 1
GRANT
Stopping database after primary initialization...
waiting for server to shut down.... done
server stopped
Tue Mar 27 00:07:17 UTC 2018
```

So I am wrong that setup.sql is not called. But it seems that the database is stopping too soon, perhaps because of #59 ?

**Comment by twalk4821** [comment]
What I am trying to use the policy for is initialize each database with the proper tables and extensions. I guess this is not necessary for the replicas or backups.

**Comment by jmccormick2001** [comment]
correct, for replicas any changes you make to the primary will be replicated down to the replica and data/objects will be included in any backups.   If a policy has syntax issues the error reporting right now is only found in the apiserver container log...I'd like to give the user better feedback on SQL errors and is something I'll add to my list.

**Comment by twalk4821** [comment]
Thanks. I just want to make it so that I don't have to run the sql on the new master for every cluster creation, but it's not a big deal. The sql runs fine when I pass it in through the psql command -f option. Now I'm trying to configure the image to include and be compatible with Timescale. One of the things is that, since I installed from source with make, I think I may have installed an older version (like 9.2). timescale needs 9.6 or 10.

**Comment by twalk4821** [comment]
It does use the configuration from /examples/postgresql.conf when building new databases, no? I can't tell if changes I make in there are affecting anything in the newly deployed db

**Comment by twalk4821** [comment]
I see now in the design docs to use the create script in the config examples folder

**Comment by twalk4821** [comment]
Doesn't seem like that did anything.

**Comment by twalk4821** [comment]
Tried creating a new strategy with folder "2'" and replacing with the timescale image. No luck with that so far

**Comment by twalk4821** [comment]
Update  on the configmap: problem was with namespaces. I'll have to get used to using those.. Sorry I want to keep you in the loop without being too annoying. Not sure what the best way to do that is.

**Comment by jmccormick2001** [comment]
email me at jeff.mccormick@crunchydata.com  I can offer some general help better from the email
