### ISSUE TITLE
pgbackrest check cmd not working from pgbackrest pod after a failover

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1475]
Hello,

While searching for the reason a dB backup failed one one of my clusters, I found the following (non)-issue:

In fact, I was used to perform `$ pgbackrest check` command from within the pgbackrest pod. 
This works as long as no failover occurred. If this occurred, you will get the following error:

```
$ pgbackrest check
ERROR: [055]: raised from remote-0 protocol on 'pg-hvr-db-cluster-prd-4be98890': unable to open missing file '/pgdata/pg-hvr-db-cluster-prd-4be98890/global/pg_control' for read
```
In fact, this is due to the fact, the directory under pgdata is not correct anymore, since the new primary has an extended name (eg: pg-hvr-db-cluster-prd-4be98890-wrxx).

To what w can see the outdated information is read from an ENV variable:
`PGBACKREST_DB_PATH=/pgdata/pg-hvr-db-cluster-prd-4be98890`

Temporarely changing this variable will make the check command succeed.

So my question: 
Does it have any side effect related to pgbackrest (backup, restore, ....)?

Thanks,
José

**Comment by andrewlecuyer** [comment]
@jose-joye there should be no impact/side-effect to Operator operation as a result of that environment variable, which is actually no longer utilized by the Operator.

When various `pgBackRest` jobs are run, e.g. `stanza-create`, `backup` or `restore` jobs, the `PGDATA` directory of the current primary is injected into the `pgBackRest` command by the Operator.  For instance, you will see something like this for a `stanza-create` job (note the `--db-path` flag at the end of the command):

```bash
time="2020-04-30T22:00:46Z" level=info msg="command is pgbackrest stanza-create  --db-host=10.129.0.97 --db-path=/pgdata/mycluster 
```

The `--db-path` flag overrides the `PGBACKREST_DB_PATH`, so the `PGBACKREST_DB_PATH` env var is essentially no longer utilized.  This strategy allows the Operator to dynamically adjust as the primary changes, e.g. following a failover, without having to update the env var and restart the `pgBackRest` repository pod.

You can therefore take a similar approach when running the `check` command, .e.g. specifiy the current primary's `PGDATA` dir using the  `--db-path` flag:

```
pgbackrest check --db-path=/pgdata/mycluster-cmcg
```

**Comment by jose-joye** [comment]
@andrewlecuyer : thanks for the quick answer!
