### ISSUE TITLE
Installation guide image missing.

### ISSUE THREAD

**Issue by jonathanleang** [CrunchyData/postgres-operator#1484]
**Describe the bug**
I tried to follow the installation guide and found pod error pulling image, because it is missing.

**To Reproduce**
1. Go to https://github.com/CrunchyData/postgres-operator#installation
2. Scroll down a few line
3. see the quick install steps, and do the following 
'''
kubectl create namespace pgo
kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/master/installers/kubectl/postgres-operator.yml
'''
4. k describe pod  pgo-deploy-xxxx -n pgo See error Failed to pull image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.0": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.0 not found

**Expected behavior**
pod ready

**Comment by jkatz** [comment]
Hi - the images have not been pushed yet. We are still going through our scanning and validation process. Please see #1482

I will let you know when they are ready.

Thanks!

**Comment by jkatz** [comment]
These are now published. Thanks!
