### ISSUE TITLE
Cannot create resource 

### ISSUE THREAD

**Issue by captainjapeng** [CrunchyData/postgres-operator#1488]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by jkatz** [comment]
There is no information in this ticket that can demonstrate that an issue exists, so I am closing it.
