### ISSUE TITLE
Any way to add a metrics side car after the cluster has been created?

### ISSUE THREAD

**Issue by twalk4821** [CrunchyData/postgres-operator#149]
?

**Comment by jmccormick2001** [comment]
I think the list of containers is still immutable if I'm up to date with the current status of that feature request in Kube...but for now, you could delete the postgres cluster, then re-add it back with the same name plus "--metrics" and you will effectively get the same cluster but this time with the metrics container added in....does require downtime while you bounce the postgres cluster but its typically just a few seconds.

**Comment by jmccormick2001** [comment]
what you will need to do is either deploy your own promethues and configure that to scrape the metrics end points, or use the crunchy 'metrics' example as found in the crunchy-containers repo...there is an example there under examples/kube/metrics that will start grafana/prometheus for you in a kube cluster and also configure it to scrape the metrics container endpoints, also includes a grafana dashboard...take a look at that project/repo on how to spin that up...

**Comment by twalk4821** [comment]
Ok will, do. Thanks.

**Comment by twalk4821** [comment]
Right now my hold up is to make the collect sidecar discoverable by the prometheus/grafana pods. Those are deployed, waiting for requests, but they don't seem to have discovered the collect pod. I already labeled the dual database/collect pod with the label crunchy-collect=true, but still no luck. Any ideas?

**Comment by twalk4821** [comment]
Oh hang on, I think it's working after all.. sorry about that

**Comment by jmccormick2001** [comment]
no prob
