### ISSUE TITLE
add quota limit inside pod

### ISSUE THREAD

**Issue by obeyler** [CrunchyData/postgres-operator#1491]
**What is the motivation or use case for the change? **
On our K8S cluster, we have this rule :
no pod can run if they don't have quota defined

**Describe the solution you'd like**
Could you add the opportunity to define quota (cpu/memory) for pod

**Please tell us about your environment:**
K8S baremetal or K8S install by bosh on vsphere/openstack

* Operating System:
ubuntu
* Where is this running ( Local, Cloud Provider)
Local
* Storage being used (NFS, Hostpath, Gluster, etc):
Local storage
* Container Image Tag:
* PostgreSQL Version:
Crunchy version 4.3.0

* Platform (Docker, Kubernetes, OpenShift):
K8S 1.16
* Platform Version:

**Additional context**

**Comment by jkatz** [comment]
AFAIK this functionality already exists. [`pgo create cluster`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/)

- `--cpu`: this will automatically set the Limit as well as the request
- `--memory`: by default, this will just set a memory request. If you want to enable the memory limit, you would use the `--enable-memory-limit` flag

Is there anything else you are looking for?

**Comment by jkatz** [comment]
I should note that similar flags exist for pgBackRest and pgBouncer, so limits can be deployed across the board for memory + CPU in Operator managed pods.
