### ISSUE TITLE
PGO Deployer Ansible commands fail

### ISSUE THREAD

**Issue by v3nturetheworld** [CrunchyData/postgres-operator#1496]
**Describe the bug**
The ansible/ansible-playbook commands appear to be broken due to an issue with being unable to write to /usr/sbin/.ansible/tmp. The pgoDeployer job fails to run because of this issue, and trying to run the playbook manually inside the pgoDeployer container (or any ansible command) results in the same error. Trying to run ansible-playbook -h for example both locally inside the container as well as an openshift cluster fails.

**To Reproduce**
1. docker run -it registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.0 bash
2. ansible-playbook -h

or on the cluster:
1.  kubectl apply -f postgres-operator.yml

**Expected behavior**
The installer to correctly start deploying crunchy 4.3

**Screenshots**
![image](https://user-images.githubusercontent.com/4187476/81238244-29c10180-8fc7-11ea-961b-b0de6fc3136e.png)

**Please tell us about your environment:**

* Operating System: CentOS7.6 & RHEL7.6
* Where is this running ( Local, Cloud Provider): Local and 3 node Openshift cluster
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos7-4.3.0
* PostgreSQL Version: 12
* Platform (Docker, Kubernetes, OpenShift): Docker and OpenShift
* Platform Version: 3.11

**Additional context**

**Comment by abour** [comment]
+1 I have the exact same issue.

I'm using minikube on mac

**Comment by jkatz** [comment]
Are you using the `postgresl.yml` on `master` or the `v4.3.0` one?

[https://github.com/CrunchyData/postgres-operator/blob/v4.3.0/installers/kubectl/postgres-operator.yml](https://github.com/CrunchyData/postgres-operator/blob/v4.3.0/installers/kubectl/postgres-operator.yml)

**Comment by v3nturetheworld** [comment]
@jkatz The postgres-operator.yml you linked fixes the issue. I was following the installation guide here [https://access.crunchydata.com/documentation/postgres-operator/4.3.0/installation/postgres-operator/](https://access.crunchydata.com/documentation/postgres-operator/4.3.0/installation/postgres-operator/) which links to the yaml on master. Could the docs be updated to reflect the 4.3 yaml?

**Comment by jkatz** [comment]
Hi @v3nturetheworld,

Yeah I agree. I originally had it as `master` in case we made mistakes post-release and wanted to correct them. I guess it went in the other direction 😓 I have a ticket open on the internal tracker to modify it to point to the "released" version, and will ensure we have that out there for the future.

Thanks, glad it worked!
