### ISSUE TITLE
Question about pgbouncer load-balancing support

### ISSUE THREAD

**Issue by xmarcoied** [CrunchyData/postgres-operator#1499]
**Which example are you working with?**
I am trying to create a crunchydata cluster with pgbouncer and loadbalancing support, so read operations sent to replicas (or round-robin between primary and replicas) and write operations to primary.
**What is the current behavior?**
All of the read and write operations are sent to primary service.

**What is the expected behavior?**
I am expecting the read operations (eg: SELECT) to be sent to replicas.

**Other information** (e.g. detailed explanation, related issues,  etc)
I created the cluster with pgo client using a command like this:
I installed the operator via ansible (postgres operator v4.3.0)
`pgo create cluster cluster1 --replica-count=1 --pgbouncer` and I have tried `pgo create cluster cluster` with `pgo create pgbouncer cluster1 --replicas 1`

I didn't change anything in the pgbouncer.ini
pgbouncer.ini:
```
[databases]
* = host=cluster1 port=5432 auth_user=pgbouncer

[pgbouncer]
listen_port = 5432
listen_addr = *
auth_type = md5
auth_file = /pgconf/users.txt
auth_query = SELECT username, password from pgbouncer.get_auth($1)
pidfile = /tmp/pgbouncer.pid
logfile = /dev/stdout
admin_users = pgbouncer
stats_users = pgbouncer
default_pool_size = 20
max_client_conn = 100
max_db_connections = 0
min_pool_size = 0
pool_mode = session
reserve_pool_size = 0
reserve_pool_timeout = 5
query_timeout = 0
ignore_startup_parameters = extra_float_digits
```

**Please tell us about your environment:**

* Operating System: Linux/Ubunu
* Where is this running ( Local , Cloud Provider): Minikube
* Container Image Tag: centos7-12.2-4.3.0
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
```
Name:           cluster1-pgbouncer-8546b8774f-mt2jg
Namespace:      pgouser2
Priority:       0
Node:           minikube/10.0.2.15
Start Time:     Thu, 07 May 2020 05:59:10 +0200
Labels:         crunchy-pgbouncer=true
                name=cluster1-pgbouncer
                pg-cluster=cluster1
                pg-pod-anti-affinity=preferred
                pod-template-hash=8546b8774f
                service-name=cluster1-pgbouncer
                vendor=crunchydata
Annotations:    <none>
Status:         Running
IP:             172.17.0.10
IPs:            <none>
Controlled By:  ReplicaSet/cluster1-pgbouncer-8546b8774f
Containers:
  pgbouncer:
    Container ID:   docker://57a092806970bcdf3f38dc574d92147f2f0583c7a6fb77ce5aa11a3e5bd872dd
    Image:          registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos7-12.2-4.3.0
    Image ID:       docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer@sha256:f3736e56fa2efb89f2582d70e65de229f74d8c40cbbfdc5a65ac6c87b98c1e78
    Port:           5432/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 07 May 2020 05:59:11 +0200
    Ready:          True
    Restart Count:  0
    Requests:
      memory:  24Mi
    Environment:
      PG_PASSWORD:              <set to the key 'password' in secret 'cluster1-pgbouncer-secret'>  Optional: false
      PG_PRIMARY_SERVICE_NAME:  
    Mounts:
      /pgconf/ from pgbouncer-conf (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  pgbouncer-conf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cluster1-pgbouncer-secret
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  21m   default-scheduler  Successfully assigned pgouser2/cluster1-pgbouncer-8546b8774f-mt2jg to minikube
  Normal  Pulled     21m   kubelet, minikube  Container image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos7-12.2-4.3.0" already present on machine
  Normal  Created    21m   kubelet, minikube  Created container pgbouncer
  Normal  Started    21m   kubelet, minikube  Started container pgbouncer
```
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by jkatz** [comment]
Load balancing is not a [feature of pgBouncer](https://pgbouncer.github.io/).

What you could do is add a line to explicit connect to the "replica" Service that is deployed on behalf of the Postgres Operator (Format `<clusterName>-replica` and then have your SELECT statements get routed to that. You would still have to point your SELECT statements to explicitly use the replica Service, but the replica does provide load balancing amongst the replicas.

In my experience, it's typically better to handle query load balancing at the application level (either via code you write, or your connection driver or adapter): your application will understand which queries are reads vs. writes better than a load balancer (e.g. if you're calling a function).

Hope this helps!
