### ISSUE TITLE
Question: automated upgrade scenario after failover

### ISSUE THREAD

**Issue by GeorgFleig** [CrunchyData/postgres-operator#1501]
Hi,

first of all thanks a lot for the 4.3.0 release. Happy to see many great improvements.

I have a question about the new upgrade mechanism. Will it work in the following scenarios?

### Scenario 1

- pg cluster with 2 replicas (async), cluster name: `pg1`
- some failovers happen
- current primary is one of the pods that used to be a replica

Two things came to my mind that caused trouble in previous releases during upgrades:

1. Scaling down the cluster so only the current primary is left was not possible without manual work. If I read the changelog, this is fixed now? So the auto upgrade does not have problems with this?
2. The left over primary will have a deployment name of `pg1-wbcd` for example (because it used to be a replica). This name is reflected on the PVC name and the data folder name on the volume. When the new cluster comes up it will take the volume `pg1` instead, which will not contain the latest database changes. My workaround was to rename the PVC and folder to `pg1`. Another, easier workaround is to trigger a failover until the deployment that was the original primary is primary again, then scale down and upgrade. How is this handled in the new auto upgrade?

### Scenario 2

- pg cluster with 2 replicas (**sync**), cluster name: `pg1`
- some failovers happen
- current primary is one of the pods that used to be a replica
- sync replica is the second replica -> the original primary is the async replica

Similar issues to scenario 1. But this time using pgo failover command is no solution. It will not be possible to promote the original primary to the new primary. Only the sync replica can become the new primary.

Thanks!

**Comment by tjmoore4** [comment]
Hello!

Glad to hear that you are enjoying the 4.3.0 release.

You are correct, the new upgrade procedure is designed to handle the failover/restore cases where the 'Primary PVC' name differs from the original cluster name. 

The relevant documentation is located here: [https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/)

You will note that the updated automated procedure has two main steps, the upgrade of the Postgres Operator itself, followed by the upgrade of the individual Postgres clusters.

In your above scenario `#1`, you would want to closely follow the automated upgrade procedure, as outlined in the link above. It will not require the manual steps you've mentioned (in fact, those may result in unexpected behavior by the automated procedure).

A few important notes, at this time, only upgrades from the Crunchy PostgreSQL Operator 4.1.0 and greater are supported, and the procedure is significantly different than the previous, manual upgrade process in that most resources (the clusters, CRDs, configmaps, secrets, etc.) are left in place.

For scenario `#2`, this should all be handled by the automated upgrade process, including replica scaledown and recreation. As recommended in the documentation, a test cluster should be created after the Operator has been upgraded to ensure all settings are correct and no misconfiguration will occur during the individual upgrade procedure. If further testing is desired, you can even create a new cluster in version 4.3.0, perform various failover scenarios, and then do a test upgrade on the new cluster, as upgrades are allowed ‘within’ 4.3.0.

Finally, the manual upgrade procedure is still an option, but only recommended for version 4.0 and below. Please note, there will be some forthcoming updates to the manual procedure to correct/improve the existing procedure.

I hope this is helpful, please let me know if you have any questions!

**Comment by GeorgFleig** [comment]
Thanks for your reply @tjmoore4. I will give the new update mechanism a try with some test clusters.

One follow-up question though (affects both scenarios):
How exactly will the operator ensure the new, updated primary has the latest data loaded? Will this happen through renaming of the pv and data folder or will it rely on the backup stored in the pgbackrest repo by the previous primary?

If it relies on pgbackrest repo, how is it guaranteed that the repo contains the latest data? The pgbackrest repo could be slightly behind because it gets data via wal archiving and not via streaming replication. Is it guaranteed that the pgbackrest repo contains the latest dataset once all pg pods are terminated during the upgrade?

The new primary coming up will get a pv with outdated data from a previous replica in both of my scenarios. So an up-to-date pgbackrest repo would be the only way to make sure no data is lost during an upgrade.

**Comment by tjmoore4** [comment]
You’re very welcome.

In regard to your question, while many elements of the cluster are recreated during the automated upgrade process, the PVCs for both the primary pod and the pgBackRest repo are preserved. On recreation, the new cluster deployment will point to these PVCs and their existing storage paths. As such, this allows the very latest data to be preserved. Any recreated replicas will then sync to this data.
