### ISSUE TITLE
client.pem missing

### ISSUE THREAD

**Issue by internetuser2008** [CrunchyData/postgres-operator#1515]
** Which example are you working with? **
https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator 
ver 4.3.0

**What is the current behavior?**
When running pgo version 
pgo version
FATA[0000] failed to set up TLS client: client certificate/key loading: open/ home/deployuser/.pgo/pgo/client.pem: no such file or directory

ls -l ./.pgo/pgo/*
-rw------- 1 deployuser deployuser     1285 May 13 00:05 ./.pgo/pgo/client.crt
-rw------- 1 deployuser deployuser     1675 May 13 00:05 ./.pgo/pgo/client.key
-rwxrwx--- 1 deployuser deployuser 42100329 May 13 00:05 ./.pgo/pgo/pgo
-rw------- 1 deployuser deployuser       14 May 13 00:05 ./.pgo/pgo/pgouser

**What is the expected behavior?**
client.pem not present 
did not see any entry for .pem in client-setup.sh
```
# Use the pgo.tls secret to generate the client cert files
kubectl get secret -n "${PGO_OPERATOR_NAMESPACE}" pgo.tls -o 'go-template={{ index .data "tls.crt" | base64decode }}' > $OUTPUT_DIR/client.crt
kubectl get secret -n "${PGO_OPERATOR_NAMESPACE}" pgo.tls -o 'go-template={{ index .data "tls.key" | base64decode }}' > $OUTPUT_DIR/client.key
# ensure the files are locked down to the specific user running this
chmod a-rwx,u+rw "${OUTPUT_DIR}/client.crt" "${OUTPUT_DIR}/client.key"

```
**Other information** (e.g. detailed explanation, related issues,  etc)
Was able to reproduce same in two separate setup Ubuntu 18.0

**Please tell us about your environment:**
Ubuntu 18.0 with microk8s

* Operating System: Ubuntu 18.0
* Where is this running ( Local , Cloud Provider): local
* Storage being used (NFS, Hostpath, Gluster, etc): Local storage
* Container Image Tag:
* PostgreSQL Version: n/a
* Platform (Docker, Kubernetes, OpenShift): kubernetes
* Platform Version: 1.18.2

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName: n/a
 kubectl describe pvc: n/a
 kubectl get nodes:
kubectl -npgo get nodes
NAME   STATUS   ROLES    AGE   VERSION
bkub   Ready    <none>   21d   v1.18.2-41+b5cdb79a4060a3
 kubectl log yourPodName: n/a

**Comment by jkatz** [comment]
The example there needs to be updated. The correct formulation is available in the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/)

```
export PGOUSER="${HOME?}/.pgo/pgo/pgouser"
export PGO_CA_CERT="/tmp/client.crt"
export PGO_CLIENT_CERT="/tmp/client.crt"
export PGO_CLIENT_KEY="/tmp/client.key"
export PGO_APISERVER_URL='https://127.0.0.1:8443'
```

**Comment by jkatz** [comment]
This is now corrected on the website.

**Comment by internetuser2008** [comment]
The problem is that it's not creating client.pem file and I didn't see anything in client-setup.sh that crates the .pem file. When running the pgo command it fail due to client.pem file not being there.

pgo version
FATA[0000] failed to set up TLS client: client certificate/key loading: open /home/deployuser/.pgo/pgo/client.pem: no such file or directory

**Comment by internetuser2008** [comment]
Thanks it works now.
