### ISSUE TITLE
Cluster creation fails when using PostGIS container image

### ISSUE THREAD

**Issue by VDVsx** [CrunchyData/postgres-operator#1516]
**Describe the bug**
Cluster creation fails when using the PostGIS container image as base, works fine when using the default image.
crunchy-postgres-gis:centos7-12.2-4.3.0 container fails to start due to missing environment variables.

Container logs:
```
INFO: Setting PGROOT to /usr/pgsql-12.
ERROR: PG_MODE environment variable is not set, aborting.

```

**To Reproduce**
1. After having minikube configured and running, get the v4.3.0 manifest: 
```
curl https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.3.0/installers/kubectl/postgres-operator.yml > postgres-operator.yml
```
2. Edit the file in order to deploy the pgo client in the cluster:
```
- name: PGO_CLIENT_CONTAINER_INSTALL
   value: "true"
```
3. Create a pgo namespace for the deployments and apply the manifest:
```
kubectl create namespace pgo
kubectl apply -f postgres-operator.yml
```
4. Create a cluster with the PostGIS image:
```
kubectl exec -n pgo deploy/pgo-client --  pgo create cluster -n pgo data-archive --ccp-image=crunchy-postgres-gis

```

**Expected behavior**
After a while the cluster is up and running

**Please tell us about your environment:**

* Operating System: Ubuntu 18.04
* Where is this running: local/minikube
* Storage being used: Hostpath
* Container Image Tag: postgres-operator:centos7-4.3.0/crunchy-postgres-gis:centos7-12.2-4.3.0
* PostgreSQL Version: 12.2
* Platform: Kubernetes
* Platform Version: 1.18

**Additional info**
I had to change pgo.yaml settings for hostpath since the accessMode is empty, that should not matter for this issue, and is also required to run the default image.

**Comment by VDVsx** [comment]
Sorry for the noise, looks like I was looking at old instructions(https://access.crunchydata.com/documentation/postgres-operator/3.5.2/operator-cli/), when using the ha image it works.

So:
`-ccp-image=crunchy-postgres-gis-ha`

instead of
`--ccp-image=crunchy-postgres-gis`

**Comment by metasim** [comment]
@VDVsx Thanks for following up. Had the same problem. Many thanks!
