### ISSUE TITLE
pgo 4.3.0: QoS of cluster Pod?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1526]
Hello,

This question is related to #1391 and #1453. 
We have started to play with the new version and it looks great :-)

For our deployment, we have set, for both CPU and Memory, the _request_ and _limit_ values (using the `--enable-memory-limit` flag).
Doing so, we were expecting to get a QoS of _Guaranted_ for the cluster pod. 
However, the pod has 2 containers (database and collect). Since _collect_ has request/limit not set, we are back to _Burstable_ level for QoS.

Is this behavior expected?

Thanks,
José

**Comment by jkatz** [comment]
That behavior would be expected. We would need to add a CRD attribute / flag to support setting those attributes for the metrics sidecar.

The "quick fix" would be to give the metrics sidecar the same resources as the database container which for a production database is likely a huge mismatch based on what each of them do, so Iw would not like to do that :smile:

The hot fix is to modify the deployment to give the metrics sidecar resources requests / limits.

**Comment by jkatz** [comment]
Opting for a solution somewhere in between "quick fix" and "full fix" per 82d93f7

**Comment by jose-joye** [comment]
Great!
Thanks
Jose

**Comment by dadez** [comment]
Hi @jkatz, thank you for delivering a fix so fast. 
Why didn't you set any requests values ?

**Comment by jose-joye** [comment]
If you only set the limit, the request is automatically set to the limit
José

**Comment by dadez** [comment]
Hi @jose-joye , thank you, I have tested and it's true, the collect container have both requests and limits with the same value

**Comment by jkatz** [comment]
Yes, this was a trick I learned from @cbandy yesterday, so credit to where credit is due.
