### ISSUE TITLE
Add extensions after cluster creation?

### ISSUE THREAD

**Issue by twalk4821** [CrunchyData/postgres-operator#153]
Hi -

I am wondering if there is currently any easy procedure for installing an extension after the cluster has already been deployed and populated. I just went through an extensive sync process and after the fact realized an additional extension would have been nice to include. Any support for this? Also relatedly is the notion of adjusting database configuration files without having to restart everything. 

Thanks - 
Tyler

**Comment by jmccormick2001** [comment]
sorry for the VERY late response, the answer is no, once the container is running you can't add extensions afterwards.

**Comment by denishpatel** [comment]
@jmccormick2001 Any chance to include plperl extension in postgis docker image?
