### ISSUE TITLE
HostPath not configured correctly

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/postgres-operator#155]
According to the directions, 

> NOTE: This will create and use /data on your local system as the persistent store for the operator to use for its persistent volume.

`/data` is **not** created when you run `make deployoperator`, this leads to chown errors when creating clusters.

**Comment by jmccormick2001** [comment]
@xenophenes  can you confirm this is still an issue?

**Comment by xenophenes** [comment]
considering it was never added to the Makefile, it's still an issue :) 

Options for solving it are:

1) Remove the segment in the docs stating that /data is created, include instructions on setting up HostPath if not present.
2) Modify deploy.sh to have /data be created by default with the appropriate permissions.

I can implement either/or, just let me know a preference @jmccormick2001

**Comment by xenophenes** [comment]
The original note was removed from the docs and there's documentation on properly configuring HostPath.
