### ISSUE TITLE
pgo-deployer 4.3.1 image not found

### ISSUE THREAD

**Issue by sapkra** [CrunchyData/postgres-operator#1557]
**Describe the bug**
I've tried to deploy the recently released version 4.3.1 but the image is not available.

**To Reproduce**
```bash
> docker pull registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.1
Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.1 not found: manifest unknown: manifest unknown
```

**Comment by jkatz** [comment]
Thanks for your excitement for the release. We just tagged the image a few hours ago. Pushes to public repositories occur over several days as they must go through scanners and final QA.

**Comment by sapkra** [comment]
Ok, interesting. I wanted to try it because I have some problems using 4.3.0 with OpenShift regarding the fs group which should be fixed in the new version.

**Comment by Phil-Taylor-IW** [comment]
Same here FYI - looking forward to 4.3.1

`docker pull registry.developers.crunchydata.com/crunchydata/postgres-operator:centos7-4.3.1
Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/postgres-operator:centos7-4.3.1 not found: manifest unknown: manifest unknown`

**Comment by CermakM** [comment]
Any update on this?

**Comment by Phil-Taylor-IW** [comment]
`➜ docker pull registry.developers.crunchydata.com/crunchydata/postgres-operator:centos7-4.3.1
Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/postgres-operator:centos7-4.3.1 not found: manifest unknown: manifest unknown
(⎈ |minikube:pgo)
postgres-operator/installers/ansible on tags/v4.3.0 [!] at ☸️  minikube (pgo) took 4s
➜ date
Tue 26 May 2020 21:55:17 NZST`

**Comment by internetuser2008** [comment]
Same error for me.

`19s         Warning   Failed              pod/pgo-deploy-vfcfd   Failed to pull image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.1": rpc error: code = Unknown desc = failed to resolve image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.1": no available registry endpoint: registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.1 not found
`

**Comment by jkatz** [comment]
The images have not been pushed out publicly yet.

I will forewarn that we may be skipping ahead to do a public push of 4.3.2, as you may have noticed due to a flurry of recent commits to the repository.

Thank you for your patience.

**Comment by ormandj** [comment]
@jkatz 4.3.2 is showing up as a release, but the images still do not exist. Is this by design?

**Comment by sapkra** [comment]
@ormandj Maybe because it's still a pre-release:
![image](https://user-images.githubusercontent.com/8087568/83794646-9569bd80-a69e-11ea-8bd4-978bd6ef551c.png)

**Comment by davi5e** [comment]
Seems to me very similar to George Carlin's pre-boarding rant 😂

I am waiting to the public release of the image...

**Comment by jkatz** [comment]
The images first are pushed to our private repositories. When that is finished, we then push them to the public ones. For this release cycle, that could be as early as tomorrow.

As we did not have the same issue that caused us to decide to not roll out the 4.3.1's publicly, we do not anticipate an issue making these available. I will fully address that in a comment tomorrow.

I'm glad you're very excited for the public release of the images -- I do think our build team does an excellent job in preparing them. In the interim, you can always play around with building them on your own with our [development environment](https://access.crunchydata.com/documentation/postgres-operator/latest/contributing/developer-setup/) instructions.

**Comment by jkatz** [comment]
I am pleased to report that v4.3.2 is now released. More information is here:
[https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator)

For more information on the release process, I left some commentary here:
[https://github.com/CrunchyData/postgres-operator/issues/1585#issuecomment-639543910](https://github.com/CrunchyData/postgres-operator/issues/1585#issuecomment-639543910)

Enjoy the release!

**Comment by brandonros** [comment]
Where is the Dockerfile for pgo-deployer?
