### ISSUE TITLE
S3 storage with Letsencrypt TLS Certificate

### ISSUE THREAD

**Issue by yaroslavkasatikov** [CrunchyData/postgres-operator#1560]
Hi team,
I have an s3 storage with Letsencrypt TLS Certificate. It works fine from browser or from curl. I added letsencrypt CA into a secret and created cluster with this command:

```
 pgo create cluster active --pgbouncer --replica-count=2   --pgbackrest-storage-type=local,s3   --pgbackrest-s3-key=KEY--pgbackrest-s3-key-secret=SECRET  --pgbackrest-s3-bucket=postgres-bucket  --pgbackrest-s3-endpoint=s3.my.s3.storage.com   --pgbackrest-s3-region=eu-west-1   --pgbackrest-s3-ca-secret=aws-s3-ca   --password-superuser=supersecrethippo   --password-replication=somewhatsecrethippo   --namespace=mypg   --password=opensourcehippo

```

It creates a cluster and puts my CA into clustername-backrest-repo-config, but active-stanza-create pod failed with this error:

```[yaroslav@yaroslav pgo]$ oc logs -f active-stanza-create-2wmvp
time="2020-05-20T13:48:03Z" level=info msg="pgo-backrest starts"
time="2020-05-20T13:48:03Z" level=info msg="debug flag set to false"
time="2020-05-20T13:48:03Z" level=info msg="backrest stanza-create command requested"
time="2020-05-20T13:48:03Z" level=info msg="backrest command will be executed for both local and s3 storage"
time="2020-05-20T13:48:03Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.128.0.31 --db-path=/pgdata/active && pgbackrest stanza-create  --db-host=10.128.0.31 --db-path=/pgdata/active --repo-type=s3]"
time="2020-05-20T13:48:03Z" level=info msg="command is pgbackrest stanza-create  --db-host=10.128.0.31 --db-path=/pgdata/active && pgbackrest stanza-create  --db-host=10.128.0.31 --db-path=/pgdata/active --repo-type=s3 "
time="2020-05-20T13:49:05Z" level=error msg="command terminated with exit code 95"
time="2020-05-20T13:49:05Z" level=info msg="output=[]"
time="2020-05-20T13:49:05Z" level=info msg="stderr=[ERROR: [095]: unable to verify certificate presented by 'postgres-bucket.s3.my.s3.storage.com:443': [2] unable to get issuer certificate\n]"
time="2020-05-20T13:49:05Z" level=error msg="command terminated with exit code 95"
```

if I try to use curl from debug pod for task - it works fine.

Could you please  help me with this issue? 
Many thanks,
Yaroslav

**Comment by jkatz** [comment]
Borrowing from [release notes](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.3.0/):

```--pgbackrest-s3-ca-secret specifies the name of a Kubernetes Secret that contains a key (aws-s3-ca.crt) to override the default CA used for making connections to a S3 interface```

Ensure that the name in the Secret of the CA cert is `aws-s3-ca.crt`

**Comment by yaroslavkasatikov** [comment]
Hi, yes, it is existed and it creates correct `aws-s3-ca.crt` file in `clustername-backrest-repo-config`.

Probably the issue is in crt. Look, I have this chain for my letencrypt cert:

ROOT: `CN = DST Root CA X3 ; O = Digital Signature Trust Co.`  -> Intermediate: `CN = Let's Encrypt Authority X3 O = Let's Encrypt C = US` ->  My cert: `CN = s3.my.dns.name`

What should be put in CA? As far as know `DST Root CA X3` is common cert which shold be stored in default TrustStore. So is it just intermediate or chain?

Anyway, as I told you before, curl works inside container without issue, so I'm a bit confusing.

**Comment by jkatz** [comment]
Did you put the whole certificate chain in the certfile?

**Comment by yaroslavkasatikov** [comment]
Hi @jkatz !
Thanks for your reply. Yes, it helped. I had put only intermediate. Now I changed it for full chain and SSL error gone. Unfortunately,   I got other error, which is realted to unavaolabilty s3 path-style using :(

**Comment by asoltesz** [comment]
I also had this problem with Backblaze B2 (they now supply a native S3 compatible API access).

OpenSSH didn't return the full chain for the region endpoint (possibly not set by Backblaze), so I had to manually lookup and export the DST Root CA X3 cert from Firefox and place into the secret (3 certs in this case: Backblaze, Let's Encrypt, Digital Signature Trust Co).

After this, the stanza-create finally succeeded.
