### ISSUE TITLE
multiple dbs in one cluster

### ISSUE THREAD

**Issue by zhubx007** [CrunchyData/postgres-operator#1562]
hi, How can I create multiple DBs in one cluster? Or do we support to do this action?

**Comment by jkatz** [comment]
This is presently a PostgreSQL function:

1. Log into PostgreSQL (via psql or what not) as a privileged user (e.g. superuser)
2. `CREATE DATABASE newdb;`

Perhaps we can add it as an Operator function, but it seems that this skews to be application. Bootstrapping with the single database name (`pgo create cluster --database=whatever`), which exists today, seems to be a fair compromise.

**Comment by zhubx007** [comment]
So do you mean, if I want to create multiple DBs in one cluster, now we can just login postgresql with superuser to run command "create database db"?
If I do this, do the multiple dbs follow the pg operator HA?
