### ISSUE TITLE
multiple DBs in one cluster still follow the pg operator HA?

### ISSUE THREAD

**Issue by zhubx007** [CrunchyData/postgres-operator#1564]
So do you mean, if I want to create multiple DBs in one cluster, now we can just login postgresql with superuser to run command "create database db"?
If I do this, do the multiple dbs follow the pg operator HA?

_Originally posted by @zhubx007 in https://github.com/CrunchyData/postgres-operator/issues/1562#issuecomment-632456693_

**Comment by jkatz** [comment]
Just to ensure we're saying the same thing...

`pgo create cluster` can create one or more PostgreSQL *clusters* that are managed by the Operator.

`pgo create cluster hippo` creates a cluster called `hippo`.
`pgo create cluster zebra` creates a cluster called `zebra`.

Within each cluster, you can have multiple PostgreSQL databases.

Let's say I log into `hippo` as a privileged user:

```
psql -h <hippo-hostname> -p 5432 hippo
```

I can create multiple databases within the `hippo` cluster:

```
CREATE DATABASE hippo_lake;
CREATE DATABASE hippo_tree;
```

etc.

The rules of HA/replication apply to a *cluster* as a whole, so every single object that is created in a PostgreSQL cluster. So yes, you can not only have multiple PostgreSQL clusters managed by the PostgreSQL Operator, but multiple databases within the clusters as well.
