### ISSUE TITLE
How to temporarily shutdown pgo and all postgresql clusters

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1570]
Hello,
We have several clusters managed by `pgo 4.2.2`. Some have only 1`primary` and some other have both `primary` and up to 1 `replica`.

We need to perform maintenance work on our network infrastructure and we want to minimize the risk around postgresql clusters during this period.
During that time, the k8s clusters will not be shutdown. However, we want to stop all postgresql clusters (and probably also pgo).

We were wondering what is the best way to achieve our goal?
Our initial thought is the following:

- Update the desired value of the pgo deployment to 0
- for each cluster:
   - if a replica is present, set the desired value of deployment to 0
   - set the desired value of the primary deployment to 0
   - set the desired value of the backrest deployment to 0
- perform the work on the network infrastructure
- for each cluster:
   - set the desired value of the backrest deployment to 1
   - set the desired value of the primary deployment to 1
   - if a replica is present, set the desired value of deployment to 1
- Update the desired value of the pgo deployment to 1

Is this a viable way to go?
Do you see a better approach?

Thanks for any advise
José

**Comment by jkatz** [comment]
[`pgo update cluster --shutdown`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_update_cluster/) :grin:

There is some discussion of how it works in the context of [multi-Kubernetes cluster deployments](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/) but it effectively does what you describe above.

**Comment by jose-joye** [comment]
Hello Jonathan,
Great!
However, for production, we are still in 4.2.2. 
This feature is available as of 4.3.x

So for now, we will apply the procedure described above

José
