### ISSUE TITLE
Remove pods etc. when CR is deleted

### ISSUE THREAD

**Issue by garyedwards** [CrunchyData/postgres-operator#1572]
**What is the motivation or use case for the change?**

I am testing your operator based on the [Creating a PostgreSQL Cluster with Kubernetes CRDs](https://info.crunchydata.com/blog/creating-a-postgresql-cluster-with-kubernetes-crds) guide and I can bring up a database successfully.

However when I want to take down / delete the database I remove the Pgcluster object from my cluster and the pod, pvc etc. remain.  Even if I then delete the pod by hand it is recreated.

My experience with other operators is that when the CR is deleted the operator handles deleting the appropriate and associated objects.

**Describe the solution you'd like**

The operator should recognize when a Pgcluster object is removed and delete the associated objects from the cluster.

**Please tell us about your environment:**

* Operating System: Fedora 32.20200520.0 (IoT Edition)
* Where is this running ( Local, Cloud Provider): Self hosted
* Storage being used (NFS, Hostpath, Gluster, etc): rancher.io/local-path
* Container Image Tag: centos7-4.2.2
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.17.2+k3s1

**Additional context**

N/A

**Comment by jkatz** [comment]
Thanks for the feedback! This is a duplicate of #1203 and what we are aiming to do based on #847 

The PostgreSQL Operator has a fair bit of history behind it and we have been moving toward adopting a fully available CR-only / declarative workflow. You can see this based on some of the [features added in 4.3.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.0) where now attributes that are edited in the pgclusters CR will cause the Operator to apply those changes across the managed clusters.

You will see this handled in an upcoming release.

Thanks!

**Comment by garyedwards** [comment]
Hi @jkatz thanks for your reply and work on this great project.  I can not believe I missed #1203 in my searching apologies I will close as a duplicate.  Look forward to seeing how things develop.
