### ISSUE TITLE
pgo 4.2.2: ' primary pod is not in Ready state' when performing a backup

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1581]
Hello,

We are starting to have this error when running backup on some clusters.
These clusters have at least the following pattern:

- They all have one replica
- Several failovers occurred
- we had to create new replica (and delete the initial one due to some issue)

The error is thrown from backrestimpl.go::getPrimaryPodName.
In fact for our primary, the label `service-name` points to the replica service instead of the primary one.

We have "solved" our issue by manually changing the label to point to the primary service....

Here also a side note, we have seems that there is an inconsistency on the method you use to check if the pod is primary. Within the same file in the `isPrimary` method you only check if the `service-name` label point to the primary service.
In other part of the code, you check the label `role=master` (which seems to be the right way)

José

**Comment by jkatz** [comment]
Oops, this was missed for awhile, sorry!

I think your analysis is correct, those `isPrimary` checks expose a race condition where the Service + Pod + service label could be out of sync for a moment. The `role` label, at present, provides the source of truth. Those should be updated.
