### ISSUE TITLE
Replicas and read-only queries 

### ISSUE THREAD

**Issue by paulbarbu** [CrunchyData/postgres-operator#1583]
Hello,

I cannot find anything related to this in the documentation, nor do I have the necessary PostgreSQL experience outside of Kubernetes to know this, so I have to ask.

[This documentation page](https://access.crunchydata.com/documentation/postgres-operator/4.3.1/architecture/overview/) says: `Now let’s say we want to have one replica available to run read-only queries against, but we want its hardware profile to mirror that of the primary instance. We can run the following command:`

If I create a cluster with a primary and one or more replicas, is the Kubernetes DNS round-robin used to direct queries both to the primary and the replica?
If yes, how are read-only queries detected and sent to the replica? Or is this something the application using the database should take care of, in which case the replica is just a standby?

**Comment by paulbarbu** [comment]
As a followup question:
Will the replica also use the WAL that it gets from the primary when a failover scenario happens?
Or it will just restore the last know backup and lose a part of the date (data that was written by the master since the last backup)

**Comment by jkatz** [comment]
> is the Kubernetes DNS round-robin used to direct queries both to the primary and the replica?

No.

The Operator will deploy two services, one for the primary, and one for all replicas. It is up to your application to choose how to route them, which is overall the better preferred way.

For example, let's save I have a query that reads:

`SELECT do_something();`

Without any knowledge of what `do_something` does, how would the Kubernetes service know if this is a read-only query, or if the function mutates the data and this is actually a write?

Many application frameworks provide ways to make it easy to divert queries to a read-write note and/or a read-only node. It's generally best to leave this up to your applications to decide, as they will know the query and how it is used better than any intermediary services.

> Will the replica also use the WAL that it gets from the primary when a failover scenario happens?

The short answer is yes*.

* The are a variety of factors that go into this, but generally a healthy replica is kept up-to-date by receiving WAL from a primary. The discussion of the nuances of all this would likely fill a small book and/or be the contents of a [50 minute talk](https://www.youtube.com/watch?v=wyFvB5j1QkI&t=1s) (or a series of talks), so it's easier to reduce it down to yes*.

**Comment by paulbarbu** [comment]
Thank you,

It makes perfect sense.

Barbu Paul - Gheorghe
