### ISSUE TITLE
Quick Start's postgres-operator.yml refers to unavailable image

### ISSUE THREAD

**Issue by feuGeneA** [CrunchyData/postgres-operator#1585]
**Describe the bug**
Quick Start instructions cannot be followed, because the referenced postgres-operator.yml refers to a non-existant image.  Specifically, I can see the following in my Kubernetes Dashboard: `Failed to pull image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.1": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.1 not found: manifest unknown: manifest unknown`

**To Reproduce**
1. Go to https://access.crunchydata.com/documentation/postgres-operator/4.3.1/quickstart/
2. Follow the instructions through "Step 2: Installation"
3. Attempt to go through "Step 3: Verification," but note that the actual results do not align with the expected results

**Expected behavior**
I expected the doc to refer me to a working postgres-operator.yml

**Please tell us about your environment:**

* Operating System: Debian Linux
* Where is this running: Local
* Storage being used: Hostpath
* Container Image Tag:
* PostgreSQL Version:
* Platform: Kubernetes
* Platform Version:
```bash session
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
In effect, this may be interpreted as a duplicate of https://github.com/CrunchyData/postgres-operator/issues/1557.  However, I would beg to differ.  While that Issue is specifically about v4.3.1, this Issue is simply about the doc being in a non-sequiter state.

I understand that there may be complications with getting the 4.3.1 image available, but if that's taking time, can you simply revert the doc to a known version that works?  As it stands now, I don't know what the previous working version was, and I can't seem to find that information anywhere.

[Edit: When initially raised, the error message cited v4.3.2, but I've reverified it for 4.3.1 and edited to match that, since that's the version used in the Quick Start.  I had tried with 4.3.2 and accidentally copied the error message from that experiment into the initial Issue report here.  FYI, the behavior was the same, "manifest unknown."]

**Comment by jkatz** [comment]
4.3.1 is not publicly available, and 4.3.2 has not been released. You can use 4.3.0 :smile:

**Comment by feuGeneA** [comment]
If I may politely push back, I'd like to contend that this Issue should not be closed.

I just tried successfully with 4.3.0, so now you've successfully gotten _me_ started with `postgres-operator`, but the next person that goes to the Quickstart will hit the same wall I did.

My intention was to raise an Issue against the doc, and the doc remains broken.

Perhaps you should change "latest" to point to 4.3.0?

**Comment by jkatz** [comment]
@feuGeneA I have reopened the issue.

4.3.1 is the latest release. We have not pushed 4.3.1 publicly as we will be pushing 4.3.2 soon. 4.3.1 does have some minor issues with the install but could be confusing, so instead of pushing those publicly (which would cause more confusion and raise more issues), we are going to push out 4.3.2.

I apologize for the inconvenience.

**Comment by feuGeneA** [comment]
Personally, I would expect "latest" to refer to the "latest _publicly_ available release".  The idea of a not-publicly-available release being labeled "latest" feels really weird to me.

If you're able to not-inconveniently re-target the semantics of "latest" to a previous version, I would recommend you consider it.

Inconveniences expected from an open source project.  No need to apologize.  I'm just trying to help out the next person to come down this path. :pray:

**Comment by slashk** [comment]
As a followup, does this mean that we need to replace all instances of `4.3.1` in the `postgres-operator.yml` with `4.3.0`? Why have you just rolled back the commit on this? 

Also, the docs now point to `4.3.2` and that image isn't out either.

**You have been down for 11+ days now.**

**Comment by qeternity** [comment]
Surprised to find this as well. At the very least, there should be consistency: the docs are public, and point to private and unreleased assets. I understand having private assets but then perhaps the docs shouldn't reference them.

**Comment by Phil-Taylor-IW** [comment]
Update on the 4.3.2 public image availability, please @jkatz ?

**Comment by jkatz** [comment]
Thank you for your patience, I am pleased to report that the containers are now available in our public registry:

[https://www.crunchydata.com/developers/download-postgres/containers/postgresql12](https://www.crunchydata.com/developers/download-postgres/containers/postgresql12)

I would like to take a moment to address some of the questions and comments about the release process and what happened during this release cycle.

The typical release process we follow is as follows:

- For major/minor releases, we have an alpha/beta process. We have started pushing beta containers to the developer portal to give feature previews and allow for more testing (we do love feedback!)
- For all releases, we have a release candidate process. Typically, there should only be one release candidate and this is code complete. Should we find a critical bug, etc. we may issue additional release candidates, but once we are satisfied with the release candidate, we will move to a GA stamp
- Once the GA stamp is applied, the build team starts building and validating the containers. These containers are pushed to several repositories: support subscribers have first access to the built images, followed by pushes out to public repositories.

As soon as the GA stamp is applied, the project is technically released. While we love the images that our build team makes (and we're glad you love them too!), the container images can be built independently following the [development environment instructions](https://access.crunchydata.com/documentation/postgres-operator/latest/contributing/developer-setup/). As such, at that point it is considered released. The container images are considered part of the packaging to make it easier for you to get started on the PostgreSQL Operator, and our goal is to roll them out in a timely fashion after.

With 4.3.1, after the GA stamp, we became aware of an issue in the `pgo-deployer` container that could present challenges in the installation process. This left us with two options:

1. Continue rolling out the 4.3.1 images knowing that issues would be open against the `pgo-deployer` container image.
1. Hold the 4.3.1 images and plan to release a 4.3.2 shortly thereafter, knowing that issues would be open against the missing 4.3.1 images.

No matter what, it is an issue. For this case, we chose Option 2, but if we run into this situation, future we may choose option 1.

In regards to the documentation being available, as mentioned, 4.3.1 was released. Even though the images were unavailable in the various public repositories, they could be built form the tag.

I hope this sheds some light on the decision making process, and I hope that you enjoy using version 4.3.2 and future versions to come.

**Comment by feuGeneA** [comment]
Thank you very much for the explanation, I really appreciate it.

If I may politely push back yet again, I'd like to contend that this is _still_ an issue.

In my mind, the problem is that the introductory quick start doc says absolutely nothing about building from source.  (Right? Am I just missing it?)  As someone new to Kubernetes as a whole, I was still trying to figure out what an "operator" even was, and it was not obvious to me that building from source was even an option.

As it stands now, if this situation recurs (if the code and docs are released but images are not) then the Quickstart will be a dead end once again.

What would make this feel resolved for me is if there were something in the Quickstart's Installation section that refers you to those instructions on how to build from source, and that tells you what do do next.  (Publish the build to a local docker tag?  And then modify `postgres-operator.yml` to refer to that tag? :shrug:)  It could be under a "just in case" or "worst case scenario" heading, or maybe even tucked away in some expandable/collapseable DIV or something, but without that additional clue the Quickstart still feels broken to me.

**Comment by jkatz** [comment]
Thank you for your feedback @feuGeneA. As this is an open source project, if you would like to submit a pull request over where you think this could be improved, I would be happy to review it.

**Comment by asoltesz** [comment]
@CrunchyData-In-General

Thanks for the hard work on the PGO operator.

I would also like to - constructively - recommend a release process improvement that allows for more consistent results.

I strongly believe that refreshing the documentation and posting the release page should only happen AFTER the images are posted. 

Something like this:
- Publish the Docker images (either CrunchyData Dev Portal or Docker Hub). Do not update the "latest" tags.
...
- whatever long-running tasks the release process needs and may result in a failed release
...
- Publish the updated documentation
- Create the release page in GitHUB
- Update the "latest" tags in the registries

This would also better handle the case of an aborted release.

CrunchyData is seemingly popular enough so that you will get constant bug reports about this otherwise. People just cannot wait for your stuff :)
