### ISSUE TITLE
Custom annotations for PVC

### ISSUE THREAD

**Issue by Thoro** [CrunchyData/postgres-operator#1587]
Is there a way to add custom annotations for each of the PVCs that are created? (i.e. wal archive / pgbackrest repo / primary or secondary)

My current storage provider initializes the PV with root:root ownership, and only an annotation can set a different ownership. I have current used 26:26 as ownership, which works for postgresql, but not for the pgbackrest archive (uid 2000).

Are there other uids in use?

**Comment by Thoro** [comment]
I have dabbled a bit in the code, and since the pvc templates are go templates there is an easy option to actually add this feature.

for me it would be enough to either 

have the HasPrefix / HasSuffix functions available in the template to evaluate if the current pvc ends with -pgbr-repo 

OR

Provide a separate variable that designates for which deployment the pvc will be used. 
i.e.  pgbr-repo / primary / replica / wal

**Comment by jkatz** [comment]
This is handled in PGO v5.0: [https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/customize-cluster/#annotations](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/customize-cluster/#annotations)
