### ISSUE TITLE
pgBackRest wal/backup information available?

### ISSUE THREAD

**Issue by Thoro** [CrunchyData/postgres-operator#1588]
Is there a command or a metric provider that gives me information about the current wal / last archived wal / last backup date / etc. so I can monitor a cluster appropriately?

**Comment by jkatz** [comment]
[pgo show backup](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_show_backup/)

I would suggest reading through the [common tasks with the pgo client](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/) guide which covers a lot of typical operational environment scenarios.

You can also go through one of the [guided tutorials](https://learn.crunchydata.com/kube).

**Comment by Thoro** [comment]
Thanks, but it's not exactly what I'm looking for.

-) It does display all created backups, but it does not display the latest received WAL archive.
-) It doesn't seem to be machine parsable, is there an option with json / yaml available?

(I would actually like to ask such question on slack or similar, is that available?)

**Comment by Thoro** [comment]
Actually I found that pgBackReset provides info command, which actually displays the WAL 

pgo show backup:

```
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1)
 ```

pgbackrest info
```
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1): 000000010000000000000001/00000002000000000000001B
```

Additionally it also provides the --output=json flag to provide machine readable output.

I guess 1) qualifies as a bug and 2) would be a nice feature to facility monitoring via i.e. nagios / zabbix / ...

otherwise, could the operator provides metrics for prometheus with these values?

for example there could be some nice metrics from the operator:

- last wal archive
- last (full/incremental/differential) backup
- up replicas
- up primaries
- status of services
- number of failovers (?)

Should I create additional issues for each of those 3 points?

**Comment by jkatz** [comment]
What the `pgo` command displays is directly from the JSON. You can query the API directly if you want the input. `pgo` just queries a RESTful API to get that information, and most calls return structured data.

All of the things that you are requesting are already features of the Operator, or are one degree away. The `pgo show backup` command will list out all of the last backups taken, if you have taken backups.

You can get the number of up replicas/primaries from the `pgo test` command. `pgo show backup` also has information about the Deployments/Services too, though it's better to get that from Kubernetes itself.

`pgo failover --query` / `pgo scaledown --query` will provide the replication lag from replicas. I believe those also have an `-o` flag.

The "# of failovers" is available in the "Timeline" part of the JSON response from `pgo scaldown --query` etc.

I do advise following that guide and playing around with the various options, as well as some experimentation.

We do not have a Slack channel, but we do provide additional help and setup as such through our [support subscriptions](https://www.crunchydata.com/about/value-of-subscription/).

**Comment by Thoro** [comment]
Thanks, I wasn't even thinking about the REST Api, since the examples in the documentation are just about creating a backup.

After checking the pgo code they provide actually everything I need.

I still believe that the `pgo-mac show backup` command is not displaying the min and max wals files correctly, because the server actually delivers them in the REST response, but they are not displayed on the cli.
