### ISSUE TITLE
create cluster: existing replicas are not reused

### ISSUE THREAD

**Issue by Thoro** [CrunchyData/postgres-operator#1589]
**Describe the bug**
After deleting a cluster with `pgo delete cluster hippo --keep-data --keep-backups` and the recreating with --replica-count=1 the previous replica is not recreated, but a new one is created.

**To Reproduce**
pgo create cluster hippo --replica-count=1
kubectl -n pgo get pod
=> you should see 2 up servers, master + replica
pgo delete cluster hippo --keep-data --keep-backups
pgo create cluster hippo --replica-count=1
kubectl -n pgo get pod
=> you see the previous master + a new replica instead of the old one
kubectl -n pgo get pvc
=> you see 2 pvc volumes for replicas and one for master

**Expected behavior**
If there is already a replica available, it should reuse the existing pvcs

**Please tell us about your environment:**

* Operating System: Centos 7
* Where is this running ( Local, Cloud Provider): local
* Storage being used (NFS, Hostpath, Gluster, etc): storageClass
* Container Image Tag: centos7-4.3.0
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): kubernetes
* Platform Version: 1.15.3

**Comment by jkatz** [comment]
This is expected behavior.
