### ISSUE TITLE
4.3.0: Metrics unable to start (invalid username) after recreate

### ISSUE THREAD

**Issue by Thoro** [CrunchyData/postgres-operator#1590]
**Describe the bug**
I recreated the cluster and added the metrics option, now the crunchy-collect container is unable to connect to the database.

Additionally it seems the password for the ccp_monitoring user is always "password", I am aware of PgmonitorPassword in the pgo.yml (but actually the entry is missing and only in the documentation)

Wouldn't it be preferable to have a unique password per cluster? As we have with the user itself?

**To Reproduce**
have Metrics: false in pgo.yaml.

pgo create cluster hippo
pgo delete cluster hippo --keep-data --keep-backups

pgo create cluster hippo --metrics

=> metrics container says it's ready, but logs an error message:

psql: error: could not connect to server: FATAL:  password authentication failed for user "ccp_monitoring"

The would mean that by passing the --metrics flag on cluster create the schema and user are not created in the existing cluster.

I did the cross check, if the --metrics flag is passed on the first create cluster it will correctly add the monitor schema and the user.

**Expected behavior**
If I recreate a cluster with --metrics it should add the schema and user to the existing database.

**Please tell us about your environment:**

* Operating System: Centos 7
* Where is this running ( Local, Cloud Provider) local
* Storage being used (NFS, Hostpath, Gluster, etc): storageClass
* Container Image Tag: centos7-4.3.0
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.15.3

**Comment by jkatz** [comment]
I believe CrunchyData/crunchy-containers#1236 handles this as it makes the metrics process idempotent.
