### ISSUE TITLE
4.3.0: Cpu and Memory limits not added to db deployments

### ISSUE THREAD

**Issue by Thoro** [CrunchyData/postgres-operator#1592]
**Describe the bug**
I have created a cluster with pgo create cluster hippo --cpu="1" --memory="2Gi" but the resulting deployment of the db does not have those resources set, the resources are empty.

The pgcluster configuration file also contains the resources:

```
  resources:
    cpu: "1"
    memory: 2Gi
```

**To Reproduce**
pgo create cluster hippo --cpu="1" --memory="2Gi"

=> check the resulting deployment, it will have resources: {} instead of 

```
resources:
  requests:
    cpu: 1
    memory: 2Gi
```

**Expected behavior**
Correct resources limits on requested containers.

**Screenshots**

**Please tell us about your environment:**

* Operating System: Centos 7
* Where is this running ( Local, Cloud Provider) local
* Storage being used (NFS, Hostpath, Gluster, etc): storageClass
* Container Image Tag: Centos7-4.3.0
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): kubernetes
* Platform Version: 1.15.3

**Comment by jkatz** [comment]
This is handled by #1567 and will be in an upcoming release.

**Comment by Thoro** [comment]
@jkatz  Any eta on that 4.3.2 release? Seems it fixed a bunch of bugs

**Comment by jkatz** [comment]
I believe it has no effect as resources are set earlier, but it does seem like it should be removed.
