### ISSUE TITLE
Feedback about using declarative/Gitops principles with this operator

### ISSUE THREAD

**Issue by aelbarkani** [CrunchyData/postgres-operator#1595]
**What is the motivation or use case for the change? **
This is a global feedback about the usability of this operator on a declarative/GitOps model, with ArgoCD for example. We have been testing the last month with @yaroslavkasatikov your operator and compare it with other Postgres operators in order to use it as the basis for a Postgres as a Service solution for our clients.
The conclusion to which we arrived is that the operator has strong adhesion to pgo CLI: it is almost impossible to operate a database without using the client, so it's very difficult to use it with yaml files only (actually there is no documentation about it, so we had to do some reversal engineering).
This makes the operator unusable in a declarative/gitops model, where everything should be described as yaml.

Here are some examples of the difficulties we encountered:
- Scaling up/down a cluster: it seems we need to create another resource pgreplica, instead of managing the number of replicas from pgcluster resource.
- Upgrading the cluster: we didn't find to way to replicate with yamls what pgo upgrade command does.
- Scheduled backup: we didn't find a way to do it with yamls.
- Point in time restore: same, we couldn't find a way to replicate --pitr-target behavior.

Is there any roadmap to support a more declarative model ? This is a very important prerequisite for K8S users, since it makes infrastructure more industrialized and reproducible.

**Describe the solution you'd like**
Some examples:
- Scaling up/down a cluster: make the replicas field in pgcluster the one which used to scale up/down the number of replicas.
- Upgrading the cluster: when modifying a version in pgcluster, the operator should create the corresponding tasks to perform a migration.
- Scheduled backup: support a field like scheduledBackup: "0 6 * * *" in pgcluster.
- Point in time restore: have a field in pgcluster that indicates the time target when restoring a database.

**Please tell us about your environment:**

* Operating System: CentOS
* Where is this running ( Local, Cloud Provider): Cloud Provider
* Storage being used (NFS, Hostpath, Gluster, etc): AWS EBS
* Container Image Tag: 4.3.0
* PostgreSQL Version: 10
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 4.4.3

**Comment by jkatz** [comment]
> Is there any roadmap to support a more declarative model 

Yes. We've kept #847 as a reminder that we continue to make things more declarative.

We've made strides towards this in 4.3 by making more elements declarative (e.g. managing cluster resources, working with pgBouncer, etc.), and will continue to do so. Keep in mind that this projects was one of the first Operators and has been around for several years and we continue to evolve based on how people user Operators and what is currently supported in all of the versions of Kubernetes, etc. that we support.

**Comment by jkatz** [comment]
I have linked this to #847 and will ensure your feedback is incorporated into consideration. Thanks!

**Comment by aelbarkani** [comment]
ok thanks !

**Comment by cristianrat** [comment]
> ok thanks !

I'm hitting a wall in deploying this from argocd.
When I use the Yaml flavour, the files are too big for argo
And the helm one, well... can't even make it run
Were you successful?
