### ISSUE TITLE
Support for multiple schedule of the same backup type?

### ISSUE THREAD

**Issue by binhnguyenduc** [CrunchyData/postgres-operator#1597]
For business requirements, I need to schedule multiple incremental backups during the day. I'm trying to set up schedules as follow:

```
    # Beginning of day
    pgo -n database create schedule
          --schedule-type=pgbackrest
          --pgbackrest-storage-type=local,s3
          --schedule="0 1 * * 1-5"
          --pgbackrest-backup-type=incr
          postgres-cluster

    # Midday
    pgo -n database create schedule
          --schedule-type=pgbackrest
          --pgbackrest-storage-type=local,s3
          --schedule="0 5 * * 1-5"
          --pgbackrest-backup-type=incr
          postgres-cluster

    # Before batch
     pgo -n database create schedule
          --schedule-type=pgbackrest
          --pgbackrest-storage-type=local,s3
          --schedule="30 12 * * 1-5"
          --pgbackrest-backup-type=incr
          postgres-cluster

    # After batch
    pgo -n database create schedule
          --schedule-type=pgbackrest
          --pgbackrest-storage-type=local,s3
          --schedule="30 13 * * 1-5"
          --pgbackrest-backup-type=incr
          postgres-cluster
```

Versions:
```
pgo client version 4.3.0
pgo-apiserver version 4.3.0
```

It seems impossible, since after the first schedule, I received the following error message:
`Schedule postgres-cluster-pgbackrest-incr already exists`

Could you please let me know if I can do that? And if so, how?
If not, maybe you could support naming for schedule so I can schedule multiple cron with the same backup type. 

Thank you very much for the awesome operator!

PS: I understand I could set up different kubernetes cronjobs to call pgo backup whenever I want and however I want. However, since PGO already support schedule cron-like jobs, I just think it would be nice to be able to do this with just pgo.

**Comment by jkatz** [comment]
Does this work?

```shell
pgo -n database create schedule
   --schedule-type=pgbackrest
   --pgbackrest-storage-type=local,s3
   --schedule="30 1,5,12,13 * * 1-5"
   --pgbackrest-backup-type=incr
   postgres-cluster
```

**Comment by binhnguyenduc** [comment]
I guess that could work. However, the options are still limited to the same minute (30) and day (1-5). It is still not possible if I would, say, have needs for incremental backup once daily on Saturday and Sunday.

**Comment by jkatz** [comment]
@binhnguyenduc we have been considering using CronJobs for awhile for a variety of reasons and having those managed as part of our CRDs. From there, yes we agree we would be able to give more flexibility, in addition to some other advantages from a maintenance perspective.

I'm not sold on the "different minute, same day" point for backup scheduling as I typically ran my backups on a consistent schedule (e.g. a full backup once a night, an incremental backup every 4 hours) which had a lot of advantages in my book, i.e. predictability and consistency. Of course, I understand that different business requirements dictate different schedules, and in the future Im' sure we will make this more flexible.

From an immediate standpoint, I believe the issue at hand is resolved, and I will include this use case as feedback to inform our roadmap on the move to using CronJob objectives.
