### ISSUE TITLE
CLI version to match Github tags

### ISSUE THREAD

**Issue by drzero42** [CrunchyData/postgres-operator#1600]
I am the maintainer for a tool called [vk](https://github.com/cellpointmobile/vk) which can install single-binary CLI tools from github releases for you, and automatically update them for you. This works by the tool being able to output which version it is, then looking up the latest release on Github, looking at the associated tag and then comparing them to see if a newer version is available.

The pgo CLI tool does not currently look to be able to report it's own version, only the version of the postgres-operator installed in a cluster. That makes it impossible for vk to handle pgo currently.

It would be great if a subcommand could be added that will report the client version, rather than the server version. The current version subcommand could also be augmented with a --client-only or similar argument, to only report the client version. This version information would need to follow the Github tags that are also used for releases. If Goreleaser is used, it is fairly simple to get this information added during build.

Being able to identify which version of the pgo tool is installed, is obviously also useful to people not using vk, so they won't have to guess whether it is time to update or not.

**Comment by jkatz** [comment]
`pgo version` already does this AFAICT:

```
pgo version
pgo client version 4.3.2
pgo-apiserver version 4.3.2
```

**Comment by drzero42** [comment]
@jkatz Ahh yes, so it does. However, it must talk to the pgo-apiserver for this to work apparently.
I was trying it out without having a pgo-apiserver up and running and was getting this error: `Error: The PGO_APISERVER_URL environment variable or the --apiserver-url flag needs to be supplied.`
I just expected that it would only report the apiserver version.
Being able to get the client version without having to talk to the apiserver is what I am really asking for here then :)

**Comment by drzero42** [comment]
The obvious role model here would be kubectl, where you can do `kubectl version --client` to get just the client's version number, without talking to a cluster.

**Comment by jkatz** [comment]
Seems reasonable. I've put up a PR.
