### ISSUE TITLE
Missing 4.3.2 container images

### ISSUE THREAD

**Issue by asoltesz** [CrunchyData/postgres-operator#1602]
The 4.3.2 release page is 2 days old but I cannot seem to find the Docker images for it.

Neither on Docker HUB (https://hub.docker.com/r/crunchydata/postgres-operator/tags?page=1&name=4.3)

Nor, on the CrunchyData Developer Portal: https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator

**Comment by jkatz** [comment]
These are available. For an explanation on the process for how these are rolled out, please see: https://github.com/CrunchyData/postgres-operator/issues/1585#issuecomment-639543910
