### ISSUE TITLE
Issue while using ansible playbook to deploy pgo 4.3.2

### ISSUE THREAD

**Issue by DinshKW44** [CrunchyData/postgres-operator#1603]
**Describe the bug**
When installing the pgo 4.3.2 on k8s cluster 1.16.3, it is failing with the below error:
time="2020-06-05T18:52:29Z" level=info msg="debug flag set to false"
time="2020-06-05T18:52:34Z" level=info msg="postgres-operator apiserver starts" func="main.main()" file="apiserver.go:109" version=4.3.2
time="2020-06-05T18:52:34Z" level=info msg="Pgo Namespace is [pgo]" func="apiserver.Initialize()" file="apiserver/root.go:107" version=4.3.2
time="2020-06-05T18:52:34Z" level=info msg="InstallationName is [devtest]" func="apiserver.Initialize()" file="apiserver/root.go:114" version=4.3.2
time="2020-06-05T18:52:34Z" level=info msg="apiserver starts" func="apiserver.Initialize()" file="apiserver/root.go:126" version=4.3.2
time="2020-06-05T18:52:34Z" level=info msg="loading PermMap with 60 Permissions\n" func="apiserver.InitializePerms()" file="apiserver/perms.go:189" version=4.3.2
time="2020-06-05T18:52:34Z" level=info msg="Config: pgo-config ConfigMap found, using config files from the configmap" func="config.getRootPath()" file="config/pgoconfig.go:744" version=4.3.2
time="2020-06-05T18:52:34Z" level=error msg="Unmarshal: error converting YAML to JSON: yaml: line 42: did not find expected key" func="config.(*PgoConfig).GetConfig()" file="config/pgoconfig.go:543" version=4.3.2
time="2020-06-05T18:52:34Z" level=error msg="error converting YAML to JSON: yaml: line 42: did not find expected key" func="apiserver.Initialize()" file="apiserver/root.go:134" version=4.3.2
time="2020-06-05T18:52:34Z" level=error msg="error in Pgo configuration" func="apiserver.Initialize()" file="apiserver/root.go:135" version=4.3.2

**To Reproduce**
1. Install the pgo version 4.3.2 using ansible. 
https://github.com/CrunchyData/postgres-operator/tree/v4.3.2/installers/ansible
2. The api-server, scheduler and operator crashloop with the error below:
level=error msg="Unmarshal: error converting YAML to JSON: yaml: line 42: did not find expected key" func="config.(*PgoConfig).GetConfig()" file="config/pgoconfig.go:543" version=4.3.2

**Expected behavior**
All the containers within the pod should come up without error.

**Screenshots**

**Please tell us about your environment:**

* Operating System: LInux
* Where is this running ( Local, Cloud Provider): Local K8s
* Storage being used (NFS, Hostpath, Gluster, etc): csi-rbd
* Container Image Tag: registry.developers.crunchydata.com/crunchydata/postgres-operator:centos7-4.3.2
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16.3

**Additional context**

**Comment by DinshKW44** [comment]
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"

[all:vars]

crunchy_debug='false'

# ==================
# Installation Methods
# One of the following blocks must be updated:
# - Deploy into Kubernetes
# - Deploy into Openshift

# Deploy into Openshift
# ==================
# Note: openshift_host can use the format https://URL:PORT
# Note: openshift_token can be used for token authentication
# ==================
# openshift_host=''
# openshift_skip_tls_verify=true
# openshift_user=''
# openshift_password=''
# openshift_token=''

# Deploy into Kubernetes
# ==================
# Note: Context name can be found using:
#   kubectl config current-context
# ==================
kubernetes_context='K1Atl'

# Create RBAC
# ==================
# Note: you may disable creating RBAC resources if they where already
# provisoned by a cluster admin.
# ==================
create_rbac='true'

# Namespace Mode
# ==================
# Note: this setting is only applicable if 'create_rbac=true'.
#
# When installing RBAC using 'create_rbac', the namespace mode determines
# what Cluster Roles are installed.  The default mode if a value is not
# specified here is "dynamic", which gives the Operator the full set of
# Cluster Roles to create/modify/delete namespaces, and also install RBAC
# within those namespaces in order to create PG clusters.  A value of
# "readonly" can also be specified, which allows the Operator to view
# namespaces, but not create/modify/delete them nor create  RBAC within
# them.  And finally "disabled" prevents the creation of any Cluster Roles,
# and therefore disables all namespace functionality.
# ==================
# namespace_mode='dynamic'

# Dynamic RBAC
# ==================
# Note: this setting is only applicable if 'namespace_mode' is set to
# 'readonly' or 'disabled'.
#
# When creating target namespaces during installation, this setting
# determines what RBAC is created within the target namespace.  If set to
# 'true', the RBAC created in those namespaces will allow the PostgreSQL
# Operator itself to create the ServiceAccounts, Roles and RoleBindings
# it requires to create PG clusters.  If set to 'false' (the default), 
# the installer will instead create the ServiceAccounts, Roles and
# RoleBindings), and the PostgreSQL Operator will not be granted the
# ability to create the RBAC it requires within those namespaces.
# ==================
# dynamic_rbac='false'

# ===================
# PGO Client Container Settings
# The following settings configure the deployment of a PGO Client Container
# ===================
# PGO Client Container Install
#pgo_client_container_install='false'

# PGO Apiserver URL - Url to be used to connect to the operator service
#pgo_apiserver_url='https://postgres-operator'

# PGO Client Secret
#pgo_client_cert_secret='pgo.tls'

# ===================
# PGO Settings
# The following settings configure the Crunchy PostgreSQL Operator
# functionality.
# ===================

# The name of the PGO installation
pgo_installation_name='devtest'

# PGO Admin Credentials
pgo_admin_username='admin'
pgo_admin_password='admin'

# PGO Admin Role & Permissions
pgo_admin_role_name='pgoadmin'
pgo_admin_perms='*'

# Namespace where operator will be deployed
# NOTE: Ansible will create namespaces that don't exist
pgo_operator_namespace='pgo'

# Comma separated list of namespaces Operator will manage
# NOTE: Ansible will create namespaces that don't exist
namespace='pgouser1'

# Crunchy Container Suite images to use. The tags centos7 and rhel7 are acceptable.
# CentOS7 images can be found in dockerhub: https://hub.docker.com/u/crunchydata
# RHEL7 images are available to Crunchy customers: https://access.crunchydata.com/login/
ccp_image_prefix='registry.developers.crunchydata.com/crunchydata'
ccp_image_tag='centos7-12.3-4.3.2'

# Name of a Secret containing credentials for container image registries.
# Provide a path to the Secret manifest to be installed in each namespace. (optional)
ccp_image_pull_secret=''
ccp_image_pull_secret_manifest=''

# Crunchy PostgreSQL Operator images to use.  The tags centos7 and rhel7 are acceptable.
pgo_image_prefix='registry.developers.crunchydata.com/crunchydata'
pgo_image_tag='centos7-4.3.2'

# Name of a Secret containing credentials for container image registries.
# Provide a path to the Secret manifest to be installed in each namespace. (optional)
#pgo_image_pull_secret=''
#pgo_image_pull_secret_manifest=''

# PGO Client Install
pgo_client_install='true'
pgo_client_version='v4.3.2'

# PGO Apiserver TLS Settings
#pgo_tls_no_verify='false'
#pgo_disable_tls='false'
#pgo_apiserver_port=8443
#pgo_tls_ca_store=''
#pgo_add_os_ca_store='false'
#pgo_noauth_routes=''

# PGO Event Settings
#pgo_disable_eventing='false'

# Set to 'true' to assign the cluster-admin role to the PGO service account.
# Needed for OCP installs to enable dynamic namespace creation
#  (see the PGO docs for more details).
pgo_cluster_admin='true'

# This will set default enhancements for operator deployed PostgreSQL clusters
backrest='true'
badger='false'
metrics='false'
sync_replication='false'

# This is used if one wants to disable the setting of the fsGroup for PostgreSQL
# which can occur in the default "restricted" deployment of OpenShift
disable_fsgroup='false'

# This will set the default pod anti-affinity for the deployed PostgreSQL
# clusters. Pod Anti-Affinity is set to determine where the PostgreSQL Pods are
# deployed relative to each other There are three levels:
#
# - required: Pods *must* be scheduled to different Nodes. If a Pod cannot be
#   scheduled to a different Node from the other Pods in the anti-affinity
#   group, then it will not be scheduled.
# - preferred (default): Pods *should* be scheduled to different Nodes. There is
#   a chance that two Pods in the same anti-affinity group could be scheduled to
#   the same node
# - disabled: Pods do not have any anti-affinity rules
#
# The `pod_anti_affinity` label sets the Pod anti-affinity for all of the Pods
# that are managed by the Operator in a PostgreSQL cluster. In addition to the
# PostgreSQL Pods, this also includes the pgBackRest repository and any
# pgBouncer pods. By default, the pgBackRest and pgBouncer pods inherit the
# value of `pod_anti_affinity`, but one can override the default by setting
# the `pod_anti_affinity_pgbackrest` and `pod_anti_affinity_pgbouncer` variables
# for pgBackRest and pgBouncer respectively
pod_anti_affinity='preferred'
pod_anti_affinity_pgbackrest=''
pod_anti_affinity_pgbouncer=''

# pgBadger Defaults
pgbadgerport='10000'

# pgBackRest Defaults
archive_mode='true'
archive_timeout=60
#backrest_port=''

# Log Defaults
log_statement='none'
log_min_duration_statement=60000

# Autofail Settings
disable_auto_failover='false'

# Scheduler Settings
scheduler_timeout=3600

# pgBackRest S3 Settings
#backrest_aws_s3_key=''
#backrest_aws_s3_secret=''
#backrest_aws_s3_bucket=''
#backrest_aws_s3_endpoint=''
#backrest_aws_s3_region=''

# Service Type for PG Primary & Replica Services
service_type='ClusterIP'

# ===================
# PostgreSQL Settings
# Default parameters for objects created when the database container starts
# such as: default database name and default username.
# ===================
# The database defaults to the name of the PostgreSQL cluster that is created
# unless a database name is specified in "db_name"
db_name=''
# db_password_age_days sets the length of time before a password for a
# PostgreSQL expires. This is default to "0" which is unlimited
db_password_age_days=0
db_password_length=24
db_port=5432
db_replicas=0
db_user='testuser'

# ==================
# Default Container Resource Configurations
# ==================
# Define the default container resource configurations that differ from the
# PostgreSQL Operator defaults. As a convenience, the current PostgreSQL
# Operator defaults are listed with each variable
#
# "default_instance_memory" represents the memory request for a PostgreSQL
# instance. For production instances, this should be at least 512Mi, but we
# model a number that is OK for just basic deployment testing. However, you
# really should make this value bigger
default_instance_memory='128Mi'

# "default_pgbackrest_repo_memory" represents the memory request for a
# pgBackRest repository
# default_pgbackrest_memory='48Mi'
#
# "default_pgbouncer_memory" represents the memory request for a pgBouncer
# instance
# default_pgbouncer_memory='24Mi'

# ==================
# Storage Settings
# ==================
# Which storage definitions to use when creating persistent volumes
# for a variety of uses.

backrest_storage='primary'
backup_storage='primary'
primary_storage='primary'
replica_storage='primary'
wal_storage='primary'



storage1_name='backrest'
storage1_access_mode='ReadWriteOnce'
storage1_size='30Gi'
storage1_type='dynamic'
storage1_class='rbd-default'
storage1_fs_group=26

storage2_name=''primary
storage2_access_mode='ReadWriteOnce'
storage2_size='3Gi'
storage2_type='dynamic'
storage2_class='csi-rbd-fast'
storage2_fs_group=26

storage3_name='backup'
storage3_access_mode='ReadWriteOnce'
storage3_size='50Gi'
storage3_type='dynamic'
storage3_class='rbd-fast'
storage3_fs_group=26

storage4_name='replica'
storage4_access_mode='ReadWriteOnce'
storage4_size='30Gi'
storage4_type='dynamic'
storage4_class='rbd-fast'
storage4_fs_group=26

# ==================
# Container Resource Configurations
# ==================
# Define container resource configurations that can be used to set CPU & memory requirements and limits
# for containers created by the PGO.  Also set default resource configs for various PGO container types.

#default_container_resources=''
#default_load_resources=''
#default_rmdata_resources=''
#default_backup_resources=''
#default_pgbouncer_resources=''

resource1_name='small'
resource1_requests_memory='512Mi'
resource1_requests_cpu=0.1
resource1_limits_memory='512Mi'
resource1_limits_cpu=0.1

resource2_name='large'
resource2_requests_memory='2Gi'
resource2_requests_cpu=2.0
resource2_limits_memory='2Gi'
resource2_limits_cpu=4.0

# ==================
# Metrics
# ==================
# Optional installation of Grafana and Prometheus optimized
# to work with the Crunchy PostgreSQL Operator

# Note: Ansible will create namespaces that don't exist
metrics_namespace='pgo'
exporterport='9187'

grafana_install='false'
grafana_admin_username='admin'
grafana_admin_password=''
#grafana_storage_access_mode='ReadWriteOnce'
#grafana_storage_class_name='fast'
#grafana_volume_size='1G'
#grafana_supplemental_groups=65534

prometheus_install='false'
#prometheus_storage_access_mode='ReadWriteOnce'
#prometheus_storage_class_name='fast'
#prometheus_volume_size='1G'
#prometheus_supplemental_groups=65534


# ==================
# Namespace Cleanup
# ==================
# The following settings determine whether or not the PGO and metrics namespaces (defined using
# inventory variables 'pgo_operator_namespace', 'namespace' and 'metrics_namespace') are deleted
# when deprovisioning. Please note that this will also result in the deletion of any non-PGO
# resources deployed in these namespaces, and cannot be undone. By default (and unless otherwise
# specified using the variables below), all namespaces will be preserved when deprovisioning.

#delete_operator_namespace='false'
#delete_watched_namespaces='false'
#delete_metrics_namespace='false'

**Comment by jkatz** [comment]
@DinshKW44 This is your error:

`storage2_name=''primary`

should be:

`storage2_name='primary'`

**Comment by DinshKW44** [comment]
Kill me
