### ISSUE TITLE
RBAC error

### ISSUE THREAD

**Issue by mw-0** [CrunchyData/postgres-operator#1605]
I have deployed using Ansible 4.3.2  using create rbac

create basic cluster in namespace

run pgo show status and Operator is error
 pgo status
Operator Start:          error
Databases:               3
Claims:                  3
Total Volume Size:       15Gi      

Database Images:
                         1      registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos7-12.3-4.3.2
                         1      registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos7-12.3-4.3.2
                         1      registry.developers.crunchydata.com/crunchydata/pgo-backrest-repo:centos7-4.3.2
                         5      registry.developers.crunchydata.com/crunchydata/pgo-backrest:centos7-4.3.2
                         1      registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-12.3-4.3.2

logs from the apiserver show
time="2020-06-08T09:25:31Z" level=error msg="error getting pods selector=[name=postgres-operator]" func="kubeapi.GetPods()" file="kubeapi/pod.go:49" version=4.3.2
time="2020-06-08T09:25:31Z" level=error msg="pods is forbidden: User \"system:serviceaccount:pgo:postgres-operator\" cannot list resource \"pods\" in API group \"\" in the namespace \"pgo\"" func="apiserver/statusservice.getOperatorStart()" file="apiserver/statusservice/statusimpl.go:64" version=4.3.2

I have edited the role  pgo-role in pgo namespace to give list permissions to the pods and the error has now gone.
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list

**Comment by cbandy** [comment]
It sounds like roles and bindings weren't created in the namespace in which you want to deploy postgres clusters. What are `create_rbac`, `namespace_mode`, and `namespace` variables set to in your inventory?

**Comment by mw-0** [comment]
Hi,
This is my variables.  If you view the pgo-role do you have pods there?
create_rbac='true'
namespace_mode='dynamic'
pgo_operator_namespace='pgo'
namespace='test1,test2,test3'

**Comment by jkatz** [comment]
Inspecting the code, it does not even look like "Operator Start Time" is producing a value that's helpful, and ultimately the uptime can be derived from `kubectl` (and more accurately at that). So I went ahead and removed that, which removes the need to grant additional RBAC.
