### ISSUE TITLE
pgo 4.3.2: Is it safe to use 'Patroni Rest API' instead of 'xxx-pgha-config cm' to update configuration settings?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1606]
Hello, 
Back in pgo 4.2.2, we decided to use the `patroni rest API` instead of the `<clusterName>-pgha-config` ConfigMap to update the configuration settings.

For us, it was necessary to know when the settings were actually applied. With the direct cm change, it was not really possible to be informed about the completion of the update of the settings.

Therefore, we did the following:
```
kubectl -n $NS port-forward svc/$CLUSTER_NAME 8009:8009 &

# Get the current version of the dynamic configuration
curl -s localhost:8009/config | jq .

# Change the existing configuration with new settings
curl -X PATCH -H "Content-Type: application/json" -d @/tmp/${CONTAINER_RESOURCES}.json http://localhost:8009/config | jq .

# Patroni will restart PostgreSQL only when restart is pending in order to apply some changes in the PostgreSQL config.
curl -s -XPOST -d '{"restart_pending":"true"}' http://localhost:8009/restart

# check patroni
curl -s localhost:8009/patroni | jq .

# close port-forwarding
fg
CTRL+C
```

In the pgo 4.3.x, you did a lot of work related to this CM and the DCS.
So our question is the following:
Is it still safe to update the setting directly using Patroni. Will the `<clusterName>-pgha-config` CM be automatically updated (as well as any required resource)?

Thanks for any hints
José

**Comment by andrewlecuyer** [comment]
As of v4.3.0 of the Operator, which includes the configuration enhancements you mentioned, all PostgreSQL and/or Patroni configuration changes should be made via the `<clusterName>-pgha-config` ConfigMap, and not by updating Patroni configuration resources directly.  This ConfigMap is now the source of truth for all PG and Patroni configuration, and the Operator will constantly reconcile its contents with cluster's configuration to ensure all configuration settings have been properly applied to either the cluster's DCS and/or any individual database instances as appropriate.  This therefore means any changes made directly to the DCS and/or local instance configuration settings will be overridden when this reconciliation occurs.

**Comment by jose-joye** [comment]
@andrewlecuyer ,
Thanks for the reply!
Is there any way, to know when the modification has been really applied to the cluster(s).
Currently, we use a modified extended version of the pgo-osb. In that sense, we will have access to any pgo REST API to check this if it is available.

Thanks,
José

**Comment by andrewlecuyer** [comment]
Once a change is made to the `dcs-config` section of the `<clusterName>-pgha-config` ConfigMap, that change is immediately applied to the actual DCS, which is the `<clusterName>-config` ConfigMap created by Patroni (and from there the config is reconciled every 60 seconds, allowing the operator to reattempt any config changes that may have failed on the first attempt, e.g. due to a transient error in the Kubernetes cluster).  Therefore, if you inspect the `config` annotation of the `<clusterName>-config` ConfigMap after making a change, you will see the change reflected.

```bash
$ kubectl get cm mycluster-config -o yaml | grep config: -A 7
    config: '{"postgresql": {"parameters": {"unix_socket_directories": "/tmp,/crunchyadm",
      "wal_level": "logical", "archive_mode": true, "archive_command": "source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh
      && pgbackrest archive-push \"%p\"", "archive_timeout": 60, "log_directory":
      "pg_log", "shared_buffers": "128MB", "temp_buffers": "8MB", "log_min_duration_statement":
      60000, "log_statement": "none", "work_mem": "4MB", "max_wal_senders": 6, "shared_preload_libraries":
      "pgaudit.so,pg_stat_statements.so"}, "use_slots": false, "recovery_conf": {"restore_command":
      "source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-get
      %f \"%p\""}, "use_pg_rewind": true}}'
```

Additionally, you can also view the actual DCS Config via the Patroni REST API `config` endpoint, e.g.:

```bash
$ curl localhost:8009/config
{"postgresql": {"parameters": {"unix_socket_directories": "/tmp,/crunchyadm", "wal_level": "logical", "archive_mode": true, "archive_command": "source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push \"%p\"", "archive_timeout": 60, "log_directory": "pg_log", "shared_buffers": "128MB", "temp_buffers": "8MB", "log_min_duration_statement": 60000, "log_statement": "none", "work_mem": "4MB", "max_wal_senders": 6, "shared_preload_libraries": "pgaudit.so,pg_stat_statements.so"}, "use_slots": false, "recovery_conf": {"restore_command": "source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-get %f \"%p\""}, "use_pg_rewind": true}}
```

And from there you can restart as you always have, e.g. by calling the Patroni `restart` endpoint, or you could also use the new `restart` command built into the `pgo` client (though we do not yet have support for only restarting those instances with a restart pending):

```bash
pgo restart mycluster
```

**Comment by jose-joye** [comment]
@andrewlecuyer 
We are currently using this method from a modified pgo-osb to update the configuration of the created pg instance based on the chosen plan.
This works great. However, we had to duplicate the type definition within our code (eg: DCSConfig Struct, ...).
All is available within the postgres-operator code but it is not exposed (it is under ./internal/operator/config/dcs.go).

Will it be possible to make it available in a future release so we can refer to the type instead of code duplication? :-)

Thanks
José
