### ISSUE TITLE
PITR restore is confusing in blog post (last backup must be provided manually)

### ISSUE THREAD

**Issue by asoltesz** [CrunchyData/postgres-operator#1607]
** Which example are you working with? **

Blog post (2019-APR-10)
https://info.crunchydata.com/blog/pgbackrest-point-in-time-recovery-using-crunchy-postgresql-operator

Current documentation (v4.3.2): https://access.crunchydata.com/documentation/postgres-operator/4.3.2/pgo-client/common-tasks/#disaster-recovery-backups-restores

**What is the current behavior?**

The blog post says that you need to manually set the backup ID for PITR to work correctly, otherwise, it will default to the last backup which may be later than the requested Point In Time.

The current documentation doesn't say anything about the need to manually specify a backup.

**What is the expected behavior?**

The operator automatically looks up the last backup in the pgBackrest repo, before the requested Point In Time and uses that (+the WAL) for the restore.

According to my tests, the operator behaves as I expect it and properly finds the last backup before the requested Point In Time and restores from it (and not from the latest backup).

I suspect that the need to manually set the backup was only needed in an earlier version of the operator and is now not needed.

If so, the blog post could have a warning on it that PITR semantics have changed in a major way (even though the post is only 1 year old).

**Comment by jkatz** [comment]
That blog post is about Operator 3.5.2.

I'm closing this as this is not a current issue with the Operator. Please feel free to comment on the blog post.

**Comment by asoltesz** [comment]
@jkatz 
For the sake of clarity (beginners like me reading this):

Could you confirm that with the current operator version (4.3.2), one only needs to provide the Point In Time target (timestamp) and restore will happen from the last backup before the timestamp + the WAL files leading up to the timestamp?

**Comment by jkatz** [comment]
Yes. This is due to a very nice feature added in [pgBackRest 2.24](https://pgbackrest.org/release.html#2.24), which is the version that Operator 4.3 is using:

> Auto-select backup set on restore when time target is specified. Auto-selection is performed only when --set is not specified. If a backup set for the given target time cannot not be found, the latest (default) backup set will be used

Kudos to the pgBackRest team for making it much more seamless :smile:

**Comment by asoltesz** [comment]
Thanks.
