### ISSUE TITLE
annotations for --service-type=LoadBalancer

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1608]
** Which example are you working with? **
https://access.crunchydata.com/documentation/postgres-operator/4.3.2/pgo-client/common-tasks/#advanced-operations

In the docs above you mention that I can set the ServiceType for a cluster deployment to LoadBalancer.  When running on AWS would be great to be able to use annotations for the LoadBalancer e.g. 
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

Is it possible to add annotations somehow?  If so how?  If not, this would be a great addition.

Thanks!

**Comment by jkatz** [comment]
You can modify the Service template. Assuming your Operator is in the `pgo` namespace:

1.`kubectl -n pgo edit configmap pgo-config`
1. Find `cluster-service.json`
1. Add the annotations you desire
1. Restart the Operator, e.g.

```shell
kubectl -n pgo scale deployment --replicas=0 postgres-operator
kubectl -n pgo scale deployment --replicas=1 postgres-operator
```

1. Deploy a new PostgreSQL cluster. the corresponding Service should have the annotation.

You could do this for the other Service templates that are in that file.

**Comment by alrooney** [comment]
awesome!  Thanks much.  Will give that a try.
