### ISSUE TITLE
PGO .26 doc error operator-docs.asciidoc

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/postgres-operator#161]
https://github.com/CrunchyData/postgres-operator/blob/pre26/docs/operator-docs.asciidoc

pgo createa user sally --selector=name=mycluster

should be create

**Comment by xenophenes** [comment]
@jmccormick2001  I'll take care of this one in my docs PR.

**Comment by xenophenes** [comment]
This can be closed out, FYI.
