### ISSUE TITLE
Allow changing of S3 back location with reinitialize  using pgo update cluster

### ISSUE THREAD

**Issue by gauravshankarcan** [CrunchyData/postgres-operator#1610]
- [ ] bug report
 - [x] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
once pgo create cluster is defined , there is no way to change s3 configurations.
In a multi Site configurations,  say 2 sites (On prem s3, not amazon aws)

Primary site ---> s3 bucket in secondary site ------> Replica in secondary site 

On the event of a primary site failure, we can definitely promote secondary site, but not change the s3 configuration on the secondary site to ship WAL logs are reinitialized back to primary site when the primary site is back online. 

**What is the expected behavior?**

pgo update/clone cluster mycluster -- s3URL="xxx" -S3bucket="xxxx" --S3="region"  -S3key="xxx" -S3secret="" 

**What is the motivation or use case for changing the behavior?**
In a multi site setup . During a failover and failback , cluster promotion should always ship logs  to external site.

This is definitely possible with AWS , but if the  customer is using an on prem s3, the deployment should account for s3 being in one of the on-prem datacenters of the cluster. And the datacenter can potentially go dead needing to re initialize the s3 location

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System: Any
 - Container Image Tag:  4.3.2
 - Operator Version: 4.3.2
 - Storage (NFS, hostpath, storage class): Any 
 - PostgreSQL Version: 12.3
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by jkatz** [comment]
This can now be done in [PGO 5.0](https://access.crunchydata.com/documentation/postgres-operator/v5/). A tutorial on [backup configuration](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/) can be found here: [https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/)
