### ISSUE TITLE
pgo 4.3.2: Is it still possible to perform a minor upgrade of postgresql using pgo?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1612]
With pgo 4.2.2, it was possible with the upgrade command to perform a minor upgrade of the postgresql version of a cluster: https://access.crunchydata.com/documentation/postgres-operator/4.2.2/pgo-client/reference/pgo_upgrade/

This seems not possible anymore with 4.3.2 : https://access.crunchydata.com/documentation/postgres-operator/4.3.2/pgo-client/reference/pgo_upgrade/

Am I missing something?

Thanks,
José

**Comment by jkatz** [comment]
Yes, `pgo upgrade` still performs the minor upgrade.

Presently minor versions of PostgreSQL are tied to an Operator version. Please see [compatibility](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/) for more details.

The `pgo upgrade` command is able to handle both Operator updates as well as PostgreSQL minor version updates.

**Comment by jose-joye** [comment]
@jkatz ,
Thanks for the answer.

So, If I understand you correctly, with the version 4.3.2 of pgo, it will not be possible to upgrade to  11.9 of PostgreSQL (in case a critical security issue is found with 11.8).
You would have to release a new pgo version first?

José

**Comment by jkatz** [comment]
PostgreSQL Operator update releases are timed with [PostgreSQL update releases](https://www.postgresql.org/developer/roadmap/).
