### ISSUE TITLE
arm64 image support

### ISSUE THREAD

**Issue by rur0** [CrunchyData/postgres-operator#1614]
**What is the motivation or use case for the feature? **
I own a 8 RPI4 kubernetes cluster that I am using for hosting a web app 

**Describe the solution you'd like**
Offer arm64 compatiable docker images on the repository 'registry.developers.crunchydata.com/crunchydata'

**Describe any alternatives you've considered**
n/a

**Please tell us about your environment:**

* Operating System:
* Where is this running: Local
* Storage being used: NFS
* Container Image Tag: n/a
* PostgreSQL Version: n/a
* Platform (Docker, Kubernetes, OpenShift): kubernetes (k3s)
* Platform Version:

**Additional context**

**Comment by jkatz** [comment]
We currently provide CentOS base images publicly and CentOS + UBI base images for support subscribers. We are not planning to support arm64 at this time.
