### ISSUE TITLE
Error cloning cluster with pgbackrest-storage-type=s3

### ISSUE THREAD

**Issue by kglebova** [CrunchyData/postgres-operator#1617]
Hi,

I'm using PGO v4.3. I want to clone pgo cluster with pgbackrest-storage-type=s3

pgo clone testdb testdbc1 --enable-metrics --pgbackrest-storage-source=s3 -n test-cl
Created clone task for:  testdbc1
workflow id is  ad7e8477-d05d-4f20-929a-ed4926f14e87

But I get an error while recovering:

ERROR: [055]: unable to load info file '/backrestrepo/testdbc1-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/testdbc1-backrest-shared-repo/backup/db/backup.info.copy':
       FileMissingError: raised from remote-0 protocol on 'testdbc1-backrest-shared-repo': unable to open missing file '/backrestrepo/testdbc1-backrest-shared-repo/backup/db/backup.info' for read
       FileMissingError: raised from remote-0 protocol on 'testdbc1-backrest-shared-repo': unable to open missing file '/backrestrepo/testdbc1-backrest-shared-repo/backup/db/backup.info.copy' for read
       HINT: backup.info cannot be opened and is required to perform a backup.
       HINT: has a stanza-create been performed?

File  /backrestrepo/testdbc1-backrest-shared-repo/backup/db/backup.info exist on backup storage.

 pgo show workflow ad7e8477-d05d-4f20-929a-ed4926f14e87 -n test-cl
       parameter           value
       ---------           -----
       clone 1.1: create pvc2020-06-12T08:06:02Z
       clone 1.2: sync pgbackrest repo2020-06-12T08:06:02Z
       clone 2: restoring backup2020-06-12T08:06:38Z
       pg-cluster          testdbc1
       task submitted      2020-06-12T08:06:02Z
       workflowid          ad7e8477-d05d-4f20-929a-ed4926f14e87

But database is no restored.
How can I solve this problem?

**Comment by jkatz** [comment]
Works 100% for me in 4.3.2:

```shell
pgo create cluster --pgbackrest-storage-type s3 --pgbackrest-s3-key=<redacted> --pgbackrest-s3-key-secret=<redacted> bear

# Wait for cluster to come up. Importantly, wait for the initial backup to complete. With S3 this can take a few moments

$ kubectl get pods
NAME                                          READY   STATUS      RESTARTS   AGE
backrest-backup-bear-chvg2                    0/1     Completed   0          10m
bear-59d74597df-bsm72                         1/1     Running     0          10m
bear-backrest-shared-repo-6ddc6ff8c8-449xx    1/1     Running     0          10m
bear-stanza-create-jnln6                      0/1     Completed   0          10m

# Create a clone:

pgo clone bear otter --pgbackrest-storage-source s3

# Wait for the clone to complete

$ kubectl -n jkatz get pods
NAME                                          READY   STATUS      RESTARTS   AGE
backrest-backup-bear-chvg2                    0/1     Completed   0          10m
backrest-backup-otter-mm2fq                   0/1     Completed   0          3m2s
bear-59d74597df-bsm72                         1/1     Running     0          10m
bear-backrest-shared-repo-6ddc6ff8c8-449xx    1/1     Running     0          10m
bear-stanza-create-jnln6                      0/1     Completed   0          10m
otter-7dfb5cbfc6-wcv54                        1/1     Running     0          3m31s
otter-backrest-shared-repo-6bbf54895d-ncqvk   1/1     Running     0          3m32s
otter-stanza-create-qwtz7                     0/1     Completed   0          3m5s
pgo-backrest-repo-sync-otter-vcjg-9tqws       0/1     Completed   0          4m46s
restore-otter-oyou-8kj9p                      0/1     Completed   0          4m31s
```
