### ISSUE TITLE
The way to change pgbouncer.ini 

### ISSUE THREAD

**Issue by kglebova** [CrunchyData/postgres-operator#1618]
Hi,
I'm using PGO v4.3.
And I use pgbouncer to connect to master and replica.
Every time I change pgbouncer.ini I have to deploy operator and recreate pgbouncer on the cluster. It would be nice to implement pgbouncer.ini changes through
 kubectl edit cm <pgbouncer-name-config>
 for each cluster separately where pgbouncer is created.

**Comment by jkatz** [comment]
Thanks for the feedback @kglebova. This is something we have thought about adding in a future release.

**Comment by jkatz** [comment]
However, I should mention that pgbouncer.ini is currently stored in the pgBouncer Secret, so you can achieve this functionality today by updating the Secret.
