### ISSUE TITLE
How is pgbouncer supposed to work in cluster?

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1619]
I added pgbouncer to my cluster as follows: 
```
pgo create pgbouncer retroelk
```
My cluster uses service type: LoadBalancer but the pgbouncer service does not have a load balancer when I do kubectl get svc -n pgo
```
$ kubectl get svc -n pgo
NAME                            TYPE           CLUSTER-IP       EXTERNAL-IP                                                                     PORT(S)                                                                       AGE
postgres-operator               ClusterIP      10.100.19.135    <none>                                                                          8443/TCP,4171/TCP,4150/TCP                                                    2d11h
retroelk                        LoadBalancer   10.100.78.225    a27769cd8ac5011ea9c89063c62fec76-0c77074de257b68d.elb.us-east-2.amazonaws.com   10000:30686/TCP,9187:32522/TCP,2022:30188/TCP,8009:32198/TCP,5432:30594/TCP   10h
retroelk-backrest-shared-repo   ClusterIP      10.100.164.124   <none>                                                                          2022/TCP                                                                      10h
retroelk-pgbouncer              ClusterIP      10.100.228.36    <none>                                                                          5432/TCP                                                                      8h
retroelk-replica                LoadBalancer   10.100.58.68     a87b51a47ac5511ea9c89063c62fec76-aea02c977938e079.elb.us-east-2.amazonaws.com   10000:30602/TCP,9187:32458/TCP,2022:30383/TCP,8009:30121/TCP,5432:32182/TCP   9h
```
I have the following questions about pgbouncer:

1. Should it have the same service type as the cluster?  That makes more sense to me.  But since it doesn't how do I set it's service type to LoadBalancer? 
2. I would have expected to have a pgbouncer instance for each replica too as I thought pgbouncer did not do load balancing between instances.  Is this correct behavior?  Is pgbouncer doing load balancing between the primary and replicas?
3. I am playing with pgbouncer because I will have a lot of pods accessing the pg db and therefore will have a lot of connections to the db.  What settings, if any, besides CPU and RAM which I can set via the operator should I be worried about to make sure the pg instances can handle a large number of connections e.g. 2000 connections?

I am using ver 4.3.2 of the crunchy data operator.

**Comment by jkatz** [comment]
Sounds like you're doing some interesting stuff that gets into a lot of nuances of how to optimize using PostgreSQL in a production environment. I'd suggest shooting an [email over](https://www.crunchydata.com/contact/) to discuss further, as this could get into a fairly lengthy exchange :smile:

**Comment by alrooney** [comment]
Will do!  Thanks.

**Comment by alrooney** [comment]
So reached out to have discussion specific to my use case but think it is worth having the discussion about how pgbouncer should work here as that might be helpful to others.  In this diagram you show that pgbouncer is load balancing between the replica and the primary:
![image](https://user-images.githubusercontent.com/1009422/84677497-ccd93500-aefc-11ea-8a17-f6a4e1b4e9a7.png)
I don't know too much about pgbouncer as we have typically done connection pooling in the application layer but the little research I had done made me think it was primarily doing connection pooling not load balancing.  And specifically on their site FAQ they say "PgBouncer does not have internal multi-host configuration."  So curious about how crunchydata is using PgBouncer and how if PgBouncer is pooling between the primary and replica does PgBouncer decide which requests to send to the primary vs the read replica?  If there's a blog I missed somewhere about this feel free to point me at that but couldn't find anything doing a quick search.

**Comment by jkatz** [comment]
By default, pgBouncer connects to the primary service. As such, even if a replica fails over, your applications can still maintain connection to pgBouncer and they are automatically rerouted to the newly promoted primary. In my testing, I've noticed the failover time tends to be faster with using pgBouncer, but YMMV.

However, one can always configure pgBouncer (presently the pgbouncer.ini file sits in a Secret, but that will likely change to a ConfigMap). An older setup explicitly defined the replica service as part of the pgBouncer definition: that is removed by default but one could add it back in if they wanted to route queries to it.

pgBouncer does not do load balancing, but for many reasons it's better for the application to handle load balancing than an external service. For example, how would an external service know where to route `SELECT do_something();`? Does that function change any underlying data? If it does, well, it has to go to the primary, but it doesn't, we could certainly route it to a replica.

I will note that we can add to our documentation around pgBouncer as it centers mostly around the "how to" vs. "what and why", possibly with a blog post or two for good measure. Outside of that, as this is not really a bug report / feature request I am going to close this ticket.
