### ISSUE TITLE
pgo 4.3.2 in Openshift 3.11 using postgres-operator-ocp311.yml with DYNAMIC_RBAC=true don't work

### ISSUE THREAD

**Issue by tobiasrdm** [CrunchyData/postgres-operator#1620]
**Describe the bug**
Deploy `v4.3.2` in Openshift 3.11 using `postgres-operator-ocp311.yml` with `DYNAMIC_RBAC: "true"` do not work: Pod postgres-operator Crash Loop Back-off.

[pod-postgres-operator.log](https://github.com/CrunchyData/postgres-operator/files/4773387/pod-postgres-operator.log)
`level=error msg="roles.rbac.authorization.k8s.io \"pgo-target-role\" is forbidden: attempt to grant extra privileges:`

**To Reproduce**
1. Using [openshift-client tools 3.11](https://github.com/openshift/origin/releases/tag/v3.11.0), execute `oc cluster up`
2. Execute `oc login -u system:admin`
3. Download https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.3.2/installers/kubectl/postgres-operator-ocp311.yml
4. Edit downloaded `postgres-operator-ocp311.yml` changing value of `DYNAMIC_RBAC` to `true`
5. Execute `oc create namespace pgo`
6. Execute `oc apply -f postgres-operator-ocp311.yml`
7. Wait for deploy complete and see `postgres-operator` Pod log in `pgo` namespace

**Expected behavior**
The Pod `postgres-operator` up and running without errors.

**Please tell us about your environment:**

* Operating System: Linux Mint 19.3
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: centos7-4.3.2
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): Openshift Origin
* Platform Version: 3.11

**Additional context**
[pod-postgres-operator.log](https://github.com/CrunchyData/postgres-operator/files/4773417/pod-postgres-operator.log)

**Comment by jkatz** [comment]
Yes, this is expected and why it's [set here](https://github.com/CrunchyData/postgres-operator/blob/master/installers/kubectl/postgres-operator-ocp311.yml#L73-L74) as such. We make mention of in the [release notes](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.2):

> For deployments of the PostgreSQL Operator using the pgo-deployer container to OpenShift 3.11 environments, a new template YAML file, postgresql-operator-ocp311.yml is provided. This YAML file requires that the pgo-deployer is run with cluster-admin role for OpenShift 3.11 environments due to the lack of support of the escalate RBAC verb. Other environments (e.g. Kubernetes, OpenShift 4+) still do not require cluster-admin.

**Comment by tobiasrdm** [comment]
Is there any way to deploy with `DYNAMIC_RBAC=true` in Openshift 3.11?
If not, what are the required RBAC configurations?

**Comment by jkatz** [comment]
The installer handles this for the `NAMESPACE` that you specify in it. If you need to add additional namespaces to be watched, you can use the [`add-targeted-namespace.sh`](https://github.com/CrunchyData/postgres-operator/blob/v4.3.2/deploy/add-targeted-namespace.sh) script.

The RBAC required is documented in the [Namespace](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/) architecture page.
