### ISSUE TITLE
grafana never shows cluster as up in overview dashboard due to ccp_is_in_recovery_status

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1621]
**Describe the bug**
Cluster appears to be working correctly but grafana overview dashboard shows cluster as down

![image](https://user-images.githubusercontent.com/1009422/84576449-ddfe3680-ad82-11ea-9f21-ca6b2187db82.png)

Looking at how this metric is constructed this seems to be due to ccp_is_in_recovery_status prometheus metric reporting a value of 2.  

This is the metric:
pg_up{job="[[pgnodes]]"} / ccp_is_in_recovery_status{job="[[pgnodes]]"}

pg_up returns 1
and
ccp_is_in_recovery_status returns 2

**To Reproduce**
1. Install pgo ver 4.3.2
2. Install grafana and prometheus using ansible
3. Create a pg cluster.
4. Go to grafana and the pg overview dashboard and note that the instances show "down"

**Expected behavior**
grafana dashboard should show instances as "up" or not "down"

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
AWS EKS
* Storage being used (NFS, Hostpath, Gluster, etc):
io1 
* Container Image Tag:
centos7-11.8-4.3.2
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
k8s 1.15
* Platform Version:
1.15
**Additional context**
$ pgo show config
BackrestStorage: io1-15-encrypted
BackupStorage: io1-15-encrypted
BasicAuth: ""
Cluster:
  Backrest: true
  BackrestPort: 2022
  BackrestS3Bucket: ""
  BackrestS3Endpoint: ""
  BackrestS3Region: ""
  Badger: false
  CCPImagePrefix: registry.developers.crunchydata.com/crunchydata
  CCPImageTag: centos7-11.8-4.3.2
  Database: ""
  DefaultBackrestMemory: 48Mi
  DefaultInstanceMemory: 128Mi
  DefaultPgBouncerMemory: 24Mi
  DisableAutofail: false
  DisableFSGroup: false
  DisableReplicaStartFailReinit: false
  EnableCrunchyadm: false
  ExporterPort: "9187"
  Metrics: true
  PGBadgerPort: "10000"
  PasswordAgeDays: ""
  PasswordLength: "24"
  PgmonitorPassword: ""
  PodAntiAffinity: preferred
  PodAntiAffinityPgBackRest: ""
  PodAntiAffinityPgBouncer: ""
  Policies: ""
  Port: "5432"
  Replicas: "0"
  ServiceType: ClusterIP
  SyncReplication: false
  User: testuser
Pgo:
  Audit: false
  ConfigMapWorkerCount: null
  ControllerGroupRefreshInterval: null
  NamespaceRefreshInterval: null
  NamespaceWorkerCount: null
  PGClusterWorkerCount: null
  PGOImagePrefix: registry.developers.crunchydata.com/crunchydata
  PGOImageTag: centos7-4.3.2
  PGReplicaWorkerCount: null
  PGTaskWorkerCount: null
PrimaryStorage: io1-15-encrypted
ReplicaStorage: io1-15-encrypted
Storage:
  glusterfs:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 100Gi
    StorageClass: glusterfs-storage
    StorageType: dynamic
    SupplementalGroups: ""
  gp2:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 100Gi
    StorageClass: gp2
    StorageType: dynamic
    SupplementalGroups: ""
  hostpathstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: ""
  io1-15-encrypted:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 100Gi
    StorageClass: io1-15-encrypted
    StorageType: dynamic
    SupplementalGroups: ""
  nfsstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: "65534"
  nfsstoragered:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: "65534"
  primarysite:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 4G
    StorageClass: primarysite
    StorageType: dynamic
    SupplementalGroups: ""
  replicastorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 700M
    StorageClass: ""
    StorageType: create
    SupplementalGroups: ""
  storageos:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 5Gi
    StorageClass: fast
    StorageType: dynamic
    SupplementalGroups: ""
WALStorage: ""

**Comment by alrooney** [comment]
```
$ pgo status
Operator Start:          2020-06-13 16:25:30 +0000 UTC
Databases:               3
Claims:                  3
Total Volume Size:       200Gi     

Database Images:
                         2	registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-11.8-4.3.2
                         2	registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos7-11.8-4.3.2
                         1	registry.developers.crunchydata.com/crunchydata/pgo-backrest-repo:centos7-4.3.2
                         2	registry.developers.crunchydata.com/crunchydata/pgo-backrest:centos7-4.3.2

Databases Not Ready:

Labels (count > 1): [count] [label]
	[4]	[vendor=crunchydata]
	[3]	[pg-cluster=retroelk]
	[2]	[pgo-version=4.3.2]
	[2]	[crunchy-pgha-scope=retroelk]
	[2]	[pgo-pg-database=true]
	[2]	[crunchy_collect=true]
	[2]	[workflowid=c0c68ffe-a7f9-476b-a9ac-8b2d96da3199]
	[2]	[service-type=LoadBalancer]
	[2]	[pg-pod-anti-affinity=]
```
```
$ pgo show cluster --all

cluster : retroelk (crunchy-postgres-gis-ha:centos7-11.8-4.3.2)
	pod : retroelk-594bfd7555-sjmr7 (Running) on ip-10-0-21-223.ec2.internal (2/2) (primary)
	pvc : retroelk
	pod : retroelk-okkj-948b7f9c8-nlvrn (Running) on ip-10-0-21-223.ec2.internal (2/2) (replica)
	pvc : retroelk-okkj
	resources : Memory: 128Mi
	storage : Primary=50Gi Replica=50Gi
	deployment : retroelk
	deployment : retroelk-backrest-shared-repo
	deployment : retroelk-okkj
	service : retroelk - ClusterIP (172.20.217.219)
	service : retroelk-replica - ClusterIP (172.20.251.120)
	pgreplica : retroelk-okkj
	labels : autofail=true crunchy_collect=true deployment-name=retroelk pg-cluster=retroelk pg-pod-anti-affinity= service-type=LoadBalancer crunchy-pgbadger=false crunchy-pgha-scope=retroelk name=retroelk pgo-backrest=true pgo-version=4.3.2 pgouser=admin workflowid=c0c68ffe-a7f9-476b-a9ac-8b2d96da3199 
```
```
$ pgo test retroelk

cluster : retroelk
	Services
		primary (172.20.217.219:5432): UP
		replica (172.20.251.120:5432): UP
	Instances
		primary (retroelk-594bfd7555-sjmr7): UP
		replica (retroelk-okkj-948b7f9c8-nlvrn): UP
```

**Comment by jkatz** [comment]
Sometimes it takes some time to start showing statistics in the Grafana dashboard. I have yet to pin down why.

**Comment by alrooney** [comment]
I'm getting stats in grafana just this particular stat seems off.  I believe the ccp_is_in_recovery_status stat is a crunchydata specific stat isn't it?  I looked in the code but couldn't find what it means.  I'm getting that stat but it is 2?  Would you expect that to return 2 with the config of one replica?

**Comment by jkatz** [comment]
[Operator 4.5](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0) received a major update to [monitoring](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/), which should resolve this issue. Thanks for reporting!
