### ISSUE TITLE
very problematic pgo client

### ISSUE THREAD

**Issue by tirelibirefe** [CrunchyData/postgres-operator#1622]
I've on-prem bare-metal Kubespray Kuebrnetes 1.18 on vSphere. 
Whenever I attempt to install postgres-operator, I lost hours with pgo client. There is no enough documentation. There is no Istio connection description, there is no enough pgo container installation documentation, there is no receipes to create custom pgo client certificates.

I use certificates in .pgo folder. It doesn't connect.
I used certificates in pgo.tls secret, it doesn't connect.
I used fqdn, it doesn't connect, I used hostname, no luck.
I used Istio millions of combinations, mutualTLS, ISTIO_ MUTUAL, simple tls, without tls, PASSTHROUGH etc. it never connects.
I used LoadBalancer instead of ClusterIP, it doesn't connect.

Could you please advise what I'm missing? I'm puling my hairs here.

```
`kikadmin@vdi-mk2-ubn:~$ cat .bashrc | grep pgo
export PGO_OPERATOR_NAMESPACE=pgo
export PATH="/home/kikadmin/.pgo/pgo:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/bin/istio-1.6.2/bin:/snap/bin"
export PGOUSER="/home/kikadmin/.pgo/pgo/pgouser"
export PGO_CA_CERT="/home/kikadmin/.pgo/pgo/client.crt"
export PGO_CLIENT_CERT="/home/kikadmin/.pgo/pgo/client.crt"

export PGO_CLIENT_KEY="/home/kikadmin/.pgo/pgo/client.key"
kikadmin@vdi-mk2-ubn:~$ cat /etc/hosts
127.0.0.1       localhost
127.0.1.1       vdi-mk2

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

192.168.215.21 pg-operator

kikadmin@vdi-mk2-ubn:~$ ls .pgo/pgo/
client.crt  client.key  pgo  pgouser

kikadmin@vdi-mk2-ubn:~$ pgo version --debug
DEBU[0000] debug flag is set to true
DEBU[0000] in initConfig with url=https://pg-operator:443
DEBU[0000] GetSessionCredentials called
DEBU[0000] PGOUSER environment variable is being used at /home/kikadmin/.pgo/pgo/pgouser
DEBU[0000] pgouser file found at /home/kikadmin/.pgo/pgo/pgouser contains admin:pgbeytepe
DEBU[0000] [admin pgbeytepe]
DEBU[0000] username=[admin] password=[pgbeytepe]
DEBU[0000] setting up httpclient with TLS
DEBU[0000] GetTLSTransport called
DEBU[0000] version called
DEBU[0000] ShowVersion called
DEBU[0000] https://pg-operator:443/version
Error: Get https://pg-operator:443/version: dial tcp 192.168.215.21:443: connect: connection refused
kikadmin@vdi-mk2-ubn:~$
`
```

**Comment by jkatz** [comment]
Adding TLS certificate for the `pgo` client is discussed here: [https://access.crunchydata.com/documentation/postgres-operator/latest/security/api-encryption-configuration/](https://access.crunchydata.com/documentation/postgres-operator/latest/security/api-encryption-configuration/).

The error message here:

```
Error: Get https://pg-operator:443/version: dial tcp 192.168.215.21:443: connect: connection refused
```

Seems to indicate that if that is indeed the PostgreSQL Operator API server, it is not listening on port 443. The default port it listens on is 8443, which is listed in the [installation prerequisites](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/prerequisites/). You may want to set [`PGO_APISERVER_URL`](https://access.crunchydata.com/documentation/postgres-operator/4.3.2/pgo-client/) to `https://192.168.215.21:8443`. That environmental variable is covered in a bunch of places, including the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/).

We do not provide guidance for Istio as we do not support it. We have had reports of strange behaviors with Istio (which may be in some past closed tickets).

Lastly, I would counter the "lack of documentation" claim around the `pgo` client. In addition to detailed [installation documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/pgo-client/), there is also a comprehensive guide on [how to use it](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/). While it may not cover every single scenario, it should help with the vast majority of daily usage. There is also a `pgo-client` container that exists as well which helps with installation (particularly if you can execute commands from it in a Kube-native way).

(I will admit that the the `pgo-client` container itself likely needs a bit more documentation as it appears we "buried the lede" but that can be easily remedied).

Outside of reported bugs, most issues with the `pgo` client have tended to be around either configuration or the behavior/configuration of some other application within the deployment environment, such as Istio or Calico.
