### ISSUE TITLE
Backups don't run when master evicted

### ISSUE THREAD

**Issue by djcooklup** [CrunchyData/postgres-operator#1623]
When master pod evicted (ie pod remains but status failed with new master pod), scheduled and manual backups fail to run with following message in operator container of postgres-operator:

`More than one primary found when creating backrest job`

The backup job gets deleted and makes it unclear that things are actually failing, however i'm uncertain if that's expected

**Steps to repro**
1) Trigger eviction on master pod
2) Either scheduled backup or manual backup execution eg `pgo backup a --pgbackrest-storage-type s3 -n pgo`
3) Backup not taken

**Expected behavior**
I'd propose either backup runner should only care about non failed pods, or role:master label should be removed from failed pods

**Environment**
postgres-operator 4.3.0
kubernetes 1.16.9 on aks

**Additional context**
Log snippet:
time="2020-06-14T22:11:37Z" level=debug msg="task putting key in queue pgo/backrest-backup-a" func="controller/pgtask.(*Controller).onAdd()" file="controller/pgtask/pgtaskcontroller.go:175" version=4.3.0
time="2020-06-14T22:11:37Z" level=debug msg="working on pgo/backrest-backup-a" func="controller/pgtask.(*Controller).processNextItem()" file="controller/pgtask/pgtaskcontroller.go:74" version=4.3.0
time="2020-06-14T22:11:37Z" level=debug msg="queue got key ns=[pgo] resource=[backrest-backup-a]" func="controller/pgtask.(*Controller).processNextItem()" file="controller/pgtask/pgtaskcontroller.go:79" version=4.3.0
time="2020-06-14T22:11:37Z" level=debug msg="{\"status\":{\"message\":\"Successfully processed Pgtask by controller\",\"state\":\"pgtask Processed\"}}" func="kubeapi.PatchpgtaskStatus()" file="kubeapi/pgtask.go:193" version=4.3.0
time="2020-06-14T22:11:37Z" level=debug msg="backrest task added" func="controller/pgtask.(*Controller).processNextItem()" file="controller/pgtask/pgtaskcontroller.go:132" version=4.3.0
time="2020-06-14T22:11:37Z" level=error msg="More than one primary found when creating backrest job backrest-backup-a" func="operator/backrest.Backrest()" file="operator/backrest/backup.go:91" version=4.3.0

**Comment by jkatz** [comment]
Curious, do you know how the Pod was evicted?

It sounds like it successfully failed over / reschedule, but the label on the Evicted pod is still being considered.

I think the fix is to not consider evicted pods in "multiple primary" check. An Evicted Pod is no longer active, and we shouldn't consider it.

The "quick fix" is to delete the Evicted pod.

**Comment by djcooklup** [comment]
Yup yup, pod was evicted due to node memory pressure and was successfully rescheduled, so nothing went wrong in the handling of that (which was good)

Fix sounds good to me, also can confirm that deleting evicted pod restores normal behaviour as expected

**Comment by jkatz** [comment]
Thanks for checking @djcooklup glad to hear it's working post-evicted Pod deletion.

I put up a PR that should fix it in #1624 though I would emphasize it's a "draft" PR as I'd like for @cbandy + @andrewlecuyer to take a look at it as I rushed it together just to show the methodology (and I'm not thrilled at my "code repeat") / they'll likely have a better way of dealing with it.
