### ISSUE TITLE
Problem after upgrade operator from 4.3.0 to 4.3.2

### ISSUE THREAD

**Issue by gricuk** [CrunchyData/postgres-operator#1625]
**Which example are you working with?**

I've tried to upgrade pgo operator and images from 4.3.0 to 4.3.2. I've updated operator via update my inventory in ansible. Then I've tried to update my db cluster, but cluster doesn't initialize after pod re-created.

**What is the current behavior?**
The following error:

`Mon Jun 15 14:44:53 UTC 2020 INFO: Starting SSHD..
Mon Jun 15 14:44:53 UTC 2020 INFO: Starting background process to monitor Patroni initization and restart the database if needed
Now removing "pause" key from patroni.dynamic.json configuration file if present
Mon Jun 15 14:44:53 UTC 2020 INFO: Initializing cluster bootstrap with command: '/usr/local/bin/patroni /tmp/postgres-ha-bootstrap.yaml'
Mon Jun 15 14:44:53 UTC 2020 INFO: Running Patroni as PID 1
2020-06-15 14:44:54,495 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-06-15 14:44:54,502 INFO: Reaped pid=132, exit status=0
2020-06-15 14:44:54,508 INFO: Reaped pid=135, exit status=0
2020-06-15 14:44:54,508 CRITICAL: system ID mismatch, node testdb-edfq-5659567d57-tfp2x belongs to a different cluster: 6837110244418605212 != 6836640985457381533
`

**What is the expected behavior?**

Pod should be successfully created with new version.

**Other information** (e.g. detailed explanation, related issues,  etc)
I've edited configmap `testdb-config` and change `initialize` field in annotation section with 6836640985457381533 value. And now it works good.

Could you please explain upgrade procedure? Why the operator does not change the value in configmaps?

**Comment by jkatz** [comment]
Did you use the [automated upgrade procedure](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/automatedupgrade/)?

**Comment by gricuk** [comment]
> Did you use the [automated upgrade procedure](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/automatedupgrade/)?

Yes, I've used this procedure.

**Comment by tjmoore4** [comment]
For context, could you please provide details of your inventory file, as well as the command used when creating the initial pgcluster (in this case, what was specified in 4.3.0)?

**Comment by gricuk** [comment]
> For context, could you please provide details of your inventory file, as well as the command used when creating the initial pgcluster (in this case, what was specified in 4.3.0)?

`pgo create cluster testdb -d test --cpu=2 --memory=4Gi --storage-config=micro --metrics  --pgbackrest-storage-type=s3  -n test-cl`

We are using original inventory file (just storage classes, s3 bucket and metrics was changed)

**Comment by tjmoore4** [comment]
After running some 4.3.0 to 4.3.2 upgrade tests, I was unable to replicate this issue. The relevant log block from my cluster is below:

```
Tue Jul 14 20:43:29 UTC 2020 INFO: Starting SSHD..
Tue Jul 14 20:43:29 UTC 2020 INFO: Starting background process to monitor Patroni initization and restart the database if needed
Now removing "pause" key from patroni.dynamic.json configuration file if present
Tue Jul 14 20:43:29 UTC 2020 INFO: Initializing cluster bootstrap with command: '/usr/local/bin/patroni /tmp/postgres-ha-bootstrap.yaml'
Tue Jul 14 20:43:29 UTC 2020 INFO: Running Patroni as PID 1
2020-07-14 20:43:30,052 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-07-14 20:43:30,068 INFO: Reaped pid=134, exit status=0
2020-07-14 20:43:30,080 INFO: Reaped pid=137, exit status=0
2020-07-14 20:43:30,081 WARNING: Postgresql is not running.
2020-07-14 20:43:30,081 INFO: Lock owner: None; I am testdb-65d479859-7qp49
2020-07-14 20:43:30,085 INFO: Reaped pid=138, exit status=0
2020-07-14 20:43:30,086 INFO: pg_controldata:
  pg_control version number: 1201
  Catalog version number: 201909212
  Database system identifier: 6849437641778618519
  Database cluster state: shut down
  pg_control last modified: Tue Jul 14 20:42:27 2020
```
As you can see, this did not result in the system ID mismatch issue. I will note that it can take some amount of time for the database to begin receiving connection after upgrade, and, depending on connection speed, etc, S3 connections may increase this time. However, I would not expect the issue described above regardless of the time required.
