### ISSUE TITLE
How to increase the pgbackrest pvc size without bringing down cluster?

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1626]
** Which example are you working with? **
pgo 4.3.2 
I have deployed a cluster with pgo 4.3.2 and would like to now increase the pgbackrest pvc size without bringing down the cluster.  What's the recommended procedure for doing that?

**Comment by jkatz** [comment]
The only "automated" way to do this is to use `pgo clone --pgbackrest-pvc-size` and/or create a new cluster as a "standby" cluster that has a large pgBackRest PVC size, and then ultimately failover to that.

You can adjust the PVC size for the pgBackRest repository yourself -- this does not cause "downtime" of the PostgreSQL cluster, though you will not be able to push WAL archives to the repository during downtime (unless you are using S3 as well, but if you're using S3 you do not need to worry about resizing).

Automating PVC resizing is something we have looked at , but the nicer methods for doing this are available in much newer version of Kubernetes (and while nicer, still need a **lot** of testing esp. as we are dealing with data, ergo we are cautious), and as we are maintaining backwards compatibility, save for rare exceptions, down to 1.11 (OCP 3.11), we will look at incorporating these futures into a future release when deemed ready.

**Comment by alrooney** [comment]
@jkatz thanks much.  I am using local and s3 for my backups but backups are failing so seems like it won't do the s3 backup if it can't do the local one too. To edit the pvc for backrest would I just use ```kubectl edit pvc retroelk-pgbr-repo``` and change the size or is there a pgo way to do it?  And I haven't tried yet but usually you can't change the size of a PVC.  So do I have to delete it and recreate it and then restart the pod/scale the retroelk-backrest-shared-repo deployment?

**Comment by alrooney** [comment]
Ah just realized that by "automated" way you probably mean using pgo so I get it that there is no pgo way to change the pvc size...

But is there a way to change the backrest backup from using local and s3 to just using s3 without recreating the whole cluster?  Either using kubectl or pgo?

**Comment by jkatz** [comment]
`pgo create cluster --pgbackrest-storage-type=s3` sets up a PostgreSQL cluster to use *only* S3 as the pgBackRest repository.  Backups to S3 can be slow (see #1617) and it's imperative that  you've configured the settings to S3 correctly, but other than the latency issues I have not had any problems (outside of bugs) running my pgBackRest repository S3 only.

**Comment by alrooney** [comment]
I was able to increase the pvc size.

**Comment by jkatz** [comment]
@alrooney Great. What method did you use?

I do believe at some point we'll automate something like this into the Operator (particularly once we up the minimum version of Kube), but want to get a better understanding of what options are available now.
