### ISSUE TITLE
Cluster Pods Stuck as PENDING due to PVC Issues.

### ISSUE THREAD

**Issue by salemylucas** [CrunchyData/postgres-operator#1628]
**Describe the bug**
Hello, I'm trying to create a test cluster on a Slave Node of a Kubernetes Cluster, however the pods get stuck as status "PENDING", please take a look at the PVCs manifest, I found they are not requesting for specific storage. I tried creating a PV in case they are not able to create it dynamically, manifest attached in the next section. 

**To Reproduce**
1. Deploy a Multi Node Kubernetes Cluster on two Centos 7 VMs.
2. Deploy the pgo on the Minion/Slave Node of the cluster
3. Install the pgo client and run it (kubectl -n pgo port-forward svc/postgres-operator 8443:8443)
4. Run the command to create a default Cluster (pgo create cluster testcluster -n pgo)

**Expected behavior**
It should deploy the pods of the cluster

**Actual behavior**
It gets stuck on the cluster repo volume binding/creation. 

List of pods running:
![Pods](https://user-images.githubusercontent.com/66966408/84693958-98b64200-af05-11ea-823c-d36b4ad9ff69.png)

Cluster Creation:
![Cluster](https://user-images.githubusercontent.com/66966408/84694015-b1bef300-af05-11ea-8335-303c4b1821aa.png)

PVC Status created by pgo:

![pvc status](https://user-images.githubusercontent.com/66966408/84694056-c3a09600-af05-11ea-9af7-b3b3c90f3e23.png)

PV Created trying to solve the Binding Issue:

![pv admin](https://user-images.githubusercontent.com/66966408/84694096-d74bfc80-af05-11ea-93d4-b91fcc76e4ce.png)

Pods Status 

![cluster_stuck](https://user-images.githubusercontent.com/66966408/84694577-a8825600-af06-11ea-9415-bcd870221df3.png)

**Please tell us about your environment:**

- CentOS Linux 7 (Core)

- Kubernetes Version 1.18 installed using Kubeadm

- Calico Network Deployment

- Two nodes Kubernetes Cluster

- pgo deployment performed on the minion/slave Node.

- On Premise
-Local Storage
- Container Image Tag: registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.2

**Comment by jkatz** [comment]
Ensure you follow the directions for setting up the storage classes for your primaries, replicas, and pgBackRest storage classes. This is detailed in various locations, e.g.:

- [Quickstart Configuration](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/#step-1-configuration)

Without additional details with how your installed the PostgreSQL Operator in your environment, there's not much more I can do to help, but based on the error message, this sounds like a configuration issue with your storage.
