### ISSUE TITLE
2.6 is released but images are not available in docker hub 

### ISSUE THREAD

**Issue by bergerx** [CrunchyData/postgres-operator#163]
I just tried to follow the documentation for v2.6 but it failed several times due to trying to pull the images from docker hub with 2.6 tag which are not available, only 2.6-rc1 tags are there.

**Comment by xenophenes** [comment]
The "master" branch of the Postgres Operator is treated as unstable; 2.6 will be coming out relatively shortly - we are in the testing process of the release candidate for 2.6 now. In the meantime, please view the 2.5 tagged branch - https://github.com/CrunchyData/postgres-operator/tree/2.5 - to experiment with the latest stable release of the Operator.

**Comment by bergerx** [comment]
Hi, thanks for the quick reply, i followed the instructions for 2.5 and it just worked, thanks.
