### ISSUE TITLE
Is there any leader-election mechanism when multiple operator replicas deployed in a k8s  Cluster(the replicas ,in a operator deployment, is bigger than 1)?

### ISSUE THREAD

**Issue by zjtheone** [CrunchyData/postgres-operator#1630]
Hello,

** Which example are you working with? **
pgo 4.3.2

I want to change the replicas number in the operator deployment yaml , I am confused about  the operator itself's  high-available?

I can find any information about the operator itself's high-available in the manual.

Thanks for any hints!

**Comment by jkatz** [comment]
Information about [PostgreSQL high availability](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/) is here. The short answer is yes: leader election is automatic in the basic multi-replica case. This is well covered in the documentation, and there is also a blog that should cover the topic on [high availability PostgreSQL](https://info.crunchydata.com/blog/deploy-high-availability-postgresql-on-kubernetes).

Information about running multiple Operators such that you can run [multi-Kubernetes deployments](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/) is [here](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/), and there is a [blog covering the topic as well](https://info.crunchydata.com/blog/multi-kubernetes-cluster-postgresql-deployments).

Leader election occurs within a PostgreSQL cluster. Cross-cluster deployments (i.e. the example in the blog) do not support automatic leader selection across the deployments. The documentation and the blog both cover the procedure.

The complications over having an cross-Kubernetes cluster deployment entirely automated are covered in issue #1099 and to fully support that, we would need for the Kubernetes Federation API (or some other mechanism) to mature.

Multi-Kubernetes cluster deployments are still a relatively new area and we will watch and see what approach makes the best sense.

Lastly, in terms of the PostgreSQL Operator itself, it is not meant to be run with multiple replicas in the Deployment. Based on how the Operator pattern works, this is true of most Operators. With the [HA architecture for PostgreSQL](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/) this is fine: even if the Operator is down, the PostgreSQL clusters themselves will be able to maintain their own availability. Some other non-critical Operator functions may be unavailable while there are no Operator Pods scheduled, but it will not affect the uptime of the PostgreSQL cluster.
