### ISSUE TITLE
Best way to configure pgAudit for a postgres cluster

### ISSUE THREAD

**Issue by v3nturetheworld** [CrunchyData/postgres-operator#1632]
** Which example are you working with? **
N/A. 
In order to comply with the [postgres STIG](https://www.crunchydata.com/files/stig/PGSQL-STIG-9.5+.pdf) (which is for an older version of postgres then the latest version which we are using), we need to adjust the logging settings for pgAudit in our cluster. It looks like CrunchyData even has [a tool for](https://github.com/CrunchyData/pgstigcheck-inspec) verifying STIG compliance (not sure how up to date it is though).  According to the STIG, we want to have the following settings in postgresql.conf:
```
pgaudit.log_catalog='on'
pgaudit.log_level='log'
pgaudit.log_parameter='on'
pgaudit.log_statement_once='off'
pgaudit.log='all, -misc
log_line_prefix = '%m %u %d %e : '
log_error_verbosity = default
```

What would be the best way to set these values in a crunchy cluster so that the primary, replica and (if applicable) pgbouncer have these configurations? Can these be set during the cluster creation time with `pgo create cluster` or can they be set in one of the configmaps associated with the cluster?

**Please tell us about your environment:**

* Operating System: RHEL 7.7
* Where is this running ( Local , Cloud Provider): 3 node cluster
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: crunchy-postgres-ha:centos7-12.2-4.3.0
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 3.11

**Comment by jkatz** [comment]
We do have a bunch of customers that deploy PostgreSQL STIG-compliant containers that we build which also include automated checks for compliance. We would be happy to learn more about what you are doing and assist with pgAudit configuration.  Please [send us a note](https://www.crunchydata.com/contact/) and it would be great to schedule a call to further discuss.
