### ISSUE TITLE
pgbadger cpu request

### ISSUE THREAD

**Issue by cubed-it** [CrunchyData/postgres-operator#1633]
What is the recomended way to reduce the requested cpu of pgbadger ?
Currently it request 500m by default and foreach replica. That's a lot of resources if you use pgbadger only in problem cases.

Alternatively, can pgbadger only be activated on demand?

Thanks!

**Comment by jkatz** [comment]
You can modify the pgBadger template. Assuming `pgo` is the namespace your Operator is deployed to:

1. `pgo edit cm -n pgo pgo-config`.
1. Find the `pgbadger.json` entry.
1. Edit the "resources" clause.

**Comment by cubed-it** [comment]
I replaces pgo with kubectl and found it. Thanks!

**Comment by jkatz** [comment]
@cubed-it Great.

For the other request (turning pgBadger on/off), it's something that has been asked for and under consideration for a future release.
