### ISSUE TITLE
How to restore backup from a different s3 bucket / database

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1634]
** Which example are you working with? **
pgo 4.3.2
**What is the current behavior?**
I'd like to be able to restore a backup or pg_dump done on one database to another on a completely different cluster managed by a separate operator.  So it's almost a combination of clone and standby cluster but I need to do it across operators so clone does not support that and I don't want it to interfere with the primary cluster and I want to be able to run it independently afterwards so standby cluster instructions do not quite apply.  What's the best way to do this?

**Comment by jkatz** [comment]
I would combine this with #1305 as it's a similar workflow.
