### ISSUE TITLE
replica showing huge replication lag in grafana charts

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1635]
**Describe the bug**
In our cluster with a single primary and a replica the replica is showing a huge time lag in grafana dashboards:

**Expected behavior**
There should be no or minimal < 50ms time lag in replication.  
**Screenshots**
![image](https://user-images.githubusercontent.com/1009422/84917737-b4e4eb00-b08d-11ea-9149-5468e218ad39.png)

**Please tell us about your environment:**
pgo 4.3.2
* Operating System:
* Where is this running ( Local, Cloud Provider)
AWS EKS
* Storage being used (NFS, Hostpath, Gluster, etc):
io1 ebs 
* Container Image Tag:
see below
* PostgreSQL Version:
see below
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
EKS 1.15
**Additional context**
```
$ pgo show config retroelk
BackrestStorage: io1-15-encrypted
BackupStorage: io1-15-encrypted
BasicAuth: ""
Cluster:
  Backrest: true
  BackrestPort: 2022
  BackrestS3Bucket: ""
  BackrestS3Endpoint: ""
  BackrestS3Region: ""
  Badger: false
  CCPImagePrefix: registry.developers.crunchydata.com/crunchydata
  CCPImageTag: centos7-11.8-4.3.2
  Database: ""
  DefaultBackrestMemory: 48Mi
  DefaultInstanceMemory: 128Mi
  DefaultPgBouncerMemory: 24Mi
  DisableAutofail: false
  DisableFSGroup: false
  DisableReplicaStartFailReinit: false
  EnableCrunchyadm: false
  ExporterPort: "9187"
  Metrics: true
  PGBadgerPort: "10000"
  PasswordAgeDays: ""
  PasswordLength: "24"
  PgmonitorPassword: ""
  PodAntiAffinity: preferred
  PodAntiAffinityPgBackRest: ""
  PodAntiAffinityPgBouncer: ""
  Policies: ""
  Port: "5432"
  Replicas: "0"
  ServiceType: ClusterIP
  SyncReplication: false
  User: testuser
Pgo:
  Audit: false
  ConfigMapWorkerCount: null
  ControllerGroupRefreshInterval: null
  NamespaceRefreshInterval: null
  NamespaceWorkerCount: null
  PGClusterWorkerCount: null
  PGOImagePrefix: registry.developers.crunchydata.com/crunchydata
  PGOImageTag: centos7-4.3.2
  PGReplicaWorkerCount: null
  PGTaskWorkerCount: null
PrimaryStorage: io1-15-encrypted
ReplicaStorage: io1-15-encrypted
Storage:
  glusterfs:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 100Gi
    StorageClass: glusterfs-storage
    StorageType: dynamic
    SupplementalGroups: ""
  gp2:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 100Gi
    StorageClass: gp2
    StorageType: dynamic
    SupplementalGroups: ""
  hostpathstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: ""
  io1-15-encrypted:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 100Gi
    StorageClass: io1-15-encrypted
    StorageType: dynamic
    SupplementalGroups: ""
  nfsstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: "65534"
  nfsstoragered:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: "65534"
  primarysite:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 4G
    StorageClass: primarysite
    StorageType: dynamic
    SupplementalGroups: ""
  replicastorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 700M
    StorageClass: ""
    StorageType: create
    SupplementalGroups: ""
  storageos:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 5Gi
    StorageClass: fast
    StorageType: dynamic
    SupplementalGroups: ""
WALStorage: ""

```

**Comment by freidahRFIC** [comment]
I am seeing a similar issue on a few of my clusters.  assuming we are looking at the same problem here is some additional info

checking replication lag on secondary:
`postgres=# select now() - pg_last_xact_replay_timestamp() AS replication_delay;
 replication_delay 
-------------------
 00:00:21.510963
(1 row)`

same thing on the primary:
`postgres=# select now() - pg_last_xact_replay_timestamp() AS replication_delay;
    replication_delay    
-------------------------
 51 days 10:44:04.909091
(1 row)`

It is my understanding that a primary should return the following for that query:
`postgres=# select now() - pg_last_xact_replay_timestamp() AS replication_delay;
 replication_delay 
-------------------
 
(1 row)`

I believe that the clusters not looking normal had been failed over at some point so I am wondering if some stale info is being stored still causing the perception of massive lag.

Just to verify there isn't any actual lag, lets look at wal locations
primary: 
`postgres=# select pg_current_wal_lsn();
 pg_current_wal_lsn 
--------------------
 2/72E78518
(1 row)` 

secondary:
`postgres=# select pg_last_wal_receive_lsn();
 pg_last_wal_receive_lsn 
-------------------------
 2/72E78518
(1 row)`

If we look at what metrics are actually being generated:
secondary:
`bash-4.2$ curl localhost:9187/metrics 2>/dev/null | grep -v "#" | grep lag
ccp_replication_lag_replay_time 0
bash-4.2$ `

primary:
`bash-4.2$ curl localhost:9187/metrics 2>/dev/null | grep -v "#" | grep lag
ccp_replication_lag_replay_time 4.445538e+06
ccp_replication_lag_size_bytes{replica="10.42.11.222",replica_hostname="",replica_port="35038"} 0
bash-4.2$ `

primary from a cluster that isn't showing this issue:
`bash-4.2$ curl localhost:9187/metrics 2>/dev/null | grep -v "#" | grep lag
ccp_replication_lag_replay_time{server="127.0.0.1:5432"} NaN
ccp_replication_lag_size_bytes{replica="10.42.11.61",replica_hostname="",replica_port="57560",server="127.0.0.1:5432"} 0
bash-4.2$ `

Hopefully this info is helpful in a problem a few of us are seeing.

**Comment by freidahRFIC** [comment]
I am seeing a similar issue on a few of my clusters. assuming we are looking at the same problem here is some additional info

checking replication lag on secondary:
postgres=# select now() - pg_last_xact_replay_timestamp() AS replication_delay;
replication_delay
00:00:21.510963
(1 row)

same thing on the primary:
postgres=# select now() - pg_last_xact_replay_timestamp() AS replication_delay;
replication_delay
51 days 10:44:04.909091
(1 row)

It is my understanding that a primary should return the following for that query:
postgres=# select now() - pg_last_xact_replay_timestamp() AS replication_delay;
replication_delay
(1 row)

I believe that the clusters not looking normal had been failed over at some point so I am wondering if some stale info is being stored still causing the perception of massive lag.

Just to verify there isn't any actual lag, lets look at wal locations
primary:
postgres=# select pg_current_wal_lsn();
pg_current_wal_lsn
2/72E78518
(1 row)

secondary:
postgres=# select pg_last_wal_receive_lsn();
pg_last_wal_receive_lsn
2/72E78518
(1 row)

If we look at what metrics are actually being generated:
secondary:
bash-4.2$ curl localhost:9187/metrics 2>/dev/null | grep -v "#" | grep lag
ccp_replication_lag_replay_time 0 bash-4.2$

primary:
bash-4.2$ curl localhost:9187/metrics 2>/dev/null | grep -v "#" | grep lag
ccp_replication_lag_replay_time 4.445538e+06 ccp_replication_lag_size_bytes{replica="10.42.11.222",replica_hostname="",replica_port="35038"} 0 bash-4.2$

primary from a cluster that isn't showing this issue:
bash-4.2$ curl localhost:9187/metrics 2>/dev/null | grep -v "#" | grep lag
ccp_replication_lag_replay_time{server="127.0.0.1:5432"} NaN ccp_replication_lag_size_bytes{replica="10.42.11.61",replica_hostname="",replica_port="57560",server="127.0.0.1:5432"} 0 bash-4.2$

Hopefully this info is helpful in a problem a few of us are seeing.

**Comment by jkatz** [comment]
Monitoring got an [incredible overhaul](https://crunchydata.github.io/postgres-operator/latest/architecture/monitoring/) which will be GA in the [very near future](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0-rc.1). This should fix the issue.

**Comment by freidahRFIC** [comment]
Can you describe the issue that is causing this?
Is there a suggested workaround for now?

**Comment by jkatz** [comment]
Yes. As I mentioned, the issue is that monitoring system required an [incredible overhaul](https://crunchydata.github.io/postgres-operator/latest/architecture/monitoring/), was completely rewritten and being made GA in the [upcoming 4.5.0 release](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0-rc.1), which is due out in the next few days.

The exporter files and Grafana dashboards come from the [pgMonitor](https://github.com/CrunchyData/pgmonitor/) project. You can poke around at the updated exporter files and dashboards to see if you can fit them into your existing deployment.

**Comment by jkatz** [comment]
[Operator 4.5](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0) is now released.
