### ISSUE TITLE
Upgrade pgBackrest to 2.27

### ISSUE THREAD

**Issue by asoltesz** [CrunchyData/postgres-operator#1636]
**What is the motivation or use case for the change? **

Ability to use time based retention policy for full backups with pgBackrest backups

**Describe the solution you'd like**

pgBackrest 2.27 introduces the "repo-retention-full-type" backup option that allows for a better full backup retention policy than before (which was the count of full backups)

It would allow me to set the full backup retention policy to e.g.: 6 months.

Setting a time based policy is more natural to me.

**Please tell us about your environment:**
N/A

**Additional context**
N/A

**Comment by jkatz** [comment]
We have plans to do this, but the earliest it will happen is the 4.4 release.

**Comment by jkatz** [comment]
This has been committed.
