### ISSUE TITLE
Misleading error message when backing up a cluster

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/postgres-operator#164]
When running the command to backup a cluster, it prompts with:

"WARNING - This is destructive: Are you sure? (yes/no):"

I'm assuming there must be a step in the backup process that involves deleting, but it's a little jarring to receive a "destructive" warning when backing up something. Is there a way to quiet that output when running a backup?

**Comment by jmccormick2001** [comment]
I've added the ability to offer up different confirmation messages, but in this case I think the confirmation is not necessary so I've removed it altogether when running a 'pgo backup' command.
