### ISSUE TITLE
Support to remove tablespace

### ISSUE THREAD

**Issue by Witcher1994** [CrunchyData/postgres-operator#1640]
**What is the motivation or use case for the change? **
I have a system for managing binary documents. There is a need to move documents between partitions/tablespaces. For example I need to move document to new tablespace on faster storage class and then remove old tablespace to remove volume/reduce costs. Adding tablespaces works perfect, but I also need to remove tablespaces. I tried to remove entry from pgCluster CRD but It does nothing - PVC, volumeMount and tablespace still exists. Maybe Is there any mechanism to remove tablespaces / volumes ?

**Please tell us about your environment:**

* Where is this running ( Local, Cloud Provider) AWS
* Storage being used (NFS, Hostpath, Gluster, etc): EFS, EBS
* PostgreSQL Version: 4.3.0
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.15

**Comment by jkatz** [comment]
This challenge of this is covered in the [release notes](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.3.0/):

> Dropping tablespaces can be tricky as no objects must exist on a tablespace in order for PostgreSQL to drop it (i.e. there is no DROP TABLESPACE .. CASCADE command).

further covered in the [PostgreSQL manual](https://www.postgresql.org/docs/current/manage-ag-tablespaces.html):

> Once created, a tablespace can be used from any database, provided the requesting user has sufficient privilege. This means that a tablespace cannot be dropped until all objects in all databases using the tablespace have been removed.
>
> To remove an empty tablespace, use the DROP TABLESPACE command.

Based on how a tablespace is used, it can be exhaustive to validate whether or not it is safe to drop a tablespace, as there is "no free lunch". Additionally, if you remove it directly from the CRD, there is effectively no validation whether or not the tablespace can be dropped, and as such would leave your cluster in an inconsistent state.

If you need to remove a tablespace, you can (and in this suggested order):

1. As a database administrator:
  1. drop all of the objects owned by the existing tablespace
  1. drop the tablespace
1. From Kubernetes:
  1. Modify the Deployment objects for the cluster and remove the Volume + Volume Mount entries for the tablespace you wish to remove
  1. Modify the CR to remove the entry for the tablespace.

**Comment by jkatz** [comment]
I've gone ahead and documented the procedure for how one can remove a tablespace. Given the complications mentioned above for automating the procedure (which is also covered in the documentation), I don't see removing tablespaces in an automated fashion as being a supported operation, though we can now say we support the manual removal.
