### ISSUE TITLE
 Permission denied while creating postgres cluster

### ISSUE THREAD

**Issue by samuel-sujith** [CrunchyData/postgres-operator#1642]
**Describe the bug**

The provisioning of the postgres cluster is stopping with permission issues

**To Reproduce**
1. I am trying to create a postgres cluster. I ran the ansible installer
ansible-playbook -i inventory  --tags=install --become --become-user=root main.yml
2. At this point, the operator is installer successfully
3. then i do pgo create cluster -n pgouser1 hippo
I get the below display
created cluster: hippo
workflow id: 9799703a-2393-4df0-8943-8f6e35a68f8a
database name: hippo
users:
        username: testuser password: ewdOEQ:s3TL\n[pg2KN;q57l
4. But the hippo pods are in error
NAME                                          READY   STATUS             RESTARTS   AGE
hippo-6fdcc9445-v9647                         0/1     CrashLoopBackOff   7          14m
hippo-backrest-shared-repo-6f84467d56-z9bw9   1/1     Running            0          14m

kubectl logs hippo-6fdcc9445-v9647 -n pgouser1
Thu Jun 18 18:07:41 UTC 2020 INFO: Applying base postgres config to postgres-ha configuration
Thu Jun 18 18:07:41 UTC 2020 INFO: Applying pgbackrest config to postgres-ha configuration
Thu Jun 18 18:07:41 UTC 2020 INFO: PGDATA directory is empty on node identifed as Primary
Thu Jun 18 18:07:41 UTC 2020 INFO: initdb configuration will be applied to intitilize a new database
Thu Jun 18 18:07:41 UTC 2020 INFO: Applying standard (non-TLS) remote connection configuration to pg_hba.conf
Thu Jun 18 18:07:41 UTC 2020 INFO: Custom postgres-ha configuration file not detected
Thu Jun 18 18:07:41 UTC 2020 INFO: Finished building postgres-ha configuration file '/tmp/postgres-ha-bootstrap.yaml'
mkdir: cannot create directory ‘/pgdata/hippo’: Permission denied
chmod: cannot access ‘/pgdata/hippo’: No such file or directory

same error in the other pod

**Expected behavior**
Postgres cluster hippo should get provisioned

**Screenshots**

**Please tell us about your environment:**

* Operating System: Ubuntu 16.04
* Where is this running ( Local, Cloud Provider) Local
* Storage being used (NFS, Hostpath, Gluster, etc): Ceph(Rook)
* Container Image Tag: 'centos7-12.3-4.3.2'
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.18.3

**Additional context**

**Comment by jkatz** [comment]
```
mkdir: cannot create directory ‘/pgdata/hippo’: Permission denied
chmod: cannot access ‘/pgdata/hippo’: No such file or directory
```

This is an issue with your storage configuration. If you are using Rook/Ceph you need to ensure that a) Rook/Ceph is set up correctly, and that you have [correctly configured your storage in the PostgreSQL Operator setup](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/other/ansible/prerequisites/#storage), which is covered in the linked documentation.

**Comment by samuel-sujith** [comment]
The issue is still not resolved. rook-ceph is provisioned correctly and is able to provision the PVC's too
NAME              STATUS   VOLUME             CAPACITY   ACCESS MODES   STORAGECLASS      AGE
hippo             Bound    task-pv-volume-1   10Gi       RWO            rook-ceph-block   82s
hippo-pgbr-repo   Bound    task-pv-volume     10Gi       RWO            rook-ceph-block   82s

However the logs in the pod show the permission denied error.

Data page checksums are enabled.

initdb: error: could not create directory "/pgdata/hippo": Permission denied
pg_ctl: database system initialization failed

**Comment by jastabile** [comment]
I have same issue on a HostPath volume:

It says

```
mkdir: cannot create directory ‘/pgdata/hippo’: Permission denied                                                                                                              
chmod: cannot access ‘/pgdata/hippo’: No such file or directory

**Comment by jkatz** [comment]
Similar to the response in the [earlier comment](https://github.com/CrunchyData/postgres-operator/issues/1642#issuecomment-646249572) this is likely an issue with your storage configuration or something pertaining to file ownership. For example, in OpenShift, you need to set [`disable_fsgroup`](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/ to `true`.

If you are not using a storage provisioner, you will need to ensure that the storage system is writeable by the Pods managed by the Operator.

However, this are just guesses. Without any information about your environment, this is nearly impossible to troubleshoot.

**Comment by jastabile** [comment]
Thank you @jkatz.

In my case (Hostpath) I solved it setting permissions to the directory. 
For example if `/vol` is the hostpath of the volume: `chmod 777 /vol` (just an example)
