### ISSUE TITLE
Using local disks for near-native performance

### ISSUE THREAD

**Issue by asoltesz** [CrunchyData/postgres-operator#1646]
** Which example are you working with? **

Version 4.3.2 of the documentation

**What is the current behavior?**

No information on how to use local disks to achieve the same performance as native Postgres installations.  

**What is the expected behavior?**

The storage section details how to get native speeds on Kubernetes with local disks. 

If not supported, it includes a section why this is not viable or how may be done with external tools.

**Other information** (e.g. detailed explanation, related issues,  etc)

I would like to deploy a Postgres cluster where the primary and replica instances use local or hostpath volumes provisioned from local disks (same node as the pod) in order to achieve near-native database performance.

Without this, I can only allocate the database on shared, networked storage (NFS, Rook/Ceph ...etc) which can only provide a fraction of the disk speed and responsiveness of local disks.

I assume this requires special support from the operator (e.g: force dropping PVCs when a re-sceduled pod cannot be allocated on the same node for some reason)

Is this supported explicitely by the operator?

If not, can it be supported by some external Kubernetes tool ? 

**Please tell us about your environment:**

N/A

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:

N/A

**Comment by jkatz** [comment]
You can use the `--node-label` flag, available both on `pgo create cluster` and `pgo scale`, to specify the Node Affinity for a PostgreSQL instance and keep it tied to the node (with the usual warnings about Node durability, i.e. if the node goes down, so does your Pod). If you require a Pod to be scheduled to that specific Node, and the Node is unavailable, that Pod will not be scheduled until the Node is available. If you have other Pods in that PostgreSQL cluster available, the HA mechanisms will kick in and you will maintain your availability.

You are free to use `hostpath` storage on those nodes, the availability of which is subject to your hostpath storage provisioner. The Operator works with StorageClasses in general and makes no assumptions about their implementation, though intends to do so.

Beyond that, it's up to you to manage your storage topology. The Operator gives you flexibility in this regard by not making any underlying assumptions in terms of how your storage system works.
