### ISSUE TITLE
Can't install PGO client

### ISSUE THREAD

**Issue by alterEgo123** [CrunchyData/postgres-operator#1651]
The script **client-setup.sh** returns an error. 
```
**curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.**
pgo client files have been generated, please add the following to your bashrc
export PATH=/root/.pgo/pgo:$PATH
export PGOUSER=/root/.pgo/pgo/pgouser
export PGO_CA_CERT=/root/.pgo/pgo/client.crt
export PGO_CLIENT_CERT=/root/.pgo/pgo/client.crt
export PGO_CLIENT_KEY=/root/.pgo/pgo/client.key
```

At this point, if I try to run **pgo version** it returns:
**Error: The PGO_APISERVER_URL environment variable or the --apiserver-url flag needs to be supplied.**

If I set up the PGO_APISERVER_URL variable to 'https://127.0.0.1:8443' and run **pgo version** I get:

`FATA[0000] failed to set up TLS client: client certificate/key loading: open /root/.pgo/pgo/client.pem: no such file or directory `

**To Reproduce**

```
kubectl create namespace pgo
kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.3.2/installers/kubectl/postgres-operator.yml
curl https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.3.2/installers/kubectl/client-setup.sh > client-setup.sh
chmod +x client-setup.sh
./client-setup.sh
export PGOUSER="${HOME?}/.pgo/pgo/pgouser"
export PGO_CA_CERT="${HOME?}/.pgo/pgo/client.crt"
export PGO_CLIENT_CERT="${HOME?}/.pgo/pgo/client.crt"
export PGO_CLIENT_KEY="${HOME?}/.pgo/pgo/client.pem"
export PGO_APISERVER_URL='https://127.0.0.1:8443'
export PGO_NAMESPACE=pgo
pgo version
```

**Expected behavior**
Get the installed pgo client version.

* Operating System: CentOS 7
* Where is this running: Local
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: //
* PostgreSQL Version: //
* Platform : Kubernetes
* Platform Version: 1.14

**Comment by jkatz** [comment]
Are there any files in `/root.pgo/pgo`?

**Comment by alterEgo123** [comment]
Yes
```
ls  /root/.pgo/pgo
client.crt  client.key  pgo  pgouser

```

**Comment by jkatz** [comment]
In one example I see:

`export PGO_CLIENT_KEY="${HOME?}/.pgo/pgo/client.pem"`

and in another I see

`export PGO_CLIENT_KEY=/root/.pgo/pgo/client.key`

and in your directory I see `client.key`.

I would recommend you set this patch of environmental variables:

```shell
export PATH=/root/.pgo/pgo:$PATH
export PGOUSER=/root/.pgo/pgo/pgouser
export PGO_CA_CERT=/root/.pgo/pgo/client.crt
export PGO_CLIENT_CERT=/root/.pgo/pgo/client.crt
export PGO_CLIENT_KEY=/root/.pgo/pgo/client.key
```

and then try connecting.
