### ISSUE TITLE
Adding the correct RBAC doesn't add namespace to installation in readonly mode 

### ISSUE THREAD

**Issue by eliranw** [CrunchyData/postgres-operator#1653]
**Describe the bug**
Adding the correct rbac doesn't add namespace to installation in readonly mode 

**To Reproduce**
1. Install operator in a namespace
2. Add rbac to different namespace with rolebinding to postgres-operator in the operator namespace.
3.Try to see if operator has access, and it doesnt'

**Expected behavior**
Operator has access to the namespace after dynamic rbac creation

* PostgreSQL Version: 4.3.2
* Platform (Docker, Kubernetes, OpenShift): Openshift 3.11 on prem

**Comment by jkatz** [comment]
Did you follow the instructions [here](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/) (please excuse the formatting, that will be fixed in the next release)?

**Comment by eliranw** [comment]
Yes, I got it to work by looking at the add-targeted-namespaces.yml, and I saw that you need to label namespaces in a specific way. Could it be that without the correct labels on the target namespace the operator doesn't add access to the target? If so it might need to be added to docs
