### ISSUE TITLE
Create new superuser account on cluster

### ISSUE THREAD

**Issue by Fen0l** [CrunchyData/postgres-operator#1656]
** Which example are you working with? **
Hllo everyone,

I have created a new cluster following documentation pgo create cluster mycluster but the tool that I am using required a user with the superuser role within the database cluster. As following the documentation only postgres is a superuser (and we do not have the password). Is it possible to create a new super affiliated to a cluster/bdd with the superuser role ?

I tried to use pgo create user and pguser but i did not find anything on the documentation.

**Please tell us about your environment:**
* Operating System: Local
* Storage being used NFS
* Container Image Tag: 4.3.2
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.16.8

Sorry of this is already documented but I did not find yet

**Comment by jkatz** [comment]
[`pgo show user mycluster --show-system-accounts`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_show_user/)
