### ISSUE TITLE
Replica is not getting created when using S3 backup

### ISSUE THREAD

**Issue by DinshKW44** [CrunchyData/postgres-operator#1660]
**Describe the bug**
I deployed a pgo cluster v4.3.2 using client:
pgo -n  $NAMESPACE create cluster $PGO_CLUSTER_NAME \
 --pgbackrest-storage-type=local,s3 \
 --pgbackrest-s3-ca-secret=aws-ca \
 --pgbackrest-s3-bucket=$PGBACKREST_S3_BUCKET \
 --pgbackrest-s3-endpoint=s3.ceph.zzz.com \
 --pgbackrest-s3-key=$PGBACKREST_S3_KEY \
 --pgbackrest-s3-key-secret=$PGBACKREST_S3_KEY_SECRET \
 --pgbackrest-s3-region=us-east \
 --replica-count=2 

The cluster gets created without issues but the replicas never come up with the below status message of pgreplica:
status:
  message: Pgreplica processing pending the creation of the initial backup
  state: pgreplica Pending init

pgo show backup $clusterName -n $clusterName

cluster: $clusterName
storage type: local

stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1)

        full backup: 20200615-115551F
            timestamp start/stop: 2020-06-15 07:55:51 -0400 EDT / 2020-06-15 07:58:47 -0400 EDT
            wal start/stop: 00000003000000000000000A / 00000003000000000000000B
            database size: 61.4MiB, backup size: 61.4MiB
            repository size: 7.4MiB, repository backup size: 7.4MiB
            backup reference list: 

        full backup: 20200616-000003F
            timestamp start/stop: 2020-06-15 20:00:03 -0400 EDT / 2020-06-15 20:02:46 -0400 EDT
            wal start/stop: 000000030000000000000086 / 000000030000000000000087
            database size: 327.2MiB, backup size: 327.2MiB
            repository size: 70.8MiB, repository backup size: 70.8MiB
            backup reference list: 

cluster: $clusterName
storage type: s3

stanza: db
    status: no valid backups
    cipher: none

    db (current)
        wal archive min/max (12-1)

The status is same from last 8 days. It does not create s3 backup. So I manually tried to create a s3 backup using below:
pgo backup $clusterName -n $clusterName --backup-type=pgbackrest --backup-opts="--type=full" --pgbackrest-storage-type=s3

This creates the s3 backup but it does not create replicas with the same error.
**To Reproduce**
1. Create cluster as mentioned above with s3 backend

**Expected behavior**
Backup should be created without issues and replicas should come up.

**Screenshots**

**Please tell us about your environment:**

* Operating System: Linux
* Where is this running ( Local, Cloud Provider): Kubernetes
* Storage being used (NFS, Hostpath, Gluster, etc): ceph-csi
* Container Image Tag: centos7-12.3-4.3.2
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16.3

**Additional context**

**Comment by DinshKW44** [comment]
I also noticed that the pg config file has not been updated too.
apiVersion: v1
data:
  init: "false"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-15T11:06:52Z"
  labels:
    pg-cluster: app
    pgha-config: "true"
    vendor: crunchydata
  name: $clusterName-pgha-config
  namespace: $clusterName
  resourceVersion: "144091542"
  selfLink: /api/v1/namespaces/$clusterName/configmaps/$clusterName-pgha-config
  uid: 85a3640d-f8e2-440f-9b44-2608273fd62b

**Comment by jkatz** [comment]
Replicas are spawned from pgBackRest backups. It appears that your S3 backup never completes, and the Operator is waiting for this to be done to know that it is in a consistent state in both places.

I would recommend checking your S3 configuration. There may be some error message in the failed pgBackRest backup and/or stanza create job. (I'm betting this one) that indicates why it could not take a backup.

**Comment by eliranw** [comment]
When my replicas didn't show up I saw issues in the pgBackrest backup pod's log for problems with an S3 variable in my cluster
