### ISSUE TITLE
pgbackrest with S3 configuration

### ISSUE THREAD

**Issue by alejom99** [CrunchyData/postgres-operator#1661]
Hello, I'm trying to understand how to properly configure pgbackrest when using it with S3. When we deploy a new cluster with `--pgbackrest-storage-type=s3`, do we have to specify a distinct bucket per cluster? Or can we use the same bucket for all clusters? 

When I try to use the same bucket for two or more clusters, only the first cluster gets created and the second fails. Both clusters have the same name, but are created in different namespaces.

**Comment by jkatz** [comment]
Presently, the names of the folders that each cluster gets stored to in S3 is not namespace prefixed.

At this time, if you want to have clusters of the same name in different namespaces and used the S3 integration, you should store them in different S3 buckets.

**Comment by alejom99** [comment]
@jkatz Thank you for your response. So, if every cluster has a unique name, then it should be safe to store them in the same s3 bucket, correct?

**Comment by jkatz** [comment]
Yes.

**Comment by alejom99** [comment]
Great, thank you.
