### ISSUE TITLE
What is the recommended procedure for upgrading major versions of pg while minimizing downtime

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1664]
I'm on pgo 4.3.2 and would like to figure out a procedure to be able to upgrade major versions while minimizing downtime of the db.  Was thinking of using a standby cluster with the new version.  Will that work?  Can the standby cluster be a newer version of pg?  If that will not work is there another way to minimize downtime while switching to a newer version of pg?  Specifically I am currently running 11.8 and would like to update to 12.x version of postgresql.

**Comment by eliranw** [comment]
+1

**Comment by TochukwuVictor** [comment]
Just came here to ask about this as well. There's [this documentation](https://access.crunchydata.com/documentation/crunchy-postgres-containers/4.3.2/examples/administration/upgrade/) but it's very rough around the edges and seems a bit outdated.

**Comment by jkatz** [comment]
With `pg_upgrade` you will have downtime no matter what system you are running on (Kubernetes, VMs, bare metal, etc.), though certain aspects of `pg_upgrade` allow for it to run more quickly.

If you want to achieve close-to-zero downtime, you would have to leverage logical replication and an architecture similar to this:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/)

For upgrades using logical replication, I'd refer to my colleague @hunleyd's post on the topic:

[https://hunleyd.github.io/posts/Upgrading-PostgreSQL-from-9.4-to-10.3-with-pglogical/](https://hunleyd.github.io/posts/Upgrading-PostgreSQL-from-9.4-to-10.3-with-pglogical/)

While use uses pglogical (design to work before full logical replication support was added in PostgreSQL 10), the methodology is similar.
