### ISSUE TITLE
Running postgres-operator in Rancher

### ISSUE THREAD

**Issue by internetuser2008** [CrunchyData/postgres-operator#1667]
Would I be able to follow same [quick start](https://access.crunchydata.com/documentation/postgres-operator/4.3.2/quickstart/) example to deploy postgres-operator on Rancher

**Comment by jkatz** [comment]
Probably.

I don't know if the "very, very quickstart" works as that is geared towards things like minikube/Code Ready Containers, and we don't test in Rancher, but there are likely overlapping elements.
