### ISSUE TITLE
"Failed to provision volume with StorageClass"

### ISSUE THREAD

**Issue by yattagit** [CrunchyData/postgres-operator#1672]
Hi,
I'm trying to deploy Postgre cluster with pgo on Azure.
PGO client installed successfully,

```
bash-4.2$ pgo version
pgo client version 4.3.2
pgo-apiserver version 4.3.2
```

But when I try to create a basic cluster with the command below, pods and pvc's are not being created.

`pgo create cluster testcluster`

Pod's and PVC's status are ; Pending
When I check with "kubectl describe pvc testcluster", I can see the error below.

>   Warning  ProvisioningFailed  15s (x2 over 24s)  persistentvolume-controller  Failed to provision volume with StorageClass "default": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported

How can I solve this problem?

Thanks!

**Comment by eliranw** [comment]
When installing the Postgres-operator itself, you configure the storage modes for the PVs with the storage variables in postgres-operator.yml or ansible inventory depending on your installation method.
The steps to fix this are:
1. Change the access mode in the postgres-operator.yml as so:
storage<ID>_access_mode: 'ReadWriteOnce' 
where ID is the ID of the storage that you're using.
2. Update or uninstall and install the operator again.

**Comment by jkatz** [comment]
I don’t think I could have said it better than @eliranw - thanks!
