### ISSUE TITLE
how to add nodeaffinity to postgre-operator deployment ?

### ISSUE THREAD

**Issue by StephenLiuYa** [CrunchyData/postgres-operator#1680]
** Which example are you working with? **
Developer

**What is the current behavior?**
I want to scheduler the postgre-operator to a special node, now I should edit the ansible tempalte and the rebuild the image

**What is the expected behavior?**
Is there a simple way but rebuild the deployer image?

**Other information** (e.g. detailed explanation, related issues,  etc)

* Operating System: Linux
* Where is this running ( Local , Cloud Provider)
* Container Image Tag: registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version:

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-07-01T07:52:46Z"
  generation: 1
  labels:
    vendor: crunchydata
  name: postgres-operator
  namespace: pgo
  resourceVersion: "1866454321"
  selfLink: /apis/apps/v1/namespaces/pgo/deployments/postgres-operator
  uid: ee62192a-2f0a-4325-a903-b058e24ca0e0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: postgres-operator
      vendor: crunchydata
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: postgres-operator
        vendor: crunchydata
    spec:
      containers:
```

I want to add node affinity in Spec， is there a convenient way？

**Comment by jkatz** [comment]
If you are looking to add node affinity to PostgreSQL instances, this is discussed in the [documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/#node-affinity).

If you want to add Node Affinity to the “postgres-operator” deployment itself, I suggest consulting the [Kubernetes documentation for how to set node affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/). You can edit the “postgres-operator” as you see fit, though you may need to keep track of those edits for upgrades and other scenarios.
