### ISSUE TITLE
Storage setting for rancher fails with permission 

### ISSUE THREAD

**Issue by internetuser2008** [CrunchyData/postgres-operator#1684]
**Describe the bug**
When storage is define the database pod fails with permission. 
mkdir: cannot create directory '/pgdata/bpg': **Permission denied** 

Not sure if this is but may be related to setting with Rancher storage. When left default as "hostpathstorage" pvc claim fails but, when manually created pvc it works fine. 

A storage setting suggestion would be appreciated. 

**To Reproduce**
1. Set the storage in postgres-operator.yml
```
                  - name: STORAGE1_NAME
                    value: "hostpathstorage"
                  - name: STORAGE1_ACCESS_MODE
                    value: "ReadWriteMany"
                  - name: STORAGE1_SIZE
                    value: "1G"
                  - name: STORAGE1_TYPE
                    value: "dynamic"
                    # value: "create"
                  - name: STORAGE1_CLASS
                    value: "cinder-release"
                  ....
                   - name: DISABLE_FSGROUP
                    value: "false"

```

2. PVC created 
![image](https://user-images.githubusercontent.com/13987590/86295732-e34de480-bbbc-11ea-98a2-7899bf2d4054.png)

![image](https://user-images.githubusercontent.com/13987590/86295601-979b3b00-bbbc-11ea-9215-a48c57eedc58.png)

**Expected behavior**
The permission should be set go group id 26. When change /pgdata permission it work as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/13987590/86295173-9e757e00-bbbb-11ea-9667-b2c549695ec9.png)

**Please tell us about your environment:**

* Operating System: Ubunt
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): cinder-release
* Container Image Tag: "centos7-4.3.2"
* PostgreSQL Version: 12
* Platform (Docker, Kubernetes, OpenShift): Rancher
* Platform Version: 4.3.2

**Additional context**

**Comment by jkatz** [comment]
It might need a supplemental group.

**Comment by internetuser2008** [comment]
Was able to get the database pod crated by updating pvc from RWX(Many) to RWO(single) then stanza job fails

Adding additional stanza create failure due to storage.

```
time="2020-07-08T16:26:28Z" level=info msg="pgo-backrest starts"
time="2020-07-08T16:26:28Z" level=info msg="debug flag set to false"
time="2020-07-08T16:26:28Z" level=info msg="backrest stanza-create command requested"
time="2020-07-08T16:26:28Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.42.1.149 --db-path=/pgdata/hippo1]"
time="2020-07-08T16:26:28Z" level=info msg="command is pgbackrest stanza-create  --db-host=10.42.1.149 --db-path=/pgdata/hippo1 "
time="2020-07-08T16:26:29Z" level=error msg="command terminated with exit code 47"
time="2020-07-08T16:26:29Z" level=info msg="output=[]"
time="2020-07-08T16:26:29Z" level=info msg="stderr=[ERROR: [047]: unable to create path '/backrestrepo/hippo1-backrest-shared-repo': [13] Permission denied\n]"
time="2020-07-08T16:26:29Z" level=error msg="command terminated with exit code 47"
```
try update the directory permission inside pod but pgbackrest doesn't permission  ;-(

**Comment by jkatz** [comment]
You will need to set the the pgBackRest storage configuration, detailed here:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/pgo-yaml-configuration/#storage](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/pgo-yaml-configuration/#storage)

You will likely need similar settings to the storage configuration you've configured for your PostgreSQL instances.

Anyway, this does not appear to be a bug.
