### ISSUE TITLE
Adding an option to change S3 CA in pgo-deployer

### ISSUE THREAD

**Issue by eliranw** [CrunchyData/postgres-operator#1686]
**What is the motivation or use case for the change?**
We recently switched to deploying postgres-operator with the pgo-deployer installation method instead of Ansible on prem, and we are getting issues with backups to S3. The issues seems to be that the S3 CA certificate is not configured to our S3, which is something we used to fix by changing the aws-s3-ca.crt file ourselves after cloning the git repo, but this doesn't seem to be an option with this installation method. We would still like to use this easier method but would like to have an option to give the ca as a parameter or secret somehow.

**Describe the solution you'd like**
There are many ways to fix this:
1. Change the secret containing the ca after creating clusters automatically - seems like a bad idea.
2. Adding a layer on top of the pgo-deployer image with our own CA file - we might use this solution as we don't have much of a choice, but would like a permanent and easier way.
3. Add an easy way to configure this while installing the operator - we want this.

**Please tell us about your environment:**

* Where is this running On prem
* Storage being used vsphere-disk
* Container Image Tag: 12
* PostgreSQL Version: 4.3.2
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 3.11

**Comment by jkatz** [comment]
Thanks for using `pgo-deployer`!

There are a few options available today, they all involve having created the `pgbackrest-s3-ca-secret` prior:

- Create the AWS S3 secret to use prior to the install, and specify the name of the Secret to use with `BACKREST_AWS_S3_SECRET`. This is not far off to what you were doing to customize the value of `aws-s3-ca.crt` from the previous method, you would just do this up front (and is actually, what the installer does itself). This understandably could be better documented, though the hold up could be around some changes we want to make to the Secret composition (e.g. some of the items in that Secret are not necessarily secret).

- Specify the `--pgbackrest-s3-ca-secret` on the [`pgo create cluster`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) command, which comes with the following instructions:

```      --pgbackrest-s3-ca-secret string        If used, specifies a Kubernetes secret that uses a different CA certificate for S3 or a S3-like storage interface. Must contain a key with the value "aws-s3-ca.crt"```

Presently, the installation method for setting the custom CA mirrors that of the Ansible installer (and I doubled checked the code on both), what you were doing is still currently supported by the `pgo-deployer` method. I think we can consider an easier way to bring in a custom CA certificate, given it's not a value that one needs to keep Secret in the sense of visibility, but it also something you don't want to be tampered with.

**Comment by eliranw** [comment]
Thank you for the quick reply! I did not know the solution was this easy.
