### ISSUE TITLE
Multiple Postgres Instances in one cluster

### ISSUE THREAD

**Issue by ivorpad** [CrunchyData/postgres-operator#1693]
Hi everyone,

I'm doing some research to see if it's possible to create a _PostgreSQL As a Service_ app running either on GKS or EKS, but as some of you know Google introduced a management fee per cluster of $0.10/hr.

I'm wondering if it's possible to run multiple instances of PostgreSQL in one cluster. If that's not possible then I don't think it's really cost-effective to start a DBaaS running on GKS/EKS nowadays.

**Comment by jkatz** [comment]
Yes, it is very easy to create multiple PostgreSQL instances in a single Kubernetes cluster. Though the examples in the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/) and [common tasks](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#provisioning-create-view-destroy) guide show individual PostgreSQL instance, you can easily double the commands up, e.g.:

```shell
pgo create cluster hippo
pgo create cluster lemur
```

etc. Each of these commands adds a PostgreSQL instance within your existing Kubernetes cluster.
