### ISSUE TITLE
changing max_connection in pgha_config map not changing the max_connection of database

### ISSUE THREAD

**Issue by pjhamnani** [CrunchyData/postgres-operator#1699]
I am trying to increase max_connections for Postgres by changing pgha_config map.

It should ideally change the value to 200, which i have set.

But the same is not getting reflected. 

Infact even shutdown command does not have any effect.

Will appreciate if someone can help me figure out the issue.

OS is RHEL
We are running local kubernetes cluster, v1.17
Storage used is NFS
Container image : registry.developers.crunchydata.com/crunchydata/postgres-operator:centos7-4.3.0

Describe POD output:
===========================
Name:         tms-ymgk-7d66cf544b-6r7w8
Namespace:    pgo
Priority:     0
Node:         ndc3vlnptms06/10.94.240.62
Start Time:   Mon, 22 Jun 2020 21:41:33 +0530
Labels:       NodeLabelKey=role
              NodeLabelValue=worker
              crunchy-pgha-scope=tms-ymgk
              crunchy_collect=true
              deployment-name=tms-ymgk
              name=tms
              pg-cluster=tms
              pg-pod-anti-affinity=
              pgo-pg-database=true
              pgo-version=4.3.0
              pod-template-hash=7d66cf544b
              role=master
              service-name=tms
              vendor=crunchydata
              workflowid=eb45b432-1364-4c69-bc54-9cabdcbf3134
Annotations:  status:
                {"conn_url":"postgres://10.32.0.4:5432/postgres","api_url":"http://10.32.0.4:8009/patroni","state":"running","role":"master","version":"1....
Status:       Running
IP:           10.32.0.4
IPs:
  IP:           10.32.0.4
Controlled By:  ReplicaSet/tms-ymgk-7d66cf544b
Containers:
  database:
    Container ID:   docker://287832429c68fa77f0a97c53172b3e36980b626ad98c2477dccf500da627fd17
    Image:          192.168.0.162:5000/registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos7-12.2-4.3.0
    Image ID:       docker-pullable://192.168.0.162:5000/registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha@sha256:a87e1e8b6b465b75b539c6f6f186d59d95b2595dd60d9b4aa272e6e8dc87fdfb
    Ports:          5432/TCP, 8009/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Mon, 22 Jun 2020 21:41:35 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:  4
    Requests:
      cpu:      4
      memory:   10G
    Liveness:   exec [/opt/cpm/bin/health/pgha-liveness.sh] delay=30s timeout=10s period=15s #success=1 #failure=3
    Readiness:  exec [/opt/cpm/bin/health/pgha-readiness.sh] delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PGHA_PG_PORT:                       5432
      PGHA_USER:                          postgres
      PGHA_INIT:                          <set to the key 'init' of config map 'tms-pgha-config'>  Optional: false
      PATRONI_POSTGRESQL_DATA_DIR:        /pgdata/tms-ymgk
      PGBACKREST_STANZA:                  db
      PGBACKREST_REPO1_HOST:              tms-backrest-shared-repo
      BACKREST_SKIP_CREATE_STANZA:        true
      PGHA_PGBACKREST:                    true
      PGBACKREST_REPO1_PATH:              /backrestrepo/tms-backrest-shared-repo
      PGBACKREST_DB_PATH:                 /pgdata/tms-ymgk
      ENABLE_SSHD:                        true
      PGBACKREST_LOG_PATH:                /tmp
      PGBACKREST_PG1_SOCKET_PATH:         /tmp
      PGBACKREST_PG1_PORT:                5432
      PGBACKREST_REPO_TYPE:               posix
      PGHA_PGBACKREST_LOCAL_S3_STORAGE:   false
      PGHA_DATABASE:                      tms
      PGHA_CRUNCHYADM:                    true
      PGHA_REPLICA_REINIT_ON_START_FAIL:  true
      PGHA_SYNC_REPLICATION:              false
      PGHA_TLS_ENABLED:                   false
      PGHA_TLS_ONLY:                      false
      PGHA_STANDBY:                       false
      PATRONI_KUBERNETES_NAMESPACE:       pgo (v1:metadata.namespace)
      PATRONI_KUBERNETES_SCOPE_LABEL:     crunchy-pgha-scope
      PATRONI_SCOPE:                       (v1:metadata.labels['crunchy-pgha-scope'])
      PATRONI_KUBERNETES_LABELS:          {vendor: "crunchydata"}
      PATRONI_LOG_LEVEL:                  INFO
      PGHOST:                             /tmp
    Mounts:
      /backrestrepo from backrestrepo (rw)
      /crunchyadm from crunchyadm (rw)
      /dev/shm from dshm (rw)
      /pgconf from pgconf-volume (rw)
      /pgconf/pgreplicator from primary-volume (rw)
      /pgconf/pgsuper from root-volume (rw)
      /pgconf/pguser from user-volume (rw)
      /pgdata from pgdata (rw)
      /recover from recover-volume (rw)
      /sshd from sshd (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-rmnp2 (ro)
  collect:
    Container ID:   docker://9da5b7d2beeed6518040f3b3bd50f3af4c9fd19cc4a7348b2d704ee06d0cb20b
    Image:          192.168.0.162:5000/registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-12.2-4.3.0
    Image ID:       docker-pullable://192.168.0.162:5000/registry.developers.crunchydata.com/crunchydata/crunchy-collect@sha256:8c31108a0b3cb8a688cd7835fb6a2dc690e3e5f8d33d06b0b5907bc1a0572bd7
    Port:           9187/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 22 Jun 2020 21:41:35 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      COLLECT_PG_HOST:         127.0.0.1
      COLLECT_PG_PORT:         5432
      COLLECT_PG_DATABASE:     postgres
      COLLECT_PG_PARAMS:       sslmode=disable
      JOB_NAME:                tms
      POSTGRES_EXPORTER_PORT:  9187
    Mounts:
      /collect-pguser from collect-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-rmnp2 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  pgdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  tms-ymgk
    ReadOnly:   false
  user-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-tmsuser-secret
    Optional:    false
  primary-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-primaryuser-secret
    Optional:    false
  collect-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-collect-secret
    Optional:    false
  sshd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-backrest-repo-config
    Optional:    false
  root-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-postgres-secret
    Optional:    false
  recover-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  report:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  backrestrepo:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  crunchyadm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  pgconf-volume:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      tms-pgha-config
    ConfigMapOptional:  0xc0008f307d
  pgo-pg-token-rmnp2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgo-pg-token-rmnp2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by jkatz** [comment]
I was unable to reproduce this issue. Here are the steps I followed, using the documentation on [custom configuration](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/):

1. Created a cluster `pgo create cluster hippo`
2. Once the cluster was ready, I ran `kubectl -n pgo edit cm hippo-pgha-config` and modified the following block:

```yaml
data:
  hippo-dcs-config: |
    postgresql:
      parameters:
        max_connections: 200
```

and saved.

3. I waited a moment, and then ran:

`pgo restart hippo --target hippo`

Once the cluster came back online, I executed `SHOW max_connections`:

```
 max_connections 
-----------------
 200
(1 row)
```
