### ISSUE TITLE
pgha config changes not getting reflected , even post restart

### ISSUE THREAD

**Issue by pjhamnani** [CrunchyData/postgres-operator#1710]
I am trying to increase shared memory and max connections attribute of my cluster, by altering pgha-config map. 
But post restart of the cluster, the changed values are not refleted.

My pgha config map (Changed one) is:

apiVersion: v1
data:
  init: "false"
  tms-dcs-config: "postgresql:\n  parameters:\n    archive_command: source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh
    && pgbackrest\n      archive-push \"%p\"\n    archive_mode: true\n    archive_timeout:
    60\n    log_directory: pg_log\n    log_min_duration_statement: 60000\n    log_statement:
    none\n    max_wal_senders: 6\n    shared_buffers: 3000MB\n    huge_pages: off
    \n    shared_preload_libraries: pgaudit.so,pg_stat_statements.so\n    temp_buffers:
    8MB\n    unix_socket_directories: /tmp,/crunchyadm\n    wal_level: logical\n    work_mem:
    4MB\n    max_connections: 200\n  recovery_conf:\n    restore_command: source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh
    && pgbackrest\n      archive-get %f \"%p\"\n  use_pg_rewind: true\n"
  tms-ymgk-local-config: |
    postgresql:
      callbacks:
        on_role_change: /opt/cpm/bin/callbacks/pgha-on-role-change.sh
      create_replica_methods:
      - pgbackrest
      - basebackup
      pg_hba:
      - local all postgres peer
      - local all crunchyadm peer
      - host replication primaryuser 0.0.0.0/0 md5
      - host all primaryuser 0.0.0.0/0 reject
      - host all all 0.0.0.0/0 md5
      pgbackrest:
        command: /opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh
        keep_data: true
        no_params: true
      pgbackrest_standby:
        command: /opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh
        keep_data: true
        no_master: 1
        no_params: true
      pgpass: /tmp/.pgpass
      remove_data_directory_on_rewind_failure: true
      use_unix_socket: true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-01T13:08:39Z"
  labels:
    pg-cluster: tms
    pgha-config: "true"
    vendor: crunchydata
  name: tms-pgha-config
  namespace: pgo

Our cluster name is "tms"
OS is RHEL
PGO version is "4.3.0"
Storage used is "NFS"
We are using Kubernetes

 kubectl describe yourPodName

Name:         tms-ymgk-7d66cf544b-nxfc2
Namespace:    pgo
Priority:     0
Node:         ndc3vlnptms06/10.94.240.62
Start Time:   Fri, 10 Jul 2020 21:12:01 +0530
Labels:       NodeLabelKey=role
              NodeLabelValue=worker
              crunchy-pgha-scope=tms-ymgk
              crunchy_collect=true
              deployment-name=tms-ymgk
              name=tms
              pg-cluster=tms
              pg-pod-anti-affinity=
              pgo-pg-database=true
              pgo-version=4.3.0
              pod-template-hash=7d66cf544b
              role=master
              service-name=tms
              vendor=crunchydata
              workflowid=eb45b432-1364-4c69-bc54-9cabdcbf3134
Annotations:  status:
                {"conn_url":"postgres://10.32.0.4:5432/postgres","api_url":"http://10.32.0.4:8009/patroni","state":"running","role":"master","version":"1....
Status:       Running
IP:           10.32.0.4
IPs:
  IP:           10.32.0.4
Controlled By:  ReplicaSet/tms-ymgk-7d66cf544b
Containers:
  database:
    Container ID:   docker://a4e7095a51ab08fa9d0910e413fbe3806efbf82f271fd8808ebb1fe56eca2688
    Image:          192.168.0.162:5000/registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos7-12.2-4.3.0
    Image ID:       docker-pullable://192.168.0.162:5000/registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha@sha256:a87e1e8b6b465b75b539c6f6f186d59d95b2595dd60d9b4aa272e6e8dc87fdfb
    Ports:          5432/TCP, 8009/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 10 Jul 2020 21:14:50 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:  4
    Requests:
      cpu:      4
      memory:   10G
    Liveness:   exec [/opt/cpm/bin/health/pgha-liveness.sh] delay=30s timeout=10s period=15s #success=1 #failure=3
    Readiness:  exec [/opt/cpm/bin/health/pgha-readiness.sh] delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PGHA_PG_PORT:                       5432
      PGHA_USER:                          postgres
      PGHA_INIT:                          <set to the key 'init' of config map 'tms-pgha-config'>  Optional: false
      PATRONI_POSTGRESQL_DATA_DIR:        /pgdata/tms-ymgk
      PGBACKREST_STANZA:                  db
      PGBACKREST_REPO1_HOST:              tms-backrest-shared-repo
      BACKREST_SKIP_CREATE_STANZA:        true
      PGHA_PGBACKREST:                    true
      PGBACKREST_REPO1_PATH:              /backrestrepo/tms-backrest-shared-repo
      PGBACKREST_DB_PATH:                 /pgdata/tms-ymgk
      ENABLE_SSHD:                        true
      PGBACKREST_LOG_PATH:                /tmp
      PGBACKREST_PG1_SOCKET_PATH:         /tmp
      PGBACKREST_PG1_PORT:                5432
      PGBACKREST_REPO_TYPE:               posix
      PGHA_PGBACKREST_LOCAL_S3_STORAGE:   false
      PGHA_DATABASE:                      tms
      PGHA_CRUNCHYADM:                    true
      PGHA_REPLICA_REINIT_ON_START_FAIL:  true
      PGHA_SYNC_REPLICATION:              false
      PGHA_TLS_ENABLED:                   false
      PGHA_TLS_ONLY:                      false
      PGHA_STANDBY:                       false
      PATRONI_KUBERNETES_NAMESPACE:       pgo (v1:metadata.namespace)
      PATRONI_KUBERNETES_SCOPE_LABEL:     crunchy-pgha-scope
      PATRONI_SCOPE:                       (v1:metadata.labels['crunchy-pgha-scope'])
      PATRONI_KUBERNETES_LABELS:          {vendor: "crunchydata"}
      PATRONI_LOG_LEVEL:                  INFO
      PGHOST:                             /tmp
    Mounts:
      /backrestrepo from backrestrepo (rw)
      /crunchyadm from crunchyadm (rw)
      /dev/shm from dshm (rw)
      /pgconf from pgconf-volume (rw)
      /pgconf/pgreplicator from primary-volume (rw)
      /pgconf/pgsuper from root-volume (rw)
      /pgconf/pguser from user-volume (rw)
      /pgdata from pgdata (rw)
      /recover from recover-volume (rw)
      /sshd from sshd (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-rmnp2 (ro)
  collect:
    Container ID:   docker://fbb5f3a92b061cf6e0e74ebd3625e362e8c99191d4b1af42e6d50d3b6366a80d
    Image:          192.168.0.162:5000/registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-12.2-4.3.0
    Image ID:       docker-pullable://192.168.0.162:5000/registry.developers.crunchydata.com/crunchydata/crunchy-collect@sha256:8c31108a0b3cb8a688cd7835fb6a2dc690e3e5f8d33d06b0b5907bc1a0572bd7
    Port:           9187/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 10 Jul 2020 21:12:02 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      COLLECT_PG_HOST:         127.0.0.1
      COLLECT_PG_PORT:         5432
      COLLECT_PG_DATABASE:     postgres
      COLLECT_PG_PARAMS:       sslmode=disable
      JOB_NAME:                tms
      POSTGRES_EXPORTER_PORT:  9187
    Mounts:
      /collect-pguser from collect-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-rmnp2 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  pgdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  tms-ymgk
    ReadOnly:   false
  user-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-tmsuser-secret
    Optional:    false
  primary-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-primaryuser-secret
    Optional:    false
  collect-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-collect-secret
    Optional:    false
  sshd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-backrest-repo-config
    Optional:    false
  root-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tms-postgres-secret
    Optional:    false
  recover-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  report:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  backrestrepo:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  crunchyadm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  pgconf-volume:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      tms-pgha-config
    ConfigMapOptional:  0xc000b14eed
  pgo-pg-token-rmnp2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgo-pg-token-rmnp2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

Interestingly, shutdown command, i.e
pgo update cluster tms --shutdown

did not brought my cluster down. Infact it has no imapact. Its only when i stopped operater , by issueing kubectl delete pod command, that my Database pod got terminated.

Please help. Please suggest, the log files which you will require to check the issue.

** Which example are you working with? **

**What is the current behavior?**

**What is the expected behavior?**

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by jkatz** [comment]
The short answer is to upgrade to 4.3.2 and follow the instructions from the [previous ticket](https://github.com/CrunchyData/postgres-operator/issues/1699#issuecomment-656315186).

The longer answer can be a variety of things. You may need to wait a few moments for the ConfigMap settings to propagate to the Pod. It can vary based on the refresh period of your Kubernetes environment.

Also as mentioned [specifically](https://github.com/CrunchyData/postgres-operator/issues/1699#issuecomment-656315186) in #1699 the restart command is `pgo restart hippo --target hippo`. It appears you're on 4.3.0, in which case you should update to 4.3.2 which contains bug fixes to the custom configuration support, as well as the restart command. When a newer patch release is out (e.g. 4.3.2), it is not advised to run an older patch release (e.g. 4.3.0), nor can we support it.

Lastly, please try to use the Github markdown formatting when presenting logs and commands, as it is very difficult to read and diagnose what the issue is. Thanks!
