### ISSUE TITLE
PGO 2.5 rc2 doc error

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/postgres-operator#172]
PGO Backup.
we create a backup using:
pgo backup mycluster

then we delete using:
pgo delete backup mybackup

Doesn't flow as there is no mybackup but there is a mycluster backup to delete

**Comment by jmccormick2001** [comment]
thanks, fixed in master.

**Comment by altondinsmore** [comment]
Am I driving you crazy with little things like this?
If so I can skip them.
Just let me know.

Alton

**Comment by jmccormick2001** [comment]
keep em coming!
