### ISSUE TITLE
Deploy cluster in another namespace

### ISSUE THREAD

**Issue by srikarrampa** [CrunchyData/postgres-operator#1725]
** Which example are you working with? **
I have currently deployed PostgreSQL operator in namespace "pgo". What is the pgo command to deploy clusters in a different namespace? Couldn't find it in the documentation. 

Changes done:
export PGO-OPERATOR-NAMESPACE=pgo
export NAMESPACE=my-namespace

What changes need to be done in postgres-operator.yml file?

* Where is this running ( Local )
* Platform (Kubernetes):
* Platform Version: 4.3.2

**Comment by jkatz** [comment]
First, you need to ensure that you have set up your PostgreSQL Operator deployment to handle multiple namespaces. This is covered in the [Namespace Management](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/) section of the docs.

If you want to deploy a cluster in a namespace, e.g. `db`, you would do the following:

```
pgo create cluster -n db hippo
```

This is covered in many places in the [documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/) such as the beginning of the "common tasks" section.

**Comment by srikarrampa** [comment]
https://github.com/CrunchyData/postgres-operator/blob/v4.3.2/installers/kubectl/postgres-operator.yml - I'm currently using this yml file and I think this includes to handle multiple namespaces. Could you tell me if I still need to add anything?

Thank you!

**Comment by jkatz** [comment]
The default file sets up the `dynamic` namespace mode, so you can create and delete namespaces during the lifecycle of the PostgreSQL Operator. From within these namespaces, the PostgreSQL Operator will watch for changes to its various PostgreSQL objects and react accordingly.

If you defined namespaces in the `NAMESPACE` clause on install, with the `dynamic` namespace mode, it will create those namespaces if they do not exist.

If you need to add a namespace to be watched after the fact, you can do the following

```
pgo create namespace newns
pgo create cluster -n newns hippo
```
