### ISSUE TITLE
Brand new 4.4.0 deployment via kubectl does not find image for pgo-deploy

### ISSUE THREAD

**Issue by MarkusNeviadomski** [CrunchyData/postgres-operator#1727]
Hi, I've tried to setup the brand new 4.4.0 worth the kubectl apply -f based on the postgres-operator.yaml from repo. 

But k8s is not able to fetch the given image from crunchy repo.

ImagePullBackOff: Back-off pulling image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.4.0"

Is there an issue in the yaml file or is the image still not published?

**Please tell us about your environment:**
Kubernetes 15.x on syseleven metakube

Regards, Markus

**Comment by jkatz** [comment]
These images have not been pushed out publicly yet.

**Comment by MarkusNeviadomski** [comment]
Thanks for the fast answer. Do you have an approach, until when these image will be pushed?

**Comment by jkatz** [comment]
Yes - download the 4.3.2 images :smile:

You can find instructions [here](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator) or [here](https://access.crunchydata.com/documentation/postgres-operator/4.3.2/quickstart/)

Note that there are images available for 4.4.0-beta.2 as alluded to in that first link, but I would caution using those at your own discretion as those are unsupported.

**Comment by MarkusNeviadomski** [comment]
Hi, I need the path style  configuration variable from pgbouncer  that is introduced on 4.4.0 in production setup :( 

So 4.3.2 isn't a option.

**Comment by kaoet** [comment]
I recommand uploading the images first before publishing a new release, or users will be confused when they installing the new one.

**Comment by jkatz** [comment]
It's still noted as a "pre-release" as of this writing.😉 

We apply a tag so that our build team can build off of the tag, scan, and certify the images, and distribute them to our customer repositories. Once that process is completed, we upload them to the public repositories.

**Comment by MarkusNeviadomski** [comment]
Good to know, maybe it's a good idea to make this process little bit transparent or make the image registry browsable.

How long does this process normally takes? Because I need the backup feature, so I need to decide if I go ahead with Beta release or if  I can wait until official release is available as public.

**Comment by jkatz** [comment]
Good point on the documentation. It is something I've personally had in the hopper for a bit, but I'm going to try to get that out the door.

It typically takes a couple of days from tag to public facing images. The good news is that it's been a couple of days since the tag drop, so the images should be available soon.

I don't want to overpromise/underdeliver, but knowing that the public rollout is already in progress, the images should be available in the next 24 hours.

Thanks!

**Comment by MarkusNeviadomski** [comment]
Cool! I'm on leave for the next days, so it seems to have a good chance that image is online if I am back :)

**Comment by jkatz** [comment]
@MarkusNeviadomski Hopefully this is considered overdelivery, as the images are now available:

[https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator)

Thanks for your patience!
