### ISSUE TITLE
Upgrading Operator?

### ISSUE THREAD

**Issue by strigona-worksight** [CrunchyData/postgres-operator#1730]
** Which example are you working with? **
I installed the operator using the instructions here: https://access.crunchydata.com/documentation/postgres-operator/4.4.0/installation/postgres-operator/ (well version 4.3.2 last week) and figured I'd update to 4.4.0, however I cannot find any upgrade guidelines that match those installation instructions.

As I understand there are several installation options: bash, ansible, helm and the "quickstart". I can find upgrade instructions for the "quickstart" installation type. In general is there an installation type that is more commonly used/recommended?

**Comment by jkatz** [comment]
There is a top level section for this in the sidebar of the documentation:

[https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/)

**Comment by strigona-worksight** [comment]
Thanks for the reply, I did find that, however it I don't see upgrade instructions targeted towards the "quickstart" installation method.

The [manual upgrade](https://access.crunchydata.com/documentation/postgres-operator/4.4.0/upgrade/manual/upgrade4/) says:
>  If you are upgrading PostgreSQL 12 clusters, you MUST use the Automated Upgrade Procedure.

The [automated upgrade](https://access.crunchydata.com/documentation/postgres-operator/4.4.0/upgrade/automatedupgrade/) has two sections on upgrading the operator: "Automated Upgrade when using an Ansible installation of the PostgreSQL Operator" and "Automated Upgrade when using a Bash installation of the PostgreSQL Operator".

**Comment by jkatz** [comment]
Those are subsections. The procedure is listed int eh section below:

[https://access.crunchydata.com/documentation/postgres-operator/4.4.0/upgrade/automatedupgrade/#postgresql-operator-automated-cluster-upgrade](https://access.crunchydata.com/documentation/postgres-operator/4.4.0/upgrade/automatedupgrade/#postgresql-operator-automated-cluster-upgrade)

I can see how some of that wording could be confusing. @tjmoore4 perhaps we change `Automated PostgreSQL Operator Upgrade Procedure` to `Prerequisites`?

**Comment by strigona-worksight** [comment]
Thanks again for your reply. My understanding the section `PostgreSQL Operator Automated Cluster Upgrade` is to upgrade the cluster after the operator itself has been upgraded.

I'm looking for a procedure to upgrade the operator itself.

I have also been trying to adjust values in the original `postgres-operator.yml` from the [installation page](https://crunchydata.github.io/postgres-operator/4.4.0/installation/postgres-operator/#configuration-postgres-operator-yml) by changing the `DEPLOY_ACTION` environment variable, but the job keeps failing - granted I'm just taking wild guesses at this point.

**Comment by tjmoore4** [comment]
You are correct, the instructions above are for upgrading individual clusters. 

[Here](https://access.crunchydata.com/documentation/postgres-operator/4.4.0/upgrade/automatedupgrade/#automated-upgrade-when-using-an-ansible-installation-of-the-postgresql-operator) is the link to the Operator upgrade section. We will provide some updates to the docs to make it clearer.

**Comment by strigona-worksight** [comment]
@tjmoore4 Thanks - just saw your PR with the updated documentation, trying it out now.

**Comment by strigona-worksight** [comment]
Thanks for clearing that up for me - all good now :)
