### ISSUE TITLE
Openshift 4: StorageClass ignored in Cluster creation

### ISSUE THREAD

**Issue by fsc12** [CrunchyData/postgres-operator#1735]
We're using Crunchy 4.3.2 in Openshift 4.4. We  recognized that the StorageClass-Option in pgo.yaml is always ignored during the Postgres-Cluster creation.  The Postgres-Cluster has always been created with the default-Storage class.

pgo.yaml (included in ConfigMap pgo-config)

_Cluster:
  CCPImagePrefix:  registry.connect.redhat.com/crunchydata
  Metrics:  false
  Badger:  false
  CCPImageTag:  ubi7-12.3-4.3.2
  Port:  5432
  PGBadgerPort: 10000
  ExporterPort: 9187
  User:  "pgadmin"
  Database:  "postgres"
  PasswordAgeDays:  0
  PasswordLength:  24
  Replicas:  0
  ArchiveMode:  false
  ServiceType:  ClusterIP
  Backrest:  true
  BackrestPort:  2022
  BackrestS3Bucket: ""
  BackrestS3Endpoint: ""
  BackrestS3Region:
  DisableAutofail:  false
  PodAntiAffinity: preferred
  PodAntiAffinityPgBackRest: ""
  PodAntiAffinityPgBouncer: ""
  SyncReplication: false
  DefaultInstanceMemory: "128Mi"
  DefaultBackrestMemory:
  DefaultPgBouncerMemory:
  DisableFSGroup: true
PrimaryStorage: storageos
WALStorage:
BackupStorage: storageos
ReplicaStorage: storageos
BackrestStorage: storageos
Storage:
  hostpathstorage:
    AccessMode:  ReadWriteMany
    Size:  1G
    StorageType:  create
  replicastorage:
    AccessMode:  ReadWriteMany
    Size:  700M
    StorageType:  create
  nfsstorage:
    AccessMode:  ReadWriteMany
    Size:  1G
    StorageType:  create
    SupplementalGroups:  65534
  nfsstoragered:
    AccessMode:  ReadWriteMany
    Size:  1G
    MatchLabels: crunchyzone=red
    StorageType:  create
    SupplementalGroups:  65534
  storageos:
    AccessMode:  ReadWriteMany
    Size:  1G
    StorageType:  create
    StorageClass:  ontap-san-silver
  primarysite:
    AccessMode:  ReadWriteOnce
    Size:  4G
    StorageType:  dynamic
    StorageClass:  primarysite
  alternatesite:
    AccessMode:  ReadWriteOnce
    Size:  4G
    StorageType:  dynamic
    StorageClass:  alternatesite
  gce:
    AccessMode:  ReadWriteOnce
    Size:  300M
    StorageType:  dynamic
    StorageClass:  standard
  rook:
    AccessMode:  ReadWriteOnce
    Size:  1G
    StorageType:  dynamic
    StorageClass:  rook-ceph-block
Pgo:
  Audit:  false
  PGOImagePrefix: registry.connect.redhat.com/crunchydata
  PGOImageTag: ubi7-4.3.2_

After creating a cluster, eg.
$ pgo -n pgotest-dev create cluster fccluster  

we expected PVC's with StorageClass ontap-san-silver, but we always got ontap-silver which is the default StorageClass.

**Comment by jkatz** [comment]
Did you modify pgo.yaml and then restart the PostgreSQL Operator pod?

**Comment by fsc12** [comment]
Yes, I restarted the PostgreSQL Operator pod two times.

**Comment by eliranw** [comment]
We had a similar issue, after a removal and a clean installation it was fixed

**Comment by cbandy** [comment]
@fsc12 to use a StorageClass, the StorageType should be `dynamic`. See https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/pgo-yaml-configuration/
