### ISSUE TITLE
Documentation looks incorrect for ssl configuration

### ISSUE THREAD

**Issue by aceeric** [CrunchyData/postgres-operator#1736]
Folks - regarding this URL:

https://access.crunchydata.com/documentation/postgres-operator/4.0.1/gettingstarted/design/custom-config-ssl/

It references a script:

$PGOROOT/examples/ssl-creator.sh.

Which does not appear to exist (at least not in the master branch)

**Comment by jkatz** [comment]
4.0.1 is no longer supported as it is in [`REL_4_0_FINAL`](https://github.com/CrunchyData/postgres-operator/blob/master/CONTRIBUTING.md#releases--versioning).

TLS is now fully support in the PostgreSQL Operator itself. You can read about how to set up a TLS-enabled PostgreSQL cluster in the [current documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#enable-tls):

[https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#enable-tls](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#enable-tls).
