### ISSUE TITLE
backrest_aws_s3_uri_style

### ISSUE THREAD

**Issue by iamruhua** [CrunchyData/postgres-operator#1737]
** Can anyone explain what is backrest_aws_s3_uri_style? **
There is only a brief description about it in configuration reference. Can I just left it blank? I am new user to postgres operator

**Comment by jkatz** [comment]
If you are not using path style configuration (by default, AWS S3 does not use this), you can leave it blank.

For a detailed explanation for how backups and restores work, please see the [Disaster Recovery](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/) section of the documentation. And I would recommend reading through the whole "[Architecture](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/)" section to become familiar with the PostgreSQL Operator functionality, as well as the [Common Tasks](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/) which cover the "daily maintenance" operations.
