### ISSUE TITLE
namespace [pgo] is not part of the Operator installation after upgrade to 4.4.0

### ISSUE THREAD

**Issue by jdenisgiguere** [CrunchyData/postgres-operator#1740]
**Describe the bug**

When I try to use `pgo` client, I get the following error message:

```
Error: namespace [pgo] is not part of the Operator installation
```

**To Reproduce**
1.  `kubectl -n pgo exec -it deploy/pgo-client -- pgo test -n pgo --all`
2. See error

**Expected behavior**
I would expect the operator to work on any namespaces separated by a comma in the `values.yaml` file ex: `namespace:pgo,pgopanierbleu,pgowarehouse`

**Please tell us about your environment:**

* Operating System: Pop!_OS 20.04 LTS
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): GCE
* Container Image Tag: centos7-12.3-4.4.0
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version:  Client v1.18.6 / Server 1.17.7-gke.15
* Operator installer: Ansible
* Ansible Version: v.29.6 with python 3.8.2

**Additional context**

```
I can see in the ansible logs the three namespaces I expect the Postgres Operator to manage:
TASK [pgo-operator : Create Watched Namespaces] **********************************************************************************************************************************************
skipping: [localhost] => (item=pgo) 
skipping: [localhost] => (item=pgopanierbleu) 
skipping: [localhost] => (item=pgowarehouse) 
```

**Comment by jkatz** [comment]
Which `namespace_mode` did you use?

What does `pgo show namespace` say?

**Comment by jdenisgiguere** [comment]
`namespace_mode: "dynamic"`

It now works, but I'm not sure which changes solve the issue.

It looks like there was a mismatch between the previous `pgo_installation_name` and the current one.  Using the previous one seems to fix the issue.  

I also add a namespace.

This is a partial output of `pgo show namespace --all`:

```
pgo username: admin
namespace                useraccess          installaccess       
application-system       no access           no access           
default                  no access           no access           
kube-node-lease          no access           no access           
kube-public              no access           no access           
kube-system              no access           no access           
pgo                      accessible          accessible          
pgopanierbleu            accessible          accessible          
pgotoledo                no access           no access           
pgowarehouse             accessible          accessible          
warehouse                no access           no access    
```

**Comment by jkatz** [comment]
That should be it. Given the namespaces we already in place, the Operator was looking for the labels that matched `pgo_installation_name` on it for watching.

Namespace management has also shifted a bit over the past few releases. If you have not done so already, I recommend looking at the [Namespaces](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/) section of the documentation.

Glad it's all working!

**Comment by jdenisgiguere** [comment]
Thanks @jkatz !
