### ISSUE TITLE
Cluster set up from resources

### ISSUE THREAD

**Issue by aceeric** [CrunchyData/postgres-operator#1741]
Regarding: https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/

I'm trying to stand up a cluster purely from manifests and kustomize, without using the pgo client tool.

This section: Custom Resource Workflows > Create a PostgreSQL Cluster

Walks through the process of generating key materials, then converting those into a secret. Everything makes sense until this:
```
# create the backrest-repo-config example file and substitute in the newly
# created keys
cat <<-EOF > "${pgo_cluster_name}-backrest-repo-config.yaml"
apiVersion: v1
...
data:
...
  config: SG9zdCAqClN0cmljdEhvc3RLZXlDaGVja2luZyBubwpJZGVudGl0eUZpbGUgL3RtcC9pZF9lZDI1NTE5ClBvcnQgMjAyMgpVc2VyIHBnYmFja3Jlc3QK
  sshd_config: IwkkT3BlbkJTRDogc3NoZF9jb25maWcsdiAxLjEwMCAyMDE2LzA4LzE1IDEyOjMyOjA0IG5hZGR5IEV4cCAkCgojIFRoaXMgaXMgdGhlIHNzaGQgc2VydmVyIHN5c3RlbS13aWRlIGNvbmZpZ3VyYXRpb24gZmlsZS4gIFNlZQojIHNzaGRfY29uZmlnKDUpIGZvciBtb3JlIGluZm9ybWF0aW9uLgoKIyBUaGlzIHNzaGQgd2FzIGNvbXBpbGVkIH
```
The other key materials are from elements of the script. But the `config` and `sshd_config` keys get these blocks of what appear to be base-64 encoded data. It's not clear where they came from so doesn't instill confidence that they will just work further on down in the installation process.

Can some additional documentation be provided? Or - include the source of that content?

**Comment by jkatz** [comment]
You can get the contents of the files from [Decoding a Kubernetes Secret](https://kubernetes.io/docs/concepts/configuration/secret/#decoding-a-secret), e.g.:

`echo $config | base64 -d`

```
Host *
StrictHostKeyChecking no
IdentityFile /tmp/id_ed25519
Port 2022
User pgbackrest
```

These files container some overrides to ensure pgBackRest is able to properly function between the PostgreSQL instances and the pgBackRest repository.


We could probably simplify the `sshd_config` a bit and just include the lines that are not being overridden, so the blob would become smaller.

**Comment by jkatz** [comment]
I added some additional context to the documentation. Thanks for reporting!

**Comment by aceeric** [comment]
I would also offer that you can define the Secret with stringData fields and Kubernetes will auto-encrypt. This is useful in documentation where you're trying to present something that's partially self-documenting:
```
$ cat <<EOF | kubectl apply -f -
kind: Secret
apiVersion: v1
metadata:
  name: test
stringData:
  config: |
    Host *
    StrictHostKeyChecking no
    IdentityFile /tmp/id_ed25519
    Port 2022
    User pgbackrest
EOF
secret/test created
$ kubectl get secret test -o "jsonpath={.data['config']}" | base64 --decode
Host *
StrictHostKeyChecking no
IdentityFile /tmp/id_ed25519
Port 2022
User pgbackrest

```

**Comment by jkatz** [comment]
Thanks for the tip. Those secrets come from examples that were quite dated, and perhaps it'd be worth updating them to be a bit easier to read (and force some improvements to the overall structure).

**Comment by aceeric** [comment]
Thank you
