### ISSUE TITLE
How to change the storage size of the cluster

### ISSUE THREAD

**Issue by iamruhua** [CrunchyData/postgres-operator#1743]
Hi, I am new to pgo.
Currently we are starting a project to provide saas service to customers on aws eks. It's clear that database might need to change the storage size in the future. I can not find any command to change the size of the pgo managed postgresql cluster. And I tried to change the pvc created by pgo by editing the  pvc yaml configuration directly. k8s reports that, the pvc can not be updated because it's not dynamically provisioned.

I am using the gp2 storage class in pgo configuration. I am expecting the postgresql instances should be created with dynamic provisioned storage.  Is there any miss understanding? Or pgo just created those storage pv seperately?

Is there any correct way other than backup and restore procedure?

**Comment by jkatz** [comment]
You are correct, you would have to use `pgo create cluster newcluster --restore-from=oldcluster --resize_flags`. If availability is a concern, the techniques listed [here](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/) can help with that process.

At some point we will make it easier to resize the clusters. We do maintain compatibility back to versions of Kubernetes that do not have access to the ability to [resize PVCs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-an-in-use-persistentvolumeclaim). If you are on a compatible version of Kubernetes, you can always attempt to resize the PVC directly, though YMMV.

Lastly, the PostgreSQL Operator is designed to be storage class agnostic. It will provision a PVC based upon the storage configuration you pass in.

**Comment by jkatz** [comment]
For the open issue please see #1626
