### ISSUE TITLE
pgBouncer and pgPool with High Availability

### ISSUE THREAD

**Issue by junaid-a10** [CrunchyData/postgres-operator#1752]
**Which example are you working with?** 
I am working with kube pgpool example.

**Other information** (e.g. detailed explanation, related issues,  etc)
I want to run the postgres operator in a production environment and want every component to be able to scale and be fault tolerant. I want to use pgPool for connection pooling and load balancing read write queries. pgPool provides fault tolerance using Watchdog. Do I need pgPool with Watchdog for high availability or should I just use Kubernetes deployment with say replication factor of n?

Does Crunchy Postgres Operator provides High Availability for pgBouncer? Or do we need to setup HAproxy in front of pgBouncer? I am assuming it does since there is a --pgbouncer-replicas flag in create cluster command and load balancing can be leveraged from kubernetes service. Can the same be done for pgPool i.e. spinning up a deployment with n replicas?

**Please tell us about your environment:**

* Operating System: CentOS 7.8.2003
* Where is this running ( Local , Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: crunchy-pgpool:centos7-12.3-4.3.2, Postgres Operator Version 4.3.2
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: Kubernetes version 1.18

**Comment by jkatz** [comment]
The PostgreSQL Operator already provides HA / fault tolerance using distributed consensus, i.e. via Kubernetes. You can read about the architecture of this here:

- [High Availability](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/)

I would recommend reading through the above URL before making architecture decisions.

You can deploy multiple pgBouncer replicas as part of the PostgreSQL Operator. The Operator manages the # of pgBouncer replicas available (among other things).

The PostgreSQL Operator does not have an integration with pgPool II. You would have to manage that on your own. If you plan to deploy the Operator, I recommend you use its own built-in HA solution, as it provides distributed consensus HA.

To understand the overall architecture, I recommend reading the [Architecture](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/) section of the documentation. For understanding "daily operations", I recommend reading the [Common Tasks](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/) section.
