### ISSUE TITLE
pgBackrest stanza create fails with s3 backend (MinIO)

### ISSUE THREAD

**Issue by Fen0l** [CrunchyData/postgres-operator#1753]
**Which example are you working with?**
I am trying to use MinIO Object storage as s3 storage to backup pgsql databases.

**What is the current behavior?**
pgBackrest stanza create fails. It does not take parameters given to pgo create cluster. postgres-operator has been configured with proper S3 parameters:
```
backrest_aws_s3_bucket: "pgo-backrest"
backrest_aws_s3_endpoint: "10.10.0.05:9001"
backrest_aws_s3_key: "pgo-backrest"
backrest_aws_s3_region: "us-west-1"
backrest_aws_s3_secret: ""
backrest_aws_s3_uri_style: "true"
backrest_aws_s3_verify_tls: "false"
...
backrest_storage: "storageos"
backup_storage: "storageos"
primary_storage: "storageos"
replica_storage: "storageos"
...
storage5_name: "storageos"
storage5_access_mode: "ReadWriteOnce"
storage5_size: "25Gi"
storage5_type: "dynamic"
storage5_class: "storage-class-k8s"
```

other parameters has been left by default for now.

**Please tell us about your environment:**

* Operating System: CentOS
* Where is this running: local
* Storage being used: storageos
* Container Image Tag: 4.4.0
* Platform: Kubernetes
* Platform Version: 1.16

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:

Creation of PGCluster:
`pgo create cluster -n pgo --pgbackrest-s3-bucket="pgo-backrest" --pgbackrest-s3-endpoint="10.10.0.5:9001" --pgbackrest-s3-key="pgo-backrest" --pgbackrest-s3-key-secret="SECRET" --pgbackrest-storage-type="s3" --pgbackrest-s3-region="us-west-1" tests3-3`
```
➜  k logs tests3-3-stanza-create-4x4ks
time="2020-08-04T10:19:09Z" level=info msg="pgo-backrest starts"
time="2020-08-04T10:19:09Z" level=info msg="debug flag set to false"
time="2020-08-04T10:19:09Z" level=info msg="backrest stanza-create command requested"
time="2020-08-04T10:19:09Z" level=info msg="s3 flag enabled for backrest command"
time="2020-08-04T10:19:09Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=172.18.4.16 --db-path=/pgdata/tests3-3 --repo1-type=s3]"
time="2020-08-04T10:19:09Z" level=info msg="command is pgbackrest stanza-create  --db-host=172.18.4.16 --db-path=/pgdata/tests3-3 --repo1-type=s3 "
time="2020-08-04T10:19:09Z" level=error msg="command terminated with exit code 37"
time="2020-08-04T10:19:09Z" level=info msg="output=[]"
time="2020-08-04T10:19:09Z" level=info msg="stderr=[ERROR: [037]: stanza-create command requires option: repo1-s3-bucket\n]"
time="2020-08-04T10:19:09Z" level=error msg="command terminated with exit code 37"
````

```
➜  k logs tests3-3-backrest-shared-repo-5976445f65-zdzkc
Starting the pgBackRest repo
The pgBackRest repo has been started
```

Does postgres-operator 4.4.0 contain this fix ? i saw similar issue before.

Thanks for the help ,

**Comment by jkatz** [comment]
Set `backrest_aws_s3_uri_style: "true"` to either `backrest_aws_s3_uri_style: "path"` or `backrest_aws_s3_uri_style: "host"`
