### ISSUE TITLE
pgo version  : Error: Invalid Status Code: 400

### ISSUE THREAD

**Issue by pmpetit** [CrunchyData/postgres-operator#1754]
** Which example are you working with? **
https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator
**What is the current behavior?**

pgo version                  
pgo client version 4.4.0
Error: Invalid Status Code: 400

**What is the expected behavior?**
success
**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

kubectl -n pgo get pods                                         
NAME                                 READY   STATUS      RESTARTS   AGE
pgo-deploy-qwrls                     0/1     Completed   0          8d
postgres-operator-6f5b7d7698-f45b5   4/4     Running     0          8d

last logs from apiserver
time="2020-08-04T14:58:21Z" level=debug msg="got 1 services for pgwatch2-db" func="internal/apiserver/clusterservice.getServices()" file="internal/apiserver/clusterservice/clusterimpl.go:305" version=4.4.0
time="2020-08-04T14:58:21Z" level=debug msg="myselector is pg-cluster=pgwatch2-db" func="internal/kubeapi.GetpgreplicasBySelector()" file="internal/kubeapi/pgreplica.go:46" version=4.4.0
time="2020-08-04T14:58:21Z" level=debug msg="no replicas found" func="internal/apiserver/clusterservice.getReplicas()" file="internal/apiserver/clusterservice/clusterimpl.go:1601" version=4.4.0
time="2020-08-04T14:58:30Z" level=debug msg="versionservice.VersionHandler called" func="internal/apiserver/versionservice.VersionHandler()" file="internal/apiserver/versionservice/versionservice.go:40" version=4.4.0
time="2020-08-04T14:58:30Z" level=debug msg="Authentication Attempt Version username=[admin]" func="internal/apiserver.Authn()" file="internal/apiserver/root.go:327" version=4.4.0
time="2020-08-04T14:58:30Z" level=debug msg="Authentication Success" func="internal/apiserver.Authn()" file="internal/apiserver/root.go:346" version=4.4.0

pgo version --debug                                                                                                                                                                         
DEBU[0000] debug flag is set to true                    
DEBU[0000] in initConfig with url=http://127.0.0.1:8443 
DEBU[0000] GetSessionCredentials called                 
DEBU[0000] PGOUSER environment variable is being used at /home/user/.pgo/pgo/pgouser 
DEBU[0000] pgouser file found at /home/user/.pgo/pgo/pgouser contains admin:examplepassword 
DEBU[0000] [admin examplepassword]                      
DEBU[0000] username=[admin] password=[examplepassword]  
DEBU[0000] setting up httpclient with TLS               
DEBU[0000] GetTLSTransport called                       
DEBU[0000] version called                               
pgo client version 4.4.0
DEBU[0000] ShowVersion called                           
DEBU[0000] http://127.0.0.1:8443/version                
DEBU[0000] &{400 Bad Request 400 HTTP/1.0 1 0 map[] 0xc0004f8660 -1 [] true false map[] 0xc000290200 <nil>} 
DEBU[0000] http status code is 400                      
Error: Invalid Status Code: 400

**Comment by jkatz** [comment]
Do you have any Service proxies or anything between the Operator and your client?

Interestingly, the PostgreSQL Operator API server does not return any `400` error codes, so it sounds like something may be intercepting the response.

**Comment by pmpetit** [comment]
no proxies.....

**Comment by jkatz** [comment]
Do other requests work? It appears in your logs that there was a call to one of the `pgo * cluster` commands.

**Comment by pmpetit** [comment]
Hello, yes other requests from an other laptop are ok

**Comment by pmpetit** [comment]
using the example :
pgo show cluster -n pgo crdcluster                                                                                                                                                         Error:  Invalid Status Code: 400

**Comment by pmpetit** [comment]
i have install the pgo-client in a pod.
i still do not understand what is happening....

**Comment by pmpetit** [comment]
pffff, it was : 
PGO_APISERVER_URL='https://127.0.0.1:8443'
vs
PGO_APISERVER_URL='http://127.0.0.1:8443'
