### ISSUE TITLE
Can't scale to > 1 replica

### ISSUE THREAD

**Issue by aceeric** [CrunchyData/postgres-operator#1755]
We have the postgres operator 4.4.0 watching a namespace. We create a Pgcluster with spec.replicas="2". We never see the number of pods increase and in the operator logs we see:
```
pgreplica queue got key ns=[rco] resource=[crunchy-cluster-uozq]
working...no replica found, means we process
[pgreplica Controller] onUpdate ns=rco /apis/crunchydata.com/v1/namespaces/rco/pgreplicas/crunchy-cluster-uozq
replica crunchy-cluster not found file=internal/kubeapi/pgreplica.go:85
```
Note:
```
oc get pgreplica
NAME
crunchy-cluster-qwub
crunchy-cluster-uozq
```
If I look at that last point in the code, it looks like it is trying to get a resource without the unique string appended. The bottom line is - the cluster never scales up to more than one pod.

This is on OpenShift 3.11.59 / Kubernetes 1.11

**Comment by andrewlecuyer** [comment]
Did the initial pgBackRest stanza-create the backup jobs complete successfully?

The replicas will not bootstrap until these jobs are successful (specifically since a backup is needed to create the replicas), so wondering if there was an issue with one of these jobs during cluster initialization.

**Comment by aceeric** [comment]
I actually don't see any jobs at all. And:
```
oc logs crunchy-cluster-backrest-shared-repo-596988c495-xvfsx
Starting the pgBackRest repo
The pgBackRest repo has been started
```
I'm ramping up on Crunchy so forgive my ignorance.

**Comment by jkatz** [comment]
You would have to check for the Pods and/or Jobs within the namespace, e.g. if there is a `Job` with the suffix `stanza-create` that completed.

Likely the cluster did not properly initialize, and as such now replicas were able to be created.
