### ISSUE TITLE
User pgBouncer permission denied

### ISSUE THREAD

**Issue by junaid-a10** [CrunchyData/postgres-operator#1758]
** Which example are you working with? **
pgBouncer with postgres operator
 
**What is the current behavior?**
Cannot create database or insert / select from tables already created in a database.
pgBouncer can only create tables and run queries on tables created in default database `postgres`

**What is the expected behavior?**
user pgBouncer to be able to create database, run database migrations and perform queries.

**Other information** (e.g. detailed explanation, related issues,  etc)
I am using pgBouncer as a connection pooler and will be using user pgBouncer in client applications to connect to pgBouncer.

**Please tell us about your environment:**

* Operating System: CentOS 7.7.1908 / CentOS 7.8.2003
* Where is this running ( Local , Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: crunchydata/crunchy-pgbouncer:centos7-12.3-4.3.2
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.14.1 / v1.18

**Comment by junaid-a10** [comment]
I have been able to allow pgBouncer user to create database using `ALTER USER pgbouncer CREATEDB;` but when I created the database and tried creating a table it gives the error `ERROR:  permission denied for schema pgbouncer`. When creating a database a schema pgbouncer is also created and `show search_path` returns `"$user", public`. So any table by default will be created in pgbouncer schema. Tried creating a table with `public.table_name` and it was created successfully. Then I ran `set search_path = public;` to only create tables in public schema.
Is this the way to go about using connecting to postgres from client application using pgbouncer?

**Comment by jkatz** [comment]
The `pgbouncer` user is a special service account that facilitates the user of pgBouncer with PostgreSQL. It serves up to two purposes:

1. To be able to authenticate other PostgreSQL users to the PostgreSQL database via pgBouncer
1. To be able to grab information and statistics by logging into the pgbouncer Deployment directly.

You should *not* be using the pgBouncer account to interact with PostgreSQL directly. It is purposely given limited privileges.

Instead, you should create PostgreSQL users, for example, with the `pgo create user` command. These users can then log into their databases via the pgBouncer Deployment.

For more information, please see the [Common Tasks](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/) section of the documentation (some of this is buried in [Advanced Operations](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#advanced-operations).
