### ISSUE TITLE
Question about pgbackrest schedule

### ISSUE THREAD

**Issue by pmpetit** [CrunchyData/postgres-operator#1759]
Hello, 
The version i am testing is 4.3.0 through gcp marketplace.
Following docs...
I have create hippo cluster in wateringhole ns, operator in pgo ns.

I created a backup schedule
pgo create schedule hippo -n wateringhole --schedule="0 1 * * *" --schedule-type=pgbackrest --pgbackrest-backup-type=full

i do not understand where the configuration schedule is stored, i can not see anything in pgtasks CRD, in backrest-backup-hippo....
i thought i would find a crontab parameter entry with "0 1 * * *" somewhere....

it means that every backup configuration must be done with pgo client ?

thanks

**Comment by jkatz** [comment]
You can get the schedules with either:

-  [`pgo show schedule` -n wateringhole hippo](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_show_schedule/)

or by searching for the ConfigMap where it is stored, in this case `hippo-pgbackrest-full`.

You should be able to create the config maps manually, but this is not recommended. The procedure for creating scheduled backups may change in the future to adopt some of the Kubernetes primitives, so a safe bet is to use the `pgo` client which will be able to transparently account for those changes.
