### ISSUE TITLE
Add capability to take create and manage pg backups on a schedule

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#176]
Currently, we have to manually run "pgo backup" commands to take backups.

Please provide ability for users to specify backup and retention policies for each cluster and kubernetes takes care of implementing the policy.

**Comment by jmccormick2001** [comment]
crunchy-scheduler integration will land in operator 3.4.0, the code is now merged in, it is dependent upon crunchy-scheduler 2.2.0 being pushed out in that upcoming release.
