### ISSUE TITLE
Restore with "pgo create --restore-from"

### ISSUE THREAD

**Issue by aurelien43** [CrunchyData/postgres-operator#1760]
Hello,
I opened an issue about « pgo restore cluster with custom  configmap »  #1732 
Solution (pgo create cluster XXX --restore-from …) is working for my datas but many objects and parameters are not proprely restore. This include :
·       schedules
·       secrets (for postgresql user/password create with pgo)
·       posgresql.conf / pg_hba.conf  / pg_ident.conf parameters
·       maybe other objects ?

**To Reproduce**
As issue #1732  : 
1. Create the configmap
2. Create the cluster
3. After this, create an user with PGO, schedule a backup, edit cluster configmap (example : shared_buffers in posgresql.conf)
4. Restore the cluster with "--restore-from" parameter
At this moment, parameters are not restored, user secrets are badly restored and pgo schedule is empty.

The solution for cloning a tls cluster have the same problem. ( issue #1677 )

For me, « pgo clone » and « pgo restore » commands are the right places to achieve those actions properly. 
what do you think about it ?

**Please tell us about your environment:**
* Operating System: centos7
* Where is this running ( Local, Cloud Provider): VM
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos7-12.3-4.4.0
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16

**Comment by jkatz** [comment]
`pgo create cluster --restore-from` creates a new cluster.

That said, we are aware of the issues you are describing for a restore "in place" and are working on a fix for a future release.

**Comment by jkatz** [comment]
The fixes should be in CrunchyData/crunchy-containers#1253 and #1801 and will be available in the 4.5.0 release.
