### ISSUE TITLE
Feature Request for pgbackrest in PGO to support Azure cloud storage

### ISSUE THREAD

**Issue by sokukata** [CrunchyData/postgres-operator#1761]
Hello,

I install PGO with helm and try to backup with local and s3.
Then I read https://info.crunchydata.com/blog/announcing-pgbackrest-for-azure-fast-reliable-postgres-backups and try with azure

1) I try to use azure as pgbackrest-storage-type
- Get an error because type can be only local or/and s3

2) I exec /bin/bash in pods to edit conf as shown in the article  : 
```bash
kubectl exec --stdin --tty clusters3-backrest-shared-repo-xxxxxxxxx-xxxx -n pgo -- /bin/bash

vi /etc/pgbackrest/pgbackrest.conf

# edit file and save

exit

#create a schedule to test
pgo -n pgo create schedule xxxxxx. --schedule="*/5 * * * *" \
  --schedule-type=pgbackrest  --pgbackrest-backup-type=incr
```
- Pod created by the job finish in error 
```bash
kubectl logs xxxxxxx-incr-sch-backup-xxxx -n pgo

time="2020-08-06T12:35:03Z" level=info msg="pgo-backrest starts"
time="2020-08-06T12:35:03Z" level=info msg="debug flag set to false"
time="2020-08-06T12:35:03Z" level=info msg="backrest backup command requested"
time="2020-08-06T12:35:03Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --type=incr  --db-host=xx.xx.xx.xx --db-path=/pgdata/xxxxxxx]"
time="2020-08-06T12:35:03Z" level=info msg="command is pgbackrest backup --stanza=db --type=incr  --db-host=xx.xx.xx.xx --db-path=/pgdata/xxxxxxxx "
time="2020-08-06T12:35:03Z" level=error msg="command terminated with exit code 32"
time="2020-08-06T12:35:03Z" level=info msg="output=[]"
time="2020-08-06T12:35:03Z" level=info msg="stderr=[WARN: configuration file contains invalid option 'repo1-azure-account'\nWARN: configuration file contains invalid option 'repo1-azure-container'\nWARN: configuration file contains invalid option 'repo1-azure-key'\nERROR: [032]: 'azure' is not allowed for 'repo1-type' option\n]"
time="2020-08-06T12:35:03Z" level=error msg="command terminated with exit code 32"
```

 I just wanted to ask if the PGO's pgbackrest will support azure cloud storage as well in the future ?

From pgbackrest: 
https://github.com/pgbackrest/pgbackrest/issues/939
https://github.com/pgbackrest/pgbackrest/pull/1055

**Comment by jkatz** [comment]
The [PostgreSQL Operator supports pgBackRest 2.27 at the moment](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/) - Azure Storage support was added in 2.28, so it does not support Azure yet.

If you needed immediate support for Azure, you could use [MinIO to broker pushing backups to Azure](https://docs.min.io/docs/minio-gateway-for-azure.html).

At some point, I am sure we will add direct support for Azure Storage, but it is not on the immediate roadmap. Some of the upcoming changes in 4.5 may allow for a manual configuration of interfacing with Azure Storage directly, though we are not making said changes with Azure immediately in mind, but rather to make it easier to configure pgBackRest overall.

**Comment by sokukata** [comment]
Thanks,
I'm gonna watch Mino gatway for now.

**Comment by to266** [comment]
As the [4.6.0](https://access.crunchydata.com/documentation/postgres-operator/4.6.0/releases/4.6.0/) was released, it seems that [pgBackRest 2.31](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/) is supported and therefore azure cloud storage for backups should work, right? (if so -> yay! :raised_hands: )

If so, even though it's not fully documented, do I understand it correctly that I can utilize the feature titled "Customizing pgBackRest via ConfigMap" from the [4.5.0 release](https://access.crunchydata.com/documentation/postgres-operator/4.6.0/releases/4.5.0/) and put the necessary configuration mentioned in [this original blogpost](https://info.crunchydata.com/blog/announcing-pgbackrest-for-azure-fast-reliable-postgres-backups), therefore no longer needing to manually `exec` into the pod and edit it there? (I'm guessing that `pgo` will figure out the first part automatically, and `archive_command = 'pgbackrest --stanza=demo archive-push %p'` is not needed)

**Comment by bryanasdev000** [comment]
Up!

Seems with the latest release (4.7.0) we have pgBackRest at 2.33, which in theory should support Azure Blob according to @jkatz linked issue, but I just compiled pgo it and did not found listed in any help command (but we already have GCS yay!).

@jkatz, if that's not the case, how I can help to implement this?

**Comment by bryanasdev000** [comment]
Some alternatives:

- Use Minio or Minio Gateway
- Azure Blobs CSI Driver
> I had some problems (capacity planning) with this one in my setup, but it can be a viable alternative for others.
- Disk (PV/PVC) + Velero and `--keep-data` or `--keep-backup` when deleting clusters.

**Comment by jkatz** [comment]
This is added in PGO 5.0:

[https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/#using-azure-blob-storage](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/#using-azure-blob-storage)
