### ISSUE TITLE
 Can I use the command "helm uninstall pgo-operator -n pgo" to remove only postgres-operator, but keep the running database?

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [CrunchyData/postgres-operator#1764]
In variables, I use parameters:
delete_operator_namespace: "false"
delete_watched_namespaces: "false"
But this drops the database anyway.

**Comment by IlyaNakhaichuk** [comment]
In variables, I use parameters:
delete_operator_namespace: "false"
delete_watched_namespaces: "false"
But this drops the database anyway.

**Comment by jkatz** [comment]
Set:

`preserve_pg_clusters: "true"`

This looks like it's in the template configuration file but not in the documentation. CC @jmckulk on getting this documented.

**Comment by IlyaNakhaichuk** [comment]
I tried to set this parameter, but the result is the same. When the command "helm uninstall.. " was executed, it still deleted the database.

**Comment by IlyaNakhaichuk** [comment]
Is it possible to solve this problem in a different way?

**Comment by IlyaNakhaichuk** [comment]
@jkatz Could you help me in my issue?

**Comment by jkatz** [comment]
4.5 has some fixes to ensure that it's easier to maintain uniformity of parameters across the installers (i.e. a single source of truth).

What is the use case for doing this?
