### ISSUE TITLE
Custom Config & configMaps

### ISSUE THREAD

**Issue by pmpetit** [CrunchyData/postgres-operator#1765]
Hello,
i am testing 
https://access.crunchydata.com/documentation/postgres-operator/4.4.0/advanced/custom-configuration/

it is said that i can use /github/postgres-operator/examples/custom-config/create.sh to create configMap and use my own postgresql config.
i assume $PGO_CMD=pgo
and 

$PGO_CMD create configmap pgo-custom-pg-config --from-file=$DIR -n ${PGO_NAMESPACE}

but 
pgo does not let you create configmaps....
 i can onyl use
    * cluster
    * pgadmin
    * pgbouncer
    * pgouser
    * pgorole
    * policy
    * namespace
    * user

am i wrong ?
I try to see an example of configmap for a personal config
Thanks

**Comment by jkatz** [comment]
I believe some of the documentation needs to be modified. The ability to customize a PostgreSQL cluster can occur through the `<clusterName>-pgha-config` ConfigMap that is created when the PostgreSQL cluster is created. This is specified in the section below:

[Modifying PostgreSQL Cluster Configuration](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/#modifying-postgresql-cluster-configuration).

If you edit that ConfigMap (e.g. `kubectl edit cm <clusterName>-pgha-config`) you can modify the PostgreSQL configuration.

**Comment by pmpetit** [comment]
ok, but i think that when it is created using 
https://access.crunchydata.com/documentation/postgres-operator/4.4.0/custom-resources/

configMap is not created

**Comment by andrewlecuyer** [comment]
@pmpetit just to clarify, `PGO_CMD` in the `create.sh` script should point to either `kubectl` or `oc` (if using OpenShift) command line tools.  E.g. our example `envs.sh` script that defines various env vars used by various Operator scripts sets it to `kubectl`:

https://github.com/CrunchyData/postgres-operator/blob/611496f78f65268e6c0b22ecc0ea36ac4ba19d80/examples/envs.sh#L15

**Comment by pmpetit** [comment]
arf sorry about that....
i should have read more carefully....
