### ISSUE TITLE
Add capability to take incremental backups

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#177]
"pgo backup" command takes full physical backups and saves them to a backup pvc. 

This approach is taking up too much storage for backups. 

Please implement incremental physical backup feature to reduce the storage requirements for backups.

**Comment by jmccormick2001** [comment]
we will support this via the new backrest integration I think, for example you can perform an incremental backup using the following command as of current develop branch:

pgo backup mycluster --backup-type=pgbackrest --pgbackrest-opts="--type=incr"
