### ISSUE TITLE
node selector

### ISSUE THREAD

**Issue by sergioteixeiraptc** [CrunchyData/postgres-operator#1771]
is there any option for node selection? need to force pods into a specific node and cant seem to work with node labels.

thanks

**Comment by jkatz** [comment]
[Node affinity](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/#node-affinity) is discussed here in the documentation.

**Comment by sergioteixeiraptc** [comment]
no way to force it to a specific node? that method only uses prefered

**Comment by jkatz** [comment]
You can set it to be "required" by editing the `affinity.json` file in the `pgo-config` ConfigMap:

1. Assuming that the PostgreSQL Operator is deployed to the `pgo` namespace: `kubectl -n pgo edit cm pgo-config`
2. Find the entry `affinity.json` (which should be the first one)
3. Change `preferredDuringSchedulingIgnoredDuringExecution` to `requiredDuringSchedulingIgnoredDuringExecution`
4. Save.
5. Restart the PostgreSQL Operator Pod.
6. Deploy the PostgreSQL cluster with the desired Node labels.

That said, "required" is a double-edged sword. With "preferred", Kubernetes will make a best effort to schedule the Pod to the Nodes that have matching node labels, but if it cannot do that, will schedule to another node. With required, if Kubernetes cannot schedule to a Node with matching node labels, it will not schedule the Pod at all. As such, this could lead to unexpected downtime.

**Comment by sergioteixeiraptc** [comment]
thanks a lot!

**Comment by sergioteixeiraptc** [comment]
though if i do that @jkatz i get the following error

`time="2020-08-11T08:25:05Z" level=error msg="json: cannot unmarshal array into Go struct field NodeAffinity.spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution of type v1.NodeSelector" func="internal/operator/cluster.AddClusterBase()" file="internal/operator/cluster/cluster.go:111" version=4.4.0`

**Comment by sergioteixeiraptc** [comment]
my affinity json cm
```
  affinity.json: |2
                "nodeAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [{
                    "weight": 10,
                    "preference": {
                    "matchExpressions": [{
                        "key": "{{.NodeLabelKey}}",
                        "operator": "{{.OperatorValue}}",
                        "values": [
                            "{{.NodeLabelValue}}"
                        ]
                    }]
                    }
                }]
                }

```

**Comment by jkatz** [comment]
I probably should have referenced the spec and [example from the Kube docs](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/pod-with-node-affinity.yaml)

So this becomes:

```
  affinity.json: |2
                "nodeAffinity": {
                  "requiredDuringSchedulingIgnoredDuringExecution": {
                    "nodeSelectorTerms": [{
                      "matchExpressions": [{
                        "key": "{{.NodeLabelKey}}",
                        "operator": "{{.OperatorValue}}",
                        "values": [
                            "{{.NodeLabelValue}}"
                        ]
                      }]
                    }]
                  }
                }
```
