### ISSUE TITLE
External prometheus rules docs

### ISSUE THREAD

**Issue by sergioteixeiraptc** [CrunchyData/postgres-operator#1773]
are there any docs related to connecting to external prometheus?

**Comment by jkatz** [comment]
Is the Prometheus instance within the Kubernetes cluster, or is it in an externally networked environment?

Additionally, we're doing some significant work on the monitoring stack for the upcoming 4.5 release (e.g. #1757) which will make it easier to work with other Prometheus installations.

**Comment by sergioteixeiraptc** [comment]
prometheus is running inside the k8s cluster

**Comment by jkatz** [comment]
This is the configuration file that will be used as part of the 4.5 release. It comes from the upstream [pgMonitor](https://github.com/CrunchyData/pgmonitor) project:

[https://github.com/CrunchyData/pgmonitor/blob/master/prometheus/crunchy-prometheus.yml.containers](https://github.com/CrunchyData/pgmonitor/blob/master/prometheus/crunchy-prometheus.yml.containers)

**Comment by sergioteixeiraptc** [comment]
ok thanks!
