### ISSUE TITLE
TLS Replication: Using a Certificate with different CN than primaryuser

### ISSUE THREAD

**Issue by v3nturetheworld** [CrunchyData/postgres-operator#1774]
** Which example are you working with? **
The common pgo tasks "TLS Authentication for PostgreSQL Replication" example

I'm using the OpenShift  [Service Serving Certificate Secrets](https://docs.openshift.com/container-platform/3.11/dev_guide/secrets.html#service-serving-certificate-secrets)  method to generate the TLS key-pair for the TLS enabled cluster and replication. The common name in tls.crt ends up being `<secret-name>.<namespace>.svc` and unfortunately there's no way to change this. From the documentation it seems like I can simply create a pg_ident mapping in a custom config when creating the cluster to map the primary user to this CN, however I must be doing something wrong since I'm getting the error below. What is the correct way to map a CN that isn't `primaryuser` for the replication to work? The postgresql settings in my custom config look like this:
```
postgresql:
      callbacks:
        on_role_change: /opt/cpm/bin/callbacks/pgha-on-role-change.sh
      create_replica_methods:
      - pgbackrest
      - basebackup
      pg_ident:
      - primaryuser_cert primaryuser.crunchy-test.svc primaryuser 
      pg_hba:
      - local all postgres peer
      - local all crunchyadm peer
      - hostssl replication primaryuser 0.0.0.0/0 cert map=primaryuser_cert
      - hostssl all primaryuser 0.0.0.0/0 reject
      - hostssl all all 0.0.0.0/0 md5
``` 

And the CN on the cert is `primaryuser.crunchy-test.svc`

**What is the current behavior?**
Replica fails to connect to primary with primaryuser account with the error:
```
2020-08-11 22:54:44,544 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 685, in get_local_timeline_lsn_from_replication_connection
    with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 679, in get_replication_connection_cursor
    with get_connection_cursor(**conn_kwargs) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
    with psycopg2.connect(**kwargs) as conn:
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SSL error: certificate verify failed
```

**Please tell us about your environment:**

I'm using the latest images with tag centos7-12.3-4.4.0

**Comment by v3nturetheworld** [comment]
Never mind, after playing around with it a bit, I found the configuration I had above does work, however something about using the generated Service Signing Certs causes the verification to fail... manually generating the tls keypair and signing with the same root  ca the Service Serving Cert/root openshift cert worked so there must be something wrong with the openshift generated tls keypair.

**Comment by jkatz** [comment]
Glad to hear the configuration works!
