### ISSUE TITLE
after deploy pgadmin we get "malformed pbkdf2_sha512 hash (checksum must be exactly 64 bytes)" as json result page from login

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1776]
**Describe the bug**
After deploying pgadmin to cluster we get to pgadmin4  login page after we enter a supposedly correct or purposedly incorrect password,  we get "malformed pbkdf2_sha512 hash (checksum must be exactly 64 bytes)" as json result page..

**To Reproduce**
pgo -n pgo create pgadmin test10

and try to access pgadmin

**Expected behavior**
get into pgadmin of course

**Screenshots**

**Please tell us about your environment:**

* Operating System: ubuntu 20.04
* Where is this running  Virtual
* Storage being used is a longhorn volume
* Container Image Tag: for pgadmin4 inside pgo is registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:centos7-12.3-4.4.0
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version:1.18

**Additional context**

**Comment by jkatz** [comment]
I was unable to reproduce this.

I would recommend rotating the password for the user, e.g:

```
pgo update user test10 --username=<USERNAME> --password=<PASSWORD>
```

or

```
pgo update user test10 --username=<USERNAME> --rotate-password
```

**Comment by IJOL** [comment]
I didnt understand your response give the issue, i was talikng about the pgadminsetup to first enter pgadmin4, please read the issue

**Comment by IJOL** [comment]
Oops, my fault of course sorry for the noise
