### ISSUE TITLE
How to create new users in cluster with access to pgadmin instance

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1784]
AFAIK when we deploy a new pgadmin instance for a cluster the only user thar has access to pgadmin, is the testuser every cluster has, we need to know how to give access to the pgadmin instance to newly created user in the cluster..

Saludos, Ignacio J. Ortega

**Comment by jkatz** [comment]
This is described in detail in the [documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/pgadmin4/):

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/pgadmin4/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/pgadmin4/)

There is also a blog post that rehashes the concepts described in the documentation that may prove helpful:

[https://info.crunchydata.com/blog/deploy-pgadmin4-with-postgresql-on-kubernetes](https://info.crunchydata.com/blog/deploy-pgadmin4-with-postgresql-on-kubernetes)
