### ISSUE TITLE
How to change postgres version for a cluster

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1785]
We nee to change the postgres version used to create a cluster is that possible?

Saludos, Ignacio J. Ortega

**Comment by jkatz** [comment]
The list of compatibility between versions of PostgreSQL + the PostgreSQL Operator is documented here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/)

The process for upgrading is detailed here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/automatedupgrade/](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/automatedupgrade/)
