### ISSUE TITLE
Error when trying pgo backup cluster --backup-opts='--type full'

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1786]
The Job is  deployed but the pods the backup job starts failed with the log below...

time="2020-08-15T14:29:55Z" level=info msg="pgo-backrest starts"
time="2020-08-15T14:29:55Z" level=info msg="debug flag set to false"
time="2020-08-15T14:29:55Z" level=info msg="backrest backup command requested"
time="2020-08-15T14:29:55Z" level=info msg="command to execute is [pgbackrest backup --type full --db-host=10.42.1.34 --db-path=/pgdata/test10-taoq]"
time="2020-08-15T14:29:55Z" level=info msg="command is pgbackrest backup --type full --db-host=10.42.1.34 --db-path=/pgdata/test10-taoq "
time="2020-08-15T14:30:24Z" level=error msg="command terminated with exit code 64"
time="2020-08-15T14:30:24Z" level=info msg="output=[]"
time="2020-08-15T14:30:24Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\nERROR: [064]: raised from local-1 protocol: unable to write '/backrestrepo/test10-backrest-shared-repo/backup/db/20200815-142955F/pg_data/base/117146/118197.gz.pgbackrest.tmp'\n]"
time="2020-08-15T14:30:24Z" level=error msg="command terminated with exit code 64"

**Comment by IJOL** [comment]
Was lack of space at backup storage repo,stating to understand the thing, it works great despite my issues, was a fundamental lack of knowledge onnour part, we are a seasoned patroni users, but rookies a pgbackrest, sorry for the noises.. great software!!

**Comment by jkatz** [comment]
@IJOL I recommend using [`pgo df`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_df/) to get an insight into how much disk resources your cluster is using.

I'm also please to report that the 4.5 release will take monitoring to the next level, which will be out in a few weeks.
