### ISSUE TITLE
How to create user with CREATEDB  rights added

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1787]
Can i change the defaults permission a role created with pgo -n pgo create user test10 --username=test10 --password=XXXXX has?

**Comment by jkatz** [comment]
This is not really a function of the PostgreSQL Operator, but rather based on the ACL and other policies that you may wish to set. That said, there are a few ways you can do this:

1. Authenticate into your PostgreSQL database as the superuser (`postgres`) account and assign the create role to the new account:

```sql
ALTER ROLE test10 CREATEDB;
```

2. Create a [policy](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#policy-management) (more info [https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#policy-management](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#policy-management)) that creates the user and assign the policy to run after the database is created, e.g.:

```
cat <<EOF > policy.sql
CREATE ROLE test10 LOGIN CREATEDB;
EOF

pgo create policy createdb  -n pgo --in-file=policy.sql
pgo create cluster -n pgo hippo --policies=createdb
```
