### ISSUE TITLE
Import(restore) data from outside the Cluster

### ISSUE THREAD

**Issue by devopsevd** [CrunchyData/postgres-operator#1789]
**What is the motivation or use case for the change? **
I am migrating from Postgres server on AWS. Would like to create a Postgres cluster using the crunchydata operator and import or restore from and existing data dump.
I dont see a way to migrate the existing data from Postgres server on AWS into a Postgres cluster created using the operator.

**Describe the solution you'd like**
I would be able to import or restore a database dump from out side the postgres cluster by passing in the url for the database dump either from GCP shared bucket or AWS s3 bucket.

**Please tell us about your environment:**

* Operating System: Linux based 
* Where is this running ( Local, Cloud Provider) - GCP GKE cluster
* Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC, 
* Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
* PostgreSQL Version:12.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16.11-gke.5

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jkatz** [comment]
I would recommend looking at some of the methodologies presented at the following URLs:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/)
- [https://access.crunchydata.com/documentation/postgres-operator/4.4.0/architecture/disaster-recovery/#restore-to-a-new-cluster](https://access.crunchydata.com/documentation/postgres-operator/4.4.0/architecture/disaster-recovery/#restore-to-a-new-cluster)

The "restore to a new cluster" method could work if you have your data backed up to S3 using pgBackRest, and have the naming conventions of the PostgreSQL Operator match the name of that bucket.

Alternatively, you can try setting up a PostgreSQL instance as a "standby" from the S3 repository you have set up and bootstrap the cluster from there.
