### ISSUE TITLE
Creating a cluster I dont see an option to pass username and password through secrets

### ISSUE THREAD

**Issue by devopsevd** [CrunchyData/postgres-operator#1790]
**What is the motivation or use case for the change? **
Using the pgo create cluster command - i dont see an option to pass username password though a kubernetes secrets.

https://access.crunchydata.com/documentation/postgres-operator/4.4.0/pgo-client/reference/pgo_create_cluster/

**Describe the solution you'd like**
Using the operator I would have an option to pass the username password through kubernetes secrets while creating the cluster 

**Please tell us about your environment:**

* Operating System: Linux based 
* Where is this running ( Local, Cloud Provider) - GCP GKE cluster
* Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC, 
* Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
* PostgreSQL Version:12.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16.11-gke.5

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jkatz** [comment]
You can use the `-secret-from` flag to accomplish this. Note that the Secrets must match the format expected by the PostgreSQL Operator for cluster boostrapping, which you can see when you create a cluster the standard way.

Alternatively, if you wish to provide these values in a pre-existing Secret, you can do so by following the "custom resource" creation method, with instructions provided here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/)
