### ISSUE TITLE
2x the data

### ISSUE THREAD

**Issue by sergioteixeiraptc** [CrunchyData/postgres-operator#1793]
having this issue where my master has 2x the data than its suposed to when i do bulk inserts? its suposed to have 80GB size and it currently has 160GB, does it keep copies of itself on the master?

**Comment by jkatz** [comment]
This is not a PostgreSQL Operator issue but a general PostgreSQL question. That said, I will provide some brief guidance.

There are several things that can get written to disk as data is loaded into PostgreSQL, including:

- [Write ahead logs](https://www.postgresql.org/docs/current/wal-intro.html)
- [PostgreSQL logs themselves](https://www.postgresql.org/docs/current/runtime-config-logging.html)

If you want to limit the amount of WAL generated during a database import, you can set the table to be `UNLOGGED`, though to ensure the data is persisted and ultimately replicated, you will have to set it back to `LOGGED` when the import is done. This will still generate WAL but you delay this activity happening.

(Separately, the PostgreSQL Operator provides the option to write WAL to a different PVC. There are advantages and disadvantages to doing that).

You can tune what, when, how you want things sent to the PostgreSQL logs based on the configuration settings sent above.
