### ISSUE TITLE
Separate parameter for pgadmin PVC size

### ISSUE THREAD

**Issue by psavva** [CrunchyData/postgres-operator#1795]
When creating a pgadmin instance for a cluster, the PVC is taken from the cluster PVC size, which causes a large waste of space if you deploy the pgadmin module.

**Describe the solution you'd like**
Please add a separate parameter in the config to allow a separate fixed side for the pgadmin PVC.
Please also allow for an override on the pgo client.

**Please tell us about your environment:**

* Operating System: Centos 7
* Where is this running: Bare Metal Local
* Storage being used: Rook-Ceph
* Container Image Tag: V4.4.0
* PostgreSQL Version: default (v12)
* Platform: K8s
* Platform Version: 1.18

**Comment by psavva** [comment]
If you like, I can attempt at implementing it tomorrow.
However, I have zero experience on go, nor building crunchy data, pgo, etc...  If you point me to a slack or a getting started as a dev, I can attempt it...

**Comment by jkatz** [comment]
I appreciate the enthusiasm in contributing!

There is a section on [how to contribute](https://access.crunchydata.com/documentation/postgres-operator/latest/contributing/) in the documentation, which discusses setting up a development environment, etc:

[https://access.crunchydata.com/documentation/postgres-operator/latest/contributing/](https://access.crunchydata.com/documentation/postgres-operator/latest/contributing/)

I will note that the environment can be a bit onerous to set up, though once we shift to go modules (#1648) it will be a bit easier.

I will also note that we're about to hit feature freeze for 4.5 so if the patch is not ready soon it may take some time.

I would say that this feature request is moderately complicated: it touches quite a few parts of the code, but there are patterns for how to do this (e.g. WAL PVC etc.)

**Comment by jkatz** [comment]
Alternatively, I would suggest as a shorter term fix, as you're on a newer version of Kubernetes, is to leverage the [PVC resizing features](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-an-in-use-persistentvolumeclaim) and manually resize the PVC.

Also based on your provisioning strategy / storage class, the pgAdmin 4 PVC may not actually utilize as much space as the PostgreSQL cluster, though in theory could use up that much.

**Comment by jkatz** [comment]
This is now committed and will be available in 4.7.0.
