### ISSUE TITLE
Using the postgres operator how I can I increase the connections per user value for pgbouncer ( how to update default_pool_size = 20)

### ISSUE THREAD

**Issue by devopsevd** [CrunchyData/postgres-operator#1796]
** Which example are you working with? **
We have deployed the postgres operator and created a cluster. using the pgo commands

**What is the current behavior?**
 the connections per user value for pgbouncer is limited to  default_pool_size = 20

**What is the expected behavior?**
Using the postgres operator (thought pgo client) I should be able to increase the connections per user value for pgbouncer ( how to update default_pool_size = 20)

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by jkatz** [comment]
Presently this information is in the `<clusterName>-pgbouncer-secret` in the `pgbouncer.ini` entry. You would need to modify that entry with your desired value. You would need to at least reload pgbouncer after that (I don't know if the config option requires a restart).

Alternatively, though this will not persist, you can log into pgbouncer directly and set the settings with the [`SET`](https://www.pgbouncer.org/usage.html#set-key--arg) command.

A future Operator release will move this file into a ConfigMap which will make it easier to edit.
