### ISSUE TITLE
pgo scale stuck on Pending init pgreplica

### ISSUE THREAD

**Issue by kubealex** [CrunchyData/postgres-operator#1798]
** Which example are you working with? **

Scaling a simple cluster on a fresh installation

**What is the current behavior?**

    message: Pgreplica processing pending the creation of the initial backup
    state: pgreplica Pending init

**What is the expected behavior?**

The cluster scales

**Please tell us about your environment:**

* Operating System:  centos
* Where is this running ( Local , Cloud Provider): local
* Storage being used (NFS, Hostpath, Gluster, etc): Rook-ceph
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.18

Logs in any pod don't show anything about the scaling.

**Comment by jkatz** [comment]
The error message is stated in what you said: `Pgreplica processing pending the creation of the initial backup`

For the cluster to scale, you need to ensure the initial backup is taken, as that is what is used to expedite the creation of the new cluster. The process is as such:

- PostgreSQL primary is created
- pgBackRest repo is initialized

The first two must complete for the next steps to proceed:

- An initial pgBackRest stanza is created
- An initial backup is taken

Once those completed, then any replicas requested upon creation can then scale up.

Please check your local environment to ensure that the stanza-create job ran successfully, as well as the initial backup.
