### ISSUE TITLE
PGO scale --replica very slow

### ISSUE THREAD

**Issue by aakashmuthuramalingam** [CrunchyData/postgres-operator#1799]
Team,

I deployed this operator with 3 nodes and once it is created, it took a full backup automatically(8MB). After that, I loaded around 1TB of data in postgres and tried to scale up. It was very slow. It took around 14 hours to make it sync a single replica.

**pgo scale pgtest --replica-count=1**

As per doc, **During the provisioning of the replica, a pgBackRest restore takes place in order to bring it up to the point of the last backup. If
data already exists as part of this replica, then a "delta restore" is performed. (NOTE: If you have not taken a backup in awhile
and your database is large, consider taking a backup before performing scaling up.)**

So, I manually triggered a backup, by default it started to take incremental backup of around 423GB. (Default command(single process) and it took more than 20 hours to complete)

Again tried adding one more pod, there is no improvement.

So, tried with initiating full backup using --process-max=16. It took only 2 hours to complete, however addition of new replica still taking long time. (Looks like it is not using backup and still applying wal from backrest I guess)

**pgo backup pgtest --backup-opts="--type=full --process-max=32"**

1. Is there any way to speed up the scale a replica ? 14 hours is not acceptable for us.
2. Why it is not using backups or how to confirm it is using backup or not for scale up ?
3. Am I doing anything wrong here ?

We are doing this tests for our production migration. Please let me if you need any more details. 

* Operating System: Centos
* Where is this running ( Local , Cloud Provider) Cloud Provider
* Storage being used (NFS, Hostpath, Gluster, etc): Persistent Volume Claim (PVC)
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes

Thanks for this great work

Aakash

**Comment by jkatz** [comment]
I think this is worth looking into, but given you loaded the data and then scaled up, why not scale up prior to loading the data?

**Comment by jkatz** [comment]
Tying this to #1401 which makes a similar request.
