### ISSUE TITLE
Restoring from a cluster with different major version fails

### ISSUE THREAD

**Issue by kaoet** [CrunchyData/postgres-operator#1800]
**Describe the bug**
Use `pgo create --restore-from` to clone a cluster with different major version fails.

**To Reproduce**
1. `pgo create cluster old --ccp-image-tag=centos7-11.8-4.4.0`
2. Insert some data into `old` cluster.
3. `pgo create cluster new --restore-from=old`

**Expected behavior**
The `new` cluster is setup with data from the `old` cluster.

**Actual behavior**
The `new-bootstrap` job keeps crashing, with `Exit status 1`. I didn't see any log produced by it.

**Please tell us about your environment:**

* Operating System: Linux
* Where is this running ( Local, Cloud Provider): GKE
* Storage being used (NFS, Hostpath, Gluster, etc): Disk in GCP
* Container Image Tag: 4.4.0
* PostgreSQL Version: 11 and 12
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16.13

**Additional context**
Despites `pgo create --restore-from` fails, the `pgo clone` works correctly. But the output saids it's deprecated and instructs me to use `pgo create --restore-from`. Due to the reason I mention above, it's actually not replaceable.

**Comment by jkatz** [comment]
The `--restore-from` flag is *not* for performing [PostgreSQL major upgrades](https://www.postgresql.org/docs/current/upgrading.html), and I'm a bit surprised that a major upgrade would work with `pgo clone` -- that seems more accidental than not. A _minor_ upgrade would work, but that should work with both methods.

To perform a major upgrade, you would need to use the [`crunchy-upgrade`](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/) container. For your scenario, the process would look like:

1. `pgo create --restore-from` using the same version (11.8 => 11.8)
1. Run `crunchy-upgrade` to perform the major upgrade on the new cluster

Example use cases for the intended behavior of `pgo create --restore-from` can be found in the [documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/).
