### ISSUE TITLE
How to change configuration we set during installation?

### ISSUE THREAD

**Issue by TheMisir** [CrunchyData/postgres-operator#1806]
First of all thanks for such an amazing tool =)

I might be asking a stupid question but anyways, how can I change configuration we set during installation process. For example default storage types, or pgo user & password or `backrest_aws_s3_verify_tls` value, etc...

I'm currently deleting entire pgo cluster and operator and recreating when I want to change a config.

1. Delete postgres clusters using pgo cli
2. `kubectl delete all --all -n pgo`
3. `kubectl delete namespace pgo`
4. Update postgres-operator.yaml
5. `kubectl create namespace pgo`
6. `kubectl apply -f postgres-operator.yaml`

Which takes some time during setup & configuration process. (For example now I have to disable aws s3 TSL verification and I'm doing all the steps above).

I have not found details about that on documentation.

**Comment by jkatz** [comment]
This configuration exists in the `pgo.yaml` entry in the `pgo-config` ConfigMap that is deployed in the same namespace as the PostgreSQL Operator. You can do the following:

1. Open up the editor for the `pgo-config` ConfigMap `kubectl -n pgo edit cm pgo-config`
1. Find the `pgo.yaml` entry
1. Edit the values that you would like to change.
1. Save
1. Restart the PostgreSQL Operator. You can do this by scaling down/up the Deployment, or deleting the active Operator Pod.

**Comment by TheMisir** [comment]
Thank you so much =)
