### ISSUE TITLE
hostpathstorage 

### ISSUE THREAD

**Issue by yangvipguang** [CrunchyData/postgres-operator#1807]
**Describe the bug**
I use the default operator yaml file. And the storage type is hostpathstorage
![image](https://user-images.githubusercontent.com/11416887/90994269-d6f96d00-e5ea-11ea-824b-0424ef30cb37.png)
But After creating pg cluster with pgo client . I ocurrs some issues with storage .
![image](https://user-images.githubusercontent.com/11416887/90994298-e7a9e300-e5ea-11ea-82b8-f2674fd8f5d8.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

Operating System: K8S
Where is this running ( Local, Cloud Provider) Alicloud
Storage being used (NFS, Hostpath, Gluster, etc): hostpath
Container Image Tag: 4.4.1
PostgreSQL Version: 12.4
Platform (Docker, Kubernetes, OpenShift): K8S
Platform Version: 1.16

**Additional context**

**Comment by jkatz** [comment]
This doesn't show all the values for the `storage1` class so I can't give a definitive answer. From the information provided, it could be one of a few things:

1. No persistent volumes for hostpath storage have been created.
1. There may be a provisioning mechanism for hostpath in your environment, but you would need to specify the appropriate storage class.

**Comment by yangvipguang** [comment]
@jkatz  Ok. Thanks。
I still have a few questions to ask：
1、I have configured S3 for backup, but what  do  the following backup and backrest storage are used to storage .
![image](https://user-images.githubusercontent.com/11416887/91111660-af220c00-e6b3-11ea-976d-a82c1a867121.png)
![image](https://user-images.githubusercontent.com/11416887/91111685-b9dca100-e6b3-11ea-986d-087c330233a9.png)
2、backup and backrest are used for backup, what is the difference between them。
3、I have a suggestion I hope you can combine your experience to come up with a best practice。
4、If I want to add other extensions, how can I add them more conveniently。

**Comment by jkatz** [comment]
`backup_storage` is used to specify the storage of the logical (`pg_dump`) backups. It was also used for `pg_basebackup` backups, but those have been removed in favor of pgBackRest.
- `backrest_storage` is used to specify the storage for the pgBackRest repository. This setting is not applicable to using S3 or an S3 interface.

**Comment by yangvipguang** [comment]
@jkatz  ok thanks  one more question. if i want to change pgo config in the pgo client container。 I just see how to show configs。

**Comment by jkatz** [comment]
The client container accepts environmental variables as the ones described here:

[https://access.crunchydata.com/documentation/postgres-operator/4.4.1/pgo-client/#command-overview](https://access.crunchydata.com/documentation/postgres-operator/4.4.1/pgo-client/#command-overview)

An explanation for how it works is here:

[https://access.crunchydata.com/documentation/postgres-operator/4.4.1/installation/pgo-client/#pgo-client-container](https://access.crunchydata.com/documentation/postgres-operator/4.4.1/installation/pgo-client/#pgo-client-container)

**Comment by weiya1990** [comment]
@jkatz  I have changed the operator yaml  by changing **pg-primary-data** of storage5_name  to **pg-primary-data-1**。
![image](https://user-images.githubusercontent.com/38902618/92675641-79874f00-f352-11ea-8f14-eadeba1bd306.png)
then, 
1、I restart the operator deployment 
2、 delete the deploy job and reapply the operator yaml , and the job rerun again .
all of above step is done.But all failed with config of fetching  new storage config of storage5_name: "pg-primary-data-1"
![image](https://user-images.githubusercontent.com/38902618/92675659-873cd480-f352-11ea-8be1-45ff13d883b3.png)
