### ISSUE TITLE
Failed to pull image crunchy-collect

### ISSUE THREAD

**Issue by TheMisir** [CrunchyData/postgres-operator#1809]
**Describe the bug**
When I specify `--ccp-image-tag` for `postgres-gis-ha`, `crunchy-collect` also uses same tag which is not available (because -gis tag contains postgis version while crunchy-collect doesn't).

**To Reproduce**

1. Install pgo to k8s cluster
2. Create pgo cluster using the command below:
```sh
pgo create cluster mypg \
  --pgbackrest-storage-type local,s3 \
  --ccp-image=crunchy-postgres-gis-ha \
  --ccp-image-tag=centos7-12.4-3.0-4.4.1
```

3. Kubernetes fails to pull crunchy-collect image (with wrong tag)

**Here's error message**

```
Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-12.3-3.0-4.4.0": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-12.4-3.0-4.4.1 not found
```

**Expected behavior**
Specifying different tags for postgres container and collect container. Eg:

```sh
crunchy-postgres-gis-ha:centos7-12.4-3.0-4.4.1
crunchy-collect:centos7-12.4-4.4.1
```

**Please tell us about your environment:**

* Operating System:
  - My workstation: Window 10 (1909)
  - Worker node: Debian 10
  - Master node: idk
* Where is this running: Linode Managed Kubernetes
* Storage being used: Linode BlockStorage
* Container Image Tag: centos7-12.4-3.0-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: idk

**Additional context**
Is there a way to specify different tags for each container (postgres and collect)?

**Comment by TheMisir** [comment]
# Note 1.

When I don't use `--ccp-image-tag` the database container gives same error (fails to pull postgres-gis-ha image).

```sh
pgo create cluster mypg \
  --pgbackrest-storage-type local,s3 \
  --ccp-image=crunchy-postgres-gis-ha
```

**Comment by jkatz** [comment]
See #1749

**Comment by TheMisir** [comment]
Thanks for reply @jkatz 

I fixed by manually changing kubernetes deployment image tag for database pod. Would this may make any issue in future? I did not found where does pgo stores deployment info so I could change there too.
