### ISSUE TITLE
Add capability to run custom jobs against pg clusters

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#181]
This request is to provide DBAs/SAs the ability to write custom shell/SQL scripts to run against postgres instances in kubernetes environment.

**Comment by jmccormick2001** [comment]
currently SQL is stored in pgpolicy CRDs,     one aspect of this feature is that you would have something akin to 'pgo create schedule --policy=somepolicy ....', that would cause the SQL from the policy to be stored in the schedule config map, the scheduler would submit Jobs to execute this SQL.

**Comment by jmccormick2001** [comment]
will be mostly implemented in 3.5 with the new scheduler, sql (policies) can be scheduled.  Not sure we want to schedule bash scripts at this point but am thinking about it for 3.6.
