### ISSUE TITLE
Using wal2json in pgo-cluster

### ISSUE THREAD

**Issue by kglebova** [CrunchyData/postgres-operator#1816]
Hi,
I'm using PGO v4.4.0
I want to use plugin wal2json for logical decoding on my pgo-cluster.
But I am getting error:
bash-4.2$ pg_recvlogical -d postgres --slot test_slot --create-slot -P wal2json
pg_recvlogical: error: could not send replication command "CREATE_REPLICATION_SLOT "test_slot" LOGICAL "wal2json" NOEXPORT_SNAPSHOT": ERROR:  could not access file "wal2json": No such file or directory

How can I install the wal2json plugin on my pgo-cluster?

**Comment by jkatz** [comment]
wal2json is currently not included in the container image.

**Comment by gricuk** [comment]
> wal2json is currently not included in the container image.

Are you planning to include wal2json in future releases?

**Comment by jkatz** [comment]
I've added it to the roadmap to be considered. It's not complicated to add, it would just involve the usual testing, documentation etc.

I would put it at a good probability that it is added in the future.

**Comment by jkatz** [comment]
This will be included in the 4.5.0 release.
