### ISSUE TITLE
pgbackrest for backup with s3

### ISSUE THREAD

**Issue by yangvipguang** [CrunchyData/postgres-operator#1820]
**Describe the bug**
I have  tried several times for backup with pgbackrest. local is good but  s3 occures some following issues。
![image](https://user-images.githubusercontent.com/11416887/91379971-69ea0f80-e856-11ea-9224-c1d1a33146a5.png)

Has anyone encountered this problem?

**Please tell us about your environment:**

* Operating System: Centos 7
* Where is this running ( Local, Cloud Provider)：AliCloud  with  OSS
* Storage being used (NFS, Hostpath, Gluster, etc): NAS
* Container Image Tag: 4.4.1
* PostgreSQL Version:  12.4
* Platform (Docker, Kubernetes, OpenShift): K8S
* Platform Version: 1.16

**Additional context**

**Comment by jkatz** [comment]
Ensure that `stanza-create` successfully runs. Also ensure that you are creating the stanza in a clean directory.

**Comment by strigona-worksight** [comment]
If the `stanza-create` does not complete successfully, is there any way to get back into a good state without recreating the cluster? I created a cluster with s3 backup, but the s3 bucket DNS hadn't fully propagated so the job failed.

**Comment by jkatz** [comment]
Re-create the `stanza-create` job. After that, you can kick off an initial backup with `pgo bacup`
