### ISSUE TITLE
How to get status of started backup after running pgo backup

### ISSUE THREAD

**Issue by rubin55** [CrunchyData/postgres-operator#1825]
**What is the motivation or use case for the feature?**
Have a way to wait for an initiated backup and/or to know if it was succesful or not.

**Describe the solution you'd like**
We currently initiate backups using `pgo backup` which works nicely so far. However, we want to know if a backup is actually done because we do pipeline integrated backups where the pipeline should only continue after a succesful backup.

However, currently pgo backup only returns something like this:

    created Pgtask backrest-backup-common-db

I can afterwards look at the backup list using `pgo show backup` and reason that any backup of the same type, after the start date of the backup command is the backup I would expect to appear, but of course this is not guaranteed precise.

Would it maybe be possible to add a uuid to the backup that pgo would return when initiating a backup and that would show up in the show backup list? A correlation id so to speak?

**Describe any alternatives you've considered**
As described above, use start date of backup as a boundary, looking at the show backup list, any backup of the same type that **shows up** would be assumed to be the backup result. Obviously not very atomic.

**Please tell us about your environment:**

* Operating System: Linux
* Where is this running ( Local , Cloud Provider): Private Kubernetes cluster, v1.17.6
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: v4.4.0
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.17.6

**Additional context**

Current pgo command output:
```
$ pgo backup common-db --backup-opts="--type=full --repo1-retention-full=1" -n some-namespace
created Pgtask backrest-backup-common-db
```

Suggested pgo command output:
```
$ pgo backup common-db --backup-opts="--type=full --repo1-retention-full=1" -n some-namespace
created Pgtask backrest-backup-common-db with correlation id 53c212d4-a5be-488a-9677-f8c6ed47d510
```

**Comment by jkatz** [comment]
The `pgo show backup` command interfaces directly with pgBackRest to get that list -- in fact, that list is just the direct JSON output of `pgbackrest info -o json` mapped over.

Presently pgBackRest does not support a "progress" feature, so the best bet would be to check the Kubernetes Jobs list and determine if the Job is still running.

**Comment by jose-joye** [comment]
my 2 cents:
From our side, we go within the pg-backrest pod and do the following:

$ cd tmp
$ tail db-backup.log -f

José

**Comment by jkatz** [comment]
@jose-joye Cool!

I think if we found some happy medium, it would be to detect that the backup job has successfully completed and fire an event as a result of it. My only hesitation is over what we do with the event system in the future. We will supporting eventing in some way, I am just not sure if it will be the current way.

**Comment by rubin55** [comment]
@jkatz What I would love is an option like `--await` or somesuch that would essentially foreground the pgo backup command, optionally with the log output from pgo's backrest container that does the backup, which would return 0 if succesful, 1+ if error. Would such a feature not be awesome and/or possible?
