### ISSUE TITLE
How to disable the default backup job

### ISSUE THREAD

**Issue by timbrd** [CrunchyData/postgres-operator#1828]
I am currently using pgo version 4.4.1 on OpenShift 4.5.

At least once a day the operator starts a job to backup my postgres cluster. Since it is a development cluster only, I would like to disable the backup. Unfortunately I couldn't find documentation for it though.

Can anyone please give me a tip on how to disable the backup?

**Comment by jkatz** [comment]
Did you use [`pgo create schedule`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_schedule/) to create a scheduled backup? If you did, you'll have to use [`pgo delete schedule`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_delete_schedule/) to delete it.

There is an initial backup taken after a cluster is created, but it should not be occur after that.

**Comment by timbrd** [comment]
> Did you use [`pgo create schedule`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_schedule/) to create a scheduled backup? If you did, you'll have to use [`pgo delete schedule`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_delete_schedule/) to delete it.

No, I didn't create any schedules. That's why I was suprised to find a backup job running.

> There is an initial backup taken after a cluster is created, but it should not be occur after that.

Okay, that explains the backup job I've found. Does the operator start new jobs after canceling the initial run?

**Comment by jkatz** [comment]
> Okay, that explains the backup job I've found. Does the operator start new jobs after canceling the initial run?

If the initial run fails, the Job will keep retrying until it exceeds or it gives up.

**Comment by timbrd** [comment]
Thanks for clarification!
