### ISSUE TITLE
How can I change backup S3 credentials & details after creating cluster and setting up backup schedules.

### ISSUE THREAD

**Issue by TheMisir** [CrunchyData/postgres-operator#1829]
As I mentioned in title I need to change S3 backup details to another s3 compatible server. I don't mind if I lost S3 backups. Just want to not break something that already works (bkz: don't want to down postgres server since it's used in production). So, which configs / secrets I need to change?

** Example cluster details: **

Namespace: myapp
Cluster: mypg

**Comment by jkatz** [comment]
The name of the secret containing the pgBackRest credentials is called `<clusterName>-backrest-repo-config`. So in your case:

```
kubectl describe secret -n myapp mypg-backrest-repo-config
```

There are a few entries in there. The S3 credentials are in:

- `aws-s3-ca.crt` - the CA certificate for your S3 host. The default is Amazon's certificate.
- `aws-s3-key` - the AWS S3 key
- `aws-s3-key-secret` - they AWS S3 secret

You then have to make changes to the pgclusters.crunchydata.com custom resource for `mypg` which. may involve updating these fields:

- backrestS3Bucket
- backrestS3Endpoint
- backrestS3Region
-  backrestS3URIStyle
- backrestS3VerifyTLS

However, those changes do **not** automatically propagate. You would have to manually apply those changes to the appropriate Deployments.

A different approach that would involve downtime, but potentially easier, is to:

`pgo delete cluster -n myapp mypg  --keep-data --keep-backups` and then `pgo create cluster -n myapp mypg` with all of the settings for your new S3 repository.

Regardless, you should test each approach in your non-production environment to find what you are comfortable with.
