### ISSUE TITLE
pgbouncer connection refused

### ISSUE THREAD

**Issue by pmpetit** [CrunchyData/postgres-operator#1830]
Hello,
i have created a user with
pgo create user -n myns mycluster --username=testpgbouncer --managed --password=mypwd

port-forward to pgbouncer service:
k port-forward -n myns service/mycluster-pgbouncer 60901:60901

when i connect with :

psql -U testpgbouncer -h localhost -p 60901 -d mydb
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

on pgbouncer side:
E0831 11:55:33.169844 1515613 portforward.go:391] an error occurred forwarding 60901 -> 60901: error forwarding port 60901 to pod f9a215e9bcbc0db3f2f39d4b61a59862156ab8985a71fb8e56f8ddc1aa3549ea, uid : exit status 1: 2020/08/31 09:55:38 socat[24551] E connect(5, AF=2 127.0.0.1:60901, 16): Connection refused

pgbouncer was created with;
pgo create pgbouncer -n myns mycluster

**Comment by pmpetit** [comment]
For your information,
if i let the default port to 5432 (instead of 60901) then it is ok

**Comment by jkatz** [comment]
pgBouncer lists on port 5432 by default, so I believe the port forward you are looking for is:

`kubectl port-forward -n myns service/mycluster-pgbouncer 60901:5432`

Also, the connection string states `psql -U testpgbouncer -h localhost -p 60901 -d mydb`

where the database is `mydb`, but it looks like the name of your cluster (and deafult database) is `mycluster`.

**Comment by pmpetit** [comment]
i can not "kubectl port-forward -n myns service/mycluster-pgbouncer 60901:5432" because service /mycluster-pgbouncer expose only 60901:
error: Service mycluster-pgbouncer does not have a service port 5432

**Comment by pmpetit** [comment]
i have change teh default port to something <> 5432 in pgo.conf (60901)

but when i add pgbouncer, then the port is still 5432 in pgbouncer.ini but the pgbouncer service only propose port from pgo.yaml (60901)

**Comment by jkatz** [comment]
Hm, so looking at the code, I noticed a few things:

- The pgBouncer Deployment itself takes the port it should use from the `pgo.yaml` file: 

https://github.com/CrunchyData/postgres-operator/blob/c4fe5493de87861050b53dcf84b186229ef73df6/internal/operator/cluster/pgbouncer.go#L490

As well as this gem:

https://github.com/CrunchyData/postgres-operator/blob/c4fe5493de87861050b53dcf84b186229ef73df6/internal/operator/cluster/pgbouncer.go#L605-L607

(When I last did a major pass through this code, I left that comment :smile:)

- However, the pgbouncer.ini file takes the PostgreSQL port from the CRD:

https://github.com/CrunchyData/postgres-operator/blob/c4fe5493de87861050b53dcf84b186229ef73df6/internal/operator/cluster/pgbouncer.go#L689

That said, if you're saying that the PostgreSQL port is set in the `pgo.yaml` to be 60901, then it _should_ be working. If you modified the port directly in the `postgresql.conf` (or equivalent customization) outside of the CRD / commands, I would see this failing, as there would be no way for the Operator to reconcile the information.

That all said, perhaps we need a well-defined heuristic for how the ports work, as well as the ability to specify a specific listening port for pgBouncer, which would be. a new feature.

**Comment by pmpetit** [comment]
I modified the port in pgo.yaml to 60901, services are well created, but the secret in pgbouncer.ini is still
[pgbouncer]
listen_port = 5432

**Comment by jkatz** [comment]
If the cluster already exists, you need to update the `pgbouncer.ini` file in the Secret, then restart the pgBouncer Pods.

**Comment by jkatz** [comment]
129317f et al. introduce a change that ensures the pgBouncer Pods use the same port as defined by the PostgreSQL Pod, instead of whatever is set in the Operator default configuration. This is backpatched to all supported versions.
