### ISSUE TITLE
Any Way to specify "node affinity" for a running cluster

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1831]
Hello, 

We have some clusters that are already deployed and we want to make sure they will run on a dedicated set of nodes only.
We have seen that it is easily possible to define the set of nodes that are allowed at cluster creation or when scaling a cluster.

However, in our case, we already have a deployed cluster and do not want to scale it up (and down again) to specify this.

Is there an "official" workaround to re-schedule the pods on a given set of nodes?
Will it be ok to edit:
- the pgcluster and add the necessary elements under "labels" and "userlabels"
- the main deployment and add also the necessary elements (we do not have replica here...)

By the way, we check the deployment of the backrest pod. With pgo 4.2.2, there is no information that specify where the related pod should be scheduled (even though, the --node-label was specified at cluster creation).

Thanks,
José

**Please tell us about your environment:**

Operating System: SUSE Linux Enterprise Server 12 SP3
Where is this running : Local
Storage being used: NFS
Container Image Tag: crunchydata/postgres-operator:centos7-4.2.2
PostgreSQL Version: crunchy-postgres-ha:centos7-11.7-4.2.2
Platform : kubernetes
Platform Version: 1.11.4

**Comment by jkatz** [comment]
I don't know if this would be an "official" way, but likely the best bet forward is:

1. Update the [appropriate custom resource](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/) to add the Node Affinity rule that you want. As noted in the documentation, this will have no effect.

2. *This may cause downtime* Update the Deployment of the PostgreSQL instance that you want to have the matching Node Affinity rules, but using the full [Kubernetes syntax](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity).

A future release will contemplate adding in the ability to update the node label(s).

Hope this helps!

**Comment by jose-joye** [comment]
Thanks!
