### ISSUE TITLE
After backup, latest symlink becomes unreachable

### ISSUE THREAD

**Issue by douggutaby** [CrunchyData/postgres-operator#1832]
**Describe the bug**
After a full/incr/diff backup run on a postgres cluster the latest symlink is unreachable in the ${CLUSTERNAME}-backrest-shared-repo pod.
sh-4.2$ ls -la /backrestrepo/toci-backrest-shared-repo/backup/db/latest
ls: cannot access /backrestrepo/toci-backrest-shared-repo/backup/db/latest: Permission denied
sh-4.2$ ls -la /backrestrepo/toci-backrest-shared-repo/backup/db/
....
drwxr-x---.  3 pgbackrest root    1 Aug 12 17:10 backup.history
-rw-r-----.  1 pgbackrest root 5790 Aug 31 13:38 backup.info
-rw-r-----.  1 pgbackrest root 5790 Aug 31 13:38 backup.info.copy
l??????????  ? ?          ?       ?            ? latest
sh-4.2$ 

**To Reproduce**
1. pgo create cluster
2. pgo backup
3. When backup is finished, try to run another backup
4. See error:
unable to remove '/backrestrepo/toci-backrest-shared-repo/backup/db/latest': [13] Permission denied

**Expected behavior**
sh-4.2$ ls -la /backrestrepo/toci-backrest-shared-repo/backup/db/latest 
lrwxrwxrwx. 1 pgbackrest root 33 Aug 31 11:14 /backrestrepo/toci-backrest-shared-repo/backup/db/latest -> 20200831-074548F_20200831-111244I
sh-4.2$ 

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): cephfs
* Container Image Tag: pgo-backrest-repo:centos7-4.4.0
* PostgreSQL Version: 4.4.0
* Platform (Docker, Kubernetes, OpenShift): OpenShift (OKD4)
* Platform Version: 4.5.0-0.okd-2020-07-14-153706-ga

**WA**
After ${CLUSTERNAME}-backrest-shared-repo pod delete, the new pod is good again for one backup.

**Comment by jkatz** [comment]
Was this a one-off issue or could you reproduce it consistently?

On the surface, this sounds like an issue with the storage class and the settings used to interface with it, but curious if you were able to consistently reproduce this.

**Comment by douggutaby** [comment]
Yes, I can reproduce it any time. Today I set anyuid instead of the dynamic uid, but the result is the same. The strange is that only this latest symlink is wrong, all of the other files seem good. Delete pod and latest works again.

**Comment by jkatz** [comment]
Spoke with folks more familiar with pgBackRest and determined this is not an issue. It's likely an issue with the configuration either of the underlying filesystem or the configuration of the Operator.

Are you using `DISABLE_FSGROUP=true` in your installation configuration?

**Comment by douggutaby** [comment]
No, it is false.

**Comment by douggutaby** [comment]
I set it to true in the yaml and set the DEPLOY_ACTION to update and run oc apply -f 
It updated the operator, after that I upgrade my cluster. First backup was successfull, but after the the latest symlink is ????? again.

**Comment by jkatz** [comment]
Is there something in your environment that prevents symlinks from being created within Pods?

**Comment by douggutaby** [comment]
I try to find them, but I don't know what I should look for.

**Comment by douggutaby** [comment]
Seems like a ceph issue not pgbackrest, because I got the same for a different pod with same pvc.
