### ISSUE TITLE
Error: backrestrepo pod not found for cluster example-db

### ISSUE THREAD

**Issue by rubin55** [CrunchyData/postgres-operator#1835]
We just ran into an issue where we had more than one backrestrepo pod - i.e., 1 terminated and 1 active backrestrepo pod, so matching `!=1` (see commit link below). We thusly got:

    pgo show backup common-db -n example
    Error: backrestrepo pod not found for cluster example-db

When we threw away the terminated pod, the command succeeded again. This feels like a bug to me.

I found the following associated commit:
https://github.com/CrunchyData/postgres-operator/commit/22c792658d510bbf055286569ec4186aae6e4f40

Search for `backrestrepo pod not found` line, see:
https://github.com/CrunchyData/postgres-operator/commit/22c792658d510bbf055286569ec4186aae6e4f40#r41942528

**Comment by jkatz** [comment]
- What version of Kubernetes are you running?
- What version of the Operator are you running?
- What activity was going on in your environment that would cause two Pods to be available?

I don't disagree that we can update the error message and/or not error at all but it helps to provide additional context. Thanks!

**Comment by rubin55** [comment]
>     * What version of Kubernetes are you running?
1.17.6

>     * What version of the Operator are you running?
4.4.0
 
>     * What activity was going on in your environment that would cause two Pods to be available?
We had a hanging NFS share and terminated the backrestrepo pod, which ended up in a terminated state; in the meantime, a new fresh pod was created that worked, but the client didn't like it and said:  `Error: backrestrepo pod not found for cluster example-db`. I searched and ran into that commit and reasoned that that `!=1` would match two pods, regardless of state. We threw away the terminated pod and the pgo client started working again.

> I don't disagree that we can update the error message and/or not error at all but it helps to provide additional context. Thanks!
Thanks! sorry for that!

**Comment by jkatz** [comment]
@rubin55 Thanks that helps a lot!

I'll look into ensuring that the above check is only performed on active Pods, as we shouldn't be considering Pods in other states. This likely extends to a bunch of the we're doing, but will look at getting this bug fixed for the upcoming release.

**Comment by jkatz** [comment]
Fix proposed. Will backpatch to supported versions.
