### ISSUE TITLE
Can't deploy postgres-operator, deploy pod stuck in a crash loop

### ISSUE THREAD

**Issue by Evolutiony** [CrunchyData/postgres-operator#1838]
** Which example are you working with? **
I'm working with quickstart https://access.crunchydata.com/documentation/postgres-operator/4.4.1/installation/postgres-operator/  but I tried other methods (except Helm) and none of them worked for me.

**What is the current behavior?**
The pgo-deploy-something pod, created by the job, keeps crashing after a minute or so. I'm unable to deploy the pgo operator. If I change the ` DEPLOY_ACTION = 'uninstall' ` it also can't be deployed, it fails with error.

` [root@localhost kubernetes]# sudo -u centos kubectl get pods -n pgo`
` NAME                            READY                  STATUS                       RESTARTS                      AGE`
`pgo-deploy-n2pqf            0/1                       Error                               0                             10m`

**What is the expected behavior?**
Pod should run untill the operator is installed, at which point it should turn into completed status.

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System:
* Where is this running : Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos7-12.4-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.19

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
` [root@localhost kubernetes]# sudo -u centos kubectl get pods -n pgo
NAME               READY   STATUS   RESTARTS   AGE
pgo-deploy-n2pqf   0/1     Error    0          10m `

` [root@localhost kubernetes]# sudo -u centos kubectl describe pod pgo-deploy-n2pqf -n pgo
Name:         pgo-deploy-n2pqf
Namespace:    pgo
Priority:     0
Node:         node1.cornet/192.168.31.46
Start Time:   Tue, 01 Sep 2020 18:21:07 +0200
Labels:       controller-uid=4fc7ba05-cf1e-4863-bb32-9d57c1ce3b3e
              job-name=pgo-deploy
Annotations:  cni.projectcalico.org/podIP: 192.168.234.150/32
              cni.projectcalico.org/podIPs: 192.168.234.150/32
Status:       Failed
IP:           192.168.234.150
IPs:
  IP:           192.168.234.150
Controlled By:  Job/pgo-deploy
Containers:
  pgo-deploy:
    Container ID:   docker://f479ae5f956f8247a349fd14becbb7185e7e7be067574f58797086b2096cd46d
    Image:          registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.4.1
    Image ID:       docker-pullable://registry.developers.crunchydata.com/crunchydata/pgo-deployer@sha256:0aa64425a996547d0554a8447b1c3354e2377dc55149cef0ea3be150e3ef043b
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 01 Sep 2020 18:21:08 +0200
      Finished:     Tue, 01 Sep 2020 18:23:49 +0200
    Ready:          False
    Restart Count:  0
    Environment:
      DEPLOY_ACTION:  uninstall
    Mounts:
      /conf from deployer-conf (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-deployer-sa-token-th5lg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  deployer-conf:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      pgo-deployer-cm
    Optional:  false
  pgo-deployer-sa-token-th5lg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgo-deployer-sa-token-th5lg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From                   Message
  ----    ------     ----  ----                   -------
  Normal  Pulled     17m   kubelet, node1.cornet  Container image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.4.1" already present on machine
  Normal  Created    17m   kubelet, node1.cornet  Created container pgo-deploy
  Normal  Started    17m   kubelet, node1.cornet  Started container pgo-deploy
  Normal  Scheduled  16m   default-scheduler      Successfully assigned pgo/pgo-deploy-n2pqf to node1.cornet `

` sudo -u centos kubectl get pv
NAME                               CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                      STORAGECLASS   REASON   AGE
cnplatform-service-logger-claim0   100Mi      RWX            Retain           Bound       default/cnplatform-service-logger-claim0                           6h39m
crunchy-pv1                        1Gi        RWX            Retain           Available                                                                      27h
crunchy-pv10                       1Gi        RWX            Retain           Available                                                                      2d23h
crunchy-pv11                       1Gi        RWX            Retain           Available                                                                      2d23h
crunchy-pv12                       1Gi        RWX            Retain           Available                                                                      2d23h
crunchy-pv13                       1Gi        RWX            Retain           Available                                                                      2d23h
crunchy-pv15                       1Gi        RWX            Retain           Available                                                                      2d23h
crunchy-pv16                       1Gi        RWX            Retain           Available                                                                      2d23h `

` [root@localhost kubernetes]# sudo -u centos kubectl get nodes
NAME                    STATUS   ROLES    AGE    VERSION
localhost.localdomain   Ready    master   4d3h   v1.19.0
node1.cornet            Ready    <none>   4d2h   v1.19.0
node2.cornet            Ready    <none>   4d2h   v1.19.0 `

 kubectl log yourPodName

` [root@localhost kubernetes]# sudo -u centos kubectl logs pgo-deploy-n2pqf -n pgo
PLAY [Deploy Crunchy PostgreSQL Operator] **************************************
TASK [Gathering Facts] *********************************************************
ok: [localhost]
TASK [pgo-preflight : include_tasks] *******************************************
included: /ansible/roles/pgo-preflight/tasks/vars.yml for localhost
TASK [pgo-preflight : Check for "/conf/values.yaml"] ***************************
ok: [localhost]
TASK [pgo-preflight : fail] ****************************************************
skipping: [localhost]
TASK [pgo-preflight : include_vars] ********************************************
ok: [localhost]
TASK [pgo-preflight : fail] ****************************************************
skipping: [localhost]
TASK [pgo-preflight : assert] **************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
TASK [pgo-preflight : assert] **************************************************
skipping: [localhost]
TASK [pgo-preflight : assert] **************************************************
skipping: [localhost]
TASK [pgo-preflight : assert] **************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
TASK [pgo-preflight : include_tasks] *******************************************
skipping: [localhost]
TASK [pgo-preflight : include_tasks] *******************************************
included: /ansible/roles/pgo-preflight/tasks/check_kubernetes.yml for localhost
TASK [pgo-preflight : Check if the kubectl command is installed] ***************
changed: [localhost]
TASK [pgo-preflight : Ensure kubectl is installed] *****************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
TASK [pgo-preflight : include_tasks] *******************************************
included: /ansible/roles/pgo-preflight/tasks/check_vars.yml for localhost
TASK [pgo-preflight : Check if mandatory variables are defined] ****************
skipping: [localhost] => (item=pgo_operator_namespace)
skipping: [localhost] => (item=pgo_installation_name)
skipping: [localhost] => (item=pgo_admin_username)
skipping: [localhost] => (item=pgo_admin_password)
skipping: [localhost] => (item=pgo_admin_role_name)
skipping: [localhost] => (item=pgo_admin_perms)
skipping: [localhost] => (item=ccp_image_prefix)
skipping: [localhost] => (item=ccp_image_tag)
skipping: [localhost] => (item=pgo_image_prefix)
skipping: [localhost] => (item=pgo_image_tag)
skipping: [localhost] => (item=disable_auto_failover)
skipping: [localhost] => (item=badger)
skipping: [localhost] => (item=metrics)
skipping: [localhost] => (item=archive_mode)
skipping: [localhost] => (item=archive_timeout)
skipping: [localhost] => (item=db_password_length)
skipping: [localhost] => (item=create_rbac)
skipping: [localhost] => (item=db_port)
skipping: [localhost] => (item=db_replicas)
skipping: [localhost] => (item=db_user)
skipping: [localhost] => (item=backrest_storage)
skipping: [localhost] => (item=backup_storage)
skipping: [localhost] => (item=primary_storage)
skipping: [localhost] => (item=replica_storage)
skipping: [localhost] => (item=pgo_client_version)
skipping: [localhost] => (item=pgbadgerport)
skipping: [localhost] => (item=exporterport)
skipping: [localhost] => (item=scheduler_timeout)
skipping: [localhost] => (item=namespace_mode)
skipping: [localhost] => (item=reconcile_rbac)
TASK [pgo-operator : Set output directory fact] ********************************
ok: [localhost]
TASK [pgo-operator : Ensure output directory exists] ***************************
changed: [localhost]
TASK [pgo-operator : include_tasks] ********************************************
skipping: [localhost] => (item=openshift_auth.yml)
skipping: [localhost] => (item=openshift.yml)
TASK [pgo-operator : include_tasks] ********************************************
included: /ansible/roles/pgo-operator/tasks/kubernetes_auth.yml for localhost
included: /ansible/roles/pgo-operator/tasks/kubernetes.yml for localhost
TASK [pgo-operator : Set the Kubernetes Context] *******************************
skipping: [localhost]
TASK [pgo-operator : include_tasks] ********************************************
included: /ansible/roles/pgo-operator/tasks/cleanup.yml for localhost
TASK [pgo-operator : Use kubectl or oc] ****************************************
ok: [localhost]
TASK [pgo-operator : Find watched namespaces] **********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl get namespaces -o json --selector=vendor=crunchydata,pgo-installation-name=devtest\n", "delta": "0:02:30.649731", "end": "2020-09-01 16:23:49.307821", "msg": "non-zero return code", "rc": 1, "start": "2020-09-01 16:21:18.658090", "stderr": "Unable to connect to the server: dial tcp 10.96.0.1:443: i/o timeout", "stderr_lines": ["Unable to connect to the server: dial tcp 10.96.0.1:443: i/o timeout"], "stdout": "", "stdout_lines": []}
PLAY RECAP *********************************************************************
localhost                  : ok=16   changed=2    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0 `

**Comment by jkatz** [comment]
`"Unable to connect to the server: dial tcp 10.96.0.1:443: i/o timeout"`

It appears that the Kubernetes environment is unreachable from within the `pgo-deployer` container.

**Comment by jkatz** [comment]
Based on how your environment is set up, it may be easier to deploy by running the Ansible playbooks from your host machine directly. You can find them here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/installation/other/ansible/](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/other/ansible/)

Other than that, it sounds like, for whatever reason in your environment, the `pgo-deployer` container can't talk to your API server.

**Comment by Evolutiony** [comment]
Thank you for a quick response.

That IP 10.96.0.1 is kubernetes pod IP, even though my nodes and calico (I'm using calico for communication between the nodes), uses 192. range. 

I tried the Ansible approach and I get an error ` fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl config use-context kubernetes-admin@kubernetes", "delta": "0:00:00.094481", "end": "2020-09-02 12:46:05.993285", "msg": "non-zero return code", "rc": 1, "start": "2020-09-02 12:46:05.898804", "stderr": "error: no context exists with the name: \"kubernetes-admin@kubernetes\"", "stderr_lines": ["error: no context exists with the name: \"kubernetes-admin@kubernetes\""], "stdout": "", "stdout_lines": []} ` , however when I run the command `kubectl config current-context` I get the following result `kubernetes-admin@kubernetes`

I've used the default kubeadm installation, and I'm running this on Centos 7 virtual machines.
I did notice this error `"Unable to connect to the server: dial tcp 10.96.0.1:443: i/o timeout"` when I experimented with other stuff, the problem is I don't even know where that IP is coming from. The IP itself belongs to kubernetes service in default namespace with type ClusterIP.

**Comment by jkatz** [comment]
The Calico mention is a key bit. We've seen issues in the past based on Calico's settings or other networking policy settings that can cause communication issues with various services. #1362 may have some guidance on how to troubleshoot.

Anyway, this seems to be something in your environment as other services are affected and not directly to the Operator itself.
