### ISSUE TITLE
pgbadger service not working with 4.3.2

### ISSUE THREAD

**Issue by avanichy25** [CrunchyData/postgres-operator#1848]
**I'm submitting a ...**

 
 - [x] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**  
**Bug**

**What is the current behavior?**
I am running with 4.3.2 with badger enabled. After spinning up a cluster i can see badger sidecar is up and running but while opening via browser, it complaining below error.

```
Error running badger-generate: exit status 137
/tmp/cmd: line 1:    68 Killed                  /bin/pgbadger -f stderr -o /report/index.html /pgdata/testnew/pg_log/*.log
```
**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**
It should work without any issues.

**What is the motivation or use case for changing the behavior?**
NA

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

```
pgo create cluster testnew --replica-count=1 --sync-replication --cpu-limit 1 --cpu 500m --memory-limit 2Gi --memory 512Mi -n pgo --pgbouncer --pgbadger --metrics
```

**Please tell us about your environment:**

 - Operating System: Azure COS
 - Container Image Tag: 4.3.2
 - Operator Version: 4.3.2
 - Storage (NFS, hostpath, storage class): stroageclass default()
 - PostgreSQL Version:  
 - Platform (Docker, Kubernetes, OpenShift): k8s
 - Platform Version:

**Comment by jkatz** [comment]
Try increasing the memory request/limit. This was the outcome of #1763.

This was backpatched down to 4.4.1, but you could apply similar logic for 4.3.3 (and 4.3.2 by extension).
