### ISSUE TITLE
Trying to access PostgreSQL database from different namespace

### ISSUE THREAD

**Issue by rg2609** [CrunchyData/postgres-operator#1849]
**Describe the bug**
I am trying to access the postgres data from the different namespace, but I could not connect to the database through `psql`.
I tried the following psql commands to connect the database.
```
psql -U postgres -h postgres-operator -p 8443 -d postgres

psql -U postgres -h postgres-operator -d postgres

psql -U postgres -h hippo -d postgres
```
I am getting an error `psql: could not translate host name "hippo" to address: Name or service not known`

**Expected behavior**
Connet the database.

**Please tell us about your environment:**

* Operating System: Debian GNU/Linux 10 (buster)
* Where is this running ( Local , Cloud Provider): GCE
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: centos7-12.4-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.18.8

**Comment by jkatz** [comment]
- What environment are you running `psql` from? Is on a host machine or some other service?
- If it's on your host machine, did you publicly expose the service so that `psql` is able to access it?
- If you did not expose the service, did you set up a port forward?

**Comment by rg2609** [comment]
I am running the `psql` command from the Kubernetes container.

**Comment by jkatz** [comment]
If you've deployed your PostgreSQL container to a different namespace (which, the default PostgreSQL Operator scripts use `pgo`), you'll have to specify the FQDN of your environment:

[https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services).

If you're trying to connect to a database from within a PostgreSQL container itself, you do not need to specify the hostname as you can connect over a unix socket. In this case, `psql hippo` works.

If you want to connect directly from your host machine, you can set up a port forward. Assuming the defaults:

```
kubectl -n pgo port-forward svc/hippo 5432:5432
psql -h localhost -p 5432 -U testuser hippo
```
