### ISSUE TITLE
Install Helm chart and PGO client

### ISSUE THREAD

**Issue by rg2609** [CrunchyData/postgres-operator#1855]
I am trying to install the crunchy data through helm and I found the helm chart of it in your repository, but for the PGO client, there is nothing in your helm repository. Actually I wanted this CrunchyData to be installed through the Terraform. So if there any repository or any way to add PGO client installation via Terraform.

**Please tell us about your environment:**

* Operating System: Debian GNU/Linux 10 (buster)
* Where is this running ( Local , Cloud Provider): GCE
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: centos7-12.4-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.18.8

**Comment by jkatz** [comment]
You can install the `pgo-client` container from the Helm chart by setting [`pgo_client_container_install `](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/) to `true`.

If you want to install the binary in your local environment, you can set [`pgo_client_install`](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/) to `true` run the [`client-setup.sh`](https://github.com/CrunchyData/postgres-operator/blob/master/installers/kubectl/client-setup.sh) script, or download it directly from the [releases](https://github.com/CrunchyData/postgres-operator/releases) page.

**Comment by rg2609** [comment]
Thank you @jkatz  for your help, and its works. my next 2nd question is that can we create a cluster to in this helm chart.

**Comment by rg2609** [comment]
@jkatz and how to run the initial setup.sql file

**Comment by jkatz** [comment]
> can we create a cluster to in this helm chart.

No. However, we welcome patches that can continue to improve the PostgreSQL Operator

> how to run the initial setup.sql file

You first need to create a policy. This is described here:

[Policy Management](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#policy-management)

Once the SQL policy is in place, you can reference it using the [`--policies`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) flag on create, which maps to the [`Policies`](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/) CRD attribute.

**Comment by rg2609** [comment]
> You can install the `pgo-client` container from the Helm chart by setting [`pgo_client_container_install `](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/) to `true`

I did this and after that `pgo` command will run under the 'pgo-client` deployment container. And for creating a policy with `--in-file=init_db.sql` flag, that needs the init_db.sql to be in the 'pgo-client' container. 

So how to make the `init_db.sql` file perent in the `pgo-client` container.
