### ISSUE TITLE
Cannot creat logical backups with pgo with cluster default password

### ISSUE THREAD

**Issue by xmarcoied** [CrunchyData/postgres-operator#1856]
**Describe the bug**
Cannot create logical backups 

**To Reproduce**
1. Created a pgo cluster with pgo cli command ` pgo create cluster test`
2. Created a logical backup with pgo cli command `pgo backup test --backup-type=pgdump`

**Expected behavior**
Backup job to happen successfully

**Current behavior**
When checking kubernetes logs with `kubectl -n pgo1 logs jobs/backup-test-pgdump-ucki` 
I find that 
```
Sun Sep  6 12:29:32 UTC 2020 INFO: Waiting for PostgreSQL to be ready..
test:5432 - accepting connections
Sun Sep  6 12:29:32 UTC 2020 INFO: Checking if PostgreSQL is accepting queries..
psql: error: could not connect to server: FATAL:  password authentication failed for user "postgres"
password retrieved from file "/tmp/pgpass
```

**Please tell us about your environment:**

* Operating System: Linux, Ubuntu 18
* Where is this running: Minikube Local
* Storage being used (NFS, Hostpath, Gluster, etc):
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: operator 4.4.0

**Comment by xmarcoied** [comment]
I just resolved this issue, by setting a password in the command of creation cluster. 

So, I create cluster with `pgo create cluster test --password=testpassowrd` , then when I performed the logical backup. It did worked fine. 

I am kinda interested to fix this bug, so if there's somebody passing on this issue experienced with the codebase, let me know where I can start. 
Thanks.

**Comment by jkatz** [comment]
I was unable to reproduce this issue: my logical backup worked even with the default randomly generated password.

How soon after did you run `pgo backup test --backup-type=pgdump` after `pgo create cluster test`? If you did not allow enough time, there is a chance that the `postgres` user's password had not yet been set up, which would certainly cause the logical backup to fail.

**Comment by xmarcoied** [comment]
@jkatz 
That's most probably what happened at my side too. Thanks. 
Will close the issue.
