### ISSUE TITLE
Enabling google stackdriver metrics.

### ISSUE THREAD

**Issue by xmarcoied** [CrunchyData/postgres-operator#1858]
** Which example are you working with? **
I am trying to send metrics generated from pgo clusters to google stackdriver (through google prometheus-to-sd sidecar). 

**What is the current behavior?**
I can only find the prometheus-synatx metrics.

**What is the expected behavior?**
I want to add the prometheus-to-sd side car so, I send the metrics to google stackdriver at the end.

**Comment by jkatz** [comment]
The Deployment templates for the PostgreSQL clusters are configurable, so you can choose to add your own sidecars (with a warning of YMMV):

1. Edit the `pgo-config` ConfigMap:

`kubectl -n pgo edit cm pgo-config`

2. Find the `cluster-deployment.json` entry
3. Modify the Deployment template to your specifications
4. Restart the PostgreSQL Operator Pod

```
kubectl -n pgo scale postgres-operator --replicas=0
kubectl -n pgo scale postgres-operator --replicas=1
```

5. Any newly deployed PostgreSQL clusters will be deployed with the new template.

However, looking at [https://github.com/Stackdriver/stackdriver-prometheus-sidecar](https://github.com/Stackdriver/stackdriver-prometheus-sidecar) it seems that this would deploy next to your Prometheus Deployment, which is a separate Deployment process, and with the changes coming in Operator 4.5.0 (files for that are already committed), you can choose how you deploy Prometheus.

Anyway, it's ultimately up to you how you deploy Prometheus: the Operator enables metrics collection, and while we have installers to set up the aggregation/visualization (i.e. Prometheus/Grafana), you have the flexibility to choose how you ingest the statistics.
