### ISSUE TITLE
Failed to build the operator

### ISSUE THREAD

**Issue by renlei-bj** [CrunchyData/postgres-operator#1859]
**Describe the bug**
Followed the document to build the project but got errors.

**To Reproduce**
1. Followed this guide: https://access.crunchydata.com/documentation/postgres-operator/latest/contributing/developer-setup/
2. My environment variables are set as below:
    ```
    export PGOROOT=$GOPATH/src/github.com/crunchydata/postgres-operator
    export PGO_BASEOS=rhel7
    export PGO_CMD=kubectl
    export PGO_IMAGE_PREFIX=crunchydata
    export PGO_OPERATOR_NAMESPACE=pgo
    export PGO_VERSION=4.4.1
    ```
3. In the step of other requirements, I am using a rhel7 but I still downloaded the files.
    - [x] The development host has been created, has access to yum updates, and has a regular user account with sudo rights to run yum.
    - [x] GOPATH points to a directory containing src,pkg, and bin directories.
    - [x] The development host has $GOPATH/bin added to its PATH environment variable. Development tools will be installed to this path. Defining a GOBIN environment variable other than $GOPATH/bin may yield unexpected results.
    - [x] The development host has git installed and has cloned the postgres-operator repository to $GOPATH/src/github.com/crunchydata/postgres-operator. Makefile targets below are run from the repository directory.
    - [ ] Deploying the Operator will require deployment access to a Kubernetes or OpenShift cluster
    - [x] Once you have cloned the git repository, you will need to download the CentOS 7 repository files and GPG keys and place them in the $PGOROOT/conf directory. You can do so with the following code:

4. Step of `make setup` was successful.

5. Steps of `make verify-codegen` and `make update-codegen` were failed:
```
# make verify-codegen
/root/work/go/src/github.com/crunchydata/postgres-operator/hack/verify-codegen.sh
bash: /root/work/go/src/github.com/crunchydata/postgres-operator/hack/../hack/../../code-generator/generate-groups.sh: No such file or directory
```

6. Step of `make all` was failed:
```
go install -gcflags='' pgo/pgo.go
# github.com/crunchydata/postgres-operator/pkg/generated/clientset/versioned/typed/crunchydata.com/v1
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgcluster.go:73:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("pgclusters").Name(name).VersionedParams(&options, scheme.ParameterCodec).Do
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgcluster.go:90:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("pgclusters").VersionedParams(&opts, scheme.ParameterCodec).Timeout(timeout).Do
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgcluster.go:107:8: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("pgclusters").VersionedParams(&opts, scheme.ParameterCodec).Timeout(timeout).Watch
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgcluster.go:117:5: not enough arguments in call to c.client.Post().Namespace(c.ns).Resource("pgclusters").Body(pgcluster).Do
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgcluster.go:130:5: not enough arguments in call to c.client.Put().Namespace(c.ns).Resource("pgclusters").Name(pgcluster.ObjectMeta.Name).Body(pgcluster).Do
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgcluster.go:146:5: not enough arguments in call to c.client.Put().Namespace(c.ns).Resource("pgclusters").Name(pgcluster.ObjectMeta.Name).SubResource("status").Body(pgcluster).Do
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgcluster.go:158:5: not enough arguments in call to c.client.Delete().Namespace(c.ns).Resource("pgclusters").Name(name).Body(options).Do
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgcluster.go:174:5: not enough arguments in call to c.client.Delete().Namespace(c.ns).Resource("pgclusters").VersionedParams(&listOptions, scheme.ParameterCodec).Timeout(timeout).Body(options).Do
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgcluster.go:187:5: not enough arguments in call to c.client.Patch(pt).Namespace(c.ns).Resource("pgclusters").SubResource(subresources...).Name(name).Body(data).Do
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgpolicy.go:73:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("pgpolicies").Name(name).VersionedParams(&options, scheme.ParameterCodec).Do
	have ()
	want (context.Context)
pkg/generated/clientset/versioned/typed/crunchydata.com/v1/pgpolicy.go:73:5: too many errors
# github.com/crunchydata/postgres-operator/internal/config
internal/config/pgoconfig.go:743:59: not enough arguments in call to clientset.CoreV1().ConfigMaps(namespace).Get
	have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
make: *** [build-pgo-client] Error 2
```

**Expected behavior**
Can perform a successful build on rhel7.

**Screenshots**
N/A.

**Please tell us about your environment:**

* Operating System: RHEL 7.8
* Where is this running (Local)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
N/A.

**Comment by jkatz** [comment]
Per the same documentation referenced:

> Therefore, in the event that a Custom Resource defined within the PostgreSQL Operator API ($PGOROOT/pkg/apis/crunchydata.com) is updated, the verify-codegen target will indicate that an update is needed, and the update-codegen target should then be utilized to generate the updated code prior to compiling.

You only need to run that step if you have made modifications to the CRDs.

It sounds like you have dependency mismatches in your environment. Be sure you've installed the correct dependencies based on the values in Gopkg.toml et al.

I'll also note that the container images in the [Developer Portal](https://www.crunchydata.com/developers) are based on CentOS; the RHEL / UBI images are available with a subscription.
