### ISSUE TITLE
Automatic operator upgrade through OLM not working

### ISSUE THREAD

**Issue by megabreit** [CrunchyData/postgres-operator#1860]
**Describe the bug**
We're using crunchy operator 4.3.2 from Operator hub on Openshift 4.5.7.
The operator channel is "stable", approval is set to "automatic". With this setup operator updates are usually applied automatically when they appear in the channel.
Some (unknown) time ago the stable channel switched to 4.4.1.
Expected behavior is that OLM would trigger the update to 4.4.1. But it doesn't.

Feedback from Redhat was:
"...the CSV of 4.4.1 version doesn't includes the field spec.replaces, so that explains why OLM doesn't performs any automatic update."

**Please tell us about your environment:**

* Operating System: RHCOS 4.5
* Where is this running: Local
* Platform: OpenShift
* Platform Version: 4.5.7

**Additional context**
I'm not sure whether or not this is intentional or a bug.
In case it's intentional, what's the recommended upgrade procedure with or around OLM?

**Comment by jkatz** [comment]
The replaces directive is present:

[https://github.com/operator-framework/community-operators/blob/master/community-operators/postgresql/4.4.1/postgresoperator.v4.4.1.clusterserviceversion.yaml#L242](https://github.com/operator-framework/community-operators/blob/master/community-operators/postgresql/4.4.1/postgresoperator.v4.4.1.clusterserviceversion.yaml#L242)

I believe you have to go to 4.4.0 first.

**Comment by jkatz** [comment]
You may need to open up this ticket in the [Community Operators](https://github.com/operator-framework/community-operators) project, as they had recently done some things to adjust the PostgreSQL Operator channels that I am less familiar with.

**Comment by megabreit** [comment]
Thanks for the info. But the version 4.4.1 that you're referencing is not the version 4.4.1 which is on operator hub. There are 2 versions, one community version and the one I'm using, the "Redhat supported" version.. it seems not really to be supported because Redhat sent me here. I'll go to the community project and ask there...

**Comment by jkatz** [comment]
This sounds like the certified Operator, which you are correct, is part of a separate workflow.

Let me chat with some of the Red Hat folks I know and see if we can come up with an answer.

**Comment by jatindersandhu** [comment]
it is same problem occur with us. We download operator from RHEL on OC4 .. When we download in UAT it was 4.4.0 , now in prod is 4.4.1.. this changing version give us issue because we tested everything 4.4.0 version.. but everytime it change version it give us stability issue

**Comment by megabreit** [comment]
@jkatz Why did you close this issue? Did you find anybody at Redhat to talk to? The recommended issue I opened in the community project is probably useless...

**Comment by jkatz** [comment]
@megabreit I have spoken with folks at Red Hat and we have a resolution path to try out. This will most likely roll out when we perform our next release.

As it's related to the OLM, I thought that the ticket in the upstream repo would suffice. I apologize if I caused any confusion.
