### ISSUE TITLE
Recreate pgbackrest stanza

### ISSUE THREAD

**Issue by timbrd** [CrunchyData/postgres-operator#1861]
I accidentially deleted the pvc used for backups. Now the scheduled jobs are not able to backup my databases anymore:

```
time="2020-09-08T07:13:02Z" level=info msg="stderr=[ERROR: [055]: unable to load info file '/backrestrepo/postgresql-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/postgresql-backrest-shared-repo/backup/db/backup.info.copy':\n       FileMissingError: unable to open missing file '/backrestrepo/postgresql-backrest-shared-repo/backup/db/backup.info' for read\n       FileMissingError: unable to open missing file '/backrestrepo/postgresql-backrest-shared-repo/backup/db/backup.info.copy' for read\n       HINT: backup.info cannot be opened and is required to perform a backup.\n       HINT: has a stanza-create been performed?\n]"
time="2020-09-08T07:13:02Z" level=error msg="command terminated with exit code 55"
```

Is there a way to tell the operator to create the pgbackrest stanza again? I couldn't find any information in the documentation or on this repo.

**Comment by jkatz** [comment]
Have you tried executing into any of the Pods and running [`pgbackrest stanza-create`](https://pgbackrest.org/command.html#command-stanza-create)? Or creating the `stanza-create` job? The pgtask for it is modeled here:

[https://github.com/CrunchyData/postgres-operator/blob/master/internal/operator/backrest/stanza.go#L55](https://github.com/CrunchyData/postgres-operator/blob/master/internal/operator/backrest/stanza.go#L55)

or by observing how the stanza-create task looks when a new cluster is created and creating something similar.
