### ISSUE TITLE
pgo create cluster flag --password is not working for psql connection

### ISSUE THREAD

**Issue by rg2609** [CrunchyData/postgres-operator#1862]
**Describe the bug**
I am creating the postgres cluster using [`pgo_create_cluster`](https://access.crunchydata.com/documentation/postgres-operator/4.4.1/pgo-client/reference/pgo_create_cluster/) with the flag `--password` and the cluster got created, but when I tried to get `psql` connection in the same postgres pod container the password is not working.

```
bash-4.2$ psql -h localhost -U postgres -d postgres
Password for user postgres: 
psql: error: could not connect to server: FATAL:  password authentication failed for user "postgres"
```
**One more**
Along with flag `--password` added anther flag `--username` but it's setting its default username (`postgres`) in postgres database

Is there any other flag to set for the postgres password authentication and for username in the postgres database
**Please tell us about your environment:**

* Operating System: Debian GNU/Linux 10 (buster)
* Where is this running ( Local , Cloud Provider): GCE
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: centos7-12.4-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.18.8

**Comment by jkatz** [comment]
You need to use `--password-superuser` to set the password of the `postgres` user, which is the superuser. This is documented in the [`pgo create cluster`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) command:

[https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/)

This is also described in the release notes where the feature was introduced:

[https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.3.0/#standby-clusters-multi-kubernetes-deployments](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.3.0/#standby-clusters-multi-kubernetes-deployments).

**Comment by rg2609** [comment]
For `--username` flag I am getting an error
```
pgo create cluster -n pgo abc  --username="xyz"

Error: Secret "abc-xyz-secret" is invalid: metadata.name: Invalid value: "abc-xyz-secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
command terminated with exit code 2
```

**Comment by jkatz** [comment]
I was unable to reproduce this issue. This could be an issue with your Kubernetes environment, something with how your text is being encoded, or some other issue that I'm unaware of. `abc-xyz-secret` is a valid DNS-1123 name, and it so happens I have something similar created with the same command:

```
[vagrant@centos8 postgres-operator]$ kubectl -n jkatz get secrets
NAME                                  TYPE                                  DATA   AGE
abc-backrest-repo-config              Opaque                                8      41s
abc-postgres-secret                   Opaque                                2      41s
abc-primaryuser-secret                Opaque                                2      41s
abc-xyz-secret                        Opaque                                2      41s
```
