### ISSUE TITLE
storage-config

### ISSUE THREAD

**Issue by yangvipguang** [CrunchyData/postgres-operator#1865]
@jkatz   Please
I have a simple question. 
pgo create cluster testcluster2 --storage-config=fastdisk。

Does this fastdisk  have to be written in the operator in advance to take effect?
Can I directly use other storage class. Otherwise, you must modify the operator configuration file every time you add a storage class

**Comment by jkatz** [comment]
This is covered in the documentation:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/#configure-the-postgresql-operator-installer](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/#configure-the-postgresql-operator-installer)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/pgo-yaml-configuration/#storage](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/pgo-yaml-configuration/#storage)

The Operator configuration file contains "storage configurations" that are reference by the Operator itself. You can add and remove them from the configuration file as you see fit. I believe there are up to 50 that are allowed.

If you add additional storage classes in your environment, you need to create a storage configuration for them which would involve rebooting the Operator.
