### ISSUE TITLE
Not able to connect with postgreSQL using super user for creating multiple databases

### ISSUE THREAD

**Issue by vg02111989** [CrunchyData/postgres-operator#1868]
I had installed the latest 4.4.1 version of crunchy data operator for achieving Postgres HA in kubernetes
postgres-operator.yml file will create one database. but I want to create multiple database in the same postgres instance which I am not able to do.

I tried to run a client also with super user credentials but not able to login and gave error like -- 

kubectl run pgsql-postgresql-client2 --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.7.0-debian-10-r9 --env="PGPASSWORD=e8a48653851e28c69d0506508fb27fc5" --command -- psql --host 172.20.130.186 -U postgres -p 5432
psql: FATAL:  password authentication failed for user "postgres"

If I will login into postgres pod than only I was able to create any new database:

Please suggest how to create the multiple database in the same postgres instance and how to create the schemas using .SQL files

Thanks a lot in advance

**Please tell us about your environment:**

* Operating System: AWS EC2 linux
* Where is this running ( Local , Cloud Provider) - Amazon EKS cluster
* Storage being used : Amazon EFS
* Container Image Tag: centos7-12.4-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Amazon EKS
* Platform Version:

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
kubectl describe pod postgres-operator-58f448cd8c-krlw8 -n pgo
Name:         postgres-operator-58f448cd8c-krlw8
Namespace:    pgo
Priority:     0
Node:         ip-10-57-10-97.ap-south-1.compute.internal/10.57.10.97
Start Time:   Wed, 09 Sep 2020 09:06:05 +0000
Labels:       name=postgres-operator
              pod-template-hash=58f448cd8c
              vendor=crunchydata
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.57.10.206
IPs:
  IP:           10.57.10.206
Controlled By:  ReplicaSet/postgres-operator-58f448cd8c
Containers:
  apiserver:
    Container ID:   docker://fb8dce61377a6a434e4cbabd09ff3cb5ac7f481358c957b8f81b0b2640be8844
    Image:          registry.developers.crunchydata.com/crunchydata/pgo-apiserver:centos7-4.4.1
    Image ID:       docker-pullable://registry.developers.crunchydata.com/crunchydata/pgo-apiserver@sha256:6672430124f6d80075928d7094be3dd44fb8d0c58d576ae7299bcdc66ee4f953
    Port:           8443/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 09 Sep 2020 09:06:06 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get https://:8443/healthz delay=15s timeout=1s period=5s #success=1 #failure=3
    Readiness:      http-get https://:8443/healthz delay=15s timeout=1s period=5s #success=1 #failure=3
    Environment:
      CRUNCHY_DEBUG:           false
      PORT:                    8443
      NAMESPACE:               pgo
      PGO_INSTALLATION_NAME:   devtest
      PGO_OPERATOR_NAMESPACE:  pgo (v1:metadata.namespace)
      TLS_CA_TRUST:
      TLS_NO_VERIFY:           false
      DISABLE_TLS:             false
      NOAUTH_ROUTES:
      ADD_OS_TRUSTSTORE:       false
      DISABLE_EVENTING:        false
      EVENT_ADDR:              localhost:4150
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from postgres-operator-token-s8zf9 (ro)
  operator:
    Container ID:   docker://91ada863b7b52e826237b6d42e1df558ec406490001d2dc9cc32391ea5aea477
    Image:          registry.developers.crunchydata.com/crunchydata/postgres-operator:centos7-4.4.1
    Image ID:       docker-pullable://registry.developers.crunchydata.com/crunchydata/postgres-operator@sha256:b189bf0578b1adc205ba71bd4ea96eaa803bea8f7accf491fd93bd0012ad2941
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 09 Sep 2020 09:06:06 +0000
    Ready:          True
    Restart Count:  0
    Readiness:      exec [ls /tmp] delay=4s timeout=1s period=5s #success=1 #failure=3
    Environment:
      CRUNCHY_DEBUG:           false
      NAMESPACE:               pgo
      PGO_INSTALLATION_NAME:   devtest
      PGO_OPERATOR_NAMESPACE:  pgo (v1:metadata.namespace)
      MY_POD_NAME:             postgres-operator-58f448cd8c-krlw8 (v1:metadata.name)
      DISABLE_EVENTING:        false
      EVENT_ADDR:              localhost:4150
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from postgres-operator-token-s8zf9 (ro)
  scheduler:
    Container ID:   docker://18587c7a8d85baf48578f747b3c3ac15b05341e5b469456fdf0290d3678d2ccf
    Image:          registry.developers.crunchydata.com/crunchydata/pgo-scheduler:centos7-4.4.1
    Image ID:       docker-pullable://registry.developers.crunchydata.com/crunchydata/pgo-scheduler@sha256:7c1a192ba376a82b4307a6fe3eb005667a3a21b8d43719e987e51de06a09a222
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 09 Sep 2020 09:06:07 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       exec [bash -c test -n "$(find /tmp/scheduler.hb -newermt '61 sec ago')"] delay=60s timeout=1s period=60s #success=1 #failure=2
    Environment:
      CRUNCHY_DEBUG:           false
      PGO_OPERATOR_NAMESPACE:  pgo (v1:metadata.namespace)
      NAMESPACE:               pgo
      PGO_INSTALLATION_NAME:   devtest
      TIMEOUT:                 3600
      EVENT_ADDR:              localhost:4150
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from postgres-operator-token-s8zf9 (ro)
  event:
    Container ID:   docker://20fbbec5f70e8c549a53dc968afce9b3df2c4f0de7f089ba91e5cbdfb445fd34
    Image:          registry.developers.crunchydata.com/crunchydata/pgo-event:centos7-4.4.1
    Image ID:       docker-pullable://registry.developers.crunchydata.com/crunchydata/pgo-event@sha256:225b7cf0b1d2b80becb63840e40766442429f9326be75d6cf14660c254a4c8a5
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 09 Sep 2020 09:06:07 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:4151/ping delay=15s timeout=1s period=5s #success=1 #failure=3
    Environment:
      TIMEOUT:  3600
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from postgres-operator-token-s8zf9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  postgres-operator-token-s8zf9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  postgres-operator-token-s8zf9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>

 kubectl describe pvc -n pgo

Name:          wso2dbcluster
Namespace:     pgo
StorageClass:  efs-sc
Status:        Bound
Volume:        wso2dbcluster-pv
Labels:        pg-cluster=wso2dbcluster
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    wso2dbcluster-64cf64d6dd-5gkvk
Events:        <none>

Name:          wso2dbcluster-pgbr-repo
Namespace:     pgo
StorageClass:  efs-sc
Status:        Bound
Volume:        wso2dbcluster-pgbr-repo-pv
Labels:        pg-cluster=wso2dbcluster
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    wso2dbcluster-backrest-shared-repo-868d58474f-bph2p
Events:        <none>

Name:          wso2dbcluster-ytye
Namespace:     pgo
StorageClass:  efs-sc
Status:        Bound
Volume:        wso2dbcluster-ytye-pv
Labels:        pg-cluster=wso2dbcluster
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    wso2dbcluster-ytye-5bbb44c945-2p7sz
Events:        <none>

**Comment by jkatz** [comment]
You can get the superuser password by running the [`pgo show user`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_show_user/) command with the `--show-system-accounts` flag. The superuser password will be under the `postgres` entry.

You can also extract that value from the associated Secret that is deployed alongside the cluster.

If you want to set the superuser password yourself, you can use the `--password-superuser` flag when running `pgo create cluster`

Note that to log in as a superuser, you have to connect to the database with the primary Service that's available, or through the Pod directly, or while exec'd into the Pod. You cannot log in via the pgBouncer Deployment.

**Comment by vg02111989** [comment]
Thanks a lot Jonathan for your response

I had already setted the superuser(postgres) password while creating the cluster as you have mentioned also
the sample command what I had used is :
pgo create cluster dbcluster --replica-count=1 --password-superuser=postgres --password-replication=postgres --password=dbuser

After that I tried to login as super user using the clusterIp of the primary instance, something like this 

pgo test dbcluster

cluster : dbcluster
        Services
                primary (172.20.130.186:5432): UP
                replica (172.20.195.73:5432): UP
        Instances
                primary (dbcluster-64cf64d6dd-5gkvk): UP
                replica (dbcluster-ytye-5bbb44c945-2p7sz): UP

Now tried to connect like this :
kubectl run pgsql-postgresql-client2 --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.7.0-debian-10-r9 --env="PGPASSWORD=postgres" --command -- psql --host 172.20.130.186 -U postgres -p 5432

but received the response like :
psql: FATAL:  password authentication failed for user "postgres"

but at the same time if I will try to login using username as "dbuser" and password as "dbuser"(which i gave while creating cluster) which I had provided in portgres-operator.yaml, I am able to login

Kindly share your views and suggest any way by which I can login using postgres as super user and create multiple databases

Thanks a lot in advance

**Comment by jkatz** [comment]
I don't know how the `docker.io/bitnami/postgresql:11.7.0-debian-10-r9` container works and how it deals with logging in as a superuser. This is not something that we support.

Check that the `postgres` user has its password set correctly by verifying with the command I suggested above:

```
pgo show user --show-system-accounts dbcluster
```

You can also try connecting from the `psql` command line tool itself and verify that you can connect that way. You can use a port-forward similar to what is used for the Operator:

```
kubectl -n pgo port-forward svc/dbcluster 5432:5432

# in a different window
PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres postgres
```

**Comment by vg02111989** [comment]
Thanks Jonathan for your response

Still I am not able to connect with the way you have shared, below are the details:

pgo show user --show-system-accounts dbcluster

CLUSTER       USERNAME          PASSWORD EXPIRES  STATUS ERROR
------------- ----------------- -------- -------- ------ -----
dbcluster     adminpostgresuser          never    ok
dbcluster     crunchyadm                     never    ok
dbcluster     dbuser            dbuser      never    ok
dbcluster     postgres          postgres  never    ok
dbcluster     primaryuser       postgres never    ok

kubectl -n pgo port-forward svc/dbcluster 5432:5432
Forwarding from 127.0.0.1:5432 -> 5432
Forwarding from [::1]:5432 -> 5432

PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres postgres
psql: FATAL:  password authentication failed for user "postgres"

but still if I will give user as "dbuser", than I am able to login

PGPASSWORD=dbuser psql -h localhost -p 5432 -U dbuser postgres
psql (10.4, server 12.4)
WARNING: psql major version 10, server major version 12.
         Some psql features might not work.
Type "help" for help.

postgres=>

Kindly have a look and share your comments why I am not able to login as postgres user

**Comment by vg02111989** [comment]
Hey Jonathan,

If I am not able to login via postgres super-user than can you suggest some best ways to create multiple databases in the same instance of postgres and to create schemas in those databases using .SQL files

Thanks a lot in advance

**Comment by jkatz** [comment]
It sounds like you either have the incorrect password for the `postgres` or some other process that you are allowing to access your database changed the password. You can explicitly updated the password of the postgres user using the [`pgo update user`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_update_user/) command:

`pgo update user --username=postgres --password=postgres` (though I don't recommend this password).

From there you can log in as the superuser.

**Comment by vg02111989** [comment]
Hi Jonathan

When I fire the command as  :  pgo show user --show-system-accounts dbcluster

I will get the response as:
CLUSTER   USERNAME   PASSWORD  EXPIRES STATUS ERROR

dbcluster    postgres      postgres         never      ok
dbcluster    dbuser         dbuser           never       ok

that shows the password of postgres user is 'postgres' only and no other process is running who have access to my cluster as I am doing the fresh installation.
Also as I mentioned, I am able to login as dbuser but for postgres user still its same error:-> _psql: FATAL: password authentication failed for user "postgres"_

Also when I tried to login inside pod and using kubectl exec than I am able to login as postgres user that shows the password for superuser is 'postgres' only.

Not able to understand why I am getting issue when trying to login from outside.
Also as you had suggested, previously I was using some bitnami image, but now I had installed postgres client only in my master node for accessing db, but still the issue persists.

**Comment by jkatz** [comment]
The password is being loaded from the Secret. As mentioned in the [previous reply](https://github.com/CrunchyData/postgres-operator/issues/1868#issuecomment-690355495) your password may have changed independently. If someone updates the password in PostgreSQL itself, it will not be propagated to the Kubernetes Secret. Additionally, as passwords are one-way hashed in PostgreSQL, the Operator is unable to introspect any changes to passwords.

So as suggested, you should update the password with the `pgo update user` command as displayed above.

With the case of being able to log in from inside the Pod itself, you are using [peer authentication](https://www.postgresql.org/docs/current/auth-peer.html) which does not require a password.

**Comment by vg02111989** [comment]
Thanks Jonathan

I had created a new cluster and without supplying password as --password-superuser and retrieved the password using command : _pgo show user --show-system-accounts db2cluster_

and with this password, I am able to login now with postgres user

The issue should be what you had mentioned, I had set the password while creating cluster and it might not propagated to kubernetes secrets.

Just one more query with respect to updating the password:
as you had mentioned command for updating the password as :  _pgo update user --username=postgres --password=postgres123 --selector=name=dbcluster_
I am getting error like _Error: postgres is a system account and cannot be used_

Can you suggest the way to change the password of postgres superuser as its considering as system account

Thanks a lot in advace

**Comment by vg02111989** [comment]
One more query I have, if you can clarify than it will of great help

While creating cluster, I am giving replica-count=1 as I need to create Active/Standby instances of postgres
Now, for assigning storage, I need to get the replica pod name which will be setting some randon string after cluster name for example :  _dbcluster-scvf-_
Will it be possible to label this name so we know what replica name cluster will be creating and accordingly we can create the persistent volume to attach with it

Thanks a lot in advance

**Comment by webchi** [comment]
Looks like same issue. Can connect by application which is into the cluster but can't connect to the forwarded port on localhost
```
❯ pgo show user --all --show-system-accounts

CLUSTER                       USERNAME    PASSWORD             EXPIRES STATUS ERROR 
----------------------------- ----------- -------------------- ------- ------ -----
main-234-review-k8s-pgcluster postgres    postgres*            never   ok           
main-234-review-k8s-pgcluster primaryuser Moresecurepassword*  never   ok           
main-234-review-k8s-pgcluster user        Supersecurepassword* never   ok           
❯ PGPASSWORD=Supersecurepassword* psql -h localhost -p 5432 -U user pgcluster
psql: FATAL:  password authentication failed for user "user"
FATAL:  password authentication failed for user "user"
❯ PGPASSWORD=postgres* psql -h localhost -p 5432 -U postgres postgres
psql: FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"
```
