### ISSUE TITLE
What would be the max limit a postgres operator POD can support?

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#1872]
**What is the motivation or use case for the change? **

Whether the operator POD can support ~8TB DB? Any issues we can see on the POD/Node/Cluster/Operator for supporting such a huge PVC size?
Is 8TB PVC allocated is sequential or distributed?
How much max PVC size for one pod is recommended?

**What is the expected behavior?**
To have a postgres operator with 8TB DB with high availability

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
A lot of factors go into this. I know of many multi-terabyte databases that are being managed by the PostgreSQL Operator, including ones that far exceed 8TB.

However, these limitations depend on a lot of factors: your Kubernetes environment and the amount of resources it has, the storage classes available in your environment, the type of physical storage that is interfacing with it, the design of your schema, your data access patterns, how your PostgreSQL clusters are tuned, how your pgBackRest repository is tuned etc. I know of some workloads that use the [tablespace](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/tablespaces/) feature to spread data across multiple PVCs.

(I'll note this is not limited to just Kubernetes, but can extend to VMs and bare metal).

If you are looking at just storage, you will need to research your storage class and storage provider to understand its benefits and limitations. And as with any application, you will need to do your own research and testing to determine what makes the most sense for you.
