### ISSUE TITLE
 How to set it  Global imagePullPolicy.

### ISSUE THREAD

**Issue by weiya1990** [CrunchyData/postgres-operator#1878]
Hello：
    How to set the rule of imagePullPolicy with Always  when creating pg cluster , because Docker image is modified, but it is still the previous tag.

**Comment by jkatz** [comment]
You can modify the `cluster-deployment.json` template and set the `imagePullPolicy` in that. The default template file looks like this:

[https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/cluster-deployment.json](https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/cluster-deployment.json)

**Comment by weiya1990** [comment]
Thank you very much. It has been modified
