### ISSUE TITLE
Horizontal auto-scaling of postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#1882]
So far we can create a postgres cluster with 1 primary db instance and X number of replica instances.
could we configure the cluster to horizontally **autoscale** the number of primary or replica instances based on a criteria like cpu/memory utilization or something else?
Is there any **autoscale** feature for scaling cpu/memory upto its limits.

**Please tell us about your environment:**
Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
No.
