### ISSUE TITLE
Want to change DEFAULT_POOL_SIZE in pgbouncer.ini

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#1883]
**What is the current behavior?**
We want to change the default_pool_size in pgbouncer.ini but not able to edit it as its readonly file. when tried to use EXPORT command we could see that the commmand works (export default_pool_size=100) but do not know how can I test it. The SET is not working for me. Kindly let me know how can i change the dafult_pool_size
**What is the expected behavior?**
DEFAULT_POOL_SIZE=20 to be changed to DEFAULT_POOL_SIZE=100 (100 is taken as example)
**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
You need to modify the `pgbouncer.ini` entry in the Secret and then reload the pgBouncer Pods.

However, thanks to #1880 this will soon be in a configuration map.
