### ISSUE TITLE
Trying CrunchyData postgres-operator with NFS storage.

### ISSUE THREAD

**Issue by rg2609** [CrunchyData/postgres-operator#1884]
**Describe the bug**
I am trying out the CrunchyData postgres-operator(Helm) with [NFS](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) Helm chart. And I am unable to create the Cluster with NFS. The following configuration is performed:

1. Installed NFS helm chart [Repo](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner)
`helm install nfs-abc stable/nfs-server-provisioner`

2. Set the postgres storage values [Doc](https://crunchydata.github.io/postgres-operator/stable/installation/configuration/#_storage_configuration)
```
backrest_storage: 'nfsstorage'
backup_storage: 'nfsstorage'
primary_storage: 'nfsstorage'
replica_storage: 'nfsstorage'
```
3. Set the storage configuration [Doc](https://access.crunchydata.com/documentation/crunchy-postgres-containers/2.3.0/installation-guide/storage-configuration/)
```
export CCP_SECURITY_CONTEXT='"supplementalGroups": [65534]'
export CCP_STORAGE_PATH=/nfsfileshare
export CCP_NFS_IP=data-nfs-abc-nfs-server-provisioner-0.default.svc.cluster.local
export CCP_STORAGE_MODE=ReadWriteMany
export CCP_STORAGE_CAPACITY=400M
```
4. Created PGO cluster
`pgo create cluster -n pgo hippo --pvc-size='2Gi'`

Am I missing something that too is configured or doing something wrong? my purpose is to use NFS as postgres storage. Any help will be appreciated. 
**Please tell us about your environment:**

* Operating System: Debian GNU/Linux 10 (buster)
* Where is this running ( Local , Cloud Provider): GCE
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos7-12.4-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.18.8

**Comment by jkatz** [comment]
Without logs of what's happening during cluster provisioning, it's very difficult to provide guidance on what is going on. Having the full configuration of your file would also help.

That being said, I work with NFS as my test environment (though without a provisioner) and I know of production NFS deployments with the PostgreSQL Operator, so my hunch is this is configuration or environmental related.

**Comment by rg2609** [comment]
Env Variables:
```
export CCP_SECURITY_CONTEXT='"supplementalGroups": [65534]'
export CCP_STORAGE_PATH=/nfsfileshare
export CCP_NFS_IP=data-nfs-dravoka-nfs-server-provisioner-0.default.svc.cluster.local
export CCP_STORAGE_MODE=ReadWriteMany
export CCP_STORAGE_CAPACITY=400M
```
Pgo command:
```
pgo create cluster -n pgo dravoka --storage-config='nfsstorage' --pgbackrest-storage-config='nfsstorage' --pvc-size='2Gi'
```

PVC describe:
```
kubectl describe -n pgo pvc dravoka
Name:          dravoka
Namespace:     pgo
StorageClass:  standard
Status:        Pending
Volume:
Labels:        pg-cluster=dravoka
               pgremove=true
               vendor=crunchydata
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason              Age                    From                         Message
  ----     ------              ----                   ----                         -------
  Warning  ProvisioningFailed  112s (x10 over 7m45s)  persistentvolume-controller  Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported
```
Pod Describe:
```
kubectl describe -n pgo pod dravoka-backrest-shared-repo-9fdd77886-j2mjv
Name:           dravoka-backrest-shared-repo-9fdd77886-j2mjv
Namespace:      pgo
Priority:       0
Node:           <none>
Labels:         name=dravoka-backrest-shared-repo
                pg-cluster=dravoka
                pg-pod-anti-affinity=preferred
                pgo-backrest-repo=true
                pod-template-hash=9fdd77886
                service-name=dravoka-backrest-shared-repo
                vendor=crunchydata
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/dravoka-backrest-shared-repo-9fdd77886
Containers:
  database:
    Image:      registry.developers.crunchydata.com/crunchydata/pgo-backrest-repo:centos7-4.4.1
    Port:       2022/TCP
    Host Port:  0/TCP
    Requests:
      memory:  48Mi
    Environment:
      PGBACKREST_STANZA:           db
      SSHD_PORT:                   2022
      PGBACKREST_DB_PATH:          /pgdata/dravoka
      PGBACKREST_REPO_PATH:        /backrestrepo/dravoka-backrest-shared-repo
      PGBACKREST_PG1_PORT:         5432
      PGBACKREST_LOG_PATH:         /tmp
      PGBACKREST_PG1_SOCKET_PATH:  /tmp
      PGBACKREST_DB_HOST:          dravoka
    Mounts:
      /backrestrepo from backrestrepo (rw)
      /sshd from sshd (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  sshd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dravoka-backrest-repo-config
    Optional:    false
  backrestrepo:
    Type:        PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:   dravoka-pgbr-repo
    ReadOnly:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  76s (x7 over 9m58s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 2 times)

```

**Comment by rg2609** [comment]
> export CCP_NFS_IP=data-nfs-dravoka-nfs-server-provisioner-0.default.svc.cluster.local

This is the [NFS Helm](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) chart and its working with other applications as storage. And there is a storageClass called `nfs` which is to be used in `PVC`. I am unable to find a way to give  `pvc` a storageClass as `nfs`

**Comment by jkatz** [comment]
The error is right here:

```Warning  ProvisioningFailed  112s (x10 over 7m45s)  persistentvolume-controller  Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported```

You need to update your [`AccessMode`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) for provisioning your Persistent Volumes Claim to be `ReadWriteOnce`, i.e., set the PostgreSQL Operator configuration `access_mode` for the `PersistentVolumeClaim` to be `ReadWriteOnce`.

**Comment by rg2609** [comment]
I know the error with creating with the PVC. Values for `nfsstorage` as in helm values and the access_mode is `ReadWriteMany`
```
      storage3_name: "nfsstorage"
      storage3_access_mode: "ReadWriteMany"
      storage3_size: "1G"
      storage3_type: "create"
      storage3_supplemental_groups: "65534"
```
I wanted to know how to use the `nfs` storage.

**Comment by jkatz** [comment]
Change:

`storage3_access_mode: "ReadWriteMany"`

to

storage3_access_mode: "ReadWriteOnce"

Restart (or if you want, redeploy) the PostgreSQL Operator. Future PostgreSQL clusters will be deployed with the access mode set to `ReadWriteOnce`.

**Comment by rg2609** [comment]
> storage3_access_mode: "ReadWriteOnce"
If I did these changes in `values.yaml`, that ok but how NFS StorageClass `nfs` will be used.

> kubectl describe -n pgo pvc dravoka
> Name:          dravoka
> Namespace:     pgo
> StorageClass:  standard

This PVC is taking the default `StorageClass` i.e. `standard`

**Comment by rg2609** [comment]
we found the issue in your **v4.4.1** release tag, I am trying to installing helm chart in v4.4.1 by:
```
helm install pgo -n pgo .  --set storage3_type="dynamic" --set storage3_class="nfs" --set pgo_client_container_install="true"
```
but this is not setting the `storage_class` as `nfs` for `nfsstorage`.
`pgo show config -n pgo`
```
nfsstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: "nfs"
    StorageType: dynamic
    SupplementalGroups: "65534"
```

Then I tried same helm install in **master** branch then the `storage_class` getting value as `nfs`
`pgo show config -n pgo`
```
nfsstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: dynamic
    SupplementalGroups: "65534"
```

**Comment by jkatz** [comment]
@rg2609 Thanks for that and your patience with the issue. This is something we need to address in the codebase and will work on a fix.

**Comment by jkatz** [comment]
The configuration is now backpatched to the older branch (`REL_4_4`). Thanks!

**Comment by rg2609** [comment]
Welcome :smile: @jkatz
