### ISSUE TITLE
Restore data from PVC

### ISSUE THREAD

**Issue by yattagit** [CrunchyData/postgres-operator#1885]
Hi,
I'm using PGO 4.4.0 version and trying to backup Postgre DB cluster and restore data again.
I'm using Azure WS environment.

**1-** If i run the command below, command is creating "testpvc" pvc successfully.
`pgo backup hacluster --backup-type="pgdump" --pvc-name="testpvc"`

But I can't able to restore data from this PVC. 
I checked whole Crunchy Data pages and tried lots of variation of commands but still same. 

Which command should I use?

**2-** If is use the command below,  it's not creating any PVC.
`pgo backup hacluster --backup-opts="--type=full"`

Where is the backup data stored? How can I access it? And which command should I use to restore? The command below is only indicate time, is this the only option`?

`pgo restore hacluster --pitr-target="2019-12-31 11:59:59.999999+00"`

And what is the difference this parameter's and the first one? First one is creating a PVC and store backup data in there I guess? And the second one is not creating any PVC.

Thanks!

**Comment by jkatz** [comment]
The command you are using is for taking logical dumps with `pg_dump`. Typically, "restores" with this method are for loading individual tables moving segments of data between PostgreSQL clusters, or migrating between PostgreSQL major versions.

You can follow the procedure listed here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#logical-backups-pg-dump-pg-dumpall](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#logical-backups-pg-dump-pg-dumpall)

or review the full command reference:

[https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_restore/](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_restore/).

If you are looking to restore a database, you should be using the physical backup system using the Operator's integration with pgBackRest. There are step-by-step instructions for how to restore:

[https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#restore-a-cluster](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#restore-a-cluster)

There are two ways to do it, either by restoring in place via `pgo restore`, or by creating a new cluster using `pgo create cluster --restore-from`.

As I mentioned in #1881, the procedures are well-documented. You may need to add additional flags based upon how you set up your pgBackRest environment, though the documentation does include suggestions around that, and you can find the full list of flags available in the `pgo client` reference.

If you believe there can be improvements to the documentation, suggestions and patches are of course welcome.

**Comment by yattagit** [comment]
Just updated my question.
