### ISSUE TITLE
Can't connect to default "postgres" db using pgbouncer

### ISSUE THREAD

**Issue by lgarcia11** [CrunchyData/postgres-operator#1887]
I can connect successfully using `psql -p 5432 -U testuser -d postgres` directly but with pgbouncer and only when connecting to the default "postgres" db, I get the error **psql: error: could not connect to server: Connection refused**
I'm using pgo version 4.4.1

**Comment by jkatz** [comment]
From the Operator's perspective the "default" database is the one that is your cluster name (e.g. `hippo`) or whatever you provide as part of the `pgo create cluster --database` flag.

I've typically treated the `postgres` database as an administrative database and avoid using it for application purposes per best practices. Perhaps in trying to push best practices my view of the world is too narrow. The patch for adjusting this is trivial and I will propose something.

That all said, we do need to better document the pgBouncer support. That is on my todo.

If you need to enable it presently in, you can run the following SQL as a superuser in the `postgres` database:

[https://raw.githubusercontent.com/CrunchyData/crunchy-containers/master/bin/postgres-ha/sql/pgbouncer/pgbouncer-install.sql](https://raw.githubusercontent.com/CrunchyData/crunchy-containers/master/bin/postgres-ha/sql/pgbouncer/pgbouncer-install.sql)

**Comment by jkatz** [comment]
This will be a part of the 4.5.0 release.

Given it's a behavior change, this won't be backpatched.
