### ISSUE TITLE
Getting EOF issue when creating cluster

### ISSUE THREAD

**Issue by ipochi** [CrunchyData/postgres-operator#189]
Getting the below error when creating with or without --pgpool option

`pgo create cluster testcluster --pgpool`
`FATA[0000] Do: Post https://<postgres-operator_cluster_ip>:8443/clusters: EOF `

`pgo version`
`pgo client version 2.6`
`apiserver version 2.6`

**Comment by jmccormick2001** [comment]
can you attach the log output from the postgres-operator pod?  for both the apiserver and operator containers.  I'll take a look.

**Comment by ipochi** [comment]
@jmccormick2001  i did create the custom pgo config map as it was complaining in the logs, still getting EOF issue

**Comment by jmccormick2001** [comment]
thanks, can you send me your pgo.yaml file?

**Comment by ipochi** [comment]
@jmccormick2001 
```
Cluster:
  CCPImagePrefix:  crunchydata
  CCPImageTag:  centos7-10.3-1.8.2
  Port:  5432
  User:  testuser
  Database:  userdb
  PasswordAgeDays:  60
  PasswordLength:  8
  Strategy:  1
  Replicas:  0
PrimaryStorage: storage1
BackupStorage: storage1
ReplicaStorage: storage1
Storage:
  storage1:
    AccessMode:  ReadWriteOnce
    Size:  200M
    StorageType:  dynamic
    StorageClass:  px-sc
    Fsgroup:  26
Pgo:
  Audit: false
  Metrics: false
  LSPVCTemplate:  /config/pgo.lspvc-template.json
  LoadTemplate:  /config/pgo.load-template.json
  COImagePrefix:  crunchydata
  COImageTag:  centos7-2.6

**Comment by jmccormick2001** [comment]
the config looks right at first glance, lets try this...delete the current postgres-operator pod, or redeploy, then try 'pgo create cluster something' again, get the full apiserver and operator logs, post those here...I'm looking for log messages at the very top of the logs.

**Comment by jmccormick2001** [comment]
also, after you run the 'create', run 'kubectl get pvc' and lets see the status of the PVC that would have been created.

**Comment by jmccormick2001** [comment]
let me know if you are still having issues, if not I'll close this one out.
