### ISSUE TITLE
Images tags v4.5.0-beta.1 not found.

### ISSUE THREAD

**Issue by bitsdominicada** [CrunchyData/postgres-operator#1890]
Hi, i'm testing from master branch via ansible installer and got error from images container they had references to
tags  v4.5.0-beta.1 but not found it. Thanks in advance.

**Comment by jkatz** [comment]
These images have not been pushed out publicly. Please note that the release is tagged as a "pre-release."

To download the publicly available images, please see [https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator).

If you still intend to use the Ansible installer against the available images (I would recommend you use the `pgo-deployer` container as it just encapsulates the Ansible installer), check out the `REL_4_4` branch.

**Comment by bitsdominicada** [comment]
Thanks!

Enviado desde mi iPhone
