### ISSUE TITLE
Where backup files are stored?

### ISSUE THREAD

**Issue by yattagit** [CrunchyData/postgres-operator#1895]
Hi,
I'm using PGO 4.4.0 version and trying to backup Postgre DB cluster and restore data again.
I'm using Azure WS environment.

When I run the command below, backups are listing like below;

I wonder where these backups storing? How can I reach them?

```
bash-4.2$ pgo show backup hacluster
cluster: hacluster
storage type: local
stanza: db
    status: ok
    cipher: none
    db (current)
        wal archive min/max (12-1)

        full backup: 20200915-155556F
            timestamp start/stop: 2020-09-15 15:55:56 +0000 UTC / 2020-09-15 15:56:24 +0000 UTC
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 31.1MiB, backup size: 31.1MiB
            repository size: 3.7MiB, repository backup size: 3.7MiB
            backup reference list:

        incr backup: 20200915-155556F_20200915-155957I
            timestamp start/stop: 2020-09-15 15:59:57 +0000 UTC / 2020-09-15 16:00:03 +0000 UTC
            wal start/stop: 000000010000000000000005 / 000000010000000000000005
            database size: 31.1MiB, backup size: 2.8MiB
            repository size: 3.7MiB, repository backup size: 322.2KiB
            backup reference list: 20200915-155556F

        full backup: 20200915-161628F
            timestamp start/stop: 2020-09-15 16:16:28 +0000 UTC / 2020-09-15 16:16:58 +0000 UTC
            wal start/stop: 00000001000000000000000A / 00000001000000000000000A
            database size: 31.1MiB, backup size: 31.1MiB
            repository size: 3.7MiB, repository backup size: 3.7MiB
            backup reference list:

bash-4.2$
```

Thanks!

**Comment by jkatz** [comment]
> I wonder where these backups storing? How can I reach them?

As indicated in the diagram in the documentation, the pgBackRest repository is attached to a Pod. The Pod is managed by a Deployment which, in your specific case, is called `hacluster-backrest-shared-repo` and has, in your specific case, a PVC called `hacluster-pgbr-repo`. You should rarely, if ever, need to manipulate the PVC directly -- the PostgreSQL Operator can handle the management of your backups via the pgBackRest command.

> I'm using PGO 4.4.0 version and trying to backup Postgre DB cluster and restore data again.

Most of this is covered both in the reply I gave you [here](https://github.com/CrunchyData/postgres-operator/issues/1889#issuecomment-693401769) and in the [documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/).

I again recommend reading through the documentation to understand how the various functionality of the PostgreSQL Operator works and leveraging [`kubectl`'s introspection functions](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-finding-resources) to play around with the different objects that are deployed.
