### ISSUE TITLE
Where pgdump backups are stored?

### ISSUE THREAD

**Issue by yattagit** [CrunchyData/postgres-operator#1896]
Hi,
I'm using PGO 4.4.0 version and trying to backup Postgre DB cluster and restore data again.
I'm using Azure WS environment.

When I run "`pgo backup hacluster --backup-type="pgdump" --pvc-name="testpvc3`" command, it says backups task created succesfully.

But I don't see this backups if I check with "`pgo show backup hacluster`" command. There is nothing. 

1. How can I see/list this backups? 
2. How can I restore data from it?

Regards.

**Comment by jkatz** [comment]
> 1. How can I see/list this backups?

[https://github.com/CrunchyData/postgres-operator/issues/1889#issuecomment-692982856](https://github.com/CrunchyData/postgres-operator/issues/1889#issuecomment-692982856)

> 2. How can I restore data from it?

[https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#restore-from-a-logical-backup](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#restore-from-a-logical-backup)
