### ISSUE TITLE
How to configure PostgreSQL Monitor to support SSL connection

### ISSUE THREAD

**Issue by shuhanfan** [CrunchyData/postgres-operator#1902]
**Describe the bug**
I'm trying installing PostgreSQL Monitoring by kubectl config files(ref:installers/metrics/kubectl/postgres-operator-metrics.yml). But when I set `tlsOnly=true` in pgCluster, the crunchy-collect couldn't work. The error message is:

```
could not connect to server: FATAL:  no pg_hba.conf entry for host "127.0.0.1", user "ccp_monitoring", database "postgres", SSL off
```

The pg_hba.conf  is:
```
# Do not edit this file manually!
# It will be overwritten by Patroni!
local all postgres peer
local all crunchyadm peer
hostssl replication primaryuser 0.0.0.0/0 cert
hostssl all primaryuser 0.0.0.0/0 reject
hostssl all all 0.0.0.0/0 md5
```

If I set `tlsOnly=false`, everything went well.
The pg_hba.conf is:
```
# Do not edit this file manually!
# It will be overwritten by Patroni!
local all postgres peer
local all crunchyadm peer
hostssl replication primaryuser 0.0.0.0/0 cert
hostssl all primaryuser 0.0.0.0/0 reject
hostssl all all 0.0.0.0/0 md5
host replication primaryuser 0.0.0.0/0 md5
host all primaryuser 0.0.0.0/0 reject
host all all 0.0.0.0/0 md5
```

So how could I configure to make crunchy-collect in Monitoring support SSL connection?

**Expected behavior**
I can access the 9187 port of postgres service, which is exposed for PostgreSQL metrics collect.

**Please tell us about your environment:**

* Operating System:
* Where is this running : Clouds
* Storage being used : gce
* Container Image Tag: centos7-4.4.1
* Platform (Docker, Kubernetes, OpenShift): Kubernetes

**Comment by jkatz** [comment]
[Monitoring has changed for the upcoming v4.5.0 release](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0-beta.1) and I would recommend trying with that.

If you cannot wait for that, the monitoring user is connecting over TCP but is not going out over an external network, i.e. it's over the internal network interface. It is fine for it to not connect over TLS. You can allow for TLS Only to be true and just add a rule for the user:

```
host all ccp_monitoring 127.0.0.1 md5
```

or modify the the `EXPORTER_PG_PARAMS` environmental variable in the collect container configuration, i.e.

```
EXPORTER_PG_PARAMS:      sslmode=require
```

or higher.

**Comment by jkatz** [comment]
I will note that I can replicate this issue in the `4.5.0-beta.1`.

I am going to propose a change that automatically sets `sslmode=require` if `--tls-only` is enabled.

**Comment by jkatz** [comment]
@shuhanfan I've made a programmatic change so TLS-only clusters will work with the metrics collection in the 4.5 release.

As it's a nontrivial change to one of our templates, I'm hesitant to backpatch this to 4.4. If we had not made significant changes to the monitoring functionality, I would err on the side of backpatching, but as a) we did make said major chagnes and b) 4.5 will be out in the next few weeks, I am just going to leave this in the upstream.

That said, the workarounds described in [https://github.com/CrunchyData/postgres-operator/issues/1902#issuecomment-696110628](https://github.com/CrunchyData/postgres-operator/issues/1902#issuecomment-696110628) would suffice in 4.4 and earlier. I do recommend that you wait for the 4.5 support in monitoring as it is [greatly improved](https://crunchydata.github.io/postgres-operator/latest/architecture/monitoring/).

Thanks for reporting!

**Comment by shuhanfan** [comment]
> @shuhanfan I've made a programmatic change so TLS-only clusters will work with the metrics collection in the 4.5 release.
> 
> As it's a nontrivial change to one of our templates, I'm hesitant to backpatch this to 4.4. If we had not made significant changes to the monitoring functionality, I would err on the side of backpatching, but as a) we did make said major chagnes and b) 4.5 will be out in the next few weeks, I am just going to leave this in the upstream.
> 
> That said, the workarounds described in [#1902 (comment)](https://github.com/CrunchyData/postgres-operator/issues/1902#issuecomment-696110628) would suffice in 4.4 and earlier. I do recommend that you wait for the 4.5 support in monitoring as it is [greatly improved](https://crunchydata.github.io/postgres-operator/latest/architecture/monitoring/).
> 
> Thanks for reporting!

Thanks very much! I'll wait for the 4.5 👍
