### ISSUE TITLE
PSQL Exception - Too many clients

### ISSUE THREAD

**Issue by vg02111989** [CrunchyData/postgres-operator#1905]
Hi,

I have deployed Active-Standyby Postgres cluster using cruncy data in k8s.
I am running 2 Active-Active instances of my couple of applications and while bringing up, its giving me exceptions as 👍 

Caused by: org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:613) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:161) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.Driver.makeConnection(Driver.java:465) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.Driver.connect(Driver.java:264) ~[postgresql-42.2.16.jar:42.2.16]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:319) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:739) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:671) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
        at org.wso2.carbon.identity.core.persistence.JDBCPersistenceManager.getDBConnection(JDBCPersistenceManager.java:147) ~[org.wso2.carbon.identity.core_5.17.5.jar:?]

I have checked the max_connections of the DB and its 100
Not sure why this is happening.

Please suggest what can be done, may be implementing some connection pooling, if Yes than how I can implement so that all my applications should be able to get the connections from postgres

Thanks a lot in advance

**Comment by jkatz** [comment]
There are several ways to remediate this problem:

1. [Increase the value of `max_connections`](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/)
1. [Set up pgBouncer](https://access.crunchydata.com/documentation/postgres-operator/4.4.1/pgo-client/common-tasks/#connection-pooling-via-pgbouncer)
1. Set up connection pooling from your application code.

However, I would recommend checking `pg_stat_activity` to see what is connecting to your database to try and understand the source of the issue and why there are many connections being made.

**Comment by vg02111989** [comment]
Hi Jonathan

Apologies for the late reply as I moved to concentrate on some other stuffs.
I tried to setup pgBouncer as you had suggested, also pgBouncer server also came up:

 pgo test dbcluster

cluster : dbcluster
        Services
                primary (10.233.50.26:5432): UP
                pgbouncer (10.233.0.121:5432): UP
                replica (10.233.49.239:5432): UP
        Instances
                primary (dbcluster-5f857644bc-qhlcs): UP
                replica (dbcluster-kozy-84fb9fb6b6-jrqtt): UP

but when I am trying to connect psql client via pgBouncer service, I am not able to connect

I had followed the below link also:

https://www.crunchydata.com/developers/download-postgres/containers/pgbouncer

but here its asking to give some env file, but using pgo client, there is no option to give this
Also after following the steps to create roles and permission after going inside postgres, still I am getting :

PGPASSWORD=bounceadmin psql -h 10.233.0.121 -p 5432 -U postgres postgres
psql: ERROR:  pgbouncer cannot connect to server

**Comment by jkatz** [comment]
What version of the Postgres Operator are you using?

**Comment by vg02111989** [comment]
Hey

i am using 4.4.1 version of crunchy data postgres operator


pgo version

pgo client version 4.4.1
pgo-apiserver version 4.4.1

**Comment by jkatz** [comment]
You cannot connect directly to the `postgres` database via pgBouncer in Operator 4.4.1. A behavior change for this was added in 4.5.0.

The full discussion is in #1887

**Comment by vg02111989** [comment]
My use case is ...I have to connect to postgres database as superuser to login after that I need to create some more databases and schema in newly created db's.
So, wanna confirm if I will use latest version of operator i.e 4.5.0 and create the postgres cluster with option as --pgbouncer, I should be able to connect to db using the service IP of pgbouncer just similar way what I am connecting with primary service IP for eg

PGPASSWORD=pgadmin@12 psql -h <**pgbouncer_service_ip**> -p 5432 -U postgres postgres
as today I am connecting like this way 
 pgadmin@12 psql -h <**primary_cluster_service_ip**> -p 5432 -U postgres postgres

after which my application can connect automatically for creating multiple db and schema's in the same postgres instance

Kindly comment if I have missed something in my understanding of using pgbouncer crunchydata postgres connection pooler

**Comment by jkatz** [comment]
I would again go back to this comment, which recommends a few things:

[https://github.com/CrunchyData/postgres-operator/issues/1905#issuecomment-696700598](https://github.com/CrunchyData/postgres-operator/issues/1905#issuecomment-696700598)

in particular, the `pg_stat_activity` comment which allows you to inspect what is connecting.

The Operator 4.5.0 release also added improvements to the monitoring system, which includes information on how many connections are being made to your database (though, it does not describe what those connections are doing; that is what `pg_stat_activity` and others help with).

Information about the 4.5.0 release is here:

[https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0)

and some blog posts about monitoring:

- [https://info.crunchydata.com/blog/setup-postgresql-monitoring-in-kubernetes](https://info.crunchydata.com/blog/setup-postgresql-monitoring-in-kubernetes)
- [https://info.crunchydata.com/blog/postgresql-monitoring-for-application-developers-dba-stats](https://info.crunchydata.com/blog/postgresql-monitoring-for-application-developers-dba-stats)

**Comment by vg02111989** [comment]
I guess i need to update only as I followed the SQL script you had added in the discussion #1887 
but I am getting the same error when I am trying to connect like this :
PGPASSWORD=pgadmin@123 psql -h <pgbouncer-_service_ip> -p 5432 -U postgres postgres

error I am getting is same -- **_psql: ERROR:  pgbouncer cannot connect to server_**

**Comment by vg02111989** [comment]
Thanks Jonathan,

I will go through those links and revert back if require more clarification:

Can you please also share how we can pass the max_connections option while creating the postgres cluster using PGO CLI, like if I want to set that max_connections value as may be 500 for specific db_cluster instance, that case, how I can specify those
