### ISSUE TITLE
DB pods - anti affinity

### ISSUE THREAD

**Issue by vg02111989** [CrunchyData/postgres-operator#1907]
Hi,

I want to create the db pods in the specific nodes of my k8s cluster, for that I used the option as --node-label to set the node selector, but by this, only primary db is creating in the specific node, other replicas are creating in different nodes which I don't want to do, I want to create all the db pods in same node.

Please suggest how I can set the pods affinity to none so it can be created on the node defined in node selector by using label --node-label

Thanks a lot in advance

**Comment by jkatz** [comment]
This is covered in the [documentation](https://access.crunchydata.com/documentation/postgres-operator/4.4.1/architecture/high-availability/#how-the-crunchy-postgresql-operator-uses-pod-anti-affinity):

> `disabled`: Pod Anti-Affinity is not used.

e.g.

`pgo create cluster hippo --replica-count=2 --pod-anti-affinity=disabled`

**Comment by vg02111989** [comment]
Thanks Jonathan for the response:

The same I had tried but it's not creating on the same node:
below is the output 

**wsoaffinitydbcluster-6d86b8b7d6-k8vqq                        1/1     Running     0          8m45s   10.233.110.82    infra-cas   <none>           <none>
wsoaffinitydbcluster-backrest-shared-repo-66cb676d49-6kzr6   1/1     Running     0          8m57s   10.233.76.173    db-2        <none>           <none>
wsoaffinitydbcluster-gvqb-8448757979-5xkxj                   1/1     Running     0          5m1s    10.233.76.176    db-2        <none>           <none>
wsoaffinitydbcluster-nkzb-5fd6cb6bd-cqh44                    1/1     Running     0          5m      10.233.80.39     db-1        <none>           <none>
wsoaffinitydbcluster-stanza-create-4lz2p                     0/1     Completed   0          5m54s   10.233.76.174    db-2        <none>           <none>**


The command I had used is :
**pgo create cluster wsoaffinitydbcluster --replica-count=2 --node-label=esmp=supported --pod-anti-affinity=disabled --password=dbuser**

where node-label as esmp is for infra-cas node

can you please share your views on the same

**Comment by vg02111989** [comment]
Hey Jonathan

As it's not working as suggested by you, request you to not close this issue.

Thanks a lot in advance

**Comment by jkatz** [comment]
By default, the node affinity that is used is `preferred` which is defined here in the documentation:

[https://access.crunchydata.com/documentation/postgres-operator/4.4.1/architecture/high-availability/#node-affinity](https://access.crunchydata.com/documentation/postgres-operator/4.4.1/architecture/high-availability/#node-affinity)

So if Kubernetes determines that it cannot successfully determine it can schedule the Pod to the Node that you specify ,it will attempt to schedule it to a different node. This is the correctly defined behavior.

If you want to customize this, you can update the `affinity.json` template in the `pgo-config` ConfigMap. The shape of the JSON looks like this:

[https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/affinity.json](https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/affinity.json)

You can edit the `pgo-config` ConfigMap to have it set to use `required` node affinity. I happened to do exactly that yesterday to test a different scenario.

Separately, you can set the Deployment to use required node affinity.

Anyway, as preferred node affinity is the defined and documented behavior in the PostgreSQL Operator, and as the Operator does allow you to customize the node affinity behavior from the template, I am still treating this issue as resolved.
