### ISSUE TITLE
How to create a cluster with 9.6.* postgres version in operator 4.4.0

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1913]
we have tried , to build a cluster using a 9.6.* image as stated in the versions page but it seems that it's not present in your registry.. any help willbe appreaciated

pgo -n pgo create cluster zzzz --pvc-size=10Gi \
	--ccp-image-tag centos7-9.6.18-4.4.0 \
    --database test \
    --replica-count=1 \
    --pgbackrest-s3-key zzzzzzzzzzzzzzzzzzz \
    --pgbackrest-s3-key-secret zzzzzzzzzzzzzzzzzzzzzzzzzzzzz \
    --pgbackrest-storage-type local,s3

the pod for the db finally is not built because of the not found image..

**Comment by IJOL** [comment]
I did manage to earn a bit more, and i now know, that simple that containers for 10.* and 9.* are simply not built by you, i tried to see if we could bake tha image need oruselvesm but we have not managed to do it , we use ubuntu, and to prepare the nided bits is very time consuming. and we are really in hurry, we have found that one badly needed query works very slowly in 11 and 12, so we need 9.6 as base, we are in the verge of using our own custom image we used in the past with docker, we bet will solve our problems now, but we much prefer to use operator, could we ask if you can build and upload to the the crunchy register images for 9.* and 10.*, it would be awesome..

**Comment by IJOL** [comment]
we tried 11 too, changig the config, but the query yet run slowly..

**Comment by jkatz** [comment]
We do make builds for older, supported PostgreSQL versions available in our customer portal.

I am curious about the slow query piece though -- PostgreSQL 11 and 12 (and [now 13](https://www.postgresql.org/about/news/2077/)!) have introduced a lot of performance improvements.

Is the slow query using [JIT compilation](https://www.postgresql.org/docs/current/jit.html)? I found in some of my tests in upgrading from an older versions of PostgreSQL to 11+, I would have queries slow down as they were JIT'd when they shouldn't have been. You can set `jit = off` in that case, which you can do on a per-session basis or just do it in the configuration.

Beyond my troubleshooting without much information, are you sure the indexes were properly rebuilt, `ANALYZE` was run, etc? Does `EXPLAIN ANALYZE` between the two different versions reveal anything intriguing?

**Comment by IJOL** [comment]
Dont worry as ever it was our fault, a bad restore, everything seems
running smoothtly now, many thanks and sorry for all the noises,




Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by jkatz** [comment]
@IJOL Glad to hear it! I think you will like [PostgreSQL 12](https://info.crunchydata.com/blog/just-upgrade-how-postgresql-12-can-improve-your-performance) 😄
