### ISSUE TITLE
All external WAL PVC gets terminated when replica is destroyed

### ISSUE THREAD

**Issue by dakine1111** [CrunchyData/postgres-operator#1915]
**Describe the bug**
If a cluster is scaled down all WAL PVCs will be terminated

**To Reproduce**
1. Create a cluster with >= 1 replica
2. Scaledown the cluster.
3. All *-wal PVCs will be terminated

**Expected behavior**
Only the WAL PVC of the deleted replica gets terminated.

**Please tell us about your environment:**

* Container Image Tag: centos7-12.4-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.5.11

**Comment by jkatz** [comment]
What command did you use to scaledown the cluster?

**Comment by dakine1111** [comment]
pgo scaledown debug-postgresql01 -n shared-debug --target debug-postgresql01-lcfm

**Comment by jkatz** [comment]
@dakine1111 Thanks for reporting, we've successfully reproduced the issue and will work on a bug fix.

**Comment by jkatz** [comment]
A fix is applied to all supported versions. Thanks for reporting!
