### ISSUE TITLE
Command for backup, restore tablespace in postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#1916]
** Which example are you working with? **

We are newly using the tablespace to spread the data in our operator. Can you please let me know if there is any command or flags that can be used to backup, restore for our postgres operator (in pogclientcommnad).

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
This is covered in great detail in multiple sections of the documentation:

- [Disaster Recovery](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/)
- [Backups & Restores](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#disaster-recovery-backups-restores)

Tablespaces are treated as [part of the entire cluster](https://www.postgresql.org/docs/current/manage-ag-tablespaces.html). They are included in the backups and restores by [pgBackRest](https://pgbackrest.org/#features/tablespace-link-support), which is what the PostgreSQL Operator uses to manage backups/restores (I believe in part I covered in [https://github.com/CrunchyData/postgres-operator/issues/1908#issuecomment-696709657](https://github.com/CrunchyData/postgres-operator/issues/1908#issuecomment-696709657) :smile:)

Looking at your version number, I do recommend moving up to either 4.4.1 or 4.3.3, both of which have fixes and improvements to the cluster restore process.

**Comment by kseswar** [comment]
Thank you very much :)

**Comment by jkatz** [comment]
You're welcome!
