### ISSUE TITLE
Add ability to delete backups created using pgo backup command

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#192]
pgo backups are created in a backup pvc and cannot be accessed directly to manage backups.
Need the ability to delete backups from backup pvc to implement retention policies.

**Comment by xenophenes** [comment]
This functionality has been implemented with the `delete backup` command and this issue should be good to close, @jmccormick2001. @pmereddy1, if you could just confirm that the following functionality is what you were looking for?

```
[pgo1: ~/odev/src/github.com/crunchydata/postgres-operator] kubectl get pgbackups
NAME      AGE
example   7m
[pgo1: ~/odev/src/github.com/crunchydata/postgres-operator] pgo delete backup example
WARNING: Are you sure? (yes/no): yes
Deleted backup example
[pgo1: ~/odev/src/github.com/crunchydata/postgres-operator] kubectl get pgbackups
No resources found.
```

**Comment by jmccormick2001** [comment]
moved to clubhouse.
