### ISSUE TITLE
Supported Platforms

### ISSUE THREAD

**Issue by pengbo0328** [CrunchyData/postgres-operator#1921]
According to the documentation [Supported Platforms](https://access.crunchydata.com/documentation/postgres-operator/latest/#supported-platforms), the Crunchy PostgreSQL Operator is tested on the following Platforms:

* Kubernetes 1.13+
* OpenShift 3.11+
* Google Kubernetes Engine (GKE), including Anthos
* VMware Enterprise PKS 1.3+

Does Crunchy PostgreSQL Operator support for Amazon EKS?
I have installed Crunchy PostgreSQL Operator on Amazon EKS, and it seems working fine.

**Comment by jkatz** [comment]
Hi @pengbo0328,

Yes, we do support Amazon EKS, we have a few customers running the Operator on that. I should ensure it's added to the list :smile:

Thanks!

**Comment by jkatz** [comment]
@pengbo0328 Thanks for the report, I have updated the documentation.

**Comment by OmarEltamasehy** [comment]
Google Kubernetes Engine (GKE), including Anthos,

Appreciate your support as I tried to configure Crunchy postgresql operator via our GKE cluster but it give me that our cluster is not eligible so I think that Anthos is not enabled via our GKE cluster as the above so please advice if you mean that to edit my cluster settings to enable cloud-run-for-Anthos flag or what?  As Anthos is very big usage and I need to specify what needed exactly from Anthos to be configured via cluster.

**Comment by jkatz** [comment]
@OmarEltamasehy For information about Anthos, please reach out to info@crunchydata.com
