### ISSUE TITLE
 error too many connections for pgbouncer in postgres operator 

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#1923]
The changes in pgbouncer to increase connections seems to be not working!
We increased the count to 400 in pgbouncer.ini
and tried to create more than 100, specifically 120. It gives error too many connections.

We had followed the same workaround suggested by you in https://github.com/CrunchyData/postgres-operator/issues/1883 for editing the default pool size. But here we edited the max_client_conn.

Is there any maximum limit to max_client_conn ?

Am I editing the right place for increasing the db connections.
I can also see that max_db_connections=0 is unlimited. But also we are not facing connection problem.

Could you please help me in this?

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

![image](https://user-images.githubusercontent.com/50865786/94281989-f2022880-ff6c-11ea-879e-6216a70f2d9c.png)

We also checked using pgbench utility which creates required connections for querying purpose
![image](https://user-images.githubusercontent.com/50865786/94282042-00504480-ff6d-11ea-8532-e913af454182.png)

**Comment by jkatz** [comment]
You may need to try:

`pool_mode = transaction`

I can't find the exact source in the [pgBouncer](https://www.pgbouncer.org/usage.html) documentation, but I recall in a previous life having to do something similar.

**Comment by cbandy** [comment]
If you want or need to keep `pool_mode = session`, take a look at [PostgreSQL's `max_connection`](https://www.postgresql.org/docs/current/runtime-config-connection.html) parameter which can be set [in the `*-pgha-config` ConfigMap](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/).
