### ISSUE TITLE
Add CRD support to define multiple users/databases per cluster

### ISSUE THREAD

**Issue by GrandChaman** [CrunchyData/postgres-operator#1925]
**What is the motivation or use case for the feature? **
So that one can deploy the Operator without user interaction.

**Describe the solution you'd like**
Either modify the current `pgcluster` CRD to allow to define multiple users and multiples databases

or

A new CRD, that would allow to define databases and users for clusters.

**Describe any alternatives you've considered**
Currently, the alternative would be to use the `pgo` client.

**Comment by jkatz** [comment]
- What is your workflow/use case?
- What does `pgo [create|show|update|delete] user` lack that you are looking for?
- What is the preference for the Operator managing databases vs. using the `postgres` superuser account to `CREATE DATABASE`?
- How would you want sensitive information (e.g. user credentials) to be managed by a CRD?

**Comment by GrandChaman** [comment]
Hi,
 - Workflow : We use `hashicorp/terraform` to deploy our kubernetes infrastructure, to limit user interaction. Having CRD would allow us to reduce user interactions even more.
- Is `pgo` lacking ? Not at all
- We could use `terraform` to directly create databases and roles, even though, I thought it would make a nice addition to the operator.
- Sensitive information could be read from kubernetes secrets and/or `hashicorp/vault`

**Comment by jkatz** [comment]
Follow-up question: is there a reason why you cannot log in directly as the `postgres` superuser (created as part of the standard Operator workflow) and create additional users or databases?

Are you looking for the PostgreSQL users to have Secrets managed by the Operator?

**Comment by GrandChaman** [comment]
Hi,

Indeed, one could use the superuser to create the necessary roles & databases, but I was more looking for a simple solution where the operator would manage roles and their associated secrets.

The reason we would prefer using CRD to define roles & databases would be to further the interoperability of our Infrastructure-as-code codebase.

**Comment by jkatz** [comment]
Follow-up question :smile:

Would being able to interact directly with the API server that the Operator exposes be sufficient? `pgo * user` interfaces with that.

**Comment by GrandChaman** [comment]
It would do of course, it would be less practical IMO though

**Comment by jkatz** [comment]
Thanks for bearing with me while I've asked a lot of questions as I'm trying to better understand this case.

There are several issues here I am trying to balance:

- Duplicating information: PostgreSQL itself keeps a catalog of databases (pg_database) and users (pg_authid), and there is the very real potential that this could get out of sync if we're storing it in two places.
  - We inherit some of this risk by allowing for the concept of "managed users", where the user credentials are kept in a Kubernetes Secret. However, if someone logs into PostgreSQL and does `\password`, that Secret immediately becomes stale.
- Security: If we start putting user credentials in the CRD itself, well, it's not very safe :smile: Perhaps we could keep an array of Secrets, or have a Secret that contains all of the credentials we want to keep in sync. If the Operator detects that the Secret is updated, it will sync PostgreSQL...
  - ...but, what if one of the users is updated e.g. via `\password` -- do we want the password in the Secret to override it? This can quickly become messy...
- We do have `Database` available for bootstrapping the PostgreSQL cluster, and perhaps could turn that into an array. However, if that array is updated, we could allow for "inadvertent bad things to happen", e.g. dropping an entire database. (Though that is what backups are for...)

I'd lean more towards supporting the ability to manage individual databases from the CRD, though still not a huge fan of the information being in two places. You may be able to do this yourself leveraging policies: an guide for how to do something similar via CRD is present here: [https://github.com/CrunchyData/postgres-operator/issues/1928#issuecomment-700933908](https://github.com/CrunchyData/postgres-operator/issues/1928#issuecomment-700933908)

I'm more leery of having more user management in the CRD, both from the double management and the security standpoint. I'd have to think on that more or hear more use cases for it.

For the time being, you can automate user management via the API server's exposed endpoint.

**Comment by mtrmarko** [comment]
I do have some questions around this topic, so I hope what I just ran into can help add relevant information. I am fairly new to Kubernetes and started experimenting building a cluster at home and at work. One of the components I am looking to add to the cluster is Harbor docker image and helm chart registry. Harbor comes with a helm chart that allows you to create a Postgres instance during deployment, or you can provide information for an external instance as well. I am experimenting with running and managing Postgres instances on Kubernetes, so it felt natural to try and build an instance with CrunchyData postgres operator, rather than let one be built with Harbor deployment. However, Harbor seems to require 4 separate databases to function (as it bundles other open source components), but the Helm chart seems to assume one instance will be used for all 4 databases. See <https://github.com/goharbor/harbor-helm/blob/master/values.yaml>, specifically line 682-690 of the values.yaml file.

So, now I am questioning the best way to handle this type of scenario. Based on the discussion so far, it seems like I can build a cluster with postgres operator, and add 3 more databases to it manually (in addition to the one that was created automatically with the cluster). I assume I could also build 4 separate clusters, although I am not sure if Harbor can be made to work if each of the 4 databases was hosted on a separate instance. I am still researching this.

If I was to just create 3 additional databases manually on the existing cluster, does that come with any downsides? Will backups, replication, etc work across all databases as they are added, or will only the first database be covered? Sorry if these are dumb questions, as I am not as familiar with Postgres and am still learning.

**Comment by jkatz** [comment]
Thanks for explaining the use case, that is certainly interesting. I can see where having database names on the CR could make it easier, particularly for bootstrapping. Maybe that is the use case: the database/users section is part of a bootstrapping section in the CRD, though doing a double check with people smarter than me to ensure that follows modern Kube best practices.

You can also create Postgres databases at bootstrap time using the [policies](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#policy-management) feature, which really just a way to execute SQL scripts. Doing this via the CR workflow is describe #1928, and I believe there may be an easier way to do so by loading in a `setup.sql` file referenced via a ConfigMap or the like (while the HA container is a different container, a good chunk of that spec is referenced [here](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-postgres/))

For specific questions:

> If I was to just create 3 additional databases manually on the existing cluster, does that come with any downsides?

A "database" in PostgreSQL is just a subdivided unit of the cluster. It's hard to pinpoint upsides/downsides specifically, though certainly more databases means there is more to manage. Managing permissions and access controls are one area that can come to bite you. Even if you deployed it as 4 separate clusters, you're likely to see similar issues, though you're just changing the problem space slightly.

I think with anything, it's understanding the difference of what it takes to get something up and running vs. production considerations. With PostgreSQL, the latter part can and has filled books. As an example, I wrote a talk years about using the [PostgreSQL Foreign Data Wrapper feature](https://www.slideshare.net/jkatz05/developing-and-deploying-apps-with-the-postgres-fdw) where I detailed how easy it was to get up and running in development vs. deploying it in production.

There are few, if any, technologies that can offer a full "free lunch" in a production PostgreSQL environment beyond simple applications: you will have to do a bit of tuning of the configuration file, but in the fullness of time I'm sure this can be further automated. Where the Operator helps is in the orchestration of the technologies you need to run PostgreSQL in production, and offering conveniences for managing availability, DR, and rolling out changes while allowing for customizability.

> Will backups, replication, etc work across all databases as they are added, or will only the first database be covered?

Yes. With the Postgres Operator, backups are managed via [pgBackRest](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/) which covers all the databases in a cluster. Replication uses PostgreSQL native replication facilities, and presently physical replication is all-or-nothing (logical replication allows you to replicate individual databases, tables, etc. The Operator is using physical).

> Sorry if these are dumb questions, as I am not as familiar with Postgres and am still learning.

Nope, these are questions are perfectly good. I appreciate hearing about the use case.

**Comment by mtrmarko** [comment]
Thank you @jkatz! That was a very detailed and informative response. It sounds like I can leverage policies for my use case. I will give it a go.

**Comment by jkatz** [comment]
Direct CRD support is on the roadmap for PGO 5.x. We are targeting the next feature release, though that can change based on priorities.
