### ISSUE TITLE
Metrics are not available when using S3 as the only backrest storage type

### ISSUE THREAD

**Issue by dakine1111** [CrunchyData/postgres-operator#1930]
**Describe the bug**
We've just found out that metrics are not available when using S3 as the only backrest storage type.
With local,s3 as backrest storage type the collect container works as expected.

**To Reproduce**
1. Create a cluster with --pgbackrest-storage-type s3
2. oc -n shared-debug exec debug-postgresql01-fbpq8 -c collect -- curl http://127.0.0.1:9187/metrics
Failed connect to 127.0.0.1:9187; Connection refused
In the logs of the collect container there are messages like:
time="2020-09-30T08:57:23Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_backrest_last_diff_backup pq: invalid input syntax for type json" source="postgres_exporter.go:1286"
time="2020-09-30T08:58:23Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_backrest_last_incr_backup pq: invalid input syntax for type json" source="postgres_exporter.go:1286"
time="2020-09-30T08:59:24Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_backrest_last_runtime pq: invalid input syntax for type json" source="postgres_exporter.go:1286"
time="2020-09-30T09:00:29Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_backrest_last_full_backup pq: invalid input syntax for type json" source="postgres_exporter.go:1286"
3. Create a cluster with --pgbackrest-storage-type local,s3
4. oc -n shared-debug exec debug-postgresql02-dsddr1 -c collect -- curl http://127.0.0.1:9187/metrics
is showing the metrics

**Expected behavior**
When using S3 as the only backrest storage type we would like to get the metrics of the cluster.

**Please tell us about your environment:**

* Storage being used (NFS, Hostpath, Gluster, etc): S3
* Container Image Tag: centos7-12.4-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.5.11

**Comment by jkatz** [comment]
I'm pleased to reported that this is resolved in the upcoming [4.5.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0-rc.1) release as part of the new and improved [monitoring](https://crunchydata.github.io/postgres-operator/latest/architecture/monitoring/) stack.

Thanks!
