### ISSUE TITLE
How to set the resources (RAM & CPU) for Postgres instance 

### ISSUE THREAD

**Issue by rg2609** [CrunchyData/postgres-operator#1934]
I am using the Helm chart and NFS storage, I wanted to know that how can I set the CPU and RAM for the Postgres in Helm chart.
I guess the following `values.yaml` variables are used for setting up the RAM if I am not wrong, but I haven't found the variable to set the CPU resources.
```
default_instance_memory: "128Mi"
default_pgbackrest_memory: "48Mi"
default_pgbouncer_memory: "24Mi"
default_exporter_memory: "24Mi"
```

**Please tell us about your environment:**

* Operating System: Debian GNU/Linux 10 (buster)
* Where is this running ( Local , Cloud Provider): GCE
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos7-12.4-4.4.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.18.8

**Comment by jkatz** [comment]
Those variables are related to setting the default memory values for each of those components.

CPU values are set on a per-cluster basis. There is now a [tutorial that covers this](https://crunchydata.github.io/postgres-operator/latest/tutorial/customize-cluster/).

If the goal is to create a Helm chart, you would need to set those values as part of creating a custom resource: [https://crunchydata.github.io/postgres-operator/latest/custom-resources/](https://crunchydata.github.io/postgres-operator/latest/custom-resources/)

Are you creating a Helm chart for creating custom resources?

**Comment by rg2609** [comment]
Thank you @jkatz :+1:

**Comment by jkatz** [comment]
@rg2609 You're welcome!
