### ISSUE TITLE
Unable to pull pgo-deployer:centos7-4.5.0

### ISSUE THREAD

**Issue by timbrd** [CrunchyData/postgres-operator#1936]
I just tried to upgrade pgo 4.4.1 to 4.5.0 using helm. 
Therefore I have updated my values.yml according to the one from the [git repository](https://github.com/CrunchyData/postgres-operator/blob/v4.5.0/installers/helm/values.yaml) and did an `helm upgrade` as explained in the documentation.

My kubernetes cluster is not able to find the pdo-deployer image though:

```
Failed to pull image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.5.0": rpc error: code = Unknown desc = Error reading manifest centos7-4.5.0 in registry.developers.crunchydata.com/crunchydata/pgo-deployer: manifest unknown: manifest unknown
```

**Comment by kfirfer** [comment]
Me either

**Comment by jkatz** [comment]
The images have not rolled out to the public repositories yet. They will over the next few days. Thank you for your patience.

**Comment by kfirfer** [comment]
Hi @jkatz 
IMO when the operator version publish's on the official docs, the docker images will be available instantly, current situation could make people just goes by the project without any notices

**Comment by jkatz** [comment]
Hi,

If you would like to stay updated about when the images are rolled out publicly, please feel free to sign up for release updates:

[https://www.crunchydata.com/developers/newsletter](https://www.crunchydata.com/developers/newsletter)

This will allow you to get notices on when the images are publicly available.

Thanks!

**Comment by kfirfer** [comment]
@jkatz 
Not every one knows that... but thanks anyway

**Comment by jkatz** [comment]
The images are now available. Enjoy!
