### ISSUE TITLE
pgbackrest very slow on OpenShift

### ISSUE THREAD

**Issue by jvincze84** [CrunchyData/postgres-operator#1937]
Hi All,

** Which example are you working with? **
I'm trying to create backup:
` pgo backup postgres-dbname--backup-opts="--type=full --log-level-console=debug"  -n mynamspace`

**What is the current behavior?**
The backup takes more than half an hour, but the database almost empty. (3-4 MB)

**What is the expected behavior?**
Should be a bit faster to take a backup. 

**Other information** (e.g. detailed explanation, related issues,  etc)
Log of the backrest-backup-postgres-* pod:
```
time="2020-10-03T09:11:05Z" level=info msg="pgo-backrest starts"
time="2020-10-03T09:11:05Z" level=info msg="debug flag set to false"
time="2020-10-03T09:11:05Z" level=info msg="backrest backup command requested"
time="2020-10-03T09:11:05Z" level=info msg="command to execute is [pgbackrest backup --type=full --log-level-console=debug --db-host=10.165.24.157 --db-path=/pgdata/postgres-mydb]"
time="2020-10-03T09:11:05Z" level=info msg="command is pgbackrest backup --type=full --log-level-console=debug --db-host=10.165.24.157 --db-path=/pgdata/postgres-mvadb "
time="2020-10-03T09:44:01Z" level=info msg="output=[2020-10-03 09:11:05.488 P00  DEBU . . . . 
```
Between the two timestamp below happens nothing:
`time="2020-10-03T09:11:05Z" --> Time="2020-10-03T09:44:01Z"`

**Please tell us about your environment:**

* Operating System: 
OpenShift 4.5 FCOS (Fedora release 32 (Thirty Two))
* Where is this running ( Local , Cloud Provider)
Local Cluster on Vsphere
* Storage being used (NFS, Hostpath, Gluster, etc):
Rook (cephfs)
* Container Image Tag:
crunchydata/pgo-backrest:centos7-4.4.1
* PostgreSQL Version:
4.4.1.
* Platform (Docker, Kubernetes, OpenShift):
crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.18.2
RuntimeApiVersion:  v1alpha1
* Platform Version:
OpenShift 4.5

Has someone experienced behavior like this?

Thanks a lot!

**Comment by jkatz** [comment]
- Where is the storage system located?
- What is the network saturation on your system?
- What is the resource utilization on the node that your pgBackRest repo resides?

Typically when I've seen pgBackRest being slow, it has been due to to location of the storage system (e.g., backing up to S3 from outside the AWS network) or pgBackRest not being configured to utilize enough resources for a very large database (e.g., bumping up process-max).

**Comment by jvincze84** [comment]
@jkatz 
Thank you very much for you reply.
We have several node (~20),  and the rook storage devices (/dev/sd*)  are attached to the 1st, 2nd and 3rd node.
The typical write speed of the cephfs is about 100-120 MB/s. 

> Where is the storage system located?
Rook is installed to first three node of the cluster.
But we can experience the same problem on OKD3 with GlusterFS. 

> What is the network saturation on your system?
I don't know the answer, but all of the nodes are placed in the same VLAN without any active device (FW, rotuer, etc.)

> What is the resource utilization on the node that your pgBackRest repo resides?
This is a really new cluster and we don't have significant load on it.
CPU usege of the node during the backup:
![image](https://user-images.githubusercontent.com/22055109/95048593-631daa80-06e8-11eb-9892-50b25eba1921.png)

Thanks!

**Comment by andrewlecuyer** [comment]
@jvincze84 thanks for the additional information.  To further troubleshoot, we'd like to first determine if the issue is with the network and/or Kubernetes API (when a pgBackRest Job it run, the container exec's into the pgBackRest repo Pod via the Kube API to run the backup command), or with the pgBackRest command itself.

Therefore, can you exec into the pgBackRest repo Pod yourself via `oc`, and then try manually running the backup command?  E.g.:

```bash
oc exec -it <backrest-repo-pod-name> -n <backrest-repo-pod-namespace> -- bash
pgbackrest backup --type=full --log-level-console=debug --db-host=10.165.24.157 --db-path=/pgdata/postgres-mvadb
```

Be sure to set the IP for `--db-host` and the path for `--db-path` according to the current primary your are trying to backup.

We are basically curious if you see the same performance issues when running the command manually from within the repo container itself, or if you only see these perofrmance issues when initializing the backup via `pgo backup` (and therefore a Job).  This will help us to narrow down where the issue might be.

**Comment by jvincze84** [comment]
Hi @andrewlecuyer 

I've run the suggested command from the pod manually and took ~4 mins.:

`2020-10-06 06:53:01.950 P00   INFO: expire command end: completed successfully (3752ms)`
But it's a bit rare for me that backing up 31 MB takes 4 minutes:
`2020-10-06 06:52:55.741 P00   INFO: full backup size = 31.1MB`

Right after the manually backup I tried with pgo command:

`pgo backup postgres-mvadb --backup-opts="--type=full --log-level-console=debug" -n dxl-fat3  --debug`
And took more than 12 minutes:
```
time="2020-10-06T07:42:20Z" level=info msg="pgo-backrest starts"
time="2020-10-06T07:42:20Z" level=info msg="debug flag set to false"
time="2020-10-06T07:42:20Z" level=info msg="backrest backup command requested"
time="2020-10-06T07:42:20Z" level=info msg="command to execute is [pgbackrest backup --type=full --db-host=10.165.24.157 --db-path=/pgdata/postgres-mvadb]"
time="2020-10-06T07:42:20Z" level=info msg="command is pgbackrest backup --type=full --db-host=10.165.24.157 --db-path=/pgdata/postgres-mvadb "
time="2020-10-06T07:55:42Z" level=info msg="output=[]"
time="2020-10-06T07:55:42Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\n]"
time="2020-10-06T07:55:42Z" level=info msg="pgo-backrest ends"
```

**Additional info:**

**Start Backup:**
`[postgres] 2020-10-06 11:13:22$ pgo backup postgres-mvadb --backup-opts="--type=full --log-level-console=debug" -n dxl-fat3  --debug`

**Process list inside the backreest-backup-* pod:**
```
[postgres] 2020-10-06 11:13:36$ oc exec -it backrest-backup-postgres-mvadb-4sjr8 -n dxl-fat3 -- ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
postgres       1  0.2  0.0 335548 21380 ?        Ssl  09:17   0:00 /opt/cpm/bin/pgo-backrest
postgres      24  0.0  0.0  51772  3508 pts/0    Rs+  09:18   0:00 ps aux
[postgres] 2020-10-06 11:13:52$
```

**Process list inside the *-backrest-shared-repo-* pod:**
```
[postgres] 2020-10-06 11:13:52$ oc exec -it postgres-mvadb-backrest-shared-repo-6bdd957477-9qlh8 -n dxl-fat3 -- ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
pgbackr+       1  0.0  0.0  11708  2628 ?        Ss   09:17   0:00 /bin/bash /usr/local/bin/pgo-backrest-repo.sh
pgbackr+      22  0.0  0.0 112940  7508 ?        S    09:17   0:00 /usr/sbin/sshd -D -f /sshd/sshd_config
pgbackr+      23  0.0  0.0  11840  2976 pts/0    Ss+  09:17   0:00 sh
pgbackr+      31  0.0  0.0  11704  2572 ?        Ss   09:17   0:00 bash
pgbackr+      37  0.3  0.0 100012 15996 ?        S    09:17   0:00 pgbackrest backup --type=full --log-level-console=debug --db-host=10.165.24.163 --db-path=/pgdata/postgres-mvadb-hylt
pgbackr+      38  0.0  0.0  75132  6476 ?        S    09:17   0:00 ssh -o LogLevel=error -o Compression=no -o PasswordAuthentication=no postgres@10.165.24.163 pgbackrest --log-level-console=off --log-level-
pgbackr+      39  0.2  0.0  98284  8056 ?        D    09:17   0:00 pgbackrest --checksum-page --host-id=1 --log-level-console=off --log-level-file=off --log-level-stderr=error --pg1-host=10.165.24.163 --pg1
pgbackr+      40  0.0  0.0  75280  6552 ?        S    09:17   0:00 ssh -o LogLevel=error -o Compression=no -o PasswordAuthentication=no postgres@10.165.24.163 pgbackrest --checksum-page --log-level-console=
pgbackr+      41  0.0  0.0  51772  3472 pts/1    Rs+  09:18   0:00 ps aux
```

**Process list inside the database server pod:**
```
[postgres] 2020-10-06 11:14:34$ oc exec -it postgres-mvadb-hylt-7885ff7974-wcsrl -n dxl-fat3 -- bash
Defaulting container name to database.
Use 'oc describe pod/postgres-mvadb-hylt-7885ff7974-wcsrl -n dxl-fat3' to see all of the containers in this pod.
bash-4.2$ ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
postgres       1  0.0  0.0  44276 11064 ?        Ss   08:39   0:00 /usr/bin/python3 /usr/local/bin/patroni /tmp/postgres-ha-bootstrap.yaml
postgres     141  0.0  0.0 112944  3716 ?        Ss   08:39   0:00 /usr/sbin/sshd -f /sshd/sshd_config
postgres     209  0.0  0.1 652124 55804 ?        Sl   08:40   0:02 /usr/bin/python3 /usr/local/bin/patroni /tmp/postgres-ha-bootstrap.yaml
postgres     246  0.0  0.0 302316 24776 ?        S    08:40   0:00 postgres -D /pgdata/postgres-mvadb-hylt --config-file=/pgdata/postgres-mvadb-hylt/postgresql.conf --listen_addresses=0.0.0.0 --port=5432 --
postgres     257  0.0  0.0 153620  5208 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: logger
postgres     259  0.0  0.0 302460 11468 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: checkpointer
postgres     260  0.0  0.0 302316  5812 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: background writer
postgres     261  0.0  0.0 302316 10148 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: walwriter
postgres     262  0.0  0.0 302856  8592 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: autovacuum launcher
postgres     263  0.0  0.0 155736  5748 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: archiver   last was 00000002000000000000002C
postgres     264  0.0  0.0 155872  5648 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: stats collector
postgres     265  0.0  0.0 302736  6948 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: logical replication launcher
postgres     269  0.0  0.2 382268 67208 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: ccp_monitoring postgres 127.0.0.1(37760) idle
postgres     294  0.0  0.0 303656 16740 ?        Ss   08:40   0:00 postgres: postgres-mvadb-hylt: postgres postgres [local] idle
postgres     323  0.4  0.0 314004 26608 ?        Ss   08:40   0:11 postgres: postgres-mvadb-hylt: reallysuperuser dxlfat3 10.165.25.43(45718) idle
postgres   10882  0.0  0.0 150624  8508 ?        Ss   09:17   0:00 sshd: postgres@notty
postgres   10884  0.0  0.0  89856  6984 ?        Ss   09:17   0:00 pgbackrest --log-level-console=off --log-level-file=off --log-level-stderr=error --pg1-local --pg1-path=/pgdata/postgres-mvadb-hylt --pg1-p
postgres   10885  0.0  0.0 303804 15120 ?        Ss   09:17   0:00 postgres: postgres-mvadb-hylt: postgres postgres [local] idle
postgres   10886  0.0  0.0 150624  8716 ?        Ss   09:17   0:00 sshd: postgres@notty
postgres   10888  0.9  0.0  89632  7896 ?        Ss   09:17   0:00 pgbackrest --checksum-page --log-level-console=off --log-level-file=off --log-level-stderr=error --pg1-local --pg1-path=/pgdata/postgres-mv
postgres   11238  0.0  0.0  15280  3336 pts/0    Ss   09:19   0:00 bash
postgres   11244  0.0  0.0  55212  4024 pts/0    R+   09:19   0:00 ps aux
```

Thanks a lot!

**Comment by v3nturetheworld** [comment]
@jvincze84 did you ever resolve this issue with Ceph? I'm beginning to debug a similar issue with rook-ceph on OpenShift4.6 where backups take ~1.5 hours for just the cluster creation. ~7s per write+checksum from the /tmp/db-backup logs in the backrest repo. I'm going to try adjust the BackrestConfig settings to allow async backups and likely a few other settings but for whatever reason Ceph is significantly slower the a local-storage backup which takes ~60-80 seconds.

**Comment by jkatz** [comment]
FYI, there is an issue found and filed in the ceph upstream:

[https://bugzilla.redhat.com/show_bug.cgi?id=1975510](https://bugzilla.redhat.com/show_bug.cgi?id=1975510)

pgBackRest is adding a workaround for an upcoming release, but the full fix will require for changes in the ceph upstream.
