### ISSUE TITLE
problems listing backup of some cluster

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1938]
I'm in trouble getting the list of backups  from some cluster
below is the show cluster and the message I'm getting, when trying on the same cluster to get backups.. 

how I can solve this?

8<--------------------------------------------------------------------------------------------
cccccccc@hippo14:~/svn/k8s$ pgo show cluster  rios

cluster : rios (crunchy-postgres-ha:centos7-12.3-4.4.0)
	pod : rios-ibqt-5cd46fd7ff-twrs7 (Running) on k1.gggggggggggg.com (1/1) (primary)
		pvc: rios-ibqt (20Gi)
	pod : rios-iehk-6bdd766f66-4dgrn (Running) on k3.gggggggggggg.com (1/1) (replica)
		pvc: rios-iehk (5Gi)
	resources : Memory: 128Mi
	deployment : rios-backrest-shared-repo
	deployment : rios-ibqt
	deployment : rios-iehk
	deployment : rios-pgadmin
	policy: createdb-rios
	service : rios - ClusterIP (10.43.229.17)
	service : rios-pgadmin - ClusterIP (10.43.53.234)
	service : rios-replica - ClusterIP (10.43.152.142)
	pgreplica : rios-ibqt
	pgreplica : rios-iehk
	labels : createdb-rios=pgpolicy crunchy-pgadmin=true deployment-name=rios-ibqt workflowid=27b86d06-7bc7-44d4-871e-eb1ad412add3 autofail=true name=rios pg-cluster=rios pg-pod-anti-affinity= pgo-backrest=true pgo-version=4.4.0 pgouser=admin crunchy_collect=false crunchy-pgha-scope=rios crunchy-pgbadger=false 
cccccccc@hippo14:~/svn/k8s$ pgo show backup rios
Error: primary pod is not in Ready state
8<--------------------------------------------------------------------------------------------

**Comment by jkatz** [comment]
See discussion in #1927
