### ISSUE TITLE
What is the image name (V4.5) for the gis container?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1939]
Hello,

I have started playing with the pgo 4.5 (look good!)

I tried to get a GIS image. However, I'm not sure if the image name is correct. Looking at your repository, you have the following:
```
registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:centos7-11.9-2.5-4.5.0
```
plus a bunch of others based on what we want :-)

However, in the previous version, it was called **crunchy-postgres-gis-ha**
Have you renamed the image?

If yes, this is not an issue. I just wanted to be sure

Thanks,
José

**Comment by jkatz** [comment]
Presently there are two flavors of GIS containers:

- `crunchy-postgres-gis`: meant for standalone deployments, be it with Docker, Podman, Kubernetes, etc.
- `crunchy-postgres-gis-ha`: meant for the Operator.

Both are available.

A future release with contemplate a simplification of this.

**Comment by jose-joye** [comment]
Thanks!
As always fast and accurate answers! :-)
