### ISSUE TITLE
Setting image pull secret for CCP image does not work

### ISSUE THREAD

**Issue by GeorgFleig** [CrunchyData/postgres-operator#1941]
**Describe the bug**
https://github.com/CrunchyData/postgres-operator/pull/1169 introduced the possibility to set an image pull secret for the CCP image. The secret is being added to the ServiceAccount `postgres-operator` in the operator namespace, while it should be added to the ServiceAccount `pgo-pg` in the target namespace. The postgres pod uses the `pgo-pg` ServiceAccount and therefore fails to pull the image when using a protected registry for the CCP image.

Manually defining the secret in the `pgo-pg` ServiceAccount resolves the issue.

**To Reproduce**
1. Set `ccp_image_prefix` to a private registry.
2. Set `ccp_image_pull_secret` to the corresponding secret to access this registry.
3. Deploy a cluster.

**Expected behavior**
Pod should start with an image from a private registry.

**Please tell us about your environment:**

I'm running an older version of the PGO but the latest ansible installer is not setting the secret in the right ServiceAccount (the other installers probably too, haven't checked): https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/pgo-pg-sa.json

* Deployment method: ansible
* Operating System: Ubuntu 18.04
* Where is this running: Private cloud
* Storage being used: Ceph
* Container Image Tag: 4.2.2
* PostgreSQL Version: 11.6
* Platform (Docker, Kubernetes, OpenShift): k8s 1.15

**Additional context**
Operator and postgres databases reside in different namespaces.

**Comment by jkatz** [comment]
4.2 is [EOL](https://github.com/CrunchyData/postgres-operator/tree/REL_4_2_FINAL).

There have been changes to interfacing with image pull secrets in newer versions of the Operator, though some of those changes may be implied by the changes to namespace management. You can find an amalgamation of [release notes](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/) here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/releases/](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/)

And information on [upgrading](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/) here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/)

We have been unable to reproduce this issue on supported versions, but if you upgrade and find you still have an issue, please feel free to reopen the issue.
