### ISSUE TITLE
Install grafana and prom  via operatorhub

### ISSUE THREAD

**Issue by gauravshankarcan** [CrunchyData/postgres-operator#1942]
** Which example are you working with? **
https://operatorhub.io/operator/postgresql

**What is the current behavior?**
Default install only operator, 

**What is the expected behavior?**
we need the metrics pods as well .

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider) Openshift On prem
* Storage being used (NFS, Hostpath, Gluster, etc): Portworx
* Container Image Tag: ubi-4.4.1
* PostgreSQL Version: 12 
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: OpenShift 4.5

Via Operator how do we install metrics ? is there any documentation for this.
This works via the ansible installer not via the operator hub.

**Comment by jkatz** [comment]
There are instructions on how to install metrics stack provided here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/installation/metrics/](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/metrics/)

This does not require Ansible. It can be installed via the container-based installer.

as well as more information about the metrics stack that has been rebuilt for Operator 4.5:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/).

For the 4.5 release, we moved to using the upstream containers for Prometheus and Grafana. We do not have plans at this time to provide an installation for Prometheus/Grafana via OLM.
