### ISSUE TITLE
How to add taints ?

### ISSUE THREAD

**Issue by tdien105** [CrunchyData/postgres-operator#1943]
Hi,

Can you show me how to add toleration for PGO deployment ? (both primary and replica instances). I didnt see any instruction about that in your documentation. Many thanks,

**Comment by jkatz** [comment]
Presently the PostgreSQL Operator is maintaining backwards compatibility to Kubernetes 1.11 as we still support Openshift 3.11. When a new major upgrade release comes out (i.e. a 5.0), we will raise that compatibility and perhaps add explicit support for tolerations as part of the Operator deployment process.

As such, please refer to the official Kubernetes documentation for how to manage [taints and tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/).
