### ISSUE TITLE
PGO backup fails with PG pod unable to ssh to repo host

### ISSUE THREAD

**Issue by viki00** [CrunchyData/postgres-operator#1947]
** Which example are you working with? **
CrunchyData V 4.5.0 - Running command "pgo backup viki -n pgouser1 --debug"

**What is the current behavior?**
Error in the Postgresql logs
ERROR: [125]: remote-0 process on 'viki-backrest-shared-repo' terminated unexpectedly [255]: ssh: Could not resolve hostname viki-backrest-shared-repo: Name or service not known
2020-10-07 15:29:55.621 UTC [179] LOG:  archive command failed with exit code 125
2020-10-07 15:29:55.621 UTC [179] DETAIL:  The failed archive command was: source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push "pg_wal/000000010000000000000001"

**What is the expected behavior?**
Successful Backup
**Other information** (e.g. detailed explanation, related issues,  etc)
[vagrant@vmc4 postgres-operator]$ k get pods -n pgouser1
NAME                                         READY   STATUS      RESTARTS   AGE
backrest-backup-viki-xkl8f                   0/1     Error       0          45s
viki-6697466b96-nmzp8                        1/1     Running     0          5h47m
viki-backrest-shared-repo-7f99fb7865-xwkmz   1/1     Running     0          5h47m
viki-stanza-create-rqfqc                     0/1     Completed   0          5h47m

archive_command           | source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push "%p"

[vagrant@vmc4 postgres-operator]$ k get svc -n pgouser1
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
viki                        ClusterIP   10.97.58.47     <none>        2022/TCP,5432/TCP   6h18m
viki-backrest-shared-repo   ClusterIP   10.109.240.82   <none>        2022/TCP            6h18m

[vagrant@vmc4 postgres-operator]$ k describe svc viki -n pgouser1
Name:              viki
Namespace:         pgouser1
Labels:            name=viki
                   pg-cluster=viki
                   vendor=crunchydata
Annotations:       <none>
Selector:          pg-cluster=viki,role=master
Type:              ClusterIP
IP:                10.97.58.47
Port:              sshd  2022/TCP
TargetPort:        2022/TCP
Endpoints:         172.18.0.5:2022
Port:              postgres  5432/TCP
TargetPort:        5432/TCP
Endpoints:         172.18.0.5:5432
Session Affinity:  None
Events:            <none>

[vagrant@vmc4 postgres-operator]$ k describe svc viki-backrest-shared-repo -n pgouser1
Name:              viki-backrest-shared-repo
Namespace:         pgouser1
Labels:            name=viki-backrest-shared-repo
                   pg-cluster=viki
                   pgo-backrest-repo=true
                   vendor=crunchydata
Annotations:       <none>
Selector:          name=viki-backrest-shared-repo
Type:              ClusterIP
IP:                10.109.240.82
Port:              <unset>  2022/TCP
TargetPort:        2022/TCP
Endpoints:         172.18.0.4:2022
Session Affinity:  None
Events:            <none>

**Please tell us about your environment:**

* Operating System: Minikube on a Centos 7 
* Where is this running ( Local , Cloud Provider) - local
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: centos7-4.5.0
* PostgreSQL Version:12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version:minikube version: v1.13.1

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

[vagrant@vmc4 kubectl]$ k describe pod viki-6697466b96-nmzp8 -n pgouser1
Name:         viki-6697466b96-nmzp8
Namespace:    pgouser1
Priority:     0
Node:         minikube/172.17.0.2
Start Time:   Wed, 07 Oct 2020 15:21:26 +0000
Labels:       crunchy-pgha-scope=viki
              crunchy-postgres-exporter=false
              deployment-name=viki
              name=viki
              pg-cluster=viki
              pg-cluster-id=b6860551-a039-4479-85c3-486488074d93
              pg-pod-anti-affinity=
              pgo-pg-database=true
              pgo-version=4.5.0
              pgouser=admin
              pod-template-hash=6697466b96
              role=master
              service-name=viki
              vendor=crunchydata
              workflowid=9457d70a-b51c-497e-9db5-6aef4c86968d
Annotations:  status:
                {"conn_url":"postgres://172.18.0.5:5432/postgres","api_url":"http://172.18.0.5:8009/patroni","state":"running","role":"master","version":"...
Status:       Running
IP:           172.18.0.5
IPs:
  IP:           172.18.0.5
Controlled By:  ReplicaSet/viki-6697466b96
Containers:
  database:
    Container ID:   docker://5494aa05bcc33b26e07ce04f80ec7b6a0be8d507cc65e00054b558f84887edd5
    Image:          registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos7-12.4-4.5.0
    Image ID:       docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha@sha256:8f8c3e0a385f5d5185ea5fff18f1b875665e1639fde90bd40501ea1e211aa44f
    Ports:          5432/TCP, 8009/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 07 Oct 2020 15:21:28 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      memory:   128Mi
    Liveness:   exec [/opt/cpm/bin/health/pgha-liveness.sh] delay=30s timeout=10s period=15s #success=1 #failure=3
    Readiness:  exec [/opt/cpm/bin/health/pgha-readiness.sh] delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PGHA_PG_PORT:                       5432
      PGHA_USER:                          postgres
      PGHA_INIT:                          <set to the key 'init' of config map 'viki-pgha-config'>  Optional: false
      PATRONI_POSTGRESQL_DATA_DIR:        /pgdata/viki
      PGBACKREST_STANZA:                  db
      PGBACKREST_REPO1_HOST:              viki-backrest-shared-repo
      BACKREST_SKIP_CREATE_STANZA:        true
      PGHA_PGBACKREST:                    true
      PGBACKREST_REPO1_PATH:              /backrestrepo/viki-backrest-shared-repo
      PGBACKREST_DB_PATH:                 /pgdata/viki
      ENABLE_SSHD:                        true
      PGBACKREST_LOG_PATH:                /tmp
      PGBACKREST_PG1_SOCKET_PATH:         /tmp
      PGBACKREST_PG1_PORT:                5432
      PGBACKREST_REPO_TYPE:               posix
      PGHA_PGBACKREST_LOCAL_S3_STORAGE:   false
      PGHA_DATABASE:                      viki
      PGHA_CRUNCHYADM:                    true
      PGHA_REPLICA_REINIT_ON_START_FAIL:  true
      PGHA_SYNC_REPLICATION:              false
      PGHA_TLS_ENABLED:                   false
      PGHA_TLS_ONLY:                      false
      PGHA_STANDBY:                       false
      PATRONI_KUBERNETES_NAMESPACE:       pgouser1 (v1:metadata.namespace)
      PATRONI_KUBERNETES_SCOPE_LABEL:     crunchy-pgha-scope
      PATRONI_SCOPE:                       (v1:metadata.labels['crunchy-pgha-scope'])
      PATRONI_KUBERNETES_LABELS:          {vendor: "crunchydata"}
      PATRONI_LOG_LEVEL:                  INFO
      PGHOST:                             /tmp
      PGHA_WALDIR:                        /pgwal/viki-wal
    Mounts:
      /crunchyadm from crunchyadm (rw)
      /dev/shm from dshm (rw)
      /etc/pgbackrest/conf.d from pgbackrest-config (rw)
      /etc/podinfo from podinfo (rw)
      /pgconf from pgconf-volume (rw)
      /pgconf/pgreplicator from primary-volume (rw)
      /pgconf/pgsuper from root-volume (rw)
      /pgconf/pguser from user-volume (rw)
      /pgdata from pgdata (rw)
      /pgwal from pgwal (rw)
      /recover from recover-volume (rw)
      /sshd from sshd (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-f97sl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  pgdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  viki
    ReadOnly:   false
  user-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  viki-testuser-secret
    Optional:    false
  primary-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  viki-primaryuser-secret
    Optional:    false
  sshd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  viki-backrest-repo-config
    Optional:    false
  root-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  viki-postgres-secret
    Optional:    false
  recover-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  report:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  crunchyadm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  pgbackrest-config:
    Type:                Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:       viki-config-backrest
    ConfigMapOptional:   0xc00049da6d
    SecretName:          viki-config-backrest
    SecretOptionalName:  0xc00049da6e
  pgconf-volume:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      viki-pgha-config
    ConfigMapOptional:  0xc00049daa8
  podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      limits.cpu -> cpu_limit
      requests.cpu -> cpu_request
      limits.memory -> mem_limit
      requests.memory -> mem_request
      metadata.labels -> labels
      metadata.annotations -> annotations
  pgwal:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  viki-wal
    ReadOnly:   false
  pgo-pg-token-f97sl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgo-pg-token-f97sl
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>

[vagrant@vmc4 kubectl]$ k get pvc -n pgouser1
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
viki             Bound    pvc-ef754155-975d-49ca-bc39-979776f0faa2   1G         RWX            standard       6h24m
viki-pgbr-repo   Bound    pvc-7317d17f-cbb5-4c58-903e-0db517870723   1G         RWX            standard       6h24m
viki-wal         Bound    pvc-da1b9884-ca66-4e1c-b25e-cf07856fd93d   1G         RWX            standard       6h24m
[vagrant@vmc4 kubectl]$
[vagrant@vmc4 kubectl]$
[vagrant@vmc4 kubectl]$ k describe pvc viki
Error from server (NotFound): persistentvolumeclaims "viki" not found
[vagrant@vmc4 kubectl]$ k describe pvc viki -n pgouser1
Name:          viki
Namespace:     pgouser1
StorageClass:  standard
Status:        Bound
Volume:        pvc-ef754155-975d-49ca-bc39-979776f0faa2
Labels:        pg-cluster=viki
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1G
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    viki-6697466b96-nmzp8
Events:        <none>
[vagrant@vmc4 kubectl]$ k describe pvc viki-pgbr-repo -n pgouser1
Name:          viki-pgbr-repo
Namespace:     pgouser1
StorageClass:  standard
Status:        Bound
Volume:        pvc-7317d17f-cbb5-4c58-903e-0db517870723
Labels:        pg-cluster=viki
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1G
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    viki-backrest-shared-repo-7f99fb7865-xwkmz
Events:        <none>
[vagrant@vmc4 kubectl]$ k describe pvc viki-wal -n pgouser1
Name:          viki-wal
Namespace:     pgouser1
StorageClass:  standard
Status:        Bound
Volume:        pvc-da1b9884-ca66-4e1c-b25e-cf07856fd93d
Labels:        pg-cluster=viki
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1G
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    viki-6697466b96-nmzp8
Events:        <none>

[vagrant@vmc4 kubectl]$ k get nodes
NAME       STATUS   ROLES    AGE   VERSION
minikube   Ready    master   25h   v1.19.2

**Comment by jkatz** [comment]
The key bit is:

```
ERROR: [125]: remote-0 process on 'viki-backrest-shared-repo' terminated unexpectedly [255]: ssh: Could not resolve hostname viki-backrest-shared-repo: Name or service not known
```

which seems to indicate there is a networking issue in your environment. It could be a transient issue, it could be something with your network overlay, or it could be a Pod Security Policy or the like that your administrator set.

In short, you need to ensure SSH is allowed in your environment.

This topic is covered in detail in #1362 and briefly in the [cluster creation troubleshooting](https://access.crunchydata.com/documentation/postgres-operator/4.5.0/tutorial/create-cluster/#troubleshooting) (though we should probably add it to the disaster recovery troubleshooting guide).
