### ISSUE TITLE
postgres-operator 4.5.0 how do you add node affinity and pod priority class to pg deployments

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1949]
Is there a way with pgo 4.5.0 to add node affinity and a pod priority class to the pg deployments created by pgo?

**Comment by jkatz** [comment]
Node affinity is certainly supported and described in detail here:

[https://access.crunchydata.com/documentation/postgres-operator/4.5.0/architecture/high-availability/#node-affinity](https://access.crunchydata.com/documentation/postgres-operator/4.5.0/architecture/high-availability/#node-affinity)

If you need stronger node affinity other than you can adjust the `affinity.json` template. There is a detailed description of how to do so here: [https://github.com/CrunchyData/postgres-operator/issues/1907#issuecomment-696798258](https://github.com/CrunchyData/postgres-operator/issues/1907#issuecomment-696798258)

Pod Priority classes became [stable in Kube 1.14](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/). For now, we're maintaining backwards compatibility to Kube 1.11 (to support OCP 3.11), and while a future major release will allow for us to raise our min-Kube level, we're making a conscious effort to avoid introducing changes that would break users on OCP 3.11.

If you want to add Pod Priority Classes on your own, you could add it directly to the `cluster-deployment.json` template, similar to the description of the `affinity.json` template.
