### ISSUE TITLE
Change de default replica creation method to basebackup

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1951]
Hi, i found that using pgbackrest to create replicas is not doing well for us, is rather slow, and has problems when s3 is down, i would like to change the default patroni snippet to change order in this part:

		  create_replica_methods:
		  - pgbackrest
		  - basebackup

but i dont find where this part has his template.. where can i change that for every cluster in mi installlation?

**Comment by jkatz** [comment]
Duplicated by #1952
