### ISSUE TITLE
Why is it so hard to figure out what container to use?

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1955]
Trying to use pgo 4.4.1 because I am hitting so many issues trying to use pgo 4.5.0.  Now I am hitting issues using pgo 4.4.1 because I can't seem to find the right container to use.  I am looking here at available options: https://www.crunchydata.com/developers/download-postgres/containers/postgis and I picked --ccp-image-tag=centos7-11.9-2.4-4.4.1.  However, it fails to create the cluster and the container because it can't find this image:   
```
Warning  Failed     20s (x2 over 31s)  kubelet, prod1-db-0  Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-11.9-2.4-4.4.1": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-11.9-2.4-4.4.1 not found: manifest unknown: manifest unknown
```

Here's the full list of events from creating the pod:
```
Events:
  Type     Reason     Age                From                 Message
  ----     ------     ----               ----                 -------
  Normal   Scheduled  <unknown>          default-scheduler    Successfully assigned pgo/retroelk-84c5d868c6-nqgks to prod1-db-0
  Normal   Pulling    88s                kubelet, prod1-db-0  Pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos7-11.9-2.5-4.4.1"
  Normal   Pulled     69s                kubelet, prod1-db-0  Successfully pulled image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos7-11.9-2.5-4.4.1"
  Normal   Created    55s                kubelet, prod1-db-0  Created container database
  Normal   Started    55s                kubelet, prod1-db-0  Started container database
  Warning  Failed     33s (x4 over 55s)  kubelet, prod1-db-0  Error: ImagePullBackOff
  Normal   Pulling    22s (x3 over 55s)  kubelet, prod1-db-0  Pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-11.9-2.5-4.4.1"
  Warning  Failed     21s (x3 over 55s)  kubelet, prod1-db-0  Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-11.9-2.5-4.4.1": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-11.9-2.5-4.4.1 not found: manifest unknown: manifest unknown
  Warning  Failed     21s (x3 over 55s)  kubelet, prod1-db-0  Error: ErrImagePull
  Warning  Unhealthy  15s (x3 over 35s)  kubelet, prod1-db-0  Readiness probe failed:
  Normal   BackOff    8s (x5 over 55s)   kubelet, prod1-db-0  Back-off pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-collect:centos7-11.9-2.5-4.4.1"
```

What image am I supposed to use if I want to use postgres with postgis v11.9?

**Comment by alrooney** [comment]
Here's how I am creating the cluster: 
```
kubectl exec -ti -n pgo deploy/pgo-client -- pgo create cluster retroelk --standby \
  --service-type=NodePort \
  --pgbackrest-s3-bucket=<bucket> \
  --pgbackrest-s3-endpoint=s3.amazonaws.com \
  --pgbackrest-s3-region=us-east-1 \
  --pgbackrest-s3-key=<key> \
  --pgbackrest-s3-key-secret=<secret>  \
  --pgbackrest-pvc-size=500Gi \
  --pgbackrest-s3-uri-style=host \
  --pgbackrest-s3-verify-tls=true \
  --username=retroelk-user \
  --password=<password> \
  --password-superuser=<password-superuser> \
  --password-replication=<password-replication> \
  --pgbackrest-storage-type=local,s3 \
  --pgbackrest-repo-path=/backrestrepo/retroelk-backrest-shared-repo \
  --metrics \
  --cpu=8 \
  --memory=16Gi \
  --cpu-limit=15 \
  --memory-limit=48Gi \
  --ccp-image=crunchy-postgres-gis-ha \
  --ccp-image-tag=centos7-11.9-2.4-4.4.1 \
  --pvc-size=100Gi \
  --node-label=minim.co/node-use=postgres \
  --custom-config=retroelk-custom-config \
  -n pgo

**Comment by alrooney** [comment]
I can get past this issue by omitting the --metrics flag when creating the cluster but obviously it isn't creating the collector sidecar if I do that.

**Comment by jkatz** [comment]
This is covered in #1749

**Comment by jkatz** [comment]
It would also be helpful to understand what you mean by:

> I am hitting so many issues trying to use pgo 4.5.0

if it's beyond any off the GitHub issues you've opened, as generic comments do not necessarily help us to improve the product or effectively troubleshoot an issue.

We have started up a new mailing list to see if it helps communicating around things like setting up a newer version of the Operator. If you are interested in joining, you can find the information here:

[https://github.com/CrunchyData/postgres-operator#support](https://github.com/CrunchyData/postgres-operator#support)

**Comment by alrooney** [comment]
Sorry - just some frustration bubbling up as I have been trying for several days now to get things working with pgo 4.5.0 and keep hitting numerous issues/questions.  Filing specific issues as I find them.  I think I would feel much less frustrated if I felt empowered to debug some of these issues myself instead of filing issues with you guys and waiting for responses.  The operator is a very cool piece of software that enables a very complex architecture.   But would be great if you guys wrote up somewhere how to debug, where to look at logs for each of the components etc.  As far as I know - nowhere in your documentation do you even describe how to exec into the db container and go look at the postgres logs.  I figured this out, but for anyone who hasn't this would probably save them and you a ton of time.  And then you need to do this for backrest, bouncer and the other components.  I would have been happy to poke around and hopefully figure out the centos8 issue that I was hitting with 4.5.0 but I didn't even know where to go look for logs or how to debug backrestrepo directory not found.  And then doubly frustrating that when I log into the backrest container it has no useful logs and when I try to go look at the var/log/pgbackrest directory I can't because I don't know how to access this root owned directory.  Your documentation on how the system works is awesome - but it could definitely do with some sections on debugging when things don't work and where to go look for logs and how things are supposed to work i.e. what containers are created with pvcs and what directories etc.
