### ISSUE TITLE
password authentication failed for user "ccp_monitoring"

### ISSUE THREAD

**Issue by yangvipguang** [CrunchyData/postgres-operator#1962]
**Describe the bug**
I have  created a pg  cluster kong with metrics . but  the  exporter in kong pod  print some error logs:
![image](https://user-images.githubusercontent.com/11416887/95710088-920cc100-0c92-11eb-9cca-f674aa267153.png)

I have tried several times。 The results  are same.
I want  to  konw   how to fix it .

**Please tell us about your environment:**

* Operating System:  Centos 7
* Where is this running ( Local, Cloud Provider)  Alicloud
* Storage being used (NFS, Hostpath, Gluster, etc):  NAS
* Container Image Tag:  centos7-4.5.0
* PostgreSQL Version:  12.4
* Platform (Docker, Kubernetes, OpenShift):  K8S
* Platform Version:  1.16

**Additional context**

**Comment by jkatz** [comment]
I believe that error is a false positive. The `postgres_exporter` server should not be able to start if it's unable to connect to the PostgreSQL database (see the lower line). This can happen while things the system is starting up: the exporter is trying to connect to a database that is not fully available yet. That is the typical error when it fails to connected. As it runs `SELECT now();` to check the connection, you can see the successful connection at that point in the log line.

Anyway, this is not an issue. That said, I'll add some documentation in one of the troubleshooting sections.
