### ISSUE TITLE
Unable to create postgis image based cluster

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#1970]
Describe the bug
It is still impossible to create a postgis image based cluster as in the exampple from docs (Common pgo Client Tasks -> Create a PostgreSQL Cluster with PostGIS)

Pgbager tries to pull image with tag centos7-12.4-3.0-4.5.0 instead of centos7-12.4-4.5.0

And it isnt documented how to add env variables to "pgo-config" configmap with  for temporary solution:
 - name: RELATED_IMAGE_CRUNCHY_COLLECT
   value: crunchydata/crunchy-collect:centos7-12.3-4.4.0

To Reproduce
pgo create cluster hagiscluster
--ccp-image=crunchy-postgres-gis-ha
--ccp-image-tag=centos7-12.4-3.0-4.5.0

Expected behavior
Bpbanger pulls an image with proper tag

Environment:
Google Kubernetes Engine cluster
Container Image Tag: crunchy-postgres-ha:centos7-12.4-4.5.0
Platform Version: 1.17.9-gke.6300

**Comment by DavidKmn** [comment]
We are also trying to setup PostGIS and facing the same issues...

**Comment by jkatz** [comment]
Please use #1749 for tracking this.
