### ISSUE TITLE
Restore a cluster 

### ISSUE THREAD

**Issue by aurelien43** [CrunchyData/postgres-operator#1973]
hello, 
when i try to restore a cluster with pgo restore commande, the bootstrap pods crash. 

The error of bootstrap pods : 
ERROR: [040]: unable to restore to path '/pgwal/test-450-wal' because it contains files
       HINT: try using --delta if this is what you intended.

I try to use --delta  but there are the same error. 

**To Reproduce**
1. Create a cluster : pgo create cluster test-450  --pgbadger
2. Restore this cluster : pgo restore test-450 --backup-opts="--log-level-console=debug"

**Please tell us about your environment:**

* Operating System: centos7
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): CSI (SAN)
* Container Image Tag: centos7-12.4-4.5.0
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16

**Comment by jkatz** [comment]
Are you mounting an external WAL volume?

**Comment by aurelien43** [comment]
Yes a CSI storage.

**Comment by jkatz** [comment]
@aurelien43 Thanks, we've confirmed this is indeed a bug. It only affects 4.5. We will prepare a fix that will be available for 4.5.1.

In the interim, to perform a restore with an already in use WAL PVC, you can manually delete said WAL PVC and the restore should proceed.

Thanks for reporting!
