### ISSUE TITLE
Replica failed in postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#1977]
We had a space issue because of which the replicas was down. We increased the pvc size but also its not up. Do you have any suggestions?

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
Please see the response in [https://github.com/CrunchyData/postgres-operator/issues/1976#issuecomment-710030830](https://github.com/CrunchyData/postgres-operator/issues/1976#issuecomment-710030830) which provides links to resources that should help you figure out the best strategy. If the replica is out-of-sync, you will need to reprovision the replica.
