### ISSUE TITLE
Is it possible to get sudo (root) access on postgres primary and replica containers?

### ISSUE THREAD

**Issue by denishpatel** [CrunchyData/postgres-operator#1981]
Trying to get sudo access on postgres container running on kubernates cluster. Is it possible?

**Comment by jkatz** [comment]
You can have `postgres` superuser access, but you cannot `sudo` directly, as this is typically undesired behavior when running in a containerized environment.

You may be able to find a way to get `root` behavior via [capabilities](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container) though that would be a science experiment (and my brief tests with capabilities for something else did not work as plan).

My question is: why do you need root access?

**Comment by alrooney** [comment]
2 use cases that I hit:

1) I wanted to edit the script that determines if pg is healthy in the db container, but I couldn't because it was owned by root
2) I wanted to look at logs for backrest in /var/log/pgbackrest in the backrest container but I couldn't because it was readable only by root

**Comment by denishpatel** [comment]
@jkatz Thanks for quick reply on this. 

Other than @alrooney provided some use cases... i wanted to install plperl extension through PGDG repo to play around and eventually roll as docker image

**Comment by jkatz** [comment]
> 2. I wanted to look at logs for backrest in /var/log/pgbackrest in the backrest container but I couldn't because it was readable only by root
> 
> ```
> $ kk exec -ti retroelk-backrest-shared-repo-7bd8f45b4b-r2ntq -n pgo -- bash
> [pgbackrest@retroelk-backrest-shared-repo-7bd8f45b4b-r2ntq /]$ cd /var/log
> [pgbackrest@retroelk-backrest-shared-repo-7bd8f45b4b-r2ntq log]$ ls -l
> total 716
> -rw------- 1 root utmp    384 Oct 10 20:33 btmp
> -rw-r--r-- 1 root root    193 Aug  9 21:38 grubby_prune_debug
> -rw-r--r-- 1 root root 584292 Oct  1 19:35 lastlog
> drwxr-x--- 2 root root   4096 Oct  1 19:35 pgbackrest
> -rw------- 1 root root 128064 Oct  1 19:35 tallylog
> -rw-rw-r-- 1 root utmp      0 Aug  9 21:38 wtmp
> -rw------- 1 root root   2139 Oct  1 19:35 yum.log
> [pgbackrest@retroelk-backrest-shared-repo-7bd8f45b4b-r2ntq log]$ cd pgbackrest
> bash: cd: pgbackrest: Permission denied
> [pgbackrest@retroelk-backrest-shared-repo-7bd8f45b4b-r2ntq log]$
> ```

That seems wrong and warrants investigation. Though given the "pgbackrest process" does not run as root, I wonder what is even making it into there. Flagging for the team.

**Comment by andrewlecuyer** [comment]
@alrooney per our default configuration, pgBackRest should be logging to `/tmp`.

https://github.com/CrunchyData/postgres-operator/blob/71c81daf84cb2cfe4f07edf26362834b63b993e1/installers/ansible/roles/pgo-operator/files/pgo-configs/backrest-job.json#L68-L71

https://github.com/CrunchyData/postgres-operator/blob/71c81daf84cb2cfe4f07edf26362834b63b993e1/installers/ansible/roles/pgo-operator/files/pgo-configs/pgbackrest-env-vars.json#L29-L32
