### ISSUE TITLE
Deleted/failed primary pod in kubernetes ends up with all-replica cluster

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#1982]
Manual failover with "pgo failover" command cant do it with primary. Is crunchy provides primary failover at all?
In my staging environment GKE nodes go down sometimes and if crunchy master pod was running on that node it ends up with three replica cluster with no primary. 
How can I prevent losing primary in situations like this? Whole db cluster replication? Standby cluster?
<img width="476" alt="Screenshot 2020-10-19 at 11 23 00" src="https://user-images.githubusercontent.com/42073646/96420866-b15d9e00-11fe-11eb-9b7e-756aaf0a9136.png">

To Reproduce
- kubectl delete pod "crunchy-current-master-pod"
- pgo test cluster "crunchy-pg-cluster"

Expected behavior
- failover algorithm promotes primary from one of current replicas 

Environment:
Google Kubernetes Engine cluster
Container Image Tag: crunchy-postgres-ha:centos7-12.4-4.5.0
Platform Version: 1.17.9-gke.6300

Cluster created with command:
pgo create cluster -n pgo pgsql-cluster-eu-1 --ccp-image=crunchy-postgres-ha --ccp-image-tag=centos7-12.4-4.5.0 --metrics --pgbouncer  --replica-count=2 --pgbadger --sync-replication --pvc-size=2Gi --pgbackrest-pvc-size 3Gi --storage-config=csi-ssd-multizone --replica-storage-config=csi-ssd-multizone --pgbackrest-storage-config=csi-ssd-multizone --pgbouncer-replicas=3 --pod-anti-affinity=preferred  --pgbackrest-storage-type=local,s3

*csi-ssd-multizone is manually created multizone ssd storage type with csi driver

Thank you!

**Comment by jkatz** [comment]
I'm having a bit of trouble following this as there appears to be several topics mentioned. I can tell you that one of my manual test cases for automatic failover is `kubectl delete pod "crunchy-current-master-pod"` (and I believe that one is also in the test suite, though would have to check).

`pgo failover` does not let you target the current primary for failover: you have to target a replica. It basically demotes the primary and promtes a replica.

For details on the high availability system in the Operator:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/)
- [[https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/high-availability/](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/high-availability/)

It appears that you have a multi-zone setup. There are additional considerations when deploying across availability zones:

[https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/multi-zone-design-considerations/](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/multi-zone-design-considerations/)

Note the literature on multi-zone was written awhile ago before multi-zone was widely available, let alone being considered in actual deployment architectures. Some of the contents may be updated, but a recent run through showed that the process still worked.

Anyway, without logs from your PostgreSQL Pods and the Operator itself, it's difficult to make any further analysis on whether this is a bug or if there is an issue with your setup.

Thanks!
