### ISSUE TITLE
Installing without ansible/pgo-deployer

### ISSUE THREAD

**Issue by james-callahan** [CrunchyData/postgres-operator#1984]
**What is the motivation or use case for the feature? **

Currently the only documented installation methods are all via ansible. Even the helm chart just creates a job (pgo-deployer) that runs ansible. This is very unusual, and does not play well with generally accepted means for managing kubernetes clusters.

**Describe the solution you'd like**

A collection of kubernetes manifests to apply to a cluster that include all components that will be running long term in the cluster. These could be templated via helm; or (preferably) ready to use with kustomize.

**Comment by jkatz** [comment]
PGO 5.0 is installable with Kustomize + Helm: [https://access.crunchydata.com/documentation/postgres-operator/v5/installation/](https://access.crunchydata.com/documentation/postgres-operator/v5/installation/)
