### ISSUE TITLE
creating replica with pgo 4.5.0 cannot control pvc size and pvc size is not same as primary

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1986]
version = pgo 4.5.0
scaling a cluster as follows:

```
kubectl exec -ti -n pgo deploy/pgo-client -- pgo scale radius-prodkdcam1 \
>   --storage-config=localstorage \
>   --node-label=minim.co/node-use=postgres \
>   --replica-count=1 \
>   -n pgo
```
However, the resulting pvc size is wrong i.e. not same as primary:

```
NAME                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
radius-prodkdcam1                Bound    pvc-85d546dc-ffa6-4ef2-bf32-359fa8d235dd   50Gi       RWO            local-storage       25m
radius-prodkdcam1-pgbr-repo      Bound    pvc-fc935b31-4ba5-45a7-a545-268559e39ec3   200Gi      RWO            glusterfs-storage   25m
radius-prodkdcam1-qzyr           Bound    pvc-ab9566ed-fa40-4904-952f-11b9ffd14b82   100G       RWO            local-storage       20s
```

And there is no way to set the pvc size: 
```
$ kubectl exec -ti -n pgo deploy/pgo-client -- pgo scale radius-prodkdcam1 \
>   --storage-config=localstorage \
>   --pvc-size=50Gi \
>   --node-label=minim.co/node-use=postgres \
>   --replica-count=1 \
>   -n pgo
Error: unknown flag: --pvc-size
```

Is there any way to create a replica with the correct pvc size?

**Comment by jkatz** [comment]
This is not directly supported. You would have to create a "storage config" with a larger PVC size in order to set the PVC size on a replica.

What is your use case where you would like to have a replica that is larger than the primary?

**Comment by alrooney** [comment]
Actually that's exactly the problem.  I don't want a replica that has a pvc larger than the primary but that is what the operator creates.  I want a replica that is the same size as the primary but the operator defaults to the size in the yaml file for the replica which is different than the primary since I used --pvc-size while creating the primary.  

Just to be clear operator defaults to 100Gb because of storage config in yaml.  I created primary with --pvc-size of 50gb but cannot create a replica of same storage size of 50Gb.  Instead the replica comes out as 100Gb and I cannot change it.

**Comment by IJOL** [comment]
I vote for this enhancement. i often use replicas to get a bigger PVC,  but now I need to scaleout the deployment of the replica make the volume bigger and start replica again, this cumbersome process will be dicthched we were able to set the replica PVC size freely..

**Comment by danielfreithofer** [comment]
you can't set the pvc size, but you might already have a config that works for your project?
i would check with 
`pgo show config <YOUR_POSTGRES_DEPLOYMENT> -n <YOUR_PROJECT_NAMESPACE>`
and if there is one that fits you can use
`pgo scale postgres --replica-count <INT> --storage-config=<NAME_OF_STORAGE_CONFIG> -n <YOUR_PROJECT_NAMESPACE>`
and the operator will provision the replicas with a pvc in the size of the storage configs preset

**Comment by jkatz** [comment]
[PVC resizing](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/update-cluster/#update-pvc-size) was added to [4.7.0](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.7.0/#resize-persistent-volume-claims-resize-pvcs).

The size of a replica PVC can be set directly on the `pgreplicas.crunchydata.com` [custom resource](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/) as well. You typically don't want a replica to be a different size than your other instances if it's in the failover group.

Anyway, I believe there are already multiple paths to handling this.
