### ISSUE TITLE
Can't install metrics infrastructure in On Premise environment

### ISSUE THREAD

**Issue by eliranw** [CrunchyData/postgres-operator#1987]
**Describe the bug**
We have been installing postgres-operator on our on premise environment and upgrading when a new version releases for a few months now. when we upgraded to 4.5.0, we have received errors when helm installing the metrics infrastructure, on the Ansible module that downloads PgMonitor because we are not connected to the network, and can't get_url to httpsL//guthub.com/CrunchyData/pgmonitor etc.. If this was an option that we can override in the helm values it would be helpful.

**To Reproduce**
1. Install metrics infrastructure in an on prem environment without internet.

**Expected behavior**
have an option in the helm values that changes the crunchydata pgmonitor URL

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running: On Prem Env
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag: 4.5.0
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 3.11

**Additional context**

**Comment by eliranw** [comment]
I have fixed this by manually changing the docker image with a URL that has the pgmonitor release tar.gz , though I still prefer a cleaner option

**Comment by jkatz** [comment]
Support for this is now merged in and will be available in 4.6.0 and 4.5.2.
