### ISSUE TITLE
Manual Pgcluster resource creation without pgo client

### ISSUE THREAD

**Issue by Zhuvikin** [CrunchyData/postgres-operator#199]
Is there a way to create new cluster without pgo client installation? The CLI is great but in some cases the fully automated Pgcluster deployment is needed. There should be an ability to default clusters be created after postgres-operator start up.

**Comment by jmccormick2001** [comment]
hmmn,  this is a good question....certainly possible...I'll give it some thought but it could be an interesting one...maybe some sort of init script a user could write then add into the installation or similar.

**Comment by Zhuvikin** [comment]
@jmccormick2001 thank you for the reply! I use helm chart to install operator. I found that PGO client sends request to the apiserver container and it creates new Pgcluster object which is consumed by operator container. I tried to create Pgcluster object manually without pgo client but it seems there are a lot of service fields in the Pgcluster yaml which shouldn't be passed directly.
I think it would be great to add, for example, a Config Map which is listened by apiserver container by default in addition to PGO rest api. Apiserver will react on the changes in this Config Map and adapt configuration of the clusters similarly how PGO client does. Of course we can start with very simple solution first.

**Comment by aduong** [comment]
@Zhuvikin, we actually create Pgclusters without the `pgo` client. The operator appears to do the work of setting up the cluster after that.
> I tried to create Pgcluster object manually without pgo client but it seems there are a lot of service fields in the Pgcluster yaml which shouldn't be passed directly.
Perhaps there should be documentation about the particular fields of the Pgcluster custom resource. I've resorted at the moment to tracing the the code.

**Comment by aelbarkani** [comment]
is there any documentation on how to create and manage the clusters through manifests instead of through pgo client ? we tested the operator and would like to adopt it in production, but it is blocking for us if we cannot configure the cluster through kubernetes manifests

**Comment by jmccormick2001** [comment]
the operator client API currently creates a set of resources when creating a PG cluster....those resources are made up of a) the Secrets that hold the initial default PG credentials, b) the pgcluster CRD that defines the PG cluster, and c) the pgtask CRD that tracks the workflow request

its possible today to create these resources manually but its not documented.  What I might end up doing is reducing these resources to only a pgcluster CRD being required to be created, that would make end users like yourself that want to create PG clusters (by resources) much easier than what it would require currently.  I'll give this some thought, let me know if that is what would work for you.  cheers.

**Comment by aelbarkani** [comment]
definitely yes! creating a unique pgcluster resource would do the job

**Comment by nodanero** [comment]
I've seen using CRDs same way for other operators like "rook ceph" (https://rook.io/docs/rook/v0.9/ceph-block.html), Heptio Ark, CoreOS etcd.
I think is the best way at the moment.
