### ISSUE TITLE
Crunchy operator Postgres  Cluster with LDAP integration

### ISSUE THREAD

**Issue by nkdeepa89** [CrunchyData/postgres-operator#1991]
Trying to enable AD integration with postgres cluster created using crunchy postgres operator. But it is not working as expected. Please suggest some solutions here.

**Comment by jkatz** [comment]
- What is your LDAP provider?
- What does your configuration file look like?
- Do you have any logs that show the errors?
- Are you using `ldap` or `gssapi` in your `pg_hba.conf` file?
