### ISSUE TITLE
Upgrade cluster to postgres 13

### ISSUE THREAD

**Issue by kumy** [CrunchyData/postgres-operator#1992]
**Describe the bug**
Upgrade from postgres 12 to 13 fails with an invalid configuration. Also creating new cluster with image tag `centos7-13.0-4.5.0` while trying to restore a backup from `centos7-12.4-4.5.0` also fails.

**To Reproduce**
case 1:
1. pgo create cluster hippo12  --ccp-image-tag=centos7-12.4-4.5.0
2. pgo  backup create hippo12
3. pgo upgrade --ccp-image-tag=centos7-13.0-4.5.0 hippo12

case 2:
1. pgo create cluster hippo12  --ccp-image-tag=centos7-12.4-4.5.0
2. pgo  backup create hippo12
3. pgo create cluster hippo13 --ccp-image-tag=centos7-13.0-4.5.0 --restore-from hippo12

**Expected behavior**
Cluster should be upgraded to newer postgres version and data restored

**Actual behavior**
The cluster fails to start with a configuration error:
```
[…]
2020-10-21 15:13:29.002 GMT [209] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/pgdata/hippo13/postgresql.conf" line 26
2020-10-21 15:13:29.002 GMT [209] FATAL:  configuration file "/pgdata/hippo13/postgresql.conf" contains errors
[…]
```

**Please tell us about your environment:**

* Operating System: Ubuntu
* Where is this running: Local
* Storage being used: topolvm
* Container Image Tag: centos7-12.4-4.5.0 / centos7-13.0-4.5.0
* PostgreSQL Version: 12.4 / 13.0
* Platform: Kubernetes
* Platform Version: 1.18

**Additional context**
Creating a cluster with 13.0 without restoring data seems to work fine.
I'm new to CrunchyData and in learning/trying process. I may be wrong thinking postgres version could be upgraded like this. I dind't found in the documentation a clear description for such major version upgrade, I may have missed it, feel free to point me to the right page :+1: 
Bests

**Comment by eliranw** [comment]
As far as I know, wal_keep_segments is deprecated in Postgres 13 in favor of wal_keep_size

**Comment by jkatz** [comment]
This is true, per [release notes](https://www.postgresql.org/docs/13/release-13.html):

```
Rename configuration parameter wal_keep_segments to wal_keep_size (Fujii Masao)

This determines how much WAL to retain for standby servers. It is specified in megabytes, rather than number of files as with the old parameter. If you previously used wal_keep_segments, the following formula will give you an approximately equivalent setting:

wal_keep_size = wal_keep_segments * wal_segment_size (typically 16MB)
```

Additionally, neither the Operator nor containers use `wal_keep_size`/`wal_keep_segments`, so this is something in your own custom configuration.

Also, you can't upgrade PostgreSQL using the "Case 2"  method, i.e. you can't restore a cluster from a physical backup from an older PostgreSQL version to a newer one. If you want to perform a major upgrade, you have to use the `crunchy-upgrade` container:

[https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/)

Presently, the Operator itself does not support major upgrades in an automatic fashion. Presently, you would either have to manually invoke the crunchy-upgrade container (referenced above), perform a [`pg_dumpall` type strategy](https://www.postgresql.org/docs/current/app-pg-dumpall.html, or write a customized online upgrade script, which would require a nontrivial effort.

Hope this helps!

**Comment by kumy** [comment]
Hi,
@jkatz thanks for your reply

> Additionally, neither the Operator nor containers use wal_keep_size/wal_keep_segments, so this is something in your own custom configuration.

I'm pretty sure I did not made any custom configuration. I've just used the command above.

Thanks for the link to `crunchy-upgrade` I missed it in the documentation, I was persisting looking into `Crunchy PostgreSQL Operator Documentation`, a link to the `crunchy-upgrade` is probably missing there…

**Comment by eliranw** [comment]
@jkatz 
I know this issue is closed but I have been having issues with this upgrade myself as well.  From what I understand I cant use `pgo upgrade` to upgrade major versions, so is there a different solution with the `pgo` cli or should I `kubectl apply` a crunchy-upgrade container with environment variables according to the docs you referenced?
