### ISSUE TITLE
Root and Replication User requirements

### ISSUE THREAD

**Issue by kevinlmadison** [CrunchyData/postgres-operator#1999]
** Which example are you working with? **
n/a
**What is the current behavior?**
Users called `postgres` and `primaryuser` are created by default.
**What is the expected behavior?**
I would like to be able to set the names and passwords for the superuser and replication user using the operator's rest API when creating a new postgres cluster.
**Other information** (e.g. detailed explanation, related issues,  etc)
I need to know if I can control the names and passwords for the superuser and replication user created during the creation of a new cluster using the operator's rest API. Also, are the names `postgres` and `primaryuser` required by the operator in order to function properly? Where might I find the best and most up to date documentation on the operator's rest API? Thank you!
**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by jkatz** [comment]
> I need to know if I can control the names and passwords for the superuser and replication user created during the creation of a new cluster using the operator's rest API.

These are automatically generated by the Operator, but can be explicitly using the `--password-superuser` and `--password-replication` flags on [`pgo create cluster`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/).

> Also, are the names postgres and primaryuser required by the operator in order to function properly?

Yes.

> Where might I find the best and most up to date documentation on the operator's rest API?

You can reach out to info@crunchydata.com for those docs.
