### ISSUE TITLE
replica pod ran out of space

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#200]
There was a kubernetes node issue that cause the replica pod to be re-created on a different kube node and this caused the replica pod to re-initialize database from primary while keeping the old one.

This cause the replica pod to run out of space and is stuck in crashloop backoff state.

**Comment by jmccormick2001** [comment]
merged in a fix for this into pre27, new replicas should not be created in the same deployment after this fix, ready to retest.
