### ISSUE TITLE
ERROR when create new cluster with restore-from and wal-storage-size

### ISSUE THREAD

**Issue by douggutaby** [CrunchyData/postgres-operator#2003]
**Describe the bug**
I couldn't create new cluster with restore-from when I wanted to use separated storage for WAL.

**To Reproduce**
1. Create clusterold
2. Wait for first full backup
3. Create clusternew with --restore-from and --wal-storage-size
4. Check bootstrap log:
ERROR: [078]: unable to remap invalid link 'pg_wal'

**Expected behavior**
Creating cluster without error.

**Please tell us about your environment:**
* Operating System: OpenShift 4.5 FCOS (Fedora release 32 (Thirty Two))
* Where is this running ( Local , Cloud Provider): Local Cluster on Vsphere
* Storage being used (NFS, Hostpath, Gluster, etc): Rook (cephfs)
* Container Image Tag: crunchydata/pgo-backrest:centos7-4.5.0
* PostgreSQL Version: 4.5.0.
* Platform (Docker, Kubernetes, OpenShift): crictl version
Version: 0.1.0
RuntimeName: cri-o
RuntimeVersion: 1.18.2
RuntimeApiVersion: v1alpha1
* Platform Version: OpenShift 4.5

**Comment by jkatz** [comment]
I believe this is resolved by #1980 and will be available in 4.5.1.

**Comment by douggutaby** [comment]
Thanks, do you know when 4.5.1 will be available?

**Comment by jkatz** [comment]
Patch releases are timed around PostgreSQL software updates. The next [PostgreSQL update is Nov 12](https://www.postgresql.org/developer/roadmap/), so 4.5.1 will be available sometime after that.

For more information on release, please see [https://github.com/CrunchyData/postgres-operator#releases](https://github.com/CrunchyData/postgres-operator#releases).

Thanks!
