### ISSUE TITLE
Not able to use storages 1,2,3 and 4 while creating cluster in postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2008]
Hi there,

We are trying to use different storages for backrest, primary, wal, tablespace1 and tcblespace2 in same cluster.

In our deployer.yaml file we have provide 5,6 and 7 for backrest, primary and wal. And trying to accommodate  stoarge 3 and 4 for tablespace1 and tcblespace2. But when we create a cluster using the command

pgoClientCommand: create cluster hippo-demo --password-superuser qwerty123 --password qwerty123 --pgbouncer --tablespace=name=testtablesapce1:storageconfig=gce-tb1 --tablespace=name=testtablesapce2:storageconfig=gce-tb2

The storages for tablespace are not created. Even the cluster is in updated replicas available status.

Does operator supports this kind of usage?

Please find the screenshots for the same.

![image](https://user-images.githubusercontent.com/50865786/97580077-de892800-1a18-11eb-9b9c-bae23287b7ae.png)

![image](https://user-images.githubusercontent.com/50865786/97580154-f791d900-1a18-11eb-975c-23533ef1a4b4.png)

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
This was a known issue fixed in [4.3.1](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.1).

There have been 3 releases of 4.3.x to date that all contain bug fixes. If you need to remain on 4.3.3, I suggest upgrading to the latest version, 4.3.3.
