### ISSUE TITLE
A way to safely delete incremental backups from s3 storage

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#2009]
Good day!
Is there a way to delete incremental backups from s3 bucket without manually deleting files and directories (which will lead to violating initial backup folders structure)?

We have created schedule with the command shown below:
pgo create schedule pgsql-cluster -n pgo --schedule-type=pgbackrest --pgbackrest-backup-type=incr --pgbackrest-storage-type=s3 --schedule="1 */3 * * *"

So, we don't specify retention when created it. So bucket increasing space usage.

Environment:
Google Kubernetes Engine cluster
Container Image Tag: crunchy-postgres-ha:centos7-12.4-4.5.0
Platform Version: 1.17.9-gke.6300

**Comment by jkatz** [comment]
This is discussed in the "[Set Backup Retention](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/#set-backup-retention)" section, which is similar to "[setting retention policies](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#setting-backup-retention-policies)" section of the documentation.

You can also update (or recreate) your backup schedule to set a retention policy. pgBackRest evaluates the retention policy each time you set it.

If you want to use a time-based retention policy, you can do so in Operator 4.5. This syntax is covered in the [pgBackRest](https://pgbackrest.org/) documentation.
