### ISSUE TITLE
Add capability to scale down pg cluster using pgo

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#201]
pgo can be used to scale pg cluster. But, there is no easy way to scale down a cluster by deleting a replica.

**Comment by jmccormick2001** [comment]
@jkatz

**Comment by jmccormick2001** [comment]
I've merged into pre32 the following new commands:

pgo scale mycluster --query
pgo scale mycluster --scale-down-target=xxxxx --delete-data

I've updated the docs for this to describe it, there are 2 new API calls for this feature.
