### ISSUE TITLE
Backup creation fails when using minio with GCS gateway in GKE (WAL segment timeout)

### ISSUE THREAD

**Issue by AbbasgoriS4** [CrunchyData/postgres-operator#2012]
** Which example are you working with? **
When I try to create a Postgres cluster by running pgo create cluster (name) command backrest-backup job fails with the ERROR: [082]: WAL segment 000000010000000000000006 was not archived before the 60000ms timeout. I tried running pgbackrest backup command inside pgbackrest pod the error is same.

**What is the current behavior?**
The backrest-backup job get succeed only with --pgbackrest-storage-type=local but it fails with --pgbackrest-storage-type=s3

**What is the expected behavior?**
Complete the backup and push it to the remote repo.

**Other information** (e.g. detailed explanation, related issues,  etc)
crunchy data operator version: 4.4.0
pgbackrest version: 2.27
I'm pasting the postgresql.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

archive_command = 'source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push "%p"'
archive_mode = 'True'
archive_timeout = '60'
cluster_name = '(cluster-name)'
hot_standby = 'on'
listen_addresses = '0.0.0.0'
log_directory = 'pg_log'
log_min_duration_statement = '60000'
log_statement = 'none'
max_connections = '100'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '6'
max_worker_processes = '8'
port = '5432'
shared_buffers = '128MB'
shared_preload_libraries = 'pgaudit.so,pg_stat_statements.so'
temp_buffers = '8MB'
track_commit_timestamp = 'off'
unix_socket_directories = '/tmp,/crunchyadm'
wal_keep_segments = '8'
wal_level = 'logical'
wal_log_hints = 'on'
work_mem = '4MB'
hba_file = '/pgdata/pgo-minio/pg_hba.conf'
ident_file = '/pgdata/pgo-minio/pg_ident.conf'

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider)
Google Kubernetes engine

* Storage being used (NFS, Hostpath, Gluster, etc):
GCE

* Container Image Tag:
centos7-12.3-4.4.0

* PostgreSQL Version:
12.3

* Platform (Docker, Kubernetes, OpenShift):
Kubernetes

* Platform Version:
1.15.12-gke.20

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
Name:               backrest-backup-pgo-minio-258lz
Namespace:          ansible
Priority:           0
PriorityClassName:  <none>
Node:               gke-internal-cluster-internal-pool-7cd04009-lkfq/10.128.15.196
Start Time:         Fri, 30 Oct 2020 20:45:52 +0530
Labels:             backrest-command=backup
                    controller-uid=9e4847ca-3e77-40c3-ba45-a4eaeb070ced
                    job-name=backrest-backup-pgo-minio
                    pg-cluster=pgo-minio
                    pgo-backrest=true
                    pgo-backrest-job=true
                    vendor=crunchydata
Annotations:        <none>
Status:             Failed
IP:                 10.0.0.206
Controlled By:      Job/backrest-backup-pgo-minio
Containers:
  backrest:
    Container ID:   docker://dba0330550bc0eba5d06f1cea97cf15578eeb7321159d132758be7f3848a726a
    Image:          registry.developers.crunchydata.com/crunchydata/pgo-backrest:centos7-4.4.0
    Image ID:       docker-pullable://registry.developers.crunchydata.com/crunchydata/pgo-backrest@sha256:014bf42ad3562efa8659349e2ee34ba765889252ce954b214c672895a01828c7
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 30 Oct 2020 20:45:53 +0530
      Finished:     Fri, 30 Oct 2020 20:49:42 +0530
    Ready:          False
    Restart Count:  0
    Environment:
      COMMAND:                           backup
      COMMAND_OPTS:                      --type=full --db-host=10.0.1.87 --db-path=/pgdata/pgo-minio
      PITR_TARGET:                       
      PODNAME:                           pgo-minio-backrest-shared-repo-7c7b5f496f-skcxn
      PGBACKREST_STANZA:                 
      PGBACKREST_DB_PATH:                
      PGBACKREST_REPO_PATH:              
      PGBACKREST_REPO_TYPE:              s3
      PGHA_PGBACKREST_LOCAL_S3_STORAGE:  false
      PGHA_PGBACKREST_S3_VERIFY_TLS:     false
      PGBACKREST_LOG_PATH:               /tmp
      NAMESPACE:                         ansible (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-backrest-token-crbl2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  pgo-backrest-token-crbl2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgo-backrest-token-crbl2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName
time="2020-10-30T15:15:53Z" level=info msg="pgo-backrest starts"
time="2020-10-30T15:15:53Z" level=info msg="debug flag set to false"
time="2020-10-30T15:15:53Z" level=info msg="backrest backup command requested"
time="2020-10-30T15:15:53Z" level=info msg="s3 flag enabled for backrest command"
time="2020-10-30T15:15:53Z" level=info msg="command to execute is [pgbackrest backup --type=full --db-host=10.0.1.87 --db-path=/pgdata/pgo-minio --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2020-10-30T15:15:53Z" level=info msg="command is pgbackrest backup --type=full --db-host=10.0.1.87 --db-path=/pgdata/pgo-minio --repo1-type=s3 --no-repo1-s3-verify-tls "
time="2020-10-30T15:19:42Z" level=error msg="command terminated with exit code 82"
time="2020-10-30T15:19:42Z" level=info msg="output=[]"
time="2020-10-30T15:19:42Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\nERROR: [082]: WAL segment 000000010000000000000012 was not archived before the 60000ms timeout\n       HINT: check the archive_command to ensure that all options are correct (especially --stanza).\n       HINT: check the PostgreSQL server log for errors.\n]"
time="2020-10-30T15:19:42Z" level=error msg="command terminated with exit code 82"

**Comment by jkatz** [comment]
The output provides two pieces of information that would help:

```
HINT: check the archive_command to ensure that all options are correct (especially --stanza).
HINT: check the PostgreSQL server log for errors.
```

- What is the value of the `archive_command`?
- What do the PostgreSQL logs themselves say? These are in the `pg_log` directory in the `/pgdata` directory of your PostgreSQL Pod.

**Comment by AbbasgoriS4** [comment]
The value of **archive_command** is **'source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push "%p"'**
and the **log inside pg_log directory is**
2020-10-30 14:51:35.923 UTC [174] LOG:  database system was shut down at 2020-10-30 14:51:35 UTC
2020-10-30 14:51:35.924 UTC [175] FATAL:  the database system is starting up
2020-10-30 14:51:35.934 UTC [171] LOG:  database system is ready to accept connections

**Comment by jkatz** [comment]
Do you have logs from the PostgreSQL instance during the failure?

More likely than not, there is an incorrect configuration that is causing authentication to fail between pgBackRest and MinIO, which is why the `archive_timeout` is being reached.

**Comment by AbbasgoriS4** [comment]
There are no failure logs from PostgreSQL but here is what I see in logs all the time
**2020-11-02 05:12:46,167 INFO: Lock owner: pgo-minio-6dfd679dcb-cxdg2; I am pgo-minio-6dfd679dcb-cxdg2
2020-11-02 05:12:46,217 INFO: no action.  i am the leader with the lock**

and I am not sure about authentication is wrong because it's able to create and store tar files inside the bucket. It is creating two folders that are archive and backup and it's storing all the tar files into it.

**Comment by AbbasgoriS4** [comment]
I ran **pgbackrest backup --repo1-retention-full=2 --archive-timeout=60 --db-host=10.0.1.85 --db-path=/pgdata/pgo-minio --repo1-type=s3 --no-repo1-s3-verify-tls --log-level-console=detail** inside pgbackrest pod and these are the last logs from it.

**2020-11-02 07:47:52.955 P01   INFO: backup file 10.0.1.87:/pgdata/pgo-minio/base/1/13174 (0B, 100%)
2020-11-02 07:47:53.065 P01   INFO: backup file 10.0.1.87:/pgdata/pgo-minio/base/1/13169 (0B, 100%)
2020-11-02 07:47:53.066 P00   INFO: full backup size = 31MB
2020-11-02 07:47:53.066 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2020-11-02 07:47:53.268 P00   INFO: backup stop archive = 000000010000000000000016, lsn = 0/16000050
2020-11-02 07:47:53.488 P00 DETAIL: wrote 'backup_label' file returned from pg_stop_backup()
2020-11-02 07:47:53.589 P00   INFO: check archive for segment(s) 000000010000000000000015:000000010000000000000016
ERROR: [082]: WAL segment 000000010000000000000015 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
2020-11-02 07:48:54.772 P00 DETAIL: socket statistics: objects 2, sessions 4, retries 0
2020-11-02 07:48:54.772 P00 DETAIL: tls statistics: objects 2, sessions 4, retries 0
2020-11-02 07:48:54.772 P00   INFO: http statistics: objects 2, sessions 4, requests 23, retries 2, closes 0
2020-11-02 07:48:54.772 P00   INFO: backup command end: aborted with exception [082]**

I even tried with timeout 1800s but it just waited for 30m and then failed with the same error.

**Comment by dwarburt** [comment]
FWIW, I'm getting exactly the same thing trying to use the S3 storage with a Digital Ocean Spaces "bucket".

I'm using this backup command: `pgo backup grafanadb2 --pgbackrest-storage-type=s3 --backup-opts="--type=full"`
and the backrest-backup-grafanadb2-etc pod log file says this:
```
time="2020-11-13T01:52:57Z" level=info msg="pgo-backrest starts"
time="2020-11-13T01:52:57Z" level=info msg="debug flag set to false"
time="2020-11-13T01:52:57Z" level=info msg="backrest backup command requested"
time="2020-11-13T01:52:57Z" level=info msg="s3 flag enabled for backrest command"
time="2020-11-13T01:52:57Z" level=info msg="command to execute is [pgbackrest backup --type=full --db-host=10.244.2.163 --db-path=/pgdata/grafanadb2 --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2020-11-13T01:52:57Z" level=info msg="command is pgbackrest backup --type=full --db-host=10.244.2.163 --db-path=/pgdata/grafanadb2 --repo1-type=s3 --no-repo1-s3-verify-tls "
time="2020-11-13T01:56:33Z" level=error msg="command terminated with exit code 82"
time="2020-11-13T01:56:33Z" level=info msg="output=[]"
time="2020-11-13T01:56:33Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space
      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
ERROR: [082]: WAL segment 00000003000000000000009E was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
]"
time="2020-11-13T01:56:33Z" level=error msg="command terminated with exit code 82"
```
But I have a second cluster that's also using the same command and works fine. Both clusters are writing *some* files to the bucket, but only one can do the full backup.

(second cluster, that works correctly)
```
time="2020-11-13T02:06:36Z" level=info msg="pgo-backrest starts"
time="2020-11-13T02:06:36Z" level=info msg="debug flag set to false"
time="2020-11-13T02:06:36Z" level=info msg="backrest backup command requested"
time="2020-11-13T02:06:36Z" level=info msg="s3 flag enabled for backrest command"
time="2020-11-13T02:06:36Z" level=info msg="command to execute is [pgbackrest backup --type=full --db-host=10.244.1.154 --db-path=/pgdata/armigerdb2 --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2020-11-13T02:06:36Z" level=info msg="command is pgbackrest backup --type=full --db-host=10.244.1.154 --db-path=/pgdata/armigerdb2 --repo1-type=s3 --no-repo1-s3-verify-tls "
time="2020-11-13T02:08:31Z" level=info msg="output=[]"
time="2020-11-13T02:08:31Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space
      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
]"
time="2020-11-13T02:08:31Z" level=info msg="pgo-backrest ends"
```

**Comment by jkatz** [comment]
- Are there logs from MinIO that could indicate an error?
- Where there communication errors between MinIO and the external object storage system at the time?
