### ISSUE TITLE
Ampersand in PGBACKREST_REPO1_S3_KEY_SECRET breaks script.

### ISSUE THREAD

**Issue by SockenSalat** [CrunchyData/postgres-operator#2024]
I am currently experimenting with the Multi-Cluster-Standby _stuff_ and I experienced the following problem:

When trying to create a Standby-Cluster from S3 the procedure _hung_, after inspecting the logs I found the following:

`/tmp/pgbackrest_env.sh: line 6: EGUJYH: command not found`

a look into this script showed that the `PGBACKREST_REPO1_S3_KEY_SECRET` included an `&` just before the `EGUJYH`.

Might be a good Idea to use `"` in such scripts.

Operator Image being used: `4.5.0`

**Comment by SockenSalat** [comment]
the same is true for `;`

**Comment by jkatz** [comment]
This has been fixed and is backpatched to 4.5, 4.4, and 4.3. Thank you for reporting!
