### ISSUE TITLE
Disable the backup feature on chruncy operator 4.5.0

### ISSUE THREAD

**Issue by jatindersandhu** [CrunchyData/postgres-operator#2025]
Hi,
    I know on operator 4.5.0 by default backup is taken when cluster is created with pgo command. In our setup we do not need backup as postgres is not source of truth in our case. We get data from teradata so if DB is corrupt we can recreate everything. Now every time postgres get restarted backup start happening. We have allocated very minimum 1 GB pvc to backup as is required in pgo.yaml. It filled up so easily , even I try to create archive_command /bin/true. it is also give issue
Here are ERROR On backup pod
time="2020-11-06T18:19:11Z" level=info msg="output=[]"
time="2020-11-06T18:19:11Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\nERROR: [068]: archive_command '/bin/true' must contain pgbackrest\n]"
time="2020-11-06T18:19:11Z" level=error msg="command terminated with exit code 68"

**Comment by jkatz** [comment]
The backup architecture is designed inline with PostgreSQL best practices. You can read about the architecture here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/)
