### ISSUE TITLE
Operator version selection operatorhub.io

### ISSUE THREAD

**Issue by jatindersandhu** [CrunchyData/postgres-operator#2026]
We used to install chruncy operator from operatorhub.io as this is only supported by Openshift.  Operatorhub.io does not allow us to select older version. This is creating huge problem for us as we want same version of operator in UAT and PROD. Now in our UAT we have 4.4.1 version and PROD 4.5.0. Every new version we have to fix deployment issue as what we did in UAT is not valid.

For example collect.json is not valid file in 4.5.0. but openshift 4.5 version need minimum memory request 32 MB. Although we figure out how to change memory request using pgo. 
But these minor changes affect our project timeline. 

**_We need ability to select version OPERATORHUB.IO ,_**

**Comment by jkatz** [comment]
I believe you need to talk to the [OperatorHub folks](https://github.com/operator-framework/community-operators) about this and find out what their recommendation is.

You can find out more about [production support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) here: [https://access.crunchydata.com/documentation/postgres-operator/latest/support/](https://access.crunchydata.com/documentation/postgres-operator/latest/support/)

**Comment by jatindersandhu** [comment]
Thanks for your answer, We talk with them.. Operatorhub.io said it is vendor(Chruncydata) who control the version and There are other operator like redis which give us ability to select version

**Comment by jkatz** [comment]
We typically follow the guidance from the OperatorHub folks so would likely need additional information from them on how to make these updates.

**Comment by jatindersandhu** [comment]
Thanks for Answer, I raise the question with them waiting for answer
