### ISSUE TITLE
2 node cluster?

### ISSUE THREAD

**Issue by bodleytunes** [CrunchyData/postgres-operator#2027]
I know its bad (terrible) design as there would be no quorum, but I was wondering if I for testing I could force Crunchy to balance over a 2 node cluster (K3S)

I'm currently running rancher k3s but I have only 2 nodes available.   When I deploy pgo, I can see the operator ends up one node and all the other database nodes end up squashed up on the opposite node.

I was wondering if there was a way I could balance them between both nodes, at least for testing purposes?  I had a look at the affinity rules but still they end up on one node as if they cant live next to the operator.

I'm not clued up on databases hence this might be a silly question, but thought I'd ask anyway as at least I'd learn something!

Cheers!
Jon.

**Comment by jkatz** [comment]
You would likely want a more aggressive pod anti-affinity setting, particularly `required`:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/#how-the-crunchy-postgresql-operator-uses-pod-anti-affinity](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/#how-the-crunchy-postgresql-operator-uses-pod-anti-affinity)

Given you only have two nodes, this would cause one of the Pods to become unschedulable as there is also the pgBackRest repo, so you may want to create the cluster with `--pod-anti-affinity=required --pod-anti-affinity-pgbackrest=preferred` ([`pgo create cluster`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) reference).

The node affinity uses `preferred` scheduling by default. You would have to modify the `affinty.json` to use the "required" rules, which is described [here](https://github.com/CrunchyData/postgres-operator/issues/1907#issuecomment-696798258). The reason I suggest the pod anti-affinity method above for this exercise is that it is better for production environments, though I figure your K3S instance is not being employed for that.

**Comment by bodleytunes** [comment]
Thanks I'll look at those settings.
