### ISSUE TITLE
After a create cluster with --restore-from pgo df for that cluster gives an error..

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#2029]
**Describe the bug**
After a create cluster with --restore-from pgo df for that cluster gives an error..

```
nacho@hippo14:~/svn/k8s/production$ pgo show cluster genrios
Handling connection for 8444

cluster : genrios (crunchy-postgres-ha:centos7-12.4-4.5.0)
	pod : genrios-6bb4bb8c7b-gcgr7 (Running) on pan.bitvax.com (1/1) (primary)
		pvc: genrios (8Gi)
	resources : Memory: 128Mi
	deployment : genrios
	deployment : genrios-backrest-shared-repo
	service : genrios - ClusterIP (10.43.255.12)
	labels : autofail=true name=genrios pg-cluster-id= pgo-version=4.5.0 workflowid=c6523a79-dd68-4aaf-a3da-eec59bcf84ba crunchy-pgbadger=false deployment-name=genrios pg-cluster=genrios pgouser=admin backrest-storage-type=local crunchy-pgha-scope=genrios crunchy-postgres-exporter=false custom-config=pgo-custom-pg-config pg-pod-anti-affinity= pgo-backrest=true 
nacho@hippo14:~/svn/k8s/production$ pgo df genrios
Handling connection for 8444
Error: 

```
**To Reproduce**
Create a cluster with --restore-from

**Additional context**

It's a completelñy new uncustomized at all operator 4.5.0 install with storage provided by longhorn (BTW check longhorn it is awesome)

**Comment by jkatz** [comment]
- Are all of the Pods in the cluster up and available?
- Are you using an external WAL PVC or tablespaces?

**Comment by IJOL** [comment]
Yes and NO for the question, I suspect that the bootstrap pod is being
used, and hence de error, nothing apart from normal is a barebones 4.5.0
install,  the only thing that we are doing what we weren't doing already is
the restore-from thing..


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by IJOL** [comment]
My suspicion was correct deleting the bootstrap pod did the trick, I now get pgo df from restore-from clusters.. it's fine as a workaround for me I was a little uneasy about that problem, but now it's pretty simple under the morning lights.. ;)  something to look at in the upcoming release..

**Comment by jfmatth** [comment]
I had the exact issue happen to me on MicroK8s.  Deleting the bootstrap POD did the trick!

**Comment by jkatz** [comment]
Thanks for the report. I agree, this sounds like a bug. Treating it as so.
