### ISSUE TITLE
Under which circunstances a pgdata cluster directory ends being renamed to something_2020-11-08...

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#2030]
```
local crunchy-pgbadger=false crunchy-pgha-scope=cweb pg-cluster=cweb 
nacho@hippo14:~/svn/k8s/production$ kexec pgo cweb-bf ls -l /pgdata/
total 20
drwx--S--- 20 postgres postgres  4096 Nov  8 00:00 cweb
drwxrws---  2 root     postgres 16384 Oct 19 08:55 lost+found
nacho@hippo14:~/svn/k8s/production$ kexec pgo ^etl ls -l /pgdata/
total 24
drwx------ 20 postgres postgres  4096 Nov  8 17:12 etl
drwx--S--- 20 postgres postgres  4096 Nov  8 17:12 etl_2020-11-08-17-12-01
drwxrws---  2 root     postgres 16384 Sep 27 13:36 lost+found
nacho@hippo14:~/svn/k8s/production$ 

```
These two clusters were recovered using our volume manager and restored in the same way, but the second one gets the cluster directory etl , renamed to etl_2020-11-08-17-12-01

I assumed we will be the culprits of this one, only trying to learn to avoid'em

**Comment by jkatz** [comment]
This is created as part of the `--restore-from` process. I believe if the restore is successful it is supposed to be cleaned up, but need to double check with @andrewlecuyer on that one.

**Comment by IJOL** [comment]
I'm getting this directory from a non restore-from cluster, it's a clean
cluster, almost all others worked as expected doing the
backup/restore through the volume system.. it's an unrelated problem, but
very annoying, the db that failed to come up, were very tiny , but the same
with 1 Tb will be different..


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by IJOL** [comment]
To be clear about that, we recovered almost all of our databases
without a glitch using the volume backup/restore capabilities, except
this one and another, of course, we suspect that there are a file or a
file will be not present, that makes the starting process rename the
pgdata dir,  hence the question, is not related to the other
problems..


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by IJOL** [comment]
@jkatz This continues being an open question for me there was a glitch, It needs to have some sort of explanation, to be able to avoid such problems in future

**Comment by jkatz** [comment]
We made various improvements to how restore and recovery are handled in [4.6.0](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.6.0/) with anything considered a bug fix backpatched to currently supported versions. In case of larger databases, we try to avoid the directory rename so we can perform a delta restore, e.g. https://github.com/CrunchyData/postgres-operator/commit/a8bd519aa3881c011fdfa965d08c6eace1f98ef1

If you are looking for additional troubleshooting, you can read about the various [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) options.
