### ISSUE TITLE
Deleting old clusters doesn't remove them from the metrics infrastructure

### ISSUE THREAD

**Issue by eliranw** [CrunchyData/postgres-operator#2031]
**Describe the bug**
We are using the metrics infrastructure, and want it to show the environment like it is. When we delete old pgclusters, they can still be chosen in the grafana, and right now because of testing we have deleted and recreated all old clusters, and more than half of the clusters in grafana don't exist anymore. Is there a way to resync the grafana dashboards to the current environment? 

**To Reproduce**
1. Create Metrics infrastructure
2. Create a few clusters
3. Delete a few clusters
4. Deleted clusters still exist in the grafana dashboards.

**Expected behavior**
Old clusters won't be seen anymore

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running: On prem
* Storage being used :
* Container Image Tag: 12.4-4.5
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version:

**Additional context**
If this can be solved somehow manually from deleting the prometheus data PVC (as we aren't production yet and it's ok to lose data), then it is fine, but I'd prefer something more automated and less involved with deleting data 😞

**Comment by jkatz** [comment]
This is based on how Prometheus is retaining data. As the monitoring stack can be deployed into an arbitrary Prometheus setup, we cannot make assumptions on how one would like to retain data in their environment. You should be able to tweak Prometheus in that regard, but this is out of scope for the Operator.
