### ISSUE TITLE
Does postgres operator v4.5 supports service annotations

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2033]
Does postgres operator v4.5 supports service annotation out of the box.
Like external DNS 

kubectl patch svc <SRV-Name> -p '{"metadata": {"annotations": { "external-dns.alpha.kubernetes.io/hostname": "<SVCName>.<Namespace>.<DNS-Zone-Name>"}}}' -n <Namespace>

**Comment by jkatz** [comment]
You can modify the `cluster-service.json` template that is stored in `pgo-config`. The default file looks like this:

[https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/cluster-service.json](https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/cluster-service.json)
