### ISSUE TITLE
Synchronous Replication - is it possible to specify synchronous_commit=remote_apply?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2034]
Hello,

We are currently using pgo 4.5.0.

We want to put in place some clusters with Replicas. These clusters "should not" lose any transactions in case the replica take the master role.
The ideal case is to use synchronous replication with "synchronous_commit = on". This will ensure the replica is up to date with the master. However, this has an impact on the speed of write-queries.... I know we cannot have every thing :-)

I believe that we could accept the risk of using synchronous replication with "synchronous_commit=remote_apply". This will reduce the extra time needed to wait. Refer to https://www.postgresql.org/docs/11/warm-standby.html#SYNCHRONOUS-REPLICATION.

So our questions:

- What is the "synchronous_commit" type applied when we set --sync-replication option when creating a cluster with pgo?
- Is there any way to specify that we want either "synchronous_commit = on" or "synchronous_commit = remote_apply"?

Thanks a lot,
José

**Comment by jkatz** [comment]
> What is the "synchronous_commit" type applied when we set --sync-replication option when creating a cluster with pgo?

[`on` -- this is the PostgreSQL default](https://www.postgresql.org/docs/13/runtime-config-wal.html#GUC-SYNCHRONOUS-COMMIT).

> Is there any way to specify that we want either "synchronous_commit = on" or "synchronous_commit = remote_apply"?

You would update the `synchronous_commit` parameter in the PostgreSQL configuration block in the ConfigMap.

@andrewlecuyer made a nice blog post on [synchronous replication in the Postgres Operator](https://info.crunchydata.com/blog/synchronous-replication-in-the-postgresql-operator-for-kubernetes-guarding-against-transactions-loss) here:

[https://info.crunchydata.com/blog/synchronous-replication-in-the-postgresql-operator-for-kubernetes-guarding-against-transactions-loss](https://info.crunchydata.com/blog/synchronous-replication-in-the-postgresql-operator-for-kubernetes-guarding-against-transactions-loss)

As you note, there is a speed / safety tradeoff when tweaking `synchronous_commit`. However, upon consulting with those smarter than me, I would say that the decision tree is a bit more complicated. Detailing out what each setting does:

- `on` -- ensures a sync replica writes the WAL record to disk.
- `remote_apply` -- ensures a sync replica applies the transaction so its visible on the replica.
- `remote_write` -- ensures a sync replica writes the WAL record to the kernel -- it is not necessarily sync'd to the disk yet, but does not guard against losing data if the kernel crashes.

`remote_apply` may *not* be faster, you would have to do some testing. `remote_write` *should* be faster, but there is risk of data loss.

**Comment by jose-joye** [comment]
@jkatz : Many thanks for the detailled answer!
I will test this

José
