### ISSUE TITLE
ccp_pg_stat_statments metrics

### ISSUE THREAD

**Issue by yangvipguang** [CrunchyData/postgres-operator#2036]
** Which example are you working with? **
I have installed pg operator with the latest version(4.5).  I want to monitoring with pg stat statments metrics. but the pg exporter has no any pg stat metrics like below：
![image](https://user-images.githubusercontent.com/11416887/98625227-2d548d00-234a-11eb-8f40-b7d505823390.png)

I can see that the query files has been added in the monitor。
![image](https://user-images.githubusercontent.com/11416887/98625422-891f1600-234a-11eb-95fd-2979baa28c8c.png)

* Operating System:
* Where is this running ( Local , Cloud Provider)  cloud provider
* Storage being used (NFS, Hostpath, Gluster, etc): nas
* Container Image Tag:  4.5
* PostgreSQL Version:  4.5
* Platform (Docker, Kubernetes, OpenShift):  K8S
* Platform Version: 1.16

**Comment by yangvipguang** [comment]
@jkatz  and  could  you give me some advice how to implement like this。
https://www.postgresql.eu/events/pgconfeu2018/sessions/session/2166/slides/147/monitoring.pdf

**Comment by jkatz** [comment]
The ability to pull `pg_stat_statement` metrics was just added as of the 4.5.1 release. For a direct integration, we will wait for the pgMonitor project to provide a dashboard that can be integrated into the [Postgres Operator Monitoring](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/) solution.

**Comment by yangvipguang** [comment]
@jkatz   I have just upgraded to 4.5.1 version. But I still can't find the pg_stat_statement  metrics.

**Comment by jkatz** [comment]
The query files were missing as part of loading the information into the exporter. This change has been added in and backpatched down to `4.5`.

If need be, you could follow the logic that is presented in the pull request and apply those changes to the `queries.yml` file that exists within the `exporter` container.
