### ISSUE TITLE
Operator version

### ISSUE THREAD

**Issue by jatindersandhu** [CrunchyData/postgres-operator#2039]
We are using crunchy operator for our  postgresql. We do not have any HA requirements. We use openshift certified channel to install the operator. Problem installing operator from there is that everytime new version available,, now we have three version of operator in UAT and PROD. Can this is possible to create different channel for different version. Like photo below Redis operator give the way to select different version but chruncy does not give this.
May be I am raising this question multiple time but we need ability to control the version.
![image (2)](https://user-images.githubusercontent.com/45833435/98698264-d8ae1380-2343-11eb-8d22-065e658af22e.png)
![image (1)](https://user-images.githubusercontent.com/45833435/98698269-d946aa00-2343-11eb-8cef-cd4d0831a3fb.png)

**Comment by jatindersandhu** [comment]
any update please

**Comment by jatindersandhu** [comment]
Please let me know if it possible .. otherwise we have to leave this operartor solution and go for some other solution because we can not sustain version change like this.

**Comment by jkatz** [comment]
Repeated asking has a tendency to exponentiate answering time. I recommend reading our [support guide](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) around this.

As mentioned in #2026, this needs to be discussed with the OperatorHub folks as they have set up the various channels. I have a note to reach out to them directly at some point.

**Comment by jatindersandhu** [comment]
ok

**Comment by jkatz** [comment]
I've reached out to some of the Red Hat folks to figure out the best path forward.

**Comment by jatindersandhu** [comment]
Thanks.. I reached out even operatorhub.io they said they only manage community version. Not Red Hat certify channel. I love this operator as whole solution but our requirement here is very less but management want keep same version otherwise they do not want this operator if version can not control . I reaching out Red-hat , operatorhub.io and you just to find where to ping to find solution

**Comment by jkatz** [comment]
I spoke with our friends at Red Hat. One of their suggestions is that you can pin the current version of the Postgres Operator by setting `subscription.spec.currentCSV` to pin the `stable` channel to a specific CSV, e.g. ‘postgresoperator.v4.5.0’ if that is what you want to use, and to set `installPlanApproval: Manual` to make sure you're not automatically updating. I was informed that this solution can be generally applied to other Operators as well.

If you would like to discuss more specific solutions or would like to further coordinate with Red Hat, please reach out at info@crunchydata.com.

**Comment by jatindersandhu** [comment]
Thanks for answer.. But pin is not solution for us as we have 4.4.1 in uat and 4.5.0 is in prod. By the time we get approval to upgrade UAT to 4.5.0 version (because of holidays it might take few month) they might be high chance that 4.5.0 version might not available in OC catalog. In Redis we can have multiple version because they give us multiple channels (one for stable or current version, others for older version). In Chruncy we do have only one stable channel. May be we can not have multiple channel solution like Redis. I will also send email to info@crunchdata.com
