### ISSUE TITLE
Cannot look at logs in pgbouncer container /var/log/pgbouncer due to permission denied

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#2041]
pgo ver 4.3.2

trying to debug potential issue with pgbouncer but when I exec into the container I cannot look at logs in /var/log/pgbouncer due to permission denied.  How can I look at logs in that container to debug issues with pgbouncer (not kubectl logs not showing all logs).  What other ways to debug pgbouncer?

**Comment by jkatz** [comment]
The default for pgBouncer logging is to output to `/dev/stdout`, which puts it into STDOUT vis-a-vis `kubectl logs`.

Based on what you are looking to debug, you may need to raise the verbosity of the logs:

[https://www.pgbouncer.org/config.html#log-settings](https://www.pgbouncer.org/config.html#log-settings).

4.5.0 makes it easier to configure pgBouncer as it keeps the configuration in a ConfigMap. In earlier versions, you can apply custom settings by updating the `/pgconf/pgbouncer.ini` file and reloading, or via the pgbouncer commands.
