### ISSUE TITLE
Not able to set the pgbouncer user password using pgo client

### ISSUE THREAD

**Issue by vg02111989** [CrunchyData/postgres-operator#2045]
Hi,

I am using the latest PGO version 4.5.0 which has the capability to connect to db via pgbounce service.

I am using the below command to create the cluster along with pgbouncer, but as mentioned in the docs, I am not able to set the password of pgbouncer user by using command

pgo create cluster dbcluster --pgbouncer --replica-count=1 --pgbouncer-pass=pgadmin123 --password-superuser=admin@1234 -n go

I am getting error -- 
Error: unknown flag: --pgbouncer-pass
Usage:
  pgo create cluster [flags]

**Comment by jkatz** [comment]
This is discussed here: [https://access.crunchydata.com/documentation/postgres-operator/4.5.0/tutorial/pgbouncer/#rotate-pgbouncer-password](https://access.crunchydata.com/documentation/postgres-operator/4.5.0/tutorial/pgbouncer/#rotate-pgbouncer-password)

As pgBouncer is a system managed service, we do not directly expose its password. However, you can access its password from the pgBouncer Secret that is located alongside the pgBouncer Deployment.
