### ISSUE TITLE
Cluster does not start because of SSL error

### ISSUE THREAD

**Issue by andrei-matei** [CrunchyData/postgres-operator#2048]
** Which example are you working with? **
I installed postgres-operator 4.5.0

**What is the current behavior?**
After successfully installing the operator and pgo client, I open port forward 8443 to the Kubernetes service and try to connect the first cluster. Backrest pod gets created and started, the cluster pod gets created, but after starting Patroni, I get a SSL Error when it tries to call the Kubernetes API Server. I can see in the logs of API Server "Unknown certificate authority".

**What is the expected behavior?**
To be able to start the cluster without SSL error.

**Other information** (e.g. detailed explanation, related issues,  etc)
Error in hippo (example cluster):

`Thu Nov 12 17:33:03 UTC 2020 INFO: Applying SSHD..
Thu Nov 12 17:33:03 UTC 2020 INFO: Checking for SSH Host Keys in /sshd..
Thu Nov 12 17:33:03 UTC 2020 INFO: Checking for authorized_keys in /sshd
Thu Nov 12 17:33:03 UTC 2020 INFO: Checking for sshd_config in /sshd
Thu Nov 12 17:33:03 UTC 2020 INFO: setting up .ssh directory
Thu Nov 12 17:33:03 UTC 2020 INFO: Starting SSHD..
Thu Nov 12 17:33:03 UTC 2020 INFO: Starting background process to monitor Patroni initization and restart the database if needed
Thu Nov 12 17:33:03 UTC 2020 INFO: Initializing cluster bootstrap with command: '/usr/local/bin/patroni /tmp/postgres-ha-bootstrap.yaml'
Thu Nov 12 17:33:03 UTC 2020 INFO: Running Patroni as PID 1
2020-11-12 17:33:03,679 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),)': /api/v1/namespaces/pgo/configmaps?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo
2020-11-12 17:33:03,682 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),)': /api/v1/namespaces/pgo/pods?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo
2020-11-12 17:33:03,685 ERROR: Request to server https://10.32.0.1:443 failed: MaxRetryError("HTTPSConnectionPool(host='10.32.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/pgo/configmaps?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))",)
2020-11-12 17:33:03,688 ERROR: Request to server https://10.32.0.1:443 failed: MaxRetryError("HTTPSConnectionPool(host='10.32.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/pgo/pods?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))",)
2020-11-12 17:33:04,685 ERROR: ObjectCache.run TypeError("unsupported operand type(s) for -: 'NoneType' and 'float'",)`

**Please tell us about your environment:**
Kubernetes 18.10, on-peremise install using Kubeadm, with 3 master nodes using HAProxy as a load balancer and 6 worker nodes

* Operating System: CentOS 7.8.2003 (Core)
* Host machine: local ESXi home-lab
* Storage being used (NFS, Hostpath, Gluster, etc): Rook-Ceph block
* Container Image Tag: 4.5.0
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 18.10

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
`Events:
  Type     Reason                  Age                 From                     Message
  ----     ------                  ----                ----                     -------
  Normal   Scheduled               11m                 default-scheduler        Successfully assigned pgo/hippo-597db64794-tx9z6 to worker02.fineas.vienna.devopslog.eu
  Normal   SuccessfulAttachVolume  11m                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-4569be54-f0e2-4c32-9189-1ccb689b68ac"
  Normal   Pulled                  11m                 kubelet                  Container image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos7-12.4-4.5.0" already present on machine
  Normal   Created                 11m                 kubelet                  Created container database
  Normal   Started                 11m                 kubelet                  Started container database
  Warning  Unhealthy               83s (x60 over 11m)  kubelet                  Readiness probe failed:`

 kubectl describe pvc
`Events:
  Type    Reason                 Age   From                                                                                                        Message
  ----    ------                 ----  ----                                                                                                        -------
  Normal  ExternalProvisioning   13m   persistentvolume-controller                                                                                 waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
  Normal  Provisioning           13m   rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-764fb7fbdb-tsh48_7accb225-8568-47d0-b57d-d3782615b617  External provisioner is provisioning volume for claim "pgo/hippo-pgbr-repo"
  Normal  ProvisioningSucceeded  13m   rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-764fb7fbdb-tsh48_7accb225-8568-47d0-b57d-d3782615b617  Successfully provisioned volume pvc-1c0984ee-b708-41ed-a207-3a356498945c`

 kubectl get nodes
 kubectl log yourPodName <above>

Thanks,
Andrei

**Comment by jkatz** [comment]
What does the configuration file for your cluster look like?

**Comment by andrei-matei** [comment]
Hi @jkatz 

I have not used a specific config for the cluster, I just forwarded the port to the service and tried to run: 
pgo create cluster hippo

So I guess all configuration is default. Is there anything to configure regarding SSL? I tried to create a CA secret with the same CA I used to install the K8s cluster and generated cert+key from that CA and added them as a tls secret and pointed the new cluster to those 2 secrets but the result was the same, when Patroni starts, it tries to get the configmaps from API Server and I get the certificate error.

**Comment by jkatz** [comment]
The TLS feature in the Operator for configuring Postgres clusters has nothing to do with communicating to the Kubernetes API.

Is the overall environment healthy? I noticed this message in one of your logs:

```
Warning Unhealthy 83s (x60 over 11m) kubelet Readiness probe failed:
```

Do you have any network security policies or pod security policies in place? Do the Kubernetes API server logs show anything about the connection? Are other services working?

**Comment by andrei-matei** [comment]
The overall cluster is healthy, all nodes are in Ready state. I don't use any Network policies. As a CNI plugin I use Calico, also I have MetalLB to provide LB services and ingress-nginx as an ingress. 
Rook-Ceph is also installed which provides storage for the cluster and by using taints I have 3 nodes dedicated to this.

postgres-operator runs in one of the other 3 nodes. The operator gets correctly installed and started.

Warning Unhealthy 83s (x60 over 11m) kubelet Readiness probe failed: -> This actually comes from the cluster pod I try to start and fails. 
The API Server throws this error:  log.go:172] http: TLS handshake error from 10.10.81.112:33052: remote error: tls: unknown certificate authority (IP is nodes2 where cluster pod is deployed). PVCs are provisioned correctly from the correct StorageClass (otherwise pod would fail).

I know it's a weird error and I have never found this anywhere so I think it's something from the environment itself but I cannot understand what it is or where I should look as I followed the instructions from the Crunchy operator 4.5.0.

**Comment by andrei-matei** [comment]
This error seems to come from kubernetes service itself, it is the api-server service:
`2020-11-13 20:40:43,623 ERROR: **Request to server https://10.32.0.1:443 failed: MaxRetryError("HTTPSConnectionPool(host='10.32.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/pgo/pods?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))",)**

hippo is the name of the test cluster I tried to start:
2020-11-13 20:40:44,445 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 700, in _load_cluster
    self._wait_caches(stop_time)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 692, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2020-11-13 20:40:44,445 WARNING: Can not get cluster from dcs
2020-11-13 20:40:44,622 ERROR: ObjectCache.run TypeError("unsupported operand type(s) for -: 'NoneType' and 'float'",)
2020-11-13 20:40:44,624 ERROR: ObjectCache.run TypeError("unsupported operand type(s) for -: 'NoneType' and 'float'",)
2020-11-13 20:40:44,626 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after **connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),)': /api/v1/namespaces/pgo/configmaps?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo**`

Anyone any ideas? I am banging my head against the wall for the last day :)

Thanks in advance,
Andrei

**Comment by jkatz** [comment]
Yes, we've been discussing it :wink:

We're also in the process of releasing bug fix updates and was attempting to bide enough time to suggest "try the new version and see if it's any different," as the patch release updates to Patroni 2.0.1.

Patroni has an option called `bypass_api_service`: [https://patroni.readthedocs.io/en/latest/SETTINGS.html#kubernetes](https://patroni.readthedocs.io/en/latest/SETTINGS.html#kubernetes) I don't know if this would do the trick, but you could set that in the configuration. Customizing configuration is covered here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/)

Otherwise, it may be worth reporting the issue in the Patroni upstream: [https://github.com/zalando/patroni](https://github.com/zalando/patroni) to see if they've encountered the issue. It does not appear to be directly related to the Operator functionality.

**Comment by andrei-matei** [comment]
Could you be a little more specific as to where exactly I need to add that parameter? Sorry but I am new to Crunchy. I believe that might help as that would avoid talking to the API server so using a cert.

Also, I have found this: https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c
I wonder if the Python script checks the validity of the certificate by its own defined list of CAs because that would assume you have an external valid cert which is not the case with Kubernetes.

**Comment by jkatz** [comment]
We looked into this a bit further. It seems to skew towards something being up with the certificates.

Patroni looks for the Kubernetes CA certificate to be loaded to the following directory:

[https://github.com/zalando/patroni/blob/0a1f389686827bad168186f20cc5146ede620787/patroni/dcs/kubernetes.py#L30](https://github.com/zalando/patroni/blob/0a1f389686827bad168186f20cc5146ede620787/patroni/dcs/kubernetes.py#L30)

Based on the error messages, the CA is loaded in but is invalid, per what you've said:

[https://github.com/zalando/patroni/blob/0a1f389686827bad168186f20cc5146ede620787/patroni/dcs/kubernetes.py#L63-L67](https://github.com/zalando/patroni/blob/0a1f389686827bad168186f20cc5146ede620787/patroni/dcs/kubernetes.py#L63-L67)

Patroni allows for some of the other certificates to have optional validation, but it does not appear that this available for working with the Kubernetes API. I would recommend trying to go down that route though and ensure that you have the proper CA loading into the Pods that are generated.

With the customizations, you would have to add a block similar to:

```yaml
kubernetes:
  bypass_api_service: true
```

though it would need to be tested, as the customizations allowed through the Operator are typically aimed customizing the PostgreSQL deployment, not interfacing with Kubernetes.

**Comment by andrei-matei** [comment]
Hello @jkatz 

Thank you for your input. I will try to get into the Pod and check what cert is being loaded and work from there. I opened an issue with Patroni as well and they seem to say the same. I will check this and report back.

Also, I think 4.5.1 is out so I will try that one. I am a little bit pressed with other issues so hope to find time sometime this week. Will report back here.

Thanks,
Andrei

**Comment by bohrasd** [comment]
> ```yaml
> kubernetes:
>   bypass_api_service: true
> ```

I don't know if Im doing it wrong but it doesnt work for me. Im running 4.5.0 on k3d, and I put it both in dcs and local config, and I tried restart and kill the pod, and then I check `patronictl edit-config`, that configuration is not there.

**Comment by SugendhKGanga** [comment]
I have been running into the same issue above too. could you please help me to understand what the fix was?

I am on pgo version 4.7.2. 

the database pod never comes up and seeing this error in the logs:
```
NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/tmp/nss_wrapper/postgres/passwd' readonly -1:No such file or directory
NWRAP_ERROR(1) - nwrap_files_getpwuid: Error loading passwd file
nss_wrapper: user exists
nss_wrapper: group exists
nss_wrapper: environment configured
[0;32mMon Aug 23 16:54:06 UTC 2021 INFO: postgres-ha pre-bootstrap starting...[0m
[0;32mMon Aug 23 16:54:06 UTC 2021 INFO: pgBackRest auto-config disabled[0m
[0;32mMon Aug 23 16:54:06 UTC 2021 INFO: PGHA_PGBACKREST_LOCAL_S3_STORAGE, PGHA_PGBACKREST_LOCAL_GCS_STORAGE and PGHA_PGBACKREST_INITIALIZE will be ignored if provided[0m
[0;32mMon Aug 23 16:54:06 UTC 2021 INFO: Defaults have been set for the following postgres-ha auto-configuration env vars: PGHA_DEFAULT_CONFIG, PGHA_BASE_BOOTSTRAP_CONFIG, PGHA_BASE_PG_CONFIG[0m
[0;32mMon Aug 23 16:54:06 UTC 2021 INFO: Defaults have been set for the following postgres-ha env vars: PGHA_PATRONI_PORT[0m
[0;32mMon Aug 23 16:54:06 UTC 2021 INFO: Defaults have been set for the following Patroni env vars: PATRONI_NAME, PATRONI_RESTAPI_LISTEN, PATRONI_RESTAPI_CONNECT_ADDRESS, PATRONI_POSTGRESQL_LISTEN, PATRONI_POSTGRESQL_CONNECT_ADDRESS[0m
[0;32mMon Aug 23 16:54:06 UTC 2021 INFO: Setting postgres-ha configuration for database user credentials[0m
[0;32mMon Aug 23 16:54:06 UTC 2021 INFO: Setting 'pguser' credentials using file system[0m
[0;32mMon Aug 23 16:54:06 UTC 2021 INFO: Setting 'superuser' credentials using file system[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Setting 'replicator' credentials using file system[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Applying base bootstrap config to postgres-ha configuration[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Applying base postgres config to postgres-ha configuration[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Applying pgbackrest config to postgres-ha configuration[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Applying standard (non-TLS) remote connection configuration to pg_hba.conf[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Custom postgres-ha configuration file not detected[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Finished building postgres-ha configuration file '/tmp/postgres-ha-bootstrap.yaml'[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: postgres-ha pre-bootstrap complete!  The following configuration will be utilized to initialize [0m
******************************
postgres-ha (PGHA) env vars:
******************************
PGHA_BASE_PG_CONFIG=true
PGHA_PATRONI_PORT=8009
PGHA_PG_PORT=5432
PGHA_PGBACKREST_LOCAL_S3_STORAGE=false
PGHA_SYNC_REPLICATION=false
PGHA_USER=postgres
PGHA_INIT=true
PGHA_DEFAULT_CONFIG=true
PGHA_PASSWORD_TYPE=
PGHA_REPLICA_REINIT_ON_START_FAIL=true
PGHA_PGBACKREST=true
PGHA_BASE_BOOTSTRAP_CONFIG=true
PGHA_STANDBY=false
PGHA_PGBACKREST_LOCAL_GCS_STORAGE=false
PGHA_TLS_ONLY=false
PGHA_TLS_ENABLED=false
PGHA_DATABASE=hippo-01
******************************
Patroni env vars:
******************************
PATRONI_POSTGRESQL_CONNECT_ADDRESS=192.168.190.181:5432
PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
PATRONI_NAME=hippo-01-9b675c87c-8r249
PATRONI_SCOPE=hippo-01
PATRONI_RESTAPI_LISTEN=0.0.0.0:8009
PATRONI_POSTGRESQL_DATA_DIR=/pgdata/hippo-01
PATRONI_RESTAPI_CONNECT_ADDRESS=192.168.190.181:8009
PATRONI_LOG_LEVEL=INFO
PATRONI_KUBERNETES_LABELS={vendor: "crunchydata"}
PATRONI_KUBERNETES_SCOPE_LABEL=crunchy-pgha-scope
PATRONI_KUBERNETES_NAMESPACE=dba-postgres-operator-dev
******************************
Patroni bootstrap method: initdb
******************************
Patroni configuration file:
******************************
bootstrap:
  method: initdb
  pgbackrest_init:
    command: '/opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh
      primary'
    keep_existing_recovery_conf: true
  existing_init:
    command: '/opt/crunchy/bin/postgres-ha/bootstrap/create-from-existing.sh'
    keep_existing_recovery_conf: true
  dcs:
    postgresql:
      parameters:
        jit: off
        unix_socket_directories: /tmp
        wal_level: logical
        archive_mode: on
        archive_command: 'source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-set-env.sh
          && pgbackrest archive-push "%p"'
        archive_timeout: 60
        log_directory: pg_log
        shared_buffers: 128MB
        temp_buffers: 8MB
        log_min_duration_statement: 60000
        log_statement: none
        work_mem: 4MB
        max_wal_senders: 6
        shared_preload_libraries: pgaudit.so,pg_stat_statements.so,pgnodemx.so
      use_slots: false
      recovery_conf:
        restore_command: 'source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-set-env.sh
          && pgbackrest archive-get %f "%p"'
      use_pg_rewind: true
  post_bootstrap: /opt/crunchy/bin/postgres-ha/bootstrap/post-bootstrap.sh
  initdb:
  - encoding: UTF8
  - data-checksums
postgresql:
  use_unix_socket: true
  pgpass: /tmp/.pgpass
  create_replica_methods:
  - pgbackrest
  - basebackup
  pgbackrest:
    command: '/opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh
      replica'
    keep_data: true
    no_params: true
  pgbackrest_standby:
    command: '/opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh
      standby'
    keep_data: true
    no_params: true
    no_master: 1
  remove_data_directory_on_rewind_failure: true
  callbacks:
    on_role_change: /opt/crunchy/bin/postgres-ha/callbacks/pgha-on-role-change.sh
  pg_hba:
  - local all postgres peer
  - host replication primaryuser 0.0.0.0/0 md5
  - host all primaryuser 0.0.0.0/0 reject
  - host all all 0.0.0.0/0 md5
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Applying SSHD..[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: nss_wrapper: ssh configured[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Checking for SSH Host Keys in /sshd..[0m
[0;32mMon Aug 23 16:54:07 UTC 2021 INFO: Checking for authorized_keys in /sshd[0m
[0;32mMon Aug 23 16:54:08 UTC 2021 INFO: Checking for sshd_config in /sshd[0m
[0;32mMon Aug 23 16:54:08 UTC 2021 INFO: Starting SSHD..[0m
WARNING: 'UsePAM no' is not supported in Fedora and may cause several problems.
[0;32mMon Aug 23 16:54:08 UTC 2021 INFO: Starting background process to monitor Patroni initization and restart the database if needed[0m
[0;32mMon Aug 23 16:54:08 UTC 2021 INFO: Initializing cluster bootstrap with command: '/usr/local/bin/patroni /tmp/postgres-ha-bootstrap.yaml'[0m
[0;32mMon Aug 23 16:54:08 UTC 2021 INFO: Running Patroni as PID 1[0m
2021-08-23 16:54:10,083 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),)': /api/v1/namespaces/dba-postgres-operator-dev/pods?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo-01
2021-08-23 16:54:10,144 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),)': /api/v1/namespaces/dba-postgres-operator-dev/configmaps?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo-01
2021-08-23 16:54:10,146 ERROR: Request to server https://10.96.0.1:443 failed: MaxRetryError("HTTPSConnectionPool(host='10.96.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/dba-postgres-operator-dev/pods?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo-01 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))",)
2021-08-23 16:54:10,151 ERROR: Request to server https://10.96.0.1:443 failed: MaxRetryError("HTTPSConnectionPool(host='10.96.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/dba-postgres-operator-dev/configmaps?labelSelector=vendor%3Dcrunchydata%2Ccrunchy-pgha-scope%3Dhippo-01 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))",)
2021-08-23 16:54:11,148 ERROR: ObjectCache.run TypeError("unsupported operand type(s) for -: 'NoneType' and 'float'",)
2021-08-23 16:54:11,152 ERROR: ObjectCache.run TypeError("unsupported operand type(s) for -: 'NoneType' and 'float'",)
```
Also, I have set these values to the following while setting up the operator -
```
namespace_mode="disabled"
serviceAccount.name="pgo-deployer-sa"
pgo_operator_namespace=$DEV_NAMESPACE
namespace=$DEV_NAMESPACE
pgo_disable_tls="true"
pgo_tls_no_verify="true"
pgo_apiserver_port=8080
pgo_apiserver_url="http://postgres-operator"
```
Also - I am using helm to create the pg cluster - https://github.com/CrunchyData/postgres-operator/tree/REL_4_7/examples/helm

Any help would be greatly appreciated. Thanks
