### ISSUE TITLE
pgo deletes not working on windows

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#205]
I am using operator 2.6 and I can get version, create objects and show objects.
But, when i try to do "pgo delete <object>" , it gets stuck.

**Comment by jmccormick2001** [comment]
likely an issue with the golang version used to build the windows binary...my fix to this will be to convert DELETE to GET in the API, also will add separate 'delete' perms to the list of pgo rbac perms

**Comment by jmccormick2001** [comment]
ok, ready to test, merged into pre27..will require a rebuild of pgo and apiserver.
