### ISSUE TITLE
liveness and readiness processes in postgres database POD

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2051]
In one of the production deployments for Postgres CrunchyData, we are seeing almost 13000 to 14000 liveness and readiness processes in postgres database POD.

Please see a snippet of these processes below.

26 2857935 0.0 0.0 13304 2236 ? S Oct28 0:00 /bin/bash /opt/cpm/bin/health/pgha-readiness.sh 

26 2857980 0.0 0.0 13304 3176 ? Ss Oct25 0:00 /bin/bash /opt/cpm/bin/health/pgha-liveness.sh 

26 2858052 0.0 0.0 13304 2308 ? S Oct26 0:00 /bin/bash /opt/cpm/bin/health/pgha-readiness.sh 

26 2858094 0.0 0.0 13304 3256 ? Ss Oct29 0:00 /bin/bash /opt/cpm/bin/health/pgha-readiness.sh 

Because of this, POD was consuming a lot of resources on the node and made that specific node unstable.

what scenario POD can have so many liveness and readiness processes?

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
4.3.0 is out of support. If this can be verified on the latest version of 4.3.x or a newer version, we can look at it.
