### ISSUE TITLE
Default storage class

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2052]
Hi Team,

Just wanted to know how can we set a default storage class for postgres operator

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
[Support for Kubernetes default storage classes was added in Postgres Operator v4.5.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0).

PR #1912 shows the template file modification that can be made if you want to attempt to run it in an older version ([https://github.com/CrunchyData/postgres-operator/pull/1912/files#diff-eec4085a11beff027403318475c14ce1b7ac63b814ac9ddf1d63a59c2afd8b0d](https://github.com/CrunchyData/postgres-operator/pull/1912/files#diff-eec4085a11beff027403318475c14ce1b7ac63b814ac9ddf1d63a59c2afd8b0d)) however, it is technically unsupported until v4.5.0.
