### ISSUE TITLE
pgo create cluster --standby from s3 failed

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#2053]
If primaryuser password was not set, it is generated during cluster creation. In that case, accidently deleted cluster cannot be restored from s3 pgbackrest backup. Same goes to other password variables.
Command, given below, fails with kubernetes pod logs on the screenshot.

pgo create cluster -n pgo pgsql-cluster --ccp-image=crunchy-postgres-ha --ccp-image-tag=centos7-12.4-4.5.0 --metrics --pgbouncer  --pgbadger  --sync-replication --pgbackrest-storage-type=local,s3 --standby \
--password-superuser "i know this one"
--pgbackrest-s3-key "i know this one" \
  --pgbackrest-s3-key-secret "i know this one" \
  --pgbackrest-s3-bucket "i know this one" \
  --pgbackrest-s3-endpoint "i know this one" \
  --pgbackrest-s3-region "i know this one" \
  --pgbackrest-repo-path "i know this one" \
  --password-replication "THIS ONE I DIDNT KNOW BECAUSE I DIDNT SET IT DURING CLUSTER CREATION" 

![image](https://user-images.githubusercontent.com/42073646/99432247-ec95de80-291c-11eb-8600-f22518b0af08.png)

Describe the solution you'd like
1.Describe the workaround for this situation
2.Add proper documentation pages

Please tell us about your environment:
Google Kubernetes Engine cluster
Container Image Tag: crunchy-postgres-ha:centos7-12.4-4.5.0
Platform Version: 1.17.9-gke.6300

**Comment by jkatz** [comment]
You can update the password for the users that are managed by secrets using the [`pgo update user`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_update_user/) command. This process is [already documented](https://access.crunchydata.com/documentation/postgres-operator/4.5.1/pgo-client/common-tasks/#postgresql-cluster-user-operations), and I don't think we need anything specific for this if the password is forgotten.

Additionally, if the user's password has not changed, you can reveal it using [`pgo show user --show-system-accounts`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_show_user/). I would be more interested in adding that bit to a "troubleshooting" or regular section around creating standby clusters, as I think that is generally more useful.

**Comment by aprilito1965** [comment]
Thank you for responding!
Updating user on pgo side doesn't update it on s3 backup side i believe.

Can you clarify to me logs from screenshot i attached? 
"password authentification failed for user "primaryuser"

If i dont provide password during standby creation - what password did it auth with? And with what does it compared? The one stored on s3 global objects backup?

**Comment by DavidKmn** [comment]
@jkatz

**Comment by DavidKmn** [comment]
We are experiencing the same issue in production. Would appreciate a fast response, thank you!

**Comment by jkatz** [comment]
You can read about [production support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) here.

Otherwise, issues are responded to in a reasonable amount of time by folks who are both engineering or contributing to the PostgreSQL Operator community in some way, shape, form, or fashion.

**Comment by aprilito1965** [comment]
@jkatz Thank you!
One last question - is primary user password is randomly generated? Same as testuser? (if it wanst set with parameter during cluster creation)

**Comment by aprilito1965** [comment]
Is there a way to edit s3 pgbackert backup to authentificate replication user with no password? with editing pg_hba.conf?

**Comment by jkatz** [comment]
> Can you clarify to me logs from screenshot i attached?
> "password authentification failed for user "primaryuser"

This means that `primaryuser`, which is used for replication (and likely this is coming from one of your replicas) is unable to authenticate to PostgreSQL. So in your standby cluster, your replicas are not going to be able to use streaming replication.

> If i dont provide password during standby creation - what password did it auth with? 

No password. Authentication is just failing.

> And with what does it compared?

It could be the original password that was generated with your primary cluster. If you happened to change that password independently of updating the Secret, it will use that password.

> The one stored on s3 global objects backup?

The "global objects backup on S3" (I'll call it the physical backup in the pgBackRest repository in S3) contains whatever password `primaryuser` was set to in your PostgreSQL cluster.

> One last question - is primary user password is randomly generated? Same as testuser? (if it wanst set with parameter during cluster creation)

Yes.

> Is there a way to edit s3 pgbackert backup to authentificate replication user with no password? with editing pg_hba.conf?

Yes. This was added in [v4.4.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.4.0) and is documented here:

[TLS Authentication for PostgreSQL Replication
](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#tls-authentication-for-postgresql-replication)

**Comment by jkatz** [comment]
I've amended the documentation to provide the `pgo show user --show-system-accounts` nugget. Hope this helps.
