### ISSUE TITLE
nsqd eating node resouces

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#2057]
We are running operator 4.5.0 without apparent problems, but we are seeing a high cpu consumption by the nsqd process started by the operator, there any way to control how much cpu is used by nsqd?

**Comment by jkatz** [comment]
There are a few options:

1. In the `postgres-operator` Deployment template, place a CPU resource limit on the `event` container.
2. You can disable nsqd` with the `DISABLE_EVENTING` flag/configuration parameter on installation.

If you're not using any of the eventing functionality, I'd recommended option #2.

**Comment by IJOL** [comment]
we are in runtime so, adding the env var to the operator deployment and restarting the operator POD should do the trick, isn't it?

**Comment by jkatz** [comment]
Yes, though adding/modifying the environmental variable in the Operator Deployment should automatically restart the Pod. If it doesn't, you can certainly manually trigger it.

**Comment by IJOL** [comment]
Just to let you know out of curiosity we tried to see what happens when doing a pgo watch clustername , and we don't see anything happening apart from the first messages about connection succeded, what is supposed to happen now? which events are logged here? we tried pgo backup..

**Comment by jkatz** [comment]
If you disable eventing, then nothing will be sent via NSQ. If you are using that feature, then I would recommend the first option described, i.e. explicitly setting a CPU limit.

This list of available events is aggregated here: [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/eventing/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/eventing/)
