### ISSUE TITLE
Can not install pgbouncer and pgbager with --ccp-image=crunchy-postgres-gis-ha       4.5.0

### ISSUE THREAD

**Issue by catfish34** [CrunchyData/postgres-operator#2059]
postgres-operator v4.5.0

I want to create cluster:
`pgo create cluster myclustername --pgbadger --pgbouncer --ccp-image=crunchy-postgres-gis-ha --ccp-image-tag=centos7-12.4-3.0-4.5.0`

But have problem with pgbadger and pgbouncer:
```
 Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos7-12.4-3.0-4.5.0": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos7-12.4-3.0-4.5.0 not found: manifest unknown: manifest unknown

 Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbadger:centos7-12.4-3.0-4.5.0": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/crunchy-pgbadager:centos7-12.4-3.0-4.5.0 not found: manifest unknown: manifest unknown

```
Looks like there are no crunchy-pgbouncer:centos7-12.4-3.0-4.5.0 and crunchy-pgbadger:centos7-12.4-3.0-4.5.0 image in registry?
Or possible I should use something like "pgbadger_image-tag"?

**Comment by jkatz** [comment]
This is fixed in [4.5.1](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.1). Please see #1749
