### ISSUE TITLE
Create cluster from logical backup

### ISSUE THREAD

**Issue by fboismenu** [CrunchyData/postgres-operator#2060]
Hello there :) 

I would like to know if it's possible to create a new cluster from a logical backup (`pgo backup --backup-type=pgdump ...`),
in similar fashion than `pgo create cluster --from-backup`.

This would be very helpful to support major version ugrades...

Many thanks in advance!

**Comment by jkatz** [comment]
If the goal is to perform a major upgrade, I would suggest using the `crunchy-upgrade` container which is described here: [https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/) (and it works up to Postgres 13, and I have made a note to update the documentation).

There are a few ways to create a cluster from a logical backup and/or perform a major version upgrade:

1. Follow an upgrade procedure similar to the `pg_dumpall` approach outline here, i.e. run pg_dumpall directly on the newc luster connecting to the old one: [https://info.crunchydata.com/blog/performing-a-major-postgresql-upgrade-with-pg_dumpall](https://info.crunchydata.com/blog/performing-a-major-postgresql-upgrade-with-pg_dumpall)
1. Load a custom script at cluster bootstrap, a method of which is described here: [https://github.com/CrunchyData/postgres-operator/issues/1928#issuecomment-731295420](https://github.com/CrunchyData/postgres-operator/issues/1928#issuecomment-731295420)
1. If you are very ambitious, you can attempt an [online upgrade using logical replication](https://info.crunchydata.com/blog/online-upgrade-in-postgres)
