### ISSUE TITLE
Deleting a backup

### ISSUE THREAD

**Issue by breku** [CrunchyData/postgres-operator#2061]
Hi,

I wanted to know if it's possible to delete a backup to reclaim some space. I did that by using 
`pgo delete backup test1 --debug`
but nothing happend beside the log 
`DEBU[0000] deleteBackup called [test1]`

If it's not implemented is it possible to delete a backup manually with **rm**. If so what files and folders should I leave to not destroy a cluster?

**Comment by jkatz** [comment]
Backups in a pgBackRest repository are supposed to be sequential as they are designed to properly play out a restore timeline. As such, the appropriate way to do this is by setting your backup retention. This is described in the documentation in a few places:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/#set-backup-retention](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/#set-backup-retention)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#backups](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#backups)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#setting-backup-retention-policies](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#setting-backup-retention-policies)

pgBackRest also allows you to explicit `expire` (aka "delete") a backup using `--set`, but this is not recommend: [https://pgbackrest.org/command.html#command-expire](https://pgbackrest.org/command.html#command-expire). As such we do not expose this interface at this time.

Using `rm` to delete backups has the potential to put your pgBackRest repository into a world of hurt and is not recommended under any circumstances.
