### ISSUE TITLE
Add restore-from-namespace to create cluster options

### ISSUE THREAD

**Issue by m33li5** [CrunchyData/postgres-operator#2062]
**What is the motivation or use case for the change? **

When using `pgo create cluster newcluster --restore-from=oldcluster` it would be great if one could specify the namespace of `oldcluster`, in order to deploy `newcluster` to a new namespace.

**Describe the solution you'd like**
`pgo -n newnamespace create cluster newcluster --restore-from=oldcluster --restore-from-namespace=oldnamespace`

**Comment by jkatz** [comment]
This is similar to #1232 though this request could end up superseding it.

That said, one of the reason we haven't pursued #1232 further is that it can create some weird dynamics in a Kubernetes environment, particularly around the security barrier that Namespaces create. There seem to be a few general deployment patterns that Operators fit into:

- Restricted to a single namespace
- Restricted to managing objects in several namespaces
- Allow dynamic management across any and all namespaces

(which I think we document fairly well here: [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/)

So, we would need to be sure that if one is running that command, the Operator does have permissions to manage things in that Namespace, we're able to copy all of the pertinent objects from the `oldcluster` over into there, and then perform the subsequent restore. It's seems perfectly reasonable, but it also seems as if it's going against the security barriers that Namespaces have set up.

That all said, the present day way to do this is to create a cluster as a standby in a different namespace. This is not dissimilar from the "multi-Kubernetes cluster" that is described here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/)

i.e. where you have S3 or some intermediate S3-like storage system providing the ability to initialize the standby cluster in a different namespace, then detaching the new cluster and having it run within the new namespace.
