### ISSUE TITLE
Pgbouncer secret is missing when creating standby cluster on the same kubernetes cluster

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#2064]
When i create standby cluster, pgbouncer deployment shows that containers are in creating state all the time. I checked everything and noticed that pgbouncer configmap had been created and secret has not. And i believe containers are waiting due to this fact.

The thing is pgbouncer password cannot be provided from user during main cluster creation. So we have only one option:
use --secret-from when creating standby cluster, am i right?

I also has a noob question (i cannot find any straight answer to it in postgres or crunchy docs):
- is standby cluster continuously syncing with main cluster or it just copies initial architecture and pull latest backup on promotion?

Command used to create standby cluster:
pgo create cluster -n pgo pgsql-standby \
--replica-count=2 \
--password-replication='' \
--password '' \
--password-superuser '' \
--metrics  \
--pgbadger \
--sync-replication \
--pgbouncer \
--pgbouncer-replicas=3 \
--pgbackrest-storage-type=s3 \
--pgbackrest-s3-key '' \
 --pgbackrest-s3-key-secret '' \
 --pgbackrest-s3-bucket '' \
 --pgbackrest-s3-endpoint '' \
 --pgbackrest-s3-region '' \
 --pgbackrest-repo-path '' \
 --standby

Google Kubernetes Engine cluster
Container Image Tag: crunchy-postgres-gis-ha:centos7-12.5-3.0-4.5.1
Platform Version: 1.17.12-gke.2502

Thank you very much, guys, for your product, for your help and quick respones!

**Comment by aprilito1965** [comment]
So i just checked --secret-from option and there is something strange going on.

I deleted all cli password parameters and added --secret-from with main cluster name:
 
pgo create cluster -n pgo pgsql-standby
--replica-count=2
--metrics
--pgbadger
--sync-replication
--pgbouncer
--pgbouncer-replicas=3
--pgbackrest-storage-type=s3
--pgbackrest-s3-key ''
--pgbackrest-s3-key-secret ''
--pgbackrest-s3-bucket ''
--pgbackrest-s3-endpoint ''
--pgbackrest-s3-region ''
--pgbackrest-repo-path ''
--standby
--secret-from=pgsql

Standby cluster is definitely read secrets from main cluster (i can see my testuser password in pgo output after stanby creation command)

But pgbouncer deployment still linked to unexisting pgsql-STANDBY-pgbouncer-secret (not pgsql-pgbouncer-secret), so pgbouncer pods are in waiting state.

**Comment by jkatz** [comment]
> is standby cluster continuously syncing with main cluster or it just copies initial architecture and pull latest backup on promotion?

It is continuously syncing. You can read about it here: [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/)

I believe the issue is that "--secret-from" does not include support for the pgBouncer Secret. There is some guidance on how to get pgBouncer to work with the cluster in that documentation:

> As pgBouncer was enabled for the cluster, the pgbouncer user’s password is rotated, which will bring pgBouncer online with the newly promoted active cluster. If pgBouncer is still having trouble connecting, you can explicitly rotate the password with the following command:

```shell
pgo update pgbouncer --rotate-password hippo-standby
```

**Comment by aprilito1965** [comment]
@jkatz Thank you for your responce!

But it is not a connection issue i guess. 
pgbouncer deployment just doesnt create pods - they are stuck in waiting stage and not created at all.

But i will try your solution! Thank you for your answer!

**Comment by aprilito1965** [comment]
So after executing command with --rotate-password i get the error

**Comment by aprilito1965** [comment]
@jkatz 
I tried to create standby cluster without --pgbouncer --pgbouncer-replicas parameters and its up and runnnig. But when i try to create pgbouncer for this cluster - deployment is created but pods are in waiting state because there is no pgbouncer-secret created.

So^ for now there is no way to create standby clone ready for promotion. Maybe it depentds on promotion state.

**Comment by aprilito1965** [comment]
update:
after manually exporting pgbouncer-secret from main cluster to yaml, rewriting it with standby cluster references and applying with kubectl apply from edited file, pgbouncer deployment in standby cluster is up and running (all replicas were created)

**Comment by jkatz** [comment]
I missed this when putting together a6beb661652fb8a4f16225248ac022dbf45de15d but a6beb661652fb8a4f16225248ac022dbf45de15d fixes this issue. It is available in 4.6.0 and backpatched to the 4.5 series.
