### ISSUE TITLE
Getting 400 error after deploying new operator

### ISSUE THREAD

**Issue by eliranw** [CrunchyData/postgres-operator#2065]
**Describe the bug**
Deployed new Postgres operator on a new namespace to switch usage from the old one to the new one. After deploying we started getting error 400 on every pgo cli command. Also getting the same errors from the pgo client container

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Operator apiserver doesn't return any special logs as well, and port forwarding to localhost gives same error

**Comment by jkatz** [comment]
Do you have any logs from the `apiserver`?

**Comment by eliranw** [comment]
I redeployed multiple times and it was fixed when I changed the postgres-operator name in the helm values somehow. The issue can be closed.
