### ISSUE TITLE
image tags 4.5.1 not on dockerhub

### ISSUE THREAD

**Issue by eliranw** [CrunchyData/postgres-operator#2067]
Also tried pulling from registry.developers.crunchydata.com and didn't find them.

**Comment by jkatz** [comment]
Please see #2050 for the status of OperatorHub.

Also without any clear reproduction steps or what images may be missing, there's nothing I can do to troubleshoot this. All the images for 4.5.1 have been pushed to registry.developers.crunchydata.com.
