### ISSUE TITLE
Replica recovery crashed after upgrade pgo-cluster (4.5.0)

### ISSUE THREAD

**Issue by kglebova** [CrunchyData/postgres-operator#2068]
Hi,
After updating  pgo-operator from 4.4.1 to version 4.5.0, the replica broke.
pgo upgrade namecl1 -n ns1
When the backup was started to restore the replica, primary database  pod was deleted 
And replica recovery crashed

kubectl logs backrest-backup-namecl1-5vq8g --all-containers  -n ns1 
time="2020-11-22T21:49:31Z" level=info msg="pgo-backrest starts"
time="2020-11-22T21:49:31Z" level=info msg="debug flag set to false"
time="2020-11-22T21:49:31Z" level=info msg="backrest backup command requested"
time="2020-11-22T21:49:31Z" level=info msg="s3 flag enabled for backrest command"
time="2020-11-22T21:49:31Z" level=info msg="command to execute is [pgbackrest backup --type=full --db-host=10.42.209.70 --db-path=/pgdata/namecl1 --repo1-type=s3]"
time="2020-11-22T21:49:31Z" level=info msg="command is pgbackrest backup --type=full --db-host=10.42.209.70 --db-path=/pgdata/namecl1 --repo1-type=s3 "
time="2020-11-22T21:51:43Z" level=error msg="command terminated with exit code 56"
time="2020-11-22T21:51:43Z" level=info msg="output=[]"
time="2020-11-22T21:51:43Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\nWARN: unable to check pg-1: [UnknownError] remote-0 process on '10.42.209.70' terminated unexpectedly [255]: ssh: connect to host 10.42.209.70 port 2022: Connection timed out\nERROR: [056]: unable to find primary cluster - cannot proceed\n]"
time="2020-11-22T21:51:43Z" level=error msg="command terminated with exit code 56"

There is a replica in the config pgo-cluster
pgo show cluster namecl1 -n ns1

cluster : namecl1 (crunchy-postgres-ha:centos7-12.4-4.5.0)
	pod : namecl1-785584c457-ztcgx (Running) on <hostname> (2/2) (primary)
		pvc: namecl1 (2000Gi)
	resources : CPU: 6 Memory: 16Gi
	limits : CPU: 6 Memory: 16Gi
	deployment : namecl1
	deployment : namecl1-backrest-shared-repo
	service : namecl1 - ClusterIP (10.43.175.78)
	service : namecl1-nodeport - ClusterIP (10.43.151.144)
	service : namecl1-replica - ClusterIP (10.43.50.104)
	pgreplica : namecl1-joyk

How can I restart replica recovery?

**Comment by kglebova** [comment]
If I try to delete replica, 
pgo scaledown namecl -n ns1 --target=namecl-joyk
I get  
not found

**Comment by jkatz** [comment]
```
remote-0 process on '10.42.209.70' terminated unexpectedly [255]: ssh: connect to host 10.42.209.70 port 2022: Connection timed out
ERROR: [056]: unable to find primary cluster - cannot proceed
```

This sounds like a networking issue. What does `pgo test` say?

**Comment by kglebova** [comment]
cluster : namecl 
	Services
		primary (10.43.175.78:5432): UP
		primary (10.43.151.144:5432): UP
		replica (10.43.50.104:5432): UP
	Instances
		primary (namecl -785584c457-ztcgx): UP

**Comment by jkatz** [comment]
Thanks. Is there any output that shows if the replica Pod in the cluster has failed? (e.g. from `kubectl get pods`)? Are there any logs specifically on the replica Pod itself? Does the replica PVC still exist?

**Comment by kglebova** [comment]
No. Pods and replica pvc does not exist. 
Only 
 pvc-d97c8eab-a6b9-485d-8c42-d57c18eaf974   2000Gi     RWO            Delete           Released   namecl /namecl-xybj                  vsan-single             14d

After 
pgo upgrade namecl1 -n ns1
replica has been deleted
Pods with backrest-shared-repo and primary database were started.
But backrest-backup-namecl1 did not start and the replica was not recreated

**Comment by gricuk** [comment]
> Thanks. Is there any output that shows if the replica Pod in the cluster has failed? (e.g. from `kubectl get pods`)? Are there any logs specifically on the replica Pod itself? Does the replica PVC still exist?

Hi, I'll provide additional info:
`kubectl get pgreplicas.crunchydata.com -n namecl1 namecl1-replica -oyaml`
```
status:
  message: Pgreplica processing pending the creation of the initial backup
  state: pgreplica Pending init
```
Looks like replica stuck and waiting initial backup . Is it possible to run initial backup manually?

**Comment by Seb0042** [comment]
Hi,
I've just migrated from 4.50 to 4.6.1 and have the same issue with replica. When I try to create one with pgo scale it is stuck on the same message as @gricuk . Backup is working so what is it waiting for ?

**Comment by jkatz** [comment]
Without any logs it's nearly impossible to tell what the issue is. What would be helpful would be:

- Logs from the Operator
- Logs from the PostgreSQL pods themselves
- Logs from the /pgdata/.../pg_log directory
- Output from `pgo show backup`
- Output from `pgo test`

etc.

**Comment by Seb0042** [comment]
Yes you're right, forgot to paste some informations:

Installation method is the Helm one.

cluster : mycluster
        Services
                primary (10.0.22.124:5432): UP
                primary (10.0.22.104:5432): UP
        Instances
                primary (mycluster-5d4b5cdf9-dlrns): UP

pgo show backup mycluster

cluster: mycluster
storage type: posix

stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1)

        full backup: 20210317-133336F
            timestamp start/stop: 2021-03-17 14:33:36 +0100 CET / 2021-03-17 14:36:41 +0100 CET
            wal start/stop: 00000002000000010000001B / 00000002000000010000001E
            database size: 1.4GiB, backup size: 1.4GiB
            repository size: 379.6MiB, repository backup size: 379.6MiB
            backup reference list:

        diff backup: 20210317-133336F_20210318-000111D
            timestamp start/stop: 2021-03-18 01:01:11 +0100 CET / 2021-03-18 01:02:33 +0100 CET
            wal start/stop: 0000000200000003000000A1 / 0000000200000003000000A2
            database size: 1.4GiB, backup size: 1.3GiB
            repository size: 385.1MiB, repository backup size: 370.2MiB
            backup reference list: 20210317-133336F

pgo scale mycluster
WARNING: Are you sure? (yes/no): yes
created Pgreplica mycluster-tjwg

Operator log as a file in attachment.
PostgreSQL pods logs is only for the primary, with always the same lines:
2021-03-18 15:50:02,692 INFO: no action.  i am the leader with the lock
2021-03-18 15:50:12,619 INFO: Lock owner: mycluster-5d4b5cdf9-dlrns; I am mycluster-5d4b5cdf9-dlrns

[operator.txt](https://github.com/CrunchyData/postgres-operator/files/6165436/operator.txt)

no log today in the pg_log directory

no log for pgbackrest

By the way, I see that the pgreplicas object is created:

kubectl get pgreplicas.crunchydata.com mycluster-tjwg -o yaml
apiVersion: crunchydata.com/v1
kind: Pgreplica
metadata:
  creationTimestamp: "2021-03-18T15:49:26Z"
  generation: 2
  labels:
    name: mycluster-tjwg
    pg-cluster: mycluster
    pgouser: admin
  name: mycluster-tjwg
  namespace: mynamespace
  resourceVersion: "165329984"
  selfLink: /apis/crunchydata.com/v1/namespaces/mynamespace/pgreplicas/mycluster-tjwg
  uid: bef55157-fd11-4267-a7fb-5e5952580dcc
spec:
  clustername: mycluster
  name: mycluster-tjwg
  namespace: mynamespace
  nodeAffinity: null
  replicastorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 2G
    storageclass: nfs
    storagetype: dynamic
    supplementalgroups: ""
  serviceType: ""
  status: ""
  tolerations: []
  userlabels:
    pgo-version: 4.6.1
    workflowid: c02923db-e932-46c3-bac7-efe6e3571059
status:
  message: Pgreplica processing pending the creation of the initial backup
  state: pgreplica Pending init

**Comment by Seb0042** [comment]
Hi, 
I tried to modify the configuration as you wrote (usepam no), ad then deleted the primary and backrest pods. 
I had a new issue, primary pod complaining about the primaryuser password and putting itself as non healthy. As I had  only one working node, my cluster was not reachable.
So I did a pgdump of data, deleted the cluster without data and recreated it, restored the data. 
Now it's ok.

**Comment by cristichiru** [comment]
I am speculating here: most probably you have changed the postgress password before updating the operator. I think you could have manually updated the passwords as well, by setting the old ones back in the secrets.

Regardless, happy you have eventually solved the issue, albeit not in the most elegant manner.
