### ISSUE TITLE
Delete cluster with is metrics

### ISSUE THREAD

**Issue by aurelien43** [CrunchyData/postgres-operator#2069]
Hello, 
When i have a cluster with his metrics, if I delete this cluster whit the commande 'pgo delete cluster', I still see it in the grafana dashboard : 'postgresql-overview'. 

So How to delete a cluster with his metrics or delete metrics after deleting a cluster?  

**Please tell us about your environment:**
* Operating System: centos7
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): CSI (SAN)
* Container Image Tag: centos7-12.4-4.5.0
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.17

**Comment by jkatz** [comment]
Please see #2031 for commentary on this.
