### ISSUE TITLE
Issues after pgo failover

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#207]
After running "pgo failover", the following items are not accurate

1) primary label: Instead of having "primary=true" on primary pod, we see "replica=false"
2) There is only one deployment. The cluster had 2 deployments before failover. One for master and one for replica
3) pgtask object created to perform failover is not removed. This prevents further failovers on this cluster
4) both primary and replica pod name look like replica pod names.

**Comment by jmccormick2001** [comment]
merged in fix for this into pre27 branch, ready to retest.
