### ISSUE TITLE
4.5.1 Error scraping metrics ccp_pg_hba_checksum/ccp_pg_settings_checksum

### ISSUE THREAD

**Issue by djcooklup** [CrunchyData/postgres-operator#2071]
After upgrading from 4.4.0 -> 4.5.1 we're encountering some errors when scraping metrics.

Upgrade approach for us to minimise downtime was to:

- Upgrade postgres-operator
- Create a new standby cluster via command similar to the following
`pgo create cluster h \
    -n pgo \
    --standby \
    --metrics \
    --replica-count 0 \
    --password <redacted> \
    --password-superuser <redacted> \
    --password-replication <redacted> \
    --pgbackrest-storage-type s3 \
    --pgbackrest-repo-path=/backrestrepo/default-backrest-shared-repo \
    --server-ca-secret postgres-ca \
    --server-tls-secret postgres-tls \
    --pvc-size 16Gi \
    --memory 4Gi \
    --memory-limit 4Gi \
    --node-label lup.events/purpose=general \
    --pod-anti-affinity preferred `
- Cutover to that cluster via shutdown of old cluster and promote
- Manually removal of old 4.4 cluster resources due to delete cluster not working on un-upgraded resources

I understand this differs from your recommended approach to upgrade, however our priority is minimising downtime as much as possible, hopefully this approach shouldn't be relevant to the issue, however worth mentioning in case it is.

We initially received 11 query errors from the exporter container and resolved 9 of them by 
CREATE EXTENSION pgnodemx SCHEMA monitor;

This left us with two remaining issues:

time="2020-11-24T22:46:01Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_pg_hba_checksum pq: function monitor.pg_hba_checksum() does not exist" source="postgres_exporter.go:1356"
time="2020-11-24T22:46:01Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_pg_settings_checksum pq: function monitor.pg_settings_checksum() does not exist" source="postgres_exporter.go:1356"
time="2020-11-24T22:46:02Z" level=error msg="queryNamespaceMappings returned 2 errors" source="postgres_exporter.go:1474"

Would your team be able to advise where those come from?

Cheers :)

**Comment by jkatz** [comment]
As mentioned in the [v4.5.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0) release notes, pgMonitor is updated to use version 4.4 (though as 4.4 is in pre-release, I believe v4.5.1 is tagged to 4.4-RC7). You would need to (re?)-install the functions and tables required for the exporter to work. For example, the ones for PostgreSQL 12 are in this file:

[https://github.com/CrunchyData/pgmonitor/blob/v4.4-RC7/exporter/postgres/setup_pg12.sql](https://github.com/CrunchyData/pgmonitor/blob/v4.4-RC7/exporter/postgres/setup_pg12.sql), which includes `monitor. pg_settings_checksum` and `monitor. pg_hba_checksum`.

**Comment by djcooklup** [comment]
Thanks @jkatz I appreciate the info
