### ISSUE TITLE
Operator 4.5.1 on Openshift 3.11 problem with creating pgo-role-rbac.yaml

### ISSUE THREAD

**Issue by AleksanderRoszig** [CrunchyData/postgres-operator#2072]
**Describe the bug**
During installation using https://access.crunchydata.com/documentation/postgres-operator/4.5.1/installation/postgres-operator/ pgo-deployer I got:
TASK [pgo-operator : Create PGO RBAC] ******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/tmp/.pgo/operator451/output/pgo-role-rbac.yaml"],

**To Reproduce**
1. oc create -f postgres-operator.yml
2. check logs in postgres-deployer logs

**Expected behavior**
Correct installation of operator and file with pgo-role-rbac.yaml in repository so that I can chceck what is the problem and make this manually.

* Container Image Tag: pgo-deployer:centos7-4.5.1
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 3.11

**Additional context**
Log:
`TASK [pgo-operator : Create PGO RBAC] ******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/tmp/.pgo/operator451/output/pgo-role-rbac.yaml"], "delta": "0:00:01.964506", "end": "2020-11-26 11:35:05.118645", "msg": "non-zero return code", "rc": 1, "start": "2020-11-26 11:35:03.154139", "stderr": "Error from server (Forbidden): error when creating \"/tmp/.pgo/operator451/output/pgo-role-rbac.yaml\": roles.rbac.authorization.k8s.io \"pgo-role\" is forbidden: attempt to grant extra privileges: [{[update] [] [configmaps] [] []} {[update] [] [secrets] [] []}] user=&{system:serviceaccount:operator451:pgo-deployer-sa 2c8d5380-2fd7-11eb-8279-00505689fc41 [system:serviceaccounts system:serviceaccounts:operator451 system:authenticated] map[]} ownerrules=[{[get] [ user.openshift.io] [users] [~] []} {[list] [ project.openshift.io] [projectrequests] [] []} {[get list] [ authorization.openshift.io] [clusterroles] [] []} {[get list watch] [rbac.authorization.k8s.io] [clusterroles] [] []} {[get list] [storage.k8s.io] [storageclasses] [] []} {[list watch] [ project.openshift.io] [projects] [] []} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] [] [] [] [/healthz /healthz/*]} {[get] [] [] [] [/ /.well-known /.well-known/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /osapi /osapi/ /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/*]} {[get] [] [] [] [/version]} {[get] [] [] [] [/version/*]} {[get list create patch delete] [] [namespaces] [] []} {[list] [] [pods] [] []} {[list get create delete] [] [secrets] [] []} {[get create delete list] [] [configmaps services persistentvolumeclaims] [] []} {[get create delete patch list] [] [serviceaccounts] [] []} {[get list watch create delete] [apps extensions] [deployments] [] []} {[get create delete] [apiextensions.k8s.io] [customresourcedefinitions] [] []} {[get create delete bind escalate] [rbac.authorization.k8s.io] [clusterroles clusterrolebindings roles rolebindings] [] []} {[create delete] [rbac.authorization.k8s.io] [roles] [] []} {[delete list] [batch] [jobs] [] []} {[delete list] [crunchydata.com] [pgclusters pgreplicas pgpolicies pgtasks] [] []} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[list watch get] [servicecatalog.k8s.io] [clusterserviceclasses clusterserviceplans] [] []} {[get] [] [] [] [/healthz/ready]} {[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[create] [ build.openshift.io] [builds/docker builds/optimizeddocker] [] []} {[create] [ build.openshift.io] [builds/jenkinspipeline] [] []} {[create] [ build.openshift.io] [builds/source] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/*]} {[delete] [ oauth.openshift.io] [oauthaccesstokens oauthauthorizetokens] [] []} {[get] [] [] [] [/ /.well-known /.well-known/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /osapi /osapi/ /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version/ /version/*]} {[get] [] [] [] [/version]} {[impersonate] [authentication.k8s.io] [userextras/scopes.authorization.openshift.io] [] []} {[create get] [ build.openshift.io] [buildconfigs/webhooks] [] []} {[get] [ image.openshift.io] [imagestreams/layers] [] []}] ruleResolutionErrors=[]\nError from server (AlreadyExists): error when creating \"/tmp/.pgo/operator451/output/pgo-role-rbac.yaml\": rolebindings.rbac.authorization.k8s.io \"pgo-role\" already exists", "stderr_lines": ["Error from server (Forbidden): error when creating \"/tmp/.pgo/operator451/output/pgo-role-rbac.yaml\": roles.rbac.authorization.k8s.io \"pgo-role\" is forbidden: attempt to grant extra privileges: [{[update] [] [configmaps] [] []} {[update] [] [secrets] [] []}] user=&{system:serviceaccount:operator451:pgo-deployer-sa 2c8d5380-2fd7-11eb-8279-00505689fc41 [system:serviceaccounts system:serviceaccounts:operator451 system:authenticated] map[]} ownerrules=[{[get] [ user.openshift.io] [users] [~] []} {[list] [ project.openshift.io] [projectrequests] [] []} {[get list] [ authorization.openshift.io] [clusterroles] [] []} {[get list watch] [rbac.authorization.k8s.io] [clusterroles] [] []} {[get list] [storage.k8s.io] [storageclasses] [] []} {[list watch] [ project.openshift.io] [projects] [] []} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] [] [] [] [/healthz /healthz/*]} {[get] [] [] [] [/ /.well-known /.well-known/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /osapi /osapi/ /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/*]} {[get] [] [] [] [/version]} {[get] [] [] [] [/version/*]} {[get list create patch delete] [] [namespaces] [] []} {[list] [] [pods] [] []} {[list get create delete] [] [secrets] [] []} {[get create delete list] [] [configmaps services persistentvolumeclaims] [] []} {[get create delete patch list] [] [serviceaccounts] [] []} {[get list watch create delete] [apps extensions] [deployments] [] []} {[get create delete] [apiextensions.k8s.io] [customresourcedefinitions] [] []} {[get create delete bind escalate] [rbac.authorization.k8s.io] [clusterroles clusterrolebindings roles rolebindings] [] []} {[create delete] [rbac.authorization.k8s.io] [roles] [] []} {[delete list] [batch] [jobs] [] []} {[delete list] [crunchydata.com] [pgclusters pgreplicas pgpolicies pgtasks] [] []} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[list watch get] [servicecatalog.k8s.io] [clusterserviceclasses clusterserviceplans] [] []} {[get] [] [] [] [/healthz/ready]} {[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[create] [ build.openshift.io] [builds/docker builds/optimizeddocker] [] []} {[create] [ build.openshift.io] [builds/jenkinspipeline] [] []} {[create] [ build.openshift.io] [builds/source] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/*]} {[delete] [ oauth.openshift.io] [oauthaccesstokens oauthauthorizetokens] [] []} {[get] [] [] [] [/ /.well-known /.well-known/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /osapi /osapi/ /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version/ /version/*]} {[get] [] [] [] [/version]} {[impersonate] [authentication.k8s.io] [userextras/scopes.authorization.openshift.io] [] []} {[create get] [ build.openshift.io] [buildconfigs/webhooks] [] []} {[get] [ image.openshift.io] [imagestreams/layers] [] []}] ruleResolutionErrors=[]", "Error from server (AlreadyExists): error when creating \"/tmp/.pgo/operator451/output/pgo-role-rbac.yaml\": rolebindings.rbac.authorization.k8s.io \"pgo-role\" already exists"], "stdout": "", "stdout_lines": []}
`

**Comment by jkatz** [comment]
> "Error from server (AlreadyExists): error when creating \"/tmp/.pgo/operator451/output/pgo-role-rbac.yaml\": rolebindings.rbac.authorization.k8s.io \"pgo-role\" already exists"

It appears the Role and RoleBindings for the Postgres Operator are already installed into this Namespace. In the installer file, you can set `create_rbac` to `false` to skip the RBAC setup.

**Comment by AleksanderRoszig** [comment]
It helped

**Comment by AleksanderRoszig** [comment]
pgo-role isn't correctly deployed
"Error from server (Forbidden): error when creating \"/tmp/.pgo/operator451/output/pgo-role-rbac.yaml\": roles.rbac.authorization.k8s.io \"pgo-role\" is forbidden: attempt to grant extra privileges:

**Comment by jkatz** [comment]
I probably should have started with this question, being did you use the installer file for OpenShift 3.11:

[https://github.com/CrunchyData/postgres-operator/blob/master/installers/kubectl/postgres-operator-ocp311.yml](https://github.com/CrunchyData/postgres-operator/blob/master/installers/kubectl/postgres-operator-ocp311.yml)

**Comment by AleksanderRoszig** [comment]
No. When I used that installation went smoothly. 
```
pgo version
pgo client version 4.5.1
pgo-apiserver version 4.5.1
```

but now I have problem with API and I don't know is that issue with roles, permisions, or other problem?
```
pgo create namespace pgouser3
Error: Method POST for URL /namespacecreate is not allowed in current the Operator install: 405
```

```
pgo update namespace new_namespace
Error: Method POST for URL /namespaceupdate is not allowed in current the Operator install: 405
```

**Comment by AleksanderRoszig** [comment]
Logs from:
operator container:

```
time="2020-12-02T09:45:59Z" level=error msg="Controller Manager: Controller Group for namespace operator451 does not have the required list privileges for resource jobs in the Batch API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:377" version=4.5.1
--
  | time="2020-12-02T09:45:59Z" level=error msg="Namespace Controller: error syncing Namespace 'operator451': Controller Manager: cannot start controller group for namespace operator451 because it does not have the required privs, will attempt to start on the next ns refresh interval" func="internal/controller/namespace.(*Controller).processNextWorkItem()" file="internal/controller/namespace/namespacecontroller.go:155" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot create serviceaccounts in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:134" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot create serviceaccounts in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:134" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot create serviceaccounts in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:134" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot create serviceaccounts in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:134" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-target-role\" is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot get roles.rbac.authorization.k8s.io in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-backrest-role\" is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot get roles.rbac.authorization.k8s.io in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-pg-role\" is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot get roles.rbac.authorization.k8s.io in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: rolebindings.rbac.authorization.k8s.io \"pgo-target-role-binding\" is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot get rolebindings.rbac.authorization.k8s.io in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:113" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: rolebindings.rbac.authorization.k8s.io \"pgo-backrest-role-binding\" is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot get rolebindings.rbac.authorization.k8s.io in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:113" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="operator is unable to reconcile RBAC resource: rolebindings.rbac.authorization.k8s.io \"pgo-pg-role-binding\" is forbidden: User \"system:serviceaccount:operator451:postgres-operator\" cannot get rolebindings.rbac.authorization.k8s.io in the namespace \"operator451\": no RBAC policy matched" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:113" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="Controller Manager: Controller Group for namespace operator451 does not have the required list privileges for resource pgtasks in the crunchydata.com API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:352" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="Controller Manager: Controller Group for namespace operator451 does not have the required list privileges for resource pgclusters in the crunchydata.com API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:352" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="Controller Manager: Controller Group for namespace operator451 does not have the required list privileges for resource pgreplicas in the crunchydata.com API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:352" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="Controller Manager: Controller Group for namespace operator451 does not have the required list privileges for resource pgpolicies in the crunchydata.com API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:352" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="Controller Manager: Controller Group for namespace operator451 does not have the required list privileges for resource pods in the Core API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:365" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="Controller Manager: Controller Group for namespace operator451 does not have the required list privileges for resource jobs in the Batch API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:377" version=4.5.1
  | time="2020-12-02T09:46:59Z" level=error msg="Namespace Controller: error syncing Namespace 'operator451': Controller Manager: cannot start controller group for namespace operator451 because it does not have the required privs, will attempt to start on the next ns refresh interval" func="internal/controller/namespace.(*Controller).processNextWorkItem()" file="internal/controller/namespace/namespacecontroller.go:155" version=4.5.1

```

scheduler container: 

```
E1202 09:48:52.327160       8 reflector.go:307] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.ConfigMap: unknown (get configmaps)
--
  | E1202 09:48:53.343857       8 reflector.go:307] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.ConfigMap: unknown (get configmaps)
  | E1202 09:48:54.399446       8 reflector.go:307] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.ConfigMap: unknown (get configmaps)
```

**Comment by jkatz** [comment]
In OpenShift 3.11, you need to manually add the namespaces to be watched by the Postgres Operator. There is a note about this somewhere in the documentation though I am failing to find it at the moment, which means we need to make it clearer. There is a script to help with this here:

[https://github.com/CrunchyData/postgres-operator/blob/v4.5.1/deploy/add-targeted-namespace.sh](https://github.com/CrunchyData/postgres-operator/blob/v4.5.1/deploy/add-targeted-namespace.sh)

Alternatively, you can specify which namespaces you want to have watched using the `namespace` parameter in the installation script when you perform the installation, which is probably an easier route:

[https://github.com/CrunchyData/postgres-operator/blob/master/installers/kubectl/postgres-operator-ocp311.yml#L67](https://github.com/CrunchyData/postgres-operator/blob/master/installers/kubectl/postgres-operator-ocp311.yml#L67)
