### ISSUE TITLE
Deploying Operator: Config: \"pgo-config\" ConfigMap NOT found

### ISSUE THREAD

**Issue by AleksanderRoszig** [CrunchyData/postgres-operator#2075]
**What is the current behavior?**
I try deploy operator in version 4.5.1 using pgo-deployer. When I deployed pod in container apiserver, operator, scheduler I got this same error:
`

  | time="2020-11-27T10:18:19Z" level=info msg="debug flag set to false"
-- | --
  | time="2020-11-27T10:18:24Z" level=info msg="postgres-operator apiserver starts" func="main.main()" file="apiserver.go:109" version=4.5.1
  | time="2020-11-27T10:18:24Z" level=info msg="Pgo Namespace is [operator451]" func="internal/apiserver.Initialize()" file="internal/apiserver/root.go:103" version=4.5.1
  | time="2020-11-27T10:18:24Z" level=info msg="InstallationName is [devtest]" func="internal/apiserver.Initialize()" file="internal/apiserver/root.go:110" version=4.5.1
  | time="2020-11-27T10:18:24Z" level=info msg="apiserver starts" func="internal/apiserver.Initialize()" file="internal/apiserver/root.go:122" version=4.5.1
  | time="2020-11-27T10:18:24Z" level=info msg="loading PermMap with 59 Permissions\n" func="internal/apiserver.initializePerms()" file="internal/apiserver/perms.go:187" version=4.5.1
  | time="2020-11-27T10:18:24Z" level=info msg="Config: \"pgo-config\" ConfigMap NOT found, creating ConfigMap from files from \"/default-pgo-config/\"" func="internal/config.initialize()" file="internal/config/pgoconfig.go:747" version=4.5.1
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x1189311]
  |  
  | goroutine 1 [running]:
  | github.com/crunchydata/postgres-operator/internal/config.(*PgoConfig).GetConfig(0x215f5c0, 0x7f7e3f780878, 0xc0004dcbe0, 0xc000042047, 0xb, 0x1581f1a, 0x1)
  | /opt/cdev/src/github.com/crunchydata/postgres-operator/internal/config/pgoconfig.go:525 +0x71
  | github.com/crunchydata/postgres-operator/internal/apiserver.Initialize()
  | /opt/cdev/src/github.com/crunchydata/postgres-operator/internal/apiserver/root.go:128 +0x377
  | main.main()
  | /opt/cdev/src/github.com/crunchydata/postgres-operator/apiserver.go:110 +0x42a

`
Main problem is:

`time="2020-11-27T10:18:18Z" level=info msg="Config: \"pgo-config\" ConfigMap NOT found, creating ConfigMap from files from \"/default-pgo-config/\"" func="internal/config.initialize()" file="internal/config/pgoconfig.go:747" version=4.5.1`
**What is the expected behavior?**

**Other information** (e.g. detailed explanation, related issues,  etc)
I checked configmaps in namespace and there is deployed configmap pgo-deployer-cm and pgo-config. Clusterrole pgo-deployer-cr can create, delete, get, list configmaps.

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: latest from today
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 3.11.232

**Comment by jkatz** [comment]
There should not be a panic in there, so there is at least a bug in that regard.

If you delete the `postgres-operator` Pod that is running, does everything start running?

**Comment by jkatz** [comment]
I tracked down the issue that was causing the panic, i.e. we were not handling any errors during the initialization process in the parent function. Oops :cry:

However, given how the code works, if you reboot the Operator Pod, everything should be up and running.

**Comment by AleksanderRoszig** [comment]
It doesn't helped. I tried restart pod few times. Three times I made new job with deploy via pgo-deplyer and still there is this same error in this containers.

**Comment by jkatz** [comment]
What ConfigMaps are in the `operator451` Namespace?

```
kubectl -n operator451 get cm
```

**Comment by AleksanderRoszig** [comment]
Like I said earlier:
"I checked configmaps in namespace and there is deployed configmap pgo-deployer-cm and pgo-config. Clusterrole pgo-deployer-cr can create, delete, get, list configmaps."

**Comment by jkatz** [comment]
I saw your note from earlier, however I'm trying to systematically debug this to try and help you to get unblocked without requiring the patch that I proposed in #2077.

If you can provide the output I am specifically asking for, this will help me to continue to try troubleshooting this. Otherwise, you will have to wait for the next release.

**Comment by AleksanderRoszig** [comment]
Okay, sorry. 

I have only oc client. Does it matters? 
```
oc -n operator451 get cm
NAME              DATA   AGE
pgo-config        41     12h
pgo-deployer-cm   1      1d
```

**Comment by jkatz** [comment]
Yup, `oc` + `kubectl` are interchangeable for the purposes of this exercise.

At this point, the only thing I can think of is that the ConfigMap `get` permission is missing from the `pgo-role`. What does:

```
oc -n operator451 describe role pgo-role
```

say?

**Comment by AleksanderRoszig** [comment]
```
oc -n operator451 describe role pgo-role
Error from server (NotFound): roles.authorization.openshift.io "pgo-role" not found
```
```
oc get role --all-namespaces | findstr "pgo-role"
---Nothing found
```
```
oc get rolebindings.rbac --all-namespaces | findstr "pgo-role"
operator451                         pgo-role                                                                      34h
```


```
oc describe rolebindings.rbac pgo-role -n operator451
Name:         pgo-role
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  Role
  Name:  pgo-role
Subjects:
  Kind            Name               Namespace
  ServiceAccount  postgres-operator  operator451
```



So now I see.
rolebindings already exist and is connected to service account but pgo-deployer can't create pgo-role because of:

That is my issue from yeasterday https://github.com/CrunchyData/postgres-operator/issues/2072

`"Error from server (Forbidden): error when creating \"/tmp/.pgo/operator451/output/pgo-role-rbac.yaml\": roles.rbac.authorization.k8s.io \"pgo-role\" is forbidden: attempt to grant extra privileges:`

**Comment by AleksanderRoszig** [comment]
When I created pgo-role using this file https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/templates/pgo-role-rbac.yaml.j2 there is no problem with creating this role. When I look at log from https://github.com/CrunchyData/postgres-operator/issues/2072 I see that role pgo-role that pgo-deployer is trying to deploy is more complex than this from file that I linked earlier. For example at start of the log there is: 
`map[]} ownerrules=[{[get] [ user.openshift.io] [users] [~] []} {[list] [ project.openshift.io] [projectrequests] [] []} {[get list] [ authorization.openshift.io] [clusterroles] [] []} {[get list watch] [rbac.authorization.k8s.io] [clusterroles] [] []}` if I think correctly.
