### ISSUE TITLE
Unable to create cluster with --restore-from flag when backups are in s3

### ISSUE THREAD

**Issue by eliranw** [CrunchyData/postgres-operator#2078]
**Describe the bug**
We did a helm uninstall of the operator and reinstalled it on a different namespace. When we uninstalled, all clusters were deleted. We tried restoring the deleted clusters from the S3 backups (We had a schedule for daily full backups) with pgo create cluster --restore-from, but it failed on the bootstrap pod. When you look into the <old-cluster>-pgbackrest pod that is created when you use the --restore-from flag, it is empty and doesn't look even configured to s3, and no stanza is created. This happened on 4.5.0, and after looking that 4.5.1 had a fix to this, upgrading to 4.5.1 still didn't help.

**To Reproduce**
1. Create a cluster configured to s3
2. Do a full backup
3. delete the cluster
4. Create a new cluster with --restore-from flag, and it fails.

**Expected behavior**
A new cluster is created and then restored to the backup of the old cluster

**Screenshots**
On prem solution without internet, so no screenshots.

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider): On Prem
* Storage being used (NFS, Hostpath, Gluster, etc): 
* Container Image Tag: 4.5.1
* PostgreSQL Version: 12.5
* Platform (Docker, Kubernetes, OpenShift): Openshift 
* Platform Version: 3.11

**Additional context**
We did a fix by manually pulling the latest full backup from the s3 bucket to a postgres VM and running a pgdump. Then we CURLed the dump file into a new cluster and then running a pg_restore straight from the new cluster without the restore-from flag, and then took a full backup. This took a lot of time and was quite messy.

**Comment by jkatz** [comment]
Did you specify the `--repo-type` in the `--restore-opts`? This is covered in the documentation:

[https://access.crunchydata.com/documentation/postgres-operator/4.5.1/pgo-client/common-tasks/#create-a-postgresql-cluster-using-a-backup-from-another-postgresql-cluster](https://access.crunchydata.com/documentation/postgres-operator/4.5.1/pgo-client/common-tasks/#create-a-postgresql-cluster-using-a-backup-from-another-postgresql-cluster)

**Comment by jkatz** [comment]
I was unable to reproduce this with two cases:

I created a cluster:

```
pgo create cluster seal \
  --pgbackrest-storage-type=s3 \
  --pgbackrest-s3-key=<redacted> \
  --pgbackrest-s3-key-secret=<redacted>
```

I create some data on the initial cluster:

```
CREATE TABLE whales (whale_name text);
INSERT INTO whales VALUES ('beluga'), ('blue'), ('minke');
```

### Case 1: Restore from a S3 repo to a cluster using S3 to back it

```
pgo create cluster whale \
  --restore-from=seal --restore-opts="--repo-type=s3" \
  --pgbackrest-storage-type=s3 \
  --pgbackrest-s3-key=<redacted> \
  --pgbackrest-s3-key-secret=<redacted>
```

### Case 2: Restore from a S3 repo to a cluster using a local repo to back it

```
pgo create cluster otter --restore-from=seal  --restore-opts="--repo-type=s3"
```

Both cases work and restored the data as expected.

Ensure that you have imported the proper containers for 4.5.1. In the future, also include the commands you used to run as well as any logs indicating a failure.

**Comment by eliranw** [comment]
Thanks for the quick reply. I did not see the part of the docs with the restore-opts.

**Comment by eliranw** [comment]
Hi, I have tested with the --restore-opts and the bootstrap pod still failed. The command to create the new cluster is 
`pgo --debug create cluster awx-preprod --pbackrest-storage-type=s3 --cpu=500m --memory 1Gi --pgbackrest-s3-bucket <redacted> --pgbackrest-s3-endpoint <redacted> --pggbackrest-s3-key <redacted> --pgbackrest-s3-key-secret <redacted> --pvc-size '5Gi' --pgbackrest-s3-ca-secret <redacted> --metrics -n awx-preprod --restore-from=pg-awx-preprod --restore-opts="--repo-type=s3"`
The following happens:
1. A pod called pg-awx-preprod-backrest-shared repo is created and goes into running state.
2. a pod called awx-preprod-bootstrap is created and falls to an error straight away, which fails on `ERROR: [078]: unable to remap invalid link 'pg_wal'`. I have seen issues with this on 4.5.0 and have ensured that the bootstrap pod is on 4.5.1. The cluster that we are trying to restore though is on 4.5.0, if that's the issue, but is there not an option to restore it if that's the problem?
