### ISSUE TITLE
panic: customresourcedefinitions.apiextensions.k8s.io is forbidden

### ISSUE THREAD

**Issue by sudheeshks179** [CrunchyData/postgres-operator#208]
Got panic when we tried to introduce a new postgress operator and test fail over.

panic: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:default:postgres-operator" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user "system:serviceaccount:default:postgres-operator"
```
goroutine 1 [running]:
main.main()
	/opt/cdev/src/github.com/crunchydata/postgres-operator/postgres-operator.go:86 +0x1c43
```
#Expected:
Throw only log error

**Comment by jmccormick2001** [comment]
will be fixed in upcoming 2.7 release, with that release CRDs are built by a script outside of the operator code, whereas in 2.6 and previous the CRDs were created programatically.
