### ISSUE TITLE
Database shutdown on pg_restore

### ISSUE THREAD

**Issue by krzystooof** [CrunchyData/postgres-operator#2083]
**Describe the bug**
Database shutdown on pg_restore.

**To Reproduce**
1. Create a big dump of database (3.9 GB in my case)
2. Try to restore it using `pg_restore -v--clean`

**Expected behavior**
Cleared and restored database.

**Actual behavior**
Afrer a while:
```
pg_restore: error: error returned by PQputCopyData: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

**Please tell us about your environment:**

* Operating System: CentOS
* Where is this running: OKD 3.11
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos7-12.5-4.5.1
* PostgreSQL Version: 12.5
* Platform (Docker, Kubernetes, OpenShift): Kubernetes - OKD
* Platform Version: 3.11

**Comment by jkatz** [comment]
Logs from the server would help. There should be in the `/pgdata/<clustername>/pg_log` directory.

- What are the memory resources that you allocated for the cluster?
- Are you running `pg_restore` within a Pod or from your local machine or elsewhere?
- If you are trying to perform a restore of a cluster that's already under management by the Operator, I suggest reading the [Disaster Recovery](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/) tutorial which covers more more efficient methods.

**Comment by krzystooof** [comment]
* **What are the memory resources that you allocated for the cluster?**
At the beginning it was 128 Mb (default after deploying from yaml). I've found out that it is not enough even for connecting with pgAdmin. Now it has 4 GB allocated.
* **Are you running pg_restore within a Pod or from your local machine or elsewhere?**
Within a Pod.
* **If you are trying to perform a restore of a cluster that's already under management by the Operator, I suggest reading the Disaster Recovery tutorial which covers more more efficient methods.**
The db cluster was not managed by any operator. I am trying to migrate it to HA system.

Yesterday there was a problem, but now repeated process to get the log, but it seems working now. The weirdest part is that nothing has changed (except time). I will reopen the issue if it will be back.
