### ISSUE TITLE
error: error upgrading connection: unable to upgrade connection: Unauthorized

### ISSUE THREAD

**Issue by Bhagi33** [CrunchyData/postgres-operator#2084]
I tried to upgrade existing postgres cluster 12.1 to postgres 13 version. with the following command 
 pgo upgrade rmgl --ccp-image-tag=centos7-12.5-4.5.1 -n pgo

unfortunately upgrade was failed. Not able to user pgo client, unable to perform any operations through pgo client. throwing below is the error

* Operating System:Cent os
* Where is this running ( Local , Cloud Provider) cloud
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: 
* PostgreSQL Version: 12
* Platform (Docker, Kubernetes, OpenShift):kubernetes
* Platform Version:centos 7

1) kubectl -n pgo port-forward svc/postgres-operator 8443:8443
error: error upgrading connection: unable to upgrade connection: Unauthorized

2) kubectl exec -it test-7479879b6b-9zlkl -n pg-op bash
error: unable to upgrade connection: Unauthorized

**Comment by jkatz** [comment]
For major upgrades, please see #1992 

Without any additional logs, it's difficult to diagnose why you cannot connect to the Operator, but it looks like it has to do with the permissions in your local Kubernetes environment. Check to ensure the proper ServiceAccounts with the appropriate Roles and RoleBindings are set up.
