### ISSUE TITLE
Migrating my current production DB to be managed by PGO without down time lor data loss.

### ISSUE THREAD

**Issue by OmarEltamasehy** [CrunchyData/postgres-operator#2086]
Dears,
Appreciate your support to migrate my production postgresql DB to be managed by Crunchy postgresql operator without down time.

cloud provider: GCP

**Comment by jkatz** [comment]
An answer around this topic is given in #2076, i.e: https://github.com/CrunchyData/postgres-operator/issues/2076#issuecomment-734912430

**Comment by OmarEltamasehy** [comment]
Dears,
Kindly be informed that my database is running in production mode and I
think that some data will be missed during restoring time so I need a way
to move the data then move the users to use the pgo cluster database and
ensure that no data is missed.

**Comment by jkatz** [comment]
Again, a method to do this is described in #2076. I have restated it in [this comment](https://github.com/CrunchyData/postgres-operator/issues/2076#issuecomment-738021427)
