### ISSUE TITLE
backrest fails with code 99

### ISSUE THREAD

**Issue by Trojaner** [CrunchyData/postgres-operator#2087]
**Describe the bug**
```
time="2020-12-02T13:11:26Z" level=info msg="pgo-backrest starts"
time="2020-12-02T13:11:26Z" level=info msg="debug flag set to false"
time="2020-12-02T13:11:26Z" level=info msg="backrest backup command requested"
time="2020-12-02T13:11:26Z" level=info msg="command to execute is [pgbackrest backup  --db-host=10.42.0.25 --db-path=/pgdata/prod-cluster]"
time="2020-12-02T13:11:26Z" level=info msg="command is pgbackrest backup  --db-host=10.42.0.25 --db-path=/pgdata/prod-cluster "
time="2020-12-02T13:12:20Z" level=error msg="command terminated with exit code 99"
time="2020-12-02T13:12:20Z" level=info msg="output=[]"
time="2020-12-02T13:12:20Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\nWARN: a timeline switch has occurred since the 20201201-014031F backup, enabling delta checksum\n      HINT: this is normal after restoring from backup or promoting a standby.\nWARN: resumable backup 20201201-014031F_20201202-130220I of same type exists -- remove invalid files and resume\nERROR: [099]: raised from local-1 protocol: invalid type at 'BRBLOCK1048576'\n]"
time="2020-12-02T13:12:20Z" level=error msg="command terminated with exit code 99"
```

` pgo create cluster -n pgo prod-cluster --replica-count=0 --storage-config default`

Additionally the WAL is never cleared, hence the database volume keeps getting bigger and bigger (about 150 GB in a week). How can I make it auto clear?

**Please tell us about your environment:**
pgo 4.5.0
pgo-apiserver 4.5.0

* Operating System: Ubuntu 20.04.1 LTS
* Where is this running: Bare Metal
* Storage being used: Longhorn
* Container Image Tag: (default value)
* PostgreSQL Version: 12.4
* Platform: Kubernetes
* Platform Version: 1.19.2

**Comment by jkatz** [comment]
The error message seems to indicate there is an invalid backup:

```
WARN: resumable backup 20201201-014031F_20201202-130220I of same type exists -- remove invalid files and resume
ERROR: [099]: raised from local-1 protocol: invalid type at 'BRBLOCK1048576'\n
```

You could manually remove the invalid files as specified, or clear the backups using a backup retention policy (see below)

RE "database volume" are you referring to the data directory or backup retention? Backup retention is covered in the documentation in various places. You can combine it with scheduling backups to ensure you have an automated retention policy:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/#set-backup-retention](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/#set-backup-retention)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#scheduling-backups](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#scheduling-backups)

If your `pg_wal` or equivalent archive directory is not being cleared on your PostgreSQL data directory, this may be a function of your local configuration and/or a replication slot that is not being acknowledged. Note that the PostgreSQL Operator does not configure replication slots, so if an unacknowledged slot is the case, then those were manually added. Here are some blog posts on the topic:

- [https://info.crunchydata.com/blog/postgresql-monitoring-for-application-developers-dba-stats](https://info.crunchydata.com/blog/postgresql-monitoring-for-application-developers-dba-stats)
- [https://info.crunchydata.com/blog/wheres-my-replica-troubleshooting-streaming-replication-synchronization-in-postgresql](https://info.crunchydata.com/blog/wheres-my-replica-troubleshooting-streaming-replication-synchronization-in-postgresql)

**Comment by Trojaner** [comment]
> RE "database volume" are you referring to the data directory or backup retention?

The pg_wal directory

> If your pg_wal or equivalent archive directory is not being cleared on your PostgreSQL data directory, this may be a function of your local configuration and/or a replication slot that is not being acknowledged.

I am not using any replicas at the moment (--replica-count=0)

**Comment by jkatz** [comment]
- Does `SELECT * FROM pg_replication_slots;` return anything?
- What does `SHOW max_wal_size;` say?

**Comment by Trojaner** [comment]
> Does SELECT * FROM pg_replication_slots; return anything?

It is empty

> What does SHOW max_wal_size;

1GB

**Comment by jkatz** [comment]
Do the PostgreSQL logs indicate that archive pushes are failing? You can find those in the `pg_log` directory.

**Comment by Trojaner** [comment]
Yes, they seem to be failing
```
2020-12-02 17:37:00.400 UTC [230] LOG:  archive command failed with exit code 41
2020-12-02 17:37:00.400 UTC [230] DETAIL:  The failed archive command was: source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push "pg_wal/000000040000000A000000AB"
ERROR: [041]: unable to load info file '/backrestrepo/prod-cluster-backrest-shared-repo/archive/db/archive.info' or '/backrestrepo/prod-cluster-backrest-shared-repo/archive/db/archive.info.copy':
       FileOpenError: raised from remote-0 protocol on 'prod-cluster-backrest-shared-repo': unable to open file '/backrestrepo/prod-cluster-backrest-shared-repo/archive/db/archive.info' for read: [5] Input/output error
       FileOpenError: raised from remote-0 protocol on 'prod-cluster-backrest-shared-repo': unable to open file '/backrestrepo/prod-cluster-backrest-shared-repo/archive/db/archive.info.copy' for read: [5] Input/output error
       HINT: archive.info cannot be opened but is required to push/get WAL segments.
       HINT: is archive_command configured correctly in postgresql.conf?
       HINT: has a stanza-create been performed?
       HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
```

**Comment by jkatz** [comment]
Thanks. I spoke with some of the pgBackRest developers and this appears to be a problem with the underlying storage. The recommendation is to check what is going on with that and bring it back into a valid state.

Based upon what happens after that, you may need to reinitialize your pgBackRest repository, but that can't be determined until the storage system is in a good state.

**Comment by Trojaner** [comment]
Thank you

**Comment by jkatz** [comment]
You're welcome.

As I don't see any immediate issue with the Operator code or any immediate places where we can improve the documentation (though perhaps this can be added to a troubleshooting pgBackRest section), I will be closing this out.
