### ISSUE TITLE
unable to add replicas after upgrade(pgo upgrade mycluster) from centos7-12.4-4.5.0 to centos7-12.5-4.4.2

### ISSUE THREAD

**Issue by Bhagi33** [CrunchyData/postgres-operator#2089]
** Which example are you working with? ** pgo upgrade rmgl --ccp-image-tag=centos7-12.5-4.5.1 -n pg-13-ver

**What is the current behavior?** 
1) after upgrade,all replicas scaled down,only primary is created with centos7-12.5-4.5.1 version. 
2) Manually i tired to add 2 replicas -- pgo scale rmgl --replica-count=2 -n pg-13-ver. 
WARNING: Are you sure? (yes/no): yes
created Pgreplica rmgl-huoq
created Pgreplica rmgl-vmsy
but replicas are not added.waited for long time more than 2 hours

**What is the expected behavior?**
1)  expecting after upgrade all replicas should comeup automatically.
2) why replicas are not adding even i created manually.

**Other information** (e.g. detailed explanation, related issues,  etc)
1)  expecting after upgrade all replicas should comeup automatically.

2) why replicas are not adding even i created manually.
again i tried another way to create another cluster, but this also not successful.

3)pgo create cluster hippo13 --ccp-image-tag=centos7-13.0-4.5.0 --restore-from=rmgl  -n pg-13-ver
Error: Cluster restored-cluster is currently bootstrapping from cluster rmgl, please try again once it is completes

**Please tell us about your environment:**

* Operating System: centos 7
* Where is this running ( Local , Cloud Provider):cloud
* Storage being used (NFS, Hostpath, Gluster, etc):NFS
* Container Image Tag: centos7-12.5-4.4.2
* PostgreSQL Version:12.5
* Platform (Docker, Kubernetes, OpenShift):Kubernetes
* Platform Version:

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by jkatz** [comment]
Going from 4.5.0 to 4.4.2 is a downgrade. 4.5.1 is the latest version.

GitHub is mislabeling what the latest version is. I will go see if this can be corrected.

**Comment by jkatz** [comment]
I would also recommend reading the documentation on versioning:

[https://github.com/CrunchyData/postgres-operator/blob/master/CONTRIBUTING.md#releases--versioning](https://github.com/CrunchyData/postgres-operator/blob/master/CONTRIBUTING.md#releases--versioning)

**Comment by Bhagi33** [comment]
Can you please let me know why replicas are not adding,even below commands are successful..
pgo scale rmgl --replica-count=2 -n pg-13-ver
WARNING: Are you sure? (yes/no): yes
created Pgreplica rmgl-huoq
created Pgreplica rmgl-vmsy

**Comment by Bhagi33** [comment]
> I would also recommend reading the documentation on versioning:
> 
> https://github.com/CrunchyData/postgres-operator/blob/master/CONTRIBUTING.md#releases--versioning

Hi
Can you  let me know why replicas are not adding,even below commands are successful..
pgo scale rmgl --replica-count=2 -n pg-13-ver
WARNING: Are you sure? (yes/no): yes
created Pgreplica rmgl-huoq
created Pgreplica rmgl-vmsy

**Comment by jkatz** [comment]
Please ensure you're Operator version is consistent with the version of the containers you are running. Information on upgrading is here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/)

If you are still having issues after that, please send over logs from the `operator` container within the `postgres-operator` Pod. Without any logs, it is very challenging to provide any debugging guidance.
