### ISSUE TITLE
Operator does not work on k8s clusters with locked down private kube API endpoints

### ISSUE THREAD

**Issue by dsargent3220** [CrunchyData/postgres-operator#2092]
Azure's AKS does not allow direct communication to the Kube API via the private internal IP, because we have to provide pods with the KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT environment vars to make them work.
We can provide these env vars to the job that creates the operator but that does not then set those env vars for the containers created in the operator pod and there does not appear to be any config to set them.

1. Create an AKS cluster
2. Try to install on the AKS cluster, setting the environment KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT  variables to the public kube API URL for pgo-deploy job
3. The job should start correctly and spin up the operator pod but the containers in the operator pod fail to start correctly as they cannot talk to the kube API
4.  fin

**Expected behavior**
We should be able to set the KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT environment vars for the operator

**Please tell us about your environment:**
Azure AKS cluster, three nodes, nothing special.

**Comment by jkatz** [comment]
The template files that the Operator uses exist in a ConfigMap called `pgo-config`. You can add the environmental variables in there.

What version of AKS are you using?

**Comment by dsargent3220** [comment]
Thanks @jkatz , that doesn't seem very automatible.  I"ve hacked the env var in and gotten it to work.
Version of AKS??  I'm not following on that.

**Comment by jkatz** [comment]
This is the first time this issue has come up, even with customers we have who run AKS, so there has not been a reason to automate this to date. What I proposed above was to help get you unblocked and moving forward 😛 

If you wanted to automate it with existing install methods, you could modify the templates before installing the Operator. While it's still not configurable in a convenient way, it does at least help move the ball forward.

> Version of AKS?? I'm not following on that.

What version of Kubernetes are you running? I am correlating that to the current version of AKS, so we can further investigate what is different in your environment vs. other environments to see if any code changes are required.

**Comment by dsargent3220** [comment]
@jkatz   Ahhh.  It never occured to me there are "version" of an AKS cluster.  Sorry about that.  We've been running on prem cluster with Rancher for a couple years but are just getting into the cloud.
We use Rancher on prem and so wanted to keep using that for AKS as well.  Looks like Rancher hasn't updated to the latest AKS version for a while.  So I think that is the problem.  We have Enterprise support through them and I've already asked them to get that added to an upcoming release. 
I'm going to spin up a small cluster using the Azure portal and see if we can talk directly to the kube API over the private IPs.  I'll let you know what I find.

**Comment by jkatz** [comment]
Cool, curious to learn more. Thanks!

**Comment by jmealo** [comment]
@dsargent3220: I'll be deploying to AKS. Did you have any further issues? Thanks :)

**Comment by jkatz** [comment]
We continuously test deployments to AKS. There are typically no issues in deploying to "vanilla" AKS clusters. I would be mindful of PSPs or other security policies that may be set up, as typically it's other things in the environment that tend to cause issues.
