### ISSUE TITLE
INFO Logs continuously printing in postgres cluster

### ISSUE THREAD

**Issue by vg02111989** [CrunchyData/postgres-operator#2097]
Hi,
I am using 4.4.1 version of the crunchy data Postgres operator.

I want to implement centralized Postgres logging, for the same, I had disabled logging_collector and set log_destination as "stderr" so that logs will redirect to standard output and kept the log_statement as "mod".
 
The standard output is getting lots of INFO logs in both Primary and Replica sets stating which node is leader and having the lock.
for eg:
_2020-12-03 14:15:17,829 INFO: no action.  i am the leader with the lock_

Is there any way I can disable these logs or change log level from INFO to ERROR or something else by which we will not get those frequent logs

Also,
is there any way to pass these configurations like _logging_collector, log_destination_, etc while creating posters cluster or while deploying postgres-operator because as of now we have to update the dcs config inside _hacluster-pgha-config_ map, which will not be suggested approach in the production environment

Thanks a lot in advance for the help

**Comment by vg02111989** [comment]
@jkatz 
Any suggestions from your side will always be very helpful.

Thanks a lot in advance

**Comment by jkatz** [comment]
The settings for setting the Patroni log level are documented here: [https://patroni.readthedocs.io/en/latest/SETTINGS.html#log](https://patroni.readthedocs.io/en/latest/SETTINGS.html#log)

You can read about cluster customization here: [https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/). You can pass in an initial custom configuration on the `--custom-config` flag.

**Comment by vg02111989** [comment]
Hi Jonathan

I had already tried using --custom-config option:
The approach I tried is:

1. I had created the postgres-ha.yaml file with some custom configuration like max_connections,  log_destination under dcs config.
2. Created the config map referring to that postgres-ha.yaml file.
3. Passed this config map as the option with --custom-config flag, but it haven't updated inside the postgressql.conf file.

Seems that way is not working properly

Is there any other way of doing the same

**Comment by vg02111989** [comment]
> The settings for setting the Patroni log level are documented here: https://patroni.readthedocs.io/en/latest/SETTINGS.html#log
> 
> You can read about cluster customization here: https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/. You can pass in an initial custom configuration on the `--custom-config` flag.

I tried to follow the patroni docs for changing the log level from default INFO to ERROR by updating in dcs config as PATRONI_LOG_LEVEL: ERROR, but its not affecting.

Can you please elaborate a bit more if possible so I would be able to achieve.

It would of great help

Thanks

**Comment by vg02111989** [comment]
Hi
Any update

How I can set the PATRONI_LOG_LEVEL or is there any way to turning off patroni logging to stderr
as PATRONI logs are creating mess when we are trying to implement centralized logging with ELK

Any suggestions will be highly appreciated

Thanks a lot in advance

**Comment by jkatz** [comment]
If you are looking for immediate support, please review the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page. Otherwise, questions on GitHub are answered when someone in the community is able to review it.
