### ISSUE TITLE
Missing "thirdpartyresource.extentions pg-clone.crunchydata.com not found" error when creating cluster

### ISSUE THREAD

**Issue by vladimirvivien** [CrunchyData/postgres-operator#21]
I pulled the latest source code, built locally, and deployed necessary resources successfully:
```
kubectl get deployment,po,configMap,thirdpartyresource
NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/postgres-operator   1         1         1            1           2m

NAME                                    READY     STATUS    RESTARTS   AGE
po/postgres-operator-2889167354-mjdtk   1/1       Running   0          2m

NAME               DATA      AGE
cm/operator-conf   6         1h

NAME                                             DESCRIPTION                             VERSION(S)
thirdpartyresources/pg-backup.crunchydata.com    A postgres backup ThirdPartyResource    v1
thirdpartyresources/pg-cluster.crunchydata.com   A postgres cluster ThirdPartyResource   v1
thirdpartyresources/pg-upgrade.crunchydata.com   A postgres upgrade ThirdPartyResource   v1
```
However, when I attempt to create a cluster, I get the following (this is true with other pgo commands):
```
pgo create cluster mycluster
DEBU[0000] kubeconfig path is /home/vladimir/admin.conf
DEBU[0000] namespace is default
DEBU[0000] ConnectToKube called
ERRO[0000] thirdpartyresources.extensions "pg-clone.crunchydata.com" not found
ERRO[0000] required pg-clone.crunchydata.com TPR was not found on your kube cluster
```
It is worth noting this works ok when I pull the pre-built binaries ver 1.2 for `postgres-operator` and `pgo`.

**Comment by vladimirvivien** [comment]
Hi @jmccormick2001 
Any idea what is causing this error ? I just tried again with a rebase and still getting the same error.

Thank you.

**Comment by jmccormick2001** [comment]
you might make sure to restart the operator deployment, completely removing it, and restarting it, you should have the clone TPR created at startup time by this new version of the operator deployment.  I'm about to tag version 1.3 today as well and will generate some new binaries for that release.  I retested it all this morning on a fresh build/VM and things seem to work, this is a Centos7 kubeadm 1.6 VM.

**Comment by jmccormick2001** [comment]
1.3 is ready for you to try out.

**Comment by vladimirvivien** [comment]
@jmccormick2001 thanks for responding.
