### ISSUE TITLE
Handling connection for 8443

### ISSUE THREAD

**Issue by ckvtvm-arch** [CrunchyData/postgres-operator#2101]
** Which example are you working with? **

Setting up operator cluster . running pgo version

**What is the current behavior?**

af71194@LC02CHB58MD6R postgres-operator % oc -n "$PGO_OPERATOR_NAMESPACE" port-forward deployment/postgres-operator 8443
Forwarding from 127.0.0.1:8443 -> 8443
Forwarding from [::1]:8443 -> 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443

**What is the expected behavior?**

connection successful

**Other information** (e.g. detailed explanation, related issues,  etc)

Not able to complete the port forwarding.

**Please tell us about your environment:**

CRC

* Operating System: Mac
* Where is this running ( Local , Cloud Provider) - Local
* Storage being used (NFS, Hostpath, Gluster, etc): Default
* Container Image Tag: NA
* PostgreSQL Version: 4.5.0 provided by Crunchy Data
* Platform (Docker, Kubernetes, OpenShift): openshift
* Platform Version:4.5.0 provided by Crunchy Data

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by jkatz** [comment]
I don't see any errors listed above. It seems that the port forward is successfully accepting connections, based on the `Handling connection for 8443` messages. That is what one typically sees when using `pgo`. Are there any additional errors?

**Comment by ckvtvm-arch** [comment]
But command never completes the port forwarding and waiting for more than 30 mts , please let me know if there is a way to debug this connection waiting

**Comment by cbandy** [comment]
The `oc port-forward` command doesn't end; it is busy forwarding connections. Run `pgo` commands from another terminal window or background the `oc port-forward` process using your shell job controls.

To end the `oc port-forward` command, press <kbd>Ctrl</kbd> + <kbd>C</kbd>.

**Comment by ckvtvm-arch** [comment]
af71194@LC02CHB58MD6R ~ % pgo version
Error: The PGO_APISERVER_URL environment variable or the --apiserver-url flag needs to be supplied.
af71194@LC02CHB58MD6R ~ % export PGO_APISERVER_URL="https://127.0.0.1:8443"
af71194@LC02CHB58MD6R ~ % pgo version                                      
FATA[0000] failed to set up TLS client: PGO_CA_CERT not specified 
af71194@LC02CHB58MD6R ~ % export PGO_CA_CERT=/Users/af71194/certificates/server.crt                                                                       
af71194@LC02CHB58MD6R ~ % export PGO_CLIENT_CERT=/Users/af71194/certificates/server.crt
af71194@LC02CHB58MD6R ~ % export PGO_CLIENT_KEY=/Users/af71194/certificates/server.key 
af71194@LC02CHB58MD6R ~ % pgo version                                                  
pgo client version 4.4.2
Error: Authentication Failed: 401

af71194@LC02CHB58MD6R ~ % pgo version
pgo client version 4.4.2
Error: Authentication Failed: 401

af71194@LC02CHB58MD6R ~ % echo "username:password" > $HOME/.pgouser
af71194@LC02CHB58MD6R ~ % pgo version                              
pgo client version 4.4.2
Error: Authentication Failed: 401

**Comment by jkatz** [comment]
I don't believe your authentication credentials are set up properly. I would recommend following the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/) and [tutorial](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/) for how to get this set up. If you want to see the manual steps that the quickstart takes for loading the user credentials you can follow them here: [https://raw.githubusercontent.com/CrunchyData/postgres-operator/master/installers/kubectl/client-setup.sh](https://raw.githubusercontent.com/CrunchyData/postgres-operator/master/installers/kubectl/client-setup.sh)

If you are setting this up on your own, the default credentials will be stored in a Secret in the same namespace as the Operator with a name of `pgouser-admin` (or `pgouser-<USERNAME>`). You can read the credentials from the Secret and store them locally.

**Comment by ckvtvm-arch** [comment]
i tried for few hours trying to create .pgouser, pgouser  pgorole , secrets etc.  can you please let me know how you have achieved this:

1) .pgouser in home directory as username:password
2) .pgorole in home directory as pgoadmin:version (my guess as documentation is not available, but permission to apply version using admin role)
3) pgorole in /conf/postgres-operator as username:password
4) secrets pgouser-admin - copy the user name and password and export to pgo_username and pgo_password
5) make installrbac , but it fails due to command not found and variable not set

I tried makeinstall RBAC file, but that doesnt works too.

**Comment by jkatz** [comment]
I'm not quite sure what you are doing, but this deviates from the aforementioned [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/) and [tutorial](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/) links, which provide scripts that automate the setup of both the Operator and the `pgo` client.

The `client-install.sh` will, by default, install the various credential files into a directory in `${HOME}/.pgo/${PGO_OPERATOR_NAMESPACE}`. The use credentials go into a file called `pgouser` within that directory.

However, the `pgo` client will look for where these files are using the `PGOUSER` environmental variable, so if you are placing the credentials in your come director, you would have to set `PGOUSER` to point to those. Using what you said in [https://github.com/CrunchyData/postgres-operator/issues/2101#issuecomment-740981310](https://github.com/CrunchyData/postgres-operator/issues/2101#issuecomment-740981310) this would be:

```
export PGOUSER=$HOME/.pgouser
```

The `client-install.sh` script, when invokved, prints out the directions on how to set up that variable.

**Comment by ckvtvm-arch** [comment]
let me delete my cluster and install operator once again

**Comment by ckvtvm-arch** [comment]
it is solved now - i used pgo version --debug

**Comment by jkatz** [comment]
Excellent!
