### ISSUE TITLE
Standby cluster create a pgbackrest job to its own directory on s3 and it fails

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#2102]
After a month after creating standby cluster i noticed a failed `backrest-backup-pgsql-cluster-standby` job with logs:
![1](https://user-images.githubusercontent.com/42073646/101463035-f7f18e00-394d-11eb-964f-c3d520332ded.jpg)

If I understand correctly, standby cluster shouldnt create its own backups, because it uses main cluster backrest folder. But it is more of a speculation of mine.

Standby cluster was created with this command:

```
pgo create cluster -n pgo pgsql-cluster-standby \
--replica-count=2 \
--metrics \
--pgbadger \
--pgbouncer \
--pgbouncer-replicas=3 \
--sync-replication \
--pod-anti-affinity=preferred \
--pgbouncer \
--pgbouncer-replicas=3 \
--pgbackrest-storage-type=s3 \
--pgbackrest-s3-key= ...  \
--pgbackrest-s3-key-secret= ... \
--pgbackrest-s3-bucket= ... \
--pgbackrest-s3-endpoint=s3.amazonaws.com \
--pgbackrest-s3-region= ... \
--pgbackrest-repo-path='/backrestrepo/pgsql-cluster-backrest-shared-repo' \
--standby
```

`pgo show schedule pg-standby-cluster -n pgo` returnes `No schedules found.`

Google Kubernetes Engine cluster
Container Image Tag: crunchy-postgres-gis-ha:centos7-12.5-3.0-4.5.1
Platform Version: 1.17.13-gke.2001

Thank you!

**Comment by jkatz** [comment]
@aprilito1965 Thanks for reporting. This is an undesired behavior, or as some people would term it, a "bug" -- #2104 should address this, and it will be backpatched down to the 4.4 line.
