### ISSUE TITLE
how to recover from stanza create failure

### ISSUE THREAD

**Issue by nevetS** [CrunchyData/postgres-operator#2105]
** Which example are you working with? **
pgo create cluster

I passed in a bad s3 configuration.  I want to start over.

**What is the current behavior?**
pgo status clustername shows 0 databases
kubectl get pods shows a series of stanza-create pods in error
pgo delete cluster responds with Error: no clusters found
Updating backrest-repo-config secret with updated settings doesn't resolve issue

**What is the expected behavior?**
I would expect I can either delete the cluster or update the configuration.  Deleting the cluster is not possible, and I don't think I'm updating the configuration properly.

**Comment by jkatz** [comment]
Does the cluster still exist?

```
pgo show cluster --all
```

If stanza-create does not fire, we don't consider the cluster as being in a valid date. `pgo delete cluster` should remove the entry in the `pgcluster` custom resource.

Can you try creating a new cluster?

**Comment by nevetS** [comment]
That was the problem...

`pgo show cluster --all` spelled out that I should have been using the namespace in the commands.
