### ISSUE TITLE
I have a postgres cluster running with version 4.3.0 - is there an upgrade path to 4.5.1

### ISSUE THREAD

**Issue by devopsevd** [CrunchyData/postgres-operator#2109]
**Other information** (e.g. detailed explanation, related issues,  etc)
Deployed a postgres cluster using postgres operator version 4.3.0.
Looking at options to upgrade to version 4.5.1
Is there a prescribed or supported upgrade path from 4.3.0 to 4.5.1

**Please tell us about your environment:**

* Where is this running ( Local , Cloud Provider) - GKE
* Storage being used (NFS, Hostpath, Gluster, etc): Google storage - PVC
* Container Image Tag:  pgo-deployer:centos7-4.3.0
* PostgreSQL Version: centos7-12.2-4.3.0
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: GKE 1.17.13-gke.1400

**Comment by jkatz** [comment]
There is an entire section of the documentation just on upgrading:

[https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/)

As some general advice:

- The automated upgrade method is your easiest bet, but like with everything, you should test prior and ensure you are comfortable with it.
- Do not attempt to perform a PostgreSQL major version upgrade at the same time (e.g. 12 => 13).
