### ISSUE TITLE
No image for Postgres 9.6 operator 4.3.0

### ISSUE THREAD

**Issue by AleksanderRoszig** [CrunchyData/postgres-operator#2110]
Hi
I can't find image on dockerhub for operator in version 4.3.0 and PostgreSQL 9.6.
https://hub.docker.com/r/crunchydata/crunchy-postgres-ha/tags?page=1&ordering=last_updated&name=4.3.0

https://catalog.redhat.com/software/containers/crunchydata/crunchy-postgres-ha/5e10c5a0ecb5246c09cb0f02?tag=latest&push_date=1605560850000

but in documentation I see that it should be available https://access.crunchydata.com/documentation/postgres-operator/4.3.0/configuration/compatibility/

I tried create cluster with images with tags centos7-9.6.16-4.2.0 and centos7-9.6.16-4.2.1 but it doesn't works because of 
log from pod:
"Thu Dec 10 13:16:21 UTC 2020 INFO: Applying SSHD..
Thu Dec 10 13:16:21 UTC 2020 INFO: Checking for SSH Host Keys in /sshd..
Thu Dec 10 13:16:21 UTC 2020 ERROR: No ssh_host_rsa_key found in /sshd.  Exiting.."

Can you push this image to repository?

**Comment by jkatz** [comment]
You can view the images that are publicly available in the Developer Portal: [https://www.crunchydata.com/developers](https://www.crunchydata.com/developers) and the policy on which images are available publicly. For how images are released, please view the note in the README on [release](https://github.com/CrunchyData/postgres-operator#releases).

I would also strongly suggest running a newer version of the Operator than 4.3.0, as there have been several bug fixes releases in the 4.3 series itself (latest being 4.3.4).
