### ISSUE TITLE
pg_wal filling up and archive files not being deleted and backups failing

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#2115]
pgo 4.5.1 

cluster info as follows:
```
$ pgoc pgo show cluster retroelk-prod1-azure -n pgo

cluster : retroelk-prod1-azure (crunchy-postgres-gis-ha:centos7-11.9-2.5-4.5.0)
	pod : retroelk-prod1-azure-9dd6fd444-phhw6 (Running) on prod1-db-1 (2/2) (primary)
		pvc: retroelk-prod1-azure (100Gi)
	pod : retroelk-prod1-azure-cmyc-55fd469bdc-p6z7g (Running) on prod1-db-0 (2/2) (replica)
		pvc: retroelk-prod1-azure-cmyc (100G)
	pod : retroelk-prod1-azure-tapu-67bc49c74b-v4n28 (Running) on prod1-db-2 (2/2) (replica)
		pvc: retroelk-prod1-azure-tapu (100G)
	resources : CPU: 8 Memory: 16Gi
	limits : CPU: 15 Memory: 48Gi
	deployment : retroelk-prod1-azure
	deployment : retroelk-prod1-azure-backrest-shared-repo
	deployment : retroelk-prod1-azure-cmyc
	deployment : retroelk-prod1-azure-pgbouncer
	deployment : retroelk-prod1-azure-tapu
	service : retroelk-prod1-azure - ClusterIP (10.105.129.54)
	service : retroelk-prod1-azure-pgbouncer - ClusterIP (10.101.227.65)
	service : retroelk-prod1-azure-replica - ClusterIP (10.98.138.154)
	pgreplica : retroelk-prod1-azure-cmyc
	pgreplica : retroelk-prod1-azure-tapu
	labels : pgouser=admin service-type=NodePort workflowid=4098ec34-1913-48e8-86a6-b46690c41030 name=retroelk-prod1-azure pg-pod-anti-affinity= pgo-backrest=true crunchy-postgres-exporter=true custom-config=retroelk-custom-config pgo-version=4.5.0 NodeLabelValue=postgres autofail=true crunchy-pgbadger=false crunchy-pgha-scope=retroelk-prod1-azure deployment-name=retroelk-prod1-azure pg-cluster=retroelk-prod1-azure
```

Archives got backed up I believe because backrest repo disk was full.  But now have cleared space on the backrest repo disk (see issue #2111) but archives are still not being cleared from the primary.  When I try to run a backup both to s3 and locally I get failures.  Trying to run it with debug turned on so will post logs here as soon as I get them again as it takes it a while to fail.

**Comment by alrooney** [comment]
Here's failure from running backup:
```
DEBUG:     storage/storage::storageList: => null\n2020-12-10 22:05:54.297 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)\n2020-12-10 22:05:54.397 P00   INFO: backup command end: aborted with exception [082]\n2020-12-10 22:05:54.397 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)\n2020-12-10 22:05:54.398 P00  DEBUG:     common/lock::lockRelease: => true\n2020-12-10 22:05:54.398 P00  DEBUG:     common/exit::exitSafe: => 82\n2020-12-10 22:05:54.398 P00  DEBUG:     main::main: => 82\n]"
time="2020-12-10T22:05:54Z" level=info msg="stderr=[WARN: resumable backup 20201210-172601F of same type exists -- remove invalid files and resume\nERROR: [082]: WAL segment 00000010000016AF000000A6 was not archived before the 60000ms timeout\n       HINT: check the archive_command to ensure that all options are correct (especially --stanza).\n       HINT: check the PostgreSQL server log for errors.\n]"
time="2020-12-10T22:05:54Z" level=error msg="command terminated with exit code 82"
```

**Comment by jkatz** [comment]
One nice thing about pgBackRest is that it tends to give detailed error messages:

```
WARN: resumable backup 20201210-172601F of same type exists -- remove invalid files and resume
ERROR: [082]: WAL segment 00000010000016AF000000A6 was not archived before the 60000ms timeout
HINT: check the archive_command to ensure that all options are correct (especially --stanza).
HINT: check the PostgreSQL server log for errors.
```

I would guess that you have not made changes to the `archive_command` outside of the defaults that the Operator sets. I would recommend checking the PostgreSQL server logs for errors. It also sounds like an attempted backup failed and may need to be rerun.

I will note that this is skewing towards [production support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) instead of issues/enhancements/documentation requests with the Operator.

**Comment by alrooney** [comment]
Thanks @jkatz I looked in the pg_logs and there is not data there regarding the archiving - there was when the disk was full but nothing now.  And there's no reason for the timeout either - it happens both with local disk and s3 and on different wal segments.

**Comment by jkatz** [comment]
Is the pgBackRest Pod reachable from the PostgreSQL Pod? You can verify this by running `pgbackrest info` from the PostgreSQL Pod.

**Comment by alrooney** [comment]
Yes pgBackRest Pod is reachable from the pg pod.  Thanks for suggesting I confirm that but yes it is reachable.  Here's output of command run on the pg pod:
```
$ kk exec -ti retroelk-prod1-azure-9dd6fd444-phhw6 -c database -- bash
bash-4.2$ pgbackrest info
stanza: db
    status: ok (backup/expire running)
    cipher: none

    db (current)
        wal archive min/max (11-1): 00000010000015ED0000007F/00000010000016A00000008A

        full backup: 20201203-060004F
            timestamp start/stop: 2020-12-03 06:00:04 / 2020-12-03 06:20:45
            wal start/stop: 00000010000015ED0000007F / 00000010000015ED000000F1
            database size: 22.3GB, backup size: 22.3GB
            repository size: 5.3GB, repository backup size: 5.3GB

        full backup: 20201204-060004F
            timestamp start/stop: 2020-12-04 06:00:04 / 2020-12-04 06:18:30
            wal start/stop: 00000010000016060000008A / 0000001000001606000000EE
            database size: 22.5GB, backup size: 22.5GB
            repository size: 5.4GB, repository backup size: 5.4GB

        full backup: 20201205-060004F
            timestamp start/stop: 2020-12-05 06:00:04 / 2020-12-05 06:18:30
            wal start/stop: 00000010000016220000003A / 00000010000016220000007D
            database size: 22.7GB, backup size: 22.7GB
            repository size: 5.4GB, repository backup size: 5.4GB

        full backup: 20201206-060003F
            timestamp start/stop: 2020-12-06 06:00:03 / 2020-12-06 06:20:02
            wal start/stop: 000000100000163A00000014 / 000000100000163A00000056
            database size: 22.9GB, backup size: 22.9GB
            repository size: 5.4GB, repository backup size: 5.4GB

        full backup: 20201207-060003F
            timestamp start/stop: 2020-12-07 06:00:03 / 2020-12-07 06:18:38
            wal start/stop: 000000100000165000000061 / 0000001000001650000000AC
            database size: 23GB, backup size: 23GB
            repository size: 5.4GB, repository backup size: 5.4GB

        full backup: 20201208-060004F
            timestamp start/stop: 2020-12-08 06:00:04 / 2020-12-08 06:18:10
            wal start/stop: 000000100000166B0000002E / 000000100000166B000000A4
            database size: 23.2GB, backup size: 23.2GB
            repository size: 5.5GB, repository backup size: 5.5GB

        full backup: 20201209-060004F
            timestamp start/stop: 2020-12-09 06:00:04 / 2020-12-09 06:21:27
            wal start/stop: 0000001000001682000000F5 / 00000010000016830000004F
            database size: 23.4GB, backup size: 23.4GB
            repository size: 5.5GB, repository backup size: 5.5GB
bash-4.2$ 
```

Also I increased the archive timeout to 120s and still having issues.  But strange thing is that it is happening on different wal segments:
```
$ kk get po
NAME                                                        READY   STATUS      RESTARTS   AGE
backrest-backup-retroelk-prod1-azure-4vh5d                  0/1     Error       0          41m
backrest-backup-retroelk-prod1-azure-7gv7j                  1/1     Running     0          5m14s
backrest-backup-retroelk-prod1-azure-d6hx9                  0/1     Error       0          25m
pgo-client-5f59c74967-2trwh                                 1/1     Running     0          21d
postgres-operator-6d4f8dc6d5-wtvsz                          4/4     Running     0          58d
radius-prodkdcam1-864885f6d8-bzfh5                          2/2     Running     0          51d
radius-prodkdcam1-backrest-shared-repo-79c45f7448-k6xd7     1/1     Running     0          51d
radius-prodkdcam1-full-sch-backup-rlhm7                     0/1     Completed   0          16h
radius-prodkdcam1-qzyr-6b8f88fb79-q95xg                     2/2     Running     0          51d
retroelk-prod1-azure-9dd6fd444-phhw6                        2/2     Running     1          58d
retroelk-prod1-azure-backrest-shared-repo-9cd4f6464-4bcm8   1/1     Running     0          58d
retroelk-prod1-azure-cmyc-55fd469bdc-p6z7g                  2/2     Running     0          58d
retroelk-prod1-azure-pgbouncer-849b4fdcf4-2r427             1/1     Running     0          11d
retroelk-prod1-azure-pgbouncer-849b4fdcf4-mpfmj             1/1     Running     0          11d
retroelk-prod1-azure-pgbouncer-849b4fdcf4-z6hhh             1/1     Running     0          11d
retroelk-prod1-azure-tapu-67bc49c74b-v4n28                  2/2     Running     2          58d
alec@Alecs-MacBook-Pro ~/Developer/violetatrium/retroelk (MIN-7679) $ kk logs backrest-backup-retroelk-prod1-azure-4vh5d
time="2020-12-11T00:06:43Z" level=info msg="pgo-backrest starts"
time="2020-12-11T00:06:43Z" level=info msg="debug flag set to false"
time="2020-12-11T00:06:43Z" level=info msg="backrest backup command requested"
time="2020-12-11T00:06:43Z" level=info msg="backrest command will be executed for both local and s3 storage"
time="2020-12-11T00:06:43Z" level=info msg="command to execute is [pgbackrest backup --type=full --repo1-retention-full=7 --archive-timeout=120 --db-host=10.244.27.9 --db-path=/pgdata/retroelk-prod1-azure && pgbackrest backup --type=full --repo1-retention-full=7 --archive-timeout=120 --db-host=10.244.27.9 --db-path=/pgdata/retroelk-prod1-azure --repo1-type=s3]"
time="2020-12-11T00:06:43Z" level=info msg="command is pgbackrest backup --type=full --repo1-retention-full=7 --archive-timeout=120 --db-host=10.244.27.9 --db-path=/pgdata/retroelk-prod1-azure && pgbackrest backup --type=full --repo1-retention-full=7 --archive-timeout=120 --db-host=10.244.27.9 --db-path=/pgdata/retroelk-prod1-azure --repo1-type=s3 "
time="2020-12-11T00:22:17Z" level=error msg="command terminated with exit code 82"
time="2020-12-11T00:22:17Z" level=info msg="output=[]"
time="2020-12-11T00:22:17Z" level=info msg="stderr=[WARN: resumable backup 20201210-230215F of same type exists -- remove invalid files and resume\nERROR: [082]: WAL segment 00000010000016B200000028 was not archived before the 120000ms timeout\n       HINT: check the archive_command to ensure that all options are correct (especially --stanza).\n       HINT: check the PostgreSQL server log for errors.\n]"
time="2020-12-11T00:22:17Z" level=error msg="command terminated with exit code 82"
alec@Alecs-MacBook-Pro ~/Developer/violetatrium/retroelk (MIN-7679) $ kk logs backrest-backup-retroelk-prod1-azure-d6hx9
time="2020-12-11T00:22:19Z" level=info msg="pgo-backrest starts"
time="2020-12-11T00:22:19Z" level=info msg="debug flag set to false"
time="2020-12-11T00:22:19Z" level=info msg="backrest backup command requested"
time="2020-12-11T00:22:19Z" level=info msg="backrest command will be executed for both local and s3 storage"
time="2020-12-11T00:22:19Z" level=info msg="command to execute is [pgbackrest backup --type=full --repo1-retention-full=7 --archive-timeout=120 --db-host=10.244.27.9 --db-path=/pgdata/retroelk-prod1-azure && pgbackrest backup --type=full --repo1-retention-full=7 --archive-timeout=120 --db-host=10.244.27.9 --db-path=/pgdata/retroelk-prod1-azure --repo1-type=s3]"
time="2020-12-11T00:22:19Z" level=info msg="command is pgbackrest backup --type=full --repo1-retention-full=7 --archive-timeout=120 --db-host=10.244.27.9 --db-path=/pgdata/retroelk-prod1-azure && pgbackrest backup --type=full --repo1-retention-full=7 --archive-timeout=120 --db-host=10.244.27.9 --db-path=/pgdata/retroelk-prod1-azure --repo1-type=s3 "
time="2020-12-11T00:42:22Z" level=error msg="command terminated with exit code 82"
time="2020-12-11T00:42:22Z" level=info msg="output=[]"
time="2020-12-11T00:42:22Z" level=info msg="stderr=[WARN: resumable backup 20201210-230215F of same type exists -- remove invalid files and resume\nERROR: [082]: WAL segment 00000010000016B20000008F was not archived before the 120000ms timeout\n       HINT: check the archive_command to ensure that all options are correct (especially --stanza).\n       HINT: check the PostgreSQL server log for errors.\n]"
time="2020-12-11T00:42:22Z" level=error msg="command terminated with exit code 82"
```
This is a lot like the issue I hit before with glusterfs and standby reading from S3, but here I am trying to write from a db running on a non glusterfs disk to S3.  However, the backrest repo is on glusterfs!  How does sending archive files to S3 work?  Are they first saved on the backrest repo disk?  What happens if you do not do a local backup at all?  Do files still get staged on the backrest repo pod and local disk?

**Comment by alrooney** [comment]
Before when I encountered this with glusterfs I was able to see disk errors in the pg_log as the standby was reading WAL files.  But I'm not seeing any disk errors here just a timeout.  Which log or log level should I set or where would I look to see any disk errors with pgbackrest?

**Comment by alrooney** [comment]
Confirmed that this is NOT a glusterfs issues.  Changed to using a local-storage PVC and still getting same errors i.e. fails to archive random WAL files as above with a timeout.  Where do I look for additional info to help debug this situation?  Failing fixing this how can I reset the whole backup system to try to get back to a working install without taking down the cluster?

**Comment by alrooney** [comment]
Ok... I think I understand what is going on... the archiving is not happening at all from the primary to the backrest repo.  The reason for the different wals it keeps saying in the log is because every full backup is looking for a different wal set.  They are never present.  How do I debug and restart the archive process on the primary?

**Comment by alrooney** [comment]
Actually maybe the archiving process is actually supposed to be running on the backrest repo now that I think of it... So how do I restart the archiving process on the backrest repo?

**Comment by jkatz** [comment]
@alrooney I spoke with one of the pgBackRest developers to get a better understanding of the pgBackRest behavior in this case and what remediation steps would be.

After some discussion, the pgBackRest upstream is going to look into ways of better handling out-of-disk situations. If you are curious you can track that progress here:
[https://github.com/pgbackrest/pgbackrest/projects/2#card-51086064](https://github.com/pgbackrest/pgbackrest/projects/2#card-51086064).

For the immediate resolution, and this is going off of the fact that you have your backups and archives still going to your S3 bucket, the "safest" approach is to junk the current PVC for your pgBackRest Pod and start fresh. You would have to follow the process that the Operator typically follows, i.e.

1. Create a PVC
1. Ensure that PVC is mountable by the pgBackRest repository Deployment (and in turn Pod)
1. Run the create-stanza Job
1. Take an initial backup.

Another resolution would be to switch your pgBackRest configuration in your PostgreSQL environment to go to S3-only. Again, this would be a matter of following the same steps as to what the Operator does.

I will give the usual 🚨 🚨 bells for both of the above.

This does beget questions about how we can handle updates to pgBackRest environmental settings during the lifecycle of a PostgreSQL cluster ("Day 2" operations, if you will). There are some upstream changes we are waiting for in pgBackRest itself that we are waiting on before we begin to tackle improvements around that, so I would list those as us having a roadmap to have a roadmap around that.

As I did mention in #2118, this is not an issue with the PostgreSQL Operator itself, which is why I closed the ticket, as well as due to the fact there were already several tickets open around this matter. I am sorry that you ran into an out-of-disk issue, and I am of course happy to try to triage bugs, features, and documentation requests. I do kindly ask that you follow our various procedures listed on in our various [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) sections as those are available to provide help in operational situations.

**Comment by alrooney** [comment]
@jkatz thanks much for that info.  I guess I thought of the operator as including all of the processes that it packages but understand now that you think of this as a pgbackrest specific issue.  Re my issue I think I have figured out what is going on and have some helpful recommendations for anyone else hitting this issue:

1) The archives are actually pushed by the pg primary not pulled by the backrest as I mistakenly thought before (it really helps to have a global understanding of how everything works together so bear with me and other non dbas as we figure this out :-)).  I don't understand why I am not seeing anything in the pg log (is this a bug?) but figured out the archive process is failing by exec'ing into the primary and then listing the processes and grepping for archive as follows: 
```
bash-4.2$ ps aux | grep archive
postgres  4020  0.0  0.0 157804  5828 ?        Ss   Nov29   2:03 postgres: retroelk-prod1-azure: archiver   failed on 00000010000016A00000008B
postgres 29691  0.0  0.0  12548  2168 pts/13   S+   16:30   0:00 grep archive
``` 
2) Looking through the pg_wal directory on my pg 11 server I don't have that WAL file but I see a reference to it and a lot of other files that aren't in the pg_wal in the /pgdata/retroelk-prod1-azure/pg_wal/archive_status directory.  All these files end with .ready e.g.
```
0000000F.history.done		
00000010000016A00000008B.ready
00000010000016A00000008C.ready
00000010000016A00000008D.ready
etc...
```
So I am assuming that the pg wal archiver looks in this directory for wals that are ready to archive (again understanding how things work really helps).

3) So archiver on primary is failing because it can't find WALs that I deleted with pg_archivecleanup because my primary disk was filling up because the disk was full on my backrestrepo.  So now seeing how this chain reaction played out... backrest disk filled up.  Primary started filling up because archiver failed to write WALs to archive on backrestrepo.  I cleaned up WALs on the primary because it was also now running out of disk space using a tool specifically designed for that i.e. pg_archivecleanup but I guess pg_archivecleanup does not cleanup the archive_status files and so the archiver is now trying to archive files that are missing.  

4) So next I am planning to delete all the missing files in the /pgdata/retroelk-prod1-azure/pg_wal/archive_status.  I'll update here with if that works or causes the next disaster :-)

**Comment by alrooney** [comment]
That seems to have done the trick.  Here's a little script I ran in the pgdata/cluster/pg_wal directory to get things sorted and the archiving working again:
```
cd /pgdata/retroelk-prod1-azure/pg_wal
mkdir archive_status_new
for FILE in *; do cp "archive_status/$FILE.ready" archive_status_new/; done;
cp archive_status/*.done archive_status_new/
mv archive_status archive_status_backup && mv archive_status_new archive_status
```

**Comment by PhanSon95** [comment]
Hi @alrooney I'm facing with same problem, but has small different.
My cluster has 6 replicas and 1 primary. I've created cluster without --wal-storage so my `pgdata` grow up very fast with pg_data include 60% storage inside it.
So my pod was stuck at container database with error 
```
 FATAL: could not write lock file "postmaster.pid": No space left on device
```
I've exec into container and check storage size of pg_wal inside folder `/pgdata/my-cluster/pg_wal`:
```
00000002.history                          0000004D0000002A000000DA          000000530000002C000000C4  000000530000002E000000B9  0000005300000030000000AE
00000003.history                          0000004D0000002A000000DB          000000530000002C000000C5  000000530000002E000000BA  0000005300000030000000AF
00000004.history                          0000004D0000002A000000DC          000000530000002C000000C6  000000530000002E000000BB  0000005300000030000000B0
00000005.history                          0000004D0000002A000000DD          000000530000002C000000C7  000000530000002E000000BC  0000005300000030000000B1
00000006.history                          0000004D0000002A000000DE          000000530000002C000000C8  000000530000002E000000BD  0000005300000030000000B2
00000007.history                          0000004D0000002A000000DF          000000530000002C000000C9  000000530000002E000000BE  0000005300000030000000B3
00000008.history                          0000004D0000002A000000E0          000000530000002C000000CA  000000530000002E000000BF  0000005300000030000000B4
......
0000004D0000002A000000D6                  000000530000002C000000C0          000000530000002E000000B5  0000005300000030000000AA  00000053.history
0000004D0000002A000000D7                  000000530000002C000000C1          000000530000002E000000B6  0000005300000030000000AB  archive_status
0000004D0000002A000000D8                  000000530000002C000000C2          000000530000002E000000B7  0000005300000030000000AC
0000004D0000002A000000D9                  000000530000002C000000C3          000000530000002E000000B8  0000005300000030000000AD
```
Then I checked storage overview and result is:
```
bash-4.2$ du -h
148K    ./archive_status
38G     .
```
Question is: Can I clean the file at `pg_wal` folder which make pod can ready again ? 
Thanks you

**Comment by jkatz** [comment]
I would recommend reading [this](https://info.crunchydata.com/blog/postgresql-monitoring-for-app-developers-alerts-troubleshooting) for [out-of-disk troubleshooting strategies](https://info.crunchydata.com/blog/postgresql-monitoring-for-app-developers-alerts-troubleshooting).

**Comment by DinshKW44** [comment]
pgo version: 4.3.2
2021-02-25 19:15:10.899 UTC [31074] ERROR:  requested WAL segment 0000003D00000131000000BB has already been removed
2021-02-25 19:15:12.354 UTC [31075] ERROR:  requested WAL segment 0000003D00000131000000BB has already been removed

Copied 0000003D00000131000000BB from replica to the /pgdata/$cluster_name/pg_wal
pgbackrest-repo was full and pg_wal in the primary was full. Had to increase the storage storage and primary was up. But pg_wal still gets filled up as below. 

`-rw-------. 1 postgres postgres  16M Feb 25 22:11 0000011F000001B900000071
-rw-------. 1 postgres postgres  16M Feb 25 22:13 0000011F000001B900000072
drwxrws---. 4 postgres postgres 328K Feb 25 22:13 .
-rw-------. 1 postgres postgres  16M Feb 25 22:13 0000011F000001B900000073
drwxr-sr-x. 2 postgres postgres 440K Feb 25 22:13 archive_status
bash-4.2$ du -sh
114G	.
bash-4.2$ ls | wc -l
7556`

I am running into the similar issue. Any suggestions on how to resolve this?
