### ISSUE TITLE
Enable ssl and tls for postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2117]
Hi Team,
I want to enable ssl and tls in our postgres operator. How can i enable and add certs to it.
Is there any thing like certs manager in postgres operator? 

**Please tell us about your environment:**
Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
This is described in depth in the documentation:

[https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/tls/](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/tls/)
