### ISSUE TITLE
After disk full event in backrest repo archiving stops and cannot recover even with pod restart

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#2118]
Version pgo 4.5.0
See #2115 and #2111 for more details but creating this issue as I am now getting to the bottom of the underlying issue which seems to be that archiving has stopped and is no longer running even after a restart of the pgbackrest pod.  Normally I would expect an archiving lock in /tmp/pgbackrest/ but do not see it there.  How can debug what is preventing the archiving from working?

**Comment by jkatz** [comment]
This does not appear to be a bug, feature request, or documentation issue. Please use the [postgres-operator mailing list](https://github.com/CrunchyData/postgres-operator#support):

[https://github.com/CrunchyData/postgres-operator#support](https://github.com/CrunchyData/postgres-operator#support)

**Comment by alrooney** [comment]
huh?  I'm confused.  The backups aren't working how is this not an issue with the operator?

**Comment by alrooney** [comment]
@jkatz can you please explain why this is not a bug?  I am happy to collect logs to prove or disprove whether this is a bug in the operator or operation issue but seems premature to say this is just an operation issue?
