### ISSUE TITLE
pgBackrest does not connect to minio s3 storage

### ISSUE THREAD

**Issue by echel0n** [CrunchyData/postgres-operator#2120]
**Describe the bug**
time="2020-12-13T01:53:37Z" level=info msg="pgo-backrest starts"
time="2020-12-13T01:53:37Z" level=info msg="debug flag set to false"
time="2020-12-13T01:53:37Z" level=info msg="backrest stanza-create command requested"
time="2020-12-13T01:53:37Z" level=info msg="s3 flag enabled for backrest command"
time="2020-12-13T01:53:37Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.244.2.237 --db-path=/pgdata/gitlab --repo1-type=s3]"
time="2020-12-13T01:53:37Z" level=info msg="command is pgbackrest stanza-create  --db-host=10.244.2.237 --db-path=/pgdata/gitlab --repo1-type=s3 "
time="2020-12-13T01:55:39Z" level=error msg="command terminated with exit code 101"
time="2020-12-13T01:55:39Z" level=info msg="output=[]"
time="2020-12-13T01:55:39Z" level=info msg="stderr=[ERROR: [101]: TLS error [1:336031996] unknown protocol\n]"
time="2020-12-13T01:55:39Z" level=error msg="command terminated with exit code 101"

**To Reproduce**
  backrestS3Bucket: "pgo-backups"
  backrestS3Endpoint: "vault.cluster.san:9000"
  backrestS3Region: "us-east-1"
  backrestS3URIStyle: "path"

**Please tell us about your environment:**
Running Minio for backend S3 storage

* Operating System:
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): S3
* Container Image Tag: centos7-12.5-4.5.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.18.6

**Comment by echel0n** [comment]
Does the S3 storage backend require TLS be enabled or is there a way to disable pgbackrest from using TLS all together ?

**Comment by jkatz** [comment]
```
time="2020-12-13T01:55:39Z" level=info msg="stderr=[ERROR: [101]: TLS error [1:336031996] unknown protocol\n]"
time="2020-12-13T01:55:39Z" level=error msg="command terminated with exit code 101"
```

There seems to be TLS communication error with your MinIO Pod. On the Operator side, ensure you have the correct CA mounted. You can either set this globally in the `pgo-backrest-repo-config` Secret via the `aws-s3-ca.crt` key or using the `--pgbackrest-s3-ca-secret` flag as described in [`pgo create cluster`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/)

I cannot comment on your MinIO setup.

**Comment by jkatz** [comment]
With pgBackRest, at most you can disable TLS verification ([https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-verify-tls](https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-verify-tls)) but you cannot disable TLS.

**Comment by echel0n** [comment]
So I was able to disable the TLS verification as I found out that pgBackrest requires Minio to run with TLS, however now I get a different error.

```
time="2020-12-13T05:38:03Z" level=info msg="pgo-backrest starts"
time="2020-12-13T05:38:03Z" level=info msg="debug flag set to false"
time="2020-12-13T05:38:03Z" level=info msg="backrest stanza-create command requested"
time="2020-12-13T05:38:03Z" level=info msg="s3 flag enabled for backrest command"
time="2020-12-13T05:38:03Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.244.1.223 --db-path=/pgdata/gitlab --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2020-12-13T05:38:03Z" level=info msg="command is pgbackrest stanza-create  --db-host=10.244.1.223 --db-path=/pgdata/gitlab --repo1-type=s3 --no-repo1-s3-verify-tls "
time="2020-12-13T05:38:05Z" level=error msg="command terminated with exit code 39"
time="2020-12-13T05:38:05Z" level=info msg="output=[]"
time="2020-12-13T05:38:05Z" level=info msg="stderr=[ERROR: [039]: HTTP request failed with 403 (Forbidden):\n       *** URI/Query ***:\n       /pgo-backups/backrestrepo/gitlab-backrest-shared-repo/archive/db/archive.info\n       *** Request Headers ***:\n       authorization: <redacted>\n       content-length: 0\n       host: vault.cluster.san\n       x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n       x-amz-date: \n       *** Response Headers ***:\n       accept-ranges: bytes\n       content-length: 0\n       content-security-policy: block-all-mixed-content\n       date: Sun, 13 Dec 2020 05:38:05 GMT\n       server: MinIO/RELEASE.2020-05-16T01-33-21Z\n       vary: Origin\n       x-amz-bucket-region: us-east-1\n       x-amz-request-id: 16503009CC409F2B\n       x-xss-protection: 1; mode=block\n]"
time="2020-12-13T05:38:05Z" level=error msg="command terminated with exit code 39"
```

**Comment by echel0n** [comment]
OK, I'm going to close this out, was a late night and just now see that I didn't base64 encode the AWS secret but did the key, argh, sorry for the troubles.

Thanks!
