### ISSUE TITLE
 http status code is 403 for pgo client connecting to openshift cluster

### ISSUE THREAD

**Issue by ckvtvm-arch** [CrunchyData/postgres-operator#2121]
** Which example are you working with? **
Trying to connect to my org cluster which has the operator installed via pgo. I was able to connect to CRC cluster set up in my laptop, but i am not able to connect to the openshift cluster set up in my Org. 

I am using the certificates generated by pgo for both crc and openshift in my org.

**What is the current behavior?**
Error: Get https://127.0.0.1:8443/version: remote error: tls: bad certificate
**What is the expected behavior?**
Connection successful . 
**Other information** (e.g. detailed explanation, related issues,  etc)

Error: Get https://127.0.0.1:8443/version: remote error: tls: bad certificate

**Please tell us about your environment:**

* Operating System: Mac
* Where is this running ( Local , Cloud Provider) - Local
* Storage being used (NFS, Hostpath, Gluster, etc): None
* Container Image Tag: crunchy operator
* PostgreSQL Version: 4.5.0
* Platform (Docker, Kubernetes, OpenShift): openshift
* Platform Version: 4.6.3

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by ckvtvm-arch** [comment]
--disable-tls , but getting the Error: Get https://127.0.0.1:8443/version: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

**Comment by ckvtvm-arch** [comment]
Somehow fixed the tls certificate issue by generating certificates, but now i am getting the below:
DEBU[0001] &{403 Forbidden 403 HTTP/1.1 1 1 map[Content-Length:[39] Content-Type:[text/plain; charset=utf-8] Date:[Mon, 14 Dec 2020 03:30:46 GMT] X-Content-Type-Options:[nosniff]] 0xc0001a20a0 39 [] false false map[] 0xc00027e600 0xc0000dec60} 
DEBU[0001] http status code is 403                      
Error: Invalid Status Code: 403

**Comment by ckvtvm-arch** [comment]
I think the pgo credentials (pgouser) may not be authenticated by openshift cluster. how do we connect to openshift cluster using my HA account . i can trying changing the pgouser to have the openshift cluster credentials or do we need something like postgres-operator-playbooks

**Comment by ckvtvm-arch** [comment]
I will talk to my admin to create a secret as per pgouser-admin.yaml.j2

**Comment by jkatz** [comment]
Do you have logs from the `apiserver` container that resides within the `postgres-operator` Pod?

**Comment by ckvtvm-arch** [comment]
2020/12/14 03:18:41 http: TLS handshake error from 127.0.0.1:60566: tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "serial:643920442033123828")

**Comment by ckvtvm-arch** [comment]
But i am not getting the bad tls certificate error anymore and right now i am getting 403 error which means that the credentials are not valid ?, am i right ?

**Comment by ckvtvm-arch** [comment]
It looks like an issue with client key and server key : 

4452499052:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.140.1/libressl-2.8/crypto/pem/pem_lib.c:684:Expecting: TRUSTED CERTIFICATE

**Comment by jkatz** [comment]
The certificates being used do not sound like they were generated by the Operator installation method, or that the certificates have not been loaded in properly by the client.

If you use one of the standard Postgres Operator installation methods, it will generate a self-signed TLS keypair for the server. This in turn is made available for the client using the `client-install.sh` that is referenced in the documentation:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/)

The Postgres Operator also presents options to disable TLS verification as well as TLS itself for interfacing with the API server:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/)

**Comment by ckvtvm-arch** [comment]
I have used the operator installation generated certificates for CRC cluster, but it doesn't works for my Org cluster. Hence i generated my own certificates using openssl . right now i am investigating on openssl and mac machine @ https://stackoverflow.com/questions/34612991/openssl-key-generation-on-os-x-failing

**Comment by ckvtvm-arch** [comment]
Also i will request my admin to see if he can re-install the operator with tls disabled

**Comment by ckvtvm-arch** [comment]
I am running into an issue again , can you please help

DEBU[0000] https://postgres-operator-co-postgres-crunchydata-dev.apps.ent-ocp4-np1-har.antmdc.internal.das/version 
DEBU[0000] &{403 Forbidden 403 HTTP/1.1 1 1 map[Content-Length:[39] Content-Type:[text/plain; charset=utf-8] Date:[Wed, 20 Jan 2021 02:43:11 GMT] X-Content-Type-Options:[nosniff]] 0xc00068c0e0 39 [] false false map[] 0xc00050c300 0xc0001382c0} 
DEBU[0000] http status code is 403                      
Error: Invalid Status Code: 403
