### ISSUE TITLE
ssl/tls - how can we renewal the certs 

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2122]
How can we check the self expiry dates of signed certificates.
how will they get renewed, who will renew the certificates if expired
Is there any documentation where we can refer 

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
This doesn't have to do with the Postgres Operator. I suggest reading literature on certificate management.
