### ISSUE TITLE
PG crunch operator 4.5.0 ( docker image ) - PG10 support

### ISSUE THREAD

**Issue by aherkarsatish11** [CrunchyData/postgres-operator#2123]
I'm trying to find the pg10 image in the latest crunchy operator release i.e. 4.5.0 & 4.5.1 but seems like that is still not available 
Can someone please help me when can we expect pg10 release ( https://hub.docker.com/r/crunchydata/crunchy-postgres-ha/tags?page=1&ordering=last_updated&name=4.5.0 ) or we completed stopped support pg10 with latest operator version ?

I'm having issue with pgbackrest older version i.e. 2.20 due to which backup are failing and looking to upgrade pgbackrest to 2.30 & should be available in pg10 image

* Operating System:
* Where is this running ( Local , Cloud Provider): AWS
* Storage being used (NFS, Hostpath, Gluster, etc): S3, EBS
* Container Image Tag: centos7-10.11-4.2.1
* PostgreSQL Version: 10.11
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 3.11

**Comment by jkatz** [comment]
Please see #2110 for an explanation.

I will note that the 4.5.x series has pgBackRest 2.29, not 2.30.
