### ISSUE TITLE
Error received when installing the postgres operator version 4.3.4

### ISSUE THREAD

**Issue by devopsevd** [CrunchyData/postgres-operator#2125]
Reference:
https://github.com/CrunchyData/postgres-operator/tree/REL_4_3#installation

When trying to setup postgres operator version 4.3.4
Encountered the following error from the logs of the postgres-operator

time="2020-12-14T21:58:28Z" level=error msg="pgclusters.crunchydata.com is forbidden: User \"system:serviceaccount:postgres-operator-crunchy1-v430:postgres-operator\" cannot list resource \"pgclusters\" in API group \"crunchydata.com\" in the namespace \"postgres-operator-crunchy1-v430\"" func="operator/operatorupgrade.checkVersion()" file="operator/operatorupgrade/version-check.go:55" version=4.3.4

Attached JSON format of the logs from GKE UI.

This worked about 2 weeks ago on the same GKE cluster and it donesn't work now. I see the error message and think this has something to do with RBAC, but could not zero in on the root cause. Can you please review and advise.

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider) : GKE
* Storage being used (NFS, Hostpath, Gluster, etc): GCP PVC
* Container Image Tag: pgo-deployer:centos7-4.3.4
* PostgreSQL Version: centos7-4.3.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.1.7.x

[downloaded-logs-20201214-170531.txt](https://github.com/CrunchyData/postgres-operator/files/5691866/downloaded-logs-20201214-170531.txt)

**Comment by jkatz** [comment]
- How did you install the Operator?
- Do you have logs from the installation method you used?

**Comment by devopsevd** [comment]
I followed installation instructions from the following url https://github.com/CrunchyData/postgres-operator/tree/REL_4_3#installation

Attaching the installation log.
[installation_log.txt](https://github.com/CrunchyData/postgres-operator/files/5698952/installation_log.txt)

[postgres-operator.txt](https://github.com/CrunchyData/postgres-operator/files/5698954/postgres-operator.txt)

**Comment by jkatz** [comment]
The installer logs are in your `pgo-deploy-tsr4r ` container. Can you please send those over?

**Comment by devopsevd** [comment]
Thank you.
logs from the pgo-deploy-tsr4r container.
[deployer.txt](https://github.com/CrunchyData/postgres-operator/files/5699068/deployer.txt)

**Comment by jkatz** [comment]
```
TASK [pgo-operator : Create Watched Namespaces] ********************************
skipping: [localhost] => (item=postgres-operator-crunchy2-v430) 

TASK [pgo-operator : Create Watched Namespaces (Dynamic RBAC)] *****************
skipping: [localhost] => (item=postgres-operator-crunchy2-v430) 

TASK [pgo-operator : Label Watched Namespaces (Dynamic RBAC)] ******************
skipping: [localhost] => (item=postgres-operator-crunchy2-v430) 

TASK [pgo-operator : Template Local Namespace RBAC (Dynamic RBAC)] *************
skipping: [localhost]

TASK [pgo-operator : Cleanup Local Namespace RBAC (Dynamic RBAC)] **************
skipping: [localhost] => (item=postgres-operator-crunchy2-v430) 

TASK [pgo-operator : Create Local Namespace RBAC (Dynamic RBAC)] ***************
skipping: [localhost] => (item=postgres-operator-crunchy2-v430) 
```

It appears that the RBAC creation was skipped for your watched namespaces. The default installation file does not enabled the `DYNAMIC_RBAC` feature, though it does enable `CREATE_RBAC` so I'm not sure if you are working with a modified installation or not.

Regardless, you will need to ensure that the RBAC required by the Operator is set up in those namespaces. You could try to do this by enabling the "DYNAMIC_RBAC" in the configuration. You can read more about this in the [namespace management](https://access.crunchydata.com/documentation/postgres-operator/4.3.4/architecture/namespace/) section of the documentation.

Lastly, if this is an upgrade, I suggest reading the section on [upgrading](https://access.crunchydata.com/documentation/postgres-operator/4.3.4/upgrade/).

**Comment by devopsevd** [comment]
Thank you.
