### ISSUE TITLE
How to enable crunchy-postgres-exporter using CRD

### ISSUE THREAD

**Issue by echel0n** [CrunchyData/postgres-operator#2126]
I've trying to enable metrics using CRDs but am not seeing where I specify the secret that contains the user/pass for the ccp_monitoring db user to pass through on the CRD PGCluster, any advise/help would be greatly appreciated.

Thanks!

**Comment by jkatz** [comment]
This will be simplified in 4.6.0 via #2124. I would recommend either waiting for that release (targeted January) or using the existing workflow detailed in the [monitoring documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/)
