### ISSUE TITLE
The postgres database operator has crashed 8 hours ago and did not restart since.

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2127]
In our environment (deployed on GCP) is down.
The postgres database operator has crashed 8 hours ago and did not restart since.

Only the following postgres-related PODs are running - the operator is in CrashLoopBackOff while the DB engine POD is not even started:
pgo-client-5b5ccd798b-4s2bt                                       1/1     Running            0          8h
postgres-management-backrest-shared-repo-5594d4d847-s7fq9         1/1     Running            0          8h
postgres-operator-7df5d8448d-zqs7z                                3/4     CrashLoopBackOff   102        8h0m
postgres-user-settings-backrest-shared-repo-765c786569-drdl7      1/1     Running            0          8h

The operator POD logs show:
...
time="2020-12-15T12:31:01Z" level=debug msg="Cluster Config: finished syncing DCS config for cluster postgres-user-settings (namespace sedsac-ea-infra)" func="operator/config.(*DCS).Sync()" file="operator/config/dcs.go:129" version=4.3.0
time="2020-12-15T12:31:01Z" level=debug msg="Cluster Config: DCS config for cluster postgres-management in namespace sedsac-ea-infra is up-to-date, nothing to apply" func="operator/config.(*DCS).apply()" file="operator/config/dcs.go:186" version=4.3.0
time="2020-12-15T12:31:01Z" level=debug msg="Cluster Config: finished syncing DCS config for cluster postgres-management (namespace sedsac-ea-infra)" func="operator/config.(*DCS).Sync()" file="operator/config/dcs.go:129" version=4.3.0
panic: runtime error: index out of range [0] with length 0

goroutine 206 [running]:
github.com/crunchydata/postgres-operator/operator/config.(*LocalDB).apply(0xc0014a2200, 0xc0014b6150, 0x25, 0x1, 0x0)
	/opt/cdev/src/github.com/crunchydata/postgres-operator/operator/config/localdb.go:241 +0x991
github.com/crunchydata/postgres-operator/operator/config.(*LocalDB).Sync.func2(0xc0014a2200, 0xc0014a4510, 0xc0014b6150, 0x25)
	/opt/cdev/src/github.com/crunchydata/postgres-operator/operator/config/localdb.go:166 +0x46
created by github.com/crunchydata/postgres-operator/operator/config.(*LocalDB).Sync
	/opt/cdev/src/github.com/crunchydata/postgres-operator/operator/config/localdb.go:163 +0x2a3

**Detailed logs :**
[downloaded-logs-20201215-215900.txt](https://github.com/CrunchyData/postgres-operator/files/5697190/downloaded-logs-20201215-215900.txt)

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
This has already been fixed in a later version.
