### ISSUE TITLE
How can we apply values for resources cpu and memory request and limits to the postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2131]
On how we can apply  values of resource cpu and memory requests and limits to the postgres-operator ( currently we are manually editing the postgres-operator deployment using the command kubectl edit deployment <dep_name> )

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
This is covered [extensively in the documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/customize-cluster/#customize-cpu-memory), but to benefit from this you will need to update to a supported version of the latest in the 4.3.x series.

**Comment by kseswar** [comment]
Hi, Thank you for sharing the link.
I have already reviewed this document. My question is specific to the operator pod itself.
The documentation only talks about the cluster it does not specify the operator pod
