### ISSUE TITLE
About pgo upgrade --no-prompt flag, any work around ?

### ISSUE THREAD

**Issue by devopsevd** [CrunchyData/postgres-operator#2135]
** Which example are you working with? **
Trying to upgrade cluster from current version operator 4.3.0 / postgres 12.2 to operator 4.5.1 / postgres 12.5
using the documentation 
https://access.crunchydata.com/documentation/postgres-operator/4.5.1/upgrade/automatedupgrade/
https://access.crunchydata.com/documentation/postgres-operator/4.5.1/pgo-client/reference/pgo_upgrade/
pgo upgrade mycluster
Upgrades the cluster for use with the upgraded Postgres Operator version.

**Other information** (e.g. detailed explanation, related issues,  etc)
I see that pgo upgrade does not have the --no-prompt flag , our requirement is to automate the upgrade process and we are able handle the operator upgrade from 4.3.0 to 4.5.1 via script.
However could not make any headway on the pgo upgrade on all our deployments (20+ currently) using a script. 
Can you share any work around ? 

Please tell us about your environment:

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.5.1 
PostgreSQL Version:12.5
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
The "workaround" would be to query the API directly.

That said, it seems prudent to add a `--no-prompt` flag to the command.

**Comment by jkatz** [comment]
Looking at the code, it appears the facilities were added to support `--no-prompt` except the actual exposing of the flag. As such, I can actually classify this as a bug (though in the release notes I'll list it as a change) and backpatch it.

**Comment by devopsevd** [comment]
Thank you.
