### ISSUE TITLE
pgo upgrade command, pods don't come backup

### ISSUE THREAD

**Issue by devopsevd** [CrunchyData/postgres-operator#2145]
** Which example are you working with? **
Trying to upgrade cluster from current version operator 4.3.0 / postgres 12.2 to operator 4.5.1 / postgres 12.5
using the documentation
https://access.crunchydata.com/documentation/postgres-operator/4.5.1/upgrade/automatedupgrade/
https://access.crunchydata.com/documentation/postgres-operator/4.5.1/pgo-client/reference/pgo_upgrade/
pgo upgrade mycluster
Upgrades the cluster for use with the upgraded Postgres Operator version.

Other information (e.g. detailed explanation, related issues, etc)
When run the command pgo upgrade cluster hippo
I see the following error

-----

time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts \"postgres-operator\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"serviceaccounts\" in API group \"\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileRBAC()" file="internal/controller/manager/rbac.go:49" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts \"pgo-default\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"serviceaccounts\" in API group \"\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:134" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts \"pgo-target\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"serviceaccounts\" in API group \"\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:134" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts \"pgo-backrest\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"serviceaccounts\" in API group \"\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:134" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts \"pgo-pg\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"serviceaccounts\" in API group \"\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:134" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-target-role\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"roles\" in API group \"rbac.authorization.k8s.io\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-backrest-role\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"roles\" in API group \"rbac.authorization.k8s.io\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-pg-role\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"roles\" in API group \"rbac.authorization.k8s.io\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: rolebindings.rbac.authorization.k8s.io \"pgo-pg-role-binding\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"rolebindings\" in API group \"rbac.authorization.k8s.io\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:113" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: rolebindings.rbac.authorization.k8s.io \"pgo-target-role-binding\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"rolebindings\" in API group \"rbac.authorization.k8s.io\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:113" version=4.5.1
time="2020-12-21T23:05:59Z" level=error msg="operator is unable to reconcile RBAC resource: rolebindings.rbac.authorization.k8s.io \"pgo-backrest-role-binding\" is forbidden: User \"system:serviceaccount:postgres-test-upgrade-gdu1-11:postgres-operator\" cannot get resource \"rolebindings\" in API group \"rbac.authorization.k8s.io\" in the namespace \"postgres-test-upgrade-gdu1-11\"" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:113" version=4.5.1

-----

Attached full log from operator container.

The version 4.3.0 operator and the cluster were sucessfully installed and running before I started the upgrade.
The operator upgrade proceeded as planned. Once the version 4.5.1 operator was installed, I exec'd into the pgo-client pod to run the pgo upgrade command.
The cluster was scaled down. It did not come backup.
I see that the PVC are still intact, the secrets, configmaps still intact.
The Pods did not come up, when I checked the logs from the postgre-operator pod (operator container) I find the above error messages.

Can you please review and share your inputs?

Please tell us about your environment:

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.5.1
PostgreSQL Version:12.5
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5
[downloaded-logs-20201221-180717.txt](https://github.com/CrunchyData/postgres-operator/files/5726940/downloaded-logs-20201221-180717.txt)

**Comment by jkatz** [comment]
This is an RBAC issue. Ensure you have properly set up the RBAC and provided the correct permissions for the Operator Pod to run.  In the [upgrade documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/automatedupgrade/) there is a specific step that describes updating the RBAC: [https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/automatedupgrade/#upgrading-the-operator](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/automatedupgrade/#upgrading-the-operator).
