### ISSUE TITLE
How to get or create image with specific postgis and pg version?

### ISSUE THREAD

**Issue by Roarain** [CrunchyData/postgres-operator#2150]
According to 
- https://www.crunchydata.com/developers/download-postgres/containers/postgis
- https://github.com/CrunchyData/postgres-operator/blob/master/installers/olm/Makefile#L17
- https://github.com/CrunchyData/postgres-operator/blob/master/internal/util/util_test.go#L35

But cannot find postgresql 10.15 , postgis 2.4 or postgis 3.0 .
like 
- registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos7-10.15-2.4-4.5.1
- registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos7-10.15-3.0-4.5.1

How to get or create image ?

cannot find postgresql10 on dockerhub 
- https://hub.docker.com/r/crunchydata/crunchy-postgres-gis-ha/tags?page=1&ordering=last_updated&name=4.5.1

**Comment by jkatz** [comment]
Each PostgreSQL version supports two versions of PostGIS:

13: (3.1 when it's available), 3.0
12: 3.0, 2.5
11: 2.5, 2.4
10: 2.4, 2.3
9.6: 2.3, 2.2

#1956 is the impetus to get this better documented, which will happen before the 4.6 release.

More information about releases: [https://github.com/CrunchyData/postgres-operator#releases](https://github.com/CrunchyData/postgres-operator#releases)

#2110 has an explanation around older versions of PostgreSQL.
