### ISSUE TITLE
Cannot create cluster after upgrade to 4.5.1 - pgo-backrest-repo-config secret not found

### ISSUE THREAD

**Issue by jatalocks** [CrunchyData/postgres-operator#2159]
**Describe the bug**
Whenever I try to create a cluster using either oc/kubectl or the pgo client, nothing is being created and I get the following error in the operator pod:

`level=error msg="secrets \"pgo-backrest-repo-config\" not found" func="internal/util.CreateBackrestRepoSecrets()" file="internal/util/cluster.go:156" version=4.5.1`

`level=error msg="secrets \"pgo-backrest-repo-config\" not found" func="internal/operator/cluster.AddClusterBase()" file="internal/operator/cluster/cluster.go:93" version=4.5.1`

If I try to create the "pgo-backrest-repo-config" myself using the examples with the fields: "authorized_keys,id_ed25519,ssh_host_ed25519_key,config,sshd_config",
I get the following errors after trying to create a cluster:

`level=error msg="template: pgo-backrest-repo-template.json:51:32: executing \"pgo-backrest-repo-template.json\" at <.CCPImagePrefix>: can't evaluate field CCPImagePrefix in type *backrest.RepoDeploymentTemplateFields" func="internal/operator/backrest.CreateRepoDeployment()" file="internal/operator/backrest/repo.go:131"  version=4.5.1`

`level=error msg="template: pgo-backrest-repo-template.json:51:32: executing \"pgo-backrest-repo-template.json\" at <.CCPImagePrefix>: can't evaluate field CCPImagePrefix in type *backrest.RepoDeploymentTemplateFields" func="internal/operator/cluster.AddClusterBase()" file="internal/operator/cluster/cluster.go:105"  version=4.5.1`

**To Reproduce**
1. Install the 4.5.1 version of the operator
2. Try to create a cluster using the pgo client

**Expected behavior**
pgo-backrest-config-repo secret is being created with appropriate fields and a cluster is being created

**Please tell us about your environment:**

* Where is this running ( Local, Cloud Provider): Openshift 4.3
* Storage being used (NFS, Hostpath, Gluster, etc): Vsphere-volume
* Container Image Tag: 4.5.1
* Platform (Docker, Kubernetes, OpenShift): Openshift 
* Platform Version: 4.3

**Additional context**
I've previously been running operator 4.3 without problem and pgbackrest was being created. I upgraded to 4.5.1 to install metrics after pgmonitor was added. Now my metrics work but not cluster is being created.

**Comment by jkatz** [comment]
How did you perform the upgrade?

**Comment by jatalocks** [comment]
I removed the entire operator namespace and it's resources, including CRDs and Roles, uploaded the new images to my private repository on premise and deployed the operator again with image pull policy always

**Comment by jkatz** [comment]
I'm not quite sure what is going on, but it sounds like there are some vestigial remnants that are lying around, whether they are Kubernetes objects or an older container.

In the future, I would recommend following the [upgrade guide](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/) in the documentation, which has automated a lot of this process and helps to keep more things intact.

**Comment by jatalocks** [comment]
I looked over the automated update procedure and did accordingly using the deploy action of pgo-deploy container by letting it create the resources for me instead lf the install action. Still, same problem persists. I don't know what I'm missing

**Comment by jkatz** [comment]
There is something wrong in your `pgo-backrest-repo-template.json` entry in your `pgo-config` ConfigMap. The field `{{.CCPImagePrefix}}` does not exist. In fact, this does not appear to exist on either 4.5.1 or the latest REL_4_3 commits:

- [4.5.1](https://github.com/CrunchyData/postgres-operator/blob/v4.5.1/installers/ansible/roles/pgo-operator/files/pgo-configs/pgo-backrest-repo-template.json)
- [REL_4_3](https://github.com/CrunchyData/postgres-operator/blob/REL_4_3/installers/ansible/roles/pgo-operator/files/pgo-configs/pgo-backrest-repo-template.json)

I am not sure if you customized your ConfigMap templates at all. There are a few ways to go about fixing it:

- Edit the entry in the `pgo-config` ConfigMap and modify the erroneous line. My recommendation is making sure it matches the format presented in [4.5.1](https://github.com/CrunchyData/postgres-operator/blob/v4.5.1/installers/ansible/roles/pgo-operator/files/pgo-configs/pgo-backrest-repo-template.json)
- Regenerate the `pgo-config` ConfigMap. You can delete it from your Operator namespaces and, as one of the nice things of [4.5.1](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.1), the Operator will automatically regenerate it. The steps to do this:

- Scale down the Operator so there are no running Pods
- Delete the `pgo-config` ConfigMap
- Scale up the Operator

Verify that the file matches the expected one above.

If you are still getting errors after that, my suspicion is that one of your images is not the 4.5.1 image. What are the tags on the images and which registry did you download them from?

**Comment by jatalocks** [comment]
You might be correct about an error from my part, I did move all the images with the centos7-13.1-4.5.1 and centos7-4.5.1 from the crunchydata project on dockerhub and then tagged them myself after they were "none" (docker default export method does not keep tag). If that is the case that I tagged them incorrectly I still presume there would be some kind of intern container error but each container had the files it needs. On the pgo-deploy 4.3.0, which is this last one I had before upgrading, the field of {{.PGOImagePrefix}} and not {{.CCPImagePrefix}} existed on the pgo-backrest-repo-template.json entry in my pgo-config (like the commits show). So, I have no idea where the CCPImagePrefix field came from because I did not change it myself.
I tried the method of fixing it manually but other issues arose in other parts of the pgo-conf, for example in the cluster deployment template where /opt/crunchy folder didn't exist so it couldn't run the readiness script, so it was too much fixing them all instead of the root cause.

As of now I downgraded for 4.3.0 for the operator and use the 4.5.1 deployer for the metrics. I will update when I carefully redo to process of download the images and upgrading.

**Comment by jkatz** [comment]
Without inspecting your system, I can't comment too much further on what happened or why certain errors are or are not manifesting.

I will note that you should at least consider updating to [4.3.4](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.4) as there were plenty of bug fixes between [4.3.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.0) and then which I would recommend taking for a much better experience:

- [https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.1](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.1)
- [https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.2](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.2)
- [https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.3](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.3)
- [https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.4](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.4)

(Normally patch releases are easy updates as they are typically just container swaps -- there were some CRD changes in 4.3.2 [a one-time exception to the rule] which may make that trickier so please review the upgrade docs).

I will also note that, given PostgreSQL 13 was not available for 4.3.0, migrating to PostgreSQL 13 will require going through a ["major upgrade"](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/) which you can perform with the [crunchy-upgrade](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/) container (ignore that the docs only specify up to PostgreSQL 11).

Glad you were able to get the monitoring functionality working.  I am certainly a fan of it.
