### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by gurjeet** [CrunchyData/postgres-operator#216]
The news release linked below mentions that there's a version 3 of the Postgres-operator. Which branch/tag is that release is under?

The latest release I see is of version 2.6. https://github.com/CrunchyData/postgres-operator/releases

https://www.prnewswire.com/news-releases/crunchy-data-announces-the-release-of-the-crunchy-postgresql-operator-3-0-with-focus-on-automated-database-management-with-kubernetes-300643516.html

**Comment by jmccormick2001** [comment]
should be good now that 3.0 is released, tag 3.0 created.
