### ISSUE TITLE
Add filters to show backup command

### ISSUE THREAD

**Issue by daanemanz** [CrunchyData/postgres-operator#2160]
**What is the motivation or use case for the change?**
When auditing backups for a given cluster / namespace, it would be useful to be able to specify how far back in time you'd like to go to see backups and whether they failed or succeeded.

**Describe the solution you'd like**
Using the `pgo show backup` command, I would like to see a flag `--backups-from` with a timestamp argument that specifies from which time I'd like to see backup information. Another flag `--backups-to` would also be useful.

**Comment by benjaminjb** [comment]
Hello @daanemanz, is this still an ongoing concern? Are you still using PGO v4?

**Comment by daanemanz** [comment]
Hey @benjaminjb - this issue can be closed. We are no longer using Crunchy Data. Thanks!
