### ISSUE TITLE
Restore from different cluster

### ISSUE THREAD

**Issue by lgarcia11** [CrunchyData/postgres-operator#2161]
**What is the motivation or use case for the feature?**
 Create a scheduled task that will clone a production cluster into a staging cluster.

**Describe the solution you'd like**
pgo restore staging-cluster --restore-from=production-cluster

**Comment by jkatz** [comment]
How is this different than [`pgo create cluster --restore-from`](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#restore-to-a-new-cluster)?

**Comment by lgarcia11** [comment]
The difference will be if the cluster exist, 
`pgo create cluster --restore-from` will say **Error: pgcluster cluster was found so we will not create it**
`pgo restore cluster --restore-from` will work destroying the current cluster and then restoring it.

**Comment by jkatz** [comment]
I'm not following. `pgo create cluster --restore-from` will perform a restore from a different cluster. It will copy the data from one cluster (active or inactive) and establish a new cluster, similar to a clone.

**Comment by jkatz** [comment]
Not hearing anything else back, I am going to close this out. As I understand it, we already support this functionality, but if I am mistaken please do clarify. Thanks!
