### ISSUE TITLE
pgbackrest storage class configuration problem

### ISSUE THREAD

**Issue by sorinpepelea** [CrunchyData/postgres-operator#2164]
In microk8s there is a problem with default storageclass microk8s-hostpath related to user privilege for paths hosted under different nodes. 
I have managed to use rook-ceph-block storage (with --storage-config=...), but there is no option for pgbackrest storageclass , hence defaults to microk8s-hostpath.  
Is there any way to configure pgo client for using same rook storage class for pgbackrest  also ?

**Comment by jkatz** [comment]
The pgBackRest storage class can be set up in a few ways.

First, you need to ensure that you have your [storage configuration set up](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/#storage-configuration-options) as described in the installation docs.

From there, there are three options to choose:

1. During installation set the [`backrest_storage`](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/) parameter to be the storage configuration you wish to use.
2. During runtime, modify the `pgo.yaml` entry in the `pgo-config` ConfigMap and set the `BackrestStorage` entry to be the storage configuration you wish to use. You will have to restart the `postgres-operator` Pod for that change to take effect.
3. When creating a cluster, use the [`--pgbackrest-storage-config` flag](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) that is specified as part of the [`pgo create cluster`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) command.

The first two options will ensure that the pgBackRest storage configuration is defaulted every time you create the cluster. The third option allows you to specify the storage configuration on a one-off basis.
