### ISSUE TITLE
Disable-fsgroup parameter

### ISSUE THREAD

**Issue by sorinpepelea** [CrunchyData/postgres-operator#2171]
What is the option for disabling FSGROUP at cluster creation ? i tried like everything  : 
--disable-fsgroup 
and variation - with/without "-" or caps, etc
Nothing seems to work
Postgres-operator version is 4.5.1

**Comment by jkatz** [comment]
As [described previously](https://github.com/CrunchyData/postgres-operator/issues/2162#issuecomment-752998802) `disable_fsgroup` is an installation time parameter.

**Comment by sorinpepelea** [comment]
My problem is that i am unable to create path '/backrestrepo/grid-backrest-shared-repo': [13] Permission denied
in "stanza-create" pod

**Comment by sorinpepelea** [comment]
All other pods seem to run ok . So i tried everithing, changing FSGroup in configs, change runAsUser..nothing seems to work...pgbouncer, cluster and backrest pods runs ok. But stanza keeps complaining about insuficient rights
