### ISSUE TITLE
v4.6.0-beta.1 is not working

### ISSUE THREAD

**Issue by kesavkolla** [CrunchyData/postgres-operator#2174]
**Describe the bug**
When I try to provision postgres-operator/v4.6.0-beta.1 the deployment is not succeded. I got an error saying image **registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos8-4.6.0-beta.1** is not available.

**To Reproduce**
```shell
kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.6.0-beta.1/installers/kubectl/postgres-operator.yml
```

**Expected behavior**
The pgo operator should be deployed

**Please tell us about your environment:**

* Operating System: Ubuntu 20.10
* Where is this running Local
* Storage being used (NFS, Hostpath, Gluster, etc): hostpath
* Container Image Tag: pgo-deployer:centos8-4.6.0-beta.1
* PostgreSQL Version: 13.1
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.20.1

**Comment by jkatz** [comment]
This has not been pushed to any repositories yet. When it is, we will make an announcement to the [developer portal announcement list](https://www.crunchydata.com/developers/newsletter).

The documentation still references v4.5.1 as the latest version.

Thanks for your interest in testing!

**Comment by kesavkolla** [comment]
I saw the bug fixes and version bumps for Patroni and thought I can test this out. Any timeline for this release to be available for general public?

**Comment by jkatz** [comment]
You can read about how the container images are released here:

- [https://github.com/CrunchyData/postgres-operator#releases](https://github.com/CrunchyData/postgres-operator#releases)

As [mentioned above](https://github.com/CrunchyData/postgres-operator/issues/2174#issuecomment-754879756), we will announce public image availability on the developer portal announcement list when they are pushed.

In all likelihood the beta images will be available tomorrow (as of this writing), but it depends on how the build/scan/smoke test process goes.

**Comment by jkatz** [comment]
4.6 is now GA. You can find more information about the release here: [https://github.com/CrunchyData/postgres-operator/releases/tag/v4.6.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.6.0)
