### ISSUE TITLE
How to use pgbackrest version 2.31

### ISSUE THREAD

**Issue by kesavkolla** [CrunchyData/postgres-operator#2176]
I've installed pgo operator with version 4.5.1. The pgbackrest that came along with the cluster is 2.29

Is there any way to update the pgbackrest version? I'm using s3[minio] as repository to store backups. The version 2.29 doesn't apply correct retention rules in this version. I want to upgrade to latest version and test if the retention settings are applied correctly.

**Comment by jkatz** [comment]
> The version 2.29 doesn't apply correct retention rules in this version.

Can you describe the exact issue? Do you have any logs or information to show that the retention settings are incorrect?

**Comment by kesavkolla** [comment]
I think I understood the issue. When I run pgo backup it's by default creating **incr** type backups. They don't follow the retention settings. If I create either **full** or **diff** backups they're following the retention settings.

I need to see how to pass backup-type=diff to pgo backup command.

**Comment by kesavkolla** [comment]
Yes I figured out how to use pgo backup command.

**Comment by jkatz** [comment]
Great!
