### ISSUE TITLE
How to efficiently lifecycle pgo version with many namespace and clusters?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2177]
We are trying to define an efficient life-cycle model of our postgresql environment in order to follow the _postgres-operator_ releases rhythms.

We currently have pgo version 4.5.1 installed within a dedicated namespace and it manages many namespaces (>50), each containing several pg-clusters..... And we have more coming....
We also extended the pgo-osb to provide a self-service portal to our internal projects (through cloud-foundry).

When we want to upgrade the version of the pgo, we have to do the following:

1. Upgrade the pgo version
2. Upgrade the pgo-osb
3. for each pg-cluster: upgrade it using `pgo upgrade` cmd (for instance)

With this, we have the following challenges:
- Once the pgo version is upgraded, we have to run the part 3 in a very short time since once the pgo is upgraded, it is not able to manage anymore the clusters that have not been upgraded yet. 
- This also means that if a customer requests any action through the pgo-osb for a cluster that has not yet been upgraded, this will be rejected (since the cluster must be upgraded first).

To mitigate the issue, we had the following idea in mind:

- When a new version of the operator is released, install, on the same k8s cluster, the newest version of the Operator (meaning we have both the old and the version available
- Also install in parallel the new version of the pgo-osb
- "Somehow", migrate namespaces one-by-one by changing the _managing Operator_.

However, according to the pgo documentation, I cannot (anymore?) find any section saying that we can run several operators within the same k8s cluster (same/different operator version).

Assuming this is possible, will it be possible to then move the control of one namespace from operator1 to operator2?

Do you have any thought on your side to efficiently life-cycle pgo/clusters in environment with many-many namespaces and pg-clusters?  

Thanks for any hints
José

**Comment by jose-joye** [comment]
Hello, 

Any hints about this question :-)

Regards,
José

**Comment by jkatz** [comment]
If you're looking for something that's more immediately responded to, I'd suggest taking a peek at [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), otherwise someone may provide thoughts about it in the fullness of time. Thanks!

**Comment by AleksanderRoszig** [comment]
@jose-joye "However, according to the pgo documentation, I cannot (anymore?) find any section saying that we can run several operators within the same k8s cluster (same/different operator version)."

I tried resolve this problem and that's not easy now. In my opinion you can't run two different version of operator. I tried do this with 4.3.0 and 4.5.1, 4.6.0. Problem is that operator search all namespaces that has something related to operator if it has then opertor try do something and if version is not correct then is error. You can resolve that by using this script ./odev/src/github.com/crunchydata/postgres-operator/deploy/add-targeted-namespace.sh nameOfNamespaceToAdd. 
If you want to use version 4.6 you change all namespaces with clusters using this script, if you want use 4.3.0 you use this script in version 4.3.0 for all namespaces and use operator in version 4.3.0 but you cant have running two operators in this same time. 

You can write script to do this for you faster. This process is safe.

**Comment by jose-joye** [comment]
@AleksanderRoszig 
Thanks for the reply and sorry I somehow missed it...

I will give a try 

José

**Comment by andrewlecuyer** [comment]
Considering this issue involves an upgrade process for older versions of Crunchy Postgres for Kubernetes, I am going to proceed with closing this specific issue.

If you have any additional questions, and/or if you would like to further discuss upgrade processes as relates to v5 of the operator, please feel free to reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).

And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/

Thanks!
