### ISSUE TITLE
Unhealthy Liveness and 

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2178]
Hi,

Firstly, We had deployed a postgres operator with v4.3.0. long back and its one of the replica pod has error Pods have warnings. And when described could find as below:
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  18m (x28 over 3h14m)  kubelet  Liveness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  Unhealthy  68s (x33 over 3h14m)  kubelet  Readiness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded

<img width="813" alt="lr" src="https://user-images.githubusercontent.com/50865786/103894486-041b6780-5115-11eb-887a-4a0e879e1f2d.PNG">

How can we check the liveness and readiness probes ?
How can we overcome or control this kind of situation in near future?

Secondly, I have deployed a postgres operator with v4.5.1 and using the command "kubectl get pod hippo-chhz-7bff7b4775-2ln2m -n postgres-gdu1-issue-simulate-2 -o yaml",  found the liveness, readiness files path. Logged into the path and compared the liveness, readiness files of v4.5.1 with liveness, readiness files of v4.3.0. And could not find any difference between the two versions.
Is there any changes with liveness and readiness probes in v4.5.1 compared to v4.3.0?

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
Please upgrade to 4.3.4 or a newer version of the Postgres Operator.
