### ISSUE TITLE
thousands of liveness and readiness probe curl requests

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2181]
Hi,

When we exec into the postgres cluster pod and grep for readiness and liveness probe (12k and 6k requests respectively). 
Also we can see that the RAM usage is high because the above thousands of curl requests. 
Could you please let us know why this is happening?
Also why kubernetes is not taking action like restarting the pod?

Please find the screenshots supporting the statment
<img width="601" alt="i" src="https://user-images.githubusercontent.com/50865786/103929554-7c991d00-5143-11eb-9a6d-dba260b4e53e.png">
<img width="663" alt="i4" src="https://user-images.githubusercontent.com/50865786/103929576-8458c180-5143-11eb-9b21-6fc2424d5842.png">
<img width="601" alt="i1" src="https://user-images.githubusercontent.com/50865786/103929587-8884df00-5143-11eb-8048-a75d74e56b67.png">
<img width="601" alt="i2" src="https://user-images.githubusercontent.com/50865786/103929614-95a1ce00-5143-11eb-9436-5527e33e4218.png">
<img width="661" alt="i3" src="https://user-images.githubusercontent.com/50865786/103929641-9d617280-5143-11eb-9528-26eb4fe60585.png">

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
Changes and fixes have been made to the readiness and liveness probes in newer versions of the Operator. Please upgrade to 4.3.4 or a newer version.
