### ISSUE TITLE
How to configure mount path volumes for "/pgdata", "/run/secrets/kubernetes.io/sericeaccount" and "/pgwal"

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2182]
Hi,

When exec into the postgres pod and df -h we could see that 119GB is allocated to most of the volumes. 
For few volumes like storing "/run/secrets/kubernetes.io/sericeaccount" we dont need 119GB of volume to be used. But would like have more volume for for "/pgdata" and "/pgwal"
I like to know how we can configure the mount path volume?

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/50865786/103931370-342f2e80-5146-11eb-89a5-4c359690cfa3.png)

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.5.1
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
The documentation specifies how you can [set PVC size at cluster creation time](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/customize-cluster/#customize-pvc-size).

**Comment by vinodhreddygabbireddy** [comment]
The documentation link talks about only "/pgdata" directory but we want to configure  all the directories provided in the image below.
How can I change pvc size for "/pgwal" or  "/run/secrets/kubernetes.io/sericeaccount". Why it is defaulting to 119 GB across all the directories.
![image](https://user-images.githubusercontent.com/77124228/103938651-707b7400-50df-11eb-82fe-60b4027693db.png)
