### ISSUE TITLE
Postgres database shutdown after /pgwal mount is full. Causing numerous readiness and liveness threads results in high CPU and Memory Usage

### ISSUE THREAD

**Issue by vinodhreddygabbireddy** [CrunchyData/postgres-operator#2183]
On a running pod after  "/pgwal" mount is full the pod logs shows that database server is shutting down. Expectation is liveness probe should trigger a pod restart instead it is creating numerous readiness and liveness threads results in high CPU and Memory Usage. Below are the screenshot from the pods where the database is shutdown but pod is in running state.

Another question is how to configure/change pvc's? The documentation [link ](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/customize-cluster/#customize-pvc-size) talks about only "/pgdata" directory but we want to configure all the directories provided in the image below.
How can I change pvc size for "/pgwal" or "/run/secrets/kubernetes.io/sericeaccount". Why it is defaulting to 119 GB across all the directories.
![image](https://user-images.githubusercontent.com/77124228/103943710-68bfcd80-50e7-11eb-87c2-4d61ebee9631.png)
![image](https://user-images.githubusercontent.com/77124228/103943750-7aa17080-50e7-11eb-913c-78a324dcd45e.png)
![image](https://user-images.githubusercontent.com/77124228/103944064-f8657c00-50e7-11eb-8701-f830c5fbe235.png)
![image](https://user-images.githubusercontent.com/77124228/103944090-00252080-50e8-11eb-90dd-a66043ecccc2.png)
![image](https://user-images.githubusercontent.com/77124228/103944112-061b0180-50e8-11eb-9f91-147c469bf275.png)
![image](https://user-images.githubusercontent.com/77124228/103944134-0ddaa600-50e8-11eb-84a2-7f1c14b7e49c.png)

Please tell us about your environment:
Postgres  operator version: 4.3.0
Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.5.1
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
This appears to be a re-ask of #2182. There is information about [production support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) found at this URL:

[https://access.crunchydata.com/documentation/postgres-operator/latest/support/](https://access.crunchydata.com/documentation/postgres-operator/latest/support/)

**Comment by vinodhreddygabbireddy** [comment]
The suggestion provided in #2182 is talking about /pgdata mount only but we are looking for configuring other mounts in the pod ("/pgwal", "/run/secrets/kubernetes.io/sericeaccount"). 
Also why there are so many liveness and readiness are triggered in the pod after server is down? I don't find this the support documentation. 
Please let me know how to proceed.
