### ISSUE TITLE
Postgres v4.5.1 db not responding/auto-healing but gke pod is in running state

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2184]
Hi there,

We have a postgres operator installed with v4.5.1.
Once the pgwal is full we could see that the db is reinitializing and can find error  mentioned as below
**2021-01-08 11:21:22.258 UTC [437826] ERROR:  requested starting point 0/7E000000 is ahead of the WAL flush position of this server 0/7DFFEF28**
We are not able to perform any db operations but the pod is in running state in gcp console (kubernetes)
Below is the health check response when we do a curl on http://127.0.0.1:8009/health
**bash-4.2$ curl http://127.0.0.1:8009/health
{"state": "running", "postmaster_start_time": "2021-01-07 11:07:28.300 UTC", "role": "master", "server_version": 120005, "cluster_unlocked": false, "xlog": {"location": 2181038080}, "timeline": 1, "database_system_identifier": "6914973136471646372", "patroni": {"version": "2.0.1", "scope": "hippo"}}**

Can you please let us know how we can recover the container from the scenario and trigger an auto-heal of the container without performing a restart on the pod.

<img width="576" alt="i6" src="https://user-images.githubusercontent.com/50865786/104051687-863b8700-520e-11eb-987b-0cfc940bd137.png">
<img width="576" alt="i7" src="https://user-images.githubusercontent.com/50865786/104052624-fc8cb900-520f-11eb-8911-b459805de5ca.png">
<img width="576" alt="i8" src="https://user-images.githubusercontent.com/50865786/104052632-01ea0380-5210-11eb-9f24-a632e4b0375c.png">

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.5.1
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
This does not appear to be a bug. For information on [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) please review the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) section of the documentation.
