### ISSUE TITLE
The installing pgo metrics 4.5.1 not work based

### ISSUE THREAD

**Issue by e-Evolution** [CrunchyData/postgres-operator#2186]
**Describe the bug**
When trying to install pgo metrics 4.5.1 not work.

I got this error <urlopen error [Errno -2] Name or service not known>", "owner": "daemon", "size": 4096, "state": "directory", "uid": 2, "url": "https://github.com/CrunchyData/pgmonitor/archive/v4.4-RC7.tar.gz"}

**To Reproduce**
1.  kubectl create namespace pro
2. git clone https://github.com/CrunchyData/postgres-operator.git
3. cd postgres-operator/installers/helm
4. helm install postgres-operator . -n pgo
5. so good everything 
6. cd postgres-operator/installers/metrics/helm
7. helm install metrics . -n pgo
8. here fail

**Expected behavior**
the installation should finish 

**Screenshots**
the deployment show error

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/786968/104066453-1229c080-51c7-11eb-90fc-05627d354964.png">

this log info 

kubectl logs pod/pgo-metrics-deploy-7j29z -n pgo

PLAY [Deploy Crunchy PostgreSQL Operator Monitoring] ***************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [pgo-metrics-preflight : include_tasks] ***********************************
included: /ansible/metrics/roles/pgo-metrics-preflight/tasks/vars.yml for localhost

TASK [pgo-metrics-preflight : Check for "/conf/values.yaml"] *******************
ok: [localhost]

TASK [pgo-metrics-preflight : fail] ********************************************
skipping: [localhost]

TASK [pgo-metrics-preflight : include_vars] ************************************
ok: [localhost]

TASK [pgo-metrics-preflight : fail] ********************************************
skipping: [localhost]

TASK [pgo-metrics-preflight : assert] ******************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [pgo-metrics-preflight : assert] ******************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [pgo-metrics-preflight : assert] ******************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [pgo-metrics-preflight : assert] ******************************************
skipping: [localhost]

TASK [pgo-metrics-preflight : assert] ******************************************
skipping: [localhost]

TASK [pgo-metrics-preflight : assert] ******************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [pgo-metrics-preflight : include_tasks] ***********************************
skipping: [localhost]

TASK [pgo-metrics-preflight : include_tasks] ***********************************
included: /ansible/metrics/roles/pgo-metrics-preflight/tasks/check_kubernetes.yml for localhost

TASK [pgo-metrics-preflight : Check if the kubectl command is installed] *******
changed: [localhost]

TASK [pgo-metrics-preflight : Ensure kubectl is installed] *********************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [pgo-metrics-preflight : include_tasks] ***********************************
included: /ansible/metrics/roles/pgo-metrics-preflight/tasks/check_vars.yml for localhost

TASK [pgo-metrics-preflight : Check if mandatory metrics variables are defined] ***
skipping: [localhost] => (item=metrics_namespace) 
skipping: [localhost] => (item=pgmonitor_version) 

TASK [pgo-metrics-preflight : include_tasks] ***********************************
included: /ansible/metrics/roles/pgo-metrics-preflight/tasks/preflight-grafana.yml for localhost

TASK [pgo-metrics-preflight : Check if inventory file variables are defined for Grafana] ***
skipping: [localhost] => (item=grafana_admin_username) 
skipping: [localhost] => (item=grafana_admin_password) 
skipping: [localhost] => (item=grafana_dashboards_configmap) 
skipping: [localhost] => (item=grafana_datasources_configmap) 
skipping: [localhost] => (item=grafana_image_name) 
skipping: [localhost] => (item=grafana_image_prefix) 
skipping: [localhost] => (item=grafana_image_tag) 
skipping: [localhost] => (item=grafana_port) 
skipping: [localhost] => (item=grafana_service_name) 
skipping: [localhost] => (item=grafana_service_type) 
skipping: [localhost] => (item=grafana_storage_access_mode) 
skipping: [localhost] => (item=grafana_volume_size) 

TASK [pgo-metrics-preflight : include_tasks] ***********************************
included: /ansible/metrics/roles/pgo-metrics-preflight/tasks/preflight-prometheus.yml for localhost

TASK [pgo-metrics-preflight : Check if inventory file variables are defined for Prometheus] ***
skipping: [localhost] => (item=db_port) 
skipping: [localhost] => (item=pgbadgerport) 
skipping: [localhost] => (item=prometheus_configmap) 
skipping: [localhost] => (item=prometheus_image_name) 
skipping: [localhost] => (item=prometheus_image_prefix) 
skipping: [localhost] => (item=prometheus_image_tag) 
skipping: [localhost] => (item=prometheus_port) 
skipping: [localhost] => (item=prometheus_service_name) 
skipping: [localhost] => (item=prometheus_service_type) 
skipping: [localhost] => (item=prometheus_storage_access_mode) 
skipping: [localhost] => (item=prometheus_volume_size) 

TASK [pgo-metrics-preflight : include_tasks] ***********************************
included: /ansible/metrics/roles/pgo-metrics-preflight/tasks/preflight-alertmanager.yml for localhost

TASK [pgo-metrics-preflight : Check if inventory file variables are defined for Alertmanager] ***
skipping: [localhost] => (item=alertmanager_configmap) 
skipping: [localhost] => (item=alertmanager_rules_configmap) 
skipping: [localhost] => (item=alertmanager_image_name) 
skipping: [localhost] => (item=alertmanager_image_prefix) 
skipping: [localhost] => (item=alertmanager_image_tag) 
skipping: [localhost] => (item=alertmanager_log_level) 
skipping: [localhost] => (item=alertmanager_port) 
skipping: [localhost] => (item=alertmanager_service_name) 
skipping: [localhost] => (item=alertmanager_service_type) 
skipping: [localhost] => (item=alertmanager_storage_access_mode) 
skipping: [localhost] => (item=alertmanager_volume_size) 

TASK [pgo-metrics : Set Metrics Directory Fact] ********************************
ok: [localhost]

TASK [pgo-metrics : Ensure Output Directory Exists] ****************************
changed: [localhost]

TASK [pgo-metrics : include_tasks] *********************************************
skipping: [localhost] => (item=openshift_auth.yml) 
skipping: [localhost] => (item=openshift.yml) 

TASK [pgo-metrics : include_tasks] *********************************************
included: /ansible/metrics/roles/pgo-metrics/tasks/kubernetes_auth.yml for localhost
included: /ansible/metrics/roles/pgo-metrics/tasks/kubernetes.yml for localhost

TASK [pgo-metrics : Set the Kubernetes Context] ********************************
skipping: [localhost]

TASK [pgo-metrics : Create Namespace pgo] **************************************
changed: [localhost]

TASK [pgo-metrics : Use kubectl or oc] *****************************************
ok: [localhost]

TASK [pgo-metrics : Download pgmonitor v4.4-RC7] *******************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/.pgo/metrics/pgo", "elapsed": 20, "gid": 2, "group": "daemon", "mode": "0700", "msg": "Request failed: <urlopen error [Errno -2] Name or service not known>", "owner": "daemon", "size": 4096, "state": "directory", "uid": 2, "url": "https://github.com/CrunchyData/pgmonitor/archive/v4.4-RC7.tar.gz"}

PLAY RECAP *********************************************************************
localhost                  : ok=21   changed=3    unreachable=0    failed=1    skipped=11   rescued=0    ignored=0   

**Please tell us about your environment:**

* Operating System: Debian GNU/Linux 10 (buster)
* Where is this running ( Local)
* Storage being used (Hostpath):
* Container Image Tag: centos7-4.5.1
* PostgreSQL Version: 13.1
* Platform (Kubernetes v1.20.1):
* Platform Version: postgres-operator 4.5.1

**Comment by jkatz** [comment]
This works for me:

```
$ curl -L https://github.com/CrunchyData/pgmonitor/archive/v4.4-RC7.tar.gz > v4.4-RC7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   131  100   131    0     0   1578      0 --:--:-- --:--:-- --:--:--  1578
100 12.8M    0 12.8M    0     0  6208k      0 --:--:--  0:00:02 --:--:-- 7240k

$ ls -l v4.4-RC7.tar.gz
-rw-r--r--. 1 vagrant vagrant 13452503 Jan  8 21:57 v4.4-RC7.tar.gz
```

Check your network settings.

**Comment by jkatz** [comment]
Based on your deployment environment, this may be require the request as noted in #1987

**Comment by e-Evolution** [comment]
Based in #1987 where can change the url 

how can change the url to stable version release https://github.com/CrunchyData/pgmonitor/releases/tag/v4.4 vs v4.4-RC7.tar.gz

I try research  into the postgres-operator/installers/metrics/helm directory and not found any ref to v4.4-RC7.tar.gz

kind regards

**Comment by jkatz** [comment]
For all intents and purposes for the Postgres Operator, pgMonitor 4.4 RC7 == pgMonitor 4.4.

If you're network is unable to call out to the Internet, you will either need to change your network settings to be able to download a file from GitHub or wait for the changes that are suggested in #1987.

Given we've heard this request a few times now, I'm working on a patch to address this.
