### ISSUE TITLE
ephemeral storage limit

### ISSUE THREAD

**Issue by pmpetit** [CrunchyData/postgres-operator#2188]
Hello,
i am testing pgo operator.

pod is always evicted (see attached desc)
[yk-5c9b5bbbbc-vncbp.log](https://github.com/CrunchyData/postgres-operator/files/5790593/yk-5c9b5bbbbc-vncbp.log)

i did not find any plaecs where i can change this limit value....
thx

**Comment by jkatz** [comment]
This is will documented:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/customize-cluster/#customize-pvc-size](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/customize-cluster/#customize-pvc-size)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/customize-cluster/#customize-cpu-memory](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/customize-cluster/#customize-cpu-memory)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_update_cluster/](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_update_cluster/)

**Comment by pmpetit** [comment]
Thanks, but what about ephemeral storage limit ?
there is nothing about that.
Do you think i can change cpu_limit or memory_limit keyword with ephemeral_limit ?

**Comment by pmpetit** [comment]
Local ephemeral storage resource limit comes with

FEATURE STATE: Kubernetes v1.10 [beta]

**Comment by jkatz** [comment]
This is at least causing me to review what we are using for ephemeral volumes. There appear to be a few legacy ones that are included as part of the cluster-deployment, but I believe those can be removed.

However, there is one that is an interesting case:

```json
{
  "name": "dshm",
  "emptyDir": {
    "medium": "Memory"
  }
}
```

Per #1359 this was added to ensure that each PostgreSQL Pod has access to the full spectrum of shared memory, which is an  important part of the PostgreSQL run time (#1358). 

The error message from your log states:

```
  Warning  Evicted           23s                     kubelet            The node was low on resource: ephemeral-storage. Container database was using 84Ki, which exceeds its request of 0.
```

though I am unsure what is specifically triggering that. If there is no shared memory available, then there is an issue or a setting in your local Kubernetes environment that needs to be investigated.

Perhaps we tie the shared memory request limit to the memory limit assigned to a Pod, but that gets to be a bit more complicated as shared memory is traditionally a subset of the overall resources consumed by a PostgreSQL instance.
