### ISSUE TITLE
Greeting key error on stanza-create job when deploying operator with custom timescale extension

### ISSUE THREAD

**Issue by honne23** [CrunchyData/postgres-operator#2189]
**Describe the bug**
After using the code available <a href="https://github.com/CrunchyData/crunchy-containers/issues/747">here</a> to build the crunchy-postgres-ha container with a custom extension (`timescaledb`); when deploying to a k8s cluster on GKE an error occurs and causes the `stanza-create` job to enter a `CrashLoopBackOff`.

**To Reproduce**
1. Build a custom postgres-ha image using the following Dockerfile:
```dockerfile
FROM crunchydata/crunchy-postgres-ha:centos7-12.5-4.4.2

USER root

RUN curl -sSL -o /etc/yum.repos.d/timescale_timescaledb.repo "https://packagecloud.io/install/repositories/timescale/timescaledb/config_file.repo?os=el&dist=7" && \
    yum --disablerepo=crunchypg12 update -y && \
    yum --disablerepo=crunchypg12 install -y timescaledb-postgresql-12 && \
    yum clean all 

RUN sed -i '/shared_preload_libraries:/ s/$/,timescaledb/' /opt/cpm/conf/postgres-ha-initdb.yaml && \
    sed -i '/\\c "\${PGHA_DATABASE}"$/a CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;' /opt/cpm/bin/sql/setup.sql

USER 26
```
2. `docker push` image to relevant repo (in my case `eu.gcr.io`)
3. Deploy postgres cluster with custom image:
```bash
pgo create cluster my-db --ccp-image-prefix="eu.gcr.io/<project-id>" --ccp-image="timescale-custom" -c latest  -d <dbname> -u <username> --password="<password>"
```
4. Observe the logs for the `my-db-stanza-create-xxxx` pod

**Expected behavior**
A smooth cluster setup with no issues where the `stanza-create` jobs runs through to completion.

**Please tell us about your environment:**

* Operating System: Container Optimised OS
* Where is this running: Google Cloud Kubernetes Engine
* Storage being used: K8s PVC
* Container Image Tag: `centos7-12.5-4.4.2`
* PostgreSQL Version: 12.5
* Platform: Docker, Kubernetes
* Platform Version: K8s 1.16.15

**Additional context**
Output logs from `stanza-create`:
```bash
time="2021-01-10T02:19:07Z" level=info msg="pgo-backrest starts"
time="2021-01-10T02:19:07Z" level=info msg="debug flag set to false"
time="2021-01-10T02:19:07Z" level=info msg="backrest stanza-create command requested"
time="2021-01-10T02:19:07Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.8.0.41 --db-path=/pgdata/xworks-db]"
time="2021-01-10T02:19:07Z" level=info msg="command is pgbackrest stanza-create  --db-host=10.8.0.41 --db-path=/pgdata/xworks-db "
time="2021-01-10T02:19:07Z" level=error msg="command terminated with exit code 56"
time="2021-01-10T02:19:07Z" level=info msg="output=[]"
time="2021-01-10T02:19:07Z" level=info msg="stderr=[WARN: unable to check pg-1: [ProtocolError] expected value '2.29' for greeting key 'version' but got '2.27'\nERROR: [056]: unable to find primary cluster - canno
t proceed\n]"
time="2021-01-10T02:19:07Z" level=error msg="command terminated with exit code 56"
```

**Comment by jkatz** [comment]
It sounds like you have an incompatible image in the mix. Please see the [chart on version compatibility](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/):

- [https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/)
- (Specifically for 4.4.2: [https://access.crunchydata.com/documentation/postgres-operator/4.4.2/configuration/compatibility/](https://access.crunchydata.com/documentation/postgres-operator/4.4.2/configuration/compatibility/)
