### ISSUE TITLE
Backrest Backup Job not use correct `backrest-shared-repo` POD Name

### ISSUE THREAD

**Issue by satriashp** [CrunchyData/postgres-operator#2192]
**Describe the bug**
After backrest-shared-repo Deployment got rolling-update (change POD name), backrest-backup-*** Job not use the correct POD name. This job still using old POD name that no longer exists.

**To Reproduce**
1. Perform rolling update (`kubectl rollout restart`) on backrest-shared-repo Deployment.
2. Wait for backrest-backup-*** Job to be trigger (cause i dont know how to manual triggered it.)
3. Job getting fail cause this error
```
time="2021-01-11T03:40:52Z" level=error msg="pods \"yara-backrest-shared-repo-866866ccf-6lt2f\" not found"
```

**Expected behavior**
Job successfully done.

**Screenshots**
https://paste.pics/f8963f06a4fbeabec5768a9ba50b1ce8

**Please tell us about your environment:**

* Operating System: 
* Where is this running ( Local, Cloud Provider) 
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag: pgo-backrest:centos7-4.5.1
* PostgreSQL Version: 11.10
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 

**Additional context**
Complete Error message from Job:
```
time="2021-01-11T03:40:52Z" level=info msg="pgo-backrest starts"
time="2021-01-11T03:40:52Z" level=info msg="debug flag set to false"
time="2021-01-11T03:40:52Z" level=info msg="backrest backup command requested"
time="2021-01-11T03:40:52Z" level=info msg="command to execute is [pgbackrest backup --type=full --db-host=100.96.50.61 --db-path=/pgdata/yara]"
time="2021-01-11T03:40:52Z" level=info msg="command is pgbackrest backup --type=full --db-host=100.96.50.61 --db-path=/pgdata/yara "
time="2021-01-11T03:40:52Z" level=error msg="pods \"yara-backrest-shared-repo-866866ccf-6lt2f\" not found"
time="2021-01-11T03:40:52Z" level=info msg="output=[]"
time="2021-01-11T03:40:52Z" level=info msg="stderr=[]"
time="2021-01-11T03:40:52Z" level=error msg="pods \"yara-backrest-shared-repo-866866ccf-6lt2f\" not found"
```

**Comment by jkatz** [comment]
There is a [tutorial](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/) that covers how to take backups:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/)

as well as documentation for how the overall backup infrastructure works:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/)

I'm not quite sure what the current state of your environment is based on what you did (and that also starts to skew towards [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/)) so I can't necessarily provide a solution that can get you out of your situation.

I will note the following facts though:

- `*-backrest-shared-repo` is the name of the Deployment. The Pod name can change based upon changes to the environment, e.g. running a `rollout` (which I don't believe there is a circumstance in which you want to do that).
- if the backup job started during the time in which a Pod was terminated, then the backup job will certainly fail. The job is designed to communicate directly with the Pod, not the Service.

Anyway, I believe if you follow the instructions provided in the linked docs, you will be able to successfully take explicit backups.

**Comment by satriashp** [comment]
@jkatz Is there a default scheduled backup inside the cluster when cluster created?
Cause its look like doing full backup every hours. And that backup job used old backrest-shared-repo POD NAME instead a new one.
When i check list of scheduled backup for the cluster, is empty.
```
pgo show schedule <CLUSTER_NAME>
```
