### ISSUE TITLE
How can I use a custom image for the postgres container only?

### ISSUE THREAD

**Issue by jarrettprosser** [CrunchyData/postgres-operator#2193]
I'm using the 4.5.1 operator and need to install some extensions in the Postgres image. I can see this is being asked about in #2016, but in the meantime I was going to try and use a custom image that I maintain with the required extensions installed. How can I configure the operator to use a private registry with a custom Postgres image, while using the public images for all the other containers?

Thanks!

**Comment by jkatz** [comment]
Which extensions are you looking to install?

**Comment by jarrettprosser** [comment]
In one instance [pg_partman](https://github.com/pgpartman/pg_partman), and in another [timescaledb](https://github.com/timescale/timescaledb).

**Comment by fgielow** [comment]
I share interest in compiling a custom image with timescaleDB.

**Comment by moimart1** [comment]
I follow instruction here: https://github.com/CrunchyData/postgres-operator/issues/2189#issue-782818137

With this `Dockerfile`
```dockerfile
ARG FROM_IMAGE=registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos7-12.5-4.5.1
FROM ${FROM_IMAGE}

USER root
RUN curl -sSL -o /etc/yum.repos.d/timescale_timescaledb.repo "https://packagecloud.io/install/repositories/timescale/timescaledb/config_file.repo?os=el&dist=7" && \
    yum --disablerepo=crunchypg12 update -y && \
    yum --disablerepo=crunchypg12 install -y timescaledb-2-postgresql-12 && \
    yum clean all

RUN sed -i '/shared_preload_libraries:/ s/$/,timescaledb/' /opt/cpm/conf/postgres-ha-initdb.yaml && \
    sed -i '/\\c "\${PGHA_DATABASE}"$/a CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;' /opt/cpm/bin/sql/setup.sql

USER postgres
```

Then I push my custom image and run this command:
```sh
pgo create cluster hippo --ccp-image-prefix <my-registry> --ccp-image crunchy-postgres-ha --ccp-image-tag centos7-12.5-4.5.1
```

I connect to hippo db and I be able to create hyper_table (https://docs.timescale.com/latest/getting-started/creating-hypertables)

I don't know if it's a good solution, but it seems work :)

**Comment by jarrettprosser** [comment]
Thanks @moimart1, that's close to what I need. The last missing piece is that I have a private registry. Can I pass `imagePullSecrets` to the operator somehow to allow access to a private registry? There's a guide to adding secrets [here](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/postgres-operator/), but it's for the operator image, not the database image.

**Comment by jkatz** [comment]
https://github.com/CrunchyData/postgres-operator/issues/2193#issuecomment-758264075

Both of these extensions were added in PGO 4.7 🎉

**Comment by yash-kalwani** [comment]
> Both of these extensions were added in PGO 4.7 🎉

Hi @jkatz from what i understand timescaledb has two distribution licenses Apache 2 and TSL

So in version 4.7 the timescaledb version that is being used is of the Apache 2 license which limits the use of timescaledb in a database-as-a-service distribution ( which i am assuming what crunchydata is doing ) hence the 4.7 version of PGO only supports the Apache 2 license and not the TSL license right?

**Comment by jkatz** [comment]
This is covered in the [4.7 release notes](https://access.crunchydata.com/documentation/postgres-operator/4.7.4/releases/4.7.0/) and a [blog post on the topic](https://blog.crunchydata.com/blog/using-timescaledb-extension-with-the-pgo-the-postgres-operator).
