### ISSUE TITLE
pgo client binaries for windows.

### ISSUE THREAD

**Issue by Hiteshchaudhari1** [CrunchyData/postgres-operator#2196]
** Which example are you working with? **
I am using a Windows OS and when installing pgo client on windows, binaries are not available. I tried to execute it using Cygwin but it did not work either.

**What is the current behavior?**
pgo client cannot be install on windows

**What is the expected behavior?**
pgo client binaries for windows os

**Other information** (e.g. detailed explanation, related issues,  etc)
Just want to check if pgo client have binaries for windows or could be installed on windows? or is it only possible on Linux distributions.
**Please tell us about your environment:**

* Operating System: Windows 10
* Where is this running ( Local , Cloud Provider): Cloud Provider
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag: 
* PostgreSQL Version: 
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 3.11

**Comment by jkatz** [comment]
There is a `pgo` client Windows build provided with every release, e.g:

[https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.1](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.1)

Download he `pgo.exe` file at the bottom.
