### ISSUE TITLE
How to recover from backrest-shared-repo pod failure?

### ISSUE THREAD

**Issue by therealppk** [CrunchyData/postgres-operator#2197]
** Which example are you working with? **
I created a Cluster with pgbackrest and storage set to S3.
```
pgo create cluster my-cluster \
	--pgbackrest-s3-bucket="<bucket>" \
	--pgbackrest-s3-endpoint="s3.amazonaws.com" \
	--pgbackrest-s3-key="<key>" \
	--pgbackrest-s3-key-secret="<secret-key>" \
	--pgbackrest-s3-region="us-east-1" \
	--pgbackrest-s3-uri-style="path" \
	--pgbackrest-storage-type="s3" \
	--replica-count=2 \
	--password="xxxx" \
	--password-replication="xxxx" \
	--password-superuser="xxxx"
```

I setup a schedule.
```
pgo create schedule my-cluster --schedule="0 1 * * *" \
  --schedule-type=pgbackrest  --pgbackrest-backup-type=full \
  --schedule-opts="--repo1-retention-full=7"
```

It ran well till the Kubernetes node hit resource limit and the pods started to fail. Among the other failed pods, pgbackest-shared-repo pod also failed.

The schedule is also failing with the error shown below.
```
pods \"my-cluster-backrest-shared-repo-67c8dc884b-thqxd\" not found"
```

What is the correct way to recover from this? How do I recreate backrest-shared-repo?

**Comment by jkatz** [comment]
> It ran well till the Kubernetes node hit resource limit and the pods started to fail. 

If there is a problem with your Kubernetes environment, you will need to start troubleshooting from there. The pgBackRest repository is governed by a Deployment, so any Pods will automatically be recreated if you have resources available. I would suggest fixing the resource issues in your environment and things should heal automatically.
