### ISSUE TITLE
No information on restart permissions - pgo restart cluster_name

### ISSUE THREAD

**Issue by AleksanderRoszig** [CrunchyData/postgres-operator#2198]
**Describe the bug**
On page 155, 156 I don't see information about permission to restart cluster using new command `pgo restart cluster_name `https://access.crunchydata.com/documentation/postgres-operator/4.5.1/pdf/postgres_operator.pdf .

**Comment by jkatz** [comment]
For the API server. I believe the permission name is `Restart`:

https://github.com/CrunchyData/postgres-operator/blob/72df1a1fd764059fb0c0da7bae0913bfefc194ed/internal/apiserver/perms.go#L32

I believe this is just a simple documentation fix.

**Comment by maleka12** [comment]
I also have problem with this permission. When I try to execute:

pgo create pgorole restart --permissions="Restart"

I get Error: Restart not a valid Permission

I am using version 4.5.1:
pgo version
pgo client version 4.5.1
pgo-apiserver version 4.5.1

Can you check this please?

**Comment by aleksrosz** [comment]
@maleka12  https://github.com/CrunchyData/postgres-operator/issues/2203
maybe you have to build new image or use newer version.

**Comment by maleka12** [comment]
yeah, I can see that in 4.5.2 this permission is already implemented
https://access.crunchydata.com/documentation/postgres-operator/4.5.1/security/configure-postgres-operator-rbac/
https://access.crunchydata.com/documentation/postgres-operator/4.5.2/security/configure-postgres-operator-rbac/
but upgrade is not an option for now - maybe some workaround? ;)
