### ISSUE TITLE
Kuubernetes - Create Postgres users with ConfigMap | Problem with $ in password

### ISSUE THREAD

**Issue by srinathganesh** [CrunchyData/postgres-operator#2200]
**My script to create a new cluster**
Note: `--custom-config="crunchydata-init-sql"` is used
```
kubectl exec -n $NAMESPACE -it $PGO_CLINT -- 
    pgo create cluster -n $NAMESPACE foo --storage-config='nfsstorage' --pgbackrest-storage-config='nfsstorage' 
       --custom-config="crunchydata-init-sql" 
       --password=$PG_PASSWORD --password-superuser=$PG_PASSWORD
```

Then my config map looks like this
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: crunchydata-init-sql
data:
  setup.sql: |
    CREATE USER foo_admin_0 PASSWORD 'Secret#@$*&%!#$fooo';
    CREATE USER foo_admin_1 PASSWORD 'Secret#@*&%!#fooo';
    CREATE USER foo_admin_2 PASSWORD 'Pass1234';
    -- create db....revoke and grant lines (not relevent here)
```

**Problem**:
1. ANY user with password that contains `$` does NOT work. ie. user cannot login

**Observation**:
1. User get created, everything wroks fine
2. When I log into `psql` shell and create user with password containing special char, it works just fine. ONLY when it comes in config map the problem exists.
3. `kubectl get configmap crunchydata-init-sql -o yaml` is **OK**, no issues

**Questions**:
1. Does Crunchydata have a better way to automate create users? (Kubernetes)

--------------

Please tell us about your environment:

$ pgo version
pgo client version 4.4.1
pgo-apiserver version 4.4.1
Operating System: Crunchydata Kubernetes Helm Chart DEFAULTS
Where is this running ( Local , Cloud Provider): Kubernetes Cluster
Storage being used (NFS, Hostpath, Gluster, etc): Any Kubernetes PVC
Platform (Docker, Kubernetes, OpenShift): Kubernetes
crunchy-postgresql-operator Helm chart postgres-operator
home: https://github.com/CrunchyData/postgres-operator
version: 0.1.0
appVersion: 4.4.1

**Comment by jkatz** [comment]
Storing the user credentials in a ConfigMap is not good practice so I'm not eager to try to explore a fix.
