### ISSUE TITLE
Add default_instance_cores, default_pgbackrest_cores, default_exporter_cores

### ISSUE THREAD

**Issue by aleksrosz** [CrunchyData/postgres-operator#2201]
**What is the motivation or use case for the change?**
It will be easier to create many clusters for tests if in configuration of operator I can define default request for cores like I can now define memory. 
Something like default_instance_cores, default_pgbackrest_cores, default_exporter_cores

**Describe the solution you'd like**
I think that should be added there https://github.com/CrunchyData/postgres-operator/blob/0c9905f9b866d1831fd07cbdfe19857730d7dcdc/installers/ansible/roles/pgo-operator/templates/pgo.yaml.j2 and in configuration file.

**Comment by jkatz** [comment]
I linked the issue incorrectly.  I meant to link #2198

**Comment by aleksrosz** [comment]
@jkatz Can it be closed?
