### ISSUE TITLE
Helm chart version

### ISSUE THREAD

**Issue by echel0n** [CrunchyData/postgres-operator#2213]
I noticed you've bumped the helm chart app version a few times but do not seem to be bumping the chart version, because of this helm does not know there is a new version out when checking and nor does renovate which I use for automating the updating of my cluster helm chartrs, could you also please bump the helm chart when you bump the app version or make modifications to it?

Thanks!

**Comment by jkatz** [comment]
This was already bumped in https://github.com/CrunchyData/postgres-operator/commit/6a90c80451aadf085f0f703e85d3bbe7bc81d7fa -- 4.6 has not been released yet, so I don't see any reason to bump the chart version further.

**Comment by echel0n** [comment]
Sure, under the examples folder I can see it was but under `installers/helm` it remains at 0.1.0
So then the question is, which is the folder I should be using?

**Comment by jkatz** [comment]
An sorry I missed that. I will make the update.

**Comment by echel0n** [comment]
Thanks!

**Comment by jkatz** [comment]
This is merged and will be available for 4.6
