### ISSUE TITLE
Documentation pgo 4.5.1 still refer to autofail=true instead of enable-autofail 

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2214]
In several places within the doc, the following command is shown:

`go update cluster hacluster --autofail=true`

It should be replaced with:
`pgo update cluster hacluster --enable-autofail `

Regards,
José

**Comment by jkatz** [comment]
@jose-joye Fixed, as well as references to `--autofail=false`. Thanks for reporting!
