### ISSUE TITLE
Is there a way to disable pgbackrest ?

### ISSUE THREAD

**Issue by pylSER** [CrunchyData/postgres-operator#2217]
I really don't need this and it seems to make the whole procedure complicated when using pgbackrest.

**Comment by jkatz** [comment]
There is not a way to disable it. pgBackRest both simplifies and enhances the process of HA and provides a tool to conveniently handle backups. Each release has made improvements on this overall integration -- it is particularly efficient in 4.5 and the upcoming 4.6 release.

Without information what "makes the whole procedure complicated" there is not much to act on here.

**Comment by jkatz** [comment]
I would recommend [watching one of David Steele's talks about the merits of pgBackRest](https://www.youtube.com/watch?v=sFScE1UOcKM). and read some various literature around it. For simple deployments, there is not much you need to do, and when there is a storage issue with your PostgreSQL clusters, or you want to take an action such as cloning, you will be glad that you have backups available :wink:
