### ISSUE TITLE
Customconfig is not applying for v4.5.1

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2218]
Hi there,

We wanted to add parameters like max_connections, min_wal_size and max_wal_size for our cluster using customconfig.
We have created a customconfig.yaml file similar to the details as mentioned in the link: https://github.com/CrunchyData/postgres-operator/blob/72281ca2dd535ec3ebc26833aefe63f95664a578/docs/content/advanced/custom-configuration.md

When we apply it through our pipeline (ci/cd) and use "kubectl describe configmap -n <namespace> <clusterName>-pgha-config"
We are not able to see the values provide in the customconfig.yaml file, instead we can see the values mentioned in the above link.

Expected result:

data:
    postgres-ha.yaml: |
        ---
        bootstrap:
          dcs:
            postgresql:
              parameters:
                logging_collector: on
                log_directory: pglogs
                log_min_duration_statement: 0
                log_statement: none
                max_wal_senders: 6
                max_connections: 200
                shared_preload_libraries: pgaudit.so
                shared_buffers: 256MB
                temp_buffers: 10MB
                work_mem: 5MB
                min_wal_size = 5GB
                max_wal_size = 30GB                
        postgresql:  
          pg_hba:
            - local all postgres peer
            - local all crunchyadm peer
            - host replication primaryuser 0.0.0.0/0 md5
            - host all primaryuser 0.0.0.0/0 reject
            - host all postgres 0.0.0.0/0 md5
            - host all testuser1 0.0.0.0/0 md5
            - host all testuser2 0.0.0.0/0 md5
        
Result we got:

Data
====
hippo-dcs-config:
----
postgresql:
  parameters:
    archive_command: source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest
      archive-push "%p"
    archive_mode: true
    archive_timeout: 60
    log_directory: pg_log
    log_min_duration_statement: 60000
    log_statement: none
    max_wal_senders: 6
    shared_buffers: 128MB
    shared_preload_libraries: pgaudit.so,pg_stat_statements.so,pgnodemx.so
    temp_buffers: 8MB
    unix_socket_directories: /tmp,/crunchyadm
    wal_level: logical
    work_mem: 4MB
  recovery_conf:
    restore_command: source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest
      archive-get %f "%p"
  use_pg_rewind: true

hippo-local-config:
----
postgresql:
  callbacks:
    on_role_change: /opt/cpm/bin/callbacks/pgha-on-role-change.sh
  create_replica_methods:
  - pgbackrest
  - basebackup
  pg_hba:
  - local all postgres peer
  - local all crunchyadm peer
  - host replication primaryuser 0.0.0.0/0 md5
  - host all primaryuser 0.0.0.0/0 reject
  - host all all 0.0.0.0/0 md5
  pgbackrest:
    command: /opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh replica
    keep_data: true
    no_params: true
  pgbackrest_standby:
    command: /opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh standby
    keep_data: true
    no_master: 1
    no_params: true
  pgpass: /tmp/.pgpass
  remove_data_directory_on_rewind_failure: true
  use_unix_socket: true

hippo-mzlh-local-config:
----
postgresql:
  callbacks:
    on_role_change: /opt/cpm/bin/callbacks/pgha-on-role-change.sh
  create_replica_methods:
  - pgbackrest
  - basebackup
  pg_hba:
  - local all postgres peer
  - local all crunchyadm peer
  - host replication primaryuser 0.0.0.0/0 md5
  - host all primaryuser 0.0.0.0/0 reject
  - host all all 0.0.0.0/0 md5
  pgbackrest:
    command: /opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh replica
    keep_data: true
    no_params: true
  pgbackrest_standby:
    command: /opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh standby
    keep_data: true
    no_master: 1
    no_params: true
  pgpass: /tmp/.pgpass
  remove_data_directory_on_rewind_failure: true
  use_unix_socket: true

init:
----
false
Events:  <none>

Kindly let us know what can be done to over come this problem.

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.5.1
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
There is an error in your configuration. You can find documentation on how custom configuration works here:

- [Tutorial](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/customize-cluster/)
- [Details](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/)
- [Configuration Reference](https://patroni.readthedocs.io/en/latest/SETTINGS.html)

As this is an operational issue, more information can be provided via [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/).
