### ISSUE TITLE
POD tolerations support 

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2220]
Hi There,

We wanted to use POD tolerations for v4.5.1. But we could see that defining node tolerations on cluster create and update was added on a beta release (v4.6.0-beta.1)
Could you please let us know a planned date to have the above POD tolerations support on a stable release

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.5.1
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
Information on releases can be found here:

[https://github.com/CrunchyData/postgres-operator#releases](https://github.com/CrunchyData/postgres-operator#releases)
