### ISSUE TITLE
403 Forbidden 403 HTTP/1.1 1 1 map[Content-Length:[39] Content-Type:[text/plain; charset=utf-8] 

### ISSUE THREAD

**Issue by ckvtvm-arch** [CrunchyData/postgres-operator#2223]
I have tried creating several certificates , but no luck. Please help me if there is a easy way to fix this, TLS cannot be disabled as per project needs.

af71194@LC02CHB58MD6R ~ % pgo version --debug                                                
DEBU[0000] debug flag is set to true                    
DEBU[0000] in initConfig with url=https://postgres-operator-co-postgres-crunchydata-dev.apps.ent-ocp4-np1-har.antmdc.internal.das 
DEBU[0000] GetSessionCredentials called                 
DEBU[0000] looking in /Users/af71194/.pgouser for credentials 
DEBU[0000] /Users/af71194/.pgouser found                
DEBU[0000] pgouser file found at /Users/af71194/.pgouser contains admin:examplepassword 
DEBU[0000] [admin examplepassword]                      
DEBU[0000] username=[admin] password=[examplepassword]  
DEBU[0000] setting up httpclient with TLS               
DEBU[0000] GetTLSTransport called                       
DEBU[0000] version called                               
pgo client version 4.5.0
DEBU[0000] ShowVersion called                           
DEBU[0000] https://postgres-operator-co-postgres-crunchydata-dev.apps.ent-ocp4-np1-har.antmdc.internal.das/version 
DEBU[0000] &{403 Forbidden 403 HTTP/1.1 1 1 map[Content-Length:[39] Content-Type:[text/plain; charset=utf-8] Date:[Wed, 20 Jan 2021 06:14:27 GMT] X-Content-Type-Options:[nosniff]] 0xc00028afe0 39 [] false false map[] 0xc00047c200 0xc0000e0370} 
DEBU[0000] http status code is 403

**Comment by ckvtvm-arch** [comment]
also i see PGHA_TLS_ENABLED = FALSE and PGHA_TLS_ONLY=FALSE in the environment. Also i see CRUNCHY-GPG-KEY.public from the terminal. For now, i have created a tls certificate named pgo.tls based on the cert and keys generated from client-setup.sh .

**Comment by ckvtvm-arch** [comment]
please advise

**Comment by jkatz** [comment]
@ckvtvm-arch if you are looking for immediate help please see our guidance on [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/).

I had started looking at this earlier -- it does not appear to be a bug but a configuration issue. This requires more information to figure out what happened, i.e. what's provided in the troubleshooting template:

- Which Kubernetes platform are you using? Which version are you running?
- Which version of the Operator did you install?
- How did you install the Operator?
- Did you customize the configuration or the environment at all?
- Did you customize the environmental variables in your local environment at all?

The [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/) tends to be the fastest way to get things set up, and allows for things to be customized if you are looking to move things into production.

**Comment by ckvtvm-arch** [comment]
Openshift 4.3
4.5.0 
Openshift console
No customization other the secrets created for pgo.tls based on client install keys and certificates
No change to environment variables other than the below
export PGO_OPERATOR_NAMESPACE=co-postgres-crunchydata-dev
export PGO_APISERVER_URL="https://$(oc -n "$PGO_OPERATOR_NAMESPACE" get route postgres-operator -o jsonpath="{.spec.host}")"
PGO_CMD=oc  ./client-setup.sh
	
export PATH=/Users/af71194/.pgo/co-postgres-crunchydata-dev:$PATH
export PGOUSER=/Users/af71194/.pgo/co-postgres-crunchydata-dev/pgouser
export PGO_CA_CERT=/Users/af71194/.pgo/co-postgres-crunchydata-dev/client.crt
export PGO_CLIENT_CERT=/Users/af71194/.pgo/co-postgres-crunchydata-dev/client.crt
export PGO_CLIENT_KEY=/Users/af71194/.pgo/co-postgres-crunchydata-dev/client.key

**Comment by jkatz** [comment]
@ckvtvm-arch  Thanks.

First, I recommend using Operator 4.5.1 as that includes bug fixes.

The documentation states that a [403 error is triggered due to a missing permission](https://access.crunchydata.com/documentation/postgres-operator/latest/security/configure-postgres-operator-rbac/). There is likely something off with your role setup. This is set in the `pgorole-...` Secret.

For simplicity, I suggest using `*` which is a catch-all for all of the permissions. This is what is set by default. Once you have things working, you can further tighten the permissions.

**Comment by ckvtvm-arch** [comment]
Let me try 4.5.1 . i have already set * as pgorole permissions

**Comment by jkatz** [comment]
Then there is a mismatch in your names somewhere, i.e. between the name of the user you are authenticating as and the name on the role Secret.

**Comment by ckvtvm-arch** [comment]
builder-dockercfg-jw7tf             kubernetes.io/dockercfg               1      56d
builder-token-s25xg                 kubernetes.io/service-account-token   4      56d
builder-token-xv4w5                 kubernetes.io/service-account-token   4      56d
default-dockercfg-gbb4h             kubernetes.io/dockercfg               1      56d
default-token-lzf74                 kubernetes.io/service-account-token   4      56d
default-token-qzh4t                 kubernetes.io/service-account-token   4      56d
deployer-dockercfg-7vcs4            kubernetes.io/dockercfg               1      56d
deployer-token-bkprk                kubernetes.io/service-account-token   4      56d
deployer-token-wmmdm                kubernetes.io/service-account-token   4      56d
hippo-backrest-repo-config          Opaque                                5      46h
hippo-pgbouncer-secret              Opaque                                2      46h
hippo-postgres-secret               Opaque                                2      47h
hippo-primaryuser-secret            Opaque                                2      47h
hippo-quay-secret                   Opaque                                2      47h
hippo-tls-keypair                   kubernetes.io/tls                     2      40h
pgo-backrest-dockercfg-sz9mc        kubernetes.io/dockercfg               1      56d
pgo-backrest-repo-config            Opaque                                2      43d
pgo-backrest-token-2t4qp            kubernetes.io/service-account-token   4      56d
pgo-backrest-token-d8776            kubernetes.io/service-account-token   4      56d
pgo-default-dockercfg-cbbtg         kubernetes.io/dockercfg               1      56d
pgo-default-token-ch9p2             kubernetes.io/service-account-token   4      56d
pgo-default-token-hzt8k             kubernetes.io/service-account-token   4      56d
pgo-pg-dockercfg-rkz59              kubernetes.io/dockercfg               1      56d
pgo-pg-token-2rss5                  kubernetes.io/service-account-token   4      56d
pgo-pg-token-nq5vd                  kubernetes.io/service-account-token   4      56d
pgo-target-dockercfg-rbscx          kubernetes.io/dockercfg               1      56d
pgo-target-token-tpnzq              kubernetes.io/service-account-token   4      56d
pgo-target-token-wxz6d              kubernetes.io/service-account-token   4      56d
pgo.tls                             kubernetes.io/tls                     2      28h
pgorole-pgoadmin                    Opaque                                2      39h
pgouser-admin                       Opaque                                3      39h
postgres-operator-dockercfg-rplvc   kubernetes.io/dockercfg               1      56d
postgres-operator-token-2267t       kubernetes.io/service-account-token   4      56d
postgres-operator-token-htrwn       kubernetes.io/service-account-token   4      56d
postgresql-ca                       Opaque                                1      40h
sshd-config                         Opaque                                1      46h

**Comment by ckvtvm-arch** [comment]
af71194@LC02CHB58MD6R kafka-kafdrop % oc describe secret pgorole-pgoadmin
Name:         pgorole-pgoadmin
Namespace:    co-postgres-crunchydata-dev
Labels:       pgo-pgorole=true
              rolename=pgoadmin
              vendor=crunchydata
Annotations:  <none>

Type:  Opaque

Data
====
permissions:  1 bytes
rolename:     8 bytes

**Comment by ckvtvm-arch** [comment]
this was resolved by creating a new namespace and re-installing the operator. I havent added any TLS certificate, roles, user, permissions. It was a very unusual issues for many weeks looking at all various possibilities.

**Comment by jkatz** [comment]
Glad it is resolved.
