### ISSUE TITLE
Add "operator" label to this repository

### ISSUE THREAD

**Issue by VladMasarik** [CrunchyData/postgres-operator#2224]
**What is the motivation or use case for the change? **
Allow others to discover this repository easily.

**Describe the solution you'd like**
Add "operator" label to this repository.

**Additional context**
You have only two labels, and when I was searching for PostgresQL operators on GitHub I found only the Zalando one. Suffice to say I went to search further, and luckily found this project. Thanks!
![image](https://user-images.githubusercontent.com/28529900/105190289-25794c00-5b36-11eb-95f2-b137c3b3a5ba.png)

**Comment by jkatz** [comment]
Thanks for the suggestion, I've gone ahead and made some updates!
