### ISSUE TITLE
node pool for v4.5.1 postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2226]
Hi There,

We want to test node pool for our cluster and tried deploying cluster using below command.

pgo create cluster hippo --password-superuser qwerty123 --password qwerty123 --pgbouncer --replica-count 3 --node-label=node_pool=gto-operator-pool-a

But the cluster was not deployed in the desired node pool (gto-operator-pool-a) but found in node pool gke1-pool-n1.

[root@lvndev012336 ~]# kubectl get pods -n postgres-v45-aiops4 -o wide | grep hippo
backrest-backup-hippo-ghvgz                    0/1     Completed   0          17h   240.0.19.81     gke-gke1-pool-n1-s64-b-v1-83ebb9ce-8kwk   <none>           <none>
backrest-backup-hippo1-5ltx6                   0/1     Completed   0          16h   240.0.124.202   gke-gke1-pool-n1-s64-a-v1-7043b845-a8fn   <none>           <none>
hippo-598f8c9c74-2mdnw                         1/1     Running     0          17h   240.0.231.253   gke-gke1-pool-n1-s64-c-v1-46e97013-7fge   <none>           <none>
hippo-axnz-5776c89ffd-sfpfz                    1/1     Running     0          17h   240.0.133.192   gke-gke1-pool-n1-s64-a-v1-7043b845-zy9c   <none>           <none>
hippo-axvn-56458946f4-shblw                    1/1     Running     0          17h   240.0.19.83     gke-gke1-pool-n1-s64-b-v1-83ebb9ce-8kwk   <none>           <none>
hippo-backrest-shared-repo-6494bb88dd-nblln    1/1     Running     1          17h   240.0.124.40    gke-gke1-pool-n1-s64-a-v1-7043b845-a8fn   <none>           <none>
hippo-pgbouncer-5bb4f67976-sr474               1/1     Running     0          17h   240.0.195.106   gke-gke1-pool-n1-s64-b-v1-83ebb9ce-kjno   <none>           <none>
hippo-stanza-create-xb2qx                      0/1     Completed   0          17h   240.0.19.80     gke-gke1-pool-n1-s64-b-v1-83ebb9ce-8kwk   <none>           <none>
hippo-xpov-5756f979b6-6mxbd                    1/1     Running     0          17h   240.0.15.202    gke-gke1-pool-n1-s64-b-v1-83ebb9ce-bs09   <none>           <none>
hippo1-69d78c785c-pk2jn                        1/1     Running     0          16h   240.0.231.33    gke-gke1-pool-n1-s64-c-v1-46e97013-7fge   <none>           <none>
hippo1-backrest-shared-repo-7dfcf7d54f-r9hq2   1/1     Running     1          16h   240.0.124.38    gke-gke1-pool-n1-s64-a-v1-7043b845-a8fn   <none>           <none>
hippo1-lwgd-5db4647fd6-bz87c                   1/1     Running     0          16h   240.0.133.195   gke-gke1-pool-n1-s64-a-v1-7043b845-zy9c   <none>           <none>
hippo1-onoa-69c8f96db9-58kjl                   1/1     Running     0          16h   240.0.19.113    gke-gke1-pool-n1-s64-b-v1-83ebb9ce-8kwk   <none>           <none>
hippo1-pgbouncer-84d9db5c7f-rrdch              1/1     Running     0          16h   240.0.11.128    gke-gke1-pool-n1-s64-a-v1-7043b845-dwb5   <none>           <none>
hippo1-stanza-create-c9qq9                     0/1     Completed   0          16h   240.0.124.201   gke-gke1-pool-n1-s64-a-v1-7043b845-a8fn   <none>           <none>

We also tried with below command but it was same result as earlier.

pgo create cluster hippo1 --password-superuser qwerty123 --password qwerty123 --pgbouncer --replica-count 2 --node-label=cloud.google.com/gke-nodepool=gto-operator-pool-a

output:
[root@lvndev012336 ~]# kubectl get pods -n postgres-v45-aiops4 -o wide | grep hippo1
backrest-backup-hippo1-5ltx6                   0/1     Completed   0          16h   240.0.124.202   gke-gke1-pool-n1-s64-a-v1-7043b845-a8fn   <none>           <none>
hippo1-69d78c785c-pk2jn                        1/1     Running     0          16h   240.0.231.33    gke-gke1-pool-n1-s64-c-v1-46e97013-7fge   <none>           <none>
hippo1-backrest-shared-repo-7dfcf7d54f-r9hq2   1/1     Running     1          16h   240.0.124.38    gke-gke1-pool-n1-s64-a-v1-7043b845-a8fn   <none>           <none>
hippo1-lwgd-5db4647fd6-bz87c                   1/1     Running     0          16h   240.0.133.195   gke-gke1-pool-n1-s64-a-v1-7043b845-zy9c   <none>           <none>
hippo1-onoa-69c8f96db9-58kjl                   1/1     Running     0          16h   240.0.19.113    gke-gke1-pool-n1-s64-b-v1-83ebb9ce-8kwk   <none>           <none>
hippo1-pgbouncer-84d9db5c7f-rrdch              1/1     Running     0          16h   240.0.11.128    gke-gke1-pool-n1-s64-a-v1-7043b845-dwb5   <none>           <none>
hippo1-stanza-create-c9qq9                     0/1     Completed   0          16h   240.0.124.201   gke-gke1-pool-n1-s64-a-v1-7043b845-a8fn   <none>           <none>

We tried to add flag --node-affinity-type=required while deploying but i think v4.5.1 does not support this flag.

Could you please suggest how can we deploy a cluster in desired node pool.

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.5.1
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
The [documentation on node affinity](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/#node-affinity) for 4.5.1 states that the Operator uses *preferred* node affinity for scheduling and adds:

> The Node Affinity only uses the preferred scheduling strategy (similar to what is described in the Pod Anti-Affinity section above), so if a Pod cannot be scheduled to a particular Node matching the label, it will be scheduled to a different Node.

So this is expected behavior.

The 4.6.0 version of the Operator added support for required node affinity, which will attempt to force the scheduling of Pods to Nodes matching the label. You can read about this in the release notes:

- [4.6.0 beta 1 release notes](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.6.0-beta.1)
- [Nightly Build Release Notes](https://crunchydata.github.io/postgres-operator/latest/releases/4.6.0/#node-affinity-enhancements)
