### ISSUE TITLE
Can't disable full backups while created standard postgres cluster

### ISSUE THREAD

**Issue by AleksanderRoszig** [CrunchyData/postgres-operator#2227]
** Which example are you working with? **
When I create standard cluster:
`pgo create cluster examplecluster` it create cluster that is backuped every circa 15 minutes via full backup. If I use command
`pgo backup examplecluster --backup-opts='--test-retention-full=7' then it create according to the documentation standard incremental backup, delete full backups that last only 7 and makes in future correct incremental backups but that doesn't affect full backups every 15 minutes. Is that correct? How to disable this full backups.
`
**What is the current behavior?**
Full backups every 15 minutes + backups from command `pgo backup`

**What is the expected behavior?**
Only backups managed by command `pgo backup`

* Operating System:
* Where is this running ( Local , Cloud Provider) Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: registry.connect.redhat.com/crunchydata/ tag:ubi7-4.5.1
* PostgreSQL Version: 12.5 and 9.6
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 3.11

**Comment by jkatz** [comment]
Please see the thread on #2106. Any information to provide something that can reproduce the behavior will be helpful, but please use #2106 to discuss.
