### ISSUE TITLE
Slight update to `pgo` client documentation 

### ISSUE THREAD

**Issue by VladMasarik** [CrunchyData/postgres-operator#2228]
**What is the motivation or use case for the change?**
Clear up documentation

**Describe the solution you'd like**
In this [document](https://github.com/CrunchyData/postgres-operator/blob/master/docs/content/installation/postgres-operator.md#install-the-pgo-client-relref-installationpgo-client-), in there is a line "Sets the following environmental variables". When I was installing the operator, I was quite confused because the variables were not set, and the script output said something else. In other words the docs say the `client-setup.sh` sets the env vars, but it does not, you have to do it. 

Additionally, I believe the `export PATH=$HOME/.pgo/$PGO_OPERATOR_NAMESPACE:$PATH` is missing, although the script output is mentioning it.

**Additional context**
I don't mind writing the PR, but I am not sure if it is worth writing it, and maybe I missed something in the docs so my suggestion wouldn't make sense, which is why I am writing issue first to know what you think.

**Comment by jkatz** [comment]
Thanks for the suggestion. Pull requests are more than welcome, and it would be easier to comment on it once there are specific changes outlined.

**Comment by VladMasarik** [comment]
Related to #2328 which got reworked, and added later on.
