### ISSUE TITLE
pgo-backrest-repo-config secret is missing

### ISSUE THREAD

**Issue by lusu007** [CrunchyData/postgres-operator#2230]
**Which example are you working with?**
I'm working with the example from [operatorhub.io](https://operatorhub.io/operator/postgresql). I have deployed the postgres operator according to the instructions provided by a click on the install button on operatorhub. For cluster creation I'm using the 'Postgres Primary Cluster Member' example from the documentation on that site.

**What is the current behavior?**
I'm deploying a Postgres Cluster using the Postgres Primary Cluster Member example in the operatorhub readme page. After applying my created Pgcluster resource the operator doesn't start a database cluster. 
The operator throws the following error in the log:
```
time="2021-01-24T19:28:20Z" level=info msg="PostgreSQL Operator initialized and running, waiting for signal to exit" func="main.main()" file="postgres-operator.go:110" version=4.5.1
I0124 19:28:22.069577 1 shared_informer.go:197] Waiting for caches to sync for global-keycloak-postgres
I0124 19:28:22.169819 1 shared_informer.go:204] Caches are synced for global-keycloak-postgres
time="2021-01-24T19:29:19Z" level=error msg="secrets \"pgo-backrest-repo-config\" not found" func="internal/util.CreateBackrestRepoSecrets()" file="internal/util/cluster.go:156" version=4.5.1
time="2021-01-24T19:29:19Z" level=error msg="secrets \"pgo-backrest-repo-config\" not found" func="internal/operator/cluster.AddClusterBase()" file="internal/operator/cluster/cluster.go:93" version=4.5.1
2021/01/24 19:29:19 INF 2 (localhost:4150) connecting to nsqd
```

**What is the expected behavior?**
The operator should start a cluster.

**Other information** (e.g. detailed explanation, related issues,  etc)
Pgcluster file:
```yaml
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  labels:
    archive: 'false'
  name: keycloak
  namespace: global-keycloak-postgres
spec:
  PrimaryStorage:
    name: keycloak
    size: 1G
  ccpimage: crunchy-postgres-ha
  ccpimagetag: centos7-12.5-4.5.1
  clustername: keycloak
  database: keycloak
  exporterport: '9187'
  name: keycloak
  pgbadgerport: '10000'
  port: '5432'
  primarysecretname: keycloak-primaryuser-secret
  rootsecretname: keycloak-postgres-secret
  userlabels:
    archive: 'false'
  usersecretname: keycloak-keycloak-secret
```

My user secret for postgres are created after the [official operator documentation](https://access.crunchydata.com/documentation/postgres-operator/4.5.1/custom-resources/). The documentation also mentions that a secret must be created with the information for the pgBackrest repository. But it is not described in detail what exactly has to be done. I skipped this step so far.

**Please tell us about your environment:**

* Where is this running (Local, Cloud Provider): OVH Managed Kubernetes
* Storage being used (NFS, Hostpath, Gluster, etc): OVH Block Storage
* Container Image Tag: (default from latest operator)
* PostgreSQL Version: (default from latest operator)
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: (default from latest operator)

**Comment by jkatz** [comment]
I don't think the issue is the `pgo-backrest-repo-secret` error. The Operator may log that as an error, but it will create that Secret automatically.

I don't think that CR would work in 4.5.1. 4.6 was just released, I would suggest trying again with that:

[https://github.com/CrunchyData/postgres-operator/releases/tag/v4.6.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.6.0)

workflows around that are here:

[https://access.crunchydata.com/documentation/postgres-operator/4.6.0/custom-resources/](https://access.crunchydata.com/documentation/postgres-operator/4.6.0/custom-resources/)

**Comment by lusu007** [comment]
Thank you for your answer. I will give it a try the coming days. 😄

**Comment by lusu007** [comment]
I fixed it on version 4.5.1 by creating the `pgo-backrest-repo-secret` before creating a `pgcluster` resource.

But now I'm getting another error:
```
time="2021-02-04T12:09:18Z" level=error msg="Deployment.apps \"\" is invalid: metadata.name: Required value: name or generateName is required" func="internal/operator/cluster.AddClusterBase()" file="internal/operator/cluster/cluster.go:105" version=4.5.1
```

**Comment by jkatz** [comment]
What does your pgcluster YAML file look like?

> btw: I can't find the newest version on OperatorHub yet. Is there an ETA on that?

Please see:

- https://github.com/operator-framework/community-operators/pull/3066
- https://github.com/operator-framework/community-operators/pull/3067

**Comment by lusu007** [comment]
After experimenting a bit more I the first pod gets started. But on startup of the database pod I get the following error now.

```

initdb: error: could not create directory "/pgdata/kratos": Permission denied
pg_ctl: database system initialization failed
2021-02-04 19:23:22,956 INFO: removing initialize key after failed attempt to bootstrap the cluster
Process Process-1:
Traceback (most recent call last):
File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
abstract_main(Patroni, schema)
File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
controller.run()
File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
super(Patroni, self).run()
File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
self._run_cycle()
File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
logger.info(self.ha.run_cycle())
File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
info = self._run_cycle()
File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1346, in _run_cycle
return self.post_bootstrap()
File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1242, in post_bootstrap
self.cancel_initialization()
File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1235, in cancel_initialization
raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```

My pgcluster file looks like the following:
```
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: kratos
  labels:
    archive: 'false'
    name: kratos
    pg-cluster: kratos
    deployment-name: kratos
    crunchy-pgha-scope: kratos
  name: kratos
  namespace: global-kratos-postgres
spec:
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: "csi-cinder-classic"
    storagetype: dynamic
    fsgroup: "26"
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: kratos-postgres
    size: 1G
    storageclass: "csi-cinder-classic"
    storagetype: dynamic
    fsgroup: "26"
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: "csi-cinder-classic"
    storagetype: dynamic
    fsgroup: "26"
  ccpimage: crunchy-postgres-ha
  ccpimagetag: centos7-12.5-4.5.1
  clustername: kratos
  database: kratos
  exporterport: '9187'
  name: kratos
  namespace: global-kratos-postgres
  pgbadgerport: '10000'
  port: '5432'
  primarysecretname: kratos-primaryuser-secret
  rootsecretname: kratos-postgres-secret
  userlabels:
    archive: 'false'
  usersecretname: kratos-kratos-secret
```


> Please see:
> 
> operator-framework/community-operators#3066
> operator-framework/community-operators#3067
Thanks I will have a look on that 😄

**Comment by jkatz** [comment]
> initdb: error: could not create directory "/pgdata/kratos": Permission denied

This sounds like a permission issue at your storage layer. Note that on OpenShift if you have a restricted Security Context Constraint, you will need to set `disable_fsgroup` to `true` in the `pgo.yaml` section of the `pgo-config` ConfigMap and restart the Operator. (which is covered in the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/), tutorial, and several other places in the [docs](https://access.crunchydata.com/documentation/postgres-operator/latest/)).

Otherwise, you may need to troubleshoot your storage provisioner.

**Comment by rienafairefr** [comment]
> After experimenting a bit more I the first pod gets started. But on startup of the database pod I get the following error now.
> 
> ```
> 
> initdb: error: could not create directory "/pgdata/kratos": Permission denied
> pg_ctl: database system initialization failed
> 2021-02-04 19:23:22,956 INFO: removing initialize key after failed attempt to bootstrap the cluster
> Process Process-1:
> Traceback (most recent call last):
> File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
> self.run()
> File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
> self._target(*self._args, **self._kwargs)
> File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
> abstract_main(Patroni, schema)
> File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
> controller.run()
> File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
> super(Patroni, self).run()
> File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
> self._run_cycle()
> File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
> logger.info(self.ha.run_cycle())
> File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
> info = self._run_cycle()
> File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1346, in _run_cycle
> return self.post_bootstrap()
> File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1242, in post_bootstrap
> self.cancel_initialization()
> File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1235, in cancel_initialization
> raise PatroniFatalException('Failed to bootstrap cluster')
> patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
> ```
> 
> My pgcluster file looks like the following:
> 
> ```
> apiVersion: crunchydata.com/v1
> kind: Pgcluster
> metadata:
>   annotations:
>     current-primary: kratos
>   labels:
>     archive: 'false'
>     name: kratos
>     pg-cluster: kratos
>     deployment-name: kratos
>     crunchy-pgha-scope: kratos
>   name: kratos
>   namespace: global-kratos-postgres
> spec:
>   BackrestStorage:
>     accessmode: ReadWriteMany
>     matchLabels: ""
>     name: ""
>     size: 1G
>     storageclass: "csi-cinder-classic"
>     storagetype: dynamic
>     fsgroup: "26"
>   PrimaryStorage:
>     accessmode: ReadWriteMany
>     matchLabels: ""
>     name: kratos-postgres
>     size: 1G
>     storageclass: "csi-cinder-classic"
>     storagetype: dynamic
>     fsgroup: "26"
>   ReplicaStorage:
>     accessmode: ReadWriteMany
>     matchLabels: ""
>     name: ""
>     size: 1G
>     storageclass: "csi-cinder-classic"
>     storagetype: dynamic
>     fsgroup: "26"
>   ccpimage: crunchy-postgres-ha
>   ccpimagetag: centos7-12.5-4.5.1
>   clustername: kratos
>   database: kratos
>   exporterport: '9187'
>   name: kratos
>   namespace: global-kratos-postgres
>   pgbadgerport: '10000'
>   port: '5432'
>   primarysecretname: kratos-primaryuser-secret
>   rootsecretname: kratos-postgres-secret
>   userlabels:
>     archive: 'false'
>   usersecretname: kratos-kratos-secret
> ```
> 
> > Please see:
> > [operator-framework/community-operators#3066](https://github.com/operator-framework/community-operators/pull/3066)
> > [operator-framework/community-operators#3067](https://github.com/operator-framework/community-operators/pull/3067)
> 
> Thanks I will have a look on that smile

Hi @lusu007, I think I have the exact same problem (same provider, same error), what was the fix, if any ?
