### ISSUE TITLE
Install on EKS cluster with no outbound internet access 

### ISSUE THREAD

**Issue by ntorba** [CrunchyData/postgres-operator#2233]
**Which example are you working with?**
https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/

**Question**
I'm currently working on an EKS cluster on a private network with no internet access. I was able to put the docker image for the pgo-deploy job on a dockerhub that the EKS has access to, but it looks like the pgo-deploy job itself also pulls more images from the crunchy data registry. 

Is there a good way to perform the install on a cluster with no outbound access? 

Thanks!

**Please tell us about your environment:**
AWS EKS v1.17

**Comment by jkatz** [comment]
Pre-load the images. There is a list of them here: [https://github.com/CrunchyData/postgres-operator/blob/master/installers/olm/postgresoperator.csv.images.yaml](https://github.com/CrunchyData/postgres-operator/blob/master/installers/olm/postgresoperator.csv.images.yaml) and within the docs. The docs also explain how the tags work, though I believe we can make that a bit clearer.

**Comment by ntorba** [comment]
@jkatz That's exactly the file I was hoping for, thanks!
