### ISSUE TITLE
delete backup is not working with Postgres Operator 4.3.0 and 4.5.1 version

### ISSUE THREAD

**Issue by rj9333** [CrunchyData/postgres-operator#2234]
Our environment: GKE Cluster
PGO version: 4.3.0 and 4.5.1 
We are trying to delete backup using 
pgo delete backup 20210127-084307F_20210127-085405I -n <namespace> 

Below is the output for this.
WARNING: Are you sure? (yes/no): y
DEBU[0001] deleteBackup called [20210127-084307F_20210127-085405I]

When we check back the backup using show backup command, still the backup exists, its not getting deleted. 

How can we delete the full and incremental backups separately.

**Comment by jkatz** [comment]
[Upgrade to 4.6.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.6.0):

> A pgBackRest backup can now be deleted with pgo delete backup. A backup name must be specified with the --target flag. Please refer to the documentation for how to use this command.

[https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/#deleting-a-backup](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/#deleting-a-backup)
