### ISSUE TITLE
Can we backup/restore postgres database from/to GCS buckets

### ISSUE THREAD

**Issue by rj9333** [CrunchyData/postgres-operator#2235]
We would like to copy the backup to GCS buckets as our PGO is deployed on GKE cluster. Its easy for us to store and retrieve regular backups from GCS bucket.

Is there anyway we can do this?

**Comment by jkatz** [comment]
pgBackRest does not have support for GCS, but GCS compatibility can be achieved using MinIO's gateway support. Please see #1791, #2012, and any issue that references using MinIO as a gateway.
