### ISSUE TITLE
When can we expect 4.6.0 postgres-operator, pgo-deployer, pgo-client images on Docker hub 

### ISSUE THREAD

**Issue by rj9333** [CrunchyData/postgres-operator#2236]
We want to pull latest images (4.6.0) for the postgres-operator, pgo-deployer and pgo-client images from Dockerhub( https://hub.docker.com/u/crunchydata)

Could you please let us know when can we expect them to use?

**Comment by jkatz** [comment]
The prelease process is detailed in the README](https://github.com/CrunchyData/postgres-operator#releases).

The images are already available in the Crunchy Data Customer Portal and [Developer Portal](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator).
