### ISSUE TITLE
Backrest Backup Job not use correct `backrest-shared-repo` POD Name

### ISSUE THREAD

**Issue by satriashp** [CrunchyData/postgres-operator#2237]
**Describe the bug**
Is there a default scheduled backup inside the cluster when cluster created?
Cause its look like doing full backup every two or three hours. And that backup job used old backrest-shared-repo POD NAME instead a new one.
When i check list of scheduled backup for the cluster, is empty.
```
pgo show schedule <CLUSTER_NAME>
```
Error log from Job tell that POD `cluste_name-backrest-shared-repo-xxx` no longger found.

But if i manually create backup or create a scheduled backup, the backup job succeed.
`pgo backup hacluster --backup-opts="--type=full"`
```
pgo create schedule hacluster --schedule="*/5 * * * *" \
--schedule-type=pgbackrest  --pgbackrest-backup-type=full
```
**To Reproduce**
1. Rolling update or delete backrest-shared-repo
2. See automatic Backup job, its should fail.

**Expected behavior**
Backup Job use new POD name.

* Operating System:
* Where is this running ( Local, Cloud Provider): AWS 
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version: 11.10
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.15.7

**Additional context**
I already ask the same question [here](https://github.com/CrunchyData/postgres-operator/issues/2192),

**Comment by jkatz** [comment]
> Is there a default scheduled backup inside the cluster when cluster created?

[There is an initial backup taken](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/provisioning/) but it is not added to a scheduled backup:

> Once the PostgreSQL primary instance is ready, there are two follow up actions that the PostgreSQL Operator takes to properly leverage the pgBackRest repository:
> 
> - A new pgBackRest stanza is created
> - An initial backup is taken to facilitate the creation of any new replica

I'm not entirely following the situation above. It sounds like you might have an artifact from a previous cluster? But it also sounds like you're deleting things independently of the Operator managing them, which can lead to bad results.

**Comment by satriashp** [comment]
This is screenshot from my postgres cluster. [screenshot](https://prnt.sc/xsgwis)
cluster name: staging
Cluster already created 14 Days ago. And this cluster not have any scheduled backup.

Error log from `backrest-backup-staging-k6zw9 ` POD:
```
time="2021-01-29T03:52:54Z" level=info msg="pgo-backrest starts"
time="2021-01-29T03:52:54Z" level=info msg="debug flag set to false"
time="2021-01-29T03:52:54Z" level=info msg="backrest backup command requested"
time="2021-01-29T03:52:54Z" level=info msg="command to execute is [pgbackrest backup --type=full --db-host=100.96.8.3 --db-path=/pgdata/staging]"
time="2021-01-29T03:52:54Z" level=info msg="command is pgbackrest backup --type=full --db-host=100.96.8.3 --db-path=/pgdata/staging "
time="2021-01-29T03:52:54Z" level=error msg="pods \"staging-backrest-shared-repo-6f94bcf795-9xtqk\" not found"
time="2021-01-29T03:52:54Z" level=info msg="output=[]"
time="2021-01-29T03:52:54Z" level=info msg="stderr=[]"
time="2021-01-29T03:52:54Z" level=error msg="pods \"staging-backrest-shared-repo-6f94bcf795-9xtqk\" not found"
```
Error message say pods `staging-backrest-shared-repo-6f94bcf795-9xtqk` not found.

**Comment by jkatz** [comment]
@satriashp What happens when you try to manually take a backup with `pgo backup`? Does that work?

Do there also happen to be any evicted Pods with the name `staging-backrest-shared-repo-6f94bcf795-9xtqk`?

Based on the answers to those questions I believe I have found some code that can be updated to handle this situation.

**Comment by jkatz** [comment]
I've proposed a solution for the issue based on what's described. The backup scheduler will only consider Pods that are in the `Running` phase when trying to create the backups.

This can be backpatched down to 4.4

**Comment by satriashp** [comment]
> @satriashp What happens when you try to manually take a backup with `pgo backup`? Does that work?
> 
> Do there also happen to be any evicted Pods with the name `staging-backrest-shared-repo-6f94bcf795-9xtqk`?
> 
> Based on the answers to those questions I believe I have found some code that can be updated to handle this situation.

Its working fine when i manually triggered backup. Thanks for your response @jkatz .
