### ISSUE TITLE
Add an option to add another postgres exporter for per-db metrics

### ISSUE THREAD

**Issue by ssiahetiong** [CrunchyData/postgres-operator#2247]
**What is the motivation or use case for the change? **
The exporter sidecar container has a limitation to scrape per-db metrics for **multiple** databases. The standalone pgmonitor setup recommends separation of cluster level and per-db level metrics. See:
https://github.com/CrunchyData/pgmonitor/blob/853afdfc7d7b59a38e4fd20da7bdc058217be5ef/exporter/postgres/sysconfig.postgres_exporter_pg13#L16

**Describe the solution you'd like**
Add new flag "--enable-metrics-db=db1,db2...dbN". This will launch a new exporter container inside the pod for handling per-db metrics.

**Comment by jkatz** [comment]
I'm not sure I see the need for this? The integration that's set up in the [monitoring stack](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/) already breaks out the metrics on a per database basis.

**Comment by ssiahetiong** [comment]
The metrics: ccp_stat_user_tables and ccp_table_size [https://github.com/CrunchyData/pgmonitor/blob/master/exporter/postgres/queries_per_db.yml] are only scrape for a particular database defined in EXPORTER_PG_DATABASE (defaults to postgres). If you have a single database in the cluster, it can be changed accordingly, but with multiple databases, there is a need to separate the cluster level vs the per-db level, since if you define multiple database and combine cluster and per-db level metric, there will be a lot of conflicts [https://github.com/CrunchyData/pgmonitor/blob/853afdfc7d7b59a38e4fd20da7bdc058217be5ef/exporter/postgres/sysconfig.postgres_exporter_pg13_per_db#L14]. For the per-db level, multiple databases can be defined using DATA_SOURCE_NAME [https://github.com/wrouesnel/postgres_exporter/issues/224]

**Comment by ssiahetiong** [comment]
To replicate this problem, create a cluster with multiple databases. On grafana, import dashboard for https://github.com/CrunchyData/pgmonitor/blob/master/grafana/TableSize_Details.json and https://github.com/CrunchyData/pgmonitor/blob/master/grafana/CRUD_Details.json. Notice only the postgres dbname metrics are scraped.

**Comment by rreckel** [comment]
It would also be nice, if one could change the default EXPORTER_PG_DATABASE in the pgcluster definition. Very often one wants to scrap the ccp_stat_user_tables of the "main user" database and not the postgres database.
Whould that be possible?
I think, that adding a new "ExporterDbName" value in the pgcluster definition and changing the exporter.json accordingly would be enough?

**Comment by jkatz** [comment]
> It would also be nice, if one could change the default EXPORTER_PG_DATABASE in the pgcluster definition. Very often one wants to scrap the ccp_stat_user_tables of the "main user" database and not the postgres database.
Whould that be possible?

Maybe I'm not following, but the exporter already scrapes data from all databases and you are able to view them individual. For example, using the visualizations in the upcoming 4.7 release, here are queries that I ran solely on the `hippo` database within my cluster.

<img width="1573" alt="Screen Shot 2021-05-07 at 8 58 16 AM" src="https://user-images.githubusercontent.com/1694/117453039-7872e580-af12-11eb-9bef-e13db06aafbe.png">

I also ran queries against the `postgres` database and they did not show up in this view.

**Comment by jkatz** [comment]
And actually, reviewing the original context for this issue, I believe this is resolved for 4.7.

**Comment by rreckel** [comment]
Ok, Sorry. I changed my panel in Grafana to not use cpp_stat_user_tables_* anymore.
But it would have been a nice to have. As mentioned by @ssiahetiong I will change the deployment to set the EXPORTER_PG_DATABASE.

Thanks for the explanations.
