### ISSUE TITLE
Add Support for Node Affinity + Tolerations for pgBouncer

### ISSUE THREAD

**Issue by rj9333** [CrunchyData/postgres-operator#2252]
We have deployed Postgres operator 4.6.0 version in GKE cluster in default node pool and trying to deploy postgres hippo cluster in a dedicated node pool using node-affinity and toleration options. 

We could see below hippo cluster components created in the dedicated node pool but hippo pgbouncer is not creating in dedicated pool, it is taking default node instead. 

```
NAME                                                       READY       STATUS                                 NODE
backrest-backup-hippo-xfclr                              0/1            Completed           gke-pgo-operator-pool-a-a33c1cf5-p4p0   
hippo-6d6d7ccfb6-4fsqz                                       1/1         Running                gke-pgo-operator-pool-a-98227e12-cvp0   
hippo-backrest-shared-repo-665f744f69-4878s   1/1         Running                  gke-pgo-operator-pool-a-a33c1cf5-p4p0   
hippo-dpuv-6c64b45d6-54p7v                              1/1        Running                  gke-pgo-operator-pool-a-373201ac-9ktu   
hippo-pgbouncer-68bbb59965-wnhdg                 1/1        Running                  gke-gke1-pool-n1-s64-a-v1-7043b845-8mk9      
hippo-rhqk-c466c4bc5-7sgmj                                1/1        Running                  gke-pgo-operator-pool-a-a33c1cf5-p4p0   
hippo-stanza-create-r49nt                                      0/1       Completed              gke-pgo-operator-pool-a-a33c1cf5-p4p0 
```  

How can we create hippo pgbouncer in the dedicated node pool?
BTW, we used below command to create cluster in a dedicated node pool. 

create cluster hippo --pgbouncer --replica-count=2 --node-label=node_pool=gke-pgo-operator-pool-a --node-affinity-type=required --toleration=dedicated=gke-operator

**Comment by jkatz** [comment]
This is a feature request. Tolerations & node affinity are currently not supported on pgBouncer, nor does the make any allusions to that. You can choose to manually employ them either by modifying the pgBouncer template.

**Comment by rj9333** [comment]
Thanks for the update @jkatz .
When can we expect this release?

**Comment by jkatz** [comment]
You can read information about how releases work here:

- [https://github.com/CrunchyData/postgres-operator#releases](https://github.com/CrunchyData/postgres-operator#releases)

or look through the release notes to get a sense of the release cadence for feature releases: [https://access.crunchydata.com/documentation/postgres-operator/latest/releases/](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/)

You can also request more information via the provided [support resources](https://access.crunchydata.com/documentation/postgres-operator/latest/support/).

**Comment by jkatz** [comment]
PGO 5.0 added support for this: [https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/connection-pooling/](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/connection-pooling/)
