### ISSUE TITLE
--node-label and --node-affinity-type for pgo update cluster command

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2253]
Hi There,

We could not see any documentation for --node-label and --node-affinity-type for pgo update cluster command. We are using tolerations to get this done for our existing cluster. we want the cluster to be in a particular node pool and it dose not have a unique tolerations value. What would you suggest?

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: 4.6.0
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
You can find out more information via [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/).
