### ISSUE TITLE
pgo-client pod throwing error for show backup command with all the db pods are up

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2254]
Hi,

When i try to exec into pgo-client pod and execute below command we are getting error. 

bash-4.2$ pgo --namespace=sedstarmidas-dev-rats-prod-rescan-db show backup rats-rescan-database
Error: primary pod is not in Ready state

Is this a known issue? 

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: 4.3.0
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
4.3.0 is no longer supported.
