### ISSUE TITLE
huge pgadmin pv

### ISSUE THREAD

**Issue by Remp69** [CrunchyData/postgres-operator#2255]
**Describe the bug**
pgadmin is created with a pv size identical to pgsql pv size.

**To Reproduce**
1. create a cluster named "dev" with --pvc-size=80Gi --wal-storage-size 40Gi --pgbackrest-pvc-size 80Gi
2. add pgadmin : pgo create pgadmin dev
3. Show pvc
> kubectl get pvc |grep dev
dev                      Bound    pvc-7be57bc8-19cc-4ce1-b29b-68ca83ed7a27   **80Gi**       RWO            sc-pgaas       23h
dev-pgadmin              Bound    pvc-ac2c8f62-eca8-4e28-a1e2-2f8060e1bd74   **80Gi**       RWO            sc-pgaas       23h
dev-pgbr-repo            Bound    pvc-c44f77ed-2990-4c2b-9155-234b3d836a66   80Gi       RWO            sc-pgaas       23h
dev-wal                  Bound    pvc-81336d06-4ad2-4602-a203-aa4630f22650   40Gi       RWO            sc-pgaas       23h
4. See pvc size

**Expected behavior**
A pvc size parameter for pgadmin ?

**Please tell us about your environment:**

* Operating System: RHEL 7.3
* Where is this running ( Local, Cloud Provider) : local
* Storage being used (NFS, Hostpath, Gluster, etc): SAN with Hitachi CSI
* Container Image Tag: centos7-13.1-4.5.1
* PostgreSQL Version: 13.1
* Platform (Docker, Kubernetes, OpenShift): kubernetes 
* Platform Version: 1.18

**Comment by jkatz** [comment]
Please see #1795
