### ISSUE TITLE
Postgres operator 3.0 setup fails with CrashLoopBackOff - k8s 1.10.2

### ISSUE THREAD

**Issue by ieugen** [CrunchyData/postgres-operator#226]
Hello, 

I've installed postgresql operator on my bare-metal cluster setup with kubeadm. 
I've installed postgres-operator with helm: 

1. cloned the repository 5779fd9e2d83d6c16d80f66b3190996670bd6dad
2. installed via helm chart https://crunchydata.github.io/postgres-operator/installation/helm-chart/  . I used the command from the chart README.md: `helm install --name postgres-operator --namespace=postgres-operator postgres-operator` 
3. manually installed missing crd resources with `kubectl creat -f $project/deploy/crd.yaml` as operator container was failing but I got into another issue. 

Checking the status yields:
````
postgres-operator   postgres-operator-788d674444-z8b4s         1/2       CrashLoopBackOff
````

The issue is with "operator" container: 

````
time="2018-05-20T21:40:34Z" level=debug msg="debug flag set to true"
time="2018-05-20T21:40:34Z" level=debug msg="setting NAMESPACE to postgres-operator"
time="2018-05-20T21:40:34Z" level=debug msg="CCP_IMAGE_PREFIX set, using crunchydata"
time="2018-05-20T21:40:34Z" level=debug msg="CO_IMAGE_PREFIX set, using crunchydata"
at end of setup, beginning wait...Watch Pgbackup objects
Watch Pgingestcluster objects
Watch Pgreplica objects
Watch Pgcluster objects
Watch Pgupgrade objects
time="2018-05-20T21:40:34Z" level=info msg="Watch pod objects"
time="2018-05-20T21:40:34Z" level=info msg="Watch job objects"
time="2018-05-20T21:40:34Z" level=info msg="Watch Pgtask objects"
Watch Pgpolicy objects
time="2018-05-20T21:40:34Z" level=info msg="MajorUpgradeProcess watch starting..."
E0520 21:40:35.744735       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/podcontroller.go:76: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:postgres-operator:default" cannot list pods in the namespace "postgres-operator"
time="2018-05-20T21:40:36Z" level=error msg="error watching upgrade jobunknown (get jobs.batch)"
````

**Comment by jmccormick2001** [comment]
yep, check the deploy.sh script and notice the rbac.yaml and other security related files that need to be loaded...those might have been missed by the current helm chart deployment method.

**Comment by jmccormick2001** [comment]
Thanks...if CO_NAMESPACE environment var is not set to the right namespace
it can mess up rbac

**Comment by blaggacao** [comment]
Seems we are just on the same issue :smile: https://github.com/CrunchyData/postgres-operator/issues/219#issuecomment-390526174

**Comment by ieugen** [comment]
Merge in #219 . Same issues as there.
