### ISSUE TITLE
Helm Chart Example Upgrade for HA

### ISSUE THREAD

**Issue by AdrianXIA** [CrunchyData/postgres-operator#2260]
** Which example are you working with? **
  I use the helm charts from master (4.6.0), for deploying the operator and cluster.

**What is the current behavior?**
   Updating the number of replicas (HA=true) using helm upgrade command, there is no a really update.
   I see a change for property "replicas" in the Pgcluster kind but I do not see any change to number of pods/deployments.
   Also, if you manually delete a deployment for a replica, there is no action from operator.

   Using the pgo client as described in documentation works as expected for scaling in and scalling out.

**What is the expected behavior?**
   I expect the operator to creates/destroys automatically replicas.

**Please tell us about your environment:**

* Operating System: Linux
* Where is this running ( Local , Cloud Provider): AWS
* Storage being used (NFS, Hostpath, Gluster, etc): -
* Container Image Tag: centos8-13.1-4.6.0
* PostgreSQL Version:  -
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.6.15

**Comment by jkatz** [comment]
Thanks, I've logged this as an enhancement we can make to the Helm example. Contributions are of course welcomed.

> I expect the operator to creates/destroys automatically replicas.

Beyond Helm, there are many ways this can be handled:

- [Scaling via Custom Resources](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/#scale)
- [Scaling via CLI](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/high-availability/)

**Comment by benjaminjb** [comment]
Hi @AdrianXIA, I just wanted to double-check that you're still using PGO v4 and still running into this issue?

**Comment by AdrianXIA** [comment]
Hello @benjaminjb I am using version: 5.2.0. I didn't check if the issue is still present. I use a constant no of replicas.

**Comment by benjaminjb** [comment]
Hmmm, OK, sounds like we can close this ticket for now, so I'll go ahead with that, and if you have any problems with 5.2.0, please open a ticket. (For fun, I just tried to use our v5 Helm chart to see if I could change the number of replicas in a cluster, and it seemed to work, so that's another positive for v5.)
