### ISSUE TITLE
Operator Rest-Api

### ISSUE THREAD

**Issue by Schmaetz92** [CrunchyData/postgres-operator#2261]
**I'm submitting a Bug**

 
 - [x] bug report
 - [ ] feature request
 - [ ] support request

**What is the current behavior?**
The Rest-Api in V 4.6.0 seems to be partly buggy.
The following functions do not work as expected: 
- create cluster: no error, no reaction
- create label -> selector not working -> no cluster found (also in v 4.5.1) 

**If the current behavior is a bug, please provide the steps to reproduce:**
Upgrade operator from 4.5.1 to 4.6.0 and create a cluster via Rest-Api (direct via script not via pgo client)

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)
With version 4.5.1, the creation of clusters was possible without any problems. The creation of labels by means of a selector did not work there.

Other functions work under the operator 4.6.0 (Rest-API)
For example: 
show all cluster (working)
show one cluster via clustername (working)
show one cluster via selector=name=... (working)

**Please tell us about your environment:**

 - Operating System: redhat linux
 - Container Image Tag: all
 - Operator Version: 4.6.0
 - PostgreSQL Version: all
 - Platform (Docker, Kubernetes, OpenShift): Openshift 
 - Platform Version: 4.6.13

**Comment by jkatz** [comment]
There's too little information here to determine if there is actually a problem. However, if it's similar to #2262, please see #2262 which has a full reproducible bug report.
