### ISSUE TITLE
Any way to apply custom labels that are applied to all resources managed by pgo?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2267]
**What is the motivation or use case for the feature?**
Currently, if a custom label is set during cluster creation (_pgo create cluster -l_), it is applied only to  _pgcluster_ CR and _pods_. 
These custom labels are not set to other k8s resources (_svc_, _pvc_, ....)

**Describe the solution you'd like**
The custom labels should be applied to all k8s resources

**Please tell us about your environment:**
pgo 4.5.1
k8s: 1.17.13

Thanks,
José

**Comment by jkatz** [comment]
@jose-joye This would be new work -- noting this as an enhancement request.

**Comment by jose-joye** [comment]
Hello @jkatz,
Actually, our use case is related to _prometheus Operator_ together with _ServiceMonitor_ and _Prometheusrules_ CRDs.

Our services, that are monitored, have attached to each resource (deployment, pod, CR, pvc, ...) a dedicated label (eg: _servicename: kafka_). This allows an easy discovery of resources pro kind of service we expose.

For pgo, it would be nice to propagate the label, we apply to a cluster, to all resources related to that cluster. 
If I'm correct, at the moment, only the pgcluster CR and  new pods are labeled with the provided custom labels.

Currently, our use case would be fulfilled with the following:
- define in the installer/ansible/value.yaml, a set of labels to be applied to all cluster resources when a cluster is created (in fact, you do this consistently with the _vendor=crunchy_ label).
- redeploy pgo

Allowing to provide custom labels at cluster creation or even updating labels on running cluster (and propagating to all resources) is a nice to have feature in our case. 

Thanks a lot,
José

**Comment by douggutaby** [comment]
+1
I need this feature for the same reason (prometheus+servicemonitor). I tried  pgo label but it creates label to the deployments not for the services

**Comment by jkatz** [comment]
If there is consistency across the labels, you can presently modify the template files in `pgo-config` to add labels to various objects.

**Comment by benjaminjb** [comment]
@douggutaby is this still an ongoing need and are you still using PGO v4?

**Comment by douggutaby** [comment]
We are still using v4, I hope we will upgrade to 5 next year, because the last few upgrade from v4 didn't work.
I use what jkatz suggested and set custom label in pgo-config.

**Comment by benjaminjb** [comment]
OK, sounds like this issue is done then, so I'll close it, but if you run into problems migrating from v4 to v5, that might be worth opening another ticket (unless there's already one opened for that topic).
