### ISSUE TITLE
4.6.0 upgrade fails using pgo upgrade command 

### ISSUE THREAD

**Issue by rj9333** [CrunchyData/postgres-operator#2270]
Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC
Container Image Tag: 4.6.0
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

We are following below reference to upgrade hippo cluster 
https://access.crunchydata.com/documentation/postgres-operator/4.6.0/pgo-client/reference/pgo_upgrade/

When we run `upgrade cluster hippo --no-prompt- debug --ignore-validation` its terminating hippo cluster primary, replicas and other components like backrest-backup-hippo, pghippo-backrest-shared-repo and hippo-pgbouncer but not re-creating them. 

It only creates hippo pgcluster and when we run `describe pgcluster hippo` it shows below
```
Name:         hippo
Namespace:    abcd
Labels:       crunchy-pgha-scope=hippo
              deployment-name=hippo
              name=hippo
              pg-cluster=hippo
              pg-pod-anti-affinity=
              pgo-backrest=true
              **pgo-version=4.6.0**
              pgouser=admin
              workflowid=27511026-ea55-4785-a04a-8f4315e4382c
Annotations:  current-primary: hippo
              **is-upgraded: true**
              primary-deployment: hippo
              **upgrade-in-progress: true**
              upgrade-info: From_4.5.1_to_4.6.0
API Version:  crunchydata.com/v1
Kind:         Pgcluster

```

But its not working and we see below errors in operator pod 
time="2021-02-10T06:54:15Z" level=error msg="ERROR onAdd getting pgtask : pgtasks.crunchydata.com \"backrest-backup-hippo\" not found" func="internal/controller/pgtask.(*Controller).processNextItem()" file="internal/controller/pgtask/pgtaskcontroller.go:92" version=4.6.0

we found 4.5.1 images in https://hub.docker.com/r/crunchydata/pgo-backrest/tags?page=1&ordering=last_updated 
but not able to see 4.6.1 images for crunchydata/pgo-backrest,  crunchydata/pgo-backrest-repo, crunchydata/pgo-backrest-restore, crunchydata/pgo-backrest-repo-sync

Could you please let me know if that is the reason for not recreating hippo cluster components

**Comment by jkatz** [comment]
There were changes made to the images, which are described in detail in the [4.6.0 release notes](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.6.0/).

Beyond that, the logs you've shared don't seem to indicate any errors that are occurring with the upgrade. There are a few known issues that will be resolved in 4.6.1 (#2250, #2264), but I don't see anything to indicate in the above that you have hit them.
