### ISSUE TITLE
postgres db versions supported by operator v4.6.0

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2271]
Hi There,

What are the postgres db versions that operator v4.6.0 supports, and is 12.5 part of it?

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: 4.6.0
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
[This is documented](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/).
