### ISSUE TITLE
Backups fail after a failover

### ISSUE THREAD

**Issue by mesobreira** [CrunchyData/postgres-operator#2272]
**Describe the bug**
Backups only works when the primary node is the original/first pod created.
When we do a failover, the backup fails with the following error: "primary pod is not in Ready state"
Is this a normal message ? Do we need to reconfigure backups after a failover ?

**To Reproduce** 
1 - Initial Situation:
mes@ucrunchy01$ pgo -n pgo test raid20

cluster : raid20
        Services
                primary (10.100.224.177:5432): UP
                replica (10.102.38.56:5432): UP
        Instances
                primary (raid20-57856d96f-znz72): UP
                replica (raid20-hllg-6b5f8557cc-9qzwt): UP

2 - Launch a backup job (it works fine)
mes@ucrunchy01:~/crunchydata01/crunchy02$ pgo -n pgo backup raid20 --backup-opts="--type=full"

created Pgtask backrest-backup-raid20

3 - Perform a Manual failover
mes@ucrunchy01$ pgo -n pgo failover raid20
WARNING: Are you sure? (yes/no): yes

failover success for cluster raid20

4 - The failover was well succeded 
mes@ucrunchy01$ pgo -n pgo test raid20

cluster : raid20
        Services
                primary (10.100.224.177:5432): UP
                replica (10.102.38.56:5432): UP
        Instances
                replica (raid20-57856d96f-znz72): UP
                primary (raid20-hllg-6b5f8557cc-9qzwt): UP

5- Launch a new Backup after the failover
mes@ucrunchy01$ pgo -n pgo backup raid20 --backup-opts="--type=full"

Error: primary pod is not in Ready state

**Please tell us about your environment:**

Operating System: Ubuntu
Where is this running ( Local , Cloud Provider): Local
Storage being used (NFS, Hostpath, Gluster, etc): HostPath
Container Image Tag: centos8-13.1-4.6.0
PostgreSQL Version: 13
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 4.6.0

**Additional Notes:**
If we do a failback, the backups works again.

**Comment by jkatz** [comment]
By default, a backup is taken after a failover.

However, I did reproduce this exact issue and looks like it's a trivial fix. Thanks for reporting!

**Comment by jkatz** [comment]
This fix is applied and backpatched down to 4.4. Thanks again for reporting!
