### ISSUE TITLE
Cannot deploy a postgres cluster with version 12.5 

### ISSUE THREAD

**Issue by mesobreira** [CrunchyData/postgres-operator#2273]
** Which example are you working with? **
We want to use the version 12.5 of postgres.

**What is the current behavior?**
We change the CCPImageTag in pgo.yaml
CCPImageTag:  centos7-12.5-4.4.2

When we launch a cluster creation with pgo command, we have the following error during the deployment:

  Normal   Pulling    14s (x2 over 30s)  kubelet            Pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos7-12.5-4.4.2"
  Warning  Failed     11s (x2 over 26s)  kubelet            Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos7-12.5-4.4.2": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos7-12.5-4.4.2 not found: manifest unknown: manifest unknown
  Warning  Failed     11s (x2 over 26s)  kubelet            Error: ErrImagePull

**Other information** (e.g. detailed explanation, related issues,  etc)
 We checked your docker repo and in fact there is only the version centos8-13.1-4.6.0 available.
 Do we need to change or downgrade something more ?

**Please tell us about your environment:**
Operating System: Ubuntu
Where is this running ( Local , Cloud Provider): Local
Storage being used (NFS, Hostpath, Gluster, etc): HostPath
Container Image Tag: centos7-12.5-4.4.2
PostgreSQL Version: 12.5
Platform (Docker, Kubernetes, OpenShift): Kubernets
Platform Version: 4.6.0

**Comment by jkatz** [comment]
You can browse the publicly available images in the [Crunchy Data Developer Portal](https://www.crunchydata.com/developers/download-postgres/containers). The full set of images are available in the subscriber portal.
