### ISSUE TITLE
pgo schedule issues.

### ISSUE THREAD

**Issue by DinshKW44** [CrunchyData/postgres-operator#2275]
**I'm submitting a issue that I am facing**

 
 - [ ] bug report
 - [ ] feature request
 - [ X] support request

**Do you want to request a *feature* or report a *bug*?**
This is an issue I am facing. Mostly a bug.

**What is the current behavior?**
version: 4.5.0
I create a schedule with the below command:

pgo create schedule  $clusterName -n $namespace --schedule="* */3 * * *" \
  --schedule-type=pgbackrest  --pgbackrest-backup-type=full --pgbackrest-storage-type=local,s3 \
  --schedule-opts="--repo1-retention-full=3"

It creates a schedule and run the full-schedule backup but it always fails. It automatically taking the below command:
command is pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=10.233.69.195 --db-path=/pgdata/testcluster2-7 && pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=10.233.69.195 --db-path=/pgdata/testcluster2-7 --repo1-type=s3 --no-repo1-s3-verify-tls

I am expecting it should not take "--no-repo1-s3-verify-tls" as it is trying to connect to 443 port. When I create a backup using pgo backup command it works without issues and it does not take --no-repo1-s3-verify-tls.

pgo4.5 backup  $clusterName -n $namespace --backup-type=pgbackrest --backup-opts="--type=full" --pgbackrest-storage-type=s3

**If the current behavior is a bug, please provide the steps to reproduce:**
Have a cluster deployed with s3 connectivity. Once the cluster is create a pgo schedule with the below command:
pgo4.5

pgo create schedule  $clusterName -n $namespace --schedule="* */3 * * *" \
  --schedule-type=pgbackrest  --pgbackrest-backup-type=full --pgbackrest-storage-type=local,s3 \
  --schedule-opts="--repo1-retention-full=3"

**when create backup using pgo backup, the pgtask looks as below:apiVersion: crunchydata.com/v1**
kind: Pgtask
metadata:
  creationTimestamp: "2021-02-11T00:33:22Z"
  generation: 2
  labels:
    pg-cluster: testcluster2-7
    pg-cluster-id: ""
    pgouser: admin
  name: backrest-backup-testcluster2-7
  namespace: test-pgo-7
  resourceVersion: "696944095"
  selfLink: /apis/crunchydata.com/v1/namespaces/test-pgo-7/pgtasks/backrest-backup-testcluster2-7
  uid: 8a593b79-b877-44a3-b3dc-3635c02eae9a
spec:
  name: backrest-backup-testcluster2-7
  namespace: test-pgo-7
  parameters:
    backrest-command: backup
    backrest-opts: --type=full
    **backrest-s3-verify-tls: "true"**
    backrest-storage-type: s3
    containername: database
    image-prefix: registry.developers.crunchydata.com/crunchydata
    job-name: backrest-backup-testcluster2-7
    pg-cluster: testcluster2-7
    podname: testcluster2-7-backrest-shared-repo-b978f4cd7-mbpkd
  status: ""
  storagespec:
    accessmode: ""
    matchLabels: ""
    name: ""
    size: ""
    storageclass: ""
    storagetype: ""
    supplementalgroups: ""
  tasktype: backrest
status:
  message: Successfully processed Pgtask by controller
  state: pgtask Processed

**But when creating pgo schedule, the pgtask does not have "backrest-s3-verify-tls: "true"".** 
apiVersion: crunchydata.com/v1
kind: Pgtask
metadata:
  creationTimestamp: "2021-02-11T00:21:00Z"
  generation: 2
  name: testcluster2-7-full-sch-backup
  namespace: test-pgo-7
  resourceVersion: "696923136"
  selfLink: /apis/crunchydata.com/v1/namespaces/test-pgo-7/pgtasks/testcluster2-7-full-sch-backup
  uid: 943a7270-c15b-4c67-a63c-94c707247f80
spec:
  name: testcluster2-7-full-sch-backup
  namespace: ""
  parameters:
    backrest-command: backup
    backrest-opts: --stanza=db --type=full --repo1-retention-full=2 
    backrest-storage-type: s3
    containername: database
    image-prefix: registry.developers.crunchydata.com/crunchydata
    job-name: testcluster2-7-full-sch-backup
    pg-cluster: testcluster2-7
    podname: testcluster2-7-backrest-shared-repo-b978f4cd7-mbpkd
  status: ""
  storagespec:
    accessmode: ""
    matchLabels: ""
    name: ""
    size: ""
    storageclass: ""
    storagetype: ""
    supplementalgroups: ""
  tasktype: backrest
status:
  message: Successfully processed Pgtask by controller
  state: pgtask Processed
**What is the expected behavior?**

pgbackrest running backup successfully when using pgo schedule

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System: Centos
 - Container Image Tag: registry.developers.crunchydata.com/crunchydata
 - Operator Version: 7
 - Storage (NFS, hostpath, storage class): rbd-ceph
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift): Kubernetes
 - Platform Version: 1.16.3

**Comment by jkatz** [comment]
Are there any logs from the Job? Did you update the `BackrestS3VerifyTLS` to be `false`?

**Comment by DinshKW44** [comment]
I could not find "BackrestS3VerifyTLS" option in the operator manifest file and it  was found in the https://github.com/CrunchyData/postgres-operator/blob/v4.5.0/conf/postgres-operator/pgo.yaml.

I deployed operator using https://github.com/CrunchyData/postgres-operator/blob/v4.5.0/installers/kubectl/postgres-operator.yml file which has the option backrest_aws_s3_verify_tls: "true"

I created schedule using the command:
```
pgo4.5 create schedule  testcluster2-7 -n test-pgo-7 --schedule="*/5 * * * *" \
  --schedule-type=pgbackrest  --pgbackrest-backup-type=full --pgbackrest-storage-type=s3 \
  --schedule-opts="--repo1-retention-full=3"
```


```
kubectl logs testcluster2-7-full-sch-backup-gtn8s
time="2021-02-17T00:25:05Z" level=info msg="pgo-backrest starts"
time="2021-02-17T00:25:05Z" level=info msg="debug flag set to false"
time="2021-02-17T00:25:05Z" level=info msg="backrest backup command requested"
time="2021-02-17T00:25:05Z" level=info msg="s3 flag enabled for backrest command"
time="2021-02-17T00:25:05Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=10.233.69.195 --db-path=/pgdata/testcluster2-7 --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2021-02-17T00:25:05Z" level=info msg="command is pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=10.233.69.195 --db-path=/pgdata/testcluster2-7 --repo1-type=s3 --no-repo1-s3-verify-tls "
time="2021-02-17T00:28:32Z" level=error msg="command terminated with exit code 42"
time="2021-02-17T00:28:32Z" level=info msg="output=[]"
time="2021-02-17T00:28:32Z" level=info msg="stderr=[ERROR: [042]: timeout after 60000ms waiting for read from 'pgo_test_k1d.s3.ceph.cin.kore.korewireless.com:443'\n]"
time="2021-02-17T00:28:32Z" level=error msg="command terminated with exit code 42"
```

**Comment by DinshKW44** [comment]
As a test in regards to pgo schedule, I created two clusters with `backrestS3VerifyTLS: "false"` . One cluster uses ceph s3 backend and the other uses aws s3 backend. 
The initial backup gets created without issues and could see the pgo backup in the s3 storage (both aws s3 and ceph s3). 
When I create a scheduler for both the clusters using the command below:

```
pgo4.5 create schedule testcluster2-7-1 -n test-pgo-8 --schedule="* */2 * * *" \
  --schedule-type=pgbackrest  --pgbackrest-backup-type=full --pgbackrest-storage-type=s3 \
  --schedule-opts="--repo1-retention-full=3"


pgo4.5 create schedule testcluster2-9 -n test-pgo-9 --schedule="* */6 * * *" \
  --schedule-type=pgbackrest  --pgbackrest-backup-type=full --pgbackrest-storage-type=s3 \
  --schedule-opts="--repo1-retention-full=3"

```

Both the pgo clusters throw the below error:

```
k -n test-pgo-8 logs testcluster2-7-1-full-sch-backup-jbj7z
time="2021-02-17T14:16:27Z" level=info msg="pgo-backrest starts"
time="2021-02-17T14:16:27Z" level=info msg="debug flag set to false"
time="2021-02-17T14:16:27Z" level=info msg="backrest backup command requested"
time="2021-02-17T14:16:27Z" level=info msg="s3 flag enabled for backrest command"
time="2021-02-17T14:16:27Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=10.233.77.57 --db-path=/pgdata/testcluster2-7-1 --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2021-02-17T14:16:27Z" level=info msg="command is pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=10.233.77.57 --db-path=/pgdata/testcluster2-7-1 --repo1-type=s3 --no-repo1-s3-verify-tls "
time="2021-02-17T14:16:27Z" level=error msg="command terminated with exit code 50"
time="2021-02-17T14:16:27Z" level=info msg="output=[]"
time="2021-02-17T14:16:27Z" level=info msg="stderr=[ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-backup.lock': Resource temporarily unavailable\n       HINT: is another pgBackRest process running?\n]"
time="2021-02-17T14:16:27Z" level=error msg="command terminated with exit code 50"

k -n test-pgo-9 logs testcluster2-9-full-sch-backup-2x6s9
time="2021-02-17T12:59:35Z" level=info msg="pgo-backrest starts"
time="2021-02-17T12:59:35Z" level=info msg="debug flag set to false"
time="2021-02-17T12:59:35Z" level=info msg="backrest backup command requested"
time="2021-02-17T12:59:35Z" level=info msg="s3 flag enabled for backrest command"
time="2021-02-17T12:59:35Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=10.233.71.113 --db-path=/pgdata/testcluster2-9 --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2021-02-17T12:59:35Z" level=info msg="command is pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=10.233.71.113 --db-path=/pgdata/testcluster2-9 --repo1-type=s3 --no-repo1-s3-verify-tls "
time="2021-02-17T12:59:35Z" level=error msg="command terminated with exit code 50"
time="2021-02-17T12:59:35Z" level=info msg="output=[]"
time="2021-02-17T12:59:35Z" level=info msg="stderr=[ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-backup.lock': Resource temporarily unavailable\n       HINT: is another pgBackRest process running?\n]"
time="2021-02-17T12:59:35Z" level=error msg="command terminated with exit code 50"
```

Even when not using verify-tls, I am running into the lock issue. When the schedule was created, I had no other backup process running.

**Comment by clementnero** [comment]
Hello,

I have made the same observation. The S3 parameters as `BackrestS3VerifyTLS ` are never read from the associated Pgcluster resource nor used to generate the Pgtask resource.

Moreover, the relevant code has not been modified for more than two years -> https://github.com/CrunchyData/postgres-operator/blob/v4.7.1/cmd/pgo-scheduler/scheduler/tasks.go#L37-L57

@jkatz  I think that this question should be reopened and requalified as a bug.

Thx for the amazing job.
