### ISSUE TITLE
S3 > Storage type 'local' not allowed

### ISSUE THREAD

**Issue by JanCizmar** [CrunchyData/postgres-operator#2276]
** Which example are you working with? **
https://access.crunchydata.com/documentation/postgres-operator/4.5.1/pgo-client/reference/pgo_create_cluster/

**What is the current behavior?**
When i create cluster with this command:

    pgo create cluster --restore-from hippo --pgbackrest-s3-uri-style=host
    --pgbackrest-s3-bucket database-backups --pgbackrest-s3-endpoint linodeobjects.com
    --pgbackrest-s3-region eu-central-1
    --pgbackrest-s3-key xxx --pgbackrest-s3-key-secret xxx
    --pgbackrest-storage-type=s3 --pvc-size 50G --memory 1520M
    --cpu 600m --metrics --pgbackrest-s3-verify-tls=false hello

And run `pgo backup hello` I am getting this message: 

    Error: Storage type 'local' not allowed. Local storage is not enabled for pgBackRest
    in this cluster. If this cluster uses S3 storage only, specify 's3' for the pgBackRest storage type.

**What is the expected behavior?**
It backups to configured S3 bucket.

**Other information** (e.g. detailed explanation, related issues,  etc)
I am not sure if this is a bug, but the error message is probably wrong, because as you can see pgBackRest storeage type is specified properly.

**Please tell us about your environment:**

* Where is this running ( Local , Cloud Provider)
Linode LKE

Is there any way how to test or debug my S3 configuration?

**Comment by jkatz** [comment]
- Are you restoring the cluster from local repo or s3?
- What does `pgo show backup hello` output?
- What happens when you try `pgo backup hello --pgbackrest-storage-type=s3`?

**Comment by JanCizmar** [comment]
Hello,
Running command `pgo backup hello --pgbackrest-storage-type=s3` solved the issue! Thanks.

The logs of the backup pod showed that it failed to validate the TLS certificate so creating cluster with `--pgbackrest-s3-verify-tls=false` solved another issue and now it works fine.

**Comment by JanCizmar** [comment]
Also, I would like to ask if there is any way how to change the S3 configuration after the cluster is created.

**Comment by jkatz** [comment]
Glad it's working.
