### ISSUE TITLE
olm postgres operator on operatorhub.io not up to date

### ISSUE THREAD

**Issue by offlinehacker** [CrunchyData/postgres-operator#2279]
**Describe the bug**

CrunchyData postgres operator published on operatorhub.io managed by operator lifecycle manager is not up to date https://operatorhub.io/operator/postgresql. The latest published version is 4.5.1, but the latest release is already 4.6.0.

**To Reproduce**
1. Go to 'https://access.crunchydata.com/documentation/postgres-operator/4.6.0/installation/other/operator-hub/'
2. Try to follow instructions to install operator using olm.
3. Installation fails, as there is no operator with version 4.6.0 published on operatorhub (https://operatorhub.io/operator/postgresql/stable/postgresoperator.v4.6.0).

**Expected behavior**
There is operator with version 4.6.0 published on operator hub.

**Please tell us about your environment:**

* Operating System: Linux
* Where is this running: Locally using k3s
* Storage being used (NFS, Hostpath, Gluster, etc): local-storage csi
* Container Image Tag: 4.6.0
* PostgreSQL Version: 12.5
* Platform (Docker, Kubernetes, OpenShift): kubernetes
* Platform Version: 1.20.2+k3s1

**To Resolve**
Publish olm operator bundle via: https://operatorhub.io/packages

**Comment by jkatz** [comment]
This has already been pushed up to the community operators project

- [https://github.com/operator-framework/community-operators/pull/3066](https://github.com/operator-framework/community-operators/pull/3066)
- [https://github.com/operator-framework/community-operators/pull/3067](https://github.com/operator-framework/community-operators/pull/3067)

If you have further questions, please contact the OperatorHub.io maintainers. Thanks!

**Comment by offlinehacker** [comment]
Thanks, so i assume until is in upstream, index image is not updated. I just wished they had alpha image. Operator lifecycle manager is so many layers of abstractions, I am not sure it is worth it. I wished you had helm configuration published somewhere and not just in repo.
