### ISSUE TITLE
Display issue on Grafana

### ISSUE THREAD

**Issue by aurelien43** [CrunchyData/postgres-operator#2281]
Hello, 
We have found a mistake on Grafana dashboard.
 In pgBackRest Dashboard, the graph : "Time Since Last Completed Backup" have an error on legend format : Incr is full backup and Full is incr_backup

We can found this on grafana-dashboards configmap : 
![image](https://user-images.githubusercontent.com/25898200/107954745-24083b80-6f9d-11eb-8a95-210c1ca91342.png)

**Please tell us about your environment:**

* Operating System: centos7
* Where is this running ( Local, Cloud Provider) : Local
* Storage being used (NFS, Hostpath, Gluster, etc): CSI (SAN)
* Container Image Tag: centos7-12.4-4.5.1
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 4.5.1

**Comment by jkatz** [comment]
We load the dashboards from [pgMonitor](https://github.com/CrunchyData/pgmonitor). Please open an issue with the  project.

**Comment by jkatz** [comment]
Reference: https://github.com/CrunchyData/pgmonitor/issues/229

**Comment by andrewlecuyer** [comment]
This has been fixed with https://github.com/CrunchyData/pgmonitor/issues/229.
