### ISSUE TITLE
4.6.1 version not found

### ISSUE THREAD

**Issue by mesobreira** [CrunchyData/postgres-operator#2282]
Hi,

We would like to test the last version of the postgres-operator but when we try to deploy it, it seems that it's not available yet:

wget https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.6.1/installers/kubectl/postgres-operator.yml

--2021-02-15 15:09:53--  https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.6.1/installers/kubectl/postgres-operator.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-15 15:09:53 **ERROR 404: Not Found.**

The docker repos are not also updated. 
When do you think that it will be available ?

Thanks.

**Comment by jkatz** [comment]
4.6.1 has not been released yet: [https://github.com/CrunchyData/postgres-operator/releases](https://github.com/CrunchyData/postgres-operator/releases).

You can read more about how the Postgres Operator is released in the README:

[https://github.com/CrunchyData/postgres-operator#releases](https://github.com/CrunchyData/postgres-operator#releases)
