### ISSUE TITLE
How to upgrade operator from 4.51 to 4.6?

### ISSUE THREAD

**Issue by jfmatth** [CrunchyData/postgres-operator#2283]
** Which example are you working with? **
Only one i could find is the one for installation
```
kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.6.0/installers/kubectl/postgres-operator.yml
```

**What is the current behavior?**
Results in an error 
```
kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.6.0/installers/kubectl/postgres-operator.yml
serviceaccount/pgo-deployer-sa unchanged
clusterrole.rbac.authorization.k8s.io/pgo-deployer-cr unchanged
configmap/pgo-deployer-cm unchanged
clusterrolebinding.rbac.authorization.k8s.io/pgo-deployer-crb unchanged
The Job "pgo-deploy" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"pgo-deploy", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-uid":"af390cd2-5977-425d-9777-b648a08c28cc", "job-name":"pgo-deploy"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"deployer-conf", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc017164600), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil), Ephemeral:(*core.EphemeralVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"pgo-deploy", Image:"registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos8-4.6.0", Command:[]string(nil), Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:"DEPLOY_ACTION", Value:"install", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"deployer-conf", ReadOnly:false, MountPath:"/conf", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil), SubPathExpr:""}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc00f4e2e20), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"pgo-deployer-sa", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc001137b80), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable
```

**What is the expected behavior?**
upgrade to 4.6

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**
MicroK8s
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+e7db93d188d0d1", GitCommit:"e7db93d188d0d12f2fe5336d1b85cdb94cb909d3", GitTreeState:"clean", BuildDate:"2021-01-11T23:50:46Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System: Ubuntu 20.04

* Where is this running ( Local , Cloud Provider) Local
* 
* Storage being used (NFS, Hostpath, Gluster, etc): Microk8s hoststore
* Container Image Tag: 4.51
* PostgreSQL Version: 12.5
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.19

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by jkatz** [comment]
There is a section in the documentation that covers [upgrading](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/):

[https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/)

**Comment by jfmatth** [comment]
Well, I'm not sure exactly what to do.

I downloaded the postgres-operator.yaml file, and updated the environment variable to update,
```
         env:
            - name: DEPLOY_ACTION
              value: update
```

but I'm still getting the same error.

not sure what's next

I install with the original quickstart, that's all.

**Comment by paulowoody** [comment]
Not sure if it's this, but it sounds like you may need to clean-up the installation artifacts from the previous installation first, as per "Post-Installation" at the end of the installation instructions. e.g. `kubectl delete -f .\postgres-operator.yml`. Then retry the upgrade?

**Comment by jfmatth** [comment]
@paulowoody  and @jkatz 

Thanks for the help, but I finally figured it out.

I think the docs need to be updated since in order to upgrade the operator, i needed to delete the pgo-deploy job first.  If i didn't do that, then I continued to get the same error.

Now the question is, how to upgrade the client w/o trashing my certs?

**Comment by jkatz** [comment]
> I think the docs need to be updated since in order to upgrade the operator, i needed to delete the pgo-deploy job first. If i didn't do that, then I continued to get the same error.

Contributions are certainly welcome.

> Now the question is, how to upgrade the client w/o trashing my certs?

You can download the client directly from the release page, e.g. for 4.6.1:

https://github.com/CrunchyData/postgres-operator/releases/tag/v4.6.1

**Comment by jfmatth** [comment]
Always happy to update the docs, if you can send me the right link, ill submit a pull request.

Client - Good to know, got it all working w/o trashing my certs :)

**Comment by jkatz** [comment]
> Always happy to update the docs, if you can send me the right link, ill submit a pull request.

Docs source is kept here:

[https://github.com/CrunchyData/postgres-operator/tree/master/docs](https://github.com/CrunchyData/postgres-operator/tree/master/docs)

Fairly easy to set up and test after you fork:

```
# ensure hugo is installed
git submodule update --init
cd docs
hugo server
```

The `upgrade` docs are kept in the `Upgrading` section:

https://github.com/CrunchyData/postgres-operator/tree/master/docs/content/Upgrade

In particularly ,the docs for the automatic upgrade process are kept here:

https://github.com/CrunchyData/postgres-operator/blob/master/docs/content/Upgrade/automatedupgrade.md

Thanks!

**Comment by jfmatth** [comment]
@jkatz 

Thanks for keeping this thread going.  I'll look at setting up the docs and submitting a PR soon.

I ran into a real dilemma while upgrading... DOOH.

Looks like I went from 4.50 to 4.61 and that looks like a big no-no, since there doesn't seem to be a way to upgrade my cluster easily.  Any help would be appreciated.

J
