### ISSUE TITLE
Create Stanza Unable to Find Primary Cluster in Openshift 3.11

### ISSUE THREAD

**Issue by mjrussell** [CrunchyData/postgres-operator#2284]
**Describe the bug**
When creating a postgres cluster from scratch using 4.6.0, the stanza-create job never completes successfully. It errors our 5 pods before no longer retrying.

**To Reproduce**
Create a cluster using the pgo-client on Openshift 3.11 with no run as root and fsgroup disabled in pgo yaml.

**Expected behavior**
stanza create job completes

**Screenshots**
```
kubectl logs -f test-cluster5-stanza-create-brdtq 
Mon Feb 15 22:51:51 UTC 2021 INFO: Image mode found: pgbackrest
Mon Feb 15 22:51:51 UTC 2021 INFO: Starting in 'pgbackrest' mode
time="2021-02-15T22:51:51Z" level=info msg="crunchy-pgbackrest starts"
time="2021-02-15T22:51:51Z" level=info msg="debug flag set to %tfalse"
time="2021-02-15T22:51:51Z" level=info msg="backrest stanza-create command requested"
time="2021-02-15T22:51:51Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.131.5.235 --db-path=/pgdata/test-cluster5]"
time="2021-02-15T22:51:52Z" level=info msg="output=[]"
time="2021-02-15T22:51:52Z" level=info msg="stderr=[WARN: unable to check pg-1: [UnknownError] remote-0 process on '10.131.5.235' terminated unexpectedly [255]\nERROR: [056]: unable to find primary cluster - cannot proceed\n]"
time="2021-02-15T22:51:52Z" level=fatal msg="command terminated with exit code 56"
```

On backrest-shared-repo /tmp:

```
bash-4.4$ cat db-stanza-create.log 
-------------------PROCESS START-------------------
2021-02-15 22:51:46.952 P00   INFO: stanza-create command begin 2.31: --exec-id=33-dd4cc144 --log-path=/tmp --pg1-host=10.131.5.235 --pg1-path=/pgdata/test-cluster5 --pg1-port=5432 --pg1-socket-path=/tmp --repo1-path=/backrestrepo/test-cluster5-backrest-shared-repo --stanza=db
2021-02-15 22:51:47.057 P00   WARN: unable to check pg-1: [UnknownError] remote-0 process on '10.131.5.235' terminated unexpectedly [255]
2021-02-15 22:51:47.057 P00  ERROR: [056]: unable to find primary cluster - cannot proceed
2021-02-15 22:51:47.057 P00   INFO: stanza-create command end: aborted with exception [056]
```

In the postgres logs:
```
ERROR: [125]: remote-0 process on 'postgres-backrest-shared-repo' terminated unexpectedly [255]
[2021-02-15 22:31:18.132 UTC   272   00000  602ae6df.110 449  0] LOG:  archive command failed with exit code 125
[2021-02-15 22:31:18.132 UTC   272   00000  602ae6df.110 450  0] DETAIL:  The failed archive command was: source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push "pg_wal/000000010000000000000001"
ERROR: [125]: remote-0 process on 'postgres-backrest-shared-repo' terminated unexpectedly [255]
[2021-02-15 22:31:19.263 UTC   272   00000  602ae6df.110 451  0] LOG:  archive command failed with exit code 125
[2021-02-15 22:31:19.263 UTC   272   00000  602ae6df.110 452  0] DETAIL:  The failed archive command was: source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push "pg_wal/000000010000000000000001"
ERROR: [125]: remote-0 process on 'postgres-backrest-shared-repo' terminated unexpectedly [255]
[2021-02-15 22:31:20.400 UTC   272   00000  602ae6df.110 453  0] LOG:  archive command failed with exit code 125
[2021-02-15 22:31:20.400 UTC   272   00000  602ae6df.110 454  0] DETAIL:  The failed archive command was: source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push "pg_wal/000000010000000000000001"
[2021-02-15 22:31:20.400 UTC   272   01000  602ae6df.110 455  0] WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
```

**Please tell us about your environment:**

* Operating System: centos8
* Where is this running ( Local, Cloud Provider): local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos8-4.6.0 (or centos8-12.5-4.6.0)
* PostgreSQL Version: 12.5
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.6.0

**Additional context**
It sort of looks like a possible bug with the anyuuid in OpenShift...but I'm shooting in the dark a bit. I've disabled fsgroups in the pgo-yaml but I did see in the logs of the shared-backrest-repo:

```
Starting the pgBackRest repo
creating  /backrestrepo/test-cluster5-backrest-shared-repo
/usr/local/bin/pgbackrest-repo.sh: line 50: /etc/pgbackrest/pgbackrest.conf: Permission denied
The pgBackRest repo has been started
```

I tried to follow this for a while and it does look like there might be a bug here. Here's what I tried on the shared-repo:

```
bash-4.4$ id
uid=1001680000(pgbackrest) gid=0(root) groups=0(root),1001680000
```

```
bash-4.4$ ls -larth /etc/pgbackrest
total 0
drwxrwsrwt. 3 root 1001680000 80 Feb 15 22:37 conf.d
drwxr-xr-x. 1 root root       51 Feb 15 22:37 ..
drwxrwxr-x. 1 2000 postgres   20 Feb 15 22:37 .
```

```
bash-4.4$ cat /etc/passwd
...
pgbackrest:x:1001680000:0:pgbackrest user:/:/bin/bash
```

```
bash-4.4$ cat /etc/group
...
pgbackrest:x:0:pgbackrest
```
Then I took a look at what /usr/local/bin/pgbackrest-repo.sh  was doing and tried executing it:

```
bash-4.4$ printf "[%s]\npg1-path=/tmp/pg1path\n" "$PGBACKREST_STANZA" >> /etc/pgbackrest/pgbackrest.conf
bash: /etc/pgbackrest.conf: Permission denied
```

It looks like the folder is only writable by postgres group which the user isn't a part of or id 2000 but because of the anyuuid I'm not that user. I ended up trying a custom Dockerfile where I just gave that folder 777 and it did actually write to it, but I still had the problem stated above. Hoping you have some other thoughts on logs to look at. I read a bit on other issues regarding authentication, tls or firewall, but after hitting these issues I stripped it to a bare-bones deploy off of the client so it doesn't appear to be that at first glance.

**Comment by jkatz** [comment]
This sounds like an issue at your storage level. Are you provisioning storage manually or using a storage provisioner?

**Comment by mjrussell** [comment]
Thanks for the quick reply!

What is indicating to you that its storage? This environment uses a netapp with their trident plugin for storage provisioning.

I realized I hadn't mentioned that I did not have issues with 4.5.1 and the configs are largely the same except with the changes to 4.6.0.

Is there way to get more info I can get from whats failing for pgbackrest? Now the permission denied is fixed (which looks like fsgroups more than anything) its hard to tell if theres anything else wrong.

**Comment by jkatz** [comment]
What is the image name of the container that you are using for 4.6.0? Note that the [pgBackRest repo container was renamed](https://access.crunchydata.com/documentation/postgres-operator/4.6.0/releases/4.6.0/) in 4.6.0. The Dockerfile does explicit set the permission of `/etc/pgbackrest` to be owned by the `pgbackrest` user (UID 2000), and the startup script does add configuration to `/etc/pgbackrest/pgbackrest.conf`. Are you running with `readOnlyRootFilesystem`?

**Comment by mjrussell** [comment]
`registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-12.5-4.6.0` and `registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-12.5-4.6.0` for backrest and backrest-repo which look like they match what you posted. For `scc` there is no `readOnlyRootFilesystem` but we are using `anyuuid`.

When I looked at etc/password is looked like pgbackrest user wasnt being reset to 2000 so anything owned by 2000 was no longer allowed. Right here - https://github.com/CrunchyData/crunchy-containers/blob/master/bin/pgbackrest-repo/uid_pgbackrest.sh#L20 it drops the 2000 out. Im not super familiar with all thats going on in this script but wasnt sure if this recently changed

**Comment by mjrussell** [comment]
Also to be clear, I was able to fix adding the lines to the pgbackrest.conf by making that folder 777. Which probably isn't right...but would be fine temporarily. Unfortunately I dont see any logs or info about what next might be the issue. I suppose that theres likely other issues with the pgbackrest-shared-repo perms that might impact it functioning

**Comment by Vermillionaire** [comment]
It looks like some permissions changes might not have carried over to the new backrest repo image. The backrest container had this permissions change for `/etc/pgbackrest` in v4.5.1: https://github.com/CrunchyData/postgres-operator/blob/bcd02e5a19aafca1d0d39026056a9477dc41bb48/build/pgo-backrest-repo/Dockerfile#L34 

I could not find the equivalent permissions in any containers or scripts in v4.6.0. This folder needs to be owned by the root group if you are writing to it in OpenShift.

**Comment by jkatz** [comment]
It's right here:

https://github.com/CrunchyData/crunchy-containers/blob/71d70a1698b716e8bc94cbc250f5c4b4f3e4110b/build/pgbackrest-repo/Dockerfile#L28-L30

**Comment by jkatz** [comment]
As it's late here, I'll provide a brief explanation for now: the change between 4.6.0 + 4.5.1 had to do with the directory ownership of the `/etc/pgbackrest` directory specifically in the pgBackRest repository container, which was alluded to in the original report. The ownership change caused the reported failure when using `anyuid` mode in OCP 3.11.

The reason why this manifested was due to the change in how the pgBackRest repo container was constructed, i.e. it was using a new container as its base.

The reason my suspicion was the storage layer at first is that when similar things are reported, that tends to be the case. I missed the `/etc/pgbackrest` detail which was the clue for this one. The incorrect ownership under `anyuid` mode would cause the configuration file to not properly generate, which has the cascading failure effect that you noticed.

The good news: this came in just under the radar for the 4.6.1 cut off (I was literally about to stamp, and decided to take one more look at this) so this will be included in the upcoming patch release.

One of my colleagues may also chime in on a workaround until 4.6.1 is out.

Anyway, thanks for reporting!

**Comment by mjrussell** [comment]
@jkatz awesome! Thank you very much. I think i see the fix based on your commit here - https://github.com/CrunchyData/crunchy-containers/commit/07459045de14862204b7679d7c98bf36f9445e1e#diff-e04d60c5e7007cfbdec302ad721e7ba9416a05bd6f37f43d959e445489b67683L22 

I can throw that in a Dockerfile and tweak the tags so we can make some immediate progress.

When do you expect 4.6.1 to be out?

**Comment by mjrussell** [comment]
So I have a Dockerfile with the following:
```
FROM registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-12.5-4.6.0
USER root
# See https://github.com/CrunchyData/postgres-operator/issues/2284 and
# https://github.com/CrunchyData/crunchy-containers/commit/07459045de14862204b7679d7c98bf36f9445e1e#
# Temporary fix until 4.6.1
RUN chown -R pgbackrest:root /etc/pgbackrest
RUN rm -f /run/nologin

USER 2000
```

Unfortunately this image still does not work for me. Am I missing anything else in the dockerfile? I confirmed the permissions do indeed look better for /etc/pgbackrest

```
kubectl exec -it postgres-backrest-shared-repo-6dc64c6bc4-8s22c  -- ls -larth /etc/pgbackrest                  
total 4.0K
drwxrwsrwt. 3 root       1000140000 80 Feb 17 06:23 conf.d
drwxr-xr-x. 1 root       root       51 Feb 17 06:23 ..
-rw-r--r--. 1 pgbackrest root       27 Feb 17 06:23 pgbackrest.conf
drwxrwxr-x. 1       2000 root       43 Feb 17 06:23 .
```

**Comment by mjrussell** [comment]
@jkatz  do you have the workaround handy? I want to definitely see if there is still another issue we need to troubleshoot or I simply didn't get it all in my Dockerfile workaround.

**Comment by jkatz** [comment]
@andrewlecuyer Got it working with `anyuid` set on OCP 3.11 this morning when we QA'd the 4.6.1 pre release image, so it's likely configuration. Perhaps he can share his manifest.

**Comment by andrewlecuyer** [comment]
@mjrussell to troubleshoot further, can you show the SSC annotation (i.e. the `openshift.io/scc` annotation) being applied to each of the various Pods created for the cluster? For instance, just like the following shows the SCC annotation for a Primary PG Pod, can you provide the same for the Primary, Repo and any Job Pods?

```
$ oc describe pod mycluster1-6674485cd6-hlndf | grep Annotations:
Annotations:    openshift.io/scc: anyuid
```

And based on the SCC's you see based on those annotations, can you provide a copy of the contents of those SCC's within your  environment?

**Comment by mjrussell** [comment]
@andrewlecuyer sure thing. They are all runny with the scc anotation `restriected` (sorry I had saud anyuid above) which has the following:
```
oc get scc restricted
NAME                 PRIV    CAPS   SELINUX     RUNASUSER          FSGROUP     SUPGROUP    PRIORITY   READONLYROOTFS   VOLUMES
restricted           false   []     MustRunAs   MustRunAsRange     MustRunAs   RunAsAny    <none>     false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
```

**Comment by Vermillionaire** [comment]
We are still having issues with the backup piece of the operator. This time it is the `stanza-create` job failing. We think we have narrowed it down to a bug in the ssh config between  `backrest-shared-repo` and the `postgres` pod.  (maybe also a permissions issue like above?)

When we ssh from the `backrest-shared-repo` pod: 
``` bash
bash-4.4$ ssh -o LogLevel=debug -o Compression=no -o PasswordAuthentication=no pgbackrest@10.150.4.66
debug1: Reading configuration data //.ssh/config
debug1: //.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: configuration requests final Match pass
debug1: re-parsing configuration
debug1: Reading configuration data //.ssh/config
debug1: //.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: FIPS mode initialized
debug1: Connecting to 10.150.4.66 [10.150.4.66] port 2022.
debug1: Connection established.
debug1: identity file /tmp/id_ed25519 type -1
debug1: identity file /tmp/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.0
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.0
debug1: match: OpenSSH_8.0 pat OpenSSH* compat 0x04000000
debug1: Authenticating to10.150.4.66:2022 as 'pgbackrest'
debug1: SSH2_MSG_KEXINIT sent
Connection reset by 10.150.4.66 port 2022
```

I modified the configs on the ssh server in the postgres container to get the debug logs: 
```bash
debug1: FIPS mode initialized
debug1: inetd sockets after dupping: 4, 4
Connection from 10.140.5.30 port 41354 on 10.150.4.66 port 2022
debug1: Local version string SSH-2.0-OpenSSH_8.0
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.0
debug1: match: OpenSSH_8.0 pat OpenSSH* compat 0x04000000
debug1: sshd_selinux_change_privsep_preauth_context: Failed to open SELinux context file [preauth]
debug1: list_hostkey_types:  [preauth]
No supported key exchange algorithms [preauth]
debug1: do_cleanup [preauth]
debug1: monitor_read_log: child log fd closed
debug1: do_cleanup
debug1: Killing privsep child 49863
```

While we were exploring this we also saw this error in the ssh server logs. Dont know if it is a warning or actually an issue for the SSHD server: 
```Couldn't create pid file "/var/run/sshd.pid": Permission denied```

We have verified that ssh is working in the 4.5.1 operator we are still running in the cluster. Does someone know anything that changed in the new version that might have broken SSH? Our theory are either incompatible config with FIPS or bad permissions on the keys in the container.

**Comment by jkatz** [comment]
@Vermillionaire I opened this up in #2289
