### ISSUE TITLE
Configure pgo cluster with custom storage class and PVC

### ISSUE THREAD

**Issue by nuthanbn** [CrunchyData/postgres-operator#2286]
**Describe the bug**
pgo cluster creation is failing since it is unable to use the requested storage class for creating pvc's.

I have created a new storage class on Kubernetes and added the new storage configuration STORAGE5_*  in helm values file(pgo configuration).
For some reason, pgo client is ignoring the configuration provided in the pgo yaml and the command. 

**Storage configuration from pgo.yaml(helm values.yaml):**

storage5_name: "standard"
storage5_access_mode: "ReadWriteMany"
storage5_size: "50Gi"
storage5_type: "create"
storage5_class: "postgres-sc"
storage5_match_labels: "app=test"

**kubectl/pgo commands:**

To create a label for existing persistent volume
**kubectl label pv demo-pv app=test

Create postgres cluster with configured storage configuration 
**pgo create cluster testdb --storage-config=standard --metrics --password nuthan 

PVC binding is failing. please note that default storage-class in the cluster is picked instead of postgres-sc
**kubectl get pvc
NAME                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
testdb                    Pending                                                                                                          managed-nfs-storage   7m58s

PV details:
**kubectl get pv demo-pv
NAME              CAPACITY   ACCESS.   MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
demo-pv.            200Gi      RWX            Retain           Available                                              postgres-sc                         3h1m

**To Reproduce**
1. Create a new storage class
2. Create PV
2. Try to use the custom storage class in pgo cluster creation command

I was able to see a similar issue here.
**https://github.com/CrunchyData/postgres-operator/issues/1685**

Is this a known issue?. How to create a cluster with the custom storage class? Can you please advise.

**Expected behavior**
Postgres cluster should be created with the specified storage class. PVC should bind based on the configured labels from pgo.yaml(helm values file) and pv labels.

**Please tell us about your environment:**

* Operating System: CentOS Linux 7
* Where is this running: On-premises Kubernetes 
* Storage being used (NFS, Hostpath, Gluster, etc): MapR file system(hadoop HDFS)
* Container Image Tag: 
* PostgreSQL Version: 13.1
* PGO client: 4.6.0
* Postgres operator: 4.6.0
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.18

**Comment by jkatz** [comment]
- What does `kubectl describe pv demo-pv` say?
- What does `kubectl describe pvc testdb` say?
- Do you have output from the Operator logs? `kubectl logs -n <postgres-operator-ns> <postgres-operator-pod> -c operator`?

**Comment by nuthanbn** [comment]
Jonathan,
Thank you for the response.
Please find the requested command output and logs.

![image](https://user-images.githubusercontent.com/49142248/108141476-c9c8c100-70e9-11eb-8736-a1627efd0976.png)
![image](https://user-images.githubusercontent.com/49142248/108141725-4491dc00-70ea-11eb-8c37-ad48a781efa1.png)
![image](https://user-images.githubusercontent.com/49142248/108141798-6c813f80-70ea-11eb-9b9b-3a940013b107.png)

**Comment by nuthanbn** [comment]
@jkatz ,
Have you ever tried storage class on Kubernetes? Custom configuration is not working for me. 
I have tried creating various storage index like storage5 and storage11.

**Comment by jkatz** [comment]
> Have you ever tried storage class on Kubernetes?

Yes, we test the Postgres Operator against a variety of different storage classes and configurations.

The error appears to be within your provisioning system. It's difficult for me to copy and paste the text as this is all in images, but the output describes "waiting for volume to be created either by external provisioner "example.com/nfs" or manually created by the system administrator."

I would first try testing to see if you can manually create a PV and then bind it to a PVC, and then test against doing this with the Postgres Operator. I don't think this is a bug with the Operator.
