### ISSUE TITLE
installation with local volume pv

### ISSUE THREAD

**Issue by marlin1993** [CrunchyData/postgres-operator#2287]
Hi
i am using a kubernetes cluster in a virtual machine based host.

And i dont have storage class.Can you please guide me through how i can create a hostpath pv and install the operator?

I install the operator but when i tried to create a cluster the pod never initiated.Because it is showing persistent volume not found.

i will be very grateful if you provide me some solution.

Thank you.

**Comment by jkatz** [comment]
There are example scripts for provisioning PVs available here:

[https://github.com/CrunchyData/postgres-operator/tree/master/pv](https://github.com/CrunchyData/postgres-operator/tree/master/pv).

There is ample documentation on installing and using the Postgres Operator available here, I would suggest browsing that: [https://access.crunchydata.com/documentation/postgres-operator/](https://access.crunchydata.com/documentation/postgres-operator/).

I would also strongly suggest using a hostpath storage provisioner or an environment that provides one, as this will mitigate the risk of creating self-made issues.

Beyond that, I would suggest reviewing some of the [community and other support options](https://access.crunchydata.com/documentation/postgres-operator/latest/support/).
