### ISSUE TITLE
Selecting Topology for Pod Anti Affinity

### ISSUE THREAD

**Issue by AdrianXIA** [CrunchyData/postgres-operator#2288]
In the configmap **pgo.config** is a file defined a file **pod-anti-affinity.json**.

Q1: Is there any way to modify the property **topologyKey** to another values? e.g: **topology.kubernetes.io/zone**

According to [this](https://access.crunchydata.com/documentation/postgres-operator/4.6.0/architecture/high-availability/), this mode schedules the pod based on hostname.
Using topology.kubernetes.io/zone, the resources will be created based on availability zones for K8S cluster deployed in cloud.

According to [this](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity), it can be used multiple values for a **key** specified to **matchExpressions**.

Q2: Can multiple values be specified?

**Comment by AdrianXIA** [comment]
I manually changed the topology to **topology.kubernetes.io/zone** and created a Postgres cluster. 
It worked.

**Comment by jkatz** [comment]
> It worked.

Brilliant. :+1:

Yes, if you want to customize the Pod anti-affinity topologyKey etc. to be different itself, you can do so in pod-anti-affinity.json.

**Comment by AdrianXIA** [comment]
Hello,

May the topologykey be added as a configurable parameter, somewhere?
When the cluster runs on-premise, the kubernetes.io/hostname is useful, there is no availability zone.
But when the cluster run on a cloud provider you want to populate the availability zones first instead selecting two nodes in the same availability zone.

Thanks.

**Comment by jkatz** [comment]
I would consider using "node affinity" support (improved in 4.6) for the topology you are looking at:

- [Node Affinity](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/#node-affinity)
- [Multi-Zone Design Considerations](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/multi-zone-design-considerations/)
- This blog may be of interest as well: https://info.crunchydata.com/blog/kubernetes-pod-tolerations-and-postgresql-deployment-strategies
