### ISSUE TITLE
pgo_admin_password randomly generated

### ISSUE THREAD

**Issue by aurelien43** [CrunchyData/postgres-operator#2290]
Hello, 
In the version 4.5.1, when pgo_admin_password  is blank, the password is randomly generated. 
But in 4.6.0, when pgo_admin_password  is blank, the password is empty.

![Capture](https://user-images.githubusercontent.com/25898200/108383310-f83dbd80-7209-11eb-8e57-011dbdb65f9b.PNG)

**Please tell us about your environment:**

* Operating System: centos
* Where is this running ( Local, Cloud Provider) : Local
* Storage being used (NFS, Hostpath, Gluster, etc): CSI (SAN)
* Container Image Tag: centos8-13.1-4.6.0
* PostgreSQL Version: 13.1
* Platform (Docker, Kubernetes, OpenShift):Kubernetes
* Platform Version: 4.6.0

**Comment by jkatz** [comment]
I could not reproduce this issue. Please check your logs in the `apiserver` container to see if there were any errors with the generation.

**Comment by aurelien43** [comment]
I have an error : 

time="2021-02-19T07:26:40Z" level=info msg="Password in pgouser secret pgouser-admin for operator installation pgo in namespace pgo is empty. Setting a generated password." func="internal/apiserver.setRandomPgouserPasswords()" file="internal/apiserver/root.go:520" version=4.6.0
time="2021-02-19T07:26:40Z" level=error msg="Could not patch pgouser secret pgouser-admin with generated password for operator installation pgo in namespace pgo" func="internal/apiserver.setRandomPgouserPasswords()" file="internal/apiserver/root.go:542" version=4.6.0
time="2021-02-19T07:26:40Z" level=info msg="Namespace operating mode is 'disabled'" func="internal/apiserver.Initialize()" file="internal/apiserver/root.go:151" version=4.6.0

**Comment by jkatz** [comment]
```
Could not patch pgouser secret pgouser-admin with generated password for operator installation pgo in namespace pgo
```

It sounds like you are missing a permission. If you are customizing your RBAC, please ensure you can patch Secrets. This is described in the documentation:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/#rbac-reconciliation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/#rbac-reconciliation)

**Comment by aurelien43** [comment]
effectively it's come from RBAC. 
I use namespace_mode : "disable" and i can patch Secrets. 
But, the RBAC create by pgo-role-rbac have not the patch verbs for the ressource secret and if i add patch secret, it's works for me. 
https://github.com/CrunchyData/postgres-operator/blob/v4.6.0/installers/ansible/roles/pgo-operator/templates/pgo-role-rbac.yaml.j2#L20
it's normal or not ?
