### ISSUE TITLE
Can't set an annotation correctly due to comma in value

### ISSUE THREAD

**Issue by bborovan** [CrunchyData/postgres-operator#2292]
** Which example are you working with? **
We are using the pgo operator and are trying to set a new annotation for Datadog monitoring following your examples at:
https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#custom-annotations

**What is the current behavior?**
We try to set a simple annotation and it works as expected, however, when we try to set an annotation for Datadog in our case, it fails to work as expected, due to the syntax being more complex it seems. 

**What is the expected behavior?**
We would expect it to work regardless of it being more complex syntax for the annotations, since the annotation is valid.

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**
Kubernetes with your PGO installed and working

* Operating System:
Linux

* Where is this running ( Local , Cloud Provider)
On premission Kubernetes cluster (k3s)

* Storage being used (NFS, Hostpath, Gluster, etc):
local-path / hostpath

* Container Image Tag:
N/A

* PostgreSQL Version:
13

* Platform (Docker, Kubernetes, OpenShift):
Kubernetes

* Platform Version:
1.19

This is the annotation we want to add (as typically entered in the annotations section in the settings for the pod):
ad.datadoghq.com/postgres.logs: '[{"source": "postgresql-cd", "service": "postgresql-cd"}]'

To facilitate this we ran:
pgo update cluster postgresql-cd --annotation=ad.datadoghq.com/postgres.logs=\'[{"source":"postgresql-cd","service":"postgresql-cd"}]\'

However, when we run:
kubectl describe pod [POD NAME] -n pgo 

For one of the deployed PostgreSQL instances (we have 1 replica - so two pods running), the Annotation shows it is set to:
Annotations:  ad.datadoghq.com/postgres.logs: [service:postgresql-cd]

For each of the PostgreSQL pods.

So you can see it is not applying the annotation as desired.

Can you please suggest how to apply this correctly? Your documentation does not show such examples and we are unsure what to do.

Thank you!

**Comment by jkatz** [comment]
Did you try editing the custom resource directly? This is documented on the custom resources page:

https://access.crunchydata.com/documentation/postgres-operator/4.6.1/custom-resources/

**Comment by bborovan** [comment]
Thank you for the info @jkatz!

**Comment by jkatz** [comment]
To further explain, the issue is that the `--annotation` et al. flags are able to take "lists of things" (which is part of the viper parser). It allows for two ways to denote a list:

- via multiple instantiations of the flag (e.g. `--annotation=abc=def --annotation=ghi=jkl`)
- via a comma separated list (e.g. `--annotation=abc=def,ghi=jkl`)

Because of that behavior of the library, the only way to handle annotations that have commas would be to modify the annotations directly via the custom resource.

**Comment by bborovan** [comment]
Thank you @jkatz again!
