### ISSUE TITLE
Update pgBouncer pod

### ISSUE THREAD

**Issue by pengbo0328** [CrunchyData/postgres-operator#2293]
I have read the tutorial below, but it doesn't mention how can I update the parameters of pgBouncer.

  https://access.crunchydata.com/documentation/postgres-operator/4.6.1/tutorial/pgbouncer/

If the pgbouncer.ini or pg_hba.conf defined in **ConfigMap** (e.g. hippo-pgbouncer-cm) is updated, can pgBouncer pod detect the change automatically and restart or reload pod? Or do I need to restart pgBouncer pod manually?

If I want to connect to PostgreSQL through pgBouncer using a regular PostgreSQL's user, do I need to register the username and hashed password in **users.txt**.

**Comment by jkatz** [comment]
> If the pgbouncer.ini or pg_hba.conf defined in ConfigMap (e.g. hippo-pgbouncer-cm) is updated, can pgBouncer pod detect the change automatically and restart or reload pod? Or do I need to restart pgBouncer pod manually?

You would need to restart the pgBouncer pod manually (or scale down/up the replicas in it). I can add that as an enhancement request.

> If I want to connect to PostgreSQL through pgBouncer using a regular PostgreSQL's user, do I need to register the username and hashed password in users.txt.

The Operator automatically manages this. It uses pgBouncer's `auth_query` mechanism to query the `pg_authid` table through a restricted function. `users.txt` only contains the credentials for the `pgbouncer` user itself. You can add regular PostgreSQL users either though the `pgo create user`  command or directly in PostgreSQL, and pgBouncer will be aware of the changes.

**Comment by pengbo0328** [comment]
Thank you for your quick response.
I have understood the feature.

**Comment by jkatz** [comment]
PGO 5.0 added support for this. You can find an example of how to customize this here:

[https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/connection-pooling/#configuration](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/connection-pooling/#configuration)
