### ISSUE TITLE
Changing params after creating db cluster

### ISSUE THREAD

**Issue by vispatster** [CrunchyData/postgres-operator#2295]
I have set up pgo-operator and hippo cluster using kube manifests. I am trying to apply those yamls using CD approach. However, whenever any params changed in `pgcluster` manifest does not apply change to kubernetes. While describing the `kubectl -n pgo describe pgcluster`, it returns something like "cluster change initialized". Then, nothing happens. 

steps: 
- applied under pgo to setup operator (https://github.com/CrunchyData/postgres-operator/blob/master/installers/kubectl/postgres-operator.yml)
- Then , 
 ```
cd ./examples/kustomize/createcluster/
kustomize build base/ | sed 's/storageclass: ""/storageclass: default/g' | kubectl -n pgo apply -f  -
```
now, hippo cluster has been created. 
To change pvc size, 

```
kustomize build base/ | sed 's/storageclass: ""/storageclass: default/g' | sed 's/1G/2G/g' |kubectl -n pgo apply -f  -
```
The above command returns "cluster change initialized" and nothing happens under cluster.

**Comment by jkatz** [comment]
Please review the documentation on which parameters can be modified:

[https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/)

#1311 details  an enhancement request to allow for the resizing of volumes. This is currently on the roadmap and may be completed for the next release.
