### ISSUE TITLE
Upgrade procedure PG 12.6 to 13.2

### ISSUE THREAD

**Issue by lbartnicki92** [CrunchyData/postgres-operator#2296]
Hi!

I've tested PostgreSQL Operator Upgrade process from 4.6.0 to 4.6.1 - it works well.
Also I updated pgcluster from PG 13.1 to 13.2 by pgo upgrade command.

But I have one question about upgrading PostgreSQL created by Operator from for example: PostgreSQL 12.6 to 13.2

Does Operator supports such operation? 
I've tried with pgo upgrade and --ccp-image-tag  parameter but always it ended with:
Error: cannot upgrade from centos8-12.6-4.6.1 to centos8-13.2-4.6.1, upgrade task failed.

Is there any method? Or I have to do logical backup and restore from 12.6 cluster to new 13.2 cluster?
I've found that tehre is pg_upgrade image, but there is no infromation in docs how to use it?

**Comment by jkatz** [comment]
Glad to hear it's working.

The Operator does not handle major upgrades directly. There is documentation on how to use the [`crunchy-upgrade`](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/) container to handle this. Some others have reported how they have handled major upgrades through various GitHub issues that have been open.

**Comment by lbartnicki92** [comment]
Today I tested crunchy-upgrade image, in upgrade.json I have:

                           {
                                "name": "OLD_VERSION",
                                "value": "12"
                            },
                            {
                                "name": "NEW_VERSION",
                                "value": "13"
                            }
                        ]
                    }

Is this correct? My pgcluster running PG 12.6 now on 4.6.1 Operator

After running run.sh:

kubectl logs upgrade-ncz4f -n pgo
Wed Feb 24 14:11:59 UTC 2021 INFO: **Unsupported NEW_VERSION of 13.**

**Comment by psavva** [comment]
@lbartnicki92 Any chance you can give me pointers how to perform the upgrade from 12 to 13?
I see you're using the crunchy-upgrade, and i'm a bit lost as how to use it.
