### ISSUE TITLE
Logical backup to temp directory first

### ISSUE THREAD

**Issue by lgarcia11** [CrunchyData/postgres-operator#2298]
I'm using azure file share as my backup storage and taking a logical backup takes a very long time, wouldn't it be better if the backup is taken locally first and then copied to the backup storage?

**Comment by jkatz** [comment]
Logical backups are taken directly to the PVC that they are mounted to. If that storage is distant, then they will take time.

Even if we were to reroute the logical backups to `/tmp` or the like, we would still have to take the backups and then copy to the remote storage. This may in fact end up taking longer, given it sounds like the cost of writes to the remote storage is high.
