### ISSUE TITLE
Create cluster from YAML / at operator init

### ISSUE THREAD

**Issue by jamessewell** [CrunchyData/postgres-operator#2299]
Hi all,

I'm running the operator in bare K8s and want to be able to package cluster creation as YAML (or, alternatively have the cluster created as the operator inits). Is this possible, or do I *have* to use pgo create cluster?

Cheers,
James

**Comment by jkatz** [comment]
Yes, there is ample documentation and examples on how to create Postgres clusters via YAML and other GitOps tooling:

### Docs
- [Using Custom Resources](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/)

### Blogs
- [Using GitOps to Self-Manage Postgres in Kubernetes](https://info.crunchydata.com/blog/gitops-postgres-kubernetes)
- [Helm, GitOps and the Postgres Operator](https://info.crunchydata.com/blog/gitops-postgres-kubernetes-helm)

### Examples
- [Helm](https://github.com/CrunchyData/postgres-operator/tree/master/examples/helm)
- [Kustomize](https://github.com/CrunchyData/postgres-operator/tree/master/examples/kustomize/createcluster)

as well as examples in previous issues.
