### ISSUE TITLE
Considerations multipile PVCs for non-shared external storage

### ISSUE THREAD

**Issue by vladimirvivien** [CrunchyData/postgres-operator#23]
@jmccormick2001 
I got the postgres operator to work with Dell EMC's ScaleIO. Here are some considerations to help with scaling the operator for non-shared external storage like ScaleIO:
* Create a PVC for main database data mounted at `/pgdata`
* Create a PVC for backup database data mounted at  `/pgbackup`.  
* Create a PVC for replica pods data mounted at `/pgdata`

This will help avoid conflicts when scheduling on multi-node Kubernetes clusters where main database pod and replica pods may get scheduled on the same instance.

**Comment by jmccormick2001** [comment]
thanks for the update Vladimir and I love to hear it works with ScaleIO!  Our customers will like to hear that too.  

regarding the PVCs, if you do not specify the CLUSTER.PVC_NAME within the .pgo.yaml config file, then it should allocate the PVCs individually instead of using a shared PVC.  Hopefully I've not broken that functionality and will test it to make sure it still works.  regards.

**Comment by vladimirvivien** [comment]
@jmccormick2001 
Hi, yes, when `CLUSTER.PVC_NAME` is not provided, the operator code does create the PVC as needed.  

Design Question:
I am not familiar with Postgres clustering.  Do the replica DBs stay sync'd by access master DB data from filesystem or is it via a replication service over network.  If it's by sharing files, is there a mechanism to prevent read/write races between master/replicas ? 

I am asking because I am trying to determine if each replica should have their own PVCs (if replication is via replication service) ?

Thanks.

**Comment by jmccormick2001** [comment]
postgres replicas get their state by a network connection to the master, so each replica needs it's own unique PVC essentially.  Initially each replica starts with an empty PVC, then connects to the master via the network, and the replication proceeds until the replica is at the same state of the master with regards to data.

**Comment by vladimirvivien** [comment]
@jmccormick2001 
Thanks for clarifying the mechanism between master db/replica dbs.  You mentioned that 
>  each replica needs it's own unique PVC essentially
However, when I create a cluster I only see one PVC auto-generated.  For instance, the following shows the sequence of creating a cluster:
```
vladimir@k8s-controller:~$ pgo create cluster pgcluster
DEBU[0000] kubeconfig path is admin.conf
DEBU[0000] namespace is default
DEBU[0000] ConnectToKube called
DEBU[0000] connected to kube. at admin.conf
DEBU[0000] create cluster called
DEBU[0000] create cluster called for pgcluster
DEBU[0000] pgcluster pgcluster not found so we will create it
created PgCluster pgcluster
```
Show the cluster
```
vladimir@k8s-controller:~$ pgo show cluster all
DEBU[0000] kubeconfig path is admin.conf
DEBU[0000] namespace is default
DEBU[0000] ConnectToKube called
DEBU[0000] connected to kube. at admin.conf

cluster : pgcluster (unknown)
DEBU[0000] listing cluster all
├── deployment : pgcluster
├── deployment : pgcluster-replica
├── replicaset : pgcluster-3167509731
├── replicaset : pgcluster-replica-2588046056
├── pod : pgcluster-3167509731-8xx99 (Running) (1/1)
├── pod : pgcluster-replica-2588046056-901d0 (Running) (1/1)
├── pod : pgcluster-replica-2588046056-jmt6s (Running) (1/1)
├── service : pgcluster (10.97.144.7)
└── service : pgcluster-replica (10.98.80.240)
```
Listing the PVC shows only one
```
vladimir@k8s-controller:~$ kubectl get pvc
NAME            STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pgcluster-pvc   Bound     pvc-3d544a9e-5c2d-11e7-9f7f-42010a800064   16Gi       RWO           pg-storage     1m
```

Unless I misunderstood, I was expecting to see a PVC for the master  DB pod `pgcluster` and one for the replicas `pgcluster-replica` pod.  Seeing only one PVC means that the volume must be being shared.

**Comment by jmccormick2001** [comment]
make sure your .pgo.yaml config file doesn't specify a PVC_NAME setting, that is what is used to determine whether or not a unique PVC is used or not.  With that removed from your config, you should start seeing PVCs created for the replicas as well.  The naming convention is "somename"-pvc

**Comment by vladimirvivien** [comment]
@jmccormick2001 
Hi I am not specifying `PVC_NAME` in my `.pgo.yaml` file as you can see from the pasted content.  So, I am not sure why I am not seeing the PVC's generated for the replicas.  
```
vladimir@k8s-controller:~$ cat .pgo.yaml
KUBECONFIG:  /home/vladimir/admin.conf
NAMESPACE:  default
CLUSTER:
  CCP_IMAGE_TAG:  centos7-9.6-1.4.1
  PORT:  5432
  PG_MASTER_USER:  master
  PG_MASTER_PASSWORD:  ********
  PG_USER:  testuser
  PG_PASSWORD:  *******
  PG_DATABASE:  userdb
  PG_ROOT_PASSWORD:  ********
  PVC_SIZE:  16Gi
  PVC_ACCESS_MODE:  ReadWriteOnce
  FSGROUP:  26
  SUPPLEMENTALGROUPS:  65534
  STRATEGY:  1
  REPLICAS:  2
PGO:
  LSPVC_TEMPLATE:  /home/vladimir/.pgo.lspvc-template.json
  CO_IMAGE_TAG:  centos7-1.2.0
  DEBUG:  true
```
When I create cluster `pgcluster` it only creates one PV as shown below.
```
vladimir@k8s-controller:~$ kubectl get pvc
NAME            STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pgcluster-pvc   Bound     pvc-3d544a9e-5c2d-11e7-9f7f-42010a800064   16Gi       RWO           pg-storage     2h
```

**Comment by jmccormick2001** [comment]
this is a bug on my part, I hope to have a fix today for it.

**Comment by gregscds** [comment]
On Wed, Jun 28, 2017 at 11:42 AM, Vladimir Vivien <notifications@github.com>
wrote:

> I am not familiar with Postgres clustering. Do the replica DBs stay sync'd
> by access master DB data from filesystem or is it via a replication service
> over network. If it's by sharing files, is there a mechanism to prevent
> read/write races between master/replicas ?
>

Jeff answered for this specific application.  In the general case for
PostgreSQL you can create a replica from either a filesystem copy (usually
rsync, but could be tar etc.) or just replicate over the network.  rsync
gives you some options like limiting network traffic bandwidth that can be
really handy.

When Poistgres is in the middle of an active replication it's careful not
to do anything that would cause a serious problem for the read-only replica
to playback.  If there is some read/write conflict, the query running on
the replica is cancelled.  There are some tuning parameters you can tweak
to give queries more time to finish before that happens.  The standard way
to test all this out is to DROP a table that's being read on a standby and
then watch the query get cancelled.  I highly recommend testing your
application for robustness when that form of query cancellation happens;
it's not just a concern during replication, query cancels like the DROP
case can happen any time.

**Comment by jmccormick2001** [comment]
version 1.3.2 is now out there, it should address the bug you found, with that version it will now create the replica PVCs as emptyDir by default when the PVC_NAME is not specified (implying you are not using a shared PVC volume type).   So, if you wanted to try dynamic storage provisioning for the replicas, you would modify the cluster-replica-deployment-1.json configuration file to match your storage configuration, replace the emptyDir volume type with something else.  I'm going to work up an example of this using some sort of volume type that supports dynamic provisioning in an upcoming release, if you get it working with ScaleIO, I would love to have a copy of your configuration file to add to the repo.

**Comment by vladimirvivien** [comment]
@jmccormick2001 Hi I tested 1.3.2.  When I omit PVC_NAME in .pgo.yaml, the replica deployment does not seem to be deployed on the cluster by the operator.  

```
> kubectl get deployment,service
NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/pgcluster           1         1         1            1           11m
deploy/postgres-operator   1         1         1            1           22h

NAME                    CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
svc/kubernetes          10.96.0.1      <none>        443/TCP    44d
svc/pgcluster           10.99.29.193   <none>        5432/TCP   11m
svc/pgcluster-replica   10.101.69.91   <none>        5432/TCP   11m
```

However, when I set the name `PVC_NAME` in .pgo.yaml, the replica deployment works, but only creates one PVC as before.
```
> kubectl get pv,pvc,po
NAME                                          CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                 STORAGECLASS   REASON    AGE
pv/pvc-74c04d22-6367-11e7-8872-42010a800064   16Gi       RWO           Delete          Bound     default/crunchy-pvc   pg-storage               3m

NAME              STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pvc/crunchy-pvc   Bound     pvc-74c04d22-6367-11e7-8872-42010a800064   16Gi       RWO           pg-storage     3m

NAME                                    READY     STATUS    RESTARTS   AGE
po/pgdb-3224194718-cc745                1/1       Running   0          2m
po/pgdb-replica-2430100643-ldthc        1/1       Running   0          2m
po/pgdb-replica-2430100643-x4hdt        1/1       Running   0          2m
po/postgres-operator-3390452221-cdbjk   1/1       Running   2          23h
```

**Comment by RonnyMaas** [comment]
It would be nice to have operator create RWO PVC's for replica's when PVC_NAME is not specified instead of emptyDir for none shared volumes. 
I can imagine that it can be tricky if replica count is more then 1. But with a replica count of 1 it might be as easy as creating a second PVC with a suffix -replica that is used for the replica?

emptyDir requires a pod to stay on the same host. If it is relocated all data is lost/deleted.
A RWO PVC can follow the pod if it moves to a different host.

I have operator now working with openstack cinder but RWO PVC is only created for master and setting PVC_NAME will result in PVC not found.

**Comment by jmccormick2001** [comment]
thanks Vladimir, its likely a bug, I'll test this out and verify before the upcoming release.

**Comment by jmccormick2001** [comment]
@RonnyMaas thanks for your comment, I've been thinking about this for awhile actually, that being
is a Deployment the right construct to run the Postgres Replicas within, probably not due to what
you point out.  Using a Deployment forces the user to use a shared PVC (which might not work
for their file system type), or use emptyDir which as you state has limitations in that the data
is removed if the pod dies or relocates.  Dynamic provisioning would be a possibility for the
Replica(s) but not all file system types work with Dynamic provisioning.

So what I'll likely do, is change the way the PG replicas are created and just create
a standard Pod for each PG replica, this will allow for the PVC flexibility that users will want.  The
operator will let user's scale up the PG replicas as it currently does but just not using the Deployment
construct to make the scaling happen, instead the operator will implement the scaling which 
should not be too hard.

**Comment by RonnyMaas** [comment]
@jmccormick2001 sounds nice :)

Perhaps also PVC claim type can be used to determine strategy for replica's
If type contains Once (as in RWO) assume non shared storage and if it contains Many (as in RWM) assume shared storage.
Might need an extra parameter for replica storage.
But then it is possible to use RWO for master and an option to choose RWO of RWM for replica's
Drawback is that it will probably make the needed changes more difficult.

**Comment by jmccormick2001** [comment]
Vladimir, are there plans for ScaleIO to support dynamic storage provisioning?  I'm looking at how the replica's specify PVCs and was wondering if this was an option.

**Comment by jmccormick2001** [comment]
in the next release (coming soon), you'll see I've reworked the way storage is specified in the .pgo.yaml file, it is split now between master and replica storage configurations, you can also specify a STORAGE_TYPE of 'existing', 'emptydir', 'create', or 'dynamic'...my hope is with this new structure that the operator will be able to support any sort of storage configuration.

**Comment by jmccormick2001** [comment]
release 1.4 it now out, using 'create' storage type should take care of this issue as it will create a unique PVC for each postgres database and each replica.

**Comment by RonnyMaas** [comment]
Pvc's with Openstack Cinder appear to be working fine with 1.4 for master and replica's (Haven't tested all scenario's yet).

But master and replica end up on the same node/worker when i create a cluster with one replica.

I' am also having some issue's when draining a node for maintenance. Daemonsets are ignored by drain and forcing a drain will not relocate master to other node leaving only read-only cluster running during maintenance.

**Comment by RonnyMaas** [comment]
Also although cinder pv/pvc are attached to workers i have mount errors for volumes on workers. (will investigate)

**Comment by jmccormick2001** [comment]
there will be a "node selection" feature for sure, it will let you pin a replica to a specific node via the command line flag, but it will also by default try to place replicas on a different node than where the master is...my plan is to have this for the next release along with support for dynamic storage.

**Comment by jmccormick2001** [comment]
all, just pushed v1.5 that includes node affinity and a complete makeover for specifying
different storage types via the configuration file....I'll close this issue out since I think this
is covered by this release.  as always, thanks for the ideas and testing!
