### ISSUE TITLE
Upgrading PostgreSQL MAJOR VERSION - Unsupported NEW_VERSION

### ISSUE THREAD

**Issue by lbartnicki92** [CrunchyData/postgres-operator#2301]
Today I tested crunchy-upgrade image, in upgrade.json I have:

                       {
                            "name": "OLD_VERSION",
                            "value": "12"
                        },
                        {
                            "name": "NEW_VERSION",
                            "value": "13"
                        }
                    ]
                }
Is this correct? My pgcluster running PG 12.6 now on 4.6.1 Operator

After running run.sh:

kubectl logs upgrade-ncz4f -n pgo
Wed Feb 24 14:11:59 UTC 2021 INFO: Unsupported NEW_VERSION of 13.

------------------------------------------------------------
Glad to hear it's working.

The Operator does not handle major upgrades directly. There is documentation on how to use the [`crunchy-upgrade`](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/) container to handle this. Some others have reported how they have handled major upgrades through various GitHub issues that have been open.

_Originally posted by @jkatz in https://github.com/CrunchyData/postgres-operator/issues/2296#issuecomment-784430656_

**Comment by jkatz** [comment]
Hm that does appear to be a bug.

**Comment by jkatz** [comment]
This is fixed and backpatched down to 4.4. Thanks for reporting.

For interim guidance until the containers are released again, I would suggest picking one of the methods for upgrading that are described in the [PostgreSQL documentation](https://www.postgresql.org/docs/current/upgrading.html).
