### ISSUE TITLE
I Need Load balancing between replicas pods 

### ISSUE THREAD

**Issue by rghoubentini** [CrunchyData/postgres-operator#2302]
** Which example are you working with? **  : postgres operator 4.6.1

**What is the current behavior?**  : I created a cluster and I succeeded to scale up 
**What is the expected behavior?** : Load balancing between replicas pods 
* Where is this running ( Local , Cloud Provider) : Local 
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Platform (Docker, Kubernetes, OpenShift): Kubernetes

**Comment by jkatz** [comment]
This is created by default when you scale up a PostgreSQL cluster. It follows the name `<clusterName>-replica`.

Use `kubectl get svc` in your namespace to discover the Service that you need.
