### ISSUE TITLE
Allow installing cluster-wide from OperatorHub

### ISSUE THREAD

**Issue by ibotty** [CrunchyData/postgres-operator#2303]
I would like to install the operator cluster-wide from operator hub.

I can, of course, change the cluster roles after installation, but I am hesitant to do so:  they might get overwritten on an upgrade.

**Comment by jkatz** [comment]
Can you try the upgrade procedure and see if that in fact happens?

**Comment by cbandy** [comment]
@ibotty, when installed through OLM, the operator runs in the `dynamic` mode described in the document @jkatz linked. You can use the `pgo create namespace` and `pgo update namespace` commands to tell the operator which namespaces to watch for `pgcluster` objects. The operator has permission to watch any namespace, but namespaces created some other way won't be watched automatically.
