### ISSUE TITLE
How to recreate the pgbackrest-repo pvc

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#2304]
Hi, folks:

before a series of very big changes on one our databases, we needed to make the volume that stores the pgbackrest-repo way bigger than we need it to be in our normal operations..  so want we recreate the pgbackrest-repo pvc in any way, what should be the procedure for doing this kind of operations, or the best way is to recreate the cluster from a restore-from? if we can avoid recreate the cluster that would be great.. t's a big one..

Thanks in advance

**Comment by ValClarkson** [comment]
Hi IJOL,

I just wanted to revisit this issue and see if you have given v5 a try with the multi-repo setup for pgbackrest, this would allow you to have multiple repos available as well as sizes.  This would allow you to add additional repo(s) to your cluster as needed.  See the docs [here](https://access.crunchydata.com/documentation/postgres-operator/5.3.0/tutorial/backups/) for more information.
