### ISSUE TITLE
Crunchy postgres operator gets [504] Gateway Time-out

### ISSUE THREAD

**Issue by AbbasgoriS4** [CrunchyData/postgres-operator#2307]
**Describe the bug**
We are using the Postgres operator for more than a couple of months. we are using minio gcs gateway for taking scheduled backups. everything was working fine with --pgbackrest-backup-type=incr. recently we decided to change it full backup with retention policy. It even took 3 days of full backups but suddenly for the last two days it started failing with the following error. ERROR: [101]: [504] Gateway Time-out.

**The Postgres operator was installed using ansible**

**To Reproduce**
 I tried taking backups manually by running 
**pgo backup $CLUSTERNAME --backup-opts="--type=full" --backup-type=pgbackrest --pgbackrest-storage-type=s3 -n $NAMESPACE**

but the error is same. I even tried --backup-opts="--type=incr" still it failed.

**Expected behavior**
To take full backup to gcs using minio gateway without any error.

**Screenshots**

**Please tell us about your environment:**

* Operating System: Linux based node
* Where is this running ( Local, Cloud Provider): GCP
* Storage being used (NFS, Hostpath, Gluster, etc): GCE
* Container Image Tag: centos7-4.4.0
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): GKE (Kubernetes)
* Platform Version: 1.16.15-gke.7800

**Additional context**
Logs from backrest-backup pod
time="2021-03-01T08:19:54Z" level=info msg="pgo-backrest starts"
time="2021-03-01T08:19:54Z" level=info msg="debug flag set to false"
time="2021-03-01T08:19:54Z" level=info msg="backrest backup command requested"
time="2021-03-01T08:19:54Z" level=info msg="s3 flag enabled for backrest command"
time="2021-03-01T08:19:54Z" level=info msg="command to execute is [pgbackrest backup  --db-host=10.0.2.127 --db-path=/pgdata/$clustername --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2021-03-01T08:19:54Z" level=info msg="command is pgbackrest backup  --db-host=10.0.2.127 --db-path=/pgdata/$clustername --repo1-type=s3 --no-repo1-s3-verify-tls "
time="2021-03-01T08:22:45Z" level=error msg="command terminated with exit code 101"
time="2021-03-01T08:22:45Z" level=info msg="output=[]"
time="2021-03-01T08:22:45Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\nERROR: [101]: [504] Gateway Time-out\n]"
time="2021-03-01T08:22:45Z" level=error msg="command terminated with exit code 101"

**Comment by jkatz** [comment]
- Did anything change with your general networking?
- Do you have any NetworkPolicy objects in place?
- Did any of the global security (PSPs, SCCs, etc.) change?

**Comment by AbbasgoriS4** [comment]
There are no changes in network. We are running Postgres operator on two different clusters with same configuration(production and development clusters). on prod cluster we are running three database clusters and scheduled full backups which takes backups regularly without any issues. In development cluster we are running two database clusters which both the database backups are failing.

**Comment by jkatz** [comment]
This doesn't sound like a bug with the Postgres Operator, but likely some configuration change or networking issue in that environment.

Beyond that, you can look at the various [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) options available.

**Comment by AbbasgoriS4** [comment]
Ok the only differents between two Postgres operators is they have different minio endpoint urls. but I even tried redeploying the minio helm chart again.
