### ISSUE TITLE
Postgresql extensions support

### ISSUE THREAD

**Issue by kglebova** [CrunchyData/postgres-operator#2309]
Hi,
I'm using PGO v4.5.1
I want to install the cstore_fdw extension
This extension is very important for our database.
How can I do this?

**Comment by jkatz** [comment]
Why do you want `cstore_fdw`? The tables that are used in this extension do not work with physical backups.

**Comment by kglebova** [comment]
I have a database that uses this extension. I want to transfer this database to operator. Pgbackrest can backup data in sctore format (we use pgbackrest for backup). Only data cannot be replicated. But we don't use a replica

**Comment by kglebova** [comment]
We use this extension to store archived data. Сstore_fdw allows us to compress data
