### ISSUE TITLE
pgo 4.5.1: changing memory requirement of a cluster with replica (sync) will unset leader

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2311]
**I'm submitting a ...**

 
 - [ x] bug report
 
**What is the current behavior?**
Changing memory or cpu requirements of a pg cluster with **_replica_** **_(and sync replication)_** will set all pods as replica (no primary anymore).
In fact, this requires a restart of pods to apply the new requirement and his leads to this issue (related to https://github.com/CrunchyData/postgres-operator/issues/2132).

**If the current behavior is a bug, please provide the steps to reproduce:**
```
# create a cluster with replica and sync replication
$ pgo -n cfae-bit-cbcd create cluster jose-no-leader --replica-count=1 --sync-replication

# ensure we have a primary and a replica
$ pgo -n cfae-bit-cbcd show cluster jose-no-leader

# change memory and cpu requirement of the exporter
$ pgo -n cfae-bit-cbcd update cluster  jose-no-leader --exporter-memory=72Mi --exporter-memory-limit=72Mi --exporter-cpu=200m --exporter-cpu-limit=200m

# note: modifying the pgcluster CR directly leads to the same issue

# check the result --> no leader anymore
pgo -n cfae-bit-cbcd show cluster jose-no-leader

cluster : jose-no-leader (crunchy-postgres-ha:centos7-11.10-4.5.1)
        pod : jose-no-leader-6574fb56cd-c5l7n (Running) on worker15.ccp02.adr.admin.ch (2/2) (replica)
                pvc: jose-no-leader (8Gi)
        pod : jose-no-leader-yhux-88549c99-47kpf (Running) on worker15.ccp02.adr.admin.ch (2/2) (replica)
```

**What is the expected behavior?**
A Leader should be set back automatically

Currently, we have:
- to look at the <pg-cluster>-sync config map to find out the last known leader
- perform a pgo failover to set the leader (using the last-known one)

**Please tell us about your environment:**
 - Operating System: SUSE Linux Enterprise Server 15 SP1
 - Where is this running ( Local)
 - Storage being used (NFS)
 - Container Image Tag: crunchy-postgres-ha:centos7-11.10-4.5.1
 - PostgreSQL Version: 11.10
 - Platform (kubernetes 1.17.13 )

**Comment by jkatz** [comment]
I would also see if 4.6 helps with this situation with the introduction of "rolling updates" -- in fact, I think 4.6 does resolve this.

I would also refer back to the explanation in https://github.com/CrunchyData/postgres-operator/issues/2132#issuecomment-748719843 as well as the documentation.
