### ISSUE TITLE
Multi cluster sharding feature

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#2312]
Is there any solution for handling a sharding proccess in crunchy postgres operator?
I saw multi-cluster architecture considerations in docs, but only for HA and replication purposes.

Can you share your thoughts about this topic? Is there any plans for implementing some mechanisms for that?

Thank you!

**Comment by jkatz** [comment]
I've written about a similar topic here: https://info.crunchydata.com/blog/active-active-postgres-federation-on-kubernetes
