### ISSUE TITLE
is this supported?  4.5.2 -> 4.6.1

### ISSUE THREAD

**Issue by jfmatth** [CrunchyData/postgres-operator#2316]
Is upgrading from 4.5.2 to 4.6.1 supported?

I had to do ```pgo upgrade cluster1 --ignore-validation``` and then got errors on the startup

```
2021-03-04 01:37:22.664 GMT [9010] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/pgdata/sotb-v1-dev/postgresql.conf" line 26
2021-03-04 01:37:22.664 GMT [9010] FATAL:  configuration file "/pgdata/sotb-v1-dev/postgresql.conf" contains errors
```
Before i file a full bug report, just asking if it's supported

**Comment by jkatz** [comment]
Yes, upgrading between Operator 4.5.2 and 4.6.1 is supported.

However, if you are trying to upgrade between Postgres 12 and Postgres 13, you need to treat it as a major Postgres upgrade. That is not automatic.

**Comment by jfmatth** [comment]
HI @jkatz thanks for the response, and i'm continuing to learn about the operator upgrades and Postgres. 

Question - Does the operator have a major postgres path, or should i just follow the Postgres docs and use pg_dumpall, etc.?

thanks again for all the help here.
