### ISSUE TITLE
User postgres cannot login through pgbouncer despite docs claim

### ISSUE THREAD

**Issue by stevekerrison** [CrunchyData/postgres-operator#2319]
**Describe the bug**

[The docs say](https://access.crunchydata.com/documentation/postgres-operator/4.6.1/tutorial/pgbouncer/#connect-to-a-postgres-cluster-through-pgbouncer) that pgbouncer will allow any non-system user created via `pgo create user` to login, as well as the `postgres` superuser. However, the `get_auth` function excludes the `postgres` user by virtue of its query filtering out _all_ superusers, of which `postgres` is one:

```sql
CREATE OR REPLACE FUNCTION pgbouncer.get_auth(username text)
 RETURNS TABLE(username text, password text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT rolname::TEXT, rolpassword::TEXT
  FROM pg_authid
  WHERE
    NOT pg_authid.rolsuper AND
    NOT pg_authid.rolreplication AND
    pg_authid.rolcanlogin AND
    pg_authid.rolname <> 'pgbouncer' AND (
      pg_authid.rolvaliduntil IS NULL OR
      pg_authid.rolvaliduntil >= CURRENT_TIMESTAMP
    ) AND
    pg_authid.rolname = $1;
$function$
```

In my use case, having `postgres` user access via pgbouncer would be nice, but it can be worked around if needed. In any case, either the docs may need an update, or the function needs tweaking to provide an exception.

**To Reproduce**
1. `psql -h $BOUNCERHOST -p $BOUNCERPORT "... user=postgres"`
2. Observe "No such user" error after entering passowrd
    ```
    Password: 
    psql: error: ERROR:  no such user
    ```

**Expected behavior**

The [docs say](https://access.crunchydata.com/documentation/postgres-operator/4.6.1/tutorial/pgbouncer/#connect-to-a-postgres-cluster-through-pgbouncer):

> [...] note the types of users that can connect to PostgreSQL through `pgBouncer`:
> - Any regular user that’s created through `pgo create user` or a user that is not a system account.
> - The `postgres` superuser

**Please tell us about your environment:**

* Operating System: EC2 Linux
* Where is this running: EKS
* Storage being used: EBS
* Container Image Tag: Not sure, pgo `4.6.1` is being used
* PostgreSQL Version: 13.2
* Platform: K8S
* Platform Version: 1.19

Great piece of software, folks! 🍻

**Comment by stevekerrison** [comment]
I would suppose something like this would address the issue _if_ such a fix is desirable:

```sql
CREATE OR REPLACE FUNCTION pgbouncer.get_auth(username text)
 RETURNS TABLE(username text, password text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT rolname::TEXT, rolpassword::TEXT
  FROM pg_authid
  WHERE
    (
        (
            NOT pg_authid.rolsuper AND
            NOT pg_authid.rolreplication AND
            pg_authid.rolname <> 'pgbouncer'
        ) OR (
            pg_authid.rolname = 'postgres'
        )
    ) AND pg_authid.rolcanlogin AND (
      pg_authid.rolvaliduntil IS NULL OR
      pg_authid.rolvaliduntil >= CURRENT_TIMESTAMP
    ) AND
    pg_authid.rolname = $1;
$function$
```

**Comment by jkatz** [comment]
The docs claim that you can log into the postgres **database**:

> Connections to pgBouncer can now be passed along to the default postgres database. If you have a pre-existing pgBouncer Deployment, the most convenient way to access this functionality is to redeploy pgBouncer for that PostgreSQL cluster (pgo delete pgbouncer + pgo create pgbouncer).

re: [https://access.crunchydata.com/documentation/postgres-operator/4.6.1/releases/4.5.0/](https://access.crunchydata.com/documentation/postgres-operator/4.6.1/releases/4.5.0/)

Allowing the `postgres` user to log in via `pgbouncer` would effectively make the `pgbouncer` a superuser, and that may not be desirable for many environments.
