### ISSUE TITLE
Support custom CA/certificate in apiserver

### ISSUE THREAD

**Issue by stevekerrison** [CrunchyData/postgres-operator#2324]
**What is the motivation or use case for the change?**

Currently, PGO allows [clusters to be configured](https://access.crunchydata.com/documentation/postgres-operator/4.6.1/tutorial/tls/) with user-provided TLS secrets. However, the PGO API does not. The self-generated certs have `*` as the `CN` field and clients will not trust them, as [documented in the _Direct API Calls_ section](https://access.crunchydata.com/documentation/postgres-operator/4.6.1/advanced/direct-api-calls/) where the need to curl with `--insecure` set, despite using the provided CA cert and client key/cert.

Efforts to increase security on the API, such as https://github.com/CrunchyData/postgres-operator/issues/1978, will be somewhat dampened by the lack of cert/CA configuration, and suppressing TLS warnings or errors such as cert hostname mismatches is generally not good practice.

**Describe the solution you'd like**

There's probably two key things to look at:

1. Allow the current self-generated CA, server and client certs to be provided by the user instead, maybe through three new installer parameters:
   - `apiserver-ca-secret` containing `ca.crt` similar to that used when creating clusters with `--server-ca-secret`
   - `apiserver-server-secret` containing `tls.key` and `tls.crt` similar to `--server-tls-secret`
   - `apiserver-client-secret` containing another `tls.key` and `tls.crt` that'll be used by the client. Right now these all three certs have `CN=*` and `client-setup.sh` will fetch the client cert for the user, so this would be sufficient.
2. Strengthen the way the API uses client certs and match them to individual `pgouser`s:
   - Still provide `apiserver-ca-secret` and `apiserver-server-secret` options
   - If neither are provided, have an option to specify what the `CN` or `SAN` fields on the server cert should be, so that `curl` or other clients can run without `--insecure` mode or their equivalent.
   - Generate a client cert for the user `admin` with `CN=admin`
   - Add checks to API that verify the client presented by the cert has a key usage of `TLS Web Client Authentication` and that the CN matches the username presented in the request headers.
     - This mirrors what the clients will do: Verify the CN matches the host they're connecting to, and that the cert allows `TLS Web Server Authentication`
    
These can be done incrementally. The old behaviour could be preserved for upgraded installations. Option 2 then makes it possible to issue a unique client cert per user, either negating the need for the user/pass combination, or augmenting it in a 2FA-ish way (cert/key is something I have, password is something I know... provided I don't store key and password together).

If done properly, this will also allow PGO API to be issued a cert by an OS-trusted source (such as Let's Encrypt), whilst still using its own CA for authenticating clients. I note that the [`pgo` client docs](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/) do mention the `EXCLUDE_OS_TRUST` / `--exclude-os-trust` environment var/option, so support for well-known issuers should already be there (or the custom CA could also be installed in the trust pool, I guess).

**Please tell us about your environment:**

I'm assuming a K8S environment with cert-manager or similar, to make generating the custom TLS secrets easy. But any environment where the user has a way of generating/providing these to PGO at install time is fine.

**Comment by jkatz** [comment]
I believe this is already supported? Have you tried setting [`pgo_tls_ca_store`](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/tls/)?

**Comment by stevekerrison** [comment]
Ah yes, that covers part of it, thanks. So `pgo_tls_ca_store` can be used to customise the trust store. However, it looks like it's just a file path. Presumably one would have to modify the spec of the apiserver to mount an appropriate secret into that location, and I don't see an obvious way to do that from the installer YAML yet?

Beyond that, it is still missing the ability to control the operator API's server cert, I think?

Then there remains a question of whether the client certs should somehow be bound to the accounts they are used for, rather than "any valid cert from this list of CAs is fine"? This really boils down to whether you want to give people the option to follow the practice of avoiding sharing keys/certs between accounts.

**Comment by andrewlecuyer** [comment]
Since this issue involves the API server for and older version of Crunchy Postgres for Kubernetes, I am going to proceed with closing this specific issue.

If you have any additional questions, and/or if you would like to further discuss the v5 API's, please feel free to reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).

And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/

Thanks!
