### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by jfmatth** [CrunchyData/postgres-operator#2330]
I want to continue to upgrade as updates come out, but when moving from 4.5.x to 4.6.x I need to make sure the Postgres version stays at 12, how do i do that ?

I thought it was specifying the tag info on the upgrade, but that isn't working.

can you give an example of 4.5.x to 4.6 while keeping the postgres version at 12?

thanks,

**Comment by jkatz** [comment]
Did you try [pgo upgrade --ccp-image-tag=$TAG_VERSION](https://access.crunchydata.com/documentation/postgres-operator/4.6.1/pgo-client/reference/pgo_upgrade/)?

**Comment by jfmatth** [comment]
@jkatz thanks for the super quick response.

Yes i did
```
./pgo-461 upgrade sotb-v1-dev --ccp-image-tag centos8-12.6-4.5.1
```

but ended up getting CrashLoopBackoff since it couldn't find the image in the repo.

I found a table once that listed all this info, is that somewhere?

**Comment by jkatz** [comment]
Did you try `--ccp-image-tag centos8-12.6-4.5.2`?

**Comment by jfmatth** [comment]
I think i understand this process now.

Is there a table or docs pointing to all the image tags and what versions of Postgres?

I think the tag shows the version of postgres and operator, right?

**Comment by jfmatth** [comment]
Well, so much for understanding this, but here's more info for you @jkatz 

Given the original 4.5.2 cluster
```
jfmatth@Dad-dell5580:~/development/pgo$ ./pgo-461 show cluster  --all

cluster : sotb-v2-dev (crunchy-postgres-ha:centos8-12.6-4.5.2)
        pod : sotb-v2-dev-qaje-59f59ff469-9qgm8 (Running) on microk8-server (1/1) (replica)
                pvc: sotb-v2-dev-qaje (6Gi)
        pod : sotb-v2-dev-f4758d4d8-kkssr (Running) on microk8-server (1/1) (primary)
                pvc: sotb-v2-dev (6Gi)
        resources : CPU: 500m Memory: 4Gi
        deployment : sotb-v2-dev-backrest-shared-repo
        deployment : sotb-v2-dev
        deployment : sotb-v2-dev-qaje
        service : sotb-v2-dev - ClusterIP (10.152.183.57) ExternalIP (192.168.1.103) - Ports (2022/TCP, 5432/TCP)
        service : sotb-v2-dev-replica - ClusterIP (10.152.183.229) ExternalIP (192.168.1.105) - Ports (2022/TCP, 5432/TCP)
        pgreplica : sotb-v2-dev-qaje
        labels : pgouser=admin service-type=LoadBalancer crunchy-pgbadger=false crunchy-pgha-scope=sotb-v2-dev deployment-name=sotb-v2-dev name=sotb-v2-dev pgo-backrest=true pgo-version=4.5.2 autofail=true crunchy-postgres-exporter=false pg-cluster=sotb-v2-dev pg-pod-anti-affinity= workflowid=ba5287de-e5e3-4eba-9076-f6fa02267d79
```
I upgraded to 4.6.1
```
jfmatth@Dad-dell5580:~/development/pgo$ k delete -f postgres-operator-452.yml
serviceaccount "pgo-deployer-sa" deleted
clusterrole.rbac.authorization.k8s.io "pgo-deployer-cr" deleted
configmap "pgo-deployer-cm" deleted
clusterrolebinding.rbac.authorization.k8s.io "pgo-deployer-crb" deleted
job.batch "pgo-deploy" deleted
jfmatth@Dad-dell5580:~/development/pgo$ k apply -f postgres-operator-461.yml
serviceaccount/pgo-deployer-sa created
clusterrole.rbac.authorization.k8s.io/pgo-deployer-cr created
configmap/pgo-deployer-cm created
clusterrolebinding.rbac.authorization.k8s.io/pgo-deployer-crb created
job.batch/pgo-deploy created
```

I then tried to upgrade the existing cluster to 4.6.1 but keeping the image-tag for 4.5.2
```
jfmatth@Dad-dell5580:~/development/pgo$ ./pgo-461 upgrade sotb-v2-dev --ccp-image-tag centos8-12.6-4.5.2
All active replicas will be scaled down and the primary database in this cluster will be stopped and recreated as part of this workflow!
WARNING: Are you sure? (yes/no): yes
created upgrade task for sotb-v2-dev
```

Sadly, same issue
```
sotb-v2-dev-backrest-shared-repo-6f9657f577-p69s7   0/1     ImagePullBackOff    0          45s
```
```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  7m29s                   default-scheduler  Successfully assigned database/sotb-v2-dev-backrest-shared-repo-6f9657f577-p69s7 to microk8-server
  Normal   Pulling    5m53s (x4 over 7m28s)   kubelet            Pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-12.6-4.5.2"
  Warning  Failed     5m52s (x4 over 7m27s)   kubelet            Error: ErrImagePull
  Warning  Failed     5m52s (x4 over 7m27s)   kubelet            Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-12.6-4.5.2": rpc error: code = NotFound desc = failed to pull and unpack image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-12.6-4.5.2": failed to resolve reference "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-12.6-4.5.2": registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-12.6-4.5.2: not found
  Warning  Failed     5m28s (x7 over 7m27s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    2m24s (x20 over 7m27s)  kubelet            Back-off pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-12.6-4.5.2"
```

Hope this helps.

**Comment by jfmatth** [comment]
In digging in a little more between 4.5.x and 4.6.x I've noticed the container images for the backrest are very different

I built a 4.5.1 cluster, upgraded that to 4.5.2 - No issues
I build a 4.5.2 cluster
I then upgraded 4.5.2 to 4.6.1 and then built a cluster

Here are the Image: descriptors on a describe of the various cluster backrest pods

4.5.2
```
jfmatth@Dad-dell5580:~/development/pgo$ k describe pod/test452-backrest-shared-repo-64656cbf57-62tcc -n database | grep
Image
    Image:          registry.developers.crunchydata.com/crunchydata/pgo-backrest-repo:centos8-4.5.2
```
4.6.1
```
jfmatth@Dad-dell5580:~/development/pgo$ k describe pod/test461-backrest-shared-repo-699f48bbb6-lc48r -n database | grep Image
    Image:          registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-13.2-4.6.1
```

Notice that 4.5.x uses ```pgo-backrest-repo``` and 4.6.x uses ```crunch-pgbackrest-repo```

Does this mean that it's not possible to upgrade from 4.5.x to 4.6.x even though we specify the --ccp-image-tag?  Seems like it, since it's failing to pull the backrest container of the correct name as shown above?

Not sure if this is helping, just trying to fully understand why it's failing.

thanks,

**Comment by beer1970** [comment]
is it possible to run 4.6.1 operator with a 4.5.2 image?  I understand you want to stay on version 12 but when I upgrade with

` pgo upgrade --ccp-image-tag=centos8-12.6-4.6.1 basic-cluster -n basic`

You will get the version 12 with the 4.6.1 , does that fix your issue?

It works mostly, sometimes I get a Crashloopback container database

**Comment by jfmatth** [comment]
@beer1970 Oscar, thank you for the reply.

That is basically what I'm looking for, but more important, where did you get the image tag?  I'm looking for the table that shows all the available image tags for a particular version.

Your logic makes sense and again, thank you.  I'll try this out today.

**Comment by beer1970** [comment]
On https://www.crunchydata.com/developers/download-postgres/containers/postgresql12 I can see the tags on the right , e.g.

`docker pull registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-12.6-4.6.1`

**Comment by jfmatth** [comment]
I tried creating a new cluster with that same ccp-image-tag and received the same issues :(

**Comment by beer1970** [comment]
I see on the end of your error
`dial tcp: lookup registry.developers.crunchydata.com: Temporary failure in name resolution
  Warning  Failed     15s (x3 over 103s)  kubelet            Error: ImagePullBackOff`
sounds like a connection issue with DNS

I tried again and no error
`pgo upgrade --ccp-image-tag centos8-12.6-4.6.1 basic-cluster -n o4p-ds-pg-operator
All active replicas will be scaled down and the primary database in this cluster will be stopped and recreated as part of this workflow!
WARNING: Are you sure? (yes/no): yes
created upgrade task for basic-cluster

NAME↑      IMAGE                                                                                        READY  STATE     INIT     RS PROBES(L:R)   CPU  MEM  %CPU  %MEM PORTS   AGE     │
│ database   registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-12.6-4.6.1   true   Running   false     0 off:off       n/a  n/a   n/a   n/a 2022    70s`

**Comment by jkatz** [comment]
I agree, that sounds like an issue with DNS resolution.

I don't believe there are any discovered programmatic issues with the upgrade method, so I am going to close this out.

**Comment by jfmatth** [comment]
Just to give you my findings, YES, my cluster was broken somehow and not sure why.  

After a reboot, all examples and helpful advice here worked 100%

Thanks again everyone!
