### ISSUE TITLE
crunchy 4.6.1 - operator is unable to reconcile RBAC resource

### ISSUE THREAD

**Issue by ckvtvm-arch** [CrunchyData/postgres-operator#2331]
** Which example are you working with? **

creating a cluster

**What is the current behavior?**

time="2021-03-12T05:59:06Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-target-role\" is forbidden: user \"system:serviceaccount:pgo:postgres-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:pgo\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"apps\"], Resources:[\"replicasets\"], Verbs:[\"get\" \"list\" \"watch\" \"create\" \"patch\" \"update\" \"delete\" \"deletecollection\"]}" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.6.1

**What is the expected behavior?**

cluster created and test successful

**Other information** (e.g. detailed explanation, related issues,  etc)

cluster created , but test shows as down

**Please tell us about your environment:**

* Operating System: Mac
* Where is this running ( Local , Cloud Provider) - cloud
* Storage being used (NFS, Hostpath, Gluster, etc): pvc
* Container Image Tag: 4.6.1
* PostgreSQL Version: 4.6.1
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 4.5

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-target-role
  namespace: pgo
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/pgo/roles/pgo-target-role
  uid: f2125981-438c-4eba-94d1-a1fa10be933b
  resourceVersion: '5352974683'
  creationTimestamp: '2021-01-25T21:33:29Z'
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
      - deletecollection
    apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - pods
      - pods/exec
      - pods/log
      - replicasets
      - secrets
      - services
      - persistentvolumeclaims
  - verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
      - deletecollection
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
      - deletecollection
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
      - deletecollection
    apiGroups:
      - crunchydata.com
    resources:
      - pgclusters
      - pgpolicies
      - pgtasks
      - pgreplicas

**Comment by ckvtvm-arch** [comment]
time="2021-03-12T06:49:06Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-target-role\" not found" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:112" version=4.6.1

**Comment by jkatz** [comment]
It sounds like you are missing a permission somewhere. If you are running in a more restrictive namespace mode, you will need to ensure all the appropriate permissions are granted.

This is covered under the [RBAC Reconciliation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/#rbac-reconciliation) section of the documentation.
