### ISSUE TITLE
Change BackrestStorage on running cluster possible?

### ISSUE THREAD

**Issue by ggrames** [CrunchyData/postgres-operator#2332]
**Which example are you working with?**
Running cluster in openshift 4.6 with postgres operator 4.5.1
The cluster uses 2 pvc's 
One for the postgres and one for the backrest
Currently the backrest pvc uses the default thin storage class.

**What is the current behavior?**
I want to change this to another custom one without recreation of the cluster. The custom storage works when i create a new cluster.
But how to change the pvc of the backrest to the custom one.
The postgres pvc itself should be untouched.

**What is the expected behavior?**
Running backrest pvc on other storage class. It can be also a new pvc with the new storage class.

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System:
Openshift 4.6
* Where is this running ( Local , Cloud Provider)
Vsphere VM's
* Storage being used (NFS, Hostpath, Gluster, etc):
vsphere storage provider / nfs storage
* Container Image Tag:
registry.developers.crunchydata.com/crunchydata/postgres-operator:centos7-4.5.1
* PostgreSQL Version:
centos7-12.5-4.5.1
* Platform (Docker, Kubernetes, OpenShift):
Openshift
* Platform Version:
4.6

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName

`
oc describe pod test-postgresql-backrest-shared-repo-66f96496b4-rllwb
Name:         test-postgresql-backrest-shared-repo-66f96496b4-rllwb
Namespace:    pgo-test
Priority:     0
Node:         ocp-infra-02.ocp.intern.mydomain.at/10.100.250.57
Start Time:   Fri, 12 Mar 2021 10:24:11 +0100
Labels:       name=test-postgresql-backrest-shared-repo
              pg-cluster=test-postgresql
              pg-pod-anti-affinity=preferred
              pgo-backrest-repo=true
              pod-template-hash=66f96496b4
              service-name=test-postgresql-backrest-shared-repo
              vendor=crunchydata
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.128.4.79"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.128.4.79"
                    ],
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: pgo
Status:       Running
IP:           10.128.4.79
IPs:
  IP:           10.128.4.79
Controlled By:  ReplicaSet/test-postgresql-backrest-shared-repo-66f96496b4
Containers:
  database:
    Container ID:   cri-o://fd817df1282fa1501b98136b9ca713afa152ab9505db6a40080fe1ea2a833ac3
    Image:          registry.developers.crunchydata.com/crunchydata/pgo-backrest-repo:centos7-4.5.1
    Image ID:       registry.developers.crunchydata.com/crunchydata/pgo-backrest-repo@sha256:b51d28c30b3bc7ebcbcbf5acee07626269670f76da6b4429b73ac0ce5764cb4f
    Port:           2022/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 12 Mar 2021 10:24:25 +0100
    Ready:          True
    Restart Count:  0
    Requests:
      memory:  48Mi
    Environment:
      PGBACKREST_STANZA:           db
      SSHD_PORT:                   2022
      PGBACKREST_DB_PATH:          /pgdata/test-postgresql
      PGBACKREST_REPO_PATH:        /backrestrepo/test-postgresql-backrest-shared-repo
      PGBACKREST_PG1_PORT:         5432
      PGBACKREST_LOG_PATH:         /tmp
      PGBACKREST_PG1_SOCKET_PATH:  /tmp
      PGBACKREST_DB_HOST:          test-postgresql
    Mounts:
      /backrestrepo from backrestrepo (rw)
      /etc/pgbackrest/conf.d from pgbackrest-config (rw)
      /sshd from sshd (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  sshd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  test-postgresql-backrest-repo-config
    Optional:    false
  backrestrepo:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-postgresql-pgbr-repo
    ReadOnly:   false
  pgbackrest-config:
    Type:                Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:       test-postgresql-config-backrest
    ConfigMapOptional:   0xc001cc9d79
    SecretName:          test-postgresql-config-backrest
    SecretOptionalName:  0xc001cc9d7a
QoS Class:               Burstable
Node-Selectors:          <none>
Tolerations:             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                         node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                         node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason                  Age   From                     Message
  ----    ------                  ----  ----                     -------
  Normal  Scheduled               28m   default-scheduler        Successfully assigned pgo-test/test-postgresql-backrest-shared-repo-66f96496b4-rllwb to ocp-infra-02.ocp.intern.mydomain.at
  Normal  SuccessfulAttachVolume  28m   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-af8eb334-c963-45af-a391-e72c9707d8a5"
  Normal  AddedInterface          28m   multus                   Add eth0 [10.128.4.79/23]
  Normal  Pulled                  28m   kubelet                  Container image "registry.developers.crunchydata.com/crunchydata/pgo-backrest-repo:centos7-4.5.1" already present on machine
  Normal  Created                 28m   kubelet                  Created container database
  Normal  Started                 28m   kubelet                  Started container database
`

 kubectl describe pvc

`
oc describe pvc test-postgresql-pgbr-repo
Name:          test-postgresql-pgbr-repo
Namespace:     pgo-test
StorageClass:  thin
Status:        Bound
Volume:        pvc-af8eb334-c963-45af-a391-e72c9707d8a5
Labels:        pg-cluster=test-postgresql
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/vsphere-volume
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    test-postgresql-backrest-shared-repo-66f96496b4-rllwb
Events:
  Type    Reason                 Age   From                         Message
  ----    ------                 ----  ----                         -------
  Normal  ProvisioningSucceeded  40m   persistentvolume-controller  Successfully provisioned volume pvc-af8eb334-c963-45af-a391-e72c9707d8a5 using kubernetes.io/vsphere-volume
`

 kubectl get nodes

`
oc get nodes

NAME                                STATUS   ROLES    AGE    VERSION

ocp-compute-01.ocp.intern.mydomain.at   Ready    worker   308d   v1.19.0+e405995

ocp-compute-02.ocp.intern.mydomain.at   Ready    worker   308d   v1.19.0+e405995

ocp-compute-03.ocp.intern.mydomain.at   Ready    worker   308d   v1.19.0+e405995

ocp-compute-04.ocp.intern.mydomain.at   Ready    worker   308d   v1.19.0+e405995

ocp-compute-05.ocp.intern.mydomain.at   Ready    worker   308d   v1.19.0+e405995

ocp-compute-06.ocp.intern.mydomain.at   Ready    worker   308d   v1.19.0+e405995

ocp-control-01.ocp.intern.mydomain.at   Ready    master   308d   v1.19.0+e405995

ocp-control-02.ocp.intern.mydomain.at   Ready    master   308d   v1.19.0+e405995

ocp-control-03.ocp.intern.mydomain.at   Ready    master   308d   v1.19.0+e405995

ocp-infra-01.ocp.intern.mydomain.at     Ready    infra    308d   v1.19.0+e405995

ocp-infra-02.ocp.intern.mydomain.at     Ready    infra    308d   v1.19.0+e405995

ocp-infra-03.ocp.intern.mydomain.at     Ready    infra    308d   v1.19.0+e405995

`

 kubectl log yourPodName

**Comment by jkatz** [comment]
Presently this is a manual task but we are planning to do work in this area for the 4.7.0 release of the Operator.

**Comment by ggrames** [comment]
OK. Thanks.
At the moment my idea is to usw 2 times pgo create cluster
pgo create cluster test1 --restore-from test ......
pgo deleted cluster test .....
pgo create cluster test --restore-from test1 ......  Here with the custom storage dir the backrest

Do you have a other or better idea?
