### ISSUE TITLE
Restore with pgbackrest and Create Cluster based on Backup fails partially

### ISSUE THREAD

**Issue by Schmaetz** [CrunchyData/postgres-operator#2336]
Describe the bug
When restoring a cluster with PGBackrest or creating a new cluster based on backup, errors often occur.
These variants were tested:

Restore:
> pgo restore test --pitr-target="2021-03-09 08:54:07.062997+01" --backup-opts="--type=time --set=20210309-075406F"
> pgo restore test --pitr-target="2021-03-09 06:06:04.062997+00" --backup-opts="--type=time"
> pgo restore pgo-ssp-owncluster-dev --backup-opts="--set=20210308-101351F"

Create:
> pgo create cluster test-0 --restore-from test --restore-opts "--type=time --target='2021-03-09 06:06:04.062997+00'"

Pitr fails every time. Using snapshots only partially.
I attach the log as an attachment.

To Reproduce

For Restore:
Create cluster
restore via initial snapshost
See error from bootstrap-Pod
Expected behavior
It is to be expected that the restore is carried out successfully every time.

For Create Cluster:
Create a cluster based on an existing backup

Please tell us about your environment:

Operating System:
Where is this running ( Local, Cloud Provider): Cloud-Provider
Storage being used (NFS, Hostpath, Gluster, etc): own Storage
Container Image Tag: crunchy-postgres-ha:centos8-12.6-4.6.1
PostgreSQL Version: 12.6
Platform (Docker, Kubernetes, OpenShift): Openshift
Platform Version: 4.6.18
Additional context
[log.txt](https://github.com/CrunchyData/postgres-operator/files/6157302/log.txt)
[log (3).txt](https://github.com/CrunchyData/postgres-operator/files/6157304/log.3.txt)
[log (2).txt](https://github.com/CrunchyData/postgres-operator/files/6157306/log.2.txt)
[log (4).txt](https://github.com/CrunchyData/postgres-operator/files/6157307/log.4.txt)

Many greetings

**Comment by jkatz** [comment]
There seem to be a confluence of things occurring here. The first log indicates that there was an incorrect option passed into the restore command so it could not complete.

With the others, I would need more information that would be contained within the PostgreSQL logs themselves, which are found in the `pg_log` directory within `/pgdata/<clustername>`

Are there valid backups? What does `pgo show backup test` output?

**Comment by Schmaetz** [comment]
Hi, 
sorry for my late reply. 
I have now tried various things and it still goes wrong sometimes. 

In the following attempt, I communicate directly with the API (without pgo.client). For this, I have recorded the communication of the pgo client during the restore command using wireshark and taken over the necessary parameters. 

The following data was used: 
URL: https://IP_ADRESSE/restore
Data:
{"FromCluster":"pgo-benchmark-test-exp","PITRTarget":"2021-03-22 10:29:08.000000+01","RestoreOpts":"--type=time --set=20210322-092855F","BackrestStorageType":"","ClientVersion":"4.6.1","Namespace":"exp"}

-> Show Backup: 
cluster: pgo-benchmark-test-exp
storage type: posix

stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1)

        full backup: 20210322-092855F
            timestamp start/stop: 2021-03-22 10:28:55 +0100 CET / 2021-03-22 10:29:08 +0100 CET
            wal start/stop: 000000010000000000000004 / 000000010000000000000004
            database size: 54.1MiB, backup size: 54.1MiB
            repository size: 6.2MiB, repository backup size: 6.2MiB
            backup reference list:

        incr backup: 20210322-092855F_20210323-115542I
            timestamp start/stop: 2021-03-23 12:55:42 +0100 CET / 2021-03-23 12:55:45 +0100 CET
            wal start/stop: 0000000100000000000000EA / 0000000100000000000000EA
            database size: 54.5MiB, backup size: 14.7MiB
            repository size: 6.2MiB, repository backup size: 1.7MiB
            backup reference list: 20210322-092855F

The Bootstrap Pod goes into error state shortly after start-up and shuts down. The following Pod runs permanently with the familiar error message: 

[0;32mThu Mar 25 09:01:06 UTC 2021 INFO: Correct the issue, remove '/pgdata/pgo-benchmark-test-exp.initializing', and try again[0m
[0;32mThu Mar 25 09:01:06 UTC 2021 INFO: Your data might be in: /pgdata/pgo-benchmark-test-exp_2021-03-25-08-54-00[0m
[0;33mThu Mar 25 09:01:16 UTC 2021 WARN: Detected an earlier failed attempt to initialize[0m

I have attached the error log. 

Many greetings and thanks for your help
[log (7).txt](https://github.com/CrunchyData/postgres-operator/files/6203354/log.7.txt)

**Comment by Schmaetz** [comment]
Hi @jkatz ,
it would be great if you could help me with this. 
The behavior remains the same and an error in the transferred data I can not discover. 

Best regards

**Comment by andrewlecuyer** [comment]
Since this issue involves restore functionality from an older version of Crunchy Postgres for Kubernetes (including an older version of pgBackRest), I am proceeding with closing this issue.

If you have any additional questions, and/or if you would like to further discuss Disaster Recovery (DR) scenarios, processes, functionality, etc. with Crunchy Postgres for Kubernetes v5, please feel free to reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).

And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/

Thanks!
