### ISSUE TITLE
Operator ClusterRolebinding provides elevated cluster access to namespace admins

### ISSUE THREAD

**Issue by ctrought** [CrunchyData/postgres-operator#2339]
**Describe the bug**
When you install the crunchy postgresql operator to a namespace it creates a `ClusterRolebinding` referencing the `ClusterRole` `postgresoperator.<version>`, the rolebinding includes the `postgres-operator` serviceaccount from the installed namespace. This cluster scoped rolebinding provides access to get, create, patch, delete many resources in the cluster including but not limited to namespaces, pods, secrets, persistentvolumes as well as everything in the crunchydata.com api group. Because the operator service account is exposed to admins in the namespace, they can obtain the token in its secret and login to the service account inheriting the permissions provided by the `ClusterRolebinding` & `ClusterRole`.

**To Reproduce**
1. Install the crunchy postgresql operator into a tenant namespace
2. Create an account or login to an existing account that only has the admin role scoped to that namespace
3. Grab the operator service account token `TOKEN=$(oc sa get-token postgres-operator)`
4. Login using the token `oc login --token="$TOKEN"`
5. The namespace admin (now logged in as postgres-operator SA) has access to create/delete/view any namespace, pod, deployment, secret, and all the resources mentioned in the `postgres-operator` `ClusterRole` across the entire cluster.

**Expected behavior**
Since the operator is installed in each target namespace, it should not rely on a `ClusterRoleBinding`. The operator should instead use a `Rolebinding` and `Role` managed in each installed namespace so that privileges are scoped to it and users cannot gain access to the entire cluster. There might also be some resources included in the `ClusterRole` that are not required by the operator.

**Please tell us about your environment:**
* Where is this running ( Local, Cloud Provider): Local
* Container Image Tag: `crunchydata/postgres-operator:centos8-4.6.1`
* PostgreSQL Operator Version: 4.6.1
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.6.16

**Additional context**
Namespace admins can delete everything and take down your cluster 🗡️ 💀

**Comment by jkatz** [comment]
This is a feature. The Postgres Operator has several different namespace modes, which are documented here:

[Namespace Management](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/).

While the dynamic mode is the default (which again, is documented), you can further lock this down to being `readonly` which only has read-only cluster-level privileges, or `restricted`, which eliminates the cluster roles.

Installing via OLM requires a dynamic namespace mode -- other installation methods allow you to install in `readonly` or `restricted` from the get go.

**Comment by ctrought** [comment]
Thanks @jkatz, I missed that. 

> Installing via OLM requires a dynamic namespace mode

Does that mean PG instances must be created/managed by a cluster-admin, and this installation mode via OLM would not be ideal for multi-tenant environments?

What I've seen from operators that watch globally, would be configured something like the below.

```
    olm.targetNamespaces: ''
    olm.operatorNamespace: openshift-operators-redhat
```

**Comment by jkatz** [comment]
> Does that mean PG instances must be created/managed by a cluster-admin

No. We have many instances of the Operator running where the end users are unprivileged and are able to manage their own Postgres instances.

You can also install with OLM and further lock down who/what/how the different namespaces are managed per the [aforementioned guide](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/). I know of many customers and users who are running the Operator successfully in a multi-tenant setup.

We'll look into some of the additional OLM settings, though the install itself is designed to be "easy to get started" while showcasing the maximum number of features. The docs provide further guidance for how to lock things down.
