### ISSUE TITLE
Pod Anti Affinity tweaks

### ISSUE THREAD

**Issue by darren1713** [CrunchyData/postgres-operator#2342]
The current pod anti affinity applies the anti affinity settings to the database master node, the replica nodes, backrest, and pgbouncer, creating an unexpected node resource unavailability. The anti affinity settings are clearly needed to ensure the master/replica nodes are kept separate, but is it intentional that pgbouncer and backrest are also part of the same anti affinity settings? We found this out by creating a 3 note kubernetes cluster, and deploying a cluster with 2 replicas. Because the master node is created first, then pgbouncer, then backrest, and then the 2 replicas. Only the master, pgbouncer, and backrest started before the 2 replicas were not scheduled.

The documentation here: https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/ under "How The Crunchy PostgreSQL Operator Uses Pod Anti-Affinity" specifically states that the anti affinity rules are not applied to pgbouncer and backrest, but they are. I had a read through v4.6.1 and 4.6.2 release notes but this fix was not mentioned.

The expected behavior is for the anti affinity settings to apply to the database nodes (master/replicas) and not to backrest/pgbouncer. Although it would make sense for them to not be scheduled on the active master node. It is quite easy to obtain the expected behavior by 1) removing the antiaffinity settings from backrest/pgbouncer and 2) adding the following to the podAntiAffinity key:

              - key: pgo-pg-database
                operator: In
                values:
                - "true"

Had a look at the code and it's straightforward, and then started running through all of the variants in my mind of "well then how do you tell pgbouncer and backrest to run" and "you might want to force those to a non-master node" and "maybe some deployments really want it this way." The best option is likely a configuration setting for anti-affinity of the database nodes, and a separate anti-affinity configuration setting for backrest/pgbouncer. 

* Operating System: Linux
* Where is this running ( Local, Cloud Provider): GKE
* Storage being used (NFS, Hostpath, Gluster, etc): K8 storage
* Container Image Tag: 4.6.0
* PostgreSQL Version: 13
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.17

Appreciate your input/background on this. Cheers

**Comment by jkatz** [comment]
You can set specific pod anti-affinity rules just for pgBackRest and pgBouncer.

- [Pod Anti-Affinity Specification](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/#pod-anti-affinity-specification)
- [`pgo create cluster` flags](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) -- find the ones that start with `--pod-anti-affinity`

Regarding the documentation on the HA architecture page, it specifically states:

```
By default, when a new PostgreSQL cluster is created using the PostgreSQL Operator, pod anti-affinity rules will be applied to any deployments comprising the full PG cluster.
```

and goes on the list that this includes the `pgBackRest` and `pgBouncer` containers. It further states that in the default setup:

```
When required is utilized for the default pod anti-affinity, a separate node is required for each deployment listed above comprising the PG cluster. This ensures that the cluster remains highly-available by ensuring that node failures do not impact any other deployments in the cluster. However, this does mean that the PostgreSQL primary, each PostgreSQL replica, the pgBackRest repository and, if deployed, the pgBouncer Pods will each require a unique node, meaning the minimum number of Nodes required for the Kubernetes cluster will increase as more Pods are added to the PostgreSQL cluster. Further, if an insufficient number of nodes are available to support this configuration, certain deployments will fail, since it will not be possible for Kubernetes to successfully schedule the pods for each deployment.
```

However, as stated above, there are ways to tweak it for those individual Deployments.

Perhaps there could be an addendum in the architecture docs to be clear that you can tweak the formula for pgBackRest + pgBouncer, but from a functionality standpoint, this should be satisfied.

**Comment by jkatz** [comment]
I updated the documentation to be clearer on this point. Again as I understand it, this appears to be already supported, but please feel free to correct me if I'm mistaken.

**Comment by darren1713** [comment]
Thank you! Testing now by specifically creating the separate anti-affinity settings for the DB pods, pgbouncer, and backrest, and fully expecting them to play nice now. Thanks for the pointers and updated docs. Will update again if I run across any unintended behaviors. Cheers
