### ISSUE TITLE
Pgcluster BackrestStorage vs backrestS3... attributes

### ISSUE THREAD

**Issue by aceeric** [CrunchyData/postgres-operator#2345]
Using 4.6.1, we've configured a `Pgcluster` CR with:
```
...
name: crunchy-cluster
...
backrestS3Bucket: zzzz
backrestS3Region: default
backrestS3Endpoint: rook-ceph-rgw-object-store
backrestS3URIStyle: path
backrestS3VerifyTLS:  "false"
backrestStorageTypes:
- s3
...
```

And, in addition, we _do not_ specify the `BackrestStorage` stanza. The database never progresses, and when I `kubectl describe pgcluster` I get:

```
...
Events:
  Type    ... Message
  -----   ... --------
  Warning ... persistentvolumeclaim "crunchy-cluster-pgbr-repo" not found
```

Since I am specifying - through the `pgbackrestS3...` set of attributes - that I want S3 to be used for backrest storage, why am I also required to specify a `BackrestStorage` PVC? This would seem to be redundant and - in fact - I don't want a PVC to be used.

But it looks like the `BackrestStorage` stanza is expected to be populated by the operator.

**Comment by jkatz** [comment]
Yup, for now you need to specify it. You can set the PVC size to be small if it's not going to be used.

This can/may/will change in the future, but for now this is the current behavior.
