### ISSUE TITLE
scheduled backup looks for the wrong pg-backrest pod

### ISSUE THREAD

**Issue by OmriDim** [CrunchyData/postgres-operator#2346]
**Describe the bug**
on multiple projects, our sceduled backup jobs fails, the pod's log shows an error message saying  the backrest pod has not been found, followed by a pod name that is not matched with the current cluster's backrest pod.
logs:  
time="2021-03-21T20:10:54Z" level=info msg="command is pgbackrest backup --type=full --db-host=<ip> --db-path=<db/path> --repo-type=s3"
time="2021-03-21T20:10:54Z" level=info msg="pods \"<wrong-backrest-pod-name>\" not found"

**To Reproduce**
pgo --debug create scedule --scedule=\"0 2 * * *\" --scedule-type=pgbackrest --pgbackrest-type=full <cluster-name> -n <namespace> --pgbackrest-storage-type 's3' --apiserver-url <api-url> --scedule-opts='--repo1-retention-full=14'

**Expected behavior**
successful back up of the cluster

**Please tell us about your environment:**
crunchy version 4.5.1 
Where is this running ( Local, Cloud Provider): on prem openshift
Container Image Tag: centos7-12.5
PostgreSQL Version: 12.5
Platform (Docker, Kubernetes, OpenShift): openshift
Platform Version: openshift 4.5

thank you!

**Comment by jkatz** [comment]
My hunch is that this is environmental, though could be related to a [4.5.2](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.2) bug fix.

- Can you take a backup with `pgo backup`?
- Are there phantom pgBackRest Pods in your namespace?
- Are there any additional security settings that may be preventing a proper connection from being made?
- Does archiving still work between you Postgres primary and the pgBackRest repository?

There was also a bug fix in [4.5.2](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.2) around scheduled backups:

> Only attempts to start scheduled backups in running pgBackRest repository Pods.
