### ISSUE TITLE
Support updating cluster with tls information

### ISSUE THREAD

**Issue by ibotty** [CrunchyData/postgres-operator#2347]
**Describe the bug**
It's possible to create a cluster with TLS, but not possible to update it.  There is no `--server-tls-secret` option for `update cluster` and setting the secrets in `pgcluster` crd does not change the running cluster.

**Comment by jkatz** [comment]
This is a known enhancement request. Thanks!

**Comment by jkatz** [comment]
This is fully implemented for the upcoming 4.7 release.
