### ISSUE TITLE
database container - status not ready after few days of running the service

### ISSUE THREAD

**Issue by ckvtvm-arch** [CrunchyData/postgres-operator#2350]
After i install the operator, the services run for few days and then started having the issue with database container due to which the pgbadger is not available.

I am not sure whether this happens after each auto upgrade of the operator .

I used to delete the cluster and proceed with recreation. Please advise 

xxxxx@xxxx ~ % oc describe pod vantage-postgresql-db-6795d7dfdc-6dvtg
Name:         vantage-postgresql-db-6795d7dfdc-6dvtg
Namespace:    vantage-dev
Priority:     0
Node:         va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das/30.118.44.54
Start Time:   Wed, 24 Mar 2021 21:54:40 -0400
Labels:       crunchy-pgha-scope=vantage-postgresql-db
              crunchy-postgres-exporter=true
              deployment-name=vantage-postgresql-db
              name=vantage-postgresql-db
              pg-cluster=vantage-postgresql-db
              pg-pod-anti-affinity=preferred
              pgo-pg-database=true
              pgo-version=4.6.2
              pgouser=admin
              pod-template-hash=6795d7dfdc
              service-name=vantage-postgresql-db
              vendor=crunchydata
              workflowid=791bff06-9a34-4606-b1b0-a215e5b6ba25
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.130.25.16"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.130.25.16"
                    ],
                    "default": true,
                    "dns": {}
                }]
              kubernetes.io/limit-ranger:
                LimitRanger plugin set: cpu request for container database; cpu, memory limit for container database; cpu, memory request for container ex...
              openshift.io/scc: restricted
              status:
                {"conn_url":"postgres://10.130.25.16:5432/postgres","api_url":"http://10.130.25.16:8009/patroni","state":"stopped","role":"uninitialized",...
Status:       Running
IP:           10.130.25.16
IPs:
  IP:           10.130.25.16
Controlled By:  ReplicaSet/vantage-postgresql-db-6795d7dfdc
Containers:
  database:
    Container ID:   cri-o://f1e4408321df5f330684606f58f0f89a118a1ea232690556eb2dcf15463c3255
    Image:          registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.2-4.6.2
    Image ID:       registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha@sha256:0c1f78a403d4ab4372f9bfbce2447f4c2de00d78690b46aaa84f3b09f32d47b9
    Ports:          5432/TCP, 8009/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 24 Mar 2021 21:55:13 -0400
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:      200m
      memory:   128Mi
    Liveness:   exec [/opt/crunchy/bin/postgres-ha/health/pgha-liveness.sh] delay=30s timeout=10s period=15s #success=1 #failure=3
    Readiness:  exec [/opt/crunchy/bin/postgres-ha/health/pgha-readiness.sh] delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MODE:                               postgres
      PGHA_PG_PORT:                       5432
      PGHA_USER:                          postgres
      PGHA_INIT:                          <set to the key 'init' of config map 'vantage-postgresql-db-pgha-config'>  Optional: false
      PATRONI_POSTGRESQL_DATA_DIR:        /pgdata/vantage-postgresql-db
      PGBACKREST_STANZA:                  db
      PGBACKREST_REPO1_HOST:              vantage-postgresql-db-backrest-shared-repo
      BACKREST_SKIP_CREATE_STANZA:        true
      PGHA_PGBACKREST:                    true
      PGBACKREST_REPO1_PATH:              /backrestrepo/vantage-postgresql-db-backrest-shared-repo
      PGBACKREST_DB_PATH:                 /pgdata/vantage-postgresql-db
      ENABLE_SSHD:                        true
      PGBACKREST_LOG_PATH:                /tmp
      PGBACKREST_PG1_SOCKET_PATH:         /tmp
      PGBACKREST_PG1_PORT:                5432
      PGBACKREST_REPO1_TYPE:              posix
      PGHA_PGBACKREST_LOCAL_S3_STORAGE:   false
      PGMONITOR_PASSWORD:                 <set to the key 'password' in secret 'vantage-postgresql-db-exporter-secret'>  Optional: false
      PGHA_DATABASE:                      vantage-postgresql-db
      PGHA_REPLICA_REINIT_ON_START_FAIL:  true
      PGHA_SYNC_REPLICATION:              false
      PGHA_TLS_ENABLED:                   false
      PGHA_TLS_ONLY:                      false
      PGHA_STANDBY:                       false
      PATRONI_KUBERNETES_NAMESPACE:       vantage-dev (v1:metadata.namespace)
      PATRONI_KUBERNETES_SCOPE_LABEL:     crunchy-pgha-scope
      PATRONI_SCOPE:                       (v1:metadata.labels['crunchy-pgha-scope'])
      PATRONI_KUBERNETES_LABELS:          {vendor: "crunchydata"}
      PATRONI_LOG_LEVEL:                  INFO
      PGHOST:                             /tmp
    Mounts:
      /dev/shm from dshm (rw)
      /etc/pgbackrest/conf.d from pgbackrest-config (rw)
      /etc/podinfo from podinfo (rw)
      /pgconf from pgconf-volume (rw)
      /pgconf/pgreplicator from primary-volume (rw)
      /pgconf/pgsuper from root-volume (rw)
      /pgconf/pguser from user-volume (rw)
      /pgdata from pgdata (rw)
      /sshd from sshd (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-6jj72 (ro)
  exporter:
    Container ID:   cri-o://ccaee43097b5c4e791025bd2ce1188c02a3c40259ed50398d056cf7b1a2eb441
    Image:          registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:centos8-4.6.2
    Image ID:       registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter@sha256:f2b90fac6db77686e929b6620db51c7fb6a17e1f675de57ca433b9f62d00f54e
    Port:           9187/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 24 Mar 2021 21:55:23 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:     200m
      memory:  500Mi
    Environment:
      EXPORTER_PG_HOST:        127.0.0.1
      EXPORTER_PG_PORT:        5432
      EXPORTER_PG_DATABASE:    postgres
      EXPORTER_PG_PARAMS:      sslmode=disable
      JOB_NAME:                vantage-postgresql-db
      POSTGRES_EXPORTER_PORT:  9187
      EXPORTER_PG_USER:        <set to the key 'username' in secret 'vantage-postgresql-db-exporter-secret'>  Optional: false
      EXPORTER_PG_PASSWORD:    <set to the key 'password' in secret 'vantage-postgresql-db-exporter-secret'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-6jj72 (ro)
  pgbadger:
    Container ID:   cri-o://78132d38f679924c0099a76abcb8d2b6af2dda2f91493cdc91acf319284b24c7
    Image:          registry.developers.crunchydata.com/crunchydata/crunchy-pgbadger:centos8-13.2-4.6.2
    Image ID:       registry.developers.crunchydata.com/crunchydata/crunchy-pgbadger@sha256:abd47fe0f5806107f9f9163767c0f9ed387bf7da8ab4a5def3fa1e0790fa51ff
    Port:           10000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 24 Mar 2021 21:55:41 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  64Mi
    Requests:
      cpu:      500m
      memory:   64Mi
    Readiness:  tcp-socket :10000 delay=20s timeout=1s period=10s #success=1 #failure=3
    Environment:
      BADGER_TARGET:          vantage-postgresql-db
      PGBADGER_SERVICE_PORT:  10000
    Mounts:
      /pgdata from pgdata (ro)
      /report from report (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-6jj72 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  pgdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  vantage-postgresql-db
    ReadOnly:   false
  user-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vantage-postgresql-db-testuser-secret
    Optional:    false
  primary-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vantage-postgresql-db-primaryuser-secret
    Optional:    false
  sshd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vantage-postgresql-db-backrest-repo-config
    Optional:    false
  root-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vantage-postgresql-db-postgres-secret
    Optional:    false
  report:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  64Mi
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  pgbackrest-config:
    Type:                Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:       vantage-postgresql-db-config-backrest
    ConfigMapOptional:   0xc0012b4229
    SecretName:          vantage-postgresql-db-config-backrest
    SecretOptionalName:  0xc0012b422a
  pgconf-volume:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      vantage-postgresql-db-pgha-config
    ConfigMapOptional:  0xc0012b423d
  podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      limits.cpu -> cpu_limit
      requests.cpu -> cpu_request
      limits.memory -> mem_limit
      requests.memory -> mem_request
      metadata.labels -> labels
      metadata.annotations -> annotations
  pgo-pg-token-6jj72:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgo-pg-token-6jj72
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                     From                                                         Message
  ----     ------                  ----                    ----                                                         -------
  Normal   Scheduled               <unknown>                                                                            Successfully assigned vantage-dev/vantage-postgresql-db-6795d7dfdc-6dvtg to va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das
  Normal   SuccessfulAttachVolume  9m21s                   attachdetach-controller                                      AttachVolume.Attach succeeded for volume "pvc-331b39ff-b42b-4f3a-aa6b-5c4811e2276a"
  Normal   AddedInterface          9m14s                   multus                                                       Add eth0 [10.130.25.16/23]
  Normal   Pulling                 9m14s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.2-4.6.2"
  Normal   Pulled                  8m48s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Successfully pulled image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.2-4.6.2" in 25.405472362s
  Normal   Created                 8m48s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Created container database
  Normal   Started                 8m48s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Started container database
  Normal   Pulling                 8m48s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:centos8-4.6.2"
  Normal   Pulled                  8m38s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Successfully pulled image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:centos8-4.6.2" in 9.72482222s
  Normal   Created                 8m38s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Created container exporter
  Normal   Started                 8m38s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Started container exporter
  Normal   Pulling                 8m38s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbadger:centos8-13.2-4.6.2"
  Normal   Pulled                  8m20s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Successfully pulled image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbadger:centos8-13.2-4.6.2" in 17.644324051s
  Normal   Created                 8m20s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Created container pgbadger
  Normal   Started                 8m20s                   kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Started container pgbadger
  Warning  Unhealthy               4m12s (x25 over 8m12s)  kubelet, va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das  Readiness probe failed:

**Comment by ckvtvm-arch** [comment]
after recreating the cluster - it works displaying the log as  i am the leader with the lock. After successful run for few days, it will show as waiting on leader. Is it because cluster is not being used by any other services and it is going on waiting mode and getting locked ?

**Comment by jkatz** [comment]
This sounds like something operational and not a bug with the Operator. I would suggest checking out one of the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) options.
