### ISSUE TITLE
Restore PostgreSQL from s3 backup - Error: Unable to find PVC

### ISSUE THREAD

**Issue by teplydat** [CrunchyData/postgres-operator#2352]
**Describe the bug**
When I try to restore a new postgres database from a s3 backup, the error is: "Error: Unable to find PVC postgres-db-pgbr-repo for cluster postgres-db, cannot to restore from the specified data source"

**To Reproduce**
- create postgres cluster with s3 backup conf
- create a backup on s3
- delete the postgres cluster
- restore the postgrescluster from an existing s3 backup:
```
pgo create cluster postgres-db-new  --restore-from=postgres-db --restore-opts="--repo-type=s3" --pgbackrest-s3-bucket=... --pgbackrest-s3-endpoint=... --pgbackrest-s3-key=... --pgbackrest-s3-key-secret=... --pgbackrest-s3-region=... --pgbackrest-storage-type=s3 --pgbackrest-s3-ca-secret=... --pgbackrest-s3-uri-style=path --pgbackrest-s3-verify-tls=true --apiserver-url=... --pgo-ca-cert=... --pgo-client-cert=... --pgo-client-key=... --namespace default
```
btw: `pgo create cluster postgres-db --restore-from=postgres-db ...` (restoring previous cluster) has the same problem

**Expected behavior**
According to this doc: https://access.crunchydata.com/documentation/postgres-operator/4.6.1/pgo-client/common-tasks/#disaster-recovery-backups-restores
it should be possible to restore a postgres cluster from s3 (and not from a pvc) with the option: `--restore-opts="--repo-type=s3`

**Please tell us about your environment:**
```
pgo version 
pgo client version 4.6.1
pgo-apiserver version 4.6.1
```

Did I missed something?

**Comment by benjaminjb** [comment]
@teplydat -- Are you still experiencing this issue with PGO v4.6?
