### ISSUE TITLE
Update pgcluster to enable sync replication - how

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2354]
**Which example are you working with?**
Is it possible to update a cluster created without replica to a cluster with 1 or several replica(s) and sync replication?

Currently when creating a cluster, it is possible to specify if we want to enable the sync replication using the `--sync-replication` parameter. However, it is not possible to set this setting on an an existing cluster using for instance `pgo update cluster`.

We are trying to convert a running cluster without replica to a cluster with 1 replica and sync-replication. 
To what I understand, at the moment, we have to specify, at the cluster creation, if we want to use sync-replication in order to really use it in case a replica is added at a later stage.

Is there any way to achieve what we want without specifying up front the type of replication?

Thanks!
José

**Please tell us about your environment:**

We are currently using pgo 4.5.1

**Comment by jkatz** [comment]
To do this via `pgo update cluster` / updating the pgcluster CR would be new functionality.

**Comment by jose-joye** [comment]
@jkatz : Thank for the quick reply :-)

Is it a viable solution for me to simply modify the `sync replication` value within pgcluster CR prior scaling up the cluster?

José

**Comment by benjaminjb** [comment]
@jose-joye (a) sorry for the long delay in replying, but (b) is this still an issue you are running into with v4? Or have you updated to v5 and are still experiencing an issue like this?
