### ISSUE TITLE
Stanza cannot connect to primary

### ISSUE THREAD

**Issue by douggutaby** [CrunchyData/postgres-operator#2357]
**Describe the bug**
After upgrade from 4.6.1 to 4.6.2 the cluster upgrade can recreate psql cluster but stanza cannot run.
It said it cannot connect to (primary pod IP), and unable to find primary cluster.
It is the same if I run pgo backup on this cluster.

**To Reproduce**
1. Upgrade operator (oc apply -f postgres-operator.yml)
2. Upgrade any postgres cluster
3. Stanza error

**Please tell us about your environment:**
Openshift 4.7, Crunchy 4.6.2

**Additional context**
After I downgrade to 4.6.1 it is working again.

**Comment by jkatz** [comment]
Do you have any logs? Without those I don't even know where to begin investigating.

**Comment by andrewlecuyer** [comment]
@douggutaby can you provide a copy of your `sshd_config` following the upgrade?  It will be located in the `<clusterName>-backrest-repo-config` Secret.

**Comment by gricuk** [comment]
hi, we have the same problem, do you have any solutions how to fix this?

**Comment by gricuk** [comment]
@jkatz

**Comment by andrewlecuyer** [comment]
@gricuk @douggutaby please try setting `UsePAM no` in your `sshd_config` prior to the upgrade (this requires modifying `sshd_config` in the `<clusterName>-backrest-repo-config` Secret).

**Comment by gricuk** [comment]
> @gricuk @douggutaby please try setting `UsePAM no` in your `sshd_config` prior to the upgrade (this requires modifying `sshd_config` in the `<clusterName>-backrest-repo-config` Secret).

Sorry, we aren't using openshift. We upgraded from 4.6.1 to 4.6.2 and getting the same error when stanza create running: 
```
time="2021-03-30T13:56:42Z" level=info msg="stderr=[WARN: unable to check pg-1: [UnknownError] remote-0 process on '10.42.105.82' terminated unexpectedly [255]\nERROR: [056]: unable to find primary cluster - cannot proceed\n]"```
k8s version: v1.19.8

**Comment by andrewlecuyer** [comment]
You will want `UsePAM` to be set to `no` regardless of Kubernetes distro (i.e. whether using OpenShift or not).  This change was made for v4.6.2, and you can see the updated comment in the latest `sshd_config`: https://github.com/CrunchyData/postgres-operator/blob/26240c1cdbe43a182d37305ae29728b529d78d7f/installers/ansible/roles/pgo-operator/files/pgo-backrest-repo/sshd_config#L83-L85.

The issue here is that this change isn't being applied during the upgrade, which the PR referenced above addresses.  As a result, for now you will simply need to make this change manually prior to upgrading.

**Comment by douggutaby** [comment]
Thank you @andrewlecuyer I understand now.
I only wanted to upgrade because of the pgadmin pythton fix, but it isn't that important to edit secrets/configmaps.
I think I will wait for 4.6.3 or 4.7 I don't know which will be the next.

**Comment by mattboyd11** [comment]
@jkatz I'm trying to deploy a postgres cluster from scratch with 4.7 but running into this same issue. Everything works fine if I deploy a cluster with the 4.6.2 tag.

Kubernetes Version: 1.19.8
PGO Version: 4.7.0
ccp-image="crunchy-postgres-gis-ha"
ccp-image-tag="centos8-13.3-3.1-4.7.0"

stanza-create logs:
nss_wrapper: user exists
nss_wrapper: group exists
nss_wrapper: environment configured
Wed May 26 21:43:09 UTC 2021 INFO: Image mode found: pgbackrest
Wed May 26 21:43:09 UTC 2021 INFO: Starting in 'pgbackrest' mode
time="2021-05-26T21:43:09Z" level=info msg="crunchy-pgbackrest starts"
time="2021-05-26T21:43:09Z" level=info msg="debug flag set to false"
time="2021-05-26T21:43:09Z" level=info msg="backrest stanza-create command requested"
time="2021-05-26T21:43:09Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.68.6.8 --db-path=/pgdata/pgdb-beta]"
time="2021-05-26T21:43:09Z" level=info msg="output=[]"
time="2021-05-26T21:43:09Z" level=info msg="stderr=[WARN: unable to check pg-1: [UnknownError] remote-0 process on '10.68.6.8' terminated unexpectedly [255]: ssh: connect to host 10.68.6.8 port 22: Connection refused\nERROR: [056]: unable to find primary cluster - cannot proceed\n]"
time="2021-05-26T21:43:09Z" level=fatal msg="command terminated with exit code 56"

backrest-shared-repo logs:
nss_wrapper: user exists
nss_wrapper: group exists
nss_wrapper: environment configured
Starting the pgBackRest repo
nss_wrapper: ssh configured
creating  /backrestrepo/pgdb-beta-backrest-shared-repo
The pgBackRest repo has been started
WARNING: 'UsePAM no' is not supported in Fedora and may cause several problems.

Confirmed that usePAM no is set in pgo-backrest-repo-config and <cluster_name>-backrest-repo-config secrets under sshd_config.

**Comment by ibotty** [comment]
@mattboyd11 I assume that's the same issue I ran into.  Note the `port 22`.  See #2478.
