### ISSUE TITLE
PostGIS image tags other than centos8-13.2-3.0-4.6.2

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#2359]
Good day!

In our Crunchy cluster we are using crunchy-postgres-gis-ha:centos7-12.5-3.0-4.5.1 image tags.
How we want to upgrade our cluster.

First, we should update client side (we are using .sh script) to 4.6.2 
Secondly, we should update postgres-operator to 4.6.2 (we are using helm chart version).
But there is a variable in helm chart values named "ccp_image_tag".

I think, to perform minor update we should set this value to something like centos7-12.6-3.0-4.6.2 (or centos8-12.6-3.0-4.6.2) according to compatibility list:
https://access.crunchydata.com/documentation/postgres-operator/4.6.2/configuration/compatibility/

But the problem is there are no such image tags in crunchy dockerhub repo:
https://hub.docker.com/r/crunchydata/crunchy-postgres-gis-ha/tags?page=1&ordering=last_updated

What should we do then to update and use operator 4.6.2 without major upgrate to Postgres 13.2?

Thank you!

**Comment by jkatz** [comment]
The centos8-12.6-3.0-4.6.2 image can be found here:

[https://www.crunchydata.com/developers/download-postgres/containers/postgis](https://www.crunchydata.com/developers/download-postgres/containers/postgis)
