### ISSUE TITLE
How to create cluster with nfs storage.

### ISSUE THREAD

**Issue by bmoss6** [CrunchyData/postgres-operator#2360]
** Which example are you working with? **
pgo client
**What is the current behavior?**
pgo create cluster $clustername is creating PVC's that seem to ignore the values specified in the values.yaml configmap for pgo-deployer-cm. Resulting in PVC's that are unable to correctly bind. Even when using match labels, this behavior persists.
**What is the expected behavior?**
pgo create cluster $clustername should create PVC's as specified by the storage config class listed in primary_storage, backup_storage, replica_storage, etc.
**Other information** (e.g. detailed explanation, related issues,  etc):
Here is relevant info from the postgres-operator.yaml
```
backrest_storage: "nfsstoragered"
backup_storage: "nfsstoragered"
primary_storage: "nfsstoragered"
replica_storage: "nfsstoragered"
...
storage4_name: "nfsstoragered"
storage4_access_mode: "ReadWriteMany"
storage4_size: "1G"
storage4_match_labels: "crunchyzone=red"
storage4_type: "create"
storage4_supplemental_groups: "65534"
```

**Please tell us about your environment:**

* Operating System:
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos8-4.6.1
* PostgreSQL Version: 13.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.18

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc

```
Name:          test-wal
Namespace:     pgo
StorageClass:  default
Status:        Pending
Volume:        
Labels:        pg-cluster=test
               pgremove=true
               vendor=crunchydata
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason              Age                            From                         Message
  ----     ------              ----                           ----                         -------
  Warning  ProvisioningFailed  <invalid> (x2 over <invalid>)  persistentvolume-controller  Failed to provision volume with StorageClass "default": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported

```
Notice that the the annotations and warnings suggest the PVC is using a storage class "default", which ignores the configuration specified in the configmap.

**Comment by jkatz** [comment]
If you are using NFS, you are responsible for provisioning your own persistent volumes (PV). This is true of pretty much any Kubernetes application that is utilizing NFS through persistent volumes. It is helpful to use a NFS volume provisioner, otherwise you have to provision them on your own.

For local development, I use https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner

And I add the storage class that it creates as my default storage class, which then lets it "just work" with the "default" settings.
