### ISSUE TITLE
declarative-friendly helm chart

### ISSUE THREAD

**Issue by travisghansen** [CrunchyData/postgres-operator#2363]
I'm trying to manage a series of operators declaratively with gitops practices (I'm specifically using argocd). The chart is rendered via `template` commands and then resources are spewed out but `helm` is **not** invoked to actually do install/upgrade/uninstall.

The way the chart is designed is pretty abnormal and really makes the above deployment scenario challenging:

- crds are not included/rendered by the chart (presumably the job pod interacts with k8s to deploy them)
- assets created by the chart are later deleted by the pod (at least that's my understanding based on my reading of the doc..the rbac is cleaned up)

As designed, argo *thinks* a certain set of resources should belong (whatever is rendered by `template`) to the application, if those are no longer present a diff is detected and it appears as though the deploy didn't occur correctly. Additionally, resources created by the job pod aren't detected as belonging to the deployment so it's harder to detect health of the deployment (from the context of argo).

**Describe the solution you'd like**

- resources are rendered and *not* deleted by pods/etc after the fact
- install/uninstall/upgrade logic decoupled from helm
  - crds not managed by the job pod
  - job pod is retired
  - install/upgrade logic is detected by the controller pod on startup
  - removal logic is managed by a user 'manually' (removal in the sense of removing crds/functionality entirely, etc..not deleting the operator deployment or something of that nature)
 
Thanks for the consideration!

**Comment by jkatz** [comment]
PGO 5.0 was built declarative first. We have started building out a repository of Helm charts in the [PGO exmaples](https://github.com/CrunchyData/postgres-operator-examples) repository.

We are of course open to suggestions and contributions to our Helm charts.

Thanks!

**Comment by travisghansen** [comment]
Awesome! I'll got check it out!
