### ISSUE TITLE
Is it possible to choose a different pgBackRest version?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [CrunchyData/postgres-operator#2364]
Now that GCS support was implemented in pgBackRest 2.33, is it possible to use it in the current operator version (4.6.2)? This is the only thing missing for us to be able to use the operator, since our whole platform runs on GCP.

Thank you

**Comment by jkatz** [comment]
Version bumps of pgBackRest are tied to feature releases of the Operator (see [Compatibility](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/)), so the next bump will be around the 4.7 release.

There may still need to be some work for simpler integration with GCS (see: #1791) but one may still be able to concoct something when present.

This is not to say that you can't run the Postgres Operator on GCP -- in fact we test the Operator extensively on this. You can still use the "local" storage support connected to a GKE provisioned storage. The key is ensuring that your backup volume is on a separate disk from your data volume.
