### ISSUE TITLE
after delete pgadmin could not create pgadmin again

### ISSUE THREAD

**Issue by nogoodbay** [CrunchyData/postgres-operator#2366]
**Describe the bug**

Create pgadmin again after delete pgadmin, the terminal prompt:

```
Error: error creating tasks for one or more clusters
bank-reconciliation-pg-dev: error - pgtasks.crunchydata.com "pgadmin-add-bank-reconciliation-pg-dev" already exists
```

**To Reproduce**

1. create pgadmin 
2. delete pgadmin
3. create pgadmin
4. got already exists error

**Expected behavior**

create success again

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by jkatz** [comment]
I was unable to reproduce this issue on 4.6.2 (and given there is no version provided, I don't know what version you attempted this on). The steps I used:

```
pgo create pgadmin hippo
pgo delete pgadmin hippo
pgo create pgadmin hippo
```

Be sure that you wait long enough for each task to complete.
