### ISSUE TITLE
Actvity: jkatz Allow a single instance/replica to have its PVC resized

### ISSUE THREAD

**Issue by Schmaetz** [CrunchyData/postgres-operator#2369]
Hi, 
i've just a Question about the Activity: Allow a signle instance/replica to have its PVC resized. 
jkatz wrote: 
```
 Allow a single instance/replica to have its PVC resized

This allows for a single instance/replica to have its individual PVC
resized.  Similar to the other PVC operations, it must meet
the following requirements:

- Each PVC needs to be unmounted from the Pod for a PVC change to
take effect.
- The storage class assigned to the PVC must support resizing
- The new size of the PVC must be larger than the old size

If a cluster-wide PVC size change is subsequently initiated, the
Operator will ignore the change for the specific instance, unless the
cluster change has a larger value than the instance value.

Issue: [ch8477]
```

Why is it necessary to unmount the pvc? With Kuberntes 1.15 pvc-resize is usable (beta function). There is no need to unmount the pvc. The expand works while the db is in progress. 

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-an-in-use-persistentvolumeclaim

The operator would only have to resize the pvc directly and either store the new storage size directly or always read the current size of the primary pvc and use it for new replicas. 

Best regards

**Comment by jkatz** [comment]
This question is better for the [community list](https://access.crunchydata.com/documentation/postgres-operator/latest/support/).

However, for a quick answer, PGO currently maintains compatibility for OpenShift 3.11 (described in a [variety of places in the documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/), which relies on Kubernetes 1.11 (and a little bit of 1.12). This ensures that our users who are still on OpenShift 3.11 can have convenient access to the PVC resize future, and this feature is handled in a way to minimize, if not have zero, disruption.

In the future we may have a release that breaks compatibility with OpenShift 3.11 that can leverage the newer PVC resizing capabilities.

**Comment by Schmaetz** [comment]
Thanks a lot for your answer.  :)

Best regards
