### ISSUE TITLE
Policies with tls only 

### ISSUE THREAD

**Issue by aurelien43** [CrunchyData/postgres-operator#2370]
Hello, 
Policies use postgres user with ssl off evenif the cluster is create with --tls-only and this pg_hba.conf : 

>  pg_hba:
>       - local all postgres peer
>       - hostssl all postgres 0.0.0.0/0 md5 clientcert=1
>       - hostssl replication primaryuser 0.0.0.0/0 md5
>       - hostssl all primaryuser 0.0.0.0/0 reject
>       - hostssl all all 0.0.0.0/0 md5

If i remove clientcert=1 it's work but SSL is off with postgres user. 

**Error Logs**

`> kc logs policy-test-aurel-pgaas-security-pgopolicy-schedule-q894n `
`Mon Apr 12 13:53:05 UTC 2021 INFO: Image mode found: sqlrunner`
`Mon Apr 12 13:53:05 UTC 2021 INFO: Starting in 'sqlrunner' mode`
`psql: error: FATAL:  connection requires a valid client certificate `
`FATAL: no pg_hba.conf entry for host "10.115.79.232", user "postgres", database "postgres", SSL off`

**Please tell us about your environment:**

* Operating System: cento8
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): CSI (SAN)
* Container Image Tag: centos8-13.2-4.6.1
* PostgreSQL Version: 13.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 4.6.1

**Comment by jkatz** [comment]
I'm unable to reproduce this with just the `--tls-only` flag. I did not try setting `clientcert=1` in the pg_hba.conf file, but conceivably that would not work, as the "sqlrunner" would need awareness of a client key/cert pair. However -- this would still execute over TLS (as I proved on my local) -- you are just not doing client certificate verification (though with `clientcert=1`, the "verification" is that "the certificate the client is presenting is from a CA I trust").

Both `pgo create cluster --policies` and `pgo apply` execute the SQL file directly from within the container, so it is connecting over the UNIX socket, not a client connection. It seems that running it on a schedule creates the job runner that goes over a TCP socket. I wouldn't be opposed to switching the scheduler to execute the policy over a UNIX socket, which would allow for your case to work, but would have to see if there are any ramifications from a performance perspective when doing so.
