### ISSUE TITLE
Syntax error on Prometheus deployment

### ISSUE THREAD

**Issue by Martin-Hogge** [CrunchyData/postgres-operator#2371]
**Describe the bug**
When installing `operator-metrics`, the job fails with 

> failed: [localhost] (item=prometheus-deployment.json) => {"ansible_loop_var": "item", "changed": true, "cmd": ["kubectl", "create", "-f", "/tmp/.pgo/metrics/output/prom/prometheus-deployment.json", "-n", "pgo"], "delta": "0:00:00.405503", "end": "2021-04-13 09:21:33.939652", "failed_when_result": true, "item": "prometheus-deployment.json", "msg": "non-zero return code", "rc": 1, "start": "2021-04-13 09:21:33.534149", "stderr": "error: error parsing /tmp/.pgo/metrics/output/prom/prometheus-deployment.json: json: line 29: invalid character '}' looking for beginning of object key string", "stderr_lines": ["error: error parsing /tmp/.pgo/metrics/output/prom/prometheus-deployment.json: json: line 29: invalid character '}' looking for beginning of object key string"], "stdout": "", "stdout_lines": []}

I managed to get the content of `/tmp/.pgo/metrics/output/prom/prometheus-deployment.json`:
```
cat /tmp/.pgo/metrics/output/prom/prometheus-deployment.json

{
    "apiVersion": "apps/v1",
    "kind": "Deployment",
    "metadata": {
        "name": "crunchy-prometheus",
        "labels": {
            "app.kubernetes.io/name": "postgres-operator-monitoring"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
          "matchLabels": {
            "name": "crunchy-prometheus",
            "app.kubernetes.io/name": "postgres-operator-monitoring"
          }
        },
        "template": {
            "metadata": {
                "labels": {
                    "name": "crunchy-prometheus",
                    "app.kubernetes.io/name": "postgres-operator-monitoring"
                }
            },
            "spec": {
                "securityContext": {
                    "fsGroup": 26,
                    "runAsUser": 2,
                    "runAsNonRoot": true,
                },
                "serviceAccountName": "prometheus-sa",
                "containers": [
                    {
                        "name": "prometheus",
                        "image": "prom/prometheus:v2.24.0",
                        "ports": [
                            {
                                "containerPort": 9090,
                                "protocol": "TCP"
                            }
                        ],
                        "readinessProbe": {
                            "httpGet": {
                                "path": "/-/ready",
                                "port": 9090
                            },
                            "periodSeconds": 10
                        },
                        "livenessProbe": {
                            "httpGet": {
                                "path": "/-/healthy",
                                "port": 9090
                            },
                            "initialDelaySeconds": 15,
                            "periodSeconds": 20
                        },
                        "env": [],
                        "volumeMounts": [
                            {
                                "mountPath": "/etc/prometheus",
                                "name": "prometheusconf"
                            },
                            {
                                "mountPath": "/prometheus",
                                "name": "prometheusdata"
                            },
                            {
                                "mountPath": "/etc/prometheus/alert-rules.d",
                                "name": "alertmanagerrules"
                            }
                        ]
                    }
                ],
                "volumes": [
                    {
                        "name": "prometheusconf",
                        "configMap": {
                            "name": "crunchy-prometheus"
                        }
                    },
                    {
                        "name": "prometheusdata",
                        "persistentVolumeClaim": {
                            "claimName": "prometheusdata"
                        }
                    },
                    {
                        "name": "alertmanagerrules",
                        "configMap": {
                            "name": "alertmanager-rules-config"
                        }
                    }
                ]
            }
        }
    }
}
```

We can see in `spec.template.spec.securityContext` that their is an extra `,` after `runAsNonRoot`.

**To Reproduce**
1. Follow https://access.crunchydata.com/documentation/postgres-operator/4.6.2/quickstart/ to install `postgres-operator` with a new cluster `hippo` 
2. Install `postgres-operator-metrics`: `kubectl apply -f /path/to/postgres-operator-metrics.yml` (only change graphana username and password)

**Expected behavior**
Metrics stack are installed with prometheus.

**Please tell us about your environment:**

* Where is this running: Cloud (GKE)
* Storage being used (NFS, Hostpath, Gluster, etc): GKE default storage
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 4.6.2

**Comment by jkatz** [comment]
This was already fixed in https://github.com/CrunchyData/postgres-operator/commit/cd08c8b503cf1a3feaef6917a14d731e0aca9991 and https://github.com/CrunchyData/postgres-operator/commit/2995db90dc405881f83a7bd689397ab4df801cd4

**Comment by Martin-Hogge** [comment]
Thank you. Do you have an estimate of when this fix will be available?
