### ISSUE TITLE
Pgoperator Helm chart storage class configuration in values.yaml is missing

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#2372]
Good day!

In my team we are using pgoperator helm chart. Since 4.6.1 version "storage<N>_class" line used for configuring storage classes in values.yaml has been removed. So clusters created with "pgo create" command always use "standard" class. Is there any reason for this? Am i missing something in docs?

Thank you!

**Comment by benjaminjb** [comment]
Hi @aprilito1965 -- just to clarify, when I look at the Helm chart values.yaml in 4.6 [here](https://github.com/CrunchyData/postgres-operator/blob/REL_4_6/installers/helm/values.yaml), I see a bunch of `storageN_DESCRIPTOR` fields, with different fields for `backrest_storage`, `primary_storage`, etc. There's documentation [here](https://access.crunchydata.com/documentation/postgres-operator/4.7.8/installation/configuration/#storage-configuration-options) for that.

If you're still using v4, I hope this helps; but if you are using v4, you might also want to make sure that you're using the Helm chart in the v4 branch in this repo and not the `postgres-operator-examples` repo.

If you're still using v4 and still having a problem with this, please reopen this ticket.
