### ISSUE TITLE
Add existing namespace to operator

### ISSUE THREAD

**Issue by Martin-Hogge** [CrunchyData/postgres-operator#2373]
**Which example are you working with?**
hyppo

**What is the current behavior?**
`pgo create mycluster -n mynamespace` returns 

> namespace [mynamespace] is not part of the Operator installation 

and `pgo create namespace mynamespace` returns 

> namespaces "mynamespace" already exists

**What is the expected behavior?**
Being able to add a cluster to an existing namespace.

**Other information** (e.g. detailed explanation, related issues,  etc)
The namespace on which I want to add the cluster can't be deleted. It already host another Postgresql solution that I want to migrate to CrunchyData solution.

**Please tell us about your environment:**

* Where is this running ( Local , Cloud Provider): Cloud (GKE)
* Storage being used (NFS, Hostpath, Gluster, etc): GKE default storage
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 4.6.2

Thank you.

**Comment by jkatz** [comment]
The simplest way to add an existing namespace to the Operator is by adding the following two labels:

```
vendor=crunchydata
pgo-installation-name=$PGO_INSTALLATION_NAME
```

You can get the $PGO_INSTALLATION_NAME by running a `kubectl describe deployments` on the `postgres-operator` Deployment, i.e:

```
kubectl -n pgo describe deployments.apps postgres-operator

# output trundcated...

PGO_INSTALLATION_NAME:   devtest

# output trundcated...
```

[Namespaces](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/) are [covered thoroughly in the documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/), though we may need to add something around adding an already existing namespace.

Potentially, we could do something where if you run `pgo create namespace` on an already existing namespace, we just add the labels on it.

**Comment by andrewlecuyer** [comment]
Another option is to run `pgo update namespace`, e.g. `pgo update namespace mynamespace`.

**Comment by jkatz** [comment]
Yeah that's the simpler one.

Will leave this open just to ensure we have the documentation clear on those points.
