### ISSUE TITLE
Create superuser

### ISSUE THREAD

**Issue by Martin-Hogge** [CrunchyData/postgres-operator#2376]
**What is the current behavior?**
`pgo create user` doesn't have an option to create a superuser.

**What is the expected behavior?**
Being able to create a Postgresql superuser role.

**Other information** (e.g. detailed explanation, related issues,  etc)
Actually the only superuser is the user `postgres`. How could I create superuser ?

**Please tell us about your environment:**

* Where is this running ( Local , Cloud Provider) Cloud (GKE)
* Storage being used (NFS, Hostpath, Gluster, etc): GKE default storage
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 4.6.2

Thank you.

**Comment by jkatz** [comment]
The Operator creates a single superuser account called `postgres`, as you have pointed out. Technically the `postgres` user is a service account to perform superuser operations, but we do allow for people to chose to log in as this user.

Any other user created via `pgo create user` has regular privileges. If you wish to turn these into superuser accounts, you can login as the `postgres` user and run [`ALTER ROLE .. SUPERUSER`](https://www.postgresql.org/docs/current/sql-alterrole.html). However, and I say this without knowing what you are trying to accomplish, in general you should try to limit access to Postgres superuser accounts.
