### ISSUE TITLE
ERROR: EXPORTER_PG_PASSWORD environment variable is not set, aborting.

### ISSUE THREAD

**Issue by kumarvijendar** [CrunchyData/postgres-operator#2377]
**Describe the bug**
I tried deploying the latest version of the chart i'e 4.6.2. the postgres-operator's deployment fails with the following error
ERROR: EXPORTER_PG_PASSWORD environment variable is not set, aborting.
**To Reproduce**
Deploy the latest chart of postgres-operator. the version is 4.6.2
In postgres-operator's operator container's log:
ERROR: EXPORTER_PG_PASSWORD environment variable is not set, aborting.
**Expected behavior**
The documentation says something like:
**EXPORTER_PG_PASSWORD**|none|Provides the password needed to generate the PostgreSQL URL required by the PostgreSQL Exporter to connect to a PG database.  Should typically match the `PGMONITOR_PASSWORD` value set in the `crunchy-postgres` container.|

But there is not any reference of this PGMONITOR_PASSWORD variable anywhere after release version 4.4.0

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running (Cloud)
* Storage being used (NFS):
* Container Image Tag:
* PostgreSQL Version: crunchy_postgres_ha:centos8-12.6-4.6.2
* Platform (OpenShift):
* Platform Version: 4.6.1

**Additional context**
The exporter's deployment seems to use the password from a secret [postgres-operator/installers/ansible/roles/pgo-operator/files/pgo-configs/exporter.json](https://github.com/CrunchyData/postgres-operator/blob/725a8dafb643f1313886c76a40359264851769ff/installers/ansible/roles/pgo-operator/files/pgo-configs/exporter.json#L48)
But the deployment is being aborted by the starting shell script: [postgres-operator/bin/crunchy-postgres-exporter/start.sh](https://github.com/CrunchyData/postgres-operator/blob/725a8dafb643f1313886c76a40359264851769ff/bin/crunchy-postgres-exporter/start.sh#L73)

**Comment by jkatz** [comment]
If you are deploying using the Postgres Operator, you should not encounter any issues, as all of those values are managed. [Monitoring](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/) is discussed in detail in the documentation: [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/monitoring/)

**Comment by kumarvijendar** [comment]
@jkatz 
```
+(/opt/cpm/bin/start.sh:73)> set_default_pg_exporter_env(): env_check_err EXPORTER_PG_PASSWORD
+(/opt/cpm/bin/common_lib.sh:31)> env_check_err(): [[ -z '' ]]
+(/opt/cpm/bin/common_lib.sh:33)> env_check_err(): echo_err 'EXPORTER_PG_PASSWORD environment variable is not set, aborting.'
++(/opt/cpm/bin/common_lib.sh:39)> echo_err(): date
Wed Apr 14 18:03:19 UTC 2021 ERROR: EXPORTER_PG_PASSWORD environment variable is not set, aborting.
+(/opt/cpm/bin/common_lib.sh:39)> echo_err(): echo -e '\033[0;31mWed Apr 14 18:03:19 UTC 2021 ERROR: EXPORTER_PG_PASSWORD environment variable is not set, aborting.\033[0m'
```

**Comment by jkatz** [comment]
That is not a path in the 4.6.2 container. Please ensure you are using the correct container.

I don't believe this is a bug.

**Comment by kumarvijendar** [comment]
Can you please point out which path exactly are you talking about. 
I will investigate my configuration accordingly.

**Comment by jkatz** [comment]
In 4.6, the paths inside the containers were renamed from `/opt/cpm/` to `/opt/crunchy`, so the exporter container you are using is not a 4.6 container. You need to ensure you have loaded in the properly versioned container.
