### ISSUE TITLE
postgres-operator stanza-create job failing | pgbackrest not able to connect to postgres db

### ISSUE THREAD

**Issue by kumarvijendar** [CrunchyData/postgres-operator#2381]
** Which example are you working with? **
postgres operator 4.6.2 installed by helm version 4.6.2
**What is the current behavior?**
stanza-create job fails with 

```
Fri Apr 16 06:43:28 UTC 2021 INFO: Image mode found: pgbackrest
Fri Apr 16 06:43:28 UTC 2021 INFO: Starting in 'pgbackrest' mode
time="2021-04-16T06:43:28Z" level=info msg="crunchy-pgbackrest starts"
time="2021-04-16T06:43:28Z" level=info msg="debug flag set to %tfalse"
time="2021-04-16T06:43:28Z" level=info msg="backrest stanza-create command requested"
time="2021-04-16T06:43:28Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=some-db-host --db-path=/pgdata/some-db-name]"
time="2021-04-16T06:43:28Z" level=info msg="output=[]"
time="2021-04-16T06:43:28Z" level=info msg="stderr=[WARN: unable to check pg-1: [UnknownError] remote-0 process on 'some-db-host' terminated unexpectedly [255]: postgres@some-db-host: Permission denied (publickey,keyboard-interactive).\nERROR: [056]: unable to find primary cluster - cannot proceed\n]"
time="2021-04-16T06:43:28Z" level=fatal msg="command terminated with exit code 56"
```
**What is the expected behavior?**
pgbackrest should be able to connect to the postgres pod as everything is being managed by the postgres-operator
**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System:
* Where is this running (Cloud Provider) GCP
* Storage being used (NFS):
* Container Image Tag:
* PostgreSQL Version: centos8-12.6-4.6.2
* Platform (OpenShift): OpenShift
* Platform Version: 4.6.1
* Kubernetes Version: v1.19.0

**Comment by jkatz** [comment]
Please read the remediation listed in: https://github.com/CrunchyData/postgres-operator/issues/2375#issuecomment-819994898

**Comment by kumarvijendar** [comment]
@jkatz 
I checked my sshd_config, saw that UsePAM is set to no
```

# This is set explicitly to *no* as we are only using pubkey authentication and
# because each container is isolated to only an unprivileged user.
UsePAM no
```
The issue which I am getting is somewhat different from the one mentioned in [#2375 (comment)](https://github.com/CrunchyData/postgres-operator/issues/2375#issuecomment-819994898)

I am getting  Permission denied (publickey,keyboard-interactive)

`[WARN: unable to check pg-1: [UnknownError] remote-0 process on 'some-db-host' terminated unexpectedly [255]: postgres@some-db-host: Permission denied (publickey,keyboard-interactive).\nERROR: [056]: unable to find primary cluster - cannot proceed\n]"`
