### ISSUE TITLE
 ccp_backrest_last_incr_backup pq: invalid input syntax for type json" source="postgres_exporter.go:1356"

### ISSUE THREAD

**Issue by kumarvijendar** [CrunchyData/postgres-operator#2382]
**Describe the bug**
Postgres operator 4.6.1
Postgres version 12.6

Exporter is throwing following error in logs 
```
time="2021-04-17T12:39:21Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_backrest_last_full_backup pq: invalid input syntax for type json" source="postgres_exporter.go:1356"
time="2021-04-17T12:40:21Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_backrest_last_info pq: invalid input syntax for type json" source="postgres_exporter.go:1356"
time="2021-04-17T12:41:22Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_backrest_last_diff_backup pq: invalid input syntax for type json" source="postgres_exporter.go:1356"
time="2021-04-17T12:42:22Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_backrest_last_incr_backup pq: invalid input syntax for type json" source="postgres_exporter.go:1356"
time="2021-04-17T12:42:22Z" level=error msg="queryNamespaceMappings returned 4 errors" source="postgres_exporter.go:1474"
```

**To Reproduce**
Deploy a postgres-operator with version 4.6.1 with containers version centos8-12.6-4.6.1

**Expected behavior**

The exporter should not throw any errors.

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider) Cloud Provider
* Storage being used (NFS, Hostpath, Gluster, etc): 
* Container Image Tag: centos8-4.6.1
* PostgreSQL Version: 12.6
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.6.1
* Kubernetes version: 1.19.0

**Additional context**

Strange but the operator did not create stanza-create job in the namespace.

```
oc get job -n my-namespace-pgo
NAME                             COMPLETIONS   DURATION   AGE
backrest-backup-my-db  1/1           73s        15m
backrest-backup-my-db  1/1           2m1s       15m
backrest-backup-my-db   1/1           2m1s       15m
```

**Comment by jkatz** [comment]
This is not an issue with the exporter. This can occur for a variety of reasons:

- The pgBackRest repository has not been initialized
- The metrics were not available at the time the initial scrape occurred
- There is a lag / timeout between scraping the metrics and retrieving the information from the pgBackRest repository

Separately, the release notes for 4.6.1 state a behavior change around the stanza create Job:

> The post-cluster creation pgBackRest tasks, i.e. creating a stanza and creating an initial backup, are now deleted by the Operator should they complete successfully. Besides good housekeeping, this provides a workaround for an OpenShift 3.11 bug that was causing the Operator to continuously issue pgBackRest backups during an OpenShift refresh cycle.

[https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.6.1/](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.6.1/)

Lastly, please try to report bugs against the latest release for a series (e.g. 4.6.2, 4.5.2, etc.) as issue may already be resolved in a newer version. Thanks!
