### ISSUE TITLE
Issue integrating istio sidecar proxy with postgres-operator

### ISSUE THREAD

**Issue by avanichy25** [CrunchyData/postgres-operator#2385]
**Describe the bug**
I am trying to integrate istio sidecar proxy with my services but postgres-operator is not supporting it.

**To Reproduce**
1. Install istio-1.9.2 
2. inject sidecar istio-proxy in the namespace of the services deployed
3. pgo-deploy got stuck and after enabling the label with istio-injection=enabled not able to remove the cluster from pgo-client

```
  pod : kong-postgres-rmdata-cwds-btckm (Running) on aks (1/2) (unknown)
  pod : kong-postgres-rmdata-mcxs-47lx5 (Running) on aks (1/2) (unknown)
````
**Expected behavior**
After enabling the label for istio the postgres operator should be deployed normally.

**Please tell us about your environment:**
Deploying on azure cloud v1.18.14

* Storage being used (NFS, Hostpath, Gluster, etc): Default
* PostgreSQL Version: centos7-4.3.2
* Platform (Docker, Kubernetes, OpenShift): kubernetes
* Platform Version: v1.18.14

**Additional context**
Please provide some information to inject the istio with postgres.

**Comment by jkatz** [comment]
This is not a bug report for PGO. If you are looking for general support, please review the [Support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) options.
