### ISSUE TITLE
Retention policy for incremental backups

### ISSUE THREAD

**Issue by Martin-Hogge** [CrunchyData/postgres-operator#2386]
**What is the current behavior?**
We can't set a retention policy for incremental backup.

**What is the expected behavior?**
Being able to set retention policy for incremental backup.

**Other information** (e.g. detailed explanation, related issues,  etc)
Tried with the option `--repo1-retention-incr` but it fails with `invalid option`.

Maybe their is a reason why retention policy can't be set to incremental backup, then it would be helpful to have an explanation in the documentation.

Thank you.

**Comment by Martin-Hogge** [comment]
Ok I found the answer in the documentation of PgBackRest: https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-archive.

**Comment by jkatz** [comment]
For questions around general support, please review the [Support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) section of the documentation.
