### ISSUE TITLE
Where are the docker images for postgres 11 (pgo 4.6.2)?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2387]
I'm want to play with pgo 4.6.2 and need the images for postgresql 11. According to the compatibility requirement found under https://access.crunchydata.com/documentation/postgres-operator/4.6.2/configuration/compatibility/, it should support version 11.11.

I look at 

- the developer portal (https://www.crunchydata.com/developers/download-postgres/containers/postgresql11). 
They are not there. Which is according to the note at the top of the page correct: (postgresql 11 or centos 7 will not be published anymore there).
- dockerhub (https://hub.docker.com/r/crunchydata/crunchy-postgres/tags?page=1&ordering=last_updated&name=4.6.2).
There we can see only the image for postgresql 13.

Am I missing something?

Thanks a lot for any light on this
José

**Comment by jkatz** [comment]
There is documentation around this on the Developer Portal in the header:

[https://www.crunchydata.com/developers](https://www.crunchydata.com/developers)

**Comment by jose-joye** [comment]
@jkatz 
You mean we have to buy an active subscription in order to get access to these image?
--> We are re-directed to the "crunchydata customer portal".
