### ISSUE TITLE
Helm installer doesn't follow convention

### ISSUE THREAD

**Issue by kubaracek** [CrunchyData/postgres-operator#2390]
**Describe the bug**
While importing the helm chart into Tanka it complains for 2 reasons. Chart.yml contains invalid key mapping on the `description` line. Multiple jobs (install, update, uninstall) have the same metadata name.

**Screenshots**
![image](https://user-images.githubusercontent.com/16261998/115437469-7fa8ac80-a20c-11eb-9be4-5aeb1ee7fc03.png)

**Comment by jkatz** [comment]
This is a bit challenging to decipher. Do you have a reference to what the conventions are? Would you be interested in opening up a PR with a suggested fix?

**Comment by kubaracek** [comment]
@jkatz Sorry for the vague description. It's a super simple fix and writing this took more time than fixing it actually. I hope it's clear from the PR

**Comment by jkatz** [comment]
Awesome, looks great. Will merge soon -- thanks!

**Comment by jkatz** [comment]
Committed. I think this is safe to backpatch, so I will add to the support releases. Thanks!
