### ISSUE TITLE
CA certificate too weak

### ISSUE THREAD

**Issue by OmriDim** [CrunchyData/postgres-operator#2394]
**Describe the bug**
After upgrading the operator and all of it's clusters to version 4.6.1  from 4.5.1, In our close openshift environment we are not able to restore clusters as they fail the bootstrap phase, with the error "unable to load info file '....backup.info' .... CA certificate too weak.
It is important to note we are using a s3 with certificates that use sha1 which is **not** managed by us and that everything seemed to work before the upgrade.
Is it possible that the new operator version does not support sha1?
if so, why do s3 backup work, while s3 restore not?

**To Reproduce**
pgo restore <cluster-name> --pitr-target=x --backup-opts=--type=time --pgbackrest-storage-type=s3 -n <namespace> --apiserver-url <apiserverurl>

**Expected behavior**
point in time restore from s3 bucket 

Please tell us about your environment:
crunchy version 4.6.1
Where is this running ( Local, Cloud Provider): on prem openshift
Container Image Tag: centos8-12.6
PostgreSQL Version: 12.6
Platform (Docker, Kubernetes, OpenShift): openshift
Platform Version: openshift 4.5

Thank you!

**Comment by jkatz** [comment]
This is likely any issue from going from a centos7 to a centos8 base container. See:

[https://www.xenami.net/posts/2019-05-05-ssl-ca-certificate-too-weak/](https://www.xenami.net/posts/2019-05-05-ssl-ca-certificate-too-weak/)

The options would be to update your PKI or move back to a centos7 base container.  It's mentioned somewhere in the docs, we do make all of the EL7 based containers available in Customer Portal.

**Comment by jkatz** [comment]
As an addendum, we are evaluating if there are any options in the pgBackRest upstream that can help bypass this issue (though effectively it would be disabling TLS verification), though it would be in a future release of pgBackRest and, in turn, PGO.

**Comment by dwsteele** [comment]
It would be interesting to see if passing `--no-repo1-s3-verify-tls` to `pgbackrest restore` would fix this issue. Looks like you would need to pass `--backup-opts=--no-repo1-s3-verify-tls` to `pgo`.

**Comment by OmriDim** [comment]
`--no-repo1-s3-verify-tls` is not a valid  `--backup-opts` option to `pgo restore` (we tried).

**Comment by jkatz** [comment]
Did you try setting `backrestS3VerifyTLS` to `"false"` (string value) in the custom resource?

**Comment by OmriDim** [comment]
All of our cluster's pgclusters-`backrestS3VerifyTLS` are set to `"false"`
