### ISSUE TITLE
S3 backup failure

### ISSUE THREAD

**Issue by kasuncp** [CrunchyData/postgres-operator#2395]
**What is the current behavior?**

When the operator is configured to use AWS S3 for backups, the `backrest-backup-<cluster_name>` jobs error out with the following log

```
[0;32mThu Apr 22 06:40:27 UTC 2021 INFO: Image mode found: pgbackrest[0m
[0;32mThu Apr 22 06:40:27 UTC 2021 INFO: Starting in 'pgbackrest' mode[0m
time="2021-04-22T06:40:27Z" level=info msg="crunchy-pgbackrest starts"
time="2021-04-22T06:40:27Z" level=info msg="debug flag set to %tfalse"
time="2021-04-22T06:40:27Z" level=info msg="backrest backup command requested"
time="2021-04-22T06:40:27Z" level=info msg="s3 flag enabled for backrest command"
time="2021-04-22T06:40:27Z" level=info msg="command to execute is [pgbackrest backup --type=full --db-host=10.128.0.37 --db-path=/pgdata/eng-dev --repo1-type=s3]"
time="2021-04-22T06:41:29Z" level=info msg="output=[]"
time="2021-04-22T06:41:29Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\nERROR: [039]: HTTP request failed with 403 (Forbidden):\n       *** URI/Query ***:\n       /backrestrepo/eng-dev-backrest-shared-repo/backup/db/latest\n       *** Request Headers ***:\n       authorization: <redacted>\n       content-length: 0\n       host: randoli-data-backup.s3.amazonaws.com\n       x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n       x-amz-date: <redacted>\n       *** Response Headers ***:\n       content-type: application/xml\n       date: Thu, 22 Apr 2021 06:41:28 GMT\n       server: AmazonS3\n       transfer-encoding: chunked\n       x-amz-id-2: D0pgrZZDCJN0mc40wGfhK4MK+fVfY5qWwAzJ1lzlcqwpuSU0Ai0EmbxTLkb1Hm2DMnrUdiB9RiA=\n       x-amz-request-id: H556CMFRKV9CM9D1\n       *** Response Content ***:\n       <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n       <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>H556CMFRKV9CM9D1</RequestId><HostId>D0pgrZZDCJN0mc40wGfhK4MK+fVfY5qWwAzJ1lzlcqwpuSU0Ai0EmbxTLkb1Hm2DMnrUdiB9RiA=</HostId></Error>\n]"
time="2021-04-22T06:41:29Z" level=fatal msg="command terminated with exit code 39"
```

**What is the expected behavior?**

Backups should be successfully saved in the S3 bucket.

**Other information** (e.g. detailed explanation, related issues,  etc)

Based on the documentation at https://access.crunchydata.com/documentation/postgres-operator/4.6.2/architecture/disaster-recovery I updated the `pgo.yaml` with the bucket details and the secret `pgo-backrest-repo-config` was created to provide AWS access and secret keys before deploying the operator.

It seems the `backrest-backup-<cluster_name>` pods can access the bucket as it creates a new directory structure `backrestrepo/` in the bucket. But based on the logs it's trying to access a file at `/backrestrepo/eng-dev-backrest-shared-repo/backup/db/latest` which doesn't even exist and it's getting a 403 Forbidden error.

**Please tell us about your environment:**

* Where is this running ( Local , Cloud Provider): AWS
* Storage being used (NFS, Hostpath, Gluster, etc): Ceph
* Container Image Tag: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.2-4.6.2
* PostgreSQL Version: 13.2
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 4.6.2

**Comment by jkatz** [comment]
Are the permissions on your S3 bucket set up correctly for the AWS key/key secret you're using to authenticate with?

**Comment by kasuncp** [comment]
> Are the permissions on your S3 bucket set up correctly for the AWS key/key secret you're using to authenticate with?

I added "s3:DeleteObject" to the bucket policy and it worked! I didn't think the operator needed delete permissions as these are backups and we are trying to preserve data. But I guess I was wrong. Thank you for your input, it drove me towards the solution. 

This issue can be closed.

**Comment by jkatz** [comment]
If you have retention policies set (which you should, otherwise you will be storing infinite archives and backups), you definitely need delete permissions. Additionally, pgBackRest (which powers the backup interface) may have routine file cleanup / compression, etc. as a part of its ongoing operations.

**Comment by kasuncp** [comment]
Gotcha. Thanks for the explanation @jkatz 👍
