### ISSUE TITLE
Postgresql closing connections?

### ISSUE THREAD

**Issue by kukosek** [CrunchyData/postgres-operator#2396]
**Describe the bug**
It seems that postgres closes connections to it.

**To Reproduce**
1. Create a cluster using quickstart
2. Make a python program using psycopg2 that does an operation every 1sec
3. Wait for the errors

**Expected behavior**
No error should happen

**Real behavior**
 After some time after initializing the connection, when obtaining the cursor, it throws the error:

```py
cur = db.cursor()
# psycopg2.InterfaceError: connection already closed
```
I solved this by making a DB holder class that automatically reconnects (initializes the connection again) when
this error is thrown.

But still, sometimes it losts connection even after creating the cursor and throws this error:
```py
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Please tell us about your environment:**

* Operating System: Ubuntu 20.04
* Local kubernetes cluster, just 1 node for the time being
* Storage being used: Local persistent volume
* Container Image Tag:
```
Database Images:
                         3	registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.2-4.6.2
                         3	registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-13.2-4.6.2
                         2	registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-13.2-4.6.2
```
* PostgreSQL Version: dont know
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: kubernetes installed with kubeadm

**Additional context**
Pgo pod logs is full of "Lock owner: ..." INFO and "INFO:no action. i am the leader with the lock".

Just one warning after startup of the pod:
`WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"`

I would like to see the postgres logs, but i dont know how to access them.

**Comment by jkatz** [comment]
Do you have any logs from the `/pgdata/<clustername>/pg_log` directory?

**Comment by kukosek** [comment]
> Do you have any logs from the `/pgdata/<clustername>/pg_log` directory?

```
2021-04-22 10:46:49.580 UTC [433] LOG:  unexpected EOF on client connection with an open transaction
2021-04-22 10:50:49.297 UTC [4813] LOG:  unexpected EOF on client connection with an open transaction
2021-04-22 13:08:04.134 UTC [6021] LOG:  could not receive data from client: Connection reset by peer
2021-04-22 13:08:04.134 UTC [6021] LOG:  unexpected EOF on client connection with an open transaction
2021-04-22 14:02:57.320 UTC [27198] LOG:  could not receive data from client: Connection reset by peer
2021-04-22 14:02:57.320 UTC [27198] LOG:  unexpected EOF on client connection with an open transaction
```
Also, when I opened up my servers terminal, it  was full of this:
![image](https://user-images.githubusercontent.com/16265013/115776951-03050200-a3b5-11eb-8027-846285d7f946.png)

This is an IP of the pod network. I use flannel pod network. So maybe it has something to do with something couldnt connect to the postgres DB pod? I dont know at all

**Comment by jkatz** [comment]
The PostgreSQL logs indicate that it's something from the client connection. The client is saying that can't connect to the server. So I would agree with your assessment that it's something in your network. You should try troubleshooting down that path.

I don't think this is a PGO issue.
