### ISSUE TITLE
[4.7.0-beta.2] Client still shows version as 4.6.2

### ISSUE THREAD

**Issue by aakarshg** [CrunchyData/postgres-operator#2404]
Came across this while trying to test out the 4.7.* beta releases. 

```
[blah@blah postgres-operator]$ ./installers/kubectl/client-setup.sh
Operating System found is Linux...
Downloading pgo version: v4.7.0-beta.2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   609  100   609    0     0   2082      0 --:--:-- --:--:-- --:--:--  2078
100 39.5M  100 39.5M    0     0  36.5M      0  0:00:01  0:00:01 --:--:--  238M
[blah@blah postgres-operator]$ pgo version
pgo client version 4.6.2
```

I was specifically interested to try out the latest version for the monitoring updates and the GCS bucket backup related features.

Also is there an ETA for the release candidate releases for v4.7.0 ?

**Comment by jkatz** [comment]
4.7.0-beta.2 is marked as a pre-release. We have not publicly released those images. Beta release may or may not be pushed to the Developer Portal.

In the case of the `pgo` client, I purposefully did not update the version tag in it, but I will do so in the next release.

Barring any setbacks, the GA will be within the next 2 weeks.

Information on release distribution is available here:

[https://github.com/CrunchyData/postgres-operator#releases](https://github.com/CrunchyData/postgres-operator#releases)

**Comment by jkatz** [comment]
@aakarshg If you're still curious to play with the beta, we pushed `v4.7.0-beta.3` `to registry.developers.crunchydata.com/crunchydata`
