### ISSUE TITLE
Monitoring with Splunk

### ISSUE THREAD

**Issue by eliranw** [CrunchyData/postgres-operator#2406]
**What is the motivation or use case for the change? **
We are monitoring our infrastructure with Splunk, and want to know if there can be any integrations with it. The Grafana dashboards are great for monitoring, but we would love to see the metrics in the Splunk platform for a cohesive experience. 
We currently added monitoring to our whole Openshift cluster but it is large with many projects, and would like to only monitor the Postgres clusters.

**Describe the solution you'd like**
Using Splunk HEC tokens to send all metrics to a Splunk platform instead of or in addition to using Grafana.

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jkatz** [comment]
It does appear that Splunk supports metrics from Prometheus exporters, so this may just be configuration?

There may be work that PGO could do to better support log aggregation, so I'm tentatively marking this as a enhancement, but this may just be configuration on the Splunk end?

**Comment by andrewlecuyer** [comment]
Hi @eliranw!

I recommend checking out the custom sidecar capability that is included in Crunchy Postgres for Kubernetes v5, which provides a powerful way to integrate additional tools/containers for monitoring, log collection, etc. (as well as a variety of other use cases!) into your PostgresCluster deployments:

https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/customize-cluster/#custom-sidecar-containers

Additionally, here is a great blog post that walks through this feature, as well as similar use cases, in further detail:

https://www.crunchydata.com/blog/log-export-examples-using-crunchy-postgres-for-kubernetes

And if you would like to further discuss your use-case for Splunk - or if you run into any issues using custom sidecars - please feel free to either submit a new issue, or you can also reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join) for further discussion with the community.

Thanks!
