### ISSUE TITLE
Add name of port for Prometheus Operator

### ISSUE THREAD

**Issue by AleksanderRoszig** [CrunchyData/postgres-operator#2407]
**What is the motivation or use case for the feature? **
Easier monitoring of databases with external Prometheus using Prometheus Operator 

**Describe the solution you'd like**
Add port name to database port. Now when database is deployed with --metrics flag we have:
    image: registry.connect.redhat.com/crunchydata/crunchy-postgres-exporter:ubi7-4.5.1
    imagePullPolicy: IfNotPresent
    name: postgres-exporter
    ports:
    - containerPort: 9187
      protocol: TCP
      
and Prometheus Operator need name of that port so it shoud look like:
    - containerPort: 9187
      name: postexport (in my version it has to be less than 15 characters) 
      protocol: TCP
    
    https://github.com/prometheus-operator/prometheus-operator
    https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md
    
That will be useful if someone want collect metrics but using own stack without deploying solutions from Crunchy.

**Comment by jkatz** [comment]
You can modify the `exporter.json` file in `pgo-config` to affix the name of the port. Have you tried that?

Though it may behoove us just to add names to the ports. That seems like it could be a low cost change.

**Comment by AleksanderRoszig** [comment]
I just started working on that and yet I didn't tried that so thank you for hint. 

_Though it may behoove us just to add names to the ports. That seems like it could be a low cost change._  Yes, exacly.

**Comment by jkatz** [comment]
Committed. It will be available in 4.7.0. While trivial to add, given it's technically an interface change, I don't want to backpatch.

**Comment by AleksanderRoszig** [comment]
@jkatz I see that it should be only in service https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md 

"The ServiceMonitor has a label selector to select Services and their underlying Endpoint objects. The Service object for the example application selects the Pods by the app label having the example-app value. The Service object also specifies the port on which the metrics are exposed."

**Comment by jkatz** [comment]
Thanks. I think there's no harm in adding the named ports to the Pods and perhaps they will be helpful someday.
