### ISSUE TITLE
Helm Chart - Create cluster

### ISSUE THREAD

**Issue by jiwanovski87** [CrunchyData/postgres-operator#2410]
**Which example are you working with?**
Example of how to create a new cluster with a helm chart.
[https://github.com/CrunchyData/postgres-operator/tree/master/examples/helm](url)
**What is the current behavior?**
I run the `helm install -n pgo postgres-cluster postgres` block and get a positive feedback with "When your cluster has finished deploying, you can connect to it with the following credentials:"....

But when I inspect kubernetes I cannot see that anything has happend.
Runnung `kubectl --n pgo port-forward svc/postgres 5432:5432 `ends into "Error from server (NotFound): services "postgres" not found".
**What is the expected behavior?**
The Helm script should deploy a new Postgres Cluster.
**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider)
Cloud Provider: Azure
* Storage being used (NFS, Hostpath, Gluster, etc):
PVC 
* Container Image Tag:
centos8-13.2-4.6.2
* PostgreSQL Version:

* Platform (Docker, Kubernetes, OpenShift):
1.19.9
* Platform Version:

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 **kubectl describe yourPodName**
When I run this for Pod pgoclusters I receive the following. This looks like from an earlier test today...
Name:         pgo-jiw
Namespace:    pgo
Labels:       argocd.argoproj.io/instance=cms-core
              crunchy-pgha-scope=pgo-jiw
              deployment-name=pgo-jiw
              name=pgo-jiw
              pg-cluster=pgo-jiw
              pgo-version=1.16.0
              pgouser=admin
Annotations:  current-primary: pgo-jiw
API Version:  crunchydata.com/v1
Kind:         Pgcluster
Metadata:
  Creation Timestamp:  2021-04-28T07:27:26Z       
  Generation:          1
  Managed Fields:
    API Version:  crunchydata.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:current-primary:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:argocd.argoproj.io/instance:
          f:crunchy-pgha-scope:
          f:deployment-name:
          f:name:
          f:pg-cluster:
          f:pgo-version:
          f:pgouser:
      f:spec:
        .:
        f:BackrestStorage:
          .:
          f:accessmode:
          f:size:
          f:storagetype:
        f:PrimaryStorage:
          .:
          f:accessmode:
          f:name:
          f:size:
          f:storagetype:
        f:ReplicaStorage:
          .:
          f:accessmode:
          f:size:
          f:storagetype:
        f:ccpimage:
        f:ccpimageprefix:
        f:ccpimagetag:
        f:clustername:
        f:database:
        f:exporterport:
        f:limits:
          .:
          f:cpu:
          f:memory:
        f:name:
        f:namespace:
        f:pgDataSource:
          .:
          f:restoreFrom:
          f:restoreOpts:
        f:pgbadgerport:
        f:pgoimageprefix:
        f:podAntiAffinity:
          .:
          f:default:
          f:pgBackRest:
          f:pgBouncer:
        f:port:
        f:user:
        f:userlabels:
          .:
          f:pgo-version:
    Manager:         argocd-application-controller
    Operation:       Update
    Time:            2021-04-28T07:27:26Z
  Resource Version:  460897
  Self Link:         /apis/crunchydata.com/v1/namespaces/pgo/pgclusters/pgo-jiw
  UID:               af6036a3-e7cc-445c-b5b8-700651aef7bc
Spec:
  Backrest Storage:
    Accessmode:   ReadWriteOnce
    Size:         2Gi
    Storagetype:  dynamic
  Primary Storage:
    Accessmode:   ReadWriteOnce
    Name:         pgo-jiw
    Size:         1Gi
    Storagetype:  dynamic
  Replica Storage:
    Accessmode:    ReadWriteOnce
    Size:          1Gi
    Storagetype:   dynamic
  Ccpimage:        crunchy-postgres-ha
  Ccpimageprefix:  registry.developers.crunchydata.com/crunchydata
  Ccpimagetag:     centos8-13.2-4.6.2
  Clustername:     pgo-jiw
  Database:        pgo-jiw
  Exporterport:    9187
  Limits:
    Cpu:      0.25
    Memory:   1Gi
  Name:       pgo-jiw
  Namespace:  pgo
  Pg Data Source:
    Restore From:
    Restore Opts:
  Pgbadgerport:    10000
  Pgoimageprefix:  registry.developers.crunchydata.com/crunchydata
  Pod Anti Affinity:
    Default:       preferred
    Pg Back Rest:  preferred
    Pg Bouncer:    preferred
  Port:            5432
  User:            admin
  Userlabels:
    Pgo - Version:  1.16.0
Events:             <none>
 **kubectl describe pvc**
 **kubectl get nodes**
 NAME                              STATUS   ROLES   AGE   VERSION
aks-default-41757440-vmss000000   Ready    agent   44h   v1.19.9
 **kubectl log yourPodName**

**Comment by jkatz** [comment]
Do you have any logs from the Operator Pods or the Postgres Pods that show any sort of error?

**Comment by jiwanovski87** [comment]
I do have a log from the operator pod. I cannot see any postgress pod yet.

time="2021-04-28T11:34:53Z" level=info msg="debug flag set to false" func="main.main()" file="cmd/postgres-operator/main.go:55" version=4.6.2
time="2021-04-28T11:34:58Z" level=info msg="CRUNCHY_DEBUG flag set to false" func="internal/operator.Initialize()" file="internal/operator/common.go:97" version=4.6.2
time="2021-04-28T11:34:58Z" level=info msg="NAMESPACE pgo" func="internal/operator.Initialize()" file="internal/operator/common.go:101" version=4.6.2
time="2021-04-28T11:34:58Z" level=info msg="InstallationName devtest" func="internal/operator.Initialize()" file="internal/operator/common.go:104" version=4.6.2
time="2021-04-28T11:34:59Z" level=info msg="Config: \"pgo-config\" ConfigMap found, using config files from the configmap" func="internal/config.initialize()" file="internal/config/pgoconfig.go:733" version=4.6.2
time="2021-04-28T11:34:59Z" level=info msg="default instance memory set to [128Mi]" func="internal/config.(*PgoConfig).Validate()" file="internal/config/pgoconfig.go:380" version=4.6.2
time="2021-04-28T11:34:59Z" level=info msg="default pgbackrest repository memory set to [48Mi]" func="internal/config.(*PgoConfig).Validate()" file="internal/config/pgoconfig.go:386" version=4.6.2
time="2021-04-28T11:34:59Z" level=info msg="default pgbouncer memory set to [24Mi]" func="internal/config.(*PgoConfig).Validate()" file="internal/config/pgoconfig.go:392" version=4.6.2
time="2021-04-28T11:35:00Z" level=info msg="EventTCPAddress set to localhost:4150" func="internal/operator.Initialize()" file="internal/operator/common.go:154" version=4.6.2
time="2021-04-28T11:35:00Z" level=info msg="Configure install namespaces: namespace pgo will be updated to be owned by this installation" func="internal/ns.ConfigureInstallNamespaces()" file="internal/ns/nslogic.go:511" version=4.6.2
2021/04/28 11:35:00 INF    1 (localhost:4150) connecting to nsqd
2021/04/28 11:35:00 ERR    1 (localhost:4150) error connecting to nsqd - dial tcp [::1]:4150: connect: connection refused
time="2021-04-28T11:35:00Z" level=error msg="Error: dial tcp [::1]:4150: connect: connection refused" func="pkg/events.Publish()" file="pkg/events/eventing.go:74" version=4.6.2
time="2021-04-28T11:35:00Z" level=error msg="Unable to setup namespaces: dial tcp [::1]:4150: connect: connection refused" func="internal/operator.SetupNamespaces()" file="internal/operator/common.go:542" version=4.6.2
time="2021-04-28T11:35:00Z" level=fatal msg="Error configuring operator namespaces: dial tcp [::1]:4150: connect: connection refused" func="main.main()" file="cmd/postgres-operator/main.go:84" version=4.6.2

**Comment by jkatz** [comment]
Was the `pgclusters.crunchydata.com` custom resource created?

**Comment by jiwanovski87** [comment]
Yes this is created.
See initial comment, I have put the `kubectl describe yourPodName` from there.

**Comment by jkatz** [comment]
> See initial comment, I have put the kubectl describe yourPodName from there.

I apologize, I missed that. Unfortunately it's a bit difficult to read when it's a raw, unformatted text dump.

I think there is a clue here:

```
level=fatal msg="Error configuring operator namespaces
```

in that PGO may not be watching nor have sufficient privileges to manage clusters within a namespace. If you customized the RBAC for PGO, I would suggest reading this page, which covers it in great detail:

[Namespace Management](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/)
