### ISSUE TITLE
OLM Deployment not compatible with k8s

### ISSUE THREAD

**Issue by sergeyshevch** [CrunchyData/postgres-operator#2411]
**Describe the bug**
I tryied to deploy postgres operator to my k8s cluster with OLM. And i got errors with ssh connection between pods.
After this i deployed operator with ansible pod and now it works correctly

**To Reproduce**
1. Deploy operatort with OLM deployment to pure k8s cluster
2. Create new postgres cluster

**Expected behavior**
Cluster setted up and operation correctly

**Please tell us about your environment:**

* Operating System: Ubuntu 20.04 (On all nodes)
* Where is this running ( Local, Cloud Provider): Hetzner Cloud. K8s setted up with Kubespray
* Storage being used (NFS, Hostpath, Gluster, etc): Hetzner CSI storage
* Container Image Tag: - 
* PostgreSQL Version: -
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.20.5

**Additional context**

**Comment by jkatz** [comment]
Do you have any logs that show the errors?

There is nothing here that seems to indicate that this is a problem with the OLM deployment, at least not without any logs to review what happened during the OLM deployment.

**Comment by sergeyshevch** [comment]
I will redeploy operator on new ns and send all related logs
