### ISSUE TITLE
configmap does not take effect

### ISSUE THREAD

**Issue by 1121437613** [CrunchyData/postgres-operator#2416]
Experts help me, urgently ask for help
I refer to the official website document to customize the configuration parameters of pgsql, but the strange thing is that these parameters do not take effect (for example: shared_buffers)
I created the configmap first, and then specified --custom-config through the pgo client to create the cluster

The command is as follows:

cat > mypgcluster-custom-config.yaml<<EOF
---
bootstrap:
  dcs:
    postgresql:
      parameters:
        max_connections: 3000
        shared_buffers: 8GB
        temp_buffers: 128MB
        work_mem: 128MB
        vacuum_cost_delay: 0 
        bgwriter_delay: 10ms
        bgwriter_lru_maxpages: 1000
        bgwriter_lru_multiplier: 10.0
        effective_io_concurrency: 0
        max_worker_processes: 128
        max_parallel_workers_per_gather: 0
        synchronous_commit: off
        wal_compression: on
        wal_writer_delay: 10ms
        wal_writer_flush_after: 1MB
        checkpoint_timeout: 30min
        max_wal_size: 8GB
        min_wal_size: 2GB
        checkpoint_completion_target: 0.2
        hot_standby_feedback: off
        random_page_cost: 1.1
        log_checkpoints: on
        log_statement: 'ddl'
        log_autovacuum_min_duration: 0
        autovacuum_freeze_max_age: 1500000000
        autovacuum_multixact_freeze_max_age: 1600000000
        autovacuum_vacuum_cost_delay: 0ms
        vacuum_freeze_table_age: 1450000000
        vacuum_multixact_freeze_table_age: 1450000000
        log_min_duration_statement: 5s
EOF

kubectl -n pgo create configmap mypgcluster-custom-config --from-file=mypgcluster-custom-config.yaml
pgo create -n pgo cluster mypgcluster \
--replica-count=1 \
--pvc-size=50Gi \
--pgbackrest-pvc-size=50Gi \
--cpu=2 --memory=16G \
--cpu-limit=2 --memory-limit=16G \
--custom-config=mypgcluster-custom-config

**Comment by jkatz** [comment]
You need to ]restart your PostgreSQL cluster](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_restart/) for changes to `shared_buffers` to take effect. This is covered in the PostgreSQL documentation:

[https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-SHARED-BUFFERS](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-SHARED-BUFFERS)

If you need "urgent help", I suggest reviewing the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/) page.

**Comment by 1121437613** [comment]
> 您需要[重新启动PostgreSQL群集]]（https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_restart/）才能使更改`shared_buffers`生效。PostgreSQL文档中对此进行了介绍：
> 
> https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-SHARED-BUFFERS
> 
> 如果您需要“紧急帮助”，建议您阅读[支持](https://access.crunchydata.com/documentation/postgres-operator/latest/)页面。


I have tried restart cluster, but the result has not changed
(The parameter value has not changed), I also tried deleting the pod and re-creating it, and the configuration parameter value has not changed.

**Comment by 1121437613** [comment]
> > 您需要[重新启动PostgreSQL版本]]（[https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_restart/）才能使更改“ shared_buffers”生效。PostgreSQL文档中进行进行了介绍：](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_restart/%EF%BC%89%E6%89%8D%E8%83%BD%E4%BD%BF%E6%9B%B4%E6%94%B9%60shared_buffers%60%E7%94%9F%E6%95%88%E3%80%82PostgreSQL%E6%96%87%E6%A1%A3%E4%B8%AD%E5%AF%B9%E6%AD%A4%E8%BF%9B%E8%A1%8C%E4%BA%86%E4%BB%8B%E7%BB%8D%EF%BC%9A)
> > https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-SHARED-BUFFERS
> > 如果您需要“紧急帮助”，建议您阅读[支持](https://access.crunchydata.com/documentation/postgres-operator/latest/)页面。
> 
> 我尝试了重新启动集群，但是结果没有改变
> （参数值没有改变），我还尝试了删除Pod并重新创建它，并且配置参数值没有改变。

I verified that only edit configmap <cluster_name>-pgha-config
Configuration will take effect
