### ISSUE TITLE
No provider for Postgres-Operator in Terraform

### ISSUE THREAD

**Issue by sathishc58** [CrunchyData/postgres-operator#2420]
Have an idea to improve PGO? We'd love to hear it! We're going to need some information from you to learn more about your feature requests.

Please be sure you've done the following:

- [ ] Provide a concise description of your feature request.

       Provider 'postgresql' exists to create DB's using Terraform.  However, I am unable to find out provider for 'postgres operator' using Terraform. 

- [ ] Describe your use case. Detail the problem you are trying to solve.

       I installed 'Postgres operator' manually on K8S cluster (bare-metal and NOT on cloud).   I had to automate pg-operator and creation of DB instances in pg-operator using Terraform

       However, it appears that, there's no support for 'pgo_operator'  in Terraform
      
- [ ] Describe how you envision that the feature would work.
- [ ] Provide general information about your current PGO environment.
   
       1)  CentOS 7 (on-premises not Cloud)
       2)  Terraform v0.12.2

## Overview

Provide a concise description of your feature request.

Appropriate support should be provided to automate creation of 'pgo operator' from Terraform

## Use Case

Describe your use case. Why do you want this feature? What problem will it solve? Why will it help you? Why will it make it easier to use PGO?

I am trying to automate installation, configuration and creation of DB's using PG Operator from Terraform

## Desired Behavior

Describe how the feature would work. How do you envision interfacing with it?

I would provide something like below to create postgres_operator in Terraform eg

provider "postgresql_operator" {
  // something goes here
} 

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: CentOS 7 with Kubernetes Cluster (On-premises not cloud)
- Platform Version: 7.0
- PGO Image Tag: N/A
- Postgres Version N/A
- Storage: N/A
- Number of Postgres clusters: N/A

## Additional Information

Please provide any additional information that may be helpful.

Would like to know whether there's any URL or documentation exists to install Postgres-Operator using Terraform on bare-metal server

**Comment by jkatz** [comment]
I'd be willing to look at a patch contribution.

**Comment by sathishc58** [comment]
> I'd be willing to look at a patch contribution.

Thank you Jonathan

**Comment by jkatz** [comment]
Just to be clear, I'm presently not looking to write a patch myself, but if someone were to submit a patch, I would consider it :smile:

**Comment by aakarshg** [comment]
Hey @sathishc58 can you please share your terraform workflow/plan to provision crunchy pgo/ pgo clusters through terraform ? I'll be embarking on something similar soon so maybe it'd be helpful if you can make a contribution to the installers folder. I volunteer to test and work on recommendations/suggestions for the workflow/plans. :)

**Comment by benjaminjb** [comment]
@sathishc58 do you have a terraform plan for this?
