### ISSUE TITLE
configuration file contains invalid option 'repo1-storage-verify-tls'\nWARN: configuration file contains invalid option 'repo1-storage-ca-file

### ISSUE THREAD

**Issue by Vinutha-Garimella** [CrunchyData/postgres-operator#2421]
Hi, I am using this example from postgresoperator project and creating postgres cluster by using configmaps to use s3 configurations, stanza pods results in error state with following error

`Mon May  3 14:29:26 UTC 2021 INFO: Image mode found: pgbackrest
Mon May  3 14:29:26 UTC 2021 INFO: Starting in 'pgbackrest' mode
time="2021-05-03T14:29:26Z" level=info msg="crunchy-pgbackrest starts"
time="2021-05-03T14:29:26Z" level=info msg="debug flag set to %tfalse"
time="2021-05-03T14:29:26Z" level=info msg="backrest stanza-create command requested"
time="2021-05-03T14:29:26Z" level=info msg="s3 flag enabled for backrest command"
time="2021-05-03T14:29:26Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=192.168.1.7 --db-path=/pgdata/postgres-db --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2021-05-03T14:31:27Z" level=info msg="output=[]"
time="2021-05-03T14:31:27Z" level=info msg="stderr=[WARN: configuration file contains invalid option 'repo1-storage-verify-tls'\nWARN: configuration file contains invalid option 'repo1-storage-ca-file'\nERROR: [101]: TLS error [1:336130315] wrong version number\n]"
time="2021-05-03T14:31:27Z" level=fatal msg="command terminated with exit code 101"`

https://github.com/CrunchyData/postgres-operator/blob/master/examples/kustomize/createcluster/base/pgcluster.yaml

```postgres.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-db-config-backrest
    namespace: pgo
data:
    global.conf: |-
        [global]
        repo1-s3-endpoint=minio.minio.svc.cluster.local
        repo1-s3-port=9000
        repo1-s3-bucket=pgbackup
        repo1-s3-region=us-east-1
        repo1-s3-uri-style=path
        repo1-storage-verify-tls=n
        repo1-storage-ca-file=/etc/ssl/certs/ca.cert
        repo1-retention-full=1
        repo1-retention-full-type=count
        repo1-retention-diff=2
        repo1-storage-verify-tls=n
        compress-level=9
        start-fast=y
        repo1-s3-key=<redacted>
        repo1-s3-key-secret=<redacted>
        repo1-type=s3
        [global:archive-push]
        compress-level=3
 ---
 apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
    annotations:
        current-primary: postgres-db
    labels:
        crunchy-pgha-scope: postgres-db
        deployment-name: postgres-db
        name: postgres-db
        pg-cluster: postgres-db
        pgo-version: 4.6.2
        pgouser: admin
    name: postgres-db
    namespace: pgo
spec:
    BackrestStorage:
        accessmode: ReadWriteOnce
        matchLabels: ''
        name: postgres-db-backrest-storage
        size: 1G
        storageclass: lvm-provisioner
        storagetype: dynamic
        supplementalgroups: ''
    primaryStorage:
        accessmode: ReadWriteOnce
        matchLabels: ''
        name: postgres-db-primary-storage
        size: 1G
        storageclass: lvm-provisioner
        storagetype: dynamic
        supplementalgroups: ''
    ReplicaStorage:
        accessmode: ReadWriteOnce
        matchLabels: ''
        name: postgres-db-replica-storage
        size: 1G
        storageclass: lvm-provisioner
        storagetype: dynamic
        supplementalgroups: ''
    annotations:
        global: {}
        backrest: {}
        pgBouncer: {}
        postgres: {}
    backrestStorageTypes:
        - s3
    backrestS3Bucket: pgbackup
    backrestS3Endpoint: minio.minio.svc.cluster.local:9000
    backrestS3Region: us-east-1
    backrestS3URIStyle: path
    backrestS3VerifyTLS: 'false'
    ccpimage: crunchy-postgres-ha
    ccpimageprefix: registry.developers.crunchydata.com/crunchydata
    ccpimagetag: centos8-13.2-4.6.2
    clustername: postgres-db
    database: hotelsoft
    exporterport: '9187'
    limits: {}
    name: postgres-db
    namespace: pgo
    pgDataSource:
        restoreFrom: ''
        restoreOpts: ''
    pgbadgerport: '10000'
    pgoimageprefix: registry.developers.crunchydata.com/crunchydata
    podAntiAffinity:
        default: preferred
        pgBackRest: preferred
        pgBouncer: preferred
    port: '5432'
    tolerations: []
    user: pgoadmin
    userlabels:
        pgo-version: 4.6.2
 
*******Cluster status******
kubectl get pods -n pgo
NAME                                                READY   STATUS      RESTARTS   AGE
pgo-deploy-wtwcq                                    0/1     Completed   0          106m
postgres-db-74cb558b8b-459gv                        1/1     Running     0          30m
postgres-db-backrest-shared-repo-65f342sb-2dfnlc   1/1     Running     0          30m
postgres-db-stanza-create-6km85                     0/1     Error       0          28m
postgres-db-stanza-create-6qpxh                     0/1     Error       0          26m
postgres-operator-775568bc-pqbdt                    4/4     Running     0          106m


can anyone help me with configuration.

**Comment by Vinutha-Garimella** [comment]
Hi, can anyone let me know the  correct configuration of these two variables
`repo1-storage-verify-tls=n
  repo1-storage-ca-file=/etc/ssl/certs/ca.cert`

**Comment by jkatz** [comment]
If you're looking for immediate support, I suggest reading the [Support](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/) page. Otherwise you will have to wait for someone in the community to respond.

**Comment by Vinutha-Garimella** [comment]
Hi, I still face the same issue with this image as well, if there is any fix for it please let me know

```
ccpimage: crunchy-postgres-gis-ha
ccpimagetag: centos8-13.2-3.0-4.6.2
```

**Comment by jkatz** [comment]
> TLS error [1:336130315] wrong version number\n]

This sounds like there is a TLS incompatibility somewhere in your system, likely TLS being too old on your MinIO host.

**Comment by Vinutha-Garimella** [comment]
@jkatz  thanks for response, 

I am trying to disable the tls check in postgres for minio settings, I don't know why it's still checking the tls certificates for minio host

**Comment by Vinutha-Garimella** [comment]
Closing this issue as postgres needs tls certificates of minio, while creating minio cluster I didn't create it with `requestAutoCert: true,` option because of which I was facing issue with postgres cluster creation.
After recreating minio with certificate I am able get postgres pods up and running with correct backup buckets creations etc.
