### ISSUE TITLE
Sheduled backup job fails

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#2425]
Good day!

We are facing strange behaviour during scheduled cluster backup. For a long period of time it was working just fine.
But today it fineshed with exit code. Here is the log:

 |   | 2021-05-04 12:03:33 | time="2021-05-04T09:03:33Z" level=fatal msg="error dialing backend: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-eb8eb4bc40984d3dd49a\"?"
-- | -- | -- | --
  |   | 2021-05-04 12:03:33 | time="2021-05-04T09:03:33Z" level=info msg="stderr=[]"
  |   | 2021-05-04 12:03:33 | time="2021-05-04T09:03:33Z" level=info msg="output=[]"
  |   | 2021-05-04 12:03:33 | time="2021-05-04T09:03:33Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --type=incr  --repo1-retention-full=2 --repo1-retention-full-type=count --db-host=10.0.1.50 --db-path=/pgdata/pgsql-cluster ; pgbackrest backup --stanza=db --type=incr  --repo1-retention-full=2 --repo1-retention-full-type=count --db-host=10.0.1.50 --db-path=/pgdata/pgsql-cluster --repo1-type=s3 --no-repo1-s3-verify-tls]"
  |   | 2021-05-04 12:03:33 | time="2021-05-04T09:03:33Z" level=info msg="backrest command will be executed for both local and s3 storage"
  |   | 2021-05-04 12:03:33 | time="2021-05-04T09:03:33Z" level=info msg="backrest backup command requested"
  |   | 2021-05-04 12:03:33 | time="2021-05-04T09:03:33Z" level=info msg="debug flag set to %tfalse"
  |   | 2021-05-04 12:03:33 | time="2021-05-04T09:03:33Z" level=info msg="crunchy-pgbackrest starts"
  |   | 2021-05-04 12:03:33 | Tue May  4 09:03:33 UTC 2021 INFO: Starting in 'pgbackrest' mode
  |   | 2021-05-04 12:03:33 | Tue May  4 09:03:33 UTC 2021 INFO: Image mode found: pgbackrest

Please tell us about your environment:
Google Kubernetes Engine cluster
Container Image Tag: crunchy-postgres-ha:centos8-13.2-4.6.2
Platform Version: 1.18.16-gke.502

**Comment by jkatz** [comment]
Sounds like an issue in your environment. Has something changed with your networking or node settings? Did you recently perform a Kube update?

**Comment by aprilito1965** [comment]
Absolutely nothing. It is an incremental backup. It runs every 3 hours. And today it just started to fail& Nothing has changed during last weeks. No auto updates or something like that, no deploys. I will try to recreate the schedule and write back.

**Comment by aprilito1965** [comment]
Addition.

When I try to port forward postgres operator pod with:

kubectl -n pgo port-forward svc/postgres-operator 8443:8443

I also receive:

error: error upgrading connection: error dialing backend: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-eb8eb4bc40984d3dd49a"?

**Comment by aprilito1965** [comment]
It is definitely a kubernetes cluster issue. Closing.

Thank you for your work and quick responce!
