### ISSUE TITLE
Pgmonitor custom url path for accessing grafana service via ingress

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#2426]
Hi!

Is there a way to pass a parameter during kubernetes deploy to change default url path used for accessing grafana service (via ingress resource for example)?
It is actually posible with something like that:

[server]
domain = example.com
root_url = http://example.com/monitoring/

In my other grafana instance (included in prometheus-stack helm chart) i use this values.yaml snippet:

grafana.ini:
server:
domain: examplehost.com
root_url: "%(protocol)s://%(domain)s:%(http_port)s/graf/"
serve_from_sub_path: true

I know that it is also a way to do it with env:

grafana:
env:
GF_SERVER_ROOT_URL: https://myhostname.example.com/grafana
GF_SERVER_SERVE_FROM_SUB_PATH: 'true'

Thank you!

**Comment by jkatz** [comment]
I'd entertain a proposed patch for this.

**Comment by benjaminjb** [comment]
Hi @aprilito1965 is this still an ongoing issue for you? It sounds like you might be able to accomplish this (as you note) through adding some particular env vars to our [monitoring stack](https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/monitoring/grafana/deployment.yaml#L14).

I'm going to close this ticket, but please reopen if you want to continue the conversation around this.
