### ISSUE TITLE
Any way to specify more than 1 process to be used for internal backups?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2427]
Hello,

We have some use cases where we have to delete a PG instance with the --keep-backups and --keep-data (or only --keep-backups) and create it again using the existing PVC(s). 
This works fine. But, if the cluster size is large, this takes a while until the cluster is up and ready.
In such a case, pgo starts a backup during the setup process. This backup is started with 1 process (pgbackrest give the option to start several processes to run the backup and speed it up).

So my question:
Is there any way to adjust the number of process that is started in such a case?

Thanks,
José

**Comment by benjaminjb** [comment]
Hello @jose-joye, is this still a problem you're experiencing? And are you still on v4? I'm going to preemptively close this ticket as this issue hasn't seen a lot of activity, but if this is still an issue, please reopen it so we can continue the conversation. Cheers!
