### ISSUE TITLE
How can I generate swagger docs for postgres-operator locally?

### ISSUE THREAD

**Issue by andrewzah** [CrunchyData/postgres-operator#2429]
This doesn't seem to be documented anywhere. We would like to generate swagger docs locally.

**Comment by kevinlmadison** [comment]
Wondering this as well, thank you!

**Comment by ccravens** [comment]
I asked this question like a year ago with no response 🤷‍♂️

https://github.com/CrunchyData/postgres-operator/issues/1336

**Comment by jkatz** [comment]
What are you doing that involves a direct integration to the API server?

**Comment by kevinlmadison** [comment]
Creating and managing postures clusters via our own custom API. Using a CLI
isn't a good option for us.

**Comment by benjaminjb** [comment]
Is this something people are still interested in having?
