### ISSUE TITLE
Add replication role information in show cluster command

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#243]
Newer pod names do not contain "replica" word in it. So, it is difficult to know which pod is the primary.
Can you add replication role information in the output of 
"pgo show cluster <cluster>" command

**Comment by jmccormick2001** [comment]
added code into pgo command to print 'primary' on the pgo show cluster output for the pod that is the primary within the cluster.  This is in the autofail branch and will make it to rel 3.1.
