### ISSUE TITLE
question pgo 4.7.0: ensure replica is created when sync replication is chosen during cluster creation

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2430]
I read the release notes for pgo 4.7.0 and 1 change has taken my attention:

> Ensure that at least one replica is created when sync replication is chosen during cluster creation.

Do you mean that creating a cluster with sync replication enabled (but without replica) will lead to a cluster with 1 replica automatically?

If this is the case, this means we have no option to easily convert a cluster created without replica to a cluster with a sync replica. In fact, under 4.5.1, I have used this 'trick' in order to allow, at a later stage, to scale a cluster initially created without replica to a cluster with sync replica (This was a workaround for a previous question: https://github.com/CrunchyData/postgres-operator/issues/2354)

Regards,
José

**Comment by jkatz** [comment]
https://github.com/CrunchyData/postgres-operator/pull/2392/files has the details on how this works. It's just at the CLI/API level, and basically it just says that if you create a cluster with `--sync-replication`, you need to set `--replica-count` to be at least 1.

You can do whatever you want thereafter in the lifecycle of a cluster.
