### ISSUE TITLE
UserLabels not being applied

### ISSUE THREAD

**Issue by ccravens** [CrunchyData/postgres-operator#2431]
Please ensure you do the following when reporting a bug:

I upgraded from 4.4.1 to 4.6.2, this used to work in 4.4.1 but does not seem to be working in 4.6.2.

I send a POST request to `/clusters` and it creates my postgres cluster, but is not creating kubernetes labels from the `UserLabels` attribute. Been looking through the code and it seems like it should still be working?

- Platform: `Kubernetes`
- Platform Version: `1.20.4`
- PGO Image Tag: `centos8-4.6.2`
- Postgres Version `13`
- Storage: `ceph`

## Steps to Reproduce
Set a label via UserLabels like `mylabel=label`, upgrade to 4.6.2, cluster created but label not applied

### EXPECTED

Label to be on postgres deployment object

### ACTUAL

No label

**Comment by jkatz** [comment]
The `UserLabels` functionality received an overhaul in 4.7.0. You can test this in `4.7.0-beta.3`.

**Comment by kevinlmadison** [comment]
I see this has been marked as a duplicate, can you link to the duplicate issue please?

**Comment by ccravens** [comment]
@jkatz thank you for your response! Ok I'll try `4.7.0-beta.3`. Does this overhaul mean that the way I apply a label to a postgres deployment is changed? Or should it still be the same? Something like this:

```
https.post('/clusters',
        {
          ArchiveFlag: true,
          .........
          UserLabels: `mylabel=label`,
          Username: '',
        }
```

**Comment by jkatz** [comment]
4.7 work: https://github.com/CrunchyData/postgres-operator/pull/2424

However, with the additional context, I believe the change though between 4.4 and 4.6 is that the input for how UserLabels can be submitted changed to be parsed into a `map` type:

https://github.com/CrunchyData/postgres-operator/blob/master/pkg/apiservermsgs/clustermsgs.go#L60

which was described in the [4.6 Breaking Changes](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.6.0/#breaking-changes) section of the docs in the context of the CLI:

> The --labels flag on pgo create cluster is removed and replaced with the --label, which can be specified multiple times. The API endpoint for pgo create cluster is also modified: labels must now be passed in as a set of key-value pairs. Please see the “Features” section for more details.
