### ISSUE TITLE
How to determine standby cluster replication lag

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#2433]
pgo 4.5.0

What is the best way to determine replication lag of the standby cluster?  Is there a pgo query to determine this?  Been looking through the documentation here: https://access.crunchydata.com/documentation/postgres-operator/4.6.2/architecture/high-availability/multi-cluster-kubernetes/ and not seeing anything.

**Comment by jkatz** [comment]
Discussing with upstream, we would first need to have a new metric available that can help calculate this. There is a [patch](https://github.com/CrunchyData/pgmonitor/pull/241/commits/865b57efd6b1b1327b161c878f7b454ffe4c8bb7) proposed here. There is some discussion that goes along with this metric as well.

We would then need to wait on the metric being incorporated into the dashboards -- from there we could set up the various orchestration to handle it.

Thanks for the suggestion!

**Comment by benjaminjb** [comment]
Since the fix referenced above was merged, I'm going to close this PR, but if you're having trouble getting that metric, please reopen to discuss the issue.
