### ISSUE TITLE
Cannot use a custom image

### ISSUE THREAD

**Issue by kasuncp** [CrunchyData/postgres-operator#2434]
I'm using the Crunchy Data Operator 4.6.2 on OpenShift 4.6. 

In the [documentation](https://access.crunchydata.com/documentation/postgres-operator/4.6.2/pgo-client/reference/pgo_create_cluster/), I noticed that we can give a custom Postgres image by specifying values for `CCPImage`, `CCPImagePrefix`, and `CCPImageTag`. 

I tried the following command to deploy a cluster using an [image from Docker Hub](https://hub.docker.com/layers/crunchydata/crunchy-postgres-ha/centos7-11.10-4.4.2/images/sha256-01de82c1e1ee3a2b6624e7b6c8f647a108aa3a4e5a1d2dad50fe0199ec6a0a0a?context=explore)  

```
pgo create cluster -n $PGO_OPERATOR_NAMESPACE my-db \
 --ccp-image-prefix=crunchydata \
 --ccp-image=crunchy-postgres-ha \
 --ccp-image-tag=centos7-11.10-4.4.2
```

But the deployed cluster still uses the default image `registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.2-4.6.2`. 

Then I tried only changing the image tag, keeping default values for the other params.

```
pgo create cluster -n $PGO_OPERATOR_NAMESPACE my-db \
--ccp-image-tag=centos8-13.1-4.6.0
```

But this still creates a Postgres 13.2 instance. 

Is there anything else I need to specify in the command?

**Comment by jkatz** [comment]
Using 4.6.2, with my default image repository not being the upstream repo:

```
$ pgo version
pgo client version 4.6.2
pgo-apiserver version 4.6.2

$ pgo create cluster custom-hippo \
  --ccp-image-prefix=registry.developers.crunchydata.com/crunchydata \
  --ccp-image-tag=centos8-13.1-4.6.0
created cluster: custom-hippo

$ kubectl -n jkatz describe deployments.apps custom-hippo
Name:                   custom-hippo
Namespace:              jkatz
CreationTimestamp:      Fri, 07 May 2021 13:07:48 +0000

[TRUNCATED]

  Containers:
   database:
    Image:       registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.1-4.6.0
```

So without any corresponding error logs (prompted by the "file a bug" workflow), there's nothing to indicate here that there is a bug.

https://github.com/CrunchyData/postgres-operator/issues/2387#issuecomment-822506812 also mentions which images are publicly available, whereas [https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/) discusses compatibility.
