### ISSUE TITLE
pgo version compatibility check

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#244]
using a pgo client that is not of the same version as the apiserver usually results in weird error like below.

Could you do a compatibility check and print a user friendly error message

INFO[0000] &{0xc420010580 {0 0} false 0xc420014130 <nil> 0x6764e0}
 
ERRO[0000] json: cannot unmarshal object into Go struct field ShowClusterPod.PVCName of type string 
INFO[0000] json: cannot unmarshal object into Go struct field ShowClusterPod.PVCName of type string

**Comment by jmccormick2001** [comment]
merged code into autofail branch, will land in 3.1 release, after this change pgo client and server versions must match or an error is returned to the pgo client user.  The reason for this code change is to avoid cases where old pgo clients are attempting to work with more recent versions of the server API.
