### ISSUE TITLE
allow pgo commands to output yaml files

### ISSUE THREAD

**Issue by kesavkolla** [CrunchyData/postgres-operator#2442]
It would be great if pgo commands has a flag which can generate yaml file. I wanted to use pgo create cluster command but before creating it I want to check the yaml file whether everything is correct or not.

**Comment by benjaminjb** [comment]
That's an interesting idea, and something I might want to implement in the new v5 client. Just to check, are you still running into this need? And are you still using v4 and its client?

**Comment by kesavkolla** [comment]
Right now I am not using any version. I've upgraded my kubernetes and this operator is not compatible with new version. It's still a very useful feature in my opinion

**Comment by benjaminjb** [comment]
Oh, we actually just released 5.3.0 this week for our open-source users which is compatible with K8s v1.25. (I'm going to make a note about the pgo create to yaml in our v5 client, but will close this issue otherwise.)
