### ISSUE TITLE
Unable to find information how to Upgrade the cluster when going from Postgres centos7 postgres 12 -> centos8  postgres 13

### ISSUE THREAD

**Issue by psavva** [CrunchyData/postgres-operator#2454]
Dear Developers, 

I have updated my postgres operator from version 4.4 to the latest 4.6.2
I have followed the guide for the automated upgrade using ansible.  After some roadhumps (probably my fault), I had finally upgraded the operator, and all was working well.

I am now trying to upgrade my postgres from version centos7-12.3-4.4.0 to centos8-13.2-4.6.2

```
[root@FLATRO metrics-server]# pgo -n pgo upgrade neha-dgc
All active replicas will be scaled down and the primary database in this cluster will be stopped and recreated as part of this workflow!
WARNING: Are you sure? (yes/no): yes
Error: cannot upgrade from centos7-12.3-4.4.0 to centos8-13.2-4.6.2, upgrade task failed.
[root@FLATRO metrics-server]#

```

Please can I request help, perhaps instructions on how to achieve the upgrade?

**Comment by jkatz** [comment]
Upgrading between the two follows the [standard upgrade process](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/automatedupgrade/).

To see if there is a bug, you would need to provide way more details, such as what is suggested in the [bug reporting template](https://github.com/CrunchyData/postgres-operator/issues/new?assignees=&labels=&template=bug_report.md).
