### ISSUE TITLE
[4.7.0] Can't install pgo through pgo-deployer as the image doesn't seem to exist

### ISSUE THREAD

**Issue by aakarshg** [CrunchyData/postgres-operator#2456]
## Overview

Cloned the latest master and tried to install 4.7.0 version of pgo as follows:
`kubectl apply -f installers/kubectl/postgres-operator.yml`

The above command did create the job object but pod couldn't be created as the image wasn't found:

```
  Normal   Pulling         14s (x2 over 29s)  kubelet, gke-dev-default-pool-f7874cb6-8zmz  Pulling image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos8-4.7.0"
  Warning  Failed          14s (x2 over 29s)  kubelet, gke-dev-default-pool-f7874cb6-8zmz  Failed to pull image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos8-4.7.0": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos8-4.7.0 not found: manifest unknown: manifest unknown
  Warning  Failed          14s (x2 over 29s)  kubelet, gke-dev-default-pool-f7874cb6-8zmz  Error: ErrImagePull
  Normal   BackOff         2s (x4 over 28s)   kubelet, gke-dev-default-pool-f7874cb6-8zmz  Back-off pulling image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos8-4.7.0"
  Warning  Failed          2s (x4 over 28s)   kubelet, gke-dev-default-pool-f7874cb6-8zmz  Error: ImagePullBackOff
```

## Environment

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.): GKE
- Platform Version: (e.g. `1.20.3`, `4.7.0`): 1.17
- PGO Image Tag: (e.g. `centos8-4.7.0`) centos8-4.7.0
- Postgres Version (e.g. `13`) 13
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class) pd-ssd

## Additional Information

Wondering if we've to register somewhere to be able to pull images for 4.7.0 as i'm able to pull the 4.6.2 image fine.

**Comment by jkatz** [comment]
Please see information about how releases roll out here in the [README](https://github.com/CrunchyData/postgres-operator#releases):

https://github.com/CrunchyData/postgres-operator#releases

Currently 4.7.0 is marked as a pre-release.

Thanks!

**Comment by aakarshg** [comment]
Thanks.. I should've read that. it's my bad.
