### ISSUE TITLE
Pod postgres-pgo fails to start

### ISSUE THREAD

**Issue by lyptt** [CrunchyData/postgres-operator#246]
With the latest helm chart from master (#666ae19), postgres-pgo fails to successfully start, with postgres-operator reporting the following error:

> E0604 06:16:25.772145       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/backupcontroller.go:82: Failed to list *v1.Pgbackup: pgbackups.cr.client-go.k8s.io is forbidden: User "system:serviceaccount:data:default" cannot list pgbackups.cr.client-go.k8s.io in the namespace "data"
time="2018-06-04T06:16:25Z" level=error msg="error watching upgrade jobunknown (get jobs.batch)"

The service account postgres-pgo is definitely being created, so I'm not really sure what the issue is.

**Comment by jmccormick2001** [comment]
should be working as of 3.2.0.
