### ISSUE TITLE
Node Affinity for PgBackrest (shared-repo deployment)

### ISSUE THREAD

**Issue by RenaudDemarneffe** [CrunchyData/postgres-operator#2464]
## Overview

I could be very nice if it was possible to define node affinity rules for the PgBackrest (the backrest-shared-repo deployment).
Indeed, actually, we are able to define node affinity rules for the Postgres cluster (master and replicas) but for the deployment managing the backups, it's not possible.

## Use Case

For e.g., into my configuration, I have some nodes of the cluster that are on a node pool with elasticity (for running jobs) and some on a node pool without elasticity (for running deployments). I'm able to force the postgres cluster running on nodes without elasticity but I'm not able for the backrest-shared-repo deployment.
Another use case is to force running the backrest-shared-repo deployment into a special zone of the cluster.

## Desired Behavior

Beeing able to specify node affinity rules for  backrest-shared-repo deployment.

## Environment

- Platform: `Kubernetes` `AKS`
- Platform Version: `4.7.0`
- PGO Image Tag: `centos8-4.7.0`
- Postgres Version: `13`
- Storage: `pvc`
- Number of Postgres clusters: (`2`)

**Comment by jkatz** [comment]
This is added in [PGO 5.0](https://access.crunchydata.com/documentation/postgres-operator/v5/). I don't believe the tutorial has an example for this specific case, but you can configure it in `spec.backups.pgbackrest.repoHost.dedicated` in the `postgrescluster` custom resource.
