### ISSUE TITLE
synchronous services

### ISSUE THREAD

**Issue by OmriDim** [CrunchyData/postgres-operator#2465]
Describe the bug
as a cloud services provider we need a solution for synchronic action on the users clusters, our initial idea was that every pgo command is followed by the creation of a pgtask object, because it is not the situtaion, we must have a way to make sure all operations were finished successfully.
we have tried monitoring the `pgo show cluster` command, but it is not reliable.
can you suggest any 'best practice'  solutions for us?

Expected behavior
synchronous services for crunchtdata operator.

Please tell us about your environment:
crunchy version 4.6.1
Where is this running ( Local, Cloud Provider): on prem openshift
Container Image Tag: centos7-12.6
PostgreSQL Version: 12.6
Platform (Docker, Kubernetes, OpenShift): openshift
Platform Version: openshift 4.5

thank you!

**Comment by benjaminjb** [comment]
Is this still something you're running into @OmriDim ? Are you still using PGO v4.6?
