### ISSUE TITLE
Artifacts created by PGO are not recognizable by label

### ISSUE THREAD

**Issue by mdraijer** [CrunchyData/postgres-operator#2470]
Please ensure you do the following when reporting a bug:

- [ ] Provide a concise description of what the bug is.
- [ ] Provide information about your environment.
- [ ] Provide clear steps to reproduce the bug.
- [ ] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [ ] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

## Overview

When a namespace is designated to be watched by the operator (by putting labels on the namespace), some objects are created. These objects must be recognizable by a label. Some are (label "vendor=crunchydata") but many are not.

An important reason to have them recognizable is to be able to delete them when the namespace is not watched by the operator anymore.

## Environment

- Platform Version: `Kubernetes 1.19` (`OpenShift 4.6`)
- PGO Image Tag: (e.g. `centos8-4.6.1`)

## Steps to Reproduce

* In a particular namespace, perform `kubectl get sa,secret,role,rolebinding --show-labels`.
* Put the labels on the namespace so it is watched by the operator.
* Perform `kubectl get sa,secret,role,rolebinding --show-labels` again and observe the differences.

4 Service accounts are created of which only 1 has a label:

```
serviceaccount/pgo-backrest   2         36m   <none>
serviceaccount/pgo-default    2         36m   <none>
serviceaccount/pgo-pg         2         36m   vendor=crunchydata
serviceaccount/pgo-target     2         36m   <none>
```

The secrets for the service account do not need a label because they are tightly coupled to the sa and they are deleted automatically when the sa is deleted.

1 other secret is created by the operator without a label:

```
secret/postgres-operator-dockercfg-5x89v   kubernetes.io/dockercfg               1      36m     <none>
```

3 Roles are created of which only 1 has a label:

```
role.rbac.authorization.k8s.io/pgo-backrest-role                                         2021-05-26T13:15:51Z   <none>
role.rbac.authorization.k8s.io/pgo-pg-role                                               2021-05-26T13:15:52Z   vendor=crunchydata
role.rbac.authorization.k8s.io/pgo-target-role                                           2021-05-26T13:15:51Z   <none>
```

3 Role bindings are created of which only 1 has a label:

```
rolebinding.rbac.authorization.k8s.io/pgo-backrest-role-binding                                 Role/pgo-backrest-role                                         36m     <none>
rolebinding.rbac.authorization.k8s.io/pgo-pg-role-binding                                       Role/pgo-pg-role                                               36m     vendor=crunchydata
rolebinding.rbac.authorization.k8s.io/pgo-target-role-binding                                   Role/pgo-target-role                                           36m     <none>
```

### EXPECTED

All artifacts mentioned above have the label "vendor: crunchydata" so they can easily be distinguished and removed when necessary.

## Additional Information

I know that the pgo-config configmap can be patched to add labels, but this should be built in in the operator.

**Comment by jkatz** [comment]
@mdraijer Thanks for reporting. I agree, all of the associated objects with PGO should have labels.

I'll treat this as a bug as it seems safe/prudent to backpatch.

**Comment by jkatz** [comment]
I've made a first pass at this (and a patch up soon). However, this Secret:

> secret/postgres-operator-dockercfg-5x89v 

PGO doesn't create any image pull secrets automatically, so I don't think it's PGO's responsibility to affix its label to any pull secrets that may later be associated with it.
