### ISSUE TITLE
could not create replica after restore

### ISSUE THREAD

**Issue by nogoodbay** [CrunchyData/postgres-operator#2471]
## Overview

When i restore a cluster by `pgo create cluster new-cluster --restore-from=...` everything is ok, but when i scale up , i can see the new Pgreplica status like this:

```
status:
  message: Pgreplica processing pending the creation of the initial backup
  state: pgreplica Pending init
```

The new-cluster status like this:

```
status:
  message: Pgcluster successfully bootstrapped from an existing data source
  state: pgcluster Bootstrapped
```

After search the postgres-operator source code, i find these code in `pgreplicacontroller.go` file:

```
if cluster.Status.State == crv1.PgclusterStateInitialized {
  // create Rgreplica
  ..
} else {
 // set replica to PgreplicaStatePendingInit stats
 ...
}

```

So create replica only if the cluster is `PgclusterStateInitialized`，but after restore , the cluster is not that state。
And then i want to know when the cluster state when to set `PgclusterStateInitialized`，i find method `SetClusterInitializedStatus` in `controllerutil.go` file, this method set cluster state to `PgclusterStateInitialized`.

After search where invoke that method, i found following:

1. `backresthandler.go` file line 87, which when pgha-backup-type is bootstrap
2. `backresthandler.go` file line 147, which when cluster is standby
3. `inithandler.go` file line 225, which when handle standby cluster initilization
4. `promotionhandler.go` file line 88, which when promote pod

It is likely when create a cluster restore from an exist cluster not invoke any of these 4 methods。

Then i manual modify the new-cluster status to `PgclusterStateInitialized`, and scale again, everything is ok.

My questions are:
1. why cluster could not set to `PgclusterStateInitialized`
2. is it ok when i manual modify status to `PgclusterStateInitialized`

## Environment

Please provide the following details:

- Platform: `Kubernetes`
- Platform Version: `4.7.0`
- PGO Image Tag:`centos8-4.7.0`
- Postgres Version  `12`
- Storage: longhorn

**Comment by jkatz** [comment]
- Did the Postgres cluster actually initialize?
- Was an initial backup created? What does `pgo show backup new-cluster` say?
