### ISSUE TITLE
Scheduling backups through CustomResourceDefinitions (CRDs)

### ISSUE THREAD

**Issue by ekolovos** [CrunchyData/postgres-operator#2477]
Hi All,
  After checking thoroughly the docs and the issues on github, I was not able to find the resource definitions for scheduling backups through declarative manifests. As of now the only way that I found to schedule backups is through pgo cli. I have checked this page (https://access.crunchydata.com/documentation/postgres-operator/4.1.2/overview/scheduler-overview/) but it is very generic and does not provide enough information.

So, Would it be possible to provide some clues on how to schedule backups through CRDs ?

Thank you for your time.

**Comment by jkatz** [comment]
This was asked on the community support mailing list.
