### ISSUE TITLE
pgbackrest-pods from Operator 4.7.0 do not pick up ssh-config

### ISSUE THREAD

**Issue by ibotty** [CrunchyData/postgres-operator#2478]
## Overview

The ssh-config is not picked up by any pgbackrest pods (e.g. `my-db-bootstrap-xxx` for new db clusters or `backrest-backup-my-db-xxx` for db clusters provisioned with earlier versions).

Log-excerpt follows.  Note SSH port `22`.

```
[...]
Tue Jun  1 07:41:46 UTC 2021 INFO: Applying SSHD..
Tue Jun  1 07:41:46 UTC 2021 INFO: nss_wrapper: ssh configured
Tue Jun  1 07:41:46 UTC 2021 INFO: Checking for SSH Host Keys in /sshd..
Tue Jun  1 07:41:46 UTC 2021 INFO: Checking for authorized_keys in /sshd
Tue Jun  1 07:41:46 UTC 2021 INFO: Checking for sshd_config in /sshd
Tue Jun  1 07:41:46 UTC 2021 INFO: Starting SSHD..
WARNING: 'UsePAM no' is not supported in Fedora and may cause several problems.
Tue Jun  1 07:41:46 UTC 2021 INFO: Starting background process to monitor Patroni initization and restart the database if needed
Tue Jun  1 07:41:46 UTC 2021 INFO: Initializing cluster bootstrap with command: '/usr/local/bin/patroni /tmp/postgres-ha-bootstrap.yaml'
Tue Jun  1 07:41:46 UTC 2021 INFO: Patroni will not run as PID 1. Creating signal handler
2021-06-01 07:41:46,703 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-06-01 07:41:46,705 INFO: Lock owner: None; I am keycloak-db-bootstrap-qg9dt
2021-06-01 07:41:46,749 INFO: trying to bootstrap a new cluster
2021-06-01 07:41:46,749 INFO: Running custom bootstrap script: /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh primary
Tue Jun  1 07:41:46 UTC 2021 INFO: Valid PGDATA dir found for primary, a delta restore will be peformed
ERROR: [125]: remote-0 process on 'keycloak-db-backrest-shared-repo.auth.svc.cluster.local.' terminated unexpectedly [255]: ssh: connect to host keycloak-db-backrest-shared-repo.auth.svc.cluster.local. port 22: No route to host
Tue Jun  1 07:41:49 UTC 2021 ERROR: pgBackRest primary Creation: pgBackRest restore failed when creating primary
[...]
```

The ssh-config looks ok-ish though:
```
sh-4.4$ cat /sshd/config
Host *
        StrictHostKeyChecking no
        IdentityFile /tmp/id_ed25519
        Port 2022
        User pgbackrest
sh-4.4$ ssh -F /sshd/config keycloak-db-backrest-shared-repo.auth.svc.cluster.local hostname
keycloak-db-backrest-shared-repo-67b44666cb-f8wcr
```

## Environment

Please provide the following details:

- Platform: OpenShift (OKD)
- Platform Version: 4.7.0-0.okd-2021-05-22-050008
- PGO Image Tag: `centos8-13.3-4.7.0`
- Postgres Version `13`
- Storage: local-storage or rook-rbd

**Comment by ibotty** [comment]
I am pretty sure that CrunchyData/crunchy-containers@1f3c04f20c22d5d35e05aa15c64627aeb50d1fce is the problem.

It does not copy `.ssh/config`.

**Comment by jkatz** [comment]
We've not been able to reproduce the above, but https://github.com/CrunchyData/crunchy-containers/pull/1366 may fix the issue.

**Comment by ibotty** [comment]
That might very well be the reason.  Do I have to manually update the `*-backrest-repo-config` secrets?  Or how can I ensure that they are up-to-date?  I am using multi-namespace operator btw.

**Comment by ibotty** [comment]
I checked and the pgo-config manifest templates did not get updated.  I replaced the operator's pgo-config configmap with the files in `installers/ansible/roles/pgo-operator/files/pgo-config` and the pgo-backrest-repo-config configmap with `installers/ansible/roles/pgo-operator/files/pgo-backrest-repo/sshd_config`.  Afterwards I could create new databases again.

How can I ensure, that these files get updated?

**Comment by andrewlecuyer** [comment]
As of PGO v5.1, SSHD has been removed from the PGO architecture, and has been replaced with TLS.  Per the [PGO v5.1.0 relase notes](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.1.0/):

> Previous versions of PGO relied on the use of ssh to take backups and store archive files on Kubernetes-managed storage. PGO v5.1 now uses mTLS to securely transfer and manage these files.

We therefore recommend [upgrading](https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/v4tov5/) to the latest version of PGO v5, and if you still have trouble with restore, backups, etc., please do not hesitate to reach out.

The docs for the latest version of PGO v5 can be found here:

https://access.crunchydata.com/documentation/postgres-operator/latest/
