### ISSUE TITLE
Use crunchy pgMonitor to monitor external postgres cluster.

### ISSUE THREAD

**Issue by empeekdev** [CrunchyData/postgres-operator#2479]
Hi! Does there any example how we can configure crunchy pgMonitor to fetch data from external postgres-exporters? What exactly I mean: we have two clusters, the first one is desired for application deployment, the another one for service tools ( registries, monitoring and etc). It would be great if there was some opportunity for monitoring postgres cluster in first kubernetes cluster from the second one. 
We’ve already tried to set target in default job in prometheus config file but it doesn’t work as expected. As I saw there is `__data__` label with database container IP in pod. I know that we can change service type for postgres cluster from ClusterIP to LoadBalancer to get external ip, so maybe we can force prometheus listen external address instead of internal one from local cluster?   
Thanks in advance for the reply!

**Comment by empeekdev** [comment]
I don't know if this is the correct repository for this issue, so maybe it should have been asked at https://github.com/CrunchyData/pgmonitor

**Comment by empeekdev** [comment]
Closing this issue. The current goal can be achieved using prometheus federation

**Comment by jkatz** [comment]
This topic is discussed here: https://groups.google.com/a/crunchydata.com/g/postgres-operator/c/5ZnNyK5eKf4
