### ISSUE TITLE
Custom Image tags being overridden

### ISSUE THREAD

**Issue by turbra** [CrunchyData/postgres-operator#2481]
## What we are planning to do:

**Issue 2** - In the <a href="https://access.crunchydata.com/documentation/postgres-operator/4.6.2/pgo-client/reference/pgo_create_cluster/" rel="nofollow">documentation</a>, we can give a custom Postgres image by specifying values for `CCPImage`, `CCPImagePrefix`, and `CCPImageTag`. This is constantly overridden by something and always deploys the latest version, regardless of what is set.

## What Happens:
	
It fails to use the custom ccpimage tags

	   
## Environment

- Platform: (`Openshift`)
- Platform Version: (`4.6.25`)
- PGO Image Tag: (`ubi8-13.2-4.6.2`) and (`ubi8-13.1-4.6.2`) and (`ubi7-12.6-4.6.1`)
- Postgres Version (`13.2`)
- Operator Version (`4.6.2`)	   

# Custom Image Attempt - leveraging the certified operators provided in OpenShift
## Database Deployment YAML (Here the image gets updated to the latest version instead of the one we specified, this is not the behavior in community edition)
<pre><code>
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  selfLink: /apis/apps/v1/namespaces/pgo/deployments/hippo
  resourceVersion: '158065621'
  name: hippo
  uid: 47b2fbd5-842e-4248-8e51-d61efc6d91a1
  creationTimestamp: '2021-05-21T16:40:16Z'
  generation: 2
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-05-21T16:40:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
    - manager: postgres-operator
      operation: Update
      apiVersion: apps/v1
      time: '2021-05-21T16:40:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:pgo-pg-database': {}
            'f:crunchy-pgha-scope': {}
            .: {}
            'f:pgo-version': {}
            'f:pgouser': {}
            'f:service-name': {}
            'f:pg-cluster': {}
            'f:vendor': {}
            'f:name': {}
            'f:deployment-name': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:deployment-name': {}
              'f:pg-cluster': {}
              'f:pgo-pg-database': {}
              'f:vendor': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                'f:pgo-pg-database': {}
                'f:pg-pod-anti-affinity': {}
                'f:crunchy-pgha-scope': {}
                .: {}
                'f:pgo-version': {}
                'f:pgouser': {}
                'f:pg-cluster': {}
                'f:vendor': {}
                'f:name': {}
                'f:deployment-name': {}
            'f:spec':
              'f:volumes':
                'k:{"name":"sshd"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:secretName': {}
                'k:{"name":"pgdata"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"podinfo"}':
                  .: {}
                  'f:downwardAPI':
                    .: {}
                    'f:defaultMode': {}
                    'f:items': {}
                  'f:name': {}
                'k:{"name":"primary-volume"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:secretName': {}
                .: {}
                'k:{"name":"user-volume"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:secretName': {}
                'k:{"name":"pgbackrest-config"}':
                  .: {}
                  'f:name': {}
                  'f:projected':
                    .: {}
                    'f:defaultMode': {}
                    'f:sources': {}
                'k:{"name":"root-volume"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:secretName': {}
                'k:{"name":"dshm"}':
                  .: {}
                  'f:emptyDir':
                    .: {}
                    'f:medium': {}
                  'f:name': {}
                'k:{"name":"report"}':
                  .: {}
                  'f:emptyDir':
                    .: {}
                    'f:medium': {}
                    'f:sizeLimit': {}
                  'f:name': {}
                'k:{"name":"pgconf-volume"}':
                  .: {}
                  'f:name': {}
                  'f:projected':
                    .: {}
                    'f:defaultMode': {}
                    'f:sources': {}
              'f:containers':
                'k:{"name":"database"}':
                  'f:image': {}
                  'f:volumeMounts':
                    'k:{"mountPath":"/pgconf"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/pgconf/pguser"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/sshd"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:readOnly': {}
                    'k:{"mountPath":"/etc/podinfo"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/pgdata"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/etc/pgbackrest/conf.d"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/dev/shm"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    .: {}
                    'k:{"mountPath":"/pgconf/pgreplicator"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/pgconf/pgsuper"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:livenessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    'k:{"name":"PATRONI_SCOPE"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef':
                          .: {}
                          'f:apiVersion': {}
                          'f:fieldPath': {}
                    'k:{"name":"PGHA_STANDBY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGBACKREST_PG1_SOCKET_PATH"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHOST"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGBACKREST_REPO1_PATH"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGBACKREST_PG1_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PATRONI_KUBERNETES_LABELS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"MODE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGBACKREST_REPO1_HOST"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHA_REPLICA_REINIT_ON_START_FAIL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHA_SYNC_REPLICATION"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PATRONI_KUBERNETES_NAMESPACE"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef':
                          .: {}
                          'f:apiVersion': {}
                          'f:fieldPath': {}
                    'k:{"name":"ENABLE_SSHD"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHA_USER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"BACKREST_SKIP_CREATE_STANZA"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHA_INIT"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"PGHA_TLS_ONLY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PATRONI_POSTGRESQL_DATA_DIR"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHA_PGBACKREST_LOCAL_S3_STORAGE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHA_TLS_ENABLED"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHA_PGBACKREST"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGBACKREST_STANZA"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PATRONI_LOG_LEVEL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PATRONI_KUBERNETES_SCOPE_LABEL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGBACKREST_REPO1_TYPE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHA_DATABASE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGBACKREST_DB_PATH"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGHA_PG_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PGBACKREST_LOG_PATH"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:securityContext':
                    .: {}
                    'f:allowPrivilegeEscalation': {}
                    'f:privileged': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":5432,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":8009,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:serviceAccount': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:terminationGracePeriodSeconds': {}
              'f:serviceAccountName': {}
              'f:securityContext':
                .: {}
                'f:runAsNonRoot': {}
              'f:affinity':
                .: {}
                'f:podAntiAffinity':
                  .: {}
                  'f:preferredDuringSchedulingIgnoredDuringExecution': {}
  namespace: pgo
  labels:
    pgouser: ''
    pgo-version: 4.6.2
    service-name: hippo
    pg-cluster: hippo
    vendor: crunchydata
    name: hippo
    deployment-name: hippo
    crunchy-pgha-scope: hippo
    pgo-pg-database: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: hippo
      pg-cluster: hippo
      pgo-pg-database: 'true'
      vendor: crunchydata
  template:
    metadata:
      creationTimestamp: null
      labels:
        pgouser: ''
        pgo-version: 4.6.2
        pg-cluster: hippo
        vendor: crunchydata
        name: hippo
        deployment-name: hippo
        pg-pod-anti-affinity: preferred
        crunchy-pgha-scope: hippo
        pgo-pg-database: 'true'
    spec:
      restartPolicy: Always
      serviceAccountName: pgo-pg
      schedulerName: stork
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: vendor
                      operator: In
                      values:
                        - crunchydata
                    - key: pg-pod-anti-affinity
                      operator: Exists
                    - key: pg-cluster
                      operator: In
                      values:
                        - hippo
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
      containers:
        - resources: {}
          readinessProbe:
            exec:
              command:
                - /opt/crunchy/bin/postgres-ha/health/pgha-readiness.sh
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: database
          livenessProbe:
            exec:
              command:
                - /opt/crunchy/bin/postgres-ha/health/pgha-liveness.sh
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MODE
              value: postgres
            - name: PGHA_PG_PORT
              value: '5432'
            - name: PGHA_USER
              value: postgres
            - name: PGHA_INIT
              valueFrom:
                configMapKeyRef:
                  name: hippo-pgha-config
                  key: init
            - name: PATRONI_POSTGRESQL_DATA_DIR
              value: /pgdata/hippo
            - name: PGBACKREST_STANZA
              value: db
            - name: PGBACKREST_REPO1_HOST
              value: hippo-backrest-shared-repo
            - name: BACKREST_SKIP_CREATE_STANZA
              value: 'true'
            - name: PGHA_PGBACKREST
              value: 'true'
            - name: PGBACKREST_REPO1_PATH
              value: /backrestrepo/hippo-backrest-shared-repo
            - name: PGBACKREST_DB_PATH
              value: /pgdata/hippo
            - name: ENABLE_SSHD
              value: 'true'
            - name: PGBACKREST_LOG_PATH
              value: /tmp
            - name: PGBACKREST_PG1_SOCKET_PATH
              value: /tmp
            - name: PGBACKREST_PG1_PORT
              value: '5432'
            - name: PGBACKREST_REPO1_TYPE
              value: posix
            - name: PGHA_PGBACKREST_LOCAL_S3_STORAGE
              value: 'false'
            - name: PGHA_DATABASE
              value: hippo
            - name: PGHA_REPLICA_REINIT_ON_START_FAIL
              value: 'true'
            - name: PGHA_SYNC_REPLICATION
              value: 'false'
            - name: PGHA_TLS_ENABLED
              value: 'false'
            - name: PGHA_TLS_ONLY
              value: 'false'
            - name: PGHA_STANDBY
              value: 'false'
            - name: PATRONI_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PATRONI_KUBERNETES_SCOPE_LABEL
              value: crunchy-pgha-scope
            - name: PATRONI_SCOPE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''crunchy-pgha-scope'']'
            - name: PATRONI_KUBERNETES_LABELS
              value: '{vendor: "crunchydata"}'
            - name: PATRONI_LOG_LEVEL
              value: INFO
            - name: PGHOST
              value: /tmp
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5432
              protocol: TCP
            - containerPort: 8009
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pgdata
              mountPath: /pgdata
            - name: user-volume
              mountPath: /pgconf/pguser
            - name: primary-volume
              mountPath: /pgconf/pgreplicator
            - name: root-volume
              mountPath: /pgconf/pgsuper
            - name: sshd
              readOnly: true
              mountPath: /sshd
            - name: pgconf-volume
              mountPath: /pgconf
            - name: dshm
              mountPath: /dev/shm
            - name: pgbackrest-config
              mountPath: /etc/pgbackrest/conf.d
            - name: podinfo
              mountPath: /etc/podinfo
          terminationMessagePolicy: File
          image: >-
            registry.connect.redhat.com/crunchydata/crunchy-postgres-ha@sha256:c724ac97d0cbef25a64a6afc7ec15382f9b5830f396cb521df4070474024b555
      serviceAccount: pgo-pg
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: hippo
        - name: user-volume
          secret:
            secretName: hippo-hippo-secret
            defaultMode: 420
        - name: primary-volume
          secret:
            secretName: hippo-primaryuser-secret
            defaultMode: 420
        - name: sshd
          secret:
            secretName: hippo-backrest-repo-config
            defaultMode: 420
        - name: root-volume
          secret:
            secretName: hippo-postgres-secret
            defaultMode: 420
        - name: report
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
        - name: dshm
          emptyDir:
            medium: Memory
        - name: pgbackrest-config
          projected:
            sources:
              - configMap:
                  name: hippo-config-backrest
                  optional: true
              - secret:
                  name: hippo-config-backrest
                  optional: true
            defaultMode: 420
        - name: pgconf-volume
          projected:
            sources:
              - configMap:
                  name: pgo-custom-pg-config
              - configMap:
                  name: hippo-pgha-config
                  optional: true
            defaultMode: 420
        - name: podinfo
          downwardAPI:
            items:
              - path: cpu_limit
                resourceFieldRef:
                  containerName: database
                  resource: limits.cpu
                  divisor: 1m
              - path: cpu_request
                resourceFieldRef:
                  containerName: database
                  resource: requests.cpu
                  divisor: 1m
              - path: mem_limit
                resourceFieldRef:
                  containerName: database
                  resource: limits.memory
                  divisor: '0'
              - path: mem_request
                resourceFieldRef:
                  containerName: database
                  resource: requests.memory
                  divisor: '0'
              - path: labels
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels
              - path: annotations
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-05-21T16:40:16Z'
      lastTransitionTime: '2021-05-21T16:40:16Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-05-21T16:40:16Z'
      lastTransitionTime: '2021-05-21T16:40:16Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "hippo-57b8ff48c8" has successfully progressed.

</pre></code>

### CRD - reflecting the custom images defined
<pre><code>
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  name: hippo
  labels:
    crunchy-pgha-scope: hippo
    deployment-name: hippo
    name: hippo
    namespace: pgo
    pg-cluster: hippo
    pgo-version: 4.6.2
  annotations:
    current-primary: hippo
  namespace: pgo
spec:
  port: '5432'
  exporterport: '9187'
  clustername: hippo
  pgbadgerport: '10000'
  userlabels:
    pgo-version: 4.6.2
  name: hippo
  ccpimage: crunchy-postgres-ha
  ccpimagetag: ubi8-13.1-4.6.2
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ''
    name: hippo
    size: 5Gi
    storageclass: somestorageclass
    storagetype: dynamic
    supplementalgroups: ''
  database: hippo
  namespace: pgo
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ''
    name: ''
    size: 5Gi
    storageclass: somestorageclass
    storagetype: dynamic
    supplementalgroups: ''
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ''
    name: ''
    size: 5Gi
    storageclass: somestorageclass
    storagetype: dynamic
    supplementalgroups: ''
  podAntiAffinity:
    default: preferred
  user: hippo

</pre></code>

### Operator Logs - reflecting the image is overwritten
<pre><code>
time="2021-05-19T19:00:48Z" level=info msg="default pgbackrest repository memory set to [48Mi]" func="internal/config.(*PgoConfig).Validate()" file="internal/config/pgoconfig.go:386" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="default pgbouncer memory set to [24Mi]" func="internal/config.(*PgoConfig).Validate()" file="internal/config/pgoconfig.go:392" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="CheckEnv: using PGO_IMAGE_TAG env var: ubi8-4.6.2" func="internal/config.(*PgoConfig).CheckEnv()" file="internal/config/pgoconfig.go:841" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="CheckEnv: using PGO_IMAGE_PREFIX env var: registry.connect.redhat.com/crunchydata" func="internal/config.(*PgoConfig).CheckEnv()" file="internal/config/pgoconfig.go:846" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="CheckEnv: using CCP_IMAGE_TAG env var: ubi8-13.2-4.6.2" func="internal/config.(*PgoConfig).CheckEnv()" file="internal/config/pgoconfig.go:851" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="CheckEnv: using CCP_IMAGE_PREFIX env var: registry.connect.redhat.com/crunchydata" func="internal/config.(*PgoConfig).CheckEnv()" file="internal/config/pgoconfig.go:856" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image crunchy-pgbackrest-repo overridden by: registry.connect.redhat.com/crunchydata/crunchy-pgbackrest-repo@sha256:f06dc265ba427ae55e6452feae2c8be27331d0f280c19d2a1f0ba754ce2e86ce" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image pgo-client overridden by: registry.connect.redhat.com/crunchydata/pgo-client@sha256:1f205ea03c9b0eca6fbe966dc2000d8e0e8255450327d6d4beccdbb0f6f6bba2" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image pgo-rmdata overridden by: registry.connect.redhat.com/crunchydata/pgo-rmdata@sha256:8ef27d45639d97b7c20c75da301c352ffda6a2154dc750a13c93aa78f5a645cc" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image crunchy-postgres-exporter overridden by: registry.connect.redhat.com/crunchydata/crunchy-postgres-exporter@sha256:974e2475e01cada12cddf155633ca87a5ca5f7f3068aaeb2903c7a6d970b5446" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image crunchy-pgadmin4 overridden by: registry.connect.redhat.com/crunchydata/crunchy-pgadmin4@sha256:55c1db7e595ab3d724b6c2a5937a29eb6645f4360e67462ee7a3275f09674ebb" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image crunchy-pgbouncer overridden by: registry.connect.redhat.com/crunchydata/crunchy-pgbouncer@sha256:1e82897e38e6083e3b5e376b3e624777b7e032fe7d816368e2e3d9a8d83b6abc" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image crunchy-postgres-ha overridden by: registry.connect.redhat.com/crunchydata/crunchy-postgres-ha@sha256:c724ac97d0cbef25a64a6afc7ec15382f9b5830f396cb521df4070474024b555" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image crunchy-postgres-gis-ha overridden by: registry.connect.redhat.com/crunchydata/crunchy-postgres-gis-ha@sha256:06525c3e82f66af4cc5d0ab692e43330ef81f325687b90166a2a4fc47a3a18c7" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image crunchy-pgbackrest overridden by: registry.connect.redhat.com/crunchydata/crunchy-pgbackrest@sha256:bf6071db6729c1ba0df920c64c6f28f91aeab650c3e52ca91b98b26a5627c3d3" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="image crunchy-pgbadger overridden by: registry.connect.redhat.com/crunchydata/crunchy-pgbadger@sha256:36fd6f70949b551bd0cc548c42a7a5cca88e97ffd2bc18c1bc87a64e7bd11dac" func="internal/operator.initializeContainerImageOverrides()" file="internal/operator/common.go:367" version=4.6.2
time="2021-05-19T19:00:48Z" level=info msg="EventTCPAddress set to localhost:4150" func="internal/operator.Initialize()" file="internal/operator/common.go:154" version=4.6.2

</pre></code>

**Comment by jkatz** [comment]
In #2463 you referenced that this was installed via OperatorHub. OperatorHub has opinions around how custom images are loaded via the `RELATED_IMAGES_` environmental variables. The full list that PGO provides is found here:

https://github.com/CrunchyData/postgres-operator/blob/master/installers/olm/postgresoperator.csv.images.yaml

I believe that if you do not set those values, or unset them, you can then transfer control of image loading to the custom resources.

Beyond the above, you will need to consult the OperatorHub documentation for how to set images, as that is dependent upon that system.
