### ISSUE TITLE
Online PVC resize

### ISSUE THREAD

**Issue by Remp69** [CrunchyData/postgres-operator#2482]
When using a storageclass based on CSI, we can resize a pvc without restarting containers. Example :
kubectl patch pvc cluster1_wal -p '{"spec":{"resources":{"requests":{"storage": "100Gi"}}}}'

PGO 4.7.0 introduces the ability to resize pvc, but it needs to restart the pod.
Is it possible to add a feature to resize pvc without downtime when the storageclass permit it ?

## Environment
- Platform: Kubernetes 1.19
- PGO Image Tag: centos8-4.7.0
- Storage: SAN thru CSI

**Comment by jkatz** [comment]
As mentioned in the [release notes](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.7.0/#resize-persistent-volume-claims-resize-pvcs), PGO maintains backward compatibility to OpenShift 3.11, which is based on Kubernetes 1.11. This method was chosen to provide a minimally disruptive way to apply PVC resize changes -- even though the Pod restarts, it is handled via a [rolling update](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/#rolling-updates).

At some point we will have a release that no longer supports OpenShift 3.11 in which we can consider additional storage resizing methods.

**Comment by Remp69** [comment]
OK then we are waiting :)

Thanks a lot for you answer.

**Comment by jkatz** [comment]
@Remp69 Is PVC resizing an operation you perform frequently?

**Comment by Remp69** [comment]
Not so often, but can be during opening hours in production, for example if we are close to wal saturation.

**Comment by quickstrike101** [comment]
Hi @jkatz,

i'm using crunchy postgres operator version 4.6.2 and postgres version 12.6 , i'm unable to resize pvc , couldn't  find any option , can you please help

**Comment by jkatz** [comment]
PVC resizing was added in 4.7 and is also supported in v5.

Anything beyond that would be considered a [support](https://access.crunchydata.com/documentation/postgres-operator/v5/support/) issue.
