### ISSUE TITLE
Enable use of non-HA Postgis image by operator.

### ISSUE THREAD

**Issue by swoodcoc** [CrunchyData/postgres-operator#2483]
- Related to issue #1749 which appears to be fixed in PR #1993.
- The fix has addressed using image crunchy-postgres-gis-ha, but not crunchy-postgres-gis.
- There are multiple related issues that have been closed for this, e.g. #2310

Request: add an additional if statement to function GetStandardImageTag in internal/util/util.go:

```
if imageName == "crunchy-postgres-gis" && strings.Count(imageTag, "-") > 2 {
        return gisImageTagRegex.ReplaceAllString(imageTag, "$1$2")
}
```

**I can create a PR for this if needed.**

Example of cluster deployment:
```
pgo create cluster test-cluster \
  --ccp-image=crunchy-postgres-gis \
  --ccp-image-tag=centos8-13.3-3.1-4.7.0 \
  --replica-count=2 \
  --service-type=LoadBalancer \
  --pgbouncer --pgbadger --metrics \
  --username admin \
  --sync-replication \
  --database=dbtest \
  --pvc-size=5Gi \
  --pgbackrest-pvc-size=15Gi
```

**Comment by jkatz** [comment]
`crunchy-postgres-gis-ha` is tailored to work with PGO.
