### ISSUE TITLE
Postgres images missing from Developer portal

### ISSUE THREAD

**Issue by mdraijer** [CrunchyData/postgres-operator#2484]
## Overview

In the Developer portal not all supported Postgres versions are available

## Environment

Please provide the following details:

- Platform: `Kubernetes (OpenShift)`
- Platform Version: `1.20 (4.7)`
- PGO Image Tag: `centos8-4.6.1`

### REPRO

Check Developer portal (https://www.crunchydata.com/developers/download-postgres/containers)

### EXPECTED

Images for the Postgres versions mentioned here: https://access.crunchydata.com/documentation/postgres-operator/4.7.0/configuration/compatibility/

E.g. for 4.6.1: 13.2, 12.6, 11.11, 10.16, 9.6.21

E.g. for 4.7.0: 13.3, 12.7, 11.12, 10.17, 9.6.22

### ACTUAL

Find only Postgres 12 and 13.

When I check Docker Hub there are older versions, but these are also older _minor_ versions, linked to older _operator_ versions. Check for example https://hub.docker.com/r/crunchydata/crunchy-postgres-ha/tags?page=1&ordering=last_updated&name=11

## Additional Information

We are running a tool that uses a Postgres database, but only supports Postgres up to version 11. Which _is_ still supported by the CrunchyData Postgres Operator, but which images cannot be found anywhere.

**Comment by jkatz** [comment]
The Developer Portal provides images for newer versions of Postgres for the purposes of evaluation and development. The entire catalog of images are available in the Customer Portal.
