### ISSUE TITLE
pgo 4.5.0 missing images and no pg11 images available for any version of pgo

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#2485]
According to the release notes for 4.7.0 pgo 4.4 images were supposed to be removed but all the 4.5.0 images seem to have been removed too.  In addition there seem to be no pg11 images available despite release notes specifically referencing pg11.

The image we were using no longer seems available i.e. we can no longer pull this image:
```
Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos7-11.9-2.5-4.5.0": rpc error: code = NotFound desc = failed to pull and unpack image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos7-11.9-2.5-4.5.0": failed to resolve reference "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos7-11.9-2.5-4.5.0": registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos7-11.9-2.5-4.5.0: not found
```

```
  --ccp-image=crunchy-postgres-gis-ha \
  --ccp-image-tag=centos7-11.9-2.5-4.5.0 \
```
Is there any way to still get access to this image?  We were also exploring upgrading to pgo 4.6.3 but can't find any postgis 11.x images.  Are there any available that we missed?  The release notes for 4.6.3 reference support for 11.12 but can't find any of these images?  Any help identifying any 11.x images that we can use would be greatly appreciated.

**Comment by jkatz** [comment]
A notice went out to the [developer mailing list](https://www.crunchydata.com/developers/newsletter) several months ago and was displayed on the website for awhile about the deprecation and removal of the CentOS 7 images and the PG11 images. The CentOS 8 images for PGO 4.5 are available in the developer portal.

**Comment by alrooney** [comment]
@jkatz just subscribed to the mailing list.  Thanks.  Is there any way we can get those old images to host ourselves while we figure out a way to upgrade?

**Comment by empeekdev** [comment]
> @jkatz just subscribed to the mailing list. Thanks. Is there any way we can get those old images to host ourselves while we figure out a way to upgrade?

You can pull them from dockerhub

**Comment by empeekdev** [comment]
@jkatz looks like that old images was removed from dockerhub too. Is there any method to get old images? Our application and dependencies depends on centos7 so maybe we can pull them from somewhere and host ourselves ?

**Comment by hoeggi** [comment]
Since i ran into the same issue, if you still have this version running somewhere you can `docker/podman save` the image as a tarball, transfer it to the machines where you need it and then `docker/podman load` it. This way you don't need to change the image/registry name.
Alternatively you can tag the image with your own registry and push it there but this requires you to also change the image name of your current deployment. 

I tested option one and it works but is really just a short term workaround.

Does anyone know how to change the image of a running cluster (if even possible)?
