### ISSUE TITLE
Primary DB crashing

### ISSUE THREAD

**Issue by sriniarul** [CrunchyData/postgres-operator#2488]
Configured a postgres cluster having 1 master and 1 standby with pgbouncer and metrics sidecar kubernetes pod using the pro cmd. Haven't limited any resource to the pods

After few days I got broken pipe exception in the primary pod log, but that was just a few and the pod was serving the DB request successfully, but next day the primary pod got crashed internally restarting the service and trying to register itself in DCS, as replica becomes the primary I replaced the crashed pod with new one. Similar issue happened again.  

**Pod log**

[primary_pod_log.txt](https://github.com/CrunchyData/postgres-operator/files/6608988/primary_pod_log.txt)

#########################################################################
**pg_hba.conf**

{
	"init": "false",
	"lisadb-dcs-config": "postgresql:
		  parameters:
		    archive_command: source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push \"%p\"
		    archive_mode: true
		    archive_timeout: 60
		    jit: false
		    log_directory: pg_log
		    log_min_duration_statement: 60000
		    log_statement: none
		    max_wal_senders: 6
		    shared_buffers: 128MB
		    shared_preload_libraries: pgaudit.so,pg_stat_statements.so,pgnodemx.so
		    temp_buffers: 8MB
		    unix_socket_directories: /tmp
		    wal_level: logical
		    work_mem: 4MB
		  recovery_conf:
		    restore_command: source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-get %f \"%p\"
		  use_pg_rewind: true
		",
	"lisadb-erfz-local-config": "postgresql:
		  callbacks:
		    on_role_change: /opt/crunchy/bin/postgres-ha/callbacks/pgha-on-role-change.sh
		  create_replica_methods:
		  - pgbackrest
		  - basebackup
		  pg_hba:
		  - local all postgres peer
		  - host replication primaryuser 0.0.0.0/0 md5
		  - host all primaryuser 0.0.0.0/0 reject
		  - host all all 0.0.0.0/0 md5
		  pgbackrest:
		    command: /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh replica
		    keep_data: true
		    no_params: true
		  pgbackrest_standby:
		    command: /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh standby
		    keep_data: true
		    no_master: 1
		    no_params: true
		  pgpass: /tmp/.pgpass
		  remove_data_directory_on_rewind_failure: true
		  use_unix_socket: true
		",
	"lisadb-nxuw-local-config": "postgresql:
		  callbacks:
		    on_role_change: /opt/crunchy/bin/postgres-ha/callbacks/pgha-on-role-change.sh
		  create_replica_methods:
		  - pgbackrest
		  - basebackup
		  pg_hba:
		  - local all postgres peer
		  - host replication primaryuser 0.0.0.0/0 md5
		  - host all primaryuser 0.0.0.0/0 reject
		  - host all all 0.0.0.0/0 md5
		  pgbackrest:
		    command: /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh replica
		    keep_data: true
		    no_params: true
		  pgbackrest_standby:
		    command: /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh standby
		    keep_data: true
		    no_master: 1
		    no_params: true
		  pgpass: /tmp/.pgpass
		  remove_data_directory_on_rewind_failure: true
		  use_unix_socket: true
		"
}

##########################################################################

**kubernetes - v2.2.0
pgo client version 4.6.2
pgo-apiserver version 4.6.2
pod image - crunchy-postgres-ha:centos8-13.2-4.6.2
PVC - NFS storage**

**Comment by jkatz** [comment]
Can you share any logs from `/pgdata/<clustername>/pg_log` with any sensitive information redacted?

**Comment by sriniarul** [comment]
unfortunately I lost that log with that specific container. same issue is happening on the running container but not yet crashed
here is the log file of two days. I stripped some unwanted lines
[Uploading pg_log.txt…]()

**Comment by jkatz** [comment]
> 2021-06-06 01:25:12.466 UTC [110700] ERROR:  requested WAL segment 000000030000017500000077 has already been removed

This seems to indicate that someone deleted a WAL file that Postgres was requesting to reach consistency. That would certainly cause downtime.

This can be corrected with a [restore](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/#restores).

Based upon the times of the logs, it seems that you did something of that nature for recovery. All the other messages indicate normal operation, with perhaps a need to do some [Postgres tuning](https://blog.crunchydata.com/blog/tuning-your-postgres-database-for-high-write-loads).

Beyond that, this seems to skew [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/); I don't see anything that appears to be a bug.
