### ISSUE TITLE
service annotation

### ISSUE THREAD

**Issue by vgulch** [CrunchyData/postgres-operator#2489]
When you use external-dns to create domain names for services with type LoadBalancer  annotation is needed to be set
From what i see its not possible to annotate a service
It'd be nice to follow the same way as its done for deployments annotations

We use k8s 1.18, pgo 4.7.0, postgres 13

**Comment by jkatz** [comment]
Seems reasonable. This was recently done for labels in 4.7; I don't see why we couldn't or shouldn't do it for annotations.

If you need this today, you could modify the `service.json` entry in the `pgo-config` ConfigMap to have the annotations that you want.

**Comment by frbjo3** [comment]
This is a feature we would also like to see.
Almost all implementations of service type: LoadBalancer is depending on annotations for configuring the cloud provider loadbalancer that is created.

Also, I don´t really see how this can be done with a configmap, and are not able to find any useful information in the 5.x documentation about it.

**Comment by alishchytovych** [comment]
Need it badly as well

**Comment by danielbichuetti** [comment]
Being able to provide custom annotations for services would be really amazing. Like pgBouncer, pgAdmin and so on. ExternalDNS need to have an annotation setup on the service that we want to expose, as an example.

Today we can annotate only on the resource itself, not on the exposed service.

**Comment by andrewlecuyer** [comment]
Support for custom service annotations has now been added to PGO v5 with https://github.com/CrunchyData/postgres-operator/pull/3302.
