### ISSUE TITLE
 pgo-custom-pg-config

### ISSUE THREAD

**Issue by jamessewell** [CrunchyData/postgres-operator#2491]
I'm running 4.6.2 and trying to bootstrap my clusters with custom-config.

I'm using `pgo-custom-pg-config` which works well - but I want to bootstrap with users created, with passwords from secrets - I obviously can't store these in a configmap.

I can use something like `configmapsecrets` to embed by secrets, but then `pgo-custom-pg-config` becomes a secret, not a configmap which is not supported.

In the setup sql there are subs like this:

```
    CREATE USER ${PGHA_USER} LOGIN;
    ALTER USER ${PGHA_USER} PASSWORD $$${PGHA_USER_PASSWORD}$$;
```

Can I get a description of what is happening here? I'm confused as `PGHA_USER` is set to `postgres` on my database deployment, but I was pretty sure this was meant to create my `user` from the cluster spec (which is created somehow)?

Is there a nice way to inject secrets into my bootstrap?

**Comment by jamessewell** [comment]
Just want to note that I *do not* want to manage roles via the CRD - this would be nice to have but totally understand that it has sync implications.

**Comment by jamessewell** [comment]
Thinking about this more I think that I just am looking for a way of getting custom secret values into the `pgo-custom-config` sql.

Is there some way of doing this (mounting and exposing custom secrets or setting env vars)?

**Comment by prlaurence** [comment]
@jamessewell doing some house cleaning and noticed this issue one is quite long in the tooth. my assumption is that this is no longer relevant to you. given that much as changed in v5 and the passage of time and events, I presume this is no longer relevant to you. if you are still interested in the topic, feel free to reopen or to create a new issue.
