### ISSUE TITLE
Multi primary instances

### ISSUE THREAD

**Issue by nadendlaprasad** [CrunchyData/postgres-operator#2494]
Is it possible run multiple primary instances to distribute the load ? If yes, can you please provide the details ? I couldn't find from the docs. If no, can we expect this feature from the next release ?

**Comment by jkatz** [comment]
I would recommend reading these blog posts for different ways of doing this:

- [Active-Active Postgres Federation on Kubernetes]()https://blog.crunchydata.com/blog/active-active-postgres-federation-on-kubernetes)
- [Building Cloud Native Data Analytic Services for the Edge](https://www.openshift.com/blog/building-cloud-native-data-analytic-services-for-the-edge)

However, there are many tradeoffs when you are building out a multi-primary setup. Typically you will want a standard [high availability](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/) setup, or a setup that spans [multiple regions / zones](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/multi-zone-design-considerations/). In some scenarios, you may want a [multi-cluster](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/) setup.

PostgreSQL also scales very well vertically and for the most part you do not need to distribute load. If you are looking for a simple read scaling, PGO deploys a service for just its replicas that allow you to safely distribute your read queries that way. However, I would recommend figuring out what your write load is and tuning your Postgres database to manage that; you may find that you may only need a single instance that can accept writes.
