### ISSUE TITLE
pgo user -  error  command terminated with exit code 2 for crunchy 4.7

### ISSUE THREAD

**Issue by ckvtvm-arch** [CrunchyData/postgres-operator#2495]
I was able to work on crunchy on the previous versions, but with 4.7 , I was not able to retrieve the initial login password for admin or even to create /update the user.

Is this is because of the new pgbackrest ssh authentication which is creating the issue for the new cluster pgadmin access

I am running these clusters in openshift

af71194@LC02CHB58MD6R ~ % pgo show user --show-system-accounts keycloak-postgresql -n vantage-sit                                                    

CLUSTER USERNAME PASSWORD EXPIRES STATUS ERROR                               
------- -------- -------- ------- ------ -----------------------------------
                                  error  command terminated with exit code 2 

af71194@LC02CHB58MD6R ~ % pgo update user --username postgres  --set-system-account-password -s name=keycloak-postgresql -n vantage-sit --password admin

CLUSTER             USERNAME PASSWORD EXPIRES STATUS ERROR                               
------------------- -------- -------- ------- ------ -----------------------------------
keycloak-postgresql postgres                  error  command terminated with exit code 2 
af71194@LC02CHB58MD6R ~ %

**Comment by ckvtvm-arch** [comment]
all the pgo commands to create / update user have the same issues

af71194@LC02CHB58MD6R ~ % pgo show user --selector=name=keycloak-postgresql -n vantage-sit --debug
DEBU[0000] debug flag is set to true                    
DEBU[0000] in initConfig with url=https://127.0.0.1:8443 
DEBU[0000] GetSessionCredentials called                 
DEBU[0000] PGOUSER environment variable is being used at /Users/af71194/.pgo/pgo/pgouser 
DEBU[0000] pgouser file found at /Users/af71194/.pgo/pgo/pgouser contains admin:admin 
DEBU[0000] [admin admin]                                
DEBU[0000] username=[admin] password=[admin]            
DEBU[0000] setting up httpclient with TLS               
DEBU[0000] GetTLSTransport called                       
DEBU[0000] ShowUser called...[https://127.0.0.1:8443/usershow] 
DEBU[0000] &{200 OK 200 HTTP/1.1 1 1 map[Content-Length:[164] Content-Type:[application/json] Date:[Sat, 12 Jun 2021 00:22:11 GMT] Www-Authenticate:[Basic realm="Restricted"]] 0xc0007b6600 164 [] false false map[] 0xc00035e600 0xc00028c160} 
DEBU[0000] http status code is 200                      

CLUSTER USERNAME PASSWORD EXPIRES STATUS ERROR                               
------- -------- -------- ------- ------ -----------------------------------
                                  error  command terminated with exit code 2 
af71194@LC02CHB58MD6R ~ % pgo create user --username=admin  --password=admin keycloak-postgresql --managed -n vantage-sit

CLUSTER             USERNAME PASSWORD EXPIRES  STATUS ERROR                               
------------------- -------- -------- -------- ------ -----------------------------------
keycloak-postgresql admin                      error  command terminated with exit code 2

**Comment by ckvtvm-arch** [comment]
psql: error: FATAL:  no pg_hba.conf entry for host "[local]", user "1004260000", database "version", SSL off

**Comment by ckvtvm-arch** [comment]
af71194@LC02CHB58MD6R ~ % pgo show cluster --all -n vantage-sit                                                                                     

cluster : keycloak-postgresql (crunchy-postgres-ha:centos8-13.3-4.7.0)
	pod : keycloak-postgresql-856865ccdd-h64hc (Running) on va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das (3/3) (primary)
		pvc: keycloak-postgresql (954Mi)
	resources : Memory: 128Mi
	deployment : keycloak-postgresql
	deployment : keycloak-postgresql-backrest-shared-repo
	deployment : keycloak-postgresql-pgadmin
	service : keycloak-postgresql - ClusterIP (172.30.150.255) - Ports (10000/TCP, 9187/TCP, 2022/TCP, 5432/TCP)
	service : keycloak-postgresql-pgadmin - ClusterIP (172.30.178.75) - Ports (5050/TCP)
	labels : name=keycloak-postgresql pg-cluster=keycloak-postgresql pgo-version=4.7.0 pgouser=admin workflowid=77409951-34ae-46fa-b520-04f41869441c crunchy-pgadmin=true 
af71194@LC02CHB58MD6R ~ % pgo update user --selector keycloak-postgresql --username=postgres --set-system-account-password --password=admin -n vantage-sit
Error: no clusters found
af71194@LC02CHB58MD6R ~ % pgo update user -s keycloak-postgresql --username=postgres --set-system-account-password --password=admin -n vantage-sit
Error: no clusters found
af71194@LC02CHB58MD6R ~ % pgo update user -s keycloak-postgresql --username=postgres --set-system-account-password --password=admin -n vantage-sit
Error: no clusters found
af71194@LC02CHB58MD6R ~ % pgo update user -s keycloak-postgresql --username=postgres --set-system-account-password --password=admin -n vantage-sit

**Comment by ckvtvm-arch** [comment]
af71194@LC02CHB58MD6R ~ % pgo update user -s name=keycloak-postgresql --username=postgres --set-system-account-password --password=admin -n vantage-sit

CLUSTER             USERNAME PASSWORD EXPIRES STATUS ERROR                               
------------------- -------- -------- ------- ------ -----------------------------------
keycloak-postgresql postgres                  error  command terminated with exit code 2 
af71194@LC02CHB58MD6R ~ %

**Comment by jkatz** [comment]
Can you provide logs from the `apiserver` container in the `postgres-operator` Pod after running these commands?

**Comment by ckvtvm-arch** [comment]
time="2021-06-11T23:59:30Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-11T23:59:30Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0

**Comment by ckvtvm-arch** [comment]
time="2021-06-11T23:59:30Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-11T23:59:30Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0
time="2021-06-12T00:03:27Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:03:27Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0
time="2021-06-12T00:05:09Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:05:09Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.updateUser()" file="internal/apiserver/userservice/userimpl.go:1166" version=4.7.0
time="2021-06-12T00:09:14Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:09:14Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.updateUser()" file="internal/apiserver/userservice/userimpl.go:1166" version=4.7.0
time="2021-06-12T00:14:57Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:14:57Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0
time="2021-06-12T00:16:50Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:16:50Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.updateUser()" file="internal/apiserver/userservice/userimpl.go:1166" version=4.7.0
time="2021-06-12T00:21:46Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:21:46Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0
time="2021-06-12T00:22:11Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:22:11Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0
time="2021-06-12T00:25:17Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:25:17Z" level=error msg="command terminated with exit code 2" func="internal/util.SetPostgreSQLPassword()" file="internal/util/cluster.go:510" version=4.7.0
time="2021-06-12T00:25:17Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.CreateUser()" file="internal/apiserver/userservice/userimpl.go:248" version=4.7.0
time="2021-06-12T00:31:32Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:31:32Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0
time="2021-06-12T00:31:38Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:31:38Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0
time="2021-06-12T00:32:49Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:32:49Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0
time="2021-06-12T00:35:23Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:35:23Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0
time="2021-06-12T00:46:45Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:46:45Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.updateUser()" file="internal/apiserver/userservice/userimpl.go:1166" version=4.7.0
time="2021-06-12T00:56:31Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:56:31Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.updateUser()" file="internal/apiserver/userservice/userimpl.go:1166" version=4.7.0
time="2021-06-12T00:57:25Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T00:57:25Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.updateUser()" file="internal/apiserver/userservice/userimpl.go:1166" version=4.7.0
time="2021-06-12T01:00:40Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T01:00:40Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.updateUser()" file="internal/apiserver/userservice/userimpl.go:1166" version=4.7.0
time="2021-06-12T01:03:41Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T01:03:41Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.updateUser()" file="internal/apiserver/userservice/userimpl.go:1166" version=4.7.0
time="2021-06-12T01:04:04Z" level=error msg="command terminated with exit code 2" func="internal/kubeapi.ExecToPodThroughAPI()" file="internal/kubeapi/exec.go:76" version=4.7.0
time="2021-06-12T01:04:04Z" level=error msg="command terminated with exit code 2" func="internal/apiserver/userservice.ShowUser()" file="internal/apiserver/userservice/userimpl.go:506" version=4.7.0

**Comment by jkatz** [comment]
Can you please provide the following information that is [helpful for troubleshooting](https://github.com/CrunchyData/postgres-operator/issues/new?assignees=&labels=&template=bug_report.md):

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.)
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `centos8-4.7.0`)
- Postgres Version (e.g. `13`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

Can you also provide the image tag of the container you are using, and if you did anything special while upgrading.

**Comment by ckvtvm-arch** [comment]
Platform: , OpenShift 
Platform Version: Client Version: openshift-clients-4.4.0-202006211643.p0-2-gd89e458c3
Server Version: 4.6.17
Kubernetes Version: v1.19.0+e405995

PGO Image Tag:  
pgo client version 4.7.0
pgo-apiserver version 4.7.0

Postgres Version (e.g. 13) - psql (PostgreSQL) 13.3
Storage: nfs (planned to use as soon as the cluster is set up).

**Comment by ckvtvm-arch** [comment]
I havent cutomized the image:
     
 image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-4.7.0

**Comment by jkatz** [comment]
The "error" that is being returned is due to the command being executed on the image failing. If you customized the image, this could very well be the case that your customization is creating some interference with the command that is being executed (which is just `psql`).

If the image is customized, this is likely not a bug with the Operator (also given we test the user operations against standard images).

As a side note, with NFS, there is a lot you need to consider when storing your data on it that could end up leading into issues later on. I suggest reading the [PostgreSQL documentation on NFS](https://www.postgresql.org/docs/current/creating-cluster.html#CREATING-CLUSTER-NFS) about this.

**Comment by ckvtvm-arch** [comment]
we haven't customized the image and also we are not using NFS for now. does it means the PGO command fails on the image 4.7 which was working well in previous versions?

**Comment by jkatz** [comment]
I apo

**Comment by ckvtvm-arch** [comment]
no probs

**Comment by jkatz** [comment]
I apologize, I misread the comment. That said, I don't believe this is a bug in PGO or with the images. We run multiple automated and manual e2e tests across platforms that include the `pgo show user` command.

I just performed a fresh install on my local environment of 4.7.0 (which also happens to use NFS) using the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/). I ran the following:


```
pgo create cluster hippo
```

Once the cluster was up and running, I then ran the following:

```
pgo show user hippo
```

which yielded:

```
CLUSTER USERNAME PASSWORD                 EXPIRES STATUS ERROR 
------- -------- ------------------------ ------- ------ -----
hippo   testuser <redacted>                       never   ok    
```

So I don't think this is a bug.

If you made modifications to how your default `postgres` database user behaves, that could affect how those commands execute as well. At this point, I think this skews [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) as from performing similar tests I am unable to reproduce the issue.

**Comment by ckvtvm-arch** [comment]
Any command related to the user is throwing the error while all other pgo commands works well

af71194@LC02CHB58MD6R ~ % pgo show user --all
Error: empty namespace is not valid from pgo clients
af71194@LC02CHB58MD6R ~ % pgo show user --all -n vantage-sit

CLUSTER USERNAME PASSWORD EXPIRES STATUS ERROR                               
------- -------- -------- ------- ------ -----------------------------------
                                  error  command terminated with exit code 2 
af71194@LC02CHB58MD6R ~ % pgo show cluster --all -n vantage-sit

cluster : keycloak-postgresql (crunchy-postgres-ha:centos8-13.3-4.7.0)
	pod : keycloak-postgresql-856865ccdd-h64hc (Running) on va33dlvocp052.ent-ocp4-np1-har.antmdc.internal.das (3/3) (primary)
		pvc: keycloak-postgresql (954Mi)
	resources : Memory: 128Mi
	deployment : keycloak-postgresql
	deployment : keycloak-postgresql-backrest-shared-repo
	deployment : keycloak-postgresql-pgadmin
	service : keycloak-postgresql - ClusterIP (172.30.150.255) - Ports (10000/TCP, 9187/TCP, 2022/TCP, 5432/TCP)
	service : keycloak-postgresql-pgadmin - ClusterIP (172.30.178.75) - Ports (5050/TCP)
	labels : workflowid=77409951-34ae-46fa-b520-04f41869441c crunchy-pgadmin=true name=keycloak-postgresql pg-cluster=keycloak-postgresql pgo-version=4.7.0 pgouser=admin 
af71194@LC02CHB58MD6R ~ %
