### ISSUE TITLE
Support declarative creation of backup schedules

### ISSUE THREAD

**Issue by bo0ts** [CrunchyData/postgres-operator#2500]
## Overview

Currently backup schedules are created as configmaps containing json. AFAIK this is not documented and the only official way to create a schedule is using `pgo create schedule`.

## Use Case

When creating a Pgcluster and associated resources declaratively (using the Pgcluster CR) it would be nice to have a custom resources that represents a backup schedule.

**Comment by jkatz** [comment]
This is planned for an upcoming release.

**Comment by jkatz** [comment]
This is addressed in PGO 5: 

[https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backup-management/#managing-scheduled-backups](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backup-management/#managing-scheduled-backups)
