### ISSUE TITLE
Cannot connect to new PGO instance

### ISSUE THREAD

**Issue by eric-aops** [CrunchyData/postgres-operator#2502]
Hi, 

I had to recreate my PGO installation and now cannot connect to it. I used the Ansible way to deploy it all, tried update and uninstall and install a couple of times but keep on getting the same error:

```
pgo client version 4.7.0
Handling connection for 8443
Error: Invalid Status Code: 403
```

Can anyone please point me in the right direction to fix this issue? 

Kind regards 

Eric V.

**Comment by jkatz** [comment]
A search through the issues shows a few of the cases where this may occur, as well as several suggested resolutions:

- [https://github.com/CrunchyData/postgres-operator/issues/2121#issuecomment-744633545](https://github.com/CrunchyData/postgres-operator/issues/2121#issuecomment-744633545)
- [https://github.com/CrunchyData/postgres-operator/issues/2223#issuecomment-764177337](https://github.com/CrunchyData/postgres-operator/issues/2223#issuecomment-764177337)
