### ISSUE TITLE
PITR doesn't work on 4.7.0

### ISSUE THREAD

**Issue by cap1984** [CrunchyData/postgres-operator#2506]
Hi there

It seems like 4.7.0 operator version has lost its ability to restore to a particular time or transaction id (xid). When I'm specifying such parameters, bootstrap pod falls into infinite loop. On the other hand, regular restore works as before.

## Environment
- Platform: GKE
- Platform version: 1.20

- PGO Image tag: centos8-4.7.0
- Postgres Version: 13
- Storage: gcs, ssd-g2(local pvc)

## STR
1. Start the cluster according to documentation
`$ kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.7.0/installers/kubectl/postgres-operator.yml`
`$ ./installers/kubectl/client-setup.sh`
`pgo create cluster some-name --pgbackrest-gcs-bucket operator-testing --pgbackrest-gcs-key ./credentials.json --pgbackrest-storage-type gcs`
2. Insert some data into the database with `CREATE DATABASE ...; INSERT INTO ...`
3. Make a backup
`pgo backup some-name --pgbackrest-storage-type gcs`
4. Wait till backup completion and schedule the restore with
`pgo restore some-name --pitr-target='2021-06-21 17:16:20.999999+00' --backup-opts='--type=time'` (time should be adjusted according to `pgo show backup some-name`)
or
`pgo restore some-name --backup-opts="--type=xid --target=502" --pgbackrest-storage-type gcs`
5. Ensure that bootstrap pod has been initiated

**Expected result**: Bootstrap pods completes execution

**Actual result**: Bootstrap pod execution never ends

## Logs and manifests

[bootstrap.log](https://github.com/CrunchyData/postgres-operator/files/6689071/bootstrap.log)
[postgresql-Mon.log](https://github.com/CrunchyData/postgres-operator/files/6689103/postgresql-Mon.log)
[job.bootstrap.some-name.yaml.txt](https://github.com/CrunchyData/postgres-operator/files/6689116/job.bootstrap.some-name.yaml.txt)

**Comment by jkatz** [comment]
I was unable to reproduce this on 4.7.0, but I actually don't think there is an error.

I would suggest exec'ing into the bootstrap Pod and looking at the PostgreSQL log in there. What may be going on is that you are replaying a bunch of WAL logs and based upon the size and your available resources, the recovery is taking awhile.
