### ISSUE TITLE
pgo create schedule disallows multiple storage types

### ISSUE THREAD

**Issue by SockenSalat** [CrunchyData/postgres-operator#2507]
After upgrading to 4.7.0 I tried to create a backup schedule utilising S3 and local storage.

The [Documentation][1] states:

`--pgbackrest-storage-type string   The type of storage to use when scheduling pgBackRest backups. Either "posix", "s3" or both, comma separated. (default "posix")`

but when used with `--pgbackrest-storage-type=posix,s3` I receive the error message:

`Error: you can only select one storage type`

Since only one schedule `pgbackrest-full` is allowed, how can I achieve a backup being made to both locations?

[1]: https://access.crunchydata.com/documentation/postgres-operator/4.7.0/pgo-client/reference/pgo_create_schedule/

**Comment by jkatz** [comment]
That is an error in the docs, but this is addressed in an upcoming release.

**Comment by jkatz** [comment]
This is addressed in PGO 5.
