### ISSUE TITLE
Using AWS IAM roles with pgBackRest

### ISSUE THREAD

**Issue by MiLk** [CrunchyData/postgres-operator#2509]
## Overview

I would like to be able to allow pgBackRest to connect S3 using IAM roles instead of having credentials for an IAM user.
pgBackRest already support this via the [`repo1-s3-role`](pgbackrest) option.
It seems the [pgBackRest container](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/pgbackrest-repo/pgbackrest-repo.sh#L66-L80) doesn't support it.
And as a result neither do the operator.

## Use Case

We want to have the least amount of IAM users and API credentials to reduce the attack surface.
IAM roles is a safer way to handle access to AWS services as they don't come with long term credentials but are assumed by other services. They can be used assigned to specific pods using [IAM roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) or [kiam](https://github.com/uswitch/kiam).

Having support for using directly AWS roles with pgBackRest instead of IAM users would help keeping things secure, and remove the need for extra credentials.

## Desired Behavior

By specifying `backrestS3Role` in the Pgcluster CRD, I would expect pgBackRest to work without having to specify credentials via the `backrest-repo-config` file.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: EKS
- Platform Version: v1.20.4-eks-6b7464
- PGO Image Tag: centos8-13.3-4.7.0
- Postgres Version: 13.3
- Storage: EBS (gp3)
- Number of Postgres clusters: 2

**Comment by james-callahan** [comment]
> They can be used assigned to specific pods using [IAM roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

This depends on https://github.com/pgbackrest/pgbackrest/issues/1203

**Comment by jkatz** [comment]
Waiting on pgbackrest/pgbackrest#1527 to merge.
