### ISSUE TITLE
Network services don't retry

### ISSUE THREAD

**Issue by haf** [CrunchyData/postgres-operator#2515]
## Overview

When setting up a new DB, the create-stanza backups the primary before adding replicas. This fails, because pgbackrest doesn't retry TCP sockets that time out.

This bug can be resolved by pgbackrest retrying connection errors.

## Environment

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.): k8s
- Platform Version: (e.g. `1.20.3`, `4.7.0`): 4.7
- PGO Image Tag: (e.g. `centos8-4.7.0`): centos-4.7.0
- Postgres Version (e.g. `13`): 12
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class): PVC on GKE

## Steps to Reproduce

Enable istio with `istioctl operator init` then deploy a ControlPlane crd instance, or even easier `istioctl install`, or just drop the initial SYN packet from pgbackrest to timeout the initial socket.

### EXPECTED

1. All networking software should retry on connection failures
2. Alternatively, jobs that are "more or less" idempotent like this one, should retry

## Logs

Found logs inside the container:

```
nss_wrapper: user exists
nss_wrapper: group exists
nss_wrapper: environment configured
Mon Jun 21 17:27:21 UTC 2021 INFO: Image mode found: pgbackrest
Mon Jun 21 17:27:21 UTC 2021 INFO: Starting in 'pgbackrest' mode
time="2021-06-21T17:27:21Z" level=info msg="crunchy-pgbackrest starts"
time="2021-06-21T17:27:21Z" level=info msg="debug flag set to false"
time="2021-06-21T17:27:21Z" level=info msg="backrest stanza-create command requested"
time="2021-06-21T17:27:21Z" level=info msg="gcs flag enabled for backrest command"
time="2021-06-21T17:27:21Z" level=info msg="command to execute is [pgbackrest stanza-create   --repo1-type=gcs]"
time="2021-06-21T17:27:21Z" level=info msg="output=[]"
time="2021-06-21T17:27:21Z" level=info msg="stderr=[]"
time="2021-06-21T17:27:21Z" level=fatal msg="error sending request: Post \"https://172.16.16.1:443/api/v1/namespaces/db/pods/analytics-db-pg-backrest-shared-repo-877c49bf-qzr9h/exec?command=bash&container=database&stderr=true&stdin=true&stdout=true\": dial tcp 172.16.16.1:443: connect: connection refused"
```

Alternative solutions, all that are slightly too hard (like building a docker container for every container that postges-operato uses to match the "prefix" for containers, from the configuration), for them to be quick solutions.

**Comment by jkatz** [comment]
[PGO 5.0](https://access.crunchydata.com/documentation/postgres-operator/v5/) has additional retry logic built into it. In 4.x, so long as it is a Job, it will retry the default amount of times (which is 6) unless your cluster administrator has set the defaults to be different.

**Comment by haf** [comment]
This is wrong. It doesn’t retry in the case described

**Comment by jkatz** [comment]
As mentioned above, please try with PGO v5.0 as it has additional retry logic built into it.
