### ISSUE TITLE
Support job templates for the *-stanza jobs

### ISSUE THREAD

**Issue by haf** [CrunchyData/postgres-operator#2516]
## Overview
It would be great to override every property of a Job created by this operator, similar to how kustomize lets you override such properties. Maybe you could provide a JobTemplate field for every job and then use the Go API for kustomize to merge it? https://pkg.go.dev/sigs.k8s.io/kustomize/api

Another database, Elasticsearch, does it like this:

https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-snapshots.html#k8s_periodic_snapshots_with_a_cronjob

You could either have this template as part of the typed operator config, or you could let us optionally provide it via a ConfigMap to the running operator.

## Use Case

Describe your use case. Why do you want this feature? What problem will it solve? Why will it help you? Why will it make it easier to use PGO?

Why? Because there might be things in a deployment that you haven't thought of, like for example custom network services that need to be up and running before running a job, or having a global lock taken by the job. I have such a use case.

This would make it easier to use PGO because I wouldn't have to have issues closed by the maintainers as "questions" but instead could use an existing extension point to solve my use case. This applies, e.g. to anyone using Istio, or their own network-modifying sidecars, or when you'd like to inject metrics/tracing/telemetry into the jobs as well as the main pods.

In the long run, you could enable the same sort of xTemplate pattern for every CRD resource you create using the operator, including the deployments for the databases.

## Desired Behavior

Let me modify the jobTemplate for jobs created by the operator.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform:  k8s
- Platform Version: 4.7.0
- PGO Image Tag: `centos8-4.7.0`
- Postgres Version: 12
- Storage: N/A

**Comment by jkatz** [comment]
In 4.x, you can modify the Job template my modifying the `backrest-job.json` template in the `pgo-config` ConfigMap.

I would also recommend trying out [PGO 5.0](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/). This provides additional tuning parameters around how the backup jobs are run and managed.

If there is still something lacking, please feel free to open up an enhancement request.
