### ISSUE TITLE
Add default values for CPU limits and requests

### ISSUE THREAD

**Issue by Remp69** [CrunchyData/postgres-operator#2518]
## Overview

Add default values for limits and requests for each container.

## Use Case

There are default values for instance, pgbackrest, pgbouncer and exporter container memory request, for example in values.yaml :

- default_instance_memory: "128Mi"
- default_pgbackrest_memory: "48Mi"
- default_pgbouncer_memory: "24Mi"
- default_exporter_memory: "24Mi"

In pgo create cluster command, we can set any requests and limits values with those paramters :

      --cpu string                            Set the number of millicores to request for the CPU, e.g. "100m" or "0.1".
      --cpu-limit string                      Set the number of millicores to limit for the CPU, e.g. "100m" or "0.1".
      --memory string                         Set the amount of RAM to request, e.g. 1GiB. Overrides the default server value.
      --memory-limit string                   Set the amount of RAM to limit, e.g. 1GiB.

      --exporter-cpu string                   Set the number of millicores to request for CPU for the Crunchy Postgres Exporter sidecar container, e.g. "100m" or "0.1". Defaults to being unset.
      --exporter-cpu-limit string             Set the number of millicores to limit for CPU for the Crunchy Postgres Exporter sidecar container, e.g. "100m" or "0.1". Defaults to being unset.
      --exporter-memory string                Set the amount of memory to request for the Crunchy Postgres Exporter sidecar container. Defaults to server value (24Mi).
      --exporter-memory-limit string          Set the amount of memory to limit for the Crunchy Postgres Exporter sidecar container.

      --pgbackrest-cpu string                 Set the number of millicores to request for CPU for the pgBackRest repository.
      --pgbackrest-cpu-limit string           Set the number of millicores to limit for CPU for the pgBackRest repository.
      --pgbackrest-memory string              Set the amount of memory to request for the pgBackRest repository. Defaults to server value (48Mi).
      --pgbackrest-memory-limit string        Set the amount of memory to limit for the pgBackRest repository.

      --pgbouncer-cpu string                  Set the number of millicores to request for CPU for pgBouncer. Defaults to being unset.
      --pgbouncer-cpu-limit string            Set the number of millicores to limit for CPU for pgBouncer. Defaults to being unset.
      --pgbouncer-memory string               Set the amount of memory to request for pgBouncer. Defaults to server value (24Mi).
      --pgbouncer-memory-limit string         Set the amount of memory to limit for pgBouncer.

Without default values, if requests and limits are needed by the K8s cluster, users have to use all this parameters each time they create a cluster.

## Desired Behavior

Add parameters for default values for requests and limits on CPU and memory for each container.
Then users can use a simple pgo create cluster command which will satisfy requirements.

## Environment
- Platform: Kubernetes
- Platform Version: `1.20`, `4.7.0`
- PGO Image Tag: `centos8-4.7.0`
- Postgres Version: `13`
- Number of Postgres clusters: around 100

**Comment by psavva** [comment]
Hi @Remp69 

These are good values for you, but not necessarily for me or anyone else.

The Defaults as I see are OK as they are, and it's up to each user of the postgres-operator to specify their limits, during creation of their cluster.

Example: 
`go -n pgo create cluster hippo --cpu=8 --memory=16Gi --pgbackrest-pvc-size=20Gi  --pvc-size=2Gi --username=myuser --password='mypassword' `

**Comment by Remp69** [comment]
I think I misspoke. I've edited my first post to clarify. Let me clarify here too :

There are PGO parameters to set default memory request of 4 containers (instance, exporter, pgbackrest, pgbouncer) : 

- default_instance_memory
- default_pgbackrest_memory
- default_pgbouncer_memory
- default_exporter_memory

My desired behavior is just to add new parameters to do the same things (set default value) for cpu limit and request and memory limit for our 4 containers (instance, exporter, pgbackrest, pgbouncer).

**Comment by jkatz** [comment]
This is doable with PGO 5.0: [https://access.crunchydata.com/documentation/postgres-operator/v5/](https://access.crunchydata.com/documentation/postgres-operator/v5/) -- it's not setting a default value per se, but the values are adjustable during the lifecycle of a cluster directly from the manifest.
