### ISSUE TITLE
Synchronous replication when a synchronous replica crashes

### ISSUE THREAD

**Issue by ragorilla** [CrunchyData/postgres-operator#2524]
Hello,

I got three questions while reading [your document regarding synchronous replication](https://access.crunchydata.com/documentation/postgres-operator/4.7.0/architecture/high-availability/), saying

> there is a potential impact to availability: if a synchronous replica crashes, any writes to the primary will be blocked until a replica is promoted to become a new synchronous replica of the primary.

1) Under synchronous replication enabled, is it possible to have non-synchronous replica connected to the primary in the cluster?
 If it doesn't make sense, is there no way except that primary wait for the crashed replica to become online to unblock the primary when the replica crashed?

2) Could I change the behavior of the primary to like below?
- write transaction to the primary continues to replicate to other replicas and completes, **ignoring the crashed replica**.

3) How long does the primary wait for until when a synchronous replica become down?
If there is a timeout for this and the timeout exceeds, I wonder the succeeding behavior of the primary.

Thank you in advance.

**Comment by jkatz** [comment]
> 1. Under synchronous replication enabled, is it possible to have non-synchronous replica connected to the primary in the cluster?

Yes.

> 2. Could I change the behavior of the primary to like below?
> write transaction to the primary continues to replicate to other replicas and completes, ignoring the crashed replica.

Yes, this is actually the default behavior.

> How long does the primary wait for until when a synchronous replica become down?
> If there is a timeout for this and the timeout exceeds, I wonder the succeeding behavior of the primary.

The default is to favor availability over consistency. The primary will continue to accept writes even if the sync rep is down, unless you choose `synchronous_mode_strict`.
