### ISSUE TITLE
Wal grows indefinitely when S3 bucket is not reachable

### ISSUE THREAD

**Issue by Martin-Hogge** [CrunchyData/postgres-operator#2525]
I found my database down this morning, after some verification I found that the cause was the WAL folder has grown indefinitely because my S3 bucket is not reachable.

Postgresql logs:
```
WARN: repo1: [HostConnectError] unable to load info file '/backrestrepo/postgres-mydomain-dev-backrest-shared-repo/archive/db/archive.info' or '/backrestrepo/postgres-mydomain-dev-backrest-shared-repo/archive/db/archive.info.copy':
      HostConnectError: raised from remote-0 protocol on 'postgres-mydomain-dev-backrest-shared-repo': timeout connecting to 'backup.mydomain.com:443'
      HostConnectError: raised from remote-0 protocol on 'postgres-mydomain-dev-backrest-shared-repo': timeout connecting to 'backup.mydomain.com:443'
      HINT: archive.info cannot be opened but is required to push/get WAL segments.
      HINT: is archive_command configured correctly in postgresql.conf?
      HINT: has a stanza-create been performed?
      HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
```

There are also `stanza-create` job that fails continuously:
```
...
2021-07-07 10:23:09.687 CESTtime="2021-07-07T08:23:09Z" level=info msg="command to execute is [pgbackrest stanza-create --db-host=10.60.5.58 --db-path=/pgdata/postgres-mydomain-dev --repo1-type=s3]"
Error
2021-07-07 10:23:10.705 CESTtime="2021-07-07T08:23:10Z" level=info msg="output=[]"
Error
2021-07-07 10:23:10.705 CESTtime="2021-07-07T08:23:10Z" level=info msg="stderr=[ERROR: [056]: unable to find primary cluster - cannot proceed\n]"
Error
2021-07-07 10:23:10.705 CESTtime="2021-07-07T08:23:10Z" level=fatal msg="command terminated with exit code 56"
```

My question is: is it possible to avoid this behaviour ? I would expect missing backups but a working database in case of unreachable s3 bucket.

Thank you for your insights.

**Comment by Martin-Hogge** [comment]
Sub-question: is there a way to switch from s3 to posix backup system ? So that when the s3 bucket is unreachable I could mitigate the issue.

Thanks.

**Comment by jkatz** [comment]
This is a PostgreSQL feature. If you are running with archive mode enabled, Postgres will retain WAL archives until it knows they have been pushed to all appropriate places.

It is possible to switch backup systems in [PGO 5.0](https://access.crunchydata.com/documentation/postgres-operator/v5/). 5.0 also supports different backup storage combinations.
