### ISSUE TITLE
Error in production: ErrImagePull & ImagePullBackOff

### ISSUE THREAD

**Issue by gritview** [CrunchyData/postgres-operator#2527]
Please ensure you do the following when reporting a bug:

- [x] Provide a concise description of what the bug is.
- [x] Provide information about your environment.
- [x] Provide clear steps to reproduce the bug.
- [x] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [x] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

## Overview

**ErrImagePull** Error in production
Cannot pull image 'registry.developers.crunchydata.com/crunchydata/postgres-operator:centos7-4.5.1' from the registry.

`rpc error: code = NotFound desc = failed to pull and unpack image "registry.developers.crunchydata.com/crunchydata/pgo-apiserver:centos7-4.5.1": failed to resolve reference "registry.developers.crunchydata.com/crunchydata/pgo-apiserver:centos7-4.5.1": registry.developers.crunchydata.com/crunchydata/pgo-apiserver:centos7-4.5.1: not found: ErrImagePull`

<img width="562" alt="Screen Shot 2021-07-08 at 3 38 35 PM" src="https://user-images.githubusercontent.com/77709482/124999254-93410380-e002-11eb-854b-846e9642732b.png">

**This happened out of the blue in production.**

## Environment

Please provide the following details:

- Platform: `Kubernetes`
- Platform Version: `1.18.17-gke.1901`
- PGO Image Tag: `centos7-4.5.1`
- Postgres Version `13`
- Storage: `local google storage`

**Comment by gritview** [comment]
`rpc error: code = NotFound desc = failed to pull and unpack image "registry.developers.crunchydata.com/crunchydata/pgo-apiserver:centos7-4.5.1": failed to resolve reference "registry.developers.crunchydata.com/crunchydata/pgo-apiserver:centos7-4.5.1": registry.developers.crunchydata.com/crunchydata/pgo-apiserver:centos7-4.5.1: not found: ErrImagePull`

**Comment by andrewlecuyer** [comment]
@gritview please see the following response: https://github.com/CrunchyData/postgres-operator/issues/2485#issuecomment-855426623

As you can see, a notice went out to the [developer mailing list](https://www.crunchydata.com/developers/newsletter) several months ago (which was displayed on the website) regarding the deprecation and removal of the CentOS 7 images.  The images that are currently publicly available via the Developer Portal (including the latest v4.5 release) can be found [here](https://www.crunchydata.com/developers/download-postgres/containers).

**Comment by gritview** [comment]
@andrewlecuyer 

 I would really appreciate your guidance in upgrading and resolving this issue. I'm not exactly sure what to do as a next step to resolve the issue.

Thank you :)
