### ISSUE TITLE
Operator container on 4.7.0 can't reconcile RBAC

### ISSUE THREAD

**Issue by adthonb** [CrunchyData/postgres-operator#2536]
Please ensure you do the following when reporting a bug:
- [ ] Provide a concise description of what the bug is.
- [ ] Provide information about your environment.
- [ ] Provide clear steps to reproduce the bug.
- [ ] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.

## Overview

I don't understand why Operator version 4.7.0 can't reconcile RBAC. I can install successfully on version 4.6.0. I try to remove the whole namespace and recreat from the manifest but I still get an error message in the operator container. 

## Environment

Please provide the following details:
- Platform: `Kubernetes`
- Platform Version: 4.7.0
- PGO Image Tag: `postgres-operator:centos8-4.7.0`
- Postgres Version: don't deploy yet
- Storage: `hostpath`

### REPRO

Provide steps to get to the error condition:

1. `kubectl create namespace pgo-new`
2. `curl -O https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.7.0/installers/kubectl/postgres-operator.yml`
2.  Replace namespace in resource and `pgo_operator_namespace` to pgo-new
2. `kubectl apply -f postgres-operator.yml`
3. `kubectl -n pgo logs --tail 15 postgres-operator-6b95f7bf54-djpbm -c operator` 

### EXPECTED

No error message on operator container

### ACTUAL

Got error message on operator container

## Logs

`time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot create resource \"serviceaccounts\" in API group \"\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:132" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot create resource \"serviceaccounts\" in API group \"\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:132" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot create resource \"serviceaccounts\" in API group \"\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:132" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: serviceaccounts is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot create resource \"serviceaccounts\" in API group \"\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileServiceAccounts()" file="internal/controller/manager/rbac.go:132" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-target-role\" is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot get resource \"roles\" in API group \"rbac.authorization.k8s.io\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-backrest-role\" is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot get resource \"roles\" in API group \"rbac.authorization.k8s.io\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-pg-role\" is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot get resource \"roles\" in API group \"rbac.authorization.k8s.io\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: rolebindings.rbac.authorization.k8s.io \"pgo-target-role-binding\" is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot get resource \"rolebindings\" in API group \"rbac.authorization.k8s.io\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:112" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: rolebindings.rbac.authorization.k8s.io \"pgo-backrest-role-binding\" is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot get resource \"rolebindings\" in API group \"rbac.authorization.k8s.io\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:112" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="operator is unable to reconcile RBAC resource: rolebindings.rbac.authorization.k8s.io \"pgo-pg-role-binding\" is forbidden: User \"system:serviceaccount:pgo-new:postgres-operator\" cannot get resource \"rolebindings\" in API group \"rbac.authorization.k8s.io\" in the namespace \"pgo-new\"" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:112" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="Controller Manager: Controller Group for namespace pgo-new does not have the required list privileges for resource pgtasks in the crunchydata.com API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:347" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="Controller Manager: Controller Group for namespace pgo-new does not have the required list privileges for resource pgclusters in the crunchydata.com API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:347" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="Controller Manager: Controller Group for namespace pgo-new does not have the required list privileges for resource pgreplicas in the crunchydata.com API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:347" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="Controller Manager: Controller Group for namespace pgo-new does not have the required list privileges for resource pgpolicies in the crunchydata.com API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:347" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="Controller Manager: Controller Group for namespace pgo-new does not have the required list privileges for resource pods in the Core API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:360" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="Controller Manager: Controller Group for namespace pgo-new does not have the required list privileges for resource jobs in the Batch API" func="internal/controller/manager.(*ControllerManager).hasListerPrivs()" file="internal/controller/manager/controllermanager.go:372" version=4.7.0
time="2021-07-12T20:17:11Z" level=error msg="Namespace Controller: error syncing Namespace 'pgo-new': Controller Manager: cannot start controller group for namespace pgo-new because it does not have the required privs, will attempt to start on the next ns refresh interval" func="internal/controller/namespace.(*Controller).processNextWorkItem()" file="internal/controller/namespace/namespacecontroller.go:151" version=4.7.0`

**Comment by jkatz** [comment]
- Did you ensure you replaced all of the `namespace` entries in the `postgres-operator.yml` file?

**Comment by adthonb** [comment]
@jkatz Yes, I replace all. Please look at it below. Sorry for the late reply.

```apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgo-deployer-sa
  namespace: pgo-new
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-new-deployer-cr
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - create
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - list
      - get
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - delete
      - list
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - get
      - create
      - delete
      - patch
      - list
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - create
      - delete
      - bind
      - escalate
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
      - list
  - apiGroups:
      - crunchydata.com
    resources:
      - pgclusters
      - pgreplicas
      - pgpolicies
      - pgtasks
    verbs:
      - delete
      - list
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgo-deployer-cm
  namespace: pgo-new
data:
  values.yaml: |-
    # =====================
    # Configuration Options
    # More info for these options can be found in the docs
    # https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/
    # =====================
    archive_mode: "true"
    archive_timeout: "60"
    backrest_aws_s3_bucket: ""
    backrest_aws_s3_endpoint: ""
    backrest_aws_s3_key: ""
    backrest_aws_s3_region: ""
    backrest_aws_s3_secret: ""
    backrest_aws_s3_uri_style: ""
    backrest_aws_s3_verify_tls: "true"
    backrest_gcs_bucket: ""
    backrest_gcs_endpoint: ""
    backrest_gcs_key_type: ""
    backrest_port: "2022"
    badger: "false"
    ccp_image_prefix: "registry.developers.crunchydata.com/crunchydata"
    ccp_image_pull_secret: ""
    ccp_image_pull_secret_manifest: ""
    ccp_image_tag: "centos8-13.3-4.7.0"
    create_rbac: "true"
    crunchy_debug: "false"
    db_name: ""
    db_password_age_days: "0"
    db_password_length: "24"
    db_port: "5432"
    db_replicas: "0"
    db_user: "ckthink"
    default_instance_memory: "256Mi"
    default_pgbackrest_memory: "48Mi"
    default_pgbouncer_memory: "24Mi"
    default_exporter_memory: "24Mi"
    delete_operator_namespace: "false"
    delete_watched_namespaces: "false"
    disable_auto_failover: "false"
    disable_fsgroup: "false"
    reconcile_rbac: "true"
    exporterport: "9187"
    metrics: "false"
    namespace: "pgo-new"
    namespace_mode: "dynamic"
    pgbadgerport: "10000"
    pgo_add_os_ca_store: "false"
    pgo_admin_password: "Aq7H3a7nI8Mpdd"
    pgo_admin_perms: "*"
    pgo_admin_role_name: "pgoadmin"
    pgo_admin_username: "admin"
    pgo_apiserver_port: "8443"
    pgo_apiserver_url: "https://postgres-operator"
    pgo_client_cert_secret: "pgo.tls"
    pgo_client_container_install: "false"
    pgo_client_install: "true"
    pgo_client_version: "4.7.0"
    pgo_cluster_admin: "false"
    pgo_disable_eventing: "false"
    pgo_disable_tls: "false"
    pgo_image_prefix: "registry.developers.crunchydata.com/crunchydata"
    pgo_image_pull_secret: ""
    pgo_image_pull_secret_manifest: ""
    pgo_image_tag: "centos8-4.7.0"
    pgo_installation_name: "devtest"
    pgo_noauth_routes: ""
    pgo_operator_namespace: "pgo-new"
    pgo_tls_ca_store: ""
    pgo_tls_no_verify: "false"
    pod_anti_affinity: "preferred"
    pod_anti_affinity_pgbackrest: ""
    pod_anti_affinity_pgbouncer: ""
    scheduler_timeout: "3600"
    service_type: "ClusterIP"
    sync_replication: "false"
    backrest_storage: "default"
    backup_storage: "default"
    primary_storage: "default"
    replica_storage: "default"
    pgadmin_storage: "default"
    wal_storage: ""
    storage1_name: "default"
    storage1_access_mode: "ReadWriteOnce"
    storage1_size: "4G"
    storage1_type: "dynamic"
    storage2_name: "hostpathstorage"
    storage2_access_mode: "ReadWriteMany"
    storage2_size: "1G"
    storage2_type: "create"
    storage3_name: "nfsstorage"
    storage3_access_mode: "ReadWriteMany"
    storage3_size: "1G"
    storage3_type: "create"
    storage3_supplemental_groups: "65534"
    storage4_name: "nfsstoragered"
    storage4_access_mode: "ReadWriteMany"
    storage4_size: "1G"
    storage4_match_labels: "crunchyzone=red"
    storage4_type: "create"
    storage4_supplemental_groups: "65534"
    storage5_name: "storageos"
    storage5_access_mode: "ReadWriteOnce"
    storage5_size: "5Gi"
    storage5_type: "dynamic"
    storage5_class: "fast"
    storage6_name: "primarysite"
    storage6_access_mode: "ReadWriteOnce"
    storage6_size: "4G"
    storage6_type: "dynamic"
    storage6_class: "primarysite"
    storage7_name: "alternatesite"
    storage7_access_mode: "ReadWriteOnce"
    storage7_size: "4G"
    storage7_type: "dynamic"
    storage7_class: "alternatesite"
    storage8_name: "gce"
    storage8_access_mode: "ReadWriteOnce"
    storage8_size: "300M"
    storage8_type: "dynamic"
    storage8_class: "standard"
    storage9_name: "rook"
    storage9_access_mode: "ReadWriteOnce"
    storage9_size: "1Gi"
    storage9_type: "dynamic"
    storage9_class: "rook-ceph-block"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pgo-new-deployer-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pgo-new-deployer-cr
subjects:
  - kind: ServiceAccount
    name: pgo-deployer-sa
    namespace: pgo-new
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pgo-deploy
  namespace: pgo-new
spec:
  backoffLimit: 0
  template:
    metadata:
      name: pgo-deploy
    spec:
      serviceAccountName: pgo-deployer-sa
      restartPolicy: Never
      containers:
        - name: pgo-deploy
          image: registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos8-4.7.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DEPLOY_ACTION
              value: install
          volumeMounts:
            - name: deployer-conf
              mountPath: "/conf"
      volumes:
        - name: deployer-conf
          configMap:
            name: pgo-deployer-cm
```
