### ISSUE TITLE
 secret <cluster>-postgres-token  missing

### ISSUE THREAD

**Issue by tamagottschi** [CrunchyData/postgres-operator#2542]
When we create a new cluster the secret <cluster>-postgres-token for the postgres superuser will not be generated.

We are running RKE (Rancher) with Kubernetes 1.19.9 and using the postgres operator version 5.0.

We created just the cluster "hippo" exactly as described in the tutorial with postgresql 13. We have the same problem with our own postgres cluster, too.

Is the missing token a bug or is there a reason for this?

Thx, Jan

**Comment by jkatz** [comment]
The superuser is not made available by default. This is for a variety of reasons.

However, an upcoming release will allow you to specify additional users/roles (e.g. superuser) you would like to create should you need to connect with a superuser.

**Comment by flotothemoon** [comment]
Just to clarify @jkatz, this means that in the current 5.0 version it's not possible at all to create additional users? While not critical, it would be very convenient to add superusers e.g. in our test environment to create & destroy test databases (is there another way to achieve this?).

**Comment by jkatz** [comment]
You can still create new users in 5.0 by logging in directly to the database and doing so.

However, #2574 should make this process simpler and will be available in the next release.
