### ISSUE TITLE
Can I use my own Postgres docker image

### ISSUE THREAD

**Issue by sskurapati** [CrunchyData/postgres-operator#2548]
Hi Team,
It's a very good operator with wonderful documentation, Thanks to each one who contribute to this project.

We are running all our services in docker, now we want to move to Kubernetes, so I am here to understand how this operator helps us.

I have few questions, please guide me.

1. We have our own Postgres docker image (with timescale and init DB scripts), is it possible to use our Postgres docker image in this operator?
2. If 1st point is possible then, how can we pass environment variables to the pod?
3. If 1st is not possible then, is there any way to trigger our init DB scripts?
4. Is the operator-provided Postgres images support timescale DB?

Please help me ASAP.

Thanks,
Sambasiva

**Comment by jkatz** [comment]
This was answered on the [community support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) mailing list.
