### ISSUE TITLE
`pgo restore` and `pgo create cluster --restore-from` doesn't work with AWS S3

### ISSUE THREAD

**Issue by shubhammalvankar** [CrunchyData/postgres-operator#2553]
Environment:
```
	Platform: OpenShift
	Platform Version: 4.6
	PGO Image Tag: ubi7-12.5-4.5.1
	Postgres Version 12
```
	
I am trying to create a new cluster, backup using pgbackrest on AWS S3 and restore from it. The cluster is created and backed up but the restore doesn't work. 

Below mentioned are the 2 config maps, one containing values.yaml and other pgo.yaml:

File containing values.yaml
```
	apiVersion: v1
	kind: ConfigMap
	metadata:
	  name: pgo-deployer-cm
	data:
	  values.yaml: |+
		---
		archive_mode: "true"
		archive_timeout: "60"
		backrest_aws_s3_bucket: ""
		backrest_aws_s3_endpoint: ""
		backrest_aws_s3_key: ""
		backrest_aws_s3_region: ""
		backrest_aws_s3_secret: ""
		backrest_aws_s3_uri_style: ""
		backrest_aws_s3_verify_tls: "true"
		backrest_port: "2022"
		badger: "false"
		ccp_image_prefix: "registry.connect.redhat.com/crunchydata"
		ccp_image_pull_secret: ""
		ccp_image_pull_secret_manifest: ""
		ccp_image_tag: "ubi7-12.5-4.5.1"
		create_rbac: "true"
		crunchy_debug: "false"
		db_name: ""
		db_password_age_days: "0"
		db_password_length: "24"
		db_port: "5432"
		db_replicas: "0"
		db_user: "testuser"
		default_instance_memory: "128Mi"
		default_pgbackrest_memory: "48Mi"
		default_pgbouncer_memory: "24Mi"
		delete_metrics_namespace: "false"
		delete_operator_namespace: "false"
		delete_watched_namespaces: "false"
		disable_auto_failover: "false"
		disable_fsgroup: "false"
		reconcile_rbac: "true"
		exporterport: "9187"
		metrics: "false"
		metrics_namespace: testcluster
		namespace: testcluster
		namespace_mode: "disabled"
		pgbadgerport: "10000"
		pgo_add_os_ca_store: "false"
		pgo_admin_password: "examplepassword"
		pgo_admin_perms: "*"
		pgo_admin_role_name: "pgoadmin"
		pgo_admin_username: "admin"
		pgo_apiserver_port: "8443"
		pgo_apiserver_url: "https://postgres-operator"
		pgo_client_cert_secret: "pgo.tls"
		pgo_client_container_install: "false"
		pgo_client_version: "4.5.1"
		pgo_cluster_admin: "false"
		pgo_disable_eventing: "false"
		pgo_disable_tls: "false"
		pgo_image_prefix: "registry.connect.redhat.com/crunchydata"
		pgo_image_pull_secret: ""
		pgo_image_pull_secret_manifest: ""
		pgo_image_tag: "ubi7-4.5.1"
		pgo_installation_name: "postgres-db"
		pgo_noauth_routes: ""
		pgo_operator_namespace: testcluster
		pgo_tls_ca_store: ""
		pgo_tls_no_verify: "false"
		pod_anti_affinity: "preferred"
		pod_anti_affinity_pgbackrest: ""
		pod_anti_affinity_pgbouncer: ""
		prometheus_install: "false"
		prometheus_storage_access_mode: "ReadWriteOnce"
		prometheus_storage_class_name: "fast"
		prometheus_supplemental_groups: "65534"
		prometheus_volume_size: "1G"
		scheduler_timeout: "3600"
		service_type: "ClusterIP"
		sync_replication: "false"
		backrest_storage: "storageos"
		backup_storage: "storageos"
		primary_storage: "storageos"
		replica_storage: "storageos"
		wal_storage: ""
		storage1_name: "hostpathstorage"
		storage1_access_mode: "ReadWriteMany"
		storage1_size: "1G"
		storage1_type: "create"
		storage2_name: "replicastorage"
		storage2_access_mode: "ReadWriteMany"
		storage2_size: "1G"
		storage2_type: "create"
		storage3_name: "nfsstorage"
		storage3_access_mode: "ReadWriteMany"
		storage3_size: "1G"
		storage3_type: "create"
		storage3_supplemental_groups: "65534"
		storage4_name: "nfsstoragered"
		storage4_access_mode: "ReadWriteMany"
		storage4_size: "1G"
		storage4_match_labels: "crunchyzone=red"
		storage4_type: "create"
		storage4_supplemental_groups: "65534"
		storage5_name: "storageos"
		storage5_access_mode: "ReadWriteOnce"
		storage5_size: "40Gi"
		storage5_type: "dynamic"
		storage5_class: ""
		storage6_name: "primarysite"
		storage6_access_mode: "ReadWriteOnce"
		storage6_size: "4G"
		storage6_type: "dynamic"
		storage6_class: "primarysite"
		storage7_name: "alternatesite"
		storage7_access_mode: "ReadWriteOnce"
		storage7_size: "4G"
		storage7_type: "dynamic"
		storage7_class: "alternatesite"
		storage8_name: "gce"
		storage8_access_mode: "ReadWriteOnce"
		storage8_size: "300M"
		storage8_type: "dynamic"
		storage8_class: "standard"
		storage9_name: "rook"
		storage9_access_mode: "ReadWriteOnce"
		storage9_size: "1Gi"
		storage9_type: "dynamic"
		storage9_class: ""
```
File containing pgo.yaml
```
	apiVersion: v1
	kind: ConfigMap
	metadata:
	  name: pgo-config
	data:
	  pgo.yaml: |
		Cluster:
		  CCPImagePrefix: registry.connect.redhat.com/crunchydata
		  Metrics:  false
		  Badger:  false
		  CCPImageTag: ubi7-12.5-4.5.1
		  Port:  5432
		  PGBadgerPort: 10000
		  ExporterPort: 9187
		  User:  testuser
		  Database:  ""
		  PasswordAgeDays:  0
		  PasswordLength:  24
		  Replicas:  0
		  ArchiveMode:  false
		  ServiceType:  ClusterIP
		  BackrestPort:  2022
		  BackrestS3Bucket: "testbucket"
		  BackrestS3Endpoint: "s3.amazonaws.com"
		  BackrestS3Region: "us-east-1"
		  BackrestS3URIStyle: "host"
		  BackrestS3VerifyTLS: false
		  DisableAutofail:  false
		  PodAntiAffinity: preferred
		  PodAntiAffinityPgBackRest: ""
		  PodAntiAffinityPgBouncer: ""
		  SyncReplication: false
		  DefaultInstanceMemory: "128Mi"
		  DefaultBackrestMemory:
		  DefaultPgBouncerMemory:
		  DisableFSGroup: true
		PrimaryStorage: storageos
		WALStorage:
		BackupStorage: storageos
		ReplicaStorage: storageos
		BackrestStorage: storageos
		Storage:
		  hostpathstorage:
			AccessMode:  ReadWriteMany
			Size:  1G
			StorageType:  create
		  replicastorage:
			AccessMode:  ReadWriteMany
			Size:  700M
			StorageType:  create
		  nfsstorage:
			AccessMode:  ReadWriteMany
			Size:  1G
			StorageType:  create
			SupplementalGroups:  65534
		  nfsstoragered:
			AccessMode:  ReadWriteMany
			Size:  1G
			MatchLabels: crunchyzone=red
			StorageType:  create
			SupplementalGroups:  65534
		  storageos:
			AccessMode:  ReadWriteOnce
			Size:  "10Gi"
			StorageType:  dynamic
			StorageClass: ""
		  primarysite:
			AccessMode:  ReadWriteOnce
			Size:  4G
			StorageType:  dynamic
			StorageClass:  primarysite
		  alternatesite:
			AccessMode:  ReadWriteOnce
			Size:  4G
			StorageType:  dynamic
			StorageClass:  alternatesite
		  gce:
			AccessMode:  ReadWriteOnce
			Size:  300M
			StorageType:  dynamic
			StorageClass:  standard
		  rook:
			AccessMode:  ReadWriteOnce
			Size:  1G
			StorageType:  dynamic
			StorageClass:  
		Pgo:
		  Audit:  false
		  PGOImagePrefix: registry.connect.redhat.com/crunchydata
		  PGOImageTag: ubi7-4.5.1
```

Creation of a cluster is done using :
	
`	pgo create cluster --tls-only=false $CLUSTER_NAME --replica-count=$DB_REPLICAS --username $PG_USERNAME --password $PG_PASSWORD --pgbackrest-storage-type s3 -n $PGO_OPERATOR_NAMESPACE --pgbackrest-s3-bucket="testbucket" --pgbackrest-s3-endpoint="s3.amazonaws.com" --pgbackrest-s3-region="us-east-1" --pgbackrest-s3-key=$AWS_S3_KEY --pgbackrest-s3-key-secret=$AWS_S3_KEY_SECRET
`

---
**Case 1:** Using `pgo restore` command to restore the same cluster to a specific time say 

Command(as an example):

`		yes | pgo restore $CLUSTER_NAME --pgbackrest-storage-type=s3 -n $PGO_OPERATOR_NAMESPACE --pitr-target="2021-07-19 19:25:00.999999+00" --backup-opts="--type=time"
`
The logs show the error:

```
		2021-07-19 14:26:33,535 INFO: trying to bootstrap a new cluster
		2021-07-19 14:26:33,535 INFO: Running custom bootstrap script: /opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh primary
		[0;32mMon Jul 19 14:26:33 UTC 2021 INFO: Empty PGDATA dir found for primary, a non-delta restore will be peformed[0m
		ERROR: [095]: raised from remote-0 protocol on 'testcluster-backrest-shared-repo': unable to set user-defined CA certificate location: [33558530] No such file or directory
		[0;31mMon Jul 19 14:26:33 UTC 2021 ERROR: pgBackRest primary Creation: pgBackRest restore failed when creating primary[0m
		2021-07-19 14:26:33,894 INFO: removing initialize key after failed attempt to bootstrap the cluster
		2021-07-19 14:26:34,199 INFO: renaming data directory to /pgdata/testcluster_2021-07-19-14-26-34
		Traceback (most recent call last):
		  File "/usr/local/bin/patroni", line 11, in <module>
			sys.exit(main())
		  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 170, in main
			return patroni_main()
		  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
			abstract_main(Patroni, schema)
		  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
			controller.run()
		  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
			super(Patroni, self).run()
		  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
			self._run_cycle()
		  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
			logger.info(self.ha.run_cycle())
		  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
			info = self._run_cycle()
		  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1346, in _run_cycle
			return self.post_bootstrap()
		  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1242, in post_bootstrap
			self.cancel_initialization()
		  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1235, in cancel_initialization
			raise PatroniFatalException('Failed to bootstrap cluster')
		patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```
		
No CA certificate is used so the I am not sure about the error.
If I try to restart the pod then the log says:

```
		[0;32mTue Jul 20 04:26:05 UTC 2021 INFO: Your data might be in: /pgdata/testcluster_2021-07-19-14-26-34[0m
		[0;33mTue Jul 20 04:26:15 UTC 2021 WARN: Detected an earlier failed attempt to initialize[0m
		[0;32mTue Jul 20 04:26:15 UTC 2021 INFO: Correct the issue, remove '/pgdata/testcluster.initializing', and try again[0m
```
		
---
	
**Case 2:** Using `--restore-from` flag in the `pgo create cluster` command to restore to a new cluster

Command:
`		pgo create cluster --tls-only=false $CLUSTER_NAME --replica-count=$DB_REPLICAS --username $PG_USERNAME --password $PG_PASSWORD -n $PGO_OPERATOR_NAMESPACE --restore-from=$CLUSTER_NAME --restore-opts="--repo-type=s3" --pgbackrest-s3-bucket="testbucket" --pgbackrest-s3-endpoint="s3.amazonaws.com" --pgbackrest-s3-region="us-east-1" --pgbackrest-s3-key=$AWS_S3_KEY --pgbackrest-s3-key-secret=$AWS_S3_KEY_SECRET `
		
The error found in the pod log is:
`		Error: Unable to find PVC testcluster-pgbr-repo for cluster testcluster, cannot to restore from the specified data source
`		
The cluster should be restored from s3 so why is it looking for a local pvc?
		
I am not sure what I am doing wrong and was wondering if there are some specific values to be configured in the pgo.yaml or while running those commands.

```
    PrimaryStorage: 
    WALStorage:
    BackupStorage: 
    ReplicaStorage: 
    BackrestStorage: 
```

I would also like to ask if there are any specific values for the above keys I need to use to backup and restore from AWS S3 ?

**Comment by shubhammalvankar** [comment]
@jkatz Can you please provide some guidance on this?

**Comment by MichaluxPL** [comment]
I second that problem.
I've tried to restore using the following command:
pgo create cluster s3test2 --restore-from=s3test --pgbackrest-storage-type=s3 --restore-opts="--repo1-type=s3 --no-repo1-s3-verify-tls --repo1-s3-bucket=${S3BUCKET} --repo1-s3-endpoint=${S3ENDPOINT} --repo1-s3-region=${S3REGION}" --pgbackrest-s3-key=${PGBACKREST_S3_KEY} --pgbackrest-s3-key-secret=${PGBACKREST_S3_KEY_SECRET} -n pgo
I've got the following error:
ERROR: [037]: restore command requires option: repo1-s3-key

Providing this option (together with repo1-s3-key-secret) in restore-opts, produces another error:
ERROR: [031]: option 'repo1-s3-key' is not allowed on the command-line
       HINT: this option could expose secrets in the process list.
       HINT: specify the option in a configuration file or an environment variable instead.

I can't see a way to provide this option directly on a pod level. Both key/secret should be taken from cluster configuration (pointed in --restore-from option).

**Comment by jkatz** [comment]
Can you provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.)
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `ubi8-5.0.2-0`)
- Postgres Version (e.g. `13`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

Can you provide the restore command that you ran?

**Comment by MichaluxPL** [comment]
Platform: Kubernetes
Platform Version: 10.20.7
PGO Image Tag: centos8-4.7.0
Postgres Version: 13
Storage: local

In terms of commands, I actually try to create a new cluster based on the other cluster backup.
I've tried (with no luck):
1.
pgo create cluster s3test2 --restore-from=s3test --pgbackrest-storage-type=s3 --restore-opts="--repo1-type=s3 --no-repo1-s3-verify-tls --repo1-s3-bucket=${S3BUCKET} --repo1-s3-endpoint=${S3ENDPOINT} --repo1-s3-region=${S3REGION}" --pgbackrest-s3-key=${PGBACKREST_S3_KEY} --pgbackrest-s3-key-secret=${PGBACKREST_S3_KEY_SECRET} -n pgo
This one produces ERROR: 
ERROR: [037]: restore command requires option: repo1-s3-key

2.
pgo create cluster s3test2 --restore-from=s3test --pgbackrest-storage-type=s3 --restore-opts="--repo1-type=s3 --no-repo1-s3-verify-tls --repo1-s3-bucket=${S3BUCKET} --repo1-s3-endpoint=${S3ENDPOINT} --repo1-s3-region=${S3REGION} --repo1-s3-key=${PGBACKREST_S3_KEY} --repo1-s3-key-secret=${PGBACKREST_S3_KEY_SECRET}" -n pgo
This ends with:
ERROR: [031]: option 'repo1-s3-key' is not allowed on the command-line
HINT: this option could expose secrets in the process list.
HINT: specify the option in a configuration file or an environment variable instead.

3. pgo create cluster s3test2 --restore-from=s3test --pgbackrest-storage-type=s3
This one cannot find source stanza, since it looks for it locally (not on S3).
I guess even this one should work, since having the --restore-from option provided, it should look for stanza where it was configured for a given cluster name.
Of course I have required backup for s3test available on S3:
pgo show backup s3test -n pgo

cluster: s3test
storage type: s3

stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13-1)

        full backup: 20210901-075357F
            timestamp start/stop: 2021-09-01 09:53:57 +0200 CEST / 2021-09-01 09:54:49 +0200 CEST
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 31.0MiB, backup size: 31.0MiB
            repository size: 3.8MiB, repository backup size: 3.8MiB
            backup reference list:

        incr backup: 20210901-075357F_20210901-080323I
            timestamp start/stop: 2021-09-01 10:03:23 +0200 CEST / 2021-09-01 10:03:26 +0200 CEST
            wal start/stop: 000000010000000000000005 / 000000010000000000000005
            database size: 31.0MiB, backup size: 216.3KiB
            repository size: 3.8MiB, repository backup size: 25.8KiB
            backup reference list: 20210901-075357F

        full backup: 20210901-081712F
            timestamp start/stop: 2021-09-01 10:17:12 +0200 CEST / 2021-09-01 10:18:11 +0200 CEST
            wal start/stop: 00000001000000000000000A / 00000001000000000000000B
            database size: 38.5MiB, backup size: 38.5MiB
            repository size: 4.8MiB, repository backup size: 4.8MiB
            backup reference list:

**Comment by MichaluxPL** [comment]
Any news regarding this one ?

**Comment by andrewlecuyer** [comment]
Since this issue involves restore functionality from an older version of Crunchy Postgres for Kubernetes (including an older version of pgBackRest), I am proceeding with closing this issue.

If you have any additional questions - or if you would like to further discuss Disaster Recovery (DR) scenarios, processes, functionality, etc. with Crunchy Postgres for Kubernetes v5 - please feel free to reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).

And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/

Thanks!
