### ISSUE TITLE
Define type of service for pgo v5

### ISSUE THREAD

**Issue by bryanasdev000** [CrunchyData/postgres-operator#2555]
Is it possible to define a service type other than Cluster IP for Postgres components?

I didn't find anything in the documentation or references of the CRDs (https://access.crunchydata.com/documentation/postgres-operator/v5/references/crd/).

I'm using the default v5 installation (https://github.com/CrunchyData/postgres-operator-examples) on AKS v1.20.7.

**Comment by jkatz** [comment]
What service type are you trying to use and why?

**Comment by bryanasdev000** [comment]
> What service type are you trying to use and why?

I'm thinking about load balancer to expose Postgres to outside application/cluster/vm.

**Comment by jkatz** [comment]
We're going to look into adding this into the next feature release.
