### ISSUE TITLE
Which of the two example collections (repos) should I use?

### ISSUE THREAD

**Issue by victor-sudakov** [CrunchyData/postgres-operator#2568]
Which of the two example collections should I use? If I want to use a Helm chart to install the operator, should I prefer postgres-operator/examples/helm/install/ or postgres-operator-examples/helm/install/ ? The charts are different, which is preferred?

Also, is Helm generally a non-recommended way to install and configure the operator? You have many examples in the kustomize subdir and not so many in the Helm subdir, why is that?

**Comment by victor-sudakov** [comment]
E.g. the excellent and rather recent blog article at https://blog.crunchydata.com/blog/gitops-postgres-kubernetes-helm seems to refer to incorrect paths and files: postgres-operator/examples/helm/postgres does not exist

**Comment by jkatz** [comment]
Either are fine -- they are both the canonical charts. In the fullness of time the Helm charts will identically mirror the Kustomize manifests. Of course, patches that expedite the process are welcome :smile:

Thanks for the comment on the blog post. That was written for the Helm chart with PGO 4.x. The examples repository is specifically for 5.

**Comment by victor-sudakov** [comment]
Hello @jkatz !

> Either are fine -- they are both the canonical charts.

But I've run "diff -r" against them and they are different! There are extra and missing sections.

> In the fullness of time the Helm charts will identically mirror the Kustomize manifests. Of course, patches that expedite the process are welcome 

Would not it be a good idea first to merge those two example repos, to avoid confusion?

**Comment by jkatz** [comment]
Sorry I misread. The Helm charts in the postgres-operator-examples repo are the canonical ones. The ones in this repo are being removed, if they have not been removed already.

**Comment by victor-sudakov** [comment]
> The Helm charts in the postgres-operator-examples repo are the canonical ones

Thank you for clarification!

**Comment by victor-sudakov** [comment]
>  The ones in this repo are being removed, if they have not been removed already.

Last I looked, they are still there and updated 4 days ago.
