### ISSUE TITLE
Gitlab review environments with postgres clusters

### ISSUE THREAD

**Issue by webchi** [CrunchyData/postgres-operator#2575]
Hi. I am trying to run postrgres cluster per [gitalb review environment](https://docs.gitlab.com/ee/ci/review_apps/). Kubernetes cluster integrated with gitlab and "[namespace per enironment](https://git.big3.ru/help/user/project/clusters/index.md#custom-namespace)" was turned on. 
For dependency chart I've took [this helm example](https://github.com/CrunchyData/postgres-operator-examples/tree/main/helm/postgres).
So I have such .gitlab-ci.yaml to deploy.

```
deploy_review:
  stage: deploy 
  image: alpine/helm:3.5.4
  script:    
   - helm upgrade project .helm --install --values=.helm/values.yaml --namespace ${KUBE_NAMESPACE}
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: http://$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  only:
    - /^review/.*$/
  tags:
    - kubernetes
```
And this error appears in brunch "review/k8s"
```
$ helm upgrade project .helm --install --values=.helm/values.yaml --namespace ${KUBE_NAMESPACE}
Release "project" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: postgresclusters.postgres-operator.crunchydata.com "default" is forbidden: User "system:serviceaccount:main-234-review-k8s:main-234-review-k8s-service-account" cannot get resource "postgresclusters" in API group "postgres-operator.crunchydata.com" in the namespace "main-234-review-k8s"
```
Is any thoughts about what is the point of happening?

**Comment by jkatz** [comment]
>  postgresclusters.postgres-operator.crunchydata.com "default" is forbidden: User "system:serviceaccount:main-234-review-k8s:main-234-review-k8s-service-account" cannot get resource "postgresclusters" in API group "postgres-operator.crunchydata.com" in the namespace "main-234-review-k8s"

Is the RBAC set up correctly?

**Comment by webchi** [comment]
> > postgresclusters.postgres-operator.crunchydata.com "default" is forbidden: User "system:serviceaccount:main-234-review-k8s:main-234-review-k8s-service-account" cannot get resource "postgresclusters" in API group "postgres-operator.crunchydata.com" in the namespace "main-234-review-k8s"
> 
> Is the RBAC set up correctly?

Not sure. How to check it?

**Comment by andrewlecuyer** [comment]
Considering this is an older issue that simply seems to have been related to invalid RBAC (additionally, we are not seeing any other issues with our current Helm installers for v5), I am proceeding with closing this issue.

If you have any additional questions, and/or if you would like to further discuss Helm installations with Crunchy Postgres for Kubernetes v5, please feel free to reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).
