### ISSUE TITLE
Copy-paste in exported metrics

### ISSUE THREAD

**Issue by zerkms** [CrunchyData/postgres-operator#2576]
My apologies for posting it to a wrong repository, but I have not found where it really originates from

```
# HELP ccp_stat_database_temp_files Number of rows deleted by queries in this database
# TYPE ccp_stat_database_temp_files gauge
ccp_stat_database_temp_files{dbname="hippo-ha",server="localhost:5432"} 0
ccp_stat_database_temp_files{dbname="postgres",server="localhost:5432"} 15
# HELP ccp_stat_database_tup_deleted Number of rows deleted by queries in this database
# TYPE ccp_stat_database_tup_deleted gauge
ccp_stat_database_tup_deleted{dbname="hippo-ha",server="localhost:5432"} 0
ccp_stat_database_tup_deleted{dbname="postgres",server="localhost:5432"} 0
```

See the `ccp_stat_database_temp_files` help line is copy-pasted from the `ccp_stat_database_tup_deleted`.

**Comment by jkatz** [comment]
Metrics come from [pgMonitor](https://github.com/CrunchyData/pgmonitor). However, without following the bug reporting template this is nearly impossible to locate where and how this is occurring.
