### ISSUE TITLE
Can not  build pgo images

### ISSUE THREAD

**Issue by killerwzb** [CrunchyData/postgres-operator#2578]
Hi:
  I use source code to build the pgo images,but i get the error like this:

error building at STEP "ADD conf/RPM-GPG-KEY-crunchydata* /": no files found matching "/home/wzbwangzhibin/postgres-operator/conf/RPM-GPG-KEY-crunchydata*": no such file or directory

The Dockerfile's content like this:

ADD conf/crunchypg${PGVERSION}.repo /etc/yum.repos.d/

I can not find this file at the conf path.How can you tell me resolve it .

If you believe you have found have found a bug, please open up [Bug Report](https://github.com/CrunchyData/postgres-operator/issues/new?template=bug_report.md)

If you have a feature request, please open up a [Feature Request](https://github.com/CrunchyData/postgres-operator/issues/new?template=feature_request.md)

You can find information about general PGO [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) at:

[https://access.crunchydata.com/documentation/postgres-operator/latest/support/](https://access.crunchydata.com/documentation/postgres-operator/latest/support/)

**Comment by jkatz** [comment]
This is described here:

[https://access.crunchydata.com/documentation/postgres-operator/latest/contributing/developer-setup/](https://access.crunchydata.com/documentation/postgres-operator/latest/contributing/developer-setup/)
