### ISSUE TITLE
crunchy 5.0 user doesn't have access to create role

### ISSUE THREAD

**Issue by stenwt** [CrunchyData/postgres-operator#2579]
There's a role created automatically by the operator, but it doesn't have access to create other roles. Is there a way I can either elevate the privileges of the operator-created user, or use a different user to access the database?

**Comment by jkatz** [comment]
Currently you can do this:

```
kubectl exec -it -c database \
    $(kubectl get pods --selector='postgres-operator.crunchydata.com/cluster=$CLUSTER_NAME,postgres-operator.crunchydata.com/role=master' -o name) -- psql -c 'CREATE ROLE ...'
```

with appropriate additions for namespace and substitution for `$CLUSTER_NAME`.

#2574 will allow for these adjustments during cluster bootstrap in 5.0.1.
