### ISSUE TITLE
Does PGO support external Etcd?

### ISSUE THREAD

**Issue by sasadangelo** [CrunchyData/postgres-operator#2589]
Hi all,

I read all the documentation here:
https://access.crunchydata.com/documentation/postgres-operator/5.0.0/

and it is clear to me that PGO uses Kubernetes API Server as DCS. Is it possible use an Etcd cluster deployed on the same Kubernetes nodes and configure Patroni to reference it in some way? I am working on a project and for several reasons, we prefer to have DCS on our own Etcd.

**Comment by jkatz** [comment]
Why do you want to use an etcd external to Kubernetes DCS?

**Comment by sasadangelo** [comment]
Essentially for two reasons:

1. The architect I am working with doesn't trust the K8s Control Plane we are working on. He experienced several downtimes of the API server and he doesn't want to connect the cluster HA with K8s Etcd HA.
2. Suppose you have a three-node PostgreSQL cluster and a K8s Control Plane replicated three times. It could happen a network partition from the Master Patroni node and the other two Patroni nodes. However, the Patroni master can still contact Kubernetes ETCD and TTL is updated. In this scenario, a new master cannot be elected so we have clients that cannot reach the master but could reach the two nodes that at that moment cannot become master.

We work on mission-critical applications and scenario 2 could become very hard to debug. 

We have Patroni running on Bare metal machines with Patroni/Etcd/PostgreSQL instances for each node. In this configuration scenario 2 above cannot happen because if the network partition occurs also the Etcd running on the same node of the master is excluded and a new Ectd master is elected and so also a new Patroni master.

We are evaluating CrunchyData to migrate our infrastructure to Kubernetes and we would like to support scenario 2 as well. Our basic idea is to deploy a three-node cluster Etcd on Kubernetes where each Pod runs on each Patroni node.

I know it is possible to configure Patroni to use its own Etcd even in Kubernetes but I don't know if there could be an issue with CrunchyData. Do you think this configuration can be supported?

**Comment by sasadangelo** [comment]
A diagram to let you understand what I am talking about.

<img width="778" alt="Screenshot 2021-08-03 at 17 35 10" src="https://user-images.githubusercontent.com/12810456/128044133-66ad15ae-b9d4-4801-a0c0-c418eee0ddbf.png">

**Comment by sasadangelo** [comment]
Hi again,

I am trying to figure out an answer to this question by myself but it is not easy. Patroni allows configuring Kubernetes as DCS (disabled by default) and an external Etcd. There are variables to do that:
https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html#kubernetes

The problem is that running the command ```kubectl explain PostgresCluster --recursive``` and I don't see a way to pass environment variables to the containers using the Postgres Operator syntax:

```
   spec <Object>
   ...
      instances <[]Object>
          affinity
          ...
          dataVolumeClaimSpec    <Object>
          ...
         metadata       <Object>
          ...
         name   <string>
         replicas       <integer>
         resources      <Object>
          ...
         tolerations    <[]Object>
          ...
         walVolumeClaimSpec     <Object>
          ...
.```

Moreover, even if I can Patroni with these environment variables I am not sure if the Postgres Operator supports this scenario.

**Comment by andrewlecuyer** [comment]
@sasadangelo we're currently reviewing some older issues and GitHub, and just wanted to follow-up here to see if you're still looking for external ETCD support.

Additionally, thank you for providing additional details about your use case.

**Comment by benjaminjb** [comment]
Closing this for now, but if this is still an issue, please reopen.
