### ISSUE TITLE
WAL archive feature enhancements

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#260]
I apologize for listing all enhancements under one issue. Please break it apart as you see fit.

1) ability to add archiving capability after the cluster is created

2) Archive pvc defaults to using backup pvc storage. Please provide a way to specify a custom storage type for archive WALs

3) archive pvc has the same size as data pvc and gets deleted along with data pvc. After a failover, all the WALs generated before the failover get deleted. Can you not delete archive pvc by default and add a new option --delete-archive that would delete archive pvc

4) Can archive pvc be setup as a shared mount across all pods of a pg cluster ?

5) wal and xlog names are used interchangeably. Could you standardize on one name ?

**Comment by jmccormick2001** [comment]
I think this is implemented in 3.5 with pgbackrest shared repo and also the xlogstorage config in pgo.yaml.  Moved to clubhouse.
