### ISSUE TITLE
Where is the PGO v5.0.1 release tag?

### ISSUE THREAD

**Issue by tgates-nalej** [CrunchyData/postgres-operator#2604]
The CrunchyData website shows the CrunchData Postgres Operator at version v5.0.1.  But I don't see that tag in this Git repo.

"V5 Docs" link on:
  https://access.crunchydata.com/documentation/  
  
goes to:
  https://access.crunchydata.com/documentation/postgres-operator/v5/

**Comment by jkatz** [comment]
5.0.1 is now available in the Developer Portal:

[https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator-5x](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator-5x)

Information about the release process is available in the README:

[https://github.com/CrunchyData/postgres-operator#releases](https://github.com/CrunchyData/postgres-operator#releases)

**Comment by tgates-nalej** [comment]
@jkatz  The links you provided uses the PGO docker images.  I'm looking for the Postgres Operator v5 source code.

**Comment by jkatz** [comment]
The source code is in this repository.

**Comment by tgates-nalej** [comment]
@jkatz  So the v5 release is not tagged here?  Why not?
