### ISSUE TITLE
adding additional container to pgbouncer v5

### ISSUE THREAD

**Issue by ThommyH** [CrunchyData/postgres-operator#2618]
## Overview
As of now, there is no option in the postgrescluster crd to add sidecars for metrics inside the pgbouncer pods. e.g. https://github.com/prometheus-community/pgbouncer_exporter
If would be nice to have the option to attach sidecars including stuff like env/valueFrom or resources.
While doing so, it would make sense to extend the container capabilities of postgres instances, where currently the only option is to add a monitoring image.

## Use Case
Monitoring pgbouncer alongside postgres instances is important to fine tune settings and identifying issues.

## Desired Behavior
A standard way of specifying additional container to pgbouncer

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: `Kubernetes`, `GKE`
- Platform Version: `1.19.x`
- PGO Image Tag: `ubi8-5.0.1-0`
- Postgres Version `13`
- Number of Postgres clusters:  soon >50

**Comment by jkatz** [comment]
> Monitoring pgbouncer alongside postgres instances is important to fine tune settings and identifying issues.

What are you looking to monitor specifically?

If the general purpose monitoring system that comes with PGO is extended to provide pgBouncer metrics, would that suffice?

> While doing so, it would make sense to extend the container capabilities of postgres instances

What are you looking to do here?

**Comment by ThommyH** [comment]
thanks for the quick reply!

We would like to monitor bouncer stats like pool active connections, max client waiting time to connect (if pool is exhausted) [https://github.com/prometheus-community/pgbouncer_exporter#metrics](see here more examples).

If the existing exporter could also do this, by all means that would also work. But might be the more difficult way.

> What are you looking to do here?

As of now, the exporter in the crd is rather limited in what we can set (configmap, resources, secret
[crd ref](https://access.crunchydata.com/documentation/postgres-operator/v5/references/crd/#postgresclusterspecmonitoringpgmonitorexporter)). If one wants to use another exporter than pgmonitor (or to add non-exporter sidecars like cleanup jobs or report generation) you need more options to configure sidecars.
For example _env_ (which allows setting vars from secrets secretKeyRef) or _command_, which are standard in pod api for container [api ref](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#container-v1-core) would be nice to have.
As it is standard in the pod api, it (extra container definition) could be easily forwarded to the deployments for both, pgbouncer and pg instances from the pgo.

**Comment by sharkymcdongles** [comment]
I agree with @ThommyH .  I think best approach would be to allow specifying sidecars to any pod deployed by the CRD. This way people can add custom sidecars where needed / wanted. I think in general the ability to have this pod deployed next to the bouncer pod would be useful: https://github.com/prometheus-community/pgbouncer_exporter

However flexibility is always nice to have.

**Comment by stoetti** [comment]
Are there any plans extending the CRD in the near future?
