### ISSUE TITLE
PgBackRest integration with ZFS S3

### ISSUE THREAD

**Issue by lbartnicki92** [CrunchyData/postgres-operator#2619]
## Overview

Hi!
Currently We are trying in our company to use Crunchy Operator with Oracle ZFS S3 for storing pgBackRest backups.
We get HTTP request failed with 400 (Bad Request) error when creating Stanza.

## Environment

- Platform: Kubernetes
- Platform Version: v1.20.7
- PGO Image Tag: postgres-operator:centos8-4.7.0
- Postgres Version: crunchy-postgres-ha:centos8-13.3-4.7.0
- Storage: HostPath for data  + S3 for backups

## Steps to Reproduce

1. Deploy operator with ConfigMap parameters:

    backrest_aws_s3_bucket: "s3/v1/export/backup_sandbox"
    backrest_aws_s3_endpoint: "10.0.175.10"
    backrest_aws_s3_key: "user"
    backrest_aws_s3_region: "eu-west-1"
    backrest_aws_s3_secret: "xxxxxxxxxxxxxxx"
    backrest_aws_s3_uri_style: "path"
    backrest_aws_s3_verify_tls: "false"

2. Create cluster with:

pgo create cluster s3test1 --pgbackrest-storage-type=s3 -n pgo

3. Execute any backup command like pgo backup ....

### EXPECTED

1. Backup write to S3

### ACTUAL

1. [root@osx05826:~]# pgo show backup s3test

cluster: s3test
storage type: s3

stanza: db
    status: other
    cipher: none

2. Errors in container:
bash-4.4$ pgbackrest stanza-create --db-host=10.233.81.32 --db-path=/pgdata/s3test --repo1-type=s3 --no-repo1-s3-verify-tls --repo-s3-bucket=s3/v1/export/backup_sandbox
ERROR: [039]: **HTTP request failed with 400 (Bad Request):**
       *** Path/Query ***:
       /s3/v1/export/backup_sandbox/?delimiter=%2F&list-type=2&prefix=backrestrepo%2Fs3test-backrest-shared-repo%2Farchive%2Fdb%2F
       *** Request Headers ***:
       authorization: <redacted>
       content-length: 0
       host: 10.0.175.10
       x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
       x-amz-date: <redacted>
       *** Response Headers ***:
       connection: close
       content-length: 282
       content-type: application/xml; charset=utf-8
       date: Thu, 19 Aug 2021 08:32:31 GMT
       server: Apache
       x-amz-request-id: tx321e1a4b965f4e279376f-00611e171f
       x-content-type-options: nosniff
       *** Response Content ***:
       <?xml version="1.0" ?>
       <Error>
         <Code>InvalidArgument</Code>
         <Message>**Bad Request (Invalid query parameter in request)**</Message>
         <Resource>/v1/export/backup_sandbox/</Resource>
         <RequestId>tx321e1a4b965f4e279376f-00611e171f</RequestId>
         <HostId>10.0.175.10</HostId>
       </Error>

3. Errors from kubectl logs on pgo backrest container:

nss_wrapper: user exists
nss_wrapper: group exists
nss_wrapper: environment configured
Thu Aug 19 10:58:14 UTC 2021 INFO: Image mode found: pgbackrest
Thu Aug 19 10:58:14 UTC 2021 INFO: Starting in 'pgbackrest' mode
time="2021-08-19T10:58:14Z" level=info msg="crunchy-pgbackrest starts"
time="2021-08-19T10:58:14Z" level=info msg="debug flag set to false"
time="2021-08-19T10:58:14Z" level=info msg="backrest stanza-create command requested"
time="2021-08-19T10:58:14Z" level=info msg="s3 flag enabled for backrest command"
time="2021-08-19T10:58:14Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.233.69.130 --db-path=/pgdata/s3test --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2021-08-19T10:58:15Z" level=info msg="output=[]"
time="2021-08-19T10:58:15Z" level=info msg="stderr=**[ERROR: [039]: HTTP request failed with 400 (Bad Request):\n**       *** Path/Query ***:\n       /s3/v1/export/backup_sandbox/?delimiter=%2F&list-type=2&prefix=backrestrepo%2Fs3test-backrest-shared-repo%2Farchive%2Fdb%2F\n       *** Request Headers ***:\n       authorization: <redacted>\n       content-length: 0\n       host: 10.0.175.10\n       x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n       x-amz-date: <redacted>\n       *** Response Headers ***:\n       connection: close\n       content-length: 282\n       content-type: application/xml; charset=utf-8\n       date: Thu, 19 Aug 2021 10:58:15 GMT\n       server: Apache\n       x-amz-request-id: tx1e6dccb7308f4836a0a29-00611e3947\n       x-content-type-options: nosniff\n       *** Response Content ***:\n       <?xml version=\"1.0\" ?>\n       <Error>\n         <Code>InvalidArgument</Code>\n         <Message>Bad Request (Invalid query parameter in request)</Message>\n         <Resource>/v1/export/backup_sandbox/</Resource>\n         <RequestId>tx1e6dccb7308f4836a0a29-00611e3947</RequestId>\n         <HostId>10.0.175.10</HostId>\n       </Error>\n       \n]"
time="2021-08-19T10:58:15Z" level=fatal msg="command terminated with exit code 39"

**Comment by jkatz** [comment]
I discussed this with some of the pgBackRest developers. It seems that there may be an issue with either the bucket name, or the combination of bucket name / path style URLs. You may need to trace the exact error in the ZFS S3 logs.

Outside of that, this does not appear to be an issue with PGO. If there is something that is reproducible and can be traced to a pgBackRest bug, please feel free to open up an issue in the [pgBackRest](https://github.com/pgbackrest/pgbackrest) repo.


(If this is a new setup, I would suggest trying out [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/)).
