### ISSUE TITLE
Add ability to compress pgo backups

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#262]
pgo backups are full filesystem copies to backup pvc. 
Since PITR and incremental backups are not available, frequent full backups are being taken and it is consuming lot of disk space.

Can you add the ability to compress backups preferably without adding any additional steps to restore.

**Comment by jmccormick2001** [comment]
pgo backup jango --backup-type=pgbackrest --pgbackrest-opts="--compress --compress-level=9"

with code in develop branch today, you can enter commands like that to have pgbackrest perform a compressed backup.  I think this is the way we'll support backup compression within the operator going forward, users can still use pgbasebackup as they typically have (pgo backup) but for advanced backup features we'll rely on pgbackrest like above.
