### ISSUE TITLE
Missing install script/Where are TLS Secrets

### ISSUE THREAD

**Issue by kahunacohen** [CrunchyData/postgres-operator#2627]
I installed pgo via the helm chart to a local minikube cluster, and I can see the pod is up and running:

```
$ kubectl get pods -n pgo
NAME                   READY   STATUS    RESTARTS   AGE
pgo-749c55c7c9-fptp5   1/1     Running   0          32h
```
 I am then told to install the pgo client from this page: https://access.crunchydata.com/documentation/postgres-operator/4.6.2/installation/other/helm/

```
curl https://raw.githubusercontent.com/CrunchyData/postgres-operator/master/installers/kubectl/client-setup.sh > client-setup.sh
chmod +x client-setup.sh
./client-setup.sh
```

However the `client-setup.sh` no longer exists in the master repo.

I found it in a tag: https://raw.githubusercontent.com/CrunchyData/postgres-operator/REL_4_7/installers/kubectl/client-setup.sh

I run it and it says it can't find the client secrets. But I installed the chart as per instructions.

Then I try to follow the manual instructions, or rather the part of the docs that explain what the client-setup.sh script is supposed to do:

```
Pulls the TLS keypair from the PostgreSQL Operator pgo.tls Secret so that the pgo client can communicate with the PostgreSQL Operator. These are saved as client.crt and client.key in the $HOME/.pgo/$PGO_OPERATOR_NAMESPACE path.
```

But I can't find the pgo.tls secret. Should this have been created with the helm install? 

These are the secrets I have under the `pgo` ns:

```
$ kubectl get secrets -n pgo
NAME                                      TYPE                                  DATA   AGE
default-token-4mxhc                       kubernetes.io/service-account-token   3      32h
pgo-token-cw4x5                           kubernetes.io/service-account-token   3      32h
sh.helm.release.v1.postgres-operator.v1   helm.sh/release.v1                    1      32h
```
How can I install the pgo client?

**Comment by jkatz** [comment]
If this is a new installation, I would recommend starting with [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/). That being said, it seems like you did install v5. If that's the case, there are no `pgo` client Secrets, as there is no `pgo` client for v5.

If you are looking for v4, I would recommend stepping through the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/) first. I will note that some of the links may need to be updated due to switch to `v5` being in the `master` branch now.

**Comment by kahunacohen** [comment]
I am installing via helm. Is there a reason there is no client for 5? Has it been replaced by something else?

**Comment by jkatz** [comment]
v5 can be managed through manifests. Here are some articles on the various design decisions and how to get started:

- [https://blog.crunchydata.com/blog/the-next-generation-of-kubernetes-native-postgres](https://blog.crunchydata.com/blog/the-next-generation-of-kubernetes-native-postgres)
- [https://blog.crunchydata.com/blog/getting-started-with-pgo-postgres-operator-5.0](https://blog.crunchydata.com/blog/getting-started-with-pgo-postgres-operator-5.0)
