### ISSUE TITLE
Documentation for Helm Outdated?

### ISSUE THREAD

**Issue by kahunacohen** [CrunchyData/postgres-operator#2635]
I would like to install pgo with helm. I found this blog post by crunchy data:
https://blog.crunchydata.com/blog/gitops-postgres-kubernetes-helm

The first step is:

```
git clone --depth 1 https://github.com/CrunchyData/postgres-operator.git
cd postgres-operator/examples/helm
```
However there is no `helm` directory here. See:
https://github.com/CrunchyData/postgres-operator/tree/master/examples

This page also doesn't seem right:
https://crunchydata.github.io/postgres-operator/3.5.0/installation/#helm-chart

If I try version 5, it doesn't exist:
https://crunchydata.github.io/postgres-operator/5.0.0/installation/

Is there up-to-date instructions on how to install via helm?

**Comment by prlaurence** [comment]
@kahunacohen yes - it appears that there are a few links that need to be updated in that blog post. i appreciate your reporting it.  The documentation for installing pgo 5 with helm can be found here: 

https://access.crunchydata.com/documentation/postgres-operator/v5/installation/helm/

**Comment by kahunacohen** [comment]
@prlaurence I followed the instructions:

```
helm install mypgo -n pgo helm/install

Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "pgo" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "mypgo": current value is "postgres-operator"
```
Can you explain the specific instructions:

`helm install <name> -n <namespace> helm/install`

No matter what I pass, the install fails with a similar message.

**Comment by uberspot** [comment]
Are there any docs on how to configure https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/#general-configuration these when installing via helm? The helm chart doesn't include any config by default.
