### ISSUE TITLE
Error after creating a cluster on pgo version 4.7.2 (pgbackrest error)

### ISSUE THREAD

**Issue by Dnathan33** [CrunchyData/postgres-operator#2648]
Please ensure you do the following when reporting a bug:

- [ x] Provide a concise description of what the bug is.
- [ x] Provide information about your environment.
- [ x] Provide clear steps to reproduce the bug.
- [ x] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [x ] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

After creating a new cluster using pgo version `4.7.2` the pgbackrest image `centos8-13.3-4.7.2` is not being found

<img width="549" alt="Screen Shot 2021-08-27 at 7 50 16 PM" src="https://user-images.githubusercontent.com/39175434/131203969-6ac4416d-7e24-4533-95c5-71063ccb2e97.png">

## Environment

Please provide the following details:

- Platform: `GKE`
- Platform Version: `4.7.2`
- PGO Image Tag: `centos8-13.3-4.7.2`
- Postgres Version: `13`
- Storage: `N/A`

## Steps to Reproduce

Create a new cluster with pgo version 4.7.2

### EXPECTED

1. A new cluster is created
2. Cluster is working as expected

### ACTUAL & Logs

After creating a cluster using the `pro create cluster gritview-postgres` command the pgbackrest errors out.

```
pgo show user -n pgo gritview-postgres --show-system-accounts     


CLUSTER USERNAME PASSWORD EXPIRES STATUS ERROR
------- -------- -------- ------- ------ -----------------------------------------------------------------------------
                                  error  primary pod not found for selector "pg-cluster=gritview-postgres,role=master"

```

```
Back-off pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-13.3-4.7.2"

Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-13.3-4.7.2": rpc error: code = NotFound desc = failed to pull and unpack image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-13.3-4.7.2": failed to resolve reference "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-13.3-4.7.2": registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-13.3-4.7.2: not found: ErrImagePull
```

```
kubectl -n pgo describe service gritview-postgres-backrest-shared-repo

Name:              gritview-postgres-backrest-shared-repo
Namespace:         pgo
Labels:            name=gritview-postgres-backrest-shared-repo
                   pg-cluster=gritview-postgres
                   pgo-backrest-repo=true
                   vendor=crunchydata
Annotations:       cloud.google.com/neg: {"ingress":true}
Selector:          name=gritview-postgres-backrest-shared-repo
Type:              ClusterIP
IP:                10.44.9.183
Port:              <unset>  2022/TCP
TargetPort:        2022/TCP
Endpoints:
Session Affinity:  None
Events:            <none>
```

## Additional Information

Seem like this image version is was not being found
`centos8-13.3-4.7.2`

**Comment by Dnathan33** [comment]
@jkatz has this been merge/PR been pushed to production? If so, I still get the same error.

**Comment by Dnathan33** [comment]
@jkatz any updates? our production envioremnt is down because of this atm.

**Comment by jkatz** [comment]
If you are beginning a new project, I recommend starting with [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/).

That said, this issue was fixed in #2647. For immediate workarounds, you can do the following:

1. In the `pgo-config` ConfigMap, find the `pgo.yaml` entry and modify the `CCPImageTag` part to say `centos8-13.4-4.7.2`. Restart the `postgres-operator` Pod (scale down/up the `postgres-operator` Deployment).

All new Postgres deployments will use the updated image tag.

2. If you do not wish to do that, you can manually specify the image tag in each `pgo create cluster` command:

```
pro create cluster gritview-postgres --ccp-image-tag=centos8-13.4-4.7.2
```

If this is a brand new Postgres deployment in general, I suggest starting out with [`v5`](https://access.crunchydata.com/documentation/postgres-operator/v5/).

**Comment by Dnathan33** [comment]
@jkatz I was able to deploy using `V5`. However, I was not able to connect my django application to the database as usual. 

in `V4` I used the local Postgres host url which followed this template `<cluster_name>.pgo.svc.cluster.local`. This is however not working in `V5`. I get the following error: `"gritview.pgo.svc.cluster.local" to address: Name or service not known`

Here is what my database config looks like in django:
cluster name = gritview
```
DATABASES = {
    'default': {
        # If you are using Cloud SQL for MySQL rather than PostgreSQL, set
        # 'ENGINE': 'django.db.backends.mysql' instead of the following.
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_name',
        'USER': 'admin',
        'PASSWORD': 'pssw',
        'HOST': 'gritview.pgo.svc.cluster.local',
        'PORT': '5432',
    }
}

```
`

**Comment by jkatz** [comment]
I recommend reading the tutorial on connecting applications:

[https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/connect-cluster/](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/connect-cluster/)
