### ISSUE TITLE
Multi database  pgcluster

### ISSUE THREAD

**Issue by alfadil** [CrunchyData/postgres-operator#2655]
Hi,
thanks for this great operator.
I want to know is it possible to have multi databases in the same cluster?

**Comment by jkatz** [comment]
[Yes](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/user-management/).

**Comment by alfadil** [comment]
> [Yes](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/user-management/).

Thank you for your response.
How?
And is it recommended?

**Comment by jkatz** [comment]
The link off of the [`yes`](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/user-management/) response goes to a tutorial that shows how to add multiple databases to a cluster.

As to "is it recommended," it's up to how you want to organize your data and what your availability and performance requirements are. It may make more sense to have each of your databases in its own cluster if you want to have them spread out over your Kubernetes topology. However, based on your access patterns, it may be fine to keep them together.

**Comment by alfadil** [comment]
that's greate,@jkatz thanks for your time.
