### ISSUE TITLE
Master pod missing label role=master

### ISSUE THREAD

**Issue by nilpntr** [CrunchyData/postgres-operator#2656]
## Overview

Missing pod labels.

## Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version: v1.18.9
- PGO Image Tag: centos8-4.7.0
- Postgres Version: 13
- Storage: ceph-csi

### EXPECTED

The master pod for a psql cluster with a label `role=master`

### ACTUAL

When I'm creating a new cluster using pgo cli, there're missing an important pod label: `role=master`. So I can't create any users for the cluster.

## Cluster info
```
cluster : singularity (crunchy-postgres-ha:centos8-13.3-4.7.0)
	pod : singularity-769b887fcc-s4q9m (Running) on iwag6i.tbk.k8s0.transip.io (1/1) (unknown)
		pvc: singularity (954Mi)
	resources : Memory: 128Mi
	deployment : singularity
	deployment : singularity-backrest-shared-repo
	deployment : singularity-pgadmin
	service : singularity - ClusterIP (10.109.201.224) - Ports (2022/TCP, 5432/TCP)
	service : singularity-pgadmin - ClusterIP (10.98.204.14) - Ports (5050/TCP)
	labels : pgo-version=4.7.0 pgouser=admin workflowid=f0533773-f658-4f77-a140-8f709cc391e1 crunchy-pgadmin=true name=singularity pg-cluster=singularity
```

**Comment by jkatz** [comment]
There is probably something that is unhealthy with your cluster. You should run `kubectl logs` on the Postgres Pod, and possibly inspect the `/pgdata/<clusterName>/pg_log` directory.

Note that if you are building out a new setup, I recommend getting started on [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/).

**Comment by benjaminjb** [comment]
If you're still running into this problem, please reopen this issue.
