### ISSUE TITLE
Operator projects using the removed APIs in k8s 1.22 requires changes.

### ISSUE THREAD

**Issue by camilamacedo86** [CrunchyData/postgres-operator#2659]
### Problem Description

Kubernetes has been deprecating API(s), which will be removed and are no longer available in 1.22. Operators projects using [these APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) versions will **not** work on Kubernetes 1.22 or any cluster vendor using this Kubernetes version(1.22), such as OpenShift 4.9+. Following the APIs that are most likely your projects to be affected by:
- apiextensions.k8s.io/v1beta1: (Used for CRDs and available since v1.16)
- rbac.authorization.k8s.io/v1beta1: (Used for RBAC/rules and available since v1.8)
- admissionregistration.k8s.io/v1beta1 (Used for Webhooks and available since v1.16)

Therefore, looks like this project distributes solutions in the [repository](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/postgresql) and does not contain any version compatible with k8s 1.22/OCP 4.9. ([More info](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138)). Following some findings by checking the distributions published:

- **postgresoperator.v4.2.0**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgbackups.crunchydata.com" "pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.3.2**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.4.0**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.5.1**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.6.1**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.1.0**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgbackups.crunchydata.com" "pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.4.1**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.5.0**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.7.0**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.2.1**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgbackups.crunchydata.com" "pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.0.1**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgbackups.crunchydata.com" "pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.2.2**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgbackups.crunchydata.com" "pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.6.0**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 
- **postgresoperator.v4.6.2**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["pgclusters.crunchydata.com" "pgpolicies.crunchydata.com" "pgreplicas.crunchydata.com" "pgtasks.crunchydata.com"]) 

**NOTE:** The above findings are only about the manifests shipped inside of the distribution. It is not checking the codebase.

### How to solve

It would be very nice to see new distributions of this project that are no longer using [these APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) and so they can work on Kubernetes 1.22 and newer and published in the [community-operators](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/postgresql) collection. OpenShift 4.9, for example, will not ship operators anymore that do still use v1beta1 extension APIs.

Due to the number of options available to build Operators, it is hard to provide direct guidance on updating your operator to support Kubernetes 1.22. Recent versions of the [OperatorSDK](https://github.com/operator-framework/operator-sdk) greater than [1.0.0](https://github.com/operator-framework/operator-sdk/releases) and [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) greater than [3.0.0](https://github.com/kubernetes-sigs/kubebuilder/releases) scaffold your project with the latest versions of these APIs (all that is generated by tools only). See the guides to upgrade your projects with OperatorSDK [Golang](https://sdk.operatorframework.io/docs/building-operators/golang/migration/), [Ansible](https://sdk.operatorframework.io/docs/building-operators/ansible/migration/), [Helm](https://sdk.operatorframework.io/docs/building-operators/helm/migration/) or the [Kubebuilder](https://book.kubebuilder.io/migration/v2vsv3.html) one. For APIs other than the ones mentioned above, you will have to check your code for usage of removed API versions and upgrade to newer APIs. The details of this depend on your codebase.

**If this projects only need to migrate the API for CRDs and it was built with [OperatorSDK](https://github.com/operator-framework/operator-sdk) versions lower than [1.0.0](https://github.com/operator-framework/operator-sdk/releases) then, you maybe able to solve it with an [OperatorSDK](https://github.com/operator-framework/operator-sdk) version >= v0.18.x < 1.0.0:**

> $ operator-sdk generate crds --crd-version=v1
> INFO[0000] Running CRD generator.                       
> INFO[0000] CRD generation complete.

**Alternatively, you can try to upgrade your manifests with [controller-gen](https://book.kubebuilder.io/reference/controller-gen.html) ([version >= v0.4.1](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.4.1)) :**

#### If this project does not use Webhooks:

> $ controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role  paths="./..."

#### If this project is using Webhooks:

1. Add the markers [sideEffects](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L81) and [admissionReviewVersions](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L114) to your webhook (Example with sideEffects=None and admissionReviewVersions={v1,v1beta1}: [memcached-operator/api/v1alpha1/memcached_webhook.go](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/api/v1alpha1/memcached_webhook.go#L39)):

2. Run the command:
> $ controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role webhook paths="./..."

For further information and tips see the [comment](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138#discussioncomment-1245759).

**Comment by jkatz** [comment]
@camilamacedo86 Thanks for your note.

[v5](https://access.crunchydata.com/documentation/postgres-operator/v5/) of the Operator is designed to support Kubernetes 1.22. We have already certified Operator in the Red Hat partner system and currently have a few PRs open to add it to OperatorHub:

https://github.com/k8s-operatorhub/community-operators/pull/164
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/178

We are maintaining compatibility for [v4](https://access.crunchydata.com/documentation/postgres-operator/latest/) with OpenShift 3.11 as we have customers who are still running OCP 3.11. Because of this, we do not want to add support for CRD API v1 as that would break compatibility.

**Comment by jkatz** [comment]
@camilamacedo86 For versions of PGO that we are not supporting on Kube 1.22+ / OCP 4.9+, we have this artifact in it:

https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/postgresql/4.7.0/postgresoperator.v4.7.0.clusterserviceversion.yaml#L13

Whereas supported versions do not contain it.

Does that suffice?

**Comment by camilamacedo86** [comment]
Hi @jkatz,

Seems that you publish in the latest days a new version `5.0.2` which should work on k8s 1.22 and OCP 4.9+. Am I right? if that is the case then, please feel free to close this issue and really thank you for make your project compatible.

**Comment by jkatz** [comment]
Hi @camilamacedo86,

> Seems that you published a new version `5.0.2` which should work on k8s 1.22 and OCP 4.9+. Am I right? 

Yes, that's correct.

> if that is the case then, please feel free to close this issue and really thank you to provide a compatible version of your solution.

You're welcome!

> The annotation; https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/postgresql/4.7.0/postgresoperator.v4.7.0.clusterserviceversion.yaml#L13 has added automatically in the cases that were possible identify that are using removed APIs in 1.22/OCP 4.9+ and will not work on this or upper versions in order to not allow users who do have not a compatible version with 4.9+ to upgrade their clusters from OCP 4.8 to 4.9 with.

Great.

> Your users need to upgrade their version installed f your operator to a compatible one with 4.9+ to upgrade the cluster safely.

Yup, that is what we expect. We worked with some Red Hatters to also ensure that we could keep the two versions on separate lines for the time being, as it's not an automatic jump (yet) from v4 to v5.

> Please, let me know if that answers your questions and concerns.

It does. Thanks!
