### ISSUE TITLE
OLM installation in `all namespaces` mode

### ISSUE THREAD

**Issue by m-yosefpor** [CrunchyData/postgres-operator#2663]
- [x] Provide a concise description of your feature request.
- [x] Describe your use case. Detail the problem you are trying to solve.
- [x] Describe how you envision that the feature would work.
- [x] Provide general information about your current PGO environment.

## Overview

Installing postgres operator with OLM only supports singleNamespace installation. It should be possible to deploy the operator in `all namespace` mode.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/47300215/131748855-3cefb5c1-27a1-4cbe-870e-cca83bb41b82.png">

## Use Case

There are many (+100) namespaces in our cluster which we want to deploy posgres on them with the help of PGO, however right now we should deploy the operator in each of the namespaces with OLM, and also for every newly created namespace, we can not use PGO without first deploying it in that namespace.

## Desired Behavior

It should be possible to deploy the operator in `all namespace` mode with OLM installation.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: `OpenShift`
- Platform Version: `4.7.0`
- PGO Version: `4.7.0`

**Comment by jkatz** [comment]
To maintain compatibility with OpenShift 3.11, we do not support all namespace mode in v4.

However, [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/) supports all namespace mode. It is available as a Certified Operator, and should be on OperatorHub.io as well (per https://github.com/k8s-operatorhub/community-operators/pull/164 and https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/178)

**Comment by m-yosefpor** [comment]
Thanks for your explanation. I installed v5 on OKD4.7, however there are no CSV (nor any operator pods consequently) created after installing the operator. Only the `Subscription` and `OperatorGroup` are created.

OLM logs:

> {"level":"error","ts":1630548725.981664,"logger":"controllers.operatorcondition-generator","msg":"Unable to find ClusterServiceVersion","request":"harbor/postgresoperator.v5.0.2","error":"ClusterServiceVersion.operators.coreos.com \"postgresoperator.v5.0.2\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n

**Comment by jkatz** [comment]
You will need to reach out to Red Hat to inquire what is happening. We have been unable to reproduce this in our OCP 4.7 environments.

**Comment by madorn** [comment]
@m-yosefpor If you are targeting installation of v5 on 4.7 in all-namespaces via the OpenShift UI, there should not be a new `OperatorGroup` created. You are targeting the pre-existing `openshift-operators` project which already contains an OperatorGroup called `global-operators`.

Happy to help if you have additional questions/issues.

**Comment by m-yosefpor** [comment]
@madorn Thanks. yes you are right, the `og` is the existing global-operators one. I assume the issue might be that we have already installed 4.7.2 postgres in some of our namespaces, and so we should clean them up before being able to install the global v5 one. Installing v5 in a specific namespace (which 4.7 is not already installed on it) works fine now.
