### ISSUE TITLE
PgBackrest latest version - packaged container

### ISSUE THREAD

**Issue by ludzzz** [CrunchyData/postgres-operator#2664]
Hi,

Currently the last package version that I found for the docker image crunchy-pgBackrest is v2.33.-2.
Is there a plan to get the v2.34 or the v2.35 of pgbackrest in crunchy docker image?

Thank you for your reply and for your work.

ps: if it's not the right place for this question, let me know.

**Comment by jkatz** [comment]
> Is there a plan to get the v2.34 or the v2.35 of pgbackrest in crunchy docker image

Yes, in an upcoming release.
