### ISSUE TITLE
My postgre-operator in hippo services does not working

### ISSUE THREAD

**Issue by farukcevik** [CrunchyData/postgres-operator#2665]
I first installed kuberenetes cluster on 3 Centos one master 2 worker nodes
then master nodes installed PGO, the Postgres Operator from Crunchy Data from https://access.crunchydata.com/documentation/postgres-operator/5.0.2/quickstart/ document everything is okey but doesn't work hippo;

$ kubectl get pods --all-namespaces
NAMESPACE           NAME                                           READY   STATUS    RESTARTS   AGE
kube-system         calico-kube-controllers-58497c65d5-vdpr7       1/1     Running   0          45m
kube-system         calico-node-cjlmn                              1/1     Running   0          45m
kube-system         calico-node-hw4d6                              1/1     Running   0          45m
kube-system         calico-node-npnql                              1/1     Running   0          45m
kube-system         coredns-78fcd69978-pp9hp                       1/1     Running   0          47m
kube-system         coredns-78fcd69978-svq5z                       1/1     Running   0          47m
kube-system         etcd-k8smaster.frkcvk.com                      1/1     Running   0          47m
kube-system         kube-apiserver-k8smaster.frkcvk.com            1/1     Running   0          47m
kube-system         kube-controller-manager-k8smaster.frkcvk.com   1/1     Running   0          47m
kube-system         kube-proxy-5mdx4                               1/1     Running   0          46m
kube-system         kube-proxy-8hvxv                               1/1     Running   0          47m
kube-system         kube-proxy-sxglp                               1/1     Running   0          46m
kube-system         kube-scheduler-k8smaster.frkcvk.com            1/1     Running   0          47m
**_postgres-operator   hippo-instance1-9h5k-0                         0/3     Pending   0          23s
postgres-operator   hippo-repo-host-0                              0/1     Pending   0          23_**s
postgres-operator   pgo-79897f84bc-wnkl6                           1/1     Running   0          3m29s 

$ kubectl get pods --namespace postgres-operator
NAME                     READY   STATUS    RESTARTS   AGE
hippo-instance1-bfx4-0   0/3     Pending   0          23m
hippo-repo-host-0        0/1     Pending   0          23m
pgo-79897f84bc-wnkl6     1/1     Running   0          24m

$ kubectl describe pods --namespace postgres-operator hippo-instance1-bfx4-0

****
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  50s (x25 over 24m)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.

$ kubectl -n postgres-operator  get all
NAME                         READY   STATUS    RESTARTS   AGE
pod/hippo-instance1-bfx4-0   0/3     Pending   0          49m
pod/hippo-repo-host-0        0/1     Pending   0          49m
pod/pgo-79897f84bc-wnkl6     1/1     Running   0          49m

NAME                      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
service/hippo-ha          ClusterIP   10.99.8.8    <none>        5432/TCP   49m
service/hippo-ha-config   ClusterIP   None         <none>        <none>     49m
service/hippo-pods        ClusterIP   None         <none>        <none>     49m
service/hippo-primary     ClusterIP   None         <none>        5432/TCP   49m

NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/pgo   1/1     1            1           49m

NAME                             DESIRED   CURRENT   READY   AGE
replicaset.apps/pgo-79897f84bc   1         1         1       49m

NAME                                    READY   AGE
statefulset.apps/hippo-instance1-bfx4   0/1     49m
statefulset.apps/hippo-repo-host        0/1     49m

**Comment by jkatz** [comment]
> 3 pod has unbound immediate PersistentVolumeClaims

Check your StorageClass setup.
