### ISSUE TITLE
Exposing api-server with ingress-nginx rule

### ISSUE THREAD

**Issue by lbartnicki92** [CrunchyData/postgres-operator#2666]
## Overview

I'm currently working on creating terminal machine, which will give access to K8s cluster with pgo operator. 
Kubectl configuration is ok. 
I started to configure pgo client. I want to set PGO_APISERVER_URL variable not with localhost, but adress of machine with ingress exposed. I'm getting Error:  Invalid Status Code: 403 with pgo client commands.
## Environment

Please provide the following details:

Platform: Kubernetes
Platform Version: v1.20.7
PGO Image Tag: postgres-operator:centos8-4.7.0
Postgres Version: crunchy-postgres-ha:centos8-13.3-4.7.0
Storage: HostPath for data

### REPRO

Provide steps to get to the error condition:

Ingress rule config:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-operator-pgo
  namespace: pgo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - postgres-operator
    secretName: operator-ingress-certs
  rules:
  - host: postgres-operator
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: postgres-operator
            port:
              number: 8443

[lbartnicki:~/k8s-code]$ kubectl describe ingresses.networking.k8s.io postgres-operator-pgo -n pgo
Name:             postgres-operator-pgo
Namespace:        pgo
Address:          10.2.240.66,10.2.240.67,10.2.240.68,10.2.240.69,10.40.240.4
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  operator-ingress-certs terminates postgres-operator
Rules:
  Host               Path  Backends
  postgres-operator
                     /   postgres-operator:8443 (10.233.81.53:8443)
Annotations:         cert-manager.io/cluster-issuer: ca-issuer
                     kubernetes.io/ingress.class: nginx
                     nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                     nginx.ingress.kubernetes.io/force-ssl-redirect: true
Events:
  Type    Reason             Age                From                      Message
  Normal  CreateCertificate  12m                cert-manager              Successfully created Certificate "operator-ingress-certs"
  Normal  Sync               12m (x2 over 12m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync               12m (x2 over 12m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync               12m (x2 over 12m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync               12m (x2 over 12m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync               12m (x2 over 12m)  nginx-ingress-controller  Scheduled for sync

[lbartnicki:~/k8s-code]$ env | grep PGO
PGO_CA_CERT=//home/lbartnicki/.pgo/pgo/client.crt
PGO_CLIENT_KEY=/home/lbartnicki/.pgo/pgo/client.key
PGO_CLIENT_CERT=//home/lbartnicki/.pgo/pgo/client.crt
PGO_NAMESPACE=pgo
PGOUSER=//home/lbartnicki/.pgo/pgo/pgouser
PGO_APISERVER_URL=https://postgres-operator:443

### EXPECTED

1. PGO Client working with operator

### ACTUAL

1. 403 Errors
[lbartnicki@osx05825.pzu.pl:~/k8s-code]$ pgo show cluster --all
Error:  Invalid Status Code: 403

## Logs

Ingress Controller logs:

`
10.2.240.126 - admin [02/Sep/2021:12:04:36 +0000] "POST /showclusters HTTP/1.1" 308 164 "-" "Go-http-client/1.1" 218 0.000 [pgo-postgres-operator-8443] [] - - - - 59bb477c67f55a0001f2634a74d7d4d1
10.2.240.126 - admin [02/Sep/2021:12:04:39 +0000] "POST /showclusters HTTP/1.1" 308 164 "-" "Go-http-client/1.1" 218 0.000 [pgo-postgres-operator-8443] [] - - - - 2dabeb98699f89cbb3875957fafb3edc
10.2.240.126 - - [02/Sep/2021:12:04:39 +0000] "POST /showclusters HTTP/1.1" 403 39 "http://postgres-operator:80/showclusters" "Go-http-client/1.1" 321 0.012 [pgo-postgres-operator-8443] [] 10.233.81.53:8443 39 0.012 403 10c15fe6bb199fa4c3d81346bd101658
10.2.240.126 - admin [02/Sep/2021:12:05:41 +0000] "POST /showclusters HTTP/1.1" 403 39 "-" "Go-http-client/1.1" 325 0.011 [pgo-postgres-operator-8443] [] 10.233.81.53:8443 39 0.011 403 bf3ddc2984699026d4b274a6b81ad4c9
10.2.240.126 - admin [02/Sep/2021:12:18:32 +0000] "POST /showclusters HTTP/1.1" 403 39 "-" "Go-http-client/1.1" 325 0.011 [pgo-postgres-operator-8443] [] 10.233.81.53:8443 39 0.011 403 fc5e1f7e897ccd7561639d4a07ea16b0
`

## Additional Information

[lbartnicki:~/k8s-code]$ pgo show cluster --all --disable-tls
Error:  Post "https://postgres-operator:443/showclusters": x509: certificate signed by unknown authority

**Comment by andrewlecuyer** [comment]
Hi @lbartnicki92!

Since this issue involves the `pgo` CLI and API server for an older version of Crunchy Postgres for Kubernetes, I am proceeding with closing this issue.

If you have any additional questions - or if you would like to further discuss the latest `pgo` CLI for Crunchy Postgres for Kubernetes v5 (documentation can be found [here](https://github.com/CrunchyData/postgres-operator-client)) - please feel free to either submit a new issue with your latest use-case/details, or you can also reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).

And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

- https://access.crunchydata.com/documentation/postgres-operator/latest/
- https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/v4tov5/
