### ISSUE TITLE
How to manage PGO client RBAC? PGO-client AUTH integrated with K8S/Openshift?

### ISSUE THREAD

**Issue by sunofsparda** [CrunchyData/postgres-operator#2674]
Hello PGO team

Do you have any thoughts on integrating PGO-client AUTH with K8S/Openshift?

Let me describe a bit our problem and infra. We have installed PGO in Openshift cluster
We have a bunch of clients which are using Openshift platform. Some of them wants to use PGO, therefore we should grant access to PGO (apply labels on namespace) and give a pgouser account
Next step is to give clients PGO-client container.
Here we faced an issue on how to manage RBAC permissions for pgo-client. It would be a big deal to manually create pgouser for each openshift client.
Do you have any thought or (automated) solution on how to manage a huge scope (10+) of pgoclients with it's own set of permissions?

**Comment by sunofsparda** [comment]
Or do you have any best practice on how to manage a huge scope (40-100+) of clients\users?

**Comment by sunofsparda** [comment]
Perhaps there is an enterprise solution for this purpose?

**Comment by jkatz** [comment]
@sunofsparda Would you mind sending a note to info@crunchydata.com with some more information about your specific use-case that requires this and what you are trying to accomplish? Thanks!

**Comment by benjaminjb** [comment]
Closing this as stale / conversation continuing elsewhere.
