### ISSUE TITLE
Restore pgcluster from S3 backup to another Kubernetes cluster

### ISSUE THREAD

**Issue by boris-lenzinger** [CrunchyData/postgres-operator#2679]
**Context** : I have an asynchronous cluster with a pgbackrest whom storage is on S3. I would like to restore this PGCluster on another Kubernetes Cluster.

I wrote a script to automate the actions. The script performs the following actions:
- Backup the PGCluster on cluster 1 (using pgo)
- Identify the latest backup and keep its reference
- Change context to cluster 2
- Loads the pgo's environment related to the target cluster
- Creates a restoration namespace
- Runs pgo update to allow the creation of a cluster in the namespace
- Creates a secret with the S3 credentials named as the one created for the original cluster. The secret is named as <cluster_name>-backrest-repo-config and works well for the other cluster
- Creates a PVC named <cluster-name>-pgbr-repo else an error is popped, even if the PVC is not used (this is a known issue and reported in #2285)
- Creates the cluster from the previous. The cluster has the exact same name as the original one. This the  command used to restore the cluster:
```bash
pgo create cluster ${cluster_name} \
  --namespace=${target_namespace} \
  --replica-count=2 \
  --pgbadger --pgbouncer --pgbouncer-replicas=2 \
  --restore-from=${cluster_name} \
  --pgbackrest-storage-type=s3 \
  --pgbackrest-s3-bucket=${s3_bucket_name} \
  --pgbackrest-s3-endpoint=${s3_endpoint} \
  --pgbackrest-s3-region=${s3_region} \
  --pgbackrest-s3-key=${s3_key} \
  --pgbackrest-s3-key-secret=${s3_key_secret} \
  --pgbackrest-s3-ca-secret=${cluster_name}-backrest-repo-config \
  --restore-opts="--type time --target=${last_full_target}"
```
The pgcluster object is created in the namespace but no pod is started and no restoration process is initiated. When I checked the trace in the operator, I found this one which is the only one related to my cluster so I guess this might be linked to the issue:

```
time="2021-09-08T08:58:36Z" level=debug msg="setting disable fsgroup to false"
    func="internal/config.(*PgoConfig).DisableFSGroup()"
    file="internal/config/pgoconfig.go:889"
    version=4.7.1

time="2021-09-08T08:58:36Z" level=debug
  msg="[123 34 114 117 110 65 115 78 111 110 82 111 111 116 34 58 116 114 117 101 44 34 102 115 71 114 111 117 112 34 58 50 54 125]"
  func="internal/operator.GetPodSecurityContext()"
  file="internal/operator/common.go:196"
  version=4.7.1

time="2021-09-08T08:58:36Z" level=debug msg="GetPodAnitAffinity with clusterName=[cluster-asynchrone]"
  func="internal/operator.GetPodAntiAffinity()"
  file="internal/operator/clusterutilities.go:720"
  version=4.7.1
                "podAntiAffinity": {
                    "preferredDuringSchedulingIgnoredDuringExecution": [
                        {
                            "weight": 1,
                            "podAffinityTerm": {
                                "labelSelector": {
                                    "matchExpressions": [
                                        {
                                            "key": "vendor",
                                            "operator": "In",
                                            "values": [
                                                "crunchydata"
                                            ]
                                        },
                                        {
                                            "key": "pg-pod-anti-affinity",
                                            "operator": "Exists"
                                        },
                                        {
                                            "key": "pg-cluster",
                                            "operator": "In",
                                            "values": [
                                                "cluster-asynchrone"
                                            ]
                                        }
                                    ] ]
                                },
                                "topologyKey": "kubernetes.io/hostname"
                            }
                        }
                    ]
                }
time="2021-09-08T08:58:36Z" level=error msg="strconv.Atoi: parsing \"\": invalid syntax"
     func="internal/controller/pgcluster.(*Controller).processNextItem()"
     file="internal/controller/pgcluster/pgclustercontroller.go:127"
     version=4.7.1

time="2021-09-08T08:58:39Z" level=debug
  msg="Controller Manager: Now reconciling RBAC in namespace pgouser2"
  func="internal/controller/manager.(*ControllerManager).reconcileRBAC()"
  file="internal/controller/manager/rbac.go:43"
  version=4.7.1
```

This Atoi failed conversion has no context and might be related to an internal mecanic while transforming some yaml to json or json to objects so sounds like "very internal" issue.

Has anyone met this issue ? How could you solve it ?

**Comment by jkatz** [comment]
You're probably failing here:

https://github.com/CrunchyData/postgres-operator/blob/f1961a93ec746216884d2b8c1a23fc6f9a4f62d3/internal/operator/backrest/repo.go#L227-L231

Likely due to missing Annotations on the restore Secret.

**Comment by boris-lenzinger** [comment]
@jkatz you nailed it ! Now I see that I need more configuration parameters. I will investigate on those. Thank you !

**Comment by jkatz** [comment]
@boris-lenzinger I'd be curious to see the final result if it is shareable.

**Comment by boris-lenzinger** [comment]
@jkatz It is for a customer but I guess this is completely shareable. I'll post the result in this issue if I'm allowed to.
