### ISSUE TITLE
invalid storage type

### ISSUE THREAD

**Issue by echel0n** [CrunchyData/postgres-operator#2683]
I'm using v4.7.0 and trying to create a backup schedule that uses S3 storage, this was working previously, now it comes back with `Error: invalid storage type: choices are: posix`

I have backrest_aws_s3 config options all setup properly, again, this was working previously, what am I missing here?

**Comment by jkatz** [comment]
Is S3 storage set up for the Postgres cluster?

https://github.com/CrunchyData/postgres-operator/blob/ea2514c4e348637c0822b61772a539836699c2c5/internal/apiserver/common.go#L121-L129

That error indicates that the values in the pgcluster spec are likely empty.

**Comment by echel0n** [comment]
Found the issue, v4.6.0 introduced a breaking change in the way S3 storage type was specified, thanks for helping me into the right direction!
