### ISSUE TITLE
pgo delete cluster --> 401 auth failed since 3.0

### ISSUE THREAD

**Issue by xorpierre** [CrunchyData/postgres-operator#269]
Hi,
I really tried everything to fix this myself but I am stuck, since 3.0, using 3.1 now, I can't delete cluster anymore, I get 401 auth error, everything else works.

I checked everything, the apiserver secret is there and in correct namespace, the .pgouser file is there with the same user:pws as apiserver has stored (using default examples anyway).

Apiserver logs just shows this

`time="2018-06-29T10:05:26Z" level=error msg="Authn Failed DeleteCluster username=[username]\n"
time="2018-06-29T10:13:11Z" level=debug msg="clusterservice.DeleteClusterHandler map[name:test]\n"
time="2018-06-29T10:13:11Z" level=debug msg="version param was [3.1]"
time="2018-06-29T10:13:11Z" level=debug msg="delete-data param was [false]"
time="2018-06-29T10:13:11Z" level=debug msg="delete-backups param was [false]"
time="2018-06-29T10:13:11Z" level=debug msg="Authn Attempt DeleteCluster username=[testuser]\n"
time="2018-06-29T10:13:11Z" level=info msg=" BasicAuthzCheck pgoadmin DeleteCluster false\n"
time="2018-06-29T10:13:11Z" level=error msg="Authn Failed DeleteCluster username=[testuser]\n"` 

any suggestion?
using all default/example settings

**Comment by jmccormick2001** [comment]
I'll look into this today.

**Comment by xorpierre** [comment]
I am not sure if delete does check for auth differently than other commands but I'd assume that if it was a auth issue then I couldn't do anything with pgo, it wouldn't just fail at the delete command.

**Comment by jmccormick2001** [comment]
weird indeed, I just tested it and it seems to work for me..I'm assuming this is a fresh 3.1 install and that no existing pgo configmaps were present on the system prior?

**Comment by xorpierre** [comment]
where would they be stored? I just did a lot of test deploys and in between downloaded the latest pgo version (started with 2.9 few months ago).
I am not compiling the client myself anyway

**Comment by jmccormick2001** [comment]
there are 2 files that determine the access, pgouser and pgorole, both of those are stored in a Secret that is deployed along with the operator on the Kube server, that secret is apiserver-conf-secret

the pgoadmin 'role' is found in pgorole, you should see a DeleteCluster permission on that role.

The 'username' user ID is tied to that pgoadmin role in the pgouser file, you should see an 
entry in there like this for example:
username:password:pgoadmin

I retested with the 3.1 pre-built binaries and images on Dockerhub just now on a clean Kube system and it seems to work as well for me.

**Comment by xorpierre** [comment]
ok I think I found the culprit now...this is my pgorole file (I got this from git)

`$ cat conf/apiserver/pgorole 
pgoadmin: ShowCluster, CreateCluster, TestCluster, ShowBackup, DeleteBackup, CreateBackup, Label, Load, CreatePolicy, DeletePolicy, ShowPolicy, ApplyPolicy, ShowPVC, CreateUpgrade, ShowUpgrade, DeleteUpgrade, CreateUser, DeleteUser, User, Version, CreateIngest, ShowIngest, DeleteIngest, CreateFailover

pgoreader: ShowCluster, TestCluster, ShowBackup, ShowPolicy, ShowPVC, ShowUpgrade, Version`

I never bothered to check that, figured the admin role has everything important...maybe this was changed around 2.9 or something? because I know this worked fine in 2.9

**Comment by jmccormick2001** [comment]
no problem, I think it did change back there in a previous release as I was implementing the operator rbac, good to hear resolution on this one.
