### ISSUE TITLE
image not found 

### ISSUE THREAD

**Issue by bilemedimkq** [CrunchyData/postgres-operator#2699]
![image](https://user-images.githubusercontent.com/42588052/133563936-493d5290-b6e3-4d02-8ed1-62ecb2b0599a.png)

I installed pgo operator and created a test cluster. but i am getting error.

PGO: 4.7.2
Rancher: 2.6.0

**Comment by ludzzz** [comment]
Look like you are not using the right image tag for the pgbackrest.
when looking at the last version they have: https://access.crunchydata.com/documentation/crunchy-postgres-containers/4.7.2/container-specifications/crunchy-pgbackrest/
your image should be:
```
registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
```

**Comment by bilemedimkq** [comment]
It might be true but I didn't change anything. I only created cluster, I didn't change the default settings of pgo and while I was creating cluster, I didn't give any command like "use this image"

**Comment by jkatz** [comment]
Please see #2648 for commentary.
