### ISSUE TITLE
Clarify usage on GCE

### ISSUE THREAD

**Issue by gmile** [CrunchyData/postgres-operator#27]
According to Readme: 

> Openshift Origin 1.5.1+ or Openshift Container Platform 3.5

...it is required to have Kubernetes installed with OpenShift. Does that mean that `postgres-operator` will not work over Google Cloud Platform (specifically Google Container Engine)? Shouldn't operator be cloud-provider agnostic?

**Comment by prlaurence** [comment]
Thank you for the question. The indicated OpenShift version requirements are only applicable to deploying in connection with OpenShift Container Platform.  The Postgres Operator runs on core Kubernetes - and thus presumably should run on Google Cloud Platform (though not sure it has been specifically tested).  We will update the Readme to clarify.  Does that address your question?

**Comment by gmile** [comment]
@prlaurence thank you and yes, that answers my question. This makes sense now. Feel free to close the issue now or when the readme is updated.

**Comment by prlaurence** [comment]
Thanks @gmile. Please let us know if you have any issues running on GCE.
