### ISSUE TITLE
ccp_nodemx_data_disk pq: value "18446744073709551615" is out of range for type bigint

### ISSUE THREAD

**Issue by douggutaby** [CrunchyData/postgres-operator#2704]
Hi,

We have an OpenShift cluster with CrunchyData postgres-operator with enabled prometheus metrics. In the export container we have found the following error:
time="2021-09-20T07:27:57Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_data_disk pq: value \"18446744073709551615\" is out of range for type bigint" source="postgres_exporter.go:1356"

I found that the monitor.fsinfo() function provides this data. For fsinfo('/') I got proper data, but for fsinfo('/pgdata') I got the number is too big for bigint like above.
We use rook-ceph for persistent volumes. Probably ceph cannot provide this data or reach a limit, maybe selinux didn't allow to collect something.

## Environment

- Platform: OpenShift
- Platform Version: 4.7.0
- PGO Image Tag: centos8-12.8-4.7.2
- Postgres Version: 12
- Storage: rook-ceph

### REPRO

Create cluster with metrics enabled.

### EXPECTED

No error, metrics collection.

### ACTUAL

ccp_nodemx_data_disk pq: value "18446744073709551615" is out of range for type bigint

## Additional Information

Recently we upgraded our postgres operator from 4.5.1 to 4.7.2 but I found the same in the old logs as well.

**Comment by jkatz** [comment]
@douggutaby You should open up this issue on the [pgnodemx](https://github.com/CrunchyData/pgnodemx) project.

**Comment by douggutaby** [comment]
Done
https://github.com/CrunchyData/pgnodemx/issues/3
Thanks

**Comment by douggutaby** [comment]
I can see the operator 4.7.4  uses pgnodemx 1.0.6, but I cannot see this release in the pgnodemx project. So, I don't know my issue fixed or not.
Can you confirm this issue fixed in 4.7.4?
Thanks

**Comment by andrewlecuyer** [comment]
@douggutaby PGO `v4.7.4` has version `1.2.0` of `pgnodemx`, which should include the change/fix you requie:

```bash
$ podman run -it registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-12.9-4.7.4 dnf list installed pgnodemx*
...
pgnodemx12.x86_64                                   1.2.0-0Crunchy.el8.centos                                    @crunchypg12
```

However, please note that you will also need to run `ALTER EXTENSION pgnodemx UPDATE;` as a superuser to update the extension once you have upgraded to PGO v4.7.4 (and therefore the new version of `pgnodemx`:

```bash
postgres=# ALTER EXTENSION pgnodemx UPDATE;
ALTER EXTENSION
```

**Comment by douggutaby** [comment]
Thank you @andrewlecuyer, I was wrong, it is the version of the extension:
"The pgnodemx extension is now at version 1.0.6"
I will check 4.7.4 on our test cluster and run the update command.
