### ISSUE TITLE
pgbadger

### ISSUE THREAD

**Issue by k1ng440** [CrunchyData/postgres-operator#272]
How to add pgbadger to postgres container?

**Comment by jmccormick2001** [comment]
today you would have to add that container spec into the deployment-cluster-1.json template and deploy the operator using that, the downside is that any new cluster you create would have pgbadger added into it, the upside is that you could go ahead and roll out pgbadger without waiting for this to be added as an option into the operator.  I like the idea of adding badger however and will add it to the next release milestone.

**Comment by jmccormick2001** [comment]
merged into pre32 this feature, with the upcoming 3.2 release if you pass 'pgo create cluster --pgbadger' or set the Badger flag globally inside pgo.yaml, the crunchy-pgbadger sidecar container will be added into each cluster postgres pod.

**Comment by esatterwhite** [comment]
Is this at all possible using the kubernetes Crds that ship with the operator? Or only the cli? And if only the cli, can it set up pgbadger on an existing cluster that was created using the kubernetes resources?
