### ISSUE TITLE
Set my own passwords for a cluster.

### ISSUE THREAD

**Issue by kevinlmadison** [CrunchyData/postgres-operator#2724]
In V5 currently it seems that passwords for a cluster are generated an put into secrets automatically. We have specific requirements around authentication in our organization and would like to know if there is some way of setting passwords manually as was possible in previous versions of the operator.

**Comment by jkatz** [comment]
- What are the requirements (at least generally speaking)?
- How are the passwords disseminated once they are set?

**Comment by kevinlmadison** [comment]
We store our passwords in a key management service and they are injected via sidecar into pods that require them.
In the previous version of PGO we would create our passwords ourselves, then run jobs against the postgres clusters to create our dbs and set passwords.
With V5 we have the convenience of being able to create users, DBs, and set permissions directly with the manifest but the password is not created by us and is stored in a secret.
We need to be able to control the legal characters and length of the password.

**Comment by kevinlmadison** [comment]
@jkatz Is there any kind of workaround for this even it's not strictly supported? This has turned out to be a breaking change for us, but we would very much like to upgrade to v5 as it greatly simplifies our database setup process and gives us access to timescaleDB out of the box.

**Comment by jkatz** [comment]
I linked the issue incorrectly, but fddc90e0f5 covers how to do this.

**Comment by kevinlmadison** [comment]
@jkatz Hey I just wanted to follow up in case anyone reads this but I can confirm that the method linked does work for me after I automated the process with ansible. For some reason when I was doing it by hand something must have been getting mangled.
Thank you again for you quick and very helpful response! You're always on point!
