### ISSUE TITLE
Resize PVC

### ISSUE THREAD

**Issue by Marvalero** [CrunchyData/postgres-operator#273]
I got this error:
```
Thu Jul  5 09:11:16 UTC 2018
2018-07-05 05:11:16 EDT [64]: [1-1] user=,db=,app=,client=FATAL:  could not write lock file "postmaster.pid": No space left on device
Thu Jul  5 09:11:16 UTC 2018 INFO: PostgreSQL is shutting down. Exiting..
```

Is there a way to resize my pvc? I use gke setup

My pvc is just 1G big, I would like it to be at least 10G
```
my-postgres           Bound     pvc-5598d486-760b-11e8-8c11-42010a840127   1Gi        RWO            standard       13d
```

**Comment by jmccormick2001** [comment]
the operator today will not perform the PVC/PV resize for you, however the most recent versions of Kube I believe do support this feature from kube directly but I will need to investigate more.

**Comment by jmccormick2001** [comment]
I think I misread your question, yes, you can increase the volume claim size by modifying the pgo.yaml configuraiton file and redeploying the operator, that way it will create the PVC sizes as you specify.
