### ISSUE TITLE
PGO v5 install failing on OpenShift 4.7 Airgap environment

### ISSUE THREAD

**Issue by Shrivastava-Varsha** [CrunchyData/postgres-operator#2734]
Hi, I am trying to install PGO v5 on OpenShift 4.7 Airgap environment, however the operator pod is failing to start with below error logs

time="2021-09-28T11:51:34Z" level=debug msg="debug flag set to true" file="cmd/postgres-operator/main.go:62" func=main.main version=5.0.2-0
I0928 11:51:35.524964       1 request.go:655] Throttling request took 1.036625493s, request: GET:https://172.30.0.1:443/apis/controlplane.operator.openshift.io/v1alpha1?timeout=32s
time="2021-09-28T11:51:41Z" level=info msg="metrics server is starting to listen" addr=":8080" file="sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:130" func="log.(*DelegatingLogger).Info" version=5.0.2-0
I0928 11:51:45.537398       1 request.go:655] Throttling request took 1.346426987s, request: GET:https://172.30.0.1:443/apis/cloudcredential.openshift.io/v1?timeout=32s
panic: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
goroutine 1 [running]:
main.assertNoError(...)
github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:39
main.isOpenshift(0x1aead90, 0xc000432280, 0xc00053efc0, 0xc000400050)
github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:110 +0x1a5
main.addControllersToManager(0x1aead90, 0xc000432280, 0x1b04eb8, 0xc0002a41c0, 0x1b04eb8, 0xc0002a41c0)
github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:96 +0xfb
main.main()
github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:80 +0x2d4

Seems itss not able to figure out this is an OpenShift environment.
I looked at the code here : https://github.com/CrunchyData/postgres-operator/blob/master/cmd/postgres-operator/main.go#L110

**Comment by jkatz** [comment]
>  unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request

Seems like a transient error. I'd recommend trying again. If the problem persists, I recommend working with your administrator on this.
