### ISSUE TITLE
Kubectl describe instance and output "Readiness probe failed: HTTP probe failed with statuscode: 503"

### ISSUE THREAD

**Issue by sertceps** [CrunchyData/postgres-operator#2736]
> My native language is not English
> I hope there's no offense in tone.
> I am sorry if any inappropriate remarks.

Hi,
When I using `kubectl describe pods stars-instance3-57ss-0` , it was an warnning in the part of **Events** .

Like this:

Events:
......
  **Warning  Unhealthy  49m (x4 over 49m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503**

It seems that all the instances have the warning. But, the application connection is working well.

Does that make any difference?

I don't know should I worry about the warning.

> Thanks to anyone for their answers.

**Comment by jkatz** [comment]
There may be something in your environment that is interfering with the readiness checks, such as the inability to communicate with the Kubernetes API. I would recommend checking there first. Patroni, which is managing the readiness probe, will also return a 503 if there is an undetermined condition.

The likelihood is that this a transient error and will resolve itself, or a Kubernetes administrator will do something to correct it.

**Comment by sertceps** [comment]
> There may be something in your environment that is interfering with the readiness checks, such as the inability to communicate with the Kubernetes API. I would recommend checking there first. Patroni, which is managing the readiness probe, will also return a 503 if there is an undetermined condition.
> 
> The likelihood is that this a transient error and will resolve itself, or a Kubernetes administrator will do something to correct it.

I get it. Thanks very much.O(∩_∩)O
