### ISSUE TITLE
good replicas not listed in failover query

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#274]
After upgrading the operator from 2.6 to 3.1, 
The following command did not the replica deployment. However, it was listed when using 2.6 operator.
pgo failover --query <cluster>

**Comment by jmccormick2001** [comment]
I've updated the documentation (merged in to pre32) for upgrading to 3.2, essentially it is this logic:

for primary Deployments apply this label: primary=true
        ....
        kubectl label deploy mycluster primary=true
        ....
        or for replica Deployments:
        ....
        kubectl label deploy mycluster-xxxx primary=false
