### ISSUE TITLE
PGO v5 : repo-host statefulset uses "default" service account

### ISSUE THREAD

**Issue by Shrivastava-Varsha** [CrunchyData/postgres-operator#2749]
Hi,

I tried to deploy PGO v5 on OpenShift 4.7. I noticed that the repo-host statefulset uses "default" service account.
Is this as per design ? Or is there a way to pass serviceAccount name in the CR for this statefulset?
I see 3 service accounts (pgo, clustername-instance and clustername-pgbackrest) created and in use by other resources except repo-host.

Regards.

**Comment by jkatz** [comment]
What is the use case to not use the default?

**Comment by jkatz** [comment]
This Pod does not need any elevated privileges, so the [default serviceaccount](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) is fine.

Given no use case is provided on why this is may not be the case, I am closing this issue.
