### ISSUE TITLE
Document upgrade steps for 2.6 to 3.1

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#275]
Please add postgres-operator upgrade steps for 2.6=>3.1
Feel free to add other combinations like
2.6=>3.0
2.6=>3.1
3.0=>3.1

**Comment by jmccormick2001** [comment]
@pmereddy1  are the latest docs sufficient for this?

**Comment by pmereddy1** [comment]
Yes. Thanks
