### ISSUE TITLE
Allow to get S3 credentials from kubrenetes secret

### ISSUE THREAD

**Issue by JrCs** [CrunchyData/postgres-operator#2752]
It will be useful to get the S3 credentials (for pgBackRest) from kubernetes secret instead of specifying them in the postgressCluster manifest.

With that the s3 secret can be create externally (with tools like vault csi provider).

**Comment by jkatz** [comment]
You can get them from the Secret, and that is the recommended way. This is described both [in the documentation](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/#using-s3) as well as demonstrated [in the examples repo](https://github.com/CrunchyData/postgres-operator-examples/tree/main/kustomize/s3).

You can reference the Secret you want to use in the [configuration block](https://access.crunchydata.com/documentation/postgres-operator/v5/references/crd/#postgresclusterspecbackupspgbackrestconfigurationindexsecret):

https://github.com/CrunchyData/postgres-operator-examples/blob/b77a4972d5f6ec37b074b8e8793b99b186084541/kustomize/s3/postgres.yaml#L21-L22
