### ISSUE TITLE
wal retention

### ISSUE THREAD

**Issue by bilemedimkq** [CrunchyData/postgres-operator#2757]
Hello. I use postgres operator v5. It looks like WAL logs of the database growing rapidly. Can we apply retention to WAL logs? Like storing WAL logs from 10 days ago and deleting the rest?

**Comment by haf** [comment]
You may be experiencing a replica that has desynced; the WAL might grow because it's keeping to-be-synchronised transactions.

**Comment by jkatz** [comment]
2048 connections is a lot, which leads me to believe you're pushing a lot of data through.

I think that @haf may be correct that your replicas are not keeping up with your throughput. Based upon latency as well as your current pgBackRest configuration (which does not appear to have any of the performance settings tweaked), you may not be able to push WAL fast enough to your repository.

Additionally, it appears your backup retention policy is only on full backups, but you're taking incremental backups every 10 minutes, so the amount of backups you have will grow infinitely without being pruned. I'm unsure why you need to take incremental backups so frequently either, but I do not know what your problem domain is.

Anyway, this does not appear to be a bug but rather an operational [support](https://access.crunchydata.com/documentation/postgres-operator/v5/support/) issue. There is guidance in here to get you started on resolving it.

**Comment by bilemedimkq** [comment]
Hi @jkatz !

No 2048 connection, I made it for a try. There are 20-30 connections on average. The database is about 2-3 gb in size.

However, I found a few interesting things.

I am using longhorn to manage storage. The replica on longhorn looks like ~14 gb. 
![image](https://user-images.githubusercontent.com/42588052/136256866-9020af3b-6eab-4b43-8e3e-41e3d0fcc26e.png)
But when I go into it and check it's only 2gb. There is a problem with longhorn, I will look into it.

![image](https://user-images.githubusercontent.com/42588052/136257122-89eae5e4-2b89-492b-a16b-b7c3414bcc01.png)

---

![image](https://user-images.githubusercontent.com/42588052/136257432-995894b8-6e61-4ff4-b741-12e9c9e3e268.png)

When I checked the repo0 host (local pgbackrest), I saw that it was indeed 20gb in size. and it's all made up of wal files. Can we apply retention to wal files as in backups?

**Comment by andrewlecuyer** [comment]
Sorry to hear you are having an issue.

This does not sound like a bug in the operator, but rather a configuration issue. Earlier in this thread a community member suggested some potential solutions.

My colleague tried to provide some more context on how the incremental backup configuration may be producing the observed WAL here:

https://github.com/CrunchyData/postgres-operator/issues/2758#issuecomment-939160817

For additional information on setting up backups, the tutorials section in the documentation may be a good place to start:

- https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/backups/
- https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/backup-management/

If you would like to join the [postgres operator mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join) and submit the details of your configuration there, a community member or a member of our team may be able to help you troubleshoot the details of the situation.

Of course if you are interested in commercial / production support, please reach out to [info@crunchydata.com](mailto:info@crunchydata.com).

We will leave this issue open to the extent there are any more details of your configuration you can share, but generally prefer to use the email list for community assistance.

**Comment by benjaminjb** [comment]
We haven't heard back directly on this issue, so I'm going to close it out. If you want to talk more about this issue, feel free to reopen or go to our [Discord](https://discord.gg/eBb65KS2Xg) to keep the conversation going.
