### ISSUE TITLE
Issues are not resolved but they are marked as 'closed'

### ISSUE THREAD

**Issue by bilemedimkq** [CrunchyData/postgres-operator#2762]
I opened 2 issues, these issues marked as "closed" without closed. Even though, I wrote answers and its been a while since the issues are opened, these issues are still not moved to "open" position. Can you please deal with this situation?

https://github.com/CrunchyData/postgres-operator/issues/2758 
https://github.com/CrunchyData/postgres-operator/issues/2757

**Comment by faust64** [comment]
> Opening issues asking to open up other issues is generally not considered a best practice to get answers


You're funny.

What about closing issues, such as #2757. Without an answer, nor a solution?
