### ISSUE TITLE
Can a cluster restore from local file generated by other clusters?

### ISSUE THREAD

**Issue by sertceps** [CrunchyData/postgres-operator#2763]
> My native language is not English
> I hope there's no offense in tone.
> I am sorry if any inappropriate remarks.

Hi, I am using PGO version 5. 
And I want to know, if I migrated the database to the new machine, can the new cluster restore from folder( or backup) generated by the old cluster?

Or is there a good way to do that?

> Thanks to anyone for their answers.

**Comment by jkatz** [comment]
The documentation provides examples for how this can be done:

- [Migrating Data Volumes](https://access.crunchydata.com/documentation/postgres-operator/v5/guides/data-migration/)
- [Disaster Recovery & Cloning](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/)
