### ISSUE TITLE
Steps to upgrade from PSQL 13 to 14 with PGO 5.0

### ISSUE THREAD

**Issue by clrxbl** [CrunchyData/postgres-operator#2766]
I have a PostgreSQL 13.4 cluster deployed using PGO 5.0.3 on an on-premise Kubernetes cluster. I noticed 5.0.3 introduced support for PostgreSQL 14 but I've been unable to find any documentation related to major Postgres version updates for PGO 5.0.

What are the advised upgrade steps to take for upgrading my current PostgreSQL 13 cluster to 14 without any data loss?

**Comment by jkatz** [comment]
Presently the best path forward is to use [`crunchy-upgrade`](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/examples/administration/upgrade/).

An upcoming release of PGO will make the major upgrade process automatic.

**Comment by jkatz** [comment]
Added in #2853 and will be available in v5.1
