### ISSUE TITLE
pgbackrest: GCS with Workload Identity

### ISSUE THREAD

**Issue by haf** [CrunchyData/postgres-operator#2768]
I would like pgbackrest to use the ambient / metadata server credential set through Workload Identity. How may I configure this?

https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#using_from_your_code

**Comment by jkatz** [comment]
#2368 is for v4. v5 came with GCS support since it became GA.

I would recommend trying out the `auto` option on the [`repoN-gcs-key-type`](https://pgbackrest.org/configuration.html#section-repository/option-repo-gcs-key-type). I have not tried it out myself yet, but that seems geared towards the automatic authentication from workload identities.

**Comment by haf** [comment]
Where's the Dockerfile for the exporter? Can't google my way to it, nothing in docs, nothing on hub.docker.com, URL not requestable, I find only shell scripts in this repo...?

**Comment by haf** [comment]
Solution: use `auto` like described above, with `pgBackRest  pgBackRest 2.35` (ensure this version); and make sure you have the bindings between the GSA and KSA set properly.

**Comment by pere3** [comment]
> I got it to work! 😁 — a few moving parts here.
> 
> It would be great if the CRD let me annotate the created service accounts; right now, I have to do this:
> 
> ```
> .PHONY: annotate_sa
> annotate_sa:
> 	for pod in pgbackrest instance ; do \
> 		kubectl annotate serviceaccount \
> 			--namespace $(NS) $(CLUSTER)-$$pod \
> 			iam.gke.io/gcp-service-account=app-$(CLUSTER)-pg@XXX-XXX.iam.gserviceaccount.com ; \
> 	done
> ```



> I got it to work! 😁 — a few moving parts here.
> 
> It would be great if the CRD let me annotate the created service accounts; right now, I have to do this:
> 
> ```
> .PHONY: annotate_sa
> annotate_sa:
> 	for pod in pgbackrest instance ; do \
> 		kubectl annotate serviceaccount \
> 			--namespace $(NS) $(CLUSTER)-$$pod \
> 			iam.gke.io/gcp-service-account=app-$(CLUSTER)-pg@XXX-XXX.iam.gserviceaccount.com ; \
> 	done
> ```

@jkatz 
i am sorry for bringing this up, but can't find a way to annotate ServiceAccount through CRD on v5.1.1 - there is still no way on doing so?

we are using gitops paradigm with argocd, so any modification done through kubectl is against our policies.

**Comment by jmartin127** [comment]
If it's helpful to anyone, the proper service account to annotate is the one named `<name>-instance` in the same namespace where your `PostgresCluster` resource resides.  For example:

```
kubectl -n <your-namespace> annotate serviceaccount <releas-name>-instance \
    iam.gke.io/gcp-service-account=<gsa>@<your-project>.iam.gserviceaccount.com
```

There are some other pre-requisites to this that are standard workload identity configuration and well documented, but knowing which service account to annotate here is crucial and not well documented.

**Comment by haf** [comment]
@jkatz Any way to set annotations for the SA in the manifests?
