### ISSUE TITLE
Provide a way to specify node-labels for primary and replica pods globally

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#277]
Please add the capability to specify node-labels for primary and replica pods globally in pgo.yaml

**Comment by jmccormick2001** [comment]
merged into develop branch, updated docs, now there is PrimaryNodeLabel and ReplicaNodeLabel settings in pgo.yaml, if these are set, they can be used to specify node labels globally when creating 
clusters, users can still override these with a command flag if they want.
