### ISSUE TITLE
PG11 images: how to rebuild older releases?

### ISSUE THREAD

**Issue by jansmets** [CrunchyData/postgres-operator#2787]
Hi
I'm new to PGO(5) and exploring some possible options. 
I'm running a self-hosted version of gitlab and that version is currently only compatible with PG10/PG11. 
I understood those images have been removed from the Crunchy Developer Portal. 

PGO5 lists these PG images as compatible :

```
https://access.crunchydata.com/documentation/postgres-operator/5.0.3/references/components/
COMPONENT | VERSION | PGO VERSION MIN. | PGO VERSION MAX.
crunchy-postgres | 14.0 | 5.0.3 | 5.0.3
crunchy-postgres | 13.4 | 5.0.3 | 5.0.3
crunchy-postgres | 12.8 | 5.0.3 | 5.0.3
crunchy-postgres | 11.13 | 5.0.3 | 5.0.3
crunchy-postgres | 10.18 | 5.0.3 | 5.0.3
```

Are there any instructions or hints on how to rebuild such a PG11 image? 

https://access.crunchydata.com/documentation/crunchy-postgres-containers/5.0.3/contributing/building/
mentions https://api.developers.crunchydata.com/downloads/repo/rpm-centos/postgresql11/crunchypg11.repo
But that repo/file is not available any more.

Given that the CrunchyData RPM package repo for PG11 are offline too I'm not sure that rebuilding a PG11 image can even be done.
Can I perhaps install the official upstream PG11 packages side-by-side to a more recent release , but maybe extensions are required too (pgnodemx, pg_cron...)

Thanks in advance

**Comment by jkatz** [comment]
There are several PostgreSQL versions made available in the Developer Portal as part of the [Developer Portal Program](https://www.crunchydata.com/developers/terms-of-use). All images are available in the Customer Portal.
