### ISSUE TITLE
Implement PodDisruptionBudgets for PostgreSQL Clusters

### ISSUE THREAD

**Issue by sharkymcdongles** [CrunchyData/postgres-operator#2788]
## Overview

Currently there is no way to implement [PodDisruptionBudgets](https://kubernetes.io/docs/tasks/run-application/configure-pdb/).

These are super useful for stateful workloads in the event of a cluster upgrade for example where pods are drained and rescheduled as nodes upgrade.
## Use Case

PodDisruptionBudgets prevent the node from draining one of the replicas until enough replicas are in Running state to allow for a safe drain. E.g. 3 replicas desired with only 1 allowed down will allow 1 to drain then wait for it to become running to drain another.

## Desired Behavior

Add a way to configure these via the CRDs like the affinity settings for example.

## Environment

GKE 1.20.10

**Comment by jkatz** [comment]
This is currently on the roadmap and will be available in an upcoming release.
