### ISSUE TITLE
[CRD doc] exporter queries customization error

### ISSUE THREAD

**Issue by Jean-Daniel** [CrunchyData/postgres-operator#2793]
In the v5 CRD reference for `PostgresCluster.spec.monitoring.pgmonitor.exporter`, the `configuration` field reference contains this paragraph:

```
Currently supports the customization of PostgreSQL Exporter queries. 
If a "queries.yaml" file is detected in any volume projected using this field,
it will be loaded using the "extend.query-path" flag: 
```

It says that one can use `queries.yaml`, but in reality, on `queries.yml` work to specifies custom queries (note the extension).

**Comment by alex1989hu** [comment]
It is fixed in https://github.com/CrunchyData/postgres-operator/pull/3407
