### ISSUE TITLE
PGAdmin with PostgresCluster discovery

### ISSUE THREAD

**Issue by edenkoveshi** [CrunchyData/postgres-operator#2795]
## Overview

The idea is to create a new CRD for pgAdmin, that will create a simple pgAdmin deployment that discovers PostgresClusters within namespace using a label selector (or simply all instances?)

## Use Case
A single namespace can have many PG clusters and one pgAdmin should really do, regardless it shouldn't be co-dependant with PostgresCluster CRs. 
Also, PostgresCluster discovery is really awesome as it automates configuration

## Desired Behavior
Creating pgAdmin creates a simple deployment + service (+ route on openshift?)
Controller discovers PostgresCluster pods by a simple label selector, and adds them to pgAdmin servers.json (can be implemented with a ConfigMap, but do we want it to be read-only?)

## Additional Information

I'll be happy to help developing this if you find this interesting.

**Comment by ValClarkson** [comment]
Hi @edenkoveshi,

We have this in our backlog for future development, Are you still interested in this?

**Comment by benjaminjb** [comment]
Hello, @edenkoveshi, I am happy to report that we now have a pgAdmin4 CRD that is capable of cluster discovery according to some label selector. For more on this, please check out the [docs](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace-scoped-pgadmin-4).

I'm going to close this ticket, but we're really interested in feedback on this new pgAdmin4 CRD -- if you get a chance to try this out, please drop us a line in our new [discord](​​https://discord.com/invite/a7vWKG8Ec9).
