### ISSUE TITLE
Restore a back from a cluster to annother

### ISSUE THREAD

**Issue by giovannicandido** [CrunchyData/postgres-operator#2809]
Hi,
I do have two kubernetes clusters with backups to a S3 storage which I'm trying to migrate.
In the second kubernetes cluster I setup a postgresql cluster with the same name, using the same yaml.
I enable the restore with the option:

```
restore:
  enabled: true
   repoName: repo1
  options:
   - --type=time
   - --target="2021-10-26 00:00:00 EDT"
```
And then annotate the cluster, but the cluster describe show me a error in the restoration:

```
Warning  UnableToCreateStanzas  55s (x118 over 25m)  postgrescluster-controller  command terminated with exit code 28: WARN: configuration file contains invalid option 'region'
ERROR: [028]: backup and archive info files exist but do not match the database
       HINT: is this the correct stanza?
       HINT: did an error occur during stanza-upgrade?

```

What is that stanza? Is a Id for the database?
How to transfer that cluster between installations of postgres-operator (k8s cluster)?

Thanks.

I try to join the google group to ask this question but is not working.

**Comment by jkatz** [comment]
My first recommendation would be to run the same version of PGO in each of the clusters. PGO upgrades are pretty simple -- it should just be an image swap -- though you should [read the release changes](https://access.crunchydata.com/documentation/postgres-operator/v5/releases/5.0.3/) in case you are affected by any.

There are a few ways to copy the data over, most of which are covered in the [disaster recovery](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/) section of the tutorial. I believe this makes the most sense in your case.

Based upon how your data is set up, a [volume migration](https://access.crunchydata.com/documentation/postgres-operator/v5/guides/data-migration/) may be the appropriate guide to follow as well.

**Comment by benjaminjb** [comment]
@giovannicandido Did Jonathan's response clear this up for you?

**Comment by giovannicandido** [comment]
It helped but at the time I did a backup outside PGO and restored in the target cluster. Unfortunately I don't have a cluster with PGO anymore to test disaster recovery scenarios, because I'm using ARM architecture.

I will close this issue, maybe someone could test the recovery from disaster scenario and add some comment later.

Thanks.
