### ISSUE TITLE
Error of asynchronous archiving  wal after upgrade PGO-cluster to  4.7.0 

### ISSUE THREAD

**Issue by kglebova** [CrunchyData/postgres-operator#2812]
Hi,
After updating pgo-operator from 4.6.2 to version 4.7.0 asynchronous archiving  wal broke.
We are using pgbackrest options:

```
[global:archive-push]
    compress-level=6
    archive-async=y
    archive-push-queue-max=60GB
    process-max=3
```
Defaul spool-path=/var/spool/pgbackrest
But now we have error:
`ERROR: [047]: unable to create path '/var/spool/pgbackrest/archive': [30] Read-only file system `

How to configure asynchronous archiving correctly now?

**Comment by jkatz** [comment]
[4.7.0](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.7.0/) defaulted all of the containers to have a read-only root filesystem.

You would have to modify the [spool path](https://pgbackrest.org/configuration.html#section-general/option-spool-path) to be in a writable directory, or modify the template to disallow read-only root filesystem.

**Comment by kglebova** [comment]
Thanks!
