### ISSUE TITLE
GitHub releases for PGO v5

### ISSUE THREAD

**Issue by mgalesloot** [CrunchyData/postgres-operator#2818]
PGO v5.* is not appearing in the list of releases at https://github.com/CrunchyData/postgres-operator/releases. 

Is it possible to add releases for PGO v5 in GitHub? It is a convenient way to track progress. Also, it would give an indication for the user what the latest release is. I believe 5.x is now the prefered version as it is working really well.

**Comment by jkatz** [comment]
This is discussed in the [FAQ](https://access.crunchydata.com/documentation/postgres-operator/v5/faq/).

Release notices are sent to the [PGO mailing list](https://access.crunchydata.com/documentation/postgres-operator/v5/support/) and the [Developer Portal mailing list](https://www.crunchydata.com/developers/newsletter).

> I believe 5.x is now the prefered version as it is working really well.

Thanks!
