### ISSUE TITLE
pgo create pgadmin in crashloop

### ISSUE THREAD

**Issue by the1forte** [CrunchyData/postgres-operator#2821]
When creating a cluster using custom TLS certs, you cannot add a pgadmin instance with "pgo create pgadmin". 

Environment:
K8s 1.18
pgo ubi7-13.4-4.7.2

Steps to recreate:
1) pgo create cluster somecluster --ccp-image-tag=ubi7-13.4-4.7.2 --server-ca-secret=postgresql-ca --server-tls-secret=tls-keypair -n pgouser1
2) pgo create pgadmin somecluster -n pgouser1

Logs from pgadmin container:

Mon Nov  1 14:21:26 UTC 2021 INFO: TLS disabled. Applying http configuration..
Mon Nov  1 14:21:27 UTC 2021 INFO: Starting Apache web server..
[Mon Nov 01 14:21:35.533207 2021] [so:warn] [pid 26] AH01574: module wsgi_module is already loaded, skipping
[Mon Nov 01 14:21:35.535472 2021] [so:warn] [pid 26] AH01574: module wsgi_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.32.0.7. Set the 'ServerName' directive globally to suppress this message
httpd (pid 26) already running

Describing containers shows:

  Normal   Pulled     6m8s (x5 over 8m34s)    kubelet            Container image "containeryard.evoforge.org/dbaas/crunchy-pgadmin4:ubi7-13.4-4.7.2" already present on machine
  Normal   Created    6m2s (x5 over 8m34s)    kubelet            Created container pgadminweb
  Normal   Started    5m46s (x5 over 8m34s)   kubelet            Started container pgadminweb
  Warning  BackOff    3m23s (x18 over 8m31s)  kubelet            Back-off restarting failed container

**Comment by jkatz** [comment]
@the1forte I was unable to reproduce this issue. I am able to load pgAdmin 4 with custom TLS.

This may require more information to troubleshoot (perhaps it's a local configuration issue) but I was unable to reproduce the reported issue with any testing.
