### ISSUE TITLE
S3 endpoint error messages

### ISSUE THREAD

**Issue by dimitrigraf** [CrunchyData/postgres-operator#2836]
# Description

We use the S3-backup mechanism of PGO and we have a non-AWS S3-compliant storage infrastructure.
When specifying the endpoint URL in [the cluster YAML file](https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/s3/postgres.yaml#L25) we could observe the following:

1. With a URL in the format of `https://s3-eu-central-1.example-domain.io` the backup does not work and the operator prints the following error message in the logs:
```
time="2021-11-08T15:33:22Z" level=error msg="unable to create stanza" error="command terminated with exit code 31: ERROR: [031]: 'https://s3-eu-central-1.example-domain.io' is not valid for option 'repo1-s3-endpoint'\n       HINT: port is not a positive integer.\n" file="internal/controller/postgrescluster/pgbackrest.go:2308" func="postgrescluster.(*Reconciler).reconcileStanzaCreate" name=hippo-s3 namespace=devit-devel reconciler=pgBackRest reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.0.3-0
```

2. With a URL in the format of `https://s3-eu-central-1.example-domain.io:443` the backup also does not work and the error is as follows:
```
time="2021-11-08T15:41:40Z" level=debug msg=Warning file="sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/recorder/recorder.go:98" func="recorder.(*Provider).getBroadcaster.func1.1" message="command terminated with exit code 31: ERROR: [031]: 'https://s3-eu-central-1.example-domain.io:443' is not valid for option 'repo1-s3-endpoint'\n       HINT: is more than one port specified?\n" object="{PostgresCluster devit-devel hippo-s3 c3eb9c92-8541-46ca-9741-f6698f858ab0 postgres-operator.crunchydata.com/v1beta1 309611713 }" reason=UnableToCreateStanzas version=5.0.3-0
```

3. The backup works with the following URLs:
- `s3-eu-central-1.example-domain.io`
- `s3-eu-central-1.example-domain.io:443`

So, specifying `https://` is apparently not allowed. In our case the problem was the somewhat misleading error messages. I'm not sure if this is an issue that should be handled by PGO or if pgbackrest  should handle this differently.
I initially ran into this problem and shrugged it off as a mistake on my side. But then a colleague of mine ran into the exact same issue, specifying the URL with a leading `https://`. That's why I thought it might be helpful to bring this topic up.

Maybe this should also be clarified in the CRD docs and the tutorial. 

# Environment

- Platform: `Kubernetes`
- Platform Version: `v1.20.7`
- PGO Image Tag: `ubi8-5.0.3-0`
- Postgres Version: `13`
- Storage: `Cloudian S3`

**Comment by jkatz** [comment]
At most on the PGO front, we can document this. I'm not opposed to doing so.

**Comment by larsks** [comment]
We just hit exactly the same problem. Rather than simply documenting it, it would be nice if either (a) the error message was more explicit ("endpoint must not be a url") or (b) it would just accept a url because we are configuring an http endpoint.
