### ISSUE TITLE
Custom labels on user sercets

### ISSUE THREAD

**Issue by Martin-Hogge** [CrunchyData/postgres-operator#2843]
## Overview

Being able to add custom labels on user sercrets.

## Use Case

My application which is not actually using CrunchyData in production is already getting the credentials of the database through a kubernetes secret. This secret is actually being fetch thanks to its labels.

For a smooth transition from my "no-crunchydata database" to the crunchydata environment I would like to add the same labels already existing secrets has to the one crunchydata will generate.

## Desired Behavior

Add an entry `PostgresCluster.spec.users[index].labels` to the crd.

## Environment

- Platform: `Kubernetes (GKE)`
- Platform Version: `1.19.14-gke.1900`
- PGO Image Tag: `ubi8-5.0.3-0`
- Postgres Version `13`
- Storage: default storage class
- Number of Postgres clusters: 1

**Comment by jkatz** [comment]
If this is just temporary, why not apply the label via the [general customized label](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/customize-cluster/#labels) functionality?

**Comment by Martin-Hogge** [comment]
This will do the trick. Don't know why I was sure labels were only applied on pods and not on secrets/config-maps, ...

Thank you for your help.
