### ISSUE TITLE
Postgresql Custom image

### ISSUE THREAD

**Issue by DTvGe45vc** [CrunchyData/postgres-operator#2854]
Hello
I want to use custom postgresql image. For instance "supabase/postgres"
For it I rebuild image and prepared postgres user id (26) by dockerfile like your image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1".

Also after start image I get the error: "Error: container has runAsNonRoot and image has non-numeric user (postgres), cannot verify user is non-root"

What I need to do for starting?

My Dockerfile
```
From supabase/postgres:13.3.0
ARG UNAME=postgres
ARG UID=26
ARG GID=26
RUN groupmod -g 3000 $(getent group | grep $GID |cut -d':' -f1 )
RUN groupmod -g $GID $UNAME
RUN usermod -u $UID -g $GID $UNAME
USER $UNAME
```

Kubernetes version v1.19.15

**Comment by jkatz** [comment]
Closed as this was asked on the mailing list.

**Comment by arpagon** [comment]
Custom Image with the basics for Supabase [crunchy-postgres](https://github.com/wundercomm/crunchy-postgres)
