### ISSUE TITLE
Pgo secret for Postgres cluster doesn't have admin right

### ISSUE THREAD

**Issue by sambeet99** [CrunchyData/postgres-operator#2858]
Bug
-----
After successful creation of Postgres cluster in Kubernates using Kustomize files , we get a secret where credentials for PostgreSQL user account is saved. However after connecting to database this user is not able to create a new database.
Unable to create database may be an issue for any other applications (java /nodejs etc..) to connect .

- Platform: Kubernetes
- Platform Version: Server Version: version.Info{Major:"1", Minor:"21"
- PGO Image Tag: env:
        - name: CRUNCHY_DEBUG
          value: "true"
        - name: RELATED_IMAGE_POSTGRES_13
          value: "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1"
        - name: RELATED_IMAGE_POSTGRES_13_GIS_3.1
          value: "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:centos8-13.4-3.1-1"
        - name: RELATED_IMAGE_PGBACKREST
          value: "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0"
        - name: RELATED_IMAGE_PGBOUNCER
          value: "registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-3"
        - name: RELATED_IMAGE_PGEXPORTER
          value: "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.3-0"

- Postgres Version: 13

## Steps to Reproduce -

(1) Steps -  https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/
    
 I have used HA mode.
 cluster name = demo

(2) After DB cluster pods and Pgo up and running, connect to Primary database using secret file.

(3) Try to create a database  command- "create database Test;"

(4) see all databses -  \l

### EXPECTED
A new database named "Test" should get created.

### ACTUAL
No new database created.

## Logs

\du - 

     Role name     |                         Attributes                         | Member of
-------------------+------------------------------------------------------------+-----------
 _crunchypgbouncer |                                                            | {}
 _crunchyrepl      | Replication                                                | {}
 demo              |                                                            | {}
 postgres          | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

 ## Additional Information

I created a cluster named "demo" and I can not create database with user "demo".

**Comment by jkatz** [comment]
I recommend reading through the [user management tutorial](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/user-management/) which covers this topic.
