### ISSUE TITLE
PGO doc link outdated for "latest"?

### ISSUE THREAD

**Issue by dimitrigraf** [CrunchyData/postgres-operator#2865]
When using https://access.crunchydata.com/documentation/postgres-operator/latest/ to access the docs for the latest version of PGO I always arrive at the docs for version 4.7.3 and I was wondering if this is correct.

**Comment by jkatz** [comment]
A lot of folks are still using v4 and the `latest` link has a bunch of docs that correspond to that.

We are planning to move the `latest` link over to v5 once v5.1 is released. You can access the newest v5 docs from this URL:

https://access.crunchydata.com/documentation/postgres-operator/v5/

**Comment by andrewlecuyer** [comment]
The ["latest"](https://access.crunchydata.com/documentation/postgres-operator/latest/) link now points to the latest version of PGO (which is PGO v5.1 at the time of this writing).

 https://access.crunchydata.com/documentation/postgres-operator/latest/
