### ISSUE TITLE
How to delete crunchydata postgres statefulset/instance

### ISSUE THREAD

**Issue by yene** [CrunchyData/postgres-operator#2871]
I scaled up my instances to 2.
How do I remove my first crunchydata postgres instance? So that the master switches over.

thank your for your time

**Comment by jkatz** [comment]
There are two ways to do this:

- Starting in PGO v5.1, you can use the ad hoc switchover feature (#2794) to promote your new primary, and then scale down within the instance set. OR
- If you need to do this now, you can create two instance sets: one that has your current primary and one with the replica. Once the replica is healthy, you can remove the instance set with the primary and the failover will occur. This is similar to the technique described in:

https://blog.crunchydata.com/blog/resize-postgres-kubernetes-volume-instance-sets

**Comment by yene** [comment]
@jkatz Thanks for the answer, just as you mentioned in the article we needed to resize an Azure disk, which requires full detach for 30s.

My quick workaround was doing a planned downtime, by scaling everything to 0 and back to 1.

**Comment by jkatz** [comment]
@yene PGO lets you scale everything down to `0` by setting the [`shutdown`](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/administrative-tasks/#shutdown) attribute on the spec.

Anyway, glad it worked out!

**Comment by cbandy** [comment]
> Thanks for the answer, just as you mentioned in the article we needed to resize an Azure disk, which requires full detach for 30s.

I see detach mentioned a few times for the CSI driver. @yene is the 30 seconds documented anywhere?

- https://docs.microsoft.com/en-us/azure/virtual-machines/linux/expand-disks
- https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi#resize-a-persistent-volume
- https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/resize

**Comment by yene** [comment]
@cbandy No, I just waited with the Azure portal open until the disk was "unattached" and resized. 
A bit disappointing compared to GCP Kubernetes where you just have to restart the pod for a disk resize.

Ticket on a discussion around AKS and resize https://github.com/Azure/AKS/issues/1477
