### ISSUE TITLE
PGO Monitoring Stack - S3 Integration

### ISSUE THREAD

**Issue by lbartnicki92** [CrunchyData/postgres-operator#2876]
Hi!

I'm currently trying to deploy PGO Monitoring Stack 4.7.3 (Grafana, Prometheus, AlertManager) to K8s cluster.
All of this components need some persistent storage to store data. 
Databases deployed with your operator we can use S3.

I searched a lot in your docs, and can't find any parameter for Monitoring Stack, to use it with S3 as persistent volumes.

Is this possible?

**Comment by jkatz** [comment]
We provide examples for installing those components within the repository using storage class options:

https://github.com/CrunchyData/postgres-operator/tree/REL_4_7/installers/metrics

However, the containers used correspond to the upstream projects. You would need to consult their documentation for using other storage options.
