### ISSUE TITLE
Need root access to containers

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#2878]
PGO 4.5.0

Whenever things stop working correctly it would be super helpful to be able to modify root files.  Like for example I am having issues with s3 archiving and my primary is filling with wal archives.  I'd like to on-the-fly modify the archive script so that it succeeds without archiving to s3 and only locally.  However, I am blocked from editing that script because the user I exec into the container with is postgres and I cannot become the root user.

**Comment by jkatz** [comment]
You can modify the `archive_command` from [custom configuration](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/) if needed.

Additionally, [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/) makes it easier to modify + rollout changes across instances.

We have no plans to allow root access to running containers managed by PGO.
