### ISSUE TITLE
Support for openshift/okd 4.9.0

### ISSUE THREAD

**Issue by daFritz84** [CrunchyData/postgres-operator#2885]
Hi,

a quick question: Since okd 4.9.0 was released, is there any concern that the operator will have incompatibilities with the new 4.9 version? 

I tried to update my dev-cluster today, and the postgres-operator is the only one operator blocking the update. 
It seems that the version is intentionally limited to 4.8

See ClusterServiceVersion Resource:
```
...
olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.8"}]
...
```

Thx,
Stefan

**Comment by jkatz** [comment]
PGO v5 supports OCP 4.9 out-of-the-box.
