### ISSUE TITLE
what about pgo client?

### ISSUE THREAD

**Issue by tirelibirefe** [CrunchyData/postgres-operator#2886]
Hello,
I couldn't have found an answer... What about pgo client pod or installation manuals for Release 5.X ? May we use the same pgo pod and/or client installation instructions with Release 4.X?

Thanks & Regards

**Comment by anonymouse-jj** [comment]
I'm also interested about using the pgo cli with version 5? Is it not available?

**Comment by sunofsparda** [comment]
Hello,
According to https://access.crunchydata.com/documentation/postgres-operator/5.0.4/releases/5.0.0/ `pgo-client` was removed

**Comment by andrewlecuyer** [comment]
Just noting in this thread that we are hard at work on our PGO v5 CLI.

More details to come soon!

**Comment by tjmoore4** [comment]
@tirelibirefe @anonymouse-jj Just wanted to make sure you were aware, the `pgo` CLI is now available for PGO v5. Please see the [Github repo](https://github.com/CrunchyData/postgres-operator-client) and [documentation](https://access.crunchydata.com/documentation/postgres-operator-client/latest/) for more information!
