### ISSUE TITLE
PGO cluster creation failing with stanza pod's error status

### ISSUE THREAD

**Issue by sibinnediyoram** [CrunchyData/postgres-operator#2893]
Hi,

We are trying to create a pgo cluster to enable replication across two kubernetes clusters using below arguments:

pgo create cluster hippo --pgbouncer --replica-count=2 \
  --pgbackrest-storage-type=posix,s3 \
  --pgbackrest-s3-key=******** \
  --pgbackrest-s3-key-secret=********\
  --pgbackrest-s3-bucket=inv-pro-sharedpgs \
  --pgbackrest-s3-endpoint=s3.ceph.*******.com \
  --pgbackrest-s3-region=us-east-1 \
  --password-superuser=****** \
  --password-replication=******* \
  --password=********* \
  --namespace=pgo-cluster-rep-test
  
PGO details:
 $ pgo version
pgo client version 4.7.2
pgo-apiserver version 4.7.2

When checking with the pods list we are seeing stanza pods with error status

NAME                                          READY   STATUS    RESTARTS   AGE
hippo-backrest-shared-repo-796bbdbbbf-gc2wh   1/1     Running   0          113m
hippo-c6464b945-pbzsb                         1/1     Running   0          112m
hippo-pgbouncer-599f4fc788-j8rpf              1/1     Running   0          111m
hippo-stanza-create-chs5s                     0/1     Error     0          111m
hippo-stanza-create-j9bv2                     0/1     Error     0          111m
hippo-stanza-create-p7s7v                     0/1     Error     0          107m
hippo-stanza-create-q99vg                     0/1     Error     0          110m
hippo-stanza-create-z2gqq                     0/1     Error     0          111m

From the logs we can see as below:
$kubectl logs hippo-backrest-shared-repo-796bbdbbbf-gc2wh -n pgo-cluster-rep-test
NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/tmp/nss_wrapper/pgbackrest-repo/passwd' readonly -1:No such file or directory
NWRAP_ERROR(1) - nwrap_files_getpwuid: Error loading passwd file
nss_wrapper: user exists
nss_wrapper: group exists
nss_wrapper: environment configured
Starting the pgBackRest repo
nss_wrapper: ssh configured
The pgBackRest repo has been started
WARNING: 'UsePAM no' is not supported in Fedora and may cause several problems.

$kubectl logs hippo-pgbouncer-599f4fc788-j8rpf -n pgo-cluster-rep-test
nss_wrapper: adding user
nss_wrapper: adding group
nss_wrapper: environment configured
Fri Dec  3 03:56:13 UTC 2021 INFO: Custom users.txt file detected..
Fri Dec  3 03:56:13 UTC 2021 INFO: Custom pgbouncer.ini file detected..
Fri Dec  3 03:56:13 UTC 2021 INFO: Starting pgBouncer..
2021-12-03 03:56:13.965 UTC [35] LOG kernel file descriptor limit: 1048576 (hard: 1048576); max_client_conn: 100, max expected fd use: 112
2021-12-03 03:56:13.965 UTC [35] LOG kernel file descriptor limit: 1048576 (hard: 1048576); max_client_conn: 100, max expected fd use: 112
2021-12-03 03:56:13.969 UTC [35] LOG listening on 0.0.0.0:5432
2021-12-03 03:56:13.969 UTC [35] LOG listening on [::]:5432
2021-12-03 03:56:13.969 UTC [35] LOG listening on 0.0.0.0:5432
2021-12-03 03:56:13.969 UTC [35] LOG listening on [::]:5432
2021-12-03 03:56:13.969 UTC [35] LOG listening on unix:/tmp/.s.PGSQL.5432
2021-12-03 03:56:13.969 UTC [35] LOG process up: PgBouncer 1.15.0, libevent 2.1.8-stable (epoll), adns: evdns2, tls: OpenSSL 1.1.1g FIPS  21 Apr 2020
2021-12-03 03:56:13.969 UTC [35] LOG listening on unix:/tmp/.s.PGSQL.5432
2021-12-03 03:56:13.969 UTC [35] LOG process up: PgBouncer 1.15.0, libevent 2.1.8-stable (epoll), adns: evdns2, tls: OpenSSL 1.1.1g FIPS  21 Apr 2020
2021-12-03 03:57:13.970 UTC [35] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us

$kubectl logs hippo-stanza-create-q99vg -n pgo-cluster-rep-test
nss_wrapper: user exists
nss_wrapper: group exists
nss_wrapper: environment configured
Fri Dec  3 03:56:44 UTC 2021 INFO: Image mode found: pgbackrest
Fri Dec  3 03:56:44 UTC 2021 INFO: Starting in 'pgbackrest' mode
time="2021-12-03T03:56:45Z" level=info msg="crunchy-pgbackrest starts"
time="2021-12-03T03:56:45Z" level=info msg="debug flag set to false"
time="2021-12-03T03:56:45Z" level=info msg="backrest stanza-create command requested"
time="2021-12-03T03:56:45Z" level=info msg="backrest command will be executed for both local and s3 storage"
time="2021-12-03T03:56:45Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.233.67.246 --db-path=/pgdata/hippo ; pgbackrest stanza-create  --db-host=10.233.67.246 --db-path=/pgdata/hippo --repo1-type=s3]"
time="2021-12-03T03:56:45Z" level=info msg="output=[]"
time="2021-12-03T03:56:45Z" level=info msg="stderr=[ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-archive.lock': Resource temporarily unavailable\n       HINT: is another pgBackRest process running?\nERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-archive.lock': Resource temporarily unavailable\n       HINT: is another pgBackRest process running?\n]"
time="2021-12-03T03:56:45Z" level=fatal msg="command terminated with exit code 50"

Is there anyone experienced with this issue with pgo version 4.7.2 ? Can we get a solution for this issue?

**Comment by jkatz** [comment]
If this is a new cluster, I suggest starting with [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/). [Setting up standbys](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/) are detailed in the [tutorial](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/)

If you need to use v4, I suggest using the latest version, 4.7.3.

**Comment by sibinnediyoram** [comment]
@jkatz Thank you for the comments. The operator was already deployed and its 4.7.2. So we need to upgrade the version as you mentioned to 4.7.3 .

**Comment by benjaminjb** [comment]
(A) @sibinnediyoram have you updated to a more recent PGO version? and
(B) are you still experiencing this problem?

**Comment by sibinnediyoram** [comment]
@benjaminjb Im not experiencing this problem anymore.
