### ISSUE TITLE
Restore single database

### ISSUE THREAD

**Issue by EugenMayer** [CrunchyData/postgres-operator#2895]
Is it possible to restore a single database from the backup? I understand how to do a disaster recovery and PITR for the entire database, but is there an option to just restore the database of a specific application?

Thanks!

**Comment by jkatz** [comment]
Yes: Please see the [`--db-include`](https://pgbackrest.org/command.html#command-restore/category-command/option-db-include) directive in the pgBackRest docs.

**Comment by EugenMayer** [comment]
Attention to all - this is most probably not what you are looking for.

This will do the following:
 a) delete all databases 
 b) restore dummies for all databases not included
 c) restore the included databases.

So basically, this is not 'restore only one database from the backup and leave all the others as is' - it is more 'wipe all databases, then restore only the included.

To be honest, I have no idea which use-case this would have, ever. But for me, this just made a lot of extra effort.

@jkatz is there any way to do what i was actually aiming for - restoring only one single database from the backups, while keeping all other database in-tact?

**Comment by EugenMayer** [comment]
Maybe an update on that front - restoring  a single database while keeping all the others in place is simply not possible, more to that under https://github.com/pgbackrest/pgbackrest/issues/165

**Comment by wht1998** [comment]
> Maybe an update on that front - restoring a single database while keeping all the others in place is simply not possible, more to that under [pgbackrest/pgbackrest#1659](https://github.com/pgbackrest/pgbackrest/issues/1659)

i do backup,then try restore single database,but don't work,all data from now
