### ISSUE TITLE
Replica service was not created

### ISSUE THREAD

**Issue by BetulMinim** [CrunchyData/postgres-operator#2896]
I am using the config below, however replica service was not created. I searched all documentation and couldn't see anything related to replica service.

apiVersion: v1
items:
- apiVersion: postgres-operator.crunchydata.com/v1beta1
  kind: PostgresCluster
  metadata:
    annotations:
      meta.helm.sh/release-name: xxxxxxxxx
      meta.helm.sh/release-namespace: pg
      postgres-operator.crunchydata.com/pgbackrest-backup: Mon Nov 29 14:28:54 EST
        2021
    creationTimestamp: "2021-11-29T18:13:48Z"
    finalizers:
    - postgres-operator.crunchydata.com/finalizer
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      rep-cluster: w2lwnok
      rep-cluster-name: xxxxxxxxx
      rep-drift-reconcillation: disabled
      rep-organization: pkvdykn
      rep-partner: rx28oml
      rep-placement: kjrdjlm
      rep-project: 1kyxdmz
      rep-project-name: defaultproject
      rep-workload: xxxxxxx
      rep-workloadid: k35d31m
    name: pg
    namespace: pg
    resourceVersion: "144255563"
    selfLink: /apis/postgres-operator.crunchydata.com/v1beta1/namespaces/pg/postgresclusters/pg
    uid: fc18136d-ccdb-4c1c-ac67-d2bdda777d52
  spec:
    backups:
      pgbackrest:
        configuration:
        - secret:
            name: pgo-s3-creds
        global:
          repo1-path: postgres-operator/xxxxxxxx/repo1
          repo1-retention-full: "14"
          repo1-retention-full-type: time
        image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
        manual:
          options:
          - --type=full
          repoName: repo1
        repoHost:
          dedicated: {}
        repos:
        - name: repo1
          s3:
            bucket: xxxxxxxxxxx
            endpoint: s3.amazonaws.com
            region: eu-west-1
          schedules:
            full: 0 1 * * *
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos8-13.4-3.1-0
    instances:
      dataVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: managed-premium
      name: pg
      replicas: 2
      resources:
        limits:
          cpu: 15
          memory: 48Gi
        requests:
          cpu: 8
          memory: 16Gi
    monitoring:
      pgmonitor:
        exporter:
          image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.2-0
    patroni:
      dynamicConfiguration:
        postgresql:
          parameters:
            max_connections: 300
      leaderLeaseDurationSeconds: 30
      port: 8008
      syncPeriodSeconds: 10
    port: 5432
    postgresVersion: 13
    proxy:
      pgBouncer:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-2
        port: 5432
        replicas: 1
    users:
    - name: postgres

Services should be like -->

NAME              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
hippo-ha          ClusterIP   10.103.73.92   <none>        5432/TCP   3h14m
hippo-ha-config   ClusterIP   None           <none>        <none>     3h14m
hippo-pods        ClusterIP   None           <none>        <none>     3h14m
hippo-primary     ClusterIP   None           <none>        5432/TCP   3h14m
hippo-replicas    ClusterIP   10.98.110.215  <none>        5432/TCP   3h14m

But we have -->

pg-ha          ClusterIP   10.100.93.237   <none>        5432/TCP   3d22h
pg-ha-config   ClusterIP   None            <none>        <none>     3d22h
pg-pgbouncer   ClusterIP   10.100.201.44   <none>        5432/TCP   3d22h
pg-pods        ClusterIP   None            <none>        <none>     3d22h
pg-primary     ClusterIP   None            <none>        5432/TCP   3d22h

How we can add replica service?

**Comment by jkatz** [comment]
Replica services were added in [5.0.3](https://access.crunchydata.com/documentation/postgres-operator/v5/releases/5.0.3/). While this does not state the version of PGO that is running, it seems to be 5.0.2 based upon both the image tag for the exporter.
