### ISSUE TITLE
GCP marketplace installation istio conflict

### ISSUE THREAD

**Issue by nurhun** [CrunchyData/postgres-operator#2902]
I'm trying to install the operator from GKE marketplace, but I'm getting "Istio is unsupported for the application, but it is enabled on this cluster"

Is there a way to install it in a certain namespace where istio-injection=disabled

Thanks,

**Comment by andrewlecuyer** [comment]
Considering this is an old/outdate thread for an older version of Crunchy Postgres for Kubernetes, I am proceeding with closing this issue.

If you are still running into any issues installing the [latest version of Crunchy Postgres for Kubernetes](https://access.crunchydata.com/documentation/postgres-operator/latest/), please feel free to submit a new issue.
