### ISSUE TITLE
Missing documentation about PodDisruptionBudget configuration

### ISSUE THREAD

**Issue by alex1989hu** [CrunchyData/postgres-operator#2905]
## Overview

Configuration of **PodDisruptionBudget** has just been added <https://github.com/CrunchyData/postgres-operator/pull/2828> but there is no follow up PR which add this to documentation, too.

## Environment

N/A

## Steps to Reproduce

N/A

### REPRO

N/A

### EXPECTED

1. <https://access.crunchydata.com/documentation/postgres-operator/v5/> contains page where user can find details how to configure PodDisruptionBudget.

### ACTUAL

1. <https://access.crunchydata.com/documentation/postgres-operator/v5/> contains page where user is not able to find details how to configure PodDisruptionBudget.

## Logs

N/A

## Additional Information

N/A

**Comment by jkatz** [comment]
The documentation was committed, but this feature is not yet released.

**Comment by alex1989hu** [comment]
> The documentation was committed, but this feature is not yet released.

Could you please share the commit sha?
