### ISSUE TITLE
Is it possible to use it with citus?

### ISSUE THREAD

**Issue by docteurklein** [CrunchyData/postgres-operator#2915]
Hey there :)
I'm maintaining a little toy citus setup on kubernetes at https://github.com/docteurklein/citus-test and wondered if it would be possible to support this kind of scenario?

Thanks!

**Comment by luatnd** [comment]
+1, All I know is Patroni can be used with Citus, looking forward to seeing Crunchy with Citus tutorial

**Comment by tunatoksoz** [comment]
I think this is solved with #3761
