### ISSUE TITLE
Readiness probe failing while creating cluster using pgo client

### ISSUE THREAD

**Issue by InderpreetSaini** [CrunchyData/postgres-operator#2916]
Hi,

I am trying to deploy a postgres cluster using pgo client on RKE2 cluster which is hosted on SUSE Linux Enterprise Server 15 SP2 VMs.

Followed the steps at https://access.crunchydata.com/documentation/postgres-operator/4.7.3/quickstart/

Readiness probe is failing for the cluster pod with the below error:

  _**Warning  Unhealthy  2s (x5 over 42s)   kubelet            Readiness probe failed: declare -x BACKREST_SKIP_CREATE_STANZA="true"
/opt/crunchy/bin/postgres-ha/common/pgha-common.sh: line 20: /proc/1/environ: Permission denied**_

Is there a way to work around this issue to get the cluster up and running? 

The same steps when I try on an Ubuntu based rke2 cluster work just fine. So the steps do not seem to be the issue.

**Comment by jkatz** [comment]
> So the steps do not seem to be the issue.

It's difficult to determine if this is the case when there is limited on how you created the Postgres cluster.

Separately, if this is a new project I suggest starting with [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/).

**Comment by InderpreetSaini** [comment]
Thanks for the suggestion. After installing v5.0.4, I did not face the readiness probe issue as it is not being used in this version.

After setting up this postgres cluster, I tried to use this cluster as an external database for harbor HA registry setup.

I am getting the below error while trying to integrate this cluster in the postgres cluster database container logs.

![image](https://user-images.githubusercontent.com/17871520/146394204-36873ac5-8287-4903-b6c7-3fa2b773cc07.png)

Is there any configuration while setting up the postgres cluster to customize the pg_hba.conf file to include the below line to allow the connection to pass through to postgres db? Tried searching the postgres documentation , but could not find it.

_host all all all md5_

Appreciate your help on this.

**Comment by bobbyd0g** [comment]
Unlike the patroni bootstrap configuration I raised in another issue, this patroni dynamicConfiguration option is definitely in there, just a bit buried in the docs [here](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/customize-cluster/) and [here](https://access.crunchydata.com/documentation/patroni/1.4.4/settings/). I just tacked this on to the end of my postgres.yaml file:
```
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - host all all all md5
```
Also worth noting I see this error whenever I've mistyped or failed to enter the db password

**Comment by jkatz** [comment]
> this patroni dynamicConfiguration option is definitely in there, just a bit buried in the docs

Customizing the Postgres configuration is described in a section labeld [Customize a Postgres Cluster](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/customize-cluster/). If there is something we can do to make that easier to find, we're open to suggestion.

That said, it appears the primary issue is resolved.

**Comment by InderpreetSaini** [comment]
> Unlike the patroni bootstrap configuration I raised in another issue, this patroni dynamicConfiguration option is definitely in there, just a bit buried in the docs [here](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/customize-cluster/) and [here](https://access.crunchydata.com/documentation/patroni/1.4.4/settings/). I just tacked this on to the end of my postgres.yaml file:
> 
> ```
>   patroni:
>     dynamicConfiguration:
>       postgresql:
>         pg_hba:
>           - host all all all md5
> ```
> 
> Also worth noting I see this error whenever I've mis-pasted or failed to enter / call the db password from secret

Thanks a lot. It worked !
