### ISSUE TITLE
Can we download old images anywhere?

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#2917]
pgo 4.5.0 

We have some old pg servers running that we have not had the chance to upgrade to latest version of postgres-operator and now the images have been removed.  Is there anywhere that we can download these old images so that we can host them ourselves and keep our database running until we have a chance to upgrade it?

Thanks!

**Comment by jkatz** [comment]
There are a subset of all PGO images available for preview in the [Developer Portal](https://www.crunchydata.com/developers/download-postgres/containers). All PGO images are available in the Crunchy Data Customer Portal. You can find more information on the [support](https://access.crunchydata.com/documentation/postgres-operator/v5/support/) page.
