### ISSUE TITLE
Avoid using some special characters in the password

### ISSUE THREAD

**Issue by EugenMayer** [CrunchyData/postgres-operator#2935]
Considering quite a number will use this in a JDBC string, avoiding some special characters will help avoid escaping issues:
 
I think the most critical ones are: `:` `@` and `/` 

Any thoughts? This is for convenience and at some points, if the helm charts consuming those have not thought well about url-encoding, it really helps to "not fight them" :)

I'am fine with just "well url-encode it and be done with it" too, no worries

**Comment by jkatz** [comment]
Have you run into this issue?

The user Secrets provide a JDBC URI and the characters should be escaped in that.

**Comment by EugenMayer** [comment]
@jkatz yes ran into issues with mattermost since they neither do support secret refs nor support usual jdbc uris.

The expect this ( without postgres;// ) : 

`externalDB.externalConnectionString: "${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${dbName}"`

So one can neither use JDBC nor jdbcUri. So to fix this, I would need to `dbPassword : urlencode(data.kubernetes_secret.db-credentials.data.password)` in terraform, so surely one can get it right, but it is harder I guess.

I mean, yes it is a fairly poorly crafted chart on several metrics (https://github.com/mattermost/mattermost-helm/tree/master/charts/mattermost-team-edition) but it is the official one at least.

I fully understand if you do not want to overcomplicate your things here because of those rather poorly crafted charts, but I though I at least bring it up for you to decide upon / know about it

**Comment by jkatz** [comment]
Even if you grab the `uri` from the Secret (which looks like it matches what mattermost expects?), the password is URI encoded for those characters, so I don't see this being an issue.

That said, perhaps https://github.com/CrunchyData/postgres-operator/issues/2781#issuecomment-946013348 is a possible solution in the longer term that allows one to specify which characters not to include. I'd rather leave it up to the user to decide which characters to exclude vs. continue to remove characters and reduce entropy.

**Comment by EugenMayer** [comment]
@jkatz no, mattermost does not expect it. It does not allow `postgresql://` to be prefixed .. yes this is odd. But they use a specific field for the driver.

i think #2781 is a good one actually, it lets us all decide how to deal with it. Make sense to me!

**Comment by EugenMayer** [comment]
Today i encountered the next issue, this time with a really well crafted chart https://github.com/stevehipwell/helm-charts/tree/master/charts/jira-software

My password includes `<` which will create issues in the actual XML configuration of jira `dbconfig.xml`.

So considering the spread of jira, this really can become problematic if people are not aware of all the bit's and pieces.

Just wanted to let you know

**Comment by cbandy** [comment]
> My password includes `<` which will create issues in the actual XML configuration of jira `dbconfig.xml`.

This chart seems to do a decent job of passing the value of the secret directly to the image environment, which then appears to [use Jinja to escape those values](https://bitbucket.org/atlassian-docker/docker-atlassian-jira/src/b2fc9ffb251146c80094f305f3c7b861d1a4ac7b/config/dbconfig.xml.j2#lines-19) into XML.

You said `<` "will create issues", but you mean that you tried it and it _was_ a problem?

**Comment by EugenMayer** [comment]
Yes, it was an actual issue, not theoretically.

I changed the password anyway, so I can share the content of dbconfig.xml 

```xml
  <jdbc-datasource>
    <url>jdbc:postgresql://pg-cluster-primary.postgres.svc:5432/jira</url>
    <username>jira</username>
    <password><bbVXvmMCQnX1K+_LcW4;S2<</password>
    <driver-class>org.postgresql.Driver</driver-class>
```

**Comment by cbandy** [comment]
Whelp. They seem to be using Jinja2 incorrectly. [This configuration](https://bitbucket.org/atlassian-docker/docker-shared-components/src/98410e658fca5792153de59ee681d22d71cd935c/image/entrypoint_helpers.py#lines-26:28) only escapes values in templates with the `xml` extension, not `xml.j2`.

I couldn't see a way to report a bug for that image project. *If you know how, I recommend it!*

```python
# ==> jinja.py <==
import os
import jinja2 as j2

env = {k.lower(): v
       for k, v in os.environ.items()}

jenv = j2.Environment(
    loader=j2.FileSystemLoader(os.getcwd()),
    autoescape=j2.select_autoescape(['xml']))

print(jenv.get_template('dbconfig.xml.j2').render(env))
print(jenv.get_template('dbconfig.xml').render(env))
```

```
==> dbconfig.xml.j2 <==
<?xml version="1.0" encoding="UTF-8"?>

<password>{{ atl_jdbc_password }}</password>
```
```
==> dbconfig.xml <==
<?xml version="1.0" encoding="UTF-8"?>

<password>{{ atl_jdbc_password }}</password>
```

```console
$ ATL_JDBC_PASSWORD='><' python jinja.py
<?xml version="1.0" encoding="UTF-8"?>

<password>><</password>

<?xml version="1.0" encoding="UTF-8"?>

<password>&gt;&lt;</password>
```

**Comment by EugenMayer** [comment]
@cbandy thank you for digging into that! Not sure myself either, neither expecting them to care too much since server is discontinued pretty much, but that is a different topic I guess.

I understand you want all the upstream applications to fix their encoding and you most probably right with that. 

I'am just not sure how realistic that is.

**Comment by EugenMayer** [comment]
Thank you a lot!

**Comment by EugenMayer** [comment]
@cbandy when is this becoming available? AFAICS yet no operator has been released, at least according to https://github.com/CrunchyData/postgres-operator-examples

Any hints would be great!
