### ISSUE TITLE
pgbackrest repoHost STS doesn't use pgbackrest SA

### ISSUE THREAD

**Issue by alecxsitex** [CrunchyData/postgres-operator#2936]
## Overview
StatefullSets for pgbackrest repoHost doesn't bind any ServiceAccounts (-instance and -pgbackrest), so repoHost pod doesn't have env for AWS EKS IAM Service Account auth binding.

## Environment
- AWS EKS 1.21
- ubi8-5.0.4-0
- Postgres Version (`14`)

### REPRO
1. In AWS EKS cluster run Postgres manifest with global AWS IAM annotations like `eks.amazonaws.com/role-arn: arn:aws:iam::account_id:role/role_with_access_to_s3` .
2.  See created STSs. 

### EXPECTED

1. STS `postgres-repo-host` manifest has fileds in pod template: 
```
serviceAccount: postgres-pgbackrest
serviceAccountName: postgres-pgbackrest
```
### ACTUAL

1. It doesn't. So pgbackrest container doesn't have AWS auth env.

## Logs
```
kubectl get sts postgres-repo-host -o yaml | grep serviceaccount # no output
kubectl exec -n razz-server -it fema-db-repo-host-0 -- env  | grep AWS # no output
```
## Additional Information
Instance's STSs (so and Pods) have SA binding and AWS envs.

**Comment by jkatz** [comment]
I have not verified what's described in the issue, but the pgBackRest repo does not interact with S3, so this shouldn't be necessary. The Postgres instances push directly to S3, as do backups.
