### ISSUE TITLE
did we build any docker  Image for pgboucner version 1.12.0 with pgbouncer-rr-patch ?

### ISSUE THREAD

**Issue by surajmachamasi** [CrunchyData/postgres-operator#2937]
i am using the default image version of the pgboucner comes with pgo,
 Are there any known image that patched with https://github.com/awslabs/pgbouncer-rr-patch which Adds query routing and rewriting extensions to pgbouncer  and works with PGO.

**Comment by jkatz** [comment]
What use case are you looking to solve?

**Comment by surajmachamasi** [comment]
for splitting  the  database load across multiple servers or clusters without impacting the configuration or code of your  applications. 

Pgbouncer-rr works the same way as pgbouncer; any target application can be connected to pgbouncer-rr as if it were an Amazon Redshift or PostgreSQL server, and pgbouncer-rr creates a connection to the actual server, or reuses an existing connection.

**Comment by prlaurence** [comment]
Hi, doing some house cleaning and noticed that this issue never got closed out. Crunchy Data packages and includes upstream pgbouncer in the containers associated with pgo. The latest versions associated with Postgres tools and extensions included in containers associated with pgo are reflected in this [list of components](https://access.crunchydata.com/documentation/postgres-operator/latest/references/components/).
