### ISSUE TITLE
pgo-deployer and k8s v. 1.23

### ISSUE THREAD

**Issue by BigKAA** [CrunchyData/postgres-operator#2938]
## Overview

In Kubernetes version 1.23, the API version of CustomResourceDefinition has changed from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1

Because of this, pgo-deployer: centos8-4.7.4 doesn't work.

## Environment

- Platform: (`Kubernetes`)
- Platform Version: (e.g. `1.23.1`)

## Steps to Reproduce

 kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.7.4/installers/kubectl/postgres-operator.yml

## Logs

TASK [pgo-operator : Create PGClusters CRD] ************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml"], "delta": "0:00:00.330581", "end": "2021-12-20 13:54:20.395843", "msg": "non-zero return code", "rc": 1, "start": "2021-12-20 13:54:20.065262", "stderr": "error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\"", "stderr_lines": ["error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\""], "stdout": "", "stdout_lines": []}

**Comment by jkatz** [comment]
[PGO v5](https://access.crunchydata.com/documentation/postgres-operator/v5/) supports Kubernetes 1.23.

If you need Kubernetes 1.22 compatibility for PGO v4, please reach out about [production support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/).
