### ISSUE TITLE
Crashes on arm64

### ISSUE THREAD

**Issue by samip5** [CrunchyData/postgres-operator#2941]
Please ensure you do the following when reporting a bug:

- [x] Provide a concise description of what the bug is.
- [x] Provide information about your environment.
- [x] Provide clear steps to reproduce the bug.
- [x] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [x] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

## Overview

The operator pod crashes with exec format error due to not having multi-arch images

## Environment

Please provide the following details:

- Platform: k3s (kubernetes)
- Platform Version: v1.22.4+k3s1
- PGO Image Tag: ubi8-5.0.4-0
- Postgres Version n/a
- Storage: nfs

### REPRO

Provide steps to get to the error condition:

1. Install kubernetes on an arm64 node
1. Try to install operator via kustomize
1. Have it fail to launch due to exec format error.

### EXPECTED

It would start up without issues

### ACTUAL

It crashes due to architecture mismatch

## Logs

```
$ k logs -n postgres-operator pgo-69949584b9-kszqq 
standard_init_linux.go:228: exec user process caused: exec format error
```

## Additional Information

Oracle has beefy ARM64 nodes that can be used for releasing and testing.

**Comment by jkatz** [comment]
Please see #2035 for discussion on ARM support.
