### ISSUE TITLE
Primary Service without label selectors v5

### ISSUE THREAD

**Issue by anonymouse-jj** [CrunchyData/postgres-operator#2943]
What is the purpose for the primary service not having labels selectors and how is this advantageous for PGO?

**Comment by jkatz** [comment]
The main reason is availability, which is discussed here: https://github.com/CrunchyData/postgres-operator/issues/2577#issuecomment-889945953

There is also a discussion of this on the mailing list pertaining to StatefulSets: https://groups.google.com/a/crunchydata.com/g/postgres-operator/c/OyFJOyplkcA/m/v5EifF8iBAAJ
