### ISSUE TITLE
Latest documentation link points to old release

### ISSUE THREAD

**Issue by Bkamau** [CrunchyData/postgres-operator#2957]
The latest documentation link https://access.crunchydata.com/documentation/postgres-operator/latest/  points to Latest Release: 4.7.4 while there is https://access.crunchydata.com/documentation/postgres-operator/v5/ pointing to Latest Release: 5.0.4.

The link https://access.crunchydata.com/documentation/postgres-operator/latest/  should always point to the **latest** version ATM, maybe?

**Comment by jkatz** [comment]
This is covered here:

https://github.com/CrunchyData/postgres-operator/issues/2865#issuecomment-975954015
