### ISSUE TITLE
unable to configure the pgo monitoring

### ISSUE THREAD

**Issue by hariyedlapalli** [CrunchyData/postgres-operator#2959]
Please ensure you do the following when reporting a bug:

- [x] Provide a concise description of what the bug is.
- [ ] Provide information about your environment.
- [ ] Provide clear steps to reproduce the bug.
- [ ] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [x] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

Add a concise description of what the bug is.

## Environment

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.)
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `ubi8-5.1.0-0`)
- Postgres Version (e.g. `14`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

### REPRO

Provide steps to get to the error condition:

1. Run `...`
1. Do `...`
1. Try `...`

### EXPECTED

1. Provide the behavior that you expected.

### ACTUAL

1. Describe what actually happens

## Logs

Please provided appropriate log output or any configuration files that may help troubleshoot the issue. **DO NOT** include sensitive information, such as passwords.

## Additional Information

Please provide any additional information that may be helpful.

**Comment by hariyedlapalli** [comment]
HI Team 

When i try to configure the pgo monitoring , I got this error message and struck here .

postgres-operator-examples-main]$ ~/kubectl apply -k kustomize/monitoring/
error: rawResources failed to read Resources: Load from path ./dashboards failed: './dashboards' must be a file (got d='/home/harikrishna/crunchy/ap-dev/postgres-operator-examples-main/kustomize/monitoring/dashboards')

Source : https://github.com/CrunchyData/postgres-operator-examples

I tried to get exact issue and i get this kind variable is missing , what could be the value for this kind variable in this file ? 

postgres-operator-examples-main]$ ~/kubectl apply -f kustomize/monitoring/crunchy_grafana_dashboards.yml --validate=false
error: unable to decode "kustomize/monitoring/crunchy_grafana_dashboards.yml": Object 'Kind' is missing in '{"apiVersion":1,"providers":[{"disableDeletion":false,"folder":"","name":"crunchy_dashboards","options":{"path":"$GF_PATHS_PROVISIONING/dashboards"},"orgId":1,"type":"file","updateIntervalSeconds":3}]}'

fyi

postgres-operator-examples-main]$ ~/kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+d5ed12c", GitCommit:"d5ed12c2580a64bf7125514c06435b4144a77e31", GitTreeState:"clean", BuildDate:"2021-09-17T23:43:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jkatz** [comment]
I followed the [instructions from the docs](https://access.crunchydata.com/documentation/postgres-operator/v5/installation/monitoring/kustomize/) and did not get an issue.

I did notice that your version of `kubectl` is not the latest 1.19.x release. I'd suggest trying to upgrade and seeing if that fixes things on your end. Also ensure that you are using the latest examples from `postgres-operator-examples`.

**Comment by hariyedlapalli** [comment]
Hi jkatz

Thank you , kubctl v1.21  worked for me .

Could you please guide me how can I use the existing PVC for BAckup on  postgres.yaml file ?

 24   backups:
 25     pgbackrest:
 26       image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
 27       repos:
 28       - name: repo1
 29         volume:
 30         #persistanceVolume:
 31         - name: crunchy-backup-pv
 32           persistentVolumeClaim:
 33             claimName: crunchy-backup
 
 Error message :
postgres-operator-examples-main]$ ~/kubectl apply -k kustomize/postgres
error: error validating "kustomize/postgres": error validating data: ValidationError(PostgresCluster.spec.backups.pgbackrest.repos[0].volume): invalid type for com.crunchydata.postgres-operator.v1beta1.PostgresCluster.spec.backups.pgbackrest.repos.volume: got "array", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
