### ISSUE TITLE
Postgres exporter stops sending disk related metrics after a while

### ISSUE THREAD

**Issue by momoadc** [CrunchyData/postgres-operator#2965]
Please ensure you do the following when reporting a bug:

- [x] Provide a concise description of what the bug is.
- [x] Provide information about your environment.
- [x] Provide clear steps to reproduce the bug.
- [x] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [x] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

After a while (about 2 months) I saw that the dashboards in Grafana stopped showing Disk Usage and Disk Activity metrics.
After debugging a bit I checked the metrics that were sent by the exporter sidecar and saw that no disk related metrics were created (data_disk_total_bytes, data_disk_available _bytes etc)

## Environment

Please provide the following details:

- Platform: `OpenShift`
- Platform Version: `4.8.24
- PGO Image Tag: (e.g. `ubi8-5.0.4-0`)
- Postgres Version (e.g. `13`)
- Storage: Isilon (nfs)

## Logs
 logs from the exporter are 
 `Error running query on database localhost:5432 : ccp_nodemx_data_disk pq: query-specified return tuple and function return type are not compatible

## Additional Information

I'm deploying the operator and PostgresClusters in a restricted network, so long logs and screenshots are unavailable

**Comment by momoadc** [comment]
After a lot of debugging, I resolved the problem and discovered a bigger issue
I've tried to run the same query to retrieve the data disk metrics. I figured out that the fsinfo function from pgnodemx returns a different data type and therefore the query fails (returns bigint instead of numeric). From there I found out that the pgnodemx version in the running database is lower than the one stated in crunchy 5.0.4. 
My conclusions were that the database was upgraded from 13.4 to 13.5 (when upgrading the operator from version v5.0.3 to v5.0.4) but the extensions didn't get the upgrade (pgnodemx from v1.1 to v1.2 and pgaudit from v1.5 to v1.5.1)
After upgrading the extension manually the metrics showed up

**Comment by jkatz** [comment]
There is an enhancement already under consideration around autoupgrading extensions -- this is a bit more of a packed topic than it may seem on the surface (e.g. does one want an extension to be upgraded?).

Specifically for metrics aggregation, the way to resolve this for the time being is to toggle off/on metrics collection on your Postgres cluster, or run `ALTER EXTENSION pgnodemx UPDATE` in each of the databases you are collecting metrics on (and `template1`). This won't affect the historical data you've collected as the visualization components are separate from that of the individual Postgres clusters.

**Comment by benjaminjb** [comment]
The https://github.com/CrunchyData/postgres-operator/pull/3400 should resolve these issues and is planned to be available in the next release, but not currently planned to be backpatched to v4. As noted, the manual fix should be to update the extensions used by the exporter, namely `pgnodemx` and `pg_stat_statements`.
