### ISSUE TITLE
Docs: Use "PG Instance" not "PG Cluster"

### ISSUE THREAD

**Issue by guettli** [CrunchyData/postgres-operator#2969]
## Overview

The term "PG cluster" is super confusing for people new to PostgreSQL.

Especially in the context of Kubernetes.

## Use Case

I am reading the docs, and I know what "PG cluster" means (one PG instance with one data-directory).

Nevertheless sometimes I need to read sentences in the docs twice because the term "cluster" has two meanings.

Why will it make it easier to use PGO?

If you avoid the term "PG cluster", then it would be easier for first-time users to understand the docs.

My suggestion is to use the term "PG instance". But it could be a different unique term, too.

## Desired Behavior

Docs should be easy to understand.

## Environment

I want learn K8s. I want to learn it by installing PGO in `kind`.

I use kind on my laptop, but have not installed PGO yet.

First I want to understand PGO

## Additional Information

Thank you very much for this great product.

**Comment by jkatz** [comment]
In the context of PGO, a Postgres cluster can be one or more instances, where an instance can be a Postgres primary or a replica. This is described in the ["What Just Happened"](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/create-cluster/#what-just-happened) section of the [Create a Postgres Cluster](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/create-cluster/) tutorial.

Potentially we can add a glossary, but the terminology appears to be consistent with Kubernetes (cluster vs. node/instance).

**Comment by guettli** [comment]
Thank you for the answer.
