### ISSUE TITLE
Tags for v5 releases

### ISSUE THREAD

**Issue by zerkms** [CrunchyData/postgres-operator#2970]
Is it deliberate that v5 does not have its own branch (and is developed in `master`) and is not tagged at all?

Thanks! :-)

**Comment by jkatz** [comment]
This is discussed in the documentation: https://access.crunchydata.com/documentation/postgres-operator/v5/faq/#where-are-the-release-tags-for-pgo-v5

**Comment by zerkms** [comment]
Does it mean there is no really way to know what commit it was built from?

https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator-5x

**Comment by zerkms** [comment]
@danielzhanghl yep, it could be that or any commit prior to that though.

**Comment by Jean-Daniel** [comment]
I read the doc but still don't get what prevents to create tag in GitHub for each release ? 

> These changes allow for more rapid feature development and releases in the upstream PGO project, while providing [Crunchy Postgres for Kubernetes](https://www.crunchydata.com/products/crunchy-postgresql-for-kubernetes/) users with stable releases for production use.

I hardly see how tagging a commit in GitHub is related to this explanation.
