### ISSUE TITLE
Postgres Cluster accessible only through Cluster IP of hippo-ha service, not a DNS name

### ISSUE THREAD

**Issue by InderpreetSaini** [CrunchyData/postgres-operator#2971]
Hi,

We are using the crunchydata postgres cluster to work as the Postgres external database for our Harbor HA setup.

We are able to access the Postgres cluster using the cluster IP of the Postgres hippo-ha service, but not able to refer the Postgres DB using a DNS name. As per our environment best practices, it should be referred by an unchanging DNS name not the clusterIP of the service.

Could you please suggest if there is any such DNS name that can be referred to use the service?

![image](https://user-images.githubusercontent.com/17871520/148723644-de544ec4-7183-4f50-aa17-33136dc33776.png)

Thanks and Regards,
Inderpreet.

**Comment by jkatz** [comment]
I suggest reading through the [Connect to a Postgres Cluster](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/connect-cluster/) section of the tutorial, which covers this topic.
