### ISSUE TITLE
Count reconciliation warnings

### ISSUE THREAD

**Issue by zerkms** [CrunchyData/postgres-operator#2985]
Have an idea to improve PGO? We'd love to hear it! We're going to need some information from you to learn more about your feature requests.

Please be sure you've done the following:

- [ ] Provide a concise description of your feature request.
- [ ] Describe your use case. Detail the problem you are trying to solve.
- [ ] Describe how you envision that the feature would work.
- [ ] Provide general information about your current PGO environment.

## Overview

Just as an experiment I checked what happens if I change the PVC size in the cluster manifest: from 2Gi down to 1Gi.

The operator happily "reconciled" it, even thought it also reported a warning:

```
time="2022-01-17T22:49:36Z" level=debug msg=Warning file="sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/recorder/recorder.go:98" func="recorder.(*Provider).getBroadcaster.func1.1" message="PersistentVolumeClaim \"db-db-l9t2-pgdata\" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value" object="{PostgresCluster clustername db a777b8b9-4d4d-462c-a5d7-e170c4af53e2 postgres-operator.crunchydata.com/v1beta1 243220699 }" reason=PersistentVolumeError version=5.0.4-0
```

I cannot see any exported metric that would count these occurrences.

So if it happens in the real cluster by mistake - there is a good chance nobody would ever pick it up.

## Use Case

To alert with prometheus in case if reconciliation is completed with warnings

## Desired Behavior

Some counter exposed that we may use to alert on

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.) kubernetes
- Platform Version: (e.g. `1.20.3`, `4.7.0`) 1.21, 5.0.4
- PGO Image Tag: (e.g. `ubi8-5.1.0-0`) ubi8-5.0.4-0
- Postgres Version (e.g. `14`) 14
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class) pvc
- Number of Postgres clusters: (`XYZ`)

## Additional Information

Please provide any additional information that may be helpful.

**Comment by andrewlecuyer** [comment]
@zerkms we create an event for the PostgresCluster if/when you attempt to reduce the PVC size.  

For instance, you can see this event when describing the PostgresCluster after attempting to change the size of an PG instance PVC (`hippo-instance1-hkn5-pgdata`) from `2Gi` to `1Gi`:

```bash
$ kubectl describe postgrescluster hippo
...
Events:
  Type     Reason                 Age    From                        Message
  ----     ------                 ----   ----                        -------
  Normal   RepoHostCreated        10m    postgrescluster-controller  created pgBackRest repository host StatefulSet/hippo-repo-host
  Normal   StanzasCreated         9m19s  postgrescluster-controller  pgBackRest stanza creation completed successfully
  Warning  UnableToCreateStanzas  9m10s  postgrescluster-controller  command terminated with exit code 50: ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-backup.lock': Resource temporarily unavailable
       HINT: is another pgBackRest process running?
  Warning  PersistentVolumeError  1s (x4 over 12s)  postgrescluster-controller  PersistentVolumeClaim "hippo-instance1-hkn5-pgdata" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value
```

Therefore, just like native Kubernetes resources (Pod's, etc.) expose various warnings, information, issues, etc. via events, so too does PGO.
