### ISSUE TITLE
Getting FATAL:  extension "timescaledb" must be preloaded with PGO 4.7.4 instance

### ISSUE THREAD

**Issue by nagannv** [CrunchyData/postgres-operator#3005]
I am getting `FATAL:  extension "timescaledb" must be preloaded `while trying to copy the existing Database dump into PGO 4.7.4 instance
Could you please help me with approach to overcome the issue

## Environment
- Platform: (`Kubernetes`.)
- pgo_client_version: "4.7.4"
- ccp_image_tag: "centos8-13.5-4.7.4"

## Logs

```
FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: /pgdata/kcpgo/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
        # Modify postgresql.conf:
        shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
        echo "shared_preload_libraries = 'timescaledb'" >> /pgdata/kcpgo/postgresql.conf

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with:
        SET timescaledb.allow_install_without_preload = 'on';
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
connection to server was lost
```

**Comment by andrewlecuyer** [comment]
@nagannv can you provide the specific steps, commands, etc. that you are using to create your cluster and then copy the existing DB dump into the PG cluster?

**Comment by nagannv** [comment]
@andrewlecuyer , I have followed below steps.

1. Create name space
`kubectl create ns pgo`

2. Apply postgres-operator.yml
`kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.7.4/installers/kubectl/postgres-operator.yml`
3. Setup pgo client
```
curl https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.7.4/installers/kubectl/client-setup.sh > client-setup.sh
chmod +x client-setup.sh
. client-setup.sh
```
4. Configure port-forward 
`kubectl -n pgo port-forward svc/postgres-operator 8443:8443&`

5. Create DB cluster
`pgo create cluster kcpgo`

6. Update user credentials
```
pgo update user --selector=name=kcpgo --username=testuser --password=<password> --set-system-account-password
pgo update user --selector=name=kcpgo --username=postgres --password=<password> --set-system-account-password
pgo update user --selector=name=kcpgo --username=primaryuser --password=<password> --set-system-account-password
```
7. Configiure the port-forward for kcpgo db instance
`kubectl -n pgo port-forward svc/kcpgo 5432:5432 &`

8. Copy postgres dump taken from another db instance enabled with timescaledb1.7version
`cat pgsql-jan2022.sql |  psql -h localhost -p 5432 -U postgres kcpgo;`

result:

In-between the copy, the session is terminating with below error
```

 set_config
------------

(1 row)

SET
SET
SET
SET
FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: /pgdata/kcpgo/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
        # Modify postgresql.conf:
        shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
        echo "shared_preload_libraries = 'timescaledb'" >> /pgdata/kcpgo/postgresql.conf

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with:
        SET timescaledb.allow_install_without_preload = 'on';
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
connection to server was lost
```

**Comment by andrewlecuyer** [comment]
@nagannv you will need to create and apply the proper custom configuration when creating your cluster to ensure the `shared_preload_libraries` setting includes `timescaledb` per the error you are seeing.

Please see the "Create a PostgreSQL Cluster With Custom Configuration" in the [Custom Configuration documentation](https://access.crunchydata.com/documentation/postgres-operator/4.7.4/advanced/custom-configuration/) for instructions on how to customize various PG settings (e.g. `shared_preload_libraries`) when bootstrapping your cluster.

**Comment by nagannv** [comment]
@andrewlecuyer , Thank you for your response. I will create following config map as suggested

**Comment by nagannv** [comment]
@andrewlecuyer, thank you for your response, I am planning to create the following config map, but have a query with regard injecting/mounting the file in v4 version. I mean to say for v5 there is an example ( in https://blog.crunchydata.com/blog/using-timescaledb-extension-with-the-pgo-the-postgres-operator ) where the `dynamicConfiguration ` has been applied under `patroni:` section.  
For the 4.7.4, if there is sample configuration available, could you please help me with sample configuration

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgo-ts-config
data:
  bootstrap:
    dcs:
      postgresql:
        parameters:
          shared_preload_libraries: timescale

```

**Comment by nagannv** [comment]
Thank you @andrewlecuyer 

1. Update postgres-ha.yaml  file with the to enable  timescaledb extension

```
---
bootstrap:
  dcs:
    postgresql:
      parameters:
        shared_preload_libraries: timescaledb
```
2.  create configmap from the file
`kubectl -n pgo create configmap ts-config --from-file=postgres-ha.yaml`

3. Create pgo cluster using config map

`pgo create cluster hippo -n pgo --custom-config=ts-config`

4. check weather timescaledb extension got enabled either by logging into PGO pod or accessing the DB instance
```
psql -h localhost -p 5432 -U postgres hippo
SHOW shared_preload_libraries 
```

**Comment by benjaminjb** [comment]
@nagannv Are you still experiencing the problem after following the documentation that Andrew pointed out?
