### ISSUE TITLE
For v5 installtion through Kustomize manifest , pgAdmin not available

### ISSUE THREAD

**Issue by sambeet99** [CrunchyData/postgres-operator#3013]
We can install PGO by 2 ways - (1) Postgres Operator Installer (https://access.crunchydata.com/documentation/postgres-
operator/latest/quickstart/) - v4
(2) Kustomize yaml (kubectl apply -k kustomize/install) - v5

In v4 , we can install pgAdmin into our kubernates cluster by pgo command. But in v5 we don't have any facilities to install pgAdmin.

How to access v5 postgres by pgAdmin ?

**Comment by andrewlecuyer** [comment]
Support for pgAdmin in PGO v5 will be included in the upcoming PGO v5.1.0 release.
