### ISSUE TITLE
"primary pod not found" error message after scheduling PGO pods on a new node 

### ISSUE THREAD

**Issue by nagannv** [CrunchyData/postgres-operator#3014]
After draining kubernetes nodes, the PGO pods are getting scheduling on new node as expected but the observing "primary pod not found" message, since DB instances are down the observing service outage at the application level, to recover from the situation it is required to reload the db dump manually after recreating PGO clusters

```
$ pgo show user -n pgo sxxxxx --show-system-accounts
Handling connection for 8443

CLUSTER USERNAME PASSWORD EXPIRES STATUS ERROR
------- -------- -------- ------- ------ -----------------------------------------------------------------
                                  error  primary pod not found for selector "pg-cluster=sxxxxx,role=master"
```

```
$ psql -h localhost -p 6432 -U postgres sxxxxx
psql: error: connection to server at "localhost" (127.0.0.1), port 6432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
```

I have created PGO cluster using the below command, and application was working as expected by making us of PGO DB instance

```
pgo create cluster sxxxx --pgbouncer --replica-count=1 \
  --sync-replication --pvc-size=10Gi \
  --pgbackrest-pvc-size=10Gi \
  --pgbackrest-storage-type=posix,s3 \
  --pgbackrest-s3-key=<s3-key> \
  --pgbackrest-s3-key-secret=<s3-key-secret> \
  --pgbackrest-s3-bucket=s3-bucket-name \
  --pgbackrest-s3-endpoint=s3.amazonaws.com \
  --pgbackrest-s3-region=ap-southeast-2 \
  --password-superuser=xxxxxxxxx \
  --password-replication=xxxxxxxxx \
  --password=xxxxxxxxx \
  --username sxxxxclusteruser
```

```
ubuntu@prodagdrgen3adminvm:~$ kubectl get pods -n pgo
NAME                                             READY   STATUS      RESTARTS   AGE
backrest-backup-sxxxxx-vlnl9                   0/1     Completed   0          14h
postgres-operator-6f5b559fd7-b5flc             4/4     Running     1          13h
sxxxxx-66f7778fc9-nvlns                        1/1     Running     0          14h
sxxxxx-backrest-shared-repo-68666c5b8d-4zcmg   1/1     Running     0          13h
sxxxxx-pgbouncer-5fb86dc978-jtbs2              1/1     Running     0          13h
sxxxxx-ywkv-85465f84d9-zqdsh                   1/1     Running     0          13h
```

However, for the past one month we are observing regular service outage when our openstack cloud service provider make any changes to k8s cluster maintenance activities ( includes repairing/draining of nodes or auto healing of the cluster ). Due to the maintenance tasks, the PGO pods are getting scheduled on new nodes, but non availability of primary pod( as shown in the below error message) observing service outage at application level.

```
$ pgo show user -n pgo sxxxxx --show-system-accounts
Handling connection for 8443

CLUSTER USERNAME PASSWORD EXPIRES STATUS ERROR
------- -------- -------- ------- ------ -----------------------------------------------------------------
                                  error  primary pod not found for selector "pg-cluster=sxxxxx,role=master"

$ psql -h localhost -p 6432 -U postgres sxxxxx
psql: error: connection to server at "localhost" (127.0.0.1), port 6432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

$kubectl drain <Node> --ignore-daemonsets --delete-emptydir-data
```

To reproduce the issue I have tried draining the nodes associated with PGO pods ( to replicate service provider maintenance activities), as PGO pods are bound to local storage the node drain activity is not proceeding unless we use --ignore-daemonsets --delete-emptydir-data flags

```
$  kubectl drain dxxxx-node-21
node/ drain dxxxx-node-21 cordoned
error: unable to drain node " drain dxxxx-node-21" due to error:[cannot delete Pods with local storage (use --delete-emptydir-data to override):pgo/sheepdog-backrest-shared-repo-68666c5b8d-4zcmg, pgo/sheepdog-ywkv-85465f84d9-zqdsh, cannot delete DaemonSet-managed Pods (use --ignore-daemonsets to ignore): kube-system/calico-node-4dzr7, kube-system/csi-cinder-nodeplugin-8fwxk, kube-system/npd-bps2x, logging/fluentd-nzpgt, prometheus/prometheus-node-exporter-qrggm], continuing command...
There are pending nodes to be drained:
  drain dxxxx-node-21
```

After draining the nodes with kubectl drain < node name> --ignore-daemonsets --delete-emptydir-data, the PGO pods are getting created on another/new nodes, and the issue is reproduced.

From "cannot delete Pods with local storage (use --delete-emptydir-data to override) " message I feel the root cause of issue is due to usage of local storage.

As previously mentioned I am using following command to create cluster, want to know whether I am missing to assign the storage while creating the cluster or missing any important configuration resulting service outage?

```
pgo create cluster sxxxx --pgbouncer --replica-count=1 \
  --sync-replication --pvc-size=10Gi \
  --pgbackrest-pvc-size=10Gi \
  --pgbackrest-storage-type=posix,s3 \
  --pgbackrest-s3-key=<s3-key> \
  --pgbackrest-s3-key-secret=<s3-key-secret> \
  --pgbackrest-s3-bucket=s3-bucket-name \
  --pgbackrest-s3-endpoint=s3.amazonaws.com \
  --pgbackrest-s3-region=ap-southeast-2 \
  --password-superuser=xxxxxxxxx \
  --password-replication=xxxxxxxxx \
  --password=xxxxxxxxx \
  --username sxxxxclusteruser

```
To use openstack storage volumes, I have update the postgres-operator.yml with following change for in the storage class section, remaining all configurations are set to the default

```
 backrest_storage: "default"
    backup_storage: "default"
    primary_storage: "default"
    replica_storage: "default"
    pgadmin_storage: "default"
    wal_storage: ""
    storage1_name: "default"
    storage1_access_mode: "ReadWriteOnce"
    storage1_size: "1G"
    storage1_type: "dynamic"
    storage1_class: "b1.standard"
```

## Environment

- Platform: ( Openstack.)
- PGO version 4.7.4

**Comment by andrewlecuyer** [comment]
Thank you for the detailed submission.

Can you please provide a copy of the logs from the PG Pod _after_ it is rescheduled?  Additionally, could you provide the output of doing a `kubectl describe` on that same Pod?

**Comment by nagannv** [comment]
Hi @andrewlecuyer 
Please find the attached logs
[logs.log](https://github.com/CrunchyData/postgres-operator/files/7998787/logs.log)

**Comment by nagannv** [comment]
@andrewlecuyer , could you please share you have any recommendations/inputs based logs, or the syntax which I am using to create the cluster.

**Comment by nagannv** [comment]
A similar issue reported by another user - "postgres cluster becomes unhealthy after draining one of the worker nodes"
https://www.postgresql.org/message-id/71de8e84252d4becbb76b622787b5251%40gmsEXCH1201.gms.ca

**Comment by nagannv** [comment]
@andrewlecuyer , after configuring HA cluster, the "primary pod not found"  is no longer present after draining the nodes for testing purpose. could you please comment whether not having HA configuration resulting "primary pod not found" while draining the nodes,.

Now with HA config, after draining the node the application is accessible without any issues and can see the primary (`INFO: no action. I am (fence-zutr-6c6d476cdc-schjs) the leader with the lock`)and second (  `INFO: no action. I am a secondary (hippo-78f5b4dcd5-tkwv6) and following a leader (hippo-zutr-6c6d476cdc-schjs` and` INFO: no action. I am a secondary (hipp-dcwe-848cb5975f-5sgxj) and following a leader (hippo-zutr-6c6d476cdc-schjs)`) association messages in the pods

```
pgo create cluster hippo --pgbouncer --replica-count=2 \
--pod-anti-affinity=preferred \
--sync-replication --pvc-size=10Gi \
--pgbackrest-pvc-size=10Gi \
--pgbackrest-storage-type=posix,s3 \
--pgbackrest-s3-key=xxxxxxxxxxxx \
--pgbackrest-s3-key-secret=xxxxxxxxxxxx \
--pgbackrest-s3-bucket=xxxxxxxxxxxx \
--pgbackrest-s3-endpoint=s3.amazonaws.com \
--pgbackrest-s3-region=ap-southeast-2 \
--password-superuser=xxxxxxxxxxxx \
--password-replication=xxxxxxxxxxxx \
--password=xxxxxxxxxxxx  \
--username hippoclusteruser
```

```
hippo-78f5b4dcd5-tkwv6                           1/1     Running     0          56m
hippo-backrest-shared-repo-5d9c567f84-s8rvr      1/1     Running     0          105m
hippo-dcwe-848cb5975f-5sgxj                      1/1     Running     0          56m
hippo-pgbouncer-56bf8b55c4-rl9jx                 1/1     Running     0          93m
hippo-stanza-create-kp7z4                        0/1     Completed   0          102m
hippo-zutr-6c6d476cdc-schjs                      1/1     Running     0          74m
```

**Comment by nagannv** [comment]
as a part of testing HA solution, drained the node in the 4 node cluster one by one using below command

kubectl drain <Node name> --ignore-daemonsets --delete-emptydir-data

On every instance draining the UI components acre accessible and PGO cluster was healthy till draining of last node. thought that HA solution has taken the original issue reported (`primary pod not found`)

But, on draining the last node the PGO cluster became unhealthy `( INFO: following a different leader because i am not the healthiest node)` i.e the issue that I observed is similar to https://www.postgresql.org/message-id/71de8e84252d4becbb76b622787b5251%40gmsEXCH1201.gms.ca


Please help us if there if any solution for the issue describe in https://www.postgresql.org/message-id/71de8e84252d4becbb76b622787b5251%40gmsEXCH1201.gms.ca

**Comment by andrewlecuyer** [comment]
Hi @nagannv!

In Crunchy Postgres for Kubernetes v5, Pod disruption Budgets (PDB's) and other related improvements have been implemented to improve PGO behavior related to Kubernetes cluster node restarts, node draining, etc.

As such, we recommend upgrading to Crunchy Postgres for Kubernetes v5.  Please see the following for documentation for more information about both PDB's in v5, as well as guidance for upgrading from v4:

- https://access.crunchydata.com/documentation/postgres-operator/latest/
- https://access.crunchydata.com/documentation/postgres-operator/5.3.1/architecture/high-availability/#pod-disruption-budgets
- https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/v4tov5/

And If you are still encountering any related issues with v5, please feel free to submit a new issue.
