### ISSUE TITLE
pgo 5: pgbackrest does not expire old backups

### ISSUE THREAD

**Issue by MarkusKepert** [CrunchyData/postgres-operator#3020]
Hi,

i have an issue with pgbackrest auto expiration of backups.

Repo1: local volume in kubernetes repo1-host pod with 100GB backup volume
Repo2: Remote storage in S3 compatible storage

Backup works well, but repo1 volume is filled up and backups are not expired automatically Using pgbackrest expire on shell i am able to expire backupsets and free up spaces used.

Is this an config issue or a bug? Not sure....

Using PGO 5.0.3 on Kubernetes 1.19

This is my pgbackrest config in operator values.yaml:
pgBackRestConfig:
  global:
    repo1-retention-full: "2"
    repo1-retention-full-type: time
    repo2-s3-key: XU3232502R0OID0NCDC3751H
    repo2-s3-key-secret: S2T5b9wPUFypQv1YTSFaIA06wKIqboi2
    repo2-s3-uri-style: path
    repo2-retention-full: "14"
    repo2-retention-full-type: time
  repos:
  - name: repo1
    schedules:
      full: "1 0 * * *"
      incremental: "0 5-22 * * *"
    volume:
      volumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 140Gi
  - name: repo2
    schedules:
      full: "0 2 * * *"
    s3:
      bucket: "backup-extranet-prod"
      endpoint: "backupstorage.dgv-intranet.de"
      region: "us-west-1"

Is this an issue in pgo or an issue in my config?

**Comment by MarkusKepert** [comment]
Thanks @jmckulk
Yes, it should keep backups for 2 days. Anyway....i does not have access to that system anymore (switch company) but in the last 2 weeks i didn't get any response from collegues that there is a problem. They changed something in incremental.

**Comment by larspl** [comment]
@jmckulk 
pgbackrest info
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (14): 0000000A000000BA00000043/00000022000000F40000007C

        full backup: 20220425-030017F
            timestamp start/stop: 2022-04-25 03:00:17 / 2022-04-25 04:23:06
            wal start/stop: 0000000A000000BA00000043 / 0000000A000000BA0000004A
            database size: 16.1GB, database backup size: 16.1GB
            repo2: backup set size: 3.0GB, backup size: 3.0GB

        full backup: 20220426-030015F
            timestamp start/stop: 2022-04-26 03:00:15 / 2022-04-26 04:05:02
            wal start/stop: 0000000A000000BB00000005 / 0000000A000000BB0000000D
            database size: 16GB, database backup size: 16GB
            repo2: backup set size: 3.0GB, backup size: 3.0GB

        full backup: 20220427-030015F
            timestamp start/stop: 2022-04-27 03:00:15 / 2022-04-27 03:50:05
            wal start/stop: 0000000A000000BB000000D5 / 0000000A000000BB000000DA
            database size: 16GB, database backup size: 16GB
            repo2: backup set size: 3GB, backup size: 3GB

        full backup: 20220428-030011F
            timestamp start/stop: 2022-04-28 03:00:11 / 2022-04-28 03:45:29
            wal start/stop: 0000000A000000BC000000C5 / 0000000A000000BC000000CE
            database size: 16.1GB, database backup size: 16.1GB
            repo2: backup set size: 3GB, backup size: 3GB

        full backup: 20220429-030007F
            timestamp start/stop: 2022-04-29 03:00:07 / 2022-04-29 03:48:52
            wal start/stop: 0000000A000000BD000000CD / 0000000A000000BD000000D2
            database size: 16.2GB, database backup size: 16.2GB
            repo2: backup set size: 3GB, backup size: 3GB

        full backup: 20220430-030008F
            timestamp start/stop: 2022-04-30 03:00:08 / 2022-04-30 04:04:34
            wal start/stop: 0000000A000000BF0000005A / 0000000A000000BF00000069
            database size: 16.2GB, database backup size: 16.2GB
            repo2: backup set size: 3GB, backup size: 3GB

        full backup: 20220501-030013F
            timestamp start/stop: 2022-05-01 03:00:13 / 2022-05-01 04:00:36
            wal start/stop: 0000000A000000C00000006A / 0000000A000000C00000006E
            database size: 16.3GB, database backup size: 16.3GB
            repo2: backup set size: 3GB, backup size: 3GB

        full backup: 20220502-030012F
            timestamp start/stop: 2022-05-02 03:00:12 / 2022-05-02 04:04:24
            wal start/stop: 0000000A000000C100000016 / 0000000A000000C10000001A
            database size: 16.3GB, database backup size: 16.3GB
            repo2: backup set size: 3GB, backup size: 3GB

        full backup: 20220503-030011F
            timestamp start/stop: 2022-05-03 03:00:11 / 2022-05-03 03:49:39
            wal start/stop: 0000000A000000C1000000B6 / 0000000A000000C1000000B9
            database size: 16.4GB, database backup size: 16.4GB
            repo2: backup set size: 3GB, backup size: 3GB

        full backup: 20220504-030006F
            timestamp start/stop: 2022-05-04 03:00:06 / 2022-05-04 03:58:50
            wal start/stop: 0000000A000000C3000000B1 / 0000000A000000C3000000B6
            database size: 16.5GB, database backup size: 16.5GB
            repo2: backup set size: 3.1GB, backup size: 3.1GB

        full backup: 20220505-030011F
            timestamp start/stop: 2022-05-05 03:00:11 / 2022-05-05 03:49:28
            wal start/stop: 0000000B000000C4000000B2 / 0000000B000000C4000000B5
            database size: 16.5GB, database backup size: 16.5GB
            repo2: backup set size: 3.1GB, backup size: 3.1GB

        full backup: 20220506-030017F
            timestamp start/stop: 2022-05-06 03:00:17 / 2022-05-06 04:05:23
            wal start/stop: 0000000B000000C600000040 / 0000000B000000C600000049
            database size: 16.7GB, database backup size: 16.7GB
            repo2: backup set size: 3.2GB, backup size: 3.2GB

        full backup: 20220507-030010F
            timestamp start/stop: 2022-05-07 03:00:10 / 2022-05-07 04:30:21
            wal start/stop: 0000000B000000C7000000C1 / 0000000B000000C7000000C9
            database size: 16.9GB, database backup size: 16.9GB
            repo2: backup set size: 3.2GB, backup size: 3.2GB

        full backup: 20220508-000106F
            timestamp start/stop: 2022-05-08 00:01:06 / 2022-05-08 00:17:41
            wal start/stop: 0000000B000000CA0000002B / 0000000B000000CA00000035
            database size: 17.5GB, database backup size: 17.5GB
            repo1: backup set size: 3.4GB, backup size: 3.4GB

        full backup: 20220508-030012F
            timestamp start/stop: 2022-05-08 03:00:12 / 2022-05-08 03:55:50
            wal start/stop: 0000000B000000CA00000093 / 0000000B000000CA00000096
            database size: 17.6GB, database backup size: 17.6GB
            repo2: backup set size: 3.4GB, backup size: 3.4GB

        full backup: 20220509-000116F
            timestamp start/stop: 2022-05-09 00:01:16 / 2022-05-09 00:14:37
            wal start/stop: 0000000B000000CC0000009D / 0000000B000000CC0000009F
            database size: 18.2GB, database backup size: 18.2GB
            repo1: backup set size: 3.5GB, backup size: 3.5GB

        full backup: 20220509-030011F
            timestamp start/stop: 2022-05-09 03:00:11 / 2022-05-09 04:01:11
            wal start/stop: 0000000B000000CD00000021 / 0000000B000000CD00000048
            database size: 18.5GB, database backup size: 18.5GB
            repo2: backup set size: 3.6GB, backup size: 3.6GB

        incr backup: 20220509-000116F_20220509-145523I
            timestamp start/stop: 2022-05-09 14:55:23 / 2022-05-09 15:03:23
            wal start/stop: 0000000B000000CF0000005A / 0000000B000000CF0000005F
            database size: 19.5GB, database backup size: 9.8GB
            repo1: backup set size: 3.7GB, backup size: 2.8GB
            backup reference list: 20220509-000116F

        incr backup: 20220509-000116F_20220509-160006I
            timestamp start/stop: 2022-05-09 16:00:06 / 2022-05-09 16:10:43
            wal start/stop: 0000000D000000CF000000FA / 0000000D000000D000000008
            database size: 19.5GB, database backup size: 12.4GB
            repo1: backup set size: 3.7GB, backup size: 3.3GB
            backup reference list: 20220509-000116F, 20220509-000116F_20220509-145523I

        incr backup: 20220509-000116F_20220509-170008I
            timestamp start/stop: 2022-05-09 17:00:08 / 2022-05-09 17:08:09
            wal start/stop: 0000000D000000D000000049 / 0000000D000000D00000004F
            database size: 19.6GB, database backup size: 9.4GB
            repo1: backup set size: 3.7GB, backup size: 2.5GB
            backup reference list: 20220509-000116F, 20220509-000116F_20220509-145523I, 20220509-000116F_20220509-160006I

        incr backup: 20220509-000116F_20220509-180010I
            timestamp start/stop: 2022-05-09 18:00:10 / 2022-05-09 18:08:21
            wal start/stop: 0000000D000000D00000008B / 0000000D000000D000000094
            database size: 19.6GB, database backup size: 10.4GB
            repo1: backup set size: 3.7GB, backup size: 2.9GB
            backup reference list: 20220509-000116F, 20220509-000116F_20220509-145523I, 20220509-000116F_20220509-160006I, 20220509-000116F_20220509-170008I

        incr backup: 20220509-000116F_20220509-190009I
            timestamp start/stop: 2022-05-09 19:00:09 / 2022-05-09 19:07:56
            wal start/stop: 0000000D000000D0000000CC / 0000000D000000D0000000D4
            database size: 19.6GB, database backup size: 9.4GB
            repo1: backup set size: 3.7GB, backup size: 2.5GB
            backup reference list: 20220509-000116F, 20220509-000116F_20220509-145523I, 20220509-000116F_20220509-160006I, 20220509-000116F_20220509-170008I, 20220509-000116F_20220509-180010I

        incr backup: 20220509-000116F_20220509-200015I
            timestamp start/stop: 2022-05-09 20:00:15 / 2022-05-09 20:09:07
            wal start/stop: 0000000D000000D0000000FE / 0000000D000000D100000004
            database size: 19.7GB, database backup size: 10.4GB
            repo1: backup set size: 3.7GB, backup size: 2.9GB
            backup reference list: 20220509-000116F, 20220509-000116F_20220509-145523I, 20220509-000116F_20220509-160006I, 20220509-000116F_20220509-170008I, 20220509-000116F_20220509-180010I, 20220509-000116F_20220509-190009I

        incr backup: 20220509-000116F_20220509-210011I
            timestamp start/stop: 2022-05-09 21:00:11 / 2022-05-09 21:07:15
            wal start/stop: 0000000D000000D100000026 / 0000000D000000D10000002B
            database size: 19.7GB, database backup size: 9.5GB
            repo1: backup set size: 3.7GB, backup size: 2.5GB
            backup reference list: 20220509-000116F, 20220509-000116F_20220509-145523I, 20220509-000116F_20220509-160006I, 20220509-000116F_20220509-170008I, 20220509-000116F_20220509-180010I, 20220509-000116F_20220509-190009I, 20220509-000116F_20220509-200015I

        incr backup: 20220509-000116F_20220509-220015I
            timestamp start/stop: 2022-05-09 22:00:15 / 2022-05-09 22:06:29
            wal start/stop: 0000000D000000D100000048 / 0000000D000000D10000004C
            database size: 19.7GB, database backup size: 9.4GB
            repo1: backup set size: 3.7GB, backup size: 2.5GB
            backup reference list: 20220509-000116F, 20220509-000116F_20220509-145523I, 20220509-000116F_20220509-160006I, 20220509-000116F_20220509-170008I, 20220509-000116F_20220509-180010I, 20220509-000116F_20220509-190009I, 20220509-000116F_20220509-200015I, 20220509-000116F_20220509-210011I

        full backup: 20220510-000110F
            timestamp start/stop: 2022-05-10 00:01:10 / 2022-05-10 00:22:09
            wal start/stop: 0000000D000000D1000000CF / 0000000D000000D1000000EE
            database size: 19.8GB, database backup size: 19.8GB
            repo1: backup set size: 3.8GB, backup size: 3.8GB

        full backup: 20220510-020015F
            timestamp start/stop: 2022-05-10 02:00:15 / 2022-05-10 03:36:53
            wal start/stop: 0000000D000000D20000007F / 0000000D000000D200000093
            database size: 19.9GB, database backup size: 19.9GB
            repo2: backup set size: 3.8GB, backup size: 3.8GB

        incr backup: 20220510-000110F_20220510-050017I
            timestamp start/stop: 2022-05-10 05:00:17 / 2022-05-10 05:06:45
            wal start/stop: 0000000D000000D2000000A8 / 0000000D000000D2000000A9
            database size: 19.9GB, database backup size: 9.6GB
            repo1: backup set size: 3.8GB, backup size: 2.6GB
            backup reference list: 20220510-000110F

        incr backup: 20220510-000110F_20220510-060008I
            timestamp start/stop: 2022-05-10 06:00:08 / 2022-05-10 06:06:40
            wal start/stop: 0000000D000000D2000000B8 / 0000000D000000D2000000B9
            database size: 19.9GB, database backup size: 9.6GB
            repo1: backup set size: 3.8GB, backup size: 2.5GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I

        incr backup: 20220510-000110F_20220510-070018I
            timestamp start/stop: 2022-05-10 07:00:18 / 2022-05-10 07:08:34
            wal start/stop: 0000000D000000D2000000E0 / 0000000D000000D2000000E6
            database size: 19.9GB, database backup size: 10.7GB
            repo1: backup set size: 3.8GB, backup size: 2.9GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-060008I

        incr backup: 20220510-000110F_20220510-080007I
            timestamp start/stop: 2022-05-10 08:00:07 / 2022-05-10 08:07:28
            wal start/stop: 0000000D000000D300000003 / 0000000D000000D300000006
            database size: 19.9GB, database backup size: 9.7GB
            repo1: backup set size: 3.8GB, backup size: 2.6GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-060008I, 20220510-000110F_20220510-070018I

        incr backup: 20220510-000110F_20220510-090009I
            timestamp start/stop: 2022-05-10 09:00:09 / 2022-05-10 09:07:57
            wal start/stop: 0000000D000000D30000006F / 0000000D000000D300000071
            database size: 19.9GB, database backup size: 9.7GB
            repo1: backup set size: 3.8GB, backup size: 2.6GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-060008I, 20220510-000110F_20220510-070018I, 20220510-000110F_20220510-080007I

        incr backup: 20220510-000110F_20220510-100016I
            timestamp start/stop: 2022-05-10 10:00:16 / 2022-05-10 10:06:49
            wal start/stop: 0000000D000000D300000082 / 0000000D000000D300000084
            database size: 19.9GB, database backup size: 9.3GB
            repo1: backup set size: 3.8GB, backup size: 2.4GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-070018I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I

        incr backup: 20220510-000110F_20220510-110016I
            timestamp start/stop: 2022-05-10 11:00:16 / 2022-05-10 11:07:42
            wal start/stop: 0000000D000000D3000000C8 / 0000000D000000D3000000CF
            database size: 20.0GB, database backup size: 9.3GB
            repo1: backup set size: 3.8GB, backup size: 2.5GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-070018I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I

        incr backup: 20220510-000110F_20220510-120012I
            timestamp start/stop: 2022-05-10 12:00:12 / 2022-05-10 12:07:16
            wal start/stop: 0000000D000000D3000000F0 / 0000000D000000D3000000F2
            database size: 20.0GB, database backup size: 9.3GB
            repo1: backup set size: 3.8GB, backup size: 2.5GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-070018I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-110016I

        incr backup: 20220510-000110F_20220510-130017I
            timestamp start/stop: 2022-05-10 13:00:17 / 2022-05-10 13:07:59
            wal start/stop: 0000000D000000D40000000A / 0000000D000000D40000000C
            database size: 20.0GB, database backup size: 9.4GB
            repo1: backup set size: 3.8GB, backup size: 2.5GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-070018I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-110016I, 20220510-000110F_20220510-120012I

        incr backup: 20220510-000110F_20220510-140006I
            timestamp start/stop: 2022-05-10 14:00:06 / 2022-05-10 14:13:13
            wal start/stop: 0000000E000000D40000007F / 0000000E000000D400000088
            database size: 20GB, database backup size: 13.0GB
            repo1: backup set size: 3.8GB, backup size: 3.4GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-110016I, 20220510-000110F_20220510-130017I

        incr backup: 20220510-000110F_20220510-150012I
            timestamp start/stop: 2022-05-10 15:00:12 / 2022-05-10 15:09:04
            wal start/stop: 0000000E000000D4000000AF / 0000000E000000D4000000B4
            database size: 20.1GB, database backup size: 9.9GB
            repo1: backup set size: 3.8GB, backup size: 2.6GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-130017I, 20220510-000110F_20220510-140006I

        incr backup: 20220510-000110F_20220510-160015I
            timestamp start/stop: 2022-05-10 16:00:15 / 2022-05-10 16:07:53
            wal start/stop: 0000000E000000D4000000D0 / 0000000E000000D4000000D1
            database size: 20.2GB, database backup size: 11.0GB
            repo1: backup set size: 3.8GB, backup size: 2.8GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-130017I, 20220510-000110F_20220510-140006I, 20220510-000110F_20220510-150012I

        incr backup: 20220510-000110F_20220510-170010I
            timestamp start/stop: 2022-05-10 17:00:10 / 2022-05-10 17:07:58
            wal start/stop: 0000000E000000D4000000F1 / 0000000E000000D4000000F5
            database size: 20.2GB, database backup size: 10GB
            repo1: backup set size: 3.9GB, backup size: 2.6GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-130017I, 20220510-000110F_20220510-140006I, 20220510-000110F_20220510-150012I, 20220510-000110F_20220510-160015I

        incr backup: 20220510-000110F_20220510-180013I
            timestamp start/stop: 2022-05-10 18:00:13 / 2022-05-10 18:08:03
            wal start/stop: 0000000E000000D500000014 / 0000000E000000D500000019
            database size: 20.3GB, database backup size: 10.1GB
            repo1: backup set size: 3.9GB, backup size: 2.7GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-130017I, 20220510-000110F_20220510-140006I, 20220510-000110F_20220510-150012I, 20220510-000110F_20220510-160015I, 20220510-000110F_20220510-170010I

        incr backup: 20220510-000110F_20220510-190017I
            timestamp start/stop: 2022-05-10 19:00:17 / 2022-05-10 19:10:31
            wal start/stop: 0000000E000000D500000044 / 0000000E000000D500000046
            database size: 20.4GB, database backup size: 10.2GB
            repo1: backup set size: 3.9GB, backup size: 2.7GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-130017I, 20220510-000110F_20220510-140006I, 20220510-000110F_20220510-150012I, 20220510-000110F_20220510-160015I, 20220510-000110F_20220510-170010I, 20220510-000110F_20220510-180013I

        incr backup: 20220510-000110F_20220510-200009I
            timestamp start/stop: 2022-05-10 20:00:09 / 2022-05-10 20:11:38
            wal start/stop: 0000000E000000D500000050 / 0000000E000000D500000053
            database size: 20.5GB, database backup size: 11.2GB
            repo1: backup set size: 3.9GB, backup size: 3GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-130017I, 20220510-000110F_20220510-140006I, 20220510-000110F_20220510-150012I, 20220510-000110F_20220510-160015I, 20220510-000110F_20220510-170010I, 20220510-000110F_20220510-180013I, 20220510-000110F_20220510-190017I

        incr backup: 20220510-000110F_20220510-210013I
            timestamp start/stop: 2022-05-10 21:00:13 / 2022-05-10 21:07:00
            wal start/stop: 0000000E000000D50000005E / 0000000E000000D50000005F
            database size: 20.5GB, database backup size: 10.2GB
            repo1: backup set size: 3.9GB, backup size: 2.7GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-130017I, 20220510-000110F_20220510-140006I, 20220510-000110F_20220510-150012I, 20220510-000110F_20220510-160015I, 20220510-000110F_20220510-170010I, 20220510-000110F_20220510-180013I, 20220510-000110F_20220510-190017I, 20220510-000110F_20220510-200009I

        incr backup: 20220510-000110F_20220510-220014I
            timestamp start/stop: 2022-05-10 22:00:14 / 2022-05-10 22:07:20
            wal start/stop: 0000000E000000D500000067 / 0000000E000000D500000068
            database size: 20.5GB, database backup size: 10.1GB
            repo1: backup set size: 3.9GB, backup size: 2.7GB
            backup reference list: 20220510-000110F, 20220510-000110F_20220510-050017I, 20220510-000110F_20220510-080007I, 20220510-000110F_20220510-090009I, 20220510-000110F_20220510-100016I, 20220510-000110F_20220510-130017I, 20220510-000110F_20220510-140006I, 20220510-000110F_20220510-150012I, 20220510-000110F_20220510-160015I, 20220510-000110F_20220510-170010I, 20220510-000110F_20220510-180013I, 20220510-000110F_20220510-190017I, 20220510-000110F_20220510-200009I,  @20220510-000110F_20220510-210013I

pgbackrest_repo.conf 
[global]
log-path=/tmp
repo1-path=/pgbackrest/repo1
repo1-retention-full=2
repo1-retention-full-type=time
[db]
...
