### ISSUE TITLE
postgres cluster becomes unhealthy after draining one of the worker nodes "INFO: following a different leader because i am not the healthiest node"

### ISSUE THREAD

**Issue by nagannv** [CrunchyData/postgres-operator#3035]
postgres cluster deployed in HA mode becomes unhealthy after draining one of the worker nodes getting following a different leader because i am not the healthiest node

Created the PGO cluster in HA mode using the below command
```
pgo create cluster indexd --pgbouncer --replica-count=2 \
--pod-anti-affinity=preferred \
--sync-replication --pvc-size=10Gi \
--pgbackrest-pvc-size=10Gi \
--pgbackrest-storage-type=posix,s3 \
--pgbackrest-s3-key=xxxxxxxxxxxx \
--pgbackrest-s3-key-secret=xxxxxxxxxxxx \
--pgbackrest-s3-bucket=xxxxxxxxxxxx \
--pgbackrest-s3-endpoint=s3.amazonaws.com \
--pgbackrest-s3-region=ap-southeast-2 \
--password-superuser=xxxxxxxxxxxx \
--password-replication=xxxxxxxxxxxx \
--password=xxxxxxxxxxxx  \
--username indexdclusteruser

```

```
$ kubectl get pods -n pgo
NAME                                             READY   STATUS      RESTARTS   AGE
indexd-78c95cfb5d-54fxt                          1/1     Running     0          3d9h
indexd-backrest-shared-repo-7c4bcbcb54-ll5xk     1/1     Running     0          3d12h
indexd-nesg-5d69bf75c-vbc74                      1/1     Running     0          3d9h
indexd-pgbouncer-788f6c749c-zkwmp                1/1     Running     0          3d9h
indexd-uxoe-68fc5cc9df-fjxn9                     1/1     Running     0          3d9h
postgres-operator-6f5b559fd7-n7pcf               4/4     Running     1          3d12h
```

Initial cluster  status

```
NAME      STATUS   ROLES    AGE    VERSION
master-0   Ready    master   154d   v1.20.6
node-22    Ready    <none>   8d     v1.20.6
node-25    Ready    <none>   8d     v1.20.6
node-29    Ready    <none>   9h     v1.20.6
node-30    Ready    <none>   8h     v1.20.6
```

Drain the node in the 4 node cluster one by one using below command 

`kubectl drain <node name > --ignore-daemonsets --delete-emptydir-data`

On every instance node draining the  application UI accessible and PGO cluster was healthy till draining of last node  ( node-30  ) in the above cluster

final state of  cluster 
```
NAME      STATUS   ROLES    AGE    VERSION
master-0   Ready    master   154d   v1.20.6
node-31    Ready    <none>   3h6m   v1.20.6
node-32    Ready    <none>   169m   v1.20.6
node-34    Ready    <none>   106m   v1.20.6
node-35    Ready    <none>   35m    v1.20.6
```
But, on draining the last node ( node-30  ) the PGO cluster became unhealthy  with error `INFO: following a different leader because i am not the healthiest node`

The issue that I observed is similar to https://www.postgresql.org/message-id/71de8e84252d4becbb76b622787b5251%40gmsEXCH1201.gms.ca

Please help us if there if any solution for the issue describe in https://www.postgresql.org/message-id/71de8e84252d4becbb76b622787b5251%40gmsEXCH1201.gms.ca

[Logs (3).log](https://github.com/CrunchyData/postgres-operator/files/8062747/Logs.3.log)

PGO version : 4.7.4
Environment:  k8s on openstack

**Comment by tjmoore4** [comment]
@nagannv In PGO, v5 Pod disruption budgets and other related improvements have been implemented to improve PGO behavior with Kubernetes cluster node restarts, node draining, etc. As such, we would recommend upgrading to v5. If you are still encountering the same issue after the upgrade, feel free to resubmit an issue.
