### ISSUE TITLE
Add tablespaces on pgo v5

### ISSUE THREAD

**Issue by benjamin-bergia** [CrunchyData/postgres-operator#3044]
Due to some limitations on the storage available to me, I need to move some of my tables to separate tablespaces.
I was only able to find a procedure to add tablespaces from the pgo client in the version 4 doc.
Has this feature been dropped in v5? If not, how to create/add tablespaces to a cluster?

**Comment by andrewlecuyer** [comment]
@benjamin-bergia can you better elaborate on the storage limitations that are impacting you?  I would like to get a story added to the PGO v5 backlog for this feature request, but would first like to better understand your use case and need for tablespaces.

For instance, PGO v5 fully supports volume resizing capabilities within Kubernetes, allowing you to re-size your volume as needed over the lifetime of your PostgreSQL cluster.  Do you have additional requirements for effectively managing volumes in your environment.

Thanks!

**Comment by benjamin-bergia** [comment]
Hi, thank you for considering this addition.

My current provider has a limit on the number of iops on each volume. The only way for me to scale IOs is to use different volumes for hot tables.

**Comment by tjmoore4** [comment]
@benjamin-bergia Thank you for the use case details; I've added them to our feature backlog.

**Comment by andrelcz** [comment]
Hello,

Was this feature added already to the roadmap?

I would like very much to upgrade to v5, but I'm blocked because of missing tablespaces support.

**Comment by benjaminjb** [comment]
Hello @benjamin-bergia , @andrelcz : support for tablespaces has been added in [this PR](https://github.com/CrunchyData/postgres-operator/pull/3575).

A few things to note: 
(a) The feature is alpha and behind a feature gate, which is discussed in [the docs](https://github.com/CrunchyData/postgres-operator/blob/master/docs/content/guides/tablespaces.md). I hope the docs are clear, but if you have any questions, please ask.

(b) The code is in the repo, but not yet in our `latest` image for the operator, which is coming, but I'm not sure when.

**Comment by benjaminjb** [comment]
Wait, @andrelcz are you updating from a v4 cluster with tablespaces to a v5 cluster with tablespaces? I would be curious to hear more about that use-case / database size.

**Comment by andrelcz** [comment]
Hello,
Thank You for the feature :)

Yes, we will update from v4 to v5. Both with tablespace. Tablespace is used to store detailed history (create, update, etc.) of objects stored in database. As application is moved from baremetal architecture to CNF, and tabelspace is mandatory in baremetal, then it is also mandatory in CNF.

In baremetal environment for example database has ~5.8 GB and tablespace ~1GB.

In Kubernetes I have still small systems: database ~8MB, tablespece ~196 kB.

**Comment by andrelcz** [comment]
Hello,

Can You please clarify what "latest" mean?  I tried with 5.3.0 and 5.3.1 but in both I got "panic: unable to parse and store configured feature gates. unrecognized feature gate: TablespaceVolumes" so I assume it is still not in those images?

And in the meantime looks like I'm in the dead end. We are still have to use PGOv4 with PostgreSQL 13. And in PGOv5 support for PostgreSQL 13 was dropped in Crunchy Data Developer Program.

Any advice how to perform upgrade?

**Comment by dsessler7** [comment]
Support for tablespaces was added in our 5.4.0 release, so I am closing this issue.

@andrelcz, I'd recommend reaching out to us at info@crunchydata.com to figure out how to move forward with upgrading to v5.
