### ISSUE TITLE
help  build centos 8 postgres docker image with mysql_fdw and clickhouse_fdw extension

### ISSUE THREAD

**Issue by surajmachamasi** [CrunchyData/postgres-operator#3045]
i am trying to build the docker image of postgres with clickhouse and mysql extension. please help me out.

**Comment by andrewlecuyer** [comment]
@surajmachamasi please provide additional details regarding your issue and/or use-case according to our issue request templates:

https://github.com/CrunchyData/postgres-operator/issues/new/choose

This includes any specific errors/issues you are running into when building.
