### ISSUE TITLE
PGO Cluster creation issue as failing to Lock Owner - podSecurityPolicy: unable to validate pod: []","reason":"Forbidden" - 

### ISSUE THREAD

**Issue by nagannv** [CrunchyData/postgres-operator#3046]
[cluster_pod_logs.log](https://github.com/CrunchyData/postgres-operator/files/8099947/cluster_pod_logs.log)
[Operator_Pod_logs.log](https://github.com/CrunchyData/postgres-operator/files/8099952/Operator_Pod_logs.log)
Trying to deploy the PGO cluster on OpenStack environment

The PGO cluster creation is failing at failing to Lock Owner as podSecurityPolicy: unable to validate pod: []" with a"reason":"Forbidden"

I am observing the issue with both PGO 4.73 and PGO 4.7.4 on Openstack Enviorment

```
2022-02-18 19:12:24,407 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-02-18 19:12:24,410 INFO: Lock owner: None; I am hipp-76b57b5697-tbg45
2022-02-18 19:12:24,451 ERROR: Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 481, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 1025, in touch_member
    ret = self._api.patch_namespaced_pod(self._name, self._namespace, body)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 466, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 402, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 371, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 201, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'c0f5e913-fcea-4ac5-9a81-cd4613b3fff1', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'f3cc0b02-7f47-4f72-b1fa-fb3245eed33a', 'Date': 'Fri, 18 Feb 2022 19:12:24 GMT', 'Content-Length': '261'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"hipp-76b57b5697-tbg45\\" is forbidden: PodSecurityPolicy: unable to validate pod: []","reason":"Forbidden","details":{"name":"hipp-76b57b5697-tbg45","kind":"pods"},"code":403}\n'

2022-02-18 19:12:24,451 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
```

operrator logs

`time="2022-02-18T19:11:44Z" level=error msg="pods \"hipp-76b57b5697-tbg45\" is forbidden: PodSecurityPolicy: unable to validate pod: []" func="internal/controller/pod.(*Controller).labelPostgresPodAndDeployment()" file="internal/controller/pod/inithandler.go:295" version=4.7.3`

Step followed:
1. Create PGO deployment  use the default  postgres-operator.yml  ( either 4.7.4 or 4.7.3) by updating   `storage1_class` as `"ceph-ssd"` ( as per Openstack Storage class definition)
2. Install PGO client, and port forward
3. create cluster 
`pgo create cluster hipp`

```
# kubectl get pods -n pgo
NAME                                        READY   STATUS      RESTARTS   AGE
hipp-76b57b5697-tbg45                       1/1     Running     0          25m
hipp-backrest-shared-repo-76cfb57d4-t5b7f   1/1     Running     0          26m
pgo-deploy-jjq68                            0/1     Completed   0          29m
postgres-operator-79c549ffc6-v92fk          4/4     Running     0          29m

```

Enviroemnt:
PGO 4.7.3 /PGO 4.74
K8s 1.21 on Openstack magnum
storage - Ceph -ssd

**Comment by nagannv** [comment]
@jmckulk could you please guide me to narrow down the issue further. Thanks in advance. I stuck at this stage for past two weeks.

**Comment by nagannv** [comment]
@jkatz Looking for your inputs which helps me move further the deployment of PGO on OpenStack

**Comment by benjaminjb** [comment]
As we have not been able to reproduce and haven't seen this before, I wonder if @andrewstuart has the right of it: this may be an issue with your env. Are you still running into this?

**Comment by ValClarkson** [comment]
Hi @nagannv 

We are closing this issue as we were unable to reproduce it, If you continue to have issues please feel free to re-open this issue or if you encounter a new problem please feel free to open a new issue.

Also, I would like to recommend that you upgrade your PGO to the latest and greatest v5 PGO our docs are located [here](https://access.crunchydata.com/documentation/postgres-operator/latest/).
