### ISSUE TITLE
pgreplica inconsistent when initial primary fails

### ISSUE THREAD

**Issue by psavva** [CrunchyData/postgres-operator#3047]
History:
We created a cluster with 1 replica, and 1 primary.
The primary failed, and the replica took the Primary Role.
We created a second replica (2 replicas, 1 primary).

Problem: 
The pgo client shows that the pgreplica is the primary, instead of the the replica or the failed primary.

Expected Behaviour:
The pgreplica shows in pgo show cluster <cluster_name> should show the "old" failed primary, as the replica, instead of the replica (which is now primary)

As can be seen in the screenshot below:

**dgc-issuance-zcnm**-bfdb9d5f9-ms62m (Running) on dgcvm04 (2/2) (primary) is shown as **primary**
however, is being reported as a replica:
pgreplica : **dgc-issuance-zcnm**

![image](https://user-images.githubusercontent.com/1454758/154925571-89638c49-b3b0-4ac4-a126-6dee26d29725.png)

**Addition Information:** 
We are expecting that it should be safe to scaledown the failed old "primary" which is actually a replica right now which shows the status "(unknown)".

It causes conflict in my mind that pgreplica shows shows the current (primary) as the replica.

**Comment by psavva** [comment]
It is safe to delete the old primary "dgc-issuance-ekbd-58d5565dff-swvbp" and proceed with creating a new replica?
The uncertainty comes from the fact that pgreplica shows the current primary a "pgreplica".
@jkatz  Could you assist?

**Comment by benjaminjb** [comment]
Thank you for bringing this issue to our attention.

The PGO v4 line you are using is no longer available through the Crunchy Developer Program (for additional details about available versions of Crunchy Postgres for Kubernetes, please see the [Supported Platforms page](https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms).

If you still require assistance with v4, please contact [info@crunchydata.com](mailto:info@crunchydata.com) to see if we can help further.
