### ISSUE TITLE
Problem with PostgreSQL Major version upgrade - PGO v.5

### ISSUE THREAD

**Issue by lbartnicki92** [CrunchyData/postgres-operator#3057]
## Overview

Upgrade PG from 12.9 to 13.5, or 13.5 to 14.1 fails with LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/pgdata/pg13/postgresql.conf.

## Environment

Please provide the following details:

Platform: Kubernetes
Platform Version: v1.20.7
PGO Image Tag: postgres-operator:centos8-12.9-0
Postgres Version: postgres-operator:ubi8-5.0.4-0
Storage: HostPath for data

### REPRO

1. Create PostgreSQL Cluster with PG12:
2. Modify yaml of this cluster:
Before modification:
  image: harbor/crunchydata/crunchydata/crunchy-postgres:centos8-12.9-0
  postgresVersion: 12
After modification:
  image: harbor/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0
  postgresVersion: 13

### EXPECTED

PG Cluster upgrade to upper MAJOR Version.

### ACTUAL

1. Operator terminates Pod with Postgres.
2. Operator starts Postgres 14
3. After kubectl logs on new Pod:
4. `2022-02-24 11:27:28,238 INFO: doing crash recovery in a single user mode
2022-02-24 11:27:28,239 ERROR: Error when reading postmaster.opts
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 383, in read_postmaster_opts
    with open(os.path.join(self._postgresql.data_dir, 'postmaster.opts')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pgdata/pg13/postmaster.opts'
2022-02-24 11:27:28,342 ERROR: Crash recovery finished with code=1
2022-02-24 11:27:28,433 INFO:  stdout=
2022-02-24 11:27:28,433 INFO:  stderr=2022-02-24 11:27:28.341 GMT [344] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/pgdata/pg13/postgresql.conf" line 29
2022-02-24 11:27:28.341 GMT [344] FATAL:  configuration file "/pgdata/pg13/postgresql.conf" contains errors`

## Additional Information

There is no custom configuration of wal_keep_segments in postgresCluster yaml. Setting explicity wal_keep_size, didn't help. 
In docs there is no info about Major Version upgrade procedure. Procedure for Minor Upgrade, works fine.

**Comment by JannikZed** [comment]
I'm facing the same error with PGO 4.7.4

**Comment by Schmaetz92** [comment]
I may be wrong, but a major upgrade by swapping the image in the definition can't work because the operator can't do a PG upgrade on its own. 

This is not a problem with minors because the basic data structure remains the same, which is no longer the case with a major change. 

For PG upgrade Crunchy provides an image.
