### ISSUE TITLE
[Question] Does high availability postgreSQL clusters support `hostpath` storage like etcd storage?

### ISSUE THREAD

**Issue by microyahoo** [CrunchyData/postgres-operator#3064]
Hi, does high availability postgreSQL clusters support `hostpath` storage like etcd storage? For example, there have three nodes to setup HA cluster, and every node uses its local path as underlying storage, how to setup and configure it? Thanks.

**Comment by microyahoo** [comment]
Another question, what's relationship between `postgres-operator` and `crunchy-containers`?

**Comment by andrewlecuyer** [comment]
> Hi, does high availability postgreSQL clusters support hostpath storage like etcd storage? For example, there have three nodes to setup HA cluster, and every node uses its local path as underlying storage, how to setup and configure it? Thanks.

Yes, that should be possible.  You can configure multiple instance sets under `spec.instances` - one for each PG replica - with each configured via the `dataVolumeClaimSpec` field to use any valid storage available in your environment (e.g. you could point each to various `hostpath` PV's available in your cluster, etc.).

See our [documentation for creating a cluster](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/create-cluster/) for more details about defining the `dataVolumeClaimSpec`:

> 1. what's relationship between postgres-operator and [crunchy-containers](https://github.com/CrunchyData/crunchy-containers)?

While the [Crunchy Postgres Operator](https://github.com/CrunchyData/postgres-operator) (`postgres-operator`) is Crunchy's fully open-source PostgreSQL operator, the [Crunchy Container Suite](https://github.com/CrunchyData/crunchy-containers) (`crunchy-containers`) provides the various components available for use with the Crunchy Postgres Operator, as described in the [Components and Compatibility documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/references/components/).

> 2. I have noticed that latest release version is 4.7.4, but I meet the same https://github.com/CrunchyData/postgres-operator/issues/2602, which recommends installing [V5](https://access.crunchydata.com/documentation/postgres-operator/v5/). Which is the latest release?

You should install the latest v5 release: https://access.crunchydata.com/documentation/postgres-operator/latest/.
