### ISSUE TITLE
Best way to upgrade major versions with operator v4?

### ISSUE THREAD

**Issue by Guitarkalle** [CrunchyData/postgres-operator#3070]
Hello,

I am wondering if there's any detailed instruction on how to, in the best way, upgrade postgres clusters (major version) that are operated by PGO? I am using operator version 4.6.2 currently and looking to upgrade postgres from 12.6 to 13.2.

I haven't been able to find very good documentation on the best approach. The only thing I've been able to find is to use the crunchy-upgrade image, but not exactly the best way to use it. I prefer to keep the same name of the cluster etc so I can use the same connection string. I basically want to swipe out the data from the old one.

Currently I do the following:
* Scale down the source cluster so no instances are running.
* Launch the crunchy-upgrade container and mounting the volume for the source data
* Run pg_upgrade <--- Here the first problem arises. When doing the post upgrade checks pg_upgrade complains it cannot start the destination postgres (13.2) because the config files seems bad. I inspected the data directory and the postgres.conf file contains full paths still pointing to the old data directory (pg_hba.config & pg_ident.conf). There also are files missing in the destination postgres pgdata directory (postgresql.base.conf). I am a bit unsure if I can just copy and edit these files since I don't know if there are configs that should be added/changed for using with 13.2 compared to 12.6
* After upgrading the data I change the container image for the cluster to the correct version (13.2) and scale up the cluster just to test it, I also changed the variable pointing the PGDATA to the new location. Here the second problem arises. When starting the cluster with the updated image I get the following error: systemID mismatch, node belongs to a different cluster. Which I guess it because I created a new database with the new postgres binaries. Should I do a patronictl remove cluster before scaling up?
 
Any pointers on how to do an upgrade in the best way would be greatly appreciated!

**Comment by Guitarkalle** [comment]
So here's an update. I have almost gotten it to work in the following way:

* Scale down cluster to 0
* Take a backup
* Perform pg_upgrade with the crunchy-upgrade image. Before this the postgres.conf needs to be modified to remove some entries that are not valid (in my case going from 12 to 13). After pg_upgrade, copy over any config files you want (I think most will be reinitialised, I haven't investigated it much so far)
* Move old pgdata to a bak folder, move the new pgdata where the old one was (so it has the name of the old cluster)
* Destroy the old cluster, but with keep-data option. Sadly at this step I have to remove the backups.
* Create a new cluster with the same name as the old one, but with the upgraded version
* Done!

This seems to work, but I have only tested with a very simple database so far. Next week I'll test on a database that is actually has real data etc.

The only problem in this is that when deleting the old cluster I have to remove the backups, which I really don't want to... If I don't then the new cluster doesn't come up because pgbackrest seems to complain about the backups are for the from database or something similar (don't have the actual error atm). So I have to see if I can copy the backups to some other place so they are not removed when destroying the cluster.

**Comment by ValClarkson** [comment]
HI @Guitarkalle,
We have recently released PGO v5.1.0, I believe your issue has been resolved with this latest release, please update to PGO v5.1.0 and try again. If your error still persists please feel free to reopen this issue or create a new one.

Please see[ release notes ](https://access.crunchydata.com/documentation/postgres-operator/5.1.0/releases/5.1.0/) about major upgrades. also see our blog post about [major upgrades](https://crunchy-www-dotcom-staging.herokuapp.com/blog/easy-major-postgresql-upgrades-using-pgo-v51)

**Comment by ggrames** [comment]
Hi @[Guitarkalle](https://github.com/Guitarkalle),
i am facing the same issue. I want to update from centos8-12.6-4.6.2 to centos8-13.2-4.6.2
Now i am at the point to search for the crunchy-upgrade image in the verison 12.6-4.6.2 but i can't find it.
Where have you downloaded it?
Thanks
GG

**Comment by ArgonV** [comment]
Howdy all, I too am experiencing an issue with the crunchy-upgrade container...
I am using this image tag: crunchydata/crunchy-upgrade:centos8-13.6-4.7.5

I am mounting the volume of the original container DB (named pg-folio) at `/pgolddata`, and the `OLD_DATABASE_NAME` env var set to `pg-folio-0`

Using the same PV/PVC, I am also mounting it at `/pgnewdata`, and the `NEW_DATABASE_NAME` env var set to `pg-folio-0`

The error I am getting is that, when going from 11 to 12, the 12 binaries cannot be found. Here is the error:
/opt/crunchy/bin/start.sh: line 157: /usr/pgsql-12/bin/pg_upgrade: No such file or directory

I am assuming these are supposed to be inside the container, after the upgrade is performed.

Lastly, I'm doing this all in K8s. Should I run this crunchy-upgrade container as a Job, Statefuleset or Deployment?

**Comment by ArgonV** [comment]
@ValClarkson , I found the issue: None of the new tags have all of the versions of the Postgres binaries built-in as they should. They only have the Postgres v13 binary.

I managed to start the container up at an entrypoint without running the start.sh script - and looked under `/usr/`
