### ISSUE TITLE
PGO v5 : Failed to push backups to S3 

### ISSUE THREAD

**Issue by yasser1chihab** [CrunchyData/postgres-operator#3072]
# Overview
We're using **postgres-operator v5** and we are  experiencing the full  backup of postgres 13 to s3 but unfortunately it fails .

# Configuration 
we are using terraform to provision the postgres-cluster and this is the configuration regarding the backup part
```
backups:
      pgbackrest:
        configuration:
        - secret : 
            name : ${var.s3_access_secret}
        image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
        global:
          repo1-path: /pgbackrest/postgres-operator/pg-test-s3/repo1
        repos:
        - name: repo1
          schedules:
            full: "*/5 * * * *"
          s3:
            bucket : ${var.s3_bucket_backup}
            endpoint : s3-website-eu-west-1.amazonaws.com
            region : ${var.aws_region}    
```
Creation of the secret  **in the same namespace of the cluster**
```
resource "kubernetes_secret" "s3-access-secret" {
    metadata {
      name = var.s3_access_secret
      namespace = var.namespace 
    }
    data = {
        repo1-s3-key = "****"
        repo1-s3-key-secret = "****" 
    }
    
}
```

# Error
when provisioning the cluster, the following error shows up in the logs of the postgres-operator
```
time="2022-03-04T09:35:03Z" level=error msg="unable to create stanza" error="command terminated with exit code 37: ERROR: [037]: stanza-create command requires option: repo1-s3-key\n" file="internal/controller/postgrescluster/pgbackrest.go:2320" func="postgrescluster.(*Reconciler).reconcileStanzaCreate" name=pg-cluster-test namespace=postgres-cluster reconciler=pgBackRest reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.0.4-0
```

thank's for your help.

**Comment by yasser1chihab** [comment]
# Resolved

the s3 access key and key-secret has to be created in a file and the content of the file has be a secret object in K8S as [the example is configured](https://github.com/CrunchyData/postgres-operator-examples/tree/main/kustomize/s3).

**Comment by MichaluxPL** [comment]
> # Resolved
> the s3 access key and key-secret has to be created in a file and the content of the file has be a secret object in K8S as [the example is configured](https://github.com/CrunchyData/postgres-operator-examples/tree/main/kustomize/s3).

Hi,

What do You exaclty mean by "the content of the file has be a secret object in K8S" ??

**Comment by yasser1chihab** [comment]
@MichaluxPL Hi,
Normally in order to push backups to s3, you have to save the credentials of your AWS in file and save this file as a secret like this : (for me using terraform) : 
```
resource "kubernetes_secret" "s3-access-secret" {
    metadata {
      name = var.s3_access_secret
      namespace = var.namespace
    }
    data = {
        "s3.conf" = file(var.s3_backup_bucket_creds)
    }
    
}
```
s3.conf : 
```
[global]
repo1-s3-key=<YOUR_AWS_S3_KEY>
repo1-s3-key-secret=<YOUR_AWS_S3_KEY_SECRET>
```

**Comment by MichaluxPL** [comment]
> @MichaluxPL Hi, Normally in order to push backups to s3, you have to save the credentials of your AWS in file and save this file as a secret like this : (for me using terraform) :
> 
> ```
> resource "kubernetes_secret" "s3-access-secret" {
>     metadata {
>       name = var.s3_access_secret
>       namespace = var.namespace
>     }
>     data = {
>         "s3.conf" = file(var.s3_backup_bucket_creds)
>     }
>     
> }
> ```
> 
> s3.conf :
> 
> ```
> [global]
> repo1-s3-key=<YOUR_AWS_S3_KEY>
> repo1-s3-key-secret=<YOUR_AWS_S3_KEY_SECRET>
> ```

Do You probably know how to configure it in yaml format ? Crunchy in their examples tend to use kustomize, I don't use, so need to create a secret myself.

**Comment by yasser1chihab** [comment]
You can create it using the following command : 
```
kubectl create secret SECRET_TYPE SECRET_NAME \
  --from-file=KEY_NAME=PATH_TO_DIRECTORY
```
Example : 
```
kubectl create secret generic credentials --from-file=password=./password.txt
```

**Comment by MichaluxPL** [comment]
> You can create it using the following command :
> 
> ```
> kubectl create secret SECRET_TYPE SECRET_NAME \
>   --from-file=KEY_NAME=PATH_TO_DIRECTORY
> ```
> 
> Example :
> 
> ```
> kubectl create secret generic credentials --from-file=password=./password.txt
> ```

Thx a lot :)
