### ISSUE TITLE
pgo-deploy fails for Kubernetes v1.22

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#3075]
Fails with the message below, it seems to me tha pgo-deploy is not able to create CRD at will, because of a changed api name ...
I badly need v4.7.4 running in brand new 1.22 kluster... Nay help will be greatly appreciated

TASK [pgo-operator : Create PGClusters CRD] ************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml"], "delta": "0:00:01.196851", "end": "2022-03-07 16:42:40.407101", "msg": "non-zero return code", "rc": 1, "start": "2022-03-07 16:42:39.210250", "stderr": "error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\"", "stderr_lines": ["error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\""], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=21   changed=5    unreachable=0    failed=1    skipped=17   rescued=0    ignored=0

**Comment by andrewlecuyer** [comment]
[PGO v5](https://access.crunchydata.com/documentation/postgres-operator/v5/) supports Kubernetes 1.22+.

If you need Kubernetes 1.22+ compatibility for PGO v4, please reach out about [production support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/).

**Comment by IJOL** [comment]
Which the latest kubernetes version supported by pgo v4.7.5


Saludos,
--------------------------------------------
Ignacio J.Ortega

**Comment by andrewlecuyer** [comment]
As mentioned above, PGO v5 should be used for Kubernetes 1.22+.

If you require PGO v4 in a Kubernetes 1.22+ environment, please feel free to reach out to info@crunchydata.com to discuss your use case further.

**Comment by johnlinp** [comment]
@andrewlecuyer OP didn't ask about PGO v5. What we want to know is the latest version of Kubernetes that PGO v4 supports.
