### ISSUE TITLE
Is there a way to manually create the ccp_monitoring user/tables/config?

### ISSUE THREAD

**Issue by m0sh1x2** [CrunchyData/postgres-operator#3079]
Hello,

I am trying to re-create the 'ccp_monitoring' user is it is not present after restore.

The exporter container is also constantly throwing the error and is not creating the `ccp_monitoring` user(as I understand it should create it):

```bash
psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "ccp_monitoring"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "ccp_monitoring"
```

Please let me know if it is possible to manually re-create the user.

Note: I am still testing this and if I find a bug or can replicate the issue then I will move this issue as a bug.

**Comment by tjmoore4** [comment]
Hello @m0sh1x2,

Some additional information regarding your environment, PGO version and the exact steps taken are needed to better understand your issue. For reference on the types of information required for troubleshooting, please see https://github.com/CrunchyData/postgres-operator/issues/new?template=bug_report.md.

Thanks!

**Comment by nawarajshahi** [comment]
@m0sh1x2 did you happen to dump and restore? Or clone? Also, which version of pgo are you running? 

If you did any of the above, you may want to update password for ccp_monitoring which you can do by first: 
1. Getting secret from whichever the namespace that you've deployed your pg cluster (secret should be sth like pg-monitoring or something to do with monitoring)
2. decode the secret 
3. exec  into pg pod (preferrably primary)
```
psql
\du #verify that ccp_monotoring user exists
ALTER ROLE ccp_monitoring with password '<password-from-secret-file>';
```

**Comment by andrewlecuyer** [comment]
Since we have not heard back on either of the requests for additional information above, closing this issue.

Please feel free to reach out again with the details requested if you are still seeing an issue with monitoring.
