### ISSUE TITLE
pgouser-admin Secret not in openshift-operators namespace

### ISSUE THREAD

**Issue by nnachefski** [CrunchyData/postgres-operator#3082]
Hello,

I'm attempting to install the pgo client for an operator installed on Openshift OKD 4.9.  My operator version is 'postgresoperator.v5.0.4'.  Looking at the pgo cli docs for Openshift, it mentions that i should obtain the pgo user:password as a pre-req, however, i do not see this user's secret anywhere on my cluster.  

```
# oc get secrets -A |grep pgo
databases                                          pgo-root-cacert                                            Opaque                                2      17d
openshift-operators                                pgo-dockercfg-vwrxn                                        kubernetes.io/dockercfg               1      17d
openshift-operators                                pgo-token-6zfpr                                            kubernetes.io/service-account-token   4      17d
openshift-operators                                pgo-token-96nvd                                            kubernetes.io/service-account-token   4      17d
```

Where can i obtain the pgouser info from with this version of the operator?

**Comment by tjmoore4** [comment]
Hello @nnachefski,
As of v5.0.0, the PGO client has been [removed](https://access.crunchydata.com/documentation/postgres-operator/5.0.4/releases/5.0.0/), but, as mentioned, all actions on a Postgres cluster can be accomplished using `kubectl`, `oc` or another preferred Kubernetes management tool.

**Comment by tjmoore4** [comment]
#2886

**Comment by ValClarkson** [comment]
Hi @nnachefski ,
It looks like your issue has been resolved.  If you need further assistance please reopen this issue or create a new one.  
We have had interest in adding a pgo cli to PGO v5 and it is on the road map for a future release.
