### ISSUE TITLE
imagePullPolicy does not work, it always set to "Always"

### ISSUE THREAD

**Issue by danielzhanghl** [CrunchyData/postgres-operator#3088]
Please ensure you do the following when reporting a bug:

- [ ] Provide a concise description of what the bug is.
 follow the example in https://access.crunchydata.com/documentation/postgres-operator/5.0.4/quickstart/
and changed the postgres-operator-examples/kustomize/postgres

apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
  **imagePullPolicy: IfNotPresent**

...

then install the pq cluster, but the image pull policy is set to "Always", the db pod should be set to "IfNotPresent" right? don't know what happend.

kubectl get pods -n postgres-operator  -o yaml |grep -i image

      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      imagePullPolicy: **Always**
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      imageID: docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:b2fac1254dd92886bf8563adc0ed80221fc0bbcb6ef2e77150ad01811b9b8e85
      image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
      imagePullPolicy: Always
      image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
      imagePullPolicy: Always
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      imagePullPolicy: Always
      image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
      imagePullPolicy: Always
      image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
      imagePullPolicy: Always
      image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
      imageID: docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-postgres@sha256:73b5dcf0c7de7d04e066133508a9a026f69de4bdccc7d0ab517ee0993e5389dd
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      imageID: docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:b2fac1254dd92886bf8563adc0ed80221fc0bbcb6ef2e77150ad01811b9b8e85
      image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
      imageID: docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-postgres@sha256:73b5dcf0c7de7d04e066133508a9a026f69de4bdccc7d0ab517ee0993e5389dd
      image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
      imageID: docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-postgres@sha256:73b5dcf0c7de7d04e066133508a9a026f69de4bdccc7d0ab517ee0993e5389dd
      image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
      imageID: docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-postgres@sha256:73b5dcf0c7de7d04e066133508a9a026f69de4bdccc7d0ab517ee0993e5389dd
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      imagePullPolicy: Always
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      imagePullPolicy: Always
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      imageID: docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:b2fac1254dd92886bf8563adc0ed80221fc0bbcb6ef2e77150ad01811b9b8e85
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      imageID: docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:b2fac1254dd92886bf8563adc0ed80221fc0bbcb6ef2e77150ad01811b9b8e85
      - name: RELATED_IMAGE_POSTGRES_14
      - name: RELATED_IMAGE_POSTGRES_14_GIS_3.1
      - name: RELATED_IMAGE_POSTGRES_13
      - name: RELATED_IMAGE_POSTGRES_13_GIS_3.1
      - name: RELATED_IMAGE_PGBACKREST
      - name: RELATED_IMAGE_PGBOUNCER
      - name: RELATED_IMAGE_PGEXPORTER
      image: registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.0.4-0
      imagePullPolicy: Always
      image: registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.0.4-0
      imageID: docker-pullable://registry.developers.crunchydata.com/crunchydata/postgres-operator@sha256:220c00fa0f7fc161e5d5917e3dacf209b3ee29b089603d8babd339848f3a3b56

==================

**Comment by tjmoore4** [comment]
Hi @danielzhanghl,

I'm curious why you are seeing `Always` in this case. An image being pulled that is not using the `latest` tag should generally default to an `imagePullPolicy` of `IfNotPresent`, as described in the Kubernetes [documentation](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting).

A few bits of information may help clear up what happened.
Can you confirm you are using PGO v5.0.4? 
What version of Kubernetes and what type of storage are you using for your cluster?
Lastly, please post your full PostgresCluster manifest in formatted YAML output.

**Comment by danielzhanghl** [comment]
@tjmoore4 thanks for the reply.
you are right, it seems there policy enabled in my cluster, it's set to Always for any pod, not only this PGO related pod, I closed this issue and will check on my side.

**Comment by danielzhanghl** [comment]
figure out my cluster turn on AlwaysPullImages plugin in API server:

    - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,NodeRestriction,Priority,PodSecurityPolicy,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,PodPreset,**AlwaysPullImages**



https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages

sorry did not realized that before...

**Comment by tjmoore4** [comment]
@danielzhanghl Thank you for the update, glad everything is now working as expected.
