### ISSUE TITLE
Support for official images?

### ISSUE THREAD

**Issue by adyanth** [CrunchyData/postgres-operator#3093]
Can I use official `postgres:14-alpine` (and other) images with this operator? Or does it have to be `registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.2-0`?

**Comment by jmckulk** [comment]
The Operator depends on the Crunchy Containers Suite and there are version dependencies between the two projects. Please see the documentation for more information about PGO [components and compatibility](https://access.crunchydata.com/documentation/postgres-operator/5.0.5/references/components/).

**Comment by adyanth** [comment]
Makes sense, the operator needs patroni and many others as part of the image.

Thanks! That answers it, cannot use `postgres:alpine`
