### ISSUE TITLE
Secret field pgbouncer-host uses dash and it's not supported by kubectl get secret --template syntax

### ISSUE THREAD

**Issue by stemid** [CrunchyData/postgres-operator#3094]
## Overview

Very simple issue here, the fields created in the DB user Secret objects that contain host, uri and stuff like that, they cannot contain dashes because then you cannot retrieve individual fields using kubectl --template.

We do this with a simple bash script to quickly get credentials that we can send to developers, but with pgbouncer-host, pgbouncer-jdbc-uri, pgbouncer-port, pgbouncer-uri and jdbc-uri it's not possible.

### You will get this error;

```
kubectl -n postgres-operator get secrets/cip-pguser-postgres --template='{{.data.pgbouncer-host}}'
error: error parsing template {{.data.pgbouncer-host}}, template: output:1: bad character U+002D '-'
```

## Environment

- Platform: Kubernetes
- Platform Version: 1.21.15
- PGO Image Tag: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
- Postgres Version 13
- Storage: PVC with Rook-Ceph CSI
- Tried with kubectl 1.21 and kubectl 1.23 so it's not an issue they have resolved in their client.

### REPRO

See Overview

### EXPECTED

1. Get individual fields from Secret object

### ACTUAL

1. Error in Overview

## Additional Information

Seems the simplest solution is to use underscores instead of dashes.

**Comment by jmckulk** [comment]
Hey @stemid, try this. It worked for me with a 1.23 client.
```
kubectl get secret hippo-pguser-user1 -o template='{{ index .data "pgbouncer-host" }}'
```

**Comment by stemid** [comment]
TIL a new syntax, thanks.
