### ISSUE TITLE
Duplicated documentation sites?

### ISSUE THREAD

**Issue by Larswa** [CrunchyData/postgres-operator#3115]
I am looking to get deeper into using the PGO operator, but I end up looking at two different documentation sites that seems to go in two different directions?

The access.crunchydata.com seems to use a more declarative approach and guide users into using YAML to set up everything.  At least in the tutorials and such.

And then there is the https://crunchydata.github.io/  that I looked at about a year ago, guiding the users in the direction of using the pgo client tool for setting up most stuff.  

I can't figure out if the https://crunchydata.github.io/ is a deprecated documentation site, and whether using the pgo tool is a deprecated way of doing things?  I personally like the yaml approach better. Integrates better with a CI/CD pipeline train of thought I think.

So ... which of the two sites is the "master" on documentation for the operator and its usage?

**Comment by Larswa** [comment]
Okay .... one more piece of the puzzle.  Am I correct in assuming that the 5.0.5 documentation only exists on  https://access.crunchydata.com/documentation/postgres-operator/5.0.5/quickstart/  ?   

And I can see in the releasenotes that indeed, version 5.x will focus on the declarative style to better enable a gitops flow.   Nice.   

From the Release notes:  https://access.crunchydata.com/documentation/postgres-operator/5.0.5/releases/5.0.0/

"PGO 5.0.0 is a major release of the Postgres Operator. The focus of this release was to take the features from the previous versions of PGO, add in some new features, and allow you to deploy Kubernetes native Postgres through a fully declarative, GitOps style workflow. As with previous versions, PGO 5.0 makes it easy to deploy production ready, cloud native Postgres."

and 

"The removal of the pgo client. This may be reintroduced in a later release, but all actions on a Postgres cluster can be accomplished using kubectl, oc, or your preferred Kubernetes management tool (e.g. ArgoCD)."

I'll just show myself out thank you very much  😂

**Comment by Larswa** [comment]
Okay ... one more question then. Where is the 5.X releases of the Operator?   I like being able to subscribe to releases for a github project, but this project only shows 4.x releases?

**Comment by benjaminjb** [comment]
Hi @Larswa, as you've discovered, our 5.x release was a pretty big overhaul to 4.x, but you can find documentation for both at access.crunchydata.com:

For 4.x: https://access.crunchydata.com/documentation/postgres-operator/v4/
For 5.x: https://access.crunchydata.com/documentation/postgres-operator/v5/

(Tell me if either of those aren't working for you and I can check that out.)

As for the releases for v5:

> With PGO v5, we’ve made some changes to our overall process. Instead of providing quarterly release tags as we did with PGO v4, we’re focused on ongoing active development in the v5 primary development branch (master, which will become main). Consistent with our practices in v4, previews of stable releases with the release tags are made available in the [Crunchy Data Developer Portal](https://www.crunchydata.com/developers).
> These changes allow for more rapid feature development and releases in the upstream PGO project, while providing [Crunchy Postgres for Kubernetes](https://www.crunchydata.com/products/crunchy-postgresql-for-kubernetes/) users with stable releases for production use.

(from the [FAQ](https://access.crunchydata.com/documentation/postgres-operator/5.0.5/faq/), "Where are the release tags for PGO v5?")

**Comment by Larswa** [comment]
Hi @benjaminjb   Thanks for helping sort this out. I think I got my head around it all now.  Closing the case.

**Comment by Larswa** [comment]
Oh and one more thing @benjaminjb  ... maybe it would be helpfull to take down the https://crunchydata.github.io/ documentation site as this is 4.X only.  If ppl end up there (as I did) they wont find the 5.x releases.  

And as for tracking 5.x releases of the operator. Where do we do that as those releases are not tagged in this github repo?

**Comment by benjaminjb** [comment]
Thanks, @Larswa, but when I go to `https://crunchydata.github.io/`, I get a 404 -- have you been able to access that recently?

**Comment by benjaminjb** [comment]
We are planning on changing that to point to v5 documentation when we release 5.1 (soon, no promises on an exact date, though).
