### ISSUE TITLE
Question on jdbc-uri in secret when a postgresql cluster is provisioned on openshift

### ISSUE THREAD

**Issue by rprakashg-redhat** [CrunchyData/postgres-operator#3129]
Installed 5.0.3 version of operator from Operatorhub in openshift 4.10 cluster and provisioned a cluster for a quarkus demo and I noticed jdbc-uri key is no longer available in the secret 
I had demo'd this a while back on a 4.8 cluster, forgot what version of operator I installed, I see in release notes for 5.0.4 version about jdbc-uri but latest version of operator in Operatorhub is showing 5.0.3. How to install the 5.0.4 version if that's the version that introduces jdbc-uri 

Thanks,
Ram

**Comment by benjaminjb** [comment]
@rprakashg-redhat Wanted to circle back on this as I think it's out of date: is this still something you're having trouble with? 

We are in the middle of releasing v5.3.0 to OperaterHub and other OLM bundles, but we've run into an issue with OCP 4.8: the operator works fine, but the installer in OCP 4.8 cannot manage the CRD file, which is over the size limit, so just wanted to let you know about that. So 5.2.0 is the last version we're supporting for OCP 4.8, but if you're using 4.9 or higher, 5.3.0 should be available soon. (We've got some tickets open with Red Hat for certifying those bundles.)
