### ISSUE TITLE
Postgres 10, 11 is missing from PGO v5 from Certified channel in OCP

### ISSUE THREAD

**Issue by sunofsparda** [CrunchyData/postgres-operator#3139]
Hello colleagues,

Could you please share some knowledge regarding PGO v5 5.0.5  in OCP 4.9.
PGO v5 5.0.5 was installed from Certified source in OperatorHub.
It is not possible to run Postgres 10 and 11 in PGO 5.0.4, 5.0.5, because operator is missing variables for these images.
![image](https://user-images.githubusercontent.com/10135454/161963213-54a5b37a-70ca-42dd-b5f5-29728f235be3.png)

According to [components](https://access.crunchydata.com/documentation/postgres-operator/v5/references/components) page, PGO v5 supports Postgres 10 and 11, but how to get them? Should I build it?

Please explain, whether should it be available in PGOv5 from Certified channel or not?

**Comment by sunofsparda** [comment]
Postgres 12 is no longer available too. According to notification at https://www.crunchydata.com/developers/download-postgres/containers `With the release of PGO 5.0.5 on March 2, 2022, Crunchy Data will no longer provide PGO 4.5 nor PostgreSQL 12 based container images in the Developer Portal through the Crunchy Data Developer Program. Additionally, with the upcoming release of PGO 5.1, Crunchy Data no longer plans to provide PGO 4.6 container images in the Developer Portal through the Crunchy Data Developer Program.`

Anyway, I'm still a bit confused.
Whether Postgres 10, 11, 12 images should be available, if PGOv5 was installed from **Certified** source in Openshift OperatorHub?

**Comment by andrewlecuyer** [comment]
Crunchy Postgres for Kubernetes is made available through the OpenShift OperatorHub for non-Crunchy Data subscription customers subject to the Crunchy Data Developer Program. If you are a Crunchy Data subscription customer that requires Crunchy Data container images that are no longer available through the Crunchy Data Developer Program, they are available through the Crunchy Data Access Portal (subscription required). Of course if you have any questions our support team is happy to assist or please contact us as [info@crunchydata.com](mailto:info@crunchydata.com).
