### ISSUE TITLE
image 

### ISSUE THREAD

**Issue by SzhiH** [CrunchyData/postgres-operator#3149]
Could you tell me if it supports adapting custom PostgreSQL images? If so, what should dockerfile pay attention to? Thank you
麻烦问一下支持适配自定义的postgresql镜像吗，支持的话 Dockerfile需要注意的点有哪些，谢谢

**Comment by benjaminjb** [comment]
The Operator depends on the Crunchy Containers Suite and there are version dependencies between the two projects. Please see the documentation for more information about PGO [components and compatibility](https://access.crunchydata.com/documentation/postgres-operator/latest/references/components/).

You may also want to check out the containers repo [here](https://github.com/CrunchyData/crunchy-containers)
