### ISSUE TITLE
pods is forbidden: User "system:serviceaccount:default:default" cannot list pods in the namespace "default" time="2018-08-19T11:40:29Z" level=error msg="error watching upgrade jobunknown (get jobs.batch)"

### ISSUE THREAD

**Issue by zhenhuadong** [CrunchyData/postgres-operator#315]
pdu@node-10-210-125-164:~$ helm status intentional-pronghorn
LAST DEPLOYED: Sun Aug 19 12:43:24 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                                 TYPE    DATA  AGE
intentional-pronghorn-pgo-apiserver  Opaque  7     1h

==> v1beta1/Deployment
NAME                       DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
intentional-pronghorn-pgo  1        1        1           0          1h

==> v1beta1/Role
NAME                               AGE
intentional-pronghorn-pgo-default  1h

==> v1beta1/RoleBinding
NAME                               AGE
intentional-pronghorn-pgo-default  1h

==> v1/Service
NAME                       TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)   AGE
intentional-pronghorn-pgo  ClusterIP  10.110.80.126  <none>       8443/TCP  1h

==> v1/ConfigMap
NAME                                DATA  AGE
intentional-pronghorn-pgo-operator  16    1h

==> v1/ServiceAccount
NAME                       SECRETS  AGE
intentional-pronghorn-pgo  1        1h

==> v1beta1/CustomResourceDefinition
NAME                            AGE
pgupgrades.cr.client-go.k8s.io  1h
pgclusters.cr.client-go.k8s.io  1h
pgingests.cr.client-go.k8s.io   1h
pgpolicies.cr.client-go.k8s.io  1h
pgreplicas.cr.client-go.k8s.io  1h
pgtasks.cr.client-go.k8s.io     1h
pgbackups.cr.client-go.k8s.io   1h

==> v1beta1/ClusterRole
intentional-pronghorn-pgo  1h

==> v1beta1/ClusterRoleBinding
NAME                       AGE
intentional-pronghorn-pgo  1h

==> v1/Pod(related)
NAME                                        READY  STATUS            RESTARTS  AGE
intentional-pronghorn-pgo-57f46d4c4c-fjthf  1/2    CrashLoopBackOff  16        1h

NOTES:
Thank you for installing postgres-operator chart.

Your release is named intentional-pronghorn.

To learn more about the release, try:

  $ helm status intentional-pronghorn
  $ helm get intentional-pronghorn

pdu@node-10-210-125-164:~$ kubectl get sa
NAME                        SECRETS   AGE
default                     1         3d
intentional-pronghorn-pgo   1         1h

pdu@node-10-210-125-164:~$ kubectl describe pod intentional-pronghorn-pgo-57f46d4c4c-fjthf
Name:           intentional-pronghorn-pgo-57f46d4c4c-fjthf
Namespace:      default
Node:           minikube/10.210.125.164
Start Time:     Sun, 19 Aug 2018 12:43:24 +0200
Labels:         app=pgo
                pod-template-hash=1390280707
                release=intentional-pronghorn
Annotations:    <none>
Status:         Running
IP:             172.17.0.9
Controlled By:  ReplicaSet/intentional-pronghorn-pgo-57f46d4c4c
Containers:
  postgres-operator-apiserver:
    Container ID:   docker://b3cf17bc53fcc4ba9437973189845724ea1eb5e79d8909cf52efc6547351e385
    Image:          crunchydata/pgo-apiserver:centos7-3.0
    Image ID:       docker-pullable://crunchydata/pgo-apiserver@sha256:5ac428ee3f78dd601c24b7e43564a8c58732286b788889e11b9c6b03b1cac55c
    Port:           8443/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sun, 19 Aug 2018 12:43:25 +0200
    Ready:          True
    Restart Count:  0
    Environment:
      CRUNCHY_DEBUG:  true
      NAMESPACE:      default (v1:metadata.namespace)
    Mounts:
      /config from apiserver-conf (ro)
      /operator-conf from operator-conf (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wtk6f (ro)
  postgres-operator-operator:
    Container ID:   docker://5368c402391c14a15d7a45df568ca2e0f3b73bfa1c99a92200beb9a658f33d3c
    Image:          crunchydata/postgres-operator:centos7-3.0
    Image ID:       docker-pullable://crunchydata/postgres-operator@sha256:22cb05e86fe0c1b376e2eaa57dbe2adb8a145dac0f77e526d6f84f5877eb9710
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sun, 19 Aug 2018 13:40:28 +0200
      Finished:     Sun, 19 Aug 2018 13:40:29 +0200
    Ready:          False
    Restart Count:  16
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      CRUNCHY_DEBUG:     true
      CCP_IMAGE_PREFIX:  crunchydata
      CO_IMAGE_PREFIX:   crunchydata
      CO_IMAGE_TAG:      centos7-3.0
      NAMESPACE:         default (v1:metadata.namespace)
      MY_POD_NAME:       intentional-pronghorn-pgo-57f46d4c4c-fjthf (v1:metadata.name)
    Mounts:
      /config from apiserver-conf (ro)
      /operator-conf from operator-conf (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wtk6f (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  operator-conf:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      intentional-pronghorn-pgo-operator
    Optional:  false
  apiserver-conf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  intentional-pronghorn-pgo-apiserver
    Optional:    false
  default-token-wtk6f:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wtk6f
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                 From               Message
  ----     ------                 ----                ----               -------
  Normal   Scheduled              58m                 default-scheduler  Successfully assigned intentional-pronghorn-pgo-57f46d4c4c-fjthf to minikube
  Normal   SuccessfulMountVolume  58m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "operator-conf"
  Normal   SuccessfulMountVolume  58m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-wtk6f"
  Normal   SuccessfulMountVolume  58m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "apiserver-conf"
  Normal   Pulled                 58m                 kubelet, minikube  Container image "crunchydata/pgo-apiserver:centos7-3.0" already present on machine
  Normal   Created                58m                 kubelet, minikube  Created container
  Normal   Started                58m                 kubelet, minikube  Started container
  Normal   Pulled                 58m (x4 over 58m)   kubelet, minikube  Container image "crunchydata/postgres-operator:centos7-3.0" already present on machine
  Normal   Created                58m (x4 over 58m)   kubelet, minikube  Created container
  Normal   Started                58m (x4 over 58m)   kubelet, minikube  Started container
  Warning  BackOff                3m (x248 over 58m)  kubelet, minikube  Back-off restarting failed container
pdu@node-10-210-125-164:~$ kubectl logs pod/intentional-pronghorn-pgo-57f46d4c4c-fjthf -c postgres-operator-operator
time="2018-08-19T11:40:29Z" level=debug msg="debug flag set to true"
time="2018-08-19T11:40:29Z" level=debug msg="setting NAMESPACE to default"
time="2018-08-19T11:40:29Z" level=debug msg="CCP_IMAGE_PREFIX set, using crunchydata"
time="2018-08-19T11:40:29Z" level=debug msg="CO_IMAGE_PREFIX set, using crunchydata"
time="2018-08-19T11:40:29Z" level=info msg="Watch Pgtask objects"
at end of setup, beginning wait...Watch Pgingestcluster objects
Watch Pgreplica objects
Watch Pgbackup objects
Watch Pgupgrade objects
Watch Pgpolicy objects
time="2018-08-19T11:40:29Z" level=info msg="Watch pod objects"
Watch Pgcluster objects
time="2018-08-19T11:40:29Z" level=info msg="Watch job objects"
time="2018-08-19T11:40:29Z" level=info msg="MajorUpgradeProcess watch starting..."
E0819 11:40:29.495079       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/ingestcontroller.go:82: Failed to list *v1.Pgingest: pgingests.cr.client-go.k8s.io is forbidden: User "system:serviceaccount:default:default" cannot list pgingests.cr.client-go.k8s.io in the namespace "default"
E0819 11:40:29.496120       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/clustercontroller.go:82: Failed to list *v1.Pgcluster: pgclusters.cr.client-go.k8s.io is forbidden: User "system:serviceaccount:default:default" cannot list pgclusters.cr.client-go.k8s.io in the namespace "default"
E0819 11:40:29.496875       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/upgradecontroller.go:82: Failed to list *v1.Pgupgrade: pgupgrades.cr.client-go.k8s.io is forbidden: User "system:serviceaccount:default:default" cannot list pgupgrades.cr.client-go.k8s.io in the namespace "default"
E0819 11:40:29.497166       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/backupcontroller.go:82: Failed to list *v1.Pgbackup: pgbackups.cr.client-go.k8s.io is forbidden: User "system:serviceaccount:default:default" cannot list pgbackups.cr.client-go.k8s.io in the namespace "default"
E0819 11:40:29.497738       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/taskcontroller.go:84: Failed to list *v1.Pgtask: pgtasks.cr.client-go.k8s.io is forbidden: User "system:serviceaccount:default:default" cannot list pgtasks.cr.client-go.k8s.io in the namespace "default"
E0819 11:40:29.497883       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/podcontroller.go:76: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:default" cannot list pods in the namespace "default"
time="2018-08-19T11:40:29Z" level=error msg="error watching upgrade jobunknown (get jobs.batch)"

**Comment by shuraa** [comment]
Got the same issue. As workaround, try to add in deployment manifest 'spec.serviceAccount=postgres-operator-pgo'

**Comment by jmccormick2001** [comment]
the helm chart was busted with respect to rbac...I've got it back to a working condition I think and that code (in pre32 branch) today will land in the 3.2.0 release which I'm planning to push out tomorrow evening.

**Comment by zhenhuadong** [comment]
@jmccormick2001  I see the image tag is still centos7-3.0. Is it correct? I thought the version should be centos7-<release-tag>.

**Comment by jmccormick2001** [comment]
I'm not seeing a 3.0 tag in the pre32 branch of code...are you looking at master branch?  if so, I'll be merging in the new code later today on top of master.

**Comment by jmccormick2001** [comment]
I'll close this one unless you are having an issue with the latest 3.2.0 version I pushed last week.

**Comment by jmccormick2001** [comment]
should be fixed now with the 3.3.0 release.
