### ISSUE TITLE
S3 backups without TLS

### ISSUE THREAD

**Issue by Subetov** [CrunchyData/postgres-operator#3155]
Hello.
Can't manage to deal with backups to MinIO.
Is there possibility to backup to s3 without TLS ?
There is no need in TLS for MinIO in our setup.
Thanks.
```
│ d terminated with exit code 101: ERROR: [101]: TLS error [1:336130315] wrong version number\n" object="{PostgresCluster ice-postgres ice-postgres-dc1 7280addf-0ddf-4797-87a3-5ead82a1a912 postgres-oper │
│ ator.crunchydata.com/v1beta1 1968856 }" reason=UnableToCreateStanzas version=5.0.5-0
```

**Comment by andrewlecuyer** [comment]
@Subetov you can disable TLS via the `repo-storage-verify-tls` setting as described in the [Configuration section](https://pgbackrest.org/configuration.html#section-repository/option-repo-storage-verify-tls) of the pgBackRest documentation.

And as described in the [Backup Configuration](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/backups/) section of the PGO documentation, pgBackRest configuration can be applied using  `spec.backups.pgbackrest.configuration` or `spec.backups.pgbackrest.global`, e.g. if using the latter: 

```yaml
spec:
  backups:
    pgbackrest:
      global:
        repo1-storage-verify-tls: "n"
```
