### ISSUE TITLE
Backup Restore not working: Can't find the Backups

### ISSUE THREAD

**Issue by rblvlvl** [CrunchyData/postgres-operator#3160]
Hello, 

i have issues restoring a backup for my postgres db.

- Platform: Kubernetes on Rancher
- Platform Version: Kubernetes v1.20.15, Rancher v2.5.9
- Postgres Version (e.g. `14`)
- Backups: Full-Backup on S3
- used Helm Chart to deploy Operator and DB
- Operator Chart: pg-operator-1.2.0
- DB Chart: pg-db-1.2.0 

**What I did:**
- deployed Postgres Operator and Postgres DB via Helm 
- first an automated backup was done through the deploy
- then i added some data into my db and created a new full backup
- deleted some tables and wanted to test the backup restore

**Available Backups:**

```
bash-4.4$ pgbackrest info 
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (14): 000000010000000000000001/00000001000000000000000F

        full backup: 20220419-112757F
            timestamp start/stop: 2022-04-19 11:27:57 / 2022-04-19 11:28:28
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 33.5MB, database backup size: 33.5MB
            repo1: backup set size: 4.3MB, backup size: 4.3MB

        full backup: 20220419-113554F
            timestamp start/stop: 2022-04-19 11:35:54 / 2022-04-19 11:37:02
            wal start/stop: 000000010000000000000009 / 00000001000000000000000A
            database size: 41.9MB, database backup size: 41.9MB
            repo1: backup set size: 5.3MB, backup size: 5.3MB
```

Wanted to restore the backup **20220419-113554F** as this one has the complete data. 

My **restore.yaml** file:
```
apiVersion: pg.percona.com/v1
kind: Pgtask
metadata:
  labels:
    pg-cluster: test-pg-db
    pgouser: admin
  name: test-backrest-restore
spec:
  name: test-backrest-restore
  parameters:
    backrest-restore-from-cluster: test-pg-db
    backrest-restore-opts: --type=time --target="2022-04-19 11:35:54"
    backrest-storage-type: s3
  tasktype: restore
``` 
`ERROR: [075]: unable to find backup set with stop time less than '2022-04-19 11:35:54'`

As this was the start time of the backup I tried the stop time as well: same error with stop timestamp.
Tried a time before the start timestamp and after the timestamp, got the same error with those timestamps.
Tried to get the correct timestamp format inside the db with `select current_timestamp` and used it in the restore.yaml with different timestamps again `backrest-restore-opts: --type=time --target="timestamp.209408+00`. Same error. 

Tried to leave the `backrest-restore-opts:` empty as it should use the latest available backup. (fount some information at point 9 https://pgbackrest.org/faq.html#time-based-pitr)

`ERROR: [075]: no backup set found to restore`

Tried only using `backrest-restore-opts: --set=20220419-113554F` and `--target=20220419-113554F`

`ERROR: [075]: backup set 20220419-113554F is not valid`

I get a few warning before the error, but these are only warning, should not be concerning in my opinion. Here is the full log when the warning occurs:

```
WARN: repo1: [CryptoError] unable to load info file '/backrestrepo/test-pg-db-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/test-pg-db-backrest-shared-repo/backup/db/backup.info.copy':
      CryptoError: raised from remote-0 ssh protocol on 'test-pg-db-backrest-shared-repo.default.svc.cluster.local.': unable to verify certificate presented by 's3-url:443': [20] unable to get local issuer certificate
      HINT: is or was the repo encrypted?
      CryptoError: raised from remote-0 ssh protocol on 'test-pg-db-backrest-shared-repo.default.svc.cluster.local.': unable to verify certificate presented by 's3-url:443': [20] unable to get local issuer certificate
      HINT: is or was the repo encrypted?
      HINT: backup.info cannot be opened and is required to perform a backup.
      HINT: has a stanza-create been performed?
**ERROR: [075]: no backup set found to restore**
Wed Apr 20 08:16:59 UTC 2022 ERROR: pgBackRest primary Creation: pgBackRest restore failed when creating primary
2022-04-20 08:16:59,061 INFO: removing initialize key after failed attempt to bootstrap the cluster
2022-04-20 08:16:59,073 INFO: renaming data directory to /pgdata/test-pg-db_2022-04-20-08-16-59
Traceback (most recent call last):
  File "/usr/bin/patroni", line 11, in <module>
    load_entry_point('patroni==2.1.1', 'console_scripts', 'patroni')()
  File "/usr/lib/python3.6/site-packages/patroni/__init__.py", line 171, in main
    return patroni_main()
  File "/usr/lib/python3.6/site-packages/patroni/__init__.py", line 139, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/lib/python3.6/site-packages/patroni/__init__.py", line 109, in run
    super(Patroni, self).run()
  File "/usr/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/lib/python3.6/site-packages/patroni/__init__.py", line 112, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1471, in run_cycle
    info = self._run_cycle()
  File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1345, in _run_cycle
    return self.post_bootstrap()
  File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1238, in post_bootstrap
    self.cancel_initialization()
  File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1231, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```
backup.info is available and the s3 storage can be accessed as the backups can be done as well. Checked in the s3 storage if there are any backups located and there are. 

Does anyone have an idea how the restore can be done? There is another option restoring the whole cluster and creating a new one, but this is not what I want. If the restore fails the whole database is gone.

**Comment by art-niu** [comment]
@rblvlvl have you got it fixed? if yes, could you please share your solution with me?

**Comment by rblvlvl** [comment]
@art-niu so far i didn't get it fixed. Saw a similar issue on Percona's Jira and tried my restore with the parameter `backrest-s3-verify-tls: "false"` as I always get a CryptoError, but so far no luck. 
I opened another issue directly at Percona, i will keep you updated about this.

**Comment by art-niu** [comment]
@rblvlvl Thanks!

**Comment by rblvlvl** [comment]
@art-niu got the solution now: https://www.percona.com/doc/kubernetes-operator-for-postgresql/faq.html#how-can-i-store-backups-on-s3-compatible-storage-with-self-issued-certificates

You need the stop timestamp of your backup and the options described in the link above. 

my **restore.yaml** looked like this: 

`apiVersion: pg.percona.com/v1
kind: Pgtask
metadata:
  labels:
    pg-cluster: test-pg-db
    pgouser: admin
  name: test-backrest-restore
spec:
  name: test-backrest-restore
  parameters:
    backrest-restore-from-cluster: test-pg-db
    backrest-restore-opts: --type=time --target="2022-04-19 11:37:02" --no-repo1-storage-verify-tls
    backrest-storage-type: s3
  tasktype: restore`

**Comment by andrewlecuyer** [comment]
@rblvlvl the Percona Postgres Operator, while based on Crunchy's Postgres Operator version 4, is otherwise not related to Crunchy's Postgres Operator nor maintained in this repository.  We are therefore unable to field/answer issues related to their operator, and will closing this issue to avoid confusion across both solutions.

However, please note that Crunchy still supports the Crunchy Postgres Operator v4 for those still using older/legacy versions of Kubernetes, with documentation for the latest version of PGO v4 found here:

- https://access.crunchydata.com/documentation/postgres-operator/v4/

Therefore, if you run into this same issue using Crunchy's Postgres Operator v4, please feel free to resubmit your issue.

That being said, we do highly recommend that you upgrade to the [Crunchy Postgres Operator version 5](https://access.crunchydata.com/documentation/postgres-operator/latest), which has been rebuilt/redesigned from the ground -up to manage production-grade PostgreSQL workloads in Kubernetes using the latest of what modern Kubernetes has to offer.  You can find instructions for upgrading to PGO v5 here:

- https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/

And here are few additional PGO v5 links as well:

- https://www.crunchydata.com/blog/getting-started-with-pgo-postgres-operator-5.0
- https://www.crunchydata.com/blog/introducing-pgo-the-open-source-postgres-operator-from-crunchy-data-version-5.1

And if you have an issues upgrading - or with restores, backups, etc. after upgrading - please feel free to reach out!

**Comment by tirelibirefe** [comment]
https://github.com/CrunchyData/postgres-operator/issues/3196

**Comment by tirelibirefe** [comment]
https://github.com/CrunchyData/postgres-operator/issues/3382
