### ISSUE TITLE
Expose operator errors via PostgresCluster status fields

### ISSUE THREAD

**Issue by StevenBarre** [CrunchyData/postgres-operator#3163]
## Overview

The PostgresCluster Custom Resource should provide errors from the operator in the status fields to aid in debugging.

## Use Case

If you create a cluster with an invalid name, and don't have RBAC to see the operators logs, there is no way to know what the issue is.

Create a PGO with an invalid name

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo-ha
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
  postgresVersion: 13
  instances:
    - name: pgha1_dev
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
        storageClassName: netapp-block-standard
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-0
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
```

Inspect the object. No errors are shown but no statefulset or pods have been created.

```console
$ oc describe postgrescluster
...
Status:
  Instances:
    Name:               pgha1_dev
  Observed Generation:  1
Events:                 <none>
```

Use my cluster admin powers to inspect the operator logs and see the error.

```console
$ oc -n crunchy-operator logs -f pgo-69949584b9-468zq
...
time="2022-04-20T17:57:21Z" level=error msg="Reconciler error" error="ConfigMap \"hippo-ha-pgha1_dev-rtp9-config\" is invalid: metadata.name: Invalid value: \"hippo-ha-pgha1_dev-rtp9-config\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" file="internal/controller/postgrescluster/instance.go:1280" func="postgrescluster.(*Reconciler).reconcileInstanceConfigMap" name=hippo-ha namespace=stevenbarre-dev reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.0.4-0
```

## Desired Behavior

The status section of the object should show any errors from the operator, or perhaps even create events showing the errors?

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: OpenShift
- Platform Version: 4.8.35
- PGO Image Tag: ubi8-5.0.4-0
- Postgres Version 13
- Storage: NetApp Trident
- Number of Postgres clusters: 1

## Additional Information

In a multi-tenant environment the operator may be installed by cluster admins in a separate namespace that developers don't have access to.

**Comment by andrewlecuyer** [comment]
@StevenBarre thank you for using PGO!

Validation has now been added to the PostgresCluster spec to prevent the creation of clusters with invalid instance set names.  For instance, you will now see the following when attempting to create the `hippo-ha` cluster you provided in your example:

```bash
$ kubectl apply -k examples/postgrescluster
The PostgresCluster "hippo-ha" is invalid: spec.instances.name: Invalid value: "pgha1_dev": spec.instances.name in body should match '^([a-z0-9]([-a-z0-9]*[a-z0-9])?)?$'
```

**Comment by StevenBarre** [comment]
What version specifically is this fixed in?
