### ISSUE TITLE
Disable pg-backrest-shared-repo

### ISSUE THREAD

**Issue by anonymouse-jj** [CrunchyData/postgres-operator#3164]
I have a large database which is not production. I have resource constraints and I'm trying to avoid having the extra PVC created for pg-backrest-shared-repo. How can I disable this feature?

**Comment by andrewlecuyer** [comment]
@anonymouse-jj thank you for using PGO!

Just noting that we have an enhancement in our backlog to make Disaster Recovery features (e.g. backups) optional for non-production use cases.
