### ISSUE TITLE
PGO v5.0.3 and v5.0.4 subscription not working

### ISSUE THREAD

**Issue by yuvraj-vansure** [CrunchyData/postgres-operator#3178]
Hello,
We are subscribing to PGO version 5.0.3 in our product on OpenShift and it was working well.
However since Today[29/04/2022] we are observing issue that PGO 5.0.3 and PGO 5.0.4 subscriptions are not working. 
InstallPlan for v5.0.3 and v5.0.4 are not being created.

Are there any issues with these 2 versions ?

**Comment by andrewlecuyer** [comment]
Thank you for reaching out!  What version of the Crunchy OLM installer are you using (community, certified or marketplace)?

We are not specifically aware of any issues with those two versions of PGO, although we did run into a few issues with our OLM bundles this week as a result of some recent Red Hat maintenance.

I will therefore take a look to see if anything in particular is going on with these bundles. 

However, we do recommend you upgrade to latest PGO releases when using OLM to ensure you have the latest features, fixes, etc.

Therefore, please try with [PGO v5.1.0](https://www.crunchydata.com/blog/introducing-pgo-the-open-source-postgres-operator-from-crunchy-data-version-5.1), and if you continue to run into subscription issues with this version, please let use know.

**Comment by andrewlecuyer** [comment]
Also, what version of OpenShift are you using?

**Comment by yuvraj-vansure** [comment]
We are using certified-operators catalog source and faced same issue on OCP 4.6, 4.7, 4.8 and 4.9

**Comment by jmckulk** [comment]
Since you automatically update, why are you subscribing to 5.0.3 instead of starting with the latest version?

We can install both of the latest PGO versions, 5.0.5 and 5.1.0. If you cannot install PGO v5.1.0, please try installing PGO v5.0.5, the latest v5.0 version. If that doesn't work, please let us know.

**Comment by tjmoore4** [comment]
@yuvraj-vansure to follow up, were you able to try installing v5.0.5?
