### ISSUE TITLE
How can I be sure "Stanza" works properly or not?

### ISSUE THREAD

**Issue by tirelibirefe** [CrunchyData/postgres-operator#3179]
Hello,
I've a postgres cluster which was installed by using pgo 5.0.4 on EKS Kubernetes. Nowadays I do a number of tests on it. 
When I describe the postgres cluster which was restored from backup / S3 reports that:

```
  Normal   StanzasCreated         42m   postgrescluster-controller  pgBackRest stanza creation completed successfully
  Warning  UnableToCreateStanzas  42m   postgrescluster-controller  command terminated with exit code 50: ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-backup.lock': Resource temporarily unavailable   
       HINT: is another pgBackRest process running?
```

When I look at other details on describtion page and logs, I cannot see any problems. Also I tried to take backup and it worked.

How can I be sure "Stanza" works properly or not?

Thanks & Regrads

**Comment by jmckulk** [comment]
hi @tirelibirefe, you can check that the stanza has been created properly by looking at the status on the `postgrescluster`.

```
status:
  conditions:
  - lastTransitionTime: "2022-05-11T18:34:40Z"
    message: pgBackRest replica create repo is ready for backups
    observedGeneration: 2
    reason: StanzaCreated
    status: "True"
    type: PGBackRestReplicaRepoReady
  pgbackrest:
    repos:
    - stanzaCreated: true
```

**Comment by andrewlecuyer** [comment]
@tirelibirefe closing this issue per the response provided by @jmckulk.

Please feel free to re-open if you still have any questions or issues.
