### ISSUE TITLE
pgo.yml  storage9 is not defined

### ISSUE THREAD

**Issue by longtian001** [CrunchyData/postgres-operator#3189]
## Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version:  k8s, 1.18.5, pgo ,4.7.5
- Storage: `rook`,`rook-ceph-block`

## Steps to Reproduce
1. clone postgres-operator of branch v4.7.5 
[root@master ~]#  git clone --single-branch --branch v4.7.5 https://github.com/CrunchyData/postgres-operator.git

2. Add custom sotrage class
[root@master ~]#  cd postgres-operator/installers/kubectl/
[root@master kubectl]# vi postgres-operator.yml
    backrest_storage: "rook"
    backup_storage: "rook"
    primary_storage: "rook"
    replica_storage: "rook"
    pgadmin_storage: "rook"

3. create postgres-operator
[root@master kubectl]# kubectl create -f postgres-operator.yml 
serviceaccount/pgo-deployer-sa created
clusterrole.rbac.authorization.k8s.io/pgo-deployer-cr created
configmap/pgo-deployer-cm created
clusterrolebinding.rbac.authorization.k8s.io/pgo-deployer-crb created
job.batch/pgo-deploy created
[root@master kubectl]#

4.pod status in namespace pgo
[root@master ~]# kubectl get po -n pgo -o wide
NAME                                 READY   STATUS             RESTARTS   AGE   IP              NODE     NOMINATED NODE   READINESS GATES
pgo-deploy-q7nfd                     0/1     Error              0          33m   10.244.177.58   work03   <none>           <none>
postgres-operator-7797b747cb-hsrc7   1/4     CrashLoopBackOff   27         32m   10.244.83.52    work01   <none>           <none>
[root@master ~]# 

5. postgres-operator logs
[root@master ~]# kubectl logs -f postgres-operator-7797b747cb-hsrc7 -n pgo --all-containers=true
time="2022-05-09T09:46:09Z" level=info msg="debug flag set to false" func="main.main()" file="cmd/postgres-operator/main.go:55" version=4.7.5
time="2022-05-09T09:46:14Z" level=info msg="CRUNCHY_DEBUG flag set to false" func="internal/operator.Initialize()" file="internal/operator/common.go:104" version=4.7.5
time="2022-05-09T09:46:14Z" level=info msg="NAMESPACE pgo" func="internal/operator.Initialize()" file="internal/operator/common.go:108" version=4.7.5
time="2022-05-09T09:46:14Z" level=info msg="InstallationName devtest" func="internal/operator.Initialize()" file="internal/operator/common.go:111" version=4.7.5
time="2022-05-09T09:46:14Z" level=info msg="Config: \"pgo-config\" ConfigMap found, using config files from the configmap" func="internal/config.initialize()" file="internal/config/pgoconfig.go:751" version=4.7.5
+ echo 'pgo-event starting'
+ trap trap_sigterm SIGINT SIGTERM
+ echo 'pgo-event starting nsqadmin'
+ /usr/local/bin/nsqadmin --http-address=0.0.0.0:4171 --nsqd-http-address=0.0.0.0:4151
+ sleep 3
pgo-event starting
pgo-event starting nsqadmin
[nsqadmin] 2022/05/09 09:39:27.876240 INFO: nsqadmin v1.1.0 (built w/go1.10.3)
[nsqadmin] 2022/05/09 09:39:27.876663 INFO: HTTP: listening on [::]:4171
+ echo 'pgo-event starting nsqd'
pgo-event starting nsqd
time="2022-05-09T09:45:53Z" level=info msg="debug flag set to false" func="main.init.0()" file="cmd/pgo-scheduler/main.go:68" version=4.7.5
time="2022-05-09T09:45:53Z" level=info msg="PGO_INSTALLATION_NAME set to devtest" func="main.init.0()" file="cmd/pgo-scheduler/main.go:75" version=4.7.5
time="2022-05-09T09:45:53Z" level=info msg="Config: \"pgo-config\" ConfigMap found, using config files from the configmap" func="internal/config.initialize()" file="internal/config/pgoconfig.go:751" version=4.7.5
time="2022-05-09T09:45:54Z" level=error msg="Error in pgoconfig: check pgo.yaml: PrimaryStorage setting is invalid: \"storage9\" is not defined" func="internal/config.(*PgoConfig).GetConfig()" file="internal/config/pgoconfig.go:549" version=4.7.5
time="2022-05-09T09:45:54Z" level=fatal msg="error in Pgo configuration: Error in pgoconfig: check pgo.yaml: PrimaryStorage setting is invalid: \"storage9\" is not defined" func="main.init.0()" file="cmd/pgo-scheduler/main.go:90" version=4.7.5
+ echo 'pgo-event waiting till sigterm'
pgo-event waiting till sigterm
+ wait
+ /usr/local/bin/nsqd --data-path=/tmp --http-address=0.0.0.0:4151 --tcp-address=0.0.0.0:4150 --log-level=warn
time="2022-05-09T09:46:09Z" level=info msg="debug flag set to false"
time="2022-05-09T09:46:14Z" level=info msg="postgres-operator apiserver starts" func="main.main()" file="cmd/apiserver/main.go:111" version=4.7.5
time="2022-05-09T09:46:14Z" level=info msg="Pgo Namespace is [pgo]" func="internal/apiserver.Initialize()" file="internal/apiserver/root.go:100" version=4.7.5
time="2022-05-09T09:46:14Z" level=info msg="InstallationName is [devtest]" func="internal/apiserver.Initialize()" file="internal/apiserver/root.go:107" version=4.7.5
time="2022-05-09T09:46:14Z" level=info msg="apiserver starts" func="internal/apiserver.Initialize()" file="internal/apiserver/root.go:119" version=4.7.5
time="2022-05-09T09:46:14Z" level=info msg="loading PermMap with 56 Permissions\n" func="internal/apiserver.initializePerms()" file="internal/apiserver/perms.go:179" version=4.7.5
time="2022-05-09T09:46:14Z" level=info msg="Config: \"pgo-config\" ConfigMap found, using config files from the configmap" func="internal/config.initialize()" file="internal/config/pgoconfig.go:751" version=4.7.5
time="2022-05-09T09:46:15Z" level=error msg="Error in pgoconfig: check pgo.yaml: PrimaryStorage setting is invalid: \"storage9\" is not defined" func="internal/config.(*PgoConfig).GetConfig()" file="internal/config/pgoconfig.go:549" version=4.7.5
time="2022-05-09T09:46:15Z" level=error msg="Error in pgoconfig: check pgo.yaml: PrimaryStorage setting is invalid: \"storage9\" is not defined" func="internal/apiserver.Initialize()" file="internal/apiserver/root.go:127" version=4.7.5
time="2022-05-09T09:46:15Z" level=error msg="error in Pgo configuration" func="internal/apiserver.Initialize()" file="internal/apiserver/root.go:128" version=4.7.5
time="2022-05-09T09:46:15Z" level=error msg="Error in pgoconfig: check pgo.yaml: PrimaryStorage setting is invalid: \"storage9\" is not defined" func="internal/config.(*PgoConfig).GetConfig()" file="internal/config/pgoconfig.go:549" version=4.7.5
time="2022-05-09T09:46:15Z" level=error msg="Error in pgoconfig: check pgo.yaml: PrimaryStorage setting is invalid: \"storage9\" is not defined" func="internal/operator.Initialize()" file="internal/operator/common.go:124" version=4.7.5
time="2022-05-09T09:46:15Z" level=fatal msg="pgo-config files and templates did not load" func="internal/operator.Initialize()" file="internal/operator/common.go:125" version=4.7.5
^C
[root@master ~]# 

## Additional Information
1.storage class
[root@master ~]# kubectl get sc 
NAME              PROVISIONER                  RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
rook-ceph-block   rook-ceph.rbd.csi.ceph.com   Delete          Immediate           true                   18h
[root@master ~]# 
2. k8s nodes
[root@master ~]# kubectl get node -A
NAME     STATUS   ROLES    AGE   VERSION
master   Ready    master   24h   v1.18.5
work01   Ready    worker   24h   v1.18.5
work02   Ready    worker   23h   v1.18.5
work03   Ready    worker   23h   v1.18.5
[root@master ~]# 
3.rook pod
[root@master ~]# kubectl get po -n rook-ceph
NAME                                               READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-f7dwm                             3/3     Running     6          18h
csi-cephfsplugin-provisioner-776f4d89f6-bbscq      6/6     Running     29         18h
csi-cephfsplugin-provisioner-776f4d89f6-lfqmj      6/6     Running     37         18h
csi-cephfsplugin-wq9cz                             3/3     Running     9          18h
csi-cephfsplugin-xsg26                             3/3     Running     9          18h
csi-rbdplugin-77j89                                3/3     Running     9          18h
csi-rbdplugin-d75mh                                3/3     Running     9          18h
csi-rbdplugin-provisioner-56ffb766f8-9drsq         6/6     Running     38         18h
csi-rbdplugin-provisioner-56ffb766f8-mrh67         6/6     Running     28         18h
csi-rbdplugin-rnk7k                                3/3     Running     9          18h
rook-ceph-crashcollector-work01-7b69b4d84f-wrg88   1/1     Running     3          18h
rook-ceph-crashcollector-work02-56dcc67db-ml4bx    1/1     Running     2          18h
rook-ceph-crashcollector-work03-db79d8779-6m956    1/1     Running     3          18h
rook-ceph-mgr-a-5c884745dc-sqt5b                   1/1     Running     4          14h
rook-ceph-mon-a-85d567fc69-knh5j                   1/1     Running     3          18h
rook-ceph-operator-84c947f948-rhtl6                1/1     Running     5          19h
rook-ceph-osd-0-589d44f7ff-wjzvw                   1/1     Running     3          18h
rook-ceph-osd-1-945f68cf4-bfcfr                    1/1     Running     2          18h
rook-ceph-osd-2-7b684bddb5-rrmp9                   1/1     Running     3          18h
rook-ceph-osd-prepare-work01-b89wn                 0/1     Completed   0          121m
rook-ceph-osd-prepare-work02-glghs                 0/1     Completed   0          121m
rook-ceph-osd-prepare-work03-cn4zs                 0/1     Completed   0          121m
rook-ceph-tools-587d8f9749-n9xfh                   1/1     Running     2          14h
[root@master ~]#

**Comment by andrewlecuyer** [comment]
@longtian001 thanks for using PGO!  This error indicates that your `pgo.yaml` configuration file references a storage configuration (in this case a storage configuration named `storage9`) that doesn't exist in the `pgo.yaml` configuration file (which is stored in a ConfigMap named `pgo-config`).

My thinking here is that a `pgo-config` ConfigMap with an invalid configuration might already exist in your environment, leading to the error you are seeing.  I therefore recommend you first delete any existing `pgo-config` ConfigMap prior to installing.  Also, the logs for the `pgo-deploy` Job (which appears to have errored) might provide a clue as well.

That being said, since it looks like you are creating a new cluster, we recommend that you create your PG cluster using PGO v5 instead.  Documentation and instructions for getting started with the latest version of PGO v5 can be found here:

https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/

As you will see, using PGO v5 you should be able to easily use your Rook StorageClass, e.g.:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.3-0
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClass: rook-ceph-block
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClass: rook-ceph-block
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
```

However, if you continue to have trouble PGO v5, please let us know.
