### ISSUE TITLE
Need to set CO_APISERVER_URL

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/postgres-operator#319]
CO_APISERVER_URL is getting set to:
CO_APISERVER_URL=https://postgres-operator:8443
In my environment I nned to get the pod and set it to the pod's ip address.
kubectl get service postgres-operator
NAME                TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
postgres-operator   NodePort   10.111.200.188   <none>        8443:30854/TCP   5m
export CO_APISERVER_URL=https://10.111.200.188:8443

**Comment by jmccormick2001** [comment]
this is the correct behavior, see hugo/content/installation/deployment.adoc for a description of CO_APISERVER_URL.
