### ISSUE TITLE
Differences between pgo with postgis and without

### ISSUE THREAD

**Issue by matzik12** [CrunchyData/postgres-operator#3191]
Hello,
I wanted to create a new postgrescluster (v5.0.3) on oc4 and had a question about it.
Is there any difference between the image of postgres with postgis and without postgis? 
When I used the image without postgis I could create the extension using the "CREATE EXTENSION postgis;" command,
and when I used the image with postgis I needed to do the same, the DB did not include the postgis extension so there is no differences between those images. Am I missing something?

Thanks,
Ziv

**Comment by andrewlecuyer** [comment]
@matzik12 the PostGIS images have all of the additional packages required to run PostGIS, which are not present in the standard (i.e. non-PostGIS) `crunchy-postgres` container.  For example, you can see the additional PostGIS packages that are installed via the Crunchy PostGIS Dockerfile:

https://github.com/CrunchyData/crunchy-containers/blob/master/build/postgres-gis/Dockerfile
