### ISSUE TITLE
Support backups from replica pod

### ISSUE THREAD

**Issue by turbra** [CrunchyData/postgres-operator#3199]
## What is the motivation or use case for the change?
pgbackrest/pgdumps backups are taken against primary pod.

## Describe the solution you'd like
Enable an option to selectively trigger backups on replica, instead of primary.

## Please tell us about your environment:

Where is this running ( Local, Cloud Provider): `Local`
- Storage being used: `SAN`
- PostgreSQL Version: `13.4`
- Platform: `Openshift`
- Platform Version: `4.8.35`
- Operator Version: `4.7.3`
- Additional context:  `We are not using pgbouncer or pgpool`

**Comment by dsessler7** [comment]
Hello @turbra, 

The recently released v5.7.0 version of Crunchy Postgres for Kubernetes allows for backups from replicas! Please see the [docs](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/backups-disaster-recovery/backups#reducing-primary-instance-load-with-the-backup-from-standby-option) for more info.

If you get a chance to try it out, please let us know what you think!
