### ISSUE TITLE
TLS Secrets not reloaded when updated

### ISSUE THREAD

**Issue by braunsonm** [CrunchyData/postgres-operator#3203]
This is more or less a duplicate of https://github.com/CrunchyData/postgres-operator/issues/2353

I'm not quite satisfied with the resolution of "just `pgo reload <cluster>`". I think it would be a good enhancement for the operator to be able to detect and gracefully handle certificate updates.

In our case we are using a short lived certificate managed by cert-manager, and this causes the certificate to be reissued every 24 hours automatically. We do not have any hand in the update so we can't be there to run `pgo reload`. The operator should handle this gracefully.

Reproduction Steps:
1. Create a certificate with cert manager
2. Create a `PostgresCluster` with `spec.proxy.pgBouncer.customTLSSecret.name` set tot he cert-manager issued certificate
3. Have cert-manager renew that certificate
4. Notice the cert served by pg-bouncer is not updated

**Comment by tjmoore4** [comment]
@braunsonm the certificate reload should now be handled without any manual reload steps, starting in PGO 5.1.0. Local testing using the scenario you described resulting in a configuration reload. Could you try your scenario again in v5.1.0+ and let us know if you're still seeing the issue?

**Comment by braunsonm** [comment]
Hey @tjmoore4 

That's great to hear. Unfortunately we've been unable to update from 5.0.4 because of a bug introduced in later versions of PGO outlined here:
 https://github.com/CrunchyData/postgres-operator/issues/3123

Seems the DNS that is used no longer operates correctly.
