### ISSUE TITLE
V3.1/pre 3.2 - pgo show pvc mycluster shows all cluster created 

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/postgres-operator#321]
pgo show pvc mycluster
	/mycluster
	/testcluster
	/xraydb0
	/xraydb1
	/xraydb2

**Comment by jmccormick2001** [comment]
this is expected when you use a shared file system like hostpath or NFS, you can use 'pgo show pvc mycluster' command flags to drill down further below the root if necessary.
