### ISSUE TITLE
Reboot of pod when needed

### ISSUE THREAD

**Issue by matzik12** [CrunchyData/postgres-operator#3211]
Hello,
Im using PGO 5.0.4 and when I am changing postgres parameters in the CR, like in your documentation, the postgres does not restart. 
When I use the command "patronictl list" I can see a new column of "Required reboot" and the operator does not reboot the postgres for me. The documentations says that if I change a parameter that requires reboot it will do it by itself, and It is not happening. Hope to know if it is a bug or I did something wrong.
Thanks,
Ziv

**Comment by cbandy** [comment]
This is fixed in [PGO 5.1.0](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.1.0/).

> - Postgres configuration changes requiring a database restart are now automatically rolled out to all instances in the cluster.
