### ISSUE TITLE
Q: Does DB cluster recover automatically, if all pods are deleted in one go (nowadays)? With sync mode & sync strict mode.

### ISSUE THREAD

**Issue by Samusername** [CrunchyData/postgres-operator#3221]
Q: Does DB cluster recover **automatically**, if all pods are deleted in one go (nowadays)? 
With kubectl delete pod pod-1 pod-2 pod-3 
**Sync** mode / sync strict mode would be in use.
With CrunchyData postgres-operator.

"Two years" ago it did not start up automatically in such scenario, with such setup. But how does it work nowadays?

[ Of course, I can test it also, but just currently I do not have spare time yet, to try it quickly. But such information would be good to know. ]

**Comment by nut24101** [comment]
All pods are deployed by statefulset, so they have their own PV.
I think it will not affect data by deleting all pods at one.

**Comment by andrewlecuyer** [comment]
As described by @tjmoore4, all is currently working as expected when we test Synchronous Replication with PGO.

If you are still running into issues with Synchronous Replication and PGO v5, or if you have any other questions, please feel free to re-open this issue or to submit a new issue.

Also, if you are still running into an issue with Synchronous Replication, any additional details about your environment, use case, PGO version, etc. would be much appreciated to troubleshoot further.
