### ISSUE TITLE
How to build PGO PostgreSQL image.

### ISSUE THREAD

**Issue by shinyaaa** [CrunchyData/postgres-operator#3225]
Hi!

I would like to build a PostgreSQL Docker image for use with PGO.
What is the relationship between [1] and [2]? I am not sure which Dockerfile to use.

[1] https://github.com/CrunchyData/postgres-operator/blob/master/build/pgo-base/Dockerfile
[2] https://access.crunchydata.com/documentation/crunchy-postgres-containers/5.1.0/contributing/building/

Regards,
Shinya Kato

**Comment by tjmoore4** [comment]
Hello @shinyaaa, 

The Postgres image is currently built using the [Crunchy Containers repo](https://github.com/CrunchyData/crunchy-containers) and is unrelated to the `pgo-base` image (reference [1]).

**Comment by shinyaaa** [comment]
Hi @tjmoore4,

Thanks! I will try.

**Comment by andrewlecuyer** [comment]
With the original question answered, proceeding with closing this issue.

Please feel free to reopen or submit a new issue if you have any additional questions.

**Comment by shinyaaa** [comment]
Hi, I also re-opened the issue because I was not sure.

Am I correct that pgo-base is used to build postgres-operator and crunchy-postgres-exporter?
If so, I assume the following part of the Makefile will not work properly? (if we follow the no-tag policy)
---
PGO_VERSION ?= $(shell git describe --tags)
---
