### ISSUE TITLE
How to rebuild postgres operator v5.1.1

### ISSUE THREAD

**Issue by olivejing** [CrunchyData/postgres-operator#3231]
## Questions
Hi,
From crunchdata document, V5.1.1 has been released. I want to rebuild V5.1.1, due to there is no tag, i do not know how to get the source code of V5.1.1. So could you provide the commit id or some other flags? Thanks.

**Comment by andrewlecuyer** [comment]
@olivejing please see the "Where are the release tags for PGO v5?" question within the PGO FAQ:

https://pgo5-docs-preview.crunchydata.com/faq/#where-are-the-release-tags-for-pgo-v5
