### ISSUE TITLE
V4 vs V5 confusing

### ISSUE THREAD

**Issue by jfmatth** [CrunchyData/postgres-operator#3244]
First off, I LOVE PGO!  Great project and product.

I'm using the v5 of the PGO and (maybe it's me, but..) it's confusing to track just the 5.x changes.  I'm subscribed to this repo for releases, but seems like 4.x is the main focus.

Am I missing something?

Thanks,

John

**Comment by kreempuff** [comment]
What was the conclusion here @jfmatth? I'm running into similar confusions

**Comment by jfmatth** [comment]
> What was the conclusion here @jfmatth? I'm running into similar confusions

They seemed to be updating 4 and 5 in parallel, but didn't find where the 5.x stuff was stored in docker.io.

I have shutdown my project using PGO for now, so hoping 5.x is the only version updated, also I think they've moved to an operator framework only vs. running PGO on the CLI.

HTH

**Comment by kreempuff** [comment]
It does, thanks!
