### ISSUE TITLE
PostgreSQL images PGO V5

### ISSUE THREAD

**Issue by matzik12** [CrunchyData/postgres-operator#3249]
Hi,
Whenever I needed an image I installed it using your download section in your website. Today I wanted to get postgres 12.9 image and saw that the oldest version you give access to is 13.3 . Where can I reach the older versions of postgres images? I can't use any other version accept postgres 12...
Thanks,
Ziv Yatzik

**Comment by jfmatth** [comment]
I had a similar ask, and eventually just moved to the latest, which i think for PG13 breaks some stuff.

**Comment by sunofsparda** [comment]
Hi everyone,
Perhaps would be helpful https://github.com/CrunchyData/postgres-operator/issues/3139

**Comment by andrewlecuyer** [comment]
Please see the [Terms of Use](https://www.crunchydata.com/developers/terms-of-use) for the Crunchy Developer Program.

Additionally, please note that container images that are no longer available through the Crunchy Data Developer Program are available through the Crunchy Data Access Portal ([subscription ](https://www.crunchydata.com/about/value-of-subscription)required). If you have any questions, or if you would like to discuss your use case further, please feel free to contact us as [info@crunchydata.com](mailto:info@crunchydata.com).
