### ISSUE TITLE
Annotations for main ha service

### ISSUE THREAD

**Issue by gricey432** [CrunchyData/postgres-operator#3265]
## Overview

Add support for annotating the `<mycluster>-ha` service

## Use Case

I've started some postgres clusters using `spec.service.type: NodePort` for external connectivity.

I'm using [external-dns](https://github.com/kubernetes-sigs/external-dns) to publish the postgres cluster's IP addresses as A records to Route 53.
This system relies on an annotation on the services you'd like to have tracked:

```
external-dns.alpha.kubernetes.io/hostname: "mypostgres.databases.internal"
```

Attaching the annotation in `spec.metadata.annotations` results in the annotation being attached to all sorts of services, giving an incorrect list of IPs published to DNS.

## Desired Behavior

Searching the PGO CRD, some parts have annotations, like pgbouncer.

This same pattern would be exposed for the "main" service (patroni?).

I'm unsure if this would be better exposed as `spec.service.metadata` or `spec.patroni.metadata`.

I think the only required change is

https://github.com/CrunchyData/postgres-operator/blob/f4231d96e42ebab000726c002cc395d9fd6a40bd/internal/controller/postgrescluster/patroni.go#L236-L237

should use the same pattern as

https://github.com/CrunchyData/postgres-operator/blob/f4231d96e42ebab000726c002cc395d9fd6a40bd/internal/controller/postgrescluster/pgbouncer.go#L261-L263

## Environment

Tell us about your environment:

Please provide the following details:

Platform: EKS
Platform Version: eks.2 k8s 1.22
PGO Image Tag: ubi8-14.2-1
Postgres Version: 14
Storage: gp3
Number of Postgres clusters: 2

**Comment by andrewlecuyer** [comment]
@gricey432 thank you for your submission!

An enhancement request has been added to the PGO backlog for implementation in a future PGO release.
