### ISSUE TITLE
Cluster Major upgrade from centos8-12.6-4.6.2 to centos8-13.2-4.6.2

### ISSUE THREAD

**Issue by ggrames** [CrunchyData/postgres-operator#3267]
Hi,

Since the registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-12.6-4.6.2 image is not available i want to update my postgres cluster to newer major version 13.2

## Questions
I started the pgo client with the command "pgo upgrade postgres -n mynamespace" and confirmed with "yes" the upgrade procedure. But the pod only terminated and nothing else happens.

I can see if the pods are started on a node which has the not available images locally stored it starts with an error.
If the image is already locally the postgres starts with the old version.
How is the correct way to upgrade the old version to the higher major version, when the images are not reachable anymore.

How will the new version (the target version) be selected? Is this automatically?

### Environment

Please provide the following details:

- Platform: (OpenShift)
- Platform Version: (4.9.37)
- PGO Image Tag OLD: (centos8-12.6-4.6.2)
- PGO Image Tag NEW: (centos8-13.2-4.6.2)
- Postgres Version (12.6 13.2)
- Storage: (vsphere thin)
- PGO Operator Version: 4.6.2

**Comment by ggrames** [comment]
My upgrade.json looks like:
`
{
    "apiVersion": "batch/v1",
    "kind": "Job",
    "metadata": {
        "name": "upgrade",
        "labels": {
            "app": "upgrade",
            "cleanup": "shared-datastores-development-upgrade"
        }
    },
    "spec": {
        "backoffLimit": 0,
        "template": {
            "metadata": {
                "name": "upgrade",
                "labels": {
                    "app": "upgrade",
                    "cleanup": "shared-datastores-development-upgrade"
                }
            },
            "spec": {
                "volumes": [
                    {
                        "name": "pgolddata",
                        "persistentVolumeClaim": {
                            "claimName": "postgres"
                        }
                    },
                    {
                        "name": "pgnewdata",
                        "persistentVolumeClaim": {
                            "claimName": "upgrade-postgres"
                        }
                    }
                ],
                "securityContext": {
                    $CCP_SECURITY_CONTEXT
                },
                "containers": [
                    {
                        "name": "upgrade",
                        "image": "crunchydata/crunchy-upgrade:centos8-13.2-4.6.2",
                        "volumeMounts": [
                            {
                                "mountPath": "/pgolddata",
                                "name": "pgolddata",
                                "readOnly": false
                            },
                            {
                                "mountPath": "/pgnewdata",
                                "name": "pgnewdata",
                                "readOnly": false
                            }
                        ],
                        "env": [
                            {
                                "name": "OLD_DATABASE_NAME",
                                "value": "postgres"
                            },
                            {
                                "name": "NEW_DATABASE_NAME",
                                "value": "postgres-upgrade"
                            },
                            {
                                "name": "OLD_VERSION",
                                "value": "12"
                            },
                            {
                                "name": "NEW_VERSION",
                                "value": "13"
                            }
                        ]
                    }
                ],
                "restartPolicy": "Never"
            }
        }
    }
}
`

I get the Error after i execute 'pgo upgrade postgres -n shared-datastores-development'

Error: cannot upgrade from centos8-12.6-4.6.2 to centos8-13.2-4.6.2, upgrade task failed.

Thanks

**Comment by andrewlecuyer** [comment]
@ggrames please upgrade to PGO v5, which has support for major PG upgrades.  Upgrade guidance to upgrade from PGO v4 to our latest PGO v5 release can be found here:

https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/v4tov5/

Additionally, please see the following blog for guidance performing a major PG upgrade using PGO and the PGUpgrade API:

https://www.crunchydata.com/blog/easy-major-postgresql-upgrades-using-pgo-v51
