### ISSUE TITLE
No matches for kind "CustomeResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by rg2609** [CrunchyData/postgres-operator#3276]
## Overview

Trying to install the CrunchyData Postgres operator through the Terraform on the K3s server. I am using the PGO Image Tag: "centos8-4.7.0"
I am getting the following error:
```
TASK [pgo-operator : Create PGClusters CRD] ************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml"], "delta": "0:00:03.704244", "end": "2022-06-27 06:34:28.810771", "msg": "non-zero return code", "rc": 1, "start": "2022-06-27 06:34:25.106527", "stderr": "error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\"", "stderr_lines": ["error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\""], "stdout": "", "stdout_lines": []}
```

## Environment

Please provide the following details:

- Platform:  `Rancher`
- Platform Version: 
```
Client Version: v1.24.1+k3s1
Kustomize Version: v4.5.4
Server Version: v1.24.1+k3s1
```
- PGO Image Tag: "centos8-4.7.0"
- Storage:  `nfs`

**Comment by andrewlecuyer** [comment]
@rg2609 thank you for using PGO!

Please install [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/), which supports Kubernetes 1.24 out-of-the-box (based on the image tag you provided you are using PGO v4.7.0, and should instead switch to our latest PGO release, v5.1.1).  The quickstart for PGO v5.1.1 can be found here:

https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/

For PGO v4 support for Kubernetes 1.24,please feel free to reach out to [info@crunchydata.com](mailto:info@crunchydata.com) to further discuss your use case.

**Comment by rg2609** [comment]
Thank @andrewlecuyer for your quick reply, will try and update here

**Comment by rg2609** [comment]
Hi @andrewlecuyer, 
I updated the PGO tag as you suggested v5.1.1 ([ubi8-5.1.1-0](https://access.crunchydata.com/documentation/postgres-operator/v5/installation/helm/)) in [helm chat](https://github.com/CrunchyData/postgres-operator/tree/v4.7.6/installers/helm) but now it's showing a different error `image not found.`

Then now I am using [Helm](https://github.com/CrunchyData/postgres-operator/tree/v4.7.5/installers/helm) but in this also I am getting the same error. 
```
TASK [pgo-operator : Create PGClusters CRD] ************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml"], "delta": "0:00:00.154125", "end": "2022-06-30 12:50:53.818784", "msg": "non-zero return code", "rc": 1, "start": "2022-06-30 12:50:53.664659", "stderr": "error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\"", "stderr_lines": ["error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\""], "stdout": "", "stdout_lines": []}
```

**Comment by rg2609** [comment]
> https://access.crunchydata.com/documentation/postgres-operator/latest/installation/helm/

But this one is `EXAMPLE`, right?

**Comment by rg2609** [comment]
@andrewlecuyer now we are trying this example but we are getting an error explained [here](https://github.com/CrunchyData/postgres-operator-examples/issues/136)

**Comment by rg2609** [comment]
@andrewlecuyer any update on this
