### ISSUE TITLE
Support IPv6 for backrest (mTLS)

### ISSUE THREAD

**Issue by gkolvo** [CrunchyData/postgres-operator#3286]
## Overview

Add support for pure IPv6 environments.

## Use Case

Now pgBackRest 2.38 listens on the first address returned by ```getaddrinfo()```. For pure IPv6 the first address is always IPv4.
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
```

## Desired Behavior

I would like to have possibility to customize ```tls-server-address``` and set it to ```--tls-server-address=::1``` 

Now it is hardcoded to ```global.Set("tls-server-address", "0.0.0.0")```

https://github.com/CrunchyData/postgres-operator/blob/6feb0ab6a28aafde023abd41ae2474323b7d043b/internal/pgbackrest/config.go#L439-L458

The proposal is to make this parameter configurable somewhere.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: (`Kubernetes`)
- Platform Version: (e.g. `1.21.7`)
- PGO Image Tag: (e.g. `ubi8-5.1.0-0`)
- Postgres Version (e.g. `13`)
- Storage: (e.g. `rook-cephfs`)
- Number of Postgres clusters: (`2`)

## Additional Information
Using global variables I get:
**pgbackrest ERROR: [031]: option 'tls-server-address' cannot be set multiple times**

**Comment by cbandy** [comment]
I've opened a request at https://github.com/pgbackrest/pgbackrest/issues/1841.

**Comment by andrewlecuyer** [comment]
@gkolvo can you try the following workaround to configure the pgBackRest TLS server for IPv6?

First, create a custom pgBackRest configuration file (e.g. `pgbr-custom.conf`) containing the following:
```conf
[global:server]
tls-server-address = ::

[global:server-ping]
tls-server-address = localhost
```

Which you can then turn into a ConfigMap:
```bash
kubectl create cm --from-file=pgbr-custom.conf my-pgbr-config
```

And from there you can add that to your pgBackRest configuration in the PostgresCluster spec, e.g.:
```yaml
spec:
  backups:
    pgbackrest:
      configuration:
      - configMap:
          name: my-pgbr-config
```

You should then see the pgBackRest TLS server pickup these settings when starting, which you can verify via the logs:
```bash
$ kubectl logs -c pgbackrest hippo-repo-host-0
P00   INFO: server command begin 2.40: --exec-id=32-b3185ba1 --log-level-console=detail --log-level-file=off --log-level-stderr=error --log-path=/pgbackrest/repo1/log --no-log-timestamp --tls-server-address=:: --tls-server-auth=pgbackrest@5a69a641-1fa9-4b46-b2d1-101edcf6fb09=* --tls-server-ca-file=/etc/pgbackrest/conf.d/~postgres-operator/tls-ca.crt --tls-server-cert-file=/etc/pgbackrest/server/server-tls.crt --tls-server-key-file=/etc/pgbackrest/server/server-tls.key
```
More specifically, note that `--tls-server-address=` is now `::`.

Looking forward to hearing your results!

**Comment by gkolvo** [comment]
@andrewlecuyer I checked this WA on 5.2.0 and it seems it works! :)
I will use this approach until pgbackrest fix it.

Thanks!

**Comment by benjaminjb** [comment]
Since that workaround works for now and we have an issue opened in pgbackrest, I'll close this issue now, but feel free to reopen if there's more here to discuss.
