### ISSUE TITLE
CRD extend spec/service/type with loadBalancerIP

### ISSUE THREAD

**Issue by kowei** [CrunchyData/postgres-operator#3289]
## Overview

Lack of spec/service/loadBalancerIP will result in dynamic internal/external IP assigned from the platform

## Use Case

Normally, I prefer to make static IPs before service deployment.  It helps better networking management, instead of dynamic IP from the platform. Because you will get extra management jobs when you have new IP, and it will change when the pod restarted.

## Desired Behavior

Provide normal spec/service/loadBalancerIP in CRD

## Environment

- Platform: AKS
- Platform Version: 1.22.6
- PGO Image Tag: ubi8-14.2-1
- Postgres Version 14
- Storage: AzureDisk
- Number of Postgres clusters: 1

## Additional Information

N/A

**Comment by andrewlecuyer** [comment]
@kowei per the Kubernetes [Service spec](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec), `loadBalancerIP` is deprecated an will be removed from future versions of Kuberenetes:

> Deprecated: This field was under-specified and its meaning varies across implementations, and it cannot support dual-stack. As of Kubernetes v1.24, users are encouraged to use implementation-specific annotations when available. This field may be removed in a future API version.

Therefore, per this guidance your specific Kubernetes vendor (e.g. AKS) will need to align with this convention/guidance to ensure proper configuration of static IP's for `LoadBalancer` services via annotations in future versions of Kubernetes.

And the meantime, if you need to specify `loadBalancerIP`, you can manually patch the `loadBalancerIP` into the service as needed, e.g.:

```bash
$ kubectl patch service hippo-ha -p '{"spec":{"loadBalancerIP":"127.0.0.1"}}'
service/hippo-ha patched
```
