### ISSUE TITLE
How do you install an extension that is not included in the image

### ISSUE THREAD

**Issue by philmccOri** [CrunchyData/postgres-operator#3292]
I can see in the docs how to configure the set up of an extension but I cannot see how to install an extension that is not already in the image.

Is this possible and is it in the docs anywhere?

Thanks

**Comment by james-callahan** [comment]
Duplicate of https://github.com/CrunchyData/postgres-operator/issues/2016

**Comment by benjaminjb** [comment]
Closing as duplicate, let's continue the conversation on the linked issue.
