### ISSUE TITLE
Unable to upgrade from v5.0.5 to v5.1.2 using Helm

### ISSUE THREAD

**Issue by jayaswalayush** [CrunchyData/postgres-operator#3309]
## Overview

While upgrading from v5.0.5 to v5.1.2 using helm gives the below error :

2022-07-18 10:14:15.755 UTC [247] FATAL:  database files are incompatible with server
2022-07-18 10:14:15.755 UTC [247] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 14.4.

## Environment

Please provide the following details:

Platform: (Kubernetes)
Platform Version: (1.23.1)
PGO Image Tag: ( ubi8-5.1.2-0 and ubi8-5.0.5-0)
Postgres Version (14 and 13)

## Steps to Reproduce

https://access.crunchydata.com/documentation/postgres-operator/5.1.2/upgrade/helm/

What specific values need to be specified for upgrading the PostgreSQL clusters from 13 to 14

postgrescluster_upgrade.yaml

---
name: postgres
instances:
  - name: instance1
    replicas: 2
    dataVolumeClaimSpec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: nodes
              operator: In
              values:
              - db_nodes
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: postgres
                postgres-operator.crunchydata.com/instance-set: instance1
pgBackRestConfig:
  global:
    repo1-retention-full: "14"
    repo1-retention-full-type: time
  manual:
    repoName: repo1
    options:
     - --type=full
  repos:
  - name: repo1
    schedules:
      full: "0 1 * * 0"
      differential: "0 1 * * 1-6"
    volume:
      volumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  restore:
    repoName: repo1
    enabled: false
    options:
    - --type=time
    - --target="2022-07-01 00:00:01"
port: 5432
patroni:
  dynamicConfiguration:
    synchronous_mode: true
    postgresql:
      parameters:
        synchronous_commit: "on"
users:
  - name: datamart
    databases:
      - datamart
    options: "SUPERUSER"
service:
  type: NodePort
openshift: false

helm upgrade postgrescluster postgrescluster -n pgo -f postgrescluster_upgrade.yaml

**Comment by Schmaetz** [comment]
You write about operator upgrade above but to me it sounds more like a postgres-upgrade.

Did you try a pg_upgrade where only the image in the cluster definition was changed?

You have to do it like this: https://www.crunchydata.com/blog/easy-major-postgresql-upgrades-using-pgo-v51

**Comment by andrewlecuyer** [comment]
As described in the previous response, it appears as though you are attempting to upgrade from PG 13 to PG 14 without utilizing the major PG upgrade process.  Therefore, if you are looking to upgrade to PG 14, please follow the blog referenced above:

https://www.crunchydata.com/blog/easy-major-postgresql-upgrades-using-pgo-v51

Otherwise you can simply stick with PG 13 for your cluster when upgrading PGO to v5.1.2, which should also prevent this error from occurring.
