### ISSUE TITLE
pgbackrest backup options

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#331]
By default pgbackrest performs Incremental backup, which is based on previous full backups. with current implementation, first time backup is full and all subsequent backups are incremental.

I would suggest to pass pgbackrest option of --type=full or diff in pgo backup command.

command should look like: pgo backup mycluster --backup-type=pgbackrest --backup-mode=full/diff

**Comment by jmccormick2001** [comment]
merged into develop branch, with this change you will have "--pgbackrest-opts" flags for both the 'pgo backup' and 'pgo restore' commands instead of the prior "--restore-opts' flag.

**Comment by jmccormick2001** [comment]
@pmereddy1
