### ISSUE TITLE
Image for crunchy-postgres v12.11

### ISSUE THREAD

**Issue by maleka12** [CrunchyData/postgres-operator#3310]
In the release notes of PGO v5.1.1 there is note:
[PostgreSQL](https://www.postgresql.org/) versions 14.3, 13.7, 12.11, 11.16, and 10.21 are now available.
link: 
https://access.crunchydata.com/documentation/postgres-operator/v5/releases/5.1.1/

Where can I find image for crunchy-postgres:ubi8-12.11-0 ? 

This image in not available in registry.developers.crunchydata.com nor redhat registry: registry.connect.redhat.com/crunchydata/crunchy-postgres

**Comment by benjaminjb** [comment]
Hello, unfortunately we do not maintain images older than Postgres 13 currently; that documentation is out-of-date.
