### ISSUE TITLE
Restore backup from production cluster to staging cluster

### ISSUE THREAD

**Issue by belmeopmenieuwesim** [CrunchyData/postgres-operator#3316]
I have a Postgres cluster running in **production** using this operator and a separate cluster running in **staging**. I would really like to be able to restore or setup/clone the staging cluster from the pgBackRest backups made for the production cluster (so I can test on live data on staging). 

How can I do this, without the backup repository for the production cluster getting corrupted?

**Comment by andrewlecuyer** [comment]
@belmeopmenieuwesim please see the following tutorial within the [PGO documentation](https://access.crunchydata.com/documentation/postgres-operator/latest) for guidance/instructions on cloning an existing  PostgresCluster:

https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/#clone-a-postgres-cluster
