### ISSUE TITLE
how to build crunchy-postgres image?

### ISSUE THREAD

**Issue by kangzemin** [CrunchyData/postgres-operator#3317]
hello,we deployed crunchydata/postgres-operator,and  thought it was great after useing it.
and we want build the image crunchydata/crunchy-postgres, but we can not find the docker file for this image, where can we get the dockerfile?

**Comment by pere3** [comment]
hello, everything images related is here: https://github.com/CrunchyData/crunchy-containers

**Comment by benjaminjb** [comment]
Closing this as answered by the community (thanks @pere3 ), please reopen if you need more info.
