### ISSUE TITLE
Pgbackrest S3 repo issue with Minio

### ISSUE THREAD

**Issue by ravipokala** [CrunchyData/postgres-operator#3319]
Hi,

I am trying to add Minio as S3 repo type through Pgbackrest in PgCluster created from the Crunchy PGO operator. I am running into the issue below, which complaints about version mismatch. I did disable TLS verification.

**pgbackrest stanza-create --db-path=/pgdata/test --repo1-type=s3 --no-repo1-s3-verify-tls**

**ERROR: [101]: raised from remote-0 protocol on 'test-backrest-shared-repo': TLS error [1:336130315] wrong version number**

Platform: Kubernetes
PGO 4.7.0

**Comment by rmiguelac** [comment]
I had the same issue and could only make it work setting MinIO with TLS

https://github.com/CrunchyData/postgres-operator-examples/issues/82#issuecomment-1026060585

**Comment by ravipokala** [comment]
that worked, thank you.
