### ISSUE TITLE
pgo pgbackrest options

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#332]
Currently in order to restore pgbackrest backup to new pvc, syntax is 
> 
pgo restore withbr --to-cluster=restored
> 

the option --to-cluster is bit confusing, it would be appropriate to call it --to-pvc as it is actually restoring to new pvc and not new cluster.

**Comment by jmccormick2001** [comment]
@pmereddy1 
merged into develop branch a change, now its 'pgo restore somecluster --to-pvc=somenewcluster'
instead of 'pgo restore somecluster --to-cluster......'
