### ISSUE TITLE
postgres-operator sourcecode

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3324]
I found that pgo does some translations ("auto corrections"). 

E.g. setting a wrong "spec.patroni.dynamicConfiguration.postgresql.parameters.archive_command: '/bin/true'" will be overwritten by a correct "spec.patroni.dynamicConfiguration.postgresql.parameters.archive_command: 'pgbackrest --stanza=db archive-push "%p"'.

I wanted to have a look at the sourcecode to see all such translations. But I can't find the code!?

Question 1) Where is this translation done?

Question 2) Where can I find the sourcecode?

Thanks, Markus

**Comment by andrewlecuyer** [comment]
@mzwettler2 the setting you referenced is set here:

https://github.com/CrunchyData/postgres-operator/blob/a909d4aeebc3d55e8512c13aba0f532958a15c8c/internal/pgbackrest/postgres.go#L41-L43

As you can see, the setting is `Mandatory`, meaning PGO is opinionated about that specific setting.

You will also see `Default` configuration settings, which unlike those that are mandatory, can be overridden.  Here is one example:

https://github.com/CrunchyData/postgres-operator/blob/a909d4aeebc3d55e8512c13aba0f532958a15c8c/internal/pgbackrest/postgres.go#L58
