### ISSUE TITLE
Chart version 3.2.0 fails to pull images

### ISSUE THREAD

**Issue by sra** [CrunchyData/postgres-operator#333]
Looks like the values.yaml is set to pull `crunchydata/postgres-operator:centos7-3.2.0-rc3`, but it doesn't exist. 

Changing it to `crunchydata/postgres-operator:centos7-3.2.0` seems to install

This is on `master` and tag`3.2.0`

**Comment by jmccormick2001** [comment]
thanks, fixed it in master.
