### ISSUE TITLE
HA PGOv4 Cluster failing  if one of the underneath Kubernetes cluster node restarts/re-created 

### ISSUE THREAD

**Issue by nagannv** [CrunchyData/postgres-operator#3336]
[PGO_clusters__POD.zip](https://github.com/CrunchyData/postgres-operator/files/9246915/PGO_clusters__POD.zip)
HA PGO clusters are failing if one of the underneath Kubernetes clusters restarts/recreated 

we are deploying the HA PGOv4.7.4 cluster with the below configuration on OpenStack Magnum Kubernetes environment

```
$ pgo version
pgo client version 4.7.4
Handling connection for 8443
pgo-apiserver version 4.7.4

```
```
pgo create cluster fxxxx --pgbouncer --replica-count=2   --pod-anti-affinity=preferred   --sync-replication --pvc-size=10Gi   --pgbackrest-pvc-size=10Gi   --pgbackrest-storage-type=posix   --password-superuser=0xxxxxxxxxxxxx   --password-replication=0xxxxxxxxxxxxx   --password=0xxxxxxxxxxxx   --username fxxxxxxxxxx

pgo create cluster ixxx --pgbouncer --replica-count=2   --pod-anti-affinity=preferred   --sync-replication --pvc-size=10Gi   --pgbackrest-pvc-size=10Gi   --pgbackrest-storage-type=posix   --password-superuser=0xxxxxxxxxxxxx   --password-replication=0xxxxxxxxxxxxx   --password=0xxxxxxxxxxxxx   --username ixxxxxxxxxx

pgo create cluster sxxxxx --pgbouncer --replica-count=2   --pod-anti-affinity=preferred   --sync-replication --pvc-size=10Gi   --pgbackrest-pvc-size=10Gi   --pgbackrest-storage-type=posix   --password-superuser=0xxxxxxxxxxxx  --password-replication=0xxxxxxxxxxxxx   --password=0xxxxxxxxxxxxx  --username sxxxxxxxxxx
```

The DB cluster pods are moving to `INFO: following a different leader because I am not the healthiest node`
the DB connection to the application failed, resulting an application outage.

Please find the sharing the logs, this is the second time in the past 6 months

in the fen2022 reported the [same]([url]()) issue in https://github.com/CrunchyData/postgres-operator/issues/3035

## Environment

- Platform: Kubernetes Openstack magnum
- Platform Version: 1.20.3
- PGO Image Tag: pgo-deployer:centos8-4.7.4
- Postgres Version (e.g. `14`)
- Storage: b1.standard

**Comment by tjmoore4** [comment]
@nagannv As also mentioned in #3305, in PGO v5 Pod disruption budgets and other related improvements have been implemented to improve PGO behavior with Kubernetes cluster node restarts, node draining, etc. As such, we would recommend upgrading to v5. If you are still encountering the same issue after the upgrade, feel free to resubmit an issue.
