### ISSUE TITLE
Is there a way to get which commit the released image is built based on?

### ISSUE THREAD

**Issue by polikeiji** [CrunchyData/postgres-operator#3346]
This question is the one following those questions.
https://github.com/CrunchyData/postgres-operator/issues/2604
https://github.com/CrunchyData/postgres-operator/issues/2617

For PGO 4, I think we can track it with Git tags.

But based on the above issues, I think we can't do it using the tags anymore. Is there a way to get it now?

**Comment by till** [comment]
Here to bump this up.

I've also read the FAQ and the associated issues. Is it possible to get an answer as to why tags are no longer published? It seems a bit counter productive to not know what you are running?

If tags are only available to paying customers, that's "fine", but please say so? (cc @jkatz)

**Comment by benjaminjb** [comment]
Yes, as noted by Jonathan in that linked issue, we don't currently tag in this repo to focus on active development.
