### ISSUE TITLE
Exporter: queryNamespaceMappings returned 3 errors

### ISSUE THREAD

**Issue by bendilley** [CrunchyData/postgres-operator#3349]
## Overview

When adding the exporter sidecar to my PostgresCluster spec, the logs for that container output the same error messages every 15 seconds:
```
time="2022-08-15T13:26:47Z" level=info msg="Error running query on database \"localhost:5432\": ccp_nodemx_mem pq: could not open file \"/sys/fs/cgroup//memory.limit_in_bytes\" for reading: No such file or directory" source="postgres_exporter.go:1356"
time="2022-08-15T13:26:47Z" level=info msg="Error running query on database \"localhost:5432\": ccp_nodemx_cpucfs pq: could not open file \"/sys/fs/cgroup//cpu.cfs_period_us\" for reading: No such file or directory" source="postgres_exporter.go:1356"
time="2022-08-15T13:26:47Z" level=info msg="Error running query on database \"localhost:5432\": ccp_nodemx_cpuacct pq: failed to find controller cpuacct" source="postgres_exporter.go:1356"
time="2022-08-15T13:26:47Z" level=error msg="queryNamespaceMappings returned 3 errors" source="postgres_exporter.go:1474"
```
In Grafana, the PGExporterScrapeError alert is firing for every instance.

## Environment

- Platform: `Kubernetes`, `Linode LKS`
- Platform Version: `Kubernetes 1.23.6`, `Debian GNU/Linux 11 (bullseye)   5.10.0-14-cloud-amd64`
- PGO Image Tag: `crunchy-postgres-exporter:ubi8-5.1.2-0`
- Postgres Version `14.2`
- Storage: `linode-block-storage-retain`

### REPRO

Provide steps to get to the error condition:

1. Run `kubectl apply cluster.yml`
1. Do `kubectl logs -fc exporter hippo-data-587d-0`
1. Try `Prometheus Alerts dashboard in Grafana`

### EXPECTED

For the container to run without errors.

### ACTUAL

Errors are being logged and PGExporterScrapeError alert is firing with critical severity.

## Logs

```
time="2022-08-15T13:26:47Z" level=info msg="Error running query on database \"localhost:5432\": ccp_nodemx_mem pq: could not open file \"/sys/fs/cgroup//memory.limit_in_bytes\" for reading: No such file or directory" source="postgres_exporter.go:1356"
time="2022-08-15T13:26:47Z" level=info msg="Error running query on database \"localhost:5432\": ccp_nodemx_cpucfs pq: could not open file \"/sys/fs/cgroup//cpu.cfs_period_us\" for reading: No such file or directory" source="postgres_exporter.go:1356"
time="2022-08-15T13:26:47Z" level=info msg="Error running query on database \"localhost:5432\": ccp_nodemx_cpuacct pq: failed to find controller cpuacct" source="postgres_exporter.go:1356"
time="2022-08-15T13:26:47Z" level=error msg="queryNamespaceMappings returned 3 errors" source="postgres_exporter.go:1474"
```

## Additional Information

This Q&A seems like it could be related: https://stackoverflow.com/questions/65646317/sys-fs-cgroup-memory-memory-limit-in-bytes-not-present-in-fedora-33

**Comment by andrewlecuyer** [comment]
Hi @bendilley thanks for reaching out!

This issue is currently being tracked in the following issue in the pgMonitor project: https://github.com/CrunchyData/pgmonitor/issues/273.

**Comment by bendilley** [comment]
Thanks @andrewlecuyer - I'll keep an eye on it there and contribute if I can.
