### ISSUE TITLE
Inconsistency with flag shorthands

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/postgres-operator#335]
There's inconsistent shorthand use between commands. For example, `-x` - 

```
pgo label
|`--delete-label` |-x |String |

pgo create cluster
|`--backup-path` |-x |String |
```

Or `-l`:

```
pgo load
|`--load-config` |-l |String |

pgo create cluster
|`--labels` |-l |String |

pgo label
|`--label` |-l |String |
```

`-s`:

```
pgo create cluster
|`--secret-from` |-s |String |

all other commands...
|`--selector` |-s |String |
```

`-e`:

```
pgo user
|`--expired` |-e |String |

pgo create cluster
|`--series` |-e |Int |
```

etc.

This should be addressed so that each command with a shortcode has a unique character that is relevant to only that command across all combinations with other flags.

**Comment by xenophenes** [comment]
@jmccormick2001 total list of proposed shorthands, with all others not listed here being removed:

--selector | -s
--output | -o
--delete-data | -d
--delete-backups | -b
--no-prompt | -n

These seem fairly universal, and we can add on shortcodes as more general ones are added or if there's a usability demand for it. 

Thoughts on also adding `pgo -v` for `pgo version` to be able to use either/or?

**Comment by jmccormick2001** [comment]
those shorthands are fine, and -v is fine too.

**Comment by xenophenes** [comment]
@cahoonpwork this issue is not ready to be closed! I need to implement the new shorthands :)

**Comment by cahoonpwork** [comment]
@xenophenes  Sorry, thought I read that a merge had taken place for it.
