### ISSUE TITLE
integrate with crunchy-cron-scheduler

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/postgres-operator#338]
1. Pgo backup mycluster --schedule=”* * * * 1” --backup-type=
2. Pgo show schedule mycluster
3. Pgo delete schedule mycluster
4. Pgo create schedule --schedule=”* * * 1” --selector=env=research --schedule-type=pgbackrest  --schedule-opts-”a b c”
5. Crunchy-scheduler included in the operator deployment.yaml
6. Pgo delete cluster mycluster “removes any schedules for this cluster”
7. Uses the existing Job templates for backup and backrest backup jobs
8. Uses the existing credential secrets created for the cluster

**Comment by jasonodonnell** [comment]
- [X] Added schedule service to API
  - [X] Added commands
    - [X] `create`
    - [X] `delete`
    - [X] `show`
  - [X] Create schedules on selectors
    - [X] pgBackRest
    - [ ] pgBaseBackup
      - [X] Discover secrets
      - [ ] Create backup PVC
      - [ ] Create job
  - [X] Delete schedules on selectors
  - [X] Show schedules
  - [ ] Add Crunchy Scheduler to deployment
  - [ ] Documentation (both container suite scheduler doc and operator doc)
  - [ ] Operator scheduler examples
