### ISSUE TITLE
crunchy-pgbouncer image contains many extra binaries

### ISSUE THREAD

**Issue by alex1989hu** [CrunchyData/postgres-operator#3396]
## Overview

I checked the current content of the pgbouncer image and I found many binaries which shall be not there in production image. Probably good to keep them for development purposes but not for production.

## Use Case

We are using`crunchy-pgbouncer` image for the features provided by PgBouncer, not for scripting, building or packaging.

As of now (not a complete list) the following binaries are installed in `crunchy-pgbouncer` image:
- awk
- cmake
- cpack
- ctest
- dig
- perl
- python
- shred

## Desired Behavior

All building tools shall be removed from the production image therefore the final image size will be smaller and may reduce the attack vector.

## Environment

- Platform: `Kubernetes`
- Platform Version: `1.21.10`
- PGO Image Tag: `ubi8-5.2.0-0`
- Postgres Version: `ubi8-14.5-1`
- Storage: `N/A`
- Number of Postgres clusters: `N/A`

## Additional Information

N/A

**Comment by tjmoore4** [comment]
@alex1989hu Thanks for the suggestion. We agree it's best to shrink our images as much as possible.
I've added a story to our backlog to further investigate this issue.

One question for you. In making this list, did you follow any formal guidance or use any tooling to determine the binaries in your list?

**Comment by alex1989hu** [comment]
@tjmoore4  thank you for your response. I wish I could tell any scanner application. It was just quick manual sanity test.

**Comment by dsessler7** [comment]
A number of unneeded binaries were removed in the latest release of our `crunchy-pgbouncer` image, so we are closing this issue.
