### ISSUE TITLE
Support timescale db 2.7

### ISSUE THREAD

**Issue by hanzala1234** [CrunchyData/postgres-operator#3398]
We need to install timescale db version 2.6. we need to upgrade it to 2.7. in documentation, I find that latest version of pgo supports 2.6.0 only
https://access.crunchydata.com/documentation/postgres-operator/5.1.0/references/components/

is there a way to install 2.7.0 version or any eta when it can have support for that?

**Comment by tjmoore4** [comment]
@hanzala1234 @bradenwright timescale 2.7.2 is included in our latest image releases for versions 5.2.0 and 5.1.3, as shown below:
```
$ podman run registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-1 rpm -qa | grep timescale
timescaledb_14-2.7.2-0Crunchy.el8.x86_64
```
Hope this helps!

**Comment by bradenwright** [comment]
Ok cool, we'll try to use that image and see how it goes, thanks for the info!

**Comment by hanzala1234** [comment]
@tjmoore4  I updated image and it seems to install updated version but its not able to load. its giving me this error

```
ERROR: could not access file "$libdir/timescaledb-2.6.1": No such file or directory
```

when I try to update extension, it's in read-only mode. is there any guide for upgrade

**Comment by hanzala1234** [comment]
while trying to update extension as mentioned in [here](https://docs.timescale.com/timescaledb/latest/how-to-guides/troubleshoot-timescaledb/#error-could-not-access-file-quot-timescaledb-lt-version-gt-quot-no-such-file-or-directory)  with query
```ALTER EXTENSION timescaledb UPDATE;```
I get this error
`ERROR:  cannot execute ALTER EXTENSION in a read-only transaction`

it seems like as soon it could find loaded extension file, it goes in read-only mode. can we have some assistance here? or we should open new github issue

**Comment by tjmoore4** [comment]
@hanzala1234 Going from PGO 5.1.2 to 5.2.0 worked as expected in my local testing (making sure to update to the appropriate Crunchy Data Postgres images). After upgrading, I did followed the provided hint:
```
ERROR:  extension "timescaledb" cannot be updated after the old version has already been loaded
HINT:  Start a new session and execute ALTER EXTENSION as the first command. Make sure to pass the "-X" flag to psql.
```
Hopefully that helps.
