### ISSUE TITLE
OpenShift operator upgrade from 5.0.4 onwards is unavailable

### ISSUE THREAD

**Issue by arizon-dread** [CrunchyData/postgres-operator#3401]
Please ensure you do the following when reporting a bug:

- [X] Provide a concise description of what the bug is.
- [X] Provide information about your environment.
- [X] Provide clear steps to reproduce the bug.
- [ ] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [x] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

OpenShift Operator channel v5 displays 5.2.0 as the latest version of postgres crunchydata certified operator, but after upgrading to 5.0.4, the interface says "Up-to-date" and no more upgrades are available. 

If I create a new namespace (openshift project) I can install the latest 5.2.0 version there w/o any issues.

I am not sure if this is related to operator handling in OpenShift or if it's the CrunchyData operator that is to "blame" for the problem of upgrading. Please direct me to RedHat if you believe the problem is with OpenShift and not CrunchyData

## Environment

Please provide the following details:

- Platform: `OpenShift`
- Platform Version:  `4.10.16`
- PGO Image Tag: `ubi8-5.0.4-0`
- Postgres Version: `14.2`
- Storage: postgres: `thin(vsphere)`, pgbackrest: `nfs`

### REPRO

Provide steps to get to the error condition:

1. Upgrade from 5.0.3 to 5.0.4 on openshift
1. Try to continuing consecutively upgrading to 5.2.0 (latest)

### EXPECTED

1. Upgrades are consecutively or in jumps, available from the openshift console to upgrade the operator and underlying cluster up until the latest version.

### ACTUAL

1. After 5.0.4, no more upgrades are available for installed operator. New operators can be installed with the latest version.

## Logs

Please let me know what logs I need to provide.

## Additional Information

I have tried editing the subscription, setting the startingCSV to 5.2.0 
[openshift installing a specific version](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/operators/administrator-tasks#olm-installing-specific-version-cli_olm-adding-operators-to-a-cluster) to no avail.
I have also tried manually creating an installPlan with 5.2.0 but it's not picked up by the operator.
When installing the new 5.2.0 (in another namespace) it says that it's replacing 5.1.3:

NAME                               DISPLAY                                         VERSION   REPLACES                    PHASE
postgresoperator.v5.2.0   Crunchy Postgres for Kubernetes   5.2.0     postgresoperator.v5.1.3   Succeeded

**Comment by tjmoore4** [comment]
@arizon-dread our OLM bundles should be properly configured to upgrade as you described. We (Crunchy Data) don't have the ability to modify existing bundles in the Red Hat repositories ourselves once they are merged, so resolving this directly would likely require Red Hat's assistance.

That said, OLM should not delete our CRD when uninstalling the Operator, so you should (theoretically, I haven't tested your scenario) be able to uninstall 5.0.4 and then reinstall 5.2.0 in the same namespace/project to upgrade any existing PostgresClusters to 5.2.0. Running a test beforehand is of course recommended.

**Comment by arizon-dread** [comment]
Thanks for this.
We upgraded the postgres version and then uninstalled + reinstalled the operator. 
Barely noticed any downtime. 
Will proceed in production when we have the opportunity.
