### ISSUE TITLE
Expose features of pgBackRest through operator

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#341]
pgBackRest has a lot of features and these are not available through operator. (Especially incremental/differential/compressed/encrypted backups).

Please provide a way to perform advanced configuration of backups for pgbackRest and pg_basebackup.

**Comment by jmccormick2001** [comment]
this one is done for pgbackrest using command line options flags, there is an issue
on the container suite to add an options environment variable to the crunchy-backup 
container which when implemented will allow me to expose that on the command line.

**Comment by jmccormick2001** [comment]
https://github.com/CrunchyData/crunchy-containers/issues/759

**Comment by jmccormick2001** [comment]
after 2.2.0 lands we will be able to implement this one.   soon.

**Comment by jmccormick2001** [comment]
added -backup-opts to 'pgo backup ' command, now it handles the both the cases of pgbackrest and pgbasebackup, in that you can pass command  flags for either backup type via this command flag (--backup-opts).  The command flags feature for crunchy-backup is implemented starting with 2.2.0 of crunchy containers.
