### ISSUE TITLE
hippo-backup pod with error status

### ISSUE THREAD

**Issue by willzhang** [CrunchyData/postgres-operator#3414]
Please ensure you do the following when reporting a bug:

- [ ] Provide a concise description of what the bug is.
- [ ] Provide information about your environment.
- [ ] Provide clear steps to reproduce the bug.
- [ ] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [ ] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

hippo-backup pod with error status

## Environment

Please provide the following details:

- Platform: (`Kubernetes`)
- Platform Version: (e.g. `1.24.1`, `4.7.7`)
- PGO Image Tag: (e.g. `ubi8-5.2.0-0`)
- Postgres Version (e.g. `14`)
- Storage: (e.g. `openebs-hostpath`)

### REPRO

Provide steps to get to the error condition:

```
kubectl apply -k manifests/postgres-operator-examples/kustomize/install/namespace
kubectl apply --server-side -k manifests/postgres-operator-examples/kustomize/install/default
kubectl apply -k manifests/postgres-operator-examples/kustomize/postgres"
```

### EXPECTED
all pods in running status or Completed status.

### ACTUAL

1. Describe what actually happens

there have one pod in Error status.

## Logs
```
root@node1:~# kubectl -n postgres-operator get pods 
NAME                           READY   STATUS      RESTARTS   AGE
hippo-backup-7bmh-g4jgx        0/1     Error       0          3h38m
hippo-backup-7bmh-gkwd9        0/1     Completed   0          3h38m
hippo-instance1-vlpv-0         4/4     Running     0          3h40m
hippo-repo-host-0              2/2     Running     0          3h40m
pgo-848fbd558f-7j2cx           1/1     Running     0          3h40m
pgo-upgrade-6b4b685577-dmblw   1/1     Running     0          3h40m
```

the pods logs

```
root@node1:~# kubectl -n postgres-operator logs -f hippo-backup-7bmh-g4jgx
time="2022-10-12T05:05:33Z" level=info msg="crunchy-pgbackrest starts"
time="2022-10-12T05:05:33Z" level=info msg="debug flag set to false"
time="2022-10-12T05:05:33Z" level=info msg="backrest backup command requested"
time="2022-10-12T05:05:33Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --repo=1]"
time="2022-10-12T05:05:33Z" level=info msg="output=[]"
time="2022-10-12T05:05:33Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\nWARN: unable to check pg1: [LockAcquireError] raised from remote-0 tls protocol on 'hippo-instance1-vlpv-0.hippo-pods.postgres-operator.svc.cluster.local.': unable to acquire lock on file '/tmp/pgbackrest/db-backup.lock': Resource temporarily unavailable\n      HINT: is another pgBackRest process running?\nERROR: [056]: unable to find primary cluster - cannot proceed\n       HINT: are all available clusters in recovery?\n]"
time="2022-10-12T05:05:33Z" level=fatal msg="command terminated with exit code 56"
```

## Additional Information

Please provide any additional information that may be helpful.

**Comment by tony-landreth** [comment]
Hi @willzhang ! Pods can become unhealthy, depending on the environment they're running in. When a job fails, it's important to note whether a reattempt succeeds. Notice that `hippo-backup-7bmh-gkwd9` completed successfully. That's the important thing. I hope this helps.

**Comment by benjaminjb** [comment]
As this question has been answered and haven't heard recently, I'll close this ticket, but if you are still experiencing this problem, please reopen this issue.
