### ISSUE TITLE
Lack of community support

### ISSUE THREAD

**Issue by maaft** [CrunchyData/postgres-operator#3419]
I started looking into PGO a few weeks ago and noticed that it is very hard to get any information if something does not work as expected with PGO.

Why is there no community forum / place for discussions? I think that adoption of PGO would greatly benefit from that.

Currently, without any ability to share opinions or discuss configuration options, running PGO does not feel very good from a developer's point of view:
- lack of github issue management / too many unanswered and open issues
- no direct feedback / communication channels (with community)
- no idea what my cluster actually runs (no link of tags/releases <-> docker containers)
- no ability to debug my running release in case something fails
- no clear documentation on how to build new releases/containers myself

Happy to hear if above points do not hold true.

It feels a little bit like that this is done on purpose. Claiming to be 100% open-source while keeping key documentation or pieces of PGO "enterprise-only". It feels like being forced into becoming a paying customer because otherwise you would drive your car (pgo) blindfolded.

For me personally, the current state of "open-sourceness" of PGO implies way to much reliance on the existence of crunchydata itself. When the company goes down, I'd have a hard time to keep my PGO deployment maintained.

**Comment by andrewlecuyer** [comment]
Thank you for your feedback - we're always looking at ways to improve our ability to effectively communicate with the PGO community, and your feedback in this area is much appreciated.

We do indeed have a community forum for PGO discussions, which is the [PostgreSQL Operator Community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).  This is referenced in the [Support section](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) of the PGO documentation.  We encourage community participation here discussing various questions, feature requests, opinions, configurations, etc. related to PGO, and would love to have you join the conversation.  And please note that the PGO Development Team does also actively participate in the community mailing list as well.

As for issue resolution and general support, please note that as is the case with many FOSS projects, we have a small team dedicated to PGO, that is working hard to get out new features, changes, fixes, etc.  Therefore, while bugs/defects raised are typically addressed in a timely manner, various other questions and requests for support in our public forums are addressed as time permits.  And of course, as a FOSS project we welcome PR submissions, as well as community participation in the discussion of various issues, questions, etc.!

> no clear documentation on how to build new releases/containers myself

We do realize this is a gap in our PGO v5 documentation (we do have a [section for building](https://access.crunchydata.com/documentation/postgres-operator/v4/contributing/developer-setup/) in the PGO v4 documentation), and plan to add a section to clarify steps for building PGO.  Additionally, we do have plans to move our Major PG Upgrades controller and documentation to this repository, which means it will soon be possible to fully build and contribute to all of PGO.

Thanks again, and we look forward to hearing from you in our [Community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join)!

**Comment by pere3** [comment]
I would like to add some of my thought about community support as well.

As a community adopter of a superior product i was having a hard time trying to get my questions answered here on github issues and google group mailing list.
Many things are straight up broken for community users (you can't build yourself crunchy-containers without modifications if you are not a paying customer).

There is also a feeling that robust community support ended with jkatz left company or something.

I'm currently have questions unanswered (https://github.com/CrunchyData/postgres-operator/issues/3379#issuecomment-1262263599, https://groups.google.com/a/crunchydata.com/g/postgres-operator/c/k-irqaUNepU?hl=en), PRs not reviewed (or not even considered, https://github.com/CrunchyData/crunchy-containers/pull/1475).

That's kinda sad.

**Comment by bbroniewski** [comment]
Hi all, I agree with the points above. How I may know which commit correspond to which version from yours v5 docs? Up to version 4.7.7 there are releases, so how now we may understand which commit refer to which version?
