### ISSUE TITLE
Allow ovverrider for postgresql.conf.sample pre-init

### ISSUE THREAD

**Issue by rhrytskiv** [CrunchyData/postgres-operator#3421]
- [x] Provide a concise description of your feature request.
- [x] Describe your use case. Detail the problem you are trying to solve.
- [x] Describe how you envision that the feature would work.
- [x] Provide general information about your current PGO environment.

## Overview

Hi, our k8s provider has this issue where we have to have huge_pages set to off before the db init otherwise it's just failing.
I couldn't find any means to do it via you docs so I mad my own docker image based on yours where I just replace postgres.conf.sample that you have. It'be best to avoid this approach and just set it via config.

p.s. dynamic postgres config settings does not solve this as they don't affect init db.

## Environment

- Platform: (`Kubernetes`)
- Platform Version: (`latest`)
- PGO Image Tag: (`ubi8-5.2.0-0`)
- Postgres Version (`14`)
- Storage: (`Mayastor`)
- Number of Postgres clusters: (`1`)

**Comment by dsessler7** [comment]
Hello @rhrytskiv, 

This issue has been resolved in our latest releases: 5.4.0, 5.3.2, 5.2.3, and 5.1.6.
