### ISSUE TITLE
Include replicas service domain in the certificate

### ISSUE THREAD

**Issue by Agalin** [CrunchyData/postgres-operator#3446]
## Overview

When PGO generates a certificate for the cluster that cert only includes the primary service in SANs. It should also include replicas service.

## Use Case

When you connect to the cluster through PGBouncer it performs strict cert validation by default (and that't the preferred approach). It fails for replicas because of the missing SAN.

## Desired Behavior

Automatically generated cert should include replicas service in SAN list just like it does with the primary service. No changes in user-facing configuration needed.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: (`Kubernetes`)
- Platform Version: (N/a)
- PGO Image Tag: (e.g. `5.1.1`)
- Postgres Version (N/A)
- Storage: (N/A)

## Additional Information

Of course it can be worked around by lowering pgbouncer TLS expectations (would like to avoid that) or replacing certs by ones generated by cert manager but support for it in the "default" setup would make adopting replica reads much easier.

**Comment by szelenka** [comment]
Seems to be hard coded.

@cbandy was there a conscious decision to only include the primary DNS names in the cert, or would it be "okay" to include the replicaService as well?

AFAIK, it'd involve duplicating the logic here:
https://github.com/CrunchyData/postgres-operator/blob/master/internal/controller/postgrescluster/cluster.go#L180-L192

For the replica Service here:
https://github.com/CrunchyData/postgres-operator/blob/master/internal/controller/postgrescluster/cluster.go#L239-L248

Then passing both services here, and merge the two lists of strings?
https://github.com/CrunchyData/postgres-operator/blob/master/internal/controller/postgrescluster/pki.go#L136

This seems related to #3025 , without the replica in the Cert, connections to the replicaService will fail Cert validation

**Comment by benjaminjb** [comment]
With the merging of the above PR, this issue has now been addressed. Thanks for pointing this out, having this addressed is definite improvement!
