### ISSUE TITLE
evaluate backrest repo pvc shared by all cluster members

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/postgres-operator#345]
currently each pg cluster compoent (primary and replicas) get their own backrest repo pvc, good for HA but bad for retaining access to previous backups on the primary, evaluate how to offer this as an option.

**Comment by pmereddy1** [comment]
Is this feature going to be in 3.4 release ?

**Comment by cdave-git** [comment]
I think it goes back to ability to use PVC of dead primary. i feel there should only be one pgbackrest repo which should get attached to current primary.

**Comment by jmccormick2001** [comment]
this one will not make it into 3.4 I think given the timeline and where I'm at., but probably 3.5.

**Comment by jmccormick2001** [comment]
this feature will first be made available in the 3.5.0-rc2 build.
