### ISSUE TITLE
CrunchyData/ postgres-operator installation in Digital ocean Kubernetes cluster.

### ISSUE THREAD

**Issue by SavanTripathi** [CrunchyData/postgres-operator#3468]
I am new to Kubernetes and I want to use Postgres-operator crunchy data in my k8s cluster. As per the installation guide i am installing it with kubectl commands.
After the first command i.e of namespace creation, it is getting successfully executed and the namespace is created.
kubectl apply -k kustomize/install/namespace

Now i want to install PGO using below command as per the guidance given in installation manual:
kubectl apply --server-side -k kustomize/install/default

I am facing error as 
error: containers path is not of type []interface{} but map[string]interface {}

 i have fork repository from GitHub and executing command as per the given manual like:  
cd to forked repository and then execute the command of kubectl.

Please guide me here. or if there are any specific step-by-step installation links or references of Postgresql in Kubernetes then suggest the same.

Thank you

**Comment by cbandy** [comment]
What version of `kubectl` do you have? The following command will show: `kubectl version -o yaml`

**Comment by SavanTripathi** [comment]
clientVersion:
  buildDate: "2020-12-08T17:59:43Z"
  compiler: gc
  gitCommit: af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38
  gitTreeState: clean
  gitVersion: v1.20.0
  goVersion: go1.15.5
  major: "1"
  minor: "20"
  platform: windows/amd64
serverVersion:
  buildDate: "2022-08-17T18:47:37Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: clean
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: linux/amd64

**Comment by cbandy** [comment]
That version of `kubectl` contains Kustomize v2.0.3 which has this issue: https://issue.k8s.io/107751

Kubernetes also [recommends](https://kubernetes.io/releases/version-skew-policy/#kubectl) that `kubectl` be within one minor version of the server. Your server is v1.24.4, so [upgrading `kubectl`](https://kubernetes.io/docs/tasks/tools/) to v1.23 or greater sort everything out.

**Comment by SavanTripathi** [comment]
Thank you cbandy for your reference. the issue is solved. as I am able to run the operator and PostgreSQL cluster. Now I am again paused at accessing the database from outside of the network using pgadmin. but I am not able to do using cluster IP and Droplet IP. I have all the credentials like the DB name, username, and password, of the PostgreSQL database. How to access it from the global public network?
