### ISSUE TITLE
unable to install operator on kubernetes v1.25 - v1beta1.Cronjob is deprecated

### ISSUE THREAD

**Issue by sorinpepelea** [CrunchyData/postgres-operator#3476]
The operator still uses old kubernetes apis, like [v1beta1.Cronjob](https://github.com/CrunchyData/postgres-operator/blob/39a8e1f9814f56cb777ffd66cd62658bb08f1bfd/internal/controller/postgrescluster/pgbackrest.go#L121), which is deprecated from v1.21 and removed in v1.25: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
This was already mentioned before, but issues were closed without any solve. @jelmer made a fix on his fork project branch kubernetes-1.25 .. but all in vain.

**Comment by alex1989hu** [comment]
hey @sorinpepelea, already fixed but not yet released https://github.com/CrunchyData/postgres-operator/issues/3365

**Comment by blaisep** [comment]
me too...

**Comment by benjaminjb** [comment]
5.3.0 has been released this week and is compatible with k8s v1.25!
