### ISSUE TITLE
Question about using the official TimescaleDB-HA image and multiple Volumes

### ISSUE THREAD

**Issue by adminnz** [CrunchyData/postgres-operator#3482]
I'm looking at methods and options for running TimescaleDB in our Azure Kubernetes cluster.
The CrunchyData operator looks to be good for Postgres, but I have two questions:

1.  All the questions I've seen about including the timescaledb extension are about the apache licensed one, or by running a custom image that installs (again the apache licensed extension). Is it possible to get the PGO to just use the official timescaledb-ha image?
(Because we require the use of the community edition features.)

2. Our data volumes are very large (multiple TB) and as such we are wanting to utilize timescaledb's ability to map hypertable chunks across tablespaces mapped to different disks. Is it possible to specify multiple volumes of different storageClasses to be mounted to the instances?

**Comment by dsessler7** [comment]
Support for tablespaces is included in the 5.4.0 release.

**Comment by esatterwhite** [comment]
I know this issue is a bit old, but aside from tablespaces, Is there a way with the operator to attach multiple volumes to a postgres node?

I want to separate the wal from other pgdata on to separate volumes for example
