### ISSUE TITLE
Multi Cluster Streaming Standby basic https auth instead of tls

### ISSUE THREAD

**Issue by hrytskivr** [CrunchyData/postgres-operator#3489]
Going trough your [Disaster Recovery Turorial](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/) it seems like it's impossible to have this solution automated because it requires tls certificate management. Why can't standby cluster use basic auth instead of tls certificates?
It's also weird that in [Multi Cluster Tutorial](https://crunchydata.github.io/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/) are cli options like _--password-replication_.

So is it possible to avoid TLS auth and use basic creds via https?

**Comment by hrytskivr** [comment]
I've managed to do this with KUBED config syncer and cert-manager. Worth adding this info to docs?

**Comment by daanbosch** [comment]
I would be interested in this documentation @hrytskivr , would you be willing to share it?
