### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by rhrytskiv** [CrunchyData/postgres-operator#3515]
Hi, could you add a changelog to unedrstand if there are any breaking or otherwise "interesting" changes between versions?

**Comment by prlaurence** [comment]
Appreciate the suggestion. We will give some thought to how we can improve the documentation here. 

In the meantime, you can find release notes that may be a helpful starting point [here](https://access.crunchydata.com/documentation/postgres-operator/5.3.0/releases/5.3.0/)
