### ISSUE TITLE
Investigate alerting capability in postgres-operator

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#352]
Currently operator does not have any metrics or alerting capability. 
It will be very useful for operator to include metrics similar to crunchy-collect container and enable them by default.

Things like auto failover events, backups, health checks, cluster creation events, errors applying policies to new clusters, mismatch between CRDs and corresponding objects in kubernetes, etc. could be exposed by operator.

Alerts can be configured in prometheus and dashboard could be built in grafana using these metrics

**Comment by jmccormick2001** [comment]
will move to clubhouse, schedule for development.

**Comment by TFK1410** [comment]
Where does this idea stand now?

I was thinking about a few ideas to get some monitoring and especially alerting with PGO.
To the list of events already mentioned in the issue I would add monitoring of WAL archiving.

For my current setup I've created a piece of Python that essentially pulls the information of every pgcluster that exists. Based on previously encountered patterns I mark the deployments that have some problems that require a closer look.

I'm thinking of expanding on that tool but it would be restrictive and presumably only work on my clusters. 
Are there any ideas on how to make a proper solution that could be a part of the newer versions of the operator?
