### ISSUE TITLE
Adding custom labels to the pgo pod

### ISSUE THREAD

**Issue by David-Angel** [CrunchyData/postgres-operator#3524]
## Overview

We need the ability to add labels to the crunchydata postgres operator pod.
We have the ability to add custom labels and annotations to the postgres pods using the PostgresCluster but not to the operator pod itself.

This is needed to disable istio but it only affects the postgres pods
`
kind: PostgresCluster
...
spec:
...
  instances:
    metadata:
      labels:
        **sidecar.istio.io/inject: "false"**
`

**RESULTS**

`kubectl get pod postgres-ha-cmo1-79vq-0 --show-labels
LABELS       
controller-revision-hash=postgres-ha-cmo1-79vq-77fb4b9464,postgres-operator.crunchydata.com/cluster=postgres-ha,postgres-operator.crunchydata.com/data=postgres,postgres-operator.crunchydata.com/instance-set=cmo1,postgres-operator.crunchydata.com/instance=postgres-ha-cmo1-79vq,postgres-operator.crunchydata.com/patroni=postgres-ha-ha,postgres-operator.crunchydata.com/role=replica,**sidecar.istio.io/inject=false**,statefulset.kubernetes.io/pod-name=postgres-ha-cmo1-79vq-0
`

`k get pods -l='postgres-operator.crunchydata.com/control-plane=pgo' --show-labels
LABELS
pod-template-hash=69d6bcf65d,postgres-operator.crunchydata.com/control-plane=pgo
`

Notice there is no way to add a custom label to the control-plane pgo pod.
istio can not be disabled without this ability.

## Use Case

We need the ability to add custom labels to the crunchydata postgres operator pod to disable istio along with future customizations we may need.

## Desired Behavior

Crunchydata should provide a simple way of adding labels to the pgo pod.
We have worked around this by altering these two files.
https://github.com/CrunchyData/postgres-operator-examples/pull/178

And adding this to our helm release.

      # labels for the postgres operator "pgo" pod itself.
      customLabels:
        sidecar.istio.io/inject: "false"

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: Kubernetes
- PGO Image Tag: LATEST
- Postgres Version: 14

**Comment by benjaminjb** [comment]
What method are you using to install the PGO operator? I would look into that to add labels to the pgo (and pgo-upgrade) pod.

**Comment by David-Angel** [comment]
After changing the installer templates we are using a HelmRelease yaml file.

It would be nice if you could merge this pull request to your "postgres-operator-examples" repostiory.
    https://github.com/CrunchyData/postgres-operator-examples/pull/178

Or giving an easier way to modify them through the postgrescluster.
Crunchydata makes it very nice and easy to modify labels and attributes for everything else.

Or give us a nice way to do it.  :)

SAMPLE helm release with the relevant changes made after altering the installer templates.
`
kind: HelmRelease
metadata:
spec:
  values:
      # labels for the postgres operator "pgo" pod itself.
      customLabels:
        sidecar.istio.io/inject: "false"
`

**Comment by benjaminjb** [comment]
Ha, fair enough! Since you've solved this issue & opened a PR in `postgres-operator-examples`, I'll close this one here and continue the conversation over there. Cheers!

**Comment by David-Angel** [comment]
Sounds good, I opened this one to give full details about the other one.
It's my first PR and I wasn't sure if anyone is looking at it or how to explain why it was added.
