### ISSUE TITLE
'Make pull' wrong pgo-lspvc version inserted.

### ISSUE THREAD

**Issue by andrewnelsonnutanix** [CrunchyData/postgres-operator#353]
When running 'make pull' for prebuilt binaries:
docker pull crunchydata/pgo-lspvc:centos7-3.2
Error response from daemon: manifest for crunchydata/pgo-lspvc:centos7-3.2 not found
make: *** [pull] Error 1

From https://hub.docker.com/r/crunchydata/pgo-lspvc/tags/
correct tag looks like 'centos7-3.2.0'

**Comment by jmccormick2001** [comment]
thanks, fixed the docs to reflect 3.2.0
