### ISSUE TITLE
Can't restore a cluster from S3 due to CA S3 certificate using MinIO

### ISSUE THREAD

**Issue by mattups** [CrunchyData/postgres-operator#3534]
## Questions
Hey all, getting a little bit desperate here.

So what I'm trying to do, is performing a restore of a cluster, on a new cluster, from S3 backups stored on MinIO.
Backups are working properly:
```
        full backup: 20230117-010006F
            timestamp start/stop: 2023-01-17 02:00:06 +0100 CET / 2023-01-17 02:05:37 +0100 CET
            wal start/stop: 0000068E0000073400000008 / 0000068E000007340000000D
            database size: 526.7MiB, backup size: 526.7MiB
            repository size: 125.4MiB, repository backup size: 125.4MiB
            backup reference list:

        incr backup: 20230117-010006F_20230117-060006I
            timestamp start/stop: 2023-01-17 07:00:06 +0100 CET / 2023-01-17 07:01:07 +0100 CET
            wal start/stop: 0000068F00000734000000F4 / 0000068F00000734000000F5
            database size: 527.9MiB, backup size: 418.1MiB
            repository size: 129.1MiB, repository backup size: 121.1MiB
            backup reference list: 20230117-010006F

        incr backup: 20230117-010006F_20230117-120005I
            timestamp start/stop: 2023-01-17 13:00:05 +0100 CET / 2023-01-17 13:00:48 +0100 CET
            wal start/stop: 00000690000007360000000B / 00000690000007360000000B
            database size: 528.5MiB, backup size: 220.6MiB
            repository size: 129.1MiB, repository backup size: 32.4MiB
            backup reference list: 20230117-010006F, 20230117-010006F_20230117-060006I
```

And in fact, I can take them out of on-prem MinIO without issues.

What I'm trying to do, is the following:
```
pgo create cluster new-cluster \
    --restore-from=old-cluster\
    --restore-opts="--repo-type=s3" \
    --pgbackrest-repo-path=/backrestrepo \
    --pgbackrest-s3-bucket=pgsql \
    --pgbackrest-s3-endpoint=on-prem.minio.endpoint \
    --pgbackrest-s3-key=xxx\
    --pgbackrest-s3-key-secret=xxx\
    --pgbackrest-s3-region=us-west-3 \
    --pgbackrest-s3-ca-secret=k8s-secret-containing-ca-cert \
    --pgbackrest-s3-uri-style=path \
    --pgbackrest-s3-verify-tls=false
```

What happens at the time of bootstrap is the following:
```
ERROR: [095]: unable to load info file '/backrestrepo/old-cluster-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/old-cluster-backrest-shared-repo/backup/db/backup.info.copy':
       CryptoError: raised from remote-0 protocol on 'old-cluster-backrest-shared-repo': unable to verify certificate presented by 'on-prem.minio.endpoint': [20] unable to get local issuer certificate
       HINT: is or was the repo encrypted?
       CryptoError: raised from remote-0 protocol on 'old-cluster-backrest-shared-repo': unable to verify certificate presented by 'on-prem': [20] unable to get local issuer certificate
       HINT: is or was the repo encrypted?
       HINT: backup.info cannot be opened and is required to perform a backup.
       HINT: has a stanza-create been performed?
Fri Jan 20 10:15:05 UTC 2023 ERROR: pgBackRest primary Creation: pgBackRest restore failed when creating primary
2023-01-20 10:15:05,520 INFO: removing initialize key after failed attempt to bootstrap the cluster
2023-01-20 10:15:05,572 INFO: renaming data directory to /pgdata/new-cluster_2023-01-20-10-15-05
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1346, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1242, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1235, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```

So, in the `k8s-secret-containing-ca-cert` I have stored the CA that also the usual backrestrepo uses, but somehow seems still failing.
The certificate of my Minio deployment is issued via Letsencrypt. Strange thing is that I'm totally able to push backups there, but apparently I have this error only on restores.

I found #2864 to be a similar case, but with actual S3 certificates. I would normally upgrade the operator but at this time I actually can't. Any idea here on the matter? 
I;m really struggling to understand how is possibile that `pgBackRest` is able to perform and store backups with the same MinIO, but having issues with CA when trying to perform a restore.
 

### Environment
- Platform: (`Kubernetes RKE v1.20 on Rancher 2.5`.)
- Platform Version: (`4.5.1` both `pgo` client and `pgo-apiserver`)
- PGO Image Tag: (`crunchydata/pgo-event:centos7-4.5.1`)
- Postgres Version (`12`)
- Storage: (`nfs`)

**Comment by andrewlecuyer** [comment]
Thanks for reaching out!

Since you are utilizing a version of Crunchy Postgres for Kubernetes that is no longer maintained in the [Crunchy Developer Portal](https://www.crunchydata.com/developers) (there have been many changes/fixes/enhancements/etc. in PGO around pgBackRest w/S3 since v4.5.1 was released in November 2020), please reach out to info@crunchydata.com for further assistance and/or to describe your use case further.

Additionally, if you do continue to experience issues with restores once you are able to upgrade to one of our [currently supported versions of Crunchy Postgres for Kubernetes](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator-5x), please feel free to submit a new issue.  And for reference, our v4 to v5 upgrade guides can be found here:

https://access.crunchydata.com/documentation/postgres-operator/latest/upgrade/v4tov5/

**Comment by mattups** [comment]
Thanks @andrewlecuyer. In the end I managed to solve, so here's my solution.

What I did was updating the provided ca cert in `pgo` configurations secrets for the key `aws-s3-ca.crt` (which is also propagated at cluster creation time to repositories pods). 

I downloaded the certificate from (here)[http://x1.i.lencr.org/], in a `.der` format. Then I used `openssl` to check it and converting it into a `.pem`.
```shell
openssl x509 -inform der -in ISRG\ Root\ X1.der -out cert.pem
```
The being done, I just copy the content of that into the `aws-s3-ca.crt` key for both the operator and the repositories configurations of the cluster I already had. I was also having a dedicated secret `k8s-secret-containing-ca-cert` for this ca cert just for my convenience.

Once done creating a cluster restore via `pgo` cli worked perfectly:
```shell
pgo create cluster new-cluster \
    --restore-from=old-cluster\
    --restore-opts="--repo-type=s3" \
    --pgbackrest-repo-path=/backrestrepo \
    --pgbackrest-s3-bucket=pgsql \
    --pgbackrest-s3-endpoint=on-prem.minio.endpoint \
    --pgbackrest-s3-key=xxx\
    --pgbackrest-s3-key-secret=xxx\
    --pgbackrest-s3-region=us-west-3 \
    --pgbackrest-s3-ca-secret=k8s-secret-containing-ca-cert \
    --pgbackrest-s3-uri-style=path \
    --pgbackrest-s3-verify-tls=false
```

Hope this may be helpful. And it was a very similar problem to #2128

**Comment by 64J0** [comment]
Had this problem today using a local container based on Postgres official image. 

The command worked after setting

```toml
repo1-s3-verify-tls=n
```

to the `pgbackrest.conf`.

The error I was getting was:

```shell
$ pgbackrest.real info --stanza=$STANZA
stanza: ...
    status: error (other)
            [CryptoError] unable to verify certificate presented by 'something.amazonaws.com:443 (num_ip.num_ip.num_ip.num_ip)': [20] unable to get local issuer certificate
                [CryptoError] on 12 retries from 733-60312ms: unable to verify certificate presented by 'something.amazonaws.com:443 (num_ip.num_ip.num_ip.num_ip)': [20] unable to get local issuer certificate
    cipher: none
```

Notice that the `num_ip.num_ip.num_ip.num_ip` part was just a regular IP v4.

- pgBackRest version: 2.54.2
