### ISSUE TITLE
Port-forward dropped after disconnection

### ISSUE THREAD

**Issue by dvarrazzo** [CrunchyData/postgres-operator#3547]
## Overview

When we forward a port to a PGO cluster, we can successfully connect to it. However, as soon as the connection is closed, the port forwarding tunnel is closed.

In certain scripts we wrote, we try to reconnect if we detect that the port-forwarding process terminated. However, the method has a race condition and often the process is closed after the check but before a new connection.

I have found [similar reports](https://stackoverflow.com/questions/72754941/port-forward-to-postgres-kubernetes-pod-fails-with-connection-reset-when-executi) in the wild.

Note: we are migrating from KubeDB databases, and that implementation doesn't have the same problem... :eyes: 

## Environment

Please provide the following details:

- Platform: tested on AKS Kubernetes 1.23.8, Kind 1.25.3
- PGO Image Tag: ubi8-5.0.5-0, ubi8-5.3.0-0
- Postgres Version: 14

## Steps to Reproduce

Assuming a database cluster called `keycloak-postgresql-14` with an user called `devel`:

```
$ kubectl port-forward \
    $(kubectl get pod -o name \
      -l postgres-operator.crunchydata.com/cluster=keycloak-postgresql-14,postgres-operator.crunchydata.com/role=master) \
    15432:5432 &
[1] 2401811
Forwarding from 127.0.0.1:15432 -> 5432
Forwarding from [::1]:15432 -> 5432

$ export PGPASSWORD=$(kubectl get secret keycloak-postgresql-14-pguser-devel -o template="{{.data.password}}")

$ psql -c "select 1" "postgresql://devel:@localhost:15432/keycloak" 
Handling connection for 15432
┌──────────┐
│ ?column? │
├──────────┤
│        1 │
└──────────┘
(1 row)

E0125 14:30:25.220731 2401811 portforward.go:406] an error occurred forwarding 15432 -> 5432: error forwarding port 5432 to pod f62bfb8d75e61571cd776ce8eedfe371583e6512845c8fef0c625764309e2c56, uid : failed to execute portforward in network namespace "/var/run/netns/cni-47a3360f-fdef-fd64-78d9-a68f483256b6": read tcp4 127.0.0.1:32828->127.0.0.1:5432: read: connection reset by peer
E0125 14:30:25.221369 2401811 portforward.go:234] lost connection to pod

[1]+  Done

$ psql -c "select 1" "postgresql://devel:@localhost:15432/keycloak" 
psql: error: connection to server at "localhost" (127.0.0.1), port 15432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
```

Trying to port-forward a service instead doesn't work:

```
$ kubectl port-forward service/keycloak-postgresql-14-ha 15432:5432 
error: cannot attach to *v1.Service: invalid service 'keycloak-postgresql-14-ha': Service is defined without a selector

$ kubectl port-forward service/keycloak-postgresql-14-primary 15432:5432 
error: cannot attach to *v1.Service: invalid service 'keycloak-postgresql-14-primary': Service is defined without a selector

$ kubectl port-forward service/keycloak-postgresql-14-pods 15432:5432 
error: Service keycloak-postgresql-14-pods does not have a service port 5432
```

Is there any workaround for the problem? Thank you very much!

**Comment by tony-landreth** [comment]
Hi there! Sorry that you're having this problem. It looks like running psql over TLS, which is the default here, might be what leads to the reset on close. You could `exec` instead of port-forwarding.
 
```
kubectl exec "${PG_CLUSTER_PRIMARY_POD}" -c database -- psql -c "<YOUR SQL HERE>"
```

Or `exec -it` to stay in psql. I hope this helps.

**Comment by dvarrazzo** [comment]
Exec'ing works no problem, but only for interactive work. Writing code to run queries in Python is not possible.

**Comment by tony-landreth** [comment]
I see. You may be interested in using a `NodePort`, described in the docs [here](https://access.crunchydata.com/documentation/postgres-operator/5.3.0/tutorial/connect-cluster/).

**Comment by dvarrazzo** [comment]
No, it doesn't seem to help (note: the cluster I've tested now has a different name from the above):

```
k port-forward service/postgres-ha 15432:31831
error: cannot attach to *v1.Service: invalid service 'postgres-ha': Service is defined without a selector
```

I tried to specify a selector for the service, but it's not accepted

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
...
spec:
  service:
    selector:
      postgres-operator.crunchydata.com/cluster: postgres
      postgres-operator.crunchydata.com/role: master
```

Is there a way to connect to a postgres cluster from outside the k8s cluster?

**Comment by tony-landreth** [comment]
PGO just configures native Kubernetes services, so [external exposure](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips) depends on the service type configured (`NodePort`, `LoadBalancer`, etc.) and from there is dependent on how the local k8s environment exposes those [services](https://kubernetes.io/docs/concepts/services-networking/service/#services-in-kubernetes) (e.g. since load balancer implementation, nodeport networking, etc. could vary between environments). So for connecting outside of your cluster, how you do that should be described by your distro docs for Kind or the AKS docs.

**Comment by dvarrazzo** [comment]
Thank you for your help. I have ended up not working actively on this, but I should in the future.

Thank you for pointing me at the service port direction: I'll play with it as soon as I have the chance/need and report back.

**Comment by chobostar** [comment]
Here is a reason:
https://github.com/kubernetes/kubectl/issues/1169#issuecomment-1165140134
>Postgres server sends an RST packet when the client(like psql) disconnecting from the server in TLS mode, because it shut down the sub-process that handling connection without reading the SSL Shutdown packet send from the client. And the new logic introduced in https://github.com/kubernetes/kubernetes/pull/103526 causes the port forward itself to be shut down when an RST packet is read from server side in the connection established via the port forward

So port-forward with enabled SSL works fine with kubectl 1.22 and below version.
