### ISSUE TITLE
How to change pg_hba.conf?

### ISSUE THREAD

**Issue by chardch** [CrunchyData/postgres-operator#3551]
I want to add a line to the `pg_hba.conf` file postgres uses so that any user can log in as long as they have password. How do I do this?

**Comment by andrewlecuyer** [comment]
@chardch please see the following for an example of how to customize the `pg_hba.conf`:

https://github.com/CrunchyData/postgres-operator/issues/2534#issuecomment-891202207

**Comment by benjaminjb** [comment]
If this is still an issue, feel free to reopen this, but I think the answer above will help you out here. (And I've added a ticket in our backlog to add this info to our docs.)
