### ISSUE TITLE
Create a new database in the same cluster with the content of specific backup of another database?

### ISSUE THREAD

**Issue by ckazimie** [CrunchyData/postgres-operator#3553]
Is is possible to create a new database in the same cluster with the content of a specific backup of another database?

**Comment by dsessler7** [comment]
Hello @ckazimie , if I understand correctly, it sounds like maybe you want to take an existing postgrescluster and use its backup as the data source for creating a new postgrescluster?  If so, you can find directions for this procedure in our docs in the "Clone a Postgres Cluster" section:

https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/

If this isn't what you would like to do, please respond with as much detail as possible.

**Comment by benjaminjb** [comment]
Hi @ckazimie, I'm going to close this for now as stale, and hope the docs Drew pointed to help, but if you want to continue this conversation, feel free to reopen.
