### ISSUE TITLE
External usage of pkg/apis/postgres-operator.crunchydata.com/v1beta1

### ISSUE THREAD

**Issue by wregen** [CrunchyData/postgres-operator#3559]
Question: How can I use pkg/apis/postgres-operator.crunchydata.com/v1beta1 in my own golang module?

I've tried "github.com/crunchydata/postgres-operator/pkg/apis/crunchydata.com/v1" but it seems to have different api.

Thank you in advance.

**Comment by tony-landreth** [comment]
Thanks for your question! In the code, you can see an [example](https://github.com/CrunchyData/postgres-operator/blob/master/internal/controller/postgrescluster/controller_test.go#L47) of how to import our code. You'll need to:
 ```go 
go get http://github.com/crunchydata/postgres-operator/pkg/apis/postgres-operator.crunchydata.com/v1beta1@master
```
Just wondering, what's your use case? We're always curious how people are using our code.

**Comment by wregen** [comment]
Thank you. It helped.

I am writing simple utility that automates backup/restore of k8s ns, PostgresCluster is one of CRs where backup is set. Currently I am using dynamic client to get/update k8s resources; with your help I'll be able to use "typed" client; the code should be clearer and I can remove lots of validations I need to do with dynamic client.
