### ISSUE TITLE
Patroni 3.x failsafe_mode support

### ISSUE THREAD

**Issue by tolleiv** [CrunchyData/postgres-operator#3563]
## Overview

Would be great to have a PGO with Patroni 3.x (currently 3.0.0) available to gain access to their recent improvements regarding dcs_failsafe_mode.

## Use Case

The dcs_failsafe_mode feature seems like a big stability win for setups with non HA-Kubernetes APIs (see https://github.com/zalando/patroni/blob/v3.0.0/docs/dcs_failsafe_mode.rst ) this would also mitigate issues like #3171 

## Desired Behavior

Would be great to have Patroni 3.x shipped with a regular release to allow for some configuration like this through the CRD:

```
spec:
  patroni:
    failsafe_mode: true
```

## Environment

Tell us about your environment:

- Platform: `Kubernetes`
- Platform Version: `1.24.9` / `1.25.6
- PGO Image Tag: `ubi8-5.3.0-0`
- Postgres Version `13`/ `14`
- Storage:` cinder.csi.openstack.org`
- Number of Postgres clusters: `10`

## Additional Information

Please provide any additional information that may be helpful.

**Comment by tjmoore4** [comment]
Hello @tolleiv, thank you for your use case details.
I've added an item to our development backlog for consideration for a future release.

**Comment by tony-landreth** [comment]
Hello @tolleiv, thanks again for describing your use case. We're excited to say that Patroni 3.1.0 is now available with our latest release.  I will therefore close this issue. We look forward to any feedback you have regarding this feature.
Please feel free to reach out in [Discord](https://discord.gg/a7vWKG8Ec9) to discuss further, or to provide any additional feedback, thoughts, etc.!
