### ISSUE TITLE
Pgo Client show Error: Get https://127.0.0.1:8443/version: dial tcp 127.0.0.1:8443: connect: connection refused

### ISSUE THREAD

**Issue by TauqeerAhmad104** [CrunchyData/postgres-operator#3573]
I am trying to install PGO crunchy on k8s. I have one master and 2 worker nodes on VMware esxi. I follow the official documentation https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/ to start with. Now my hippo cluster is running under namespace postgres-operator.

**What I want to do now:**  I want to make backup and also want to check how many backups are available. For that I am trying to install PGO client by following this documentation  
https://access.crunchydata.com/documentation/postgres-operator/4.4.1/quickstart/
I created self signed certificates and secrets for pgouser and tls varification to finish the installation. I am very new and struggling to understand the documentation. Now when I check `kubectl get deployments -n pgo` I see no resources and when I use `kubectl get pods -n pgo` I see one pod with error. 

```
TASK [pgo-operator : Create PGClusters CRD] ************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml"], "delta": "0:00:00.958477", "end": "2023-02-14 12:58:31.503884", "msg": "non-zero return code", "rc": 1, "start": "2023-02-14 12:58:30.545407", "stderr": "error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\"", "stderr_lines": ["error: unable to recognize \"/ansible/postgres-operator/roles/pgo-operator/files/crds/pgclusters-crd.yaml\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\""], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=21   changed=5    unreachable=0    failed=1    skipped=17   rescued=0    ignored=0
```
I follow your another discussion about version I also try the the most latest version of PGO as I am running 1.26 v of k8s. can you please tell me how can I fix this client issue and perform backups.? Why is the issue of my installation?  The most important question is do I need PGO client to perform backups or check and restore backups? Really tanksful for your support.

**Comment by prlaurence** [comment]
A few places to look that may be helpful in unblocking you:

-- Please take a look at the 'latest' pgo cli install documentation [here](https://access.crunchydata.com/documentation/postgres-operator-client/latest/).  From the link you provided, it appears you are trying to install the pgo cli for version 4.4.1 and there were some major changes from v4 to v5. 

-- Please take a look at the tutorials on [backup configuration](https://access.crunchydata.com/documentation/postgres-operator/5.3.0/tutorial/backups/ and [backup management ]((https://access.crunchydata.com/documentation/postgres-operator/5.3.0/tutorial/backup-management/) as they are likely useful in getting started. 

I appreciate your giving PGO a try. 

To extent you end up still having issues or would like to stay up to date on new releases, please consider joining the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join) and post any questions to the community there.

**Comment by andrewlecuyer** [comment]
@TauqeerAhmad104 the error you are seeing appears to be the result of trying to install an older version of Crunchy Postgres for Kubernetes (specifically version 4) on Kubernetes 1.26.  Therefore, please see our most recent documentation for Crunchy Postgres for Kubernetes (specifically for version 5, with `v5.3.0` being the latest release available).  This will avoid the CRD errors that you're currently seeing when installing:

- https://access.crunchydata.com/documentation/postgres-operator/latest
- https://access.crunchydata.com/documentation/postgres-operator/latest/installation/

Also, as @prlaurence referenced, please see the documentation for our latest `pgo` CLI as well:

- https://access.crunchydata.com/documentation/postgres-operator-client/latest/

And if you do need support for Crunchy Postgres for Kubernetes v4 on Kubernetes 1.26, please reach out to info@crunchydata.com to discuss your use case further.

**Comment by andrewlecuyer** [comment]
@TauqeerAhmad104 you can find the binaries for the v5 `pgo` CLI in the [postgres-operator-client](https://github.com/CrunchyData/postgres-operator-client) GitHub repostory:

https://github.com/CrunchyData/postgres-operator-client/releases/tag/v0.2.0

**Comment by benjaminjb** [comment]
Hello @TauqeerAhmad104 , I hope the above comments were helpful in unblocking you. I'm going to close this issue now, but if you're still experiencing problems, please reopen so we can continue to work on this.
