### ISSUE TITLE
Function initialize.RestrictedSecurityContext() must set securityContext.seccompProfile

### ISSUE THREAD

**Issue by ron1** [CrunchyData/postgres-operator#3585]
## Overview

Function [initialize.RestrictedSecurityContext()](https://github.com/CrunchyData/postgres-operator/blob/8b14582aaa9df139b8eb38fe48a47f546db61f02/internal/initialize/security.go#L34)  must set securityContext.seccompProfile in order to satisfy PSS Restricted Profile. This is not currently the case.

## Environment

Please provide the following details:

- Platform: (`Rancher RKE2`)
- Platform Version: (`[v1.25.6+rke2r1] CIS 1.23`)
- PGO Image Tag: (`ubi8-5.3.0-0`)
- Postgres Version (`14`)
- Storage: (`hostpath`)

### REPRO

1. Try to provision PostgresCluster.

### EXPECTED

1. PostgresCluster provisions successfully.

### ACTUAL

1. PostgresCluster fails to provision because StatefulSet Pod violates PSS Restricted Profile. Specifically, required property `securityContext.seccompProfile` is missing.

**Comment by tony-landreth** [comment]
Thanks for reporting this issue. I've created a ticket.

**Comment by belfhi** [comment]
I would like to add that there are many options for the `seccompProfile` in the CRDs, there still seem to be some places where this cannot be specified, e.g. the backups `Jobs` or the `pgbackrest.repoHost`. manually editing in those specs helps but that's not entirely the point.

**Comment by benjaminjb** [comment]
Hi @ron1 and @belfhi,

As of our latest release (v5.6.0), SeccompProfile is now set to RuntimeDefault in all Pods .  Please see the following documentation for more information:
* https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.6.x
* https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.6.x/postgrescluster#postgresclusterspecinstancesindexcontainersindexsecuritycontextseccompprofile

I'm going to close this issue now, but if you have any issues or questions feel free to re-open this issue or reach out to us on our [Discord server](https://discord.com/invite/a7vWKG8Ec9).
