### ISSUE TITLE
Enable monitoring with specifying an image

### ISSUE THREAD

**Issue by mkjpryor** [CrunchyData/postgres-operator#3594]
## Overview

I would like to be able to enable monitoring for a `PostgresCluster` instance without needing to know the specific image to use.

## Use Case

I am deploying the postgres-operator and setting `RELATED_IMAGE_PGEXPORTER` on the postgres-operator pods. I would like to be able to enable monitoring on Postgres clusters without having to repeat that image. To me, this would make sense as the admin can set the image once on the postgres-operator installation, and dev teams don't need to know which image to use in order to enable monitoring for their instance.

## Desired Behavior

I would like there to be a flag that I can set, e.g. `spec.monitoring.pgmonitor.exporter.enabled`, to enable monitoring without having to know the specific image to use.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: `Kubernetes`
- Platform Version: `1.25`
- PGO Image Tag: `ubi8-5.3.0-0`
- Postgres Version: `14`
- Storage: `csi-cinder`
- Number of Postgres clusters: N

## Additional Information

Please provide any additional information that may be helpful.

**Comment by benjaminjb** [comment]
The answer above seems to fit your need as I understand it, so I'll close this now, but if you want to continue the conversation, feel free to reopen it.

**Comment by mkjpryor** [comment]
Forgot to say that this works. Maybe just needs documenting?
