### ISSUE TITLE
Getting remote error: tls: bad certificate on PGO CLI request 

### ISSUE THREAD

**Issue by idanl21** [CrunchyData/postgres-operator#3598]
Hey :)
Im using CrunchyData postgres-operator for more then a year, im managing my Prdod Env with it.
Suddenly in the last few days is started to get `remote error: tls: bad certificate` on every request that im doing against the Operator.
I noticed that my Certs are expired, how can i change and provide them without hurt the running PGO clusters that the operator is managing ?

**Comment by andrewlecuyer** [comment]
Hi @idanl21, sorry to hear you are having trouble with the CLI.  

The CLI architecture has changed quite a bit between versions 4 and 5 of Crunchy Postgres for Kubernetes, so a bit more information would be helpful in allowing us to properly troubleshoot the error you are currently seeing.

Therefore, please provide the following information/details regarding your environment and PGO install:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.)
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `ubi8-5.1.0-0`)

Thanks!
