### ISSUE TITLE
WAL files cleanup doesn't work properly with a replica of instances

### ISSUE THREAD

**Issue by RasheedJad** [CrunchyData/postgres-operator#3600]
Hi guys,

I have deployed on an openShift cluster this operator which contains (1 repo host and 3 replicas of instances). Besides that, I have configured the operator to create backups; full backup on spefic day and the other days are for incremental backups with repo1-retention-full: '2'. So, I have noticed recently is the WAL files are spreaded across the replica instances and when the time comes to clean them, they are only cleaned in ONE of the "3 replicas of instances" and the other 2 replicas would have WAL files from long time ago. Any reason for that?

**Comment by andrewlecuyer** [comment]
Hi @RasheedJad!

I'm a little confused by the situation, but hopefully we can help.  First and foremost, I was hoping to get some additional information/details:
- Can you clarify what is meant when you say replicas are “cleaned”? The pgBackRest retention settings affect the the storage of archives and backups within the pgBackRest repository (e.g. as mounted to the repo host), so I am not clear on the reference to replicas here.  Also, please note that any cleaning up of archives and/or backups should be left to pgBackRest (as set via retention configuration settings), i.e. these files should never be manually deleted.
- Have you seen any issues with archiving or backups? E.g. have you seen anything in the PostgreSQL (or pgBackRest) logs indicating failed WAL archiving and/or any failed backups?
- Have there been any recent failovers that might correspond to some of the behavior you are seeing?
- Have you applied any other PostgreSQL configuration setting that affect WAL archiving?

Additionally, can you also please provide the following details per our issue template:
- **Platform:** (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.)
- **Platform Version:** (e.g. `1.20.3`, `4.7.0`)
- **PGO Image Tag:** (e.g. `ubi8-5.1.0-0`)
- **Postgres Version:** (e.g. `14`)
- **Storage:** (e.g. `hostpath`, `nfs`, or the name of your storage class)

This information will help us in further troubleshooting your issue.

And finally, I also recommend checking out the following docs, which touch on the backup architecture for PGO:

https://access.crunchydata.com/documentation/postgres-operator/v5/architecture/backups/

Thanks!
