### ISSUE TITLE
Dockerfile for building image postgres-operator-upgrade

### ISSUE THREAD

**Issue by Eric-zch** [CrunchyData/postgres-operator#3603]
Hi There,
Do you know if there is a dockerfile for building image postgres-operator-upgrade?
Thank you.

**Comment by andrewlecuyer** [comment]
@Eric-zch thanks for reaching out!

We actually do not have a `Dockerfile` for the `postgres-operator-upgrade` container.  More specifically, all Major PostgreSQL Upgrade controller functionality has been consolidated into the `postgres-operator` container.

Therefore, moving forward the`postgres-operator-upgrade` container will no longer be needed.  Instead, you will simply need to run the `postgres-operator` container, which will provide the required Major PG Upgrades controller & API.

Please see PR https://github.com/CrunchyData/postgres-operator/pull/3512 for more details.

**Comment by Eric-zch** [comment]
@andrewlecuyer 
That is good news! Thank you
