### ISSUE TITLE
[Docs] Add dark mode

### ISSUE THREAD

**Issue by chris-sanders** [CrunchyData/postgres-operator#3610]
Just a simple request, the docs could really use a dark mode setting. Trying to go through the [Quick Start](https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/) it would be significantly easier to consume if I could enable dark mode. While I can, and did, do this with experimental browser features it's always more reliable if a dark them is provided directy.

**Comment by craigkerstiens** [comment]
@chris-sanders Thanks for the feedback, we're working on some improvements to our docs theming in coming weeks and months and will definitely keep this in mind. Can't promise anything definitive, but a very good chance when we roll out new theme we can support dark mode.
