### ISSUE TITLE
Restore cluster from backup

### ISSUE THREAD

**Issue by idanl21** [CrunchyData/postgres-operator#3615]
Hey :)
We are using postgres-operator in order to managed our postgres cluster on production. we have 2 backups, full and inc.
I want to restore and create new cluster from one of my backups, but i could not find any guide of the process on your repo.
Maybe you have any doc that explain about the process ?

Thanks !

**Comment by benjaminjb** [comment]
Hey @idanl21, there's docs here (in /docs/content), but they're really designed to be seen here: https://access.crunchydata.com/documentation/postgres-operator/v5/

The tutorial section is a good place to start looking for specific topic; for instance, sounds like you want the Disaster Recovery and Cloning section [here](https://access.crunchydata.com/documentation/postgres-operator/5.3.1/tutorial/disaster-recovery/).

Cheers!
