### ISSUE TITLE
The previous master pod's label(role=master) remains.

### ISSUE THREAD

**Issue by ayumi-ishii** [CrunchyData/postgres-operator#3617]
I have a question about role labels.
I have created a cluster of 3 instances (3 nodes).
For availability testing, I shut down the node on which the master instance was deployed.
Then  replica was promoted and the previous master instance was detached. Failover was successful.

However, I thought the label status was incorrect. When we failover, the new master pod is labeled role=master, but the former master pod is still labeled role=master, so there are two labels with the master.
Are these label states correct?

- Platform: Kubernetes
- Platform Version: 1.24.4
- Postgres Version: 14

Thank you.

**Comment by dsessler7** [comment]
Hello,

What version of the Operator are you running? Can you send the operator logs as well as the results of a `kubectl describe postgrescluster`?
