### ISSUE TITLE
Support OCP 4.12

### ISSUE THREAD

**Issue by fyang86** [CrunchyData/postgres-operator#3619]
Hi team, we are considering deploying PGO on openshift 4.12, but it's not inside the supported OCP systems yet. Any plans when will ocp 4.12 be supported? Thank you.

**Comment by andrewlecuyer** [comment]
Hi @fyang86 , thanks for reaching out!

The upcoming Crunchy Postgres for Kubernetes v5.4.0 release will include support for OpenShift v4.12.

We currently anticipate a Crunchy Postgres for Kubernetes v5.4.0 release for our subscription customers in June.  The release will then be made available though the [Developer Program](https://www.crunchydata.com/developers/download-postgres/containers) shortly thereafter.

Thanks!
Andrew

**Comment by fyang86** [comment]
@andrewlecuyer Thanks for the reply!

**Comment by fyang86** [comment]
Hi @andrewlecuyer , is there any ETA for PGO v5.4.0 release?
Also I want to ask here, what's your future release plan wrt OpenShift versions update? Do you plan to keep up with the openshift version update?
