### ISSUE TITLE
Bootstrap Pod image container version is no longer available 

### ISSUE THREAD

**Issue by idanl21** [CrunchyData/postgres-operator#3620]
Hey, After that you deleted you registry I managed to upload your images to my private registry and changed the ccp_image and  pog_image env so i can create clusters and backups.
But when im trying to create a new cluster from existing cluster the bootstrap pod is still using the old registry, i tried to look everywhere for that image build declaration , but cannot find it so i cannot restore a new cluster.

How do you build the image address for the bootstrap pod ? and where i can change it?

**Comment by andrewlecuyer** [comment]
Hi @idanl21, sorry to hear you're having trouble.

Can you provide the commands you utilized to create the new cluster?  For instance, if using the `pgo` CLI to create the cluster, I am curious about the use of flags such as  `--ccp-image-prefix`, `--ccp-image-tag`, etc.

Additionally, have you updated your `pgo.yaml` configuration file?  More specifically, setting such as:

- `CCPImagePrefix`
- `CCPImageTag`
- `PGOImagePrefix`
- `PGOImageTag`

The settings in the `pgo.yaml` configuration file define defaults for new clusters in Crunchy Postgres for Kubernetes v4, so you'll want to be sure these settings are properly updated as well.  This file can be found in a ConfigMap called `pgo-config`, with additional details in the following docs:

- https://access.crunchydata.com/documentation/postgres-operator/v4/configuration/pgo-yaml-configuration/
- https://access.crunchydata.com/documentation/postgres-operator/v4/configuration/configuration/

Also, feel free to send over a copy of your `pgo.yaml` file (along with the command to create the cluster, per the request above), and that should provide some good hints as to what is occurring here.
