### ISSUE TITLE
Not clear documentation about high-aviability

### ISSUE THREAD

**Issue by chobostar** [CrunchyData/postgres-operator#3642]
First of all, thank you for the amount of document that PGO have. Currently, it's the most documented postgres-operator.

However I find a moment about HA (high-aviability):

>If a replica believes that the primary is unavailable, it becomes a candidate and initiates an election and **votes for itself** as the new primary. A candidate **must receive a majority of votes** in a cluster in order to be elected as the new primary.
...
>The replica with the latest LSN wins and receives the vote of the other replica. The replica with **the majority of the votes** wins.

https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/

It's known that each container with PostgreSQL instance contains Patroni - https://github.com/CrunchyData/postgres-operator/blob/69a4d6c0aa8299d192cbcd771efbe08724446481/internal/patroni/config.md

Here is the source of what each node does during failover process:
https://github.com/zalando/patroni/blob/v2.1.7/patroni/ha.py#L690-L721

* it's not "voting" at all.
* there is no such thing as "majority" during failover

Why it's an issue? My customers think that to provide consensus for HA they must have 3 nodes for each Postgresql cluster. That's not true, and it's caused them to utilize more resources and pay more. It doesn't favor PGO as an efficient tool, in terms of TCO.

**Comment by tony-landreth** [comment]
Hello @chobostar! Thanks for the feedback on our documentation. Failover requires only one healthy replica. We will update our document on High Availability.

**Comment by benjaminjb** [comment]
Hello @chobostar, thanks for bringing this to our attention. We are updating the documentation and this issue should be fixed. If you see any other documentation that is vague or could be improved, please let us know.
