### ISSUE TITLE
pgo --custom-config is not honored 

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#365]
If global config "pgo-custom-pg-config" exists then --custom-config in pgo create is ignored and cluster is created with "pgo-custom-pg-config".  I would expect new cluster to be created with new config when --custom-config is passed regardless if global config is present or not.

 
 - [ X] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - Operator Version:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by jmccormick2001** [comment]
I think this is fixed now, here is how I tested it....
a) create the global custom config map   pgo-custom-pg-config
b) create a cluster NOT specifying --custom-config
c) examine the cluster's pgconf volume which indeed specifies pgo-custom-pg-config as expected
d) create a different custom config, this one is named pgo-custom-pg-config2
e) create a cluster specifying --custom-config=pgo-custom-pg-config222222
f) examine the cluster's pgconf volume which specifies the pgo-custom-pg-config2 as expected 

          {
                "configMap": {
                    "defaultMode": 420,
                    "name": "pgo-custom-pg-config2"
                },
                "name": "pgconf-volume"
            },
