### ISSUE TITLE
Does it intend to be used this project without CrunchyData's paid program?

### ISSUE THREAD

**Issue by polikeiji** [CrunchyData/postgres-operator#3651]
Based on [this Reddit thread](https://news.ycombinator.com/item?id=31882256), I think we need to submit CrunchyData's paid program when we use the container images offered by CrunchyData on production environments. And the CRDs in PGO don't offer enough configuration ability to utilize other container images, and the project doesn't also offer enough information about the requirements for the images. I think improving CRDs to allow using another image is easy, and I opened [a PR](https://github.com/CrunchyData/postgres-operator/pull/3486) to customize the entrypoint of the container image for the backup process, but it has been left for a half year without any feedback...

I think many people reached this project to find an open-source PostgreSQL solution on Kubernetes, which is available to use for free and developed in a community-based manner. If the project's intention is to be used by only people who subscribe to CrunchyData's paid program, I think clearly mentioning it is respectful behavior of the time for engineers and development teams.

**Comment by codestrong** [comment]
wow, CrunchyData, that's not cool

**Comment by craigkerstiens** [comment]
This is good question that actually required more thought to answer than it should seem. After some (considerable) internal discussion on the topic, we have decided to make a few changes to how we approach these things and hopefully clarify our position. Specifically: 

1. We have updated our Developer Program terms to be more transparent about our expectations.

2.  We will be providing ARM builds for our software as part of the Developer Program (as soon as we can get our registry updated to support multi-arch - please bare with us it may be a few weeks).

The updated and clarified guidance to the Developer Program terms is summarized below, with the full updated terms available [here](https://www.crunchydata.com/developers/terms-of-use).

| | Individuals and small organization (<50 Employees) | Large Organization (50+ Employees) |
| --- |  --- |  --- | 
| Personal or Internal Use of Crunchy Data Software for Development Purposes  | Permitted | Permitted | 
| Personal or Internal Use of Crunchy Data Software for Production Purposes | Permitted | Not Permitted |
| Resale or Redistribution of Crunchy Data Software to Third Parties | Not Permitted | Not Permitted |
| Use of Crunchy Data Software in Connection with Consulting or Support Services Delivered to Third Parties | Not permitted | Not permitted | 

The longer answer is we (Crunchy Data) care a lot about the integrity of open source. We develop a considerable amount of open source code, we contribute to and maintain a number of open source projects, our team includes a number of individuals who have spent their careers building open source projects and communities. We care about and value the meaning of 'open source' and the benefits it provides in both the use of open source and the predictability of open source licensing.  It is important to us to continue to provide the source code we develop as open source projects on an open source basis and under open source licenses as we have always done. That of course affords users with considerable rights to use the software source - in many instances in ways that are at odds with our commercial interests. That said, we value the integrity of open source, on balance benefit from it greatly and will continue to ensure we do our small part to maintain that integrity.

At the same time we are a commercial entity and thus need to balance commercial interests. We have commercial products that we sell to our customers. These commercial products are not 'free'.  These products are generally commercial distributions of open source that is either community or Crunchy Data maintained. Our customers value the validation, testing and certification of the software we distribute, the software supply chain security value associated with those practices, and the high quality support from our team of experts. These practices may seem overly 'enterprise' to some and indeed our customers of Crunchy Postgres for Kubernetes tend to skew 'large enterprises', but we have customers across the full spectrum of users who value these commercial offerings.  The software we deliver as part of the Developer Program is an important part of these products. These products have a real cost to deliver and we have a number of customers who see the value in paying for them. 

While open source licensing of source code is a topic we care about, software users - including developers - of course generally are looking for software and not simply source code. 

Our Crunchy Data Developer Program was initially created to support developers use of our software. Based on feedback from the community and our team it now seems appropriate to update that program to better serve various interests. In balancing the interests of supporting developers use our software and our commercial interests, we do not want to make it prohibitive for developers (or small organizations) to use our software.  That said, we do want to make clear we intend for larger enterprise users to pay for use of this software in production, where the software creates real value.  While we make these updates to the Developer Program terms, we are also working to improve or communication and support for community users. More to come on that hopefully soon. 

Creating simple rules to balance important competing interests almost always produces some bad outcomes in corner cases. We are committed to continuing to listen to feedback on these issues and to do our best to learn from that feedback. In the meantime, we hope that this new clarified guidance will provide more transparency and provide a clearer, better outcome for a large spectrum of our software users and communities of interest.
