### ISSUE TITLE
Add Delete Protection of underlying PV with persistentVolumeReclaimPolicy

### ISSUE THREAD

**Issue by szelenka** [CrunchyData/postgres-operator#3654]
- [x] Provide a concise description of your feature request.
- [x] Describe your use case. Detail the problem you are trying to solve.
- [x] Describe how you envision that the feature would work.
- [x] Provide general information about your current PGO environment.

## Overview

Kubernetes has a persistentVolumeReclaimPolicy setting, to allow for specifying the reclaim policy of a PersistentVolume (ref: https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/). However this setting is not exposed through the CRD. 

There is documentation on how to alter the PV `after` the CRD and Operator create it, but this separates the infrastructure code from what's running on the system. (ref: https://github.com/CrunchyData/postgres-operator/blob/b1395cbf6fa83986e3ecc03ae186bf2d0127d3d8/docs/content/guides/storage-retention.md?plain=1#L49)

Ideally, we'd be able to specify this in the CRD with the `persistentVolumeReclaimPolicy` field.

## Use Case

Coming from Zalando Postgres Operator, have a type of "delete protection" mechanism to their CRD, which would add annotations to the k8s objects (ref: https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#delete-protection-via-annotations). 

This protected the underlying database from accidentally being purged when the CRD was deleted. So it'd be possible to recreate the cluster from an existing PV.

Crunchy has a method to build a cluster from an existing PV, but does not have a method to prevent deletion of a PV through the CRD.  

## Desired Behavior

It would be ideal if the CRD would have an option for the user to specify the persistentVolumeReclaimPolicy desired for the database being created; especially for the most important "dataVolume". For example:
```yaml
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
        persistentVolumeReclaimPolicy: "Retain"
        storageClassName: "standard"
```

The default persistentVolumeReclaimPolicy is "Delete", which means when the CRD is removed, k8s will purge the PV and all data in it. This does not protect against accidental deletes. You could create your own storageClass with the reclaim policy set to the desired policy, but this complicates re-use with other k8s services.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: `Kubernetes`
- Platform Version: 1.25
- PGO Image Tag: n/a
- Postgres Version `15`
- Storage: `standard`
- Number of Postgres clusters: n/a

## Additional Information

Update the CRD to expose persistentVolumeReclaimPolicy

**Comment by jmckulk** [comment]
Hi @szelenka,

The section of the spec that you reference, `dataVolumeClaimSpec`, relates to the `persistentvolumeclaim`, not the `persistentvolume` itself. To be able to set the reclaim policy on the volume through the spec, we would need to update the RBAC for PGO to allow changes on a `persistentvolume`. This would be a cluster-level permission, so we would only want to make that change if there isn't another option.

We do have a story in our backlog to allow `persistentvolumeclaims` to be retained upon cluster deletion.  Ideally, this solution would not require changes to a `persistentvolume` and the extra RBAC. Would this cover your use case? If so, I can link this issue to that story.

Normally, we recommend using a `storageclass` like you and @ThommyH mentioned, but I do understand how it makes re-use more complicated. Maybe you could update the installer example to also include the required storage class.

**Comment by jmckulk** [comment]
I don't think we have anything more to add around this issue at this time. If you have additional information about your use case or if the proposed solution will work for you. You are welcome to reopen this issue.
