### ISSUE TITLE
[Bug] - Crunchy Data 5.3.0 in Openshift 4.10 - no matches for kind "PGUpgrade" 

### ISSUE THREAD

**Issue by dinbtechit** [CrunchyData/postgres-operator#3665]
## Overview

we are using openshift postgres operator (v5.3.0). But there is no pgupgrade crd:

Following this documentation -> https://access.crunchydata.com/documentation/postgres-operator/latest/guides/major-postgres-version-upgrade/

We got the following error when attempting to upgrade.

```
no matches for kind "PGUpgrade" in version "posteres-operator.crunchydata.com/vlbetal"
```

## Environment

Please provide the following details:

- Platform: `OpenShift`
- Platform Version: 4.10
- PGO Image Tag: `registry.connect.redhat.com/crunchydata/crunchy-postgres@sha256:1c336e8a3a7447be70a19235b0e9bcd19663955c8f480949281f5d24463637e5`
- Postgres Version: 13
- Storage: pvc

### REPRO

Provide steps to get to the error condition:

1. Follow the steps from the documentation -  https://access.crunchydata.com/documentation/postgres-operator/latest/guides/major-postgres-version-upgrade/
2. apply 
   ```sh
    oc apply -f pgupgrade.yaml
    error: unable to recognize "vcpupgrade.yam]": no matches for kind "PUpgrade" in version "postgres-operator.crunchydata.com/v1beta1"
   ```

### EXPECTED

Should be able to upgrade postgres database by following the documentation.

### ACTUAL

Currently we are running into this error

```
error: unable to recognize "vcpupgrade.yam]": no matches for kind "PUpgrade" in version "postgres-operator.crunchydata.com/v1beta1"
```

## Logs

N/A

## Additional Information

Please let me know if you need any other info.

**Comment by jmckulk** [comment]
Hi @dinbtechit, I have a couple of questions to help debug this issue. First, how did you install the operator? Next, can you provide your `postgrescluster` spec?

**Comment by jmckulk** [comment]
The PGUpgrade controller and CRD are not available when you install PGO 5.3 through Operator Hub or OLM. They will be available in the coming 5.4 release, but if you would like to work with major upgrades now, you can always install using the postgres-operator-examples repo (https://github.com/CrunchyData/postgres-operator-examples).

**Comment by Vongott99** [comment]
Any ETA on 5.4?

**Comment by dsessler7** [comment]
CPK 5.4.0, which contains the PGUpgrade controller and CRD in the OperatorHub/OLM installers, has been released, so I am closing this issue.
