### ISSUE TITLE
Add support for postgres_exporter 13.0+

### ISSUE THREAD

**Issue by szelenka** [CrunchyData/postgres-operator#3675]
Have an idea to improve PGO? We'd love to hear it! We're going to need some information from you to learn more about your feature requests.

Please be sure you've done the following:

- [x] Provide a concise description of your feature request.
- [x] Describe your use case. Detail the problem you are trying to solve.
- [x] Describe how you envision that the feature would work.
- [x] Provide general information about your current PGO environment.

## Overview

Support for custom SQL queries for exporting metrics to Prometheus has be deprecated in `prometheus-community/postgres_exporter` upstream version 0.13+. This renders the startup logic in start.sh ineffective, and drops all custom queries provided by the `CrunchyData/pgmonitor` repo:

https://github.com/CrunchyData/postgres-operator/blob/master/bin/crunchy-postgres-exporter/start.sh

## Use Case

Remain up-to-date with the latest versions of upstream open-source Postgres, and supporting projects.

## Desired Behavior

Contribute logic for `queries.yaml` from `CrunchyData/pgmonitor` back to `prometheus-community/postgres_exporter` in the new "collections" format, and adjust the `start.sh` to start without the custom queries; such that Crunchy PGO can use the latest `prometheus-community/postgres_exporter` from upstream.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: `Kubernetes`
- Platform Version: `5.3.1`
- PGO Image Tag: `ubi8-5.3.1-0`
- Postgres Version `15`
- Storage: `standard`
- Number of Postgres clusters: `5`

## Additional Information
See sister PR for this breaking change: https://github.com/CrunchyData/pgmonitor/issues/347

**Comment by tjmoore4** [comment]
Hello @szelenka, thank you for submitting this issue.
I've added an item to our development backlog.

**Comment by benjaminjb** [comment]
Hello, @szelenka, as of our recent release, we've updated the postgres_exporter to 0.15.0 (and adjusted our startup command accordingly). 

We've changed some of the architecture around metrics collection, and one of those changes was to the exporter container, which should now be tagged like so: `crunchy-postgres-exporter:ubi8-0.15.0-0`.

(For more on the metrics and monitoring changes, check our [release blog](https://www.crunchydata.com/blog/announcing-crunchy-postgres-for-kubernetes-5-5#enhanced-metrics--monitoring) and [release notes](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.5.x#550-features).)

I'm going to close this ticket, but feel free to reopen it if there's any problems or drop us a line in our [discord](​​https://discord.com/invite/a7vWKG8Ec9).
