### ISSUE TITLE
what are config*.*.configmap CRDs for?

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3679]
There are some config\*.\*.configmap CRDs:
- PostgresCluster.spec.backups.pgbackrest.configuration[index].configMap
- PostgresCluster.spec.config.files[index].configMap
- PostgresCluster.spec.dataSource.pgbackrest.configuration[index].configMap
- PostgresCluster.spec.monitoring.pgmonitor.exporter.configuration[index].configMap
- PostgresCluster.spec.proxy.pgBouncer.config.files[index].configMap
- PostgresCluster.spec.userInterface.pgAdmin.config.files[index].configMap

What are they for? Could you show a coded example, especially the "files[index]" ones?

**Comment by benjaminjb** [comment]
Hey @mzwettler2, thanks for this question -- I poked around and I think we may need more documentation (and maybe examples) on the topic of `.config` and `.configuration` fields.

We do have some documentation around these, like in our discussion of how to [customize backups](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/backups-disaster-recovery/backups#custom-backup-configuration) in the docs and in the [CRD](https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/postgrescluster#configurationindex); or how to [customize pgbouncer](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/connection-pooling#configuration). 

So, _in general_, the answer to your question is that the `configMap` (and other fields under `files` or `configuration`) are mounted/projected on the pod for customizing.

For instance, if you wanted to run your own metrics in pgmonitor, you can accomplish that by (let me check the [CRD](https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/postgrescluster#configurationindex))

a. creating a configMap with a `queries.yml` file:
```
kubectl create configmap metric --from-file=queries.yml
```

b. and then mounting that configMap through the spec:

```
monitoring:
   pgmonitor:
     exporter:
       configuration:
         - configMap:
             name: metric
```

(That's a `configuration[index].configMap` example, but the `config.files[index].configMap` examples would look about the same.)

Hope that helps!

**Comment by mzwettler2** [comment]
Thanks
