### ISSUE TITLE
pgo create cluster --pgbackrest does not work without --custom-config option ( kube )

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#368]
When i try to create cluster with pgbackrest enabled:

` pgo create cluster foo7 --archive --autofail --pgbackrest 
`
i get Error: pgo-custom-pg-config global configmap or --custom-config flag not set, one of these is required for enabling pgbackrest

it only work if i do
pgo create cluster foo7 --archive --autofail --pgbackrest -g pgo-pgbackrest-config
created Pgcluster foo7

```

kubectl get cm
NAME                    DATA      AGE
operator-conf           21        4h
pgo-pgbackrest-config   1         4h
```

 
 - [ ] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - Operator Version:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by jmccormick2001** [comment]
this should be fixed with 3.4.0, with this version you no longer have to specify a --custom-config option.
