### ISSUE TITLE
Is it wrong notice in documentation?

### ISSUE THREAD

**Issue by balinorLiang** [CrunchyData/postgres-operator#3680]
I noticed that docs showed that pgAdmin4 is not currently compatible with PostgreSQL 15 in architecture pgAdmin4 page. 
![image](https://github.com/CrunchyData/postgres-operator/assets/134899174/761b23ac-b67a-47cd-9fdf-2818e8ab22f0)
But from pgadmin4(new version 7.4), it already supported postgreSQL15, am I wrong? 
Or would you like to share some features that are not currently compatible ? Thanks a lot~

**Comment by benjaminjb** [comment]
Hello @balinorLiang, you're right that the most recent PgAdmin is compatible with PG 15, but Crunchy Postgres for Kubernetes currently integrates with an older version of PgAdmin (4.30) which is not compatible with PG 15.  We do, however, have plans to revisit this integration to add support for PG 15, which includes upgrading to a more recent version of pgAdmin4.
