### ISSUE TITLE
Monitoring of a standby cluster

### ISSUE THREAD

**Issue by mayab2703** [CrunchyData/postgres-operator#3682]
### Overview
Hello, we are currently facing some trouble when trying to figure out a way to monitor our standby cluster
(a warm standby).

### Environment

Our environment consists of 2 sites and any customer can choose what his primary site is (meaning we can’t know for sure which site contains the primary cluster and which the standby)

We are using the Postgres exporter to collect metrics on each pod.

- Platform: OpenShift
- Platform Version: v1.21.1 (kubernetes version)
- PGO Image Tag: 4.6.1
- Postgres Version: 12.6

### The Problem
So we are faced with 2 issues:
1. Is there known method to differentiate between the primary cluster and the standby cluster?
2. what's the best practice for monitoring the standby cluster and in particularly the replication status?

Thanks in advance!

**Comment by dsessler7** [comment]
Hello @mayab2703,

Maybe I'm not understanding the situation, but how is your customer even able to use the database if you don't know which one is the live database and which one is the standby?

Regardless, I think adding a custom label when you create each cluster should help you differentiate them.

As far as monitoring the standby goes, we don't currently support this, but it is on our roadmap.

**Comment by rj-home** [comment]
+1 on this issue

**Comment by benjaminjb** [comment]
We've recently made some changes to enable monitoring from a standby cluster.

For reference: 

* here's the [announcement](https://www.crunchydata.com/blog/announcing-crunchy-postgres-for-kubernetes-5-5#monitoring-standby-clusters) where we discuss it; and
* here's our [tutorial on setting up standby monitoring](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/backups-disaster-recovery/disaster-recovery#monitoring-a-standby-cluster), which will also lead you to our docs on [setting the monitoring user's password](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/day-two/monitoring#setting-a-custom-ccp_monitoring-password).

So putting this all together:

a. to differentiate metrics from different clusters, you should be able to label those clusters;
b. with the new updates (and docs), you should be able to enable monitoring from a standby.

I'm going to close this ticket, but please reopen it if these answers don't work for you.
