### ISSUE TITLE
postgres instance set name is not actually optional

### ISSUE THREAD

**Issue by uhthomas** [CrunchyData/postgres-operator#3684]
## Overview

The name for a postgres instance set is documented as optional, but is not actually optional when validation code is generated.

https://github.com/CrunchyData/postgres-operator/blob/94ebcf2df74d38aa938f9c2e8b38604fae8c776e/pkg/apis/postgres-operator.crunchydata.com/v1beta1/postgrescluster_types.go#L423

I believe all it needs is for the string to be a pointer:

```diff
-Name string `json:"name"`
+Name *string `json:"name"`
```

**Comment by cbandy** [comment]
The CRD generated by `make generate` has an optional `name` field. (The field is not `required`.) What validation code are you generating, and how?

https://github.com/CrunchyData/postgres-operator/blob/94ebcf2df74d38aa938f9c2e8b38604fae8c776e/pkg/apis/postgres-operator.crunchydata.com/v1beta1/postgrescluster_types.go#L416-L423

https://github.com/CrunchyData/postgres-operator/blob/94ebcf2df74d38aa938f9c2e8b38604fae8c776e/config/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml#L10019-L10021

```yaml
                  required:
                  - dataVolumeClaimSpec
                  type: object
```

```console
$ yq '.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.instances.items.required' config/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml
[
  "dataVolumeClaimSpec"
]
```

**Comment by uhthomas** [comment]
I'm using [cue](https://cuelang.org/) which generates:

```cue
#PostgresInstanceSetSpec: {
	// ...

	// Name that associates this set of PostgreSQL pods. This field is optional
	// when only one instance set is defined. Each instance set in a cluster
	// must have a unique name. The combined length of this and the cluster name
	// must be 46 characters or less.
	// +optional
	// +kubebuilder:default=""
	// +kubebuilder:validation:Pattern=`^([a-z0-9]([-a-z0-9]*[a-z0-9])?)?$`
	name: string @go(Name)

        // ...
}
```

https://github.com/uhthomas/automata/blob/a1d50f6c5c9db96089c9a46fbb89682e4d378cc2/cue.mod/gen/github.com/crunchydata/postgres-operator/pkg/apis/postgres-operator.crunchydata.com/v1beta1/postgrescluster_types_go_gen.cue#L358-L365
