### ISSUE TITLE
Numerous broken links to documentation in README.md

### ISSUE THREAD

**Issue by mloskot** [CrunchyData/postgres-operator#3687]
Current https://github.com/CrunchyData/postgres-operator/blob/959f97a05869a604267d9aac43485636af59fd8e/README.md contains lots of links to important sections of PGO documentation and quite a few of those links are broken, for example:

- [High Availability](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/high-availability/)
- [distributed consensus high availability solution](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/high-availability/)
- [Disaster Recovery](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/)
- [Backups](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/)
- [restores](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/)
- [includes support for full, incremental, and differential backups as well as efficient delta restores](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/)
- [Monitoring](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/monitoring/)
- [Track the health of your PostgreSQL clusters](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/monitoring/)

There may be more

**Comment by andrewlecuyer** [comment]
Thanks for reporting this!

The broken links were the result of some recent updates to our documentation, and have now been fixed.

**Comment by mloskot** [comment]
Thanks
