### ISSUE TITLE
pgo backup status not getting updated

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#369]
**I'm submitting a ...**

 
 - [ x] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
pgo backup (pg_basebackup) on cluster completed. The job completed, the backup is created on the backup pvc. But, the "pgo show backup" still shows status as "Submitted"

**If the current behavior is a bug, please provide the steps to reproduce:**
deploy 3.2.0 operator
create a cluster using pgo create cluster testcluster
pgo backup testcluster

**What is the expected behavior?**
backup status should show completed. 

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
centos7
 - Container Image Tag:
10.5-2.1.0
 - Operator Version:
3.2.0
 - PostgreSQL Version:
10.5

 - Platform (Docker, Kubernetes, OpenShift):
openshift enterprise

 - Platform Version: 
3.10

**Comment by jmccormick2001** [comment]
should be fixed in 3.3.0.
