### ISSUE TITLE
Can't connect pgo client to cluster from PowerShell on Windows 11

### ISSUE THREAD

**Issue by vit-h** [CrunchyData/postgres-operator#3691]
Can't connect (first-time) pgo client to cluster from PowerShell on Windows 11.

I followed this instruction https://access.crunchydata.com/documentation/postgres-operator/4.0.1/installation/install-pgo-client/
Extracted certificates and key from kubeconfig, set env variables but did not get it connected.

How to get it working?
Do I connect to the right pod?
Do I have the correct setup?

kubectl port-forward pgo-9b8b6954b-fqngw -n postgres-operator 8443:8443
Forwarding from 127.0.0.1:8443 -> 8443
Forwarding from [::1]:8443 -> 8443
Handling connection for 8443
E0715 23:26:20.472493   65420 portforward.go:406] an error occurred forwarding 8443 -> 8443: error forwarding port 8443 to pod 253b113a687231c5bffd36997af9d77728760fbb4ddb22155fac268a842a6665, uid : failed to execute portforward in network namespace "/var/run/netns/cni-c43a0e4b-e3cc-c42c-9671-e54871381c2d": failed to connect to localhost:8443 inside namespace "253b113a687231c5bffd36997af9d77728760fbb4ddb22155fac268a842a6665", IPv4: dial tcp4 127.0.0.1:8443: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
E0715 23:26:20.473261   65420 portforward.go:234] lost connection to pod

when trying to connect (e.g. do pgo version) or 
pgo show user --all
Error: Do:  Post "https://127.0.0.1:8443/usershow": EOF
Error: Post "https://127.0.0.1:8443/usershow": EOF

kubectl -n postgres-operator get pods
NAME                           READY   STATUS      RESTARTS   AGE
itfpgdb-backup-ccx8-fb6mq      0/1     Completed   0          3d23h
itfpgdb-instance1-dmps-0       4/4     Running     0          3d23h
itfpgdb-instance1-nkjs-0       4/4     Running     0          3d23h
itfpgdb-repo-host-0            2/2     Running     0          3d23h
pgo-9b8b6954b-fqngw            1/1     Running     0          3m37s
pgo-upgrade-5b576ccfb5-njcq8   1/1     Running     0          63d
PS C:\Users\vital> kubectl -n postgres-operator port-forward svc/postgres-operator 8443:8443
Error from server (NotFound): services "postgres-operator" not found
PS C:\Users\vital> kubectl get svc -n postgres-operator
NAME                TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
itfpgdb-ha          ClusterIP   10.0.158.107   <none>        5432/TCP   3d23h
itfpgdb-ha-config   ClusterIP   None           <none>        <none>     3d23h
itfpgdb-pods        ClusterIP   None           <none>        <none>     3d23h
itfpgdb-primary     ClusterIP   None           <none>        5432/TCP   3d23h
itfpgdb-replicas    ClusterIP   10.0.194.220   <none>        5432/TCP   3d23h
PS C:\Users\vital> kubectl get all -n postgres-operator
NAME                               READY   STATUS      RESTARTS   AGE
pod/itfpgdb-backup-ccx8-fb6mq      0/1     Completed   0          3d23h
pod/itfpgdb-instance1-dmps-0       4/4     Running     0          3d23h
pod/itfpgdb-instance1-nkjs-0       4/4     Running     0          3d23h
pod/itfpgdb-repo-host-0            2/2     Running     0          3d23h
pod/pgo-9b8b6954b-fqngw            1/1     Running     0          5m4s
pod/pgo-upgrade-5b576ccfb5-njcq8   1/1     Running     0          63d

NAME                        TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/itfpgdb-ha          ClusterIP   10.0.158.107   <none>        5432/TCP   3d23h
service/itfpgdb-ha-config   ClusterIP   None           <none>        <none>     3d23h
service/itfpgdb-pods        ClusterIP   None           <none>        <none>     3d23h
service/itfpgdb-primary     ClusterIP   None           <none>        5432/TCP   3d23h
service/itfpgdb-replicas    ClusterIP   10.0.194.220   <none>        5432/TCP   3d23h

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/pgo           1/1     1            1           118d
deployment.apps/pgo-upgrade   1/1     1            1           118d

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/pgo-9b8b6954b            1         1         1       118d
replicaset.apps/pgo-upgrade-5b576ccfb5   1         1         1       118d

NAME                                      READY   AGE
statefulset.apps/itfpgdb-instance1-dmps   1/1     3d23h
statefulset.apps/itfpgdb-instance1-nkjs   1/1     3d23h
statefulset.apps/itfpgdb-repo-host        1/1     3d23h

NAME                            COMPLETIONS   DURATION   AGE
job.batch/itfpgdb-backup-ccx8   1/1           33s        3d23h

Installed long time ago using these instructions: https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart
and commands in particular:
kubectl apply -k kustomize/install/namespace
kubectl apply --server-side -k kustomize/install/default

ENV: AKS

Not sure where to check:
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `ubi8-5.1.0-0`)
- Postgres Version (e.g. `15`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

**Comment by dsessler7** [comment]
Hello,

It appears like you are attempting to use the v4 PGO CLI with a v5 cluster which will not work. We have a v5 specific client, the documentation and installation instructions for which can be found here:

https://github.com/CrunchyData/postgres-operator-client

If you have any further issues, please open a new issue.
