### ISSUE TITLE
What is a best practice to elect a new Postgres leader to a different availability zone?

### ISSUE THREAD

**Issue by m0sh1x2** [CrunchyData/postgres-operator#3693]
Hello,

We have a two-region k8s cluster that has two zones 30-50ms apart and we would like to set up a scenario in which we:

- Manually/Automatically elect/assign a PostgreSQL leader to the new zone in case of partial disaster or service disruption
- Do this for more than 50 to 200 clusters

Based on my understanding we can manually change the leader of a Cluster Instance using the `patroni.switchover` option. 

But can we do this with pod affinity so that we can specify in which zones the `leader` should be located at? For example assign leaders only to zone-a and replicas to zone-b.

Another option that I understand from the documentation is to use Streaming Replication and manually shutdown the primary cluster and enable the Standby cluster to a primary.

Please if possible let me know if we should consider using something else or else or if there might be a good pattern in doing HA PostgreSQL on multiple availability zones.

Thanks.

**Comment by dsessler7** [comment]
Hey there!

You can definitely specify that certain pods reside on a particular node using `nodeAffinity` as explained in the following doc:

https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability#node-affinity
