### ISSUE TITLE
Replace TPR with CRD

### ISSUE THREAD

**Issue by rimusz** [CrunchyData/postgres-operator#37]
Kubernetes 1.7 has deprecated TPRs in favor of CRDs. 
Any plans to move to CRD soon?

**Comment by jmccormick2001** [comment]
yes, it will happen, just a matter of planning when, but its on the roadmap.

**Comment by jmccormick2001** [comment]
I'll leave this open so as to remind me to get this done :^))

**Comment by rimusz** [comment]
cool, as k8s v1.8 release is planned end of the month, so that will break postgres-operator work

**Comment by rimusz** [comment]
any plans to CRD support soon?

**Comment by jmccormick2001** [comment]
yes, I have it working and in final testing, should land in a week is my plans.

**Comment by jmccormick2001** [comment]
merged into master, Version 2.0 is out the door....
