### ISSUE TITLE
Can't restore database on EKS

### ISSUE THREAD

**Issue by kyotin** [CrunchyData/postgres-operator#3700]
## Overview

I have a backup data on s3 which was generated by operator. Then now, I tried to spin-up a new postgres cluster with DataSource option so that I can restore the data before starting postgres cluster. 

But I got problem with EKS, the restore processing is working well, but it's stopped with
```
pg_ctl: could not start server
Examine the log output.
```

However, when I run the same code on GKE, it's working well.

## Environment

Please provide the following details:

- Platform: `EKS`
- Platform Version: `1.25`
- Postgres Image Tag: `crunchy-postgres:ubi8-15.3-2`
- PGBackRest Image Tag: `crunchy-pgbackrest:ubi8-2.45-2`
- Postgres Version: `15`
- Storage: `aws-ebs`

## Steps to Reproduce
Because I'm using golang code to trigger backup/restore, so it's hard for me to write down step by step. 

## Logs
I attached here 2 log files, 1 for eks, and another 1 for gke
[pgbackrest-restore_eks.log](https://github.com/CrunchyData/postgres-operator/files/12288073/pgbackrest-restore_eks.log)

[pgbackrest-restore_gke.log](https://github.com/CrunchyData/postgres-operator/files/12288071/pgbackrest-restore_gke.log)

**Comment by ValClarkson** [comment]
Hi @kyotin,

Would you be able to give us the spec you used to spin up this new postgres cluster in EKS?
