### ISSUE TITLE
Support PGVector extension

### ISSUE THREAD

**Issue by VictorGaiva** [CrunchyData/postgres-operator#3706]
## Overview

Allow usage with PGVector extension out of the box.

**Comment by andrewlecuyer** [comment]
Hi @VictorGaiva!

The pgvector extension is now available in Crunchy Postgres for Kubernetes, as show in the [v5.4.x release notes](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.4.x):

> The [pgvector](https://github.com/pgvector/pgvector) extension, version 0.4.4, is now available.

You'll therefore want to update to the latest Crunchy Postgres for Kubernetes release (e.g. v5.4.0+) to take advantage of this extension.

I hope this helps!
