### ISSUE TITLE
Pgbackrest container is unable to start due to " unable to load key file '/etc/pgbackrest/server/server-tls.key': [33558541] Permission denied" error

### ISSUE THREAD

**Issue by desorenp** [CrunchyData/postgres-operator#3707]
If you believe you have found have found a bug, please open up [Bug Report](https://github.com/CrunchyData/postgres-operator/issues/new?template=bug_report.md)

If you have a feature request, please open up a [Feature Request](https://github.com/CrunchyData/postgres-operator/issues/new?template=feature_request.md)

You can find information about general PGO [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) at:

[https://access.crunchydata.com/documentation/postgres-operator/latest/support/](https://access.crunchydata.com/documentation/postgres-operator/latest/support/)

## Questions

For questions that are neither bugs nor feature requests, please be sure to

- [ ]I have CrunchyPostgres operator running in OCP 4.11.46.
- [ ] This crunchy postgres operator was running fine on OCP 4.11.0, but after upgraded to 4.11.46, the pgbackrest pod is not coming up.
- [ ] Attach logs, where applicable. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.

Pod logs :

[cloud-user@test ~]$ oc logs -f pod/pg14-ha-patroni-repo-host-0
Defaulted container "pgbackrest" out of: pgbackrest, pgbackrest-config, pgbackrest-log-dir (init), nss-wrapper-init (init)
P00   INFO: server command begin 2.45: --exec-id=5147-66241670 --log-level-console=detail --log-level-file=off --log-level-stderr=error --log-path=/pgbackrest/repo1/log --no-log-timestamp --tls-server-address=0.0.0.0 --tls-server-auth=pgbackrest@a0bbaa9c-10d6-4711-b555-f33062fc0b68=* --tls-server-ca-file=/etc/pgbackrest/conf.d/~postgres-operator/tls-ca.crt --tls-server-cert-file=/etc/pgbackrest/server/server-tls.crt --tls-server-key-file=/etc/pgbackrest/server/server-tls.key
P00 DETAIL: statistics: {"socket.server":{"total":1}}
P00   INFO: server command end: aborted with exception [095]
ERROR: [095]: unable to load key file '/etc/pgbackrest/server/server-tls.key': [33558541] Permission denied

Below is the pod yaml:

`kind: Pod
apiVersion: v1
metadata:
  generateName: pg14-ha-patroni-repo-host-
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.7.89"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.7.89"
          ],
          "default": true,
          "dns": {}
      }]
    kubectl.kubernetes.io/restartedAt: '2023-08-18T05:37:54Z'
    openshift.io/scc: anyuid
  resourceVersion: '86043119'
  name: pg14-ha-patroni-repo-host-0
  uid: 90178bbd-c399-45c2-acb8-972e478217dc
  creationTimestamp: '2023-08-18T05:54:43Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-08-18T05:54:43Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/restartedAt': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:controller-revision-hash': {}
            'f:postgres-operator.crunchydata.com/cluster': {}
            'f:postgres-operator.crunchydata.com/data': {}
            'f:postgres-operator.crunchydata.com/pgbackrest': {}
            'f:postgres-operator.crunchydata.com/pgbackrest-dedicated': {}
            'f:statefulset.kubernetes.io/pod-name': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"5ddb1922-619d-4ee1-afe4-65d2d7c8e066"}': {}
        'f:spec':
          'f:topologySpreadConstraints':
            .: {}
            'k:{"topologyKey":"kubernetes.io/hostname","whenUnsatisfiable":"ScheduleAnyway"}':
              .: {}
              'f:labelSelector': {}
              'f:maxSkew': {}
              'f:topologyKey': {}
              'f:whenUnsatisfiable': {}
            'k:{"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"ScheduleAnyway"}':
              .: {}
              'f:labelSelector': {}
              'f:maxSkew': {}
              'f:topologyKey': {}
              'f:whenUnsatisfiable': {}
          'f:volumes':
            .: {}
            'k:{"name":"pgbackrest-config"}':
              .: {}
              'f:name': {}
              'f:projected':
                .: {}
                'f:defaultMode': {}
                'f:sources': {}
            'k:{"name":"pgbackrest-server"}':
              .: {}
              'f:name': {}
              'f:projected':
                .: {}
                'f:defaultMode': {}
                'f:sources': {}
            'k:{"name":"repo1"}':
              .: {}
              'f:name': {}
              'f:persistentVolumeClaim':
                .: {}
                'f:claimName': {}
            'k:{"name":"tmp"}':
              .: {}
              'f:emptyDir':
                .: {}
                'f:sizeLimit': {}
              'f:name': {}
          'f:containers':
            'k:{"name":"pgbackrest"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/etc/pgbackrest/conf.d"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                'k:{"mountPath":"/etc/pgbackrest/server"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                'k:{"mountPath":"/pgbackrest/repo1"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/tmp"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:command': {}
              'f:livenessProbe':
                .: {}
                'f:exec':
                  .: {}
                  'f:command': {}
                'f:failureThreshold': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:env':
                .: {}
                'k:{"name":"LD_PRELOAD"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"NSS_WRAPPER_GROUP"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"NSS_WRAPPER_PASSWD"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:securityContext':
                .: {}
                'f:allowPrivilegeEscalation': {}
                'f:capabilities':
                  .: {}
                  'f:drop': {}
                'f:privileged': {}
                'f:readOnlyRootFilesystem': {}
                'f:runAsNonRoot': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:name': {}
            'k:{"name":"pgbackrest-config"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/etc/pgbackrest/conf.d"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                'k:{"mountPath":"/etc/pgbackrest/server"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                'k:{"mountPath":"/tmp"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:command': {}
              'f:securityContext':
                .: {}
                'f:allowPrivilegeEscalation': {}
                'f:capabilities':
                  .: {}
                  'f:drop': {}
                'f:privileged': {}
                'f:readOnlyRootFilesystem': {}
                'f:runAsNonRoot': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:name': {}
          'f:hostname': {}
          'f:dnsPolicy': {}
          'f:automountServiceAccountToken': {}
          'f:restartPolicy': {}
          'f:subdomain': {}
          'f:schedulerName': {}
          'f:terminationGracePeriodSeconds': {}
          'f:initContainers':
            .: {}
            'k:{"name":"nss-wrapper-init"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/tmp"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:command': {}
              'f:securityContext':
                .: {}
                'f:allowPrivilegeEscalation': {}
                'f:capabilities':
                  .: {}
                  'f:drop': {}
                'f:privileged': {}
                'f:readOnlyRootFilesystem': {}
                'f:runAsNonRoot': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:name': {}
            'k:{"name":"pgbackrest-log-dir"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/pgbackrest/repo1"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/tmp"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:command': {}
              'f:securityContext':
                .: {}
                'f:allowPrivilegeEscalation': {}
                'f:capabilities':
                  .: {}
                  'f:drop': {}
                'f:privileged': {}
                'f:readOnlyRootFilesystem': {}
                'f:runAsNonRoot': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:name': {}
          'f:shareProcessNamespace': {}
          'f:enableServiceLinks': {}
          'f:securityContext':
            .: {}
            'f:fsGroupChangePolicy': {}
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2023-08-18T05:54:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-08-18T09:00:18Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:initContainerStatuses': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.129.7.89"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: fo-ns
  ownerReferences:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: pg14-ha-patroni-repo-host
      uid: 5ddb1922-619d-4ee1-afe4-65d2d7c8e066
      controller: true
      blockOwnerDeletion: true
  labels:
    controller-revision-hash: pg14-ha-patroni-repo-host-5649697b68
    postgres-operator.crunchydata.com/cluster: pg14-ha-patroni
    postgres-operator.crunchydata.com/data: pgbackrest
    postgres-operator.crunchydata.com/pgbackrest: ''
    postgres-operator.crunchydata.com/pgbackrest-dedicated: ''
    statefulset.kubernetes.io/pod-name: pg14-ha-patroni-repo-host-0
spec:
  restartPolicy: Always
  initContainers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: pgbackrest-log-dir
      command:
        - bash
        - '-c'
        - mkdir -p /pgbackrest/repo1/log
      securityContext:
        capabilities:
          drop:
            - ALL
            - MKNOD
        privileged: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: repo1
          mountPath: /pgbackrest/repo1
        - name: tmp
          mountPath: /tmp
      terminationMessagePolicy: File
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-3
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: nss-wrapper-init
      command:
        - bash
        - '-c'
        - >
          export NSS_WRAPPER_SUBDIR=postgres CRUNCHY_NSS_USERNAME=postgres
          CRUNCHY_NSS_USER_DESC="postgres" 

          # Define nss_wrapper directory and passwd & group files that will be
          utilized by nss_wrapper.  The

          # nss_wrapper_env.sh script (which also sets these vars) isn't sourced
          here since the nss_wrapper

          # has not yet been setup, and we therefore don't yet want the
          nss_wrapper vars in the environment.

          mkdir -p /tmp/nss_wrapper

          chmod g+rwx /tmp/nss_wrapper

          NSS_WRAPPER_DIR="/tmp/nss_wrapper/${NSS_WRAPPER_SUBDIR}"

          NSS_WRAPPER_PASSWD="${NSS_WRAPPER_DIR}/passwd"

          NSS_WRAPPER_GROUP="${NSS_WRAPPER_DIR}/group"

          # create the nss_wrapper directory

          mkdir -p "${NSS_WRAPPER_DIR}"

          # grab the current user ID and group ID

          USER_ID=$(id -u)

          export USER_ID

          GROUP_ID=$(id -g)

          export GROUP_ID

          # get copies of the passwd and group files

          [[ -f "${NSS_WRAPPER_PASSWD}" ]] || cp "/etc/passwd"
          "${NSS_WRAPPER_PASSWD}"

          [[ -f "${NSS_WRAPPER_GROUP}" ]] || cp "/etc/group"
          "${NSS_WRAPPER_GROUP}"

          # if the username is missing from the passwd file, then add it

          if [[ ! $(cat "${NSS_WRAPPER_PASSWD}") =~
          ${CRUNCHY_NSS_USERNAME}:x:${USER_ID} ]]; then
              echo "nss_wrapper: adding user"
              passwd_tmp="${NSS_WRAPPER_DIR}/passwd_tmp"
              cp "${NSS_WRAPPER_PASSWD}" "${passwd_tmp}"
              sed -i "/${CRUNCHY_NSS_USERNAME}:x:/d" "${passwd_tmp}"
              # needed for OCP 4.x because crio updates /etc/passwd with an entry for USER_ID
              sed -i "/${USER_ID}:x:/d" "${passwd_tmp}"
              printf '${CRUNCHY_NSS_USERNAME}:x:${USER_ID}:${GROUP_ID}:${CRUNCHY_NSS_USER_DESC}:${HOME}:/bin/bash\n' >> "${passwd_tmp}"
              envsubst < "${passwd_tmp}" > "${NSS_WRAPPER_PASSWD}"
              rm "${passwd_tmp}"
          else
              echo "nss_wrapper: user exists"
          fi

          # if the username (which will be the same as the group name) is
          missing from group file, then add it

          if [[ ! $(cat "${NSS_WRAPPER_GROUP}") =~
          ${CRUNCHY_NSS_USERNAME}:x:${USER_ID} ]]; then
              echo "nss_wrapper: adding group"
              group_tmp="${NSS_WRAPPER_DIR}/group_tmp"
              cp "${NSS_WRAPPER_GROUP}" "${group_tmp}"
              sed -i "/${CRUNCHY_NSS_USERNAME}:x:/d" "${group_tmp}"
              printf '${CRUNCHY_NSS_USERNAME}:x:${USER_ID}:${CRUNCHY_NSS_USERNAME}\n' >> "${group_tmp}"
              envsubst < "${group_tmp}" > "${NSS_WRAPPER_GROUP}"
              rm "${group_tmp}"
          else
              echo "nss_wrapper: group exists"
          fi

          # export the nss_wrapper env vars

          # define nss_wrapper directory and passwd & group files that will be
          utilized by nss_wrapper

          NSS_WRAPPER_DIR="/tmp/nss_wrapper/${NSS_WRAPPER_SUBDIR}"

          NSS_WRAPPER_PASSWD="${NSS_WRAPPER_DIR}/passwd"

          NSS_WRAPPER_GROUP="${NSS_WRAPPER_DIR}/group"

          export LD_PRELOAD=/usr/lib64/libnss_wrapper.so

          export NSS_WRAPPER_PASSWD="${NSS_WRAPPER_PASSWD}"

          export NSS_WRAPPER_GROUP="${NSS_WRAPPER_GROUP}"

          echo "nss_wrapper: environment configured"
      securityContext:
        capabilities:
          drop:
            - ALL
            - MKNOD
        privileged: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: tmp
          mountPath: /tmp
      terminationMessagePolicy: File
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-3
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-p6j2w
  priority: 0
  subdomain: pg14-ha-patroni-pods
  schedulerName: default-scheduler
  enableServiceLinks: false
  terminationGracePeriodSeconds: 30
  shareProcessNamespace: true
  preemptionPolicy: PreemptLowerPriority
  nodeName: clab2054-q88qf-worker-z5qkq
  securityContext:
    seLinuxOptions:
      level: 's0:c27,c19'
    fsGroupChangePolicy: OnRootMismatch
  containers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: pgbackrest
      command:
        - pgbackrest
        - server
      livenessProbe:
        exec:
          command:
            - pgbackrest
            - server-ping
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: LD_PRELOAD
          value: /usr/lib64/libnss_wrapper.so
        - name: NSS_WRAPPER_PASSWD
          value: /tmp/nss_wrapper/postgres/passwd
        - name: NSS_WRAPPER_GROUP
          value: /tmp/nss_wrapper/postgres/group
      securityContext:
        capabilities:
          drop:
            - ALL
            - MKNOD
        privileged: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: pgbackrest-server
          readOnly: true
          mountPath: /etc/pgbackrest/server
        - name: repo1
          mountPath: /pgbackrest/repo1
        - name: pgbackrest-config
          readOnly: true
          mountPath: /etc/pgbackrest/conf.d
        - name: tmp
          mountPath: /tmp
      terminationMessagePolicy: File
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-3
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: pgbackrest-config
      command:
        - bash
        - '-ceu'
        - '--'
        - >-
          monitor() {

          exec {fd}<> <(:)

          until read -r -t 5 -u "${fd}"; do
            if
              [ "${filename}" -nt "/proc/self/fd/${fd}" ] &&
              pkill -HUP --exact --parent=0 pgbackrest
            then
              exec {fd}>&- && exec {fd}<> <(:)
              stat --dereference --format='Loaded configuration dated %y' "${filename}"
            elif
              { [ "${directory}" -nt "/proc/self/fd/${fd}" ] ||
                [ "${authority}" -nt "/proc/self/fd/${fd}" ]
              } &&
              pkill -HUP --exact --parent=0 pgbackrest
            then
              exec {fd}>&- && exec {fd}<> <(:)
              stat --format='Loaded certificates dated %y' "${directory}"
            fi
          done

          }; export directory="$1" authority="$2" filename="$3"; export -f
          monitor; exec -a "$0" bash -ceu monitor
        - pgbackrest-config
        - /etc/pgbackrest/server
        - /etc/pgbackrest/conf.d/~postgres-operator/tls-ca.crt
        - /etc/pgbackrest/conf.d/~postgres-operator_server.conf
      securityContext:
        capabilities:
          drop:
            - ALL
            - MKNOD
        privileged: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: pgbackrest-server
          readOnly: true
          mountPath: /etc/pgbackrest/server
        - name: pgbackrest-config
          readOnly: true
          mountPath: /etc/pgbackrest/conf.d
        - name: tmp
          mountPath: /tmp
      terminationMessagePolicy: File
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-3
  hostname: pg14-ha-patroni-repo-host-0
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          postgres-operator.crunchydata.com/cluster: pg14-ha-patroni
        matchExpressions:
          - key: postgres-operator.crunchydata.com/data
            operator: In
            values:
              - postgres
              - pgbackrest
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          postgres-operator.crunchydata.com/cluster: pg14-ha-patroni
        matchExpressions:
          - key: postgres-operator.crunchydata.com/data
            operator: In
            values:
              - postgres
              - pgbackrest
  automountServiceAccountToken: false
  serviceAccount: default
  volumes:
    - name: pgbackrest-server
      projected:
        sources:
          - secret:
              name: pg14-ha-patroni-pgbackrest
              items:
                - key: pgbackrest-repo-host.crt
                  path: server-tls.crt
                - key: pgbackrest-repo-host.key
                  path: server-tls.key
                  mode: 384
        defaultMode: 420
    - name: repo1
      persistentVolumeClaim:
        claimName: pg14-ha-patroni-repo1
    - name: pgbackrest-config
      projected:
        sources:
          - configMap:
              name: pg14-ha-patroni-pgbackrest-config
              items:
                - key: pgbackrest_repo.conf
                  path: pgbackrest_repo.conf
                - key: config-hash
                  path: config-hash
                - key: pgbackrest-server.conf
                  path: ~postgres-operator_server.conf
          - secret:
              name: pg14-ha-patroni-pgbackrest
              items:
                - key: pgbackrest.ca-roots
                  path: ~postgres-operator/tls-ca.crt
                - key: pgbackrest-client.crt
                  path: ~postgres-operator/client-tls.crt
                - key: pgbackrest-client.key
                  path: ~postgres-operator/client-tls.key
                  mode: 384
        defaultMode: 420
    - name: tmp
      emptyDir:
        sizeLimit: 16Mi
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
status:
  containerStatuses:
    - restartCount: 48
      started: false
      ready: false
      name: pgbackrest
      state:
        terminated:
          exitCode: 95
          reason: Error
          startedAt: '2023-08-18T09:36:06Z'
          finishedAt: '2023-08-18T09:36:06Z'
          containerID: >-
            cri-o://4813b81fe1c242b6f0124a87052d77954f11555b8b98f65f13792af68af3b63f
      imageID: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:c9d36ed633e77611c2198acd423ce1eba5a0d1695ce38a1d8be85eb2360a66c0
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-3
      lastState:
        terminated:
          exitCode: 95
          reason: Error
          startedAt: '2023-08-18T09:30:54Z'
          finishedAt: '2023-08-18T09:30:55Z'
          containerID: >-
            cri-o://f8656d66f479d5bf9785c50efcb36f36bfa9935d14e7b851fe86b1555fe29c5a
      containerID: 'cri-o://4813b81fe1c242b6f0124a87052d77954f11555b8b98f65f13792af68af3b63f'
    - restartCount: 0
      started: true
      ready: true
      name: pgbackrest-config
      state:
        running:
          startedAt: '2023-08-18T05:54:57Z'
      imageID: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:c9d36ed633e77611c2198acd423ce1eba5a0d1695ce38a1d8be85eb2360a66c0
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-3
      lastState: {}
      containerID: 'cri-o://a69f229ea83382dd186c39aa31c92981e354336a75db87192561daee935529b3'
  qosClass: BestEffort
  podIPs:
    - ip: 10.129.7.89
  podIP: 10.129.7.89
  hostIP: 10.11.132.40
  startTime: '2023-08-18T05:54:43Z'
  initContainerStatuses:
    - name: pgbackrest-log-dir
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2023-08-18T05:54:55Z'
          finishedAt: '2023-08-18T05:54:55Z'
          containerID: >-
            cri-o://2b448d013fec3d73e0d3fa65358a25e05faebc2d063b0d20480c7941f82bfa28
      lastState: {}
      ready: true
      restartCount: 0
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-3
      imageID: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:c9d36ed633e77611c2198acd423ce1eba5a0d1695ce38a1d8be85eb2360a66c0
      containerID: 'cri-o://2b448d013fec3d73e0d3fa65358a25e05faebc2d063b0d20480c7941f82bfa28'
    - name: nss-wrapper-init
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2023-08-18T05:54:55Z'
          finishedAt: '2023-08-18T05:54:55Z'
          containerID: >-
            cri-o://b01051fd70e67ffa32bdbbf86665c970641375b0946a903655f23a0055b5a1ca
      lastState: {}
      ready: true
      restartCount: 0
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-3
      imageID: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:c9d36ed633e77611c2198acd423ce1eba5a0d1695ce38a1d8be85eb2360a66c0
      containerID: 'cri-o://b01051fd70e67ffa32bdbbf86665c970641375b0946a903655f23a0055b5a1ca'
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-08-18T05:54:56Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2023-08-18T09:00:17Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [pgbackrest]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2023-08-18T09:00:17Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [pgbackrest]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-08-18T05:54:43Z'
  phase: Running
`

### Environment

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`
- Platform Version: (e.g. `4.11.46``)
- PGO Image Tag: (e.g. `ubi8-5.3.1-0`)
- Postgres Version (e.g. `14.8)`
- Storage: (e.g. `ocs-storagecluster-cephfs`)

**Comment by desorenp** [comment]
Any idea how to correct the scc manually?

**Comment by ValClarkson** [comment]
Hi @desorenp 

You should be able to edit the scc `oc edit scc <scc name>` if you have permissions on the openshift env to do so.
