### ISSUE TITLE
is it possible to use postgresql+asyncpg in the connection string?

### ISSUE THREAD

**Issue by webcoderz** [CrunchyData/postgres-operator#3713]
hi i love PGO and am trying to use it in another project and was wondering is it possible to use postgresql+asyncpg in the connection string?

im setting my dtabase url env var this

```
- name: DATABASE_URL
            valueFrom: { secretKeyRef: { name: {{.Values.global.postgres.host }}-pguser-{{.Values.global.postgres.user }}, key: uri } }
```

**Comment by ValClarkson** [comment]
Hi @webcoderz 

What deployment method are you using?  would you also be able to provide your manifest? I believe the [user management](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/user-management) documentation and our [connect to application](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart#connect-an-application) example will help you with what you are trying to accomplish.

**Comment by jmckulk** [comment]
Since we haven't gotten an update on this issue in a while, I'm going to close it. If you still need help and can provide the requested information, feel free to re-open.
