### ISSUE TITLE
Operator malfunctions when creating/performing actions on clusters

### ISSUE THREAD

**Issue by Tal-987** [CrunchyData/postgres-operator#3718]
## Overview

We are using the postgres operator for a few years now, and lately have been experiencing some problems.

When creating a new cluster, the workflow stops midway and doesn't complete the creation.
Also when trying to preform other actions on existing clusters, such as scaling or promoting a standby, the process does not work properly/nothing happens at all.

## Environment

- Platform: OpenShift
- Platform Version: 4.8.0
- PGO Image Tag: 4.6.1
- Postgres Version: 12.6
- Storage: openshifts pvs & s3

### EXPECTED

When running the pgo create cluster command the cluster is fully created properly with no other problems appearing.
Also when trying to scale a cluster a pgreplica and deployment are created.

### ACTUAL

When trying to create a cluster the following objects are created in the process:
- The pgcluster
- The primary service
- The pvcs
- The pgbackrest deployment and it scales to 1 
- The clusters' primary deployment but it doesn't scale to 1 (stays 0/0)

The following objects are not created in the process:
- The backrest repo in s3
- The main configmap (pgha-config)
- All other objects that are supposed to be created after the primary pod and backrest pod are ready 
(Such as replicas)

Meaning the cluster never gets fully deployed and is not useable. 

The operator also does not work properly when trying to scale an existing cluster (the pgreplica is created but the deployment isn't) or when trying to promote a standby cluster (it just ignores the promotion command).

## Additional Information

Up untill a month ago everything worked properly
And we had no problem.

We are using the same version of operator on a different site and it shows no problems.
Also when trying to use the problematic operator in a different namespace on the same site, it works just fine(the clusters are fully created with no additional problems).

We tried to increase the operator resources but it did not help.
There is also no problem of free resourcers/quotas in this namespace.

There is no specific error that we could find in the operator logs/namespace events(we looked through all 4 of the containers and compared the output to the outputs from the working operator).

We would appreciate any help regarding this problem.

Also if you could provide a more descriptive explanation of the process happenning when a new cluster is deoployed, so that we can look for the specific moment the operator stopped working on the creation of the cluster.

**Comment by ValClarkson** [comment]
Hi @Tal-987,
Sorry you are running into issues. Looks like you are on a very old version of PGO we suggest you upgrade to PGO v5.  For information about about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation: https://access.crunchydata.com/documentation/postgres-operator/latest/. If you need immediate support for PGO v4 you can reach out to [info@crunchydata.com](mailto:info@crunchydata.com) if you would like to discuss your use case/needs further.
