### ISSUE TITLE
Continuous Restarts of PGO Pod

### ISSUE THREAD

**Issue by ksgnextuple** [CrunchyData/postgres-operator#3744]
## Overview

Hi all we are facing an issue where the postgres operator pod keeps restarting. We have 2 postgres operators on the same cluster in different namespaces. Both are of the same version. But one of them keeps restarting.

## Environment

- Platform: Kubernetes AKS
- Platform Version : 1.26.3
- PGO Image Tag: ubi8-5.4.1-0
- Postgres Version: 15

## Logs

E1013 07:14:23.236500       1 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PGUpgrade: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:kong:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope

panic: failed to wait for postgrescluster caches to sync: timed out waiting for cache to be synced
goroutine 1 [running]:
main.assertNoError(...)
	github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:44
main.main()
	github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:122 +0x513

**Comment by dsessler7** [comment]
Hello @ksgnextuple! You cannot have multiple postgres operators running in a k8s cluster if any of them are cluster-scoped. You can either have 1 cluster-scoped postgres operator OR n (1-many) single-namespace-scoped postgres operators running in a cluster (assuming each single-namespace-scoped PGO is running in its own namespace). If you need guidance on setting PGO up to be single-namespace-scoped, I recommend checking out the following documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/installation/kustomize#installation-mode
