### ISSUE TITLE
How to create replicas

### ISSUE THREAD

**Issue by matzik12** [CrunchyData/postgres-operator#3763]
Hello,
I am using pgo for a while and noticed that the replicas that i add to the patroni cluster are configured to be created using pgbasebackup. this is a problem for me because my standby was down and i had backup from standby only for a while. Now my cluster has no backup from last week and i want to create a new replica using pg_base_backup, but it doesnt work because the configuration of the "create_replica_method" in patroni.yml . this makes patroni use only pgbackrest to create a replica. Hope I have missed a feature and it already exists. 
please help me with this situation.
Thank you!
Ziv

**Comment by jmckulk** [comment]
Hey @matzik12, were you able to get this working?

**Comment by matzik12** [comment]
@jmckulk yes, like the comment above you said. Created new backup and initialized the replicas again. It worked.
I asked it cause i didnt want to fix my backups but didnt find other option :(
