### ISSUE TITLE
PGUpgrade. Upgrade the database from version 15 to version 16 error

### ISSUE THREAD

**Issue by ivanovpavel1983** [CrunchyData/postgres-operator#3792]
When we try to update the database from version 15 to version 16, we get the error:

*****************************************************************************************
Performing Consistency Checks
-----------------------------
Checking cluster versions                                     ok

*failure*
Consult the last few lines of "/pgdata/pg16/pg_upgrade_output.d/20231129T083313.457/log/pg_upgrade_server.log" for
the probable cause of the failure.

**connection to server on socket "/pgdata/.s.PGSQL.50432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?**

could not connect to source postmaster started with the command:
"/usr/pgsql-15/bin/pg_ctl" -w -l "/pgdata/pg16/pg_upgrade_output.d/20231129T083313.457/log/pg_upgrade_server.log" -D "/pgdata/pg15" -o "-p 50432 -b  -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/pgdata'" start

*****************************************************************************************
pg_upgrade_server.log
-----------------------------------------------------------------
  pg_upgrade run on Wed Nov 29 08:33:13 2023
-----------------------------------------------------------------

command: "/usr/pgsql-15/bin/pg_ctl" -w -l "/pgdata/pg16/pg_upgrade_output.d/20231129T083313.457/log/pg_upgrade_server.log" -D "/pgdata/pg15" -o "-p 50432 -b  -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/pgdata'" start >> "/pgdata/pg16/pg_upgrade_output.d/20231129T083313.457/log/pg_upgrade_server.log" 2>&1
waiting for server to start....2023-11-29 08:33:13.623 UTC [107] LOG:  pgaudit extension initialized
 stopped waiting
pg_ctl: could not start server
Examine the log output.
*****************************************************************************************

Looks like a bug https://github.com/sclorg/postgresql-container/issues/362
Is it possible to set the POSTGRESQL_UPGRADE_PGUPGRADE_OPTIONS option in the PGUpgrade CRD-entity?

**Comment by dsessler7** [comment]
Hello @ivanovpavel1983,

Are you still experiencing this issue? What version of CPK are you running (specifically interested in the tags for PGO and crunchy-upgrade)?

Can you send full upgrade logs? Postgres and PGO logs?

**Comment by ivanovpavel1983** [comment]
Hello @dsessler7.
Operator/Upgrade version is postgres-operator-upgrade:ubi8-5.3.2-0.
PosgreSQL version is crunchy-postgres:ubi8-15.3-0.
I can send full upgrade logs on Monday.
Have a nice day.

**Comment by ivanovpavel1983** [comment]
Fixed in pgo 5.5.0
