### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by mausch** [CrunchyData/postgres-operator#3793]
https://github.com/CrunchyData/postgres-operator/releases currently says the latest release is 4.7.10

https://access.crunchydata.com/documentation/postgres-operator/latest currently says the latest release is 5.4

It seems there are some missing releases on Github? This confuses users.

**Comment by andrewlecuyer** [comment]
Hi @mausch, thanks for reaching out!

Regarding your question, release see the following FAQ:

[Where are the release tags for PGO v5?](https://access.crunchydata.com/documentation/postgres-operator/latest/faq#where-are-the-release-tags-for-pgo-v5)

Additionally, we encourage you to our new Discord server, where you can get insight into new releases via our [releases-and-updates](https://discord.com/channels/1068276526740676708/1103388174685847692) channel.  Here is an invite to join, and we look forward to seeing you out there!

[Crunchy Community Discord Invite](https://discord.gg/a7vWKG8Ec9)
