### ISSUE TITLE
Back-off pulling image "registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.2.7-0"

### ISSUE THREAD

**Issue by jesmy-geon** [CrunchyData/postgres-operator#3795]
I was installing postgres operator version 5.2.7 as per the documentation provided. I need this specific version 5.2.7 because we have our on prem environment in kubernetes 1.21 and cloud environment in 1.24 and 5.2.7 is the best fit.

Unfortunately when I am installing it after changing the controllerImages:
  cluster: registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.2.7-0 am unbale to spin up the pod it says,
  
  Back-off pulling image "registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.2.7-0"

![image](https://github.com/CrunchyData/postgres-operator/assets/47318544/de3a9cfa-6649-4c26-80eb-4be9381a4c2a)

I tried many methods but still its the same error throwing out. Can some one help me find the right image ?

**Comment by jesmy-geon** [comment]
anybody here to help me ?

**Comment by benjaminjb** [comment]
Hello, @jesmy-geon. I'm sorry you're running into this problem, and I've created an action on our side to help clarify what is available via the Developer Program.

To further clarify here, we make the two most recent versions of Crunchy Postgres for Kubernetes available via the Crunchy Developer Program. Today, that includes v5.5.x and v5.4.x, as shown on the [Supported Platforms Page](https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms).

I'm sorry for the confusion about what's available, and if you want to discuss your use case more, please contact [info@crunchydata.com](mailto:info@crunchydata.com) to see if we can help further.
