### ISSUE TITLE
Missing Docker Hub Image for 3.3.0-rc3

### ISSUE THREAD

**Issue by KrzysztofWloch** [CrunchyData/postgres-operator#380]
With release of 3.3.0 - Release Candidate 3 there should be image on docker hub:
https://hub.docker.com/r/crunchydata/postgres-operator/tags/ with tag "centos7-3.3.0-rc2"

**Comment by gadelkareem** [comment]
Still image centos7-3.3.0 not found

**Comment by jmccormick2001** [comment]
final images should land tomorrow.

**Comment by cahoonpwork** [comment]
3.3.0 final is out now.
