### ISSUE TITLE
Allow annotations to be added to services

### ISSUE THREAD

**Issue by knpwrs** [CrunchyData/postgres-operator#3831]
## Overview

Right now annotations can be added to postgres instances. It would be great if we could add annotations to postgres services.

## Use Case

[Tailscale has a Kubernetes operator](https://tailscale.com/kb/1236/kubernetes-operator) that lets you expose services in your cluster as machines on your tailnet (TailScale Wireguard VPN) simply by adding an annotation to the service.

## Desired Behavior

Adding the following metadata should expose my Postgres cluster as a machine over tailscale:

```
annotations:
  tailscale.com/expose: "true"
```

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: Kubernetes
  - Platform Version: 1.27.4

## Additional Information

Question: given the documentation [here](https://tailscale.com/kb/1236/kubernetes-operator), would any other methods work for exposing a postgres cluster over Tailscale (even if it involves creating a new object).

**Comment by dsessler7** [comment]
Hello @knpwrs! You can add annotations to [the primary service](https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.5.x/postgrescluster#postgresclusterspecservicemetadata), the cluster-scoped [pgAdmin service](https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.5.x/postgrescluster#postgresclusterspecuserinterfacepgadminservicemetadata), and the [pgBouncer service](https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.5.x/postgrescluster#postgresclusterspecproxypgbouncerservicemetadata) via the postgrescluster spec as seen in the linked documentation. Cheers!
