### ISSUE TITLE
Large memory usage on the replica pod

### ISSUE THREAD

**Issue by Eric-zch** [CrunchyData/postgres-operator#3838]
## Overview

I have a Crunchy Postgres cluster on Openshift, and the cluster has a master pod and a replica pod, after the cluster is up for some days, I found the memory usage of the replica pod is greater than the memory usage of the master pod, do you know why?
Thank you.

## Environment
- Platform: OpenShift
- Platform Version: 4.10.53
- PGO Image Tag: ubi8-5.3.1-0
- Postgres Version: ubi8-14.6-2
- Pgbackrest: 2.43

<img width="1684" alt="Screenshot 2024-02-06 at 15 53 27" src="https://github.com/CrunchyData/postgres-operator/assets/67849191/ec71daf5-a1e1-4cac-b92c-01e5726a7667">

**Comment by tjmoore4** [comment]
Hi @Eric-zch. To start, is the picture you provided from the replica Pod? If so, can you provide the primary Pod as well.
Also, could you provide a copy of your PostgresCluster manifest?

**Comment by tjmoore4** [comment]
Also, one other question that might be helpful. Do you notice the memory usage continually goes up, or does it go up to a point and then plateau? If there's anything else about your environment that might be useful to know, please feel free to add that as well. Thanks!

**Comment by Eric-zch** [comment]
Hi @tjmoore4 
I did some investigation, and it seems some team members in our team did a lot of queries on the replica pod, which maybe the cause of the problem.
