### ISSUE TITLE
Releases: upload individual `pgo` binaries separately

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/postgres-operator#384]
Currently we package all the `pgo` binaries for linux, osx and windows in a tar ball.  It would be convenient if each of these binaries were uploaded separately so install instructions don't require downloading a tarball, extracting and using the proper architecture binary (think installation documentation).

**Comment by cahoonpwork** [comment]
@jasonodonnell I talked to John about this on Monday and will keep you updated on progress.

**Comment by jmccormick2001** [comment]
@crunchyjohn   John, I added you on this one just as a reminder to see if you can add this to the release processing instead of the current manual process.  thanks.
