### ISSUE TITLE
registry.developers.crunchydata.com not availible anymore..

### ISSUE THREAD

**Issue by bap-dev** [CrunchyData/postgres-operator#3859]
curl -L https://registry.developers.crunchydata.com and any other subdirs like /crunchydata/crunchy-postgres:ubi8-14.11-0
leads to:
{ "errors":[{"code":"404","message":"This container version is no longer available from the Crunchy Data Developer Program. For information on accessing these containers, please contact info@crunchydata.com." }]}
so k3s can't pull an image anymore...

please help!

**Comment by andrewlecuyer** [comment]
@bap-dev, sorry to hear you are having trouble!

As shown on the [Supported Platforms page](https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms) within the Crunchy Postgres for Kubernetes documentation, only the latest two Postgres release are available through the [Crunchy Data Developer Program](https://www.crunchydata.com/developers/terms-of-use).

https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms

However, please note that prior Postgres 14 (e.g. v14.10) builds are still available via the developer registry.

```bash
registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.10-0
```

This image should get you up-and-running.  You the can leverage the major Postgres version upgrade functionality within Crunchy Postgres for Kubernetes to get onto one the latest Postgres releases available via the Developer program:

https://access.crunchydata.com/documentation/postgres-operator/latest/guides/major-postgres-version-upgrade

I also recommend subscribing to the Developer program mailing list via the following page for the latest updates about the availability of Postgres via the Developer Program:

https://www.crunchydata.com/developers/download-postgres/containers

Hope this helps!

**Comment by andrewlecuyer** [comment]
Considering most of the conversation for this is occurring in https://github.com/CrunchyData/postgres-operator-examples/issues/255, I'm proceeding with closing this issue.

Feel free to reach out if you have any additional questions!
