### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by k1ng440** [CrunchyData/postgres-operator#386]
**I'm submitting a ...**

 
 - [x] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
postgres-operator-7b6ccdf594-zs8p5 operator E1005 16:39:16.105698       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/clustercontroller.go:80: Failed to list *v1.Pgcluster: Unauthorized
postgres-operator-7b6ccdf594-zs8p5 operator E1005 16:39:16.354019       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/podcontroller.go:77: Failed to list *v1.Pod: Unauthorized
postgres-operator-7b6ccdf594-zs8p5 operator E1005 16:39:16.471929       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/jobcontroller.go:78: Failed to list *v1.Job: Unauthorized
postgres-operator-7b6ccdf594-zs8p5 operator E1005 16:39:17.108587       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/clustercontroller.go:80: Failed to list *v1.Pgcluster: Unauthorized
postgres-operator-7b6ccdf594-zs8p5 operator E1005 16:39:17.356653       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/podcontroller.go:77: Failed to list *v1.Pod: Unauthorized
postgres-operator-7b6ccdf594-zs8p5 operator E1005 16:39:17.474166       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/jobcontroller.go:78: Failed to list *v1.Job: Unauthorized
postgres-operator-7b6ccdf594-zs8p5 operator E1005 16:39:18.112559       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/clustercontroller.go:80: Failed to list *v1.Pgcluster: Unauthorized
postgres-operator-7b6ccdf594-zs8p5 operator E1005 16:39:18.359997       1 reflector.go:205] github.com/crunchydata/postgres-operator/controller/podcontroller.go:77: Failed to list *v1.Pod: Unauthorized

**If the current behavior is a bug, please provide the steps to reproduce:**
make setup
make installrbac
make deployoperator

**What is the expected behavior?**
it should be available to be available to query kubernetes

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System: windows 10 WSL
 - Container Image Tag: centos7-10.5-2.1.0
 - Operator Version: 3.3.0-rc4
 - PostgreSQL Version: 10
 - Platform (Docker, Kubernetes, OpenShift): Kubernetes
 - Platform Version: 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jmccormick2001** [comment]
thanks, I'm trying to recreate this one...in your environment, what did you use for installing Kube?  what kube user are you using when you create the rbac resources?  thx

**Comment by k1ng440** [comment]
we are using GKE. kubectl's user was configured with the `gcloud` cli

**Comment by cahoonpwork** [comment]
I installed on GKE today and didn't get this issue with Operator 3.3.0-rc4.  Perhaps you need to setup the cluster-admin role?

kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user $(gcloud config get-value account)

**Comment by k1ng440** [comment]
hello, 
i already have clusterrolebinding but still no luck
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "cluster-admin-binding" already exists

**Comment by jmccormick2001** [comment]
Hi, is this still an issue?
