### ISSUE TITLE
how to create groups or run SQL files using crunchy postgres operator yaml without deleting the Postgres cluster

### ISSUE THREAD

**Issue by Naveen-Kamagani** [CrunchyData/postgres-operator#3862]
1. How to create groups using crunchy Postgres operator yaml? There is no documentation.
2. How to run a SQL file after creating users using Postgres operator yaml CR(not the initdb sql file). Because initdb sql file will only executed after deleting the cluster and recreating it.
Example - I have modified SQL config map and ran "kubectl apply -f postgres.yaml" . It did not add the changes added in sql config map. Also tried deleting the configmap and recreating it, still the same.

Request someone to help on this issue ASAP.

**Comment by andrewlecuyer** [comment]
Hi @Naveen-Kamagani!

Regarding your first question, we do not currently expose functionality for Postgres group creation via the PostgresCluster API.  You can therefore leverage the init SQL for this.

As for your second question, the init SQL is intended to be run at cluster-bootstrap only.   More specifically, the [Database Initialization SQL docs](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/day-two/customize-cluster#database-initialization-sql) recommend removing this setting post-cluster initialization:

> Now that databaseInitSQL is defined in your cluster status, verify database objects have been created as expected. After verifying, we recommend removing the spec.databaseInitSQL field from your spec. Removing the field from the spec will also remove databaseInitSQL from the cluster status.

Therefore, this file is not intended to be updated or re-run post-cluster initialization.
