### ISSUE TITLE
Create Openshift Service + Route on PGAdmin resource deployment

### ISSUE THREAD

**Issue by gr4ytech** [CrunchyData/postgres-operator#3875]
## Overview

When creating a PGAdmin Resource with PGO, a Kubernetes service and Openshift/OKD route should be created if ingress is selected.

## Use Case

In the current version of PGO (v5.5.1 at time of writing), when a PGAdmin resource is created in a namespace, there is no Kubernetes service or Openshift route created, making the PGAdmin resource unreachable by default. An additional option so that an ingress controller can be easily made (or selected) would make the PGAdmin resource more closely follow previously defined behavior for older postgres clusters. (UserInterface.PGAdmin in the cluster spec has a service created by default) 

## Desired Behavior

There is an option to allow ingress when creating the PGAdmin resource. When a PGAdmin resource is created, a hostname for an openshift route can be entered or generated if ingress is enabled. After the resource has been created, a Kubernetes service and route are automatically created, allowing external access via the ingress controller.

## Environment

This is an Openshift cluster running on top of Openstack. Our Openshift environment specs is as followed:

- Platform: ``Openshift/OKD``
- Platform Version: ``4.15.0``
- PGO Image Tag: ``ubi8-5.5.1-0``
- Postgres Version: ``16``
- Storage: ``standard-csi`` (Openstack Cinder)
- Number of Postgres clusters: ``1``

**Comment by andrewlecuyer** [comment]
Hi @gr4ytech, just wanted to say thanks for your feedback and the detailed enhancement request!

A story has been added to our backlog for this.
