### ISSUE TITLE
Recreate pgbackrest stanza after lost backrest-shared-repo storage, please help!

### ISSUE THREAD

**Issue by mrain32** [CrunchyData/postgres-operator#3879]
My storage VM for storing backrest-shared-repo was lost. I replaced it with a new VM and configured the persistent volume to the new one, while other crunchy-postgres pods and storages are still working (on other VMs). Now I can't create backup for the cluster:
Running backrest backup got this error:
```
time="" level=info msg="pgo-backrest starts"
time="" level=info msg="debug flag set to false"
time="" level=info msg="backrest backup command requested"
time="" level=info msg="command to execute is [pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=[IP Address1] --db-path=/pgdata/app-cluster-lyuy]"
time="" level=info msg="command is pgbackrest backup --stanza=db --type=full --repo1-retention-full=3 --db-host=[IP Address1] --db-path=/pgdata/[primary pod name] "
time="" level=error msg="command terminated with exit code 41"
time="" level=info msg="output=[]"
time="" level=info msg="stderr=[ERROR: [041]: unable to load info file '/backrestrepo/[cluster-name]-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/[cluster-name]-backrest-shared-repo/backup/db/backup.info.copy':\n       FileOpenError: unable to open file '/backrestrepo/[cluster-name]-backrest-shared-repo/backup/db/backup.info' for read: [116] Stale file handle\n       FileOpenError: unable to open file '/backrestrepo/[cluster-name]-backrest-shared-repo/backup/db/backup.info.copy' for read: [116] Stale file handle\n       HINT: backup.info cannot be opened and is required to perform a backup.\n       HINT: has a stanza-create been performed?\n]"
time="2024-03-28T17:30:05Z" level=error msg="command terminated with exit code 41"
```

I tried to re-create stanza by log in to the backrest-shared-repo-xxx-xxx pod on kubernetes, but got this error:
```
[pgbackrest@[cluster-name]-backrest-shared-repo-xxx-xxx /]$ pgbackrest check
ERROR: [055]: raised from remote-0 protocol on [cluster-name]: unable to open missing file '/pgdata/[cluster-name]/global/pg_control' for read
```

Please help! How to recreate stanza? Now our crunchy-postgres cluster running without backing up :(.

- Platform: (`Kubernetes`)
- Platform Version: (1.19.3)
- PGO Image Tag: (pgo-version=4.5.0, pgo-backrest-repo:centos7-4.5.0)
- Postgres Version (PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit)
- Storage: nfs

**Comment by andrewlecuyer** [comment]
Hi @mrain32!  Sorry to hear you are having trouble.

Considering you are using versions of PGO and Kubernetes that are no longer supported, options for troubleshooting your issue via public support forums are limited (as you can see on our [Supported Platforms page](https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms), v4.5 is no longer supported).  You can try the [Crunchy Discord server](https://discord.gg/a7vWKG8Ec9) as well, though I suspect you will get a similar result/response.

I therefore recommend reaching out via info@crunchydata.com to discuss your use-case and issue in further detail, along with options to get you back up and running.

**Comment by mrain32** [comment]
> Hi @mrain32! Sorry to hear you are having trouble.
> 
> Considering you are using versions of PGO and Kubernetes that are no longer supported, options for troubleshooting your issue via public support forums are limited (as you can see on our [Supported Platforms page](https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms), v4.5 is no longer supported). You can try the [Crunchy Discord server](https://discord.gg/a7vWKG8Ec9) as well, though I suspect you will get a similar result/response.
> 
> I therefore recommend reaching out via [info@crunchydata.com](mailto:info@crunchydata.com) to discuss your use-case and issue in further detail, along with options to get you back up and running.

Thank you for your information!
Best Regards.
