### ISSUE TITLE
How to enable debug mode in postgres

### ISSUE THREAD

**Issue by Alansyf** [CrunchyData/postgres-operator#3882]
### Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version: v1.26.13
- PGO Image Tag: ubi8-5.5.1-0
- Postgres Version 16
- Storage: hostpath

Hi Team, 
This is very generic question, I use the pgbouncer from your example high-avalibility
`registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.21-3`
with two replica. 

I understand one is master and the other is replica. 

I want to know how the traffic will go to my backend postgres cluster, for read requests through the pgbouncer, the requests will send to:
replica pod only. 
master pod only. 
or round robin? 

Thus I would like to enable the debug mode in my postgres, so each request (select statement I can see in log), but i searched  around didn't find how can i put under PostgresCluster CRD.

**Comment by ValClarkson** [comment]
Hi @Alansyf Sorry you are having issues.  A helpful doc to reference is located [here](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/day-two/customize-cluster#custom-postgres-configuration) this will enable you to change/tweak postgres settings.  Another good reference is this [blog](https://www.crunchydata.com/blog/log-export-examples-using-crunchy-postgres-for-kubernetes) which will give you an example to change logging if you wish to do so.  I also found this [doc](https://www.pgbouncer.org/faq.html#how-to-load-balance-queries-between-several-servers) to be helpful with routing information for pgbouncer.

**Comment by Alansyf** [comment]
Hi @ValClarkson , Thanks for your useful docs. 
I read and find the solution turn on debug and find the configuration finally. 

So in pgbouncer.ini, there is 

[databases]
    * = host=mlflow-pg-ha-primary port=5432

so everything are going to the primary. 

Does it mean, pgbouncer actually is not the one can help split write and read traffic. (Write to master and read to slvve)

**Comment by ValClarkson** [comment]
Hi @Alansyf, I'm glad the doc's helped you turn on debugging!  Did you happen to look at this [doc](https://www.pgbouncer.org/faq.html#how-to-load-balance-queries-between-several-servers)?  It talks about how to load balance via an external tool with pgbouncer.

**Comment by Alansyf** [comment]
Thanks, i understand now, need another tool to support LB.
