### ISSUE TITLE
How to limit or prevent the impact

### ISSUE THREAD

**Issue by clyang82** [CrunchyData/postgres-operator#3889]
## Questions

My case is that I have five components to share the same postgres (installed by crunchy operator). I may choose single DB with separate schema or separate DB. From my experience, one component is using too many resources. How could we prevent or limit the impact from affecting performance for others? Thanks for your advice.

### Environment

Please provide the following details:

- Platform: (`OpenShift`)
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `ubi8-5.x.y-0`)
- Postgres Version (e.g. `15`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

**Comment by ValClarkson** [comment]
Hi @clyang82, Thanks for submitting this issue but this question may be more suited to our [PGO project community discord](https://discord.gg/a7vWKG8Ec9), that being said have you considered 5 postgres clusters instead of a shared postgres cluster?

**Comment by clyang82** [comment]
Thanks @ValClarkson for introducing the discord. Yes. for sure we can have 5 postgres clusters. but considering the expense, I am looking for if postgres cluster can be shared.

**Comment by ValClarkson** [comment]
HI @clyang82 I see you reached out in discord, closing this issue
