### ISSUE TITLE
Add the postgrescluster helm chart to the OCI developer registry

### ISSUE THREAD

**Issue by Inigo4562** [CrunchyData/postgres-operator#3910]
## Overview

Currently only the postgres operator helm chart can be found in the OCI developer registry (oci://registry.developers.crunchydata.com/crunchydata/pgo). It would be great to also be able pull the [postgrescluster helm chart](https://github.com/CrunchyData/postgres-operator-examples/tree/main/helm/postgres) from that same registry.

## Use Case

This will allow testing with this chart without having to clone the examples github repository.

## Desired Behavior

Download the postgrescluster chart with the following command:
```
helm pull oci://registry.developers.crunchydata.com/crunchydata/postgrescluster
```

**Comment by benjaminjb** [comment]
Hey @Inigo4562, thanks for your thoughts on this and I'm adding a +1 to our backlog ticket about this. I'm going to close this issue but only because we have another open issue where we're tracking this topic:

https://github.com/CrunchyData/postgres-operator/issues/3641

**Comment by spatterIight** [comment]
This would be a much appreciated addition
