### ISSUE TITLE
Install Decoderbufs Extension

### ISSUE THREAD

**Issue by sfisli** [CrunchyData/postgres-operator#3914]
Hello, is there anyway to install a new extension (not default)? i want to install decoderbufs but i didn't find the right way to do it.

**Comment by andrewlecuyer** [comment]
The instructions to install an additional extension really depend on the specific extension.   More specifically, the installation requirements, dependencies, steps and more can vary greatly between various Postgres extensions.

Therefore, if you require an extension the is not currently included in CPK, I recommend reaching out to info@crunchydata.com to further discuss your specific needs.

**Comment by tjmoore4** [comment]
Since we haven't heard back on this issue for some time, I am closing this issue. If you need further assistance, feel free to re-open this issue or ask a question in our [Discord server](https://discord.com/invite/a7vWKG8Ec9).

**Comment by Siradjedd** [comment]
i sent a mail to the mail but no answer
