### ISSUE TITLE
Is TLS Rotation Supported?

### ISSUE THREAD

**Issue by jsievenpiper** [CrunchyData/postgres-operator#3921]
## Questions

I'm looking to deploy a PGO cluster with [custom TLS](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/day-two/customize-cluster#customize-tls), but one thing I didn't see mentioned for either custom or built-in TLS is how (or if at all) the cluster is keeping track of certificate renewals. 

In my hand-rolled cluster today, I have a cron job that runs to `pg_reload_conf()` via psql when it's time to reload certificates without downtime (as well as rolling pgpool instances which do not have a no-downtime option AFAIK).

Is this something I'll need to deploy alongside my PGO cluster, or is this customizable/handled by default?

### Environment

Please provide the following details:
- Platform: Kubernetes
- Platform Version: 1.28.5
- PGO Image Tag: ubi8-5.5.1-0
- Postgres Version: 16
- Storage: zfs-ebs

**Comment by jsievenpiper** [comment]
Thank you so much @andrewlecuyer! This was exactly what I was looking for. Sorry I must have totally missed this.

Have a great day!

**Comment by andrewlecuyer** [comment]
You're welcome @jsievenpiper, glad it helped!

Hope you have a great day as well.
