### ISSUE TITLE
Do not capture postgresql logs in physical backup

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#393]
**Describe the bug**
contents of pg_log directory are present in the physical backup. 
Not sure if this is true for backrest backups.

**To Reproduce**

**Expected behavior**
There is no need to capture the contents of pg_log.

**Screenshots**

**Please tell us about your environment:**
Applicable to all Kubernetes platforms

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by jmccormick2001** [comment]
https://www.postgresql.org/docs/11/static/app-pgbasebackup.html

as no option exists for this, a custom change in crunchy-backup will be
required to implement this feature.  I've created that Issue here:

https://github.com/CrunchyData/crunchy-containers/issues/856

**Comment by jmccormick2001** [comment]
moving to clubhouse 3.6
