### ISSUE TITLE
unrecognized configuration parameter lc_collate on postgres 16

### ISSUE THREAD

**Issue by flikweert44** [CrunchyData/postgres-operator#3934]
## Overview

After doing a major upgrade of one of our clusters from postgres 15 to 16, we noticed several connections we're not working anymore. There seems to be an issue with the locale settings. 

When creating a cluster using the hippo-example we get the same locale issues. https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/postgres/postgres.yaml

## Environment

Please provide the following details:

- Platform: AKS
- Platform 1.28.9
- PGO Image Tag: ubi8-5.5.2-0
- Postgres Version 16.3-0
- Storage: Azure managed-premium disk
- 
### REPRO

Setup the hippo cluster with postgres version 16.
RUN show lc_collate;

### EXPECTED

The default value:
"en_US.UTF-8"

### ACTUAL

Error message:

ERROR:  unrecognized configuration parameter "lc_collate" 

SQL state: 42704

## Logs

not applicable

**Comment by andrewlecuyer** [comment]
Hi @flikweert44!  What you're seeing is actually the result of a change in Postgres 16.

More specifically, please see the following in the Postgres 16 release notes:

https://www.postgresql.org/docs/release/16.0/
> Remove read-only server variables lc_collate and lc_ctype (Peter Eisentraut)
>
> Collations and locales can vary between databases so having them as read-only server variables was unhelpful.

Therefore, what you are seeing is expected after moving to Postgres 16.

Hope this helps!

**Comment by benjaminjb** [comment]
Hello @flikweert44, I believe the above question has been answered; if you check the database, it should have the `Collate` field so that you can check per database. I'm going to close this issue, but if you have other questions about this topic and PGO, please reopen it or come ask in our [Discord server](https://discord.com/invite/a7vWKG8Ec9).

**Comment by flikweert44** [comment]
Yes that answers my question, thanks
