### ISSUE TITLE
possibility to assign patroni tags to specific instances / nodes

### ISSUE THREAD

**Issue by dberardo-com** [CrunchyData/postgres-operator#3939]
i am trying to mark one of my instances / nodes as non-failoverable using the nofailover tag. also failover priority is a necessary tag to use: https://patroni.readthedocs.io/en/latest/yaml_configuration.html#tags how to achieve this ?

**Comment by benjaminjb** [comment]
This seems to be a duplicate/overlap with https://github.com/CrunchyData/postgres-operator/issues/3941, so I'm going to close this one. Please reopen if you think these two issues are distinct and should be kept distinct.
