### ISSUE TITLE
pgbackrest-repo disk is full, how do I delete all backups + config warning

### ISSUE THREAD

**Issue by MilitsaB** [CrunchyData/postgres-operator#3943]
Hi everyone!

I have two questions:

1. My pgbackrest-repo disk is full, I want to clear it out completely. I've tried following the following steps from this issue: #2111 
But I get stuck at clearing ephemeral files. I have no idea which files are safe to delete, if someone could guide it would be great!
I've checked tmp but it only contains _db.stop_ which has a size of 0. I don't want resize the PVC. And I really don't mind losing everything, I just want pgbackrest to stay functional.

2. I've noticed that I am getting this warning: `WARN: configuration file contains invalid option 'repo1-rentention-archive'`
I'm not sure why I'm getting thsi, I followed this documention: [5.5.15](https://pgbackrest.org/command.html#command-backup)
and this is my pgbackrest_repo.conf:
```
[global]
log-path=/pgbackrest/repo1/log
repo1-path=/pgbackrest/repo1
repo1-rentention-archive=1
repo1-retention-full=14
repo1-retention-full-type=time
```

**Comment by andrewlecuyer** [comment]
Hi @MilitsaB!

You appear to have a typo in this setting:

```
repo1-rentention-archive=1
```

...which should be:

```
repo1-retention-archive=1
```

(I.e., the setting you provided has extra "n" in it.)

**Comment by benjaminjb** [comment]
Hi, @MilitsaB, it sounds like the above comment may have unblocked you, so I'm going to close this issue -- but if I'm wrong, please reopen this to continue the conversation.
