### ISSUE TITLE
add command flag to enable SSL on cluster create

### ISSUE THREAD

**Issue by the1forte** [CrunchyData/postgres-operator#395]
**What is the motivation or use case for the change? **
To enable SSL encryption for Operator provisioned clusters

**Describe the solution you'd like**
This command flag would be added to the existing pgo create cluster command. It would enable SSL for the PostgreSQL cluster by turning on SSL and generating a unique server cert and key for the new cluster. The server cert and key could be mounted in pgconf and a secret would be created to load them there. This command would require a ca.crt to be provided as the certificate authorities file, which could be added to the secret as well. It is assumed this flag would require the --custom-config flag as well.

**Please tell us about your environment:**
Centos 7 with OpenShift latest release. Plan to incorporate the Postgres Operator into the environment

* Operating System: Centos 7 / RHEL 7
* Where is this running ( Local, Cloud Provider)
local
* Storage being used (NFS, Hostpath, Gluster, etc):
custom storage solution integrated with Openshift
* Container Image Tag: rhel7-10.5-2.1.0
* PostgreSQL Version: 10.5
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 3.10

**Additional context**
Note that this change does not require the enforcement of changing the authentication model in pg_hba.conf to use cert.
Add any other context or screenshots about the enhancement request here.

**Comment by ron1** [comment]
When the cluster is SSL-enabled, a pgo create user command with --managed parameter should result in the creation of a secret that includes the ca.crt as a data field. In this case, the client requires the ca.crt in order to achieve one-way TLS authentication with the server.
