### ISSUE TITLE
Hi i see PGO is under Apache 2.0 license can it be used for commercial purposes ? Do we need to enrol to crunchy developer program to use it commercialy ?

### ISSUE THREAD

**Issue by staticle** [CrunchyData/postgres-operator#3950]

**Comment by andrewlecuyer** [comment]
The source code contained within the PGO GitHub repos (this repo included) is made available under the Apache License 2.0, and is therefore subject to that specific license and associated permissions, conditions, etc.

The container images made available by Crunchy Data via the [Crunchy Data Developer Portal](https://www.crunchydata.com/developers) are subject to the [Crunchy Data Developer Program Terms of Use](https://www.crunchydata.com/developers/terms-of-use).

If you have any specific questions, feel free to reach out to us at info@crunchydata.com
