### ISSUE TITLE
PGO + ESO = reconciliation loop

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3971]
We want to use PGO with ESO (external secret operator) and HashiCorp Vault.

When we configure ESO to synchronize only the password from Vault to the K8s Secret:
1. we set a new password value in Vault
2. ESO updates the password in the Secret
3. the verifier does not change
4. PGO updates nothing

When we configure ESO to synchronize password + verifier from Vault to the K8s Secret:
1. we set a new password value in Vault
2. we clear the verifier value in Vault (set to "null"; manual hash pre-generation is not an option for us)
3. ESO updates the password + verifier in the Secret
4. PGO creates a new verifier value
5. PGO sets the database user password to the new verifier value (= new password)
6. PGO updates the verifier value in the Secret to reflect the new value
7. the update to the Secret triggers an ESO reconcile
8. ESO updates the password + verfier (to null) in the Secret
9. PGO creates a new verifier value
10. ...
11. ...
we got a reconciliation loop

Any ideas to this one?

I know, the best would be a fix in ESO so that the update of the verifier value would not trigger a reconcile.

**Comment by SergK** [comment]
Hi @mzwettler2, did you find a working solution?

**Comment by mzwettler2** [comment]
@SergK 

not really.
we use this "workaround" at the moment:

refreshinterval 0
sync only password value
generate fake verifier value "null"
