### ISSUE TITLE
It appears that there is no way to grant a role to a user/role?

### ISSUE THREAD

**Issue by jmcdonagh** [CrunchyData/postgres-operator#3983]
In some cases we will GRANT a role to another role that has the INHERIT option. I'm not seeing in the docs how to do this. So if this isn't possible, I want this to be a feature request. If it is possible, I'd like to know how. Thanks!

**Comment by andrewlecuyer** [comment]
Hi @jmcdonagh!

You can define roles and other options for any users defined via `spec.users` (e.g. `INHERIT` or `NOINHERIT`) by adjusting the `options` for the user, as shown in the following docs:

https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management#adjusting-privileges

Hope this helps!
