### ISSUE TITLE
Allow postgres extensions

### ISSUE THREAD

**Issue by thekalinga** [CrunchyData/postgres-operator#4]
User should be able to install and enable extensions such as `postgis` within postgres instances that operator creates

**Comment by thekalinga** [comment]
Or may be change the base image that operator uses to deploy postgres, such as using [this](https://hub.docker.com/r/mdillon/postgis) instead of native extension

**Comment by xenophenes** [comment]
You'll be able to find out more information about deploying a customized strategy here: https://github.com/CrunchyData/postgres-operator/blob/master/docs/design.asciidoc

Inside of the strategy templates, you can either modify these directly or create a new folder called "2" where these files are copied over and modified to fit your needs. https://github.com/CrunchyData/postgres-operator/tree/master/conf/postgres-operator/cluster/1
The Strategy section of the Design document will explain exactly how to modify each aspect of the template including providing custom Docker images.

The pgo configuration file starts out [here](https://github.com/CrunchyData/postgres-operator/blob/master/examples/pgo.yaml.emptydir) and is (during the installation step) moved to your $HOME directory if you followed the default location provided in the instructions. For more information about modifying the configuration file, please take a look at the Configuration file here: https://github.com/CrunchyData/postgres-operator/blob/master/docs/config.asciidoc but you should see the section STRATEGY:  1 where you would simply change that variable to "2".

I hope that helps!

**Comment by jmccormick2001** [comment]
the base image is something you could change by editing the various templates used by the operator, we have for instance a postgres-gis container image that include postgis, if you were to replace the current image name in the configuration it would deploy that container image instead of the default postgres image.
