### ISSUE TITLE
Documentation has disappeared :(

### ISSUE THREAD

**Issue by sharkymcdongles** [CrunchyData/postgres-operator#407]
**Describe the bug**
All of the documentation links are 404ing:

https://crunchydata.github.io/postgres-operator/

**To Reproduce**
1. Go to https://crunchydata.github.io/postgres-operator/
2. See 404

**Expected behavior**
Documentation that exists

**Comment by calvinmorrow** [comment]
The URL looks like its changed slighty:  https://crunchydata.github.io/postgres-operator/stable/

**Comment by cahoonpwork** [comment]
Yes, the URL has changed to allow us to have multiple versions available.   The documentation for the develop branch is available also: https://crunchydata.github.io/postgres-operator/latest/ . 

I will look into possible putting a something for users who have bookmarked the previous location.
