### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by ramukima** [CrunchyData/postgres-operator#412]
**Describe the bug**
The documentation at https://crunchydata.github.io/postgres-operator/stable/getting-started/, section '=== Scaling Replicas' is rendered markdown and not HTML.
 
**To Reproduce**
1. https://crunchydata.github.io/postgres-operator/stable/getting-started/, section '=== Scaling Replicas'

**Expected behavior**
The documentation must be rendered as HTML content similar to other sections.

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by jmccormick2001** [comment]
thanks, fixed in the adoc file, should render correctly as soon as the html is rebuilt.  thanks for reporting!
