### ISSUE TITLE
Include prometheus/grafana in Operator

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#416]
Currently in Operator --metrics only includes collect container, for viewing metrics you need to install prometheus /grafana separately, it would be great to have that part of pgo create command.

@jmccormick2001 

**What is the motivation or use case for the change? **

**Describe the solution you'd like**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jmccormick2001** [comment]
moving to clubhouse.
