### ISSUE TITLE
Publish Helm Chart as a Release Asset

### ISSUE THREAD

**Issue by ron1** [CrunchyData/postgres-operator#417]
**What is the motivation or use case for the change? **

I would like to download a single Helm Chart artifact for a release rather than having to acquire the set of Helm Chart artifacts via git.

**Describe the solution you'd like**

The postgres-operator release process should generate a Helm Chart archive, for example, postgres-operator-helm-chart-3.3.0.tgz. This artifact should be included as an additional, downloadable "Asset" for the Release on github.com 

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by aelbarkani** [comment]
And/or to a repository (the official one for example: https://github.com/helm/charts)

**Comment by jmccormick2001** [comment]
I've added to the Makefile 'release' target a set of commands that will create a helm release tar ball for new releases.  I'll publish that to Github releases with the upcoming 3.4 release.
