### ISSUE TITLE
recreating the cluster with same name does not work reliably

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#418]
**Describe the bug**
recreating a cluster with same name (after deleting it) does not work sometimes. 

**To Reproduce**
create a cluster, delete it and recreate a cluster with same name. 

**Expected behavior**
Cluster creation succeeds or fails with a reason. 

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
All

**Additional context**
I believe these issue(s) are because of race condition between delete and create workflows.

**Comment by jmccormick2001** [comment]
this should be better now, rmdata was not removing -spool and -wal directories when using --delete-data, I've tested on OCP using NFS and it seems to let you delete/create over and over.
