### ISSUE TITLE
Add pgo command to enable and disable log_statement = 'all'

### ISSUE THREAD

**Issue by sharkymcdongles** [CrunchyData/postgres-operator#419]
**I'm submitting a ...**

 
 - [ ] bug report
 - [ x ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently there is no way to enable log_statement = 'all' on the fly. You can make the change then issue a pgo reload command, and it isn't picked up.

**What is the expected behavior?**
pgo reload reloads the config to where logging can be enabled on the fly or a new command is added for this.

**What is the motivation or use case for changing the behavior?**
log_statement = 'all' takes up tons of space especially on heavily trafficked dbs. Adding a way to enable this on the fly would allow end users to get verbose logs for pgbadger in short bursts rather than having them enabled all the time and taking up tons of space.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag: crunchydata/crunchy-postgres:centos7-10.5-2.1.0
 - Operator Version: 3.3.0
 - Storage (NFS, hostpath, storage class): azure-disk
 - PostgreSQL Version: 10.5
 - Platform (Docker, Kubernetes, OpenShift): Kubernetes
 - Platform Version: v1.11.3

**Comment by jmccormick2001** [comment]
https://github.com/CrunchyData/crunchy-containers/issues/855

when that issue is implemented, I'll come back and implement this issue for the operator.

**Comment by jmccormick2001** [comment]
so, what I've done for this upcoming release is add LogStatement and LogMinDurationStatement settings inside pgo.yaml, those correspond to the postgresql.conf settings 'log_statement' and 'log_min_duration_statement'.  I have defaults for these to NOT log any statement that is less than 1 minute long in running, so the logs sizes will drop dramatically.  If you want to go back to the current behavour you can set LogStatement to 'all'.  This is done at an operator 'global' level at this point.
