### ISSUE TITLE
operator REST API enhancement

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#420]
**What is the motivation or use case for the change? **
Current Postgres-operator REST API does not provide a way to query the status of a long running requests. 
Example(s): create/delete cluster, create backup, etc.

**Describe the solution you'd like**

In order to check the status, clients have to be knowledgeable about the REST endpoint to check and this depends on the previous request. Typical REST API implementations have requestId in the response structure that could be used by client to get the status of request.

This enhancement request is to investigate possible solutions and implement it.

The other alternative approach could be to use REST stream API to get notifications as they happen.

**Please tell us about your environment:**
Kubernetes

* Operating System: Centos7

* Where is this running ( Local, Cloud Provider)
local

* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
9.6-2.1.0 and 10.5-2.1.0
* PostgreSQL Version: 9.6 and 10.5

* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jmccormick2001** [comment]
[oper@doppio-ocp311 postgres-operator]$ pgo show workflow a6f97e56-9c24-4afe-83ce-6eb346a89c14
parameter           value
---------           -----
completed           2018-11-09.05.00.44
pg-cluster          lastone
submitted           2018-11-09.05.00.14
workflowid          a6f97e56-9c24-4afe-83ce-6eb346a89c14


an initial attempt at workflow mgmt, when you run 'pgo create cluster', you will get back in the response a workflow ID, you can then query that workflow with that ID to know the lifecycle of events for that workflow.
