### ISSUE TITLE
support oAuth authentication in postgres-operator

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#421]
**What is the motivation or use case for the change? **
postgres-operator is using file based basic authentication and this is not acceptable for some users.

**Describe the solution you'd like**
Support oAuth authentication in postgres-operator 

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
Openshift
* Platform Version:
3.10 and later

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jmccormick2001** [comment]
moving to clubhouse.
