### ISSUE TITLE
pgo df does not report information on replicas

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#423]
**Describe the bug**
"pgo df mycluster" command returns PGDATA disk total and used space. Looks like this is based on service name. So, if a service is not created or if there are multiple replicas, the output of "pgo df"  does not show the full picture.

**To Reproduce**
Create a cluster, scale it and run "pgo df <clustername>"

**Expected behavior**
Show space utilization for all DB disks in each POD under the cluster. 

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
Openshift 3.10

**Additional context**

**Comment by jmccormick2001** [comment]
merged in change to fix this, now df command shows results for each pod within a cluster.
