### ISSUE TITLE
pgo create pgpool clustername has no confirmation

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#424]
When you run pgo create pgpool CLUSTERNAME command, there is no confirmation question or return output of success or failure.
version 3.3

**Expected behavior**

**Screenshots**

**Please tell uthes about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by jmccormick2001** [comment]
doppio-kube:[~/odev/src/github.com/crunchydata/postgres-operator] pgo create pgpool badone
pgpool added for badon

a fix for this is now in the develop branch, above is the resulting message a user will get when they run the pgo create pgpool command after this change.
