### ISSUE TITLE
pgo df errors and does not out put after failover and deletion of old primary pvc

### ISSUE THREAD

**Issue by scrummyin** [CrunchyData/postgres-operator#425]
**Describe the bug**
If you have failed over previously and removed the original primary pod and it's associated pvc (since the pod that uses it no longer exists). Next, you run a `$pg df <cluster_name>` you will get a message saying `Error: persistentvolumeclaims "<cluster_name>" not found`. It seems that df guess at one of the pvc by name. However, it looks like pgo show cluster does not display this pvc, that list of pvc should maybe be used instead for the df operation.

**To Reproduce**
1. pgo create cluster <name>
2. pgo scale cluster <name>
3. pgo failover <name> --taget <target>
4. delete pvc for original <name>
5. pgo df <name>

**Expected behavior**
Show space utilization for all DB disks in each POD under the cluster.

**Please tell us about your environment:**

* Operating System:
* Local vm running centos
* Storage being used: NFS
* Container Image Tag: centos
* PostgreSQL Version: ALL
* Platform (Docker, Kubernetes, OpenShift): oc

**Additional context**
Related to #423 one solution can probably fix both.

**Comment by jmccormick2001** [comment]
merged in change that fixes this, df command now shows all Pod's for that cluster.
