### ISSUE TITLE
Failover seems to be broken in v3.3.0

### ISSUE THREAD

**Issue by cotigao** [CrunchyData/postgres-operator#426]
**Describe the bug**
Failover (replica -> primary) is not working.

**To Reproduce**
Soon after creating the cluster with pgo, (`pgo create cluster tempo --pgpool --replica-count=2 --autofail`)
1) Delete the primary postgres pod  (using "kubectl  delete ... ")
2)  If the cluster wasn't started with "--autofail" option,  then run "pgo failover --target ... ".
3)  Either way, even with --autofail option, same problem is noticed

> $ pgo show cluster all
cluster : tempo (centos7-10.5-2.1.0)
	pod : tempo-layx-667dc566c7-5kddd (Running) on k8s-02 (0/1) (primary)
	pvc : tempo-layx
	pod : tempo-mmxv-7d9d58dc6d-g4h4r (Running) on k8s-03 (1/1) (replica)
	pvc : tempo-mmxv
	pod : tempo-nqsz-855546c97b-qfrg5 (Running) on k8s-02 (0/1) (replica)
	pvc : tempo-nqsz
	pod : tempo-pgpool-559b7d9d87-vtwfn (Running) on k8s-02 (1/1) (replica)
	deployment : tempo-layx
	deployment : tempo-mmxv
	deployment : tempo-nqsz
	deployment : tempo-pgpool
	service : tempo - ClusterIP (10.233.37.233)
	service : tempo-pgpool - ClusterIP (10.233.52.45)
	service : tempo-replica - ClusterIP (10.233.3.249)
	replica : tempo-mmxv
	replica : tempo-nqsz
	labels : archive-timeout=60 name=tempo pgo-backrest=false pgpool-secret= pg-cluster=tempo pgo-version=3.3.0 primary=true archive=false autofail=true crunchy-pgbadger=false crunchy-pgpool=true crunchy_collect=false
        
"kubectl exec .." on all the postgres pods show that  env is set to  **PGMODE=replica**, and the ones that are not ready (0/1) yet,  spew the logs:

>Sun Oct 28 18:27:19 UTC 2018
Sun Oct 28 18:27:20 UTC 2018 INFO: Setting PGROOT to /usr/pgsql-10.
Sun Oct 28 18:27:20 UTC 2018 INFO: The PGUSER secret exists.
Sun Oct 28 18:27:20 UTC 2018 INFO: The PGROOT secret exists.
Sun Oct 28 18:27:20 UTC 2018 INFO: The PGPRIMARY secret exists.
Sun Oct 28 18:27:20 UTC 2018 INFO: Cleaning up the old postmaster.pid file..
Sun Oct 28 18:27:20 UTC 2018 INFO: User ID is set to uid=26(postgres) gid=26(postgres) groups=26(postgres),65534(nfsnobody).
Sun Oct 28 18:27:20 UTC 2018 INFO: Setting ARCHIVE_MODE to off.
Sun Oct 28 18:27:20 UTC 2018 INFO: Setting ARCHIVE_TIMEOUT to 60.
Sun Oct 28 18:27:20 UTC 2018 INFO: Working on replica..
Sun Oct 28 18:27:20 UTC 2018 INFO: Initializing the replica.
Sun Oct 28 18:27:20 UTC 2018 INFO: Waiting to allow the primary database time to successfully start before performing the initial backup..
**tempo:5432 - no response
tempo:5432 - no response
tempo:5432 - no response
tempo:5432 - no response**

**Expected behavior**
Deleted primary must be replaced by the target replica(with no autofail or --autofail).

**Please tell us about your environment:**
Kubernetes: 1.11.3 ( 1 master 2 slave VMs running on vagrant setup, with master node also playing the "node" role ).   Hostpath:  /data on every VM
PostgresOperator: 3.3.0

**Comment by ramukima** [comment]
I have a 3 node kubernetes cluster with single master (n1) and two slaves (n2, n3). 
- I deployed operator, it was scheduled on node n2. 
- I provisioned a database cluster with --autofail and --pgpool enabled deployed both pods on node n2. 
- I then used pgo scale with 1 replica and node label selector for node n3.

Once everything was provisioned fine, I shutdown node n2. I did not see the operator itself or my database move to node n3 or n1 (even through I had the master tainted). I expected rescheduling of these on other available nodes.

- I restarted node n2 and everything came back to normal.
- I shutdown node n3.

I expected the replica to be scheduled back on available nodes (n1 or n2) ignoring the "node-label=n3". Is my expectation wrong ?

Even with a database cluster (--autofail) where primary was provisioned on node n3 and replica on node n2, when I shutdown the node where my primary database running, I expected the operator to perform the failover.

Not sure a "node failure" is considered a criteria for database failover or not with this patch.

**Comment by jmccormick2001** [comment]
thanks, I'll try out this scenario and see what I can find out.

**Comment by jmccormick2001** [comment]
as I test this out, one thing to note, if you 'kubectl delete pod', the Deployment will spin up another new replacing Pod after a few seconds.  In this case, it seems to work after the replacement pod spins up.  If autofail is enabled, then what could happen is the autofail might fire before the Pod comes back, so adjusting the times of the autofail check comes into play here.  But more testing is required on this one.  

The multi-node scenario mentioned in this Issue is another test case I'll work on tomorrow.

**Comment by jmccormick2001** [comment]
I tested the multi node scenario on a kube 1.12 system,  what I'm seeing is that the deployments are getting recreated on another node after the original node is turned off, however, Kube marks the older pods as 'Unknown' which is interesting.  More testing on my part to make sure this is expected.  It takes a couple of minutes it appears for Kube to reschedule onto another node.

**Comment by cotigao** [comment]
Just wanted to know how is the automatic failover handled? If a postgres pod dies, does the operator completely rely on the deployment to spin up a new one?, in which case the primary replica will always be from the same deployment. But if the primary deployment is having repeated failures in launching the pod, will the operator take action in that case (delete the unstable primary deployment and make a new pod as replica from another existing deployment) ? If a (primary) deployment itself goes away, i guess the operator  will start  the failover process straight away, right?

**Comment by jmccormick2001** [comment]
you could definitely see a competition between the primary Deployment and the Operator if you say remove a Pod under the Deployment's control.  The operator might cause a failover if the Deployment can't replace the Pod within a time frame that doesn't trigger the failover by the Operator.  If the pod dies, the Operator thinks that this Deployment is probably corrupted and will remove the Deployment as part of the failover scenario.  If a node dies that the Primary Deployment Pod is running on,  it could also trigger a failover since the startup time (rescheduling) could take longer than the Operator logic is evaluating against.

**Comment by jmccormick2001** [comment]
when you do a failover the Operator will cause a replacement Deployment to be created, this is the current expected behavior, however, people have asked to a feature to be created where the replacement Deployment is NOT created, this is for users that have very large data set sizes and don't want to have a replica auto created.

**Comment by cotigao** [comment]
Ok. So the target replica(recreated or not)  should be expected to have `PG_MODE=primary`, right?

**Comment by jmccormick2001** [comment]
PG_MODE (the container env var) is only used at cluster startup to tell the PG container if its a primary or a replica which influences the running or not of initdb.  That env var will remain = replica even if the container is promoted into a replica from a primary.  The Operator uses labels on the pgcluster CRD to know whether or not the Deployment is a primary or a replica instead.

**Comment by cotigao** [comment]
Ok. I might be missing something here, but per my understanding the `crunchy-containers/bin/postgres/start.sh` depends on this env var. It checks  `PG_MODE`  to decide on the next steps.  If it is set as replica, it waits indefinitely echo'ing `Waiting to allow the primary database time to successfully start before performing the initial backup..` That is why those 2 deployments (one recreated and the other, newly created, both having `PG_MOD=replica`), I mentioned earlier show as unready(health probe fails). **Note**: I have deleted the primary deployment (not just the primary pod) and with no automatic failover, to keep things simple.

**Comment by cotigao** [comment]
_That env var will remain = replica even if the container is promoted into a replica from a primary_ -- Did you mean _...  promoted into a primary from replica_ ?

**Comment by cotigao** [comment]
> Ok. I might be missing something here, but per my understanding the `crunchy-containers/bin/postgres/start.sh` depends on this env var. It checks `PG_MODE` to decide on the next steps. If it is set as replica, it waits indefinitely echo'ing `Waiting to allow the primary database time to successfully start before performing the initial backup..` That is why those 2 deployments (one recreated and the other, newly created, both having `PG_MOD=replica`), I mentioned earlier show as unready(health probe fails). **Note**: I have deleted the primary deployment (not just the primary pod) and with no automatic failover, to keep things simple.

**Comment by cotigao** [comment]
>  That env var will remain = replica even if the container is promoted into a replica from a primary. 

Did you mean promoted into a primary from a replica?

**Comment by jmccormick2001** [comment]
correct, a promoted replica (to primary) will still retain the PG_MODE = replica setting.  The scenario I tested just now:  create primary with replica, manually delete the primary Deployment, manually failover to the replica...that seems to work with the current develop branch code.

**Comment by cotigao** [comment]
Thanks! I will try. Could you please tell me what commit Id your branch is at? (just to make sure we are on the same page)

**Comment by jmccormick2001** [comment]
should be resolved, the new version 3.5 will be out in January which greatly changes and speeds up failover.
