### ISSUE TITLE
second autofailover is not working

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#428]
@jmccormick2001 

Setup: 1 Primary + 2 replica

Mimic first failover by removing data directory of the primary node, autofailover works as expected.

Upon doing same of deleting data on promoted replica ( new primary ), autofailover does kick in.

Operator version: 3.3

**Comment by jmccormick2001** [comment]
weird, I can't reproduce this on ocp 3.11 and the most current develop branch, will retest after RC is built.
