### ISSUE TITLE
Does crunchydata/postgres-operator:centos7-1.5.1 create the correct thirdpartyresources?

### ISSUE THREAD

**Issue by jar349** [CrunchyData/postgres-operator#43]
the logs of the postgres-operator say that they have created:
- pg-cluster.crunchydata.com
- pg-backup.<same domain on the rest of these>
- pg-upgrade
- pg-policy
- pg-clone
- pg-policy-log 

but then it goes on to say that it can't find the requested resources (they don't have dashes in their names):
```
E0920 18:20:55.418172       1 reflector.go:201] github.com/crunchydata/postgres-operator/operator/backup/backup.go:100: Failed to list *tpr.PgBackup: the server could not find the requested resource (get pgbackups.crunchydata.com)
E0920 18:20:55.418308       1 reflector.go:201] github.com/crunchydata/postgres-operator/operator/cluster/cluster.go:120: Failed to list *tpr.PgCluster: the server could not find the requested resource (get pgclusters.crunchydata.com)
E0920 18:20:55.425411       1 reflector.go:201] github.com/crunchydata/postgres-operator/operator/cluster/clone.go:73: Failed to list *tpr.PgClone: the server could not find the requested resource (get pgclones.crunchydata.com)
E0920 18:20:55.443308       1 reflector.go:201] github.com/crunchydata/postgres-operator/operator/cluster/policies.go:163: Failed to list *tpr.PgPolicylog: the server could not find the requested resource (get pgpolicylogs.crunchydata.com)
E0920 18:20:55.443419       1 reflector.go:201] github.com/crunchydata/postgres-operator/operator/upgrade/upgrade.go:73: Failed to list *tpr.PgUpgrade: the server could not find the requested resource (get pgupgrades.crunchydata.com)
``` 

the examples/tpr folder has a pg-database tpr that isn't created by default by the postgres-operator container.  Should it be?  OR is it meant for creating a single database instance for testing purposes?

30 minutes after deploying the postgres-operator, I see the following in the logs:
```
Sep 20 14:57:02 postgres-operator-3770555364-5n3sl postgres-operator error time="2017-09-20T18:57:02Z" level=error msg="error in major upgrade watch closed before Until timeout" 
Sep 20 14:57:59 postgres-operator-3770555364-5n3sl postgres-operator error time="2017-09-20T18:57:59Z" level=error msg="error in ProcessJobs watch closed before Until timeout" 
Sep 20 15:10:23 postgres-operator-3770555364-5n3sl postgres-operator error time="2017-09-20T19:10:23Z" level=error msg="error in ProcessPolicies watch closed before Until timeout" 
Sep 20 15:19:03 postgres-operator-3770555364-5n3sl postgres-operator error time="2017-09-20T19:19:03Z" level=error msg="erro in clone complete watch closed before Until timeout" 
```

**Comment by neverfox** [comment]
Saw the same thing. I wonder if this is why my cluster never enters the ready state.

**Comment by jmccormick2001** [comment]
you should see the following:

kubectl get thirdpartyresources
NAME                           DESCRIPTION                                VERSION(S)
pg-backup.crunchydata.com      A postgres backup ThirdPartyResource       v1
pg-clone.crunchydata.com       A postgres clone ThirdPartyResource        v1
pg-cluster.crunchydata.com     A postgres cluster ThirdPartyResource      v1
pg-policy.crunchydata.com      A postgres policy ThirdPartyResource       v1
pg-policylog.crunchydata.com   A postgres policy log ThirdPartyResource   v1
pg-upgrade.crunchydata.com     A postgres upgrade ThirdPartyResource      v1

**Comment by jmccormick2001** [comment]
that examples/tpr directory is old stuff that is not used, I'll remove it.,

**Comment by jmccormick2001** [comment]
those error messages you see in the log are the current behavior, I'll leave this open to make sure I fix that in an upcoming release.

**Comment by jar349** [comment]
```
$ kl get thirdpartyresources
NAME                           DESCRIPTION                                                                             VERSION(S)
istio-config.istio.io          Istio configuration                                                                     v1alpha1
pg-backup.crunchydata.com      A postgres backup ThirdPartyResource                                                    v1
pg-clone.crunchydata.com       A postgres clone ThirdPartyResource                                                     v1
pg-cluster.crunchydata.com     A postgres cluster ThirdPartyResource                                                   v1
pg-database.crunchydata.com    A database specification containing a Pod and Service which run a PostgreSQL database   v1
pg-policy.crunchydata.com      A postgres policy ThirdPartyResource                                                    v1
pg-policylog.crunchydata.com   A postgres policy log ThirdPartyResource                                                v1
pg-upgrade.crunchydata.com     A postgres upgrade ThirdPartyResource                                                   v1
```

**Comment by jar349** [comment]
note [these lines](https://github.com/CrunchyData/postgres-operator/blob/master/operator/server/server.go#L43-L50) of code - they have dashes.  But the actual TRP objects do not have the dashes: https://github.com/CrunchyData/postgres-operator/blob/master/tpr/cluster.go

**Comment by rimusz** [comment]
seeing the same thing with v1.5.2, no ThirdPartyResources get created

**Comment by jar349** [comment]
confirmed that just because the logs say they can't find the resources... 1.5.2 does create a working postgres instance.  Now my problem is that I can't connect to the database with the credentials configured in ~/.pgo.yaml.  I'll open a separate issue for that.
