### ISSUE TITLE
 pgo show cluster reporting lspvc pod

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#431]
pgo show cluster all incorrectly show `lspvc` 

I think this is related to or caused by https://github.com/CrunchyData/postgres-operator/issues/430

 pgo show cluster all

cluster : mybackup (centos7-10.5-2.1.0)
	pod : lspvc-mybackup-backup (Succeeded) on openshift-demo-master-1 (0/1) (replica)
	pvc : mybackup-backup
	pod : mybackup-7fdc7c8f88-7tr5g (Running) on openshift-demo-app-0 (1/1) (primary)
	pvc : mybackup
	deployment : mybackup
	service : mybackup - ClusterIP (172.30.45.199)
	labels : custom-config=pgo-custom-pg-config name=mybackup pg-cluster=mybackup pgo-backrest=false pgo-version=3.3.0 primary=true archive=false archive-timeout=60 crunchy-pgbadger=false crunchy_collect=false

**Comment by jmccormick2001** [comment]
I've added a selector fragment "name!=lspvc" to the pod selection logic when 'pgo show cluster' is run, this will prevent lspvc pods from showing up.
