### ISSUE TITLE
Validate pgo.yml for FsGroup and SupplementalGroup

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#432]
Validate pgo.yml to have either FsGroup or SupplementalGroup

"Storage:
  storage1:
    AccessMode:  ReadWriteOnce
    Size:  200M
    StorageType:  dynamic
    StorageClass:  standard
    Fsgroup:  26
    SupplementalGroups:  
DefaultContainerResources:
"

**Comment by jmccormick2001** [comment]
I've added a validation check in for this, to prevent an fsgroup and supplementalgroup to both be specified in pgo.yaml within a givne storage spec.
