### ISSUE TITLE
pgbouncer enhancement 

### ISSUE THREAD

**Issue by cdave-git** [CrunchyData/postgres-operator#433]
Currently only way to change pgbouncer.ini is by changing template and redeploy Operator, desired feature would be 

1. Ability to make changes to pgbouncer.ini online and reload pgbouncer process
2. Ability to use different pgbouncer.ini setting on each cluster, fox ex: cluster A might need pool_type=session while other might use transaction.

Ability to create cluster with customer pgbouncer.ini config would be an ideal.

**Comment by jmccormick2001** [comment]
moving to clubhouse for tracking and scheduling.  3.6
