### ISSUE TITLE
failover target not verified during manual failover

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#442]
**Describe the bug**
If primary deployment is used as failover target, failover works as if a scale command was issued.  

**To Reproduce**
create a cluster using postgres-operator cli/ui with or without a replica and then issue the following command 
"pgo failover <clustername> --target <primary deployment>"

**Expected behavior**
Detect that the deployment is already primary and fail the request.

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
Openshift 3.11 running 10.5-2.1.0 images

**Additional context**

**Comment by jmccormick2001** [comment]
I've create a check in the failover logic for this use case, an error is returned to the client if a user tries this scenario with this change.
