### ISSUE TITLE
Investigate exposing metrics for PostgreSQL backup volumes 

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#443]
**What is the motivation or use case for the change? **
filesystem metrics are not available for backup volumes. 

**Describe the solution you'd like**
Need a way to get filesystem metrics of backup volumes so they can be monitored and alerted on.

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
openshift 3.10+

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jmccormick2001** [comment]
moving to clubhouse for tracking, 3.6
