### ISSUE TITLE
prevent user from using reserved labels

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#448]
**Describe the bug**
pgo delete cluster <cluster_name> does not work when label "name" has a value that is different from cluster_name. 

**To Reproduce**
pgo create cluster testing -l name=appname
pgo show cluster testing (does not work)
pgo show cluster appname (works)

**Expected behavior**
if name is a reserved label, users should not be allowed to pass in custom values.

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
openshift 3.11

**Additional context**

**Comment by jmccormick2001** [comment]
moved to clubhouse for tracking, 3.6
