### ISSUE TITLE
pgo cli binary for macOS

### ISSUE THREAD

**Issue by rimusz** [CrunchyData/postgres-operator#45]

**Comment by zetaab** [comment]
I compiled this with mac using these instructions https://github.com/CrunchyData/postgres-operator/blob/master/docs/build.asciidoc#installation (of course you need modify it little bit like yum -> brew and so on)

**Comment by zetaab** [comment]
I compiled this with mac using these instructions https://github.com/CrunchyData/postgres-operator/blob/master/docs/build.asciidoc#installation (of course you need modify it little bit like yum -> brew and so on)

**Comment by jmccormick2001** [comment]
I think I've got this working now, in the version 2.0 release I included a pgo Mac binary called pgo-mac, try it out, I don't have a mac so I can't test it....let me know your results....regards.
