### ISSUE TITLE
relocation of labels from deployments to CRD

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/postgres-operator#450]
this issue tracks the goal of consolidating cluster labels to be on the CRD instead of say a Deployment..

pgo-version
policies

examine other deployment labels and relocate to CRD where appropriate, impacts various queries.

**Describe the solution you'd like**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jmccormick2001** [comment]
moving to clubhouse for tracking, milestone 3.6, this one is partially done in 3.5

**Comment by lkhomenk** [comment]
@jmccormick2001 so there will be not way to label all cluster items at once during creation?

**Comment by jmccormick2001** [comment]
the pg-cluster label is the one that gets typically applied to all related resources that pertain to a given PG cluster, but currently when you add a label to a CRD or cluster, the operator doesn't apply that same label to all related objects, that would be perhaps a good feature to add.

**Comment by lkhomenk** [comment]
Thank you a lot Jeff. That would be really great!
