### ISSUE TITLE
pgo show cluster - label descriptions

### ISSUE THREAD

**Issue by cahoonpwork** [CrunchyData/postgres-operator#465]
**What is the motivation or use case for the change? **
update labels when you run pgo show cluster, not all pods are primary or replicas anymore.
**Describe the solution you'd like**

 pgo show cluster autocluster

cluster : autocluster (centos7-10.6-2.2.0-rc9)
       pod : autocluster-pgpool-5b86d786cc-7bcw8 (Running) on gke-centos7-pgo-3-4-0-rc-default-pool-25845042-phgz (1/1) (replica)
       pod : autocluster-stly-5644756ddd-47gt6 (Running) on gke-centos7-pgo-3-4-0-rc-default-pool-25845042-8rxx (1/1) (primary)
       pvc : autocluster-stly
       pod : autocluster-uhzw-6f988cd787-6qc4v (Running) on gke-centos7-pgo-3-4-0-rc-default-pool-25845042-phgz (1/1) (replica)
       pvc : autocluster-uhzw

-- pgpool should be labelled something other than replica.

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jmccormick2001** [comment]
fixed, will be present in 3.5.0-rc2 build.
