### ISSUE TITLE
setting autofail label after cluster creation does not work

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#476]
**Describe the bug**
autofailover does not work if autofail=true label is added after the cluster is created.

**To Reproduce**
create a cluster without autofail flag, add it later on and then remove pgdata directory on primary. Failover does not happen. Instead, primary is reinitialized and standby cannot establish a connection to primary

2018-11-28 13:54:33 UTC [584]: [1-1] user=,db=,app=,client=FATAL:  database system identifier differs between the primary and standby
2018-11-28 13:54:33 UTC [584]: [2-1] user=,db=,app=,client=DETAIL:  The primary's identifier is 6628909026883715144, the standby's identifier is 6628907131224109127.

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag: 10.6-2.2.0
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
OCP-3.11 

**Additional context**

**Comment by jmccormick2001** [comment]
tracking in clubhouse, shoudl be fixed in 3.5
