### ISSUE TITLE
pgo.yaml clarification

### ISSUE THREAD

**Issue by absolutejam** [CrunchyData/postgres-operator#482]
**Which example are you working with?**
GKE
pgo client version 3.4.0
apiserver version 3.4.0
deployed via. helm

**What is the current behavior?**
When I exec into the operator pod(s), I can see there is a `/pgo-config/pgo.yaml` file.  
There is also the same file provided when cloning the repo, as part of setup.

Really, I just wanted clarification around the use of the `pgo.yaml` as it's not quite clear in the documentation. Does this need to live somewhere specific, such as in a location accessible by the operator pods, or is it expected to live in my `$HOME` directory and used by `pgo`?

Also, as an aside - it looks like I can configure a lot of the persistent config items (eg. storage locations), via. pgo.yaml but is there a way to configure clusters, backups, etc. in yaml format for VCS? I'd rather use a testable IAC method that the `pgo` CLI if I can help it.

**Comment by absolutejam** [comment]
Ah, right. So if I update the config maps, I update the associated configs on the pods. Basic Kubernetes, I know, but I'm still relatively new to Kubernetes and the operator is an abstraction above regular controllers. Initially, I wasn't sure if the client side controlled it, but that makes perfect sense; thanks for clarifying.

Understandable that not everything is in there yet. I mean, the `pgo` client is super useful, but it would be nice to emulate `kubectl -f` at some point.

Great work on this.

**Comment by lkhomenk** [comment]
One can't edit default pgo.yaml after it was deployed with operator.
1. deploy operator with replicas=2
2. pgo show config
3. edit pgo-config config map pgo.yaml , set replicas to 3
4. pgo show config => still 2. although config map has 3.
@jmccormick2001 is it expected behavior? I know that some options can be overridden during  `pgo create cluster`. but updating defaults is also needed

**Comment by jmccormick2001** [comment]
if you make any changes to pgo.yaml or one of the operator templates you will need to run 'make deployoperator' to pull in those changes.
