### ISSUE TITLE
fix pgo create schedule help documentation 

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#483]
**Describe the bug**
The help text of pgo create schedule is incorrect. Especially for 
—ccp-image-tag 
and
—no-prompt 

**To Reproduce**
pgo create schedule --help

**Expected behavior**
--no-prompt is not required for this command. Please remove it.
--ccp-image-tag: not applicable

**Screenshots**

**Please tell us about your environment:**
Openshift 3.11
* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by pmereddy1** [comment]
Also, please add details on timezone used by --schedule option.

**Comment by jmccormick2001** [comment]
moved to clubhouse.
