### ISSUE TITLE
pgo show backup does not show backups taken by scheduler

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#484]
**Describe the bug**
pgo show backup does not show taken by scheduler

**To Reproduce**
pgo create cluster mycluster
pgo backup mycluster
pgo show backup
pgo create schedule --schedule="10 10 * * *" --schedule-type=pgbasebackup --pvc-name=mycluster-backup mycluster
-- Backup is taken by the schedule. 
But, "pgo show backup" does not show this backup.

**Expected behavior**
"pgo show backup" should show the backup taken by scheduler as well.

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
openshift 3.11

**Additional context**

**Comment by jmccormick2001** [comment]
will be fixed with new 3.5 scheduler.  will track in clubhouse 3.5.
