### ISSUE TITLE
pgo show backup status error

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#488]
**Describe the bug**
pgo show backup command displays backup status as "Error" first and them changes to completed.

**To Reproduce**
Immediately after running "pgo backup <clustername>"
Run the following command
pgo show backup <clustername>

The "Backup Status" field shows "Error"

**Expected behavior**
"Backup Status" should not start off with "Error". 

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
OCP-3.11

**Additional context**

**Comment by pmereddy1** [comment]
In addition, if pgbackrest backup in progress, it does not show in the "pgo show backup" output.

**Comment by jmccormick2001** [comment]
fix made, should be present in 3.5.0-rc2 build
