### ISSUE TITLE
use openshift/kube api instead of /var/run/docker.sock in operator pod

### ISSUE THREAD

**Issue by zetaab** [CrunchyData/postgres-operator#51]
using /var/run/docker.sock in kubernetes or in openshift is incorrect way of managing loads in container orchestration system. The correct way is that it should call and manage resources using APIs in kube/oc. https://github.com/CrunchyData/postgres-operator/blob/master/examples/operator/deployment.json#L61

**Comment by jmccormick2001** [comment]
I use that docker API to get metadata off of the container image...do you happen to know how to get this info using the Kube API?  for some reason I can't seem to locate it.

**Comment by jmccormick2001** [comment]
what I'll likely to is drop that dependency altogether, its a pain to deal with from a dependency mgmt perspective and I think I can just add that metadata to the CRD at cluster creation based off the image tag.  thanks for pointing this out with this issue.

**Comment by jmccormick2001** [comment]
no longer needed, I removed the Docker API dependency altogether.
