### ISSUE TITLE
Special characters not getting filtered properly in pgo client...

### ISSUE THREAD

**Issue by scalaenthusiast** [CrunchyData/postgres-operator#513]
**Describe the bug**
Special characters specified on the pgo command line cause an error when the message is sent to the operator api.

**To Reproduce**

pgo show backup ?
Error: Invalid Status Code: 404

**Expected behavior**
The client should tell the user that either '?' is an invalid cluster name or the cluster does not exist, but not a 404 error.

**Please tell us about your environment:**

* Operating System: OS X (mac pgo client)
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): "fast" storageclass
* Container Image Tag: development code branch
* PostgreSQL Version: 10
* Platform (Docker, Kubernetes, OpenShift): Kubes
* Platform Version: 1.12

**Additional context**
Issue possibly exists with other commands as well when special characters are not properly handled.

**Comment by jmccormick2001** [comment]
moving to clubhouse 3.6 for tasking.
