### ISSUE TITLE
Returns success response but no cluster created

### ISSUE THREAD

**Issue by drshrey** [CrunchyData/postgres-operator#536]
**Describe the bug**
I call the create cluster command through the REST api like this:
```
	r.ClientVersion = "3.4.0"
	r.StorageConfig = "storageos"
	r.Series = 1

	jsonValue, _ := json.Marshal(r)
	url := fmt.Sprintf(createClusterURL, constants.PGO_APISERVER_URL)

	spew.Dump(url, constants.PGO_CREDENTIALS_USERNAME, constants.PGO_CREDENTIALS_PASSWORD)

	action := "POST"
	req, err := http.NewRequest(action, url, bytes.NewBuffer(jsonValue))
	if err != nil {
		log.Debug("req, err := http.NewRequest(action, url, bytes.NewBuffer(jsonValue))", err.Error())
		return &response, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.SetBasicAuth(constants.PGO_CREDENTIALS_USERNAME, constants.PGO_CREDENTIALS_PASSWORD)

	resp, err := authedHTTPClient.Do(req)
	if err != nil {
		log.Debug("resp, err := authedHTTPClient.Do(req)", err.Error())
		return &response, err
	}

	defer resp.Body.Close()

	log.Debugf("%v", resp)
	err = StatusCheck(resp)
	if err != nil {
		log.Debug("err = StatusCheck(resp)", err.Error())
		return &response, err
	}

	if err := json.NewDecoder(resp.Body).Decode(&response); err != nil {
		log.Printf("%v\n", resp.Body)
		log.Println(err)
		return &response, err
	}
```

I get back the response:
```
(*pgo.CreateClusterResponse)(0xc00009cd40)({
 Results: ([]string) (len=2 cap=4) {
  (string) (len=21) "created Pgcluster bar",
  (string) (len=48) "workflow id d742ad39-5dc2-410f-bc08-1d32af7b0489"
 },
 Status: (pgo.Status) {
  Code: (string) (len=2) "ok",
  Msg: (string) ""
 }
})
```

However, when I check kubernetes, I don't see any pods/ services created as a result. 

**To Reproduce**
1. create a cluster foo
2. Delete the cluster foo
3. Immediately create cluster foo right after
4. `kubectl get pods` within the namespace 

**Expected behavior**
I expect to see pods and services representing the newly created cluster.

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running: GKE
* Storage being used: persistent-disk
* Container Image Tag: `centos7-3.4.0`
* PostgreSQL Version: 
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: pgo is 3.4.0

**Additional context**

**Comment by devlounge** [comment]
Same issue here (3.5.0)

**Comment by jmccormick2001** [comment]
I'll take a look.

**Comment by tritruong** [comment]
I'm having the same issue (Kops, Po 3.5.0, Helm), the error probably comes from JSON unmarshalling error

Here is the full log

> time="2019-02-13T19:19:59Z" level=info msg="[PgclusterCONTROLLER] OnAdd /apis/cr.client-go.k8s.io/v1/namespaces/postgres-operator/pgclusters/mycluster"
time="2019-02-13T19:19:59Z" level=debug msg="[PgtaskCONTROLLER] OnAdd /apis/cr.client-go.k8s.io/v1/namespaces/postgres-operator/pgtasks/mycluster-createcluster"
time="2019-02-13T19:19:59Z" level=debug msg="UPDATED status: &v1.Pgcluster{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ObjectMeta:v1.ObjectMeta{Name:\"mycluster\", GenerateName:\"\", Namespace:\"postgres-operator\", SelfLink:\"/apis/cr.client-go.k8s.io/v1/namespaces/postgres-operator/pgclusters/mycluster\", UID:\"5adc7837-2fc4-11e9-9ab5-065370e32cce\", ResourceVersion:\"3283368\", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63685682399, loc:(*time.Location)(0x1c8a5e0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"autofail\":\"true\", \"name\":\"mycluster\"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}, Spec:v1.PgclusterSpec{Name:\"mycluster\", ClusterName:\"mycluster\", Policies:\"\", CCPImageTag:\"centos7-10.6-2.3.0\", Port:\"5432\", NodeName:\"\", PrimaryStorage:v1.PgStorageSpec{Name:\"\", StorageClass:\"io1\", AccessMode:\"ReadWriteOnce\", Size:\"4G\", StorageType:\"dynamic\", Fsgroup:\"26\", SupplementalGroups:\"\", MatchLabels:\"\"}, ArchiveStorage:v1.PgStorageSpec{Name:\"\", StorageClass:\"\", AccessMode:\"\", Size:\"\", StorageType:\"\", Fsgroup:\"\", SupplementalGroups:\"\", MatchLabels:\"\"}, ReplicaStorage:v1.PgStorageSpec{Name:\"\", StorageClass:\"gp2\", AccessMode:\"ReadWriteOnce\", Size:\"4G\", StorageType:\"dynamic\", Fsgroup:\"26\", SupplementalGroups:\"\", MatchLabels:\"\"}, BackrestStorage:v1.PgStorageSpec{Name:\"\", StorageClass:\"gp2\", AccessMode:\"ReadWriteOnce\", Size:\"16G\", StorageType:\"dynamic\", Fsgroup:\"26\", SupplementalGroups:\"\", MatchLabels:\"\"}, ContainerResources:v1.PgContainerResources{RequestsMemory:\"64Mi\", RequestsCPU:\"0.05\", LimitsMemory:\"64Mi\", LimitsCPU:\"0.05\"}, PrimaryHost:\"mycluster\", User:\"testuser\", Database:\"userdb\", Replicas:\"0\", Strategy:\"1\", SecretFrom:\"\", BackupPVCName:\"\", BackupPath:\"\", UserSecretName:\"mycluster-testuser-secret\", RootSecretName:\"mycluster-postgres-secret\", PrimarySecretName:\"mycluster-primaryuser-secret\", Status:\"\", PswLastUpdate:\"2019-02-13T19:19:59Z\", CustomConfig:\"\", UserLabels:map[string]string{\"archive-timeout\":\"60\", \"crunchy-pgbadger\":\"true\", \"crunchy_collect\":\"true\", \"pgo-backrest\":\"true\", \"pgo-version\":\"3.5.0\", \"archive\":\"true\"}}, Status:v1.PgclusterStatus{State:\"Processed\", Message:\"Successfully processed Pgcluster by controller\"}}"
time="2019-02-13T19:19:59Z" level=debug msg="pvc [mycluster] already present from previous cluster with this same name, will not recreate"
time="2019-02-13T19:19:59Z" level=debug msg="UPDATED status: &v1.Pgtask{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ObjectMeta:v1.ObjectMeta{Name:\"mycluster-createcluster\", GenerateName:\"\", Namespace:\"postgres-operator\", SelfLink:\"/apis/cr.client-go.k8s.io/v1/namespaces/postgres-operator/pgtasks/mycluster-createcluster\", UID:\"5add864d-2fc4-11e9-9ab5-065370e32cce\", ResourceVersion:\"3283369\", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63685682399, loc:(*time.Location)(0x1c8a5e0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"pg-cluster\":\"mycluster\", \"workflowid\":\"2e3b9df4-d636-486b-9c82-68d60c7b7148\"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}, Spec:v1.PgtaskSpec{Name:\"mycluster-createcluster\", StorageSpec:v1.PgStorageSpec{Name:\"\", StorageClass:\"\", AccessMode:\"\", Size:\"\", StorageType:\"\", Fsgroup:\"\", SupplementalGroups:\"\", MatchLabels:\"\"}, TaskType:\"workflow\", Status:\"\", Parameters:map[string]string{\"pg-cluster\":\"mycluster\", \"task submitted\":\"2019-02-13.19.19.59\", \"workflowid\":\"2e3b9df4-d636-486b-9c82-68d60c7b7148\"}}, Status:v1.PgtaskStatus{State:\"Processed\", Message:\"Successfully processed Pgtask by controller\"}}"
time="2019-02-13T19:19:59Z" level=info msg="workflow task added [mycluster-createcluster] ID [2e3b9df4-d636-486b-9c82-68d60c7b7148]"
time="2019-02-13T19:19:59Z" level=debug msg="pvc [mycluster-xlog] already present from previous cluster with this same name, will not recreate"
time="2019-02-13T19:19:59Z" level=debug msg="creating Pgcluster object strategy is [1]"
time="2019-02-13T19:19:59Z" level=info msg="strategy found"
time="2019-02-13T19:19:59Z" level=info msg="creating Pgcluster object using Strategy 1 in namespace postgres-operator"
time="2019-02-13T19:19:59Z" level=info msg="created with Name=mycluster in namespace postgres-operator"
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "mycluster",
        "labels": {
            "vendor": "crunchydata",
            "pg-cluster": "mycluster",
            "name": "mycluster"
        }
    },
    "spec": {
        "ports": [
    {
         "name": "postgres",
            "protocol": "TCP",
            "port": 5432,
            "targetPort": 5432,
            "nodePort": 0
        }, {
         "name": "node-exporter",
    "protocol": "TCP",
    "port": 9100,
    "targetPort": 9100,
    "nodePort": 0
    }, {
    "name": "pgbadger",
    "protocol": "TCP",
    "port": 10000,
    "targetPort": 10000,
    "nodePort": 0
    }, {
    "name": "sshd",
    "protocol": "TCP",
    "port": 2022,
    "targetPort": 2022,
    "nodePort": 0
    }, {
    "name": "postgres-exporter",
    "protocol": "TCP",
    "port": 9187,
    "targetPort": 9187,
    "nodePort": 0
    }
    ],
        "selector": {
            "service-name": "mycluster"
        },
        "type": "ClusterIP",
        "sessionAffinity": "None"
    }
}
time="2019-02-13T19:19:59Z" level=info msg="created service mycluster"
{
        "kind": "Service",
        "apiVersion": "v1",
        "metadata": {
            "name": "mycluster-backrest-shared-repo",
            "labels": {
                "name": "mycluster-backrest-shared-repo",
                "pgo-backrest-repo": "true",
                "pg-cluster": "mycluster"
            }
        },
        "spec": {
            "ports": [{
                "protocol": "TCP",
                "port": 2022,
                "targetPort": 2022,
                "nodePort": 0
            }],
            "selector": {
                "name": "mycluster-backrest-shared-repo"
            },
            "type": "ClusterIP",
            "sessionAffinity": "None"
        }
}
time="2019-02-13T19:19:59Z" level=info msg="created service mycluster-backrest-shared-repo"
{
    "kind": "Deployment",
    "apiVersion": "apps/v1",
    "metadata": {
        "name": "mycluster-backrest-shared-repo",
        "labels": {
            "name": "mycluster-backrest-shared-repo",
            "pg-cluster": "mycluster",
            "service-name": "mycluster-backrest-shared-repo",
            "pgo-backrest-repo": "true"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "matchLabels": {
                    "name": "mycluster-backrest-shared-repo",
                    "pg-cluster": "mycluster",
                    "service-name": "mycluster-backrest-shared-repo",
                "pgo-backrest-repo": "true"
            }
        },
        "template": {
            "metadata": {
                "labels": {
                    "name": "mycluster-backrest-shared-repo",
                    "pg-cluster": "mycluster",
                    "service-name": "mycluster-backrest-shared-repo",
                "pgo-backrest-repo": "true"
                }
            },
            "spec": {
        "securityContext": {
     "fsGroup": 26
},

                "containers": [{
                    "name": "database",
                    "image": "crunchydata/pgo-backrest-repo:centos7-3.5.0",
                    "ports": [{
                        "containerPort": 2022,
                        "protocol": "TCP"
                    }],

                    "env": [{
                        "name": "PGBACKREST_STANZA",
                        "value": "db"
                    }, {
                        "name": "SSHD_PORT",
                        "value": "2022"
                    }, {
                        "name": "PGBACKREST_DB_PATH",
                        "value": "/pgdata/mycluster"
                    }, {
                        "name": "PGBACKREST_REPO_PATH",
                        "value": "/backrestrepo/mycluster-backrest-shared-repo"
                    }, {
                        "name": "PGBACKREST_LOG_PATH",
                        "value": "/tmp"
                    }, {
                        "name": "PGBACKREST_DB_HOST",
                        "value": "mycluster"
                    }],
                    "volumeMounts": [{
                        "name": "sshd",
                        "mountPath": "/sshd",
                        "readOnly": true
                    }, {
                        "name": "backrestrepo",
                        "mountPath": "/backrestrepo",
                        "readOnly": false
                    }]
                }],
                "volumes": [{
                    "name": "sshd",
                    "secret": {
                            "secretName": "pgo-backrest-repo-config",
                            "defaultMode": 511
                        }
                }, {
                    "name": "backrestrepo",
                    "persistentVolumeClaim": {
                            "claimName": "mycluster-backrest-shared-repo"
                        }
                }],
                "restartPolicy": "Always",
                "dnsPolicy": "ClusterFirst"
            }
        },
        "strategy": {
            "type": "RollingUpdate",
            "rollingUpdate": {
                "maxUnavailable": 1,
                "maxSurge": 1
            }
        }
    }
}
time="2019-02-13T19:19:59Z" level=debug msg="pvc [mycluster-backrest-shared-repo] already present, will not recreate"
time="2019-02-13T19:19:59Z" level=debug msg="hi from backup create repo deploy"
time="2019-02-13T19:19:59Z" level=debug msg=mycluster-backrest-shared-repo
time="2019-02-13T19:19:59Z" level=info msg="created deployment mycluster-backrest-shared-repo"
time="2019-02-13T19:19:59Z" level=debug msg="GetAffinity with nodeLabelKey=[] nodeLabelKey=[] and operator=[In]\n"
            "resources": {
                "requests": {
                    "memory": "64Mi",
                    "cpu": "0.05"
                },
                "limits": {
                    "memory": "64Mi",
                    "cpu": "0.05"
                }
            },
time="2019-02-13T19:19:59Z" level=debug msg="configmaps \"pgo-custom-pg-config\" not found"
time="2019-02-13T19:19:59Z" level=debug msg="pgo-custom-pg-config configmap not found "
time="2019-02-13T19:19:59Z" level=debug msg="pgo-custom-pg-config was not found, , skipping global configMap"
time="2019-02-13T19:19:59Z" level=debug msg="crunchy_collect was found as a label on cluster create"
time="2019-02-13T19:19:59Z" level=info msg="namespace=postgres-operator"
time="2019-02-13T19:19:59Z" level=info msg="secretName=mycluster-primaryuser-secret"
time="2019-02-13T19:19:59Z" level=debug msg="crunchy_badger was found as a label on cluster create"
time="2019-02-13T19:19:59Z" level=debug msg="collectaddon value is [,{\n    \"name\": \"collect\",\n    \"image\": \"crunchydata/crunchy-collect:centos7-10.6-2.3.0\",\n    \"ports\": [{\n        \"containerPort\": 9187,\n        \"protocol\": \"TCP\"\n    }, {\n        \"containerPort\": 9100,\n        \"protocol\": \"TCP\"\n    }],\n    \"env\": [{\n        \"name\": \"DATA_SOURCE_NAME\",\n        \"value\": \"postgresql://ccp_monitoring:password@127.0.0.1:5432/postgres?sslmode=disable\"\n    },\n    {\n    \t\"name\": \"JOB_NAME\",\n    \t\"value\": \"mycluster\"\n    }\n    ]\n}\n]"
time="2019-02-13T19:19:59Z" level=error msg="error unmarshalling primary json into Deployment invalid character '}' looking for beginning of object key string"
time="2019-02-13T19:19:59Z" level=debug msg="[{\"op\":\"replace\",\"path\":\"/spec/status\",\"value\":\"upgrade completed\"}]"
,{
    "name": "collect",
    "image": "crunchydata/crunchy-collect:centos7-10.6-2.3.0",
    "ports": [{
        "containerPort": 9187,
        "protocol": "TCP"
    }, {
        "containerPort": 9100,
        "protocol": "TCP"
    }],
    "env": [{
        "name": "DATA_SOURCE_NAME",
        "value": "postgresql://ccp_monitoring:password@127.0.0.1:5432/postgres?sslmode=disable"
    },
    {
        "name": "JOB_NAME",
        "value": "mycluster"
    }
    ]
}
            ,{
                "name": "pgbadger",
        "image": "crunchydata/crunchy-pgbadger:centos7-10.6-2.3.0",
                "ports": [ {
                        "containerPort": 10000,
                        "protocol": "TCP"
                    }
                ],
                "readinessProbe": {
                    "tcpSocket": {
                        "port": 10000
                    },
                    "initialDelaySeconds": 20,
                    "periodSeconds": 10
                },

                "env": [ {
        "name": "BADGER_TARGET",
        "value": "mycluster"
        } ],
                "volumeMounts": [
                    {
                        "mountPath": "/pgdata",
                        "name": "pgdata",
                        "readOnly": true
                    },
                    {
                        "mountPath": "/report",
                        "name": "report",
                        "readOnly": false
                    }
                ]
            }
{
    "kind": "Deployment",
    "apiVersion": "extensions/v1beta1",
    "metadata": {
        "name": "mycluster",
        "labels": {
            "vendor": "crunchydata",
            "pgo-version": "3.5.0","deployment-name": "mycluster","primary": "true","archive-timeout": "60","crunchy_collect": "true","pgo-backrest": "true","archive": "true","name": "mycluster","pg-cluster": "mycluster","crunchy-pgbadger": "true"
        }
    },
    "spec": {
        "replicas": 1,
        "template": {
            "metadata": {
                "labels": {
                    "name": "mycluster",
                    "vendor": "crunchydata",
                    "name": "mycluster","pg-cluster": "mycluster","crunchy-pgbadger": "true","pgo-backrest": "true","archive": "true","primary": "true","archive-timeout": "60","crunchy_collect": "true","pgo-version": "3.5.0","deployment-name": "mycluster"
                }
            },
            "spec": {

                "securityContext": {
     "fsGroup": 26
},

                "containers": [


            {
                    "name": "database",
                    "image": "crunchydata/crunchy-postgres:centos7-10.6-2.3.0",
                    "readinessProbe": {
                        "exec": {
                            "command": [
                                "/opt/cpm/bin/readiness.sh"
                            ]
                        },
                        "initialDelaySeconds": 15,
                        "timeoutSeconds": 8
                    },

                        "resources": {
                "requests": {
                    "memory": "64Mi",
                    "cpu": "0.05"
                },
                "limits": {
                    "memory": "64Mi",
                    "cpu": "0.05"
                }
            },


                    "env": [{
                        "name": "PG_PRIMARY_PORT",
                        "value": "5432"
                    }, {
                        "name": "PG_MODE",
                        "value": "primary"
                    }, {
                        "name": "PG_USER",
                        "value": "postgres"
                    }, {
                        "name": "PG_PRIMARY_HOST",
                        "value": "mycluster"
                    }, {
                        "name": "LOG_STATEMENT",
                        "value": "none"
                    }, {
                        "name": "LOG_MIN_DURATION_STATEMENT",
                        "value": "60000"
                    }, {
                        "name": "PG_LOCALE",
                        "value": "en_US.UTF8"
                    }, {
                        "name": "BACKUP_PATH",
                        "value": ""
                    }, {
                        "name": "PGDATA_PATH_OVERRIDE",
                        "value": "mycluster"
                    }, {
                                    "name": "PGBACKREST_STANZA",
                        "value": "db"
                    }, {
                        "name": "PGBACKREST_REPO1_HOST",
                        "value": "mycluster-backrest-shared-repo"
                    }, {
                        "name": "BACKREST_SKIP_CREATE_STANZA",
                        "value": "true"
                    }, {
                        "name": "PGBACKREST",
                        "value": "true"
                    }, {
                        "name": "PGBACKREST_REPO1_PATH",
                        "value": "/backrestrepo/mycluster-backrest-shared-repo"
                    }, {
                        "name": "PGBACKREST_DB_PATH",
                        "value": "/pgdata/mycluster"
                    }, {
                        "name": "ENABLE_SSHD",
                        "value": "true"
                    }, {
                        "name": "PGBACKREST_LOG_PATH",
                        "value": "/tmp"
                    }, {

                        "name": "PG_DATABASE",
                        "value": "userdb"
                    }, {
                        "name": "PGMONITOR_PASSWORD",
                        "value": "password"
                    }, {
                        "name": "ARCHIVE_MODE",
                        "value": "on"
                    }, {
                        "name": "ARCHIVE_TIMEOUT",
                        "value": "60"
                    }, {
                        "name": "XLOGDIR",
                        "value": "false"
                    }, {
                        "name": "PGHOST",
                        "value": "/tmp"
                    }],


                    "volumeMounts": [{
                            "mountPath": "/pgdata",
                            "name": "pgdata",
                            "readOnly": false
                        }, {
                            "mountPath": "/backup",
                            "name": "backup",
                            "readOnly": true
                        }, {
                            "mountPath": "/backuprestrepo",
                            "name": "backrestrepo"
                        }, {
                            "mountPath": "/pguser",
                            "name": "user-volume"
                        }, {
                            "mountPath": "/pgprimary",
                            "name": "primary-volume"
                        }, {
                            "mountPath": "/pgroot",
                            "name": "root-volume"
                        }, {
                            "mountPath": "/pgwal",
                            "name": "pgwal-volume"
                        }, {
                            "mountPath": "/sshd",
                            "name": "sshd",
                            "readOnly": true
                        }, {
                            "mountPath": "/pgconf",
                            "name": "pgconf-volume"
                        }, {
                            "mountPath": "/recover",
                            "name": "recover-volume"
                        }

                    ],

                    "ports": [{
                        "containerPort": 5432,
                        "protocol": "TCP"
                    }],
                    "resources": {},
                    "imagePullPolicy": "IfNotPresent"
                }

                ,{
    "name": "collect",
    "image": "crunchydata/crunchy-collect:centos7-10.6-2.3.0",
    "ports": [{
        "containerPort": 9187,
        "protocol": "TCP"
    }, {
        "containerPort": 9100,
        "protocol": "TCP"
    }],
    "env": [{
        "name": "DATA_SOURCE_NAME",
        "value": "postgresql://ccp_monitoring:password@127.0.0.1:5432/postgres?sslmode=disable"
    },
    {
        "name": "JOB_NAME",
        "value": "mycluster"
    }
    ]
}


                            ,{
                "name": "pgbadger",
        "image": "crunchydata/crunchy-pgbadger:centos7-10.6-2.3.0",
                "ports": [ {
                        "containerPort": 10000,
                        "protocol": "TCP"
                    }
                ],
                "readinessProbe": {
                    "tcpSocket": {
                        "port": 10000
                    },
                    "initialDelaySeconds": 20,
                    "periodSeconds": 10
                },

                "env": [ {
        "name": "BADGER_TARGET",
        "value": "mycluster"
        } ],
                "volumeMounts": [
                    {
                        "mountPath": "/pgdata",
                        "name": "pgdata",
                        "readOnly": true
                    },
                    {
                        "mountPath": "/report",
                        "name": "report",
                        "readOnly": false
                    }
                ]
            }


        ],
                "volumes": [{
                        "name": "pgdata",
                        "persistentVolumeClaim": {
     "claimName": "mycluster"
}
                    }, {
                        "name": "backup",
                        "emptyDir": {
}
                    }, {
                        "name": "user-volume",
                        "secret": {
                            "secretName": "mycluster-testuser-secret"
                        }
                    }, {
                        "name": "primary-volume",
                        "secret": {
                            "secretName": "mycluster-primaryuser-secret"
                        }
                    }, {
                        "name": "sshd",
                        "secret": {
                            "secretName": "pgo-backrest-repo-config",
                "defaultMode": 511
                        }
                    }, {
                        "name": "root-volume",
                        "secret": {
                            "secretName": "mycluster-postgres-secret"
                        }
                    }, {
                        "name": "pgwal-volume",
            "persistentVolumeClaim": {
     "claimName": "mycluster-xlog"
}
                    }, {
                        "name": "recover-volume",
            "emptyDir": { "medium": "Memory" }
                    }, {
                        "name": "report",
            "emptyDir": { "medium": "Memory" }
                    }, {
                        "name": "backrestrepo",

                    }, {
                        "name": "pgconf-volume",
            "emptyDir": { "medium": "Memory" }
                    }

                ],



                "restartPolicy": "Always",
                "dnsPolicy": "ClusterFirst"
            }
        },
        "strategy": {
            "type": "RollingUpdate",
            "rollingUpdate": {
                "maxUnavailable": 1,
                "maxSurge": 1
            }
        }
    }
}
time="2019-02-13T19:19:59Z" level=debug msg="[{\"op\":\"replace\",\"path\":\"/spec/PrimaryStorage/name\",\"value\":\"mycluster\"}]"
time="2019-02-13T19:19:59Z" level=debug msg="[PodCONTROLLER] OnAdd /api/v1/namespaces/postgres-operator/pods/mycluster-backrest-shared-repo-85bf88456f-6wh9t"
time="2019-02-13T19:19:59Z" level=debug msg="pgo-backrest-repo found mycluster-backrest-shared-repo-85bf88456f-6wh9t"
time="2019-02-13T19:19:59Z" level=debug msg="[PodCONTROLLER] OnUpdate /api/v1/namespaces/postgres-operator/pods/mycluster-backrest-shared-repo-85bf88456f-6wh9t"
time="2019-02-13T19:19:59Z" level=debug msg="pgo-backrest-repo found mycluster-backrest-shared-repo-85bf88456f-6wh9t"
time="2019-02-13T19:19:59Z" level=debug msg="before pgpool check []"
time="2019-02-13T19:19:59Z" level=debug msg="pgcluster mycluster updated"
time="2019-02-13T19:19:59Z" level=debug msg="pgcluster mycluster updated"
time="2019-02-13T19:19:59Z" level=debug msg="pgcluster mycluster updated"
time="2019-02-13T19:19:59Z" level=debug msg="[PodCONTROLLER] OnUpdate /api/v1/namespaces/postgres-operator/pods/mycluster-backrest-shared-repo-85bf88456f-6wh9t"
time="2019-02-13T19:19:59Z" level=debug msg="pgo-backrest-repo found mycluster-backrest-shared-repo-85bf88456f-6wh9t"
time="2019-02-13T19:20:09Z" level=debug msg="[PodCONTROLLER] OnUpdate /api/v1/namespaces/postgres-operator/pods/mycluster-backrest-shared-repo-85bf88456f-6wh9t"
time="2019-02-13T19:20:09Z" level=debug msg="pgo-backrest-repo found mycluster-backrest-shared-repo-85bf88456f-6wh9t"

**Comment by tritruong** [comment]
I'm able created cluster after fix these:
In the template file "cluster-deployment-1.json",
    
    1/ It should be .spec.metadata.name instead of .spec.metadata.labels.name. This will cause duplicate "name" field in generated json 
    https://github.com/CrunchyData/postgres-operator/blob/develop/chart/postgres-operator/files/postgres-operator/cluster/1/cluster-deployment-1.json#L16

    2/ Duplicate container "resources" field
    https://github.com/CrunchyData/postgres-operator/blob/develop/chart/postgres-operator/files/postgres-operator/cluster/1/cluster-deployment-1.json#L41
    https://github.com/CrunchyData/postgres-operator/blob/develop/chart/postgres-operator/files/postgres-operator/cluster/1/cluster-deployment-1.json#L131

**Comment by devlounge** [comment]
Will this get fixed soon?

**Comment by cahoonpwork** [comment]
Should be in the develop branch sometime this week.  Will be in 3.5.2, which should come out in the next couple of weeks.
