### ISSUE TITLE
example nfs yaml 

### ISSUE THREAD

**Issue by chrisdrew1** [CrunchyData/postgres-operator#544]
** Which example are you working with? **
setting up nfs on the pgo operator

**What is the current behavior?**
Documentation here https://crunchydata.github.io/postgres-operator/stable/installation/configuration/#_storage_configuration

**What is the expected behavior?**
**Examples of the yaml files don't seem to exist anywhere in the project like referenced.**

Are those missing for a reason?  Are there examples of NFS storage pv anywhere else in the project to reference?

> There

 are currently 3 sample pgo configuration files provided for users to use as a starting configuration -

pgo.yaml.nfs - this configuration specifies create storage to be used, this is used for NFS storage for example where you want to have a unique PVC created for each database

pgo.yaml.storageclass - this configuration specifies dynamic storage to be used, namely a storageclass that refers to a dynamic provisioning strorage such as StorageOS or Portworx, or 

> GCE.

**Comment by jmccormick2001** [comment]
this is an error in the documentation, those template examples are no longer used, instead
the default pgo.yaml file conf/postgres-operator/pgo.yaml includes an example of
specifying a storage config for each supported type (nfs, hostpath, storage class).  This documentation error is soon to be updated with the 3.5 release which is going to go out this week.

**Comment by chrisdrew1** [comment]
Thank you.
