### ISSUE TITLE
3.5.0 Documentation doesn't have any "Custom Config" section

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#558]
**Describe the bug**
Latest 3.5.0 docs don't have "Custom Config" section. but it still works same way
3.4.0 docs already unavailable

**To Reproduce**
1. Go to 'https://crunchydata.github.io/postgres-operator/stable/#documentation'
2. Search for  on 'pgo-custom-pg-config'

**Expected behavior**
Should be there

**Additional context**
How can one get versioning of the docs?

**Comment by lkhomenk** [comment]
94e3b6effd49e6d037838ba7dd41a8a53c107b35 SHA . latest commit just in case

**Comment by cahoonpwork** [comment]
This should be fixed in the next Operator release's documentation.  We will add some information about custom config.  The 3.4.0 files are located at https://github.com/CrunchyData/postgres-operator/blob/3.4.0/hugo/content/ if you need/want to reference them.
