### ISSUE TITLE
Enable managment via Operator Framework - Operator Lifecycle Manager (OLM)

### ISSUE THREAD

**Issue by ron1** [CrunchyData/postgres-operator#559]
**What is the motivation or use case for the feature?**
Installation and management of the Postgres Operator should be consistent with other Operators available in the Operator Marketplace.

**Describe the solution you'd like**
The Operator Lifecycle Manager (OLM) component of the Operator Framework (https://github.com/operator-framework/operator-lifecycle-manager) provides a declarative way to install, manage, and upgrade operators and their dependencies in a cluster. Some users may want to use OLM to install and manage the Postgres Operator as opposed to a Helm Chart, yaml manifests, or scripts.

Provide the resources needed to make the Postgres Operator available in the OLM Catalog and document the process for registering such resources with OLM.

Git repository https://github.com/operator-framework/community-operators/tree/master/community-operators appears to now be available to host such a contribution.

**Comment by lkhomenk** [comment]
for above one would need https://github.com/CrunchyData/postgres-operator/issues/537 . and that might not work with current approach with `pgo` binary as user interface to manage operator

**Comment by jmccormick2001** [comment]
an update, the Operator is first going to be changed to run in its own namespace and service n-number of user namespaces, that work has started and I expect it to be present in 3.6.0.  After that, our goal is to support a tighter integration into Openshift.  regards.

**Comment by ron1** [comment]
OLM allows for multiple installModes including OwnNamespace, SingleNamespace, MultiNamespace, and AllNamespaces. There is no reason why the current v3.5.0 operator couldn't have a CSV that only supports installMode type OwnNamespace. Then when v3.6.0 is released, its CSV could support additional installMode types. It would be ideal if the CrunchyData Postgres Operator integrated with OLM sooner rather than later.

**Comment by ron1** [comment]
@jmccormick2001 See https://github.com/operator-framework/community-operators/blob/master/community-operators/postgresql/postgres-operator.v3.5.0.clusterserviceversion.yaml for what appears to be an initial implementation of this capability. Was this developed in coordination with the CrunchyData postgres-operator team? If so, I will go ahead and close this issue.

**Comment by jmccormick2001** [comment]
we are collaborating a bit on this for sure.

**Comment by ron1** [comment]
Thanks. I will go ahead and close this request.
