### ISSUE TITLE
Allow clusters to be deployed to a different namespace

### ISSUE THREAD

**Issue by woopla** [CrunchyData/postgres-operator#560]
**What is the motivation or use case for the change? **
As already discussed in #8, currently the operator can only deploy databases in the namespace it was installed in. This is sub-optimal, especially with Openshift where you are encouraged to separate concerns by creating one project per software being deployed.

**Describe the solution you'd like**
I would like to have an option to deploy a Postgres cluster in a different namespace.

**Please tell us about your environment:**

* Operating System: CentOS 7
* Where is this running; Local
* Storage being used: NFS and GlusterFS
* Container Image Tag: any
* PostgreSQL Version: any
* Platform: Openshift
* Platform Version: OKD 3.11

**Comment by jmccormick2001** [comment]
related to this Issue, we are currently working on making the Operator run cluster-wide in its own namespace, servicing any user namespace.  Should happen in 3.6.0.  regards.

**Comment by woopla** [comment]
Oh that's great, thanks for the quick follow-up @jmccormick2001

**Comment by jmccormick2001** [comment]
so this will be fixed in the upcoming 4.0 release in April, stay tuned but the Operator will support various deployment styles.
