### ISSUE TITLE
Included CentOS image doesn't work.

### ISSUE THREAD

**Issue by chrisdrew1** [CrunchyData/postgres-operator#562]
**Describe the bug**

**To Reproduce**
deploy cluster with default install

**Expected behavior**
With the default image for centos included in the pgo.yaml file it won't download.  I had to switch back to the image included in the 3.4 version

Doesn't work with : centos7-11.1-2.3.0-rc6
Works with centos7-10.6-2.2.0

Maybe the image doesn't exist?  Not sure where or how to check that.

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by lkhomenk** [comment]
centos7-10.6-2.2.0 - is a tag of crunchy-postgres and some other stuff from crunchy-containers. it comes from separate repo. and while development is really intense - versions change really fast :clap: . please check https://hub.docker.com/r/crunchydata/crunchy-postgres/tags to get a list of all valid tags for that image

**Comment by chrisdrew1** [comment]
Ah, perfect.  Thank you.
