### ISSUE TITLE
--metric usage instructions

### ISSUE THREAD

**Issue by chrisdrew1** [CrunchyData/postgres-operator#564]
** Which example are you working with? **
3.5 installation docs
**What is the current behavior?**

**What is the expected behavior?**

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider)
local
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
k8s
* Platform Version:

If possible please run the following on the kubernetes or Openshit (oc) commands and provide the result:
In the 3.4 docs I saw some usage for the --metrics setup for grafana/prometheus connectivity.  In the 3.5 docs that all appears to be gone.  Do you have it in another location that you can share?

**Comment by jmccormick2001** [comment]
take a look at the Crunchy Containers documentation for running the grafana and prometheus used by the Operator.

**Comment by cahoonpwork** [comment]
Documentation was updated to point user to Crunchy Containers in the section mentioning metrics.
