### ISSUE TITLE
manifests: please use Yaml instead of Json

### ISSUE THREAD

**Issue by devlounge** [CrunchyData/postgres-operator#578]
**What is the motivation or use case for the change? **

Readability and more condensed files

**Describe the solution you'd like**
Many manifests in this repository are written in Json instead of Yaml.
Yaml became a standard for manifests in Kubernetes projects.
As they say, Json is for computers, Yaml is for humans.

**Comment by devlounge** [comment]
Another thing, I noticed that multiple templates used by the operator have a mix of tabs and spaces.

**Comment by cahoonpwork** [comment]
Thanks for the input.  PGO.yaml is the main file that we expect users to update.  We are having internal discussions however on converting the files.
