### ISSUE TITLE
crunchydata/crunchy-postgres:centos7-11.1-2.3.0-rc6 not found

### ISSUE THREAD

**Issue by KASOGIT** [CrunchyData/postgres-operator#579]
**Describe the bug**
When creating cluster with the pgo it can't pull the image: crunchydata/crunchy-postgres:centos7-11.1-2.3.0-rc6

**To Reproduce**
1: pgo create cluster mycluster
2: kubectl describe pod <name-pod>
**Expected behavior**
Shoud pull the right image like crunchydata/crunchy-postgres:centos7-11.1-2.3.0 present on the dockerhub

**Please tell us about your environment:**

* Operating System: ubuntu 18.04
* Where is this running: local minikube
* Storage being used (NFS, Hostpath, Gluster, etc): host
* Platform Version: 3.5.0

**Comment by cahoonpwork** [comment]
It looks like the rc tag was not remove from pgo.yaml.  You will need to update  CCPImageTag:  centos7-11.1-2.3.0-rc6 and redeploy the operator it for it to pick up the correct image.

**Comment by KASOGIT** [comment]
That's what i did and images are pulled well now !
