### ISSUE TITLE
Pgbackrest restore ingnores "--storage-config" which was used during Cluster creation

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#593]
**Describe the bug**
1. Create cluster overriding storage-config "--storage-config=pvc10G --pgbackrest"
2. Create backup
3. Restore cluster
4. Restored cluster uses - PrimaryStorage from pgo.yaml

**Expected behavior**
Restore should consider storage-config which was used during cluster creation

**Additional context**
I've seen Issue #349 , but haven't found anything in 3.5.0 docs about that

**Comment by jmccormick2001** [comment]
I've created a fix for this that will be present in the upcoming 3.5.1 bug fix release.  That release will land next week.  thanks for reporting this one.
