### ISSUE TITLE
Dynamic parameters for pgbackrest

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#596]
**What is the motivation or use case for the feature? **
Currently pgbackrest has hardcoded stanza/repo-path. Which are pretty important and can't be edited dynamically or overridden. 
Situation when 1 Operator should rule multiple clusters and store archive/backup on S3 using pgbackrest
- We can't label jobs/shared-backrest-repo/restore-job pods during creation to pull some values from labels to configure repo-path\stanza
- There's no option to put pgbackrest.conf into custom config to be used wherever it's needed(e.g. as part of pgo-custom-pg-config)
- We can use `--backup-opts` to override everything after cluster is created. but default stanza-create job/archive will go to the hardcoded repo-path and stanza. and there's no option to create new stanza via pgo

**Describe the solution you'd like**
- populate labels from `--labels` to all cluster objects - as possible workaround
- add support for pgbackrest.conf as part of custom-config

**Describe any alternatives you've considered**
Maybe it's more about S3 support by pgo-pgbackrest, but all these should improve configuration flexibility

**Comment by lkhomenk** [comment]
Update with some recent findings : 
- there's still a variable called GLOBAL_PGBACKREST_CUSTOM_CONFIGMAP in utils.go. It confused me a bit. As in November there was an update which removed pgbackrest.conf from pgo-custom-config configmap and "pgbackresrt-env-vars" was introduced. But pgbackresrt-env-vars can't use many of cluster fields(Cluster Name, Database) and it can't be used neither in backrest-repo-template nor in restore job config files. @jmccormick2001 do have a plan to add custom-configmap for pgbackrest?

**Comment by jmccormick2001** [comment]
yeah, that is a remnant of the old way we did pgbackrest configuration, it needs to be removed which I'll make a note to do...going forward, we will try to use the backrest environment variables to configure backrest, injecting them into the pods as needed.  thanks for catching this one.
