### ISSUE TITLE
Use Kubernetes secrets to store credentials

### ISSUE THREAD

**Issue by pst** [CrunchyData/postgres-operator#6]
Currently all credentials seem to be stored in the TPRs. Is it planned to switch this to using Kubernetes secrets? This way the operator could generate credentials while deploying a new database or cluster and store them in secrets.

**Comment by jmccormick2001** [comment]
very good idea, would support some more advanced security features down the road as well.

**Comment by jmccormick2001** [comment]
I've merged into master a cut at using secrets...it will generate the passwords if you do not specify a password in the config...you can view the generated passwords using 'pgo show mycluster --show-secrets=true'
