### ISSUE TITLE
--pgbouncer doesn't trigger all crunchy-pgbouncer logic

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#603]
**Describe the bug**
--pgbouncer flag doesn't add `PGBOUNCER_PASSWORD` which is crucial for setting up pgbouncer.
`/opt/cmp/bin/modules/pgbouncer.sh` depends on this variable. w/o it default auth_query is useless:
`auth_query = SELECT username, password from pgbouncer.get_auth($1)` while there's no `pgbouncer.get_auth` function

**To Reproduce**
1. create cluster with `--pgbouncer`
2. check logs for `pgBouncer enabled.  Running setup SQL..`

**Expected behavior**
This logic should be handled by applying `--pgbouncer` flag

**Please tell us about your environment:**

* Container Image Tag: 2.3.1
* PostgreSQL Version: 10.7
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 3.5.0

**Additional context**
Manual setup of this variable sorts this out. Maybe it could be just documented

**Comment by lkhomenk** [comment]
@jmccormick2001 I've seen some comments on items related to pgbouncer, that it should get some fixes in 3.6. Can this one also get into 3.6?

**Comment by jmccormick2001** [comment]
we are working on this issue actually, it didn't make it into today's 3.5.1 release but hope to get it into 3.5.2...that code typically lives in the develop branch when it is ready...

**Comment by jmccormick2001** [comment]
@flamingdumpster

**Comment by lkhomenk** [comment]
awesome news. I check it back in 3.5.2. great!
