### ISSUE TITLE
ClusterName length issue

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#606]
**Describe the bug**
It should be limited.
When one uses pgbackrest  - restore job might fail because of to big name
"backrest-restore-my-postgresql-realtime-to-my-postgresql-realtime-enyh", which exceeds 64 symbols labels limitation

**To Reproduce**
1. Create cluster with the name of 20 symbols and --pgbackrest
2. create backup
3. init restore
4. See error. Restore job pod won't be created

**Expected behavior**
maybe avoiding such labels or adding warning msg telling that huge names are bad idea would be enough

**Comment by jmccormick2001** [comment]
should be fixed in 3.5.1.
