### ISSUE TITLE
Helm chart not updated

### ISSUE THREAD

**Issue by david-ecc** [CrunchyData/postgres-operator#618]
The helm-chart in release 3.5.1 is not updated and still uses version 3.5.0 (operator) und 2.3.0 (container).

```
$ git checkout 3.5.1
$ grep -ri '3.5.0\|2.3.0' chart/
chart/postgres-operator/Chart.yaml:appVersion: 3.5.0
chart/postgres-operator/files/postgres-operator/pgo.yaml:  CCPImageTag:  centos7-11.1-2.3.0
chart/postgres-operator/files/postgres-operator/pgo.yaml:  COImageTag:  centos7-3.5.0
chart/postgres-operator/values.yaml:  tag: centos7-3.5.0
chart/postgres-operator/values.yaml:  ccp_image_tag: "centos7-11.1-2.3.0"
chart/postgres-operator/values.yaml:  co_image_tag: "centos7-3.5.0"

```

**Comment by cahoonpwork** [comment]
Thanks for letting us know.   I will verify/fix our script that updates versions.

**Comment by cahoonpwork** [comment]
this will be updated in the next release and I scripted the missing versions so we shouldn't have the issue in the future.

**Comment by domcar** [comment]
@cahoonpwork I edited manually the Tag but I get this error when I deploy:
```
time="2019-03-13T15:12:59Z" level=debug msg="loading path [/pgo-config/pgdump-job.json]"
time="2019-03-13T15:12:59Z" level=error msg="open /pgo-config/pgdump-job.json: no such file or directory"
time="2019-03-13T15:12:59Z" level=error msg="error loading template path=/pgo-config/pgdump-job.jsonopen /pgo-config/pgdump-job.json: no such file or directory"
panic: open /pgo-config/pgdump-job.json: no such file or directory

goroutine 1 [running]:
github.com/crunchydata/postgres-operator/util.LoadTemplate(0x118baad, 0x1b, 0xc00021e700)
	/opt/cdev/src/github.com/crunchydata/postgres-operator/util/util.go:96 +0x46c
github.com/crunchydata/postgres-operator/operator.Initialize()
	/opt/cdev/src/github.com/crunchydata/postgres-operator/operator/common.go:151 +0x6a9
main.main()
	/opt/cdev/src/github.com/crunchydata/postgres-operator/postgres-operator.go:65 +0x1bf
```

Do I need to edit something else other than `pgo.yam` and `values.yaml` ?

**Comment by jecho** [comment]
looks like the file is missing; i had to copy a couple from the conf dir over to its respective chart dir

**Comment by domcar** [comment]
Yes, two files are missing
  - postgres-operator/files/postgres-operator/cluster/1/pgdump-job.json
  - postgres-operator/files/postgres-operator/cluster/1/pgrestore-job.json

**Comment by david-ecc** [comment]
In release 3.5.2 this file is missing:
chart/postgres-operator/files/postgres-operator/pgbench-job.json

**Comment by domcar** [comment]
@david-ecc Yes, the file is missing. This is very disappointing, it looks like the chart is not tested at all
