### ISSUE TITLE
Restore not working

### ISSUE THREAD

**Issue by domcar** [CrunchyData/postgres-operator#638]
**Describe the bug**
After a backup is successfully taken I tried to restore it but it fails

**To Reproduce**
1. Backup `./pgo-mac backup dom-cluster`
2. Restore `./pgo-mac restore dom-cluster`
Logs from operator:
```
time="2019-03-14T07:16:02Z" level=error msg="template: /pgo-config/backrest-restore-job.json:85:10: executing \"/pgo-config/backrest-restore-job.json\" at <.NodeSelector>: can't evaluate field NodeSelector in type backrest.restorejobTemplateFields"
```
And if I run the restore again:
```
time="2019-03-14T07:24:19Z" level=error msg="restore workflow error: depList not equal to 1 service-name=dom-cluster"
```

The same error occurs if I use a `--backup-type=pgbackrest`

* Operating System: Mac
* Where is this running: GKE
* Storage being used (NFS, Hostpath, Gluster, etc): dynamic on GKE
* Container Image Tag: centos7-3.5.0
* PostgreSQL Version: centos7-11.1-2.3.0
* Platform (Docker, Kubernetes, OpenShift): Kubernetes 1.11

**Additional context**
I deployed the Operator using the Helm Chart

**Comment by jmccormick2001** [comment]
pgo restore is only for a pgbackrest restore, this is not clear in the docs and will get fixed!

here are the restore steps for backrest:

pgo create cluster mybackrest --pgbackrest
pgo backup mybackrest --backup-type=pgbackrest
pgo restore mybackrest

**Comment by domcar** [comment]
thanks @jmccormick2001 I figured it out meanwhile.
Unfortunately I can't use pgbackrest because of https://github.com/CrunchyData/postgres-operator/issues/635

Anyway I still have some problems with pg_basebackup when I run
`./pgo-mac.3.5.1 create cluster restored --backup-path=/pgdata/mycluster-backups/2019-03-14-13-19-07 --backup-pvc=mycluster-backup --secret-from=dom-cluster --replica-count=1`

- --secret-from does not want a secret but the cluster name, but if the cluster is gone the secret does not exists anymore
- Even by recreating the secret it looks like the restored cluster does not have the same data as the first one

these are the steps I run:

- ./pgo-mac.3.5.1 create cluster mycluster --password=ciaociao --replica-count=1
- Logged in postgres and created a test DB
- Backup: ./pgo-mac.3.5.1 backup mycluster
- destroy: ./pgo-mac.3.5.1 delete cluster  mycluster
- restore: ./pgo-mac.3.5.1 create cluster mycluster-backup --backup-path=/pgdata/mycluster-backups/2019-03-14-13-19-07 --backup-pvc=mycluster-backup --secret-from=mycluster --replica-count=1

Did I do something wrong?

**Comment by jmccormick2001** [comment]
the backup path should be mycluster-backups/2019-03-14-13-19-07
don't include the /pgdata in that.

**Comment by domcar** [comment]
Thanks a lot, this helped and I was able to restore the cluster with data in it.

Still another problem, the primary cluster is created without problem, but the replica does not start because the backup PV is already attached to the primary cluster. This is the error from the describe command:

```
AttachVolume.Attach failed for volume "pvc-174a56be-4700-11e9-a808-42010a9c0221" : googleapi: Error 400: RESOURCE_IN_USE_BY_ANOTHER_RESOURCE - The disk resource 'REDACTED-pvc-174a56be-4700-11e9-a808-42010a9c0221' is already being used by 'REDACTED-c616b3ed-wj02'
```

Since I'm using k8s on GCE i have readonlyonce as accessmode, in the documentation I didn't read anywhere that this should not be used. Can you help?

**Comment by cahoonpwork** [comment]
@domcar I suspect you have multi-zone and multi-node out in GKE.  Take a look at this document: https://github.com/CrunchyData/postgres-operator/blob/develop/hugo/content/Design/_index.md , to update your storageclass.

**Comment by domcar** [comment]
@cahoonpwork No, my cluster is in a single zone, I think the point is not multi-zone but one node or many node: as the docs say, a Volume with ReadWriteOnce can be mounted by a single Node:
https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#access_modes
