### ISSUE TITLE
Authentication falied for some command

### ISSUE THREAD

**Issue by domcar** [CrunchyData/postgres-operator#640]
**Describe the bug**
Few client commands fail with authentication failed

**To Reproduce**
./pgo-mac.3.5.1 scale dom-cluster --replica-count=1   
WARNING: Are you sure? (yes/no): yes
Error: Authentication Failed: 401

Instead I can execute without problems other command like create, restore etc.
**Please tell us about your environment:**
Operator 3.5.1 deployed with Helm chart

* Operating System: MacOs
* Where is this running ( Local, Cloud Provider): GKE
* Storage being used (NFS, Hostpath, Gluster, etc): GCE 
* Container Image Tag: 3.5.1
* PostgreSQL Version: centos7-11.2-2.3.1
* Platform (Docker, Kubernetes, OpenShift): K8S

**Comment by cahoonpwork** [comment]
@domcar  I have not experienced that, I test against GKE on centos 7.  Is it the same command(s) every time or is it randomly happening?  Is there anything in the logs when this happens?

**Comment by domcar** [comment]
It's always the same commands, I know of `update` and `scale`. 
For example the folowing two commands:
```
/pgo-mac.3.5.1 update cluster dom-cluster --autofail=true                      
WARNING: Are you sure? (yes/no): yes
Error: Authentication Failed: 401
```
And after
```
➜  ~/techhub.clara.net/domenico.caruso/gke-onthefly/pgo-crunchy git:(feature/crunchy-pgo) ✗ ./pgo-mac.3.5.1 create cluster test --password=ciaociao --replica-count=1                                    
created Pgcluster test
workflow id 3f654b83-3b0f-4e63-bcc0-af6e2630e5f6
```

The api-server show (for a failed update command):
```
time="2019-03-15T12:31:38Z" level=error msg="Authentication Failed UpdateCluster username=[username]"
time="2019-03-15T13:44:21Z" level=debug msg="UpdateClusterHandler parameters name [dom-cluster] version [3.5.1] selector [] namespace [] autofail [true]"
time="2019-03-15T13:44:21Z" level=debug msg="Authentication Attempt UpdateCluster username=[username]"
time="2019-03-15T13:44:21Z" level=info msg="BasicAuthzCheck pgoadmin UpdateCluster false"
time="2019-03-15T13:44:21Z" level=error msg="Authentication Failed UpdateCluster username=[username]"
```

**Comment by domcar** [comment]
Is it possible that it is because here the permissions of scale and update are missing?
https://github.com/CrunchyData/postgres-operator/blob/3.5.1/chart/postgres-operator/files/apiserver/pgorole

**Comment by domcar** [comment]
Yes, that's the problem, I added `UpdateCluster` to the file and redeployed the cluster, now I'm able to update it

**Comment by domcar** [comment]
FYI: I needed to add also `CreateDump, RestoreDump, UpdateCluster, ScaleCluster`

**Comment by cahoonpwork** [comment]
Looks like this is fixed in the develop branch.  We will have a 3.5.2 release out this month that will have it.

**Comment by domcar** [comment]
Great, thx
