### ISSUE TITLE
Inconsistent failover with "failover_strategy_1" in v3.5

### ISSUE THREAD

**Issue by cotigao** [CrunchyData/postgres-operator#652]
The failover with the default strategy does not seem to always work  (with autofail enabled). It sometimes fails with the message `more than 1 primary pod found when trying to delete primary xyz` . I created the cluster with pgo and replica count = 2 and deleted the primary pod with `kubectl delete pod ....`

As a quickfix ,I modified the `deletePrimary()` function inside failover_strategy_1.go, to wait till it strictly gets only 1 primary pod . (by running `kubeapi.GetPods` in a loop with some sleep per iteration), But this leads to a cascading deletion of the primary pods (failover happens more than once). i.e If I had 1 primary and 2 replicas, I am left with 1 (new)primary and no replicas.

I am using v3.5 on kubernetes v1.13

**Comment by cahoonpwork** [comment]
@cotigao 
We just pushed out 3.5.2 yesterday with a updates for failover, If you can use try that version and see if you are stilling having issues.

**Comment by lkhomenk** [comment]
@cotigao what about `AutofailReplaceReplica` ? we have enabled it. and when we force delete Primary - first k8s recovers new pod inside same deployment(A) and after that postgres-cluster - removes that deployment(A) and creates a new one
