### ISSUE TITLE
Error: could not load example.com.crt and example.com.key

### ISSUE THREAD

**Issue by ksugiu** [CrunchyData/postgres-operator#654]
Hi,

I'm trying to use pgo client (version 3.5.2) on kubernetes but i can't contact my chrunchy cluster because my pgo client don't see my certificates:

This is how i launch the client : 

`pgo version --apiserver-url=https://10.43.195.3:8443 --pgo-client-key=/certs/ilk
ik8s.fr.key --pgo-client-cert=/certs/ilkik8s.fr.crt --pgo-ca-cert=/certs/ca.crt --debug`

And this is the return:

`DEBU[0000] debug flag is set to true
DEBU[0000] in initConfig with url=https://10.43.195.3:8443
DEBU[0000] GetCredentials called
DEBU[0000] looking in /root/.pgouser for credentials
DEBU[0000] /root/.pgouser found
DEBU[0000] pgouser file found at /root/.pgouser contains username:password

DEBU[0000] [username password]
DEBU[0000] username=[username] password=[password]
Error: could not load example.com.crt and example.com.key`

I don't understand why pgo don't use the pgo parameters. Any Idea ?

Thanks

**Comment by lkhomenk** [comment]
`.pgouser` file is more about pgo utility permissions. it has pretty granulated access right - check docs about BaseAuth in pgo or disable it
https://crunchydata.github.io/postgres-operator/stable/installation/ 
Just create `~/.pgouser` file
