### ISSUE TITLE
LivenessProbe and ReadinessProbe Needed

### ISSUE THREAD

**Issue by fanzhang15** [CrunchyData/postgres-operator#659]
**What is the motivation or use case for the change? **
Test the liveness and readiness of the apiserver, scheduler and operator contaners.

**Describe the solution you'd like**
Need to test the liveness and readiness of each container spperately.
Is there such a plan or quick solution?

**Please tell us about your environment:**

* Operating System: MacOS
* Where is this running ( Local, Cloud Provider) IBM Cloud
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: centos7-3.5.1
* PostgreSQL Version: N/A
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.12

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jmccormick2001** [comment]
thanks, I've added a liveness probe and readiness probes to the operator pod, which will go into the 4.0 release when it comes out.

**Comment by fanzhang15** [comment]
@jmccormick2001 Thanks. When shall we expect the formal release of 4.0 with these changes?

**Comment by jmccormick2001** [comment]
plan is to release 4.0 in the mid-late April timeframe, so soon.  The code for that lives in the develop branch currently if you want to check it out.  regards.

**Comment by fanzhang15** [comment]
@jmccormick2001 I see the RC11 is preparing for the formal release for 4.0. Could you give us a better estimate since this impacts our product delivery date? Thanks.

**Comment by jmccormick2001** [comment]
2 weeks in the window we are aiming for, final development and testing is underway.
