### ISSUE TITLE
pgo.exe v3.5.2 reports error on each command

### ISSUE THREAD

**Issue by PowerStateFailure** [CrunchyData/postgres-operator#667]
**Describe the bug**
Windows build of `pgo` utility (v3.5.2, taken from `/releases` page) reports error on each command:
```
$ pgo.exe test
Error:  open /tmp/pgo-bash-completion.out: The system cannot find the path specified.
```
_It doesn't affect any behavior of utility_, just kinda annoying

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

* Operating System: Windows 7
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by jmccormick2001** [comment]
thanks for spotting this one, it will be addressed.
