### ISSUE TITLE
pgo_mac broken for 3.5.2

### ISSUE THREAD

**Issue by ook** [CrunchyData/postgres-operator#699]
**Describe the bug**

pgo_mac doesn't work, for any command.

**To Reproduce**

1) Follow instructions to install postgres-operator 3.5.2
2) download and pgo_mac 3.5.2, make it executable

**Expected behavior**

**Screenshots**

```
kubectl -n demo port-forward postgres-operator-54485967c7-9lqhf 8443:8443 &
bash-3.2$ export CO_APISERVER_URL=https://localhost:8443
bash-3.2$ pgo version
INFO[0000] &{0xc000044200 {0 0} false 0xc000096050 <nil> 0x12881c0}

Error: invalid character 'N' looking for beginning of value
INFO[0000] invalid character 'N' looking for beginning of value
Error: invalid character 'N' looking for beginning of value
```

**Please tell us about your environment:**

* Operating System: k8s cluster on baremetal (5nodes, pv on GlusterFS)
* Hosted online.com
* Storage glusterfs
* Container Image Tag: crunchydata/pgo-scheduler:centos7-3.5.2
* PostgreSQL Version:
* Platform Kubernetes (via rancher2)
* Platform Version: 1.11.6

**Additional context**

**Comment by cahoonpwork** [comment]
Can you provide the steps you did to install the pgo client?  Was it just downloading and making it executable or did you also setup the certs and .pgouser file?

**Comment by ook** [comment]
Hi @cahoonpwork . I strictly follow the instructions:

Got `pgo` from 3.5.2 release: 
```
wget https://github.com/CrunchyData/postgres-operator/releases/download/4.0.0-rc5/pgo-mac
mv pgo-mac pgo
chmod +x pgo
```

Certs were generated previous step:

```
bash-3.2$ ls -l $COROOT/conf/postgres-operator/ | grep server
-rw-r--r--  1 thomas  staff  1196 11 avr 15:20 server.crt
-rw-r--r--  1 thomas  staff  1704 11 avr 15:20 server.key
```

Even forced on the pgo command line, it fails:

```
bash-3.2$ pgo version --pgo-ca-cert=$COROOT/conf/postgres-operator/server.crt --pgo-client-cert=$COROOT/conf/postgres-operator/server.crt --pgo-client-key=$COROOT/conf/postgres-operator/server.key
INFO[0000] &{0xc00035c240 {0 0} false 0xc00009c050 <nil> 0x12881c0}

Error: invalid character 'N' looking for beginning of value
INFO[0000] invalid character 'N' looking for beginning of value
Error: invalid character 'N' looking for beginning of value
```

And the `~/.pgouser` file is already preset.

**Comment by cahoonpwork** [comment]
Looks like you have the 4.0.0-rc5 pgo client.  There 4.0 client isn't compatible with 3.5.x. You can grab the 3.5.2 client here: https://github.com/CrunchyData/postgres-operator/releases/download/3.5.2/pgo-mac .

Let me know if that works for you.

**Comment by ook** [comment]
Sorry, it was a bad copy when filling my previous comment. It was already the 3.5.2:

```
wget https://github.com/CrunchyData/postgres-operator/releases/download/3.5.2/pgo-mac
chmod +x pgo-mac
ls -l | grep pgo
-rwxr-xr-x@ 1 thomas  staff  31923576 11 avr 15:34 pgo
-rwxr-xr-x@ 1 thomas  staff  31923576 12 avr 15:12 pgo-mac
diff pgo pgo-mac
echo $?
0
pwd
/Users/thomas/bin
```
Then
```
type pgo-mac
pgo-mac is hashed (/Users/thomas/bin/pgo-mac)
pgo-mac version --pgo-ca-cert=$COROOT/conf/postgres-operator/server.crt --pgo-client-cert=$COROOT/conf/postgres-operator/server.crt --pgo-client-key=$COROOT/conf/postgres-operator/server.key
INFO[0000] &{0xc0003381c0 {0 0} false 0xc000076060 <nil> 0x12881c0}

Error: invalid character 'N' looking for beginning of value
INFO[0000] invalid character 'N' looking for beginning of value
Error: invalid character 'N' looking for beginning of value
```
So, no change.

**Comment by cahoonpwork** [comment]
No problem.  Give us a bit and we will test it out again.  Currently testing 4.0.0-rc5 and not seeing that issue.

**Comment by jmccormick2001** [comment]
verify that the .pgouser file is in $HOME and that the credentials in it are valid and match those in the server's pgouser config file.  In 3.5.2, if you have a wrong id/psw it will throw an error like that back to the user.

**Comment by ook** [comment]
@jmccormick2001 that was it! There was a typo in the password.

I noticed there's minor errors in the documentation during installation, would you like a PR about it?

**Comment by jmccormick2001** [comment]
sure, a PR against the develop branch and we'll take a look at it, thanks for contributing!
