### ISSUE TITLE
Use K8s ConfigMap instead of PVC for /data

### ISSUE THREAD

**Issue by pst** [CrunchyData/postgres-operator#7]
Similarly to using Secrets #6 it seems using ConfigMaps instead of a hostPath PVC would make more sense to store the operator configuration and templates. Or is there a reason why ConfigMaps wouldn't work here?

**Comment by jmccormick2001** [comment]
I'm planning on using ConfigMaps for the operator config files in the next release.

**Comment by jmccormick2001** [comment]
I've modified the operator to now look for strategy templates in a configmap named operator-conf.  The examples/operator/run.sh script builds the ConfigMap, and the deployment.json file is updated to mount the configmap under /operator-conf...this code is now merged into master.
