### ISSUE TITLE
api group and deep copy

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/postgres-operator#70]
use a different api group and examine deep copy reqts.

**Comment by munnerz** [comment]
Hey - nice project 😄 

I'm not sure if you're aware, but the Kubernetes community has created tooling to generate things like DeepCopy functions, informers, listers and even a typed REST client. I'm not sure if it fits your requirements (with pgo, and your custom apiserver implementation), but could definitely be useful if you just want to generate deep copies.

The generators themselves are here: https://github.com/kubernetes/code-generator
An example of them in use: https://github.com/kubernetes/sample-controller
& a blog post explaining how & why they can be used: https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/

**Comment by jmccormick2001** [comment]
thanks for the links, very useful and timely.  regards

**Comment by jmccormick2001** [comment]
done, merged deep copy generated code into master, build is now based on kubernetes-1.8.5 which requires the deepcopy methods, leaving the api group the same for now.  release 2.3 will be based on this new build.
