### ISSUE TITLE
[Support] How to enable SSL

### ISSUE THREAD

**Issue by davi5e** [CrunchyData/postgres-operator#703]
## Which example are you working with?
Trying to create a PostgreSQL cluster using PGO. Said cluster should have SSL enabled and we can't find a documentation on how to do this.

## What is the current behavior?
No idea how to proceed. Found [this](https://github.com/CrunchyData/postgres-operator/issues/395) and [this](https://github.com/CrunchyData/crunchy-containers/tree/master/examples/kube/custom-config-ssl), but still no progress.

## What is the expected behavior?
Create the primary and all replicas so they have SSL enabled, with the keys/certs we'd generate (possibly using a Secret in the same Namespace PGO inhabits).

## Other information *(e.g. detailed explanation, related issues,  etc)*
We are basically following the documentation. Everything works, this is the only configuration we haven't figured out how to properly set.

## Please tell us about your environment:

**Operating System:**
COS
**Where is this running ( Local , Cloud Provider)
GCP GKE
**Storage being used (NFS, Hostpath, Gluster, etc):**
Rook
**Container Image Tag:**
centos7-11.2-2.3.1
**PostgreSQL Version:**
11.2
**Platform (Docker, Kubernetes, OpenShift):**
Kubernetes
**Platform Version:**
3.5.0 installed via [OperatorHub.io](https://operatorhub.io/operator/alpha/postgres-operator.v3.5.0)

**Comment by jmccormick2001** [comment]
https://github.com/CrunchyData/postgres-operator/tree/develop/examples/custom-config-ssl

we are working up an example, see above, not fully tested but would be great if you could try this out and let us know how it works for you.  regards.

**Comment by davi5e** [comment]
@jmccormick2001 I'm quite busy this week, I'll be sure to give it a try and come back to you as soon as I can

**Comment by fanzhang15** [comment]
@jmccormick2001 We need SSL but not between the client and the server, but between the master and slave nodes when doing streaming replication. pgpool.conf should be able to support this feature. How to add this feature into the CRD deployment?

For example, I run `$PGO_CMD -n $NS create -f $DIR/fromcrd.json`
How to configure the fromcrd.json or other files when doing this command to achieve what I need?

Thanks.
