### ISSUE TITLE
[Support] Behavior of upgrade and restore

### ISSUE THREAD

**Issue by rqtx** [CrunchyData/postgres-operator#740]
** Which example are you working with? **

Trying to upgrade and restore PostgreSql cluster without creating a new pvc to new replicas.

**What is the current behavior?**

I am trying to understand how upgrade and restore commands works. I notice that both commands create a new pvc to new replicas. Is it possible to avoid this behavior, like using the pvc from the old cluster on the new one?

Another behavior that I notice was that, on upgrade, the old replica keeps running. Do I have to remove it manually?

**What is the expected behavior?**

I do not want a new pvc when doing an upgrade or restore.

**Please tell us about your environment:**

* Operating System:
COS
* Where is this running ( Local , Cloud Provider)
GCP GKE
* Storage being used (NFS, Hostpath, Gluster, etc):
Rook
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
Kubernetes
* Platform Version:
3.5.0 installed via OperatorHub.io

**Comment by davi5e** [comment]
Me and my team are very interested in this as well...
