### ISSUE TITLE
Cluster fails to start due to inadequate directory permissions

### ISSUE THREAD

**Issue by shrinandj** [CrunchyData/postgres-operator#75]
I tried creating a cluster using this postgres-operator. My Kubernetes cluster is deployed on AWS. After fixing some problems with the PVC access modes (had to change the to ReadWriteOnce instead of the default ReadWriteMany), I was able to get the operator up and running. The CRDs showed up and the controller was running without errors.

However, when I create the cluster using `pgo create cluster xraydb --series=2 --labels=project=xray`, the command succeeded but the cluster doesn't come up. The cluster pod is in the Running state. The pod's logs show:

```
+ pg_isready --port=5432 --host=xraydb0-341844318-pkpwz --username=primaryuser --timeout=2
xraydb0-341844318-pkpwz:5432 - no response
+ '[' 2 -eq 0 ']'
+ sleep 2
+ true
+ pg_isready --port=5432 --host=xraydb0-341844318-pkpwz --username=primaryuser --timeout=2
xraydb0-341844318-pkpwz:5432 - no response
+ '[' 2 -eq 0 ']'
+ sleep 2
+ true
+ pg_isready --port=5432 --host=xraydb0-341844318-pkpwz --username=primaryuser --timeout=2
xraydb0-341844318-pkpwz:5432 - no response
+ '[' 2 -eq 0 ']'
+ sleep 2
```

Looking at the description of the pod using kubectl describe pod probably shows the real reason for the failure:
```
  Warning  Unhealthy              1s (x83 over 13m)  kubelet, ip-172-20-36-248.us-west-2.compute.internal  Readiness probe failed: setting PGROOT to  /usr/pgsql-9.6
chown: cannot access '/pgdata/xraydb0': No such file or directory
chown: cannot access '/pgwal/xraydb0-wal': No such file or directory
psql: could not connect to server: No such file or directory
  Is the server running locally and accepting
  connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

The pod's spec shows that pgdata should be mounted from a PVC, which it is. However, the "postgres" user does not have permissions to create files/dirs inside it.

```
bash-4.2$ mount | grep pgdat
/dev/xvdcp on /pgdata type ext4 (rw,relatime,data=ordered)
bash-4.2$ ls -lart / | grep pgdata
drwxr-xr-x   3 root     root      4096 Nov 13 23:34 pgdata
bash-4.2$ mkdir /pgdata/xraydb0
mkdir: cannot create directory '/pgdata/xraydb0': Permission denied
bash-4.2$ id
uid=26(postgres) gid=26(postgres) groups=26(postgres)
``` 

The pods show up to be in Running state, but none of the pods are ready.
```
xraydb0-341844318-pkpwz              0/1       Running   0          21m
xraydb1-1907719321-7g7fd             0/1       Running   0          21m
```

**Comment by jmccormick2001** [comment]
Try setting the fsGroup setting to 26 in the pgo.yaml config

**Comment by shrinandj** [comment]
Perfect. That did the trick. I found the documentation [here](https://github.com/CrunchyData/postgres-operator/blob/master/docs/config.asciidoc) for the FsGroup option.
