### ISSUE TITLE
modifying max_connection in postgresql.conf

### ISSUE THREAD

**Issue by pmpetit** [CrunchyData/postgres-operator#753]
** Which example are you working with? **

my example is from "./examples/quickstart.sh" and i'd like to change max_connections

**What is the current behavior?**

 max_connections 
-----------------
 100

**What is the expected behavior?**

 max_connections 
-----------------
 150

i have search, but i do not find a way to chnage it except : in 
https://crunchydata.github.io/postgres-operator/stable/cli/pgo_create_cluster/
"--custom-config string            The name of a configMap that holds custom PostgreSQL configuration files used to override defaults."

but i do not find any example of configMap....

thanks

**Comment by jmccormick2001** [comment]
Hi, you can add a custom environment variable setting in postgres-operator/conf/postgres-operator/cluster/1/cluster-deployment-1.json 

the env var you set is MAX_CONNECTIONS

if you do that, and redeploy the operator that will cause the max_connections to be set in the postgres container.

regards.

**Comment by cahoonpwork** [comment]
Here is some documentation for using custom config: https://crunchydata.github.io/postgres-operator/latest/gettingstarted/design/custom-config/   if you want to go that way.

**Comment by pmpetit** [comment]
Thanks, it was what a was looking for...
