### ISSUE TITLE
Possible to have pgo to manage any namespace?

### ISSUE THREAD

**Issue by ajoyej** [CrunchyData/postgres-operator#758]
Hello,
I have installed pgo 4.0.0-rc10. 
All run ok. 

However, I have a question related to the namespaces pgo manages.
To what I understand, we have to define in the inventory file which namespaces pgo will manage and then run the ansible-playbook command.

Is there a way to have pgo potentially managing any namespaces without running a ansible-playbook update?

A side question related to this one, should we have dedicated namespace that are managed by pgo or could we use an existing namespace containing pod of a given application

Thanks and regards,
José

**Comment by jasonodonnell** [comment]
Hi @ajoyej,

Currently the playbooks do not support manage all namespaces at this time.

> A side question related to this one, should we have dedicated namespace that are managed by pgo or could we use an existing namespace containing pod of a given application

You can add operator to an existing namespace.

Hope that helps!

**Comment by mariuszb81** [comment]
Hi @ajoyej 
where did you find pgo executable after installation? I can't locate it. therefore my pgo command doesn't work.
Thanks.

**Comment by ajoyej** [comment]
Hi @mariuszb81,

I found it under Release - 4.0.0-rc10  - Assets:

https://github.com/CrunchyData/postgres-operator/releases/download/4.0.0-rc10/pgo.exe

José

**Comment by mariuszb81** [comment]
@ajoyej 
Thank you!!!!
My verson (linux) was here:
https://github.com/CrunchyData/postgres-operator/releases/download/4.0.0-rc10/pgo

Thanks alot

**Comment by hairmare** [comment]
It looks like pgo nowadays supports managing any namespaces when using an empty `namespace=''` variable in the Ansible inventory. The check that skips validating namespaces if none are given is here:
https://github.com/CrunchyData/postgres-operator/blob/13f7e02e56ff89deb50fd998d69a7149341c2175/util/util.go#L372-L378
I'm not sure if this is considered a supported feature and currently the operator still needs a restart so it notices new namespaces.

**Comment by hairmare** [comment]
Seemlingly the scheduler component is the only one that doesn't support the "empty namespace equals all namespaces" concept:

https://github.com/CrunchyData/postgres-operator/blob/13f7e02e56ff89deb50fd998d69a7149341c2175/pgo-scheduler/pgo-scheduler.go#L68-L71

Are there any plans for supporting running databases on all the namespaces available to the operator through the K8s API?

**Comment by jmccormick2001** [comment]
there are plans/ideas we are thinking of that would allow you to dynamically add namespaces to the Operator's list of watched namespaces, and also apply the RBAC into those namespaces...that would be a great improvement we think over file based configuration like it works today.
