### ISSUE TITLE
When will pgo 4.x be available (not the RC version)? 

### ISSUE THREAD

**Issue by ajoyej** [CrunchyData/postgres-operator#767]
Hello,

Do you have any date for public availability of pgo 4.x (not the RC)?

Thanks and regards,
José

**Comment by cahoonpwork** [comment]
We are targeting the first week of June.

**Comment by tux-o-matic** [comment]
@ajoyej  It's live now.

**Comment by cahoonpwork** [comment]
@ajoyej  @tux-o-matic 
4.0.0 has been tagged, the Images and PGO client will be pushed out this morning.
