### ISSUE TITLE
Error: pgtasks.crunchydata.com "pgpool-reconfigure-democluster" already exists if deleting then creating a user

### ISSUE THREAD

**Issue by tumluliu** [CrunchyData/postgres-operator#772]
** Which example are you working with? **
when I try deleting and then creating a user with `pgo`:
```
pgo delete user demo2 --selector name=democluster --namespace pgo
WARNING: Are you sure? (yes/no): yes
pgo create user demo2 --selector name=democluster --db launchpad --managed --valid-days 180 --namespace pgo
```

**What is the current behavior?**
I got an error:
```
Error: pgtasks.crunchydata.com "pgpool-reconfigure-democluster" already exists
```
But the user `demo2` was really created. Actually, if I delete and then wait for around 10s, the create command won't complain.

**What is the expected behavior?**
user `demo2` should be created with no error. Otherwise, this will confuse the automation pipeline, e.g. ansible

**Other information** (e.g. detailed explanation, related issues,  etc)
If my understanding is correct, after running the `pgo delete user...`, some other jobs are triggered and running asynchronously. But how can I know exactly when I'm able to run the next pgo command? For such cases, I would suggest to keep the command running and blocking until all the underlying jobs are done.

**Please tell us about your environment:**
Running pgo client with ansible. 
pgo version:
```
pgo client version 4.0.0-rc10
pgo-apiserver version 4.0.0-rc10
```

* Operating System: macos / Azure k8s service
* Where is this running ( Local , Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version: 9.6
* Platform (Docker, Kubernetes, OpenShift): k8s
* Platform Version: 1.14.1

If possible please run the following on the kubernetes or Openshit (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

And by the way, the `WARNING xxxxx (yes/no)` prompt could be good although annoying. But it would be great to add the `--no-prompt` option for deleting cluster and policy also to user-deleting command. Thanks!!

**Comment by cahoonpwork** [comment]
Let us take a look, we had a similar situation with delete cluster before.

**Comment by jmccormick2001** [comment]
I've created a fix for this one, it will be present in the 4.0.0-rc13 build we are doing this week.  thanks for reporting this one.

**Comment by tumluliu** [comment]
great to know, thanks a lot @jmccormick2001 !
