### ISSUE TITLE
pgo show user gives deleted users

### ISSUE THREAD

**Issue by tumluliu** [CrunchyData/postgres-operator#777]
**Describe the bug**
After deleting a user with `pgo delete user demo01 --selector=name=democluster -n pgo`, this `demo01` user together with its password (in clear text!?) is still in the results of `pgo show user democluster -n pgo`. And from the `kubectl -n pgo get secret`, the deleted user's secret is really there. Is this behaviour by design?

**To Reproduce**
1. Create a user with `pgo create user demo007 --selector name=democluster --db launchpad --managed --valid-days 180 --namespace pgo`
2. Delete the created user `demo007` with `pgo delete user demo007 --selector=name=democluster -n pgo`
3. List the current users with `pgo show user democluster -n pgo`
4. `demo007` is still there
5. If run `pgo delete user demo007 --selector=name=democluster -n pgo` again at this point, it will complain with `Error: pq: role "demo007" does not exist`

**Expected behavior**
`demo007` and its k8s secret should be gone after running the deleting command

* Operating System: macos / Azure k8s service
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag: ccp_image_tag='centos7-9.6.12-2.4.0-rc6', pgo_image_tag='centos7-4.0.0-rc10'
* PostgreSQL Version: 9.6.12
* Platform (Docker, Kubernetes, OpenShift): k8s
* Platform Version: 1.14.1

**Comment by ValClarkson** [comment]
I ran through your scenario using ccp image centos7-9.6.13-2.4.0-rc8 and operator image centos7-4.0.0-rc11, I did not encounter any errors.  Please update to this rc and try again.  Let me know if the issue persists with the latest rc.

**Comment by tumluliu** [comment]
thanks for your reply @ValClarkson . I will try with rc13 with another fix (#772)
