### ISSUE TITLE
Run script on cluster creation

### ISSUE THREAD

**Issue by mariuszb81** [CrunchyData/postgres-operator#778]
** Which example are you working with? **

pgo client version 4.0.0-rc10
pgo-apiserver version 4.0.0-rc10
Openshit 3.11

**What is the current behavior?**

When creating cluster I need to  automatically run additional scripts on database (creating dbs, users and tables)

**What is the expected behavior?**

pgo create cluster <name> -n <namespace> --password <pass> --run <startup.script>

**Comment by cahoonpwork** [comment]
You will want to use a policy.  

https://crunchydata.github.io/postgres-operator/latest/operatorcli/pgo-overview/ 
https://crunchydata.github.io/postgres-operator/latest/operatorcli/cli/pgo_create_cluster/
