### ISSUE TITLE
the load balancer tag should allow for internal load balancers to be created

### ISSUE THREAD

**Issue by cooktheryan** [CrunchyData/postgres-operator#787]
**What is the motivation or use case for the change? **

**Describe the solution you'd like**
A clear and concise description of what you want to happen. When specifying /bin/pgo create cluster DB --service-type=LoadBalancer service-type could be internal-Loadbalancer

**Please tell us about your environment:**

* Operating System: RHEL
* Where is this running ( Local, Cloud Provider) AWS
* Storage being used (NFS, Hostpath, Gluster, etc): EBS
* Container Image Tag: 
* PostgreSQL Version: 10
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 1.13

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by cahoonpwork** [comment]
I believe you could updated the cluster service template to include the annotation if you wanted to test it out.  You would need to redploy the operator once you make that change.  

We are close to releasing 4.0.0 but should be able to add this to the 4.1.0 release.  It looks like you are running on AWS, there appears to be some more options for Load Balancer Annotations on AWS based on https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer  are you looking to use any of those?

**Comment by cooktheryan** [comment]
@cahoonpwork sound fantastic that new releases are coming.

Ya you are correct with the annotation for AWS you posted. I most likely could modify the SVC after the fact and generate a new LB. I know that a lot of providers offer an internal load balancer solution when looking at those other tabs. In the past we have used internal load balancers in OpenStack. I definitely feel like databases we would potentially see more internal load balancers than publicly accessible ones
