### ISSUE TITLE
4.0.0-rc13 "replica" database container fails to start due to permissions on ssh key

### ISSUE THREAD

**Issue by hairmare** [CrunchyData/postgres-operator#794]
**Describe the bug**
After running `pgo scale` on a cluster the "replica" component fails to start due to wrong rights on the `/sshd/ssh_host_rsa_key`.

**To Reproduce**
```bash
pgo create cluster mycluster -n pgtest
pgo scale mycluster -n pgtest
```
```
WARNING: 'UsePAM no' is not supported in Red Hat Enterprise Linux and may cause several problems.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0777 for '/sshd/ssh_host_rsa_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
key_load_private: bad permissions
Could not load host key: /sshd/ssh_host_rsa_key
sshd: no hostkeys available -- exiting.
```

The ssh key in question is mounted from a kubernetes secret and it has way more rights than ssh will allow.

```
-rwxrwxrwx 1 root root 1679 Jun  4 08:41 ssh_host_rsa_key
```
Due to the database container in the "replica" pod failing to start `pgo test` fails:
```bash
pgo test mycluster -n pgtest
```
```
cluster : mycluster 
	psql -p 5432 -h 10.106.202.16 -U postgres postgres is Working
	psql -p 5432 -h 10.106.202.16 -U postgres userdb is Working
	psql -p 5432 -h 10.106.202.16 -U primaryuser postgres is Working
	psql -p 5432 -h 10.106.202.16 -U primaryuser userdb is Working
	psql -p 5432 -h 10.106.202.16 -U testuser postgres is Working
	psql -p 5432 -h 10.106.202.16 -U testuser userdb is Working
	psql -p 5432 -h 10.105.193.209 -U postgres postgres is NOT working
	psql -p 5432 -h 10.105.193.209 -U postgres userdb is NOT working
	psql -p 5432 -h 10.105.193.209 -U primaryuser postgres is NOT working
	psql -p 5432 -h 10.105.193.209 -U primaryuser userdb is NOT working
	psql -p 5432 -h 10.105.193.209 -U testuser postgres is NOT working
	psql -p 5432 -h 10.105.193.209 -U testuser userdb is NOT working
```

**Expected behavior**
Running `pgo scale` should add a replica and `pgo test` should sucessfully test the new replica.

* Operating System: Fedora 30
* Running locally on a minikube environment
* Storage being used: minikube-hostpath
* Container Image Tag: `centos7-11.3-2.4.0-rc10`
* PostgreSQL Version: `11.3`
* Platform: Kubernetes (minikube)
* Platform Version: 1.14.2 (Kubernetes) 1.1.0 (minikube)

**Additional context**
Looking [around](https://stackoverflow.com/a/50426726) the recommendation seems to be to copy the key to a location outside of the secret where it can be chowned as needed. It looks like K8s lacks a way to specify the umask and uid that files from secrets should be mounted as. 
Another option would be to generate the host key on the fly and store it in a proper volume. It that case it might make sense to allow specifying the key via the ansible inventory. 

Please let me know how you would like to implement this and I'll look if I can find some time to prepare a PR.

**Comment by tongpu** [comment]
It seems like that this issue is also affected by kubernetes/kubernetes/issues/78308. I was not able to reproduce it when running 1.14.1.

@hairmare Can you confirm?

**Comment by hairmare** [comment]
@tongpu Can confirm, is clearly an issue with 1.14.2 and how it handles (or fails to handle) `runAsUser`. Thanks for you patience ;)
