### ISSUE TITLE
4.0.0-rc13 deployment of second cluster fails, because root user is being used

### ISSUE THREAD

**Issue by tongpu** [CrunchyData/postgres-operator#795]
**Describe the bug**
When deploying a second cluster via `pgo create cluster` the pods are stuck in `CrashLoopBackOff` because `initdb` is being run as root.

**To Reproduce**
1. `pgo create cluster cluster0 -n pgo`
2. Wait for the cluster to finish startup
3. `pgo create cluster cluster1 -n pgo`
4. Pods for cluster 1 can't be started, because `initdb` refused to be run as root.

```
Tue Jun  4 13:27:54 UTC 2019 INFO: Setting PGROOT to /usr/pgsql-11.
Tue Jun  4 13:27:54 UTC 2019 INFO: The PGUSER secret exists.
Tue Jun  4 13:27:54 UTC 2019 INFO: The PGROOT secret exists.
Tue Jun  4 13:27:54 UTC 2019 INFO: The PGPRIMARY secret exists.
Tue Jun  4 13:27:54 UTC 2019 INFO: Cleaning up the old postmaster.pid file..
Tue Jun  4 13:27:54 UTC 2019 INFO: User ID is set to uid=0(root) gid=0(root) groups=0(root).
Tue Jun  4 13:27:54 UTC 2019 INFO: Setting LOG_MIN_DURATION_STATEMENT to 60000.
Tue Jun  4 13:27:54 UTC 2019 INFO: Setting LOG_STATEMENT to none.
Tue Jun  4 13:27:54 UTC 2019 INFO: Working on primary..
Tue Jun  4 13:27:54 UTC 2019 INFO: Initializing the primary database..
Tue Jun  4 13:27:54 UTC 2019 INFO: PGDATA is empty. ID is uid=0(root) gid=0(root) groups=0(root). Creating the PGDATA directory..
Tue Jun  4 13:27:54 UTC 2019 INFO: Starting initdb..
Tue Jun  4 13:27:54 UTC 2019 INFO: XLOGDIR not found. Using default pg_wal directory..
Tue Jun  4 13:27:54 UTC 2019 INFO: Data checksums enabled.  Setting initdb to use data checksums..
Tue Jun  4 13:27:54 UTC 2019 INFO: Running initdb command: initdb -D /pgdata/cluster1  --locale=en_US.UTF8 --data-checksums > /tmp/initdb.stdout 2> /tmp/initdb.stderr
Tue Jun  4 13:27:54 UTC 2019 ERROR: Initializing the database (initdb): Unable to initialize the database: 
initdb: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
```

**Expected behavior**
Any number of clusters should be able to be deployed using the same operator.

**Please tell us about your environment:**

* Operating System: Arch Linux
* Where is this running: minikube
* Storage being used: minikube-hostpath
* Container Image Tag: `centos7-11.3-2.4.0-rc10`, `centos7-4.0.0-rc13`
* PostgreSQL Version: `11.3`
* Platform: Kubernetes (minikube)
* Platform Version: 1.14.2 (Kubernetes) 1.1.0 (minikube)

**Additional context**

**Comment by jmccormick2001** [comment]
Hi, we have seen this issue with kube 1.14.2 where a bug was present in kube that causes this error, try with a different version of kube if possible.

**Comment by tongpu** [comment]
I'm not able to reproduce the issue on 1.14.1!

@jmccormick2001 Do you have any idea what might cause this?

**Comment by jmccormick2001** [comment]
https://github.com/kubernetes/kubernetes/pull/78178

**Comment by tongpu** [comment]
I also found the corresponding issue: kubernetes/kubernetes/issues/78308

I'm going to close the issue here.
