### ISSUE TITLE
Error:  Invalid Status Code: 405

### ISSUE THREAD

**Issue by multi-io** [CrunchyData/postgres-operator#807]
**Describe the bug**
Creating a cluster fails with "Error: Invalid Status Code: 405".

**To Reproduce**
1. cloned postgres-operator 3.5.3 (ee09d3a2b6730f724b907fe328a6cc96de223eff)
2. followed https://crunchydata.github.io/postgres-operator/stable/installation/. `conf/postgres-operator/pgouser` left unchanged. `~/.pgouser` contains `testuser:testpass`. Operator exposed via an LB service. "pgo version" reports "pgo client version 3.5.3\npgo-apiserver version 3.5.3" (this request is also logged by the apiserver container)
2. ran "pgo create cluster example1"
3. pgo reports "Error:  Invalid Status Code: 405". None of the 3 pgo containers log anything.

**Expected behavior**
A cluster should be created

**Screenshots**
```
oklischat@oklischat:~/go/src/github.com/crunchydata/postgres-operator$ pgo version
pgo client version 3.5.3
pgo-apiserver version 3.5.3
oklischat@oklischat:~/go/src/github.com/crunchydata/postgres-operator$ pgo create cluster example1
Error:  Invalid Status Code: 405

oklischat@oklischat:~/go/src/github.com/crunchydata/postgres-operator$
oklischat@oklischat:~/go/src/github.com/crunchydata/postgres-operator$ set | egrep '^(CO|PGO)'
COROOT=/Users/oklischat/go/src/github.com/crunchydata/postgres-operator
CO_APISERVER_URL=https://<redacted>:8443/
CO_BASEOS=centos7
CO_CMD=kubectl
CO_IMAGE_PREFIX=crunchydata
CO_IMAGE_TAG=centos7-3.5.3
CO_NAMESPACE=demo
CO_VERSION=3.5.3
PGO_CA_CERT=/Users/oklischat/go/src/github.com/crunchydata/postgres-operator/conf/postgres-operator/server.crt
PGO_CLIENT_CERT=/Users/oklischat/go/src/github.com/crunchydata/postgres-operator/conf/postgres-operator/server.crt
PGO_CLIENT_KEY=/Users/oklischat/go/src/github.com/crunchydata/postgres-operator/conf/postgres-operator/server.key
oklischat@oklischat:~/go/src/github.com/crunchydata/postgres-operator$
```

**Please tell us about your environment:**

* Operating System: client macOS / go1.12.4, server k8s 1.14.1

**Comment by jmccormick2001** [comment]
Hi, could you rerun that 'pgo' command with "--debug" on it?  that might show something more.

**Comment by multi-io** [comment]
```
$ pgo --debug create cluster example1
DEBU[0000] debug flag is set to true
DEBU[0000] in initConfig with url=https://x.x.x.x:8443/
DEBU[0000] GetCredentials called
DEBU[0000] looking in /Users/oklischat/.pgouser for credentials
DEBU[0000] /Users/oklischat/.pgouser found
DEBU[0000] pgouser file found at /Users/oklischat/.pgouser contains testuser:testpass

DEBU[0000] [testuser testpass]
DEBU[0000] username=[testuser] password=[testpass]
DEBU[0000] setting up httpclient with TLS
DEBU[0000] create cluster called
DEBU[0000] createCluster called...[https://x.x.x.x:8443//clusters]
DEBU[0000] &{405 Method Not Allowed 405 HTTP/1.1 1 1 map[Content-Length:[0] Date:[Fri, 07 Jun 2019 08:26:07 GMT]] {} 0 [] false false map[] 0xc000390000 0xc00037a000}
DEBU[0000] http status code is 405
Error:  Invalid Status Code: 405
$
```

**Comment by jmccormick2001** [comment]
DEBU[0000] createCluster called...[https://x.x.x.x:8443//clusters]

that doesn't look right, the '//' is not correct, is that a type-o or does it really show up like that?

**Comment by jmccormick2001** [comment]
still an issue or can we close this out?

**Comment by multi-io** [comment]
Can be closed, thanks.

**Comment by dejwsz** [comment]
I have the same problem. What is the solution? The version I am testing is:
pgo client version 4.2.2
pgo-apiserver version 4.2.2

**Comment by jkatz** [comment]
@dejwsz Can you follow the instructions to provide debug information please? Run the `pgo` command you were executing with `--debug`

**Comment by dejwsz** [comment]
the same thing as above with  double '//'

**Comment by dejwsz** [comment]
OK I know - I have PGO_APISERVER_URL with '/' at the end of url - I just removed the '/' sign and it is OK. Maybe the pgo client should be smarter with this ;)

**Comment by jkatz** [comment]
We can't make assumptions about how people are deploying the Operator in their environment in that regard. They may put a web proxy in front of it or the like.

**Comment by dejwsz** [comment]
It was about the pgo client only, the url I had in PGO_APISERVER_URL env was ended with '/' character but it should not. When I removed it then pgo client started to work well right away.

**Comment by allout58** [comment]
It would be worthwhile to at least put in the documentation that, in general, your PGO_APISERVER_URL should not end with a `/`

**Comment by jkatz** [comment]
@allout58 I have modified the documentation in a few places to note this requirement.
