### ISSUE TITLE
psp support

### ISSUE THREAD

**Issue by aleks-mariusz** [CrunchyData/postgres-operator#810]
**What is the motivation or use case for the change? **

Ability to run in clusters with podsecuritypolicies in place.

**Describe the solution you'd like**

Most podsecuritypolicies prohibit containers from being started throwing CreateContainerConfigError errors if the definition of a pod does not jive with the psp defined for the cluster

**Please tell us about your environment:**

* Operating System:
CentOS 7
* Where is this running ( Local, Cloud Provider)
OnPrem
* Storage being used (NFS, Hostpath, Gluster, etc):
Portworx
* Container Image Tag:
crunchy-containers 2.4
* PostgreSQL Version:
11.3
* Platform (Docker, Kubernetes, OpenShift):
Kubernetes
* Platform Version:
v1.14.2
**Additional context**

Using the newly released crunchy postgres-operator 4.0 (purposly been watching daily what rc # you are up to lol), finally i tried to use pgo to create a cluster (single primary postgres instance), however both it and the default backrest-shared-repo pod come up with `CreateContainerConfigError`, and when i use describe on the poid it creates:

`Error: container has runAsNonRoot and image will run as root`

I had this issue with the postgres-operator pod itself, but i output the deployment definition to yaml, modified it, and replace -f'd it, however for the dynamically generated pods this isn't sustainable.. i see that the conf/postgres-operator templates have a SecurityContext related to the storage config, and what fsGroup param is added to securityContext, but how do we specify our own securityContext settings (and why can't they already be set by pgo-operator?) for pod template/definitions to be compatible with podsecuritypolicies?

**Comment by cahoonpwork** [comment]
@aleks-mariusz The issue is with Kubernetes 1.14.2 and 1.13.6 both have a bug.  Please try again in 1.14.1.

**Comment by aleks-mariusz** [comment]
Can you give any specifics about what the issue is with those versions please? Also 1.14.3 was released last week as well, perhaps that one might work as well ?

**Comment by jmccormick2001** [comment]
1.14.3 works

**Comment by davi5e** [comment]
I'm using Kubernetes `1.15` and the stanza pod always fail if I enable Pod Security Policy in the cluster.

More info here: https://github.com/CrunchyData/postgres-operator/issues/1362

What's strange is that the actual error is related to the network and both `backrest-shared-repo` and the primary/master deployments start successfully, but since `stanza-create` fails no replica gets created and the operator stalls.

Can anyone share the PSP files used with the Service Accounts created by PGO?
