### ISSUE TITLE
Simpler examples

### ISSUE THREAD

**Issue by metalmatze** [CrunchyData/postgres-operator#84]
Hey!
I would really like to try this operator, but I struggle to install it into my cluster. Your examples are almost all, from my point of view, to complicated or over engineered. It would be super helpful to have simple `.yaml` files without any sort of templating, which one can simply read through and change, if needed.
I especially like the way the Prometheus Operator's example are structured.

https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests

**Comment by jmccormick2001** [comment]
greetings,

today the operator works off a single yaml file called pgo.yaml, there is no templating
in that configuration file, you fill it in to meet your requirements, the default file I ship
for instance assumes a hostPath persistence configuration on your Kube system, if that
doesn't work for a user's requirements, they can change the values in that yaml file to suit
their needs.

I think that is fairly simple for users to deal with?  What is more complex is the configuration
files that exist for the various Postgres cluster deployment pieces.  Those are used by 
the operator to define the makeup of the Postgres cluster that is deployed by the operator
itself.  End users will typically not need to make any changes to those templates themselves
but they can if they have some unique requirements.

the contents of the pgo.yaml configuration file are documented here:
https://github.com/CrunchyData/postgres-operator/blob/master/docs/config.asciidoc

the example configuration file is found here:
https://github.com/CrunchyData/postgres-operator/blob/master/conf/apiserver/pgo.yaml

hope that is helpful in explaining the architecture.

regards

**Comment by joerghall** [comment]
I just create postgres-operator through the provided docker images. It is not clear how to do it without going through "Build and Install" section. There is also a dead link for https://hub.docker.com/r/crunchydata/postgres-operator-apiserver/ in the README.

**Comment by jmccormick2001** [comment]
thanks, I've updated the broken link, the install/build/configuration documentation will likely be merged into a single document in an upcoming release, hopefully that will make it easier to read/follow.
