### ISSUE TITLE
Error in webapp-stanza-create Pod when creating the Cluster

### ISSUE THREAD

**Issue by kannanvj** [CrunchyData/postgres-operator#842]
Hi,
  I am trying to deploy postgresql operator on my kubernetes cluster
I have deployed through the Ansible play book.

**What is the current behavior?**

I am able to deploy the postgresql operator successfully. I am creating the postgresql cluster by using following command 

pgo create cluster webapp   –labels=project=www   –pgbackrest    –autofail -n pgouser2

I have observed that 3 pods were created by operator. But one of the pos state is Error.
Following are the pods
[root@uklab9 ~]# kubectl get pod -n pgouser2
NAME                                           READY   STATUS    RESTARTS   AGE
webapp-655dd8f7c5-zpzjz                        1/1     Running   0          76m
webapp-backrest-shared-repo-646f844f99-zntkv   1/1     Running   0          76m
webapp-stanza-create-44bt6                     0/1     Error     0          75m

Following is the error from the pod logs

====
[root@uklab9 ~]# kubectl logs -f webapp-stanza-create-44bt6 -n pgouser2
time="2019-06-25T11:11:20Z" level=info msg="pgo-backrest starts"
time="2019-06-25T11:11:20Z" level=info msg="debug flag set to false"
time="2019-06-25T11:11:20Z" level=info msg="backrest stanza-create command requested"
time="2019-06-25T11:11:50Z" level=info msg="sleeping 30 seconds to avoid race with PG during startup"
time="2019-06-25T11:11:50Z" level=info msg="command to execute is [pgbackrest stanza-create ]"
time="2019-06-25T11:11:50Z" level=info msg="command is pgbackrest stanza-create  "
time="2019-06-25T11:12:11Z" level=error msg="command terminated with exit code 42"
time="2019-06-25T11:12:11Z" level=info msg="output=[]"
time="2019-06-25T11:12:11Z" level=info msg="stderr=[ERROR [042]: : remote process on 'webapp' terminated unexpectedly: ssh: Could not resolve hostname webapp: Name or service not known\n]"
time="2019-06-25T11:12:11Z" level=error msg="command terminated with exit code 42"
[root@uklab9 ~]#

====

* Operating System:
* PostgreSQL Version: 4.0.0
* Platform (Docker, Kubernetes, OpenShift):Kubernetes

Kindly help us to resolve this issue

**Comment by jmccormick2001** [comment]
hello, can you provide me the container logs from the primary database container?

**Comment by kannanvj** [comment]
Logs for Webapp Pod 
```[root@uklab9 ~]# kubectl logs -f -n pgouser2 webapp-655dd8f7c5-zpzjz
Tue Jun 25 11:10:05 UTC 2019 INFO: Setting PGROOT to /usr/pgsql-11.
Tue Jun 25 11:10:05 UTC 2019 INFO: The PGUSER secret exists.
Tue Jun 25 11:10:05 UTC 2019 INFO: The PGROOT secret exists.
Tue Jun 25 11:10:05 UTC 2019 INFO: The PGPRIMARY secret exists.
Tue Jun 25 11:10:05 UTC 2019 INFO: Cleaning up the old postmaster.pid file..
Tue Jun 25 11:10:05 UTC 2019 INFO: User ID is set to uid=26(postgres) gid=26(postgres) groups=26(postgres),2007.
Tue Jun 25 11:10:05 UTC 2019 INFO: Setting LOG_MIN_DURATION_STATEMENT to 60000.
Tue Jun 25 11:10:05 UTC 2019 INFO: Setting LOG_STATEMENT to none.
Tue Jun 25 11:10:05 UTC 2019 INFO: Working on primary..
Tue Jun 25 11:10:05 UTC 2019 INFO: Initializing the primary database..
Tue Jun 25 11:10:05 UTC 2019 INFO: PGDATA is empty. ID is uid=26(postgres) gid=26(postgres) groups=26(postgres),2007. Creating the PGDATA directory..
Tue Jun 25 11:10:05 UTC 2019 INFO: Starting initdb..
Tue Jun 25 11:10:05 UTC 2019 INFO: XLOGDIR not found. Using default pg_wal directory..
Tue Jun 25 11:10:05 UTC 2019 INFO: Data checksums enabled.  Setting initdb to use data checksums..
Tue Jun 25 11:10:05 UTC 2019 INFO: Running initdb command: initdb -D /pgdata/webapp  --locale=en_US.UTF8 --data-checksums > /tmp/initdb.stdout 2> /tmp/initdb.stderr
Tue Jun 25 11:11:08 UTC 2019 INFO: Overlaying PostgreSQL's default configuration with customized settings..
Tue Jun 25 11:11:08 UTC 2019 INFO: Temporarily starting database to run setup.sql..
waiting for server to start....2019-06-25 11:11:08 UTC [123]: [1-1] user=,db=,app=,client=LOG:  pgaudit extension initialized
2019-06-25 11:11:08 UTC [123]: [2-1] user=,db=,app=,client=LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-06-25 11:11:08 UTC [123]: [3-1] user=,db=,app=,client=LOG:  redirecting log output to logging collector process
2019-06-25 11:11:08 UTC [123]: [4-1] user=,db=,app=,client=HINT:  Future log output will appear in directory "pg_log".
 done
server started
Tue Jun 25 11:11:08 UTC 2019 INFO: Waiting for PostgreSQL to start..
/tmp:5432 - accepting connections
Tue Jun 25 11:11:08 UTC 2019 INFO: The database is ready for setup.sql.
SET
CREATE EXTENSION
CREATE EXTENSION
ALTER ROLE
CREATE ROLE
ALTER ROLE
CREATE ROLE
ALTER ROLE
CREATE DATABASE
GRANT
CREATE TABLE
GRANT
You are now connected to database "userdb" as user "postgres".
CREATE EXTENSION
CREATE EXTENSION
You are now connected to database "userdb" as user "testuser".
CREATE SCHEMA
CREATE TABLE
INSERT 0 1
Tue Jun 25 11:11:33 UTC 2019 INFO: Stopping database after primary initialization..
waiting for server to shut down........ done
server stopped
Tue Jun 25 11:11:37 UTC 2019 INFO: pgBackRest: Enabling pgbackrest..
Tue Jun 25 11:11:37 UTC 2019 INFO: pgBackRest: Created pgbackrest repository directory /backrestrepo/webapp-backrest-shared-repo
Tue Jun 25 11:11:37 UTC 2019 INFO: pgBackRest: BACKREST_SKIP_CREATE_STANZA is 'true'.  Skipping configuration check..
Tue Jun 25 11:11:37 UTC 2019 INFO: pgBackRest: BACKREST_SKIP_CREATE_STANZA is 'true'.  Skipping stanza creation..
Tue Jun 25 11:11:37 UTC 2019 INFO: Setting pgbackrest archive command..
Tue Jun 25 11:11:37 UTC 2019 INFO: Setting ARCHIVE_MODE to on.
Tue Jun 25 11:11:37 UTC 2019 INFO: Setting ARCHIVE_TIMEOUT to 0.
Tue Jun 25 11:11:37 UTC 2019 INFO: Starting PostgreSQL..
Tue Jun 25 11:11:37 UTC 2019 INFO: Applying SSHD..
Tue Jun 25 11:11:37 UTC 2019 INFO: Checking for SSH Host Keys in /sshd..
Tue Jun 25 11:11:37 UTC 2019 INFO: Checking for authorized_keys in /sshd
Tue Jun 25 11:11:37 UTC 2019 INFO: Checking for sshd_config in /sshd
Tue Jun 25 11:11:37 UTC 2019 INFO: setting up .ssh directory
Tue Jun 25 11:11:37 UTC 2019 INFO: Starting SSHD..
WARNING: 'UsePAM no' is not supported in Red Hat Enterprise Linux and may cause several problems.
2019-06-25 11:11:37 UTC [186]: [1-1] user=,db=,app=,client=LOG:  pgaudit extension initialized
2019-06-25 11:11:37 UTC [186]: [2-1] user=,db=,app=,client=LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-06-25 11:11:37 UTC [186]: [3-1] user=,db=,app=,client=LOG:  listening on IPv6 address "::", port 5432
2019-06-25 11:11:37 UTC [186]: [4-1] user=,db=,app=,client=LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-06-25 11:11:37 UTC [186]: [5-1] user=,db=,app=,client=LOG:  redirecting log output to logging collector process
2019-06-25 11:11:37 UTC [186]: [6-1] user=,db=,app=,client=HINT:  Future log output will appear in directory "pg_log".

```
Logs for webapp-backrest-shared-repo
```
[root@uklab9 ~]# kubectl logs -f -n pgouser2 webapp-backrest-shared-repo-646f844f99-zntkv
PGBACKREST env vars are set to:
PGBACKREST_DB_HOST=webapp
PGBACKREST_DB_PATH=/pgdata/webapp
PGBACKREST_LOG_PATH=/tmp
PGBACKREST_PG1_PORT=5432
PGBACKREST_REPO_PATH=/backrestrepo/webapp-backrest-shared-repo
PGBACKREST_STANZA=db
_='PGBACKREST env vars are set to:'
CONFIG is..
authorized_keys
aws-s3-ca.crt
aws-s3-credentials.yaml
config
id_rsa
ssh_host_rsa_key
sshd_config
REPO is ...
creating  /backrestrepo/webapp-backrest-shared-repo
WARNING: 'UsePAM no' is not supported in Red Hat Enterprise Linux and may cause several problems.
```

**Comment by kannanvj** [comment]
HI All,
 How to resolve this issue ?

Thanks,
Kannan V

**Comment by jmccormick2001** [comment]
could you try 'pgo create cluster foo -n pgouser2' and see if you get the same error?  thanks.

**Comment by kannanvj** [comment]
@jmccormick2001 , I am getting the similar error....
How to rectify this error ?

**Comment by jmccormick2001** [comment]
lets see what the PVC's look like:

kubectl get pvc -n pgouser2

**Comment by kannanvj** [comment]
@jmccormick2001 , PVC is in Bounded state

[root@uklab9 postgres-operator]# kubectl get pvc -n pgouser2

NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
foo                        Bound    pvc-40101cd5-9813-11e9-8cea-14feb501f21c   1Gi        RWO            gluster        5m19s
foo-backrest-shared-repo   Bound    pvc-41e7b3a5-9813-11e9-8cea-14feb501f21c   1Gi        RWX            gluster        5m16s
[root@uklab9 postgres-operator]#
[root@uklab9 postgres-operator]#

**Comment by kannanvj** [comment]
Please find the attached postgres-operator pod logs. 
I have enabled crunchy_debug flag. Then I have captured this log.

[postgres-operator.txt](https://github.com/CrunchyData/postgres-operator/files/3330142/postgres-operator.txt)

**Comment by kannanvj** [comment]
@jmccormick2001 , After changing the FsGroup, still I am getting the similar issue...
Please find the attached output for "pgo show config" 
[config.txt](https://github.com/CrunchyData/postgres-operator/files/3331581/config.txt)

i have verified my storageclass.. It seems it is fine...
Following is the output for "pgo test foo"

-------------

[root@uklab9 ~]# pgo test foo -n pgouser2

cluster : foo
        psql -p 5432 -h 10.233.4.210 -U postgres postgres is Working
        psql -p 5432 -h 10.233.4.210 -U postgres userdb is Working
        psql -p 5432 -h 10.233.4.210 -U primaryuser postgres is Working
        psql -p 5432 -h 10.233.4.210 -U primaryuser userdb is Working
        psql -p 5432 -h 10.233.4.210 -U testuser postgres is Working
        psql -p 5432 -h 10.233.4.210 -U testuser userdb is Working
[root@uklab9 ~]#

----------


Still i am getting the similar issue as below

-------------------
[root@uklab9 ~]# kubectl logs -f -n pgouser2 foo-stanza-create-xn6m4
time="2019-06-26T18:59:53Z" level=info msg="pgo-backrest starts"
time="2019-06-26T18:59:53Z" level=info msg="debug flag set to false"
time="2019-06-26T18:59:53Z" level=info msg="backrest stanza-create command requested"
time="2019-06-26T19:00:23Z" level=info msg="sleeping 30 seconds to avoid race with PG during startup"
time="2019-06-26T19:00:23Z" level=info msg="command to execute is [pgbackrest stanza-create ]"
time="2019-06-26T19:00:23Z" level=info msg="command is pgbackrest stanza-create  "
time="2019-06-26T19:00:44Z" level=error msg="command terminated with exit code 42"
time="2019-06-26T19:00:44Z" level=info msg="output=[]"
time="2019-06-26T19:00:44Z" level=info msg="stderr=[ERROR [042]: : remote process on 'foo' terminated unexpectedly: ssh: Could not resolve hostname foo: Name or service not known\n]"
time="2019-06-26T19:00:44Z" level=error msg="command terminated with exit code 42"
[root@uklab9 ~]#
-----------

Please help me to debug this issue

**Comment by jmccormick2001** [comment]
ok, lets try this next:

kubectl exec -it yourrepopodname bash -n pgouser2

you are exec'ing into the backrest repo...when you are in, enter the following
command:

ssh postgres@foo

see if you can connect to the primary and if that hostname resolves...

**Comment by kannanvj** [comment]
@jmccormick2001 , I have checked with all the pods which are created by postgresql operator.
When we create the cluster, operator will create following 3 pods...
For all those 3 pods doesn't have "foo" entry on the file /etc/hosts

---

[root@uklab9 ansible]# kubectl get pod -n pgouser2
NAME                                      READY   STATUS    RESTARTS   AGE
foo-6cf5b7b5f6-fssd4                      2/2     Running   0          9m
foo-backrest-shared-repo-8c7dd666-csdmv   1/1     Running   0          9m
foo-stanza-create-82jcq                   0/1     Error     0          8m34s
[root@uklab9 ansible]#

---- 

Following is the "/etc/hosts" entry for the pod foo-stanza-create-82jcq. Also this pod doesn't  contain any ssh package. But other pod is having ssh utility. None of the pod having the entry for hostname foo

-----

bash-4.2$ cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.233.67.39    foo-stanza-create-82jcq

----

**Comment by jmccormick2001** [comment]
run kubectl exec -it foo-backrest-shared-repo-8c7dd666-csdmv bash -n pgouser2

then run 'ssh postgres@foo' inside the container, let me know the results.

**Comment by kannanvj** [comment]
@jmccormick2001 , It is not able to resolve the hostname foo

----

bash-4.2$ ssh postgres@foo
ssh: Could not resolve hostname foo: Name or service not known
bash-4.2$
 
----

**Comment by jmccormick2001** [comment]
leads me to think you have a network problem..there is a service that should be called 'foo', it should resolve from within the backrest repo container, if not, a network issue is happening.

**Comment by kannanvj** [comment]
Thanks @jmccormick2001 ... It was a mistake from my kube-dns pod... Now i have fixed it...
Thanks a lot for your support.
