### ISSUE TITLE
Security issue of Postgres Operator user having access to security of many namespaces

### ISSUE THREAD

**Issue by fanzhang15** [CrunchyData/postgres-operator#843]
**What is the motivation or use case for the change? **
Postgres Operator has RBAC at ClusterRole level. It allows get, list and create secrets. This poses a security issue when `pgouser1` who has access to the Operator, also has full access to the security of `pgouser2`. This is similar to Tiller user having access to the security of different namespaces.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pgopclusterrolesecret
rules:
  - verbs:
      - get
      - list
      - create
    apiGroups:
      - '*'
    resources:
      - secrets

**Describe the solution you'd like**
I want Operator to NOT have access to security.

**Please tell us about your environment:**
Environment irrelevant

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jmccormick2001** [comment]
Hi,

the operator has create permissions on the namespaces it watches because it is creating Secrets in those namespaces...users only have access to the Operator API that are known and registered in pgouser and have rights defined by pgorole...pgo users are also restricted as to what namespaces
they have access to by pgorole definitions.

maybe I'm not following your concern however, if so, please elaborate and I'll try to address.

regards.

**Comment by leigh-j** [comment]
This issue is similar/ the same as https://github.com/CrunchyData/postgres-operator/issues/905
operator service account should not have access to all secrets on cluster. Ideally managing the operator does not require cluster admin.

**Comment by jkatz** [comment]
Hi @leigh-j,

Which version of the Operator are you using? Operator 4.1 does not require any ClusterAdmin _except_ for the installation, and the only ClusterRole permissions are as such and only required for dynamic namespacing:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pgo-cluster-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - namespaces
      - serviceaccounts
      - roles
      - rolebindings
```

If you do not wish to use the dynamic namespace feature, you can add the namespaces manually, using the scripts available in the "deploy" directory, e.g. [add-targeted-namespace.sh](https://github.com/CrunchyData/postgres-operator/blob/master/deploy/add-targeted-namespace.sh)
