### ISSUE TITLE
PGO create user fails 

### ISSUE THREAD

**Issue by kannanvj** [CrunchyData/postgres-operator#846]
**Describe the bug**
When I am trying to create the user, i am getting the below error
"Error: pgo client and server version mismatch"

But when i execute the command pgo version, i am getting the client and server version is remains same.

----

[root@uklab9 ansible]# pgo version
Handling connection for 8443
pgo client version 4.0.0
pgo-apiserver version 4.0.0

-----

**To Reproduce**
1.  After creating the postgresql cluster successfully, create the user as below
    pgo create user test --selector=db=postgresql --password test --valid-days 180

It is failing with the below error 

[root@uklab9 ansible]# pgo create user test --selector=db=postgresql --password test --valid-days 180 --debug
DEBU[0000] debug flag is set to true
DEBU[0000] in initConfig with url=https://127.0.0.1:8443
DEBU[0000] GetCredentials called
DEBU[0000] PGOUSER environment variable is being used at /root/.pgo/pgo/pgouser
DEBU[0000] pgouser file found at /root/.pgo/pgo/pgouser contains admin:test123

DEBU[0000] [admin test123]
DEBU[0000] username=[admin] password=[test123]
DEBU[0000] setting up httpclient with TLS
DEBU[0000] create user called
DEBU[0000] createUsers called...[https://127.0.0.1:8443/users]
Handling connection for 8443
DEBU[0000] &{200 OK 200 HTTP/1.1 1 1 map[Content-Type:[application/json] Www-Authenticate:[Basic realm="Restricted"] Date:[Thu, 27 Jun 2019 13:17:38 GMT] Content-Length:[79]] 0xc000236080 79 [] false false map[] 0xc000155500 0xc00010eb00}
DEBU[0000] http status code is 200
Error: pgo client and server version mismatch
[root@uklab9 ansible]#

**Expected behavior**
User should get created successfully

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider) Local
* Storage being used (NFS, Hostpath, Gluster, etc): Gluster
* Platform (Docker, Kubernetes, OpenShift): Kubernetes

**Comment by jmccormick2001** [comment]
strange, can you try this:

pgo create user test --selector=name=test1 --password=test --valid-days=180 -n pgouser1

replace test1 with the name of your PG cluster.

**Comment by kannanvj** [comment]
@jmccormick2001 , yes. I am able to create the user name same as PG cluster.
One more observation, After adding the user name as  PGcluster, then we are able to add any other username
