### ISSUE TITLE
Add release 4.0.1 to OperatorHub.io

### ISSUE THREAD

**Issue by ron1** [CrunchyData/postgres-operator#849]
Add releases 4.0 and 4.0.1 to OperatorHub.io.

**Comment by cahoonpwork** [comment]
This is in progress now.  We will update this issue when it is out there.

**Comment by AnacondaJose** [comment]
Is there anything I can do to help out with this issue?

**Comment by flamingdumpster** [comment]
Thank you for offering - this will be completed soon though.

**Comment by ron1** [comment]
I see add to community-operators is done. Now only add to upstream-community-operators remains. I suspect this should be mostly copy and paste. Will this be completed soon?

**Comment by flamingdumpster** [comment]
Yes, the upstream is next and will be roughly the same, changes only where needed.

**Comment by ron1** [comment]
Done.
