### ISSUE TITLE
pgbadger container can not generate report automatically

### ISSUE THREAD

**Issue by muhaook** [CrunchyData/postgres-operator#851]
**Describe the bug**
I can see 2 processes (start-pgbadger.sh and /opt/cpm/bin/badgerserver) running in pgbadger container, but report was not generated automatically. 

**To Reproduce**
1. install ansible
2. pull postgre-operator source code and update inventory file (enable badger, add correct namespace and storage parameters)
3. create namespace (mh-ansible) in kubernetes
4. run command: ansible-playbook -i /Users/mike1/apic/go/src/github.com/postgres-operator/ansible/inventory --tags=install --ask-become-pass main.yml
5. postgre-operator is installed now. start to use pgo to deploy db / pgbadger containers
6. set up environmental variables:
export PGO_CA_CERT="/Users/mike1/.pgo/mh-ansible/client.crt"
export PGO_CLIENT_CERT="/Users/mike1/.pgo/mh-ansible/client.crt"
export PGO_CLIENT_KEY="/Users/mike1/.pgo/mh-ansible/client.pem"
export PGOUSER="/Users/mike1/.pgo/mh-ansible/pgouser"
export PGO_APISERVER_URL='https://127.0.0.1:8443'
7. set up port-forward:
k port-forward postgres-operator-5896586ff5-w57f2 8443 -n mh-ansible &
8. run pgo:
pgo create cluster dbcluster -n mh-ansible --password password --replica-count 1

**Expected behavior**
expected to see index.html under /report folder.

**Screenshots**
NA

**Please tell us about your environment:**

* Operating System: MacOS
* Where is this running ( Local, Cloud Provider): IBM cloud
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version: latest
* Platform (Docker, Kubernetes, OpenShift): Docker (18.09.2, build 6247962) + Kubernetes:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6+IKS", GitCommit:"ac5f7341d5d0ce8ea8f206ba5b030dc9e9d4cc97", GitTreeState:"clean", BuildDate:"2019-05-09T13:26:51Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Platform Version:

**Additional context**

**Comment by ruairi-hayes** [comment]
@muhaook can you try this with the `--pgbadger` flag set in your create to see if that gets it working for you
e.g. 
pgo create cluster dbcluster -n mh-ansible --password password --replica-count 1 --pgbadger
The pgo api may be doing some configuration behind the scenes

**Comment by muhaook** [comment]
The issue still exists with flag --pgbadger.

The command line I run:
pgo create cluster dbcluster -n $NS --replica-count 1 --pgbadger

After running the command, I had a look at pgbadger container. There was a db log file, but still the /report folder was empty.

[postgres@dbcluster-65b5494ddd-7tmkb report]$ cd /pgdata/dbcluster/pg_log
[postgres@dbcluster-65b5494ddd-7tmkb pg_log]$ ls
postgresql-Thu.log
[postgres@dbcluster-65b5494ddd-7tmkb pg_log]$ ls -l
total 64
-rw------- 1 postgres postgres 60179 Jul 11 16:04 postgresql-Thu.log
[postgres@dbcluster-65b5494ddd-7tmkb pg_log]$ cd /report
[postgres@dbcluster-65b5494ddd-7tmkb report]$ ls
[postgres@dbcluster-65b5494ddd-7tmkb report]$

**Comment by ValClarkson** [comment]
@muhaook can you try running some sql statements against the primary db and then check the reports folder for the index.html file?

**Comment by muhaook** [comment]
I run some sql statements just now, but the /report folder was still empty. 

Details:
muhaos-mbp:postgres-operator-helm mike1$ k exec -it dbcluster-65b5494ddd-7tmkb -c database -n $NS bash
bash-4.2$ psql
psql (11.3)
Type "help" for help.

postgres=# \c
You are now connected to database "postgres" as user "postgres".
postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF8 | en_US.UTF8 | 
 template0 | postgres | UTF8     | en_US.UTF8 | en_US.UTF8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF8 | en_US.UTF8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 userdb    | postgres | UTF8     | en_US.UTF8 | en_US.UTF8 | =Tc/postgres         +
           |          |          |            |            | postgres=CTc/postgres+
           |          |          |            |            | testuser=CTc/postgres
(4 rows)

postgres=# \dt 
            List of relations
 Schema |     Name     | Type  |  Owner   
--------+--------------+-------+----------
 public | primarytable | table | postgres
(1 row)

postgres=# select count(*) from primarytable;
 count 
-------
     0
(1 row)

postgres=# create table mike (c char(100));
CREATE TABLE
postgres=# insert into mike values (current_timestamp);
INSERT 0 1
postgres=# insert into mike select * from mike;
INSERT 0 1
postgres=# insert into mike select * from mike;
INSERT 0 2
postgres=# insert into mike select * from mike;
INSERT 0 4
postgres=# insert into mike select * from mike;
INSERT 0 8
postgres=# insert into mike select * from mike;
INSERT 0 16
postgres=# insert into mike select * from mike;
INSERT 0 32
postgres=# insert into mike select * from mike;
INSERT 0 64
postgres=# insert into mike select * from mike;
INSERT 0 128
postgres=# insert into mike select * from mike;
INSERT 0 256
postgres=# insert into mike select * from mike;
INSERT 0 512
postgres=# insert into mike select * from mike;
INSERT 0 1024
postgres=# insert into mike select * from mike;
INSERT 0 2048
postgres=# insert into mike select * from mike;
INSERT 0 4096
postgres=# insert into mike select * from mike;
INSERT 0 8192
postgres=# insert into mike select * from mike;
INSERT 0 16384
postgres=# insert into mike select * from mike;
^[[AINSERT 0 32768
postgres=# insert into mike select * from mike;
^[[A
^[[A
INSERT 0 65536
postgres=# insert into mike select * from mike;
INSERT 0 131072
postgres=# insert into mike select * from mike;
INSERT 0 262144
postgres=# select (*) from mike;
ERROR:  syntax error at or near "*"
LINE 1: select (*) from mike;
                ^
postgres=# select count(*) from mike;
 count  
--------
 524288
(1 row)

postgres=# exit
bash-4.2$ exit
exit
muhaos-mbp:postgres-operator-helm mike1$ k exec -it dbcluster-65b5494ddd-7tmkb -c pgbadger -n $NS bash
[postgres@dbcluster-65b5494ddd-7tmkb /]$ cd /report
[postgres@dbcluster-65b5494ddd-7tmkb report]$ ls
[postgres@dbcluster-65b5494ddd-7tmkb report]$ ls -l
total 0
[postgres@dbcluster-65b5494ddd-7tmkb report]$

**Comment by ValClarkson** [comment]
@muhaook can you try port-forwarding pgbadger and then hitting the ui 

kubectl port-forward dbcluster-65b5494ddd-7tmkb -n $NS 10000:10000

http://localhost:10000/api/badgergenerate

I ran a new cluster, I added data, then hit the ui and the index.html showed up in the reports folder

**Comment by muhaook** [comment]
I saw the report this way. Thanks Val.
