### ISSUE TITLE
can't create a postgres user with pgo create user

### ISSUE THREAD

**Issue by mirinus** [CrunchyData/postgres-operator#857]
I failed to create a user for postgres.  How can I set the password for user "postgres" ?

$ pgo create user test2 --selector=name=mycluster --password test --valid-days 180 -n pgouser1 --debug
DEBU[0000] debug flag is set to true
DEBU[0000] in initConfig with url=https://51.77.178.87:8443
DEBU[0000] GetCredentials called
DEBU[0000] looking in /home/ubuntu/.pgouser for credentials
DEBU[0000] /home/ubuntu/.pgouser found
DEBU[0000] pgouser file found at /home/ubuntu/.pgouser contains username:password:pgoadmin:
readonlyuser:password:pgoreader:

DEBU[0000] [username password pgoadmin
readonlyuser password pgoreader ]
DEBU[0000] username=[username] password=[password]
DEBU[0000] setting up httpclient with TLS
DEBU[0000] create user called
DEBU[0000] createUsers called...[https://51.77.178.87:8443/users]
DEBU[0000] &{200 OK 200 HTTP/1.1 1 1 map[Content-Type:[application/json] Www-Authenticate:[Basic realm="Restricted"] Date:[Fri, 05 Jul 2019 02:21:59 GMT] Content-Length:[95]] 0xc0002b0080 95 [] false false map[] 0xc000171900 0xc0000f4840}
DEBU[0000] http status code is 200
Error: pq: password authentication failed for user "postgres"

**Comment by cahoonpwork** [comment]
It looks like you have a cluster `mycluster`, can you verify if  `pgo test mycluster` works?  Also, what version are you running?

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Comment by jmccormick2001** [comment]
also, try your .pgouser file with username:password as the contents
