### ISSUE TITLE
It's not possible to update user data

### ISSUE THREAD

**Issue by marrataj** [CrunchyData/postgres-operator#858]
**Describe the bug**
While trying to use `pgo user ...` command it fails with `Error: no clusters found`.

[Here](https://github.com/CrunchyData/postgres-operator/blob/master/apiserver/userservice/userimpl.go#L88) it always adds `,pg-cluster` to selector which causes that cluster is never found.

**To Reproduce**
1. Try to call `pgo user <username> --selector=name=mycluster --db <db_name> --namespace <namespace>`
2. See error: `Error: no clusters found`

**Expected behavior**
After giving proper selector as in example `--selector=name=mycluster` it should successfully update user.

**LOG**
level=debug msg="selector string=[name=mycluster,pg-cluster]"

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider): GCP
* Storage being used (NFS, Hostpath, Gluster, etc): standard
* Container Image Tag: centos7-4.0.1
* PostgreSQL Version: 10
* Platform (Docker, Kubernetes, OpenShift): Kubernetes

**Comment by jmccormick2001** [comment]
should be ready for test in 4.1.0.
