### ISSUE TITLE
having trouble using --resources-config on a create cluster

### ISSUE THREAD

**Issue by hightekvagabond** [CrunchyData/postgres-operator#861]
** Which example are you working with? **
there is no example for container resources in:
https://crunchydata.github.io/postgres-operator/latest/configuration/pgo-yaml-configuration/

like there is for storageos, but I was able to look at some other posts in forums and the pgo.yaml docs and think I've pulled one together

**What is the current behavior?**
```
pgoadmin@/home/pgoadmin> pgo create cluster  --autofail --metrics --password "xxxxxx" --pgbackrest-storage-type local --pgbadger --pgbouncer --pgbouncer-pass "xxxxxx"  --pgpool --replica-count 1  --resources-config secrets/dbpasswords/accessmanagement.resources accessmanagement
Error: secrets/dbpasswords/accessmanagement.resources ContainerResource config was not found 
pgoadmin@/home/pgoadmin> cat secrets/dbpasswords/accessmanagement.resources
ContainerResources:
    RequestsMemory:  512Mi
    RequestsCPU:  0.1
    LimitsMemory:  512Mi
    LimitsCPU:  0.1
pgoadmin@/home/pgoadmin> 
```

**What is the expected behavior?**
I expect it to set the Memory and CPU requests and limits

My first guess is that I have formatted this file wrong but not sure how, was hoping someone could point me to a better example

* Operating System: Linux
* Where is this running : aws

* Platform (Docker, Kubernetes, OpenShift): K8
* Platform Version: pgo client version 4.0.0
pgo-apiserver version 4.0.0

**Comment by jmccormick2001** [comment]
https://github.com/CrunchyData/postgres-operator/blob/master/conf/postgres-operator/pgo.yaml#L89

the default pgo.yaml defines 'small' and 'large' resource configs, you would specify those on the command line using --resources-config=small

**Comment by hightekvagabond** [comment]
Yeah, I had small and large at first, this was just another attempt to get it right, here it is with small and large from that exact example. 

`pgoadmin@/home/pgoadmin> pgo create cluster  --autofail --metrics --password "xxxx" --pgbackrest-storage-type local --pgbadger --pgbouncer --pgbouncer-pass "xxxx"  --pgpool --replica-count 1  --resources-config secrets/dbpasswords/accessmanagement.resources accessmanagement
Error: secrets/dbpasswords/accessmanagement.resources ContainerResource config was not found 
pgoadmin@/home/pgoadmin> cat secrets/dbpasswords/accessmanagement.resources
ContainerResources:
  small:
    RequestsMemory:  512Mi
    RequestsCPU:  0.1
    LimitsMemory:  512Mi
    LimitsCPU:  0.1
  large:
    RequestsMemory:  2Gi
    RequestsCPU:  2.0
    LimitsMemory:  2Gi
    LimitsCPU:  4.0
pgoadmin@/home/pgoadmin> `

**Comment by hightekvagabond** [comment]
oh, I missread your reply at first..... ok, so how would I tell my "create cluster" to use this pgo.yaml then so that I could do --resources-config=small ?

**Comment by jmccormick2001** [comment]
if you do a 'pgo show config' it will show you your currently deployed pgo.yaml configuration, it should have 'small' and 'large' defined already unless that was changed by the installer to some other names/values.  We specify 'small' and 'large' by default, but people tend to change those as they do various installs for their environment.

**Comment by hightekvagabond** [comment]
ok, that is cool, and I get how there is already a deployed pgo.yaml, and I'm able to create a cluster now defining small vs large, but, now my issue because that I need to explicitly be able to define CPU and Memory for a cluster at the time of create and being limited to just those two doesn't help

**Comment by jmccormick2001** [comment]
we are adding dynamic configuration in 4.1 of this operator, that could be added to the list of features if its helpful to folks.

**Comment by hightekvagabond** [comment]
thanks

**Comment by hightekvagabond** [comment]
even something like "Overriding Storage Configuration Defaults" as defined at the bottom of this page: https://crunchydata.github.io/postgres-operator/latest/configuration/pgo-yaml-configuration/

but for ContainerResources would be perfect
