### ISSUE TITLE
pgo create cluster storage options for backup and backrest

### ISSUE THREAD

**Issue by dadez** [CrunchyData/postgres-operator#869]
**It would be nice to can override the default `backup_storage` and `backrest_storage` as by `primary_storage` and `replica_storage`**

**add options on pgo create-cluster**
We can define the primary and replica storage configurations with this parameters:

- `--storage-config`
- `--replica-storage-config`

We should alos can define the desired storage configurations for backup and backrest:

- `--backup-storage-config`
- `--backrest-storage-config`

**Please tell us about your environment:**
Running test on a vm in vmware workstation
* Operating System: `ubuntu 18.04`
* Where is this running ( Local, Cloud Provider): `Local`
* Storage being used (NFS, Hostpath, Gluster, etc): `hostpath`
* Container Image Tag: `centos7-11.4-2.4.1`
* PostgreSQL Version: 
* Platform (Docker, Kubernetes, OpenShift): `microk8s`
* Platform Version: `1.15.0`

**Comment by cahoonpwork** [comment]
we are making some changes to make things more dynamic, I'll look into getting this is part of that.

**Comment by ajoyej** [comment]
Hello,
What is your concept when creating different clusters with different storage sizes?
At the moment, it seems we have to set within inventory file backup_storage/backrest_storage settings to the highest value we have among all clusters.
This sounds a bit strange, if 1 cluster has a requirement of 1 GB and another one of 1 TB.

How do you handle this case?
If our understanding is correct, do you have any plan to make this configurable in version 4.1?

Thanks,
José

**Comment by dadez** [comment]
any news here ?

**Comment by jkatz** [comment]
`--pgbackrest-storage-type` is added in v4.2.0

Physical backups were standardized around pgBackRest in `v4.2.0`

**Comment by ajoyej** [comment]
Hello,
According to the documentation: 
`--pgbackrest-storage-type string    The type of storage to use with pgBackRest. Either "local", "s3" or both, comma separated. (default "local")`

This is used to specify if it is local or/and s3.

What we will need here is to specify for a given cluster the size of the local backup pvc allocated.
If I'm correct, it is with 4.2, not possible to specify different backup pvc size for different cluster (with local backup storage type).

By the way, thank a lot for the great work!

José

**Comment by andrewlecuyer** [comment]
@ajoyej that is correct.  As you are seeing,  when creating a cluster using the `pgo` CLI it is not currently possible to specify a unique storage configuration for the PVC created for use the `pgBackRest` repository (e.g. as you can for the primary and replicas).  As a result, the `BackrestStorage` configuration defined in the `pgo.yaml` config file would currently need to be updated in order to change the specific storage configuration utilized by the `pgBackRest` repo in a new cluster.

**Comment by jkatz** [comment]
That said, we can look into adding support for a flag similar to `--replica-storage-config` (e.g. `pgbackrest-storage-config`) to be applied to each cluster as a one-off. As the API elements are there, this could theoretically go into the next update to 4.2. We will look into it.
