### ISSUE TITLE
CR to enable TLS on DB cluster

### ISSUE THREAD

**Issue by muhaook** [CrunchyData/postgres-operator#878]
**What is the motivation or use case for the feature? **
operator uses configmap to determine certificates and configurations to setup postgres cluster. This would not work for us. Operator should always contact CR and act up on it.

**Describe the solution you'd like**
The CR should include all necessary data that the original configMap has:
"pg_ident.conf"
"pg_hba.conf"
"postgresql.conf"
"ca.crl"
"ca.crt"
"server.crt"
"server.key"

Once the operator detects the CR, it uses data in the CR to configure TLS in postgres cluster.

**Comment by jkatz** [comment]
Work has been done in this for the `v4.2.0` release, though the non-TLS configuration bits are stored as part of the DCS that was set up for the HA system.
