### ISSUE TITLE
Spread Postgres Operator across multi-zone env

### ISSUE THREAD

**Issue by SergeyMuha** [CrunchyData/postgres-operator#890]
** Which example are you working with? **
I have vsphere with two availability zone (zone1, zone2) that don't share any resources
Kubernetes cluster deployed with two nodes, one node per zone
I have deployed Postgres Operator in zone1 and posgres cluster with --autofail --replica-count=1
so I have master pod in zone1 and replica in zone2
I tested failover
**What is the current behavior?**
Idea is that when simulated zone1 failure by  shuttingdown worker vm on zone1 I also lest without postgres operator and no failover can accrue 
**What is the expected behavior?**
Do you have options to deploy postgres operator across two or three zones

**Comment by jmccormick2001** [comment]
thanks, its on the roadmap to support a active-standby or some sort of clustered operator configuration which would be what you need for your use case.
