### ISSUE TITLE
Compatibility with Openshift 1.4 ? 

### ISSUE THREAD

**Issue by dhananjaysathe** [CrunchyData/postgres-operator#9]
Would this work with openshift 1.4 based on k8s 1.4.x ? is there something 1.5 specific you folks rely on ?

**Comment by jmccormick2001** [comment]
the ThirdPartyResource kubernetes type is required for the postgres-operator which I believe was introduced with Kube 1.5.

**Comment by dhananjaysathe** [comment]
I recall there was basic implementations of this in the later 1.3.x , they were alpha in 1.4x and 1.5x albeit with some changes. I could try this and revert unless they are using some 3rd party resource features that were specifically added post 1.4 .

**Comment by jmccormick2001** [comment]
I definitely would love to have this run on Openshift, its on my list of TODOs for sure, I'm just unsure of which version of Openshift they introduced TPRs and which version will work with the go-client v2.0

**Comment by jmccormick2001** [comment]
this uses ThirdPartyResources which is not available in Openshift 1.4, closing for now...I do have plans to support Openshift 3.5 (based on Kube 1.5).
