### ISSUE TITLE
Configure Crunchy operator to use namespace level RBAC rules

### ISSUE THREAD

**Issue by NiharDudam** [CrunchyData/postgres-operator#905]
**What is the motivation or use case for the change?**

Our clients require that we ship with the most restrictive RBAC rules possible. Since our product does not deploy across namespaces, we need to ship RBAC rules that do not request any cluster-level permissions.

**Describe the solution you'd like**
We need a way to configure crunchy operator (disable any cross namespace features) so that it  can run with namespace scoped Roles and RoleBindings

**Comment by leigh-j** [comment]
This is also a requirement at my site, all rolebindings should be at namespace rather than cluster level.

This is required for running multiple operators in a multi-tenant deployment.

**Comment by jkatz** [comment]
@leigh-j With Operator 4.1, everything can be done within a namespaced scope. You can disable using the dynamic namespaces, or set a "read-only" ClusterRole permission if you want to have the Operator see the permissions it needs across namespaces: https://github.com/CrunchyData/postgres-operator/blob/master/deploy/cluster-roles-readonly.yaml

**Comment by juanramb** [comment]
@jkatz Hi, Is there any documentation about installing the operator on a restricted namespace? I can only see documentation about using readonly, and the readonly clusterroles you mentioned, but the kubectl installer config file installers/kubectl/postgres-operator.yml contains rw clusterroles.
It'd be fine if the documentation explains what the kuberentes cluster admins must do beforehand, and what the namespace users must do to install the operator on their namespaces.

**Comment by jkatz** [comment]
- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/installation/postgres-operator/](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/postgres-operator/)
