### ISSUE TITLE
Support for Redhat UBI images 

### ISSUE THREAD

**Issue by NiharDudam** [CrunchyData/postgres-operator#906]
**What is the motivation or use case for the change?**
Our product has a requirement of using Redhat certified UBI images 

**Describe the solution you'd like**
At present all the images supported by Crunchy are based on centos7 as per 
https://hub.docker.com/u/crunchydata

I also see UBI docker files at https://github.com/CrunchyData/postgres-operator/tree/4.0.1/ubi7
and https://github.com/CrunchyData/crunchy-containers/tree/2.4.1/ubi7

The solution is to push UBI images to official crunchy docker repo if they are ready

**Comment by cahoonpwork** [comment]
Currently the UBI images are a work in progress, but the plan is to transition to them.

**Comment by jkatz** [comment]
This is ongoing work. The UBI images will be pushed to the public repository when they are ready.

**Comment by NiharDudam** [comment]
@jkatz do we have any timeline for this ?

**Comment by jkatz** [comment]
Hi @NiharDudam,

The UBI images are available in the Crunchy Data Customer Portal.

Thanks!
