### ISSUE TITLE
imagepath should have prefix 'crunchydata/' in Pgcluster CR 

### ISSUE THREAD

**Issue by muhaook** [CrunchyData/postgres-operator#913]
the operator seems to be adding a crunchydata/ image prefix automatically when creating the Pods from the Pgcluster CR. e.g. repository: crunchy-postgres

What we need is to define the imagepath with the crunchydata/ image prefix in pgcluster CR. this way, we can also use it to pull image in our installer code. 
e.g. repository: crunchydata/crunchy-postgres

**Comment by jmccormick2001** [comment]
thanks for reporting this one, we'll add the image prefix into the CR.

**Comment by NiharDudam** [comment]
@jmccormick2001 

In our use case, we upload all the images to a private repository and will not have access to the internet. 
Hence the operator should be able to read the **image name**, **tag**, and **secret** associated with it from the CR and download the images.
