### ISSUE TITLE
backuprest full backup pod has error 050

### ISSUE THREAD

**Issue by narayaana** [CrunchyData/postgres-operator#914]
**Describe the bug**

C:\Users\Ugo\pgo>pgo_4_0_0 version
pgo client version 4.0.0
pgo-apiserver version 4.0.0

There are 2 pgo clusters running on the same AKS.

kubectl logs of backup pod "" is:
time="2019-08-06T01:00:07Z" level=info msg="stderr=[ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-backup.lock': Resource temporarily unavailable\n       HINT: is another pgBackRest process running?\n]"
time="2019-08-06T01:00:07Z" level=error msg="command terminated with exit code 50"

**To Reproduce**
1. comes after a while, on both clusters.

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/52987462/62587281-b719dd00-b8f3-11e9-9679-843d677df316.png)

**Please tell us about your environment:**

* Operating System: AKS
* Storage being used (NFS, Hostpath, Gluster, etc): 
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version: 4.0.0

**Comment by lkhomenk** [comment]
@narayaana check your backrest-shared-repo pod. it seems that another backup is running. maybe some other pgbackrest processes are stuck. restarting backrest-shared-repo pod might help. anyway this issue is more related to pgbackrest. add logging to the file on pgbackrest side to catch exactly your case

**Comment by narayaana** [comment]
error really on occurs when I have more than one cluster on our namespace.
if I delete one cluster, the error disappears

**Comment by jkatz** [comment]
The pgBackRest support has been enhanced for [v4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0). I would recommend upgrading and trying to see if you can reproduce the issue there. This has been verified to work with multiple clusters running within the same namespace, as each cluster will have its own pgBackRest repository.
