### ISSUE TITLE
Manual Failover deletes working primary

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#916]
** Which example are you working with? **
Manual failover kills Primary even if Primary is OK

**What is the current behavior?**
pgo failover mycluster --target mycluster-replica
deletes primary
**What is the expected behavior?**
pgo just to switch to the replica.
Verify that Primary is fine and leave it as replica
**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Container Image Tag: 2.3.2
* PostgreSQL Version: 10
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 3.5.2

**Comment by lkhomenk** [comment]
another weirdo with manual failover - 2 replicas were created 
Failover started from 1 Primary + 2 Replicas  - operator killed primary, switched to --target pod and create 2 more replicas. end result 1 Primary + 3 Replicas
@jmccormick2001 is it expected behavior?

**Comment by jmccormick2001** [comment]
its a bug I'm working on currently, I should have a fix for it in develop branch shortly.

**Comment by jkatz** [comment]
Closing due to changes in how all of this works in [v4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0)
