### ISSUE TITLE
Collect container Resource limits

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#936]
**Describe the bug**
Collect container can grow to much. we have seen collect container consuming up to 5Gb.

**To Reproduce**
1. Heavy database or load tests on DB + collecting metrics

**Expected behavior**
It should have limits

**Comment by cahoonpwork** [comment]
Agree, we plan on adding a DefaultCollectResources config.

**Comment by jkatz** [comment]
Per #1391, we're actually taking the opposite approach :smile:

Based on some research involving Kubernetes and the OOM Killer, we're opting to not use Limits for a variety of reasons. The collect container is a bit interesting as it is effectively a stateless service, so it getting axed by the OOM killer is "OK", if not ideal, but we want to be sure we don't cause any harm to the PostgreSQL container.

Perhaps we allow for configuration of Limits on the stateless services we deploy?

**Comment by jkatz** [comment]
This is closed by #1802
