### ISSUE TITLE
pgo create user fails with certain usernames and long passwords

### ISSUE THREAD

**Issue by GeorgFleig** [CrunchyData/postgres-operator#941]
**Describe the bug**
The pgo CLI does not work when creating a pg user that contains a "-" in its name. For example: `pgo -n postgres create user test-admin --selector=name=pg1 --managed --password test --valid-days 99 --db test`.
It will return 

> `Error: pq: syntax error at or near "-"`.

Creating the same user directly within postgres works perfectly fine when having quotes around the username.

Furthermore the CLI does not allow passwords with more than 16 characters. It will return

> `Error: valid passwords are less than 16 chars`

which does not make sense to me. The limit is hardcoded in the CLI. The users of my initial deployment have longer passwords. It is also possible to have longer passwords when creating the user directly withing postgres.

The reason why I want to use the CLI and the password management is the automatic update of the pgpool secrets which comes in handy.

**Expected behavior**
I expect the same limitations of usernames and passwords then in pg itself. No additional limits.

**Please tell us about your environment:**

* Operating System: Ubuntu
* Where is this running ( Local, Cloud Provider): OpenStack
* Storage being used (NFS, Hostpath, Gluster, etc): Ceph
* Container Image Tag: crunchydata/crunchy-pgpool:centos7-11.4-2.4.1
* PostgreSQL Version: runchydata/crunchy-postgres:centos7-11.4-2.4.1
* Platform (Docker, Kubernetes, OpenShift): k8s
* Platform Version: 1.15.2

**Comment by jkatz** [comment]
I believe all of these issues have been resolved. I have not been able to reproduce it in [v4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0). I believe these were fixed in v4.1.0.
