### ISSUE TITLE
Data Loss and Latency limits during failover

### ISSUE THREAD

**Issue by louiseohalloran** [CrunchyData/postgres-operator#946]
Hi @jmccormick2001 

Regarding failover from primary to replica in Crunchy Data -  we want to understand what the behaviour is around data loss and latency.

Can you give us some detail on 

- Is data lost during the failover from master to replica. Will any transactions that are writing data to the postgres db during failover be queued and executed later once failover has completed?
- How long does failover to a replica take. 
- Are the replicas always up to date with the master or can a replica be behind the master and in this case what happens during failover.

- Regarding latency - how much is tolerated during failover. Is there a limit

In addition to this what is the recommended way - using the operator to deploy a High Availability Postgres Cluster across multiple nodes and regions to remove a single point of failure

Is it possible to have the operator manage multiple clusters across regions - where all clusters are replications of each other - if so how can these clusters be kept in sync with each other.

**Comment by jkatz** [comment]
Some resources on this:

- https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0
- https://crunchydata.github.io/postgres-operator/latest/architecture/provisioning/
- https://crunchydata.github.io/postgres-operator/latest/architecture/disaster-recovery/
- https://crunchydata.github.io/postgres-operator/latest/architecture/high-availability/
