### ISSUE TITLE
scheduler and pgdump

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#949]
** Which example are you working with? **
It's unclear why pgdump can't be added via `pgo create schedule`

**What is the current behavior?**

```
pgo create schedule --schedule="*/15 * * * *" --schedule-type=pgdump my-cluster
pgdump is not a valid schedule type
```

**What is the expected behavior?**
Can it be added?

**Comment by cahoonpwork** [comment]
Currently the only valid items that can be scheduled are pgbackrest, pgbasebackup and a policy.  We will look into what it would take to add pgdump.
