### ISSUE TITLE
replica-node-label option

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#975]
**What is the motivation or use case for the feature? **
There're not so many options to customize master and it's replicas placement
During `pgo create` one can use `--node-label` which works  - master will use that label(operator=In), and replicas use any other node(operator=NotIn)
But when one scales cluster `pgo scale` - option `--node-label` can be used to tell replicas which node to use. Same option should be added to cluster creation.
Same about Pgcluster crd - there's no way to affect replica placement if one creates pgcluster object
**Describe the solution you'd like**
adding `--replica-node-label` to the create would help a lot

**Describe any alternatives you've considered**
Separate affinity for replica/master

**Comment by jkatz** [comment]
While node labels are still supported, Pod placement for a PostgreSQL cluster has significant changes thanks to native support for pod anti-affinity in [4.2.0](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0)
