### ISSUE TITLE
How to specify the retention policy?

### ISSUE THREAD

**Issue by jippeholwerda** [CrunchyData/postgres-operator#982]
What is currently the way to specify the retention policy for pgbackrest?

I've tried: 

```
pgo backup my_cluster -n my_namespace  \                                                                                        
        --backup-type=pgbackrest \
        --backup-opts="--type=full --repo1-retention-full=3"
```

But this gives: `Error: unknown flag: --repo1-retention-full`

I see this issue: https://github.com/CrunchyData/postgres-operator/issues/351 but apparently that has not been implemented yet?

So that basically leaves the option of specifying the retention policy via `pgbackrest.conf`. Is that the recommended approach? How would you configure this?

**Comment by andrewlecuyer** [comment]
@jippeholwerda as you saw, setting ` --repo1-retention-full` via the `backup-opts` when taking a backup is not currently supported.  However, we are looking into supporting additional backup options, inlcuding the ability to set retention options (e.g. as discussed in #351).

In the meantime, it is possible to set the retention policy by setting the `PGBACKREST_RETENTION_FULL` environment variable in the pgBackRest repo deployment that is created with a new cluster.  For instance, you could edit the pgBackRest repo deployment for your cluster using `kubectl edit`, e.g.:

`kubectl edit deployment mycluster-backrest-shared-repo`

...and you can then add add the desired pgBackRest restention env vars to the spec, e.g.:

```bash
spec:
  containers:
  - env:
    - name: PGBACKREST_RETENTION_FULL
      value: "3"
```

Or if you have retention policies that you would like to apply globally to all clusters created by the PGO, you could also set the appropriate env vars in the `pgo-backrest-repo-template.json` file prior to deploying the PGO (found in `$PGOROOT/conf/postgres-operator` for a bash install, or `$PGOROOT/ansible/roles/pgo-operator/files/pgo-configs` for an Ansible install).

**Comment by jippeholwerda** [comment]
Excellent, thanks for the clarification!
