### ISSUE TITLE
chrunchydata image contain vulnerabilities

### ISSUE THREAD

**Issue by boers001** [CrunchyData/postgres-operator#991]
Hi,

We are currently implementing the crunchydata postgres-operator. we use harbor as our private docker registry. So we retag the crunchydata images  we use and push the images to our local registry. This registry scans the images agains any known vulnerabilities. We currently use the pgo-* images with version centos7-4.0.1 and we use the crunchydata-** images centos7-10.9-2.4.1 and centos7-11.4-2.4.1. We see that these image have high vulnerabilities in some libraries:
[RHSA-2019:1619](https://access.redhat.com/errata/RHSA-2019:1619)  vim-minimal    
[RHSA-2019:1587](https://access.redhat.com/errata/RHSA-2019:1587)  python

I would expect the crunchydata images that would be available in docker registry are also scanned and do not contain any high vulnerabilities. Do you have any idea when these images are patched so that these image at least  do not contain any high vulnerabilities.

Kind regards,

René

**Comment by jkatz** [comment]
Hi @boers001,

Each time we make a release, containers are re-scanned through vulnerability checkers and must pass before we push to any registry. For the case of the 4.1.0 and 4.1.1 releases, they both went through this process and passed.

Thanks,

Jonathan

**Comment by boers001** [comment]
H Jonathan,

We are currently using the 4.0.1 images. These images still contain high
vulnerabilities. Are you also fixing these images so that do not contain
those high vulnerabilities.

Kind regards,

Rene Boers

Op wo 4 dec. 2019 om 20:14 schreef Jonathan S. Katz <
notifications@github.com>:
