### ISSUE TITLE
Question: Comparison with zalando postgres-operator

### ISSUE THREAD

**Issue by jamessewell** [CrunchyData/postgres-operator#992]
Hi, I was hoping to get some sort of comparison between the two postgres operators.

I can see that you have more complimentary features (backup, pooling etc..) - but I'm mainly interested in HA. How does this compare to a Spilo/Patroni based system?

**Comment by moshloop** [comment]
This operator currently uses the readiness of the master postgres pod to trigger failover, Patroni/Spilo uses leader election via etcd/consul/zookeeper see -> https://github.com/compose/governor/blob/master/postgres-ha.pdf and https://speakerdeck.com/alexeyklyukin/postgresql-high-availability-on-kubernetes-with-patroni

**Comment by jkatz** [comment]
This has now changed with the release of [`v4.2.0`](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0) of the Operator. For more information on how HA works, please see:

https://crunchydata.github.io/postgres-operator/latest/architecture/high-availability/

**Comment by craigbox** [comment]
Given the adoption of Patroni, it now seems that this operator, erm, operates, the same way as the Zalando operator.  How should one choose between the two?  Is there potential to consolidate them?

**Comment by MohamedMSaeed** [comment]
@craigbox Hi,

I'm currently comparing them both. What did you choose and where did you find the best comparison?

Thanks in advance

**Comment by craigbox** [comment]
Hi @MohamedMSaeed; I never used either sorry, I just reported on it for the [Kubernetes Podcast](https://kubernetespodcast.com/)

Perhaps [this recent presentation](https://ossna2020.sched.com/event/c3Sn/running-your-own-postgres-database-as-a-service-on-kubernetes-lukas-fittl-microsoft) may help?

**Comment by MohamedMSaeed** [comment]
@craigbox Thanks.

**Comment by elgalu** [comment]
Without much of a deep-dive I can see a few differences:

1. Zalando's has an [Operator UI](https://postgres-operator.readthedocs.io/en/latest/operator-ui/)
2. CrunchyData's uses a `pgo` client to apply changes, e.g. `pgo create cluster example1 -n pgouser1` while Zalando's focus on everything infrastructure as code (SCM + K8s CRDs)
3. Both are validated on plain K8s however Zalando's is also validated on AWS EC2 while CrunchyData's on OpenShift, GKE/Anthos, VMware PKS. None of them seem to be testing Amazon EKS
4. Zalando doesn't provide enterprise/paid support while CrunchyData seems to be making this for a living.

**Comment by jkatz** [comment]
A couple of addenda:

- [Custom Resource](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/) workflows are supported, and all new functionality being added is done "CRD first". Some of the workflows are "hidden", i.e. you have to create a pgtask to do things, e.g. take backups.

- We do have people running the PostgreSQL Operator in EKS, though we are presently not running our regression tests in that environment. However, that may change :wink:

**Comment by EvertonSA** [comment]
> Hi @MohamedMSaeed; I never used either sorry, I just reported on it for the [Kubernetes Podcast](https://kubernetespodcast.com/).
> 
> Perhaps [this recent presentation](https://ossna2020.sched.com/event/c3Sn/running-your-own-postgres-database-as-a-service-on-kubernetes-lukas-fittl-microsoft) from Lukas Fittl may help?

your podcast is awesome
