### ISSUE TITLE
4.0.1 duplicated labels issue

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#994]
**Describe the bug**
Deployment creation fails from time to time due to duplicated "name" label
"labels": {
                    "name": "aws-cluster-pugw",
                    "vendor": "crunchydata",
                    "app": "aws-cluster",
                    "component": "postgresql",
                    "pgbouncer-password": "mEZOJajcSi","pgbouncer-secret": "","pgo-version": "4.0.1",
                    "name": "aws-cluster-replica","deployment-name": "aws-cluster-pugw","crunchy_collect": "true","NodeLabelValue": "db","backrest-storage-type": "s3","custom-config": "aws-cluster-pgo-custom-config","pgbouncer-user": "pgbouncer","replica-name": "aws-cluster-pugw","pg-cluster": "aws-cluster",
                }
            },

**To Reproduce**
1. Create cluster with 2 replicas 
2. Repeat till only 1 replica deployment will be created

**Screenshots**

**Please tell us about your environment:**

* Container Image Tag: centos7-10.9-2.4.1
* PostgreSQL Version: 10.9
* Platform (Docker, Kubernetes, OpenShift): OCP
* Platform Version: 4.0.1

**Additional context**
"name": "aws-cluster-pugw" - this label shouldn't be there

**Comment by lkhomenk** [comment]
Found scenario to 50% reproduction.
Creation of the cluster with `--node-label` and the label key containing `/`. This adds either `, ` or duplicates some labels inside metadata.labels or template.labels. https://play.golang.org/p/lNceR2KQjNb
All this breaks deployment template json

**Comment by cahoonpwork** [comment]
This appears to be an issue with how PGO parses the node selector label, and then adds the key and value as NodeLabelKey and NodeLabelValue labels on the deployment for the new PG cluster. If the key for the node label specified when creating the cluster contains slash (i.e. a prefix) (kubernetes.io/hostname), and a slash is not an accepted value for a key per the Kubernetes documentation for labels, the cluster will not be properly created, as you are seeing.  Therefore, with the current PGO labels with slashes (e.g. a prefix) cannot be used.

Are you seeing this behavior when using node labels that don't have a slash/prefix?  If so, can you tell us what the actual `pgo create` command is that you are using, maybe something else is going on too?

Thanks for all your help with the project and taking the time to provide the playground example. We would welcome the opportunity to send you a token of our appreciation. If you are interested, please contact us at info@crunchydata.com and we can connect directly.

**Comment by lkhomenk** [comment]
@cahoonpwork exactly it's more like kubernetes doesn't allow prefixed keys. But it's weird that sometimes it still works, sometimes it adds `, ` or duplicates labels. We have also tried relabeling nodes and it seems it's fine

**Comment by lkhomenk** [comment]
I assume this can be closed, but it would be great to have this documented somewhere @cahoonpwork
